add frame-ancestor to CSP to allow iframe embedding via app
owncloud/core pull request #24845
Opened 2016-05-25 14:27 UTC by butonic

cc @LukasRaeschke

2016-05-25 20:00 UTC, butonic commented
Not enough because the csp is hardcoded in https://github.com/owncloud/core/blob/master/lib/private/legacy/response.php#L246

but its a start...

2016-05-30 10:20 UTC, PVince81 commented
@BernhardPosselt @ChristophWurst

2016-05-30 10:23 UTC, ChristophWurst commented on lib/private/Security/CSP/ContentSecurityPolicy.php
> +	public function setAllowedFrameAncestorDomains($allowedFrameAncestorDomains) {
``array`` typehint?

2016-05-30 10:29 UTC, ChristophWurst commented
Changes look good. Any easy way to test this?

2016-05-31 09:58 UTC, butonic commented
I tested by adding a subdomain to my hosts file, serving oc also to that subdomain, then putting a frame.html with an iframe to the subdomain in it and finally opening the frame.html from my tld.

2016-06-23 08:16 UTC, PVince81 commented
I don't know what to do with this.

This adds new APIs and we're already past feature freeze for 9.1, so this would be more something for 9.2.
Also need someone who understands CSP to review the rule string.

2016-08-18 09:05 UTC, felixboehm commented
External Sites App is broken without this, right? Then this is a bug fix we should deliver ...

2016-08-18 09:14 UTC, PVince81 commented
Not sure, or does the external sites app is able to use wildcards instead and this is only for other apps ?

@butonic can you clarify ?

If this is a regression in external sites then we should get this new API in and fix external sites to use it.

2016-08-19 12:21 UTC, butonic commented
I was confused. External sites app is not affected.

2016-10-05 14:01 UTC, PVince81 commented
CSP tests are failing

2016-11-21 11:12 UTC, DeepDiver1975 requested changes

2017-04-07 14:55 UTC, PVince81 commented
9.2->10.0 ?

2017-07-05 06:40 UTC, Peter-Prochaska commented
Reviewed, code looks good. But can we get rid of this "unsafe-XXX" stuff?

2017-07-24 19:18 UTC, DeepDiver1975 approved these changes

2017-08-03 09:26 UTC, PVince81 commented
@butonic please adjust according to @Peter-Prochaska's comment, if possible.

2017-08-03 09:26 UTC, PVince81 commented
moving to "planned" for the next release

2017-08-07 18:55 UTC, butonic commented
@Peter-Prochaska @PVince81 Please create a separate PR to remove the unsafe-XXX CSP. I assume it neds to be part of the default csp for the text editor or whatever. Very much unrelated to this PR.

2018-04-20 13:53 UTC, butonic commented
- [ ] add other csps

2018-06-01 10:28 UTC, PVince81 commented
https://github.com/owncloud/core/pull/24845#issuecomment-383103125

assuming unfinished then ?

moving to backlog

2019-02-08 14:22 UTC, PVince81 commented
closing as there doesn't seem to be any strong requirement for this.

feel free to reopen if needed

2019-02-08 14:22 UTC, closed without merging

2019-02-08 14:22 UTC, PVince81 commented
also note: the new UI of OC will be [Phoenix](https://github.com/owncloud/phoenix) in which case the CSP will need to be defined there or on the web server on which it is deployed