stop php from sending any Cache control headers
owncloud/core pull request #26592
Opened 2016-11-09 22:43 UTC by butonic

## Description

On debian the default setting for session.cache_limiter is nocache causing Pragma, CacheControl and Expiry headers to be added to every response. This may lead to conflicting headers where owncloud sets a Cache-Control header that allows caching but Pragma is still nocache. Pragma is only needed to tell IE8 how to cache responses. No longer needed -> kill it.

This PR changes the default setting of session.cache_limiter to '' to prevent php from sending any caching related headers to get give oc full control and prevent conflicting headers.

see http://php.net/manual/de/function.session-cache-limiter.php#refsect1-function.session-cache-limiter-parameters

## Related Issue

* https://github.com/owncloud/core/pull/26589/files#diff-17d17c6a954f29c12717db921f235531L137
* https://github.com/owncloud/core/issues/21036

## Motivation and Context

cleaner caching, no unnecessary headers, profit?

## How Has This Been Tested?

Firefox, Edge, Chromium

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-11-10 14:19 UTC, PVince81 commented
Can anyone familiar with .htaccess and php settings review this ? @DeepDiver1975 @PhilippSchaffrath @felixheidecke

2016-11-10 15:30 UTC, felixheidecke commented
Sorry … no xp in caching :-/

2016-11-22 11:32 UTC, phisch requested changes

2016-11-22 11:32 UTC, PhilippSchaffrath commented on .htaccess
> +  php_value output_buffering 0s
Documentation says this is either a bool or an integer. Am i missing something @butonic?
http://php.net/manual/de/outcontrol.configuration.php#ini.output-buffering

2016-11-22 11:32 UTC, PhilippSchaffrath commented on .htaccess
> +  php_value session.cache_limiter ''
This should be either `public`, `private_no_expire`, `private` or `nocache`.
http://php.net/manual/de/function.session-cache-limiter.php

2016-11-22 11:32 UTC, PhilippSchaffrath commented on .htaccess
> +  php_value session.cache_limiter ''
Same here.

2016-11-22 11:32 UTC, PhilippSchaffrath commented on .user.ini
> +session.cache_limiter=''
Same here.

2016-11-22 11:57 UTC, DeepDiver1975 commented on .htaccess
> +  php_value session.cache_limiter ''
'' is valid 
````
Setting the cache limiter to '' will turn off automatic sending of cache headers entirely.

2016-11-22 12:04 UTC, PhilippSchaffrath commented on .htaccess
> +  php_value session.cache_limiter ''
Oh right.

2016-11-22 12:54 UTC, butonic commented on .htaccess
> +  php_value output_buffering 0s
meat fingers ...

2016-11-22 12:56 UTC, phisch approved these changes

2016-11-22 12:56 UTC, PhilippSchaffrath commented
:+1:

2016-11-22 13:08 UTC, DeepDiver1975 commented
- [ ] needs squash on merge

2016-11-25 13:57 UTC, PhilippSchaffrath commented
@DeepDiver1975 jenkins build successful, but did not report here, can you re-run the build?

2017-01-13 10:31 UTC, butonic commented
cc @VicDeo regarding IE11

2017-01-13 10:33 UTC, butonic commented
https://github.com/owncloud/core/issues/26922 has a workaround for IE caching Ajax requests without this caching

2017-01-13 14:25 UTC, VicDeo commented
well... this introduces a huge variety of IE-related issues and solves none of them at the same time.
So the only workaround would be to revert this in production :/

`mod_headers` is not always available and apache is not the only web-server. 

I'd say before taking a control on cache one should know what to do with that control.

2017-02-03 10:50 UTC, PVince81 commented
Seeing the comments from @VicDeo and the fact that you ticked "Breaking change (fix or feature that would cause existing functionality to change)" doesn't inspire trust in this PR. Also I don't have enough experience with caching headers and quirks.

@butonic is this something you'd like to continue to pursue or should we move to backlog or close this PR ?

2017-02-21 08:25 UTC, PVince81 commented
can we close ?

2017-05-19 08:39 UTC, PVince81 commented
closing due to lack of feedback

2017-05-19 08:39 UTC, closed without merging