Ensure adding resource only once
owncloud/core pull request #26661
Opened 2016-11-19 03:41 UTC by mjobst-necls

## Description
Modified php function appendIfExist -> appendOnceIfExist by only adding resources that have not already been added.

## Related Issue
#26660
Introduced by #26462

## Motivation and Context
Resources are only linked once in html file.

## How Has This Been Tested?
phpunit test
browser test

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-11-19 03:56 UTC, mjobst-necls commented on lib/private/Template/CSSResourceLocator.php
> +		$this->appendOnceIfExist($app_path, $style.'.css', $app_url);
I'm not sure if this is correct. Should non existing files be added?

2016-11-19 03:56 UTC, mjobst-necls commented on lib/private/Template/JSResourceLocator.php
> +		$this->appendOnceIfExist($app_path, $script . '.js', $app_url);
Same here

2016-11-19 03:56 UTC, mjobst-necls commented on lib/private/Template/ResourceLocator.php
> +		if (!$this->contains($root, $file) && is_file($root.'/'.$file)) {
First, check if file is already in the list and then check if file is existing, because file is_file needs io and the contains function is executed in memory only.

The (most) registered files should exist, either.

2016-11-19 03:56 UTC, mjobst-necls commented on lib/private/Template/ResourceLocator.php
> +			if ($resource[0] . '/' . $resource[2] == $root . '/'. $file) {
The check does not consider $webRoot because a file path is built by $root and $file.
Is that correct?

2016-11-19 03:56 UTC, mjobst-necls commented on tests/lib/Template/ResourceLocatorTest.php
> +		$this->assertEquals([$resource1], $locator->getResources());
Maybe we could add another test resource with a different filename. I just don't know how to ensure that the additional file is existing.

2016-11-21 07:50 UTC, PVince81 commented
@mjobst-necls thanks. @PhilippSchaffrath can you review ?

2016-11-21 09:31 UTC, DeepDiver1975 commented on lib/private/Template/ResourceLocator.php
> +		foreach ($this->resources as $resource) {
instead of looping over the array we better use a proper index on the array to ensure uniqueness.

e.g. like this:

```php
	protected function append($root, $file, $webRoot = null, $throw = true) {
		if (!$webRoot) {
			$webRoot = $this->mapping[$root];
		}
$key = "$root#$webroot#$root";
if (isset($this->resources[$key])) {
    return;
}
		$this->resources[$key] = [$root, $webRoot, $file];
		if ($throw && !is_file($root . '/' . $file)) {
			throw new ResourceNotFoundException($file, $webRoot);
		}
	}

2016-11-21 19:10 UTC, mjobst-necls commented on lib/private/Template/ResourceLocator.php
> +		foreach ($this->resources as $resource) {
I guess you mean something like "$root#$webroot#$file" ?
Well, I found out that this is not so easy because sometimes we have entries like:
- $root: /test
- $file: abc/def/ghi.css

and

- $root: /test/abc
- $file: def/ghi.css

When we would like to use a key in the array we should at least concatenate $root and $file

2016-11-21 19:26 UTC, mjobst-necls commented on lib/private/Template/ResourceLocator.php
> +		foreach ($this->resources as $resource) {
Ok, found out that

- if $webroot = null then $root = /dev/dev/workspaces/oc and $file=apps/file_version/css/versions.css
- elif $webroot = /apps/files_versions then $root = /opt/dev/workspaces/oc/apps/files_versions and $file = css/versions.css

Concatenating $root and $file should lead to an appropriate key, then.

2016-11-21 23:27 UTC, mjobst-necls commented on lib/private/Template/JSResourceLocator.php
>  		// missing translations files fill be ignored
The if block can be omitted, because append is called in every case.

The need for adding not existing resources should be discussed.

2016-11-21 23:32 UTC, mjobst-necls commented on lib/private/Template/JSResourceLocator.php
>  		// missing translations files fill be ignored
The if block can be omitted, because append is called in every case.
The need for adding not existing resources should be discussed.

2016-11-21 23:34 UTC, mjobst-necls commented
Is there a need to add non existing resources? Or shall we rather add a log entry to inform the admin?

2016-11-22 11:19 UTC, PhilippSchaffrath commented on lib/private/Template/ResourceLocator.php
> +		} else {
No need for `else` here, just end the condition and return false below it.

2016-11-22 11:19 UTC, PhilippSchaffrath commented on tests/lib/Template/ResourceLocatorTest.php
> +		$method = new \ReflectionMethod($locator, 'appendOnceIfExist');
Why is this method protected in the first place? @DeepDiver1975

2016-11-22 11:55 UTC, DeepDiver1975 requested changes

2016-11-22 11:56 UTC, DeepDiver1975 commented on tests/lib/Template/ResourceLocatorTest.php
> +		$method = new \ReflectionMethod($locator, 'appendOnceIfExist');
as stated in here https://github.com/owncloud/core/pull/26661#discussion_r89060829 - just kill this method

2016-11-22 18:01 UTC, mjobst-necls commented on tests/lib/Template/ResourceLocatorTest.php
> +		$jsResource = fopen(self::$jsResourcePath, 'w');
Hmm... Don't know whether it is a good idea to create files temporarily. What do you think about adding a permanent js file in a sub folder?

2016-11-23 17:56 UTC, mjobst-necls commented
@DeepDiver1975 Please review again and check https://github.com/owncloud/core/pull/26661#discussion_r89174404

2016-11-25 10:46 UTC, PhilippSchaffrath commented on tests/lib/Template/ResourceLocatorTest.php
> +		$jsResource = fopen(self::$jsResourcePath, 'w');
You might want to use vfsStream in that case. Example: https://github.com/owncloud/core/blob/master/tests/lib/Theme/ThemeServiceTest.php

2016-11-29 10:41 UTC, mjobst-necls commented
Review again, please.

2016-12-06 11:59 UTC, PVince81 commented
@DeepDiver1975 @PhilippSchaffrath please re-review, thanks

2016-12-06 23:25 UTC, DeepDiver1975 approved these changes

2016-12-06 23:30 UTC, DeepDiver1975 commented
:+1:

2016-12-06 23:30 UTC, merged