[WIP] OAuth 2.0 for WebDAV
owncloud/core pull request #26742
Opened 2016-11-29 20:59 UTC by joneug

## Description

The DAV app's authentication mechanism for securing the WebDAV interface was extended to either use the existing Basic Authentication or Bearer Authentication with OAuth 2.0 depending on the Authorization Header. These changes depend on the OAuth 2.0 implementation provided by the [OAuth 2.0 App](https://github.com/pssl16/owncloud-app_oauth2). When considering a merge the app has to be added.

All of this is still WIP and should enrich the discussion about implementing OAuth 2.0 in ownCloud. Unfortunately the related issue #10400 is locked and limited to collaborators.

## Related Issue

#10400

## Motivation and Context

When trying to use files in ownCloud within 3rd-party applications authorization using OAuth 2.0 has many advantages. The biggest concern in such a scenario perhaps is that when using the existing Basic Authentication the user's password has to be stored. Implementing OAuth 2.0 would resolve such issues.

## How Has This Been Tested?

Tested with PHP 7 and API testing tool. PHPUnit tests still have to be added.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-11-29 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=26742) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=26742) before we can accept your contribution.<br/><hr/>**Jonathan Neugebauer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2016-11-29 23:30 UTC, DeepDiver1975 commented
@PhilippSchaffrath @Peter-Prochaska

2016-12-21 15:00 UTC, guruz commented
Linking https://github.com/owncloud/core/issues/24995

2017-01-24 13:43 UTC, joneug commented
@PhilippSchaffrath @DeepDiver1975 @butonic Please review the changes. Looking forward to your ideas.

2017-01-24 17:23 UTC, joneug commented
I think the problem with the build failing in Jenkins is that the OAuth 2.0 app was added as a [Submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) which requires additional commands for cloning. Would you like to use submodules or should I include the OAuth 2.0 app's files directly?

2017-01-30 22:45 UTC, DeepDiver1975 commented
> I think the problem with the build failing in Jenkins is that the OAuth 2.0 app was added as a Submodule which requires additional commands for cloning. Would you like to use submodules or should I include the OAuth 2.0 app's files directly?

Linking the app via submodule is not what we really want.

What about moving your app into the owncloud organisation and also move the sabre dav related code from this PR into the app as well?

2017-01-30 22:48 UTC, DeepDiver1975 requested changes

2017-01-30 22:48 UTC, DeepDiver1975 commented on apps/dav/appinfo/v1/webdav.php
> +if (strpos(explode(' ', \OC::$server->getRequest()->getHeader('Authorization'))[0], 'Bearer') !== false) {
We need some registration/factory mechanism to instantiate the correct auth backend - I'm happy to help out here.

2017-01-30 22:48 UTC, DeepDiver1975 commented on apps/dav/appinfo/v1/webdav.php
> +	$authBackend = new \OCA\DAV\Connector\Sabre\OAuth2();
You should really inject all dependencies in the ctor

2017-01-31 18:21 UTC, joneug commented
> Linking the app via submodule is not what we really want.

I removed the submodule.

> What about moving your app into the owncloud organisation and also move the sabre dav related code from this PR into the app as well?

I moved the code related to sabre/dav into the app. What are your thoughts on the `dav` app being dependent on the `oauth2` app when trying to support both authentication backends? Are you planning to include the `oauth2` app in the core?

2017-01-31 18:23 UTC, joneug commented on apps/dav/appinfo/v1/webdav.php
> +if (strpos(explode(' ', \OC::$server->getRequest()->getHeader('Authorization'))[0], 'Bearer') !== false) {
Looking forward to your ideas.

2017-02-01 22:03 UTC, DeepDiver1975 commented
> Are you planning to include the oauth2 app in the core?

that could be one options ....



> What are your thoughts on the dav app being dependent on the oauth2 app when trying to support both authentication backends?

We have to avoid such a dependency - what you can try is to use the event handler
https://github.com/owncloud/core/blob/master/apps/dav/lib/Server.php#L85-L87

To get an idea on how to use this: https://github.com/owncloud/core/blob/master/apps/federation/lib/AppInfo/Application.php#L124-L135


What is not yet covered in this approach is to allow bearer tokens to aallow access to the OCS api.
We can address this in a second stage

2017-02-02 09:02 UTC, joneug commented
> We have to avoid such a dependency - what you can try is to use the event handler

I will look into that. Thanks!

> What about moving your app into the owncloud organisation

I tried to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) but I don't have the rights to add a repository in ownCloud. Could you please provide a repository?

2017-02-02 09:17 UTC, DeepDiver1975 commented
> I tried to transfer the repository but I don't have the rights to add a repository in ownCloud. Could you please provide a repository?

Please transfer the repo to my - I can move it to the owncloud organization

2017-02-02 09:18 UTC, joneug commented
> What is not yet covered in this approach is to allow bearer tokens to aallow access to the OCS api.
We can address this in a second stage

I added some commits regarding this.

2017-02-02 09:21 UTC, joneug commented
> Please transfer the repo to my - I can move it to the owncloud organization

Done.

2017-02-02 09:50 UTC, joneug commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'preLogin', [$userId, '']);
Where to get the password for the preLogin hook?

2017-02-02 09:51 UTC, joneug commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'postLogin', [$userId, '']);
Where to get the password for the postLogin hook?

2017-02-02 11:19 UTC, DeepDiver1975 commented
> Done.

@joneug I did not receive anything yet - mind checking again? THX

2017-02-02 11:23 UTC, phisch commented
@joneug we are planning on relying on the oauth implementation, so we should include everything in core instead of an app. (for example the clients will only use oauth in the future)

Have you checked out existing oauth server libraries?
One that looks quite well developed is this one: https://github.com/thephpleague/oauth2-server

Although we will not be able to use it to it's full potential, since we can't support middleware right now. But it should provide enough to get a solid implementation right now, and clean up easily once we decide to switch to middleware compatible psr-7 request/responses.

If you need any help, or have any questions, just ping me, i will do my best to help you getting this done!

2017-02-02 11:24 UTC, joneug commented
> @joneug I did not receive anything yet - mind checking again? THX

This is odd. I aborted the existing request and opened a new one. Hopefully now it works...

2017-02-02 11:27 UTC, DeepDiver1975 commented
> This is odd. I aborted the existing request and opened a new one. Hopefully now it works...

here we go - https://github.com/owncloud/oauth2

2017-02-02 11:29 UTC, DeepDiver1975 commented
> we are planning on relying on the oauth implementation, so we should include everything in core instead of an app. (for example the clients will only use oauth in the future)

We need to change pieces within core to make it work this is quite true - but generally speaking building this as an app is quite valid - also an app in its own repo.

2017-02-02 11:35 UTC, phisch commented
Even if it is an app that is always enabled, i just don't see the benefit from putting it into an app. Getting this to work with all different request entry points could be quite hook-heavy if it is implemented in an app. Doing this in core directly should make the implementation simpler.

2017-02-02 11:38 UTC, DeepDiver1975 commented
> Doing this in core directly should make the implementation simpler.

for sure not - e.g. the whole dav implementation is living in an app of it's own - https://github.com/owncloud/core/tree/master/apps/dav

2017-02-02 11:39 UTC, joneug commented
@DeepDiver1975 Could you please add Travis and codecov integration for the new repo?

2017-02-05 12:17 UTC, joneug commented
> We have to avoid such a dependency - what you can try is to use the event handler

I tried to add the event listener in the constructor of the app's `Application.php` like this:

```php
$dispatcher = $this->getContainer()->getServer()->getEventDispatcher();
		$dispatcher->addListener('OCA\DAV\Connector\Sabre::authInit', function($event) use($container) {
			if ($event instanceof SabrePluginEvent) {
				$authPlugin = $event->getServer()->getPlugin('auth');
				if ($authPlugin instanceof Plugin) {
					$authPlugin->addBackend(new OAuth2());
				}
			}
		});
```

Unfortunately I did not have luck authenticating after that. I am assuming that `/remote.php/dav/` is the right endpoint since only `appinfo/v2/remote.php` is using `\OCA\DAV\Server`.

2017-02-08 16:08 UTC, DeepDiver1975 commented
> Unfortunately I did not have luck authenticating after that. I am assuming that /remote.php/dav/ is the right endpoint since only appinfo/v2/remote.php is using \OCA\DAV\Server.

yes - this is only for remote.php/dav - a similar mechanism has to be added to remote.php/webdav.
Any also for the OCS API controllers - maybe we need a different approach here.

Let me think about this ....

2017-02-08 19:26 UTC, DeepDiver1975 requested changes

2017-02-08 19:26 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +	private function loginWithOAuth2($bearerToken) {
Ah - nice - you already did add this in here! Great!

2017-02-08 19:26 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +		$app = new App('oauth2');
This is what we don't want to have - core depending on an app is a no go.

We need some plugin mechanism to this ... something like

```php
namespace \OCP\Authentication;

/**
 * @returns null | IUser
 */
interface IAuthModule {
    public function auth(IRequest $request);
}
```

And classes implementing this interface can be loaded via info.xml - basically just like the TwoFactor plugins

2017-02-08 19:26 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +		$app = new App('oauth2');
And within the UserSession instead if calling tryTokenLogin, tryBearerLogin, trySessionLogin ....

We just loop over all registered modules

2017-02-09 08:02 UTC, joneug commented on lib/private/User/Session.php
> +		$app = new App('oauth2');
Ok. I will try that as soon as I have time.

2017-02-14 15:58 UTC, joneug commented
> Unfortunately I did not have luck authenticating after that.

Now it works to authenticate using the `/remote.php/dav/` endpoint. So now the `dav` app does not depend on the `oauth2` app anymore.

It did not work at first because I did not add the `<authentication/>` type in `info.xml`.

2017-02-14 19:41 UTC, joneug commented
The dependencies between the core and the `oauth2` app are now fully eliminated.

> We need some plugin mechanism to this

I added `IAuthModule` as suggested.

> And classes implementing this interface can be loaded via info.xml - basically just like the TwoFactor plugins

I updated the `oauth2` app according to this. The `AuthModule` class is registered in `info.xml` under `auth-modules`.

> And within the UserSession instead if calling tryTokenLogin, tryBearerLogin, trySessionLogin ....
> We just loop over all registered modules

I added the function `tryAuthModuleLogin` that implements this loop. I don't see a way of replacing `tryTokenLogin` with this loop as tokens are not implemented with an app. What do you think?

2017-02-14 22:03 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'postLogin', [$userId, '']);
On creation of the oauth token you could store the password - this is what is done in the token based authentication as implemented in core since 9.1

Not really nice to store the password - but we need the password in many areas ....

2017-02-15 18:37 UTC, joneug commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'postLogin', [$userId, '']);
But in the `oauth2` app, where the Access Tokens are being generated, we are not handling passwords at all. This is all done by the API's security mechanism...

2017-02-15 18:42 UTC, joneug commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'postLogin', [$userId, '']);
Besides that an AuthModule only provides the User. So inside the `loginUser` function, where the hooks should be triggered, we still don't have the password.

What do you think?

2017-02-28 16:52 UTC, joneug commented on lib/private/User/Session.php
> +		//$this->manager->emit('\OC\User', 'postLogin', [$userId, '']);
@DeepDiver1975 If storing the password is the only way, we would need to pass the password to the app after the user logged in for the client's Authorization Request (in `LoginController`'s `tryLogin` function). But besides introducing another dependency, to me it does not seem to be a good idea to pass passwords to apps.

Any ideas?

2017-03-02 16:32 UTC, joneug commented
I changed the title of the PR, because now OAuth 2.0 is fully capsulated in the app and this PR addresses the more general problem of adding 3rd-party authentication backends.

Furthermore I added the function `getUserPassword` to the `IAuthModule` interface in order to be able to trigger the hooks. Where to get the password from should not concern this PR.

As a side note: in the [OAuth 2.0 app](https://github.com/owncloud/oauth2) an empty string is returned because we are not handling any passwords at all. Consequently, only master key encryption is working, but this restriction exists when using Shibboleth, too.

2017-03-02 16:37 UTC, joneug commented
Could you please review the changes?

Additionally considering a backport to `stable9.1` would be nice since the changes are relatively small and there is high interest form our side in using OAuth 2.0 in ownCloud 9.1.

2017-03-06 14:45 UTC, DeepDiver1975 requested changes

2017-03-06 14:45 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +		$appManager = OC::$server->query('AppManager');
please inject appManager as parameter in the ctor

2017-03-06 14:45 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +						$authModule = OC::$server->query($class);
adding a type check?

```php
if ($authModule instanceof IAuthModule) {

2017-03-07 09:58 UTC, joneug commented on lib/private/User/Session.php
> +						$authModule = OC::$server->query($class);
Done

2017-03-07 10:40 UTC, joneug commented on lib/private/User/Session.php
> +		$appManager = OC::$server->query('AppManager');
I tried to inject the AppManager, but when changing the registration of `UserSession` in `Server.php` (see [here](https://github.com/pssl16/core/commit/cb6e56b9bc535e91466790f30549bd4de4e76ab7)) I get the following error:

```
PHP Fatal error:  Maximum function nesting level of '256' reached
```

Inside the closure for the `registerService` function, `$appManager = $c->getAppManager();` is called over and over again. Any ideas?

2017-03-08 19:56 UTC, joneug commented on lib/private/User/Session.php
> +		$appManager = OC::$server->query('AppManager');
No ideas?

2017-03-08 21:08 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +		$appManager = OC::$server->query('AppManager');
okay then let's keep it this way

2017-03-08 23:33 UTC, DeepDiver1975 commented
hmmm ... two tests are failing on oracle ....

````
23:15:18 There were 2 failures:
23:15:18 
23:15:18 1) Test\Files\External\Service\GlobalStoragesServiceTest::testUpdateStorage with data set #1 (array('mountpoint', 'identifier:\Test\Files\Extern...ackend', 'identifier:\Auth\Mechanism', array('value1', 'value2', 'testPassword'), array('user1', 'user2'), array(), 15))
23:15:18 Failed asserting that two arrays are equal.
23:15:18 --- Expected
23:15:18 +++ Actual
23:15:18 @@ @@
23:15:18  Array (
23:15:18 -    0 => 'user1'
23:15:18 -    1 => 'user2'
23:15:18 +    0 => 'user2'
23:15:18 +    1 => 'user1'
23:15:18  )
23:15:18 
23:15:18 /var/lib/jenkins/workspace/owncloud-core_core_PR-26742-JCGXUYPGPX2CBJQVJBQBPP3QLMW2OPW6JKKJVSVR77ZQ5M6LTFKQ/tests/lib/Files/External/Service/GlobalStoragesServiceTest.php:185
23:15:18 
23:15:18 2) Test\Files\External\Service\GlobalStoragesServiceTest::testUpdateStorage with data set #3 (array('mountpoint', 'identifier:\Test\Files\Extern...ackend', 'identifier:\Auth\Mechanism', array('value1', 'value2', 'testPassword'), array('user1', 'user2'), array('group1', 'group2'), 15))
23:15:18 Failed asserting that two arrays are equal.
23:15:18 --- Expected
23:15:18 +++ Actual
23:15:18 @@ @@
23:15:18  Array (
23:15:18 -    0 => 'user1'
23:15:18 -    1 => 'user2'
23:15:18 +    0 => 'user2'
23:15:18 +    1 => 'user1'
23:15:18  )
23:15:18

2017-03-09 06:34 UTC, joneug commented
I pulled the changes in `master` branch and now the Jenkins build was successful. But the travis build failed:

```
$ sh -c "if [ '$TEST_DAV' = '1' ]; then bash apps/dav/tests/travis/$TC/install.sh; fi"
bash: apps/dav/tests/travis/selenium/install.sh: No such file or directory

The command "sh -c "if [ '$TEST_DAV' = '1' ]; then bash apps/dav/tests/travis/$TC/install.sh; fi"" failed and exited with 127 during .
```

Are there errors in the build script (see changes of commit [cac897b](https://github.com/owncloud/core/commit/cac897be7f1bbc4b63d684e70a4caa80ada8b608))?

2017-03-09 08:01 UTC, DeepDiver1975 approved these changes

2017-03-09 08:02 UTC, DeepDiver1975 commented
> I pulled the changes in master branch and now the Jenkins build was successful. But the travis build failed:

I'd say this is unrelated ..... let's merge

2017-03-09 08:03 UTC, merged

2017-03-09 08:03 UTC, DeepDiver1975 commented
Thanks a lot! @joneug and your team! Great job!

2017-03-09 08:09 UTC, joneug commented
What do you think about backporting to 9.1?

> Additionally, considering a backport to stable9.1 would be nice since the changes are relatively small and there is high interest form our side in using this mechanism for implementing OAuth 2.0 in ownCloud 9.1.

2017-03-09 08:10 UTC, DeepDiver1975 commented
> What do you think about backporting to 9.1?

@PVince81 what's your opionion? THX

2017-03-13 08:46 UTC, joneug commented
I created a backport in PR #27370.