Let apps register Sabre plugins or collections
owncloud/core pull request #26761
Opened 2016-12-02 21:31 UTC by PVince81

## Description
See https://github.com/owncloud/core/issues/26195#issuecomment-249140878 for info.xml format.
This checks the `sabre` tags in info.xml for all apps and automatically registers the Sabre plugins and collections to the root collection.
Note that this only happens for v2 remote.php.

## Related Issue
Fixes https://github.com/owncloud/core/issues/26195

## Motivation and Context
Since we want Webdav to be used for APIs, apps need a way to register Sabre plugins and also to hook their collections to the remote.php/dav collection tree.

## How Has This Been Tested?
Manually tested with the customgroups app, not ready yet.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@DeepDiver1975 check this out

2016-12-02 21:46 UTC, PVince81 commented
- [ ] TODO: also register sabre plugins in v1 endpoint

2016-12-02 21:46 UTC, PVince81 commented
- maybe let info.xml specify for which endpoint v1, v2 or both through attributes ?

2016-12-02 21:54 UTC, PVince81 commented
- [ ] TODO: attr to tell whether the plugin needs to be registered also for public webdav ? (mostly for file properties)

2016-12-02 21:56 UTC, PVince81 commented
To demo and test this feature, I tried moving the DAV plugins for the comments into the "comments" app in 64b66d78c2ae00e717a280ed4d4b8bd2ba5b4ff2

So far only the root collection seems to work. Might need further tweaking.

2016-12-02 22:02 UTC, PVince81 commented
- [ ] BUG: looks like IUserSession isn't initialized/populated yet when a plugin's `initialize()` is called, so makes it difficult to check the current user or check if user is authed (happens in CommentsPlugin):

2016-12-02 22:11 UTC, PVince81 commented
Solved the auth issue by moving the registration of app sabre plugins into `beforeMethod` handler: https://github.com/owncloud/core/pull/26761/commits/010d4a4ad56013b62a437aa5fc554c446c3c8a9e

2016-12-04 11:16 UTC, DeepDiver1975 commented on apps/dav/lib/AppInfo/Application.php
> +		\OC_App::loadApps();
load all apps? in the past we only did load apps of type filesystem to ensure some performance on the dav backend.
new app type? e.g. dav?

2016-12-04 11:16 UTC, DeepDiver1975 commented on apps/dav/lib/AppInfo/Application.php
> +			$info = \OC_App::getAppInfo($app);
here: https://github.com/owncloud/core/pull/26588/files#diff-0513a8452fe3af4380e1bb03e0ef6aee

2016-12-04 11:16 UTC, DeepDiver1975 commented on apps/dav/lib/AppInfo/Application.php
> +				if (class_exists($command)) {
$command? unknown

2016-12-04 11:16 UTC, DeepDiver1975 commented on apps/dav/lib/AppInfo/Application.php
> +				if (class_exists($command)) {
$command

2016-12-04 11:17 UTC, DeepDiver1975 commented
> TODO: also register sabre plugins in v1 endpoint

v1 only holds files - and it's just the old interface - no need to anything new there

2016-12-05 08:33 UTC, PVince81 commented on apps/dav/lib/AppInfo/Application.php
> +				if (class_exists($command)) {
uh oh... I copied your command code and forgot to replace

2016-12-05 08:36 UTC, PVince81 commented
@DeepDiver1975 ok then we can't port the "comments" app to be a "dav" app with Sabre plugins, because then the comments plugin would be missing in the v1 endpoint.

The other alternative is to change the web UI to use webdav v2: https://github.com/owncloud/core/pull/25494. But then if there's any client who used to expected the oc:comments-unread property on the old endpoint they'd stop working. (but the likeliness of the existence of such clients is very low)

2016-12-05 09:05 UTC, DeepDiver1975 commented
> @DeepDiver1975 ok then we can't port the "comments" app to be a "dav" app with Sabre plugins, because then the comments plugin would be missing in the v1 endpoint.

comments arn't even part of v1 as of today - right? So no need to add it

2016-12-05 09:06 UTC, PVince81 commented
> comments arn't even part of v1 as of today

Only one piece is: we have a Webdav property on files that is added through the `CommentsPlugin`. The property is there to tell how many unread comments there are to be able to display an indicator in the UI.
Without this property we'd need to do extra API calls + JS-side joins to be able to add this info to the file list.

2016-12-05 09:07 UTC, DeepDiver1975 commented
> Only one piece is: we have a Webdav property on files that is added through the CommentsPlugin. The property is there to tell how many unread comments there are to be able to display an indicator in the UI.
> Without this property we'd need to do extra API calls + JS-side joins to be able to add this info to the file list.

I see - lets hardcode this piece and we are fine

2016-12-05 09:09 UTC, PVince81 commented
Hardcode, hmmm... There are multiple levels where we can do this:
1) Keep `CommentsPlugin` within the "dav" app
or
2) Move the oc:comments-unread property logic to the `FilesPlugin`. But then it would conflict with the `CommentsPlugin` one when the "comments" app is enabled.

So I guess 1) is the best approach for now.

2016-12-05 12:31 UTC, PVince81 commented
Rebased onto master to be able to use one of the new IAppManager calls.

Remaining tasks:
- [ ] write unit tests
- [ ] move `CommentsPlugin` back to apps/dav for backward compatibility
- [ ] clear out public webdav case (could be done separately as we currently seldom register plugins for that one, but will need it eventually once we do federated metadata, etc)

2016-12-05 18:08 UTC, PVince81 commented
I refactored the whole thing to simplify it.
Wrote a unit test for the plugin manager.

Please review @DeepDiver1975 @jvillafanez @VicDeo @PhilippSchaffrath 

First have a look at https://github.com/owncloud/core/pull/26761/commits/07d43a539477c8c767090fbc10e9f94220b4b87a which brings the Sabre plugins registration code.
Then see how it's used in https://github.com/owncloud/core/pull/26761/commits/ace036b9241b851b2066205b9e60e3287e98ffe5 where the comments app is changed to use it.

2016-12-06 21:05 UTC, DeepDiver1975 requested changes

2016-12-06 21:05 UTC, DeepDiver1975 approved these changes

2016-12-06 22:42 UTC, DeepDiver1975 commented
:+1:

2016-12-06 23:19 UTC, merged