Handle reading non-existing characters for any depth
owncloud/core pull request #26849
Opened 2016-12-20 16:55 UTC by VicDeo

## Description
Handle reading non-existing characters for any bit depth while creating an image from bmp

## Related Issue
Fixes https://github.com/owncloud/core/issues/26758

## Motivation and Context
Solves flooding the log file with
```
PHP Warning:  unpack(): Type n: not enough input, need 2, have 1 
```
1 entry per each missing pixel

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-20 16:57 UTC, VicDeo commented
It's better to view changes this way:
https://github.com/owncloud/core/pull/26849/files?w=1

2016-12-21 14:03 UTC, PVince81 commented
Please add unit tests

2016-12-21 16:41 UTC, VicDeo commented
@PVince81 for a private method? :)

2016-12-21 16:43 UTC, PVince81 commented
Yes, you even increased the complexity of that method.
You can use `TestCase::invokePrivate`.

Or if that's not acceptable, then write an integration test with matching image files... I guess it's much easier to write unit tests here.

2016-12-21 16:45 UTC, VicDeo commented
@PVince81  this method a hell lot of things and can be extracted into a separate class.
In the past life it was a function:
```
 	/**
 	 * Create a new image from file or URL
 	 *
 	 * @link http://www.programmierer-forum.de/function-imagecreatefrombmp-laeuft-mit-allen-bitraten-t143137.htm
 	 * @version 1.00
 	 * @param string $fileName <p>
 	 * Path to the BMP image.
 	 * </p>
 	 * @return bool|resource an image resource identifier on success, <b>FALSE</b> on errors.
 	 */
 	private function imagecreatefrombmp($fileName) {
```

2016-12-21 16:49 UTC, PVince81 commented
It's a good opportunity to add missing tests.

If you feel like the method does too much then split it into smaller functions and add tests for those.

Most important point is that we don't add tests where they are missing we'll likely have more regressions in the future. I've seen enough cases of missing/neglected/incomplete unit tests that lead to criticial regressions.

2016-12-21 19:47 UTC, butonic commented
Blame it on me. Thx for digging into it & trying to understand what it does. 🙇

2016-12-21 19:49 UTC, VicDeo commented
@butonic np, I'm refactoring this method into class now. :)

2017-01-11 18:26 UTC, PVince81 commented
Code looks fine. @Temtaime can you help testing ?

2017-01-11 19:18 UTC, Temtaime commented
I'll look into this.

2017-01-17 16:34 UTC, DeepDiver1975 requested changes

2017-01-17 16:34 UTC, DeepDiver1975 commented on lib/private/Image/BmpToResource.php
> +			$dibHeader['imagesize'] = $this->fixImageSize($header);
$header is undefined

2017-01-17 16:34 UTC, DeepDiver1975 commented on tests/lib/Image/BmpToResourceTest.php
> +	const CLASS_NAME = 'OC\Image\BmpToResource';
BmpToResource::class

2017-01-17 17:31 UTC, VicDeo commented
@DeepDiver1975 thanks for reviewing. Updated.

2017-01-17 17:55 UTC, DeepDiver1975 approved these changes

2017-01-17 17:55 UTC, DeepDiver1975 commented
Code coverage is at 75% - can we get some more? THX

2017-01-17 20:14 UTC, VicDeo commented
@DeepDiver1975 ok, let it be 88%

2017-01-18 10:27 UTC, merged