print error message when no password in occ
owncloud/core pull request #26929
Opened 2017-01-12 12:49 UTC by PhilippSchaffrath

## Description

This is a clean copy of #26481 sine i don't know how to fix a branch that messed up a rebase :stuck_out_tongue: .

Added a do-while loop to check if the password string length is larger than 0 when called by occ.

## Related Issue
#25206
## Motivation and Context

When you entered a password with a length of 0 in occ you could set a password with a length of 0. This is not desirable and also doesn't work in the ui. The behaviour should be consistent
## How Has This Been Tested?

## Screenshots (if appropriate):
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-01-12 12:55 UTC, PhilippSchaffrath commented
Seems like a few tests are not yet developed, will do that quickly.

2017-01-24 14:12 UTC, DeepDiver1975 requested changes

2017-01-24 17:40 UTC, PhilippSchaffrath commented on tests/Core/Command/User/ResetPasswordTest.php
> +		$userManagerMock = $this->getMockBuilder('OCP\IUserManager')
Using MockBuilder because i really often need to customize the mock before the builder creates it. Have gotten used to always use it. I can change it here though.

2017-04-26 09:55 UTC, PVince81 commented
needs rebase

2017-07-04 13:13 UTC, PVince81 commented
composer.lock conflict ??

@phisch please fix and rebase

2017-07-12 11:51 UTC, phisch commented
The conflict is because of the symfony console update which is necessary to properly test the console commands. This works perfectly fine in a real terminal, but has problems when being run in a fake one (like phpstorm terminal or testrunner, or jenkins).

Since this doesn't play well with Jenkins, i am kind of out of ideas here. Maybe one of you guys @PVince81 @DeepDiver1975 can test and have some ideas on how to get this to work properly? <- it's about the 2 tests at the bottom that use `getCommandTester`

If not, i'll have to remove the tests or try to re-write them with a million mocks.

2017-07-12 12:40 UTC, DeepDiver1975 requested changes
the lock file has conflicts - this needs fixing - thx

2017-07-12 12:40 UTC, DeepDiver1975 commented on tests/Core/Command/User/ResetPasswordTest.php
> +		$userManagerMock = $this->createMock('OCP\IUserManager');
IUserManager::class

2018-01-11 10:41 UTC, closed without merging