Emit postSetEnabled for user
owncloud/core pull request #26984
Opened 2017-01-19 19:46 UTC by VicDeo

## Description
Implements user enabled/disabled event

## Related Issue
#23970

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-01-20 17:21 UTC, VicDeo commented
@PVince81 is it good enough?

2017-01-20 17:32 UTC, PVince81 commented
@VicDeo yeah. A unit test would be nice if possible.

2017-01-20 18:48 UTC, VicDeo commented
@PVince81 possible. Added.

2017-01-20 18:53 UTC, PVince81 commented
:+1:

2017-01-23 11:17 UTC, DeepDiver1975 commented
This will not help. The emitter is on the user object. In order to consume the event a listener needs to be attached to each and every user. Pointless.

This is why the whole emitter concept is :hankey: 

Please use the EventDispatcher - THX

2017-01-23 12:19 UTC, VicDeo commented
@DeepDiver1975 
>This will not help.

Untrue. Tested both auto and manually, and works. ;)  


>Please use the EventDispatcher - THX

OK

2017-01-23 12:25 UTC, DeepDiver1975 commented
> Untrue. Tested both auto and manually, and works. ;)

show me the code which will listen to enabling of all users - good luck :wink:

2017-01-23 14:22 UTC, VicDeo commented
@DeepDiver1975 enabling / disabling is NOT a backend method anyway:
```
$this->config->setUserValue($this->uid, 'core', 'enabled', $enabled);
```
It can be done on per user level only. Because backend knows nothing about this operation.

2017-01-23 19:44 UTC, PVince81 commented on lib/private/User/User.php
> +			$this->emitter->emit('\OC\User', 'postSetEnabled', [$this, $enabled]);
replace this with something like:
```php
	$eventDispatcher = \OC::$server->getEventDispatcher();
	$eventDispatcher->dispatch('OC\User::postSetEnabled', $this');
```

then to listen, an app just does this:
```php
$eventDispatcher = \OC::$server->getEventDispatcher();
$eventDispatcher->addListener(
	'OC\User::postSetEnabled',
	function(IUser $user) {
             // ...
        });
```

(the param of the callback might be something else, I don't  remember exactly)

2017-01-23 19:44 UTC, PVince81 commented
> or without EventDispatcher IDK how to do it for all users ATM.

@VicDeo see https://github.com/owncloud/core/pull/26984/files#r97399288

2017-01-23 21:45 UTC, VicDeo commented
@PVince81 Ok, let it be EventDispatcher.

2017-01-23 22:07 UTC, DeepDiver1975 requested changes

2017-01-23 22:07 UTC, DeepDiver1975 commented on tests/lib/User/UserTest.php
> +		$eventDispatcher = \OC::$server->getEventDispatcher();
please don't use the event listener from the container - this can cause side effects.
It should be enough to use a mock and assert on the dispatch function

2017-01-27 11:11 UTC, DeepDiver1975 commented on tests/lib/User/UserTest.php
> +		$eventDispatcher = \OC::$server->getEventDispatcher();
@VicDeo please take care so that we can merge this one - THX

2017-01-27 16:25 UTC, VicDeo commented on tests/lib/User/UserTest.php
> +		$eventDispatcher = \OC::$server->getEventDispatcher();
to do so I need to inject EventDispatcher next to \OC\Hooks\Emitter :sob:

2017-01-30 22:19 UTC, DeepDiver1975 requested changes

2017-01-30 22:19 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +								$urlGenerator = null, EventDispatcher $eventDispatcher = null
is $eventDispatcher ever passed into this ctor?

2017-01-31 15:47 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +								$urlGenerator = null, EventDispatcher $eventDispatcher = null
@VicDeo ^^^

2017-01-31 20:59 UTC, VicDeo commented on lib/private/User/User.php
> +								$urlGenerator = null, EventDispatcher $eventDispatcher = null
@DeepDiver1975  passed now.

2017-02-02 15:53 UTC, PVince81 commented
:+1:

2017-02-02 15:53 UTC, merged