user notification for file uploads > 4GB in IE11
owncloud/core pull request #27004
Opened 2017-01-23 13:26 UTC by hurradieweltgehtunter

## Description
Notify users with IE11 to use desktop client for uploading files bigger than 4GB.

## Related Issue
https://github.com/owncloud/enterprise/issues/1779

## Motivation and Context
IE11 can't handle file uploads bigger than 4GB

## Screenshots (if appropriate):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-01-23 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=27004) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=27004) before we can accept your contribution.<br/>

2017-01-23 13:29 UTC, DeepDiver1975 requested changes

2017-01-23 13:29 UTC, DeepDiver1975 commented on apps/files/js/file-upload.js
> +			    var trident = ua.indexOf('Trident/');
please fix indent - we use tabs

2017-01-23 13:29 UTC, DeepDiver1975 commented on apps/files/l10n/en_GB.js
> +    "Total file size {size1} exceeds your browser upload limit. Please use the owncloud desktop client to upload files bigger than 4GB." : "Total file size {size1} exceeds your browser upload limit.
please remove - translations are handled via tranisfex

2017-01-23 13:29 UTC, DeepDiver1975 commented on apps/files/l10n/en_GB.json
> +    "Total file size {size1} exceeds your browser upload limit. Please use the owncloud desktop client to upload files bigger than 4GB." : "Total file size {size1} exceeds your browser upload limit.
please remove - translations are handled via tranisfex

2017-01-23 13:29 UTC, DeepDiver1975 commented on apps/files/js/file-upload.js
> +									'Total file size {size1} exceeds your browser upload limit. Please use the owncloud desktop client to upload files bigger than 4GB.', {
owncloud has to be passed in as argument due to whitelabling

2017-01-23 13:30 UTC, michaelstingl commented
@hurradieweltgehtunter Plz check if your size calculation matches the one from ownCloud.

2017-01-23 13:31 UTC, DeepDiver1975 commented
- please add unit tests
- generally speaking we implement new features and fixes on master and backport later - please respect this next time - THX
- please click on the CLA button - THX

2017-01-23 13:31 UTC, PVince81 commented on apps/files/js/file-upload.js
> +		      	}
weird indents

2017-01-23 13:31 UTC, PVince81 commented on apps/files/js/file-upload.js
> +					ie = false;
use `var` to declare these variables locally, else they'd be global

2017-01-23 13:31 UTC, PVince81 commented on apps/files/js/file-upload.js
> +			    if (ie && ieversion == 11) {
if we're doing this often, might be worth adding this as utility function to the OC.Util namespace which is currently in core/js/js.js (there is already a `isIE()` function there)

2017-01-23 13:33 UTC, michaelstingl commented
@DeepDiver1975 Fix shouldn't be required for oC 10 (https://github.com/owncloud/core/pull/26306)

2017-01-23 17:43 UTC, PVince81 commented on apps/files/js/file-upload.js
> +						if (window.File && window.FileReader && window.FileList && window.Blob) {
Is this really required or can we assume that IE11 has these ?

2017-01-23 17:44 UTC, PVince81 commented on apps/files/js/file-upload.js
> +										$('#uploadprogressbar').tipsy({gravity:'n', fade:true, live:true});
@hurradieweltgehtunter mind fixing this bad indent as well ?

2017-01-23 17:45 UTC, PVince81 commented
I'll take care of the unit tests, it's a bit complicated.

2017-01-23 18:14 UTC, PVince81 commented on apps/files/js/file-upload.js
> +									'ownCloud' : 'ownCloud',
needs to use product name in case of white labeling

2017-01-23 19:07 UTC, PVince81 commented
Added missing tests and fix theme name thingy

2017-01-24 05:14 UTC, PVince81 commented
@michaelstingl @davitol can you help test this in IE11 and non-IE11 envs with big files ?

2017-01-24 14:17 UTC, DeepDiver1975 commented on apps/files/js/file-upload.js
> +						if (window.File && window.FileReader && window.FileList && window.Blob) {
:white_check_mark: blob - http://caniuse.com/#search=Blob

please look up the rest @hurradieweltgehtunter

2017-01-24 14:26 UTC, DeepDiver1975 commented
@hurradieweltgehtunter any please squash your 4 commits into one - thx

2017-01-24 14:55 UTC, PVince81 commented on apps/files/js/file-upload.js
> +						if (window.File && window.FileReader && window.FileList && window.Blob) {
This is completely unneeded because none of the checks below is using any of these APIs.

I'll remove it.

2017-01-24 14:57 UTC, PVince81 commented
Rebased on squashed.

Please review and test.

2017-01-24 15:42 UTC, davitol commented
:+1: Total file size 3.9 GB exceeds your browser upload limit. Please use the ownCloud desktop client to upload files bigger than 3.9 GB. appears

2017-01-24 20:29 UTC, PVince81 commented
Travis, what's taking you so long ? Even Jenkins was faster...

Anyway, Travis doesn't contain any JS related tests. Merging.

2017-01-24 20:30 UTC, merged