Selenium test for PR 26979
owncloud/core pull request #27057
Opened 2017-01-31 05:57 UTC by individual-it

## Description
This is a slenium test for the PR #26979 that fixes the issue #26975
It depends on PR #27056 (Selenium implementation)

## Related Issue

PR #26979 
issue #26975

## Motivation and Context

See issue  #27055 & PR #27056

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-01-31 08:00 UTC, DeepDiver1975 requested changes

2017-01-31 08:00 UTC, DeepDiver1975 commented on tests/vendor/facebook/webdriver/example.php
> +<?php
please do not add the vendor directory

2017-01-31 08:00 UTC, DeepDiver1975 commented on .travis.yml
> +  - if [ ! -z "$SAUCE_USERNAME" ] && [ ! -z "$SAUCE_ACCESS_KEY" ]; then export TEST_SELENIUM=1 ; else export TEST_SELENIUM=0 ; fi
let's add this as a test case just like we do with caldav, carddav.

2017-01-31 08:27 UTC, individual-it commented on tests/vendor/facebook/webdriver/example.php
> +<?php
so do you want the webdriver be in tests/facebook/webdriver ?

2017-01-31 08:30 UTC, individual-it commented on .travis.yml
> +  - if [ ! -z "$SAUCE_USERNAME" ] && [ ! -z "$SAUCE_ACCESS_KEY" ]; then export TEST_SELENIUM=1 ; else export TEST_SELENIUM=0 ; fi
this is to prevent the tests to run if a PR comes from a remote fork.
So if we make it a test-case by setting TEST_SELENIUM=1 and the sauce_connector is setup in owncloud/core and I make a fork to individual-it/core commit something and make a PR. Travis would try to build that PR but the selenium tests would fail because $SAUCE_USERNAME & $SAUCE_ACCESS_KEY are not set

2017-01-31 08:41 UTC, DeepDiver1975 commented on tests/vendor/facebook/webdriver/example.php
> +<?php
I'd add this as dev dependency into /composer.json

2017-01-31 08:42 UTC, DeepDiver1975 commented on .travis.yml
> +  - if [ ! -z "$SAUCE_USERNAME" ] && [ ! -z "$SAUCE_ACCESS_KEY" ]; then export TEST_SELENIUM=1 ; else export TEST_SELENIUM=0 ; fi
I understand that part - we can still make this work (somehow ;-) )

But on travis I'd like to see an explicit job with TC=selenium listed

2017-01-31 11:17 UTC, individual-it commented
I've made the requested changes. Tests are passing on my travis instance: https://travis-ci.org/individual-it/owncloud-core/builds/196904627
Somehow composer decided to change the time format in composer.lock

2017-01-31 13:16 UTC, DeepDiver1975 commented
> Somehow composer decided to change the time format in composer.lock

this is okay - nothing to worry from my pov

2017-01-31 13:18 UTC, DeepDiver1975 commented
We need to fix the regular phpunit execution as done on jenkins.
The selenium tests are executed as well.
Maybe we move the selenium tests into a different folder.

@PVince81 @SergioBertolinSG integration tests will stay in build/integration? What is the current play?

Otherwise I suggest to restructure the tests folder:
- tests
  - unit (move all unit tests in here)
  - integration tests (move build/integration in here)
  - ui (move all selenium tests are of this pr)

objections?

2017-01-31 13:27 UTC, individual-it commented
The even more basic question is were do you like to have the selenium tests run?
I've set it up on Travis cause it's all public, free of costs and easy to set up, but you also could run it on/through your Jenkins architecture

On January 31, 2017 7:03:59 PM GMT+05:45, "Thomas Müller" <notifications@github.com> wrote:
>We need to fix the regular phpunit execution as done on jenkins.
>The selenium tests are executed as well.
>Maybe we move the selenium tests into a different folder.
>
>@PVince81 @SergioBertolinSG integration tests will stay in
>build/integration? What is the current play?
>
>Otherwise I suggest to restructure the tests folder:
>- tests
>  - unit (move all unit tests in here)
>  - integration tests (move build/integration in here)
>  - ui (move all selenium tests are of this pr)
>
>objections?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/pull/27057#issuecomment-276360547

2017-01-31 13:30 UTC, DeepDiver1975 commented
> The even more basic question is were do you like to have the selenium tests run?

As far as I can tell: travis is fine for me - let's see how this evolves. We can always move these tests to jenkins.

2017-01-31 13:30 UTC, DeepDiver1975 commented
In any case: @individual-it thanks a lot for the effort you put into this! Much appreciated!

2017-01-31 13:38 UTC, SergioBertolinSG commented
I think we should use behat mink for this http://mink.behat.org/en/latest/
and make use of the page object pattern. 

The tests which find the elements using xpath can break easily, that requires an improvement of the frontend to include proper ids to every element.

2017-02-01 10:37 UTC, individual-it commented
I totally agree that relying on xpath might be problematic, depending on how you use it.
is good: `WebDriverBy::xpath(".//table[@id='userlist']")`
is fine: `WebDriverBy::xpath(".//*[@id='app-content']/div[@class='loading']")`
problematic: `WebDriverBy::xpath(".//*table[@class='hascontrols']/tbody/tr[2]/th`

use of page object pattern sounds very good to me. [Selenium-documentation on Page Objects](https://github.com/SeleniumHQ/selenium/wiki/PageObjects) Its basically the question about how much to generalize and reuse the code. And more reuse of code if of course better.
_Within your web app's UI there are areas that your tests interact with. A Page Object simply models these as objects within the test code. This reduces the amount of duplicated code and means that if the UI changes, the fix need only be applied in one place._
If the concept of UI testing with selenium is taken onboard for oC I'm happy to write a couple PageObjects for general use

[You can make mink drive selenium on sauce-labs](https://saucelabs.com/blog/adding-sauce-to-behat).
How do you think it would benefit oC to use behat & mink? Do you think of changing from PHPUnit to Behat? Or is it about using Gherkin as language?
How much chance/need is to go on behavior-driven development (BDD) for oC?

2017-02-01 11:46 UTC, individual-it commented
I've converted my Sauce Labs account into a OSS account and that makes the tests public. If someone is interested in seeing this test+result on sauce labs site here it is: https://saucelabs.com/beta/tests/53361d4a9812466a87027fdb5a4b0109/commands#0

2017-02-06 14:40 UTC, PVince81 commented
> restructure the tests folder

@DeepDiver1975 sounds good

2017-02-07 07:57 UTC, SergioBertolinSG commented
> You can make mink drive selenium on sauce-labs.
> How do you think it would benefit oC to use behat & mink? Do you think of changing from PHPUnit to Behat? Or is it about using Gherkin as language?
> How much chance/need is to go on behavior-driven development (BDD) for oC?

To be consistent with the current integration tests suite which is already using behat. Also easier to create new tests and to understand them.

2017-02-07 08:11 UTC, michaelstingl commented
+1 for behat

2017-02-09 02:48 UTC, individual-it commented
@SergioBertolinSG I just watched your behat presentation on owncloud https://www.youtube.com/watch?v=_Sbgctq1P1U
As far as I understood you are running the behat tests on Jenkins. So if the UI tests were done in behat would you run them also on Jenkins or try to run the UI behat still on travis as @DeepDiver1975 proposed?

2017-02-15 02:37 UTC, individual-it commented
Closing this and will make a new PR with a behat / mink solution

2017-02-15 02:37 UTC, closed without merging