Remove auto-focus on certain input fields
owncloud/core pull request #27105
Opened 2017-02-07 16:37 UTC by felixheidecke

## Description
Remove auto-focus on certain input fields if browser is part of the MSIE family.

## Related Issue
https://github.com/owncloud/core/issues/22689

## Motivation and Context
Focus on input fields immediately removes the placeholder value, thus concealing the input label.

## How Has This Been Tested?
Tested using **MSIE11** and **MS Edge** on Browserstack.com

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-07 16:40 UTC, DeepDiver1975 commented
don't add node_modules - thx

2017-02-07 16:44 UTC, felixheidecke commented
> don't add node_modules - thx

ups. Thought they were part of .gitignore :fearful:

2017-02-07 16:47 UTC, DeepDiver1975 commented
> ups. Thought they were part of .gitignore :fearful:

it is - but if you do a git add  node_modules they  go in :wink:

2017-02-08 10:28 UTC, michaelstingl commented
I checked input fields of the Sharing panel. Autofocus is disabled in IE11. 👍 

I'm not aware of issues with MS Edge Browser, so disabling it for Edge shouldn't be necessary.

2017-02-08 10:28 UTC, michaelstingl requested changes
I checked input fields of the Sharing panel. Autofocus is disabled in IE11. 👍

I'm not aware of issues with MS Edge Browser, so disabling it for Edge shouldn't be necessary.

2017-02-10 10:33 UTC, PVince81 commented on core/js/sharedialoglinkshareview.js
> +				if (!bowser.msie) {
We already had a method `OC.Util.isIE()` for this.
Sorry I didn't notice earlier...

2017-02-13 12:20 UTC, felixheidecke commented on core/js/sharedialoglinkshareview.js
> +				if (!bowser.msie) {
This should be replaced by bowser.js in the future to test against version, os and other devices. Could even test before the DOM is ready. Better after 10.0 release tho. :wink:
Should I revert or keep it in for future use?

2017-02-13 17:20 UTC, PVince81 commented on core/js/sharedialoglinkshareview.js
> +				if (!bowser.msie) {
Keep it, but maybe make OC.isIE also use that?

2017-02-14 11:18 UTC, felixheidecke commented on core/js/sharedialoglinkshareview.js
> +				if (!bowser.msie) {
I'm on it ;-)

2017-02-14 12:24 UTC, felixheidecke commented
@michaelstingl please re-evaluate.

2017-02-15 12:34 UTC, michaelstingl approved these changes

2017-02-15 12:50 UTC, merged