New collumn of execution time added in db schema of oc_jobs
owncloud/core pull request #27144
Opened 2017-02-12 23:54 UTC by noveens

## Description

I have changed the schema of the db_structure.xml file and the corresponding tests where oc_jobs was concerned.

I added a column of execution duration in the oc_jobs table.

## Related Issue

https://github.com/owncloud/core/issues/27137

## Motivation and Context

This is a new feature which could help in testing of the system.

## How Has This Been Tested?

I haven't tested this.

## Screenshots (if appropriate):
Not necessary.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-12 23:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=27144) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=27144) before we can accept your contribution.<br/>

2017-02-13 08:36 UTC, PVince81 commented
This will likely not be enough.

In past ownCloud versions, the XML file was the authority regarding database schemas.
Since master / 10.0, we should use migrations to make database changes.

Have a look how it's done here: https://github.com/owncloud/core/blob/master/core/Migrations/Version20170111103310.php#L9.
Some docs about migrations: https://github.com/owncloud/documentation/pull/2742 (unfinished as this is brand new).

Let me know if you need assistance.

Once this is done the next step is to adjust the background job runner to measure the execution time and put it there.

2017-02-13 08:48 UTC, noveens commented
@PVince81 , thanks for the quick review, I'll look into it as soon as possible.
Thanks for the links to ducumentation as well.

2017-02-13 21:16 UTC, noveens commented
@PVince81 , please check now, I completed making another column in oc_jobs table named execution time through migration.

2017-02-13 21:36 UTC, DeepDiver1975 requested changes

2017-02-13 21:36 UTC, DeepDiver1975 commented on tests/lib/DB/schemDiffData/core.xml
> +			<field>
not needed

2017-02-13 21:36 UTC, DeepDiver1975 commented on tests/lib/DB/schemDiffData/unsigned.xml
> +			<field>
not needed

2017-02-13 21:55 UTC, noveens commented on tests/lib/DB/schemDiffData/unsigned.xml
> +			<field>
So I shouldn't add the new column in oc_jobs table in the schema of the tests?

2017-02-13 21:58 UTC, DeepDiver1975 commented on tests/lib/DB/schemDiffData/unsigned.xml
> +			<field>
no this is not necessary

2017-02-13 22:09 UTC, noveens commented on tests/lib/DB/schemDiffData/unsigned.xml
> +			<field>
removing it.

2017-02-13 22:17 UTC, DeepDiver1975 commented
@noveens THx - next would be to fill the columns :wink:

2017-02-13 23:23 UTC, noveens commented
@DeepDiver1975 , does that come in the scope of this bug?

2017-02-14 08:42 UTC, PVince81 commented
@noveens yes, because else the column is completely useless.

Do you need pointers ?

2017-02-14 08:54 UTC, noveens commented
@PVince81, pointers would be a great way to start.

2017-02-14 09:13 UTC, PVince81 commented
![Pointers](https://imgs.xkcd.com/comics/pointers.png)

The job is executed here: https://github.com/owncloud/core/blob/master/cron.php#L122

I suggest you add statements around here https://github.com/owncloud/core/blob/master/lib/private/BackgroundJob/Job.php#L52 to measure the running time. Then store the value in the database.

For storing, use something like https://github.com/owncloud/core/blob/master/lib/private/BackgroundJob/JobList.php#L307. Maybe a new method `setLastRunTime()`.

2017-02-14 12:39 UTC, noveens commented
@PVince81 , I have made the new method, but how to check the changes I have made?

2017-02-14 12:58 UTC, PVince81 commented on lib/private/BackgroundJob/JobList.php
> +			->set('last_run', $query->createNamedParameter($timeTaken, IQueryBuilder::PARAM_INT))
wrong column ?

2017-02-14 13:01 UTC, PVince81 commented
@noveens please have a look at my comment.

To test this you can run `php cron.php` manually.
If no job is running because of the schedule, you can reset the jobs manually with the following SQL query:
```
update oc_jobs set last_run=0,last_checked=0,reserved_at=0;
```

Then run cron.php again and see if your new column is populated.

2017-02-14 14:34 UTC, noveens commented on lib/private/BackgroundJob/JobList.php
> +			->set('last_run', $query->createNamedParameter($timeTaken, IQueryBuilder::PARAM_INT))
sorry, bad mistake :p

2017-02-14 14:38 UTC, noveens commented on lib/private/BackgroundJob/JobList.php
> +			->set('last_run', $query->createNamedParameter($timeTaken, IQueryBuilder::PARAM_INT))
@PVince81 , updated

2017-02-14 14:45 UTC, noveens commented
@PVince81 , please recheck

2017-02-14 16:08 UTC, PVince81 commented
Code looks good so far. Thanks.

Will test it later.

2017-02-14 20:00 UTC, PVince81 commented
I tested it but after running cron.php I see the last_run being populated, but the value of "execution_duration" is always 0.

Even if my computer is too fast, I'd still expect values of at least a few millisecond.
Is that timestamp in seconds ?

Wanted to test it with LDAP (which provides ways to have slower jobs) but the app is broken at the moment: https://github.com/owncloud/core/issues/27154

2017-02-14 21:06 UTC, noveens commented
@PVince81 ,
The new column I have added is of integer type since the time() function gives seconds since epoch
But the general case has time lesser than 1 second.

Hence I chose this approach.
If you need any updation, please tell me.

2017-02-15 08:54 UTC, PVince81 commented
- [ ] increase last digit in version.php to trigger an update

2017-02-15 08:56 UTC, PVince81 commented
Tested with LDAP. I saw cron.php taking a minute or so, still the column "execution_duration" contains only zeroes.

How did you test it?

2017-02-15 20:15 UTC, noveens commented
@PVince81 ,
To be frank, I didn't test it because I couldn't find a way to populate the database.
Also, once populated how should I check the values in the database?

It would be great if you could tell me how to test this.

2017-02-15 20:17 UTC, PVince81 commented
Told you here: https://github.com/owncloud/core/pull/27144#issuecomment-279701127

The table is already pre-populated by default recurring jobs after setting up OC.

2017-02-15 23:05 UTC, noveens commented
@PVince81 ,
Everything is fixed now, after lot of research and mind-breaking, my mistake was : 
I was calling setExecutionTime from the wrong class (had to be called from Job class rather than JobList class).

Please Recheck.

2017-02-16 08:34 UTC, PVince81 commented
Okay cool, it seems to work now.

I wonder if we should use millisecond values here to avoid having misleading zeroes in the column.

Thoughts ? @dercorn @jvillafanez @butonic @DeepDiver1975

2017-02-16 09:02 UTC, noveens commented
@PVince81 ,
I think we can use gettimeofday( ) to get the execution time in the precision of even microseconds, though milli is better (considering overflow problems).
Should I change the code to store milliseconds rather than seconds?

2017-02-16 12:01 UTC, jvillafanez commented
Please, include a log in the Job.php file. This will help to track the request id of the job and know what it's doing. Something like:
```
public function execute($jobList, ILogger $logger = null) {
  $jobList->setLastRun($this);
  try {
    $t1 = time();
    \OCP\Util::writeLog('jobs', 'Started background job ' . get_class($this) . print_r($this->argument, true), \OCP\Util::DEBUG);
      $this->run($this->argument);
    $secs = time() - $t1;
    \OCP\Util::writeLog('jobs', "Finished background job $secs seconds " . get_class($this) . print_r($this->argument, true), \OCP\Util::DEBUG);
  } catch (\Exception $e) {
```
So
* A log there is important. This will help to distinguish what log entries come from the background job. It's your choice if you want to wrap the `run` method in a "start" and "finish" logs.
* Logging the class with `get_class($this)` is important. This will allow to match the request id with the specific job, which will make easy to track down what the specific job is doing.
* Logging the arguments isn't really needed. I'm not sure if there is a job that uses a password, and not sure if the password will leak. In case of doubt, just ignore the arguments and stay safe.

2017-02-16 12:05 UTC, jvillafanez commented
> I wonder if we should use millisecond values here to avoid having misleading zeroes in the column.

I don't think it's needed. If we need a default value to know what jobs haven't run already, just use null or -1, and let 0 be a valid value. We don't need such precision because we're interested in long running jobs.

2017-02-16 12:13 UTC, noveens commented
@jvillafanez ,
I like the method of having a default value of -1.
I'll implement it.

I'll research more about the log part and get back if required.

2017-02-16 12:14 UTC, noveens commented
@jvillafanez , I'll implement the log part as well

Updating changes in 10 mins.

2017-02-16 12:37 UTC, noveens commented
@jvillafanez @PVince81 @DeepDiver1975 ,
Please review this PR since it seems it's okay to me now.

2017-02-16 13:22 UTC, jvillafanez commented on lib/private/BackgroundJob/Job.php
> +			\OCP\Util::writeLog('jobs', 'Started background job ' . get_class($this) . print_r($this->argument, true), \OCP\Util::DEBUG);
```
'Started background job ' . get_class($this) . ' : ' . json_encode($this->argument)
```
it seems a nicer message.

2017-02-16 13:22 UTC, jvillafanez commented on lib/private/BackgroundJob/Job.php
> +			\OCP\Util::writeLog('jobs', "Finished background job $timeTaken seconds " . get_class($this) . print_r($this->argument, true), \OCP\Util::DEBUG);
```
'Finished background job ' . get_class($this) . ' : ' . json_encode($this->argument) . " (it took $timeTaken seconds)"
```
nicer message

2017-02-16 13:26 UTC, jvillafanez commented
I don't have experience with migrations, but code looks good.

2017-02-16 15:19 UTC, PVince81 commented on lib/private/BackgroundJob/Job.php
> +			\OCP\Util::writeLog('jobs', "Finished background job $timeTaken seconds " . get_class($this) . print_r($this->argument, true), \OCP\Util::DEBUG);
also change the app name to "cron", not "jobs".

2017-02-16 15:19 UTC, PVince81 commented
Apart from the cron message this looks good.

2017-02-16 16:28 UTC, noveens commented
@bantu, @tanghus, @butonic, @DeepDiver1975 and @PVince81 ,

Please check the code, I think bug's solved now.

2017-02-17 08:21 UTC, jvillafanez commented
```
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 12","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 12","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\ExpireSharesJob job with ID 13","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\ExpireSharesJob job with ID 13","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Started background job of class : OC\\Authentication\\Token\\DefaultTokenCleanupJob","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2017-02-16T07:47:28+00:00","level":1,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Finished background job, the job took : 0 seconds\njob is an instance of class : OC\\Authentication\\Token\\DefaultTokenCleanupJob","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Run OCA\\User_LDAP\\Jobs\\UpdateGroups job with ID 15","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
{"reqId":"fpgDDP2MArnPXZMA\/Ni+","remoteAddr":"","app":"cron","message":"Finished OCA\\User_LDAP\\Jobs\\UpdateGroups job with ID 15","level":0,"time":"2017-02-17T07:47:28+00:00","method":"--","url":"--","user":"--"}
```

A couple of things taking into account from the logs:
* The `PHP_EOL` should be removed. Each log entry will be in one line, so any newline char is an unwanted addition.
* You've put `get_class($this) . print_r($this->argument, true)`. There is no space between both the get class and the print_r, so the output might be confusing.
* For now, I haven't seen any output for the `print_r($this->argument, true)`. I'm not sure how the log will look like. @noveens if you've tested it, please show a couple of outputs: one with the print_r and another one with the json_encode, so we can check what format is more useful for the admin. (I'm not requesting any change for this at the moment).

Aside from this, we have another problem as you can see in the log output: duplicated and also false messages.

Those logs come from https://github.com/owncloud/core/blob/master/cron.php#L121 , and duplicate the new logs.

In addition, timed jobs can skip their own execution (https://github.com/owncloud/core/blob/master/lib/private/BackgroundJob/TimedJob.php#L52-L54), so the "Run blablabla job with ID 13" message could be a lie because the job can be skipped.

Taking this into account, I think we should include the removal of those message and stick with the new logs because they're more accurate.

2017-02-17 11:28 UTC, noveens commented
@jvillafanez ,

As requested, I have deleted the log statements from :  https://github.com/owncloud/core/blob/master/cron.php#L121

Plus, Even I didn't find print_r($this->argument, true) print anything but IMO we should leave it so that if we have some arguments in future, it would print them.

2017-02-17 11:59 UTC, jvillafanez commented on lib/private/BackgroundJob/Job.php
> +			echo 'some' . PHP_EOL;
remove this `echo` and the `gettype` below

2017-02-17 12:03 UTC, jvillafanez commented
I think we're almost there. We'll have to check how it behaves and check if there is any additional unexpected consecuence.

From my point of view, just fix the comment above, and then it's ready for testing.

2017-02-17 12:17 UTC, noveens commented on lib/private/BackgroundJob/Job.php
> +			echo 'some' . PHP_EOL;
sorry, forgot to remove the debug statements.

Updated changes pushed.

2017-02-17 12:48 UTC, jvillafanez commented
@PVince81 @DeepDiver1975 I had to manually increase the OC version to force the trigger of the migration code (checked against daily master). I guess this will be fine once the code is merged. It's just to confirm that no more changes are needed.

Calling @owncloud/qa ....

Things to check ( @noveens feel free to add anything that has to be checked and I might be missing)
* New column "execution_time" in the "jobs" table with a default value of -1
* Running cron will:
    * set the execution time in seconds of the job in the "jobs" table. 0 is a valid value. It will help to identify what jobs have run and what jobs not.
    * add new logs entries in the owncloud.log. The logs entries should be clear enough to know what jobs have run, and should match the information contained in the "jobs" table.
* Need to test against a "heavy" system to verify we're counting the seconds right and not just setting zeros. Probably testing with LDAP active is enough to have some slow jobs which should take more than 1 second to execute.
* Find a job with arguments and check the log output.

Jenkins is complaining.... we'll need to check what happens with the tests.

2017-02-17 13:01 UTC, noveens commented
@jvillafanez ,
the column name is "execution_duration", rest everything seems fine to me.

2017-02-17 22:39 UTC, noveens commented
@bantu, @tanghus, @butonic, @DeepDiver1975 and @PVince81 ,

I managed to pass Jenkins now ( took 1h 42m :p ) please have a look and review this PR.

2017-02-20 08:04 UTC, jvillafanez commented
Revert the permission change in the config.sample.php file please.

2017-02-20 12:19 UTC, davitol commented
> New column "execution_time" in the "jobs" table with a default value of -1
> Running cron will:
> 
>     set the execution time in seconds of the job in the "jobs" table. 0 is a valid value. It will help to identify what jobs have run and what jobs not. ✅ 
>     add new logs entries in the owncloud.log. The logs entries should be clear enough to know what jobs have run, and should match the information contained in the "jobs" table.
> ✅ 
> Need to test against a "heavy" system to verify we're counting the seconds right and not just setting zeros. Probably testing with LDAP active is enough to have some slow jobs which should take more than 1 second to execute. ✅ 
> Find a job with arguments and check the log output.  ✅ 

:+1:

IMHO A small enhancement when running a job **without** arguments will be to not print the **with arguments : ** text


```
{"reqId":"4vkT2Z8Fy\/yzBApDPlqT","remoteAddr":"","app":"cron","message":"Finished background job, the job took : 0 seconds, this job is an instance of class : OCA\\Files\\BackgroundJob\\CleanupFileLocks with arguments : ","level":0,"time":"2017-02-20T12:08:15+00:00","method":"--","url":"--","user":"--"}
```

2017-02-20 13:59 UTC, noveens commented
@jvillafanez ,
I didn't get the part I have to change,
you're talking about which permissions?

2017-02-21 08:08 UTC, jvillafanez commented
<img width="1020" alt="screen shot 2017-02-21 at 09 05 54" src="https://cloud.githubusercontent.com/assets/1477829/23155941/160021d2-f815-11e6-9502-0f56eebd7ad5.png">

That change in the permissions of the config.sample.php . It shouldn't appear.

2017-02-21 10:54 UTC, noveens commented
@jvillafanez ,
pushed the changes.

2017-02-21 10:58 UTC, noveens commented
@DeepDiver1975 ,
please re-review this

2017-02-21 11:39 UTC, jvillafanez commented
I don't have anything more to add 👍

2017-02-23 10:11 UTC, noveens commented
@PVince81 ,
Can this be merged, I think it's fine now.

2017-02-23 10:12 UTC, PVince81 commented
@DeepDiver1975 can you kick Jenkins to retest this ?

2017-02-23 12:30 UTC, noveens commented
@PVince81 ,
This passed jenkins before my previous commit, which was just modifying the file permissions of config.sample.php which i suppose has nothing to do with any of the tests.

2017-02-23 12:31 UTC, merged

2017-02-23 12:32 UTC, PVince81 commented
Added to new features page: https://github.com/owncloud/core/wiki/ownCloud-10.0-Features

2017-02-23 14:02 UTC, jvillafanez commented
@PVince81 @DeepDiver1975 Backport the logging part? I think it could be quite useful and not intrusive. DB changes won't be backported.

2017-02-23 14:10 UTC, PVince81 commented
Yes, please backport the logging part.

@noveens can you do it ? Basically create a branch off "stable9.1", put your commits there then submit a PR that targets stable9.1. Only put the logging part there.

2017-02-23 14:20 UTC, noveens commented
@PVince81 ,
Sure I can do that.
Just the logging part right?
And do I have to update anything in this branch?

2017-02-23 14:38 UTC, PVince81 commented
Nothing to update here. Make a new branch.

2017-02-27 08:10 UTC, PVince81 commented
stable9.1 logging changes backport: https://github.com/owncloud/core/pull/27239