26749 final
owncloud/core pull request #27155
Opened 2017-02-14 20:54 UTC by noveens

## Description

I replaced all instances of showTemporary with show which has a cross to remove notifications.

## Related Issue

https://github.com/owncloud/core/issues/26749

## Motivation and Context

Brings a cross to remove pop-up notifications.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-02-15 08:20 UTC, PVince81 commented
Now thinking of it, we probably don't need the timeout at all for error messages.

The timeout was there in the past because the user could not close error messages. But now with the button they can. And it's better that they stay until closed to make sure the user saw it.

Imagine you start uploading a huge file, go away. Then there is an error. If the error disappears after 7 seconds, you'll never know whether the upload succeeded or not.

So let's remove the timeout for all errors that are closeable.

Just make a single commit, no need to split into so many small commits, there is no benefit for splitting this way. Thanks.

2017-02-15 11:42 UTC, noveens commented
@PVince81 ,
Sure I'll update the changes by tonight

2017-02-15 23:38 UTC, noveens commented
@PVince81 ,
Updated, please recheck

2017-02-16 08:56 UTC, PVince81 requested changes

2017-02-16 08:56 UTC, PVince81 commented on apps/files/js/file-upload.js
> +		OC.Notification.show('Upload cancelled.', {type: 'error'});
Please leave the timeout for this one. Cancelling an upload is a user action.
I tested this and it feels a bit annoying to have to not only cancel the upload but also close the error.

2017-02-16 08:56 UTC, PVince81 commented on apps/files/js/filelist.js
> +									OC.Notification.show('Could not rename "{fileName}", it does not exist any more',
You missed/killed the translation function `t()` here and many other places.
Please recheck all locations.

2017-02-16 08:56 UTC, PVince81 commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
duplicate key ? also you removed the translation function

2017-02-16 09:13 UTC, noveens commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
I couldn't find the meaning of t() function

Can you please tell me what it does.

I'll update the changes by tonight

2017-02-16 09:16 UTC, PVince81 commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
`t('Some message {placeholder}', {placeholder: 'some value to insert'})` => this will render the message "Some message some value to insert".
The "t" function will translate to another language if you switch to another language in the settings, try it.

It would be good if you could also test the changes you made or at least a few, this way you could see that something is wrong with the code.

2017-02-16 09:29 UTC, noveens commented
Oh got it now, I found some weird dictionarys while randomly going through the code.

Now I know what it does.
Will include the translate capability.

Sure, will test the changes I made.

2017-02-16 13:24 UTC, noveens commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
@PVince81 ,
when i made these changes, always a [object object ] message pops up
my guess would be that showTemporary did something with that array but show doesn't.

2017-02-16 13:29 UTC, noveens commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
I have uploaded a screenshot of the same:

http://pasteboard.co/z2viGllSc.png

2017-02-16 13:33 UTC, PVince81 commented on apps/files/js/files.js
> +							owner: ownerDisplayName,
Have a closer look at the parenthesis. Now you mixed up the values in a different way.

The correct way is:
```js
OC.Notifications.show(
    t(
        'some message maybe with {placeholder}',
        {placeholder: 'value for placeholder'}
    ),
    {
        type: 'error'
    }
);
```
(placeholder optional, only when applicable)

2017-02-16 16:18 UTC, noveens commented
@bartv2, @jmaciasportela, @PVince81 and @Xenopathic ,

Please review the updates, I think bug's solved now.

2017-02-17 09:46 UTC, PVince81 commented on apps/files/js/filelist.js
> +					OC.Notification.show(t('files', 'Invalid path'), {meout: 7, type: 'error'});
"meout" ?

2017-02-17 10:48 UTC, noveens commented on apps/files/js/filelist.js
> +					OC.Notification.show(t('files', 'Invalid path'), {meout: 7, type: 'error'});
oh sorry, my bad :p

2017-02-17 12:18 UTC, noveens commented
@PVince81 ,

Changes pushed.

2017-02-20 13:49 UTC, PVince81 commented
Now run `make test-js` and fix the test issues one by one.

In most cases you need to replace the stubbed call with `show` instead of `showTemporary`.
Let me know if you need guidance there.

2017-02-20 14:05 UTC, noveens commented
@PVince81 ,
Thanks for the pointers :P
Updated the test-files now.

2017-02-20 14:46 UTC, noveens commented
@PVince81 ,
Jenkins still seems to fail, I have no idea why.
Can you please look into it?

2017-02-20 14:48 UTC, PVince81 commented
@noveens this time it's bad luck:
```
15:09:53 Fire up the mysql docker
15:09:53 docker: Error response from daemon: grpc: the connection is unavailable.
```

2017-02-20 14:50 UTC, noveens commented
@PVince81 ,
anything else required for this issue?

2017-02-20 14:57 UTC, PVince81 commented on apps/files/js/filelist.js
> +			OC.Notification.show(t('files', message), {type: 'error'});
`message` is already translated, no need to retranslate it here

2017-02-20 14:58 UTC, PVince81 commented on apps/files/js/file-upload.js
> +						OC.Notification.show(t('files', data.errorThrown), {type: 'error'});
don't translate `data.errorThrown` here

2017-02-20 14:59 UTC, PVince81 commented on apps/updatenotification/js/notification.js
> +			type: 'error'
Not technically an error but more like an information message.

Adding the error type does make it display the cross though.

2017-02-20 16:02 UTC, noveens commented on apps/updatenotification/js/notification.js
> +			type: 'error'
I guess we should let this be?

2017-02-20 17:46 UTC, PVince81 commented on apps/updatenotification/js/notification.js
> +			type: 'error'
Yes, leave it like it was before for now

2017-02-23 10:12 UTC, noveens commented
@PVince81 ,
Can this be merged now, I think it's fine now.

2017-02-23 10:13 UTC, PVince81 commented
Yes, Jenkins is green.

2017-02-23 10:13 UTC, merged