Legacy example theme to app-theme (*wip*)
owncloud/core pull request #27162
Opened 2017-02-15 12:05 UTC by phisch

## Description
Since we have updated the way themes are created, and we only support the old theme directory out of legacy theme support reasons, the example theme should get updated to the newer way of providing themes. That's what this PR is for.

## Related Issue
https://github.com/owncloud/documentation/pull/2844

## Motivation and Context
Since the Documentation is currently being updated, we should update the theme so the documentation can reference to it as an example.

## How Has This Been Tested?
This is just providing a theme through a different way. Will be tested by hand.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-15 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=27162) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=27162) before we can accept your contribution.<br/>

2017-02-15 12:55 UTC, DeepDiver1975 commented on apps/example-theme/appinfo/info.xml
> +	<name>Example OwnCloud Theme</name>
ownCloud

2017-02-15 12:55 UTC, DeepDiver1975 commented on apps/example-theme/appinfo/info.xml
> +	<description>This App provides the example OwnCloud theme.</description>
ownCloud

2017-02-28 11:13 UTC, phisch commented
Theme can be enabled as an app now.
Please test and confirm.

2017-02-28 16:42 UTC, DeepDiver1975 requested changes

2017-02-28 16:42 UTC, DeepDiver1975 commented on apps/example-theme/appinfo/info.xml
> +		<owncloud min-version="9.2" max-version="10" />
there is no 9.2 - lets use 10 ad min and max

2017-02-28 16:46 UTC, phisch commented on apps/example-theme/appinfo/info.xml
> +		<owncloud min-version="9.2" max-version="10" />
Okay, i'll do the same for the enterprise theme.

2017-02-28 20:28 UTC, butonic commented
my serverroot is `/home/jfd/www/core` (it is a bind mount for apache with www-data rights)
the webroot is `https://asylum/oc/core/`

But in `\OC\Template\ResourceLocator::appendOnceIfExist` `$file` is `'oc/core/apps/example-theme/core/css/styles.css'` and as a result builds the wrong path: 
`/home/jfd/www/core/oc/core/apps/example-theme/core/css/styles.css` when it should be `/home/jfd/www/core/apps/example-theme/core/css/styles.css`
`OC::$WEBROOT` is correct with `"/oc/core"`

This is a quickfix:
```diff
--- lib/private/Template/ResourceLocator.php (revision )
+++ lib/private/Template/ResourceLocator.php (revision )
@@ -107,8 +107,8 @@
   */
  protected function appendOnceIfExist($root, $file, $webRoot = null) {
 
-  if (substr(ltrim($file, '/'), 0, strlen(\OC::$WEBROOT)) === \OC::$WEBROOT) {
-   $file = substr($file, strlen(\OC::$WEBROOT)-1);
+  if (substr('/'.$file, 0, strlen(\OC::$WEBROOT)) === \OC::$WEBROOT) {
+   $file = substr($file, strlen(\OC::$WEBROOT));
   }
 
   $path = $this->buildPath([$root, $file]);
```

But this should obviously be fixed in a better way.

2017-03-01 10:09 UTC, DeepDiver1975 approved these changes

2017-03-01 10:09 UTC, merged