[WIP] Central user account table arriving .....
owncloud/core pull request #27165
Opened 2017-02-15 15:34 UTC by DeepDiver1975

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-15 15:43 UTC, PVince81 reviewed
Great start!

2017-02-15 15:43 UTC, PVince81 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('id', 'integer', [
let's go big ? bigint ?

2017-02-15 15:43 UTC, PVince81 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('quota', 'string', [
Now seeing this, I remember that we already have a quota value in the oc_preferences table. But not as easy to retrieve as a single select on this table here.

Might need to think of migrating it.

2017-02-15 15:43 UTC, PVince81 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', 'string', [
also add a `backend_id` which is the user id as seen by the backend ? unless we think it is always the same as the "user_id" column. That is, assuming that multiple backends can't provide the same user id.

2017-02-15 15:43 UTC, PVince81 commented on lib/private/User/Manager.php
> +		$this->backends[get_class($backend)] = $backend;
I think in the end this would only be called in the background job (or on-demand) as we won't need the backend any more for every operation since we can rely on the account table.

2017-02-15 16:38 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', 'string', [
Maybe not that clear but this is - as of now - the class name of the backend

2017-02-15 16:39 UTC, DeepDiver1975 commented on lib/private/User/Manager.php
> +		$this->backends[get_class($backend)] = $backend;
we need the backend for login, inital setup of new accounts (auto provision mode) and import scenarios

2017-02-16 16:01 UTC, PVince81 commented on lib/private/Files/View.php
> +		return $this->userManager->get($ownerId);
This will break with federated share owners which are not resolveable through the user manager. That's why we create a "virtual" user...

2017-02-16 17:40 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +		return $this->userManager->get($ownerId);
Hmmmm - ok - then we need a second implementation of IUser for this case.
User requires an instance of Account and AccountMapper to be passed in ...

2017-02-16 22:49 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
@DeepDiver1975 Why it is a String? Shouldnt it be INT representing foreign key? Why do we allow NULL here?

2017-02-16 22:49 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +			'notnull' => false,
Why do we allow null here?

2017-02-16 22:49 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +			'comment' => '0: initial, 1: enabled, 2: disabled, 3: deleted'
0: initial, I start loving it. Is it connected with last_login, backend and home?

2017-02-16 22:49 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +			'notnull' => false,
Is it connected to 0: initial?

2017-02-16 22:49 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
Is it connected to 0: initial?

2017-02-16 22:49 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +			->orderBy($fieldName, $orderBy ? 'ASC' : 'DESC');
orderBy is quite expensive operation, do we need to do that by default?

2017-02-16 22:55 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +		return $this->findEntities($qb->getSQL(), $qb->getParameters(), $limit, $offset);
We are passing here $limit. Why do we first scan whole the table and then limit that on PHP level?

2017-02-16 22:56 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +			->orderBy($fieldName, $orderBy ? 'ASC' : 'DESC');
Why dont we use LIMIT on DB level? What findEntities is exactly doing?

2017-02-17 06:15 UTC, PVince81 commented on lib/private/Files/View.php
> +		return $this->userManager->get($ownerId);
Indeed, that would align with this idea: https://github.com/owncloud/core/issues/25815#issue-171409585

2017-02-17 06:16 UTC, PVince81 commented on lib/private/Files/View.php
> +		return $this->userManager->get($ownerId);
Later on I wonder if we should also have a "federated users backend" which would deliver such users, they'd also appear in the account table under the "federation" backend for quick lookup. (but that sounds redundant from the system address book)

2017-02-17 07:18 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +		return $this->findEntities($qb->getSQL(), $qb->getParameters(), $limit, $offset);
It is on db level. See the code inside find entries

2017-02-17 07:18 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
Because it's the php class name

2017-02-17 07:21 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->orderBy($fieldName, $orderBy ? 'ASC' : 'DESC');
Limit is on db level. And if we want pagination  we need to sort on db level.
Orderby is not expensive is there is an index.
(Need to add it 😆)

2017-02-17 08:26 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
How do you ensure, that if the backend is deleted, all related records are also deleted. Will we do single transaction doing that? Is backend primary key somewhere? This smells like possible inconsistency later, if some developer is not careful in the future.

2017-02-17 08:49 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
If a backend is not enabled or has been deleted the user can no longer login. Deleting a user is an explicit operation and nothing we should do 'just because the backend is no longer there'

2017-02-17 08:59 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +			'autoincrement' => true,
Is it a primary key or foreign key somewhere? I might have a question here about user uniqueness, where backend tries to add user which already exists, and how do we distinguish between them

2017-02-17 09:00 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('user_id', Type::STRING, [
Is it a primary key or foreign key somewhere? I might have a question here about user uniqueness, where backend tries to add user which already exists, and how do we distinguish between them. I dont also understand why we have two IDs

2017-02-17 09:01 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
I wound ensure this not null, and add another state 4: backend-deleted

2017-02-17 09:01 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +			'autoincrement' => true,
auto increment always forces to be the primary key

2017-02-17 09:02 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('user_id', Type::STRING, [
see the index definition - this is unique

2017-02-17 09:07 UTC, mrow4a requested changes
I think I need to fully understand the relationships and redundancy between tables

2017-02-17 09:08 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +			'autoincrement' => true,
Yes, this is true

2017-02-17 09:11 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('user_id', Type::STRING, [
Do you have some db relations drawing of Migration feature so we can easier understand?

2017-02-17 09:14 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('user_id', Type::STRING, [
I think I see the whole picture of relations of this table with others, but it is easier to look at it

2017-02-17 09:18 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +			'comment' => '0: initial, 1: enabled, 2: disabled, 3: deleted'
I'm not yet fully sure if we need 0:initial ...

2017-02-17 09:22 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +			->orderBy($fieldName, $orderBy ? 'ASC' : 'DESC');
Internaly in DB, in order to do limit, you have to finish all others. Adding OrderBy basically tells the plan generator that you need a whole picture of the table, thus whole scan (it is enforced by sort requiring full view on the input). Of course, unless you have index, found good reference https://www.percona.com/blog/2006/09/01/mysql-order-by-limit-performance-optimization/. Just wanted to ensure that we wont do anything crazy here :>

2017-02-17 09:52 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
yes - nut null makes sense here - thx

2017-02-17 09:53 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +		return $this->userManager->get($ownerId);
something to think about - for sure ....

2017-02-17 09:55 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->orderBy($fieldName, $orderBy ? 'ASC' : 'DESC');
The users are expected to be sorted - this has to be done in the db - no other option available

2017-02-17 09:56 UTC, DeepDiver1975 commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('user_id', Type::STRING, [
> Do you have some db relations drawing of Migration feature so we can easier understand?

I don't get this question. The migration feature is unrelated any db relations.

2017-02-17 09:57 UTC, DeepDiver1975 commented
> I think I need to fully understand the relationships and redundancy between tables

I guess so 😉

2017-02-17 10:17 UTC, mrow4a commented on core/Migrations/Version20170214112458.php
> +		$table->addColumn('backend', Type::STRING, [
Ok, because I assume we dont have a new table holding backends, we just use classnames to do that? Makes sense.

2017-02-21 12:02 UTC, mrow4a commented
@DeepDiver1975 I did not go in details in the code yet, but seems the priority in implementation of this table will be to put as much load on table scan of oc_account table, so most of queries will just ask for records of this table, and very very seldomely do the join with e.g. ldap table (this is expensive, if both tables are big, and it will be like that).

2017-02-21 14:54 UTC, PVince81 commented
> very very seldomely do the join with e.g. ldap table

@mrow4a no, if we had that it would be nice.
No, the old code does a PHP-level "join" by connecting directly to LDAP... or in some cases memcache. But partial searches are not possible with memcache so they always hit LDAP.

With this table partial searches can be done only in a single location: the oc_account table.

2017-02-21 14:55 UTC, PVince81 commented
Basically we want to avoid to hit LDAP or any other user management systems at all when not needed and rely on local information.

2017-02-28 11:55 UTC, mrow4a approved these changes

2017-03-08 17:26 UTC, PVince81 commented
> store password reset token in the account table
> store language setting in the account table as well

I'd say only store the stuff you need to efficiently read in a single query, especially the stuff in bulk.

I assume that the language is only every read once at login time, so reading oc_preferences might be ok. once.

2017-03-08 17:47 UTC, PVince81 commented
- [ ] BUG: weird error when trying to log in as a non-synced LDAP user
```
{"reqId":"hojTGqtsmakFuzvFWkTb","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\User_LDAP\\\\ILDAPWrapper! Class can not be instantiated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(113): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\User_LDAP\\\\\\\\I...')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\I...')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(65): OC\\\\ServerContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\I...')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(92): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(113): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\User_LDAP\\\\\\\\C...')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\C...')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(65): OC\\\\ServerContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\C...')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(92): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(113): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\User_LDAP\\\\\\\\A...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\A...')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(65): OC\\\\ServerContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\A...')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(92): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(113): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\User_LDAP\\\\\\\\U...')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\U...')\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Account.php(81): OC\\\\ServerContainer->query('OCA\\\\\\\\User_LDAP\\\\\\\\U...')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(368): OC\\\\User\\\\Account->getBackendInstance()\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(207): OC\\\\User\\\\Manager->newAccount('04c5609e-9872-1...', Object(OCA\\\\User_LDAP\\\\User_LDAP))\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(179): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#18 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#21 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#22 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#23 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#24 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#25 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(901): OC\\\\Route\\\\Router->match('\\\/login')\\n#26 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#27 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":94}","level":3,"time":"2017-03-08T17:44:33+00:00","method":"POST","url":"\/owncloud\/index.php\/login","user":"--"}
```

- [ ] BUG: 'occ user:sync` or `occ user:sync OCA\User_LDAP\User_LDAP` does not populate the accounts table with LDAP users. This is a freshly configured LDAP and the mapping tables are empty and stay that way. (usually you could get them populated by going to the users page but that doesn't work here any more).

This was all with https://github.com/owncloud/administration/tree/master/ldap-testing and zombies.

2017-03-08 21:34 UTC, DeepDiver1975 commented
> I'd say only store the stuff you need to efficiently read in a single query, especially the stuff in bulk.

let's see where we get with this over all - anyway: this is low prio ....

2017-03-09 07:43 UTC, butonic commented
I'd say store everything related to a user we need on 90% of the requests in the account table to save as many queries as possible. uid, display name, email, language, avatar, home mount, ... Very likely more that we query every time.

2017-03-09 07:54 UTC, butonic commented
On a different note the account table leads to a completely different role of user back ends. They basically only have a single responsibility: authenticating the user with checkPassword(). If successful the back end may update the account table with new display name or email etc if they changed.

That's it.

Then there is the task of keeping a user back end and the account table in sync. Which I see as an occ sync command. In addition to a sync all we also need a sync this uid, because for LDAP there may be triggers that can be used to update a user on demand. Gonicus eg allows that.

The user shibboleth backed in auto provision mode also just updates the account table. In SSO only mode it won't even do that.

Personally, I see an authenv app that just logs in a userid that is stored in a configurable environment variable. It may or may not require the user to exist in the account table (auto provision). That solves a lot of use cases and even allows logging in via client certificate...

2017-03-09 07:55 UTC, butonic commented
Obviously, this will require use to kill a lot of code in user_ldap and make migration rock solid.

2017-03-09 08:16 UTC, DeepDiver1975 commented
> Then there is the task of keeping a user back end and the account table in sync. Which I see as an occ sync command. In addition to a sync all we also need a sync this uid, because for LDAP there may be triggers that can be used to update a user on demand. Gonicus eg allows that.

see #27205

2017-03-09 08:36 UTC, PVince81 commented
Something comes to mind: do we need a "lastsynctime" column ?
In LDAP we had "lastFeatureRefresh" in the preferences table which told the LDAP code to not try and refetch the user details based on that value.

2017-03-09 09:28 UTC, butonic approved these changes
I tried understanding the changes. Impressive list of test changes ... the avatar stuff can be discussed idependently.

2017-03-09 09:28 UTC, butonic commented on lib/private/User/RemoteUser.php
> +	public function getAvatarImage($size) {
I don't think we really need the avatar image as part of the user. I'd prefer to implement it as an app. That app can store the avatar image inside its app folder, no need for our internal filesystem. It could try to fetch the avatar from gravatar based on the email address if an internal avatar is not available.

2017-03-09 09:28 UTC, butonic commented on lib/private/User/User.php
> +		return (int)$this->account->getLastLogin();
shouldn't the entity return the right type?

2017-03-09 09:28 UTC, butonic commented on lib/private/User/User.php
> +		// FIXME: Feels like an hack - suggestions?
foreign keys ftw ;-)

2017-03-09 09:28 UTC, butonic commented on lib/private/User/User.php
> +	public function __construct(Account $account, AccountMapper $mapper, $emitter = null, IConfig $config = null,
so we don't really need the user database backend anymore, right?

2017-03-09 09:35 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->where($qb->expr()->eq('lower_user_id', $qb->createFunction("LOWER($parameter)")));
php strtolower and database tolower behave slightly different - we have to choose one way .... (hmmm .... do I?)

2017-03-09 09:35 UTC, DeepDiver1975 commented on lib/private/User/RemoteUser.php
> +	public function getAvatarImage($size) {
separate discussion - from an api poc it is there - not much to change right away ...

2017-03-09 09:36 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +		return (int)$this->account->getLastLogin();
yes - it should ....

2017-03-09 14:00 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->where($qb->expr()->eq('lower_user_id', $qb->createFunction("LOWER($parameter)")));
grrr - actually I'm mixing it :man_facepalming:

2017-03-09 14:44 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->where($qb->expr()->eq('lower_user_id', $qb->createFunction("LOWER($parameter)")));
fixed

2017-03-14 12:59 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +	public function __construct(Account $account, AccountMapper $mapper, $emitter = null, IConfig $config = null,
the backend is accessible via the account

2017-03-17 15:05 UTC, PVince81 commented on tests/lib/Files/Cache/CacheTest.php
> +//		$user = new \OC\User\User($userId, null);
commented out ?

2017-03-21 09:38 UTC, closed without merging