UI test for PR #26979
owncloud/core pull request #27191
Opened 2017-02-21 09:59 UTC by individual-it

## Description
This is an UI test for the PR #26979 that fixes the issue #26975

This also includes the complete setup of the selenium infrastructure that can be used as the basis of further UI tests. After the discussion in #27057 behat+mink is used instead of the facebook webdriver.

For this to work travis starts behat/mink tests. And they connect to selenium running on https://saucelabs.com

## Related Issue
PR #26979 
issue #26975

### List of PRs that potentially would benefit of UI tests:
Can't set a user's quota back to Unlimited #26975
Fix long display names #27059
files_external: Keep checkbox and its label on one line #25120

## Motivation and Context

See issue  #27055 
Some bugs are hard to catch with karma & PHPUnit tests. Primarily this are front-end bugs. This PR implements end-to-end testing environment run on real browsers. Currently only Chrome browser is used, but it can be extended to multiple browsers/platforms including mobile browsers.
Currently my own sauce-labs account is used. Of course it would be good that a oC account would be used in future.

### run this tests locally
- download Selenium standalone server jar from http://docs.seleniumhq.org/download/
- download the chromedriver from: https://sites.google.com/a/chromium.org/chromedriver/ and place it in the same folder as the selenium server
- start selenium:` java -jar selenium-server-standalone-3.0.1.jar -port 4445`
- set the 3 environment variables: `SRV_HOST_NAME, SRV_HOST_URL and SRV_HOST_PORT` e.g.:
```
export SRV_HOST_NAME=localhost
export SRV_HOST_URL=owncloud-core
export SRV_HOST_PORT=80
```
- if no webserver is already running start php development server with: `bash tests/travis/start_php_dev_server.sh` (leave `SRV_HOST_URL` empty if you are using the php dev. server `export SRV_HOST_URL=""`)
it will bind to:` $SRV_HOST_NAME:$SRV_HOST_PORT`
- run tests: `bash tests/travis/start_behat_tests.sh`

### limitations
Only PRs from local branches are tested. PRs that come from a fork cannot be tested as they do not have access to the saucelabs username+key.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## How Has This Been Tested?

@individual-it joined travis with their own account on sauce labs and has run multiple tests. Created bugs and run tests again to see if they are failing.

## Screenshots (if appropriate):
**travis job:**
https://travis-ci.org/individual-it/owncloud-core/jobs/203733741
**saucelabs job:**
https://saucelabs.com/beta/tests/840fed2401854c50ab20109ac2812fb3/watch#305

2017-02-22 13:07 UTC, SergioBertolinSG commented
> start selenium:java -jar selenium-server-standalone-3.0.1.jar -port 4445

What version of java is good for this step? openjdk can be used there?

2017-02-22 15:20 UTC, individual-it commented
According to the selenium github page you need Java 8
https://github.com/vvo/selenium-standalone/blob/master/README.md

recent OpenJDK should be fine

On February 22, 2017 6:52:27 PM GMT+05:45, "Sergio Bertolín" <notifications@github.com> wrote:
>> start selenium:java -jar selenium-server-standalone-3.0.1.jar -port
>4445
>
>What version of java is good for this step? openjdk can be used there?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/pull/27191#issuecomment-281663963

2017-02-24 11:13 UTC, SergioBertolinSG requested changes

2017-02-24 11:19 UTC, individual-it commented on tests/ui/features/users.feature
> +		|1 GB       |Unlimited   |
Why shouldn't it work? At least it works fine for me. It runs 5 scenarios from that table. Check the bottom travis output:
https://travis-ci.org/individual-it/owncloud-core/jobs/203733741

2017-02-24 11:30 UTC, SergioBertolinSG commented on tests/ui/features/users.feature
> +		|1 GB       |Unlimited   |
Ahh right. It failed in my environment for different reasons.

2017-02-24 11:34 UTC, SergioBertolinSG commented
Quota validation has this issue open https://github.com/owncloud/core/issues/25358 .

2017-02-24 11:36 UTC, individual-it commented on tests/travis/start_behat_tests.sh
> +export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://'$SRV_HOST_NAME:$SRV_HOST_PORT/'","selenium2":{"wd_host":"http://'$SAUCE_USERNAME:$SAUCE_ACCESS_KEY'@localhost:444
yes that is true, need to have $SRV_HOST_URL here too
always tested it with "start_behat_tests.sh" and that does not have any path
Also just found out that if you use port 80, the browser does not display it and so you get:
`Expected to be on "http://localhost:80/index.php/login" but found "http://localhost/index.php/login" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)`

2017-02-24 12:01 UTC, individual-it commented on tests/travis/start_behat_tests.sh
> +export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://'$SRV_HOST_NAME:$SRV_HOST_PORT/'","selenium2":{"wd_host":"http://'$SAUCE_USERNAME:$SAUCE_ACCESS_KEY'@localhost:444
both problems should be fixed now

2017-03-01 10:30 UTC, DeepDiver1975 commented
I don't like that all travis tests are failing now - can we isolate this to only have selenium failing?

@individual-it can you please quide me to the docs on how to integrate travis and sauce? THX

2017-03-01 14:16 UTC, individual-it commented
The travis tests are failing because the saucelab add-on is enabled but the sauce credentials are not set up in the owncloud travis account. All tests pass on my fork: https://travis-ci.org/individual-it/owncloud-core/builds/204940857

If you agree with the concept you should do this to integrate it and make all tests pass:

1. register to saucelabs and enrol in the open source plan https://saucelabs.com/open-source
2. in travis-ci.org set for the core repro the environment variables SAUCE_USERNAME SAUCE_ACCESS_KEY
3. generate the secure string with `travis encrypt "your-access-key"` https://docs.travis-ci.com/user/sauce-connect
4. get the other changes I've made in .travis.yml into the master .travis.yml. If you like to have as little changes as possible only get those from line: 17,18,34-37 (of course you would have to change line 35+37)
5. then I can make a new PR with all the other files included from a local branch and then all tests should pass

more information is available here: https://docs.travis-ci.com/user/sauce-connect

2017-03-06 10:59 UTC, DeepDiver1975 commented
@individual-it I have added the credentials in the travis settings as environment variables.

Mind rebasing and removing your credentials? THX

2017-03-06 12:43 UTC, individual-it commented
right, my instructions were far too complicated, most of it I can make in the PR itself.
So here is the PR from a local branch  #27316
This PR is not needed any-more, so closing it

2017-03-06 12:43 UTC, closed without merging