Optimize PROPFIND for non-shared/shared by reducing the number of que…
owncloud/core pull request #27284
Opened 2017-03-01 12:32 UTC by mrow4a

Hello guys, after exams I am back at work with a lot of new energy, knowledge and ideas. Lets start the fun with this PR. 

The idea here is behavior of SharedPlugin, which I found out reviewing our code with BlackFire e.g:
This is example query if you have 100 NON-SHARED files, it put my attention on quering sharing table while we dont have shares there, and why dont we just 1 query or so..
![selection_019](https://cloud.githubusercontent.com/assets/13368647/23460015/41c5a002-fe83-11e6-8633-8b1fa2948fba.jpg)

I have been interested in what causes that amount of shares and started optimized the code:
* [x] If the same provider, query cumulatively instead of separate queries
* [ ] Write Unit tests for opt. 1
* [ ] Dont do query for all the nodes, rather use IN() clause https://github.com/owncloud/core/issues/25266#issuecomment-283274412
* [ ] Write Unit tests for opt. 2
* [ ] Give to support @felixboehm @cdamken to test with customers

2017-03-01 12:34 UTC, mrow4a commented
Results for the PROPFIND query: 

**Case 1**
![selection_020](https://cloud.githubusercontent.com/assets/13368647/23460085/97f73486-fe83-11e6-9d71-79491c73dc9b.jpg)

![selection_021](https://cloud.githubusercontent.com/assets/13368647/23460094/a651be20-fe83-11e6-9ca4-6c19c65f6fa8.jpg)

**Case 2**
100 NON-SHARED files, just someone uploaded 100 files to the folder
![selection_022](https://cloud.githubusercontent.com/assets/13368647/23460104/c0a2f3ac-fe83-11e6-8c5c-6794690d4635.jpg)

2017-03-01 12:37 UTC, DeepDiver1975 requested changes

2017-03-01 12:37 UTC, DeepDiver1975 commented on lib/public/Share/IManager.php
> +	 * @since 9.0.0
10.0.0

2017-03-01 12:57 UTC, PVince81 reviewed
Nice step forward, this is going in the right direction I think.

Next step is to take an array of nodes so you can do `where file_source in (...)` (with array_chunk of 1000 blocks)

2017-03-01 12:57 UTC, PVince81 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +	public function getAllSharesBy($userId, $shareTypes, $node, $reshares) {
let's directly add `$limit` and `$offset` to avoid having to change the interface again in the future

2017-03-01 12:57 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +			$node
next step is taking an array of nodes ?

2017-03-01 13:21 UTC, DeepDiver1975 commented
:boom: 
````
OCA\DAV\Tests\unit\Connector\Sabre\SharesPluginTest::testGetProperties with data set #0 (array())
Invalid argument supplied for foreach()

/var/lib/jenkins/workspace/owncloud-core_core_PR-27284-5KMQXE2IARTR6EZOXEANYYNTQ5MB25RWDD7UWVSPM56ZJNO46SIA/apps/dav/lib/Connector/Sabre/SharesPlugin.php:128
/var/lib/jenkins/workspace/owncloud-core_core_PR-27284-5KMQXE2IARTR6EZOXEANYYNTQ5MB25RWDD7UWVSPM56ZJNO46SIA/apps/dav/lib/Connector/Sabre/SharesPlugin.php:171
/var/lib/jenkins/workspace/owncloud-core_core_PR-27284-5KMQXE2IARTR6EZOXEANYYNTQ5MB25RWDD7UWVSPM56ZJNO46SIA/lib/composer/sabre/dav/lib/DAV/PropFind.php:98
/var/lib/jenkins/workspace/owncloud-core_core_PR-27284-5KMQXE2IARTR6EZOXEANYYNTQ5MB25RWDD7UWVSPM56ZJNO46SIA/apps/dav/lib/Connector/Sabre/SharesPlugin.php:175
/var/lib/jenkins/workspace/owncloud-core_core_PR-27284-5KMQXE2IARTR6EZOXEANYYNTQ5MB25RWDD7UWVSPM56ZJNO46SIA/apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php:125

2017-03-01 13:42 UTC, mrow4a commented
Thomas, I just been doing prove of concept, as discussed I will now adjust unit tests :> Wanted to see how much we can get

2017-03-02 09:55 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +			$node
yep

2017-03-02 09:55 UTC, mrow4a commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +	public function getAllSharesBy($userId, $shareTypes, $node, $reshares) {
I think this function is not interested in any offsets, as name states, ALL :>

2017-03-02 09:58 UTC, PVince81 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +	public function getAllSharesBy($userId, $shareTypes, $node, $reshares) {
ALL meaning "the whole result set contains all the shares of that user" but it doesn't mean we shouldn't provide a way to paginate over said result set.

2017-03-02 09:58 UTC, PVince81 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +	public function getAllSharesBy($userId, $shareTypes, $node, $reshares) {
it's the same semantics as if we say "get all users" from an install that has 10000 users, we need a way to paginate as we don't want to return 10000 entries as it would be slow, especially for the UI parts

2017-03-02 10:12 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +					$shareTypes[] = $shareType;
@PVince81 we need uniqueness here

2017-03-02 10:17 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +					$shareTypes[] = $shareType;
yes we do

2017-03-02 10:21 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +					$shareTypes[] = $shareType;
Ok, we did with @PVince81 using hashmap and array_keys to do it efficiently

2017-03-03 16:09 UTC, DeepDiver1975 commented
@SergioBertolinSG @PVince81 do we have behat tests for this? if not we need to add them BEFORE this change - THX

2017-03-03 16:14 UTC, mrow4a commented
Results for the PROPFIND query with 1st optimization:

**Case 1**
10 files, having all possible cases for sharing e.g. (folder share, file shares link, link+.., link+group+2xuser+feder)

-45 queries
![selection_030](https://cloud.githubusercontent.com/assets/13368647/23558579/72b72426-0034-11e7-92f7-60ec50e88a7a.jpg)


**Case 2**
-501 queries
![selection_031](https://cloud.githubusercontent.com/assets/13368647/23558688/cae8f7c8-0034-11e7-8e33-4f1c65e97382.jpg)

100 NON-SHARED files, just someone uploaded 100 files to the folder

If all checks pass, please switch to review @DeepDiver1975 @PVince81

2017-03-03 16:45 UTC, mrow4a commented
@DeepDiver1975 Yes, please test it, later I will write more unit tests to check more cases e.g IN() chunking .

2017-03-06 07:52 UTC, SergioBertolinSG commented
> @SergioBertolinSG @PVince81 do we have behat tests for this? if not we need to add them BEFORE this change - THX

What are the approximate steps here?

2017-03-06 08:48 UTC, PVince81 commented
Steps:

1. Login as user user1
1. Share with user/group/link
1. PROPFIND with the "oc:share-types" property, verify that the value matches the share types

The share types are unique, so if the user had two outgoing user shares, the type "user" only appears once. This field is used for the web UI to display the correct share status icon in each file row.

2017-03-06 10:16 UTC, PVince81 reviewed
Great progress!

2017-03-06 10:16 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +				array_push($nodeIdsArray, $nodeId);
we usually use `$nodeIdsArray[] = $nodeId;`. not sure if this makes a difference performance-wise

2017-03-06 10:16 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +				array_push($nodeIdsArray, $nodeId);
we usually use `$nodeIdsArray[] = $nodeId;`. not sure if this makes a difference performance-wise

2017-03-06 10:16 UTC, PVince81 commented on lib/public/Share/IManager.php
>  	 * Get shares shared by (initiated) by the provided user.
Adjust to say `Get ALL shares`

2017-03-06 10:16 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +			$this->getNodesShareTypes($nodeIdsArray);
A get function that doesn't return anything. this will likely confuse other developers. Please make that function return something.

2017-03-06 10:16 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +				$shareTypesHash = $this->cachedShareTypes[$nodeId];
Don't use the cache directly here and rely on the function doing that for you.
```php
$shareTypesHash = $this->getNodesShareTypes([$nodeId]);
```

2017-03-06 10:16 UTC, PVince81 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		$qb->andWhere($qb->expr()->in('file_source', $qb->createParameter('file_source_ids')));
We will need chunking here with `array_chunk` (because some databases have a max limit for their `IN` operator...). See how it's done here: https://github.com/owncloud/core/blob/v9.1.4/lib/private/Share20/DefaultShareProvider.php#L930

2017-03-06 10:55 UTC, mrow4a commented
@SergioBertolinSG I will today give you a full script to test it, initializing users/shares and profiling this etc.

2017-03-06 10:59 UTC, mrow4a commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		$qb->andWhere($qb->expr()->in('file_source', $qb->createParameter('file_source_ids')));
I did chunking in different part of the code, in Manager

2017-03-06 11:01 UTC, PVince81 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		$qb->andWhere($qb->expr()->in('file_source', $qb->createParameter('file_source_ids')));
What if another part of code written by a future dev calls `getAllSharesBy` ? It is better if chunking is done inside this to avoid every API consumer to have to think of doing chunking (which is likely to be duplicate code, if not forgotten)

2017-03-06 12:33 UTC, SergioBertolinSG commented
@PVince81 there are already tests about this:

https://github.com/owncloud/core/blob/master/tests/integration/features/webdav-related.feature#L301-L372

2017-03-06 12:40 UTC, mrow4a commented
Ok Vincent I will add the code style you require and let's change label to review so they can test it

2017-03-06 13:07 UTC, PVince81 commented
@SergioBertolinSG thanks for the info, that's perfect.

2017-03-06 16:14 UTC, mrow4a commented
@SergioBertolinSG https://github.com/owncloud/automated-tests/pull/47

2017-03-06 17:29 UTC, mrow4a commented
@PVince81 please review fixes and decide about changing to Review and get it tested on real sized DB? @SergioBertolinSG @SamuAlfageme

2017-03-06 18:02 UTC, PVince81 commented
rebase onto master to get rid of that JS failure

2017-03-06 18:16 UTC, mrow4a commented
@PVince81 Did that and no hope. Still some strange thing.

2017-03-06 18:21 UTC, PVince81 commented
Ok, so this means that this.data **is** defined but it has no function `state`... I'll push another PR to limit that. This is a random unexplainable failure.

2017-03-07 07:54 UTC, PVince81 commented
now the test failures are related to your changes

2017-03-07 08:52 UTC, mrow4a commented
We should probably also smashbox this PR against all tests, especially share related.

2017-03-07 10:20 UTC, mrow4a commented
@DeepDiver1975 @PVince81 Please change flag to review to indicate the PR is ready

2017-03-07 10:23 UTC, mrow4a commented
@DeepDiver1975 @PVince81 Ok, flag changed, I just need to fullfil last tick:
- integration tests (also smashbox)
- benchmark it on bigger instance

2017-03-07 12:09 UTC, DeepDiver1975 requested changes
I'm not yet sure if all changes to the unit tests are valid .... I need to have a closer look

2017-03-07 12:09 UTC, DeepDiver1975 commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
> +			$receiver = strval($i)."user2@server.com";
"$iuser2@server.com"

2017-03-07 12:09 UTC, DeepDiver1975 commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
> +		for($i = 0; $i < 200; $i++) {
why do you create 200 shared here?

2017-03-07 12:09 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +		$nodeIdsChunks = array_chunk($nodeIDs, 100);
why 100? should be 1000

2017-03-07 12:12 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +				array_push($nodeIdsArray, $nodeId);
Should I change it? isnt it equivalent?

2017-03-07 12:12 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +				array_push($nodeIdsArray, $nodeId);
Should I change it? isnt it equivalent?

2017-03-07 12:13 UTC, mrow4a commented on lib/public/Share/IManager.php
>  	 * Get shares shared by (initiated) by the provided user.
done

2017-03-07 12:14 UTC, mrow4a commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
> +		for($i = 0; $i < 200; $i++) {
To test chunking of Node IDs.

2017-03-07 12:15 UTC, mrow4a commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
> +			$receiver = strval($i)."user2@server.com";
Is it relevant? It is just test.

2017-03-07 12:15 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$nodeIdsChunks = array_chunk($nodeIDs, 100);
I think in other parts of the code we do 100

2017-03-07 13:20 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +			$qb->select('*')
In theory you don't need to rebuild the whole query in this loop, you only need to re-set the value of the `IN` operator.

You can leave this as is now.

2017-03-07 13:23 UTC, PVince81 commented
Code looks good to me now 👍 

According to @SergioBertolinSG we already have integration tests for the "oc:share-types" property so since the tests passed I think this is ready to merge.

It seems obvious to me that the performance will be significantly better and we anyway want this in 10.0. Perf testing can be done with tomorrow's daily after this is merged.

To be discussed: backporting.

@DeepDiver1975 any objections ?

2017-03-07 13:29 UTC, mrow4a commented
General conclusion here is: if you will have questions from customers -> we have function `$folderNode->getDirectoryListing()` which basicaly does query to filecache and returns the nodes. For these nodes, we are queries sharing table. Join here makes no sense because we would redo twice the work, and  `$folderNode->getDirectoryListing()` is necessary from what I can see.

2017-03-07 13:31 UTC, PVince81 commented
@mrow4a I think `getDirectoryListing` here is out of scope for this PR. Please look into it in a separate ticket/PR.

2017-03-07 23:49 UTC, DeepDiver1975 commented on apps/federatedfilesharing/tests/FederatedShareProviderTest.php
> +			$receiver = strval($i)."user2@server.com";
well - as a student you are allowed to learn even from tests :wink:

2017-03-09 10:43 UTC, DeepDiver1975 requested changes

2017-03-09 10:43 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +	 * @param  IShare[] array containing shares
please fix phpdoc

2017-03-09 10:43 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/SharesPlugin.php
> +	 * @param int[] array of folder/file nodeIDs
fix PHPDoc

2017-03-09 10:43 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +	public function getAllSharesBy($userId, $shareTypes, $nodeIDs, $reshares) {
the interface method looks like this

Node $node vs nodeIds - please correct

```php
	/**
	 * Get all shares by the given user for specified shareTypes array
	 *
	 * @param string $userId
	 * @param int[] $shareTypes
	 * @param Node|null $node
	 * @param bool $reshares Also get the shares where $user is the owner instead of just the shares where $user is the initiator
	 * @return \OCP\Share\IShare[]
	 * @since 10.0.0
	 */
	public function getAllSharesBy($userId, $shareTypes, $node, $reshares);

2017-03-10 07:15 UTC, PVince81 commented
Rebased.

Now Jenkins, I know it's Friday, but still please do your job!

2017-03-10 10:26 UTC, merged

2017-03-31 09:05 UTC, PVince81 commented
Backporting would have been nice but there are interface additions which could break.
The only way to backport is to not add the new methods to the interfaces and add a "method_exists" check in the class that would call it and log an error if it doesn't, or fallback to to the old behavior.

@DeepDiver1975 @mrow4a thoughts ?

2017-03-31 09:52 UTC, mrow4a commented
I consider backporting dark magic :>

2019-03-27 22:33 UTC, butonic commented on lib/private/Share20/DefaultShareProvider.php
> +			$qb->select('*')
nope, the andWhere calls will add duplicate where conditions to the query builder.

2019-03-28 01:12 UTC, phil-davis commented
Note: this code is in `stable10` - there is no backport PR. I guess that the "backport" discussion above from 2017 is about backporting to v9.*, and that looks like it did not happen (which is OK).

It looks like there is no "backport to stable10" because the code was already in master at the point where the stable10 branch was created.