upgrade exception printed in red at end of OCC command
owncloud/core pull request #27306
Opened 2017-03-05 11:24 UTC by noveens

## Description

Fixes #26825 

If there is an UpgradeException, the warning messages are printed in RED and also at the end of OCC command.

## Related Issue

https://github.com/owncloud/core/issues/26825

## Motivation and Context

Prints the warning messages at the end of OCC rather than top PLUS in red.

## How Has This Been Tested?

Tested when there's an upgrade exception, and when there's not. 

## Screenshots (if appropriate):
![red](https://cloud.githubusercontent.com/assets/23054294/23586854/4bafd5bc-01c4-11e7-925c-c582550261a7.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@butonic @PVince81

2017-03-06 08:34 UTC, butonic commented
👍 nice!

2017-03-06 11:09 UTC, DeepDiver1975 requested changes

2017-03-06 11:09 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +			    echo "\n\033[01;31mownCloud or one of the apps require upgrade - only a limited number of commands are available \033[0m\n";
Can you please use $output here?
You can get error colors by using the error tag within the symfony console

```php
$output->writeln('<error>foo bar</error>');

2017-03-06 11:09 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +		$this->eventDispatcher->dispatch('upgradeException');
I guess this line is a testing left-over?

2017-03-06 11:09 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
why is there an event dispatcher needed?

2017-03-06 12:03 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher->dispatch('upgradeException');
No, that's neccesary

2017-03-06 12:04 UTC, noveens commented on lib/private/Console/Application.php
> +			    echo "\n\033[01;31mownCloud or one of the apps require upgrade - only a limited number of commands are available \033[0m\n";
eventDispatcher doesn't have a $output param,
Hence I can't call $output->writeln()

2017-03-06 12:05 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
I guess that's the best thing we can implement according to need, 
If you have something better in mind, I would be more than happy to implement the changes :-)

2017-03-06 12:08 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +			    echo "\n\033[01;31mownCloud or one of the apps require upgrade - only a limited number of commands are available \033[0m\n";
```php
$this->eventDispatcher->addListener('upgradeException', function () use ($output) {
    $output->writeln();

2017-03-06 12:09 UTC, noveens commented on lib/private/Console/Application.php
> +			    echo "\n\033[01;31mownCloud or one of the apps require upgrade - only a limited number of commands are available \033[0m\n";
Oh that's great, 
Will push the changes.

Thanks.

2017-03-06 12:09 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
ah - this way you are delaying the printout ....

2017-03-06 12:10 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
Yes, I chose this method.
Is that okay?

2017-03-06 12:20 UTC, noveens commented
@DeepDiver1975 ,
can you please recheck the changes?

Thanks.

2017-03-06 12:22 UTC, DeepDiver1975 commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
I'd simply store a flag in the class as field if the exception was thrown. At the end in a simple if the necessary error output could take place

2017-03-06 12:24 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
@DeepDiver1975 ,

Sure, that would work.
Just thought this would be more cooler ;-)
Re-implementing the fix.

Thanks.

2017-03-06 12:43 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
@DeepDiver1975 ,

the $output turns out to be null after I call application->run( ) , and I can't think of a way to fix that.
Any help is much appreciated.

Thanks.

2017-03-06 14:49 UTC, noveens commented on lib/private/Console/Application.php
> +		$this->eventDispatcher = new EventDispatcher();
@DeepDiver1975 , IMHO we can't access $output after application->run() as it turns out to be null.

Am I going wrong somewhere?

2017-04-03 14:11 UTC, PVince81 commented
@DeepDiver1975 how to move forward with this ?

@noveens there are some conflicts now

2017-04-03 16:33 UTC, noveens commented
@PVince81 ,
I'll have a look at the conflicts.

2017-04-06 18:31 UTC, noveens commented
@PVince81 ,

Surprisingly the tests pass on my system :disappointed: 
I'll try jenkins with a rebase for now.

2017-04-26 09:45 UTC, PVince81 commented
Needs rebase.

If it doesn't work out, let's close to find a better solution in the future... this is low prio stuff

2017-04-26 12:50 UTC, noveens commented
@PVince81 ,
I tried rebasing the PR at a previous stage and that didn't work out.

Closing this PR, since some test "transfer-ownership.transferring ownership fails with invalid source user" is failing, need to think of a better implementation.

2017-04-26 12:50 UTC, closed without merging