Optimize PROPFIND having CommentsApp enabled by default
owncloud/core pull request #27339
Opened 2017-03-08 13:25 UTC by mrow4a

The idea here is to reduce number of O(n) queries coming from each PROPFIND in the web browser for instance with enabled comments app (this is by default). 

Prefetching required data in one query instead of iterative queries should reduce number of queries to O(1), where N is number of files in the folder.

Query 
`SELECT C.object_id, COUNT(C.object_id) FROM oc_comments C WHERE C.object_id IN(?) nodes in specific user folder AND C.object_id NOT IN(SELECT C.object_id FROM oc_comments_read_markers CRM WHERE C.object_id = CRM.object_id AND CRM.user_id = '?' AND CRM.marker_datetime > C.creation_timestamp) GROUP BY C.object_id;` 
does the job very well. Yes, I know it is more OLAP query, but this is what Web Front End is about. This is also most optimal query in our case https://sqlperformance.com/2012/12/t-sql-queries/left-anti-semi-join 

- [x] Finish first optimization
- [ ] Add chunking of IN() query for more NodeIDs to 100
- [ ] Add unit tests for optimization 1
- [ ] Cache `$children = $folderNode->getDirectoryListing();` result which will be exactly the same after finishing SharesPlugin
- [ ] Add unit tests for optimization 2
- [ ] Inform that Comments app is now "usable" for bigger instances @felixboehm @cdamken

2017-03-08 13:30 UTC, mrow4a commented
Case 1
`- 0 queries` - this is worst case because caching of `getDirectoryListing` is not yet done
![selection_039](https://cloud.githubusercontent.com/assets/13368647/23705684/5357aa9e-040b-11e7-8362-4ef48d4641fc.jpg)

![selection_040](https://cloud.githubusercontent.com/assets/13368647/23705709/6ad93bb0-040b-11e7-84f6-249364a684e3.jpg)

Case 2
100 NON-SHARED/SHARED files, just someone uploaded >100 files to the folder
`- 200 queries` - this is best case, however will be highly boosted with caching of `getDirectoryListing` which is not yet done (this is next optimization in this PR)
![selection_041](https://cloud.githubusercontent.com/assets/13368647/23705783/b3df3e9a-040b-11e7-9119-79e38ff9d8cd.jpg)

2017-03-08 13:32 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			$children = $folderNode->getDirectoryListing();
This gets exactly the same result as https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/SharesPlugin.php#L157, so need to be cached, otherwise it is huge overhead

2017-03-08 13:36 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			$children = $folderNode->getDirectoryListing();
@DeepDiver1975 @PVince81

2017-03-10 13:17 UTC, mrow4a commented
@DeepDiver1975 @PVince81 New Benchmark in the top post.. Seems comments app will be fixed now

2017-03-10 13:30 UTC, DeepDiver1975 requested changes

2017-03-10 13:30 UTC, DeepDiver1975 commented on lib/private/Comments/Manager.php
> +	 * @param $objectType string the object type, e.g. 'files'
should be

```php
@param string $objectType the object type, e.g. 'files'

2017-03-10 13:30 UTC, DeepDiver1975 commented on lib/private/Comments/Manager.php
> +	 * @param int[] NodeIDs that may be returned
phpdoc

2017-03-10 13:30 UTC, DeepDiver1975 commented on tests/lib/Comments/ManagerTest.php
> +		$user1 = $this->createMock('\OCP\IUser');
better use
```php
IUser::class

2017-03-12 11:29 UTC, mrow4a commented
@butonic Jorn, do you know which part of the querybuilder for ORACLE could cause error below in https://github.com/owncloud/core/blob/4e84cd2dd2b849dfe55ec3235e640f34582c6f68/lib/private/Comments/Manager.php#L389 ? 

![selection_059](https://cloud.githubusercontent.com/assets/13368647/23831347/8d89433c-071f-11e7-8953-651075218112.jpg)

I have problems spotting an issue

2017-03-12 11:36 UTC, butonic commented
It seens object_id is not always escaped.

2017-03-12 11:38 UTC, butonic commented
Try using an alias for c.object_id. Especially in The count function.

2017-03-12 12:19 UTC, mrow4a commented
@PVince81 @DeepDiver1975 Covered will unit tests and checked manually. To review

2017-03-12 12:22 UTC, butonic commented
C and CRM are not a problem, as long as they are consistently escaped or not escaped. In contrast to mysql, postgres or sqlite oracle uppercases unquoted identifiers.

2017-03-12 12:53 UTC, butonic commented on lib/private/Comments/Manager.php
> +			$qbMain->selectAlias('object_id', 'id')->selectAlias($qbMain->createFunction('COUNT(object_id)'), 'count')
`>createFunction('COUNT(id)'),` you created an alias. try using it in the count

2017-03-12 18:13 UTC, mrow4a commented
Jenkins error?

![selection_061](https://cloud.githubusercontent.com/assets/13368647/23834509/ede14e36-0757-11e7-8796-64104b9a58a9.jpg)

2017-03-12 19:03 UTC, butonic commented
The mysql docker seems dead?

2017-03-13 11:45 UTC, mrow4a commented
@DeepDiver1975 @PVince81 Tests are passing, what do we do with it? Travis?

2017-03-13 14:36 UTC, mrow4a commented
@DeepDiver1975 @PVince81 This PR is ready from my side. All checks passing.

2017-03-14 08:21 UTC, jvillafanez commented on lib/private/Comments/Manager.php
> +				->andWhere($qbMain->expr()->eq('c.object_id', 'crm.object_id'));
I'm not sure if it's better to move the `$qbSup` above the `$qbMain`, or just add a blank line to separate lines 411 and 412.

Right now, we have actions for the main query, then switch to the subquery, and finally we go back to the main query. That's not common in this code base as far as I know. In addition, there is no separation between lines 411 and 412, so it's easy to get confused and think that the expressions below (at least 412 and 413) target the subquery instead of the main query.

2017-03-14 08:21 UTC, jvillafanez commented on lib/private/Files/Node/Folder.php
> +			$folderContent = $this->view->getDirectoryContentFromCache($this->path);
Should we fallback to the original if the contents aren't cached?

2017-03-14 08:21 UTC, jvillafanez commented on lib/private/Files/Node/Folder.php
> +			return $this->root->getCached($this->getFullPath($path));
Same as above

2017-03-14 08:21 UTC, jvillafanez commented on lib/public/Comments/ICommentsManager.php
> +	 * @return int[] $unreadCountsForNodes hash table
It might need a better explanation. Does it returns something like `[1,2,3,4]`? or `['1','2','3']`? or `['abc' => 1, 'bcd' => 3]`?
A small example with what is expected to return might be enough.

2017-03-14 09:28 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +		$this->userFolder = $userFolder;
SharesPlugin is doing the same. If you want to get it from userSession, it is call to DB. You would need to do that separately for each plugin, generating redundant call to DB. You can write another PR removing user folder from plugins, cache user folder in userSession so that it hits the cache.

2017-03-14 09:30 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			&& !is_null($propFind->getStatus(self::PROPERTY_NAME_UNREAD))) {
I dont see a reuse here for two separate functions.

2017-03-14 09:32 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			$folderNodeID = intval($folderNode->getId());
Hmm, will check that, maybe you are right, node should return INT

2017-03-14 09:34 UTC, mrow4a commented on lib/private/Files/Node/Folder.php
> +			$folderContent = $this->view->getDirectoryContentFromCache($this->path);
This flag is more about if to get it from cache or explicitly call. If programmer knows that it can safely take it from cache, you have an option

2017-03-14 09:37 UTC, mrow4a commented on lib/private/Files/Node/Folder.php
> +			return $this->root->getCached($this->getFullPath($path));
As above

2017-03-14 09:38 UTC, mrow4a commented on lib/private/Files/Node/Folder.php
> +			$folderContent = $this->view->getDirectoryContentFromCache($this->path);
However I think I understand your confusion. The idea here is that it is not aware if this is in cache or not, but will try to hit the cache.

2017-03-14 12:38 UTC, mrow4a commented on lib/private/Comments/Manager.php
> +				->andWhere($qbMain->expr()->eq('c.object_id', 'crm.object_id'));
Separated. I created this logic as I were writing this query "by hand", having inner select

2017-03-14 15:17 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +		$this->userFolder = $userFolder;
Maybe the userSession should cache that call in order to not hit the DB twice or more... I guess we'll have to leave it as technical debt because changing it here is outside of scope.

2017-03-14 15:37 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			&& !is_null($propFind->getStatus(self::PROPERTY_NAME_UNREAD))) {
This is completely a personal opinion: big functions make the code more difficult to read. Python code style guides recommend a maximum of 50 lines per function; if your function is bigger maybe you need to refactor that function or split it into smaller parts.
My point is that, taking into account that there are at least 2 big parts in this function and that the function is already big, we can extract a couple of functions from this one to reduce the size.

There is another reason to simplify this: we're caching data into the `$this->numberOfCommentsForNodes` variable, which is fine, but it isn't clear who's reponsible to handle that variable.

2017-03-14 15:42 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			&& !is_null($propFind->getStatus(self::PROPERTY_NAME_UNREAD))) {
Honestly I followed the code style enforced by how plugins were written e.g. SharePlugin. Problem is handle () function in there and the method you see there is kind of "main". I am also not so happy with it but we would need to refactor also SharePlugin, next PR?

2017-03-14 15:43 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +		$this->userFolder = $userFolder;
True but this is also optimization for other PR this is already pretty big

2017-03-14 15:44 UTC, jvillafanez commented on lib/private/Comments/Manager.php
> +				->andWhere($qbMain->expr()->eq('c.object_id', 'crm.object_id'));
Could we sneak a blank line between lines 402 and 403?
```
				->andWhere($qbMain->expr()->eq('c.object_id', 'crm.object_id'));

			$qbMain->setParameter('crm_user_id', $user->getUID(), IQueryBuilder::PARAM_STR);
```

2017-03-14 15:47 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +		$this->userFolder = $userFolder;
👍

2017-03-14 15:48 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php
> +			&& !is_null($propFind->getStatus(self::PROPERTY_NAME_UNREAD))) {
👍

2017-03-14 16:01 UTC, mrow4a commented
Do we have behavioural tests for comments? Better AI test it @jvillafanez

2017-03-20 08:28 UTC, mrow4a commented
@jvillafanez Any new input on this PR? Does CommentsApp have integration tests?

2017-03-20 14:46 UTC, PVince81 commented
@mrow4a yes:
```
± % grep -lrie comment tests/integration 
tests/integration/config/behat.yml
tests/integration/features/bootstrap/CommentsContext.php
tests/integration/features/comments.feature
tests/integration/features/provisioning-v1.feature
```

2017-03-20 14:52 UTC, PVince81 commented
Looks like the comments integration tests are only for the comments Webdav endpoint but not for the files endpoint.

Tests are missing for the property "oc:comments-count", "oc:comments-unread", "oc:comments-href".

@mrow4a please work with @SergioBertolinSG to get some tests for this added.
The tests should have users sharing a file, one user adding a comment and the other user retrieving the above properties on directly that file.
Then do the same with "Depth: 1" on the parent folder to test the pre-fetching code path.

You can run the integration tests with these commands:
```
% cd tests/integration
% sudo -u wwwrun ./run.sh features/comments.feature
```
(you can also add line number of the scenario "comments.feature:191".

2017-03-21 08:05 UTC, SergioBertolinSG commented
@PVince81 @mrow4a Ok.

2017-03-22 10:20 UTC, jvillafanez commented
No more changes from my side.

2017-03-22 10:41 UTC, PVince81 commented
@SergioBertolinSG is working on comments tests separately, merging this.

👍

2017-03-22 10:42 UTC, merged