Optimize resolveGroupShare
owncloud/core pull request #27434
Opened 2017-03-20 16:32 UTC by mrow4a

This optimizes the case in which you do PROPFIND to some folder, in which you had group share, and that share was moved to another folder (generaly people reorganise staff from root folder to their required folders)

- [ ] Unit tests
- [ ] Verify integration tests

![selection_100](https://cloud.githubusercontent.com/assets/13368647/24110190/1557df20-0d93-11e7-9399-d2feb2cf6192.jpg)
Below is what happens when you move file `testgrshare.txt` which has some group shares receiver/send to another folder and then propfind the "old" root folder:
![selection_098](https://cloud.githubusercontent.com/assets/13368647/24110232/2fd3af78-0d93-11e7-8443-1404217ee836.jpg)

2017-03-20 17:12 UTC, mrow4a commented
@DeepDiver1975 @SergioBertolinSG @PVince81 Do we have integration for this scenario of moving group share to other folder, group share folder, fed share whatever?

2017-03-21 07:42 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +	 * Returns in the array both the updated share if one was found and for not found in DB passing predicate, the original shares.
mind clarifying what you mean with "updated share" and "original share" ?

Do you mean that "original share" is the actual group share and "updated share" is the user-specific special entry ?

2017-03-21 07:44 UTC, SergioBertolinSG commented
@mrow4a There are quite a few int. tests about sharing, perhaps the test you are looking for is this one https://github.com/owncloud/core/blob/master/tests/integration/features/sharing-v1.feature#L522 .

If you miss some specific case, please tell me / open a ticket in QA repo.

2017-03-21 09:22 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +	 * Returns in the array both the updated share if one was found and for not found in DB passing predicate, the original shares.
Hmm, ok, I should say resolved :>

2017-03-21 10:08 UTC, DeepDiver1975 requested changes

2017-03-21 10:08 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +	 * Returns in the array both the updated share if one was found and for not found in DB passing predicate, the original shares.
an the line is too long - 80 chars please

2017-03-21 10:08 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +		$shareParentIds = array_keys($parentIdToShareMap);
chunk to 1000 max?

2017-03-21 10:12 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$shareParentIds = array_keys($parentIdToShareMap);
Good point

2017-03-21 15:58 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +		$parentIdToShareMap = [];
Rename to `shareIdToShareMap` or simply `sharesMap` ? Because it seems that's what it is.
It can of course be used to resolve parents but that's only one possibility
The "parent" bit confused me.

2017-03-21 15:59 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +		$shareParentIds = [];
I have trouble understanding the chunking part, it seems this array stores chunks so call it something with "chunk" in its name. See comment below to possibly avoid saying "parent".

2017-03-21 16:00 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +			$shareParentIds[$chunkId][] = $parentId;
Can you explain the chunking part with code comments ?

It seems it's basically just building a chunked array of share ids ?
The "parent" part in the name makes it more confusing, I suggest removing it.

`$parentId` is just `$shareId`.

2017-03-21 16:04 UTC, PVince81 commented
@mrow4a code looks good. Took me a while due to the variable names confusing me.
Please adjust.

2017-03-21 16:04 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +			$shareParentIds[$chunkId][] = $parentId;
yep, it just optimised for this case array_chunk, avoiding unnecessary loops.

2017-03-21 17:36 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
Move this to another function so we can unittest it?

2017-03-21 17:36 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
is the `array_values` needed?

2017-03-21 17:36 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +				throw new \Exception("ResolveGroupShares() returned wrong result");
Any other better exception that we could throw here? I'm not fan of throwing plain exceptions

2017-03-21 18:03 UTC, DeepDiver1975 requested changes

2017-03-22 09:33 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +				throw new \Exception("ResolveGroupShares() returned wrong result");
We already throw this exception in the code in other point.

2017-03-22 09:36 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
I did unit tests it

2017-03-22 09:37 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
https://github.com/owncloud/core/pull/27434/files#diff-88730505cd190b0b2f8b43ded358feb9R1144 and did it already

2017-03-22 09:39 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Hmm good question, how array merge will handle it in upper layer. This is basicaly converting from map to classical array, which is used in upper layer

2017-03-22 09:43 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +				throw new \Exception("ResolveGroupShares() returned wrong result");
Will use @throws ProviderException

2017-03-22 12:34 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
This part of code involves chunking the shares list, which isn't related to the DB access that the rest of the function perform. That another reason to extract this piece out.

2017-03-22 12:34 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
`$shareId = $data['parent'];` I guess this won't be unqiue, will it? But if it won't be unique, the check above (`if (isset($shareIdToShareMap[$shareId]))`) could be problematic.... I need some light there.

2017-03-22 13:07 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
I have no idea what you want to achieve here

2017-03-22 13:19 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Parent is basicaly unique share ID. It is needed to track received shares moved over user folders, as in the picture in the first post. Below are DB entries to enlighten you. 


![selection_106](https://cloud.githubusercontent.com/assets/13368647/24199546/44312dc4-0f0a-11e7-96f4-5bf279359d86.jpg)

2017-03-22 13:38 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
> I need to contruct $shareIdToShareMap and $chunkedShareIds

My point is that another private function could take care of the chunking in order to make this function  to focus on fetching the data from the DB. It's fine if this function calls the "chunking function" and then fetch the data.

2017-03-22 13:40 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
but there could be several entries with the same parent.... that's what worries me.

2017-03-22 14:10 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Hmm, ok, I think you are right, will add a key unique. Makes sense.

2017-03-22 14:12 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Unit test for that? Any test plan?

2017-03-22 14:14 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
This function would need to return 4 variables, 2 int and 2 arrays...

2017-03-22 14:15 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
Ok, will try it and see how it looks like. But I get your point.

2017-03-22 14:41 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
I think this is what we are searching for https://github.com/owncloud/core/blob/master/lib/private/Share20/Share.php#L109

2017-03-22 15:26 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Each child entry with the same parent should only has a unique share_with user target, so it should be fine. I'm not aware of any case where the user might appear twice, that would likely be a bug.

2017-03-22 15:36 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Yep, I cannot also find a case how to "copy" share though

2017-03-22 15:41 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
@jvillafanez Addressed this in the commit

2017-03-22 16:06 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
I am discussing this with @cdamken lets see what comes out

2017-03-22 16:24 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
Ok we tried things and seems impossible

2017-03-22 16:43 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		foreach($shares as $share) {
:+1:

2017-03-22 16:55 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
If consider the parent will be unique, I think it's better to make the consideration all the way through, so if the assumption is wrong 💥 and 🚑 , otherwise it will be a pain to debug what's going on.

So, the key of the `$shareIdToShareMap` map will be unique and the `array_merge` (without the `array_values`) shouldn't be a problem. The only question is if those keys are used in any other place, if not we could ignore the `array_values`

2017-03-22 16:59 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
But how would you protect that?

2017-03-22 17:08 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +					throw new ProviderException('Parent of share should be unique');
@jvillafanez I think this should be what you wanted to achieve

2017-03-22 17:16 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +					throw new ProviderException('Parent of share should be unique');
👍

2017-03-22 17:20 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$resolvedShares = array_values($shareIdToShareMap);
ok, fair enough. Maybe something to check in the future. Anyway 👍

2017-03-22 17:22 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +				}else {
sneak a whitespace here?

2017-03-22 17:25 UTC, jvillafanez commented
The code is fine for me, just https://github.com/owncloud/core/pull/27434#pullrequestreview-28452950 , but unless there is any other change I don't think it's worthy.
👍 for the code.

2017-03-23 08:37 UTC, mrow4a commented
I think I addressed the reviewed code @DeepDiver1975 any ideas?

2017-03-23 19:36 UTC, PVince81 commented
:+1: from me as well, code is well more readable now.

2017-03-23 19:36 UTC, merged

2017-04-24 11:44 UTC, PVince81 commented
Not sure if we should backport this, it's a huge change and a bit risky. Needs proper retesting.

Thoughts ?

@cdamken @DeepDiver1975

2017-04-24 15:36 UTC, cdamken commented
Long story short:

The patch was sent to the customer because it looks like the fixes the issue.
The customer have 9.1.4 
The patch was applied.
The problem was fixed by the customer.

I'm not sure if cherry pick will work, but anyhow the solution works for master and 9.1.4 too.

2017-05-23 15:02 UTC, tomneedham commented
Agreed to not backport due to the risk. Advise to update to 10 or can provide this patch to other customers on 9.1.4 if they really want - with the risk that comes with it.

2017-05-23 17:17 UTC, cdamken commented
Ok, I asked to upgrade to 10.