Optimize join for sharedWith by moving logic to DB
owncloud/core pull request #27436
Opened 2017-03-20 16:46 UTC by mrow4a

This best case gets rid of doubled queries `$shares, $this->shareManager->getSharedWith` for both GROUP and USER shares, as in the PR body. Currently, if there are both user and group shares, we need to do 2 queries. With this PR, if we have both group and user shares, we need to do 1 query. If we have only user shares, old and new implementation will do 1 query per user. 

![selection_102](https://cloud.githubusercontent.com/assets/13368647/24110812/c442a988-0d94-11e7-9df2-d6f3293d39ee.jpg)

Anyways, it is big win, since this query does... 2 Left Joins! These are very expensive operations in DBMS for enterprise scale tables. 

- [ ] Unit tests 
- [ ] Need to use $this->resolveGroupShare https://github.com/owncloud/core/pull/27434

2017-03-21 18:37 UTC, PVince81 commented on lib/public/Share/IShareProvider.php
> +	 * Get shared with the given user for shares of all available types for this share provider within all nodes
what do you mean with "within" ? do you mean "for all given nodes including their subnodes" ? (and not strictly for the given nodes)

2017-03-21 18:38 UTC, PVince81 commented on apps/files_sharing/lib/MountProvider.php
> +		$requiredShareTypes = [\OCP\Share::SHARE_TYPE_USER, \OCP\Share::SHARE_TYPE_GROUP];
ah, indeed that makes sense

2017-03-21 18:39 UTC, PVince81 commented on lib/public/Share/IShareProvider.php
> +	 * Get shared with the given user for shares of all available types for this share provider within all nodes
hmm and `$node` is singular, not plural but your PHPDoc talks about "all nodes".

Please clarify and adjust the parameter name if applicable.

2017-03-21 18:42 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +		$allGroups = $this->groupManager->getUserGroups($user, 'sharing');
not sure if passing "sharing" here is correct.

@IljaN could mess up with the guest users ?
Some context: this function is called when retrieving the list of shares for which a SharedMount needs to be setup for the recipient. From my understanding passing "sharing" here risks excluding guest users and those users wouldn't see their received shares mounted.

Needs testing...

2017-03-21 18:42 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +		$allGroups = $this->groupManager->getUserGroups($user, 'sharing');
ah never mind, it's late... this was copied from the old code that already works https://github.com/owncloud/core/pull/27436/files#diff-83377463cf0d718950be360f7fcabd50L710

2017-03-21 18:46 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
this will boom boom 💥 💥 if there are users and groups with the same names, say a group called "meow" and also a user called "meow" (yes, I've seen such setups before (well, setups with both user and group called the same, not setups with "meow"))

2017-03-21 18:48 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
please make sure to add a test for this, test first FTW 😉

2017-03-21 18:49 UTC, PVince81 commented
Apart from the "meow" issue (see comments), the code looks good overall.

2017-03-22 09:24 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
Hmm, why, these are two separate shares of different types, isnt it? I will try it out though in unit test, good point!

2017-03-22 09:39 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
Yes, they might be different types.

But say if there is a crazy scenario where user "user1" is in the group "meow".
With this query you'd also select the incoming shares for the user "meow" which is wrong.

The way I see the query like: `and ((share_type = GROUP and share_with in ($userGroups) or (share_type = USER and share_with = $userId))`

2017-03-22 09:52 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
Hmm, this will slow down the query, will check if this scenario really does not work with the query I implemented.

2017-03-22 10:19 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
Yep, boom booms, will write unit test protecting this case and apply a bit slower query if there are any groups

2017-03-22 10:27 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +				$sharedWithUserOrGroupChunk,
Yeah, if the user is not member of any groups you could just discard the group filter bit completely.

2017-03-22 13:28 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +			$qb->where($qb->expr()->in(
any reason to not keep the chained calls? I mean:
```
$qb->select(....)
  ->selectAlias(....)
  ->from(...)
  ->leftJoin(...)
  ->leftJoin(...)
  ->where(....)
  ->andWhere(...)
```
unless there is a conditional clause that needs to be inserted in the middle, I think it's better this way. If the condition can be moved to the end without harming the performance, I'd move it. If the conditional clause have to be inserted in the middle, then there is no other choice.

2017-03-22 13:28 UTC, jvillafanez commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +	public function getAllSharedWith($userId, $shareTypes, $node) {
I think a comment about why `$sharetypes` is being ignored here is needed. I pass some share types and not only it ignores them, but also uses another type. My first thought is "this is wrong"

2017-03-22 13:28 UTC, jvillafanez commented on lib/public/Share/IManager.php
> +	 * @param int[] $shareTypes
This might need a better explanation... If some constants are expected, either list them or point the user to where the constants are.

2017-03-23 16:27 UTC, DeepDiver1975 requested changes

2017-03-23 16:27 UTC, DeepDiver1975 commented on apps/federatedfilesharing/lib/FederatedShareProvider.php
> +		$this->getSharedWith($userId, self::SHARE_TYPE_REMOTE, $node, -1, 0);
missing return? there is also no unit test on this I assume

2017-03-23 16:27 UTC, DeepDiver1975 commented on lib/private/Share20/Manager.php
> +		$shares = array();
```php
[]

2017-03-23 16:27 UTC, DeepDiver1975 commented on lib/public/Share/IManager.php
> +	 * @param \OC\Share\Constants[] $shareTypes
OC namespace in an OCP interface? NO

2017-03-23 16:27 UTC, DeepDiver1975 commented on lib/public/Share/IManager.php
> +	 * @param Node|null $node
add this to the argument declaration

2017-03-23 16:27 UTC, DeepDiver1975 commented on lib/public/Share/IShareProvider.php
> +	 * @param \OC\Share\Constants $shareType
:-1: you cannot change the definition of a public api

2017-03-23 16:27 UTC, DeepDiver1975 commented on tests/lib/Share20/ManagerTest.php
> +		$user = $this->createMock('\OCP\IUser');
IUser::class

2017-03-28 07:21 UTC, PVince81 commented
conflicts and comments to be resolved

2017-03-28 10:05 UTC, mrow4a commented
Ready for review.

2017-03-28 10:24 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb->expr()->andX(
you could have stored these in variables `$usersCondition` and `$groupCondition` to avoid duplicating the code here and in the block below

2017-03-28 14:35 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb->expr()->andX(
I changed queries a little and not applicable now

2017-03-29 07:55 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		$sharedWithGroup = array_map(function(IGroup $group) { return $group->getGID(); }, $allGroups);
Adjust code style here:
```
$sharedWithGroup = array_map(function(IGroup $group) {
  return $group->getGID();
}, $allGroups);
```

2017-03-29 07:55 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +			$qb = $this->dbConn->getQueryBuilder();
Could we move all the DB logic to another function?

2017-03-29 07:55 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +			array_push($providerIdMap[$providerId], $shareType);
I think unless you're pushing several items, `$providerIdMap[$providerId][] = $shareType` might perform better, and also is consistent with the rest of the code.

2017-03-29 07:57 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		$sharedWithGroup = array_map(function(IGroup $group) { return $group->getGID(); }, $allGroups);
Honestly, I adjusted to the one which is in the "original function getSharedWith" :> Question means which is "code style" :D

2017-03-29 21:01 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +			$qb = $this->dbConn->getQueryBuilder();
Done

2017-03-29 21:02 UTC, mrow4a commented
Could we have more of these tests? https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/apps/files_sharing/tests/EtagPropagationTest.php

E.g. for GROUPs etc? @SergioBertolinSG

2017-03-30 00:38 UTC, mrow4a commented
In other PR this error also appeared, no idea how this PR and other can be ralated to some external storage? @butonic 

![selection_124](https://cloud.githubusercontent.com/assets/13368647/24482500/f2fdda40-14f1-11e7-8f7d-d231b3e472c0.jpg)

2017-03-31 07:27 UTC, jvillafanez commented
I'm not sure if we can simplify more the `getChunkedAllSharedWith` call, the logic seems complex.

Anyway, 👍 for the code.

2017-03-31 09:04 UTC, mrow4a commented
@jvillafanez Yep, my goal here was to avoid as much unnecessarily loops as possible in the code. If the requirement will be to simplify the code, it will be on cost of at least 1-2 more loops over the arrays.

2017-04-11 16:02 UTC, PVince81 commented
@mrow4a write the tests yourself if possible, if you think something is missing.

Also QA can only help or assist with integration tests, not unit tests

2017-05-23 20:10 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +	public function getSharedWithUserQuery($userId, $node) {
Created separate function to create query for user shares

2017-05-23 20:11 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +	public function getSharedWithGroupQuery($groups, $node) {
Created separate function to create query for group shares

2017-05-23 20:11 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +	public function getSharedWithUserGroupQuery($groups, $userId, $node) {
Created separate function to create query for both group and user shares

2017-05-30 12:07 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb = $this->getSharedWithUserGroupQuery($groups, $userId, $node);
I don't understand this. Why the first chunk always calls this one function but other chunks the other one ? What happens if there are more than 100 in a chunk ?

What magic guarantees that the first chunk is only about users ?

Either change the code to be more readable or adjust PHPDoc to explain why and avoid future confusion

2017-05-30 12:07 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb = $this->getSharedWithUserGroupQuery($groups, $userId, $node);
or don't cheat and use two arrays, one for users and one for groups instead of putting both in one and using the first chunk with a special meaning

2017-05-31 10:45 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb = $this->getSharedWithUserGroupQuery($groups, $userId, $node);
The idea here is that if there are both user sharess and group shares, dont do 2 queries, do one as above. 

In case of chunks, you only to get user shares only once, you dont need to do that for each chunk, this is why with each next chunk you dont fetch user, but only groups.

2017-07-04 12:59 UTC, PVince81 commented on lib/private/Share20/DefaultShareProvider.php
> +					$qb = $this->getSharedWithUserGroupQuery($groups, $userId, $node);
are these two scenarios this covered by unit tests / integration tests ? if yes then I'm fine...

2017-07-27 20:23 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +			$userSharesRetrieved = false;
@PVince81 is it clearer now?

2017-07-27 20:23 UTC, mrow4a commented
@jvillafanez @PVince81 @DeepDiver1975 more ready it wont be :>

2017-07-28 06:47 UTC, jvillafanez commented
I have nothing against 👍

2017-07-28 08:57 UTC, PVince81 commented
Thanks! Please backport to stable10.

2017-07-28 08:57 UTC, merged

2017-07-28 09:22 UTC, mrow4a commented
Never backported in my life, so how to do that properly? I need to patch stable10 with this commit? Cherry-pick ?

2017-07-28 09:24 UTC, PVince81 commented
@mrow4a branch off stable10, cherry-pick, retest, then send a PR with target stable10