No longer show the version number in the public
owncloud/core pull request #27473
Opened 2017-03-23 15:41 UTC by DeepDiver1975

## Description
Don't expose server version

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-03-23 18:37 UTC, PVince81 commented
This will likely break federated sharing because federated sharing current contains a hack that checks if the remote instance is an ownCloud instance by pinging the status.php or to see if the instance is up after getting a 404/403 from a regular endpoint. I'm not sure is such calls are authenticated.

2017-03-23 18:38 UTC, PVince81 commented
```
apps/files_sharing/lib/Controllers/ExternalSharesController.php|135| $this->testUrl('https://' . $remote . '/status.php', true)
apps/files_sharing/lib/Controllers/ExternalSharesController.php|141| $this->testUrl('http://' . $remote . '/status.php', true)
apps/files_sharing/lib/External/Storage.php|255| || $this->testRemoteUrl($this->remote . '/status.php');
apps/files_sharing/lib/External/Storage.php|296| if(defined('PHPUNIT_RUN') || !$this->testRemoteUrl($this->getRemote() . '/status.php')) {
apps/federation/lib/TrustedServers.php|222| $url . '/status.php',
apps/federation/tests/TrustedServersTest.php|283| $this->httpClient->expects($this->once())->method('get')->with($server . '/status.php')
apps/federation/tests/TrustedServersTest.php|320| $this->httpClient->expects($this->once())->method('get')->with($server . '/status.php')
lib/private/Setup.php|460| $content .= "\n  RewriteCond %{REQUEST_FILENAME} !/status.php";
core/js/maintenance-check.js|1| // Check every 20 seconds via status.php if maintenance is over
core/js/maintenance-check.js|6| request.open("GET", OC.webroot+'/status.php', true);
```

2017-03-24 07:37 UTC, davivel commented
This breaks log-in with mobile apps and probably desktop client. Requires immediate patch-and-release.

@felixboehm , is this still in discussion or we'll be in OC 10.0 at any cost?

cc @michaelstingl , @nasli , @jesmrec , @davigonz

2017-03-24 07:42 UTC, nasli commented
On iOS app to validate the url we only check for "installed" parameter in status.php. You can log in but the server will have the wrong features supported by the server

To update the features supported(capabilities,cookies,forbiddencharacters,FedShares),  it is used "version" parameter.

2017-03-27 10:06 UTC, felixboehm commented
There is some danger and we need to be fast. Make it a config option.

2017-03-27 13:34 UTC, DeepDiver1975 commented
> Make it a config option.

done @felixboehm @PVince81 @guruz @davivel @nasli

2017-03-29 08:20 UTC, davivel commented
So, if configuration is "don't hide status.php", nothing changes.

If configuration is "hide it", status.php is accessible but shows no info? Sorry, my server side understanding... you know...

2017-04-03 09:20 UTC, PVince81 commented on config/config.sample.php
> + * can be a legitim step. Please condult the documentation before enabling this.
"legitimate"

"condult" => "consult"

2017-04-03 09:22 UTC, PVince81 commented on core/js/config.php
> +if (OC_User::getUser() === null) {
This page returns some config settings that might be used by some JS code in the public link page for example (ex: heartbeat interval).
Might need to split this page into two, one for the login-only settings and one for the generic settings.

2017-04-12 08:26 UTC, michaelstingl commented
What is the status here? (client and mobile development/qa depend on it)

2017-04-12 09:33 UTC, PVince81 commented on core/js/config.php
> +if (OC_User::getUser() === null) {
I wanted to test this... Even when not logged in, config.php (aja oc.js) is still loaded in a public link page.

This `if` statement doesn't work because `getUser()` returns `false`... If I fix it then it breaks the public link page when not logged in. Breaks because the public link page needs access to several JS variables provided by this, like theme information, some app configs, etc.

If we want to move forward with this PR I suggest we discard this change in core/js/config.php.

@DeepDiver1975 agree ?

2017-04-12 11:12 UTC, DeepDiver1975 commented on core/js/config.php
> +if (OC_User::getUser() === null) {
I did not observe issue while testing. What scenarios do you have in mind?

2017-04-12 11:18 UTC, DeepDiver1975 commented on core/js/config.php
> +if (OC_User::getUser() === null) {
I'll take care .... pushing ....

2017-04-12 12:05 UTC, DeepDiver1975 commented
> What is the status here? (client and mobile development/qa depend on it)

ready for the final review and can be merged for oc10 from my pov

2017-04-12 13:25 UTC, guruz requested changes
👎 

```
04-12 15:24:10:906 1562546 OCC::JsonApiJob::finished: "{\"ocs\":{\"meta\":{\"status\":\"ok\",\"statuscode\":100,\"message\":\"OK\",\"totalitems\":\"\",\"itemsperpage\":\"\"},\"data\":{\"version\":{\"major\":10,\"minor\":0,\"micro\":0,\"string\":\"10.0.0 beta2\",\"edition\":\"Community\"},\"capabilities\":{\"core\":{\"pollinterval\":60,\"webdav-root\":\"remote.php\\/webdav\",\"status\":{\"installed\":\"true\",\"maintenance\":\"false\",\"needsDbUpgrade\":\"false\",\"version\":\"\",\"versionstring\":\"\",\"edition\":\"\",\"productname\":\"\"}},\"dav\":{\"chunking\":\"1.0\"},\"files_sharing\":{\"api_enabled\":true,\"public\":{\"enabled\":true,\"password\":{\"enforced\":false},\"expire_date\":{\"enabled\":false},\"send_mail\":false,\"upload\":true},\"user\":{\"send_mail\":false},\"resharing\":true,\"group_sharing\":true,\"federation\":{\"outgoing\":true,\"incoming\":true}},\"checksums\":{\"supportedTypes\":[\"SHA1\"],\"preferredUploadType\":\"SHA1\"},\"files\":{\"bigfilechunking\":true,\"blacklisted_files\":[\".htaccess\"],\"undelete\":true,\"versioning\":true}}}}}"
```

Hides version also in capabilities

2017-04-12 14:02 UTC, DeepDiver1975 commented
@guruz addressed - please test - thx

2017-04-12 15:03 UTC, guruz approved these changes
Tested, works.. desktop client fix will be in 2.3.2

2017-04-12 15:46 UTC, PVince81 commented
Now thinking of it, without the "oc.js" fix this PR becomes pointless as someone who really wants to know the version could just ping that...

On the other hand we could merge this and then work on finding a solution to split "oc.js" into config values that are required for the UI to work and others to be kept secret.

The middle ground would be to also check the flag. If the flag to set the version is hidden, then remove the keys "version" and "versionstring" from the oc.js response.

Does that make sense ?

2017-04-13 07:38 UTC, DeepDiver1975 commented
I vote for merge. We can address oc.js in a follow up pr

2017-04-13 07:41 UTC, merged

2017-04-13 07:41 UTC, PVince81 commented
Will the follow up PR come today ? If not, we need a ticket to not forget

2017-04-13 07:41 UTC, DeepDiver1975 commented
:+1:

2017-04-13 07:45 UTC, PVince81 commented
imprecise response.

(T)icket or (P)r today ?

2017-04-13 08:51 UTC, DeepDiver1975 commented
P

2017-04-19 06:58 UTC, PVince81 commented
https://github.com/owncloud/core/issues/27669 having the fields present with empty values doesn't look that good.