Optimize PUT - dont fetch and update checksum again, reunse the one f…
owncloud/core pull request #27532
Opened 2017-03-29 08:59 UTC by mrow4a

Back to the roots, but smarter https://github.com/owncloud/core/blob/stable8.2/lib/private/connector/sabre/file.php#L212

- [ ] Unit tests 

-3 SELECT, -1 UPDATE (!)
![selection_116](https://cloud.githubusercontent.com/assets/13368647/24446693/b5d583ee-146e-11e7-9d53-198d5c9ab413.jpg)
![selection_117](https://cloud.githubusercontent.com/assets/13368647/24446698/b7e9dbe4-146e-11e7-9042-895470d5f9a0.jpg)

2017-03-29 09:12 UTC, mrow4a commented
@DeepDiver1975 Any reasoning behind this ? 
![selection_118](https://cloud.githubusercontent.com/assets/13368647/24447262/a062c038-1470-11e7-9f65-048549e5e767.jpg)

I cannot scratch my head for a use case

2017-03-30 09:28 UTC, mrow4a commented
Ready for review, needs more integration tests for checksums and PUT in general, smashbox it maybe?

2017-03-31 07:43 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->emitPostHooks($exists);
There is `$this->fileView->touch` below... This might change the behavior if the hooks are expected to run after that touch.

2017-03-31 07:43 UTC, jvillafanez commented on lib/private/Files/Stream/Checksum.php
> +	 * Remove .path extension from a file path
"remove .path extension" 👀

2017-03-31 07:45 UTC, jvillafanez commented
Has this been tested with big file chunking (old and / or new)? Are external storages included for the checksums?

2017-03-31 08:55 UTC, mrow4a commented on lib/private/Files/Stream/Checksum.php
> +	 * Remove .path extension from a file path
Honestly, this is copy-paste from another function. We might think about creating separate class serving each layer in the code for partial files

https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/Files/Cache/Scanner.php#L461-L461

https://github.com/owncloud/core/blob/e4e9864759bcd0e417a4616503d1462f05a9d716/lib/private/Encryption/Util.php#L252-L252

Currently it is really spread over the code, which is bad. @DeepDiver1975 @jvillafanez What do you think?

2017-03-31 08:56 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->emitPostHooks($exists);
In previous versions https://github.com/owncloud/core/blob/stable8.2/lib/private/connector/sabre/file.php#L202 it was like here, not sure what reasoning was behind moving it there @DeepDiver1975

2017-03-31 08:59 UTC, mrow4a commented
I think new and old chunking code uses different functions, e.g. old chunking uses https://github.com/owncloud/core/blob/0496a82cf4896e06f52eb2409f1ffe7f88f97217/apps/dav/lib/Connector/Sabre/File.php#L106-L106

2017-03-31 09:16 UTC, jvillafanez commented on lib/private/Files/Stream/Checksum.php
> +	 * Remove .path extension from a file path
I only wanted to change the wording: it should be ".part" not ".path" 😆 

There should be only a function to handle this, maybe a class for all the string-based path manipulation, but this is currently out of scope.

2017-03-31 09:27 UTC, SergioBertolinSG commented
There are tests using local storage https://github.com/owncloud/core/blob/master/tests/integration/features/checksums.feature#L135

2017-03-31 09:44 UTC, mrow4a commented
@SergioBertolinSG and external?

2017-03-31 10:05 UTC, SergioBertolinSG commented
> @SergioBertolinSG and external?

Only local set up as external storage.

2017-03-31 10:09 UTC, mrow4a commented
@DeepDiver1975 Needs to review it carefully I think when he finds the time. @jvillafanez What about creating "PartialFileUntils" class ?

2017-04-03 12:40 UTC, jvillafanez commented
"PartialFilesUtils" suggests something only for dealing with part files, but I'd like to have something more generic. String-based path manipulations, which could include part file handling; without any FS access nor VFS access.

2017-04-13 13:02 UTC, mrow4a commented
@DeepDiver1975 Is this scope of 10.0 to fix checksuming performance?

2017-05-23 21:14 UTC, mrow4a commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
Seems to me some kind of workaround for some purpose, probably for what I have erased to work

2017-05-23 21:15 UTC, mrow4a commented on lib/private/Files/Stream/Checksum.php
> +		}
It will "cache" checksum for the original file (for which .part file is created)

2017-05-24 06:39 UTC, DeepDiver1975 requested changes

2017-05-24 06:39 UTC, DeepDiver1975 commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
from my understanding this is necessary if the file was changed on disk which is detected by the scanner.
in this case the checksum has to be removed

2017-05-24 10:07 UTC, mrow4a commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
I just went with debugger, first time the PUT gets there is with https://github.com/owncloud/core/blob/186595c1b4170f02517e555548bb139a5973f034/apps/dav/lib/Connector/Sabre/File.php#L204-L204 , and https://github.com/owncloud/core/blob/186595c1b4170f02517e555548bb139a5973f034/lib/private/Files/Cache/Scanner.php#L204-L204 $newData has following contents
![selection_289](https://cloud.githubusercontent.com/assets/13368647/26398187/039cd204-4079-11e7-8c0e-f5cf821558de.jpg)

Next time it gets there is in https://github.com/owncloud/core/blob/186595c1b4170f02517e555548bb139a5973f034/apps/dav/lib/Connector/Sabre/File.php#L215-L215 and it has following content 
![selection_290](https://cloud.githubusercontent.com/assets/13368647/26398206/14a107c8-4079-11e7-913e-91a069327ce5.jpg)

2017-05-24 10:07 UTC, mrow4a commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
@DeepDiver1975 any thoughts?

2017-05-24 10:17 UTC, mrow4a commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
I cannot think where cleaning of checksum might be usefull, first call goes through https://github.com/owncloud/core/blob/186595c1b4170f02517e555548bb139a5973f034/lib/private/Files/Cache/Scanner.php#L200-L200, and second goes through https://github.com/owncloud/core/blob/186595c1b4170f02517e555548bb139a5973f034/lib/private/Files/Cache/Scanner.php#L180-L180

2017-05-30 11:52 UTC, PVince81 commented
There should be integration tests already about resetting the checksum when an external storage file change. Strange that https://github.com/owncloud/core/pull/27532#discussion_r118172698 did not trigger it.

2017-05-30 11:55 UTC, PVince81 commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
Can you retest with an external storage ? Then change a file directly on external storage and run occ files:scan. In this case, the checksum in oc_filecache must disappear since the file changed and we didn't recompute it yet.

If this still works correctly then maybe there is yet another code paths that achieves the same result... strange

2017-05-30 11:56 UTC, PVince81 commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
also beware, when testing uploads, always test these:
- old endpoint, new file upload
- old endpoint, upload + overwrite
- old endpoint, new file chunked upload
- old endpoint, chunked upload + overwrite
- repeat above with new endpoint

2017-06-21 10:45 UTC, PVince81 commented on lib/private/Files/Cache/Scanner.php
> -					$newData['checksum'] = '';
please make sure these are covered by integration tests + checksums to make sure this PR doesn't break anything

2017-06-21 10:59 UTC, mrow4a commented
For all Optimize PUT - this, https://github.com/owncloud/core/pull/28021 and https://github.com/owncloud/core/pull/28003#discussion_r123211226 - I need proper smashbox and integration tests, and check if they verify what I do here. I will finish working on tests and verifying.

2017-07-04 12:55 UTC, PVince81 commented
Rebased. master contains the integration tests I requested...

2017-07-05 14:56 UTC, merged

2018-03-21 03:34 UTC, phil-davis commented
Note: this has not been backported to ``stable10``
I happened to notice because of conflicts raised in backporting #30580 - that PR changed some indent of lines in ``Scanner.php`` e.g.
```
	// Reset the checksum if the data has changed
	$newData['checksum'] = '';
```
is taken out in ``master`` by this PR. But remains in ``stable10``

Just noting here in case someone in future does a backport of this PR. You will get some conflict there.

2018-05-06 08:35 UTC, mrow4a commented
@phil-davis @DeepDiver1975 @PVince81 I can see, in stable10 this is still not there. We still do there unnecessarily UPDATE - the checksumming information is not being reused from part file info, and requires to be additionally queries and updated.

2018-05-06 08:45 UTC, mrow4a commented
Hmm, seems this to work would need to wait for https://github.com/owncloud/core/pull/28003

2018-05-06 08:59 UTC, mrow4a commented
Hmm, it does not, since https://github.com/owncloud/core/commit/523cd341ee702c309c347d6c4780ccb6e9365f1a already solved it but detecting "real file change"

2018-05-06 09:00 UTC, mrow4a commented
@PVince81 should I create backport PR and check everything again?