[WIP] Add checkbox to remove listing permission in public links
owncloud/core pull request #27548
Opened 2017-03-31 14:11 UTC by PVince81

Fixes https://github.com/owncloud/core/issues/7747.

Checklist here: https://github.com/owncloud/core/issues/7747#issuecomment-282263457

There's more to come, we can't merge this as is because backend support is required.

2017-03-31 16:38 UTC, PVince81 commented
- [ ] BUG: how to solve conflicts ?

- [ ] TODO: JS unit tests for the new view
- [ ] TODO: beautify the view (cc @felixheidecke)

2017-03-31 16:41 UTC, PVince81 commented
This is using the file-upload.js code so when this https://github.com/owncloud/core/pull/26306#issuecomment-290762884 is fixed to work with chunking, the button from anonymous upload should also be able to work with chunking.

@DeepDiver1975 @tomneedham @IljaN @butonic check this out

2017-03-31 16:45 UTC, PVince81 commented
- [ ] TODO: error handling, properly display error message
   - [ ] conflict
   - [ ] folder gone / whatever
   - [ ] insufficient space

2017-05-03 10:32 UTC, PVince81 commented
@pmaier1 I think having it called "Allow file listing" and set by default is better.

This is how it looks on this PR:

![files_drop_core](https://cloud.githubusercontent.com/assets/277525/25657104/6d122bea-2ffc-11e7-8227-b7f88e8a2b4a.png)

If you disable "Allow uploads" the option "Allow file listing" becomes greyed out and checked.

2017-05-03 10:51 UTC, pmaier1 commented
Ok nice so far. I don't like the wording "Allow viewing file listing" :) "Hide file listing" would be perfect IMO.
As you would need to change your logic probably call it "Show file listing".

2017-05-03 11:36 UTC, PVince81 commented
The part I dislike about "Hide file listing" is mostly because you need to think positive for "Allow uploads" and then negative "Hide" instead of "Show".

We could also rename "Allow uploads" to "Disallow uploads".

@felixheidecke any feedback on the wordings ?

2017-05-03 11:50 UTC, pmaier1 commented
I leave this up to you. 'Allow' and 'Show' or 'Disallow' and 'Hide' is both fine for me while I like the first pair a bit more :)

2017-05-03 17:08 UTC, PVince81 commented
- [ ] TODO: add capability entry

2017-05-05 14:06 UTC, PVince81 commented
- [ ] Change "Allow upload" to "Allow editing"

2017-05-05 14:06 UTC, PVince81 commented
- [ ] "Show file listing"

2017-05-10 09:42 UTC, PVince81 commented
Added integration tests.

One covers the file name deduplication and will fail currently as I still need to implement this.

2017-05-10 09:48 UTC, PVince81 commented
Capability added "supports_upload_only"

2017-05-10 20:12 UTC, PVince81 commented
Found a relatively clean way to deduplicate names by overriding the PUT method, but only when a header "X-OC-Autorename" is set.

@DeepDiver1975 can you have a look and tell me whether the approach is acceptable ? It's all in https://github.com/owncloud/core/pull/27548/commits/c47b09b2987a0fdde9a5dacea492cbb9a22b6b63

2017-05-11 09:03 UTC, PVince81 commented
As discussed with @DeepDiver1975 in a chat, the approach is acceptable.
One change:

- [ ] rename "X-OC-Autorename" to "OC-Autorename"

2017-05-11 10:03 UTC, PVince81 commented
Added JS unit tests.

Next up: beautify and proper error messages

2017-05-11 11:48 UTC, tomneedham commented
@butonic

2017-05-11 13:48 UTC, PVince81 commented
Uh oh, seems the push of JS unit tests from the other computer didn't work. Note to self: no rebase!

2017-05-11 14:41 UTC, PVince81 commented
- [ ] cherry pick commits from my other computer/branch which weren't pushed properly (OC-Autorename + JS unit tests)

2017-05-11 14:44 UTC, PVince81 commented
- [ ] TEST: drag and drop upload

2017-05-11 14:51 UTC, PVince81 commented
- [ ] design adjustments:
    - [ ] visible dropzone with text "Select files for upload"
        - [ ] clicking dropzone opens file picker
        - [ ] dropping on dropzone uploads files directly

2017-05-11 20:19 UTC, PVince81 commented
![files-drop](https://cloud.githubusercontent.com/assets/277525/25970094/bc3075fa-3697-11e7-8f0c-296885d9acdd.gif)

2017-05-12 06:48 UTC, SergioBertolinSG requested changes

2017-05-12 06:48 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +    And User "user0" deletes file "/FOLDER"
This should be 'When'.

2017-05-12 06:48 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +	Then publicly uploading a file does not work
Too much indentation here.

2017-05-12 06:53 UTC, SergioBertolinSG requested changes

2017-05-12 06:53 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +	And publicly uploading file "test.txt" with password "publicpw" and content "test"
Indentation from here to the end of the scenario is not aligned.

2017-05-12 06:53 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +	And publicly uploading file "test.txt" with content "test"
Indentation from here to the end of the scenario is not aligned.

2017-05-12 06:53 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +	And publicly uploading file "test.txt" with content "test"
Indentation from here to the end of the scenario is not aligned.

2017-05-12 07:55 UTC, SergioBertolinSG requested changes

2017-05-12 07:55 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +			| mimetype			| text/plain |
Too separated.

2017-05-12 07:55 UTC, SergioBertolinSG commented on tests/integration/features/sharing-v1.feature
> +			| mimetype			| text/plain |
Too separated.

2017-05-12 07:57 UTC, PVince81 commented on tests/integration/features/sharing-v1.feature
> +			| mimetype			| text/plain |
I did a search and replace of two spaces "  " with tabs. Apparently for some reason there were two spaces there. I'll adjust it.

2017-05-12 07:59 UTC, PVince81 commented
Rebased and fixes review comments

2017-05-12 08:09 UTC, PVince81 commented
Going to pre-review the diff and fix missing stuff.

2017-05-12 08:17 UTC, PVince81 commented
Ok, fixed everything I found when looking at the diff.

Please review! See whitespace-less diff: https://github.com/owncloud/core/pull/27548/files?w=1

@pmaier1 @DeepDiver1975 @tomneedham @felixheidecke

2017-05-12 08:52 UTC, felixheidecke commented on apps/files_sharing/js/PublicUploadView.js
> +				uploadButtonLabel: t('files_sharing', 'Select files for upload'),
I suggest *"Drop files here for upload"* to hint to the drag & drop ability.

2017-05-12 08:57 UTC, pmaier1 commented on apps/files_sharing/js/PublicUploadView.js
> +				uploadButtonLabel: t('files_sharing', 'Select files for upload'),
"Click here to select files or use drag & drop to upload" as you can also use the file picker I assume.

2017-05-12 09:27 UTC, PVince81 commented on apps/files_sharing/js/PublicUploadView.js
> +				uploadButtonLabel: t('files_sharing', 'Select files for upload'),
I'll wait for you guys to settle on a solution, let me know 😄

2017-05-12 11:10 UTC, DeepDiver1975 approved these changes
NICE

2017-05-12 13:40 UTC, pmaier1 commented on apps/files_sharing/js/PublicUploadView.js
> +				uploadButtonLabel: t('files_sharing', 'Select files for upload'),
My final call: "Click to select files or use drag & drop to upload"

2017-05-12 13:40 UTC, PVince81 commented
I'll go with @pmaier1's text for now and we can merge.

If it's not optimal we can change it in a subsequent PR. This will make it possible to already get this tested...

2017-05-12 13:44 UTC, PVince81 commented
Tests passed on previous commit and the text is not covered by unit tests => merge

2017-05-12 13:44 UTC, merged

2017-05-15 13:28 UTC, PVince81 commented
> Tests passed on previous commit and the text is not covered by unit tests => merge

Never trust the green ticks, Jenkins wasn't prevent, there's a failure on master now 💥

2017-05-22 14:27 UTC, butonic commented
Is there a migration path when upgrading from an oc 9.x with files_drop app?

2017-05-22 14:34 UTC, PVince81 commented
@butonic no migration path possible for technical reasons (route name is different).

It was decided to say in the release notes that the shares must be recreated.

cc @pmaier1

2017-06-15 13:16 UTC, ckamm commented
@PVince81 I'm adding the relevant functionality to the client. To clarify: Previously the client checked the "Allow editing" box if create and update permission were present. This seems to have changed? To get matching behavior I must only check for create permission.

Does the update permission still toggle anything ui wise?