Update QueryLogger and write to log all queries with sql statements, parameters and duration of query
owncloud/core pull request #27571
Opened 2017-04-05 12:59 UTC by mrow4a

Verified with blackfire:
![selection_152](https://cloud.githubusercontent.com/assets/13368647/24706033/957c404c-1a0e-11e7-9300-09eee0cbf0ed.jpg)

Our Log:
![selection_153](https://cloud.githubusercontent.com/assets/13368647/24706044/a25cb38c-1a0e-11e7-8e07-89eabc99547f.jpg)

Example log:
![selection_155](https://cloud.githubusercontent.com/assets/13368647/24706500/3f394de0-1a10-11e7-85d0-b41b093eb8dc.jpg)

2017-04-05 13:00 UTC, mrow4a commented on lib/private/DB/Connection.php
> -		if(\OC::$server->getSystemConfig()->getValue( 'log_query', false)) {
Killed

2017-04-05 13:00 UTC, mrow4a commented on lib/private/legacy/db/statementwrapper.php
> -		if(\OC::$server->getSystemConfig()->getValue( "log_query", false)) {
Start to kill fascinating legacy code?

2017-04-05 13:01 UTC, mrow4a commented on lib/private/Diagnostics/QueryLogger.php
> +				\OCP\Util::writeLog('core', 'DB CALL : '.$sql_string.' WITH : '.$params_str.' TOOK : '.$duration.' msec',  \OCP\Util::DEBUG);
Maybe we can write additional APP out of that?

2017-04-05 13:01 UTC, mrow4a commented
Any idea how to unit test it and if this is needed?

2017-04-05 13:36 UTC, mrow4a commented
@DeepDiver1975 @PVince81 Should I adjust some documentation somewhere? This needs few flags

![selection_156](https://cloud.githubusercontent.com/assets/13368647/24707933/a6628694-1a15-11e7-9245-b02b5a803bd4.jpg)

2017-04-05 13:39 UTC, PVince81 commented
@mrow4a config.sample.php

2017-04-05 13:39 UTC, DeepDiver1975 requested changes

2017-04-05 13:39 UTC, DeepDiver1975 commented on lib/private/Diagnostics/QueryLogger.php
> +		if(\OC::$server->getSystemConfig()->getValue( "log_query", false)) {
can we have this is a class of it's own please?

2017-04-05 13:41 UTC, DeepDiver1975 commented
Thinking one step further: we could do this in an app. And even have special log format/file for the specific needs.

2017-04-05 13:42 UTC, mrow4a commented
@DeepDiver1975 So you want to write new default app to the core instead of destructor?

2017-04-05 13:52 UTC, DeepDiver1975 commented
> Thinking one step further: we could do this in an app. And even have special log format/file for the specific needs.

@PVince81 what do you say?

2017-04-05 18:17 UTC, PVince81 commented
Wasn't the log_query thing designed to be plugged into by an app ? I don't remember.

2017-04-05 18:20 UTC, mrow4a commented
xD

2017-04-05 19:27 UTC, DeepDiver1975 commented
> Wasn't the log_query thing designed to be plugged into by an app ? I don't remember.

the log_query config switch is really old and only allowed stupid logging to the regular log file.
the querylogger approach was more flexible - this is what clockwork app uses.

we will fully move over to the query logger approach and allow more flexible logging of sql statements.

so - yes - @mrow4a do it as an app :wink:

2017-04-05 19:34 UTC, mrow4a commented
Will try to do even more, open API for e.g. jenkins via smashbox to get number of queries for specific requests... ohh it can be wild, but will start simple. @DeepDiver1975 Can I have new table for that or use log file for now?

2017-04-05 19:41 UTC, DeepDiver1975 commented
> In Table I would like to store number of queries per request and maybe path or sth, so later I can data mine it. In the log I can store everything if someone wants?

I'd start to write this to a file first - possibly an new file with format as needed for the automation - have a chat with @tboerger on whats best.

i'd avoid another table - this add load on the resource which is under monitoring - kind of schroedingers cat ..... :wink:

2017-04-07 00:22 UTC, mrow4a commented
As in commit message, make sense or close PR?

2017-04-11 07:56 UTC, DeepDiver1975 approved these changes

2017-04-13 11:05 UTC, closed without merging