removed assetic
owncloud/core pull request #27679
Opened 2017-04-19 13:28 UTC by Peter-Prochaska

## Description
Removed Assetic because of some security issues

## Motivation and Context
Make owncloud more secure

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-04-20 06:52 UTC, DeepDiver1975 requested changes

2017-04-20 06:52 UTC, DeepDiver1975 commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
please do not commit htaccess - thx

2017-04-20 06:52 UTC, DeepDiver1975 commented
if i remember correctly there is a repairstep related to assets - maybe a occ command as well? THX

2017-04-20 15:00 UTC, PVince81 commented
How dangerous to put this in that close to the release ?

In the future it would be nice to address library changes at the beginning of a milestone.

2017-04-20 15:29 UTC, DeepDiver1975 commented
> In the future it would be nice to address library changes at the beginning of a milestone.

sure - but sec scanner revealed this last week ....

2017-04-20 15:29 UTC, DeepDiver1975 commented
@Peter-Prochaska composer.lokc also need changes afaik

2017-04-20 15:36 UTC, PVince81 commented
Ok, then please get this reviewed and merged before this evening.

The current code changes look fine.

2017-04-20 19:19 UTC, PVince81 commented
If this is really important, please finish this as soon as possible. Thanks.

2017-04-21 11:32 UTC, PVince81 commented
@Peter-Prochaska please always ping after updating so I can get a notification that this is ready again, else it gets lost forever in the dark abyss of ticket overflow

2017-04-21 11:34 UTC, PVince81 commented
I setup OC and it still seems to work fine 👍

2017-04-21 11:35 UTC, PVince81 commented
rebased for CI... mysql mb4 docker times out again in multiple PRs...

2017-04-21 12:08 UTC, Peter-Prochaska commented
> it gets lost forever in the dark abyss of ticket overflow
wow ;-)

2017-04-21 14:56 UTC, PVince81 commented
some weird dependency issues on Travis: https://travis-ci.org/owncloud/core/jobs/224313100

```
php build/composer.phar install --dev

You are using the deprecated option "dev". Dev packages are installed by default now.

Loading composer repositories with package information

Installing dependencies (including require-dev) from lock file

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for ocramius/package-versions 1.1.2 -> satisfiable by ocramius/package-versions[1.1.2].

    - ocramius/package-versions 1.1.2 requires php ~7.0 -> your PHP version (5.6.5) does not satisfy that requirement.

  Problem 2

    - Installation request for ocramius/proxy-manager 2.0.4 -> satisfiable by ocramius/proxy-manager[2.0.4].

    - ocramius/proxy-manager 2.0.4 requires php 7.0.0 - 7.0.5 || ^7.0.7 -> your PHP version (5.6.5) does not satisfy that requirement.

  Problem 3

    - ocramius/proxy-manager 2.0.4 requires php 7.0.0 - 7.0.5 || ^7.0.7 -> your PHP version (5.6.5) does not satisfy that requirement.

    - sensiolabs/behat-page-object-extension v2.0.1 requires ocramius/proxy-manager ^1.0||^2.0 -> satisfiable by ocramius/proxy-manager[2.0.4].

    - Installation request for sensiolabs/behat-page-object-extension v2.0.1 -> satisfiable by sensiolabs/behat-page-object-extension[v2.0.1].

make: *** [lib/composer/phpunit] Error 2
```

2017-04-24 09:05 UTC, merged

2017-04-24 19:15 UTC, PVince81 commented on .htaccess
> +</IfModule>
Next time please don't modify random files, thanks.

Regression: https://github.com/owncloud/core/commit/dbb37e7684e9d6e6d6618e5dcb66ba5a0192c3da

There is core that appends line in htaccess and it creates a syntax error if the newline is missing.

2017-10-06 19:32 UTC, kdslkdsaldsal commented
FWIW is stuff is removed / dropped it would make sense to create an issue in the documentation tracker to remove all related stuff: https://github.com/owncloud/documentation/issues/3438