Prevent empty username or email when authenticating
owncloud/core pull request #27684
Opened 2017-04-19 14:45 UTC by PVince81

## Description
Add more checks for empty user names or empty email search.

## Related Issue
None raised, see test steps.

## Motivation and Context

## How Has This Been Tested?

1. Setup OC
1. Go to personal settings
1. Set an email address
1. Set it back to empty string (this will set the email field in oc_accounts to an empty string instead of "null")
1. Using cadaver, use an empty string as "username" and type in the admin user's password (or whichever user appears first in the oc_accounts table).

Before this fix: successful login as the first user in the list
After this fix: 401 error

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@Peter-Prochaska even though it accesses the first entry in oc_accounts I don't think it's critical because it still requires you to know the password of that one user.
So consider this more as hardening.

2017-04-19 16:16 UTC, DeepDiver1975 requested changes

2017-04-19 16:16 UTC, DeepDiver1975 commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException('$user cannot be empty');
$user ?

2017-04-20 08:00 UTC, Peter-Prochaska commented
If someone changes $user to $email, then +1

2017-04-20 08:07 UTC, PVince81 commented
I'll fix that later, not critical

2017-05-04 09:32 UTC, PVince81 commented on lib/private/User/Manager.php
> +			throw new \InvalidArgumentException('$user cannot be empty');
fixed

2017-05-04 09:32 UTC, PVince81 commented
fixed, rebased, squashed

2017-05-12 09:44 UTC, DeepDiver1975 approved these changes

2017-05-12 14:10 UTC, PVince81 commented
CI stalled... ok I'll rebase

2017-05-15 09:40 UTC, merged