Sending event after mountConfig object is set
owncloud/core pull request #27740
Opened 2017-04-25 10:41 UTC by davicente

## Description
Sending an event when mountConfig object is set, in order to use it in js files without failing

## Related Issue
https://github.com/owncloud/platform/issues/94

## Motivation and Context
When .js is executed moungConfig object is not always set, so it has to wait until that. A way to do that it's waiting for an event sent by core when object has been set.

## How Has This Been Tested?
The event has been received in a .js file in the settings part.

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-25 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=27740) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=27740) before we can accept your contribution.<br/><hr/>**David Vicente** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=27740) it.</sub>

2017-04-26 08:02 UTC, PVince81 commented on apps/files_external/js/settings.js
> +	$("#body-settings").trigger("mountConfigLoaded");
It is unlikely that the storages from `loadStorages` are already properly loaded at this stage because the ajax call might not have completed yet. This even needs to be sent after the ajax callback completed successfully and populated the DOM / update UI elements.

2017-05-02 12:43 UTC, DeepDiver1975 requested changes
## TODO:
- [ ] rebase to master
- [ ] squash commits
- [x] fix cla

2017-05-02 17:17 UTC, PVince81 commented
:+1: please merge if CI passes

2017-05-02 19:09 UTC, DeepDiver1975 approved these changes

2017-05-02 19:10 UTC, merged