extended theme service
owncloud/core pull request #27746
Opened 2017-04-26 07:17 UTC by phisch

## Description
This adds the functionality to get a list of all available themes or search for one through the ThemeService.

## Related Issue

## Motivation and Context
The mail template editor needs to know which themes there are, and i don't want too much theme logic it its repository, this way we can keep it clean.

## How Has This Been Tested?
Partially tested through unittests. Fully tested by hand.
The usual overwrites: css, js, img, templates, translations, mimetype icons all work for legacy and app themes, for subdir and normal deployments.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-04 05:04 UTC, PVince81 commented
Is this done ? If yes, please set the "3 - To Review" label and summon reviewers.

2017-05-05 08:59 UTC, phisch commented
Since the changes are used in an app, should i move this to the public api?

2017-05-05 09:35 UTC, PVince81 commented on lib/private/Theme/ThemeService.php
> +		if ($themeName === '' && $this->defaultThemeExists()) {
weird, why does Github show `&&` in red now ?

2017-05-05 09:48 UTC, PVince81 commented
> Since the changes are used in an app, should i move this to the public api?

If some functions need to be called by apps, please make these public.

The code checker would complain when scanning the app if you're using private APIs

2017-05-05 11:08 UTC, phisch commented
Ok, going to update.

2017-05-12 09:41 UTC, DeepDiver1975 requested changes
public api is required

2017-05-15 09:39 UTC, PVince81 commented
@phisch any update ?

2017-05-16 07:17 UTC, phisch commented
@DeepDiver1975 please give me feedback if this is okay.

2017-05-16 08:32 UTC, DeepDiver1975 commented
> @DeepDiver1975 please give me feedback if this is okay.

OCP shall only hold interfaces - no classes. the idea here is to separate the public interface declaration from its implementation.

2017-05-17 06:53 UTC, DeepDiver1975 commented
setting back to '2 - developing' because of missing proper public interfaces

2017-05-17 06:54 UTC, PVince81 commented
Without this it will not be possible to theme the setup page as it was before, which is a regression.

Not sure how bad this is and whether it can wait for 10.0.2 @felixboehm  ...

2017-05-17 07:07 UTC, PVince81 commented
@phisch or is that only needed for the email template app?

2017-05-18 14:09 UTC, DeepDiver1975 commented on lib/private/Server.php
> +		$this->registerAlias('IThemeService', 'ThemeService');
Try 'OCP\Theme\IThemeService'

2017-05-19 09:10 UTC, PVince81 commented
@phisch how much work is missing to have this working ?

2017-05-19 09:24 UTC, phisch commented
@PVince81 ups, i just forgot to switch to review label again. It should be done.

2017-05-19 09:26 UTC, PVince81 commented
It's still a huge thing, looks a bit risk to merge now.

2017-05-19 09:30 UTC, PVince81 commented
moving to 10.0.2

2017-07-04 12:19 UTC, PVince81 commented
@phisch phinisch this ?

2017-07-12 11:41 UTC, phisch commented
@PVince81 this has been complete the whole time, we just did not want to merge because it was too close to a release.
@DeepDiver1975 can you re-review?

2017-07-12 11:42 UTC, phisch commented on lib/private/Theme/ThemeService.php
> +		if ($themeName === '' && $this->defaultThemeExists()) {
Github had a syntax highlighting hickup. (<- just for the history)

2017-07-12 12:36 UTC, DeepDiver1975 commented
translation have been tested? php as well as js translations? 

I don't see any related change in the code which could make it possible - see https://github.com/owncloud/core/issues/28167#issuecomment-313494564

@phisch

2017-07-13 12:21 UTC, phisch commented
I tested the JS translations which could be affected by this. And yes they work as expected.

2017-08-03 10:41 UTC, PVince81 commented
@phisch can you rebase to refresh CI ?

@DeepDiver1975 so this can be merged ?

2017-08-10 07:06 UTC, PVince81 commented
rebased

2017-08-10 19:01 UTC, PVince81 commented
@DeepDiver1975 no feedback from you, assuming you don't have any comment to add

2017-08-10 19:01 UTC, merged