Integrations tests to check custom DAV properties persistence
owncloud/core pull request #27750
Opened 2017-04-26 20:59 UTC by VicDeo

More 

## Description
Do you like tests? 

## Related Issue
https://github.com/owncloud/QA/issues/390

## Motivation and Context
Integration testing

## How Has This Been Tested?
By Behat engine

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-27 11:22 UTC, SergioBertolinSG requested changes

2017-04-27 11:22 UTC, SergioBertolinSG commented on tests/integration/features/dav-v2.feature
> +		And "user0" sets property of file "/testcustomprop.txt" with "{http://whatever.org/ns}very-custom-prop" "veryCustomPropValue"
How to know what is the last string?

Maybe add "with value" before like:

And "user0" sets property of file "/testcustomprop.txt" with "{http://whatever.org/ns}very-custom-prop" with value "veryCustomPropValue"

Or if this string is too long use a tablenode
And "user0" sets property of file "/testcustomprop.txt" with
 | propertyName | propertyValue |

Optional could be lo allow to set several properties at once

And "user0" sets properties of file "/testcustomprop.txt" with
  | propertyName1 | propertyValue1 |
  | propertyName2 | propertyValue2 |

2017-04-27 11:22 UTC, SergioBertolinSG commented on tests/integration/features/dav-v2.feature
> +		And as "user0" gets a custom property "{http://whatever.org/ns}very-custom-prop" of file "/testcustomprop.txt"
This statement should be When, or the set property one, but there has to be a when.

2017-04-27 11:22 UTC, SergioBertolinSG commented on tests/integration/features/dav-v2.feature
> +		And as "user0" gets a custom property "{http://whatever.org/ns}very-custom-prop" of file "/catchmeifyoucan.txt"
Missing When.

2017-04-27 11:22 UTC, SergioBertolinSG commented on tests/integration/features/dav-v2.feature
> +		And as "user1" gets a custom property "{http://whatever.org/ns}very-custom-prop" of file "/testcustompropshared.txt"
Missing When.

2017-04-27 21:14 UTC, VicDeo commented
@SergioBertolinSG thanks for review, updated

2017-04-28 07:37 UTC, SergioBertolinSG approved these changes

2017-05-02 07:30 UTC, PVince81 commented
@VicDeo please rebase. JS tests env issue should be fixed.

2017-05-02 07:32 UTC, DeepDiver1975 commented
> @VicDeo please rebase. JS tests env issue should be fixed.

I already did - wanted to know if this is really fixed

2017-05-02 07:35 UTC, DeepDiver1975 commented
js tests are green!

2017-05-02 14:17 UTC, merged