Add options to the user:sync command to handle accounts
owncloud/core pull request #27798
Opened 2017-05-02 17:14 UTC by jvillafanez

## Description
Handle missing accounts during user syncing. Requires https://github.com/owncloud/core/pull/27796 to work properly.

## Related Issue

## Motivation and Context

## How Has This Been Tested?
Manual tested all the options asked, plus without interaction.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-02 17:22 UTC, jvillafanez commented on core/Command/User/SyncBackend.php
> +				$userAccount = $this->userManager->get($u);
`$syncService->getNoLongerExistingUsers` should return Account object in order to avoid this.

2017-05-03 11:09 UTC, DeepDiver1975 requested changes

2017-05-03 11:09 UTC, DeepDiver1975 commented on core/Command/User/SyncBackend.php
> +					['nothing', 'disable accounts', 'remove accounts', 'ask later'],
we agreed on disabling by default and delete as option.
the option has to be confirmed in interactive more.

why are there two more modes?

2017-05-03 11:09 UTC, DeepDiver1975 commented on core/Command/User/SyncBackend.php
> +							function($uid, $ac) use ($output) { $output->writeln($uid); },
no onliners - nerver - ever

2017-05-03 11:36 UTC, jvillafanez commented on core/Command/User/SyncBackend.php
> +					['disable accounts', 'remove accounts', 'ask later'],
The "ask later" option is used to make a decision about what to do with the users after the admin knows who is affected.
* If the admin wants to remove the accounts maybe he want to make sure what accounts will be removed.
* If the admin wants to disable the accounts he can answer the question before starting the process and let the command run.

2017-05-03 14:33 UTC, wravenm commented
n

2017-05-04 09:09 UTC, DeepDiver1975 commented
The action is not controlable via arguments/options? Please adjust

2017-05-04 09:14 UTC, DeepDiver1975 commented
And please test your code - this is not working ....

2017-05-04 12:05 UTC, davitol commented
LGTM with the tests done until now adding https://github.com/owncloud/core/pull/27796 + https://github.com/owncloud/user_ldap/pull/85

2017-05-04 14:35 UTC, DeepDiver1975 commented
rebased and adjustments to make occ usage easier

2017-05-04 14:36 UTC, DeepDiver1975 commented
a disabled users will be reported again in case the command is rerun. but I guess this is okay since in a second run the admin might want to remove that users

2017-05-04 14:36 UTC, DeepDiver1975 approved these changes

2017-05-04 14:37 UTC, DeepDiver1975 commented
and I squashed them

2017-05-08 08:33 UTC, merged