fixed output in error pages
owncloud/core pull request #27808
Opened 2017-05-04 07:25 UTC by Peter-Prochaska

## Description
Escape output in error pages

## Related Issue
https://github.com/owncloud/core/issues/27807

## Motivation and Context
Now downloading files or folder with quotes is possible

## How Has This Been Tested?
Download File with quotes and there is no error page

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-04 07:31 UTC, DeepDiver1975 requested changes

2017-05-04 07:31 UTC, DeepDiver1975 commented on lib/private/legacy/template.php
> +			$errors = [['error' => htmlspecialchars($error_msg, ENT_QUOTES), 'hint' => htmlspecialchars($hint, ENT_QUOTES)]];
please use 

```php
\OCP\Util::sanitizeHTML($name)

2017-05-04 09:18 UTC, PVince81 commented
Code looks good. How did you test the error page ?

I tried testing the error page as well but the file name doesn't even appear there... Maybe it did in older versions.

![download-error](https://cloud.githubusercontent.com/assets/277525/25697255/8df5e50e-30ba-11e7-8ba0-6968d50c6248.png)

2017-05-04 09:19 UTC, PVince81 commented
:+1: if CI passes

2017-05-04 09:25 UTC, PVince81 commented
@Peter-Prochaska please always link to the backports in the original PR and back. Without this it makes it very difficult to track.

2017-05-12 14:08 UTC, PVince81 commented
CI stalled, @DeepDiver1975 please restart

2017-05-15 10:26 UTC, DeepDiver1975 approved these changes

2017-05-15 10:26 UTC, merged

2017-08-15 09:28 UTC, PVince81 commented
regression: https://github.com/owncloud/core/issues/28684