enable app theme with `default_enable` during installation/update
owncloud/core pull request #27819
Opened 2017-05-05 11:07 UTC by phisch

## Description
Apps are disabled during the installation and update wizard. Thats why we have to find and enable the app theme manually. This PR provides functionality to find the first app that has the type `theme` and is `default_enable`. We can't use existing functions for that, because they always check the database which is not setup at this point yet.

## Related Issue
https://github.com/owncloud/enterprise/issues/1956

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-08 07:22 UTC, PVince81 commented on lib/private/legacy/app.php
> +	 * @return false|string
PHPDoc ?

2017-05-08 07:23 UTC, PVince81 commented on lib/private/legacy/app.php
> +			$info = $parser->parse(self::getAppPath($app) . '/appinfo/info.xml');
Hmm, I thought there were other functions that would load app metadata already ? Not too happy to have yet another `/appinfo/info.xml` path hard-coded here.
Did you find the code that enables all default apps ?

2017-05-08 15:21 UTC, phisch commented on lib/private/legacy/app.php
> +			$info = $parser->parse(self::getAppPath($app) . '/appinfo/info.xml');
Yes, there is another function that loads metadata, but in some cases it tries to connect to the database, which of course fails in this case. I'm not too happy about it either.
The code that enables all default apps: `\OC\Installer::installShippedApps`

2017-05-09 12:08 UTC, PVince81 commented on lib/private/legacy/app.php
> +			$info = $parser->parse(self::getAppPath($app) . '/appinfo/info.xml');
Ok fine... this will need a good refactoring at some point

2017-05-09 12:09 UTC, PVince81 commented
👍 code looks good, I assume you've tested this thoroughly

2017-05-12 09:26 UTC, DeepDiver1975 requested changes

2017-05-12 09:26 UTC, DeepDiver1975 commented on lib/base.php
> +			$defaultEnabledAppTheme = \OC_App::getDefaultEnabledAppTheme();
sorry - but this has a bad performance impact - parsing all app info.xml on each and every request?

2017-05-12 09:28 UTC, PVince81 commented on lib/base.php
> +			$defaultEnabledAppTheme = \OC_App::getDefaultEnabledAppTheme();
this is only when "installed" is false

2017-05-12 09:28 UTC, PVince81 commented on lib/base.php
> +			$defaultEnabledAppTheme = \OC_App::getDefaultEnabledAppTheme();
basically the setup page

2017-05-12 09:32 UTC, DeepDiver1975 approved these changes

2017-05-12 09:32 UTC, merged