Add find methods to user manager and group manager
owncloud/core pull request #27832
Opened 2017-05-08 13:35 UTC by tomneedham

## Description
Adds single string searching of users by user_id, displayname and email. Handy for LDAP when user_id will now be a UUID and searching by email | disaplyname is common.

## How Has This Been Tested?
 - Setup LDAP server, tested share dialog to find users by UUID, Display name and email.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Need to add some more tests for the GroupManager find method, just looking for initial feedback before proceeding..?

2017-05-09 16:19 UTC, PVince81 commented
Steps:

1. Enable guest app
1. Run `npm run build` if you picked the guest app and are wondering why it doesn't work
1. Share a folder "test" with "Someone" and wait for the "(guest)" entry appears in the dropdown, select it
1. Type in an email address
1. Save
1. Log out
1. Open the email
1. Open the link from the email
1. Set a password
1. Login as admin user again (or whatever first user from step 1)
1. Create a folder "test2"
1. Type "Someo" to search for the existing guest user

Expected: guest user appears
Actual: "an error occurred"
```
{"reqId":"nCeGIVUGZ56IHxxMZ6Zu","level":3,"time":"2017-05-09T16:16:54+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=vince&perPage=200&itemType=folder","message":"Call to undefined method OC\\User\\User::getEmail() at \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/lib\/Controller\/ShareesController.php#165"}
```

2017-05-09 16:22 UTC, PVince81 commented
note that in my case the email address also started with "someone". Well, actually I used "Vincent" as guest name and "vincent@hostname.tld" (where hostname.tld is the local computer) when testing. So the bug could also be related to this overlap when searching.

From the error it seems to be an API issue.

2017-05-10 09:50 UTC, tomneedham commented
Pushed a fix but I can't build the guests app:
<img width="754" alt="screen shot 2017-05-10 at 11 50 12" src="https://cloud.githubusercontent.com/assets/660805/25893123/e69718d4-3576-11e7-8456-66212cdfe5c0.png">

2017-05-10 14:31 UTC, tomneedham commented
REF: https://github.com/owncloud/core/issues/27850

2017-05-11 07:19 UTC, butonic commented on lib/private/User/Backend.php
> +	const SEARCH_STRING		= 4294967296;	// 1 << 32
we start exceeding max int here ... why are the shifted by 4 annyway? wtf?

2017-05-11 09:16 UTC, butonic commented on core/Migrations/Version20170510143952.php
> +		]);
needs an index

2017-05-11 09:59 UTC, tomneedham commented on lib/private/User/Backend.php
> +	const SEARCH_STRING		= 4294967296;	// 1 << 32
👽

2017-05-12 07:07 UTC, jvillafanez commented on lib/private/User/AccountMapper.php
> +			->orWhere($qb->expr()->iLike('display_name', $qb->createNamedParameter('%' . $this->db->escapeLikeParameter($pattern) . '%')))
Quoting comment from http://stackoverflow.com/a/34029944:

> It is in PostgreSQL the keyword ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. This is not in the SQL standard but is a PostgreSQL extension.

2017-05-12 07:11 UTC, jvillafanez commented on lib/private/Group/Manager.php
> +		die(var_dump($matchingUsers));
💣 💥

2017-05-12 07:13 UTC, jvillafanez commented on core/Migrations/Version20170510143952.php
> +			'length' => 64,
This is far from being enough

2017-05-12 12:57 UTC, butonic commented on lib/private/User/AccountMapper.php
> +			->orWhere($qb->expr()->iLike('display_name', $qb->createNamedParameter('%' . $this->db->escapeLikeParameter($pattern) . '%')))
What is the question here? We use ILIKE from postgres and have adapters for [mysql]
(https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/DB/AdapterMySQL.php#L42), [sqlite](https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/DB/AdapterSqlite.php#L44) and [oracle](https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/DB/AdapterOCI8.php#L44). 

On oracle it is currently problematic when the search string contains `[` or `]` see https://github.com/owncloud/core/pull/26672

2017-05-12 14:24 UTC, DeepDiver1975 requested changes

2017-05-12 14:24 UTC, DeepDiver1975 commented on core/Migrations/Version20170510143952.php
> +		$table->addIndex(['search_attributes'], 'search_attributes_index');
we need a combined index if one query searches in multiple columns

2017-05-15 07:40 UTC, jvillafanez commented on lib/private/User/AccountMapper.php
> +			->orWhere($qb->expr()->iLike('display_name', $qb->createNamedParameter('%' . $this->db->escapeLikeParameter($pattern) . '%')))
if we have hidden magic then it's ok.

2017-05-15 14:47 UTC, PVince81 commented
ok guest app part seems to work again

2017-05-15 14:51 UTC, PVince81 commented
With the guest app if I type in the email of the previously created guest user it appears in the list with the display name and I can select it for sharing.

2017-05-15 14:54 UTC, PVince81 commented
Fixes https://github.com/owncloud/core/issues/27847

2017-05-15 15:11 UTC, PVince81 commented on core/Migrations/Version20170510143952.php
> +		$table->addIndex(['search_attributes'], 'search_attributes_index');
@tomneedham any update ?

2017-05-15 15:11 UTC, PVince81 commented
Apart from the index question, is this ready ? @butonic @DeepDiver1975 @jvillafanez

2017-05-15 15:16 UTC, cdamken commented
wait, im testing now :)

2017-05-15 15:18 UTC, cdamken commented
Looks good for me now ;)

2017-05-15 16:30 UTC, tomneedham commented
185 for the length of the search_attributes column as according to some research by @butonic this is the max indexable length we can achieve - so my understanding is that if we add an index that spans this column as well it won't be effective

2017-05-16 13:45 UTC, tomneedham commented
Working on a new branch / PR - closing for now

2017-05-16 13:45 UTC, closed without merging

2017-05-17 07:51 UTC, PVince81 commented
the new PR https://github.com/owncloud/core/issues/27906

2017-05-18 11:17 UTC, butonic commented on core/Migrations/Version20170510143952.php
> +		$table->addIndex(['search_attributes'], 'search_attributes_index');
nope. we need an index per or part of a query:

```
-- with combined index
CREATE INDEX find_index ON oc_accounts (lower_user_id, display_name, email);
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id LIKE '%test%' and display_name LIKE '%test%' and email LIKE '%test%';
0|0|0|SCAN TABLE oc_accounts
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id LIKE '%test%' or display_name LIKE '%test%' or email LIKE '%test%';0|0|0|SCAN TABLE oc_accounts
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id LIKE '%test%' or display_name LIKE '%test%' or email LIKE '%test%';
0|0|0|SCAN TABLE oc_accounts
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id = '%test%' or display_name = '%test%' or email = '%test%';
0|0|0|SCAN TABLE oc_accounts
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id = '%test%' and display_name = '%test%' and email = '%test%';
0|0|0|SEARCH TABLE oc_accounts USING INDEX find_index (lower_user_id=? AND display_name=? AND email=?)
sqlite> 

...
-- with individual indexes
CREATE UNIQUE INDEX lower_user_id_index ON oc_accounts (lower_user_id);
CREATE INDEX display_name_index ON oc_accounts (display_name);
CREATE INDEX email_index ON oc_accounts (email);
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id = '%test%' and display_name = '%test%' and email = '%test%';
0|0|0|SEARCH TABLE oc_accounts USING INDEX lower_user_id_index (lower_user_id=?)
sqlite> EXPLAIN QUERY PLAN select * from oc_accounts WHERE lower_user_id = '%test%' or display_name = '%test%' or email = '%test%';
0|0|0|SEARCH TABLE oc_accounts USING INDEX lower_user_id_index (lower_user_id=?)
0|0|0|SEARCH TABLE oc_accounts USING INDEX display_name_index (display_name=?)
0|0|0|SEARCH TABLE oc_accounts USING INDEX email_index (email=?)
sqlite> 
```

2017-05-18 11:41 UTC, butonic commented on core/Migrations/Version20170510143952.php
> +		$table->addIndex(['search_attributes'], 'search_attributes_index');
oh well. the `%test%` like comparison kills the index on all dbms. If we use `test%` it is much better:
```sql
mysql> explain select * from oc_accounts WHERE lower_user_id like '%test%' or display_name like '%test%' or email like '%test%';
+----+-------------+-------------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table       | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+-------------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | oc_accounts | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+----+-------------+-------------+------------+------+---------------+------+---------+------+------+----------+-------------+

mysql> explain select * from oc_accounts WHERE lower_user_id like 'test%' or display_name like 'test%' or email like 'test%';
+----+-------------+-------------+------------+------+----------------------------------------------------+------+---------+------+------+----------+-------------+
| id | select_type | table       | partitions | type | possible_keys                                      | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+-------------+------------+------+----------------------------------------------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | oc_accounts | NULL       | ALL  | lower_user_id_index,display_name_index,email_index | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+----+-------------+-------------+------------+------+----------------------------------------------------+------+---------+------+------+----------+-------------+
```

sqlite never seems to use an index for like
mysql can use separate indexes as well as a combined index ... if we don't do medial searches.

for ldap we have `'user_ldap.enable_medial_search'` in config.php to allow medial searches. we could do the same for sql. say ... `'accounts.enable_medial_search'`?

2017-05-18 12:43 UTC, butonic commented on core/Migrations/Version20170510143952.php
> +		$table->addIndex(['search_attributes'], 'search_attributes_index');
also see http://use-the-index-luke.com/de/sql/where/bereiche/like-filter