[:construction] User backend extendable account searching
owncloud/core pull request #27906
Opened 2017-05-16 14:47 UTC by tomneedham

## Description
Continued from: https://github.com/owncloud/core/pull/27832

### Problem
 - In OC9 we allow LDAP users to specify custom search attributes which can be used for finding users to share
 - In OC10 we have the accounts table which is used for searching to reduce the hits to LDAP servers
 - Organisations use these search attributes to help users find other users based on terms they may know (like usernames, emails, staff codes, etc)

### Proposed / Implemented Solution
 - Added a new oc_account_terms table with `account_id` (foreign key to accounts.id) and `term` columns
 - Altered user manager code to find users using these terms
 - Allow user backends to manipulate these search terms as needed (e.g: LDAP can add these from custom attributes the user configures)

User_LDAP App:
 - PR in progress to implement these features and supply the search attributes to the core https://github.com/owncloud/user_ldap/pull/98

## Related Issue
https://github.com/owncloud/user_ldap/issues/96

## How Has This Been Tested?
 - Manual testing - needs more 💪  
 - Updated unit tests -> still WIP 🚧 

## Screenshots (if appropriate):
because they make your PR look more cool:
![screen shot 2017-05-16 at 15 44 52](https://cloud.githubusercontent.com/assets/660805/26112023/a8d3f3be-3a4e-11e7-9c7c-b652f346071d.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-16 15:39 UTC, PVince81 commented on lib/private/User/AccountTerm.php
> + * Class Account
AccountTerm

2017-05-16 15:40 UTC, PVince81 reviewed
At first look the code looks fine

2017-05-16 18:25 UTC, butonic commented
The idea of the account table was to only rely on eg ldap for the login to be able to iterate over all users etc. The code that used to lead to a lot of ldap queries because it would execute pages etc was the search method used when sharing users. But also fetching any other use metadata was triggering ldap queries. Unfortunately, the ldap user bachend allos specifying additional fields that should be taken into account when doing a user search. that might eg be the `city` or multi value attributes like `mailAccounts`. That is actually a nice feature. The initial approach does not fit as @tomneedham and I today by chance stumbled over an LDIF entry with 7 email addresses. We were told there were accounts with many more. We came up with the idea of an additional table to hold arbitrary search terms. Another approach would be to add an elasticsearch based framework for this kind of cacheable metadata ... but that is nothing we can add on short notice.

For now I think this is a good approach. We could add a foreign key but did not want to be the first ones to actually use the relevant code. We would have liked to have an ORMapper, but got around it with adding an interface and making the ldap app actively update the search attributes on first login.

2017-05-17 06:17 UTC, DeepDiver1975 commented
> Hitting the LDAP server when someone types in a share search string might be ok especially as it benefits from LDAP specific searching capabilities (and patterns?).

this is one major complaint I'm hearing from big installations: searching the ldap takes ages. From an UX pov this is not acceptable.

2017-05-17 06:32 UTC, DeepDiver1975 requested changes

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/private/User/Account.php
> +	public static function fromRow(array $row) {
needed?

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/private/User/Account.php
> +	private $_termsChanged = false;
_ ?? needed ???

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/private/User/AccountTermMapper.php
> +	public function setTermsForAccount($account_id, array $terms) {
use Mapper:insert ???

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/private/User/AccountTermMapper.php
> +	public function deleteTermsForAccount($account_id) {
use Mapper:delete ???

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/private/User/Manager.php
> +		$user = new User($account, $this->accountMapper, $this->accountTermMapper, $this, $this->config, null, \OC::$server->getEventDispatcher() );
is the terms mapper necessary inside class User? I'd hide the terms mapper within the account mapper

2017-05-17 06:32 UTC, DeepDiver1975 commented on lib/public/IGroupManager.php
> +	 * @return array an array of display names (value) and user ids (key)
not the User objects?

2017-05-17 06:32 UTC, DeepDiver1975 commented on tests/lib/Group/ManagerTest.php
> +		$userManager = $this->createMock('\OC\User\Manager');
Manager:class

2017-05-17 06:32 UTC, DeepDiver1975 commented on tests/lib/Group/ManagerTest.php
> +		$userBackend = $this->createMock('\OC_User_Backend');
OC_User_Backend::class

2017-05-17 09:10 UTC, tomneedham commented
Rebased

2017-05-17 11:50 UTC, butonic commented on lib/private/User/Account.php
> +	private $_termsChanged = false;
_ to indicate it is used like _updatedFields: tracking if the attribute was changed so the mapper can act accordingly

2017-05-17 12:53 UTC, butonic commented on lib/private/User/AccountTermMapper.php
> +	public function deleteTermsForAccount($account_id) {
we want to delete by account_id, not id

2017-05-17 12:54 UTC, butonic commented on lib/private/User/AccountTermMapper.php
> +	public function setTermsForAccount($account_id, array $terms) {
adressed with https://github.com/owncloud/core/pull/27906/commits/dd377c94b645bc50d3e365ec500aafa72f507002#diff-1e60c46513705f729f8e728292eb6f3bR43

2017-05-18 08:17 UTC, PVince81 commented
This doesn't work with guest emails (haven't tried generic emails), steps:

1. Login as admin
1. Enable guest app
1. Create folder "test1"
1. Type "Vince" in share field for "test1", select "Share to guest"
1. Type in local email address, "vincent@host.tld"
1. Log out
1. Open mail, open link and set password
1. Login as admin again
1. Create another folder "test2"
1. Share "test2" with "vincent@host.tld"

Expected: autocomplete finds the guest user "Vince"
Actual: autocomplete doesn't find the user and only offers a "remote" user (due to the format).

This worked on the previous PR.

@tomneedham did you properly include searching by email ? I can see that the oc_accounts column "email" for that guest user contains the correct email address. (and it's unique)

2017-05-18 08:24 UTC, PVince81 commented
Fixed by replacing "inner join" with "left join": https://github.com/owncloud/core/pull/27906/commits/06d7c36c66d18a888f318c7f8dcd55f77749c54c

2017-05-18 08:28 UTC, tomneedham commented
🤞 for jenkins ;)

2017-05-18 12:33 UTC, butonic commented
investigating the index question in https://github.com/owncloud/core/pull/27832#discussion_r117225157 made me look up how ldap handles it. turns out we have another config option hidden in the code: https://github.com/owncloud/user_ldap/blob/5e2a75bb78f57b8a406467ad48ea68faa856a85d/lib/Access.php#L1368-L1368

It is disabled by default, so we get the same search behavior as with ldap.

we use individual indexes because every db but sqlite can combine them and they help with `getByEmail` and `getByUid` as well.

@tomneedham @DeepDiver1975 @PVince81 please review.

2017-05-18 12:35 UTC, PVince81 commented
that option was supposed to be an unsupported experimental feature, do we need it enabled now ?

2017-05-18 12:35 UTC, PVince81 commented
@jvillafanez

2017-05-18 12:36 UTC, PVince81 commented on lib/private/User/AccountMapper.php
> +		if ($search) { // TODO use medial search config option here as well
something for much later ?

2017-05-18 12:37 UTC, butonic commented
no we dont need it enabled, but since it was there i assumed someone was using it.

2017-05-18 12:38 UTC, butonic commented on lib/private/User/AccountMapper.php
> +		if ($search) { // TODO use medial search config option here as well
well if the medial search was only experimental we can get rid of all the TODOs as well as the config option stuff.

2017-05-18 13:05 UTC, PVince81 commented on lib/private/User/AccountMapper.php
> +		if ($search) { // TODO use medial search config option here as well
hmm, yeah... if the search is running entirely within OC tables then the option is not useful any more.

It was added for people with special requirements but not default due to perf impact.

2017-05-18 19:20 UTC, merged

2017-05-18 19:20 UTC, PVince81 commented
please test extensively in the RC2, thanks

2017-10-27 18:10 UTC, mrow4a commented
Hey guys, what was the motivation to add setter and getter of search terms to account https://github.com/owncloud/core/blob/master/lib/private/User/Account.php#L104-L104 ? Is that really needed? I cannot find nowhere in the code sth using it @tomneedham

2017-11-01 07:22 UTC, tomneedham commented
Since our entity ORM stuff doesnt deal with parent/child relationships we had to half bake this in ourselves. When an account is first created it is used to store search terms: https://github.com/owncloud/core/blob/master/lib/private/User/Manager.php#L452 and also when a user is synchronised: https://github.com/owncloud/core/blob/master/lib/private/User/SyncService.php#L174 

(but this logic is under a TODO to combine it since it is duplicated)

2017-11-01 07:22 UTC, tomneedham commented
group search terms is another idea.....