add unique index for vcategory owncloud/core#20952
owncloud/core pull request #27913
Opened 2017-05-17 08:05 UTC by cortho

## Description
add unique key for table *dbprefix*vcategory

## Related Issue
https://github.com/owncloud/core/issues/20952

## Motivation and Context

fix as proposed at https://github.com/owncloud/core/issues/20952#issuecomment-169949310

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-17 08:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=27913) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=27913) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=27913) it.</sub>

2017-05-17 09:00 UTC, DeepDiver1975 commented
THX - but I see following issues:
- [ ] applying the index will fail on upgrade where data is already in the system
- [ ] please use migrations to change the schema - https://doc.owncloud.org/server/10.0/developer_manual/app/schema.html#database-migrations

2017-05-17 09:01 UTC, DeepDiver1975 requested changes
see the comment ....

2017-05-22 10:57 UTC, cortho commented
added migration in https://github.com/cortho/core/commit/d674ff0169dd23164c6c4f190ff3c1e5da039993
what to do with db_structure.xml I changed in the previous commit?

2017-05-31 15:19 UTC, DeepDiver1975 requested changes

2017-05-31 15:19 UTC, DeepDiver1975 commented on core/Migrations/Version20170519112910.php
> +            ->where($qb->expr()->in(
will break in case the array has more then 1000 elements - dbms have restrictions on this .....

2017-05-31 15:19 UTC, DeepDiver1975 commented on core/Migrations/Version20170519112910.php
> +        ->where($qb->expr()->in(
same as above

2017-05-31 15:19 UTC, DeepDiver1975 commented on db_structure.xml
> +			<index>
you can remove this change

2017-06-01 08:07 UTC, cortho commented on db_structure.xml
> +			<index>
Thank you very much for your feedback, I'll have a look on this.

2017-07-04 10:15 UTC, PVince81 commented
@DeepDiver1975 PR was updated, please recheck

2018-02-20 15:04 UTC, closed without merging