Fix relative path issue in conditional log
owncloud/core pull request #27926
Opened 2017-05-18 09:13 UTC by sharidas

Fix relative path issue in conditional log

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change fixes the relative path issue in conditional log.

## Related Issue

## Motivation and Context

This change fixes the relative path issue in conditional log. For example if user provides, log file path as
data/test.log, then current code will fail. So this change will help to append SERVERROOT to data/test.log so that it wont fail.

## How Has This Been Tested?

 Create 2 users : user1 and user2
- [x] Try to share a file as user1 to user2
- [x] Verify the log

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-18 09:37 UTC, PVince81 commented on lib/private/Log/Owncloud.php
> +			if (strpos($conditionalLogFile,'/') !== 0) {
`$conditionalLogFile[0] !== '/') ? no need for searching the whole string

2017-05-18 09:42 UTC, DeepDiver1975 requested changes

2017-05-18 09:42 UTC, DeepDiver1975 commented on lib/private/Log/Owncloud.php
> +				if (!is_dir(dirname($conditionalLogFile))) {
what happens if conditionalLogFile holds no folder information? just myLogForStuff.log

2017-05-18 09:46 UTC, sharidas commented on lib/private/Log/Owncloud.php
> +				if (!is_dir(dirname($conditionalLogFile))) {
So lets say conditionalLogFile holds myLogForStuff.log, then as per line 116 in the patch, conditionalLogFile becomes SERVERROOT/myLogForStuff.log. And hence the log file will be created in the root folder of oC.

2017-05-18 09:47 UTC, PVince81 commented on lib/private/Log/Owncloud.php
> +				if (!is_dir(dirname($conditionalLogFile))) {
I think when discussing it was discovered that "owncloud.log" without path defaults to the data directory, so we should also do so for these relative paths

2017-05-18 10:00 UTC, sharidas commented
Updated change make the conditional log reside inside datadirectory if the path is relative. Also use $conditionalLogFile[0] instead of strpos.

2017-05-18 11:45 UTC, PVince81 commented on lib/private/Log/Owncloud.php
> +					mkdir(dirname($conditionalLogFile), 0755);
not sure if we really should auto-create parent dirs. does the logic for owncloud do that too ?

2017-05-18 11:57 UTC, sharidas commented on lib/private/Log/Owncloud.php
> +					mkdir(dirname($conditionalLogFile), 0755);
No only at least that's not the case with owncloud.log. If we provide data/test.log as logfile, then the file will be created automatically. Instead if we give data/testing/test.log, the log file will not be generated. Because data/testing is missing. I will remove that change for the conditionalLogFile.

2017-05-18 12:32 UTC, PVince81 commented on lib/private/Log/Owncloud.php
> +					mkdir(dirname($conditionalLogFile), 0755);
yes, in general the admin should make sure the folder in question already exists.

2017-05-19 10:45 UTC, SergioBertolinSG commented
Works 👍

2017-05-19 10:46 UTC, merged