UI test autocomplete sharing
owncloud/core pull request #27933
Opened 2017-05-18 12:06 UTC by individual-it

## Description
UI test to test the user autocompletion as per QA plan https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Sharees.md

This is build on top of #27860

## Related Issue
https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Sharees.md

## Motivation and Context
make Test plan run automatically
https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Sharees.md

## How Has This Been Tested?
run the tests in Chrome on local machine

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-18 13:20 UTC, phil-davis commented
I had a go at resolving the conflicts, but it is not happy yet. I will look again in a while...

2017-05-19 01:27 UTC, individual-it commented
this is branched off from the file renaming. Let's have the autocomplete stuff in here only

2017-05-31 17:32 UTC, phil-davis requested changes
I think just little things that are not functional.
This code should work fine.

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/lib/SharingDialog.php
> +	protected $autocompleItemsTextXpath = "//*[@class='autocomplete-item-text']";
s/autocompleItemsTextXpath/autocompleteItemsTextXpath
in all places

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/lib/SharingDialog.php
> +	 * @param bool $deletePermission not implemented yet
Params documented here but not even mentioned in the function.
shareWithUser has the params in the function call interface.
What to do?

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/shareeAutocompletion.feature
> +	Scenario: autocompletion of a pattern that matches regular existing users but also a user whith whom the item is already shared (folder)
s/whith/with
I don't think that scenario descriptions have to match any code, so this will have no other places to fix.

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/bootstrap/SharingContext.php
> +		$this->sharingDialog= $this->filesPage->openSharingDialog(
No space before =
I guess these can be tidied up.

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/bootstrap/SharingContext.php
> +		$this->sharingDialog= $this->filesPage->openSharingDialog(
No space before =

2017-05-31 17:32 UTC, phil-davis commented on tests/ui/features/lib/FilesPage.php
> +		$fileRow=$this->findFileRowByName($name, $session);
I guess we be consistent and should put spaces before and after =

2017-06-02 01:43 UTC, individual-it commented
I feel this is now ready to go.
but what happens to jenkins?

2017-06-02 05:29 UTC, phil-davis approved these changes

2017-06-02 05:36 UTC, phil-davis commented
@DeepDiver1975 and others, as well as adding new tests this makes infrastructure for generally dealing with fields that have autocomplete. In the autocomplete case the underlying AJAX only starts when the user has stopped typing for "a bit". So we need to check in the testing that the AJAX has started and then finished before moving on to check that the desired matching item(s) is in the list. Thus there are new functions here to deal with that. The existing waiting loops have also been changed so that they wait more accurately only until the real requested timeout (the previous behaviour with the counter sometimes resulted in a total wait time much greater than asked for, which delayed test completion if timeout conditions happened much)

For some reason Jenkins seems to have never even tried to start.
Is it possible to just get Jenkins to start?

2017-06-15 15:46 UTC, phil-davis commented
Jenkins did its thing with this a while ago. Merging now.

2017-06-15 15:47 UTC, merged