find instead of search
owncloud/core pull request #27962
Opened 2017-05-19 14:32 UTC by butonic

allows finding users by userid, displayname, email and additional search terms. 

related:
- https://github.com/owncloud/core/issues/27171
- https://github.com/owncloud/core/issues/27013

2017-05-19 14:33 UTC, tomneedham requested changes

2017-05-19 14:33 UTC, tomneedham commented on settings/Controller/UsersController.php
> +	 * @param string $pattern Pattern to find in the account table (usenid, displayname, email, additional search terms)
usenid?

2017-05-19 16:50 UTC, butonic commented
@PVince81 I know we will get tons of bug reports for this. Please add it to 10.0.1

2017-05-19 19:28 UTC, PVince81 commented
please add the scenarios that you have tested

2017-05-19 19:34 UTC, PVince81 commented
and also please fix the unit test.

2017-05-22 12:24 UTC, jvillafanez commented
scenarios tested with LDAP configured with sn + cn search attributes (checked with https://github.com/owncloud/user_ldap/pull/98 along with this PR)
* looking for sn ✅ 
* looking for cn ✅ 
* checked utf-8 chars ✅ 

scenarios tested with local users:
* search by user id ✅ 

not tested:
* search by email
* search by display name

2017-05-22 12:28 UTC, butonic commented on lib/private/User/AccountMapper.php
> -		$qb->select(['user_id', 'lower_user_id', 'display_name', 'email', 'last_login', 'backend', 'state', 'quota', 'home'])
@PVince81 core search is broken when an account hase more than one search term. will only happen if the new ldap app is used. but since this is core ...

2017-05-22 12:52 UTC, tomneedham commented
👍 tested with docker-ldap containers, and ran unit tests locally. Tested UI sharee search and user management search

2017-05-22 13:02 UTC, jvillafanez commented
👍

2017-05-22 13:05 UTC, tomneedham approved these changes

2017-05-22 15:07 UTC, merged