Remove apps that will go to market from shipped.json
owncloud/core pull request #27985
Opened 2017-05-23 11:38 UTC by PVince81

## Description
Makes it possible to uninstall them.

## Related Issue

## Motivation and Context

## How Has This Been Tested?
- [ ] TEST: setup works
- [ ] TEST: apps from the list still work
- [ ] TEST: occ ugprade doesn't complain, still works (no auto-disable anyway)
- [ ] TEST: removed apps can be uninstalled now

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

I don't have full understanding of the extent of the "shipped" flag. Grepping for `isShipped` seems to show a lot of locations, even some related to API responses.

@tomneedham @DeepDiver1975 @davitol

2017-05-23 11:52 UTC, davitol commented
Tested and WFM 👍

2017-05-23 12:06 UTC, PVince81 commented
Thanks. Don't merge yet, there could be consequences due to the weird OCS code that rely on this flag.

Needs to be evaluated

2017-05-23 13:24 UTC, tomneedham commented
So grepping all of these apps to show what OCS routes they might register:
```
./activity/appinfo/routes.php://API::register(
./activity/appinfo/routes.php://API::register(
./activity/appinfo/routes.php:API::register(
./dlrepogrep.sh:grep -r 'API::register(' ./repos/*
 ./notifications/appinfo/routes.php:\OCP\API::register(
./notifications/appinfo/routes.php:\OCP\API::register(
./notifications/appinfo/routes.php:\OCP\API::register(
./notifications/tests/Integration/app/appinfo/routes.php:\OCP\API::register(
./notifications/tests/Integration/app/appinfo/routes.php:\OCP\API::register(
./sharepoint/appinfo/routes.php:OC_API::register('get', '/apps/sharepoint/api/v1/mounts',
```

2017-05-23 13:28 UTC, tomneedham commented
My only concern at the moment is if apps are enhancing the notification or activity apis - looking for usages...

2017-05-23 13:44 UTC, PVince81 commented
AFAIK none of our apps are expecting more than a single response block.

Does it make a difference is shipped is there or not ? Does it influence the order or name of the response block ?

2017-05-23 18:01 UTC, DeepDiver1975 requested changes

2017-05-23 18:01 UTC, DeepDiver1975 commented on core/shipped.json
>      "market",
Kill market as well

2017-05-23 18:59 UTC, PVince81 commented on core/shipped.json
>      "market",
this will allow uninstallling the market app, (P)roceed, (A)bort ?

2017-05-23 19:36 UTC, DeepDiver1975 commented on core/shipped.json
>      "market",
If somebody wants to....

2017-05-24 08:38 UTC, PVince81 commented
> My only concern at the moment is if apps are enhancing the notification or activity apis - looking for usages...

Enhancing ? How ?

2017-05-24 08:39 UTC, PVince81 commented
and why

2017-05-24 08:46 UTC, tomneedham commented
> Enhancing ? How ?

well by latching onto the same route and altering / changing the response in some weird way

> and why

no idea

2017-05-24 09:00 UTC, PVince81 commented
removed "market".

@tomneedham is checking whether it's really possible to extend/overwrite the endpoints in 10.0. Because from what I remember we removed this possibility a long time ago when unifying the APIs. (something about integrating with app framework I think)

2017-05-24 09:17 UTC, tomneedham commented
Just checked with 10.0.1 => You can still 'extend' existing routes by registering for the same route and returning data - the responses are then 'merged'. This is done using `array_merge` with priority given to shipped apps. Collisions would only occur when using the same keys in the responses.

2017-05-24 09:23 UTC, PVince81 commented
@tomneedham thanks. This kind of weird overriding of routes isn't officially supported. I thought we properly removed this already. Might need more work for this.

This means at this point we will remove the apps anyway from shipped.json. The likeliness of someone overwriting routes like this is anyway minimal.

Waiting for CI then merge

2017-05-24 09:23 UTC, PVince81 commented
@davitol did you test the checkboxes I posted above ? If yes, please tick

2017-05-24 15:06 UTC, PVince81 commented
Test passed: https://jenkins.owncloud.org/job/owncloud-core/job/core/job/PR-27985/

2017-05-24 15:06 UTC, merged