Improved remote user search
owncloud/core pull request #27996
Opened 2017-05-24 10:59 UTC by tomneedham

## Description
Implemented paginated searching of (local|remote)addressbooks for improved search performance when searching through (multiple) very large addressbooks.

Also added configurable search properites for remote addressbook contact search - used for shareelookup on remote servers.

## Motivation and Context
 - When connected to federated servers with large addressbooks, this search method is extremely slow and can use large amount of memory due to the lack of search limits and offsets.

## How Has This Been Tested?
So far: unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-24 11:42 UTC, tomneedham commented on apps/files_sharing/lib/Controller/ShareesController.php
> +		$addressBookContacts = $this->contactsManager->search($search, $searchProperties, [], $this->limit, $this->offset);
@butonic thoughts on this? I think we should always include CLOUD and FN since they are needed to represent the user in the search dialog, but allow additional to be provided?

2017-05-24 21:52 UTC, mrow4a commented
Any update here, can I review?

2017-05-25 13:00 UTC, mrow4a commented
Apart from doubt to @butonic about CLOUD and FN, looks good to me, no doubts here :+1:

2017-06-06 14:50 UTC, butonic commented on apps/files_sharing/lib/Controller/ShareesController.php
> +		$addressBookContacts = $this->contactsManager->search($search, $searchProperties, [], $this->limit, $this->offset);
don't force CLOUD and FN ... but document it. as we just chatted: https://github.com/owncloud/documentation/blob/458ae44c975f635365cdb0abc66648bb3b3f6558/admin_manual/configuration_files/federated_cloud_sharing_configuration.rst#configuration-tips

2017-06-06 14:51 UTC, butonic commented on apps/files_sharing/lib/Controller/ShareesController.php
> +		$addressBookContacts = $this->contactsManager->search($search, $searchProperties, [], $this->limit, $this->offset);
probably give an occ command that just adds the email by setting it to `CLOUD,FN,EMAIL`. Discuss if we should make it the default?

2017-06-12 10:13 UTC, tomneedham commented
Failing with php5.6 on pgsql...

2017-06-14 11:48 UTC, tomneedham commented
Rebased to kick jenkins into action

2017-06-22 11:53 UTC, butonic requested changes
these interfaces exist since 5.0.0 ... so make the new params optional

2017-06-22 11:53 UTC, butonic commented on apps/dav/lib/CardDAV/AddressBookImpl.php
> +	public function search($pattern, $searchProperties, $options, $limit, $offset) {
add ` = null` to make the params optional or give sane defaults.

2017-06-22 11:53 UTC, butonic commented on lib/public/IAddressBook.php
> +		public function search($pattern, $searchProperties, $options, $limit, $offset);
add ` = null` to make the params optional or give sane defaults.

2017-06-22 16:33 UTC, butonic approved these changes

2017-06-22 16:49 UTC, merged