Set mtime from MemoryCache instead of using touch()
owncloud/core pull request #28003
Opened 2017-05-24 21:28 UTC by mrow4a

As in the title, I am trying to avoid unnecessarily query delivering this information different way then just querying the database twice. This PR saves around 10 query in the tested example

- [x] Integrations tests in place for this feature
- [ ] Might need some unit test update?
- [ ] In other PR, I am doing the same with checksum, and this PR might need adjustment after merge of https://github.com/owncloud/core/pull/27532

2017-05-24 21:32 UTC, mrow4a commented
@IljaN @tomneedham @DeepDiver1975 Thoughts?

2017-05-26 07:49 UTC, DeepDiver1975 requested changes

2017-05-26 07:49 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Common.php
> +	private static $metadata;
why static?

2017-05-26 07:49 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->addMetaData($internalPath, 'mtime', $request->server['HTTP_X_OC_MTIME']);
where is the actual write operation of the meta data?

2017-05-26 07:49 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Storage.php
> +	public function addMetaData($path, $key, $val);
$val -> $value

2017-05-26 07:52 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->addMetaData($internalPath, 'mtime', $request->server['HTTP_X_OC_MTIME']);
Will add description to that. It does not write any metadata hardly "to disk", any new call to getMetadata (e.g. in ->update) will have metadata overwritten with this.

2017-05-26 07:53 UTC, mrow4a commented on lib/private/Files/Storage/Common.php
> +	private static $metadata;
Hmm, seems this wrapper wont need it static, seems you are right.

2017-05-26 07:55 UTC, mrow4a commented
@DeepDiver1975 I will try also to reuse it for checksums, to avoid more queries -> https://github.com/owncloud/core/pull/28003/files#diff-be504dc886734275f06114e4306fa215L231

2017-05-26 07:58 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->addMetaData($internalPath, 'mtime', $request->server['HTTP_X_OC_MTIME']);
Maybe I should call it cacheMetadata or sth?

2017-05-26 07:58 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->addMetaData($internalPath, 'mtime', $request->server['HTTP_X_OC_MTIME']);
@DeepDiver1975

2017-05-26 08:13 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->addMetaData($internalPath, 'mtime', $request->server['HTTP_X_OC_MTIME']);
but the touch operation you are replacing was storing the mtime in file cache - my question is where this storing of information is happening now

2017-05-26 10:36 UTC, mrow4a commented
Ok, I see this wont be that easy, since "touch" literally touches the file, and this needs to be done separately @DeepDiver1975 .. ehh. This not only affects database but mtime of existing file on disk.

2017-05-26 14:36 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
The only problem which I see here, that touch() without previous call to update() will pass to preTouch hook, NonExistingNode -> https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/Files/Node/HookConnector.php#L110-L110

Question is, what do we need it for and if it is ok to call touch() on non-existing yet node.

2017-05-26 14:38 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
In case of update, pretouch will receive "previous version"

2017-05-26 14:40 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
PostTouch is executed after the scan, and receives new node :>

2017-05-26 15:07 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
For now, I dont see anything using that https://github.com/search?q=org%3Aowncloud+preTouch&type=Code, delete this hook ? @DeepDiver1975 @PVince81 ?

2017-05-30 11:35 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
These hooks could be used by third party apps so deleting would be API breakage.

2017-05-30 11:35 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
why is this a problem ?

2017-05-30 17:10 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
This particular `preTouch` adds additional queries (WRITEs/READs/UPDATEs) to each PUT files, does not matter if that app is using your pre-touch or not.

When you apply the solution above, you get rid of some queries.. when you remove `preTouch` you get rid of additional queries needed for LOCK, since this preTouch does locking+filecache query.

Problem with solution above is that we pass different things to preTouch, not sure if the correct ones. Will be good to know what app using preTouch requires in the input @DeepDiver1975 @PVince81

2017-06-21 10:34 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
If we delete pretouch, would there be an alternative hook for developers to listen to ? Is there another hook ?

Would require informing the developers mailing list and wait a bit for feedback.
If we remove it, it would be in 10.1 and not backportable (which is fine).

2017-07-04 10:08 UTC, PVince81 commented
I don't think we can remove the "touch" hook which might be used by third party app, that would be API breakage. So we might need to abandon this optimization.

@DeepDiver1975 agree ? or kill the hook ?

2017-07-27 13:43 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
>  				if ($this->fileView->touch($this->path, $request->server['HTTP_X_OC_MTIME'])) {
@PVince81 So, do we remove preTouch? :>

2017-07-27 13:49 UTC, mrow4a commented
preTouch hook :gun: ?

2017-08-03 08:24 UTC, mrow4a commented
Any update on pretouch ?

2017-08-03 08:29 UTC, PVince81 commented
> Any update on pretouch ?

We can't kill it without notifying the community.
Also I don't feel good about killing this in a minor release (10.0.3).

@DeepDiver1975 thoughts ?

2017-08-10 07:28 UTC, PVince81 commented
moving to "planned", blocked by the decision of deprecating/removing pre/post touch hooks

2018-02-15 15:54 UTC, PVince81 commented
can we have this PR without killing the touch event ?

2018-02-15 17:53 UTC, mrow4a commented
@PVince81 rewrite whole thing (so maybe it is more objectstore friendly @DeepDiver1975 )

2018-04-25 10:05 UTC, PVince81 commented
@ownclouders rebase

2018-04-25 10:05 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-25 10:06 UTC, PVince81 commented
will need adjusting unit tests

2018-04-25 10:06 UTC, ownclouders commented
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

.git/rebase-apply/patch:31: trailing whitespace.
* The issues in other components should be reported in their respective repositories: 
.git/rebase-apply/patch:137: trailing whitespace.
--> 
.git/rebase-apply/patch:167: trailing whitespace.
Login as admin user into your ownCloud and access 
.git/rebase-apply/patch:168: trailing whitespace.
http://example.com/index.php/settings/integrity/failed 
.git/rebase-apply/patch:187: trailing whitespace.
or 
warning: squelched 1596 whitespace errors
warning: 1601 lines add whitespace errors.
warning: Cannot merge binary files: core/img/background.jpg (224f9680e0726195d95604b6e995f300569ad171 vs. Merge pull request #26512 from IljaN/master)
error: Failed to merge in the changes.


```

2018-04-27 19:52 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$storage->getUpdater()->update($internalPath);
Hmm, I check it, and we don't loose any hook in here @PVince81 . Not sure why we though preTouch does not get emitted.

2018-04-27 19:56 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->changeLock(ILockingProvider::LOCK_SHARED);
Lock will be decreased from LOCK_EXCLUSIVE to LOCK_SHARED after update propagation is successfull (and additionaly touch adds new mtime)

2018-04-27 19:57 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->changeLock(ILockingProvider::LOCK_SHARED);
Do we actually need to change this lock to shared? Cannot we just release it after PUT is finished?

2018-05-15 15:54 UTC, mrow4a commented
@PVince81 @DeepDiver1975 updated and tested with smashbox, all fine - updated doc in the issue

2018-05-16 07:35 UTC, DeepDiver1975 approved these changes

2018-05-16 07:44 UTC, DeepDiver1975 commented
second approval by @PVince81 please

2018-05-16 08:51 UTC, mrow4a commented
For some strange reason, I have to add a check that updater is enabled in the view -> it seems it is possible to disable the updater in the view -> https://github.com/owncloud/encryption/blob/master/lib/Migration.php#L55

2018-05-16 09:38 UTC, phil-davis commented
Fails apiSharing suite because it is now called apiSharing-v1

Rebase to fix that.

2018-05-16 10:10 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +					// touch propagates the update using view -> basicOperation -> writeUpdate
@mrow4a as discussed, please use the storage instance's `touch` method directly instead of the view.
and keep the explicit update as it was before as the storage doesn't do a cache update

looking at the chunking code it turns out the storage->touch() access is already used there and for some reason someone forgot to also adjust it here back then

2018-05-16 15:30 UTC, mrow4a commented
@PVince81 @DeepDiver1975 updated description, tested and adjusted as reviewed

2018-05-16 15:33 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +
oh, will change it, by mistake

2018-05-16 15:34 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/Node.php
> -		} catch (ForbiddenException $ex) {
ehh, my glorious editor took action

2018-05-16 15:34 UTC, mrow4a commented on lib/private/Files/View.php
> +	public function isCacheUpdateEnabled() {
Will remove, it should be in previous commit.

2018-05-16 15:35 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +	private function handleMetadataUpdate(\OC\Files\Storage\Storage $targetStorage, $targetInternalPath) {
now we use the same function to commit mtime and propagate update - both in chunked and in single PUT

2018-05-17 08:45 UTC, PVince81 approved these changes
:+1:

2018-05-17 12:40 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-05-17 12:40 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-05-18 08:09 UTC, DeepDiver1975 commented
looks like rebasing with gitmate does not work anymore ...

2018-05-19 16:56 UTC, mrow4a commented
It was with newest master then you rebased I think.

2018-05-20 16:36 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +		$targetStorage->getUpdater()->update($targetInternalPath);
@PVince81 I am thinking, should we pass to update function mtime, or not? I cannot scratch my head over the case in which mtime wont be updated (updater should detect it I think)

2018-05-20 16:36 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +		$targetStorage->getUpdater()->update($targetInternalPath);
Maybe for safety we should call updater with mtime in case HTTP_X_OC_MTIME is set, and without in case it is not, thoughts?

2018-05-22 08:44 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +		$targetStorage->getUpdater()->update($targetInternalPath);
maybe pass it in explicitly so it involves less magic. magic being "remembering that the function is reading a global var / header"

2018-06-25 20:21 UTC, mrow4a commented
@DeepDiver1975 @PVince81 ok, I think finally this is ready :>

2018-06-25 20:24 UTC, merged

2018-06-28 18:12 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/File.php
> +			if ($targetStorage->touch($targetInternalPath, $mtime)) {
If someone wonders what essential changes, it is that we now use `$targetStorage->touch & $targetStorage->getUpdater()->update($targetInternalPath, $mtime)` instead of `$this->fileView->touch (which calls updater update() internally) & $targetStorage->getUpdater()->update($targetInternalPath, $mtime)`.

Thus we call update 1x, instead 2x