Migration to fix term column length
owncloud/core pull request #28019
Opened 2017-05-26 12:06 UTC by tomneedham

## Description
On some DB setups, the max index length can be as low as 767 bytes. This leads to a max column length of 255 chars - at the moment we have 256. https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

## Related Issue
https://github.com/owncloud/core/issues/28007

## How Has This Been Tested?
 - tested running the migration locally to observe column length change
 - tested with a term that is 256 chars and it is correctly deleted
 - added test to try and submit a term that is too long

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-26 12:07 UTC, PVince81 commented on core/Migrations/Version20170526104128.php
> +		if($table->getColumn('term')->getLength() == 255) {
`===`

2017-05-26 12:08 UTC, PVince81 commented on core/Migrations/Version20170526104128.php
> +		$db->executeQuery("DELETE FROM {$prefix}account_terms WHERE CHAR_LENGTH(term) = 256;");
>= 256 just to be on the safe side ?

2017-05-26 12:09 UTC, PVince81 commented on lib/private/User/User.php
> +				unset($terms[$i]);
assuming that messing with the PHP array indices won't affect subsequent code

I'm saying this because once upon a time I had to call `array_values()` for such array to avoid logic that iterated over indices instead of `foreach` to fail...

2017-05-26 12:10 UTC, PVince81 commented on lib/private/User/User.php
> +				unset($terms[$i]);
I suggest to use `array_filter` with a callback instead

2017-05-26 12:24 UTC, tomneedham commented
Orcale: `LENGTH()` https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions076.htm
MySQL: `CHAR_LENGTH()` https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_char-length
PGSQL: `LENGTH()` https://www.postgresql.org/docs/9.1/static/functions-string.html
SQLITE: `LENGTH()` https://sqlite.org/lang_corefunc.html#length

2017-05-26 17:15 UTC, tomneedham commented
Hmm, DBAL doesnt handle `length` - only the ORM does http://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.Query.AST.Functions.LengthFunction.html

2017-05-27 05:47 UTC, DeepDiver1975 requested changes

2017-05-27 05:47 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +			return strlen($term) <= 255;
Why not cut it off instead of fully skipping

2017-05-29 12:45 UTC, PVince81 commented on lib/private/User/User.php
> +			return strlen($term) <= 255;
@butonic cut or keep ?

there is also another ticket where @butonic suggests splitting terms on white spaces which should prevent overflows to occur in most cases

2017-05-29 12:47 UTC, PVince81 commented
@tomneedham so we need to extend our query builder. Make the default "LENGTH" and have a special case in the MySQL adapter for "CHAR_LENGTH"

2017-05-30 08:06 UTC, tomneedham commented on lib/private/User/User.php
> +			return strlen($term) <= 255;
I felt like cut off would just cause unpredictable behaviour, but then since we are searching from the beginning of these strings I guess even keeping the beginning could still be helpful.

2017-05-30 08:48 UTC, tomneedham commented
TODO now:
 - Add a test that the migration deletes rows with length > 256
 - Add a test that the expression builder length method works correctly cross DB

2017-06-02 09:48 UTC, FlyingPersian commented
When will this be updated on the main homepage as well? I'm still getting the SQLight error when downloading the install from the website. Also, I can't seem to be able to run this one when I download it. Seems that I need to compile it first?

2017-06-02 14:15 UTC, PVince81 commented
@FlyingPersian well first the fix must be finished and merged. Then it must be released as part of 10.0.3. And then we can update the web page and the owncloud-latest.zip link that the web installer uses to use 10.0.3.

If you're in a rush you can try installing from tarball directly and apply the patch manually before running the setup. (or manually changing that 256 value to 255 instead of patching)

2017-06-02 14:34 UTC, FlyingPersian commented
@PVince81: Alright, I tried adding the following three lines to the lib/private/User/User.php file, but the error still pops up:

```
// Check length of terms
		$terms = array_filter($terms, function($term) {
			return strlen($term) <= 255;
```

It basically looks like this now: http://i.imgur.com/aa1SqRY.png  
I downloaded 10.0.2, extracted it, copied over my data folder and config.php file, added the three lines, set permissions with the permissions script, turned on maintenance mode, and then used the "occ upgrade" command to upgrade. That's when the errorr pops up.

> Updating database schema
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing '                                                                                                             CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, accou                                                                                                             nt_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_ind                                                                                                             ex (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET                                                                                                              utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too lo                                                                                                             ng; max key length is 767 bytes
Update failed>

2017-06-02 14:37 UTC, PVince81 commented
@FlyingPersian I suggest to start over again (without what you patched) and use my simple instruction from https://github.com/owncloud/core/issues/28007#issuecomment-305442946. There is only one place to change to get a successful install.

The rest of the PR here is only relevant if you're going to use LDAP.

2017-06-02 15:17 UTC, butonic commented on lib/private/User/User.php
> +			return strlen($term) <= 255;
for now cut off. texts usually start with the most important information.

2017-06-05 12:09 UTC, tomneedham commented
@FlyingPersian You can also disable mysql strict mode. @PVince81 this is the best solution / advice here, it will truncate the index as necessary, then this PR will fix the column in the next release.

2017-06-05 12:12 UTC, tomneedham commented
With mb4 support i believe the max index length is actually 191 characters. https://serversforhackers.com/mysql-utf8-and-indexing

2017-06-05 14:39 UTC, tomneedham commented
Updated to reflect research into using 4 byte character sets. 191 is the max indexable string of characters.

2017-06-21 15:07 UTC, PVince81 commented
Please rebase since the migration itself was merged separately.

2017-06-21 22:33 UTC, tomneedham commented
@PVince81 the oc_migration fix is unrelated - but is 'technically' the same issue -> too long columns

2017-06-22 08:07 UTC, PVince81 approved these changes
:+1:

2017-06-22 08:08 UTC, PVince81 commented
@tomneedham please increase version.php then merge. This is needed to trigger new migrations else it won't check them at all.

2017-06-26 08:31 UTC, tomneedham commented
Set version to 10.0.2.3 because of https://github.com/owncloud/core/pull/28182

2017-06-27 13:52 UTC, tomneedham commented
kicked jenkins

2017-07-03 12:29 UTC, merged

2017-07-03 12:29 UTC, PVince81 commented
@tomneedham please backport