Only VEVENT for birthday calendar and default order to 1
owncloud/core pull request #28011
Opened 2017-05-25 13:23 UTC by tomneedham

## Description
New calendars are given a default order of 1, to always be after the default birthday calendar.

The system birthday calendar is created with VEVENT only, not VTODO as this is not possible.

## Motivation and Context
Causes issues when the birthday calendar is used for accepting events or if TODOs are created in that calendar.

## How Has This Been Tested?
 - New install and observing the created calendars
before:
![screen shot 2017-05-25 at 14 17 58](https://cloud.githubusercontent.com/assets/660805/26451849/9e82ea88-4155-11e7-8f87-d5702c93f004.png)
after:
![screen shot 2017-05-25 at 14 19 26](https://cloud.githubusercontent.com/assets/660805/26451851/a1b2886c-4155-11e7-9c22-b5f7e948ee41.png)

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-25 13:44 UTC, tomneedham commented
@DeepDiver1975 I can't find the code path for accepting an event from another user and where it is inserted into your calendar? Wanted to check where the logic is for choosing the calendar to insert it into.

2017-05-25 13:54 UTC, tomneedham commented
@DeepDiver1975 hmm so I see there is already a migration to fix this - https://github.com/owncloud/core/pull/25636/files but annoyingly the fix didn't work. How often is that repair step called - as we still have corrupt birthday calendars

2017-05-26 07:13 UTC, DeepDiver1975 commented
fixes https://github.com/owncloud/core/issues/26746 ❓

2017-05-26 07:16 UTC, DeepDiver1975 commented
> @DeepDiver1975 I can't find the code path for accepting an event from another user and where it is inserted into your calendar? Wanted to check where the logic is for choosing the calendar to insert it into.

It is within the sabre dav libs:

this propfind handles the calendar selection - https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L240
this is where the local delivery happens - https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L444

2017-05-26 07:29 UTC, DeepDiver1975 commented
> @DeepDiver1975 hmm so I see there is already a migration to fix this - https://github.com/owncloud/core/pull/25636/files but annoyingly the fix didn't work. How often is that repair step called - as we still have corrupt birthday calendars

best would be to add a migration from my pov

2017-05-26 09:22 UTC, tomneedham commented
> fixes #26746 ❓

yes should do - since I just push the birthday to the bottom of the users list

2017-07-07 06:42 UTC, DeepDiver1975 requested changes

2017-07-07 06:42 UTC, DeepDiver1975 commented on apps/dav/appinfo/Migrations/Version20170526100342.php
> -		$output->info("$updated birthday calendars updated.");
lets keep the logging in here

2017-07-07 06:57 UTC, DeepDiver1975 approved these changes

2017-07-07 12:14 UTC, merged