64bit mtime
owncloud/core pull request #28067
Opened 2017-06-02 06:54 UTC by individual-it

## Description
allow to store mtime as 64bit int
build on top of #28066

## Related Issue
#23228

## Motivation and Context
the database should hold 64bit int to be able to store dates after 2038

## How Has This Been Tested?

run new tests against pgsql, mysql & sqlite on PHP 7.1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-02 14:17 UTC, PVince81 commented on db_structure.xml
> +				<length>8</length>
we need to use the new DB migrations approach to make DB changes, don't reuse the old db_structure.xml.

See https://doc.owncloud.org/server/10.0/developer_manual/app/schema.html

2017-06-02 14:17 UTC, PVince81 commented
If all databases can deal with it then why not.

2017-06-07 11:36 UTC, individual-it commented
@PVince81 is that the correct way of changing the DB Structure?

according to the [documentation](https://doctrine-orm.readthedocs.io/projects/doctrine-dbal/en/stable/reference/types.html#bigint) `bigint` will be converted to PHP's `string` type

I can imagine 2 problems with that:

1. on 32bit systems we could theoretically have a wrong mtime if a long string is casted to int. But that should not happen because there is no way to enter a value bigger than `PHP_INT_MAX`. Except of course somebody writes the value directly to the DB or moves a DB with files that are far in the future or past from a 64bit system to a 32bit system. So I think this is more of a theoretical problem.
2. in places where `mtime` is used without being casted to `int` but compared with `===` the code will fail

2017-06-13 07:22 UTC, individual-it commented
rebased on current master

2017-06-13 07:43 UTC, phil-davis approved these changes
Looks good, assuming the Jenkins runs some time and passes. As long as the actual storage filesystems also support setting 64-bit then that gets us well past the end of the sun and practical heat death of the universe.
http://ximalas.info/2015/03/10/when-does-the-64-bit-unix-time_t-really-end/

2017-06-19 08:17 UTC, DeepDiver1975 requested changes

2017-06-19 08:17 UTC, DeepDiver1975 commented on apps/dav/appinfo/Migrations/Version20170607100912.php
> +		foreach ( array ('mtime','storage_mtime') as $column ) {
I prefer short array syntax

```php
['mtime', 'storage_mtime']

2017-06-19 08:17 UTC, DeepDiver1975 commented on apps/dav/appinfo/Migrations/Version20170607100912.php
> +			if ($table->getColumn($column)->getType()->getName() === 'integer') {
use Type::INTEGER instead of explicit string

2017-06-19 08:17 UTC, DeepDiver1975 commented on apps/dav/appinfo/Migrations/Version20170607100912.php
> +}
please undo this commit ;-)

2017-06-19 09:51 UTC, individual-it commented on apps/dav/appinfo/Migrations/Version20170607100912.php
> +}
uppps, I meant to delete an empty like to make jenkins start again.
Surprised that the tests did pass.

2017-07-04 09:52 UTC, PVince81 commented
Would be good to do a quick test on a 32 bit system (VM or rasperry pi) to confirm that it doesn't break anything

2017-07-04 14:45 UTC, PVince81 commented
uh oh https://github.com/owncloud/files_texteditor/pull/172 ?! do we need to support float mtimes ?

2017-07-04 15:29 UTC, phil-davis commented
We thought about this. Modern file systems happily keep a record of mtime and the like to some fractions of a second. e.g. I think something like:
ext4 nanoseconds
UFS - ?
FAT - 2 seconds
exFAT - 10 milliseconds
NTFS - 100 nanoseconds

Rather than using float, the database could store the int nanoseconds (traditional unix timestamp seconds x 10^9). According to my calculations, (2^63)/(60*60*24*365*10^9) is about 292. That would allow storing times +-292 years from 1970. Enough for normal files, and dates that current people might have been born etc,

Or it can store the current seconds (in 64 bit to include the beginning and end of the universe) and add another 64-bit field for the nanoseconds offset.

That allows actual timestamps from ext4 and similar to be remembered in the database.

Some issues are:
1) What is the actual resolution of the backend storage that the server happens to have? What to do about having a potentially more accurate timestamp in the database than in the file system?
2) Clients will have local file systems with different resolutions. So if they are provided nanosecond resolution when they download a file, actually they cannot store that in their local filesystem. So what will they do in the future when comparing local and server time stamps? (if the client also has its own database, then it can remember the nanosecond timestamps itself)

2017-07-13 09:15 UTC, individual-it commented
I've run the unit tests on a 32bit system with PHP 5.6 and they are passing on sqlite & mysql
on a 32bit system it would not be possible to store dates > 2038 because the mtime is always cast to int https://github.com/owncloud/core/pull/28066

2017-08-07 13:53 UTC, PVince81 approved these changes
Fine 👍 

Please rebase once to refresh CI

2017-08-08 02:42 UTC, individual-it commented
rebased, @DeepDiver1975 are you happy with the changes?

2017-08-21 07:56 UTC, DeepDiver1975 requested changes
We might want to rebase this one and see for conflicts

2017-08-21 07:56 UTC, DeepDiver1975 commented on apps/dav/tests/unit/Connector/Sabre/FileTest.php
> +					'expected result' => ($this->supportsNegativeMtime() ? (PHP_INT_MAX * - 1) : 0)
I killed this function a few days back - didn't I?

2017-08-22 09:55 UTC, individual-it commented
@DeepDiver1975 rebased the branch.
UI tests are failing because of https://github.com/owncloud/core/issues/28748

2017-08-22 09:59 UTC, DeepDiver1975 approved these changes

2017-08-22 09:59 UTC, merged

2017-08-22 09:59 UTC, DeepDiver1975 commented
@PVince81 shall we backport this?

2017-08-31 10:26 UTC, PVince81 commented
Later maybe, I don't feel safe about this

2017-09-09 08:23 UTC, PVince81 commented
@individual-it please backport for 10.0.4 so we can have it in an early beta

2017-09-09 10:44 UTC, phil-davis commented
Backport stable10 #28961

2017-09-28 11:30 UTC, phil-davis commented
Note: the migration code is being moved from dav to core in #29120