[WIP] unify config log options
owncloud/core pull request #28124
Opened 2017-06-13 15:06 UTC by butonic

The current config option naming is a grown mess. This pr changes the logging options and introducas fallback code. I did not yet add logging, because during config reading the logger is not yet initialized ... might add a shutdown function to do that.

Any other logging related options I should add?

2017-06-13 15:07 UTC, butonic commented
- [ ] add Documentation PR

2017-06-13 15:19 UTC, phil-davis commented on lib/private/Config.php
> +			$config['log.type'] = $config['log_type'];
Should the old keys be unset?

2017-06-13 20:05 UTC, butonic commented on lib/private/Config.php
> +			$config['log.type'] = $config['log_type'];
I was thinking of leaving them in, but yes, they should go ... still thinking about a way to best log usage of deprecated keys

2017-06-14 01:28 UTC, phil-davis commented on lib/private/Config.php
> +			$config['log.type'] = $config['log_type'];
Or have an upgrade step that updates old values in the config and write back to it, then forget that the old values ever existed.
There will also be the issue that in the comment text in the config there could be mentions of the old config keys (e.g. when copied from the sample config, or typed in by a sysadmin themselves explaining why they set something), and that will be misleading if the real key is updated but nit the comment.

2017-07-04 09:05 UTC, PVince81 requested changes
Please log a warning when keys cannot be updated because of readonly config.php

2018-02-15 15:50 UTC, PVince81 commented
continue or abandon ?

2019-02-08 14:55 UTC, PVince81 commented
I'd vote for abandon as this would need more work to provide key migrations, and there isn't much benefit so far in making this change

2019-02-12 14:50 UTC, butonic commented
will change anyway ...

2019-02-12 14:50 UTC, closed without merging