use X-Request-ID header as request  if provided by client
owncloud/core pull request #28144
Opened 2017-06-16 13:44 UTC by butonic

If clients send a request id we can identify the client request also in the apache and owncloud logs.
for apache the log rule needs to log the X-Request-ID environment variable

- [ ] tests, but I need to run

related:
* https://github.com/owncloud/client/issues/5647#issuecomment-298224016

also see
* https://atech.blog/viaduct/x-request-id
* https://serverfault.com/a/797611

2017-06-16 13:47 UTC, butonic commented
cc @jturcotte regarding the X-Request-ID header

2017-06-16 21:02 UTC, butonic commented
I added a few more chars to allow writing timestamps. But I don't want to allow `"`, `'`, `%` or `\` because the former two might interefere with the quotes in the JSON log. `%` might introduce url encodings and `\` is the escape char ... comments welcome.

Also ... while HEROKU just replaces invalid request IDs I want to fail early and hard ... which is why I throw the exception. Opinions?

2017-06-19 08:30 UTC, DeepDiver1975 commented
@butonic please fix le tests

![bildschirmfoto von 2017-06-19 10-30-04](https://user-images.githubusercontent.com/1005065/27276093-507f35d8-54da-11e7-8dc5-067e8cacbe85.png)

2017-06-19 08:30 UTC, DeepDiver1975 requested changes
fix le tests

2017-06-20 12:23 UTC, butonic commented
@DeepDiver1975 I fixed le tests

2017-06-22 07:12 UTC, DeepDiver1975 approved these changes

2017-06-22 07:12 UTC, merged

2017-10-27 14:30 UTC, michaelstingl commented
@butonic Backport to 10.0.x to release also with 10.0.4?

2017-11-03 13:17 UTC, PVince81 commented
@butonic please backport

2017-11-06 16:23 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/29434