Change to re-create masterkeys
owncloud/core pull request #28145
Opened 2017-06-16 13:59 UTC by sharidas

This change will help users to recreate masterkey
for encryption.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change will help users to regenerate masterkeys for encrypting data

## Related Issue

https://github.com/owncloud/enterprise/issues/2033

## Motivation and Context

This change will help users to regenerate masterkey. In current state masterkey once enabled cannot be changed. This change addresses the issue.

## How Has This Been Tested?

Using occ command created users admin and user1. Enabled encryption app and then tried to enable masterkey. Now open the UI and try to login to both admin and user1. Verify the welcome.txt file is encrypted using cat command. As admin user navigate to encryption page and then click "Create new master key" button. And then  relogin as admin user. Then navigate to encryption page and click "Encrypt files". Reload the web page or try to navigate to home page, user can see the welcome.txt is again encrypted. Verified by checking the file names generated as public and private keys. Both were different compared to first login. cat the welcome.txt of both admin and user1. Both are encrypted.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-16 14:57 UTC, tomneedham commented on apps/encryption/js/settings-admin.js
> +		console.log("I am clicked");
debug

2017-06-16 14:59 UTC, tomneedham commented on lib/private/Encryption/DecryptAll.php
> +			debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
debug

2017-06-16 15:54 UTC, sharidas commented
@tomneedham Thanks for pointing it out. Removing them :)

2017-06-21 08:25 UTC, PVince81 requested changes
If this is running within a single ajax request then this is a no go. Decrypting and reencrypting all files within a PHP request is very likely to run into PHP timeouts.

Also, if I understand correctly, this would decrypt all files on disk first then reencrypt. It would be better (but also much more complex to implement here) to decrypt with old key and reencrypt on the fly with new key, to avoid having the files exposed for a short period of time.

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +		\OC::$server->getLogger()->warning(__METHOD__." so time to create new key!!!", ['app' => __CLASS__]);
use a better message or remove ?

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +			\OC::$server->getAppConfig()->deleteApp('encryption');
this looks a bit hacky. Can we just delete the relevant keys instead of destroying everything and reenabling ?

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +			\OC::$server->getConfig()->deleteAppValues('encryption');
what's the difference between `deleteApp` above and `deleteAppValues` ? Doesn't this do the same ?

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +			\OC_App::enable('encryption');
use app manager if possible

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +			\OC::$server->getConfig()->deleteAppValue('files_encryption','installed_version');
receive `IConfig` injected in the constructor and use it instead of `getConfig()`.

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/lib/Controller/MasterKeyController.php
> +					echo "\n Entering user $user\n";
`echo` ???

2017-06-21 08:25 UTC, PVince81 commented on apps/encryption/js/settings-admin.js
> +			OC.generateUrl('/apps/encryption/ajax/reencryptFiles')
this will very likely run into PHP timeouts... would recommend only providing OCC command for this

2017-06-21 08:25 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +			\OC::$server->getAppConfig()->deleteApp('encryption');
dejavu ? I've seen this code before somewhere above

2017-07-04 11:18 UTC, sharidas commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +			$encryptedVersion = 1;
This change comes from https://github.com/owncloud/core/pull/28107. The rename operation is happening at https://github.com/owncloud/core/blob/04c958ae7464b5e17ba7e7c0e9ff0552f64ea47f/apps/encryption/lib/Command/RecreateMasterKey.php#L224

2017-07-04 11:19 UTC, sharidas commented on apps/encryption/lib/Command/RecreateMasterKey.php
> +			sleep(3);
I don't like this. Any better suggestion would be nice. It takes some time to regenerate new master keys.

2017-07-04 16:39 UTC, PVince81 commented on apps/encryption/lib/Command/RecreateMasterKey.php
> +			sleep(3);
how is that even possible ? PHP is sequential, what is it waiting for ?

AFAIK all of the openssl commands are synchronous

2017-07-04 17:19 UTC, sharidas commented on apps/encryption/lib/Command/RecreateMasterKey.php
> +			sleep(3);
It's waiting for the new master keys. The code execution happens sequentially.

2017-07-04 17:22 UTC, PVince81 commented on apps/encryption/lib/Command/RecreateMasterKey.php
> +			sleep(3);
In this case `sleep` is useless because it will block the PHP process.

If adding it solves the problem then it means there is some background / async process running somewhere, and that's not good because it means potential race conditions in other parts of the code.

2017-07-04 17:24 UTC, PVince81 commented on apps/encryption/lib/Command/RecreateMasterKey.php
> +			sleep(3);
and reading the code above I don't see any code that would spawn a separate process ? which line is starting the process that generates the new master key ?

2017-07-05 05:58 UTC, sharidas commented
Removed the ugly while loop which waited to create the masterkey. Instead in the keymanager I created the function which creates the masterkey and publicsharekey. And reused the same in the constructor.

2017-07-13 09:47 UTC, PVince81 commented
@sharidas failling unit tests, please fix

2017-07-31 11:01 UTC, sharidas commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +			$encryptedVersion = 1;
I will remove this change now.

2017-07-31 14:52 UTC, sharidas commented
Need review for this change too... This is the followup of https://github.com/owncloud/encryption/pull/6

2017-07-31 14:56 UTC, PVince81 requested changes
too hacky

2017-07-31 14:56 UTC, PVince81 commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +		//if ( \OC::$server->getAppConfig()->getValue('encryption', 'enabled', false) !== false) {
remove ?

2017-07-31 14:56 UTC, PVince81 commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +						if (\OC::$server->getSession()->get('decryptAllCmd') === true) {
arghh, no, that's too hacky

2017-07-31 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=28145) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=28145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=28145) it.</sub>

2017-07-31 17:21 UTC, sharidas commented
@PVince81 , Modified changes to some of the core API's. Removed the session hack from the code.

2017-08-01 07:22 UTC, PVince81 commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +	public function fopen($path, $mode, $sourceFileOfRename = null, $getDecryptedFile = false) {
This feels wrong and unintuitive.

Also I don't understand: the encryption wrapper always gives access to decrypted data. fread/fwrite operations are using decrypted data. Maybe what you meant here is that you want to access the encrypted binary data directly by skipping this wrapper.

So the key here is likely to find a way to skip/disable the encryption wrapper to get access to the file. Not sure how complicated this could be.

2017-08-28 14:07 UTC, sharidas commented
Obsolete PR. The final PR: https://github.com/owncloud/core/pull/28774

2017-08-28 14:07 UTC, closed without merging