Ui tests support skip
owncloud/core pull request #28140
Opened 2017-06-15 10:23 UTC by phil-davis

## Description
1) By default, ignore scenarios in UI tests that are are tagged with "@skip". Thus in automated builds or default runs of UI tests locally, scenarios tagged with "@skip" will not be run.
2) Allow the caller to specify the tag(s) of scenarios that they want to run. e.g. to locally run just the "@skip" scenarios:
```
./start_behat_tests.sh --tags "@skip"
```
3) Allow the caller to specify "no tags" so they can override the default behavior of not running "@skip" tags, so that all of both ordinary and "@skip" scenarios will run:
```
./start_behat_tests.sh --tags ""
```

## Related Issue

## Motivation and Context
Sometimes tests are developed that will fail because actually they have found a bug that needs to be fixed. It is not good practice to have tests running in master that "normally fail", because then people get used to "oh, the tests always fail". But also it is good to have the test configured so it can be run as desired (e.g. when a developer is fixing the bug) and then remove the "@skip" tag in the PR that fixes the bug.

## How Has This Been Tested?
Run the combinations of commands described above in a local VM while developing tests that display the bug described in https://github.com/owncloud/core/issues/28129 - it lets me easily run just the passing tests, just the skipped test(s) or all the tests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Travis will tell if the default works OK still.

I will update developer doco about how to run UI tests locally, once this PR is agreed.

2017-06-15 10:35 UTC, individual-it requested changes
looks generally good to me, this can be also used to tag tests that should only be run on travis cron jobs. 
Or even introduce tags like "nightly", "weekly", "release", etc.

2017-06-15 10:35 UTC, individual-it commented on tests/travis/start_behat_tests.sh
> +	if [ "$BEHAT_TAGS_OPTION_FOUND" = true ]
could we do here something like
```
 if [ "$BROWSER" == "internet explorer" ]
 then
   BEHAT_TAGS_OPTION_FOUND = true
   BEHAT_TAGS='~@skipOnIE'
fi
```

and then let the `else` part just run all the time?

2017-06-16 08:19 UTC, phil-davis commented
@individual-it I refactored it so that the lib/composer/bin/behat command line can just appear once, followed by the various parameters as substituted vars. Please review again.

2017-06-16 08:19 UTC, individual-it approved these changes

2017-06-16 10:59 UTC, merged