Proper message shown when private links accessed
owncloud/core pull request #28172
Opened 2017-06-20 14:28 UTC by sharidas

When user tries to access private links which are
not accessible, then proper message is delivered
instead of Internal server error message. So is the
case when user is logged in and tries to access
private links not accessible.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change addresses 2 causes:
1) When user logged in and tries to access private link which is not accessible. Instead of internal server error, now it shows up a message.
2) When user is not logged in and tries to access link which is not accessible

## Related Issue

## Motivation and Context

This change tries to polish up the message to be shown when non accessible private links are accessed by user under: logged in and non logged in state respectively.

## How Has This Been Tested?

Created folder private which is accessed by another user under logged in and non logged in states. The messages are displayed on the browser.

## Screenshots (if appropriate):
![loggedin](https://user-images.githubusercontent.com/3600427/27338430-c55ccffa-55f2-11e7-8c9e-c45074b527c0.png)
![notloggedin](https://user-images.githubusercontent.com/3600427/27338437-ce153a6a-55f2-11e7-8f3a-763e8ca1e099.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-20 15:10 UTC, tomneedham commented
Logged out errors should use https://github.com/owncloud/core/blob/master/core/templates/error.php to be consistent and themeable

2017-06-20 15:59 UTC, sharidas commented
@tomneedham Thanks for the review. I have changed logged out errors to error.php as suggested.

2017-06-21 05:25 UTC, sharidas commented
Updating the screenshot : 
![loggout_screenshot](https://user-images.githubusercontent.com/3600427/27368425-1667087a-5670-11e7-8893-bc3f96860777.png)

2017-06-21 07:40 UTC, PVince81 commented
@sharidas hmm weird, I seem to remember that this used to work. But now I tried with v9.1.0 when the feature was introduced and I'm also getting internal server error for non-existing files. Maybe back then I forgot to test this case and only tested inaccessible files.

But throwing `NotFoundException` should actually trigger the router to automatically display the generic "not found" error page. Maybe something has changed that.

2017-06-21 07:41 UTC, PVince81 commented on core/Controller/LoginController.php
> +			return new TemplateResponse(
please use a generic error response page instead of defining a new template

2017-06-21 08:34 UTC, tomneedham commented
Yes my opinion was that you should just be catching some ForbiddenException and NotFoundExceptions properly here, not adding these new if conditions that look quite fragile.

2017-06-21 10:44 UTC, sharidas commented
Updated the PR again.

2017-06-21 15:05 UTC, PVince81 commented on core/Controller/LoginController.php
> +			$param["error"] = "Sorry, your request could not be handled properly, please check your actions and try again.";
I don't understand why this is needed.

If a user tries to open a link to a file and requires being logged in, the they simply see the login page and the link itself is in the redirect URL. Once they are logged in, the login controller must redirect to that URL and then the ViewController takes over.

2017-06-21 15:53 UTC, sharidas commented on core/Controller/LoginController.php
> +			$param["error"] = "Sorry, your request could not be handled properly, please check your actions and try again.";
True, If the user is not logged in then automatically the redirect goes to login page.

2017-06-21 18:46 UTC, DeepDiver1975 requested changes

2017-06-21 18:46 UTC, DeepDiver1975 commented on apps/files/lib/Controller/ViewController.php
> +			$param["error"] = "You don't have permissions to access this file/folder - Please contact the owner to share it with you.";
translation missing

2017-06-22 05:32 UTC, sharidas commented on apps/files/lib/Controller/ViewController.php
> +			$param["error"] = "You don't have permissions to access this file/folder - Please contact the owner to share it with you.";
Added translation to both ViewController and LoginController.

2017-06-22 06:40 UTC, DeepDiver1975 commented
@sharidas which state is this pr now? 2 or 3 - cannot be both ;-)

2017-06-22 06:47 UTC, sharidas commented
@DeepDiver1975 I have removed 2. Once I get any feedback I will add 2 ( if required ) and remove 3. Now made as 3.

2017-06-22 08:13 UTC, PVince81 commented on core/Controller/LoginController.php
> +			$param["error"] = "Sorry, your request could not be handled properly, please check your actions and try again.";
can you remove this then ? why do we need it then ?

2017-06-22 15:16 UTC, pmaier1 commented
@sharidas yes, if not logged in a redirect to login page makes sense, of course. Maybe you could add a hint as in e.g. https://github.com/owncloud/oauth2/issues/43#issue-235171514 saying "You are trying to access a private link. Please log in first."

2017-06-23 10:05 UTC, sharidas commented
Attaching screenshot of latest login screen message : 
![newloginscreeprivatelinkaccesss](https://user-images.githubusercontent.com/3600427/27477380-9d7fdcaa-5829-11e7-8b4b-f13b3bb08379.png)

2017-06-23 18:42 UTC, PVince81 commented on core/Controller/LoginController.php
> +			$parameters['accessLink'] = true;
call it "reason" or something ? that would make that parameter reusable to be able to display message in other cases. I'm pretty sure there are a few more we could cover.

2017-06-29 14:37 UTC, sharidas commented on core/Controller/LoginController.php
> +			strpos(urldecode($redirect_url), $fpath) !== false) {
I tried with private link ( in my machine ), lets say with http://localhost/testing/index.php/f/17 and the result was appropriate. Screenshot as below:
![screenshot_20170629_200215](https://user-images.githubusercontent.com/3600427/27693085-0b3ff578-5d06-11e7-91d4-c303c78b28e7.png)

For testing if I changed the URL to lets say http://localhost/testing/index.php/foobar or http://localhost/testing/index.php/f/1/c it directly takes me to the login page.
Lot of if's doesn't look nice, though. Any suggestions regarding this?

2017-07-03 08:15 UTC, PVince81 commented on core/Controller/LoginController.php
> +			strpos(urldecode($redirect_url), $fpath) !== false) {
No idea, sorry. Might need digging into the auth / routing code.

2017-07-10 08:02 UTC, PVince81 commented on core/Controller/LoginController.php
> +		$fpath = \OC::$WEBROOT. "/index.php/f/";
please use the route generator instead, like in https://github.com/owncloud/core/blob/master/lib/private/Share/MailNotifications.php#L123

2017-07-13 09:46 UTC, PVince81 commented
@sharidas I see unit test failures, please have a look

2017-07-24 06:25 UTC, PVince81 commented on core/Controller/LoginController.php
> +			$link = $this->urlGenerator->linkToRouteAbsolute('files.viewcontroller.showFile', ['fileId' => $fileId]);
hmm, why not just reuse the redirect url directly instead of regenerating the link this way ?

2017-07-24 08:39 UTC, sharidas commented on core/Controller/LoginController.php
> +			$link = $this->urlGenerator->linkToRouteAbsolute('files.viewcontroller.showFile', ['fileId' => $fileId]);
For example in my machine while testing, the redirect url has value: ```%2Ftesting%2Findex.php%2Ff%2F17```. I was trying to access : ```http://localhost/testing/index.php/f/17```. So if I pass the fileid ```17``` to linkToRouteAbsolute, the url matches with the ```http://localhost/testing/index.php/f/17```. Inorder to extract the fileid I did the steps in the PR.

So my intention was to check if redirect url a substring of newly created link.

2017-07-24 09:18 UTC, PVince81 commented on core/Controller/LoginController.php
> +			$link = $this->urlGenerator->linkToRouteAbsolute('files.viewcontroller.showFile', ['fileId' => $fileId]);
@sharidas I still don't understand why you don't directly use the value of "redirect_url". The purpose of this variable is to contain the actual target page to open, else this value is completely useless.

2017-07-24 11:52 UTC, sharidas commented on core/Controller/LoginController.php
> +			strpos(urldecode($this->urlGenerator->getAbsoluteURL(urldecode($redirect_url))),
Modified the code . A check is done if getAbsoluteURL($redirect_url) contains string getAbsoluteURL('index/f/').

2017-08-02 14:26 UTC, sharidas commented on core/Controller/LoginController.php
> +			(strpos(urldecode($this->urlGenerator->getAbsoluteURL(urldecode($redirect_url))),
This is one way to reuse ```redirect_url``` and check if url ```urldecode($this->urlGenerator->getAbsoluteURL('/index.php/f/')``` in it.

2017-08-02 15:03 UTC, PVince81 approved these changes
Fine by me 👍

2017-08-03 14:55 UTC, PVince81 commented
@DeepDiver1975 another case of "ran for 7 hours and still running"

2017-08-03 16:25 UTC, DeepDiver1975 requested changes

2017-08-03 16:25 UTC, DeepDiver1975 commented on apps/files/lib/Controller/ViewController.php
> +			$l = \OC::$server->getL10N("core");
inject l10n?

2017-08-03 16:25 UTC, DeepDiver1975 commented on core/Controller/LoginController.php
> +			(strpos(urldecode($this->urlGenerator->getAbsoluteURL(urldecode($redirect_url))),
that looks funny ....

2017-08-03 16:25 UTC, DeepDiver1975 commented on core/Controller/LoginController.php
> +				urldecode($this->urlGenerator->getAbsoluteURL('/index.php/f/'))) !== false)) {
why decode here? the result of getAbsoluteURL is already decoded

2017-08-07 10:02 UTC, merged

2017-08-07 10:02 UTC, PVince81 commented
@sharidas please backport to stable10

2017-08-15 16:56 UTC, PVince81 commented
@sharidas missing backport

2017-08-15 17:42 UTC, sharidas commented
https://github.com/owncloud/core/pull/28600 is the PR backported. Sorry for missing this link here.