Add inactive user command
owncloud/core pull request #28171
Opened 2017-06-20 14:18 UTC by tomneedham

## Description
Allows admins to retrieve a parsable list of users that have been seen at least once, but have been inactive for a certain amount of days (no login since then). Scriptable because json output is supported with `--output-json`.

Usage:
`./occ user:inactive 30` for all users who have no logged in for 30 days.

## Motivation and Context
Admins wanting reports on inactive users in their instances.

## How Has This Been Tested?
 - Created several users in the web UI
 - Ran the command and checked none of these users showed up
 - Altered the last_login times in the accounts table
 - Ran command and checked they appeared correctly

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-21 07:44 UTC, PVince81 commented on core/Command/User/Inactive.php
> +			throw new InvalidArgumentException('Days must be above zero');
also restrict to integers ?

2017-06-21 07:45 UTC, PVince81 commented on core/Command/User/Inactive.php
> +		$this->userManager->callForSeenUsers(function(IUser $user) use (&$inactive, $days) {
Sad that we can't just do a SQL query to retrieve those. The good thing at least is that the user manager now only operated on oc_accounts, not on remote systems.

2017-06-21 07:46 UTC, PVince81 commented on core/Command/User/Inactive.php
> +			$daysSinceLastLogin = floor((time() - $lastLogin) / (60*60*24));
For technical accuracy, I'd store `time()` in a variable before the loop. Imagine that if this loop takes several hours due to millions of entries, the value of `time()` will advance as well.

2017-06-21 07:49 UTC, PVince81 commented on tests/Core/Command/User/InactiveTest.php
> +			->method('callForSeenUsers');
Please also add a test that actually runs the function in the loop and checks the response format.

You should be able to use `->will($this->returnCallback(function($func) { ... })` and then call the function from within your callback with active and inactive users.

2017-06-21 07:49 UTC, PVince81 requested changes
Looks good in general, a few more minor tweaks would be nice.

Please add unit test for the callback.

2017-06-21 08:48 UTC, tomneedham commented on core/Command/User/Inactive.php
> +		$this->userManager->callForSeenUsers(function(IUser $user) use (&$inactive, $days) {
We can, since we're looking for oc_accounts where last_login != NULL, but I thought it was best to use the usermanager methods for this

2017-06-21 08:50 UTC, tomneedham commented on core/Command/User/Inactive.php
> +			$daysSinceLastLogin = floor((time() - $lastLogin) / (60*60*24));
Good call.

2017-06-21 08:51 UTC, PVince81 commented on core/Command/User/Inactive.php
> +		$this->userManager->callForSeenUsers(function(IUser $user) use (&$inactive, $days) {
Yes, you're right. I think this approach is fine if we want it backportable.

2017-06-22 06:43 UTC, DeepDiver1975 commented
isnt this something we can handle within the report command?

2017-06-22 06:51 UTC, tomneedham commented
could do, but i read the description of the report command: 
>shows how many users have access

and that didnt sound too similar to:
>reports users who are known to owncloud, but have not logged in for a certain number of days

so I made a new command :)

2017-07-04 08:56 UTC, PVince81 approved these changes

2017-07-04 08:56 UTC, PVince81 commented
Explanation makes sense 👍

2017-07-04 08:56 UTC, merged

2017-07-04 08:56 UTC, PVince81 commented
@tomneedham please backport to stable10, looks safe enough