Groups for occ command and UI testing
owncloud/core pull request #28190
Opened 2017-06-22 06:09 UTC by phil-davis

## Description
- Add group add, delete and removeuser to occ command (group add can also add users to a group)
- Add support for creating and removing groups withing the UI testing framework
- Use this to change/add some sharing autocompletion tests to include sharing with groups as well as users

## Related Issue
Addresses https://github.com/owncloud/core/issues/20629 to provide occ group command
for which some initial work happened in https://github.com/owncloud/core/pull/21627

Also part of providing base infrastructure for UI testing #27858 

## Motivation and Context
- It is useful to be able to manage groups from occ as well as users
- UI testing needs to be able to easily create groups and put users into groups during scenario setup
- File Firewall needs this to be able to test group rules

## How Has This Been Tested?
Self-testing - Travis does it

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Once this is accepted, the documentation of the occ group command needs to be done.

2017-06-22 06:13 UTC, phil-davis commented
@SergioBertolinSG this implements #20629 which is in 10.0 backlog. Having group commands in occ is very useful for the UI testing scenario steps, and will be useful for other things also (even sysadmins who want to create and manage groups from the command line)

2017-06-22 11:14 UTC, phil-davis commented
@PVince81 @DeepDiver1975 this expands functionality of ```occ``` to be able to manage groups and their members, so I called you in for review here.
The functionality is useful for acceptance testing - a simple and well-defined way to set up groups and membership ready for testing their behavior. But also would become available to real-life sysdamins who use ```occ```. Actually a place I used to work at wanted to manage group membership for certain groups by script that could read from some outside file and make the oC groups and their membership match. This ```occ``` group functionality would have made it easy.

2017-06-28 11:34 UTC, felixboehm commented
@PVince81 please review and set proper milestone. Thanks

2017-06-29 07:37 UTC, PVince81 commented on core/Command/Group/RemoveUser.php
> +					$output->writeln('<error>User "' . $userName . '" could not be found in group "' . $group->getGID() . '"</error>');
should this maybe affect the command's return code ? should we abort ?

2017-06-29 07:39 UTC, PVince81 commented
As a CLI user I'd be confused as to what command to use for adding users to a group. I know that `add` does it too but seeing it, it's not clear that the command can do both.

I'd prefer having separate commands with clearer names:
- group:add
- group:delete
- group:add-member
- group:remove-member

2017-06-29 07:40 UTC, PVince81 commented on core/Command/Group/Delete.php
> +			return;
return error code

2017-06-29 07:40 UTC, PVince81 commented on core/Command/Group/Delete.php
> +		$output->writeln('<error>The specified group could not be deleted. Please check the logs.</error>');
return error code

2017-06-29 07:42 UTC, PVince81 commented on core/Command/Group/Add.php
> +		$users = $input->getOption('user');
please move this to a separate command, much clearer from a user's perspective.

Also I guess that the current impl would not let you add users to an existing group as you'd get "Group already exists" which sounds like an error even though the code carries on.

2017-06-29 07:42 UTC, PVince81 requested changes
See comments.

Make sure to return an error code in all `execute` commands when non-zero. It can help with scripting.

Also note that `runOcc` can check said error code in case it's useful for testing.

2017-06-29 07:46 UTC, phil-davis commented on core/Command/Group/RemoveUser.php
> +					$output->writeln('<error>User "' . $userName . '" could not be found in group "' . $group->getGID() . '"</error>');
I wonder what to do in these sort of cases. The sysadmin has asked to remove user1 from group1. Actually user1 is already not in group1, so the requested state is already the case and the occ command is a NOOP.
Do we tell the sysadmin "the user is already not in the group"?
Do we mark the text as an error? (because actually what the sysadmin asked is done)
Do we return an error code, or success?

2017-06-29 07:48 UTC, phil-davis commented on core/Command/Group/Delete.php
> +			return;
Similar thing here - should this text even be highlighted as an error?
The sysadmin asked to delete the group, the group is not even existing, so it is indeed deleted.

2017-06-29 07:48 UTC, phil-davis commented on core/Command/Group/Delete.php
> +		$output->writeln('<error>The specified group could not be deleted. Please check the logs.</error>');
Yes, I better return an error code here - this one is the system having trouble!

2017-06-29 07:50 UTC, PVince81 commented on core/Command/Group/RemoveUser.php
> +					$output->writeln('<error>User "' . $userName . '" could not be found in group "' . $group->getGID() . '"</error>');
not sure, maybe check what other system tools do. Does "groupdel" on Linux return an error code ?

2017-06-29 13:03 UTC, phil-davis commented
I can do group:add group:addmember group:removemember and group:delete OK from the command line.
If I try to add a group that exists, or delete a group that does not exist I get an error.
If I try to add/remove members from a group that does not exist I get an error.
If I try to addmember or removemember using a user name that does not exist, I get an error.

If I addmember and some users are already in the group, I do not emit an error. IMHO that is an OK condition - a scripting person can do group:addmember for all the users that they want to be in the group and do not need to try and thin if they are already in the group.

Similarly, if I removemember and some users were already removed from the group, I do not emit an error. That lets a scripting person do removemember for any user(s) that they want to make sure are not in the group without worrying if they were already removed.

Let's see if CI is happy...

2017-06-29 16:24 UTC, phil-davis commented
I don't know what is the Travis problem. The Travis build that this links to is green, but here in GitHub it says pending.

2017-06-30 08:47 UTC, individual-it approved these changes
LGTM 👍

2017-06-30 08:59 UTC, PVince81 approved these changes
:+1:

2017-06-30 08:59 UTC, merged

2017-06-30 09:00 UTC, PVince81 commented
@phil-davis please backport to stable10.

Ignoring the old rule "don't backport new features". cc @DeepDiver1975 @felixboehm

2017-06-30 09:17 UTC, phil-davis commented
Actually, the reason to backport this is that
1) it provides infrastructure that allows both core and apps to implement UI tests that deal with groups
2) apps need to be able to find this infrastructure when being tested against stable10

the fact that it also provides an enhancement/feature to the occ command, which end-users will see and can use in 10.0.3, is actually just "collateral damage" :)

2017-06-30 09:19 UTC, phil-davis commented
and this has been, and will be, a common thing for both new test infrastructure and new tests. Generally-speaking it will be "a good thing" that a more extensive set of automated tests runs in the 10.0.* series.

2017-06-30 09:21 UTC, PVince81 commented
@phil-davis thanks, makes sense

2017-06-30 09:34 UTC, phil-davis commented
@PVince81 to backport, it needs #28188 backport to be merged first into stable10.

2017-07-04 16:31 UTC, mmattel commented
@PVince81 @phil-davis 
Please add a documentation PR for this occ command.
I do not see a reference nor a PR in the documentation repository...

2017-07-05 03:42 UTC, phil-davis commented
Doc PR https://github.com/owncloud/documentation/pull/3201 created.

2017-07-05 07:38 UTC, mmattel commented
Q: maybe I missed that:
why don't we have a parameter for listing existing groups and listing existing users in a particular group?

2017-07-05 07:51 UTC, phil-davis commented
@mmattel that is a good question that I also asked myself. But I did not want to start expanding beyond what I really needed because then people might review and say "why did you add xyz?"

IMHO it would be very handy for oC admins to be able to list users and groups from the command line.

2017-07-05 08:46 UTC, mmattel commented
@phil-davis mind to add this list functinality?