loginController now emitting preLogin hook before failed login attempts
owncloud/core pull request #28206
Opened 2017-06-24 16:46 UTC by karakayasemi

## Description
There is an error in the logic of emitting preLogin signal in the LoginController. UserSession's login function is checking password and emitting preLogin signal, but loginController is either checking password before UserSession and returning view response without hook signal when failed login attempts.

With this change, unnecessary checkPassword functions are removed. Code simplified and now we are emitting preLogin hook also before failed login attempts.
## Motivation and Context
preLogin hook is not emitting on failed login attempts. 

## How Has This Been Tested?
Unit tests are working

## Types of changes
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2017-06-25 19:16 UTC, DeepDiver1975 requested changes

2017-06-25 19:16 UTC, DeepDiver1975 commented on core/Controller/LoginController.php
> +		$emailUsers = $this->userManager->getByEmail($user);
this totally removes the capability to login with the login name - right?

2017-06-25 19:16 UTC, DeepDiver1975 commented on core/Controller/LoginController.php
> +		if($this->userSession->login($user, $password) !== true) {
so login is enough - we not longer need to call checkPassword? looks strange ....

2017-06-25 19:16 UTC, DeepDiver1975 commented
an please squash your commits - thx

2017-06-26 07:37 UTC, karakayasemi commented on core/Controller/LoginController.php
> +		if($this->userSession->login($user, $password) !== true) {
login is also using userManager's checkPassword inside of it with emitting hook signal before and after checkPassword. IMHO we can trust login.

2017-06-26 07:43 UTC, karakayasemi commented on core/Controller/LoginController.php
> +		$emailUsers = $this->userManager->getByEmail($user);
If someone is trying to login with uid, getByEmail does not return anything. If a user's uid is the same as another user's email, it creates a problem.

2017-06-26 08:34 UTC, karakayasemi commented
I messed up trying to squash. Trying to resolve, but i am not a git expert.

2017-06-26 16:52 UTC, DeepDiver1975 commented
We miss a login failed hook - right?

2017-06-28 08:41 UTC, karakayasemi commented
we can add login failed hook to userSession's login method. However, I am not sure, where should we emit login failed signal also? For now, this change allows to use preLogin hook and it is enough to start security app. Should I work on login failed hook?
And also should I revert e-mail login part of the code? IMHO, it is simplifying logic and does not create any problem unless if a user's uid is the same as another user's email.

2017-06-28 09:06 UTC, DeepDiver1975 commented
> And also should I revert e-mail login part of the code? IMHO, it is simplifying logic and does not create any problem unless if a user's uid is the same as another user's email.

yes please - we shall keep the behavior

2017-06-28 09:07 UTC, DeepDiver1975 commented
> we can add login failed hook to userSession's login method. However, I am not sure, where should we emit login failed signal also? For now, this change allows to use preLogin hook and it is enough to start security app. Should I work on login failed hook?

we need that hook to log a failed login - or am I missing something?

2017-06-28 09:31 UTC, karakayasemi commented
> we need that hook to log a failed login - or am I missing something?

IMHO, Login hook signal should emit from UserSession's login method. Since failed login check is done by userManager's checkPassword method in our current password correction logic, we can not emit any hook signal from userSessions login method in failed login attempts. Because of that, I removed checkPassword methods and used userSession's login function.
I will try to make changes you said in today.

2017-06-28 11:03 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +			$this->manager->emit('\OC\User', 'failedLogin', [$uid, $password]);
shall we really expose the password?

2017-06-28 11:13 UTC, karakayasemi commented on lib/private/User/Session.php
> +			$this->manager->emit('\OC\User', 'failedLogin', [$uid, $password]);
I thought, maybe it can be useful for some warning like "it is your previous password".

2017-06-29 08:44 UTC, karakayasemi commented on lib/private/User/Session.php
> +			$this->manager->emit('\OC\User', 'failedLogin', [$uid, $password]);
Should I change password exposition? Still, I think it might be useful in fact.

2017-06-29 14:00 UTC, DeepDiver1975 commented on lib/private/User/Session.php
> +			$this->manager->emit('\OC\User', 'failedLogin', [$uid, $password]);
I would not expose the password here - @Peter-Prochaska objections?

2017-06-29 15:58 UTC, phil-davis commented on lib/private/User/Session.php
> +			$this->manager->emit('\OC\User', 'failedLogin', [$uid, $password]);
As a user, I might have accidentally put in a password for an account of mine on some other site, so would rather not have it displayed/logged... anywhere.

2017-06-30 04:43 UTC, karakayasemi commented
Now, failed login hook is exposing the only username.

2017-07-04 08:33 UTC, PVince81 commented
@DeepDiver1975 is this now acceptable for merging ?

2017-07-04 09:54 UTC, DeepDiver1975 approved these changes

2017-07-04 09:54 UTC, merged

2017-08-09 07:46 UTC, PVince81 commented
This introduced a regression which was now fixed in https://github.com/owncloud/core/pull/28450