Redirect a download to the direct download url if provided
owncloud/core pull request #28250
Opened 2017-06-28 15:20 UTC by DeepDiver1975

## Description
In case a storage supports direct download - like S3 with the presigned urls - we make use of it and redirect the download to the storage.

## Motivation and Context
Scale out to the storage and remove load from the owncloud server.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-28 15:25 UTC, DeepDiver1975 commented
@moscicki  @labkode you might be interested in this as well .....

2017-06-28 20:53 UTC, butonic commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +			return;
false ? true ? null ?

2017-06-28 20:57 UTC, butonic commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +		return;
false ? true ? null ?

2017-06-28 20:57 UTC, butonic commented on lib/public/Files/ObjectStore/IObjectStore.php
> +	function getDirectDownload($path);
where is the swift implementation?

2017-06-28 20:57 UTC, butonic commented on lib/public/Files/ObjectStore/IObjectStore.php
> +	function getDirectDownload($path);
are you planning to handle NotImplemented exceptions? or better use a new interface so existing implementations can catch up.

2017-06-29 07:22 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +			return;
in Sabre usually you return nothing (I guess it converts to null or void?) to tell that you didn't handle this request so it can move on to the next plugin.

If you return `false` it means you handled it

2017-06-29 07:24 UTC, PVince81 commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		return $this->objectStore->getDirectDownload($this->getURN($stat['fileid']));
Does the download require any authentication ? Or is it embedded within the URL ?

2017-06-29 07:25 UTC, PVince81 commented on lib/public/Files/ObjectStore/IObjectStore.php
> +	function getDirectDownload($path);
bad indent

2017-06-29 07:29 UTC, butonic commented
afaict there are presigned requests, at least in s3: https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html

2017-06-29 08:38 UTC, DeepDiver1975 commented
swift has tempurl which seem to be the same .... https://docs.openstack.org/icehouse/config-reference/content/object-storage-tempurl.html

2017-06-29 10:23 UTC, DeepDiver1975 commented on lib/public/Files/ObjectStore/IObjectStore.php
> +	function getDirectDownload($path);
Untested swift implementation is here: 5e6c5c2

2017-06-29 14:21 UTC, DeepDiver1975 commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		$stat = $stat['etag'];
this is a breaking change - we no longer use fileid to build the urn but the etag - content md5 would be better ....

2017-07-03 08:43 UTC, labkode commented
@DeepDiver1975 Hi Thomas, thanks for the information. Indeed, it can be very useful for us for streamming the data from the storage nodes without staging in the web server. We have to figure out how the handle the auth as the storage nodes are authenticated using basic auth/certificate and the OC webserver is using SSO for auth.

Cheers,
Hugo

2017-07-03 09:06 UTC, DeepDiver1975 commented
> We have to figure out how the handle the auth as the storage nodes are authenticated using basic auth/certificate and the OC webserver is using SSO for auth.

S3 and Swift use a concept which exposes a temporary link. In S3 this is called presigned urls. Swift names this tempurl. Maybe something similar works for you as well. Let me know if you need any further input.

2017-07-03 09:43 UTC, DeepDiver1975 commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			return $this->objectPrefix . $stat['md5'];
using md5 is bullshit if we want to use object versioning as supported by some objectstores

2017-08-07 08:51 UTC, PVince81 commented
@DeepDiver1975 move to "planned" or "triage" ?

2017-08-07 08:58 UTC, DeepDiver1975 commented
> @DeepDiver1975 move to "planned" or "triage" ?

can we have a 'reseach' milestone? ;-)

I will asap revive this ....

2017-08-07 09:00 UTC, PVince81 commented
> can we have a 'reseach' milestone? ;-)

we have one, it's called "backlog" ;-)

2017-09-25 09:56 UTC, guruz commented
**IMPORTANT**: For syncing to work, the desktop clients needs a way to verify that whatever content it got in the HTTP 200 reply matches with what was expected (size, ETag, contents) from the PROPFIND.
In an ideal situation, the object store would return an X-OC-Etag, however this is probably not possible so we'd need to define a scheme to "know" that headers A,B,C returned from the GET would acknowledge that the received HTTP body is what we want in terms of (size, ETag, contents).
(One idea would be Content-MD5 header)

2017-09-25 10:18 UTC, DeepDiver1975 commented
> In an ideal situation, the object store would return an X-OC-Etag, however this is probably not possible so we'd need to define a scheme to "know" that headers A,B,C returned from the GET would acknowledge that the received HTTP body is what we want in terms of (size, ETag, contents).

storing the etag as meta data is not a problem at all - this is already implemented.

let me see how easy it is to get these data ...

2017-09-25 11:01 UTC, guruz commented
> let me see how easy it is to get these data ...

Yep client does not care how you store it, client cares about the information you return explicit or implicit in the GET result. :-) (But see other discussion I think we agree on the issue)

2018-02-15 15:48 UTC, PVince81 commented
@DeepDiver1975 is this still relevant ? there are a lot of conflicts

2018-03-06 15:59 UTC, butonic commented
I need to do some more testing. I had to force downloads by [setting the content type to `application/octet-stream`](https://tools.ietf.org/html/rfc2616#section-19.5.1 ):  https://github.com/owncloud/files_primary_s3/pull/32/commits/b6de1084d873101ba411c17a1b60b6948461d07a Otherwise files the browser understood how to render would replace the current window.

I could force using a new tab but that only caused the 120MB log file to be rendered in the next tab... still not what we want.

We may need to add a parameter to the ObjectStoreInterface to allow setting the filename: https://github.com/owncloud/files_primary_s3/pull/32/commits/b6de1084d873101ba411c17a1b60b6948461d07a#r172564226

2018-03-06 16:00 UTC, butonic requested changes
I need to do some more testing. I had to force downloads by [setting the content type to `application/octet-stream`](https://tools.ietf.org/html/rfc2616#section-19.5.1 ):  https://github.com/owncloud/files_primary_s3/pull/32/commits/b6de1084d873101ba411c17a1b60b6948461d07a Otherwise files the browser understood how to render would replace the current window.

I could force using a new tab but that only caused the 120MB log file to be rendered in the next tab... still not what we want.

We may need to add a parameter to the ObjectStoreInterface to allow setting the filename: https://github.com/owncloud/files_primary_s3/pull/32/commits/b6de1084d873101ba411c17a1b60b6948461d07a#r172564226

2018-03-20 09:35 UTC, DeepDiver1975 commented
@butonic disposition content issue addressed - I'll add later a second url for display.

so we will generated a download and a display url.

2018-03-23 13:11 UTC, butonic commented
cool that works, now I get this in the console when accessing a public link url:
```
7KxZbQBfVMfGBOR:1 Refused to connect to 'http://127.0.0.1:8000/owncloud/urn%3Aoid%3A28?response-content-type=application%2Foctet-stream&response-content-disposition=attachment%3B%20filename%3D%22lorem.txt%22&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accessKey1%2F20180323%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180323T124510Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=81bf93e41cc7e658d8fd398e0d78561d96a0d05087fcd045257fa41ffb289d7d' because it violates the following Content Security Policy directive: "connect-src 'self'".
```

this patch adds that header on the public link page:
```diff
diff --git a/apps/files_sharing/lib/Controllers/ShareController.php b/apps/files_sharing/lib/Controllers/ShareController.php
index 615af5a308..456dd5289e 100644
--- a/apps/files_sharing/lib/Controllers/ShareController.php
+++ b/apps/files_sharing/lib/Controllers/ShareController.php
@@ -356,6 +356,7 @@ class ShareController extends Controller {
 
                $csp = new OCP\AppFramework\Http\ContentSecurityPolicy();
                $csp->addAllowedFrameDomain('\'self\'');
+               $csp->addAllowedConnectDomain('127.0.0.1:8000'); // use host and port of your s3 endpoint
                $response = new TemplateResponse($this->appName, 'public', $shareTmpl, 'base');
                $response->setContentSecurityPolicy($csp);
 
```


however now I get: 
```
http://127.0.0.1:8000/owncloud/urn%3Aoid%3A28?response-content-type=application%2Foctet-stream&response-content-disposition=attachment%3B%20filename%3D%22lorem.txt%22&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accessKey1%2F20180323%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180323T130206Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=fbadabd0fe62e968317b3be4a5081a2bbfef092b7e5c48985e115f3b0d8cf0fb
-> Failed to load resource: the server responded with a status of 403 (Forbidden)

Failed to load http://127.0.0.1:8000/owncloud/urn%3Aoid%3A28?response-content-type=application%2Foctet-stream&response-content-disposition=attachment%3B%20filename%3D%22lorem.txt%22&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accessKey1%2F20180323%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180323T130130Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=a422f4accdfddbeb02cbe2ce6a4ebf0bd306df0aa156f0fbacc13f747e5dfde8: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://core' is therefore not allowed access. The response had HTTP status code 403.
```

testing against scality ... need to find out how to enable that.

The bigger question is how do we add that CSP to the public page ... where else do we need to add it?
I guess apps should be allowed to register additional CSP ... but for these requests the CSP is currently not changeable.

2018-03-23 13:26 UTC, butonic commented
hmmm https://github.com/scality/S3/issues/57#issuecomment-226536174

2018-03-23 13:28 UTC, DeepDiver1975 commented
> hmmm scality/S3#57 (comment)

Direct Upload via pre-signed url is out of scope

2018-03-23 13:28 UTC, DeepDiver1975 commented
> The bigger question is how do we add that CSP to the public page ... where else do we need to add it?
> I guess apps should be allowed to register additional CSP ... but for these requests the CSP is currently not changeable.

there is a content policy manager which allows apps to globally adopt csp

2018-03-23 13:39 UTC, DeepDiver1975 commented
> however now I get:

the pre signed url is only valid for 20 minutes

2018-03-23 13:52 UTC, butonic commented
> there is a content policy manager which allows apps to globally adopt csp
nope ... the CSP for public link pages is created via new, there is currently no way to change without patching:

https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controllers/ShareController.php#L357-L360

> the pre signed url is only valid for 20 minutes
that url is generated on the public link page AFAICT so should not be the problem

2018-03-23 14:02 UTC, butonic commented
even when configuring scality to use the same hostname `core` with:
```
docker run -d --name s3server -p 8000:8000 -e ENDPOINT=core deepdiver/s3server:7.1
```
the ports are still different, I stillneed to patch the CSP and it still fails with the same error

2018-03-26 14:55 UTC, guruz commented
So you do a synchronous call to the storage on a client GET to find out the presigned URL and then HTTP redirect to it? (Just curious, In think this is fine)

2018-03-26 14:57 UTC, DeepDiver1975 commented
> So you do a synchronous call to the storage on a client GET to find out the presigned URL

no - pre signed urls are generated without interaction with the storage. crypto magic is used to generate the pre signed url

2018-04-19 12:56 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-04-19 12:56 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-19 12:56 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-24 14:49 UTC, PVince81 commented
lots of conflicts

2018-04-24 15:17 UTC, DeepDiver1975 commented
rebased

2018-05-04 10:47 UTC, butonic approved these changes

2018-05-15 08:33 UTC, butonic commented
cc @individual-it @DeepDiver1975 
- [ ] check if file firewall rules are still triggered
- [ ] do workflow rules apply?
- [ ] document encryption is incompatible with this
- [ ] what is logged for admin audit cc @tomneedham

2019-02-05 14:38 UTC, closed without merging