Add repair step to repair mismatch filecache paths
owncloud/core pull request #28253
Opened 2017-06-28 16:59 UTC by PVince81

## Description
Whenever a parent-child relationship describes a specific path but the
entry's actual path is different, this new repair step will adjust it.

In the event where another entry already exists under that name, the
latter is deleted and replaced by the above entry. This should help
preserve the metadata associated with the original entry.

This kind of situation can be create through the bug from https://github.com/owncloud/core/issues/28018

## Related Issue
Fixes the fallout created by https://github.com/owncloud/core/issues/28018

## Motivation and Context
Because we hate filecache inconsistencies.

## How Has This Been Tested?
- [ ] TEST: Unit test (some pending)
- [ ] TEST: manual test

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-28 17:01 UTC, PVince81 commented
additional stuff to try to see if the breakage looks the same:
- [ ] also try reproducing the breakage by moving through two received shares but not from the same user
- [ ] what happens if someone deletes the bogus entries, do they land broken in trash ? might need to repair that too, or at least discard
- [ ]  check if the breakage is doable by doing between two different storages (ex: external storages)
- [ ] test with more sub-entries in the source storage as it would result in multiple broken entries for a single MOVE

2017-06-28 17:12 UTC, PVince81 commented
> also try reproducing the breakage by moving through two received shares but not from the same user

Just tried that, moving file from sharer1's storage to sharer2's storage through received shares. This creates a cross-storage situation. Basically the broken entry "folderA/one/two" is still on the first sharer's storage and the rest is on the second sharer's storage:
```
+---------+--------+--------+-----------------------+----------------------------------+
| storage | fileid | parent | path                  | etag                             |
+---------+--------+--------+-----------------------+----------------------------------+
|       3 |     31 |     25 | files/folderA         | 5953e2eadd88a                    |
|       3 |     46 |     45 | files/folderA/one/two | 5953e297167fa                    |
|       3 |     26 |     25 | files/welcome.txt     | 5db5bea08897a6709d234df3ccbb000f |
|       4 |     40 |     34 | files/folderB         | 5953e2eadedad                    |
|       4 |     45 |     40 | files/folderB/one     | 5953e29719c40                    |
|       4 |     35 |     34 | files/welcome.txt     | a05b5f63ba63bb154b29d0538491009f |
+---------+--------+--------+-----------------------+----------------------------------+
```

- [ ] TODO: adjust repair step to adjust storage value: if the parent of a child is on another storage, then set the child's storage value to the same as the parent

2017-06-28 17:23 UTC, PVince81 commented
>  what happens if someone deletes the bogus entries, do they land broken in trash ? might need to repair that too, or at least discard

deleting "folderB/one" preserves the wrong path, but now its parent is in trash:
```
+--------+-----------------------+------+--------+--------------------------------------+
| fileid | path                  | name | fileid | path                                 |
+--------+-----------------------+------+--------+--------------------------------------+
|     31 | files/folderA/one/two | two  |     30 | files_trashbin/files/one.d1498670525 |
+--------+-----------------------+------+--------+--------------------------------------+
```

- [ ] make sure repair step can also repair when entries are in trash

2017-06-28 19:03 UTC, PVince81 commented
Adjusted to also fix the storage value.

And now I realize that there could be rare cases where the path value is still correct but the storage value is wrong... Ah... Yet another case.
This is likely very rare as both sharers need to have their source folder have exactly the same name and also that the recipient decides to do the cross-storage move...

But for the sake of completeness:

- [ ] also handle case where path is the same but storage value of parent is wrong/different

2017-06-28 19:14 UTC, PVince81 commented
Uh oh, and what if the target "name" is not the same as the original ? 😢 

- [ ] check case where target name is not same as original (ex: move "folderA/one" to "folderB/oneX")

2017-06-28 20:08 UTC, PVince81 commented
- [ ] what if recreated the source parent folder ?

2017-06-28 20:13 UTC, PVince81 commented
- [ ] BUG: manual test destroyed legitimate file cache entries ⚠️

2017-06-28 20:15 UTC, PVince81 commented
- [ ] BUG: apparently the repair didn't keep sub-sub entries

2017-06-28 20:36 UTC, PVince81 commented
My mega test case:

1. Check out a commit before the fix from https://github.com/owncloud/core/issues/28018
1. Create three users "user0", "user1" and "user2". user1 will be the recipient
1. Login as "user0", create "folderA" and "folderB" and share with "user1"
1. Login as "user2", create "folderA" and share with "user1"
1. Login as "user1", rename "folderA (2)" to "folderA2" (for convenience)
1. Login as "user1" with cadaver
1. Create step by step a folder `mkdir folderA/trash1/a/b/c`
1. Create step by step a folder `mkdir folderA/trash2/a/b/c`
1. Create step by step a folder `mkdir folderA/samestorage/a/b/c`
1. Create step by step a folder `mkdir folderA/samecrossstorage/a/b/c`
1. Move "folderA/trash1" to "folderB/trash1"
1. Move "folderA/trash2" to "folderA2/trash2"
1. Delete (`rmcol`) both "folderB/trash1" and "folderA2/trash2", they'll go to trash
1. Move "folderA/samestorage" to "folderB/samestorage_renamed"
1. Move "folderA/crossstorage" to "folderA2/crossstorage_renamed"
1. Run `SELECT fc.`storage`, fc.`fileid`, fc.path as path, fc.`name`, fcp.storage as parentstorage, fcp.path as parentpath FROM `oc_filecache` fc, `oc_filecache` fcp WHERE (fc.`parent` = fcp.`fileid`) AND ((CONCAT(fcp.path, '/', fc.name) <> fc.`path`) OR (fc.`storage` <> fcp.`storage`)) AND (fcp.`path` <> '');` which should give 4 results (broken entries)
1. Checkout this PR and run `occ upgrade`
1. Check the query again: no results
1. Login as "user1" in the web UI and navigate through all folders and trashbin and see that all is well

2017-06-28 20:43 UTC, PVince81 commented
- [ ] BUG: 🚫 doesn't work for sub-entries. It seems that after the repair, the base directories "a" are fixed, but then suddenly the child directories "a/b" are broken. I guess this is normal because at the time of the original select only the "a" had a wrong path, but now that the path of "a" was fixed, the entries of "a/b" now have the wrong path.

Possible solutions:

1. Rerun the select loop until there are no more entries to process

or

2. When moving an entry, also search for all child entries and fix them as well.

2017-06-28 21:16 UTC, PVince81 commented
What a night mare, there's even more to it: if a filecache entry with the target name already exist, we delete it. But now if that entry had child entries that were created after the breakage, deleting it would orphan these child entries. So after deleting we need to reparent the child entries to attach them to the repaired entry.

- [ ] reparent children of deleted entry

My worry here is that this is yet another can of worms and that the subtree reparenting has some hidden special cases.

2017-06-30 07:19 UTC, PVince81 commented
- [ ] there were reports of cases where "fileid = parent", so need to:
    - [ ] find a way to make it happen
    - [ ] make sure the repair step can repair it to, or at least leave these alone for another future step to repair

2017-06-30 09:54 UTC, PVince81 commented
We likely already have some code somewhere to reparent child entries, but that code should not be used within repairs steps so we'll likely have to do manually by doing several DB commands

2017-06-30 10:04 UTC, PVince81 commented
Yet another alternative repair solution would be to keep the wrong path but adjust the parent id to point to the correct one. In this case it would be like cancelling the move operation. But it would also require moving back the parent entry that was moved to the target, move it back to the old location and set its path, with a slight risk that someone might have recreated the missing entry.

Now this could also be problemative if someone already worked a lot with the partially moved target and added new entries there. So maybe instead of moving the target entry back we just recreate another new parent entry to fill the gap. This way the already moved metadata is in the new folder and the old subdir metadata is on the old folder.

Then user interaction is required to fix this: the user needs to decide what to do with the data, whether to reattempt the move or move everything back.

This approach sounds much less risky than the one in this PR.
So let's give it a try in a separate PR.

2017-06-30 10:05 UTC, PVince81 commented
arghh wait, the above is only about file cache stuff. The actual physical data is already on the target location. So this would require also moving the files physically, which can be tricky from within a repair step as we need to use the `View` to make sure we trigger all hooks (versions, etc)

2017-06-30 10:25 UTC, PVince81 commented
Forget about the alternative, I think I have a plan that could work out:

Let's illustrate what is happen currently, at some point we get into this broken situation:
```
+---------+--------+--------+------------------------------------------------+----------------------------------+
| storage | fileid | parent | path                                           | etag                             |
+---------+--------+--------+------------------------------------------------+----------------------------------+
|       3 |     20 |     14 | files/folderA                                  | 59562123b68de                    |
|       3 |     27 |     26 | files/folderA/one/two                          | 5956211e9f5b6                    |
|       3 |     28 |     27 | files/folderA/one/two/three                    | 5956211e9a79a                    |
|       3 |     21 |     14 | files/folderB                                  | 59562449a3ac3                    |
|       3 |     26 |     21 | files/folderB/one                              | 5956211e9f5b6                    |
|       3 |     36 |     21 | files/folderB/x                                | 595624499eaae                    |
```

Here I do a `mkdir x` then `mv x folderB/one/two`. Internally the code will notice that the parent entries for "folderB/one/two/x" do not exist in the cache. (they do but have the wrong path with "folderA")

This results in this situation which I expect might exist for some people already who continued to use the broken folder:
```
+---------+--------+--------+------------------------------------------------+----------------------------------+
| storage | fileid | parent | path                                           | etag                             |
+---------+--------+--------+------------------------------------------------+----------------------------------+
|       3 |     20 |     14 | files/folderA                                  | 59562123b68de                    |
|       3 |     27 |     26 | files/folderA/one/two                          | 5956211e9f5b6                    |
|       3 |     28 |     27 | files/folderA/one/two/three                    | 5956211e9a79a                    |
|       3 |     21 |     14 | files/folderB                                  | 59562458ca486                    |
|       3 |     26 |     21 | files/folderB/one                              | 59562458ca486                    |
|       3 |     37 |     26 | files/folderB/one/two                          | 59562458ca486                    |
|       3 |     38 |     37 | files/folderB/one/two/three                    | 595624519b05a                    |
|       3 |     39 |     37 | files/folderB/one/two/x                        | 59562454a5133                    |
|       3 |     36 |     21 | files/folderB/x                                | 595624499eaae                    |
```

At this point we could run into a conflict when moving "folderA/one/two" to "folderB/one/two" for repair purposes. The repair routine in this PR already deletes the target. This means that for every former "folderA/**" entries we can move them to the targets with the current code by repeatingly running the repair step until done. (the repeating is an issue, see https://github.com/owncloud/core/pull/28253#issuecomment-311783644).

One there is nothing else to repair the filecache looks like this:
```
+---------+--------+--------+------------------------------------------------+----------------------------------+
| storage | fileid | parent | path                                           | etag                             |
+---------+--------+--------+------------------------------------------------+----------------------------------+
|       3 |     20 |     14 | files/folderA                                  | 59562123b68de                    |
|       3 |     21 |     14 | files/folderB                                  | 59562458ca486                    |
|       3 |     26 |     21 | files/folderB/one                              | 59562458ca486                    |
|       3 |     27 |     26 | files/folderB/one/two                          | 5956211e9f5b6                    |
|       3 |     28 |     27 | files/folderB/one/two/three                    | 5956211e9a79a                    |
|       3 |     39 |     37 | files/folderB/one/two/x                        | 59562454a5133                    |
|       3 |     36 |     21 | files/folderB/x                                | 595624499eaae                    |
```

If you look closely you'll notice that the fileid of "folderB/one/two" is the same as the "folderA/one/two" we had before. So here the repair was successful.

Now since we added a new folder "x" inside there, that one is still pointing to the old parent fileid (37). This one was deleted when we replaced "folderB/one/two".

Instead of trying to manually reparent the whole tree, I suggest the following approach:

Write an additional repair step (which will be useful anyway!) that finds all entries that have a missing parent: 
```
select storage,fileid,parent,path,etag from oc_filecache fc where parent <> -1 and not exists (select 1 from oc_filecache fc2 where fc2.fileid = fc.parent) order by path;
+---------+--------+--------+-------------------------+---------------+
| storage | fileid | parent | path                    | etag          |
+---------+--------+--------+-------------------------+---------------+
|       3 |     39 |     37 | files/folderB/one/two/x | 59562454a5133 |
+---------+--------+--------+-------------------------+---------------+
```

Then, using the `dirname()` of the path, we can find the actual parent entry to reattach to.
If there is no parent to repair then we're out of luck and need to leave the entry or even delete it... a topic for another time.

The above repair needs to be repeated until there are no more unrepairable entries with missing parent.

- [ ] add second repair routine to repair filecache entry where "parent" points to a non-existing entry but a real parent entry based on path exists

2017-06-30 10:35 UTC, PVince81 commented
Select all entries where the parent points to a non-existing entry but where an entry exist with the entry's path `dirname`:
```sql
select storage,fileid,parent,path,etag from oc_filecache fc where parent <> -1 and not exists (select 1 from oc_filecache fc2 where fc2.fileid = fc.parent) and exists (select fc3.path from oc_filecache fc3 where fc3.path = substring(fc.path, 1, length(fc.path) - length(substring_index(fc.path, '/',  -1)) - 1)) order by path;

+---------+--------+--------+-------------------------+---------------+
| storage | fileid | parent | path                    | etag          |
+---------+--------+--------+-------------------------+---------------+
|       3 |     39 |     37 | files/folderB/one/two/x | 59562454a5133 |
+---------+--------+--------+-------------------------+---------------+
```

2017-06-30 10:36 UTC, PVince81 commented
if the above turns out to not work cross-DB, fall back to simply iterating over all found entries and keep a blacklist of file ids of non-repairable entries to exclude in subsequent queries.

2017-06-30 12:32 UTC, PVince81 commented
- [ ] should we update etags to trigger sync client redownload for repaired entries ? need to check if necessary

2017-06-30 12:59 UTC, PVince81 commented
The current approach already works now, which is great.
However I used some Mysql-specific functions like `SUBSTRING_INDEX` which aren't available in other DBs. I'll have to rewrite that query, possibly separate it in two queries.

But at least we know the general approach works.

- [ ] make it work for all DBs

2017-06-30 13:09 UTC, PVince81 commented
Ok so here's an idea to expand the query that uses substring_index to other DBs, do it in two steps:

1. Find all entries where the parent points nowhere: `select fc.storage,fc.fileid,fc.parent as "wrongparent",fc.path,fc.etag from oc_filecache fc where fc.parent <> -1 and not exists (select 1 from oc_filecache fc2 where fc2.fileid = fc.parent) order by path;`
1. Foreach entry with fileid as `$brokenfileid`, compute the dirname of the path as "parentpath"
1. For each entry and with the tuple `storage, parentpath`, find the actual matching parent entry: `select fileid as "correctparentid" from oc_filecache where storage=$storage and path='$parentPath';`
1. Update the broken entry: `update oc_filecache set parent=$correctparentid where fileid=$brokenfileid`

A total of three queries... not too happy.

2017-06-30 13:42 UTC, PVince81 commented
Done...

- [ ] fix progress report, might not be possible to calculate

2017-06-30 15:45 UTC, PVince81 commented
- [ ] test sync client behavior before and after the repair

2017-06-30 15:51 UTC, PVince81 commented
Turns out having an entry with "parent = fileid" makes the repair step run in circles forever... I'll add a safety against this.

2017-06-30 16:16 UTC, PVince81 commented
- [ ] have a log / output of entries which could not be fixed (the blacklist)

2017-06-30 16:17 UTC, PVince81 commented
I wonder if we should have a "dry" mode for this that only reports affected entries, just in case.

2017-06-30 16:36 UTC, PVince81 commented
Tried to test with the sync client 2.3.2 and it looks like broken filecache entries in the form from https://github.com/owncloud/core/issues/28018 doesn't even bother it. It simply syncs the contents from "folderB" and the duplicate entries in the result do not bother it.

After running the repair step, the directory structure as seen by the client doesn't change, so there is no resyncing required.

2017-06-30 16:38 UTC, PVince81 commented
- [ ] find a way to add dry mode

A bit tricky because we don't have a way to run individual repair steps.
Adding a global dry mode for `maintenance:repair` would require touching all other repair steps to be switched to dry more.

2017-07-03 08:06 UTC, PVince81 commented
repair step confirmed working so far https://github.com/owncloud/core/issues/28277#issuecomment-312497361

2017-07-03 08:23 UTC, PVince81 commented
- [ ] if expensive for big setups, only run it once when upgrading to a version with the cross-storage fix ?

2017-07-03 09:25 UTC, jvillafanez commented
If this is going to be a repair step, I think it's pointless to spend time to create an occ command with a dry run. The repair step will be always executed, and there is no option to jump over it.

As long as all the cases are covered, or at least the cases that are out won't cause a bigger mess, it should be fine.

Any sum up of cases that have been taken into account? Some cases I see, although no idea if they're reproducible:
* parent_id pointing to a missing file_id
* parent_id pointing to an existing file_id with a different expected parent path
* parent_id pointing to an existing file_id from other storage

And several additional checks to be done:
* correct path hash
* correct mimetype of the parent folder (in case we try to reparent to a non-directory)
* size of the parent folder
* etag change after reparenting (not sure if needed)

2017-07-03 09:34 UTC, PVince81 commented
@jvillafanez thanks a lot for your feedback.

The cases that this repair step fixes:
- current path doesn't match the one from the parent on same storage: reproducible before https://github.com/owncloud/core/pull/28022 by moving a file between two received shares from the same user
- current path doesn't match the one from the parent on a different storage: reproducible before https://github.com/owncloud/core/pull/28022 by moving a file between two received shares where each share comes from a different user (two storages)
- parentid pointing to a non-existing entry: not reproducible in the wild, however the first phase of the repair step will create such entries which the second phase fixes. I assume that there might be such cases existing out there so this would fix them too.
- `parent = fileid`: not reproducible at all, was reported by @butonic as seen in the wild (clustered env).

This repair step **does not**:
- repair mismatch path_hashes
- mime types

So far I don't think we need to update etags. However you got a point about the folder size, I'll check whether that one needs updating.

The purpose of this repair step is only to fix the fallout from https://github.com/owncloud/core/issues/28018, not every possible case. That would be too much. This bug is actually a move operation that failed to update the cache entries for subdirectories, so it is likely that many things were already updated properly.

- [ ] check whether folder size needs updating.

2017-07-03 09:59 UTC, PVince81 commented
After repair, currently the size of the parents isn't updated:
```
MariaDB [owncloud]> select storage,fileid,parent,path,size,etag from oc_filecache where path like 'files%' order by storage,path;
+---------+--------+--------+----------------------------------------------------------+------+----------------------------------+
| storage | fileid | parent | path                                                     | size | etag                             |
+---------+--------+--------+----------------------------------------------------------+------+----------------------------------+
|       5 |     28 |     26 | files                                                    |  163 | 595a14e59d85f                    |
|       5 |     34 |     28 | files/folderA                                            |    0 | 595a14e59d85f                    |
|       5 |     45 |     34 | files/folderA/one                                        |    0 | 595a14d6e4cf3                    |
|       5 |     46 |     45 | files/folderA/one/two                                    | 2348 | 595a14d6e4cf3                    |
|       5 |     47 |     46 | files/folderA/one/two/three                              | 2348 | 595a14d6e4cf3                    |
|       5 |     48 |     47 | files/folderA/one/two/three/bacon.txt                    | 2348 | a40fe9248acbcbe69b6a3b3251ac1a60 |
|       5 |     29 |     28 | files/welcome.txt                                        |  163 | 70dd849483534d1cc29f19d051bf7bc3 |
+---------+--------+--------+----------------------------------------------------------+------+----------------------------------+
```

From what I can see the source folder's size has already been reset to zero, but the size of the target parent is unchanged.

Running `occ files:scan --all` fixes that, so not sure if we should add additional code in the repair step to do that, considering that the logic isn't trivial.

2017-07-03 10:00 UTC, PVince81 commented
I suggest simply adding a note in the output of the repair step: if at least one entry was fixed, ask the admin to run `occ files:scan` afterwards.

2017-07-03 10:05 UTC, PVince81 commented
Added warning about `occ files:scan` in https://github.com/owncloud/core/pull/28253/commits/6e7185d0f9556e27cc9c72c51ce830df027895ec

2017-07-03 10:17 UTC, PVince81 commented
Tested with sync client 2.3.1 as the receiver of shares but I wasn't able to reproduce any of the reported breakages.

Even before the repair the sync client already has the folders in the correct location. It seems to ignore the duplicate entries that appear in the Webdav response which is good. I'm able to create and overwrite files within those bogus folders.

After the repair, the sync client might redownload some files, but not all of them. I noticed that sometimes it even redownloads files before the repair step. There could be code paths on the client where it is a bit confused by the inconsistency between PROPFIND results.

At this point I think it is ok but it would be good to at least find a way to reproduce the bug reports about "File could not be downloaded" so we can confirm that this fixes them too.

2017-07-03 10:39 UTC, PVince81 commented
I just realized that there is a scenario extension to explore: what if during the breakage, someone moves away the folders, for example "folderB/one/two" to "folderB/two". A quick local test shows that one of the two bogus entries in "folderB/one" remains and the other one is moved. Trying to access "folderB/one/two" now gives 404.

Running the repair step does repair it properly. The bogus 404 entries are gone.

2017-07-03 11:35 UTC, PVince81 commented
I'd like to finalize this now. I don't think there is much point in tried to guess what other kind of things need fixing. If such scenarios do appear we can add them later.

2017-07-04 07:44 UTC, PVince81 commented
Oracle... hopefully the last straight line to reach the goal:
```
15:14:06 1) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #0 (1, 1, 'target')
15:14:06 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
15:14:06 
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1106
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:234
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/AdapterOCI8.php:37
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:229
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:57
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:124
15:14:06 
15:14:06 2) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #1 (1, 2, 'source')
15:14:06 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
15:14:06 
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1106
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:234
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/AdapterOCI8.php:37
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:229
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:57
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:124
15:14:06 
15:14:06 3) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #2 (1, 2, 'target')
15:14:06 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
15:14:06 
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1106
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:234
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/AdapterOCI8.php:37
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:229
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:57
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:124
15:14:06 
15:14:06 4) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #3 (1, 1, 'target', true)
15:14:06 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
15:14:06 
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1106
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:234
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/AdapterOCI8.php:37
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:229
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:57
15:14:06 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2 [...]

2017-07-04 07:53 UTC, PVince81 commented
rebased, let's hope Oracle passes now...

2017-07-04 15:19 UTC, PVince81 commented
new shit from Oracle-land:
```
11:27:07 1) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #0 (1, 1, 'target')
11:27:07 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT COUNT(*) FROM "oc_filecache" fc, "oc_filecache" fcp WHERE (fc."parent" = fcp."fileid") AND ((fcp.path || '/' || fc.name <> fc."path") OR (fc."storage" <> fcp."storage")) AND (fcp."path" <> '') AND (fc."fileid" <> fcp."fileid")':
11:27:07 
11:27:07 ORA-00904: "FC"."NAME": invalid identifier
11:27:07 
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:48
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:190
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:115
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:320
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:163
11:27:07 
11:27:07 Caused by
11:27:07 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00904: "FC"."NAME": invalid identifier
11:27:07 
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:852
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:190
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:115
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:320
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:163
11:27:07 
11:27:07 2) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #1 (1, 2, 'source')
11:27:07 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT COUNT(*) FROM "oc_filecache" fc, "oc_filecache" fcp WHERE (fc."parent" = fcp."fileid") AND ((fcp.path || '/' || fc.name <> fc."path") OR (fc."storage" <> fcp."storage")) AND (fcp."path" <> '') AND (fc."fileid" <> fcp."fileid")':
11:27:07 
11:27:07 ORA-00904: "FC"."NAME": invalid identifier
11:27:07 
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:48
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:190
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:115
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:320
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/tests/lib/Repair/RepairMismatchFileCachePathTest.php:163
11:27:07 
11:27:07 Caused by
11:27:07 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00904: "FC"."NAME": invalid identifier
11:27:07 
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:852
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/Connection.php:190
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:115
11:27:07 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ@2/lib/private/Repair/RepairMismatchFileCachePath.php:320
11:27:07  [...]

2017-07-04 17:53 UTC, PVince81 commented
and now the next Oracle challenge: the SQL request doesn't return any results and I don't know why.
This makes the unit tests fail:
```
1) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #0 (1, 1, 'target')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'files/target/moved_renamed/content_to_update'
+'files/source/to_move/content_to_update'

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:168

2) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #1 (1, 2, 'source')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2'
+'1'

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:167

3) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #2 (1, 2, 'target')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2'
+'1'

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:167

4) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #3 (1, 1, 'target', true)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'files/target/moved_renamed/content_to_update'
+'files/source/to_move/content_to_update'

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:168

5) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #4 (1, 2, 'source', true)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2'
+'1'

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:167

6) Test\Repair\RepairMismatchFileCachePathTest::testRepairEntry with data set #5 (1, 2, 'target', true)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2'
+'1'
```

2017-07-04 18:00 UTC, tomneedham commented
Tested the case presented in #28018 and this repair step cleaned it up nicely. The console output we slightly misaligned if you're going for bonus points: 

![screen shot 2017-07-04 at 18 59 17](https://user-images.githubusercontent.com/660805/27839666-f8484900-60ea-11e7-98f4-a1aca1864cf2.png)

2017-07-04 18:00 UTC, PVince81 commented
- [ ] align the console output for bonus points

2017-07-04 18:06 UTC, PVince81 commented
The generated SQL that returns nothing in Oracle:
```sql
SELECT a.* FROM (SELECT fc.`storage`, fc.`fileid`, fc.`path` as `path`, fc.`name`, fcp.`storage` as `parentstorage`, fcp.`path` as `parentpath` FROM `*PREFIX*filecache` fc, `*PREFIX*filecache` fcp WHERE (fc.`parent` = fcp.`fileid`) AND ((fcp.`path` || '/' || fc.`name` <> fc.`path`) OR (fc.`storage` <> fcp.`storage`)) AND (fcp.`path` <> '') AND (fc.`fileid` <> fcp.`fileid`)) a WHERE ROWNUM <= 200;
```

2017-07-04 18:10 UTC, PVince81 commented
ah, I forgot to say, I already tried to put the concat operation in extra parenthesis: `((fcp.`path` || '/' || fc.`name`) <> fc.`path`)`, it didn't help

2017-07-04 18:24 UTC, PVince81 commented
now using `selectAlias`. Didn't solve the Oracle problem.

2017-07-05 09:35 UTC, PVince81 commented
need to replace `AND (fcp.`path` <> '')` with `AND (fcp.`path` IS NOT NULL')`

2017-07-05 09:59 UTC, PVince81 commented
Oracle tests pass for me locally now.

Let's hope all passes now!

2017-07-05 10:29 UTC, PVince81 commented
and I'm out of rebase ammo... need to merge some other stuff to master...

2017-07-05 14:58 UTC, PVince81 commented
rebased 🐺

2017-07-06 08:08 UTC, PVince81 commented
Travis fail unrelated.

@tomneedham @jvillafanez can we merge this ? I need to backport this soon...

2017-07-06 08:29 UTC, phil-davis commented
That was the annoying problem that in the UI tests it sometimes drops back to as if it is not logged in any more - so for example while attempting to rename a file it suddenly redirects back to the login page. I took a copy of the exception and restarted the Travis job. Definitely not related to this change!

2017-07-06 08:49 UTC, PVince81 commented
⚠️ 
- [ ] prevent infinite loop in case a parent points to a child entry

2017-07-06 08:51 UTC, PVince81 commented
WIP non-working stable9 backport, but will require the extra commits we'll add here: https://github.com/owncloud/core/pull/28316

2017-07-06 13:07 UTC, PVince81 commented
Added fix to repair entries that refer to own children, see https://github.com/owncloud/core/pull/28253/files#diff-ba4fc204c3929f2fea5020b962dafb1aR164

2017-07-06 13:12 UTC, PVince81 commented
please re-review @tomneedham @jvillafanez ^

2017-07-06 14:43 UTC, PVince81 commented
stable9 backport updated as well https://github.com/owncloud/core/issues/28316

2017-07-07 06:27 UTC, PVince81 commented
of course... Oracle

2017-07-07 10:10 UTC, PVince81 commented
- [ ] add as "expensive" repair step that requires the extra option ?

- [ ] provide a way to repair individual storages to avoid requiring maintenance mode (would need locking individual users/storages)

2017-07-07 12:50 UTC, PVince81 commented
no test results here due to timeout, but on stable9 it seems the Oracle is doing its thing again:
```
09:08:16 1) Test\Repair\RepairMismatchFileCachePathTest::testRepairParentIdPointingNowhere
09:08:16 Failed asserting that '4464' matches expected 4363.
09:08:16 
09:08:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-28316-3NZYPZCWJOCQ45PC4C4RHICBSPMNJB7INMFIF5LCTRSQYL2CNYBQ/tests/lib/repair/repairmismatchfilecachepathtest.php:331
```

2017-07-07 13:23 UTC, PVince81 commented
- [ ] fix infinite loop when trying to repair a "parent points to child" entry but the parent of the parent does not exist:

```
+---------+--------+--------+------------------------------------------+----------------------------------+-------+----------+
| storage | fileid | parent | path                                     | etag                             | size  | mimetype |
+---------+--------+--------+------------------------------------------+----------------------------------+-------+----------+
|       1 |     59 |     58 | files_trashbin/files                     | 595f8a7eec63c                    |     0 |        2 |
|       1 |      6 |      8 | files_trashbin/files/a.d1499433331/b     | 595f89651b234                    |     0 |        2 |
|       1 |      7 |      6 | files_trashbin/files/a.d1499433331/b/c   | 595f89651a4f7                    |     0 |        2 |
|       1 |      8 |      7 | files_trashbin/files/a.d1499433331/b/c/d | 595f896516130                    |     0 |        2 |
```

2017-07-07 13:27 UTC, PVince81 commented
These entries are currently skipped because so far I thought we can't repair them since a parent is missing for the reparenting. But now thinking of it, we could recreate the missing entry, recursively up to the root in case more than one level is missing.

Whether the folder really exists will later on be caught / cleant up by `occ files:scan`.

2017-07-07 15:31 UTC, PVince81 commented
Added a new commit that improves the repair step to also repair: https://github.com/owncloud/core/pull/28253#issuecomment-313679489

When repairing an entry where the parent id points nowhere, we first try finding an entry using the parent based on the current path. If said entry doesn't exist, the repair step now creates it, up to the storage root if necessary.

2017-07-07 15:37 UTC, PVince81 commented
Now I'm still wondering whether we should move this into a separate OCC command instead of hide it under the bunch of repair steps. We could of course have a repair step that just invokes this logic + the files scan logic to make sure this happens on upgrade. Or, the repair step could rather just run the first selects to identify potential broken entries and urges the admin to run the OCC command.

The advantage of an OCC command:
- ability to specify a specific storage/user to repair individually, with the potential user locking to avoid having to switch to maintenance mode
- select only mode: shows stats on the number of entries to fix globally / per user

@jvillafanez @tomneedham @butonic @DeepDiver1975 thoughts on this ?

2017-07-07 15:37 UTC, PVince81 commented
now remember, this is very close to what we wanted here: https://github.com/owncloud/core/issues/18922

2017-07-07 15:42 UTC, PVince81 commented
- [ ] think about moving this to an OCC command instead as per https://github.com/owncloud/core/pull/28253#issuecomment-313716602

2017-07-10 08:34 UTC, jvillafanez commented
I don't think we need an occ command for this. The situation shouldn't happen in the first place (I think this is patched already), so whatever we want to do to fix that situation should only be done once.
In addition, all entries should be fixed without exception. There is no real reason to keep some entries damaged.

2017-07-10 08:55 UTC, cdamken commented
The downtime here is crucial for many users. If I tell them that they can go in production again after repairing the database and running an `occ files:scan --all` that means for those who has more that 1 Million files around 2 or more days downtime. 😱 

My Idea, as @PVince81 explained is that at least some user can still work  and the repaired user(s) at certain time experiment a few downtime minutes , probably, `storage not found` or similar.

2017-07-10 09:23 UTC, PVince81 commented
Regarding user locking, I did a local test and it seems to work fine with the desktop client:
- locking is done by adding an exclusive lock on "$userId/files" folder (requires View.php patching to not exclude this path as it was excluded before)
- desktop client receives "423 Locked" for the locked paths, even for the sharing ones. Download doesn't work either, only PROPFIND does.

One concern though:
- [ ] if the lock stays for more than one hour because for example the repair takes longer, the cron job will likely clear it too early, need a good approach here. Maybe remove and readd the lock after some time ?

2017-07-10 09:28 UTC, felixboehm commented
occ command makes sense for me. Let an Admin decide when to run the repair-step.
Locking: 
- Is this needed to be run in downtime, for large systems?
- Can we split the job somehow into several smaller ones?

2017-07-10 09:32 UTC, PVince81 commented
> Is this needed to be run in downtime, for large systems?

@felixboehm no, the point of user storage locking is to avoid downtime. So there is no downtime except for that one user. The locking would be done automatically while running the occ repair command, and unlocking at the end.

2017-07-10 09:32 UTC, PVince81 commented
> Can we split the job somehow into several smaller ones?

Not really because everything that is done here needs to be done in sequence. Running only the first part of the repair will leave new gaps in oc_filecache which are fixed by the second part.

2017-07-10 10:05 UTC, PVince81 commented
Just now I realized something: limiting to a single storage isn't enough. Because a lot of the repair stuff is related to failed cross-storage moves. So we'd need to lock at least two storages if not more...
So even if the admin could choose a user for who to fix the storage, we'd use this value to filter by source storage and then lock that one during the whole repair. Then when repairing the target storage entries, we'd also need to lock that one.

Or, well... Don't provide a storage limit and simply lock **all** storages that would be affected by the repair at once. It won't be all possible storages/users of the system but might still be a bunch depending on the sharing scenarios. That might still be alright as it's not a full "maintenance mode".

2017-07-10 10:07 UTC, PVince81 commented
- [ ] occ command:
    - [ ] add argument to find out what storages / users will need a repair (and a lock)
    - [ ] lock the storages of **all** affected users before repair, unlock afterwards at the end of the command
    - [ ] optionally: let the admin specify a storage to repair individually, but keep in mind that we'll still need to lock any other affected storages

2017-07-10 10:11 UTC, PVince81 commented
@cdamken your worries are mostly about the files:scan, not the repair steps I think, because experienced showed some files:scan that can take days to complete. For the repair steps, it is likely that it will take less long. Well, in some cases the main query itself took about 4 hours to complete so not sure :-/

2017-07-10 10:12 UTC, PVince81 commented
I estimate that the occ approach will take me another 2-5 days to develop depending how far we want to go. I'm not feeling too happy about this...

2017-07-10 10:22 UTC, PVince81 commented
Regarding occ files:scan --all, we could make the repair step output a list of affected users for which to rerun the scan to avoid doing a full scan:

- [ ] make repair step output a report of how many users/storages have been fixed and require rescan

2017-07-10 13:27 UTC, cdamken commented
> @cdamken your worries are mostly about the files:scan, not the repair steps

both, if we have to turn on the maintenance mode for the DB repair steps, means extra work for a downtime planning, stress if something goes wrong, they have to do maintenance mode again.

2017-07-10 15:39 UTC, PVince81 commented
I'm going to try creating local tests with a huge amount of filecache entries.

There is a difference however between "total number of filecache entries" and "number of found broken entries". In the observed cases, the number of broken entries was low (13), but due to the big amount of rows to scan to find these, it might still be slow.

Today I tried with having 10k broken entries and repairing just took ages, I didn't let it continue.

Tomorrow I intend to create a little more realistic case: lots of regular filecache entries, and add some broken entries in the lot (maybe 10% or so)

2017-07-10 15:43 UTC, PVince81 commented
and once I have some local test cases it will become possible to optimize the queries and transactions a little bit more.

2017-07-10 15:47 UTC, PVince81 commented
- [ ] TODO: move transaction to the main loop and increase chunk size to 1000, seems to make it much faster

2017-07-10 15:52 UTC, PVince81 commented
one advantage is that it is possible to interrupt the repair and resume later:

- [ ] double check that interruptions are ok

Being able to interrupt could also be a solution: schedule a downtime every day or every week end for an hour to run the repair. Then interrupt and bring it back up.

2017-07-10 15:52 UTC, PVince81 commented
- [ ] reported count is not accurate due to sub-entries, check if there is a way to detect these in advance

2017-07-10 15:54 UTC, PVince81 commented
Looks like if I increase chunk size even further to 10000, the time it takes to commit doesn't seem to increase (usually about 3 seconds per chunk). If we go the CLI route:

- [ ] occ add argument to specify chunk size

2017-07-11 09:50 UTC, PVince81 commented
In general "files:scan" doesn't need any kind of locking since it has its own locking, so files:scan will not require any downtime.

Focus is then on the repair step then.

2017-07-11 09:57 UTC, PVince81 commented
Locking the user's home in "/$userId/files" is likely not enough as we will find entries in trashbin to repair. So the lock would need to be on "/$userId/".

Also we can't make the repair based only on user storages because some received federated shares and system-wide external storages might be affected as well.

2017-07-11 19:34 UTC, PVince81 commented
Anoher local test, on my laptop with SSD while on battery:

- 746980 file cache entries, from which 186744 were purposefully broken.
- first phase of repair took almost 11 minutes (652 seconds)
- second phase of repair took 13 seconds

Due to a bug in my setup I couldn't run `occ files:scan` to complete it.
Needs to retest.

In general I have the feeling that we might not need to split the command. However adding a list of storages to rescan at the end could be useful.

2017-07-11 20:02 UTC, PVince81 commented
New test:

- 745897 filecache entries, 110250 broken entries
- phase 1 time: almost 8 mintes (471 seconds)
- phase 2: 15 seconds

- files:scan: will take forever due to too many files... ok, maybe we could output not only the repaired storages but also the specific paths to rescan

2017-07-11 20:16 UTC, PVince81 commented
Tried the same with 299464 random filecache entries with only **one** broken entry.
It took about 30 seconds to run all queries (both phases) to fix that one entry. (the entry had 4 subdirs so the query had to run 4 times)

2017-07-12 14:01 UTC, PVince81 commented
- [ ] find out whether occ files:scan is even required any more, since the repair step has evolved since last time. From what I remember it was mostly to clean up real ghost entries but could be optional.

2017-07-12 14:30 UTC, PVince81 commented
- [ ] make sure this repair steps runs **before** the folder mime type repair in case of broken structures which might be misdetected as folders by the latter

2017-07-13 07:48 UTC, PVince81 commented
- [ ] add version to check to make sure the repair step (but not OCC command) runs only ever once

2017-07-21 08:08 UTC, PVince81 commented
@patrickjahns can you check the SQL queries in this PR ? They're in "query builder" form so let me know if you need help understanding them. Code comments should already say what they are doing.

You might need to get familiar with oc_filecache first...

2017-07-24 07:26 UTC, patrickjahns commented
I'll have a look into it

2017-07-24 17:19 UTC, PVince81 commented
Additional idea for making this an occ command: just combine it within files scan. Everybody knows about this command, so extend it with `--repair` with a note that it makes it more expensive. A repair would run the repair step for the user's storages and directly the regular files scan after that.

2017-07-24 18:03 UTC, tomneedham commented
> run the repair step for the user's storages

so you would scope the queries to just one user with an additional WHERE clause? This is nice because then it can be executed in a more controllable way.

2017-07-25 08:41 UTC, PVince81 commented
@tomneedham not scoping the user but the "storage".

One concern is that it would likely skip external storages and federated share storages that way, unless we use the same approach as `occ files:scan` and get all mount points of a given user.

2017-07-25 09:03 UTC, PVince81 commented
@tomneedham then there's the question whether we should still keep the repair step or not, as it might be expensive on big setups. If we don't, we still need to advise people to run it manually because it is likely that many filecaches are broken in the world out there. Or set a limit: if filecache entries count > 100000, skip the repair step and ask people to run manually ?

2017-07-26 09:27 UTC, PVince81 commented
@tomneedham see c384e471d1c63efdcab8ae71e8f64724debe28ae

Now the `occ maintenance:repair` routine only tells whether some broken entries were detected. If yes, it displays their storage numeric ids and asks to run `occ files:scan --all --repair`. (we could resolve these to user ids at some point)

Now `occ files:scan --all --repair` will run the repair step for every scanned user individually. This means you can also use `occ files:scan user1 --repair` to repair an individual user.

This is all still a bit rough and the output isn't formatted well, but maybe that is already suitable for some field testing ? (needs backport to stable9 for that)

@tomneedham let me know what you think.

2017-07-26 09:29 UTC, PVince81 commented
- [ ] TODO: adjust repair step unit tests to also check that the storage filter works: basically check that it only fixes the specific storage and not another one

2017-07-26 14:38 UTC, tomneedham commented
> Or set a limit: if filecache entries count > 100000, skip the repair step and ask people to run manually ?

I like this approach. The repair step does the count and then either runs, or outputs a message. We can also include detials about this in the release notes

2017-07-26 15:16 UTC, PVince81 commented
Hmm, but now I just remembered that even if we fix automatically within the repair step, we still need to run occ files:scan, which means we'd need a way to run occ files:scan from within the repair step. Not so nice.

2017-07-27 07:46 UTC, PVince81 commented
I'm not happy to run occ files:scan from within the repair step:
- it might take quite a while to run
- it will likely require a lot of refactoring of the scan command to make it reusable from the repair step
- files scan itself also uses the repair step when passing `--repair` which is like a two side dependency...

2017-07-27 07:47 UTC, PVince81 commented
another alternative, but also not satisfying:
- instead of requiring the rerun of occ files:scan, have the repair step itself repair whatever file scan repairs:
    - invalid mime types
    - propagate folder sizes/etags/mtime after reattaching subtrees

The problem with the latter is that it will cause duplicate logic... and increase complexity. If we want to avoid duplicating logic, would need to refactor the propagator thing in a way to make it reusable from within the repair step.

2017-07-31 07:41 UTC, PVince81 commented
The decision for now is to ignore servers that have no CLI access.
So the repair step will only ever show a warning if broken stuff is detected and one needs to run `occ files:scan --all --repair`

2017-07-31 07:42 UTC, PVince81 commented
Still need to look into the following:

- [ ] lock the user's storage while repairing to prevent concurrent operations

2017-07-31 12:54 UTC, PVince81 commented
Rebased and squashed.

I see a potential problem when trying to lock: if we assume that users are periodically syncing, there will already be a shared lock on the home which would prevent an exclusive lock to be set. So calling `--repair` has a bigger chance to run into a `LockedException`. Now we could add a loop with "sleep" to retry a few times in the repair code... On the other hand retrying after a delay is something that would be nice in a more general fashion https://github.com/owncloud/core/issues/17016

2017-07-31 14:48 UTC, PVince81 commented
So... I went ahead and implemented https://github.com/owncloud/core/issues/28544 but I'm not sure if we should backport that. But not backporting the retry wrapper also means we can't backport the repair step without having the "runner" running randomly into annoying locks...

The annoying part is mostly that whoever runs `occ files:scan` would need to do so repeatedly, manually, until the repair can go through.

That, or we need to make the repair step "safe enough" against concurrency...

2017-07-31 14:50 UTC, PVince81 commented
Hmm...

```
15:29:57 1) Test\Repair\RepairMismatchFileCachePathTest::testRepairDetachedSubtree
15:29:57 Failed asserting that 4424 matches expected 4419.
15:29:57 
15:29:57 /var/lib/jenkins/workspace/owncloud-core_core_PR-28253-IX527L356W5WI52ILM7EWD34J2FVPZGOZGZGFD3YTPKJBCWJLAIQ/tests/lib/Repair/RepairMismatchFileCachePathTest.php:441
15:29:57 
```

2017-07-31 15:37 UTC, PVince81 commented
It turns out that even a regular files:scan can have locking errors...

2017-07-31 15:41 UTC, PVince81 commented
I now added code to lock the user's storage before repairing and after repairing. If the locking fails, it displays a message. I wasn't able to test whether this locking works because every time I test concurrently, the locking exception happens much later during the scan.

Might need to add some `sleep` calls in the code for testing.

2017-07-31 15:42 UTC, PVince81 commented
- [ ] don't use `try ... finally...` to make this backportable

2017-08-02 07:11 UTC, PVince81 commented
Hmm, files scan is not available in maintenance mode which means that even if the admin wanted to, they'll need to run this "on-line" while the storage is in use.

Raised here https://github.com/owncloud/core/issues/28561

2017-08-02 07:22 UTC, PVince81 commented
seems "occ maintenance:singleuser --on" does the trick: files:scan is allowed but no file access is possible over Webdav.

2017-08-02 08:16 UTC, PVince81 commented
Argh, I just realized that now that we do storage-specific fixing, we need to make sure that regardless of repair order (storage 1 then storage 2 or reverse), the result will be the same. Why an order ? Because a lot of the breakage is due to an unfinished cross-storage move, so two storages are involved.

But we can't guarantee in which order of the users for which the admin will run `occ files:scan --repair`.

2017-08-02 08:18 UTC, PVince81 commented
a local test shows that the outcome of the repair will be slightly different when the storage order is different

2017-08-02 10:29 UTC, PVince81 commented
Just struggled with DI... Turns out the files app application container is not instantiated when registering commands, had to add it to app.php...

I've adjusted the unit tests to include storage specific test cases. Unfortunately this does prove that the outcome of a "repair only storage X then Y" gives different results for "X then Y" than for "Y then X". However if you repair "X, Y, X" or "Y, X, Y" then the final result is the same...

Some possible approaches:

- filter by X AND Y instead of just X when repairing, so this would repair both storages. One drawback is that when the admin later on wants to repair Y, it will try and repair X again. (loss of time)

or

- when repairing X, gather a list of all other storages Yn that have been met on the way. At the end, also repair these storages. There can be multiple because these are from incomplete cross-storage moves.

or

- get rid for storage filter and live with the fact that a big downtime is needed... Apart from the downtime the advantage is that it will repair faster as it repairs without filter, so no need to reselect with different filters.

2017-08-02 11:38 UTC, PVince81 commented
Looks like the RetryLockingWrapper from https://github.com/owncloud/core/pull/28544#issuecomment-319643478 will not be viable and doesn't seem to work correctly.

- [ ] add lock retry logic directly in scan command instead

2017-08-02 11:48 UTC, PVince81 commented
- [ ] find a solution for the "filter by storage" repair order issue (https://github.com/owncloud/core/pull/28253#issuecomment-319633974)

2017-08-16 09:05 UTC, PVince81 commented
Some possible solution: when doing the first phase of fixing (fixing source storage of failed cross-storage move), we gather the list of affected storage ids, then run the second phase on the list of affected storage ids.

This has the following problems:
- the gathered list of storage ids could become extremely long on big broken setups with lots of shares to lots of different users, which all have performed a failed move at some point (very unlikely?)
- wasted performance: because for each storage X we need to run phase 2 on a number N of affected storages, it is likely that when fixing another storage Y, we'll run phase 2 again on the same storages like before. The latter cannot be avoided because the first phase is creating orphaned entries that need to be fixed by phase 2. Because of this, some queries will be run more often than if we would just run both phases on ALL storages at once.

2017-08-16 09:11 UTC, PVince81 commented
- [ ] detect `--all` in command and in this case just repair all storages at once (more efficient) instead of iterating over each and repairing individually

2017-08-16 09:40 UTC, PVince81 commented
Here we go, I implemented the above:

- Run phase 2 of repair on gathered affected storages from phase 1

When fixing failed cross-storage moves in the file cache and using the storage id filter, we filter by target storage for phase 1. However, we also need to fix the source storages in phase 2. To do so, a list of affected source storages is now gathered in phase 1 to be run on phase 2.

- occ files:scan --all --repair repairs all storages at once
    
This instead of iterating over all storages which is way less efficient due to the 1-N nature of potential failed cross-storage moves that we are repairing.
    
If singleuser mode is enabled and "--all --repair" is passed, all storages will be repaired in bulk (no repair filter). If not, it will fall back to iterating over each storage which is slower.

So to summarize

- `occ files:scan userid --repair`: filters by the user's storage when repairing, also affected repairs source storages from failed moves (1-N relationship)
- `occ files:scan --all --repair` without single user mode: same as with "userid" specified, but iterates over all users and runs the repair code once for every user, filtering by the user's storage.
- `occ files:scan --all --repair` with single user mode enabled: doesn't filter by user and runs the repair code in bulk, which is faster due to less queries and iterations but requires downtime

@butonic @tomneedham I'd now say that this is ready for review, testing and shipping. Unit tests pass.

This is unfortunately very complex because we want to cover both downtime and non-downtime scenarios in an efficient way.

Please let me know what you think and don't hesitate to ask questions as this is a really complex topic...

2017-08-16 09:41 UTC, PVince81 commented
A good start would be the repair step's test case documentation which tries to illustrate the different breakage scenarios that are being fixed: https://github.com/owncloud/core/blob/a86d01abe2a0ae9c009539e4ac68268c33afdd19/tests/lib/Repair/RepairMismatchFileCachePathTest.php#L153

2017-08-16 10:11 UTC, agross commented
> If singleuser mode is enabled and "--all --repair" is passed

Does that imply maintenance mode as well or are these separate concepts?

2017-08-16 10:13 UTC, PVince81 commented
@agross I've added maintenance mode check in the code. However I think that the command `occ files:scan` is not available at all in maintenance mode. https://github.com/owncloud/core/issues/28561

2017-08-16 10:14 UTC, PVince81 commented
the reason I added maintenance mode check as well is in case we one day fix https://github.com/owncloud/core/issues/28561 and make it available there

2017-08-16 10:15 UTC, agross commented
@PVince81 IIRC, I ran `files:scan` it several times in maintenance mode.

2017-08-16 10:16 UTC, PVince81 commented
@agross I just checked on 10.0.2 and in maintenance mode you get this:
```
± % occ files:scan
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "files" namespace.         
```

2017-08-16 10:20 UTC, agross commented
@PVince81 You're right. Seems like I didn't remember correctly ;-)

2017-08-18 10:51 UTC, tomneedham commented
Rebased 🙊

2017-09-12 12:07 UTC, tomneedham requested changes
Comments from @butonic and me. Let us know if these make sense. I can implement the test additions.

2017-09-12 12:24 UTC, PVince81 commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		// root entry left alone
I did some copy-pasting of tests at some point. At the beginning everything was just a single test function. Maybe I missed removing this.

2017-09-12 12:25 UTC, PVince81 commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		/**
sounds good

2017-09-12 12:25 UTC, PVince81 commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		 *     - files/ref_child1/child (parent=fileid of the child)
yes, copy-paste error...

2017-09-12 12:25 UTC, PVince81 commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		$refChild3Id = $this->createFileCacheEntry($storageId, 'detached/ref_child3', $baseId1);
?

2017-09-12 12:26 UTC, tomneedham commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		$refChild3Id = $this->createFileCacheEntry($storageId, 'detached/ref_child3', $baseId1);
we got a bit confused that the id was being overwritten so thought it should be renamed

2017-09-12 12:27 UTC, PVince81 commented on lib/private/Repair/RepairMismatchFileCachePath.php
> +			$out->warning('Please run `occ files:scan --all --repair` to repair all affected storages');
yes... but the numeric storage id cannot be used, you need the matching user id. And as you know resolving storage id back to user id is usually a nightmare due to md5... But if the list is small an admin might be able to find out what the user is.

2017-09-12 12:27 UTC, PVince81 commented on lib/private/Files/Utils/Scanner.php
> +			if ($isHome and
possibly. I might have had another condition back then.

2017-09-12 12:27 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +				$output->writeln("<error>To repair in bulk, please switch to single user mode first: occ maintenance:singleuser --on</error>");
I didn't know about that one

2017-09-12 12:28 UTC, PVince81 commented
@tomneedham can you take care of the changes ? So far it looks like most of your comments are about the tests. I hope this means the actual repair code is alright 😄

2017-09-12 13:28 UTC, tomneedham commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		/**
Done

2017-09-12 13:31 UTC, tomneedham commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +
Done

2017-09-12 13:34 UTC, tomneedham commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		/**
Done

2017-09-12 13:49 UTC, tomneedham commented on tests/lib/Repair/RepairMismatchFileCachePathTest.php
> +		/**
Done

2017-09-12 14:00 UTC, tomneedham commented
Rebased

2017-09-14 13:14 UTC, tomneedham commented
Finally reproduced locally - can now actually fix it

2017-09-14 13:34 UTC, tomneedham commented
https://github.com/owncloud/core/blob/773bb56ff805869735035862f19775f8fb5d3e3e/lib/private/Repair/RepairMismatchFileCachePath.php#L402-L402 is failing to respond correctly on pgsql

2017-09-14 13:35 UTC, tomneedham commented
<img width="672" alt="screen shot 2017-09-14 at 14 34 25" src="https://user-images.githubusercontent.com/660805/30432527-daf22996-9959-11e7-9ed4-accfa88f5bf4.png">

returns
 ```
int(3)
int(6)
```

when attempting to reuse a fileid to keep metadata

2017-09-15 13:03 UTC, tomneedham commented
Jenkins is saying we have a stray transaction in the repair step tests... Hmm

2017-09-17 22:26 UTC, tomneedham commented
Quite a few tests failing on oracle - and this is at least the first visible reason why:
<img width="1036" alt="screen shot 2017-09-17 at 23 25 39" src="https://user-images.githubusercontent.com/660805/30525500-9c939420-9bff-11e7-9eaa-e0e110210403.png">
but it looks like something is dying earlier

2017-09-17 22:28 UTC, tomneedham commented
Rebased

2017-09-18 15:59 UTC, PVince81 commented
managed to run the OCI tests locally, are these the correct failures ?
```
Runtime:       PHP 7.1.8 with Xdebug 2.5.5
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest.xml

.................EEEE                                             21 / 21 (100%)

Time: 4.88 seconds, Memory: 16.00MB

There were 4 errors:

1) Test\Repair\RepairMismatchFileCachePathTest::testRepairSelfReferencing
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("storage", "path", "path_hash", "name", "parent", "size", "etag", "mimetype", "mimepart") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "", "d41d8cd98f00b204e9800998ecf8427e", "", -1, -1, "zombie", 2, 1]:

ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:45
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1015
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:431
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:317
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:525
/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:350

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1006
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:431
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:317
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:525
/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:350

2) Test\Repair\RepairMismatchFileCachePathTest::testRepairParentIdPointingNowhere
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("storage", "path", "path_hash", "name", "parent", "size", "etag", "mimetype", "mimepart", "fileid") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "", "d41d8cd98f00b204e9800998ecf8427e", "", -1, -1, "zombie", 2, 1, "216"]:

ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:45
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1015
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:428
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:481
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:529
/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:540

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1006
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:428
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:481
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:529
/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:540

3) Test\Repair\RepairMismatchFileCachePathTest::testRepairDetachedSubtree
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("storage", "path", "path_hash", "name", "parent", "size", "etag", "mimetype", "mimepart") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "", "d41d8cd98f00b204e9800998ecf8427e", "", -1, -1, "zombie", 2, 1]:

ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:45
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1015
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:428
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:481
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:529
/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:598

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-00001: unique constraint (AUTOTEST.FS_STORAGE_PATH_HASH) violated

/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:245
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1006
/srv/www/htdocs/owncloud/lib/private/DB/Connection.php:211
/srv/www/htdocs/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/srv/www/htdocs/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:402
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:377
/srv/www/htdocs/owncloud/lib/private/Repair/RepairMismatchFileCachePath.php:428
/srv/www/htdocs/owncloud/lib/private/ [...]

2017-09-18 16:43 UTC, PVince81 commented
I do see an entry with empty path for storage 1, so why is it inserting a duplicate ?

The logic that triggers this is likely the response from the former query that tries to select the entry for the empty path... Experience tells that Oracle doesn't work correctly with conditions like `"path" <> ''` and requires something like `is not null`...

I'll try with that...

2017-09-18 16:57 UTC, PVince81 commented
and hopefully the last failure (from local log):
```
1) Test\Repair\RepairMismatchFileCachePathTest::testRepairDetachedSubtree
Failed asserting that '234' matches expected 221.

/srv/www/htdocs/owncloud/tests/lib/Repair/RepairMismatchFileCachePathTest.php:602
```

I hope Jenkins won't find more.

2017-09-18 18:30 UTC, tomneedham commented
Mysql timeout -.-

2017-09-18 19:48 UTC, PVince81 commented
I'll have a look at the last error tomorrow...

2017-09-19 07:49 UTC, PVince81 commented
Ok, so the error is because Oracle ignores the given "fileid" and uses its own autoincrement.

Unless there is a Oracle-specific way to make it accept this value, we'd need to check "lastInsertId" and see whether it matches `$reuseFileId`. If it doesn't match, then we'd need an additional query to adjust the "parent" column of the previous one to point at this new id.

🤢

2017-09-19 08:09 UTC, PVince81 commented
From my understanding, Oracle doesn't have a concept of autoincrement. From what I see when scrolling through OraclePlatform from doctrine/dbal, it actually creates sequences and triggers for autoincrement. So to achieve the desired result above, we'd need to temporarily disable the autoincrement trigger when inserting then enabling again. Not sure if easily possible or desired...

2017-09-19 08:16 UTC, PVince81 commented
Possible approaches for the autoincrement issue:
1) accept it and replace the value of the previous "parent" to the new file id: removes the ability to recover some potentially lost metadata as we don't reuse the old fileid
or
2) disable DBAL's trigger before insert, enable again afterwards
or
3) use `select ... into...` which might bypass the trigger
or
4) insert the value first, then use `UPDATE` to adjust the fileid directly.
or
5) rewrite DBAL's Oracle trigger code to detect whether the new row already has a value for fileid (or whatever primary key column)

2017-09-19 08:45 UTC, PVince81 commented
I decided to go with solution 4, not willing to dig deeper into triggers and Oracle-specific stuff for this likely one-time repair.

2017-09-20 08:29 UTC, socrat3000 commented
So, after aaaaaaaaaaaaaaaaaaaaaaaaaaalll that talk, how can the problem be fixed??

2017-09-20 08:52 UTC, tomneedham commented
CI Passed!! 🎉

2017-09-20 09:00 UTC, tomneedham requested changes

2017-09-20 09:00 UTC, tomneedham commented on tests/lib/TestCase.php
> +			$queryBuilder = $connection->getQueryBuilder();
Ok so let's throw this out for now

2017-09-20 09:07 UTC, tomneedham commented
> So, after aaaaaaaaaaaaaaaaaaaaaaaaaaalll that talk, how can the problem be fixed??

@socrat3000 it will be a repair step which runs during upgrades and advises of corruptions. You can run the repair step as `./occ files:scan --all --repair` or per user as `./occ files:scan $uid --repair`

2017-09-20 09:07 UTC, tomneedham approved these changes

2017-09-20 12:11 UTC, socrat3000 commented
How do I merge this into my 9.0.10? As --repair option is not available in that version.

2017-09-20 12:18 UTC, PVince81 commented
:+1: for @tomneedham's changes

2017-09-20 12:19 UTC, merged

2017-09-20 12:19 UTC, PVince81 commented
@tomneedham stable10 backport please

2017-09-20 12:26 UTC, socrat3000 commented
@PVince81 Could you please let me know how I can apply this fix on my production 9.0.10?

2017-09-20 12:31 UTC, PVince81 commented
@socrat3000 you can't, the code is not compatible and would need porting and careful retesting.

Anything preventing you to upgrade to 10.0.3 ? This fix will be in 10.0.4

2017-09-20 12:35 UTC, socrat3000 commented
@PVince81 Is there any way I could apply a workaround at least for now till we upgrade?
![screenshot from 2017-09-20 15-34-22](https://user-images.githubusercontent.com/351319/30643912-4916592e-9e19-11e7-83d9-133b28cad5f6.png)

2017-09-20 12:45 UTC, PVince81 commented
@socrat3000 if you only have one affected folder, look at "oc_filecache" entry for this folder and check that all parents properly connect. The "parent" column should point at the "fileid" of the actual parent based on the "path" value. You need to manually adjust the "path" column values to match the hierarchy from parent<->fileid relationship.

2017-09-20 13:35 UTC, socrat3000 commented
Can you help with the query for this?

Kind Regards / مع تحياتي

أحمد عمرو
Ahmad Amr

On Wed, Sep 20, 2017 at 3:46 PM, Vincent Petry <notifications@github.com>
wrote:

> @socrat3000 <https://github.com/socrat3000> if you only have one affected
> folder, look at "oc_filecache" entry for this folder and check that all
> parents properly connect. The "parent" column should point at the "fileid"
> of the actual parent based on the "path" value. You need to manually adjust
> the "path" column values to match the hierarchy from parent<->fileid
> relationship.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/owncloud/core/pull/28253#issuecomment-330840133>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAVcV7o1XCy4X9xvdofn1MZezzjTO5Crks5skQkLgaJpZM4OIP79>
> .
>

2017-09-20 17:29 UTC, socrat3000 commented
@PVince81 I have now upgraded to 10.0.3, is there any way I could get that fixed before 10.0.4 is realeased?

2017-09-21 13:42 UTC, PVince81 commented
@socrat3000 just wait for @tomneedham to finish the stable10 backport/PR then you could apply it to your instance and run "occ files:scan --all --repair"

2017-09-21 13:59 UTC, tomneedham commented
@socrat3000 See https://github.com/owncloud/core/pull/29074

2017-10-09 13:45 UTC, PVince81 commented
Added doc ticket for future reference to the new commands: https://github.com/owncloud/documentation/issues/3446

2017-10-17 14:52 UTC, jdelvecchio commented
Hello there,

got the problem on Owncloud 9.1.5, the option occ files:scan --repair is not available. 
How can I fix this ? I tried in Owncloud 9.1.6, still no option --repair either.

Should I wait for the next version ?

Thanks.

2017-10-17 15:08 UTC, PVince81 commented
The backports for OC 9.1 and 9.0 are still work in progress and should hopefully be available in the next versions.

OC 10.0.4 will have the command too once released.

2017-11-07 09:11 UTC, PVince81 commented
- stable10: https://github.com/owncloud/core/pull/29074
- stable9.1: https://github.com/owncloud/core/pull/29487
- stable9: TODO

2018-02-12 15:23 UTC, enc98 commented
Hi @PVince81,
When I run /occ files: scan --all --repair into my OC (9.1.4)

# sudo -u apache path to/occ files:scan --all --repair

Answer this:
[Symfony\Component\Console\Exception\RuntimeException] The "--repair" option does not exist.

Where am I wrong?

Thanks

2018-02-12 16:49 UTC, PVince81 commented
@enc98 try updating to the latest 9.1.* version first

2018-02-20 12:36 UTC, ZennoB commented
Seems like I have the same Problem:
![180220_csync_failed_to_access](https://user-images.githubusercontent.com/36664214/36423827-9e761300-1641-11e8-9150-a556ba0dd692.jpg)

Unfortunately I am running my owncloud on a shared Webserver. I haven't tried before, but it seems like I cannot run occ commands. What else can I do to solve this problem?

I have updated to 10.0.6 after the problem occured, that did not help. 

Thanks for help!

2018-02-21 09:50 UTC, PVince81 commented
There is no other way, sorry. you need access to command line because this repair is an expensive operation that cannot be run from a regular button in the web UI, mostly because it would likely run into PHP timeouts, especially on shared hosters which have low timeout values.

See https://github.com/owncloud/documentation/issues/3831

2018-02-21 10:47 UTC, ZennoB commented
Ok. With version 10.0.6 installed, is it possible that the problem occurs again? Or did you manage to repair its cause?

2018-02-26 11:07 UTC, ZennoB commented
Problem solved. Although no offical owncloud hosting partner, my provider offered a solution, using shell script. PHP timeout was no problem in this case.