Add plugin which verifies that request headers as directed for proper endpoint
owncloud/core pull request #28263
Opened 2017-06-29 20:07 UTC by mrow4a

As in the title, looking for comments

2017-06-30 09:05 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +		$service = $GLOBALS["service"];
I'd prefer to use a different approach: have an param in the constructor `$service` or `$davVersion` and then have the instantiator set it to the one or the other.

There are actually two Sabre Server instances, one for old dav and one for new dav. It seems in this PR you only found one `Server`. The other one is `ServerFactory`, you also need to register the plugin there for consistency.

Or as an alternative: rename the plugin to `PreventOldChunking` and only register it on the new endpoint in `Server` and don't register in `ServerFactory`.

2017-06-30 09:11 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +		$service = $GLOBALS["service"];
> Or as an alternative: rename the plugin to PreventOldChunking and only register it on the new endpoint in Server and don't register in ServerFactory.

in this case you then don't need to distinguish the server since you're always coming only from new dav, so always block

2017-06-30 10:39 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +		$service = $GLOBALS["service"];
> There are actually two Sabre Server instances, one for old dav and one for new dav. It seems in this PR you only found one Server. The other one is ServerFactory, you also need to register the plugin there for consistency.

I did at it both in Server and ServerFactory :> 

> I'd prefer to use a different approach: have an param in the constructor $service or $davVersion and then have the instantiator set it to the one or the other.

Hmm, makes sense.

2017-06-30 10:39 UTC, mrow4a commented on apps/dav/lib/Server.php
> +		$this->server->addPlugin(new ValidateRequestPlugin());
@PVince81 old end

2017-06-30 10:39 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\ValidateRequestPlugin());
@PVince81 new end

2017-06-30 10:40 UTC, mrow4a commented on apps/dav/tests/unit/Connector/Sabre/ValidateRequestPluginTest.php
> +		$this->server->httpRequest = new \Sabre\HTTP\Request('PUT', 'http://server/root_url/remote.php/dav/files/user/testnew.txt', $headers);
Old Chunking In New Endpoint

2017-06-30 10:40 UTC, mrow4a commented on apps/dav/tests/unit/Connector/Sabre/ValidateRequestPluginTest.php
> +		$this->server->httpRequest = new \Sabre\HTTP\Request('PUT', 'http://server/root_url/remote.php/webdav/testchunkold.txt', $headers);
New Chunking In Old Endpoint

2017-07-01 07:57 UTC, mrow4a commented on apps/dav/lib/Server.php
> +		$this->server->addPlugin(new ValidateRequestPlugin('dav'));
Here comes request for remote.php/dav

2017-07-01 07:57 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\ValidateRequestPlugin('webdav'));
Here comes request for remote.php/webdav

2017-07-01 07:58 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +			throw new ServiceUnavailable('Specified OC-Chunk-Offset header is allowed only in dav endpoint');
If received oc-chunk-offset header, and endpoint is not dav, exception

2017-07-01 07:58 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +			&& ($this->service != 'webdav')) {
If received HTTP_OC_CHUNKED or Oc-Chunked header, and endpoint is not dav, exception

2017-07-04 08:02 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +	public function __construct($service) {
PHPdoc for the `$service` string. I'd have preferred a boolean or maybe an int for the service version. Whichever you use, its value is unclear so better add a comment

2017-07-04 08:03 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +		$this->server->on('beforeMethod', [$this, 'checkValidity'], 1);
you could just use `beforeMethod:PUT` for the PUT specific checks

2017-07-05 12:47 UTC, DeepDiver1975 requested changes

2017-07-05 12:47 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +	 * @var Server
unknown Server

2017-07-05 12:47 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +		if ($method === 'PUT'
get rid of the PUT check by using beforeMethod:PUT as explained by @PVince81 above

2017-07-05 12:49 UTC, DeepDiver1975 commented
and please have a look whats wrong with the tests

![bildschirmfoto von 2017-07-05 14-48-25](https://user-images.githubusercontent.com/1005065/27864981-14211e4e-6191-11e7-856f-2b060071f6a4.png)

2017-08-09 07:15 UTC, mrow4a commented
@DeepDiver1975 can we merge?

2017-08-09 07:18 UTC, PVince81 approved these changes
Fix the two minor issues and this is good to go 👍

2017-08-09 07:18 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +class ValidateRequestPlugin extends ServerPlugin {
PHPDoc, what does this plugin do as the name isn't self-explanaroty

2017-08-09 07:18 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ValidateRequestPlugin.php
> +			&& ($this->service != 'webdav')) {
use strict equality `!==` as per coding guidelines https://doc.owncloud.org/server/10.0/developer_manual/general/codingguidelines.html#id1

2017-08-09 07:32 UTC, mrow4a commented
@DeepDiver1975 @PVince81 done

2017-08-09 07:34 UTC, PVince81 commented
@DeepDiver1975 should we backport this?

2017-08-10 07:26 UTC, merged

2017-08-10 07:27 UTC, PVince81 commented
@mrow4a please backport to stable10. Plugging this hole early might be best.