occ commands to list users and groups
owncloud/core pull request #28312
Opened 2017-07-05 16:15 UTC by phil-davis

## Description
Provide the following new items for the occ command:
1) ListGroupMembers.php - given a group name, list the members in that group
2) ListGroups.php - list all groups on the system, with the ability to provide a string and filter the list to show only groups containing that string
3) ListUserGroups.php - given a User ID, lists the groups which that user is i
4) ListUsers.php - list all users on the system, with the ability to provide a string and filter the list to show only User IDs containing that string

## Related Issue
#28311 

## Motivation and Context
Help with managing users and groups from the occ command line.

## How Has This Been Tested?
Running the occ commands on a test system with various filters, no filtering, with non-existent user and group names.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-07-05 16:18 UTC, phil-davis commented
I don't see where there are existing "acceptance tests" that run various occ command line commands and check that the required actions or output actually happened.
@SergioBertolinSG do have that yet?

Because it would be good to know that occ commands do what they claim, both existing ones and these new ones.

2017-07-05 16:30 UTC, SergioBertolinSG commented
@phil-davis there are no tests for occ commands currently. There is this PR https://github.com/owncloud/automated-tests/pull/17
Not sure if it is worthy to look at it. They are in python and old.

@PVince81 a couple of questions:

1. Do we want to check the output of the occ commands? 
2. Do we want to add this to the behat tests?

2017-07-05 16:35 UTC, phil-davis commented
Good to know. I would think that occ command tests should be quite easy to add to the integration tests and have behat scenarios. Just needs to go in the backlog of acceptance/integration tests to be written.

2017-07-05 16:36 UTC, mmattel commented
@phil-davis
a big thanks for that, really needed.
cant test, businesstrip...
pls add a documentatuon PR ( @settermjd - fyi)

2017-07-05 16:43 UTC, phil-davis commented
Doc issue https://github.com/owncloud/documentation/issues/3203 which I will follow up once people have had a chance to review and comment on this PR.

2017-07-06 07:51 UTC, phil-davis commented
Feel free to call in anyone else who should give review or feedback on expanding the occ command.

2017-07-06 08:45 UTC, DeepDiver1975 requested changes

2017-07-06 08:45 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +use Symfony\Component\Console\Command\Command;
unused

2017-07-06 08:45 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +use Symfony\Component\Console\Input\InputOption;
unused

2017-07-06 08:45 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +			->setName('group:listmembers')
list-members

please adjust this naming convention to all group commands - THX

2017-07-06 08:45 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +			$output->writeln('<error>Group "' . $groupName . '" does not exist</error>');
I prefer interpolated strings fro better readability 

```php
$output->writeln("<error>Group $groupName does not exist</error>");

2017-07-06 08:51 UTC, phil-davis commented on core/Command/Group/ListGroupMembers.php
> +			$output->writeln('<error>Group "' . $groupName . '" does not exist</error>');
I copy-pasted this style from other code in these core/Command/... files.
Do I update everywhere so the code will look consistent?

2017-07-06 08:57 UTC, phil-davis commented on core/Command/Group/ListGroupMembers.php
> +			->setName('group:listmembers')
The following existing occ commands do not have the "-":
app:getpath
user:resetpassword
I guess these should not be changed, as that would break backward-compatibility if users have scripted/depend on them.

The following are new commands awaiting release in 10.0.3, so I can change those easily as there are no users depending on them yet:
group:addmember
group:removemember

And I will fix the new commands introduced here.

2017-07-06 09:06 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +			->setName('group:listmembers')
yes - please fix all the new ones - and yes - we failed to name those old ones 😠 

anyway - THX

2017-07-06 09:07 UTC, DeepDiver1975 commented on core/Command/Group/ListGroupMembers.php
> +			$output->writeln('<error>Group "' . $groupName . '" does not exist</error>');
generally speaking I prefer to enhance/change code only if there is a need.
changing code 'just because of making it nice' is not the way to go.

thx

2017-07-06 09:46 UTC, phil-davis commented
@DeepDiver1975 
1) Unused "use" removed from the various files
2) Hyphens added between command words
3) output string building refactored
It works for me in local testing. Hopefully Travis and Jenkins agree.

2017-07-06 09:51 UTC, DeepDiver1975 requested changes

2017-07-06 09:51 UTC, DeepDiver1975 commented on core/Command/Group/ListGroups.php
> +				'group',
search pattern or something would match better I guess

2017-07-06 09:57 UTC, phil-davis commented on core/Command/Group/ListGroups.php
> +				'group',
Yes, I had 'pattern' in there at one stage yesterday.
If I make it 'searchpattern' do I write it:
'searchpattern' or
'search-pattern' or
'searchPattern'?
(and will do the same style of thing for ListUsers.php)

2017-07-06 09:59 UTC, DeepDiver1975 commented on core/Command/Group/ListGroups.php
> +				'group',
same naming schema search-pattern - THX

2017-07-06 10:15 UTC, phil-davis commented on core/Command/Group/ListGroups.php
> +				'group',
Done

2017-07-06 13:13 UTC, phil-davis commented
@DeepDiver1975 IMHO this is good to go

2017-07-06 14:23 UTC, DeepDiver1975 approved these changes

2017-07-06 14:23 UTC, merged

2017-07-06 15:06 UTC, mmattel commented
:+1: thanks a lot
As always - pls do not forget documentation... ( @settermjd fyi)