[WIP] move SetupHelper
owncloud/core pull request #28334
Opened 2017-07-07 03:48 UTC by individual-it

## Description
move the SetupHelper class into the Helpers folder and add `deleteAllFirewallRules`

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-07-07 06:42 UTC, phil-davis approved these changes

2017-07-07 06:44 UTC, phil-davis commented
It got the Jenkins docker problem that I think is fixed by https://github.com/owncloud/core/pull/28330 - which was merged to master a few minutes ago.
@individual-it if you rebase then I expect that Jenkins will run better.

2017-07-10 08:18 UTC, PVince81 requested changes

2017-07-10 08:18 UTC, PVince81 commented on tests/TestHelpers/SetupHelper.php
> +	public static function deleteAllFirewallRules ($ocPath) {
this doesn't belong to core as it's app-specific. Please have a helper in the firewall app instead

2017-07-10 09:51 UTC, individual-it commented
@PVince81 moved it over to the firewall all https://github.com/owncloud/firewall/pull/316 and squashed

2017-07-10 09:52 UTC, individual-it commented
@PVince81 moved it over to the firewall all https://github.com/owncloud/firewall/pull/316 and squashed

2017-07-10 09:53 UTC, phil-davis approved these changes
Seems nice and minimal changes now, to just do what is needed to find the moved class with namespace.

2017-07-11 09:21 UTC, PVince81 approved these changes
:+1:

2017-07-11 09:22 UTC, merged

2017-07-12 05:49 UTC, phil-davis commented
Backport to stable10 in #28376