move sharing functions of integration tests into helper
owncloud/core pull request #28347
Opened 2017-07-10 07:06 UTC by individual-it

## Description
create a new sharingHelper class to be able to use the code also in other tests easier

## Related Issue
owncloud/QA#467

## Motivation and Context
tests of the file firewall could use this functionality so its handy to have them in a separate helper class

## How Has This Been Tested?
run all integration tests of core locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-07-10 08:41 UTC, phil-davis approved these changes

2017-07-10 12:04 UTC, individual-it commented
jenkins is failing as some of the validations are too tight

2017-07-11 11:21 UTC, davitol requested changes

2017-07-11 11:21 UTC, davitol commented on tests/integration/features/bootstrap/Sharing.php
> +				(string) $password,
Why convert password to sting? IMHO we should convert all parameters or none of them

2017-07-11 11:21 UTC, davitol commented on tests/integration/features/bootstrap/Sharing.php
> +				(string) $password,
if ((string)$field == 'expiration')  comparations should be coded with ===

2017-07-12 08:34 UTC, individual-it commented on tests/integration/features/bootstrap/Sharing.php
> +				(string) $password,
you are right, casting to string here is not needed here

2017-07-13 11:49 UTC, davitol approved these changes

2017-07-13 11:56 UTC, merged

2017-07-14 04:19 UTC, phil-davis commented
Once #28395 is merged into stable10, I will make a backport to stable10 PR for this code that fits on top.

2017-07-14 08:22 UTC, phil-davis commented
Backport to stable10 in #28396