remove unwanted characters
owncloud/core pull request #28435
Opened 2017-07-19 10:11 UTC by Peter-Prochaska

## Description
remove \r\n

## Related Issue
https://github.com/owncloud/security-tracker/issues/248

## How Has This Been Tested?
do a request with \r\n and in the request to Amazon the \r\n are removed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-07-19 11:38 UTC, DeepDiver1975 commented
![bildschirmfoto von 2017-07-19 13-38-10](https://user-images.githubusercontent.com/1005065/28365120-8b2009fa-6c87-11e7-9412-0e339844abc3.png)

2017-07-20 07:09 UTC, DeepDiver1975 requested changes

2017-07-20 07:09 UTC, DeepDiver1975 commented on lib/private/Files/External/StorageConfig.php
> +				if(!is_bool($backendOptions[$key])) {
what about performing this step only if the value is a string? I can imagine that we get in trouble with str_replace also for int, float, array .....

2017-07-20 14:41 UTC, DeepDiver1975 approved these changes

2017-07-21 13:29 UTC, merged

2017-08-18 15:06 UTC, PVince81 commented
Regression: https://github.com/owncloud/core/issues/28669