[WIP] Trying enabling CORS
owncloud/core pull request #28457
Opened 2017-07-21 10:10 UTC by noveens

## Description

Manually added the * header

## Motivation and Context

Trying to enable CORS.

## Testing instructions:
1. Download this file: https://github.com/noveens/js-owncloud-client/blob/master/browser/bundle.js
2. Create a html file in the same directory with the following code.
```html
<!DOCTYPE html>
<html>
	<head>
		<title>owncloud Lib. test</title>
		<script type="text/javascript" src="./bundle.js"></script>

		<script type="text/javascript">
			// var oc is global
			oc.setInstance('PUT OC INSTANCE HERE');
			
			oc.login('USERNAME', 'PASSWORD').then(status => {
				alert(status);
			}).catch(error => {
				alert(error);
			});

		</script>
	</head>

	<body>
		Check the console.
	</body>
</html>
```

3. Try sniffing the request to see it's response headers (Can be done using the Network tab on the right to Console in browser)

@PVince81

2017-07-21 11:27 UTC, noveens commented
Screenshot of the request and response headers : 

![asd](https://user-images.githubusercontent.com/23054294/28461737-b5cc3700-6e35-11e7-91be-26f80b087a7e.png)

2017-07-26 07:17 UTC, peterprochaska requested changes

2017-07-26 07:17 UTC, Peter-Prochaska commented on core/Controller/CloudController.php
> +		header("Access-Control-Allow-Origin: *");
Don't use * as a wildcard domain list. We should use the value of the origin header in the initial request. A much better solution ist to have a whitelist with domains that are allowed to request content from the other domain.

2017-07-26 07:17 UTC, Peter-Prochaska commented on core/Controller/CloudController.php
> +		header("Access-Control-Allow-Origin: *");
See above

2017-07-26 07:17 UTC, Peter-Prochaska commented on lib/private/legacy/response.php
> +		header("Access-Control-Allow-Origin: *");
see above

2017-07-28 08:52 UTC, noveens commented on core/Controller/CloudController.php
> +		header("Access-Control-Allow-Origin: *");
@Peter-Prochaska ,

Yes, In this Pull Request, I was first trying to manually enable CORS for all (The * header) and I later think to make an OC app, which would maintain a table of the authenticated users authenticated via OAuth2 and then enable CORS for them.

2017-07-28 09:18 UTC, PVince81 commented on core/Controller/CloudController.php
> +		header("Access-Control-Allow-Origin: *");
We need to discuss about a concept for this.

I'm not sure if CORS can be used per authenticated user/domain. If it can, then the OPTIONS call might need to be pre-authenticated to be able to go through and receive the headers.
You'd then need a list of whitelisted domains per users. Maybe this can work, I suggest you experiment with this.

2017-08-02 13:26 UTC, peterprochaska requested changes

2017-08-02 13:26 UTC, Peter-Prochaska commented on apps/provisioning_api/lib/Users.php
> +
Please don't use Access-Control-Allow-Origin together with Access-Control-Allow-Credentials. With this you can send cookies, headers and certificates from every other domain to the server. Chrome and firefox will block this with an error. You should use one or more domain names, coming from a whitelist, in Access-Control-Allow-Origin.

2017-08-02 13:28 UTC, Peter-Prochaska commented on apps/provisioning_api/lib/Users.php
> +
"Cannot use wildcard in Access-Control-Allow-Origin when credentials flag is true". This is the error

2017-08-03 15:58 UTC, noveens commented
@PVince81 @Peter-Prochaska 
Please review.
I have stored the white-listed domains using my app: https://github.com/noveens/cors
After storing the white-listed domains, I check if the requester domain is white-listed and if is, I add the CORS Headers.

Steps For Testing:
1. Install the CORS App ( https://github.com/noveens/cors )
2. Enable the App.
3. Add a domain from which you will request under Settings->Personal->security (I used a virtual host) (Don't forget to add "http://www.")
4. Use the js-owncloud-client library to request Provisioning API methods.
5. For example use this html:
```html
<!DOCTYPE html>
<html>
	<head>
		<title>owncloud Lib. test</title>
		<script type="text/javascript" src="./bundle.js"></script>
		<script type="text/javascript">
				// var oc is global
				oc.setInstance('localhost/core');

				oc.login('noveens', '123').then(status => {
					// alert(status);
					return oc.users.getUsers();
				}).then(users => {
					console.log(users);
					return oc.groups.groupExists('admin');
				}).then(groups => {
					console.log(groups);
					return oc.apps.getApps();
				}).then(apps => {
					console.log(apps);
				}).catch(error => {
					alert(error);
				});
		</script>
	</head>

	<body>
		Check the console.
	</body>
</html>
```
6. Don't forget to use this bundle: https://github.com/noveens/js-owncloud-client/blob/master/browser/bundle.js

2017-08-04 08:52 UTC, PVince81 commented on apps/provisioning_api/appinfo/routes.php
> +API::register('options', '/cloud/users', [$users, 'options'], 'provisioning_api', API::GUEST_AUTH);
Maybe better implement this directly in the OCS router ?

One idea would be to have a `@CORS` annotation in every method that allow it which would tell the router to also automatically accept the OPTIONS method.

2017-08-04 08:53 UTC, PVince81 commented on apps/provisioning_api/appinfo/routes.php
> +API::register('options', '/cloud/users', [$users, 'options'], 'provisioning_api', API::GUEST_AUTH);
ah right... OCS might not be as flexible...

But the app framework supports annotations so it would work there.

I thought we already rewired OCS to App framework somewhere... needs some research

2017-08-04 08:55 UTC, PVince81 commented on core/Controller/CloudController.php
> +		header("Access-Control-Allow-Origin: *");
this duplicate, again... yeah I think the annotation / route approach is way better so all this header logic would be in the router code instead

2017-08-04 08:59 UTC, PVince81 commented on apps/provisioning_api/appinfo/routes.php
> +API::register('options', '/cloud/users', [$users, 'options'], 'provisioning_api', API::GUEST_AUTH);
I had a quick look at `API::register()`, it seems we might not be able to use annotations easily as OCS is not the AppFramework unfortunately. One alternative would be to add an extra argument `$options` to `register()` and then register the routes this way:

```php
    API::register('post', '/cloud/users', [$users, 'options'], 'provisioning_api', API::GUEST_AUTH, ['cors' => true]);
```
but then multiple methods might be registered for the same routes and CORS doesn't restrict by verb.

So yet another approach, add a new method:
```
API::enableCors('/cloud/users');
```

This would enable CORS for the given route.

2017-08-04 09:01 UTC, PVince81 commented on core/Controller/CloudController.php
> +	 * @NoCSRFRequired
oh, looks like annotations do work, hmm...

2017-08-04 09:03 UTC, PVince81 commented on lib/private/legacy/response.php
> +				header("Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE, MKCOL, PROPFIND");
this list could be (optionally) retrieved from all known registered routes.

So if only "GET" and "POST" were registered for that route, only allow these then.

Nice to have, not a requirement I think.

2017-08-04 09:11 UTC, PVince81 commented
@noveens can you explain the CORS approach that you wanted to use ?

I remember you said that you had to pick "*" for the first request / preflight and then restrict the domain for the second one ? Can you summarize the flow step by step ?

2017-08-04 10:02 UTC, noveens commented
My Approach:

Q1. First, store domains for which the user wants to allow CORS for. (User savable, not admin)
A1. I made an OC App for this: https://github.com/noveens/cors

Q2. Pre-flight request(OPTIONS)?
A2. Give the " * " header as the response since these requests are not authenticated.

Q3. For the main request?
A3.  - Retrieve the user white-listed domains
       - Check the requester domain
       - Check if requester domain is white-listed
       - If is, add "Access-Control-Allow-Origin: White-listed Domain" and other headers.

@PVince81 @Peter-Prochaska Please Check the approach.

2017-08-07 07:07 UTC, PVince81 commented on apps/dav/appinfo/v1/webdav.php
> +if (\OC::$server->getRequest()->getMethod() === "OPTIONS") {
This should be written as a Sabre plugin instead, if possible

2017-08-07 07:07 UTC, PVince81 commented on apps/provisioning_api/lib/Apps.php
> +		$this->setCorsHeaders();
use `@CORS` annotation instead ? or is it having trouble with OCS API ?

2017-08-07 07:07 UTC, PVince81 commented on ocs/v1.php
> +	if (\OC::$server->getRequest()->getMethod() === "OPTIONS") {
any chance to put this inside the OCS router instead ?

2017-08-07 18:45 UTC, noveens commented on apps/provisioning_api/lib/Apps.php
> +		$this->setCorsHeaders();
The `@CORS` notation doesn't work with OCS (Basically all those APIs whose routes are registered using the `API::register` method).

2017-08-07 18:47 UTC, noveens commented
@PVince81 @Peter-Prochaska , 

Please check this static web-app I built:
https://github.com/noveens/staticOwncloudWebapp

2017-08-09 11:57 UTC, PVince81 commented on lib/private/legacy/api.php
> +				$requirements = [], $cors) {
adjust PHPDoc

2017-08-09 12:00 UTC, PVince81 commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +			if (\OC::$server->getAppManager()->isEnabledForUser('cors')) {
We should probably put the whitelisting thing directly into the core. I don't see any benefit of having this in a separate app.

Also having core depend on apps and hard-coded app names is usually not a good idea.

Can you bring the whitelist logic into this PR ? The likely right location is under settings/ somewhere

2017-08-10 10:22 UTC, peterprochaska requested changes
The code looks good. But no need to have a separate app.

2017-08-10 10:22 UTC, Peter-Prochaska commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +			if (\OC::$server->getAppManager()->isEnabledForUser('cors')) {
I agree with @PVince81. Why should we have a separate app?

2017-08-10 11:30 UTC, noveens commented
@PVince81 @Peter-Prochaska ,

Thanks for your approvals, I just have one doubt now:
For now, I am returning the response from here: https://github.com/owncloud/core/pull/28457/files#diff-c738eef186bd6ff91da09dff428779d1L120

So I am worried that whether the previous implementation of @CORS might be broken since it used to give cross origin access to all requester domains.

2017-08-11 12:20 UTC, PVince81 commented
Not sure but since @Peter-Prochaska said that the wildcard domain is not acceptable, it is likely that the way how the old `@CORS` worked is also insecure so having the whitelist approach is a security improvement.

@Peter-Prochaska can you confirm ?

2017-08-11 12:29 UTC, PVince81 commented on lib/private/legacy/response.php
> +		$allowedDomains = explode(",", \OC::$server->getConfig()->getUserValue($userId, 'cors', 'domains'));
I suggest renaming "cors" to "core" and the key to "cors_domains" as there is no more "cors" app.
Please check if other locations in code require a similar change.

2017-08-14 06:39 UTC, Peter-Prochaska commented
Yes, i can confirm

2017-08-14 07:34 UTC, PVince81 commented
@noveens please fix//enhance the unit tests

2017-08-16 08:06 UTC, PVince81 commented
Looks like the HTTP_ORIGIN header is not guaranteed to be always there ?
```
6. mkcol_over_plain...... [Mon Aug 14 16:32:59 2017] Undefined index: HTTP_ORIGIN at /home/travis/build/owncloud/core/apps/dav/lib/Connector/Sabre/CorsPlugin.php#62
```

from the Travis failures.

@noveens Maybe add a `isset` and proper logic to fallback to if the header is no set.

2017-08-17 20:13 UTC, noveens commented
@PVince81 @Peter-Prochaska 

The tests pass! :smile:

2017-08-18 08:29 UTC, PVince81 reviewed
Great job fixing the tests.

Potential major problem: don't use PHP_AUTH_USER, see comments.

2017-08-18 08:29 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			isset(\OC::$server->getRequest()->server['PHP_AUTH_USER'])) {
You should rather use the user from `\OC::$server->getUserSession()->getUser()->getUid()` because I'm not sure whether PHP_AUTH_USER will always be set depending on what kind of exotic auth was used (SSO, etc)

2017-08-18 08:29 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->server->on('beforeMethod', [$this, 'setCorsHeaders'], 100);
does this need to be on all possible methods or should we reduce this to sensible ones ?

2017-08-18 08:29 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			isset(\OC::$server->getRequest()->server['PHP_AUTH_USER'])) {
Note that we also have an OC Auth plugin registered into Sabre, not sure if it makes sense to somehow connect the two.

2017-08-18 08:29 UTC, PVince81 commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +		    isset($this->request->server['PHP_AUTH_USER']) &&
inject IUserSession and use $userSession->getUser()->getUID()

2017-08-18 08:29 UTC, PVince81 commented on lib/private/AppFramework/Routing/RouteConfig.php
> +			return;
What is there is an OCS route that wants to use the OPTIONS method to do something else like returning informational headers ? Returning here would likely prevent.

If there is a quick way to make it work, please go for it.
If not, it's ok to leave this as it's very unlikely that someone would add more OCS stuff... In general we try to add all new APIs as Webdav instead.

2017-08-18 08:29 UTC, PVince81 commented on lib/private/legacy/response.php
> +		header("Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE, MKCOL, PROPFIND");
Add PATCH, PROPPATCH, REPORT

2017-08-18 08:29 UTC, PVince81 commented on lib/private/legacy/response.php
> +		header("Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE, MKCOL, PROPFIND");
Add TODO comment: "infer allowed verbs from existing known routes"

2017-08-18 08:29 UTC, PVince81 commented on settings/Controller/CorsController.php
> +class CorsController extends Controller {
Add PHPDoc, what does this do ?

2017-08-18 08:29 UTC, PVince81 commented on settings/routes.php
> +		['name' => 'Cors#removeDomain', 'url' => '/settings/domains/{id}/delete', 'verb' => 'POST']
Change this route to be `DELETE /settings/domains/{id}`.

Never use verbs within an URL path, this is not RESTful

2017-08-18 13:44 UTC, noveens commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->server->on('beforeMethod', [$this, 'setCorsHeaders'], 100);
@PVince81 
This needs to be on all methods on which CORS should be enabled.
Hence, I think this should be before all methods.

2017-08-22 10:53 UTC, noveens commented
The list for all APIs which would have CORS enabled:
- [x] All WebDAV APIs
- [x] All Users APIs provided by the provisioning_api app
- [x] All Groups APIs provided by the provisioning_api app
- [x] All Apps APIs provided by the provisioning_api app
- [x] getCapabilities (Basically the Login API)
- [x] All File-Sharing APIs

@PVince81 @Peter-Prochaska, 
Do you have any more in mind?

2017-08-22 15:32 UTC, noveens commented
@PVince81 ,

Do you have any idea about the failing selenium test?
The testing video link is: https://saucelabs.com/beta/tests/ae8c7def1a9e426aabca3b28e217411e/watch#57
The failed test is at: 5 min 25 seconds

Please help :pray:

2017-08-22 15:37 UTC, PVince81 commented
@noveens if it's about rename file you can ignore it. I suggest you rebase your PR onto master, that should make this disappear.

2017-08-22 19:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=28457) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=28457) before we can accept your contribution.<br/>**22** out of **23** committers have signed the CLA.<br/><br/>:white_check_mark: PVince81<br/>:white_check_mark: DeepDiver1975<br/>:white_check_mark: phil-davis<br/>:white_check_mark: noveens<br/>:white_check_mark: owncloud-bot<br/>:white_check_mark: sharidas<br/>:white_check_mark: karakayasemi<br/>:white_check_mark: fredreichbier<br/>:white_check_mark: individual-it<br/>:white_check_mark: tomneedham<br/>:white_check_mark: felixheidecke<br/>:white_check_mark: butonic<br/>:white_check_mark: redhell<br/>:white_check_mark: VicDeo<br/>:white_check_mark: jvillafanez<br/>:white_check_mark: mrow4a<br/>:white_check_mark: mmattel<br/>:white_check_mark: phisch<br/>:white_check_mark: kdslkdsaldsal<br/>:white_check_mark: SergioBertolinSG<br/>:white_check_mark: iMocW<br/>:white_check_mark: Peter-Prochaska<br/>:x: efueger<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=28457) it.</sub>

2017-08-22 22:44 UTC, noveens commented
@PVince81 @Peter-Prochaska ,

Ready for merge?
I added tests for domain white-listing management.

2017-08-23 08:56 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (isset(\OC::$server->getRequest()->server['HTTP_ORIGIN']) &&
Since we are in a Sabre plugin, let's do it the Sabre way: add method arguments: `setCorsHeaders(RequestInterface $request, ResponseInterface $response)`. This is where you can get the headers and set the headers.

2017-08-23 08:58 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
just like this. But use `$response` for setting the headers, not `\OC_Response` as there is a risk of framework interference. Sabre has its own way to buffer the headers until the last moment.

2017-08-23 08:58 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->server->on('beforeMethod', [$this, 'setCorsHeaders'], 100);
should `setCorsHeader` also apply for the OPTIONS method which is already handled below ? Or should it be excluded ?

2017-08-23 09:01 UTC, PVince81 commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +		if ($isTest === true && isset($this->request->server['PHP_AUTH_USER'])) {
try not using `$isTest` here.

In the unit test you need to mock the `IRequest::class` and inject it into the constructor (this is why we like dependency injection because tests can inject fake objects for testing).

Don't use "PHP_AUTH_USER" but use a mock of the IUserSession that you pass in the constructor.
Here is an example how to do mocking: https://github.com/owncloud/core/blob/v10.0.3beta/tests/lib/Encryption/Keys/StorageTest.php#L74

2017-08-23 09:02 UTC, PVince81 commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +			$requesterDomain = $this->request->server['HTTP_ORIGIN'];
`$this->request->getHeader('Origin')`

2017-08-23 09:03 UTC, PVince81 commented on lib/private/legacy/api.php
> +			$requesterDomain = $_SERVER['HTTP_ORIGIN'];
`OC::$server->getRequest()->getHeader('Origin')`. Please adjust everywhere

2017-08-23 09:04 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			\OC_Response::setCorsHeaders($userId, $requesterDomain);
add `$response` argument, I see your method is already able to add headers.

Please review all locations where you used `setCorsHeader` and see if you can get ahold of a `$response` object to pass in, as using `header()` directly from PHP is ugly

2017-08-23 09:05 UTC, PVince81 commented on settings/js/panels/cors.js
> +    if (window.confirm(confirmText)) {
`OC.dialogs.confirm()`, see https://github.com/owncloud/customgroups/blob/master/js/GroupsView.js#L157

2017-08-23 09:06 UTC, PVince81 commented on settings/js/panels/cors.js
> +        removeDomain(id, token, confirmText);
add success callback and in the callback, call `$(this).closest('tr').remove();`

2017-08-23 09:08 UTC, PVince81 commented on tests/Settings/Controller/CorsControllerTest.php
> +		$this->request = $this->createMock('OCP\IRequest');
lately we're using the form `IRequest::class` which makes IDE able to detect the validity of such classes 😄

2017-08-24 01:54 UTC, noveens commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
I can't add headers using the `$response->addHeader` here, because all OPTIONS requests are unauthorized, I'll have to `return false` from this method.

If I don't return, I'll get a 401-Unauthorized

2017-08-24 01:56 UTC, noveens commented
@PVince81 ,

Any more changes? :stuck_out_tongue:

2017-08-24 07:54 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
Response and unauthorized shouldn't matter. Whatever you set on `$response`, Sabre should set into the response even if you return false.

2017-08-24 07:54 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
Can you debug into the Sabre code to find out what it does ?

2017-08-24 08:14 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->server->on('beforeMethod', [$this, 'setCorsHeaders'], 100);
@noveens ping

2017-08-24 08:16 UTC, PVince81 commented on lib/private/legacy/api.php
> +			$userId = \OC::$server->getUserSession()->getUser()->getUID();
could it happen that the user is null ?

2017-08-24 08:17 UTC, PVince81 commented on lib/private/legacy/api.php
> +			\OC_Response::setCorsHeaders($userId, $requesterDomain);
please pass $response here

2017-08-24 08:18 UTC, PVince81 commented on lib/private/legacy/response.php
> +				header("Access-Control-Allow-Origin: " . $domain);
Can we get rid of these and make sure that we always pass a `$response` to this method ?

This block is wrong for two reasons:
1) it duplicates the similar code above
2) it uses static PHP functions which make it impossible to unit test as you can't mock them. However you can mock a `$response` for testing

2017-08-24 08:18 UTC, PVince81 commented on lib/private/legacy/response.php
> +			header("Access-Control-Allow-Origin: *");
same here

2017-08-24 08:20 UTC, PVince81 commented
Iteratively approaching perfection, still a few things to handle, see my comments.

Also I'd like @DeepDiver1975 to have a final look before we merge.

2017-08-24 17:43 UTC, noveens commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
@PVince81 ,

Can you check out my new approach?

I tried to find out why sabre doesn't  set headers from the `$response` object after returning false, but couldn't find anything.

So, I made a method (https://github.com/owncloud/core/pull/28457/files#diff-f7c504a05e1213746f92d28316dcdf95R297) which would set PHP headers from a response object.
Hence, I called that method when I was returning (https://github.com/owncloud/core/pull/28457/files#diff-99f175128bced5bdb6cf1610acbc9c33R81)

2017-08-25 03:15 UTC, noveens commented
@PVince81 ,

One more iteration complete :stuck_out_tongue: 
Need for one more?

2017-08-25 07:34 UTC, DeepDiver1975 requested changes

2017-08-25 07:34 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			$userId = \OC::$server->getUserSession()->getUser()->getUID();
- [ ] inject all objects - dont use \OC::$server

2017-08-25 07:34 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			$response = \OC_Response::setCorsHeaders($userId, $requesterDomain, $response);
- [ ] dont use OC_Response

2017-08-25 07:34 UTC, DeepDiver1975 commented on lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
> +			\OC_Response::setCorsHeaders($userId, $requesterDomain, $response);
- [ ] dont use OC_Response

2017-08-25 07:34 UTC, DeepDiver1975 commented on lib/private/AppFramework/Routing/RouteConfig.php
> +		if (\OC::$server->getRequest()->getMethod() === "OPTIONS") {
- [ ] this code piece is wrong. processOCS is used when setting up routes - this is not the execution of a request. it has to go somewhere else

2017-08-25 07:34 UTC, DeepDiver1975 commented on lib/private/legacy/api.php
> +				$requirements = [], $cors) {
please provide sane default - this also reduces necessary changes to all alls of register

2017-08-25 07:34 UTC, DeepDiver1975 commented on lib/private/legacy/response.php
> +	public static function setCorsHeaders($userId, $domain, $response) {
I don't like that more code is added to OC_Response - this class is legacy and depricated. We shall kill it and not extend it

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Application.php
> +		 $container->registerService('CorsController', function(IContainer $c) {
I should not longer be necessary to explicitly register controllers - please try without

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +	public function addDomain($domain) {
phpdoc on type is missing - needed by the routing

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +			return new RedirectResponse(
try to avoid such duplications

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +		$this->logger->debug('The domain "' . $domain . '" has been white-listed.', ['app' => $this->appName]);
no need for concat - use string interpolation

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +		$domains = explode(",", $this->config->getUserValue($userId, 'core', 'domains'));
using json encode and decode is a bit saver compared to implode/explode

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +			$this->logger->error("Invalid domain ID passed for deletion");
such error messages are of no help - since this is pure ui triggered code just throw errors back to the ui - no need to polute the log

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/Panels/Personal/Cors.php
> +			$domains = 0;
stick to explicit type - it's an array -> use []

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/js/panels/cors.js
> +function removeDomain(id, token, confirmText, callback) {
dont polute global js namespace - just add the code below line 28

2017-08-25 07:34 UTC, DeepDiver1975 commented on settings/templates/panels/personal/cors.php
> +                        <input data-id="<?php echo $id; ?>" type="button" class="button icon-delete removeDomainButton" data-confirm="<?php p($l->t('Are you sure you want to remove this domain?')); ?
no echo - never ever

2017-08-25 07:34 UTC, DeepDiver1975 commented on tests/lib/AppFramework/Middleware/Security/CORSMiddlewareTest.php
> +		$this->config = \OC::$server->getConfig();
mock it

2017-08-25 07:40 UTC, PVince81 commented on settings/templates/panels/personal/cors.php
> +                        <input data-id="<?php echo $id; ?>" type="button" class="button icon-delete removeDomainButton" data-confirm="<?php p($l->t('Are you sure you want to remove this domain?')); ?
use `p()` instead

2017-08-25 07:54 UTC, PVince81 commented
@noveens I had a chat with @DeepDiver1975 and here's an additional change:

- [ ] make CORS be the default for any endpoint that extend `OCSController`. Note that other controllers based on the app framework and not OCSController must NOT have CORS by default and still needs the `@CORS` annotation.
- [ ] make the legacy OCS routes have CORS enabled by default. So simply make the `$cors` argument equal true by default. And you don't need to change all these API::register lines
- [ ] Webdav also has CORS enabled by default, I think it's already the case here

2017-08-25 15:05 UTC, noveens commented
- [ ] Move setCorsHeader code to some other place.

2017-08-25 15:28 UTC, DeepDiver1975 requested changes

2017-08-25 15:28 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	 * @param \OCP|IUserSession $userSession
| ? should be \

2017-08-25 15:28 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	 * @param \OCP|IUserSession $userSession
actually should not be there at all ..

2017-08-25 15:28 UTC, DeepDiver1975 commented on settings/Panels/Personal/Cors.php
> +			$domains = 0;
no need for all this - just json decode and you are fine

2017-08-25 15:29 UTC, DeepDiver1975 commented
and commits need to be squashed ...

2017-08-25 15:34 UTC, PVince81 commented
let's first get this finished first and squash at the end

2017-08-25 16:05 UTC, noveens commented on lib/private/legacy/response.php
> +	public static function setCorsHeaders($userId, $domain, $response) {
@DeepDiver1975 ,
Do you have any suggestions where should I put it?

2017-08-25 19:05 UTC, noveens commented on settings/Application.php
> +		 $container->registerService('CorsController', function(IContainer $c) {
I have no idea how to change this

2017-08-27 17:48 UTC, PVince81 commented on settings/Application.php
> +		 $container->registerService('CorsController', function(IContainer $c) {
Does it work if you simply remove this ?

There is some DI magic that if some controller must be instantiated, it will look for all its dependencies automatically in the container based on the expected type of the arguments.

You might need to tweak the requested arguments to help getting a match:
- UserId -> IUserSession

2017-08-28 07:31 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	 * @param \OCP\App\IUserSession $userSession
not \OCP\App\IUserSession but \OCP\IUserSession

2017-08-28 07:32 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if ($request->getHeader('origin') !== null && $this->userSession) {
better check if `$this->userSession->getUser()` is null because often times the session exists but no user was set to it (for example after a logout)

2017-08-28 07:33 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
yeah, that's already better

2017-08-28 07:34 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +			\OC_Response::setPhpHeaders($response);
No, please set the headers to the `$response` object and let Sabre handle it.

2017-08-28 07:38 UTC, PVince81 commented on lib/private/Route/Router.php
> +			$response = new \OC\OCS\Result(null, 100, 'OPTIONS request successful');
The sad part with this approach is that whenever a non-OCS route is being called with OPTIONS, it will return an OCS response. Is there a way to detect whether we're talking to an OCS route ?

I also think that if no route was registered for the path, we should probably fail directly.
Have a look whether you can move this block to the moment where the route was found, but before the route is called.

2017-08-28 07:39 UTC, PVince81 commented on lib/private/legacy/api.php
> +			$response = \OC_Response::setCorsHeaders($userId, $requesterDomain, $response);
do you need to break/exit after this ?

2017-08-28 07:40 UTC, PVince81 commented on lib/private/legacy/response.php
> +	public static function setPhpHeaders($response) {
please remove

2017-08-28 07:40 UTC, PVince81 commented on lib/public/API.php
> +									$defaults = [], $requirements = [], $cors = true){
:+1:

2017-08-28 07:41 UTC, PVince81 commented on settings/Controller/CorsController.php
> +	private static function isValidUrl($Url) {
`$url`

2017-08-28 07:41 UTC, PVince81 commented on settings/Controller/CorsController.php
> +			$Url = 'http://localhost' . substr($Url, 18);
what does this do and why ? magic number 18

2017-08-28 07:45 UTC, PVince81 commented on lib/private/legacy/response.php
> +	public static function setCorsHeaders($userId, $domain, $response) {
The problem is mostly that we need the same logic for different API formats.

If this was Webdav-only, we'd add this only in the Webdav plugin.
If this was OCS-only, we'd add this only in the OCS response code.

But here we need this for everything, so to avoid duplicating this logic, we just add it here.
An alternative would be to have a helper class that lives in the server container, but I don't think it's worth adding one for just this one method.

Let's leave this for now.

2017-08-28 07:47 UTC, PVince81 commented
@noveens can you post a test plan for how to test this step by step ? This will be useful for QA for validating this feature.

2017-08-28 07:55 UTC, PVince81 commented
Doesn't seem to work with https://github.com/noveens/staticOwncloudWebapp:

![spectacle zu6931](https://user-images.githubusercontent.com/277525/29764347-0b7f619a-8bd7-11e7-878d-dfb184a02843.png)

![spectacle re6931](https://user-images.githubusercontent.com/277525/29764360-14658b0e-8bd7-11e7-8f71-2a16a0266961.png)

2017-08-28 09:11 UTC, noveens commented
@PVince81 ,

For the staticOwncloudWebapp, can you go into the network bar of the browser and see what are the request headers being sent? (Origin)
Please whitelist the domain as the origin header, and then retry.

2017-08-28 09:14 UTC, noveens commented on settings/Application.php
> +		 $container->registerService('CorsController', function(IContainer $c) {
What about $appName?

2017-08-28 09:20 UTC, noveens commented on lib/private/legacy/api.php
> +			$response = \OC_Response::setCorsHeaders($userId, $requesterDomain, $response);
No, I don't.

If CORS is active for a route, and the request is not OPTIONS, I just need to add Acess-Control headers if the domain is whitelisted and hence, no need for breaking.

2017-08-28 09:54 UTC, PVince81 commented on settings/Application.php
> +		 $container->registerService('CorsController', function(IContainer $c) {
from what I remember it also works with magic

2017-08-28 13:22 UTC, noveens commented
@owncloud/qa @owncloud/qa-team ,

Testing instructions:
 - Since this PR enables CORS on owncloud, to test this PR, we should have a setup where requests are made requiring the "Acess-Control-Allow-Origin" header.
- I made a sample static web app: https://github.com/noveens/staticOwncloudWebapp which does the same
- Before Cloning, go to settings -> Personal -> Security -> Add Domain
- Now enter the domain name of the host you will be cloning staticOwncloudWebapp into. (eg. http://localhost OR http://virtualHost.com) (where virtualHost is your virtual host)
- Now clone the app into the whitelisted host.
- Enter the OC instance URL, username, password and press magic.
- If everything works fine, you will see all the files of your entered instance in the page itself.

2017-08-28 14:03 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$response->setStatus(200);
move this inside the `if` block ?

If there is an authorization header then it needs to be processed by the plugins, which might have a different status response.

2017-08-28 14:03 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$response = \OC_Response::setOptionsRequestHeaders($response);
should this be moved into the if block as well ?

2017-08-28 14:04 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	public function setOptionsRequestHeaders(RequestInterface $request, ResponseInterface $response) {
Can you add a unit test for this method ? I suggest to mock RequestInterface, ResponseInterface and $sapi.

2017-08-28 14:05 UTC, PVince81 commented on lib/private/Route/Router.php
> +				if (substr($url, -1) !== '/') {
I suggest to just rethrow, calling OPTIONS on the root path doesn't make much sense I think

2017-08-28 14:07 UTC, PVince81 commented on lib/private/Route/Router.php
> +				\OC_API::respond($response, \OC_API::requestedFormat());
This will send an OCS format response even if the route itself isn't from an OCS API call.
Please check if there is a way to detect if the route is OCS. Is the matcher able to instantiate the target controller so we can check if it's instanceof OcsController ? If not, check if the base file is v1.php or v2.php ...

2017-08-28 14:10 UTC, PVince81 commented on lib/private/legacy/response.php
> +		$response->addHeader("Access-Control-Allow-Headers", "authorization, OCS-APIREQUEST, Origin, X-Requested-With, Content-Type, Access-Control-Allow-Origin");
For Webdav we'll likely need more headers like "X-OC-Mtime" when setting mtime on upload, "OC-TotalLength" if using new dav chunking, etc. Also some standard Webdav headers are needed like "Destination" for a MOVE or COPY operation.
It becomes a bit tricky as we'd need every Sabre plugin to be able to register what headers they need to allow.

I suggest to hard code a few in the CorsPlugin for now. Don't hard code them here as they are not relevant to non-Webdav calls.

2017-08-28 14:11 UTC, noveens commented on lib/private/Route/Router.php
> +				if (substr($url, -1) !== '/') {
I'm not calling options on the root path.
Here, I'm mocking the original request (which would be received after the OPTIONS request), hence, it would make sense to call on the root path.

2017-08-28 14:12 UTC, PVince81 commented on lib/private/legacy/response.php
> +		$response->addHeader("Access-Control-Allow-Headers", "authorization, OCS-APIREQUEST, Origin, X-Requested-With, Content-Type, Access-Control-Allow-Origin");
Here is a non-exhaustive list:
- "X-OC-Mtime" (for PUT to set a mtime directly)
- "OC-Checksum" (for PUT)
- "OC-Total-Length" (for PUT with new dav chunking)
- "Depth" (for PROPFIND)
- "Destination" (for MOVE)
- "Overwrite" (for MOVE)

2017-08-28 14:14 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\CorsPlugin($this->userSession));
Let's remove it and only allow Cors on the new DAV endpoint which is "remote.php/dav". For files it's "remote.php/dav/files/$user/"

I assume that this is what you are targetting with your library ?

2017-08-28 14:17 UTC, PVince81 commented
Some ideas for the future to enable Sabre plugins to register CORS verbs and headers:
- add a new attribute "array $corsHeaders" on OCA\DAV\Connector\Sabre
- add a new attribute "array $corsVerbs" on OCA\DAV\Connector\Sabre

A plugin has always access to the server and is already able to extend some things like xml namespaces. The CORS stuff would work the same, so a plugin would do:
```php
	public function initialize(\Sabre\DAV\Server $server) {
		$server->$corsHeaders[] = 'Plugin-Custom-Header';
		$server->$corsVerbs[] = 'FANCYMETHOD';
	}
```

then the code that sets the header just needs to read these values.

2017-08-28 14:46 UTC, noveens commented on lib/private/Route/Router.php
> +				\OC_API::respond($response, \OC_API::requestedFormat());
Is there a need for all that?
I just need to send a 200 status and nothing else is necessary.

2017-08-28 14:48 UTC, noveens commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\CorsPlugin($this->userSession));
How to?

2017-08-28 14:52 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\CorsPlugin($this->userSession));
there are two webdav endpoints: remote.php/webdav/path/to/file is the old one.
You can perform the same operations using remote.php/dav/files/$user/path/to/file.

The backend is slightly different as you might have noticed. And remote.php/dav is built to be more extensible.

2017-08-28 14:53 UTC, PVince81 commented on lib/private/Route/Router.php
> +				\OC_API::respond($response, \OC_API::requestedFormat());
my concern is mostly whether the response contains XML stuff from OCS. If the response is completely empty then I'm fine.

2017-08-28 14:58 UTC, noveens commented on lib/private/Route/Router.php
> +				\OC_API::respond($response, \OC_API::requestedFormat());
It's totally empty.

2017-08-28 15:00 UTC, noveens commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\CorsPlugin($this->userSession));
The library uses remote.php/webdav and not dav

2017-08-28 15:07 UTC, PVince81 commented on lib/private/legacy/response.php
> +		$allHeaders['Access-Control-Allow-Methods'] = explode(",", "GET, OPTIONS, POST, PUT, DELETE, MKCOL, PROPFIND, PATCH, PROPPATCH, REPORT");
explode ? how about just listing these directly as an array?

2017-08-28 15:08 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->extraHeaders['Access-Control-Allow-Headers'] = "X-OC-Mtime, OC-Checksum, OC-Total-Length, Depth, Destination, Overwrite";
maybe use an array here instead of comma separated ? then you can implode everything at the last moment.

2017-08-28 15:17 UTC, noveens commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		$this->extraHeaders['Access-Control-Allow-Headers'] = "X-OC-Mtime, OC-Checksum, OC-Total-Length, Depth, Destination, Overwrite";
Okay.

2017-08-28 15:18 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/ServerFactory.php
> +		$server->addPlugin(new \OCA\DAV\Connector\Sabre\CorsPlugin($this->userSession));
let's leave it then

2017-08-28 15:18 UTC, PVince81 commented on lib/private/Route/Router.php
> +				\OC_API::respond($response, \OC_API::requestedFormat());
great

2017-08-28 15:19 UTC, PVince81 commented on lib/private/Route/Router.php
> +				if (substr($url, -1) !== '/') {
ok, fine

2017-08-28 15:50 UTC, PVince81 approved these changes
:+1:

2017-08-28 15:51 UTC, PVince81 commented
backport for 10.0.4, I'd like @Peter-Prochaska to have a second look

2017-08-29 07:28 UTC, merged

2017-08-29 07:28 UTC, PVince81 commented
@noveens please backport to stable10 (PR for stable10 with the same commit)

2017-08-29 15:31 UTC, phil-davis commented
Note: needs #28833 backported on top of the backport of this.

2017-08-30 14:03 UTC, SamuAlfageme commented
@jesmrec I think this one might be the one behind the behavior we saw today with OAuth; i.e. getting no-content on the `/ocs` endpoints

2017-08-30 14:13 UTC, jesmrec commented
thanks @SamuAlfageme. I will check. The point is mobile apps that are using OAuth2 as auth method are broken with the owncloud daily master from today (30th Aug). I will send more info when i confirm.

CC @PVince81

2017-08-30 15:18 UTC, PVince81 commented
@SamuAlfageme @jesmrec any detailed steps to reproduce ? Does the oauth app use the OPTIONS method ?

2017-08-30 15:18 UTC, PVince81 commented
@SamuAlfageme @jesmrec once the problem identified, if any fixing needed, please raise a new ticket and ping @noveens

2017-08-30 15:21 UTC, jesmrec commented
https://github.com/owncloud/core/issues/28860

2017-08-31 18:24 UTC, PVince81 commented
Problem was fixed in https://github.com/owncloud/core/pull/28864, good job!

2018-02-28 10:15 UTC, Emil-G commented
Why is this option shown to end users if an Admin only has permissions to edit?

2018-02-28 10:18 UTC, PVince81 commented
No, this option is editable by users only, not the admin. At some point there should be a new page where the admin can see the CORS domains set up by all users.

2018-02-28 10:27 UTC, Emil-G commented
@PVince81 : Well in 10.0.7 if a user attempts, they are shown this error:
Access forbidden
Logged in user must be an admin

2018-02-28 11:12 UTC, PVince81 commented
Ouch, then it's a bug...