[WIP] IpHelper
owncloud/core pull request #28491
Opened 2017-07-26 10:52 UTC by phil-davis

## Description
Provide functions to allow callers to find:
- a local IP address on the running system
- the bottom subnet address of that local IP address, given a CIDR
- a loopback IP address on the running system
- the bottom subnet address of that loopback IP address, given a CIDR
- for both IPv4 and IPv6 address families

## Related Issue

## Motivation and Context
Some apps (and maybe core some day) need to run tests that originate from differing IP addresses, rather than everything starting from "localhost" or...

## How Has This Been Tested?
Firewall app tests making use of it

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New test support feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

ToDo:
[ ] Calculations for IPv6 bottom of subnet

2017-07-26 10:53 UTC, phil-davis commented
@individual-it please have a look and see if this seems reasonable, or if I have gone nuts refactoring out all these little private functions.

2017-07-26 11:13 UTC, individual-it requested changes
looks fine.
1. would like to have more comments in the IpHelper, specially for non-networking people
2. can we move changes that are only about formatting in TagsHelper.php & SharinHelper.php to a separate PR?

2017-07-26 11:13 UTC, individual-it commented on tests/TestHelpers/IpHelper.php
> +		$interfaceConfig = shell_exec('ifconfig');
throw an exception if `shell_exec` does not work?

2017-07-26 16:27 UTC, phil-davis commented on tests/TestHelpers/IpHelper.php
> +	private static function loopbackIpAddress($ipAddressFamily)
Yes, I should have mentioned that I will add doc once the code seems "done". It definitely needs it.

2017-07-27 02:47 UTC, phil-davis commented
Format changes put in PR #28497

2017-07-27 09:56 UTC, phil-davis commented
Closing here - will sort out a cleaned-up PR for this...

2017-07-27 09:56 UTC, closed without merging