[WIP] dispatch event for 404 errors
owncloud/core pull request #28523
Opened 2017-07-28 09:18 UTC by karakayasemi

## Description
Dispatch event from possible 404 error locations.

## Related Issue
https://github.com/owncloud/security/issues/3

## Motivation and Context
The goal is to be able to detect 404 errors
## How Has This Been Tested?
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 please review.

2017-07-31 08:50 UTC, DeepDiver1975 requested changes

2017-07-31 08:50 UTC, DeepDiver1975 commented on lib/public/Http/ResourceNotFoundEvent.php
> + * @since 10.0.2
10.0.3

2017-07-31 09:19 UTC, karakayasemi commented
@DeepDiver1975 the version is corrected.

2017-07-31 09:28 UTC, DeepDiver1975 commented
> @DeepDiver1975 the version is corrected.

thx - I'd like to get a second voice - @PVince81 mind having a look? THX

2017-07-31 09:29 UTC, PVince81 commented
I guess `GenericEvent` would be too generic ?

If we're sending events for 404, should we also send some for 403, etc ? (if yes, separately)

2017-07-31 11:05 UTC, karakayasemi commented
I can rename ResourceNotFoundEvent class name as HttpEvents and we can dispatch all the events http events by extending this class. Similar to following: https://github.com/owncloud/core/blob/master/lib/public/Comments/CommentsEvent.php . @PVince81 is it okay for you?

2017-07-31 12:20 UTC, PVince81 commented
@karakayasemi renaming sounds good

2017-07-31 12:45 UTC, karakayasemi commented
@DeepDiver1975 @PVince81 please review. Thanks

2017-07-31 12:47 UTC, PVince81 approved these changes
:+1: from me

2017-08-01 08:59 UTC, merged

2017-08-01 09:44 UTC, DeepDiver1975 commented
backport ?

2017-08-01 10:47 UTC, karakayasemi commented
Currently, only Security app will use this event. Security app min version probably will be 10.1, since #28206's milestone 10.1 and it was not backported. If we are planning to release security app for 9.1, we need to backport #28206 also, else IMHO no need to backport.

2019-03-19 11:25 UTC, phil-davis commented
This is not in `stable10`
@karakayasemi @PVince81 @DeepDiver1975
Backport to `stable10` branch?

2019-03-19 13:06 UTC, karakayasemi commented
As far as I know, there is nothing which using this event currently, it was added for Security app, but nothing implemented yet. I am not sure that we want to keep it.

2019-03-19 13:12 UTC, PVince81 commented
@karakayasemi I suggest reverting from master then as that would qualify as "API addition that we need to maintain and keep stable in the future" if we let it in stable10

2019-03-19 13:42 UTC, karakayasemi commented
revert in here #34835