Core support for IP-based testing
owncloud/core pull request #28534
Opened 2017-07-30 14:46 UTC by phil-davis

## Description
Support for testing based on source IP address

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-07-30 16:43 UTC, phil-davis commented
If a system that runs tests for both IPv4 and IPv6 already has its web server happily listening from 1 name that has both an IPv4 and IPv6 address, then tests that specifically bind a client IP to use IPv4 or IPv6 should find their way to the corresponding IPv4 or IPv6 server address.

If you have a setup where you run 2 separate servers (e.g. 2 PHP dev servers on a test VM) and they have 2 names (e.g. one running on localhost = 127.0.0.1 IPv4, the other on ipv6-localhost ::1 IPv6), then you need to tell the test subsystem where to find those servers, e.g.:
```
export SRV_HOST_NAME="localhost"
export IPV4_HOST_NAME="localhost"
export IPV6_HOST_NAME="ip6-localhost"
```
In the example above, IPV4_HOST_NAME can be omitted, as it will default to using SRV_HOST_NAME.

2017-07-30 16:53 UTC, phil-davis commented on tests/ui/features/bootstrap/Ip.php
> +		$this->ipv4Url = getenv('IPV4_URL');
IPv4_URL and IPV6_URL are grabbed directly from the environment. They get exported by setup_behat_tests, based on SRV_HOST_NAME, IPV4_HOST_NAME, IPV6_HOST_NAME that can be set as desired externally.
Some day it will be easy to pass these through the behat.yml parameters:
https://symfony.com/doc/current/configuration/external_parameters.html
https://github.com/Behat/Behat/pull/1048
https://github.com/Behat/Behat/issues/982
but currently that requires Symfony 3.3 and some very latest Behat version. 
For the need here, we can "jump" the parameters directly from setup_behat_tests a grab then here.

2017-07-31 06:43 UTC, individual-it requested changes
impressive piece of work!

2017-07-31 06:43 UTC, individual-it commented on tests/ui/features/bootstrap/Ip.php
> +		$this->ipv4Url = getenv('IPV4_URL');
we should add this new env variables to the documentation

2017-07-31 06:43 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +				= [ 'curl' => [ CURLOPT_INTERFACE => $sourceIpAddress ]];
it does not work when a docker bridge interface is set up. I have docker installed and it creates an bridge interface called `docker0`
```
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:0e:81:7e:b2  txqueuelen 0  (Ethernet)
        RX packets 18853  bytes 1306790 (1.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19024  bytes 27164571 (25.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

docker service runs in the background but for the tests oC, selenium and the tests are running on the host, docker is not involved.
When running the tests the docker interface is found as the first one when parsing `ifconfig` and the IP is set correctly in the rules. But when running cURL something weird happens:
```
When the client accesses the server from a routable "IPv4" address                                                                                                     
Then it should not be possible to download the file "lorem.txt" using "any" dav path
```
![image](https://user-images.githubusercontent.com/2425577/28765130-d9f8fa40-75e8-11e7-9aae-fba210056bec.png)
the request is not send from `172.17.0.1` but from `192.168.100.37` what is my `wlan0` address. BUT the reply is send to the correct IP `172.17.0.1`
I've double checked, curl definitely receives `172.17.0.1` here.

maybe we have to run `brctl show` when finding valid addresses and skip bridges

2017-07-31 06:43 UTC, individual-it commented on tests/TestHelpers/IpHelper.php
> +		return self::parseIfconfigOutput('/inet6 addr: ([0123456789abcdef:]+)/');
similar to the IPv4 parser this does not work for me. For me `/inet6 (?:addr: )?([0123456789abcdef:]+)/` works
Is there a space after `addr:` in the ifconfig output?

2017-07-31 06:49 UTC, phil-davis commented on tests/TestHelpers/IpHelper.php
> +		return self::parseIfconfigOutput('/inet6 addr: ([0123456789abcdef:]+)/');
Yes, my Ubuntu 16.04 LTS has a space after the ":" for inet6 addr.
For inet addr there is no space!
This sort of human-readable text-parsing is a pain, because it is not a well-defined API. Ideally there would be a nice Unix-wide utility that provides network information in a standard way.

2017-07-31 11:08 UTC, phil-davis commented on tests/TestHelpers/IpHelper.php
> +			'/inet\s*(?:addr)?:?\s*([\d]{1,3}\.[\d]{1,3}\.[\d]{1,3}\.[\d]{1,3})/'
This allows all forms like "inetaddr" with optional ":" and space following, and optional space between "inet" and "addr". Hopefully will cope with variations that different *nix ifconfig output throws at it.

2017-07-31 11:10 UTC, phil-davis commented on tests/TestHelpers/IpHelper.php
> +		return self::parseIfconfigOutput('/inet6\s*(?:addr)?:?\s+([0123456789abcdef:]+)/');
This allows all forms like "inet6addr" with optional ":" and non-optional space following, and optional space between "inet6" and "addr". The non-optional space is because it becomes annoyingly (but not strictly) ambiguous trying to allow things like "inet6 addr:::1" - ramming the address up against the ":" can result in 3 ":" together.
Hopefully will cope with variations that different *nix ifconfig output throws at it.

2017-08-01 06:38 UTC, phil-davis commented
@individual-it now it should ignore docker network devices when trying to find useful network devices to use for tests.

2017-08-01 06:54 UTC, individual-it approved these changes

2017-08-01 09:44 UTC, merged

2017-08-01 11:08 UTC, phil-davis commented
Backport to stable10 #28551

2017-08-02 07:11 UTC, phil-davis commented
Doc in https://github.com/owncloud/documentation/pull/3259