Support starting IPv6 PHP dev server
owncloud/core pull request #28560
Opened 2017-08-02 07:08 UTC by phil-davis

## Description
Allow the developer to specify separate IPv4 and IPv6 host names or addresses for the dev PHP server.
Start a separate dev PHP server listening on each of those.

The following environment variables are used:

SRV_HOST_NAME - the default host that the server will run on (tests will typical run against that host)
IPV4_HOST_NAME - a different IPv4 host, typically used if SRV_HOST_NAME is a specifically IPv6 name
IPV6_HOST_NAME - a different IPv6 host, typically used if SRV_HOST_NAME is a specifically IPv4 name

## Related Issue

## Motivation and Context
Tests may need to test functionality specifically using IPv4 or IPv6 (e.g. firewall is starting to do this). In the dev environment there needs to be a way to easily startup and use dev PHP servers listening on both IPv4 and IPv6.

## How Has This Been Tested?
Running ordinary core tests in a dev environment with SRV_HOST_NAME ip6-localhost - the tests drive the UI accessing it through IPv6.

Running IPv6-specific tests, with IPV6_HOST_NAME ip6-localhost and SRV_HOST_NAME localhost - the tests drive the UI accessing it through IPv4, and IPv6-specific tests access the IPv6 server listening at ::1

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality) (to the dev environment)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-02 07:10 UTC, phil-davis commented
Doc in https://github.com/owncloud/documentation/pull/3259

2017-08-03 05:06 UTC, individual-it requested changes
- when I only set `SRV_HOST_NAME=localhost` the IPv4 tests fail with:
```
 GuzzleHttp\Ring\Exception\ConnectException: cURL error 7: bind failed with errno 97: Address family not supported by protocol in /home/artur/www/owncloud-core/lib/composer/guzzlehttp/ringphp/src/Client/CurlFactory.php:126
```
localhost resolves for me to `::1` So that behaviour might be actually fine

- if I set `SRV_HOST_NAME=ipv2only-hostname` IPv4 tests work as expected

- if I set `SRV_HOST_NAME=ipv2only-hostname`  and `IPV6_HOST_NAME=ip6-localhost` and have a "real" IPv6 address, IPv4 tests pass but IPv6 tests fail with 
```
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Call to a member function getStatusCode() on null in /home/artur/www/owncloud-core/apps/firewall/tests/ui/features/bootstrap/FileFirewallContext.php:593
      Stack trace:
      #0 [internal function]: FileFirewallContext->viewThePreview(true, 'regularuser', 'testimage.jpg', NULL)
.....
```
sniffing I see the UI being driven by IPv4 then I see IPv6 requests (from & to ::1) to download the files but no request trying to access the preview
using an apache2 listening to all devices works. 
Have I done a mistake in `viewThePreview()` ?

2017-08-08 10:19 UTC, phil-davis commented
@individual-it I refactored to make a function and put the common dev server starting code in it. That makes sure that things like checking serverPID wor properly now.

If you define 3 different names for SRV_HOST_NAME, IPV4_HOST_NAME and IPV6_HOST_NAME then it is going to (at least try) to start 3 PHP dev servers. Actually that would work if you have a few IP addresses that you want to listen on, so I left it like that. If some of those are defined the same, then it just tries once for each different one.

See how it goes now.

2017-08-08 10:34 UTC, phil-davis commented
viewThePreview for both IPv4 and IPv6 is working fine for me from current master in the app, and this latest script to start the needed IPv4 and IPv6 PHP dev servers.

2017-08-09 14:02 UTC, individual-it approved these changes

2017-08-09 14:09 UTC, merged

2017-08-09 14:14 UTC, phil-davis commented
Apologies - I should have done "squash and merge". I did "Rebase and nerge" and thus all 3 commits ended up on master.

2017-08-09 14:20 UTC, phil-davis commented
Backport stable10 #28629