occ app:list filter
owncloud/core pull request #28640
Opened 2017-08-10 11:52 UTC by phil-davis

## Description
- Allow a search-pattern to be entered as a parameter to ``oc app:list`` so the user can filter the list to just matching app names.
- only print the "Enabled:" and "Disabled:" sections of output if they have at least 1 app in them
- make use of this in the integration tests ``run.sh`` script to preserve the existing state of the testing app

## Related Issue
#28638

## Motivation and Context
- it is handy for a script to have some way to know if an app is currently enabled or disabled
- it could be handy for sysadmins to be able to filter the output of ``occ app:list``, that possibility comes for free here

## How Has This Been Tested?
- enable the testing app
- run some integration tests
- verify that the testing app is still enabled
- disable the testing app
- run some integration tests
- verify that the testing app is disabled

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-10 11:54 UTC, DeepDiver1975 requested changes

2017-08-10 11:54 UTC, DeepDiver1975 commented on core/Command/App/ListApps.php
> +				'Restrict the list to apps whose name matches the given regular expression'
to -> of

2017-08-10 12:00 UTC, phil-davis commented on core/Command/App/ListApps.php
> +				'Restrict the list to apps whose name matches the given regular expression'
I used similar words to https://github.com/owncloud/core/blob/master/core/Command/User/ListUsers.php#L51

I could be more verbose and say:

Restrict the list of apps to those whose name matches the given regular expression

2017-08-10 12:04 UTC, phil-davis commented
Note: I would like to make use of this from firewall testing scripts, to avoid the firewall app getting disabled on me all the time. There are probably other app testing scripts that could also make use of this to improve their friendliness.

2017-08-10 12:25 UTC, PVince81 commented
what admin is patient enough to type "--search-pattern" ? please make that "--search"

2017-08-10 12:27 UTC, phil-davis commented
It is an argument, not a command option:
```
occ app:list firewall
```
is all that is needed
similr to ``occ user:list``

2017-08-11 03:52 UTC, individual-it approved these changes

2017-08-11 04:56 UTC, phil-davis commented
@DeepDiver1975 @PVince81 questions addressed, I think. Please re-review.

2017-08-11 08:57 UTC, PVince81 approved these changes
:+1:

2017-08-11 08:57 UTC, merged

2017-08-11 10:28 UTC, phil-davis commented
Backport to stable10 #28653

2017-08-16 11:51 UTC, phil-davis commented
Doc in https://github.com/owncloud/documentation/pull/3311