Add request method getServerAddress()
owncloud/core pull request #28660
Opened 2017-08-14 02:56 UTC by phil-davis

## Description
provide getServerAddress() method that:
1) looks for it from $_SERVER
2) if not found, looks for it from $_ENV
3) if still not found, looks for it as a real external environment variable

## Related Issue

## Motivation and Context
Many servers provide the IP address of the server in $_SERVER['SERVER_ADDR'] but this is not guaranteed. In particular, as a developer, the built-in PHP dev server does not provide this! It also does not automatically load environment variables in $_ENV. So provide a function that gathers SERVER_ADDR from wherever it can find it.

This will allow devs to pre-define SERVER_ADDR as an environment variable before starting the PHP dev server. Or for other servers that may not provide it, the sysadmin can do similar.

This can be useful for things like "firewall" that may want to know which server address a request is coming in on (e.g. systems running dual stack IPv4 and IPv6, and/or multiple network interfaces). Then code can make different decisions depending on that.

## How Has This Been Tested?
Firewall app tests based on server address.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-14 04:22 UTC, individual-it commented
I don't like the fact that the function does blindly return whatever is in that env variable. Can we add a check and only return valid IPv4/6 addresses?

2017-08-14 04:44 UTC, individual-it commented
or throw an exception?

2017-08-14 04:57 UTC, phil-davis commented
I pushed a change to make it check for a valid IP address and only return valid IP or false.
Now to think about throwing an exception.

2017-08-14 12:55 UTC, phil-davis commented
@PVince81 @DeepDiver1975 and comments on this?

As far as I can see, nothing in core really cares about ``SERVER_ADDR`` - and maybe nothing ever will. So should a method getServerAddress() be added here in core, just to service firewall?

Or should I just put some logic in a function in firewall to work out ``SERVER_ADDR`` without making use of this Request class (maybe just using it to grab the $_SERVER['SERVER_ADDR'] if it exists)?

2017-08-15 06:33 UTC, individual-it requested changes

2017-08-15 06:33 UTC, individual-it commented on lib/private/AppFramework/Http/Request.php
> +	 * @return string IP address
`filter_var` will return `FALSE` if the validation fails, so that should be noted in the return comment

2017-08-15 08:34 UTC, PVince81 commented
@phil-davis adding a method to core is fine, with `@since 10.0.3` (assuming this will be in 10.0.3).

However this means we **must** set min-version to 10.0.3 for the firewall, unless you use a "method_exists" check with a fallback...

I'm fine with either solution

2017-08-15 09:04 UTC, phil-davis commented
I have fixed up the PHP doc return and since stuff.
Can be reviewed again @individual-it @PVince81

2017-08-15 10:30 UTC, individual-it approved these changes

2017-08-15 10:41 UTC, phil-davis commented
Jenkins "[ERROR] Waited 600 seconds, no response" - I do not really care right now, because bothering to merge this depends on discussion of the related code in firewall which may or may not come to make use of this.

2017-08-18 05:58 UTC, phil-davis commented
Note: this is waiting on a decision about the need for it at all.

2017-08-31 09:32 UTC, PVince81 commented
discuss later: "triage"

2018-01-31 15:36 UTC, phil-davis commented
This is not needed - closing.

2018-01-31 15:36 UTC, closed without merging