Handle BSD case for 32 bit filemtime
owncloud/core pull request #28759
Opened 2017-08-22 03:23 UTC by phil-davis

## Description
Handle the BSD (and Mac) case in lib/private/Files/Storage/Local.php filemtime
That was performing a Linux-style stat command only.

Add ``runningOnLinux`` and ``runningOnBSD`` convenience functions and refactor existing code that did special strpos() stuff to detect the OS.

Remove some legacy tests for "win" that were still in getFileSizeViaExec

## Related Issue
#28758 

## Motivation and Context
BSD stat command has different options to Linux

## How Has This Been Tested?
Copied function runningOnBSD() onto my pfSense FreeBSD system and tried calling it manually.
It returns true for that, should also work for "OpenBSD" or other variants.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-22 03:26 UTC, phil-davis commented
Note: The filemtime() 32-bit check was introduced by PR #25428 for issue #18971 but that code only had a ``stat`` command for Linux.

2017-08-22 05:51 UTC, DeepDiver1975 commented
Nice:+1:

2017-08-22 10:09 UTC, DeepDiver1975 requested changes

2017-08-22 10:09 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Local.php
> +				return (int) exec ('stat -c %Y '. escapeshellarg ($fullPath));
Unrelated to this change ... 

Isn't it stupid to call stat to get values higher then 32 bit int and then case that to a 32bit int?

2017-08-22 10:15 UTC, phil-davis commented on lib/private/Files/Storage/Local.php
> +				return (int) exec ('stat -c %Y '. escapeshellarg ($fullPath));
A good question!

2017-08-22 10:37 UTC, phil-davis commented on lib/private/Files/Storage/Local.php
> +				return (int) exec ('stat -c %Y '. escapeshellarg ($fullPath));
Not quite as stupid as it looks. The problem is that for files of SIZE > 2GB on 32-bit systems, even filemtime() fails:
http://php.net/manual/en/function.filemtime.php#68814

The file SIZE might be too big for a 32-bit signed int, but mtine will fit OK until 2038.

Since filemtime() returns an int, I guess whoever made wrote this also returned an int. But it would not matter to just remove the (int) cast.

2017-08-22 13:33 UTC, phil-davis commented
Rebased - CI should be passing on latest master.

2017-08-22 14:24 UTC, DeepDiver1975 approved these changes

2017-08-22 15:00 UTC, phil-davis commented
@DeepDiver1975 @mmattel I refactored this based on comments in the other related PR #28761 and included the little bit of Setup.php code from there. The refactoring meant that I had to touch Setup.php anyway.

2017-08-22 16:01 UTC, mmattel commented
Code looks good, not tested :+1: 
Jenkins: docker: Error response from daemon: grpc: the connection is unavailable...

2017-08-23 01:17 UTC, phil-davis commented
Rebased again and Jenkins still dies early. I guess there will be no CI until someone is available to look at it.

2017-08-23 09:34 UTC, DeepDiver1975 commented on lib/private/legacy/util.php
> +	public static function runningOn($osType) {
a little bit less code ;-)

```php
$osType = strtolower($osType) == 'mac' ? 'darwin' : strtolower($osType);
return (strtolower(substr(PHP_OS, 0, strlen($osType))) === $osType);

2017-08-23 09:43 UTC, PVince81 commented on lib/private/legacy/util.php
> +				break;
no need to break if you return directly

2017-08-23 15:30 UTC, phil-davis commented on lib/private/legacy/util.php
> +	public static function runningOn($osType) {
bsd case is different, because for that it is not necessarily at the start of the string: 
```
$x = PHP_OS;
var_dump($x);
string(7) "FreeBSD"
```

2017-08-23 15:41 UTC, DeepDiver1975 commented on lib/private/legacy/util.php
> +	public static function runningOn($osType) {
good point - didnt look that close - sorry

2017-08-23 16:01 UTC, phil-davis commented
I refactored it - maybe it is more obscure now?

But it is "flexible" - by default it checks for the parameter matching the start of PHP_OS. It can be passed 'lin' (matching a Linux...) or 'darw' (matching a 'darwin...') or 'free' (matching 'FreeBSD').
And it knows about the special cases of 'mac' => 'darwin' and 'bsd' can come anywhere in PHP_OS.

But also, I can't imagine using the "flexibility" any time soon.

2017-08-24 06:41 UTC, mmattel commented
:+1:

2017-08-24 08:58 UTC, phil-davis commented
@PVince81 or @DeepDiver1975 do either of you want to give this a final approval and press merge?
Or change or revert back something here?

2017-08-24 11:37 UTC, merged

2017-08-24 12:07 UTC, phil-davis commented
Backport stable10 #28790 
since this makes the setup warning more generic, applying to all attempts at installing on a non-linux-style platform.