Make admin feedback easier understandable
owncloud/core pull request #28775
Opened 2017-08-23 08:07 UTC by pmaier1

You might want to change ('**occ upgrade**') to this. Should also be fine if you keep it as it is :)

2017-08-23 09:00 UTC, DeepDiver1975 requested changes

2017-08-23 09:00 UTC, DeepDiver1975 commented on core/templates/update.use-cli.php
> +				p($l->t('This ownCloud instance possibly hosts many users and files. To ensure a smooth upgrade process, please use the command line updater (occ upgrade).'));
for white labling reasons owncloud has to be replaced with a variable - or you simply remove it.
 this -> your

2017-08-23 09:12 UTC, pmaier1 commented on core/templates/update.use-cli.php
> +				p($l->t('This ownCloud instance possibly hosts many users and files. To ensure a smooth upgrade process, please use the command line updater (occ upgrade).'));
- 'This' changed to 'your'
- 'ownCloud' removed

2017-08-25 07:13 UTC, DeepDiver1975 approved these changes

2017-08-25 07:14 UTC, DeepDiver1975 commented
@tomneedham please review the english strings - thx

2017-08-28 10:14 UTC, tomneedham requested changes

2017-08-28 10:14 UTC, tomneedham commented on core/templates/update.use-cli.php
> +				p($l->t('Automatic updating was disabled in config.php. To upgrade your instance, please use the command line updater (occ upgrade).'));
Automatic updating is disabled in config.php. To upgrade your instance, please use the command line updater (occ upgrade)

2017-08-28 10:14 UTC, tomneedham commented on core/templates/update.use-cli.php
> +				p($l->t('Your instance possibly hosts many users and files. To ensure a smooth upgrade process, please use the command line updater (occ upgrade).'));
It looks like your instance may host many files and/or users. To ensure a smooth upgrade process, please use the command line updater (occ upgrade).

2017-08-28 10:38 UTC, pmaier1 commented
Thanks for review @tomneedham. Incorporated the requested changes.

2017-08-28 10:47 UTC, tomneedham approved these changes

2017-08-29 08:13 UTC, merged

2017-08-29 08:14 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/28828