make ping() available, reconnect after assemble
owncloud/core pull request #28794
Opened 2017-08-24 14:56 UTC by butonic

fixes mysql server gone away on huge chunked file upload assemblys by using doctrines ping(). also see https://github.com/owncloud/core/issues/15407#issuecomment-135458449

alternative might be to use
```
'dbdriveroptions' => array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET wait_timeout = 28800'),
```

2017-08-25 06:34 UTC, DeepDiver1975 requested changes

2017-08-25 06:34 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/File.php
> +						$conn->close();
are we in a transaction here? This will result in inconsistent state ...

2017-08-25 06:34 UTC, DeepDiver1975 commented on lib/public/IDBConnection.php
> +	 * as long it returns TRUE when a reconnect succeeded and
Is the purpose of ping() really a reconnect?

2017-08-25 06:57 UTC, butonic commented on lib/public/IDBConnection.php
> +	 * as long it returns TRUE when a reconnect succeeded and
Copy'n'Paste from their phpdoc: http://www.doctrine-project.org/api/dbal/2.5/source-class-Doctrine.DBAL.Connection.html#1554-1574

2017-08-25 07:03 UTC, DeepDiver1975 commented on lib/public/IDBConnection.php
> +	 * as long it returns TRUE when a reconnect succeeded and
Okay - there is a connect in the ping() implementation.... hmmmm

2017-08-25 07:04 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/File.php
> +						$conn->close();
I'd throw an exception in here - we are in an unclear state. The request has to be performed again.

2017-08-25 07:05 UTC, DeepDiver1975 commented
> alternative might be to use

To me this is not the alternative but the proper fix ... don't let the connection being closed.

2017-08-25 07:45 UTC, butonic commented
leaving the db connection open for 8h is hardly the right thing todo. anyway, I added a suggestion in case we are in a transaction (which as of today we are not when assembling a file). If we see timeouts in other places we might move this to our Connection implementation and add it to the IDBConnection interface so that the same mechanism can be used in other places.

2017-08-25 08:33 UTC, DeepDiver1975 commented
TBH: we should remove the old chunking .....

2017-08-25 11:59 UTC, DeepDiver1975 commented
> please, not in a hurry

for sure not - no worries ;-)

2017-08-30 07:14 UTC, PVince81 commented
Is this required for new chunking as well ? Remember that newer desktop client versions will use new dav chunking now.

2017-08-30 07:15 UTC, PVince81 commented
note that final assembly in new dav is also going through File::put()

2017-08-31 09:08 UTC, PVince81 commented
@butonic finish or defer ?

2017-09-05 08:03 UTC, PVince81 commented
moving to "planned", has been reported not fixing the issue yet

2017-11-24 08:45 UTC, DeepDiver1975 commented
@butonic conflicts - please resolve

2018-02-15 15:45 UTC, PVince81 commented
conflicts.

is this still relevant ? else close

2018-11-07 22:32 UTC, closed without merging

2018-11-07 22:33 UTC, DeepDiver1975 commented
feelr free to revive any time ....