skip to next user on OutOfBoundsException
owncloud/core pull request #28805
Opened 2017-08-25 15:04 UTC by butonic

on large ldap instances a missing uuid or username currently aborts the whole sync. This PR allows backends to indicate these problems and fail with an OutOfBoundsException. For now core will log the exception and continue with the next user.

In the future we should expose this to the cli.

together with https://github.com/owncloud/user_ldap/pull/125 this skips problematic ldap users

2017-08-30 16:22 UTC, jvillafanez commented on lib/private/User/SyncService.php
> +				} catch (\OutOfBoundsException $e) {
OutOfBounds is a bad naming choice if the exception is expected to be thrown when we can access to the property. I'd rather use a custom public exception here.

2017-08-30 16:22 UTC, jvillafanez commented on lib/private/User/SyncService.php
> +					try {
maybe we could move this try / catch block to another function. This way we can avoid this nested try / catch, and also make this function more compact.

2017-08-31 08:57 UTC, PVince81 commented
@butonic any update ? See comments above.

Else would defer to "planned" for the next release.

2017-09-05 07:52 UTC, PVince81 commented
moving to "planned" as discussed with @DeepDiver1975

2017-10-19 18:38 UTC, DeepDiver1975 requested changes

2017-10-19 18:38 UTC, DeepDiver1975 commented on lib/private/User/SyncService.php
> -				$this->cleanPreferences($uid);
why is this removed?

2017-11-24 08:44 UTC, DeepDiver1975 commented
@ownclouders rebase

2017-11-24 08:44 UTC, ownclouders commented
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

2017-11-24 08:44 UTC, ownclouders commented
Automated rebase was successful!

2018-04-30 14:59 UTC, butonic commented
closing, as the current code already continues on all Exceptions. logging errors to the console tracked in https://github.com/owncloud/core/issues/31310

2018-04-30 14:59 UTC, closed without merging

2018-05-02 10:12 UTC, phil-davis commented
``backport-request`` label removed, since that is not relevant to a closed PR.