Use new DAV endpoint for single file uploads
owncloud/core pull request #28874
Opened 2017-08-31 13:48 UTC by PVince81

## Description
Use new DAV endpoint for single file uploads

## Related Issue
None.
Also see https://github.com/owncloud/core/pull/25494

## Motivation and Context
Same as https://github.com/owncloud/core/pull/25494

## How Has This Been Tested?
- [x] TEST: upload single file into current view
- [x] TEST: upload a file as a user "test@test" to confirm encoding works for the full DAV path

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Not sure if we want this right now, I'm thinking of reverting new dav for 10.0.3 due to https://github.com/owncloud/core/issues/28779.

Setting to "planned" to have a look later.

2017-10-20 10:05 UTC, jvillafanez commented
From https://github.com/owncloud/core/issues/29315#issuecomment-338162515

[ ] reuploading a file to an external storage causes an "undefined index: size" in the logs (not tested with the primary storage). Checked with 10.0.3. Not that the first time the file is uploaded, such log doesn't appear.

2017-10-20 11:33 UTC, PVince81 commented
@jvillafanez undefined size like this issue: https://github.com/owncloud/core/issues/29246

2017-12-18 11:39 UTC, PVince81 commented
#28853 was merged, we can move forward with this. @DeepDiver1975

2018-01-19 11:53 UTC, DeepDiver1975 requested changes

2018-01-19 11:53 UTC, DeepDiver1975 commented on apps/files/js/filelist.js
> +			return OC.linkToRemoteBase('dav') + '/files/' + uid + encodedPath;
not encoding the uid? just like below?

2018-01-19 11:53 UTC, DeepDiver1975 commented on core/js/tests/specs/files/clientSpec.js
> +				.toEqual('https://somehost:8080/owncloud/remote.php/dav/files/test%40%23%3F%25test/path/to%20sp%40ce/a%40b%23%3F%25/x');
user id missing in spec

2018-01-19 13:33 UTC, PVince81 commented on core/js/tests/specs/files/clientSpec.js
> +				.toEqual('https://somehost:8080/owncloud/remote.php/dav/files/test%40%23%3F%25test/path/to%20sp%40ce/a%40b%23%3F%25/x');
the user is defined here https://github.com/owncloud/core/pull/28874/files/bc7549a1bf3a18304078a8005b3e6fdb6888c1d1#diff-fddaf137bf7003f8ca5590ea5500d0e5R886 and is "test@#?%test", so the test will pass.

However in your other comment you pointed at another code path for upload URL, I likely missed adding a test for that one. Thanks for spotting

2018-01-30 14:46 UTC, PVince81 commented
@DeepDiver1975 updated and added missing tests. Please rereview

2018-02-07 11:45 UTC, PVince81 commented
@ownclouders rebase

2018-02-07 11:45 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-02-07 11:45 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-02-12 17:04 UTC, DeepDiver1975 approved these changes

2018-02-12 17:04 UTC, PVince81 commented
as discussed with @DeepDiver1975, this goes only to master

2018-02-13 05:24 UTC, merged

2018-04-10 14:24 UTC, PVince81 commented
considering that we want to focus work on stable10 we might still want to backport this. adding label as reminder