Missing oc_authtoken (session) for native clients
owncloud/core pull request #28879
Opened 2017-09-01 08:33 UTC by IljaN

## Description
oc_authtoken was not created for clients which use basic auth. (Probably everything, except browser and some dav-clients)

## Related Issue
#27845

## Motivation and Context
This  bug was introduced with commit f1dc2d9 - "Validate session only if we are not in a basic auth request". 

Looking at the commit message the intent is not quite clear to me because the dektop client and all the mobile clients use basic auth at the moment. As the issue is relatively old I assume that some technical circumstances changed or that the validateSesion method is badly named because basic auth is technically not a persisten session trough requet. With this assumption the intent of the commit makes sense.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-01 08:47 UTC, IljaN commented
@phisch / @DeepDiver1975: Is it  possible to move that session check to somwhere else? Was suprised when I saw session handling code in a method called "loadApps" ;-)))

2017-09-01 10:58 UTC, SamuAlfageme commented
@IljaN cool, now I'm getting all the sessions logged back in the webUI 🎉 


Revoking though, (using the 'Delete' button next to them) is still not working (i.e. clients using basic auth are still able to sync and keep their session - it spawns in the table on next client request). So https://github.com/owncloud/core/issues/27845 might be deeper. Also I've noticed after removing a browser session (from a different one) and hitting: 

```
curl 'https://<server>/index.php/settings/personal/authtokens' \
    -H 'OCS-APIREQUEST: true' \
    -H 'Cookie: $SESSION'
```

Server replies with 503. The rest of the endpoints is fine. No exception is raised in the logs.

2017-09-01 11:40 UTC, SamuAlfageme commented
Described that one issue in https://github.com/owncloud/core/issues/28881 as this one was only for the regression display.

2017-09-01 13:32 UTC, PVince81 commented
From my understanding from last time I looked at similar code, it seemed that there was a difference between basic auth and DAV authentication (still not sure where this is happening).

If we consider that both are two different things, then the old commit from @DeepDiver1975 was correct as it was only validating the session if we're NOT dealing with DAV authentication, so `$davUser` is null, in which case we're dealing with basic auth, not DAV auth.

The original issue though was that sessions did not appear in the list. Is there some piece of code inside of `validateSession` which we could extract and use here to make sure the session entry will be updated without validating ?

Now the other question would be whether it's really that bad to validate here additionally ?

Another concern: since you reversed the condition, it is likely that now basic auth is not getting validated any more. Maybe the `if` part should be removed completely ?

2017-09-01 14:01 UTC, IljaN commented
In my tests $davUser was always set using the sync client so go figure... Web interface does not go trough this codepath at all.

I also had the idea to pull the token update out but the code is buried in a private tokenProvider object inside session...

Yeah it would probably be the safest bet to always validate, basically reverting @DeepDiver1975 `s change.

2017-09-01 14:04 UTC, IljaN commented
Oh look what i found: 
```php
/**
	 * Add DAV authenticated. This should in an ideal world not be
	 * necessary but the iOS App reads cookies from anywhere instead
	 * only the DAV endpoint.
	 * This makes sure that the cookies will be valid for the whole scope
	 * @see https://github.com/owncloud/core/issues/22893
	 */
	$this->session->set(
		Auth::DAV_AUTHENTICATED, $this->getUser()->getUID()
	);
	return true;
```

2017-09-01 14:04 UTC, PVince81 commented
It is possible that "DAV auth" means "basic auth done on a Webdav endpoint"

2017-09-04 17:19 UTC, PVince81 commented on settings/Controller/AuthSettingsController.php
> +		if ($currentToken->getId() == $id) {
`===` ? See https://doc.owncloud.org/server/10.0/developer_manual/general/codingguidelines.html#operators

2017-09-04 17:21 UTC, PVince81 commented
If validating in all cases isn't causing any other side effects, then I'm fine with this.

Needs to be retested at best will most authentication schemes:
- basic auth on Webdav
- basic auth on OCS
- web UI session
- shibboleth ?
- auth with application token instead of password
- oauth2

2017-09-05 09:25 UTC, IljaN commented
Will figure out how to test most of these, not sure: 
...how to setup/test shibboleth and oauth2
... what exactly OCS is.

2017-09-05 09:26 UTC, PVince81 commented
@IljaN get help from QA or @SamuAlfageme for testing these cases

2017-09-05 11:08 UTC, SamuAlfageme commented
Some results after some quick checks: 

- basic auth on Webdav ✅ 
- basic auth on OCS ✅ 
- web UI session ✅ 
- shibboleth ❌ 
- auth with application token instead of password ✅ 
- oauth2 ✅ 

![sessions](https://user-images.githubusercontent.com/2644445/30058064-a1417106-9239-11e7-9963-fa4b899fd13d.png)


About Shib, I'm not sure if the sessions ever appeared in this section (or they have a separate pane somewhere; kind of like it happens with OAuth) 

Here ya go with a normal SAML request if that can help out determining if something is missing:

<details>
<summary>SAML-Authenticated <code>PROPFIND</code></summary>

```
curl \
-H 'Cookie:oc_sessionPassphrase=7hZcZNUIb3AaiNocC%2BIXh5aAYM36%2F3R1WG6i6OltcbqdYsJhHTorkR8%2BgQcmTZL7ax7CuavRwJL4GpNb2uBGPjEN2LsM2aMZ58pVCHlMzu5bMMkjzuPAvyNhwr6dgajQ; ocgwv1nxeve8=iq8npgptet00ocj15qtc2vr4g6; _shibsession_64656661756c7468747470733a2f2f646f636b65722e6f632e736f6c6964676561722e65733a31303237312f6f632d73686962=_58f8ec23b20e1ac03e7d389bad9d7197' \
-H 'Content-Length:114' \
 -X PROPFIND 'https://<server>/<shib-path>/remote.php/dav/files/alterego@testshib.org/' --data-binary '<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:">
  <d:prop>
    <d:getlastmodified />
  </d:prop>
</d:propfind>
'
```

</details>
<br/>

@IljaN maybe we can also get the `_shibsession_*=_*'`s logged in the session table somehow. I don't really know the specifics about it maybe @butonic or @DeepDiver1975 can help here. 

@PVince81 about

> basic auth on OCS 

I'm getting the "last activity" time updated from `ocs` calls, so I'd say that one works as expected as well. (they don't and I guess shouldn't originate new entries)

2017-09-05 11:17 UTC, PVince81 commented
@SamuAlfageme for shib, try with shib and the latest OC version before the regression to find out whether it ever worked before.

2017-09-06 19:38 UTC, PVince81 commented
this looks suspicious:
```

auth.access files app with basic authprovisioning.Making a web request with an enabled usersharing.Empting trashbinsharing.orphaned sharessharing.deleting file out of a share as recipient creates a backup for the ownersharing.deleting folder out of a share as recipient creates a backup for the ownersharing.moving file out of a share as recipient creates a backup for the ownersharing.moving folder out of a share as recipient creates a backup for the ownertrashbin-new-endpoint.deleting a file moves it to trashbintrashbin-new-endpoint.deleting a folder moves it to trashbintrashbin-new-endpoint.deleting a file of a shared folder moves it to trashbintrashbin-new-endpoint.deleting a shared folder moves it to trashbintrashbin-new-endpoint.deleting a received folder doesn't move it to trashbintrashbin-new-endpoint.deleting a file in a received folder it is moved to the trashbintrashbin-new-endpoint.Trashbin can be emptiedtrashbin-new-endpoint.A deleted file can be restoredtrashbin-new-endpoint.Deleting a folder into external storage moves it to the trashbintrashbin-new-endpoint.Deleting a file into external storage moves it to the trashbin and can be restoredtrashbin-new-endpoint.deleting a file moves it to trashbintrashbin-new-endpoint.deleting a folder moves it to trashbintrashbin-new-endpoint.deleting a file of a shared folder moves it to trashbintrashbin-new-endpoint.deleting a shared folder moves it to trashbintrashbin-new-endpoint.deleting a received folder doesn't move it to trashbintrashbin-new-endpoint.deleting a file in a received folder it is moved to the trashbintrashbin-new-endpoint.Trashbin can be emptiedtrashbin-new-endpoint.A deleted file can be restoredtrashbin-new-endpoint.Deleting a folder into external storage moves it to the trashbintrashbin-new-endpoint.Deleting a file into external storage moves it to the trashbin and can be restoredtrashbin-new-endpoint.Deleting an updated file into external storage moves it to the trashbin and can be restored
--
```

2017-09-07 16:40 UTC, IljaN commented
All tests should pass now :crossed_fingers:

2017-09-08 13:33 UTC, IljaN commented
@SamuAlfageme All tests are green now, please retest.

2017-09-09 08:26 UTC, PVince81 commented
moving to planned (10.0.4), too risky for post-RC.

Also I'd like to have a review from @DeepDiver1975

2017-09-18 13:58 UTC, PVince81 commented
@DeepDiver1975 can you review ?

@SamuAlfageme can you retest ?

2017-09-25 08:38 UTC, DeepDiver1975 requested changes
Please cleanup the git history. THX

2017-09-25 08:38 UTC, DeepDiver1975 commented on lib/private/legacy/app.php
> +					$userSession = \OC::$server->getUserSession();
Was this code change tested with occ commands as well as installation and upgrade scenarios?

2017-10-11 11:09 UTC, IljaN commented
@DeepDiver1975 Squashed

2017-10-24 16:33 UTC, IljaN commented
@DeepDiver1975 ping

2017-10-24 16:34 UTC, IljaN commented
ping

2017-11-02 09:03 UTC, PVince81 commented
@IljaN please answer here https://github.com/owncloud/core/pull/28879#discussion_r140716530

2017-11-02 09:06 UTC, IljaN commented on lib/private/legacy/app.php
> +					$userSession = \OC::$server->getUserSession();
@DeepDiver1975 What scenarios do you have in mind? How are occ commands related to authentication?

2017-11-02 09:24 UTC, DeepDiver1975 commented on lib/private/legacy/app.php
> +					$userSession = \OC::$server->getUserSession();
occ calls loadApps as well - there is no request object then and no usersession object.
thats my point ... but maybe the code does not even go there .. no idea - please test - THX

2017-11-06 14:30 UTC, IljaN commented
Upgrade works

2017-11-08 09:14 UTC, PVince81 commented
@davitol can you regression test auth with this PR, same as with https://github.com/owncloud/core/pull/28733 ?

If all goes well we can merge this and

- [ ] forward port to master

2017-11-08 09:15 UTC, PVince81 commented
rebased for CI (Drone didn't start...)

2017-11-08 11:26 UTC, davitol commented
> @davitol can you regression test auth with this PR, same as with #28733 ?
> 
> If all goes well we can merge this and

Uploading a file via webDAV using cadaver. The session is not shown in the list

![screen shot 2017-11-08 at 12 26 30](https://user-images.githubusercontent.com/10596560/32546653-1bbf4a48-c480-11e7-811e-71cf92e5abe6.png)

2017-11-08 11:41 UTC, IljaN commented
@davitol I just did a quicktest with desktop client, both web-session and desktop client session are displayed. Will try with cadavre to see what the difference is.

2017-11-08 11:52 UTC, davitol commented
> @davitol I just did a quicktest with desktop client, both web-session and desktop client session are displayed. Will try with cadavre to see what the difference is.

With Desktop worked for me, but for example with iOS app it shows multiple sessions, not sure if due to iOS app or for the PR (see below)

![screen shot 2017-11-08 at 12 50 16](https://user-images.githubusercontent.com/10596560/32547695-9ea5adc8-c483-11e7-9610-0b0239208c08.png)

2017-11-08 12:30 UTC, IljaN commented
@davitol I can confirm that cadavre session is not displayed... investigating

2017-11-08 16:23 UTC, IljaN commented
@davitol We figured out that cadaver does not support cookies thus doing basic auth on every request. This is why nothing is displayed in the sessions view because there is technically no session established. This would explain why Cyberduck is displayed (it probably supports cookies) 

After discussing with @DeepDiver1975 the expected behavior is that nothing is displayed for clients which do not support cookies. 

If we would "fix" that, we would have a entry for every request made by cadaver.

As for the iOS issue I need to find someone with a iPhone to be able to debug this...

2017-11-08 16:40 UTC, davitol commented
> PS: I will try to replicate the issue with Android

@IljaN With Android it went fine for me

![screen shot 2017-11-08 at 17 39 08](https://user-images.githubusercontent.com/10596560/32561152-d7c8a57e-c4ab-11e7-9674-f7306dd8087d.png)

2017-11-09 12:06 UTC, jesmrec commented
@IljaN the point is the way the iOS client is handling with the cookies. Some request are including authorization basic header but no cookies, therefore the server answers with a new cookie, and i guess that in this case a new row is included there. We will take care

2017-11-09 15:06 UTC, PVince81 commented
@jesmrec so can we merge this or will this require modifications of the PR code ?

2017-11-09 20:00 UTC, jesmrec commented
@PVince81 you can merge

2017-11-10 07:04 UTC, PVince81 commented
@jesmrec thanks.

Now for a last CI battle then we can merge.

2017-11-10 11:15 UTC, PVince81 commented
Rebased for CI, hopefully for higher timeout values

2017-11-10 13:48 UTC, PVince81 commented
codecov errors about the legacy app code, passing on this one 🙈

2017-11-10 13:48 UTC, merged

2017-11-10 13:49 UTC, PVince81 commented
@IljaN please forward port to master