Validate mail address and mail domain
owncloud/core pull request #28948
Opened 2017-09-07 18:32 UTC by imujjwal96

## Description

Using regular expressions to validate  `$mail_from_address` and `$mail_domain`
## Related Issue

Fixes #28436 

## How Has This Been Tested?

Tested regex here: http://www.phpliveregex.com/

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-09-08 05:42 UTC, phil-davis commented
This PR also got a Jenkins problem with ``sharing-v1.feature:914``
There seems to be a lot of this now???

2017-09-08 06:56 UTC, mmattel commented on settings/Controller/MailSettingsController.php
> +					(string) $this->l10n->t('Invalid Address')
Text proposal: ``Invalid Address`` --> ``Invalid eMail recipient``

2017-09-08 06:57 UTC, mmattel commented on settings/Controller/MailSettingsController.php
> +					(string) $this->l10n->t('Invalid Domain')
Text proposal: ``Invalid Domain`` --> ``Invalid eMail domain``

2017-09-11 05:58 UTC, DeepDiver1975 requested changes

2017-09-11 05:58 UTC, DeepDiver1975 commented on settings/Controller/MailSettingsController.php
> +		$regex_address = "/(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|\"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*\")/";
Please use IMailer::validateMailAddress function for this - THX

2017-09-11 12:09 UTC, imujjwal96 commented on settings/Controller/MailSettingsController.php
> +		$regex_address = "/(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|\"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*\")/";
We are taking two separate inputs for `$mail_from_address` and `$mail_domain`. Should I merge them into a single input in the UI?

2017-09-12 16:45 UTC, imujjwal96 commented on settings/Controller/MailSettingsController.php
> +		$regex_address = "/(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|\"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*\")/";
@DeepDiver1975 I've updated it. Though i didn't make any change in the UI yet.

2017-09-18 13:26 UTC, PVince81 commented
```
Tests\Settings\Controller\MailSettingsControllerTest::testSetMailSettings
Failed asserting that Array &0 (
    'data' => Array &1 (
        'message' => 'Saved'
    )
    'status' => 'error'
) is identical to Array &0 (
    'data' => Array &1 (
        'message' => 'Saved'
    )
    'status' => 'success'
).

/var/lib/jenkins/workspace/owncloud-core_core_PR-28948-II5ZCIFKAAAJDW3PM64ZM7S65WOXKGXVTLCQ5NPVX6GY3POENMVA/tests/Settings/Controller/MailSettingsControllerTest.php:120
```

@imujjwal96 can you have a look ? Also once fixed, please squash your commits into a single one. Thanks

2017-09-18 13:58 UTC, imujjwal96 commented
@PVince81 Is this the expected value? 
![image](https://user-images.githubusercontent.com/8245662/30545438-374a9016-9ca7-11e7-978e-b2c6431437ec.png)

The test case expects it as
`demo@owncloud.com `  @ `owncloud.com`
![image](https://user-images.githubusercontent.com/8245662/30545516-7b2b19b8-9ca7-11e7-9ea7-04974c361a4d.png)

2017-09-18 14:16 UTC, PVince81 commented
@imujjwal96 hmm maybe that old test was wrong

2017-11-06 14:07 UTC, PVince81 commented
kicked Jenkins

2017-12-19 13:58 UTC, PVince81 commented
Taking over for rebasing, here: https://github.com/owncloud/core/pull/29909

2017-12-19 13:58 UTC, closed without merging