Fix doc blocks / namespacing - everywhere
owncloud/core pull request #28986
Opened 2017-09-12 12:06 UTC by tomneedham

(+ one bonus that was never actually included)

2017-09-12 12:09 UTC, butonic commented
![Fix all the doc blocks](https://memegenerator.net/img/instances/500x/80365682/fix-all-the-doc-blocks.jpg)

2017-09-12 12:17 UTC, DeepDiver1975 requested changes

2017-09-12 12:17 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/Directory.php
> +	 * @throws \Sabre\DAV\Exception\Forbidden
dup

2017-09-12 12:27 UTC, butonic commented on apps/dav/lib/Connector/Sabre/Directory.php
> +	 * @throws \Sabre\DAV\Exception\Forbidden
Not a duplicate: OCA\DAV\Connector\Sabre\Exception\Forbidden != \Sabre\DAV\Exception\Forbidden

2017-09-13 11:06 UTC, butonic approved these changes

2017-09-13 11:14 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/Directory.php
> +	 * @throws \Sabre\DAV\Exception\Forbidden
then let's add a proper use statement

```php
use \Sabre\DAV\Exception\Forbidden as SabreForbidden

2017-09-14 11:39 UTC, tomneedham commented
Fixed and prefixed sabre exceptions with 'Sabre'

2017-09-14 14:37 UTC, tomneedham commented
horracle timeout

2017-09-14 14:38 UTC, tomneedham commented
rebased for luck

2017-10-10 11:10 UTC, DeepDiver1975 approved these changes

2017-10-10 12:12 UTC, tomneedham commented
rebased - waiting for CI

2017-10-12 12:40 UTC, tomneedham commented
jenkins timeout - rebasing

2017-10-16 14:22 UTC, merged