Allow non hardcoded icons for apps
owncloud/core pull request #29013
Opened 2017-09-14 16:27 UTC by sharidas

This change helps users to provide their own
custom icons for the apps which work with
ownCloud.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change helps contributors to use non-hardcoded icons. That is every app developer or contributor can now have their own separate icons which can be used with core.

## Related Issue

https://github.com/owncloud/core/issues/28751

## Motivation and Context

At present the icons are hard coded and are located at core. This prohibits the usage of custom icons for apps. With this change, contributors of apps, can have their own custom app which can be used along with core. No more saving of svg files in the core.

## How Has This Been Tested?

I have verified it against 2 apps. One is encryption app  ( the change was made in the SettingsManager.php) and another app was firewall app. For the firewall app I modified the AdminSection.php to test.

## Screenshots (if appropriate):
![settingspagenew](https://user-images.githubusercontent.com/3600427/30441656-b26ce324-9997-11e7-9cc1-45868762971c.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-15 10:30 UTC, tomneedham requested changes

2017-09-15 10:30 UTC, tomneedham commented on lib/public/Settings/ISection.php
>  	public function getIconName();
I think let's kill the name and just keep the url and we'll make it backwards compatible

2017-09-15 10:30 UTC, tomneedham commented on settings/Controller/SettingsPageController.php
> +				'icon' => $section->getIconName(),
so we can get rid of this also

2017-09-15 10:30 UTC, tomneedham commented on lib/private/legacy/app.php
> +
nooooo more static ;) Why do we need to do this copying stuff?

2017-09-15 10:30 UTC, tomneedham commented on lib/private/Settings/Section.php
> +	}
I think we could use the urlgenerator here, injected in properly

2017-09-15 10:37 UTC, sharidas commented on lib/private/legacy/app.php
> +
The intention behind this change was to fetch the data from the web url and download to apps/img folder. Anything wrong?

2017-09-15 11:54 UTC, sharidas commented
Attaching new screenshot for the change made: 
![newscreenshot](https://user-images.githubusercontent.com/3600427/30481149-c2fe98e2-9a3a-11e7-911f-5a06c645aacd.png)

2017-09-15 12:18 UTC, tomneedham requested changes

2017-09-15 12:18 UTC, tomneedham commented on lib/private/Settings/Section.php
> +	public function __construct($id, $name, $priority, $url='settings') {
we can pass in the urlgenerator here - then adjust the constructor to pass it in in `\OC\Settings\SettingsManager`

2017-09-15 12:18 UTC, tomneedham commented on lib/private/Settings/Section.php
> +			return \OC::$server->getURLGenerator()->imagePath($this->getID(), $this->url);
use passed in urlgenerator. Also, the Id is not necessarily the app id so might need some thought here

2017-09-15 12:18 UTC, tomneedham commented on settings/templates/settingsPage.php
> +				if (strpos($item['url'], '/', 1) !== false) {
we may as well standardise the core icons. So always pass a url. In the controller figure out if its a core icon or not. Then we can remove these crappy css rules for the icons

2017-09-15 14:01 UTC, tomneedham commented on lib/private/Settings/SettingsManager.php
>  				new Section('updates', $this->l->t('Updates'), 20, 'update'),
missing this one?

2017-09-15 14:01 UTC, tomneedham commented on lib/public/Settings/ISection.php
>  	 * @since 10.0
10.0.4

2017-09-15 14:02 UTC, tomneedham commented on lib/public/Settings/ISection.php
>  	 * @since 10.0
and we should keep the old method, but add `@depreceated` from 10.0.4. But this shoudl also be backwards compatible. So inside the section implementation, set `$this->url` using the url generator - don't need to worry about injection for this backwards compat

2017-09-15 14:24 UTC, sharidas commented on lib/public/Settings/ISection.php
> +	 * @deprecated since 10.0.4
Added `@deprecated`

2017-09-15 15:27 UTC, tomneedham commented
+ we should update the docs here https://doc.owncloud.org/server/latest/developer_manual/core/theming.html?highlight=theme#create-custom-sections

2017-09-19 14:30 UTC, sharidas commented on lib/public/Settings/ISection.php
>  	 * @since 10.0
So if we add `@deprecated` for getIconName in ISection then, I think we will end up having both getIconName and getIconUrl. Because the apps which will be implementing ISection would need to implement both the methods.
So ideally if we don't want to deprecate it, then may be we can have getIconName. And make it app developers responsibility to get the url to be generated and returned from getIconName(), instead of just returning the icon name which it does currently.

2017-09-27 07:13 UTC, DeepDiver1975 requested changes

2017-09-27 07:13 UTC, DeepDiver1975 commented on lib/public/Settings/ISection.php
> +	public function getIconUrl();
I don't like this - this will break all existing implementations 👎

2017-09-27 07:13 UTC, DeepDiver1975 commented on lib/public/Settings/ISection.php
> +	public function getIconUrl();
We should implement this more in sense where the returned icon name can either be a css class (as done until today) or an image name of the app which hosts the svg.

this way we don't need to change apis and implementation all over the place.

```php
$icon = $section->getIconName();
if (file_exists("$appPath/img/$icon.svg")) {
    $url = $urlGenerator->imagePath("$icon.svg");
    // TODO: add background styling hack
} else {
    // TODO: add icon css class
}

2017-10-05 13:01 UTC, jvillafanez commented on settings/Controller/SettingsPageController.php
> +			$icon = $section->getIconName() . '.svg';
Move this "getIcon" code to another function and call it here. This logic should be probably out of this class so we can unittest it properly. If there is no place for this, it should be fine to create a private function here in the short term.

In addition, I think there is already a function to retrieve icons for apps (I might be wrong) Any reason to not use it?

In the phpdoc of the new function (whenever is placed) include how the function should behave. Right now I'm not sure what is the expected behaviour if several icons are provided: if I want to use "marvellous_icon.png", why I'm checking "marvellous_icon.png.svg"?
If only .svg files are supported, make sure this is known, including in the comments of the function.
Since I have no idea what is the expected behaviour here, I'm more inclined to think the current behaviour is buggy.

2017-10-05 13:01 UTC, jvillafanez commented on settings/Controller/SettingsPageController.php
> +			$icon = $section->getIconName() . '.svg';
A couple of extra things:
* Unless the icon name is already sanitized, make sure it doesn't contain `/../` or something similar
* I'm not sure what is the "default" expectation: I guess it should be using the filename without extension as icon name (which is fine). In any case, optimize for this default case. If the default is to include the extension you'd be checking for a missing file constantly. Just something to take care of.

2017-10-05 13:01 UTC, jvillafanez commented on settings/templates/settingsPage.php
> +			$ocUrlorIcon = \OCP\Util::sanitizeHTML($item['icon']);
This could be a good time to rewrite this piece to just use this as a template and avoid adding logic here.

2017-10-06 10:22 UTC, sharidas commented on settings/templates/settingsPage.php
> +			$ocUrlorIcon = \OCP\Util::sanitizeHTML($item['icon']);
Agreed. Can we do this as a separate PR?

2017-10-06 10:33 UTC, jvillafanez commented on settings/templates/settingsPage.php
> +			$ocUrlorIcon = \OCP\Util::sanitizeHTML($item['icon']);
I don't really mind, but there will be conflicts with this PR if t isn't merged soon because that code will depend on this branch... @tomneedham @DeepDiver1975 opinions?

2017-10-06 10:43 UTC, DeepDiver1975 commented on settings/templates/settingsPage.php
> +			$ocUrlorIcon = \OCP\Util::sanitizeHTML($item['icon']);
do it in here - own commit for now to see the diff ... later we squash

2017-10-06 11:55 UTC, sharidas commented on settings/templates/settingsPage.php
> +			$ocUrlorIcon = \OCP\Util::sanitizeHTML($item['icon']);
Moved the logic from here to https://github.com/owncloud/core/pull/29013/files#diff-3393e43384d070ab12865348f9279030R123. I hope this makes sense now.

2017-10-06 12:43 UTC, jvillafanez commented
The rewrite I had in mind was more like:
```
<li class="divider"><?php p($l->t('Personal')); ?></li>
<?php foreach($_['personalNav'] as $item): ?>
<li>
  <?php if ($item['active']): ?>
    <?php if ($item['iconIsUrl]): ?>
      <a class="svg active" style="background-image: url(<?php p($item['icon']) ?>)" href='<?php p($item['link']); ?>'><?php p($item['name']) ?></a>
    <?php else: ?>
      <a class="svg active icon-<?php p($item['icon']) ?>)" href='<?php p($item['link']); ?>'><?php p($item['name']) ?></a>
    <?php endif; ?>
  <?php else: ?>
    <?php if ($item['iconIsUrl]): ?>
      <a class="svg" style="background-image: url(<?php p($item['icon']) ?>)" href='<?php p($item['link']); ?>'><?php p($item['name']) ?></a>
    <?php else: ?>
      <a class="svg icon-<?php p($item['icon']) ?>)" href='<?php p($item['link']); ?>'><?php p($item['name']) ?></a>
  <?php endif; ?>
</li>
<?php endforeach; ?>
```

Maybe we can make it smaller injecting "active" or an empty string instead of checking if the `$item['active']` is a boolean or not, but as you see, the template just output information with the minimum control structures.

2017-10-06 15:04 UTC, sharidas commented
@jvillafanez  I have updated the change let me know if this ok.

2017-10-09 06:47 UTC, jvillafanez commented on settings/templates/settingsPage.php
> +				<a class="svg <?php $item['active'] ? p(' active ') : p('') ?>" style="background-image: url(<?php p($item['icon']) ?>)" href='<?php p(\OCP\Util::sanitizeHTML($item['link'])); ?>'><?php p(\OCP\Ut
`\OCP\Util::sanitizeHTML(...)` isn't needed with the `p` function

2017-10-09 06:49 UTC, jvillafanez commented on settings/templates/settingsPage.php
> +		    <?php foreach($_['adminNav'] as $item): ?>
indentation here seems misplaced

2017-10-09 06:56 UTC, sharidas commented
@jvillafanez Corrected indentation and removed call to `\OCP\Util::sanitizeHTML()` inside `p()`

2017-10-09 07:06 UTC, sharidas commented on settings/templates/settingsPage.php
> +		    <?php foreach($_['adminNav'] as $item): ?>
Fixed.

2017-10-09 07:06 UTC, sharidas commented on settings/templates/settingsPage.php
> +				<a class="svg <?php $item['active'] ? p(' active ') : p('') ?>" style="background-image: url(<?php p($item['icon']) ?>)" href='<?php p(\OCP\Util::sanitizeHTML($item['link'])); ?>'><?php p(\OCP\Ut
Removed the call to `sanitizeHTML`

2017-10-09 07:18 UTC, jvillafanez approved these changes
Code looks good to me, not tested.

2017-10-09 07:25 UTC, sharidas commented
Tested the code by replacing icon `password` with `docker`. I copied docker.svg from https://worldvectorlogo.com/download/docker.svg and the settings page looks like this:
![changeencryptionicon](https://user-images.githubusercontent.com/3600427/31328113-e4f45112-acf0-11e7-9d29-309ab62af913.png)
And when the change is reverted back to `password` at https://github.com/owncloud/core/blob/master/lib/private/Settings/SettingsManager.php#L204 the settings page encryption icon looks like this:
![changeencryptionicon_old](https://user-images.githubusercontent.com/3600427/31328150-1ddf9b80-acf1-11e7-8d44-523213e38940.png)

2017-10-26 09:12 UTC, PVince81 commented on lib/private/Settings/SettingsManager.php
> -				new Section('updates', $this->l->t('Updates'), 20, 'update'),
why remove this ?

2017-10-26 09:18 UTC, sharidas commented on lib/private/Settings/SettingsManager.php
> -				new Section('updates', $this->l->t('Updates'), 20, 'update'),
While searching for update.svg, I couldn't find at core. That made me remove this line. I can revert back the change, if my finding was wrong.

2017-10-26 09:20 UTC, PVince81 commented on lib/private/Settings/SettingsManager.php
> -				new Section('updates', $this->l->t('Updates'), 20, 'update'),
Thanks for the explanation, I just wanted to double check that this wasn't a mistake. Let's keep it.

2017-10-26 09:20 UTC, merged

2017-10-26 09:20 UTC, PVince81 commented
@sharidas please backport

2017-10-26 09:45 UTC, sharidas commented
Created backport PR: https://github.com/owncloud/core/pull/29358