UI tests for moving files & folders
owncloud/core pull request #29010
Opened 2017-09-14 11:40 UTC by individual-it

## Description
UI tests that check if moving of files and folders happens correctly in the Web UI

## Related Issue
owncloud/QA#437

## Motivation and Context
run smoke tests automatically

## How Has This Been Tested?
run new tests locally, travis will tests the whole set

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-09-14 12:28 UTC, phil-davis requested changes

2017-09-14 12:28 UTC, phil-davis commented on tests/ui/features/bootstrap/FilesContext.php
> +	public function theMovedElementsShouldBeListedInTheInTheFolder(
InTheInThe
in the step text as well as the method name.
search/replace

2017-09-14 12:28 UTC, phil-davis commented on tests/ui/features/files/moveFiles.feature
> +	Scenario: move a file into a folder (problematic characters)
This is a fun test :)

2017-09-14 12:28 UTC, phil-davis commented on tests/ui/features/files/moveFolders.feature
> +	Scenario: move a folder into an other folder
Since you have to make some changes, may as well:
s/an other/another/

2017-09-15 16:46 UTC, phil-davis approved these changes

2017-09-15 16:47 UTC, merged

2017-09-21 01:04 UTC, individual-it commented
backport to stable10 in #29062