[WIP] Replace group manager with central group table
owncloud/core pull request #29107
Opened 2017-09-27 12:30 UTC by mrow4a

## Related Issue
fixes #27623 

## Plan
- [x] design new groups table (https://cloud.owncloud.com/index.php/s/fPpsY3J26nhT44e -> password: owncloud)
- [x] implement group entity and entity mapper
- [ ] integrate group entity mapper into the group manager
- [ ] see jenkins expode :boom: 
- [ ] iterate over all failing unit tests
- [ ] keep a close eye on the unit test execution time
- [ ] implement sync command
- [ ] design indixes based on used queries
- [ ] migration of local groups
- [ ] migration of ldap groups
- [ ] migration of saml groups
- [ ] migration or ..... groups
- [ ] ldap integration 

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-27 18:25 UTC, tomneedham commented on lib/private/Group/GroupEntity.php
> +	}
will we support a displayname as well?

2017-09-27 18:28 UTC, mrow4a commented on lib/private/Group/GroupEntity.php
> +	}
Is it requirement for LDAP?

2017-10-02 06:24 UTC, DeepDiver1975 requested changes

2017-10-02 06:24 UTC, DeepDiver1975 commented on lib/private/Group/BackendGroup.php
> +	protected $groupId;
not needed

2017-10-02 06:24 UTC, DeepDiver1975 commented on lib/private/Group/BackendGroup.php
> +	protected $displayName;
not needed

2017-10-02 06:24 UTC, DeepDiver1975 commented on lib/private/Group/BackendGroup.php
> +	protected $backend;
phpdoc missing

2017-10-02 06:24 UTC, DeepDiver1975 commented on core/Migrations/Version20170927145820.php
> +		//$table->addForeignKeyConstraint("{$prefix}backend_groups",array('backend_group_id'), array('id'));
please add right away

2017-10-02 06:24 UTC, DeepDiver1975 commented on core/Migrations/Version20170927145820.php
> +		$table->setPrimaryKey(['id']);
no further indexes?

2017-10-02 06:24 UTC, DeepDiver1975 commented on core/Migrations/Version20170927145820.php
> +		$table->addColumn('account_id', Type::BIGINT, [
👍

2017-10-02 06:24 UTC, DeepDiver1975 commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->beginTransaction();
commit?

2017-10-02 06:24 UTC, DeepDiver1975 commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->rollBack();
I see - hmmmm - does this work?

2017-10-02 06:24 UTC, DeepDiver1975 commented on tests/lib/Group/GroupMapperTest.php
> +		$this->assertInstanceOf("OC\Group\BackendGroup", $result);
```php
BackendGroup::class

2017-10-02 06:24 UTC, DeepDiver1975 commented on tests/lib/Group/GroupMapperTest.php
> +		$mapper = \OC::$server->getGroupMapper();
use this->mapper

2017-10-02 06:24 UTC, DeepDiver1975 commented on version.php
> +$OC_VersionString = '10.0.4';
no - keep 10.0.3

2017-10-02 06:24 UTC, DeepDiver1975 commented on version.php
> -$OC_Version = [10, 0, 3, 3];
no - 10.0.3.4

2017-10-02 07:17 UTC, tomneedham commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->beginTransaction();
unless you hit nestingTransationLevel = 0 it will never actually hit the DB

2017-10-02 09:47 UTC, mrow4a commented on version.php
> +$OC_VersionString = '10.0.4';
I think if you change the schema, you need to increment version.

2017-10-02 09:49 UTC, mrow4a commented on core/Migrations/Version20170927145820.php
> +		$table->setPrimaryKey(['id']);
I did not decide on it yet.

2017-10-02 10:20 UTC, DeepDiver1975 commented on version.php
> +$OC_VersionString = '10.0.4';
Not the version string but oc_version

2017-10-02 10:51 UTC, DeepDiver1975 requested changes

2017-10-02 10:51 UTC, DeepDiver1975 commented on tests/lib/DB/MigratorTest.php
> +		$this->assertTrue(true);
we should assert that the fk was set

2017-10-02 10:51 UTC, DeepDiver1975 commented on lib/private/DB/OracleMigrator.php
> +			$tableDiff->changedForeignKeys = array_map(function(Index $index) {
ForeignKeyConstraint not Index

2017-10-02 10:53 UTC, mrow4a commented on lib/private/DB/OracleMigrator.php
> +			$tableDiff->changedForeignKeys = array_map(function(Index $index) {
Oh, yes, sorry

2017-10-05 19:59 UTC, DeepDiver1975 commented
foreign key pr is merged to master - please rebase - THX

2017-10-05 21:07 UTC, mrow4a commented
One of the approaches proposed in https://github.com/owncloud/core/pull/29154

2017-10-09 13:05 UTC, mrow4a commented
@jvillafanez

2017-10-10 07:23 UTC, jvillafanez commented on lib/public/AppFramework/Db/Access.php
> +abstract class Access {
I'm unsure of the purpose of this class... maybe it's the name what doesn't fit...

Just some personal recommendations to recheck:
* Make sure the purpose of this class is clear. This implies that only the specific methods to fufill its purpose should be there.
* Make sure the abstract class has clear extension points, and evaluate how subclasses will complete this abstract class.

I guess this second point is what bothers me: abstract classes should have at least an abstract method that subclasses should implement. This isn't the case here.
Inheritance doesn't seem the way to go in this case. I'd rather use composition: just create the "Access" class and inject it wherever its needed.

2017-10-10 07:23 UTC, jvillafanez commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->beginTransaction();
I'd add a comment to make sure the trick won't be forgotten, otherwise it's quite weird that you have one transaction hanging around.

2017-10-10 07:29 UTC, DeepDiver1975 commented on lib/private/Server.php
> +		$this->registerService('GroupMapper', function(Server $c) {
It is not exposed because as per definition developers are only allowed to work on interface which are in the OCP namespace.

2017-10-10 07:30 UTC, DeepDiver1975 commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->beginTransaction();
@mrow4a please implement this without the transaction - I'm having a bad guts feeling.

2017-10-16 09:34 UTC, mrow4a commented on tests/lib/Group/GroupMapperTest.php
> +		\OC::$server->getDatabaseConnection()->beginTransaction();
I think it is just used to properly clean after the unit test. The same is in AccountMapper

2017-10-16 09:45 UTC, mrow4a commented
I think resolved most of your doubt with this base commit.

2017-11-24 07:54 UTC, DeepDiver1975 commented
@mrow4a please resolve the conflicts above and rebase - I want to see code coverage on this - THX

2017-11-27 12:47 UTC, mrow4a commented
@DeepDiver1975 A lot of unit tests are coming from related PRs, which will go on top here. I will rebase all of them which use this PR as base

2017-11-28 08:26 UTC, PVince81 commented
- [ ] test that the custom groups app still works fine

I assume that now we're only syncing group memberships, which means that the sync command needs to run for groups also. So when people create custom groups they'll need to wait for the next run for said groups to be available.

2017-11-28 09:29 UTC, mrow4a commented
Not necessarily, you can add it with group manager using createFromBackend

2017-11-28 09:33 UTC, PVince81 commented
Who is "you" ? do you mean the custom groups code ?

If the addition of the central groups table require group backend apps to be modified to work properly, we'll need to communicate this clearly once this is planned for release.

2017-11-28 11:35 UTC, mrow4a commented
Ye, code would need to add its backend to group manager (as previously), but when group is created, it has to use group manager instead of it's internal create (group manager will also create group internally)

2017-11-28 12:05 UTC, mrow4a commented on lib/private/Server.php
> -		$this->registerService('AccountMapper', function(Server $c) {
Adjusted as required @DeepDiver1975

2017-12-04 10:01 UTC, mrow4a commented
Integration PR here https://github.com/owncloud/core/pull/29282 -> it will also adjust failing tests here.

2018-01-15 13:30 UTC, mrow4a commented
@DeepDiver1975 @butonic Should we add checkbox somewhere in user interface asking if group memberships should be checked at each login? (If group was removed, or membership was denied) 

I would disable it by default, since in a lot of cases it should be done with cronjob e.g. daily. (but some organisations might be very strict about it).

2018-01-15 14:04 UTC, DeepDiver1975 commented
> @DeepDiver1975 @butonic Should we add checkbox somewhere in user interface asking if group memberships should be checked at each login? (If group was removed, or membership was denied)
> 
> I would disable it by default, since in a lot of cases it should be done with cronjob e.g. daily. (but some organisations might be very strict about it).

we can take care of this in a follow up
keep it simple

2018-01-24 09:35 UTC, mrow4a commented
Both sync command and integration is finished @DeepDiver1975 @PVince81 @butonic @tomneedham 

https://github.com/owncloud/core/pull/29752 - sync
https://github.com/owncloud/core/pull/29282 - integration

Shall we merge it to this PR and have one big? @DeepDiver1975

2018-02-04 19:09 UTC, mrow4a commented on lib/private/User/Manager.php
> -	public function reset(AccountMapper $mapper, $backends, $syncService) {
This was not deleted, but moved to the bottom of the file

2018-02-04 19:12 UTC, mrow4a commented on lib/private/Group/Manager.php
> +		$backendGroup = $this->newBackendGroup($gid, $backend);
Hmm, seems I should apply similar change here as @tomneedham applied with createOrSyncAccount in UserManager

2018-02-04 19:13 UTC, mrow4a commented on lib/public/IGroupManager.php
> +	 * @since 10.0
Hmm I am not sure if depreciating createGroupFromBackend and createUserFromBacked is good idea, would need to discuss the full motivation behind that @tomneedham

2018-02-08 22:25 UTC, mrow4a commented
Changing the label to "To Review" - the feature is ready and passes the tests @tomneedham @DeepDiver1975 @butonic @patrickjahns

2018-02-09 01:31 UTC, phil-davis commented
@mrow4a you can also remove [WIP] from the PR title.

2018-02-11 15:20 UTC, mrow4a commented
To help review the change, I sorted changed file according to their importance, please have a look in the first comment -> https://github.com/owncloud/core/pull/29107#issue-143378849 

@DeepDiver1975 @tomneedham @butonic @patrickjahns

2018-02-20 11:47 UTC, butonic commented on lib/private/Group/BackendGroup.php
> +	protected $groupId;
why? the table has id, group_id, display_name and backend
I intend to add a uuid column because group_id is more like a group_name. groups might be renamed. Display name is different, typically being more verbose.

2018-02-20 12:44 UTC, tomneedham commented on lib/private/Group/BackendGroup.php
> +	protected $groupId;
I think because the entity class handles these properties for you. Not that you don't need a groupId

2018-02-20 14:27 UTC, tomneedham commented
Testing with LDAP:

 - When logging in, a users memberships / groups are not synced. This is important where rules / permissions are enforced using group membership status.

2018-02-20 18:31 UTC, mrow4a commented
True, in each session login memberships for this users should be added/deleted

2018-02-20 19:17 UTC, butonic commented
should we sync all groups as a migration step? or just document that after upgrading the admin needs to do this manually? I am leaning in favor of an additional migration step because there is no way around it. but I would like to know how long it takes to sync 100k users with 80k groups first...

2018-02-20 19:22 UTC, mrow4a commented
You mean, while setup is being upgraded/setup it should allow to sync everything down?

2018-02-20 20:32 UTC, tomneedham commented
Migration step IMO. This was how it worked for the accounts table. We synced the accounts table with the database user backend in a migration step.

2018-02-20 20:33 UTC, tomneedham commented
> True, in each session login memberships for this users should be added/deleted

Separate PR? But this maybe should be considered a blocked bug for a next release.

2018-02-20 21:05 UTC, butonic commented
I mean when upgrading to a version that includes this pr we should sync all groups .... well we didnt do that with users ... and it was ok ... need to document it very prominently ,,, alse in the release notes ... maybe even add a migration that prints out the admin needs to setup a manual / cron sync of the groups?

2018-02-21 06:48 UTC, tomneedham commented
Well then we need to make sure it syncs on login, because this is what made it acceptable for users to not be synced.

2018-02-26 21:37 UTC, DeepDiver1975 commented
@mrow4a rebased and conflicts resolved ....

2018-02-26 21:40 UTC, mrow4a commented
I think unit tests will crash.. after rebase some things fail now

2018-02-26 21:57 UTC, mrow4a commented
Ok, it might pass, it was my typo while covering SyncService now. Lets see - anyways I will push again since I need to add more coverage

2018-02-26 22:05 UTC, mrow4a commented on lib/public/GroupInterface.php
> +	public function isSyncMaintained();
@butonic @DeepDiver1975 @tomneedham Please note while testing localy, that now one need isSyncMaintaned - LDAP without adjustment will crash https://github.com/owncloud/user_ldap/pull/190

2018-02-26 22:27 UTC, DeepDiver1975 commented on lib/public/GroupInterface.php
> +	public function isSyncMaintained();
looks like the since phpdoc tag has to be adjusted 10.0.0 looks wrong

2018-02-26 23:31 UTC, mrow4a commented
@butonic @DeepDiver1975 @tomneedham Please note while testing localy, that now one need isSyncMaintaned - LDAP without adjustment will crash owncloud/user_ldap#190

2018-02-26 23:31 UTC, mrow4a commented on lib/public/GroupInterface.php
> +	public function isSyncMaintained();
DOne

2018-03-04 14:59 UTC, mrow4a commented
I did performance test of this PR. General feedback:  
- Performance improved for all the operations when database is in sync with external backends, both regarding number of queries and number of events to external services
- Login for central_groups, even with group/user sync has improved performance due to improved LDAP handling-Frequent operations as PROPFIND benefit from less queries and events related to user management.
- Drawback: groups should be synced requrarly (daily) via cronjob in order to be available for search in the system - owncloud no longer searches external user management systems, it looks up the synced entries in the database only. 
- Membership does not need to be synced due to the fact these are handled on login - for improved login performance regalar (daily) sync of memberships via cronjob is advised.

For more details, please go to https://cloud.owncloud.com/index.php/s/eUajBR59vQNUEq1#pdfviewer

@DeepDiver1975 @tomneedham @butonic @felixboehm @cdamken

2018-03-04 16:44 UTC, patrickjahns commented
@mrow4a 

Interesting scenario to compare would be to have also a vast amount of groups. We've seen setup in the wild, where the group count was also very large. (30k users with 14k groups)

2018-03-04 16:55 UTC, mrow4a commented
True, we can ask customers to try it out. However my goal was to understand it in the least favourable scenario from central_groups - thus in case where it is causing most overhead.

2018-03-11 22:22 UTC, mrow4a commented
@PVince81 @DeepDiver1975 @butonic @tomneedham I have been on the customgroups and guest, and I can see that they will need sync on login also.. thus I remove the requirement of the flag isSyncMaintained. LDAP will work out of the box with this PR since all the things will be synced on user login. Custom Groups also works, but will require small adjustment to work better

2018-05-06 10:09 UTC, mrow4a commented
Updated the checklist for the discussions later if we want to go the direction proposed here.

2018-07-24 12:43 UTC, PVince81 commented
lots of conflicts, PR needs reviving

2018-08-07 06:07 UTC, mrow4a commented
@PVince81 I will resolve the conflicts and summarize advantages of this solution and disadvantages - last time I posted a report was in March (https://cloud.owncloud.com/index.php/s/eUajBR59vQNUEq1#pdfviewer), and there was no review. But by then central accounts were also fresh

2019-07-30 06:01 UTC, DeepDiver1975 commented
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

2019-07-30 06:01 UTC, closed without merging