[WIP] Move excluded files/folders to config array
owncloud/core pull request #29126
Opened 2017-09-29 14:59 UTC by sharidas

Moving excluded files/folders to config array.
Instead of populating in the ExcludeFile* or
ExcludeFolders* php files, we can have it in
config.php.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change would help users to mention folders/files to be excluded during integrity check to the config.php. In the config.php it will be represented as an array.

## Related Issue

https://github.com/owncloud/core/issues/23186
https://github.com/owncloud/enterprise/issues/1874

## Motivation and Context

Instead of hard coding the files/folders in the files, its better to move them to the config.php. Also this change would help the integrity check to exclude files/folders mentioned in the config.php

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-03 11:06 UTC, tomneedham commented
should also include a sample entry in config.sample.php

2017-10-03 11:06 UTC, tomneedham commented on lib/private/IntegrityCheck/Checker.php
> +		$excludeFiles = \OC::$server->getSystemConfig()->getValue('excludedFiles', '');
default should be an array since we use it in `in_array` later

2017-10-05 19:43 UTC, DeepDiver1975 requested changes

2017-10-05 19:43 UTC, DeepDiver1975 commented on config/config.sample.php
> +		1 => '/home/sujith/test/owncloud/themes',
better use OC::$SERVERROOT

example
```php
OC::$SERVERROOT . '/assets'

2017-10-05 19:43 UTC, DeepDiver1975 commented on config/config.sample.php
> +		1 => '/home/sujith/test/owncloud/themes',
and we shall find good example folders - maybe two are enough.
/apps/my-theme might be a good example and /assets

2017-10-05 19:43 UTC, DeepDiver1975 commented on config/config.sample.php
> +'excludedFilenamePatterns' =>
isn't the pattern enough to also properly exclude folders and files from above?

2017-10-05 19:43 UTC, DeepDiver1975 commented on lib/private/IntegrityCheck/Checker.php
> +		$excludeFiles = \OC::$server->getSystemConfig()->getValue('excludedFiles', []);
inject config instance - no use of \OC::$server inside any class please

2017-10-05 19:43 UTC, DeepDiver1975 commented on lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php
> +		return \OC::$server->getConfig()->getSystemValue('excludedFiles', '');
keep proper defaults - basically just like before

2017-10-05 19:43 UTC, DeepDiver1975 commented on lib/private/Setup.php
> +			'excludedFolders'   => $excludeFolders,
I would no set them during setup. the defaults will be in our code base and people can extend/change the list if they like.

2017-10-05 19:43 UTC, DeepDiver1975 commented on tests/lib/IntegrityCheck/CheckerTest.php
> -	public function testWriteCoreSignatureWithUnmodifiedHtaccess() {
where did these tests go?

2017-10-10 13:41 UTC, PVince81 commented
I heard from @Peter-Prochaska that it might not be a good idea to allow excluding whole folders, so not sure... See https://github.com/owncloud/core/issues/29094#issuecomment-335396910

2017-10-18 15:15 UTC, PVince81 commented
- [ ] Please only allow excluding files, not folders, as discussed with @Peter-Prochaska

2017-10-23 13:52 UTC, mmattel commented
Maybe only a small detail to avoid naming confusion:
``excludedFolders`` --> ``integrityExcludedFolders`` also valid for the others.

Reason: https://doc.owncloud.org/server/latest/admin_manual/configuration/server/excluded_blacklisted_files.html

2017-11-03 15:08 UTC, sharidas commented
Updated this PR to exclude files only and not folders.

2017-11-05 16:40 UTC, mmattel commented on config/config.sample.php
> +	array (
Description text: Exclude directories --> Exclude files

2017-11-05 16:47 UTC, mmattel commented on config/config.sample.php
> +	array (
Also see my comment above to avoid confusion:
This variable should be renamed from ``excludedFiles`` to ``integrityExcludedFiles``

2017-11-06 07:08 UTC, sharidas commented
Not sure how to make codecov happy for config.sample.php. Any pointers would be helpful. Thanks.

2017-11-06 09:37 UTC, PVince81 commented on config/config.sample.php
> +		0 => '.DS_Store',
no need for the numeric index

2017-11-06 09:46 UTC, sharidas commented on config/config.sample.php
> +		0 => '.DS_Store',
Updated the config.sample.php by removing numeric index.

2017-11-06 11:13 UTC, sharidas commented
Backport PR to stable10 branch: https://github.com/owncloud/core/pull/29460

2017-11-06 13:37 UTC, PVince81 commented on config/config.sample.php
> +'integrityExcludedFiles' =>
why camel case ? all of the other config entries are either dot separated, underscore separated or have no separator for all-lowercase. The latest trend is to use dots as separators.

2017-11-06 13:37 UTC, PVince81 commented on config/config.sample.php
> +'excludedFilenamePatterns' =>
not sure... maybe some files could have prefixes/suffixes ? I'd also prefer the simpler solution.

@sharidas Did anyone report such cases in the original ticket ?

2017-11-06 13:39 UTC, PVince81 commented
@Peter-Prochaska second review ?

2017-11-06 13:55 UTC, sharidas commented on config/config.sample.php
> +'excludedFilenamePatterns' =>
@PVince81 No I didn't find any cases related to exclude filename patterns in the original ticket. I think we can stick on with exclude file names and remove exclude filename patterns from the PR.

2017-11-06 14:05 UTC, sharidas commented on config/config.sample.php
> +'integrityExcludedFiles' =>
Updated to `integrity.excluded.files`

2017-11-07 09:54 UTC, peterprochaska requested changes

2017-11-07 09:54 UTC, Peter-Prochaska commented on lib/private/IntegrityCheck/Checker.php
> +	 * @return mixed
Why mixed? it's an array

2017-11-07 10:22 UTC, sharidas commented on lib/private/IntegrityCheck/Checker.php
> +	 * @return mixed
@Peter-Prochaska  Updated the PR.

2017-11-08 07:42 UTC, peterprochaska approved these changes

2017-11-08 08:42 UTC, merged

2017-11-14 18:38 UTC, mmattel commented on config/config.sample.php
> +'integrity.excluded.files' =>
@PVince81 we still have the description text mismatch stating that we exclude directories while we exclude files ...
This inconsistancy needs to be fixed and backported

2017-11-15 08:50 UTC, mmattel commented on config/config.sample.php
> +'integrity.excluded.files' =>
@PVince81 just seen that is has been fixed ...