[WIP] Admins can change display name when flag set to false
owncloud/core pull request #29132
Opened 2017-10-02 12:47 UTC by sharidas

When 'allow_user_to_change_display_name' => false, is
set in the config.php then admin user should be
able to set the display name.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When 'allow_user_to_change_display_name' => false, is set in the config.php, then the admin user should be able to set the display name of users.

## Related Issue

https://github.com/owncloud/core/issues/27442

## Motivation and Context

When 'allow_user_to_change_display_name' => false, is set in the config.php, the admin user wasn't able to set the display name. This change will help to allow the admin to set the display name for users.

## How Has This Been Tested?

- [x] create 3 users admin, user1, user2
- [x] Add 'allow_user_to_change_display_name' => false, to the config.php
- [x] Login as admin user and try to rename the admin to "Foo". It worked.
- [x] Create a new group `test` and add `user1` and `user2` to the group `test`.
- [x] Make `user1` as the group admin for `test1`.
- [x] Now try to login as `user` then try to change the display name for `user1`, it doesn't work.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-03 07:10 UTC, sharidas commented
Made modification so that admin and group admins can change the display name. It would be nice to know if we want to have only 
1) admins and group admins to change the display name of users
2) or **only** admins allowed to change display name

2017-10-05 19:33 UTC, DeepDiver1975 commented
Any chance to get this unit tested? THX

2017-10-10 13:38 UTC, PVince81 commented
@sharidas I think any kind of admin should be able to change the display name. Non-admins aka users should not.

2017-10-10 13:42 UTC, sharidas commented
So if I understand correctly 
> admins and group admins to change the display name of users
Admins and group admins are allowed to change the display name if `allow_user_to_change_display_name' => false,` is added to config.php

2017-10-10 14:30 UTC, PVince81 commented
@sharidas correct

2017-10-10 14:30 UTC, PVince81 commented
@pmaier1 FYI ^

2017-10-10 15:20 UTC, sharidas commented
Now an admin and group admin can change the users display name

2017-10-10 15:24 UTC, PVince81 commented
@sharidas please adjust unit tests. If there are none, please add some. Thanks

2017-10-10 15:40 UTC, sharidas commented
> please adjust unit tests. If there are none, please add some. Thanks

Thats next task.

2017-11-03 07:05 UTC, sharidas commented on lib/private/User/User.php
> +								Manager $groupManager = null, Session $userSession = null
Injecting GroupManager and UserSession here. Didn't liked the previous version of the patch. So used this approach. Let me know if it looks ok.

2017-11-03 14:48 UTC, sharidas commented on lib/private/User/User.php
> +								Manager $groupManager = null, Session $userSession = null
Have also added unit test for the same.

2017-11-03 14:54 UTC, PVince81 approved these changes
:+1:

2017-11-03 15:00 UTC, sharidas commented
Will create backport.

2017-11-03 15:05 UTC, sharidas commented
Backport to stable10: https://github.com/owncloud/core/pull/29442

2017-11-03 15:24 UTC, DeepDiver1975 commented
```
16:07:28 [owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q] Running shell script
16:07:28 + export NOCOVERAGE=1
16:07:28 + NOCOVERAGE=1
16:07:28 + unset USEDOCKER
16:07:28 + phpenv local 5.6
16:07:28 + make test-php TEST_DATABASE=pgsql
16:07:28 PHPUNIT="/var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/phpunit/phpunit/phpunit" build/autotest.sh pgsql 
16:07:28 Using PHP executable /opt/phpenv/shims/php
16:07:28 Parsing all files in lib/public for the presence of @since or @deprecated on each method...
16:07:28 
16:07:30 Using database oc_autotest5
16:07:30 Setup environment for pgsql testing on local storage ...
16:07:34 Installing ....
16:07:52 PHP Fatal error:  Cannot use OC\Group\Manager as Manager because the name is already in use in /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/User/User.php on line 41
16:07:52 PHP Stack trace:
16:07:52 PHP   1. {main}() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/occ:0
16:07:52 PHP   2. require_once() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/occ:11
16:07:52 PHP   3. OC\Console\Application->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/console.php:106
16:07:52 PHP   4. Symfony\Component\Console\Application->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/Console/Application.php:162
16:07:52 PHP   5. Symfony\Component\Console\Application->doRun() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/symfony/console/Application.php:130
16:07:52 PHP   6. Symfony\Component\Console\Application->doRunCommand() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/symfony/console/Application.php:228
16:07:52 PHP   7. Symfony\Component\Console\Command\Command->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/symfony/console/Application.php:874
16:07:52 PHP   8. OC\Core\Command\Maintenance\Install->execute() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/symfony/console/Command/Command.php:264
16:07:52 PHP   9. OC\Setup->install() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/core/Command/Maintenance/Install.php:86
16:07:52 PHP  10. OC\User\Manager->createUser() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/Setup.php:347
16:07:52 PHP  11. OC\User\Manager->getUserObject() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/User/Manager.php:336
16:07:52 PHP  12. spl_autoload_call() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/User/Manager.php:180
16:07:52 PHP  13. Composer\Autoload\ClassLoader->loadClass() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/private/User/Manager.php:180
16:07:52 PHP  14. Composer\Autoload\includeFile() /var/lib/jenkins/workspace/owncloud-core_core_PR-29132-2PBBEYQ3IXYKPHPI4JLRKSIPJOYVTQEFY26WO6EJ72XKCBDAG24Q/lib/composer/composer/ClassLoader.php:322

2017-11-03 15:25 UTC, DeepDiver1975 requested changes
https://github.com/owncloud/core/pull/29132#issuecomment-341735562

2017-11-05 09:39 UTC, sharidas commented
All checks passed.

2017-11-06 09:33 UTC, merged