Remove alternate keys storage during user delete
owncloud/core pull request #29144
Opened 2017-10-04 10:56 UTC by sharidas

When user is deleted the alternate key storage location
does have folder with username. So while deleting user
this should also be cleaned up.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Remove alternate key storage location during user delete process.

## Related Issue

https://github.com/owncloud/core/issues/26936

## Motivation and Context

When user is deleted, the alternate key storage location which has folder name with username should
also be deleted.

## How Has This Been Tested?

- [x] enable encryption with user keys
- [x] Using change-key-storage-root command move the keys to folder `enckeys`
- [x] Create another user `user1` apart from user `admin`
- [x] Login as `user1`
- [x] Logout from `user1` and login as `admin`
- [x] Delete the `user1`, there shouldn't be any traces of `user1` inside the folder `enckeys`

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-04 11:18 UTC, DeepDiver1975 requested changes

2017-10-04 11:18 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +		if ($this->config->getAppValue('core', 'encryption_enabled', 'no') === 'yes') {
Can't we do this in a event? This belongs to encryption - this should not live in the user class

2017-10-04 13:01 UTC, sharidas commented
Updated the PR with the help of event dispatcher. And hence there is another bit to be reviewed which is associated with this PR: https://github.com/owncloud/encryption/pull/16

2017-10-04 14:56 UTC, DeepDiver1975 requested changes

2017-10-04 14:56 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +		$this->eventDispatcher->dispatch('OC\Encryption\Keys\Storage::deleteAltUserStorageKeys', $event);
no - this way we have a specific event in here. Please use a generic event name which allows any code to integrate in here.

2017-10-05 04:36 UTC, karakayasemi commented on lib/private/User/User.php
> +		$this->eventDispatcher->dispatch('OC\Encryption\Keys\Storage::deleteAltUserStorageKeys', $event);
Why do not we use just preDelete hooks in here? If we are planning to remove hooks, imho we should use more generic event like oc.user.postdelete. 
Also, symfony has some naming conventions on the EventDispatcher, It may be beneficial for us to adhere to these rules:
-Use only lowercase letters, numbers, dots (.) and underscores (_);
-Prefix names with a namespace followed by a dot (e.g. order., user.*);
-End names with a verb that indicates what action has been taken (e.g. order.placed).
https://symfony.com/doc/current/components/event_dispatcher.html#naming-conventions

2017-10-05 07:00 UTC, sharidas commented
Got another idea, why not call https://github.com/owncloud/encryption/pull/16/files#diff-ef2f85587bb2300b22909edff73c7440L198. We already have post delete user hook in the encryption app. Let me know if this looks ok?

2017-10-05 19:30 UTC, DeepDiver1975 commented
> Got another idea, why not call https://github.com/owncloud/encryption/pull/16/files#diff-ef2f85587bb2300b22909edff73c7440L198. We already have post delete user hook in the encryption app. Let me know if this looks ok?

nice - thats the way to go - we can close this pr then - right?

2017-10-06 05:55 UTC, sharidas commented
Yes we can merge this change.

2017-10-06 06:36 UTC, DeepDiver1975 approved these changes

2017-10-06 06:36 UTC, merged

2017-10-06 07:07 UTC, sharidas commented
Created backport : https://github.com/owncloud/core/pull/29155