[Central group table] Add membership manager to central group table
owncloud/core pull request #29154
Opened 2017-10-05 20:38 UTC by mrow4a

This is first approach to handle central group table feature. It utilizes new class Membership manager, which inherits from Access class. More implementation details will go inside the code. 

@patrickjahns

2017-10-05 20:40 UTC, mrow4a commented
I will also start writing unit tests to test queries I am using, so dont focus on them to much at that point. 

If we decide on that approach, lets merge it with https://github.com/owncloud/core/pull/29107. This should not affect any other class and existing functionalities. It will when all TODOs will be implemented.

2017-10-05 20:41 UTC, mrow4a commented on lib/private/Group/Group.php
> +	 * // TODO: use BackendGroup here
All the TODOs in the code are places which should be implemented after merging this PR

2017-10-05 20:56 UTC, mrow4a commented on lib/private/Group/GroupMapper.php
> +			$backendGroup = $this->findEntity($qb->getSQL(), $qb->getParameters());
Add some additional checks which are not in original version. It should return null and not throw exception

2017-10-05 20:56 UTC, mrow4a commented on lib/private/Group/Manager.php
> +	public function isCached($gid) {
This method is required to build optimized queries

2017-10-05 20:57 UTC, mrow4a commented on lib/private/Server.php
> +			return new MembershipManager($c->getDatabaseConnection(), $c->getConfig(),
All changes in this file are obligatory so it actually all works.

2017-10-05 21:00 UTC, mrow4a commented on lib/public/AppFramework/Db/Mapper.php
> +	public function mapRowToEntity($row) {
Make it public so MembershipManager can also create the Account entities (otherwise it will only be possible inside AccountMapper)

Added @throws in phpdoc to make it clear that this function should only be used by classes which operate over oc_accounts table.

2017-10-05 21:01 UTC, mrow4a commented on lib/private/MembershipManager.php
> +class MembershipManager extends Access {
Please have a look on all the public interfaces of that class.

2017-10-05 21:04 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		if ($this->userManager->isCached($userId) && $this->groupManager->isCached($gid)) {
I use isCached mathods of Managers to build optimized queries - it means, fetch info from cache if available, otherwise perform JOIN.

2017-10-09 13:05 UTC, mrow4a commented
@jvillafanez

2017-10-10 09:17 UTC, jvillafanez commented on lib/private/MembershipManager.php
> +		if ($this->userManager->isCached($userId) && $this->groupManager->isCached($gid)) {
From my point of view, this reveals a design flaw. Why something related to the DB access has to check a class from the business logic? Why it needs to check if it's cached when noone should be interested in that?.

I think we should recheck the approach. What about the group manager handles also the membership? Could it simplify this?

2017-10-10 09:18 UTC, jvillafanez commented
I'll need to do a second review

2017-10-10 13:30 UTC, mrow4a commented on lib/private/Group/Manager.php
> +	public function isCached($gid) {
True, will write a UserCacheManager and GroupCacheManager Włoch will be used Both in Group/User Manager and Mapper

2017-10-26 21:29 UTC, mrow4a commented
Change is ready to review, full unit test coverage (target branch https://github.com/owncloud/core/pull/29107). @DeepDiver1975 @jvillafanez @butonic @PVince81

2017-10-26 21:31 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		return intval($data['count']);
Is any case this might throw an exception in this query?

2017-10-26 21:32 UTC, mrow4a commented on lib/private/MembershipManager.php
> +			\OC::$server->getLogger()->logException($e, ['app' => 'core']);
@DeepDiver1975 is this correct way of logging this exception?

2017-10-27 10:37 UTC, jvillafanez commented on lib/private/MembershipManager.php
> +			\OC::$server->getLogger()->logException($e, ['app' => 'core']);
We should check a couple of things:
* Does this class need to log something? Taking into account this is the only log here, probably not.
* Does this class need to handle that exception? I have my doubts about it.

The other option would be to not catch the exception and let it bubble up in order to handle it in other place. Note that exposing a DB exception and handle it near the output response might not be good.

I'm not saying this is bad, but there might be better options. My point is that having to log something without injecting a logger is something to be avoided, as well as injecting a class (the logger) that doesn't seem to be a clear dependency (because it's only used here). Note that swallowing the exception without doing anything is a worse option.

2017-10-27 10:37 UTC, jvillafanez commented on lib/private/MembershipManager.php
> +		$allowMedialSearches = $this->config->getSystemValue('accounts.enable_medial_search', true);
Is it worthy to extract this logic (getting the flag + setting the parameter variables) to another function? Taking into account this isn't used in other place than here, probably not unless the complexity of this function is high (I don't have data, but it doesn't seem so).

2017-10-27 10:37 UTC, jvillafanez commented on lib/private/MembershipManager.php
> +		$qb->execute();
What if the query fails? I expect the `execute()` function either return something or throws an exception. It doesn't seem this case is taken into account.

2017-10-27 10:44 UTC, mrow4a commented on lib/private/Group/GroupMapper.php
> +		return $backendGroup;
Hmm, my point here was to make in transparent that the returned object is BackendGroup, not pure Entity. The same holds for Account. But yes, I could use this in the function which calls mapRowToEntity

2017-10-27 10:45 UTC, jvillafanez commented
I haven't checked the DB queries yet. @mrow4a as unofficial DB expert I trust the queries work properly 😉  I can have a look if needed.

Btw, I don't have data about the test coverage of the MembershipManager, but it seems quite important to verify the coverage is near 100% in that class because we'll likely rely on it heavily and the DB queries aren't easy enough to ensure they'll work on all the cases in a glance.

2017-10-27 10:46 UTC, mrow4a commented on lib/private/MembershipManager.php
> +			\OC::$server->getLogger()->logException($e, ['app' => 'core']);
Hmm, makes sense. In fact, we dont handle also foreign constrain violations, so maybe this one we should not either.

2017-10-27 10:50 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		$qb->execute();
Hmm, true. Thanks!

2017-10-27 10:53 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		$allowMedialSearches = $this->config->getSystemValue('accounts.enable_medial_search', true);
Hmm, I have better idea what to do with it. Good point here.

2017-10-27 12:04 UTC, jvillafanez commented on lib/private/Group/GroupMapper.php
> +		return $backendGroup;
PHPDoc should take care of that, in this case in the parent class since it's the one that will be executed. Note that function visibility shouldn't need to be changed (from protected to public)

2017-10-27 12:41 UTC, mrow4a commented on tests/lib/MembershipManagerTest.php
> +class MembershipManagerTest extends TestCase {
I covered 100% of the MembershipManager code here @jvillafanez, ale checked corner-cases, but it would be good to have a look if I did not overlook something.

2017-10-29 18:33 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		$qb->selectAlias($qb->createFunction('COUNT(DISTINCT a.`id`)'), 'count');
@butonic I needed a.`id` to make it work on Oracle, should I put it also in another DISTINCT?

2017-10-29 18:34 UTC, mrow4a commented
100% unit tests coverage and tests passing on all dbms. PR ready for review and merging

2017-10-29 22:10 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		// Limit to 1, to prevent fetching unnecesary rows
Spelling - unnecessary

2017-10-30 07:37 UTC, jvillafanez commented
Changes look good to me. 👍

2017-10-30 12:22 UTC, mrow4a commented on lib/private/MembershipManager.php
> +		$qb->selectAlias('DISTINCT a.id', 'id')
Should I use DISTINCT a.`id` for Oracle @butonic?

2017-10-30 12:36 UTC, DeepDiver1975 requested changes

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	/** @var \OC\Group\GroupMapper */
import all classes in the use statement above

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	private function getTableAlias() {
needed? just use 'm'

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	private function getTableName() {
needed= just use 'memberships'

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	 * @param string $gid
string? not int?

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +		$qb->select(['a.id','a.user_id', 'a.lower_user_id', 'a.display_name', 'a.email', 'a.last_login', 'a.backend', 'a.state', 'a.quota', 'a.home'])
missing white space

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	private function getAffectedQuery($qb) {
IQueryBuilder $qb

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	private function getExistsQuery($qb) {
IQueryBuilder $qb

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +		if ($isInternalId) {
I'd split this into 2 functions - you gain nothing from this

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +		if ($isInternalId) {
split into two function

2017-10-30 12:36 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> -			->leftJoin('a', 'account_terms', 't', $qb->expr()->eq('a.id', 't.account_id'))
keep this for readability - we will never change the table names

2017-10-30 12:36 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +		MembershipManagerTest::clearDB();
self:: instead of MembershipManagerTest::

2017-10-30 12:36 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +		if ($this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\SqlitePlatform) {
import sqliteplatform

2017-10-30 12:36 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +		$account = MembershipManagerTest::getAccount(1);
self::

2017-10-30 12:36 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +			$this->assertInstanceOf(\Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException::class, $e);
import

2017-10-30 12:37 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> -			->leftJoin('a', 'account_terms', 't', $qb->expr()->eq('a.id', 't.account_id'))
I exactly changed that for readability also, so we don't use magic strings which are easy to mistake or confuse

2017-10-30 12:38 UTC, mrow4a commented on lib/private/MembershipManager.php
> +	private function getExistsQuery($qb) {
Not sure what you mean here

2017-10-30 12:39 UTC, mrow4a commented on lib/private/MembershipManager.php
> +	private function getTableName() {
I would prefer to keep it, because we might use this table also in other parts of the code later - e.g. fs setup optimization.

2017-10-30 12:40 UTC, mrow4a commented on lib/private/MembershipManager.php
> +	private function getTableName() {
I mean, your point is that table names won't change right?

2017-10-30 16:52 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	private function getTableName() {
tablenames dont change - yes and a a one line function like this is pointless

2017-11-01 07:25 UTC, tomneedham commented on lib/private/MembershipManager.php
> +	private function getExistsQuery($qb) {
Type hint the parameter

2017-11-01 08:38 UTC, butonic commented on lib/private/MembershipManager.php
> +		$qb->selectAlias($qb->createFunction('COUNT(DISTINCT a.`id`)'), 'count');
When using `$qb->createFunction(` you basically pass raw SQL. That is why you need to do the column escaping. With `$qb->expr()->eq(` that is not necessary, because it will do the column quoting (`a.id` becomes <code>a.&#96;id&#96;</code>) for you.

Where exactly would you put another DISTINCT?

2017-11-01 08:53 UTC, butonic commented on lib/private/MembershipManager.php
> +		$qb->selectAlias('DISTINCT a.id', 'id')
Distinc with alias is a littlve ugly. Whil doctrine has `selectAlias` and `selectDistinct` neither does what you need. `selectAlias` will treat `DISTINCT a.id` as a single identifier, escaping it to <code>DISTINCT a.`id`<code>. While that looks correct it is only by chance. Either you have test coverage for this, so we detect when docrine decides to treat this differently, or you wrap the rew sql in a function to make the problem explicit:
```php
$qb->selectAlias($qb->createFunction('DISTINCT a.`id`'), 'id');
```
Then again, this also only works as long as doctrine does not parse the funtion string for actual brackets...


So ... I would leave it as it is, but cover it with a unit test that checks the DISTINCT is working.

2017-11-06 09:47 UTC, mrow4a commented
@DeepDiver1975 can we merge it into central_groups branch? I addressed all the issues you pointed

2017-11-07 20:44 UTC, mrow4a commented
@DeepDiver1975 @PVince81 I have tested it with https://github.com/owncloud/core/pull/29282 integration into group manager, group, subadmin, user and user manager. This PR is ready

2017-11-14 08:07 UTC, mrow4a commented
Any input here?

2017-11-14 17:44 UTC, jvillafanez commented on lib/private/MembershipManager.php
> +	protected $config;
If this class isn't expected to be extended, this should be private.

2017-11-24 07:52 UTC, DeepDiver1975 commented
@ownclouders rebase

2017-11-24 07:52 UTC, ownclouders commented
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

2017-11-24 07:53 UTC, DeepDiver1975 requested changes

2017-11-24 07:53 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	public function __construct(IDBConnection $db, IConfig $config) {
PHPDoc missing

2017-11-24 07:53 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	 * @param bool $isInternalUserId
what is internal?

2017-11-24 07:53 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	 * Return backend group entities for given user id $userId (internal or gid) of which
gid?

2017-11-24 07:53 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	public function getUserBackendGroups($userId) {
do we really need this function? From my understanding everything should internally work on accountIds

2017-11-24 07:53 UTC, DeepDiver1975 commented on lib/private/Server.php
> +	public function getAccountTermMapper() {
why? public getters in class Server shall only return OCP interfaces

2017-11-24 07:53 UTC, ownclouders commented
Automated rebase was successful!

2017-11-27 13:23 UTC, mrow4a commented on lib/private/Server.php
> +	public function getAccountTermMapper() {
Hmm, so what with AccountMapper?

2017-11-28 13:04 UTC, mrow4a commented on lib/private/MembershipManager.php
> +	public function getUserBackendGroups($userId) {
It is just optimization, in case account id is only available by fetching the use from user manager.

2017-11-28 13:04 UTC, mrow4a commented
@DeepDiver1975 addressed your doubts and fixed

2017-11-30 09:22 UTC, DeepDiver1975 requested changes

2017-11-30 09:22 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +use Test\TestCase;
unused

2017-11-30 09:22 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +use OCP\AppFramework\Db\DoesNotExistException;
unused

2017-11-30 09:22 UTC, DeepDiver1975 commented on tests/lib/MembershipManagerTest.php
> +		\OC::$server->getDatabaseConnection()->executeQuery('DELETE FROM `*PREFIX*accounts`');
really kill all?

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/Server.php
> +use OC\MembershipManager;
unused

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/Server.php
> +				new EnvironmentHelper(),
remove whitspace changes

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +}
remove whitespace changes

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	public function addGroupUser($accountId, $backendGroupId) {
addGroupMemberSqlQuery throws UniqueConstraintViolationException - see PHPDoc
this method should do also throw it

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	public function addGroupAdmin($accountId, $backendGroupId) {
same as with addGroupUser

2017-11-30 09:22 UTC, DeepDiver1975 commented on lib/private/MembershipManager.php
> +	 * @param bool $isInternalGroupId
isInternalGroupId unknown 
isBackendGroupId missing in PHPDoc

2017-11-30 14:40 UTC, mrow4a commented
@DeepDiver1975 adjusted to comments

2017-12-01 11:39 UTC, DeepDiver1975 approved these changes

2017-12-01 11:39 UTC, merged