[WIP] Revert hard coded Name string in templates
owncloud/core pull request #29161
Opened 2017-10-06 09:49 UTC by felixheidecke

## Description
Revert back hard-coded name string in core template files

## Related Issue

https://github.com/owncloud/enterprise/issues/2271

## How Has This Been Tested?

Visual test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-06 09:50 UTC, felixheidecke commented on apps/files_sharing/templates/public.php
> +				<?php $theme->getName(); ?>
This, unfortunately, overrides CE & EE theme. Shouldn't happen but does :-1:

2017-10-06 09:52 UTC, felixheidecke commented on lib/private/legacy/defaults.php
> +		$this->defaultName = '<span class="own">own</span><span class="cloud">Cloud</span>'; /* short name, used when referring to the software */
To provide the look needed in the EE Theme, we a bit more HTML in the defaultName. (Related to https://github.com/owncloud/core/pull/29161/files#r143151177)

This should not be escaped but render out valid HTML. @patrickjahns or @DeepDiver1975

2017-10-06 14:55 UTC, michaelstingl requested changes
Please check my comment in https://github.com/owncloud/enterprise/issues/2271#issuecomment-334782490

2017-10-06 15:05 UTC, patrickjahns commented on lib/private/legacy/defaults.php
> +		$this->defaultName = '<span class="own">own</span><span class="cloud">Cloud</span>'; /* short name, used when referring to the software */
👎 I am not comfortable adding HTML tags to a string only field

2017-10-09 09:05 UTC, PVince81 commented
Fixes https://github.com/owncloud/core/issues/29172

2017-10-10 10:05 UTC, felixheidecke commented
I removed the hard-coded ownCloud occurrences in core.
This will alter the look in the files_sharing app in conjunction with the enterprise theme, but I guess we can live with that ;-)

@patrickjahns

2017-10-10 10:49 UTC, DeepDiver1975 commented
please squash ...

2017-10-11 14:50 UTC, felixheidecke commented
Please review @DeepDiver1975 & @patrickjahns … No longer in progress.

2017-10-11 15:17 UTC, patrickjahns approved these changes
LGTM

@michaelstingl has the final say in this matter

2017-10-11 15:59 UTC, michaelstingl approved these changes
LGTM, but I only tested the ownBrander generated theme and I didn't test if this breaks other stuff… (vanilla oC, example theme etc)

2017-10-12 08:42 UTC, merged

2017-10-12 08:47 UTC, PVince81 commented
@felixheidecke please backport to stable10