[stable8.2] Add command to pre-migrate oc_properties
owncloud/core pull request #29162
Opened 2017-10-06 09:49 UTC by tomneedham

2017-10-06 10:10 UTC, DeepDiver1975 requested changes

2017-10-06 10:10 UTC, DeepDiver1975 commented on core/command/migrate/davproperties.php
> +			$sql = "CREATE INDEX fileid_index ON *PREFIX*properties (fileid)";
Quotes? And this looks like this will not work on all dbs. Shall we at least add some platform limitation?

2017-10-09 12:31 UTC, tomneedham commented
Updated the SQL to hopefully make it valid for the platforms we support.

2017-10-16 08:46 UTC, tomneedham commented
Closing for now unless this becomes necessary

2017-10-16 08:46 UTC, closed without merging