username must be at least 3 characters long
owncloud/core pull request #29198
Opened 2017-10-10 12:15 UTC by Peter-Prochaska

## Description
Username must be at least 3 characters long

## Related Issue
HackerOne and https://github.com/owncloud/security-tracker/issues/227

## Motivation and Context

## How Has This Been Tested?
You can't add a user with 'a' or 'ab'

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-10 12:19 UTC, DeepDiver1975 approved these changes

2017-10-10 12:21 UTC, DeepDiver1975 commented
@Peter-Prochaska did you test this? jenkins is red - please have a look

2017-10-10 12:33 UTC, phil-davis commented
This will "fix" the user named "0" issue, by banning any 1 (or 2) char string as a username: #28406

2017-10-10 12:34 UTC, phil-davis commented
I guess this only applies to "local" ownCloud-created usernames. Short ones could still come from LDAP?

2017-10-10 12:36 UTC, PVince81 commented
> Short ones could still come from LDAP?

Yes

2017-10-10 12:57 UTC, Peter-Prochaska commented
Yes, localy the tests are running. I think this is a jenkis error

2017-10-10 13:24 UTC, PVince81 commented on .htaccess
> -
unrelated?

2017-10-10 13:34 UTC, Peter-Prochaska commented on .htaccess
> -
fixed

2017-10-10 14:24 UTC, mmattel commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
This ends up in min 4

2017-10-10 14:28 UTC, mmattel commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
Additionally I would place it after the whitespace check...

2017-10-10 14:31 UTC, PVince81 requested changes
see @mmattel's comments

2017-10-10 15:24 UTC, kdslkdsaldsal commented on .htaccess
> +</IfModule>
I guess this will break the .htaccess again? AFAIK the newline is expected.

2017-10-10 19:15 UTC, Peter-Prochaska commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
No and no, <=3 ist min 3. And after the whitespace check we have the problem with the "."

2017-10-10 19:16 UTC, Peter-Prochaska commented on .htaccess
> +</IfModule>
What now? Expected or not?

2017-10-11 03:24 UTC, phil-davis commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
The message says ``The username must be at least 3 characters long`` which means it can be 3, 4, 5... characters long. But if I put in a 3-character username "abc" it will not let me do it.
So the "if" test here and the message have different things. One of themm needs to be changed, depending on what is the requirement.

2017-10-11 03:28 UTC, phil-davis commented on .htaccess
> +</IfModule>
In the first place a change to ``.htaccess`` should never have been added to the commit. Sometimes git is seeing that it was modified during a local dev install, and then "just adds it" to the commit (it depends what git tool you are using and what is in the ``.gitignore`` file etc.)

So you need to press "Enter" at the end of the last line, commit and squash. Hopefully ``.htaccess`` will then become identical to the current version in master, and so it will disappear from this PR.

2017-10-11 07:09 UTC, PVince81 commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
just replace `<=` with `<`

2017-10-11 07:09 UTC, PVince81 commented on .htaccess
> +</IfModule>
`git checkout master .htaccess` to revert the changes.

htaccess is not relevant to this PR / commit, so if we want something different there, needs to be fixed separately

2017-10-11 07:35 UTC, phil-davis reviewed
Just little comments.

2017-10-11 07:35 UTC, phil-davis commented on lib/private/User/Manager.php
> +		// Username must at least 3 characters long
Username must be at least...

2017-10-11 07:35 UTC, phil-davis commented on lib/private/User/Manager.php
> +		if(strlen($uid) < 3) {
I like to have space between keywords an the next bracket, like in the next ``if (` below.
It is part of some coding standards - don't know if it is the rule in oC.

2017-10-11 07:40 UTC, mmattel commented on lib/private/User/Manager.php
> +		if(strlen($uid) < 3) {
Is there a reason why you put that quey at the start - just before all other checks like whitespace and valid characters?
Should´nt the result be **minimum three valid characters** ?

2017-10-11 07:46 UTC, DeepDiver1975 commented on lib/private/User/Manager.php
> +		if(strlen($uid) < 3) {
Quite valid question

2017-10-11 07:54 UTC, PVince81 commented on lib/private/User/Manager.php
> +		if(strlen($uid) < 3) {
the answer is likely: need more ☕️ 😉

2017-10-11 07:57 UTC, Peter-Prochaska commented on lib/private/User/Manager.php
> +		if(strlen($uid) <= 3) {
done

2017-10-11 08:04 UTC, PVince81 approved these changes
:+1:

2017-10-13 07:52 UTC, PVince81 commented
restarted jenkins

2017-10-13 10:45 UTC, merged