[WIP] Adding meta data file tree to node api
owncloud/core pull request #29207
Opened 2017-10-11 11:46 UTC by DeepDiver1975

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-12 08:14 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		return "{$this->fileId}";
fancy way of converting to string...

2017-10-12 08:14 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		// TODO: Implement getMimetype() method.
it's a "httpd/unix-directory"

2017-10-12 08:19 UTC, PVince81 reviewed
Looks good so far.

A list of TODO checkboxes would be nice.

I also miss a class `MetaVersionNode` which implements `File` and represents a past version of the file. Its getMTime() method could return the version's timestamp, etc.

2017-10-12 08:19 UTC, PVince81 commented on lib/private/Files/Meta/MetaRootNode.php
> +		throw new NotPermittedException();
I'd suggest implementing a "AbstractNode" or "AbstractFolder" that defaults to "NotPermittedException" for all methods to avoid repeating this in all the meta nodes

2017-10-12 08:19 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +		// TODO: Implement getMimetype() method.
it's a folder: "httpd/unix-directory"

2017-10-12 08:19 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +		// TODO: Implement getMTime() method.
the collection itself has no mtime, so don't bother

2017-10-12 08:20 UTC, PVince81 commented
Open questions:
- need to add MetaVersionNode
- how to do the "move" of a version to the original location ? would this be done on DAV level instead ?

2017-10-12 08:24 UTC, DeepDiver1975 commented
> how to do the "move" of a version to the original location ? would this be done on DAV level instead ?

the dav code will call the node api
```php
$version = \OC::$server->getRootFolder()->get("meta/{$info->getId()}/v/123456");
$version->copy("$userId/files/path/to/file.mov");

2017-10-17 07:39 UTC, PVince81 requested changes
Some small changes required.

And also some potential tricky topics:
- restoring a version to original location with storage specific atomic version restore vs Webdav MOVE
- get versions of trashed files by file id, if that even makes sense. Would still be good to have a way to list/access versions of a trashed file.

2017-10-17 07:39 UTC, PVince81 commented on apps/files_versions/lib/Storage.php
> +						$versions[$key]['storage_location'] = "$dir/$entryName";
is that the original path ? is it an absolute path ? please test with external storages to confirm.

Also add a comment because "storage_location" isn't self-explanatory

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +class MetaFileIdNode extends AbstractFolder {
PHPDoc, what is this class?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +//		yield new MetaPreviewCollection($this->fileId);
leftover? if not, please add a TODO in a comment to clarify that commenting this out is intentional

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		yield new MetaVersionCollection($this->fileId);
Why yield and not return ? AFAIK we haven't used yield before, do we want to start using it ?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		return false;
move these to AbstractFolder or AbstractNode ?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		throw new \InvalidArgumentException();
or NotFoundException ? If this was a Sabre node we'd return "not found" because someone is trying to get a node that doesn't exist, considering that only nodes starting with "v" exist

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		return "/meta/{$this->fileId}";
prepend the parent node path instead of hard-coding "/meta" ?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +class MetaFileVersionNode extends AbstractFile {
phpdoc

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +		//TODO: inject
later?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaRootNode.php
> +class MetaRootNode extends AbstractFolder {
phpdoc

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaRootNode.php
> +		// TODO: check if file exists
what happens when accessing a non-existing file currently ? just to evaluate criticality of this TODO

also important: one should not be able to access non-reachable file even if the file exists, for security reasons

The check should be as easy as doing `if (empty($rootNode->getById($fileId)) { die() }` or use the user home folder instead.

What about files in trash, are we already able to access their versions or should we block that use case for this iteration ?

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +class MetaVersionCollection extends AbstractFolder {
PHPD... you know the drill

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
see, here you used NotFoundException. Please use the same in the other comment above instead of InvalidArgumentException

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
We might need to fallback to the old way of doing versions to keep compatible. For example if the file is on SFTP and the storage doesn't support versions, then the versions would be stored on the local storage like it was in former versions. We should plug in those versions here.

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Node/Root.php
> +		array_shift($pieces);
what's the first piece, is it the user name ?

if yes we might need to read it out and pass it to the MetaRootNode, might be important to check permissions or other stuff

and if yes, it somehow feels like we should add a method `getUserMetaFolder($userId)` on the IRootFolder interface for public use

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Storage/Common.php
> +		if (strpos($internalPath, 'files/') !== 0) {
some external storages might extend `Common`, so any files outside of "files/" wouldn't have versions ?

for this one particular check, I suggest extending the "Home" storage class instead which is guaranteed to have the "files" folder

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Storage/Common.php
> +		if (!\OC_App::isEnabled('files_versions')) {
should we make this a trait for reusability ? probably not as the fallback mechanism should be called from within the Node implementation up there

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Storage/IVersionedStorage.php
> +interface IVersionedStorage {
PHPDoc please.

This interface should be public to allow external storages to implement it as well.
Also requires `@since` tags, etc

2017-10-17 07:39 UTC, PVince81 commented on lib/private/Files/Storage/IVersionedStorage.php
> +	public function restoreVersion($internalPath, $versionId);
If the DAV layer is requiring a "MOVE" to restore a version, there will be a target location. We can't expect the issuer of the MOVE operation to be restricted to the original location. Now from what I see, this `restoreVersion` implementation would only restore to the original location. Also we can't provide an absolute path to restore a version to another storage. In this case I wonder if Webdav MOVE is really the right way.

If we do want MOVE, maybe restoreVersion should really just be a fopen on the version somehow and let the reader store the version wherever they want. Or don't provide "restoreVersion" at all but expect people to use:
1) getContentOfVersion() => stream the contents to the target location where restoration must occur (beware of keeping mtime + metadata perhaps?)
2) deleteVersion() to delete the version from the list as it was restored
However the former might not take into account storages that are able to directly restore a version without doing any stream copy (atomic restore).

So I'm not sure currently... We might need to involve the interface after implementing several storage specific version schemes.

In any case, this here is not compatible with expecting a Webdav MOVE to do a version restoration. We need to discuss the latter.

2017-10-17 07:39 UTC, PVince81 commented on tests/lib/AvatarManagerTest.php
> +//			->willReturn('valid-user');
remove?

2017-10-17 07:42 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		yield new MetaVersionCollection($this->fileId);
yes - we want to use yield

2017-10-17 07:45 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
the fallback implementation is in class Common - in addition if there is no version support -> we simply have no versions.

2017-10-17 07:45 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Common.php
> +		if (!\OC_App::isEnabled('files_versions')) {
this implementation will change in a follow up pr

2017-10-17 07:46 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Common.php
> +		if (strpos($internalPath, 'files/') !== 0) {
file living on external storages also have the logicall path being named /files/ftp/foo/bar.txt - right?

2017-10-17 07:49 UTC, DeepDiver1975 commented on lib/private/Files/Storage/IVersionedStorage.php
> +	public function restoreVersion($internalPath, $versionId);
It is not a MOVE but a COPY. 

> Now from what I see, this restoreVersion implementation would only restore to the original location. Also we can't provide an absolute path to restore a version to another storage. In this case I wonder if Webdav MOVE is really the right way.

In a second step we can extend the implementation to allow a cross storage move/copy. but this is handled in the meta node level.

this function is really specific to restoring a version of a file within the storage.

2017-10-17 08:04 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		return false;
The abstract class throw a NotPermittedException ...

2017-10-17 08:07 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		return "/meta/{$this->fileId}";
It will never live somewhere else ...

2017-10-17 08:18 UTC, DeepDiver1975 commented on lib/private/Files/Node/Root.php
> +		array_shift($pieces);
the first piece is an emtpy string - explode of '/meta/1234' -> ['', 'meta', '1234']

2017-10-17 08:20 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		yield new MetaVersionCollection($this->fileId);
why ? can you explain the bigger picture ?

2017-10-17 08:22 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileIdNode.php
> +		yield new MetaVersionCollection($this->fileId);
I do understand this http://cogitolearning.co.uk/2013/06/php-5-5-the-power-to-yield/ but don't understand how it applies to here. There is no reason for this function to continue running after returning the value since there are no further instructions.

2017-10-17 08:27 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
are you sure we want to break existing behavior at this point in time ? I'd rather have a fallback.

Also note that if we decide that external storages that don't implement IVersionedStorage now have no versions, we'll need a repair step to clean the already existing versions that we stored for these and add an entry to the release notes.

2017-10-17 08:30 UTC, PVince81 commented on lib/private/Files/Storage/Common.php
> +		if (strpos($internalPath, 'files/') !== 0) {
For the absolute path, yes: "$userId/files/ftpmountpoint/foo/bar.txt".

But here this is about he internal path, it's "foo/bar.txt". There is no "files" folder in general on external storages. Only the home storage has a "files" folder where all the files are in. This difference caused many headaches in the past...

2017-10-17 08:32 UTC, PVince81 commented on lib/private/Files/Storage/IVersionedStorage.php
> +	public function restoreVersion($internalPath, $versionId);
Okay

2017-10-17 08:32 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
I see no breakage in behavior - but yes: all external storages need to be retested with respect to this change

2017-10-17 08:32 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Common.php
> +		if (strpos($internalPath, 'files/') !== 0) {
I'll test this - THX

2017-10-17 08:32 UTC, PVince81 commented on lib/private/Files/Storage/IVersionedStorage.php
> +	public function restoreVersion($internalPath, $versionId);
COPY + DELETE actually. The current versions app would delete the version from the list after restoring. we could decide to change the behavior to keep the version in the list though, might be useful.

2017-10-17 08:39 UTC, PVince81 commented on lib/private/Files/Node/Root.php
> +		array_shift($pieces);
I'd suggest ltrim to make sure there is really no slash there.

There are some dark corners of the code where slashes are not guaranteed to be there.

2017-10-17 08:41 UTC, PVince81 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
I think this qualifies as a change of behavior:

1) OC 10.0.3: overwrite file several times on SFTP storage, check versions list: many versions
2) future version: same operations, check versions: list empty

While I understand the motivation of removing support for versions on such storages with no fallback which would simplify our code a lot, I'm worried about user expectation / migration situations.

2017-10-19 17:31 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaVersionCollection.php
> +			throw new NotFoundException();
My goal is clear here: no feature regression! we will have versions for external storages as we did before.

2017-10-25 11:27 UTC, SergioBertolinSG requested changes

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/bootstrap/WebDav.php
> +	public function theContentLengthOfFileWithVersionIndexForUserInVersionsFolderIs($path, $index, $user, $length) {
Can we have a shorter name for this function? Behat's default names for functions are not mandatory, we can choose them.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/bootstrap/WebDav.php
> +
Extra new line here.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    Given using new dav path
This can be included in the background section.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +   Given using new dav path
This can be included in the background section.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    When user "user0" uploads file "data/davtest.txt" to "/davtest.txt"
There has to be only one When step, this has to be another And.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    Then the content length of file "/davtest.txt" with version index "1" for user "user0" in versions folder is "100"
This Then is an And step.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    Given using new dav path
This can be included in the background section.

2017-10-25 11:27 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    When user "user0" uploads file "data/davtest.txt" to "/davtest.txt"
Four When steps and two Thens.

It has to be one When and one Then, rest are Ands continuing from first Given.

The structure of every scenario should be:

Given blabla
And blabla
And blabla
...
And blabla
When blabla
**Then blabla**          <- Only one
And blabla
And blabla
...
And blabla

2017-10-25 13:18 UTC, SergioBertolinSG requested changes

2017-10-25 13:18 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    When user "user0" uploads file "data/davtest.txt" to "/davtest.txt"
I think this step should be a (given) And, and the next Then the When step.

2017-10-25 13:18 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    And user "user0" uploads file "data/davtest.txt" to "/davtest.txt"
This has to be the only When, the previous steps are all Given steps (And).

2017-10-25 13:41 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    And user "user0" uploads file "data/davtest.txt" to "/davtest.txt"
Change this When for And and previous When for And.

2017-10-25 13:43 UTC, SergioBertolinSG requested changes

2017-10-25 13:43 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    When user "user0" deletes file "/davtest.txt"
This When is an And and the next And is the When.

2017-10-25 13:54 UTC, SergioBertolinSG approved these changes
Behat tests are fine 👍

2017-10-30 08:32 UTC, PVince81 commented on tests/integration/features/dav-versions.feature
> +    Then the version folder of file "/davtest.txt" for user "user0" contains "0" elements
Can we also have a test for restoring a version ? Verify that restoration worked by checking that the version's content is now in the current file

2017-10-30 08:36 UTC, DeepDiver1975 commented on tests/integration/features/dav-versions.feature
> +    Then the version folder of file "/davtest.txt" for user "user0" contains "0" elements
@Peter-Prochaska

2017-10-30 08:36 UTC, PVince81 commented
Automated tests to add:
- restore version
- access version folder from a share receiver and see that all works fine there as well

2017-10-30 08:38 UTC, PVince81 commented
- [ ] add automated test with external storage, see https://github.com/owncloud/core/blob/master/tests/integration/features/external-storage.feature#L62 about how to set it up, needs `@local_storage` annotation

2017-10-30 08:53 UTC, PVince81 commented
- [x] TEST: DAV versions listable as share receiver of file
- [x] TEST: DAV versions listable as share receiver of parent folder
- [ ] BUG: DAV versions not listable as share receiver from external storage

Steps:

1. Enable encryption (likely optional)
1. Login as admin
1. Setup system-wide ext storage "/sftp", apply to only admin user and enable sharing
1. Create folder "/sftp/sha"
1. Create file "/sftp/sha/test.txt" with several versions
1. Share "/sftp/sha" with "user1"
1. Use DOM inspector to find the file id of "test.txt" (data-id)
1. with DAV client, connect to "remote.php/dav/meta/$fileId/v/" as user1

Expected: versions listable
Actual: not listable as user1, only listable as admin

2017-10-30 08:54 UTC, PVince81 commented
- [ ] I'd like a test for the above too, please (no encryption needed, encryption will be tested automatically after merging)

2017-10-30 08:56 UTC, PVince81 commented
- [ ] BUG: 500 error when PROPFIND on "/meta" folder. No logs: `curl -D - -u admin:admin -X PROPFIND http://localhost/owncloud/remote.php/meta/

2017-10-30 09:00 UTC, PVince81 commented
- [ ] add automated test that check doing a PROPFIND on a version fileid that is **not accessible** from the current user => must return 404.

@Peter-Prochaska some negative tests would be nice too, for security ^

2017-10-30 09:02 UTC, PVince81 commented
- [ ] BUG: need to properly block MOVE operations:

```
dav:/owncloud/remote.php/dav/meta/64/v/> mv 1509353014 ../../../files/admin/
Moving `/owncloud/remote.php/dav/meta/64/v/1509353014' to `/owncloud/remote.php/dav/files/admin/1509353014':  failed:
500 Internal Server Error
```

```
{"reqId":"UT6n3Cs23GcHKRLfY7Qc","level":4,"time":"2017-10-30T09:02:00+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/meta\/64\/v\/1509353021","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Error while copying file to target location (copied bytes: 0, expected filesize: -1 )\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(171): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(false)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(314): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('1509353021', false)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(130): Sabre\\\\DAV\\\\Tree->copyNode(Object(OCA\\\\DAV\\\\Meta\\\\MetaFile), Object(OCA\\\\DAV\\\\Files\\\\FilesHome), '1509353021')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(161): Sabre\\\\DAV\\\\Tree->copy('meta\\\/64\\\/v\\\/15093...', 'files\\\/admin\\\/150...')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(642): Sabre\\\\DAV\\\\Tree->move('meta\\\/64\\\/v\\\/15093...', 'files\\\/admin\\\/150...')\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(256): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(175): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":166,\"User\":\"admin\"}"}
```

This should be a 403.

2017-10-30 09:08 UTC, PVince81 commented
- [ ] BUG: ext storage, download versions are empty

Steps:

1. Setup SFTP ext storage "/sftp"
1. Create file "/sftp/test.txt" + versions with text editor
1. Download file with cadaver's GET: `/owncloud/remote.php/dav/meta/$fileId/v/$timestamp` (replace accordingly)

Expected: file contents is there
Actual: file is empty.

Note that downloading over the web UI works as it uses the old APIs, so the version content does exists. It's the DAV part that is not retrieving it properly.

2017-10-30 09:09 UTC, PVince81 commented
and this is why I'd like to have automated tests for ext storages ^

2017-10-30 09:43 UTC, DeepDiver1975 commented
> BUG: need to properly block MOVE operations:

I'm getting 403 - what is the file with fileid 64 ???

![bildschirmfoto von 2017-10-30 10-42-17](https://user-images.githubusercontent.com/1005065/32164232-20575474-bd5f-11e7-942e-60775209a258.png)

2017-10-30 09:45 UTC, PVince81 commented
@DeepDiver1975 a regular file. But I have user-key encryption on, maybe that's causing it.

2017-10-30 10:38 UTC, DeepDiver1975 commented
> DAV versions not listable as share receiver from external storage

sharing does simply not work 💥

2017-10-30 14:30 UTC, PVince81 commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +			$source = fopen('php://memory','r+');
I'm surprised this doesn't work by simply calling the wrapper's fopen and let it do the key magic for you.

@sharidas ideas ?

2017-10-30 14:41 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +			$source = fopen('php://memory','r+');
hmmm .... like:

```php
$this->fopen($v['storage_location'], 'r'+);

2017-10-30 15:23 UTC, DeepDiver1975 commented
> @DeepDiver1975 a regular file. But I have user-key encryption on, maybe that's causing it.

this should be fixed now - this was encryption related from my pov

2017-10-30 15:53 UTC, sharidas commented on lib/private/Files/Storage/Wrapper/Encryption.php
> +			$source = fopen('php://memory','r+');
@PVince81  Yes that's right. It wont work. The fopen call made in the updated version of this PR should work.

2017-11-06 09:46 UTC, PVince81 commented on apps/files_versions/lib/Storage.php
> +						$versions[$key]['storage_location'] = "$dir/$entryName";
@DeepDiver1975 ping

2017-11-06 09:48 UTC, PVince81 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +		$handle = $this->fopen('r+');
"r" instead of "r+". from the docs, "r+" means open for update. We only need read access

2017-11-06 09:58 UTC, PVince81 commented
- [ ] BUG: [minor] am able to `cd` into the meta folder of a fileid pointing to a folder

2017-11-06 10:00 UTC, PVince81 commented
Bug from https://github.com/owncloud/core/pull/29207#issuecomment-340380269 still exists

2017-11-06 10:01 UTC, PVince81 commented
Bug from https://github.com/owncloud/core/pull/29207#issuecomment-340382389 still exists. Still getting 500 instead of 403.

2017-11-06 10:03 UTC, PVince81 commented
Downloading a version from an ext storage file with encryption is still empty: https://github.com/owncloud/core/pull/29207#issuecomment-340383921

Strange, I thought that your changes related to encryption would fix this scenario.

What scenario did you fix and test ?

2017-11-06 10:06 UTC, DeepDiver1975 commented
> Bug from #29207 (comment) still exists

does an sftp external storage behave different compared to a local external storage? 💥

2017-11-06 10:07 UTC, PVince81 commented
@DeepDiver1975 SFTP shouldn't behave differently :-/

2017-11-06 10:07 UTC, DeepDiver1975 commented
let me retest all this  .....

2017-11-06 10:14 UTC, PVince81 commented
Even with local storage I get empty versions on download.

2017-11-06 10:18 UTC, DeepDiver1975 commented
> Even with local storage I get empty versions on download.

are you sure you grabbed the latest code?

2017-11-06 10:20 UTC, PVince81 commented
Yes, already checked
```
commit c35178fbace813cfdc2992642100dca5769e2666 (HEAD -> feature/29087, origin/feature/29087)
Author: Thomas Müller <thomas.mueller@tmit.eu>
Date:   Mon Oct 30 15:16:01 2017 +0100

    Allow decryption of versions when being accessed by getContentOfVersion()

commit 48c4ea5798e0990ba7fbccd482894c687fbb496d
Author: Thomas Müller <thomas.mueller@tmit.eu>
Date:   Mon Oct 30 12:28:29 2017 +0100

    Adding etag, mtime and mimetype to versions
```

Maybe we have some slight env differences.

If you cannot reproduce this I can try and debug it.

2017-11-06 11:42 UTC, DeepDiver1975 commented
> BUG: [minor] am able to cd into the meta folder of a fileid pointing to a folder

I dont see this as an issue - think about we will add further sub nodes in addition to v - those can be valid for folders - like the discussed redirect link

2017-11-06 13:11 UTC, PVince81 commented
- [ ] BUG: with encryption enabled, try accessing versions of disabling file: 500 error on the "v" collection: `iles_encryption\\\/OC_DEFAULT_MODULE not found while trying to get owner`

- [ ] BUG: ext storage global mount applied to "admin" group + received share as user1 from admin from said storage + encryption: try downloading version: 404 Not found. Listing the versions work though.

- [ ] BUG: same scenario as above, but try listing versions as "admin" from the ext storage file: 500 error: `test\\\/bacon.txt not found while trying to get owner` (bacon.txt is the file)

2017-11-06 13:18 UTC, PVince81 commented
Integration tests also fail for me locally, without encryption:
```
    /srv/www/htdocs/owncloud/tests/integration/features/dav-versions.feature:12
    /srv/www/htdocs/owncloud/tests/integration/features/dav-versions.feature:20
```

2017-11-07 15:19 UTC, PVince81 commented
All bugs I found are not reproducible any more now.

I noticed that if a file is in trashbin, the version collection is empty. This is fine for now. We can look into making trashed versions accessible in a future PR. In general there is no need to access trashed versions from an API standpoint at this stage.

2017-11-07 15:23 UTC, PVince81 commented
Integration tests pass locally as well, even with encryption. Good job.

Now would be cool to get integration tests for all the reported cases. AFAIK we already have all the necessary behat steps to write the scenarios.

2017-11-08 08:42 UTC, DeepDiver1975 commented
> Now would be cool to get integration tests for all the reported cases. AFAIK we already have all the necessary behat steps to write the scenarios.

this is done in #29488

2017-11-08 08:43 UTC, DeepDiver1975 commented
> I noticed that if a file is in trashbin, the version collection is empty. This is fine for now. We can look into making trashed versions accessible in a future PR. In general there is no need to access trashed versions from an API standpoint at this stage.

we anyhow need to work on trashbin api - like /meta/1234/t or what so ever - need to think about this.

2017-11-08 08:46 UTC, PVince81 approved these changes
:+1: ok to merge for master then.

Try massaging Jenkins

2017-11-08 11:54 UTC, merged

2017-11-26 15:11 UTC, phil-davis commented
@DeepDiver1975 and/or @PVince81 
Is this to be backported?
If so, then #29637 would then also logically get backported.
I ask because when making changes in master to integration tests, chunks of new code here make other (future) backports a little trickier - so if it is to be backported then good.

2017-11-27 08:34 UTC, DeepDiver1975 commented
@phil-davis there will be a bigger backport parts of all related PRs once we are done ...

2017-11-27 08:40 UTC, phil-davis commented
OK - then I will leave other "random integration and unit test refactoring" backporting for after this sort of stuff is backported.

2018-09-02 20:29 UTC, elgrafico commented
Just to let you know:    
I had an existing user "meta" and updated to 10.0.9, which gave me a bunch of  "NotPermittedException"s with webdav, gallery and whatnot, preventing access to the users files, shares and calendars.  

I'd recommend communicating that "meta" is a reserved user name since 10.0.9

2018-09-03 02:55 UTC, phil-davis commented
Issue #32547 raised. 
Username ``meta`` does not work for me.