[WIP] Introducing metadata collections in dav
owncloud/core pull request #29214
Opened 2017-10-12 04:49 UTC by sharidas

This change is to have metadata collection
in dav app. This will help users to:
1) Create fileid with a UUID
2) Create subfolder "p" inside "meta" folder
3) Create subfolder "v" inside "meta" folder
The "p" folder stands for preview and "v"
folder stands for version.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-12 07:54 UTC, DeepDiver1975 requested changes

2017-10-12 07:54 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/MetaDataHome.php
> +	public function __construct($principalInfo, IMetaData $metaData) {
there should be no principalInfo here - this collection is not user based

2017-10-12 07:54 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/RootCollection.php
> +class RootCollection extends AbstractPrincipalCollection {
no principal collection - there is no user involved.

we want 'meta/$fileid/v' not 'meta/$user/$fileId/v

2017-10-12 07:54 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/RootCollection.php
> +		$metaData = \OC::$server->getMetaData();
Please have a look at #29207 

```php
$metaNodeOfFile = \OC::$server->getRootFolder()->get("meta/{$info->getId()}/v");

2017-10-12 08:21 UTC, PVince81 commented on lib/public/IMetaData.php
> + * @since 6.0.0
10.0.4 ?

2017-10-12 08:21 UTC, PVince81 commented on lib/public/IMetaData.php
> + * This class provides avatar functionality
not avatar

2017-10-12 08:26 UTC, DeepDiver1975 commented on lib/public/IMetaData.php
> + * @since 6.0.0
this class will go away ... dont worry

2017-10-12 10:27 UTC, DeepDiver1975 commented on apps/dav/lib/SystemTag/SystemTagsByIdCollection.php
> +		return 'systemtags poda thendi';
???

2017-10-12 10:32 UTC, sharidas commented on apps/dav/lib/SystemTag/SystemTagsByIdCollection.php
> +		return 'systemtags poda thendi';
Removed. Got added to PR by mistake.

2017-10-13 06:45 UTC, DeepDiver1975 commented on lib/private/Files/Storage/Local.php
> +
TODO:
- [ ] try to move this to class Common

2017-10-17 06:50 UTC, DeepDiver1975 requested changes

2017-10-17 06:50 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/MetaDataHome.php
> +	private $metaData;
unused

2017-10-17 06:50 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/MetaDataHome.php
> +	function getChild($name) {
name ignored?

2017-10-17 06:50 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/MetaDataNode.php
> +	public function getMetaNodeFolder() {
public?

2017-10-17 06:50 UTC, DeepDiver1975 commented on apps/dav/lib/MetaData/MetaDataNode.php
> +		$this->nodeFolder->getStorage()->mkdir('meta');
as discussed - meta sub tree is read only

2017-10-19 08:29 UTC, DeepDiver1975 commented
closing this in favor of #29281

2017-10-19 08:29 UTC, closed without merging