27854 non existing folder skeletondirectory
owncloud/core pull request #29250
Opened 2017-10-15 19:04 UTC by Gandolf90

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-15 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=29250) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=29250) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=29250) it.</sub>

2017-10-16 06:22 UTC, DeepDiver1975 requested changes
Thanks a lot for your contribution!
Very welcome!
Please make sure to squash our commits. THX

2017-10-16 06:22 UTC, DeepDiver1975 commented on lib/private/legacy/util.php
> +			throw new OC\HintException('Can not Access to Skeleton Folder, check for right Path in config.php');
- [ ] please add the value of $skeletonDirectory
- [ ] test should read as
```php
throw new OC\HintException("The skeleton folder '$skeletonFolder' is not accessible.');

2017-10-16 06:22 UTC, DeepDiver1975 commented on tests/lib/UtilTest.php
> +		$this->expectException(HintException::class);
please use phpunit annotation - see the phpunit docs

2017-10-16 06:22 UTC, DeepDiver1975 commented
Please also sign the CLA - see the comment above

2017-10-18 11:16 UTC, IljaN commented
Please reference pull requests to issues like this #27854

2017-10-19 10:43 UTC, IljaN commented on tests/lib/UtilTest.php
> +		$this->expectException(HintException::class);
You can remove this line if you use the annotation see:
https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.expectedExceptionMessage

2017-10-20 12:58 UTC, IljaN commented on lib/private/legacy/util.php
> +		if(!is_dir($skeletonDirectory))  {
Missing space between if and opening parenthesis => if ( )

2017-10-24 08:52 UTC, IljaN commented
@Gandolf90 Some tests are failing, please fix. See Jenkins for details.

2017-10-24 18:56 UTC, Gandolf90 commented
@IljaN added changes 
new added tests passed - should i repair some other tests ?

2017-10-24 20:22 UTC, Gandolf90 commented
@IljaN how can I test the failed Selenium/Travis tests?

2017-10-25 10:03 UTC, IljaN commented
@Gandolf90  "make test"

2017-10-25 13:12 UTC, Gandolf90 commented
@IljaN  testet local with "make test" and jenkins tests passed
don't now why travis make with php 5.6 settings and selenium error to connect with curl as user

2017-10-25 13:16 UTC, IljaN commented
@Gandolf90 Don`t worry our CI is like a diva sometimes :)

2017-10-25 15:24 UTC, phil-davis commented
@Gandolf90 Selenium/Travis fails because this is a PR from a forked copy of the repo. So Travis does not provide the job with the authentication keys to the ownCloud SauceLabs account. There are 2 options:
1) you can ask for access to the ownCloud core repo (which I got as a new community member a few years ago without any hassle) - then clone that and make your own branch in there.
2) create yourself a SauceLabs open-source free account, then put the details in your own Travis linked to GitHub. Then make a PR of the code in your fork to the master of your fork - Travis and SauceLabs will happily talk using all your own authentication data.

2017-10-25 16:53 UTC, closed without merging

2017-10-25 17:10 UTC, Gandolf90 commented
@IljaN  or @DeepDiver1975  can you create a temporary access to make the pull request ?

2017-10-25 17:10 UTC, Gandolf90 commented
@phil-davis  thanks for Hint

2017-10-26 09:04 UTC, IljaN commented
@Gandolf90  Why close?

2017-10-26 09:12 UTC, Gandolf90 commented
@iljan Because i wanted to make a Branch from Core Repo and make there the pr as @phil-davis wrote

2017-10-26 09:41 UTC, phil-davis commented
@Gandolf90 when you make the PR in core, please mention it here so it is easy to find.

2017-10-26 09:49 UTC, Gandolf90 commented
@phil-davis ok

2017-10-26 16:57 UTC, Gandolf90 commented
@IljaN  @DeepDiver1975  @phil-davis  here it goes : https://github.com/owncloud/core/pull/29367