[Central group table][WIP] Centr groups and memberships integration
owncloud/core pull request #29282
Opened 2017-10-18 11:15 UTC by mrow4a

After https://github.com/owncloud/core/pull/29154, this PR should integrate it into https://github.com/owncloud/core/pull/29154 feature

2017-11-20 12:05 UTC, mrow4a commented
Ok, this feature is done - I only have a problem with UserTrait thing used in unit tests. I cannot make it work with membership table in unit tests obviously, since there is no FK on MemoryAccountTable, which mocks real account table
https://github.com/owncloud/core/blob/master/tests/lib/Traits/UserTrait.php

@DeepDiver1975 @PVince81 @butonic

2017-11-21 21:10 UTC, mrow4a commented
@butonic, could you have a look on the errors I got with PostgreSQL? It is very strange, and maybe you might have some clue

```22:06:48 Doctrine\DBAL\Driver\PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block```

@DeepDiver1975

2017-11-22 14:04 UTC, mrow4a commented
Ok, PR passes tests and is ready to:
1. Merge depending PRs
2. Review the last commit, which does integration with corrected unit tests. 

@DeepDiver1975 @PVince81 @butonic

2017-11-24 08:00 UTC, DeepDiver1975 requested changes
which is the pr that bring this all together into master?

2017-11-24 08:00 UTC, DeepDiver1975 commented on tests/lib/Traits/MembershipTrait.php
> +trait MembershipTrait {
make this part of groups? nobody should really work on the membership level

2017-11-28 13:15 UTC, mrow4a commented on tests/lib/Traits/MembershipTrait.php
> +trait MembershipTrait {
I am not sure what is your intention here

2017-11-28 13:16 UTC, mrow4a commented
@DeepDiver1975 
> which is the pr that bring this all together into master?

Please have a look on PR description (1st post)

2017-11-30 15:08 UTC, mrow4a commented on tests/lib/Traits/MembershipTrait.php
> +trait MembershipTrait {
@DeepDiver1975 could you clarify a bit?

2017-12-04 09:52 UTC, mrow4a commented
This PR is ready for review @DeepDiver1975 @PVince81 @jvillafanez @butonic @tomneedham - it is quite important, since it is the integration PR.

2017-12-13 13:35 UTC, mrow4a commented
Any input here?

2017-12-13 13:49 UTC, DeepDiver1975 commented on tests/lib/Traits/MembershipTrait.php
> +trait MembershipTrait {
this trait holds no functionalities a test developer could use - why should this trait be added then.

in addition if I add the group trait I expect that not only groups but also the memberships are taken care of

therefore -> merge this code into group trait

or am I missing a scenario?

2017-12-13 13:53 UTC, mrow4a commented on tests/lib/Traits/MembershipTrait.php
> +trait MembershipTrait {
I am not sure if this is possible, but I will try.

2017-12-14 21:31 UTC, tomneedham commented
11am UK Friday 15th December meet.jit.si/oc-group-table @mrow4a will run through progress, status and how we can help move this forward :)

2017-12-15 11:43 UTC, mrow4a commented on lib/public/IUser.php
> +	public function getID();
@DeepDiver1975 requires not to use it

2017-12-15 11:43 UTC, mrow4a commented on lib/private/User/RemoteUser.php
> +	public function getID() {
Drop it

2017-12-15 17:47 UTC, mrow4a commented
Rebased base branch and number of unit tests exploded, I need some time to adjust all of it, also adding fixes required by Thomas.

2018-01-15 11:34 UTC, mrow4a commented on lib/private/Group/Database.php
>  class Database extends \OC\Group\Backend {
Now, as we have memberships handled in MembershipManager, and central group table with GroupMapper, this \OC\Group\Backend becomes "external backend" - I also cleared all complex functionalities from it, and now it just stores gid.

2018-01-15 11:35 UTC, mrow4a commented on apps/provisioning_api/tests/TestCase.php
>  abstract class TestCase extends \Test\TestCase {
User and Group Traits are now used for tests. GroupTrait also handles memberships - using MembershipMemoryManager and GroupMemoryMapper

2018-01-15 11:35 UTC, mrow4a commented on apps/files_sharing/tests/SharedMountTest.php
> +		$g = $this->createGroup('testGroup');
This is GroupTrait specific function (TestCase uses GroupTrait)

2018-01-15 11:37 UTC, mrow4a commented on lib/private/Group/Group.php
> +		$account = $this->userManager->getAccountObject($user);
Since we cannot get internal user account id, we need to retrieve account for this user using user manager. Account has access to internal id @DeepDiver1975 @tomneedham (This is the fix where user class was exposing ->getId() which it shouldnt. It should be handled by user manager and account. (group manager and backend group)

2018-01-15 11:39 UTC, mrow4a commented on lib/private/User/Manager.php
> +	public function getAccountObject(\OCP\IUser $user) {
This is similar to getUserObject, but instead of getting user from account, this gives account for user. Please mind that this 2 functions are not exposed via interface for programmers. @DeepDiver1975 @tomneedham @jvillafanez

2018-01-15 11:40 UTC, mrow4a commented on lib/private/User/Manager.php
>  	public function getBackend($backendClass) {
This is very hacky and one should use getBackends instead.

2018-01-15 11:41 UTC, mrow4a commented on lib/private/User/Manager.php
> +	public function reset(AccountMapper $mapper, $backends) {
This is used only for unit tests, and as getUserObject and getAccountObject, are not exposed via interface and should be used only in User Management scope

2018-01-31 20:03 UTC, merged

2018-01-31 20:03 UTC, mrow4a commented
Merge into centr_groups branch, as discussed on CS3