[WIP] Added parts to run js tests in drone
owncloud/core pull request #29299
Opened 2017-10-19 12:50 UTC by SergioBertolinSG

Starting to add more jobs into drone.

2017-10-19 12:53 UTC, DeepDiver1975 requested changes
- [ ] remoce the js step from Jenkins file

2017-10-26 07:31 UTC, DeepDiver1975 commented on .drone.yml
> +      - PHP_VERSION=${PHP_VERSION}
both environments are not used in test-javascript.sh - right? we can drop them from my understanding

2017-10-26 10:12 UTC, SergioBertolinSG commented
Failed test in javascript:

```javascript
PhantomJS 2.1.1 (Linux 0.0.0) OC.Share.ShareDialogView autocompletion of users is sorted naturally FAILED
	Expected $[1].label = 'Petra' to equal 'peter B.'.
	Expected $[1].value.shareWith = 'Petra' to equal 'peter B.'.
	Expected $[2].label = 'peter B.' to equal 'Petra'.
	Expected $[2].value.shareWith = 'peter B.' to equal 'Petra'.
	core/js/tests/specs/sharedialogviewSpec.js:282:47
```


Some steps to debug the javascript failed test locally:

1. Install drone cli http://docs.drone.io/cli-installation
2. Clone core's master
3. Checkout my branch drone-enabling-js-tests
4. Change core's .drone.yml with my file https://gist.github.com/SergioBertolinSG/8394e95c9cb678f745b0348674daa6de
5. Run it this way: PHP_VERSION=7.1 drone exec

cc @PVince81

2017-10-26 12:22 UTC, SergioBertolinSG commented
Some error in jenkins:

ERROR: No test report files were found. Configuration error?
Finished: FAILURE

2017-10-26 12:48 UTC, SergioBertolinSG commented
PHP 7.2 is not yet supported AFAIK.
MariaDB is failing because:

```sql
Error while trying to create admin user: An exception occurred while executing 'ALTER TABLE oc_calendarsubscriptions CHANGE `lastmodified` lastmodified INT UNSIGNED DEFAULT NULL NOT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'lastmodified'
 ->
```

Do we need to have both MariaDB and MySQL ?

2017-10-27 09:57 UTC, SergioBertolinSG commented
OK, so I have skip the failing test: https://github.com/owncloud/core/pull/29299/files#diff-e18e03b16d13b8606ea5c1cfe595a23fR232

I'll open an issue in core after this is merged to fix that failing test. cc @PVince81

2017-10-27 11:16 UTC, DeepDiver1975 requested changes

2017-10-27 11:16 UTC, DeepDiver1975 commented on .drone.yml
> +      branch: [master, stable10, stable9.1]
remove branch here and rebase with master - see https://github.com/owncloud/core/blob/master/.drone.yml#L5

thx

2017-10-27 16:06 UTC, DeepDiver1975 commented
@SergioBertolinSG jenkins still hates this ..... please adopt. THX

2017-10-27 17:05 UTC, PVince81 commented
> jenkins still hates this

Hahaha, Jenkins doesn't want to be obsoleted

2017-10-27 17:08 UTC, PVince81 commented
Uh oh:
```
Test\Files\ViewTest::testCopyBetweenStorageNoCross
mkdir(): No space left on device
```

2017-10-27 20:44 UTC, tboerger commented on .drone.yml
> +      event: [push, pull_request]
Drop that, push and pull request is the default behavior

2017-10-30 08:47 UTC, DeepDiver1975 commented
squash please and we are ready to go - THX

2017-10-30 10:10 UTC, DeepDiver1975 approved these changes

2017-10-30 10:10 UTC, merged

2017-10-30 10:11 UTC, DeepDiver1975 commented
@SergioBertolinSG please backport to stable10 - for 9.1 please add this commit to #29236 - THX

2017-10-30 11:45 UTC, SergioBertolinSG commented
Backports
stable10: https://github.com/owncloud/core/pull/29387
stable9.1: Included in https://github.com/owncloud/core/pull/29236