AccountMapper get by email is now case insensitive
owncloud/core pull request #29332
Opened 2017-10-23 14:10 UTC by PVince81

## Description
AccountMapper::getByEmail() is now case insensitive.
This is important to be able to detect duplicates through this method.

## Related Issue
Required for https://github.com/owncloud/guests/pull/168

## Motivation and Context

## How Has This Been Tested?
Manual testing guests app + unit tests

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-23 14:26 UTC, mrow4a commented
To me, email should be stored lower case in the database to ensure uniqueness

2017-10-23 14:36 UTC, PVince81 commented
@mrow4a we currently don't have a constraint in the database as it might happen that more than one user have the same email address depending on which backend they come from (guests, LDAP, etc). This is a topic still to be discussed and solved. Currently we don't want to block all duplicates automatically, only the creation of guests with email addresses that already exist in the system.

Looking at the Account and AccountMapper code, it seems that we store the email address as is, not lower-cased...

2017-10-23 14:49 UTC, mrow4a commented
So when he searches for user by email, he might see many entries to select, pointing to many different users ? How he will know which one to share with...

2017-10-23 14:51 UTC, PVince81 commented
@mrow4a not really. The case where multiple user backends are providing the same email addresses is a corner case that we need to look into.

For the regular case there will only be a single email address per user.

The problem we have currently is only with the guests app which makes it possible for any user to invite by email and create an account, which becomes problematic when dealing with duplicates. The guests PR uses the method AccountMapper->getByEmail() to find if there is already an account to decide whether to allow creation or not.

Regardless of your concerns (which are also mine), I think this PR is a step in the right direction.

2017-10-23 14:55 UTC, mrow4a commented
I think this makes no sense... if you are inviting person via email, and that person already exists in the system, you should get error that this person already exists in the system. Email is kind'a unique identifier of the person in real world.

2017-10-23 14:59 UTC, mrow4a commented
I understand, that the idea is to allow people have multiple user accounts, even if it points to the same email right?

2017-10-23 15:02 UTC, PVince81 commented
> I understand, that the idea is to allow people have multiple user accounts, with the same email addresses?

No, we do not want to allow that. But currently due to the architecture it could happen for exotic setups. So we cannot add a constraint at this point without thinking about a migration for said exotic setups. This is why we removed the DB constraint to avoid breaking older setups. We'll likely add it back in the future.

2017-10-23 17:44 UTC, DeepDiver1975 requested changes

2017-10-23 17:44 UTC, DeepDiver1975 commented on lib/private/User/AccountMapper.php
> +			->where($qb->expr()->eq($qb->createFunction('LOWER(`email`)'), $qb->createNamedParameter(strtolower($email))));
we shall not mix the lower functions - both lower operations shall be handled by sql

2017-10-24 06:09 UTC, butonic commented
Even for LDAP there is a prmary email address. But ldap can be configured to use additional login attributes. And for them something like additionalEmail can be multivalue. No need to store them in the oc db unless you want to be able to search by these emails, which is what the additional search terms are for.

2017-10-24 06:18 UTC, PVince81 commented
@DeepDiver1975 fixed, please recheck. I hope the format is ok (let's see what Oracle says...).

@butonic was this your response to @mrow4a ? I think getByEmail should not use the search terms anyway as those could be truncated.

2017-10-24 06:56 UTC, DeepDiver1975 approved these changes

2017-10-24 12:12 UTC, DeepDiver1975 commented
Jenkis was successfull -> merge

2017-10-24 12:12 UTC, merged

2017-10-24 12:25 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/29341