Correctly detect that an empty files page is loaded
owncloud/core pull request #29343
Opened 2017-10-25 06:43 UTC by phil-davis

## Description
1) Be more specific about which div the ``emptycontent`` id is contained in (there are lots of ``emptycontent`` divs in different parts of the page)
2) Move check for fileList being visible so it only applies when there are files.
3) Add a core test creating an empty folder and navigating into it...

## Related Issue
#29138 
(this PR is a "downstream" thing that was noticed while getting Edge tests running)

## Motivation and Context
When a folder is empty, the UI test code is not correctly detecting that the (empty) files page for that folder is loaded. The "wait till page is loaded" logic was timing out (10 seconds). Now that we throw an exception on page load timeout, this was causing test fails in the ``files_texteditor`` tests, because those tests navigated into an empty folder and then created a file in the folder.

There were no core UI tests that navigated into an empty folder. We should have at least one such test so that the empty files page logic is exercised in core testing.

## How Has This Been Tested?
Run ``files_texteditor`` UI tests locally and confirm they now pass.'
Run the new core test locally and confirm it fails before the change, and passes with the changed code.
Travis will do a full test run for us.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-25 07:11 UTC, individual-it commented
does this solve #29264 ?

2017-10-25 07:18 UTC, phil-davis commented
Yes - I did not even know about that issue.
I am also adding some tests to navigate into a folder in the trashbin, which will exercise the empty file list in the trashbin page case. Another commit will come...

2017-10-25 08:21 UTC, individual-it approved these changes

2017-10-25 10:03 UTC, phil-davis commented
@individual-it please check the diffs again. I added core tests and a lot of associated refactoring.

2017-10-25 10:05 UTC, phil-davis commented on tests/ui/features/files/files.feature
> +		Then there are no files/folders listed
This step is a kind-of obvious test! But it does exercise the step code on a files-page file-folder list.
(the trashbin test added further down exercises the same step code when on a trashbin page)

2017-10-25 10:22 UTC, individual-it approved these changes

2017-10-25 10:25 UTC, individual-it requested changes
![screenshot-2017-10-25 job 13786 2 - owncloud core - travis ci](https://user-images.githubusercontent.com/2425577/31994042-f833ed40-b99e-11e7-8f8d-66d9c203cb98.png)

2017-10-26 02:40 UTC, phil-davis commented
@individual-it please review again. Then I can squash the last "fixup things that I broke" commit into the 2nd-last commit and let CI run again.

2017-10-26 03:14 UTC, individual-it approved these changes

2017-10-26 03:50 UTC, phil-davis commented
Backport stable10 in #29353

2017-10-26 06:06 UTC, merged