[WIP] Moved phpunit tests running on sqlite to drone
owncloud/core pull request #29365
Opened 2017-10-26 13:12 UTC by SergioBertolinSG

2017-10-27 06:11 UTC, DeepDiver1975 requested changes
one jenkins step -> 3 drone steps - this is not what we did agree on

2017-10-27 06:12 UTC, DeepDiver1975 requested changes

2017-10-27 06:12 UTC, DeepDiver1975 commented on .drone.yml
> +      branch: [master, stable10, stable9.1, stable9]
not necessary - there is a global branches config now in master - please rebase

2017-10-27 06:12 UTC, DeepDiver1975 commented on .drone.yml
> +      branch: [master, stable10, stable9.1]
not necessary

2017-10-27 06:38 UTC, DeepDiver1975 commented
failing jenkins is because of this line - https://github.com/owncloud/core/pull/29365/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R24

2017-10-27 08:38 UTC, SergioBertolinSG commented
> failing jenkins is because of this line - https://github.com/owncloud/core/pull/29365/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R24

Why does that line make it fail? The PHPUnit 7.1/sqlite stage was creating that file?

2017-10-27 09:11 UTC, DeepDiver1975 commented
> Why does that line make it fail? The PHPUnit 7.1/sqlite stage was creating that file?

its a type - the generated file is not named sqlite ....

2017-10-27 09:11 UTC, DeepDiver1975 commented
... and please squash your commits

2017-10-31 17:48 UTC, SergioBertolinSG commented
Failing in jenkins: 

Test report file /var/lib/jenkins/workspace/owncloud-core_core_PR-29365-WR66RMKOWSY7ODQJVRC4FL3OUNMRUJ6P3FKCZ6TMQYQSUSTM5HCA@3/tests/autotest-results-oci.xml was length 0

But it doesn't seem related with my changes.

2017-11-02 08:15 UTC, DeepDiver1975 approved these changes

2017-11-02 08:15 UTC, merged

2017-11-03 08:03 UTC, SergioBertolinSG commented
@DeepDiver1975 all the drone PR should be backported to stable10?