Fixed different app author scenarios not working
owncloud/core pull request #29381
Opened 2017-10-28 16:11 UTC by splitt3r

## Description
If there are multiple app authors or the app author adds email / url to <author> tag in info.xml oC is not able to display the information correctly.

Examples:

- https://github.com/pbek/qownnotesapi/blob/develop/appinfo/info.xml
- https://github.com/splitt3r/polls/blob/unit-tests/appinfo/info.xml

## Related Issue
PR https://github.com/owncloud/core/pull/29221 is somehow related.

## How Has This Been Tested?
Tested in FF, Chrome and Edge

## Screenshots (if appropriate):
![App settings](https://user-images.githubusercontent.com/1869584/32136234-a68c8a42-bc0a-11e7-95e9-1c323a17cbec.png)

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-30 07:37 UTC, DeepDiver1975 requested changes

2017-10-30 07:37 UTC, DeepDiver1975 commented on settings/js/admin-apps.js
> +		if (_.isObject(app.author) && !_.isUndefined(app.author['@value'])) {
does this work if app.author is an array of objects?

2017-10-30 08:09 UTC, splitt3r commented on settings/js/admin-apps.js
> +		if (_.isObject(app.author) && !_.isUndefined(app.author['@value'])) {
Good question 😁. I will check that and update it.

2017-12-19 16:37 UTC, PVince81 commented
would be good to add a JS unit test, at least of the parse author logic and its two code paths.

You can use `make test-js-debug`

2017-12-19 16:52 UTC, splitt3r commented
Ok, i will have a look at it.

2018-01-08 11:17 UTC, PVince81 approved these changes
:+1: thanks

2018-01-08 11:18 UTC, PVince81 commented
I've restarted the Travis tests, let's hope it was a one-time thing

2018-01-08 12:01 UTC, splitt3r commented
Hm doesn´t look that good 😞. Are these errors related to my changes?

2018-01-08 12:39 UTC, phil-davis commented
The Travis tests that fail are the UI tests - that is because this PR is from a forked repo, so the SauceLabs credentials are not available to the job.

2018-01-08 12:42 UTC, splitt3r commented
Thanks for the clarification :)

2018-01-08 12:47 UTC, phil-davis commented
I pushed this branch into my fork, where I have my own SauceLabs credentials.
https://github.com/phil-davis/core/pull/135
That is running the UI tests now and will demonstrate (hopefully!) that they pass.

2018-01-08 14:02 UTC, phil-davis commented
@splitt3r @PVince81 Travis UI tests passed in my fork. Suitable god privs could be used to merge this PR, overriding the Travis fail here.

2018-01-08 14:03 UTC, merged

2018-01-08 14:04 UTC, PVince81 commented
@splitt3r can you backport to stable10 ? Basically create a branch off stable10, cherry pick your commits and send a PR from that branch to stable10.

If not let us know and we'll take care.

2018-01-08 14:20 UTC, phil-davis commented
Care taken :)
Backport stable10 #30043 
It is easy to do it in the "real" core repo - saves the hassle of UI test fails.