Implementation of delta-sync support on server-side.
owncloud/core pull request #29404
Opened 2017-10-31 19:40 UTC by ahmedammar

## Description
This commit adds server-side support for delta-sync, this extends the core files app.

The basic approach is to store zsync metadata files in a folder called `files_zsync/` which mirrors the structure and layout of the `files/` folder but appends `.zsync` to the metadata files. These files can be requested by the client via a new route `api/v1/zsync/$path`.

Filesystem hooks are used to mirror any `move/copy/delete` operation on the base file onto the metadata file.

The upload path is implemented by modifying the `ChunkingPlugin`, the chunk files are now assumed to be named as the offsets into the original file. The implemenation copies adds a new class `AssemblyStreamZsync` which extends `AssemblyStrem` with support to fill in the missing data in between chunk offsets from a `backingFile`.

A new `zsync` capability is added to the files app, which can be checked by the client to know if delta-sync is supported or not.

## Related Issue

owncloud/core#16162.

## How Has This Been Tested?

Mostly tested by using the owncloud command line client and macOS application. With some randomly generated files using `dd` and various modifications to those files:
```
dd if=/dev/urandom of=1g.rand.img bs=$[1024*1024] count=1024

cp 1g.rand.img 1g.rand.add300m.img
dd if=/dev/urandom of=1g.rand.add300m.img bs=$[1024*1024] count=300 oseek=1024

cp 1g.rand.img 1g.rand.mod200m.img
dd if=/dev/urandom of=1g.rand.mod200m.img bs=$[1024*1024] count=100 oseek=123 conv=notrunc 
dd if=/dev/urandom of=1g.rand.mod200m.img bs=$[1024*1024] count=100 oseek=532 conv=notrunc

cp 1g.rand.img 1g.rand.mov200m.img
dd if=1g.rand.img of=1g.rand.mov200m.img bs=$[1024*1024] count=200 iseek=118 oseek=418 conv=notrunc

cp 1g.rand.img 1g.rand.del200m.img
dd if=1g.rand.img of=1g.rand.del200m.img bs=$[1024*1024] count=622
dd if=1g.rand.img of=1g.rand.del200m.img bs=$[1024*1024] iseek=822 oseek=622
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-11-02 10:59 UTC, DeepDiver1975 requested changes
Code looks really good. Extra ❤️ for all the unit tests. Nice!

2017-11-02 10:59 UTC, DeepDiver1975 commented on apps/files/lib/Hooks.php
> +		\OCP\Util::connectHook('OC_Filesystem', 'post_rename', 'OCA\Files\Hooks', 'zsync_rename_hook');
I don't really like this in here - we want to move the files app more and more into the direction of being a pure frontend app. We need this living somewhere in core.

@PVince81 or shall we move this zsync feature into it's own app?

2017-11-02 10:59 UTC, DeepDiver1975 commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
where is this controller used?

2017-11-02 11:02 UTC, ahmedammar commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
It's used here: https://github.com/owncloud/core/pull/29404/files/3f49737922fd3d6022e2e3e6dc2bc76f6c2e77ee#diff-61a244d83f15994f5e6afe870320d695R62

2017-11-02 11:03 UTC, ahmedammar commented on apps/files/lib/Hooks.php
> +		\OCP\Util::connectHook('OC_Filesystem', 'post_rename', 'OCA\Files\Hooks', 'zsync_rename_hook');
I can do whatever you guys decide, I just put it all in files app because it made sense to *me*.

2017-11-02 11:09 UTC, DeepDiver1975 commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
I got that - but who is calling this? desktop client?

2017-11-02 11:11 UTC, ahmedammar commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
Heh, yeah I thought you didn't need me to tell you that, yes used by client:
https://github.com/owncloud/client/pull/6131/commits/2f4ba787fa848c56e88eaf09a378c722b10fc793#diff-81e8ad3e8074c317de5166e5be577fc6L451

2017-11-02 11:19 UTC, DeepDiver1975 commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
okay - can we move this to dav? We shall only use dav as api between clients and server

2017-11-10 09:42 UTC, ahmedammar commented on apps/files/lib/Controller/ZsyncApiController.php
> +class ZsyncApiController extends Controller {
Done.

2017-11-14 09:59 UTC, PVince81 commented on apps/files/lib/Hooks.php
> +		\OCP\Util::connectHook('OC_Filesystem', 'post_rename', 'OCA\Files\Hooks', 'zsync_rename_hook');
@DeepDiver1975 should we move this to the "dav" app then ?

2017-11-14 10:00 UTC, PVince81 commented on apps/files/lib/Hooks.php
> +		$from = $params[\OC\Files\Filesystem::signal_param_oldpath];
As discussed with @ahmedammar on IRC, let's use file ids as the don't change on rename/move.

So the meta files are stored as "files_zsync/$fileid" then

2017-11-14 10:14 UTC, PVince81 commented
Summary of discussion on IRC for the next steps, quoting @ahmedammar:

```
new header will be used OC-Sync-Mode and a new ChunkingPlugin called ZsyncChunkingPlugin
and ZsyncFutureFile
but it will all still live in dav ...
For now UploadFolder will check for ZsyncFutureFile like it does for FutureFile, until you tell us if a new collection is needed
```

2017-11-14 10:19 UTC, PVince81 commented
Pending decisions for further steps:

1) Move into a core bundled "zsync" app ? If yes, need 2)

2) Use a separate DAV collection "/upload-zsync" to avoid hard-coded UploadFolder thing ?

3) Where to put the hook handlers ? If 1), the hooks could be put into the app.

2017-11-15 14:44 UTC, ahmedammar commented
> new header will be used OC-Sync-Mode

I didn't need a new header in the end, the new `FutureFileZsync` is enough.

> Move into a core bundled "zsync" app ?

Not sure this is even possible, see change in `Directory.php`: https://github.com/owncloud/core/pull/29404/commits/925dbc465378fee993d87d70a77abd00889f4e18#diff-dcf21c8d2df4174779892b49e8da3515

2017-11-20 17:47 UTC, mrow4a commented
Awesome @ahmedammar ! How easiest I can test it manually ? Do you use some predefined set of scripts, or just manually with the client? I consider building few scripts to test it with smashbox https://github.com/owncloud/smashbox

2017-11-20 17:50 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/Directory.php
> +			} else if (FutureFile::isFutureFile() or FutureFileZsync::isFutureFile()) {
Hmm, it is just style thing probably, but I think in the rest of the codebase we use ||. @DeepDiver1975 .

But yes, makes sense as it is a similar scenario as in chunking.

2017-11-20 17:52 UTC, mrow4a commented on apps/dav/lib/Upload/AssemblyStreamZsync.php
> +class AssemblyStreamZsync extends AssemblyStream {
Nice idea :>

2017-11-20 17:54 UTC, mrow4a commented
I dont have many comments, really good job! Wow! I need to manually test it to see where it misbehaves, but big plus for unit tests!

2017-11-20 21:04 UTC, ahmedammar commented
> How easiest I can test it manually ? Do you use some predefined set of scripts, or just manually with the client?

Yeah just manually with the command line client mostly (and the gui, but less often). I use the files generated by `dd` at the top of this PR to test it.

> I consider building few scripts to test it with smashbox https://github.com/owncloud/smashbox in some predefined scenarios.

Please do, I'm pretty much out of time on this now, I start a new job soon so I will probably disappear for a while.

> I dont have many comments, really good job! Wow! I need to manually test it to see where it misbehaves, but big plus for unit tests!

Thanks 😄

2017-11-20 21:23 UTC, mrow4a commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
Hmm, I think we might consider version, @ogoffart ?

2017-11-20 21:42 UTC, ahmedammar commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
I did think about this when I added it but I came to the conclusion that a version doesn't make much sense in this case because it's all in the metadata file itself. I can change it to a version if you prefer though, that's a pretty simple change.

2017-11-20 21:49 UTC, mrow4a commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
I think it will go safer with version, let's see feedback from client guys.

2017-11-21 08:45 UTC, ahmedammar commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
Done.

2017-11-21 09:52 UTC, mrow4a commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
Isnt the change also required on the client?

2017-11-21 09:59 UTC, ahmedammar commented on apps/dav/lib/Capabilities.php
> +				'zsync' => true,
Yes, done there too. see: https://github.com/owncloud/client/pull/6131/commits/7caaff54efda4870f33d608475c26ab6004eba9b

2018-01-11 04:02 UTC, ahmedammar commented
Bump.

2018-01-16 10:30 UTC, mrow4a commented
Ok, I reviewed this PR again (not testing it yet manualy and with our integration smashbox tests) and I have nothing to add. I am currently busy with one other thing, which I am currently finishing, and this is  next on my list. 

I am also thinking about moving this code into separate app. This PR is not that heavy, but since we are more interested into limiting code in core, it might be necessary. @DeepDiver1975 @PVince81

2018-01-16 10:41 UTC, mrow4a commented
Hmm, ok. I had a look and moving it into separate app will be quite difficult, and we would need to make more changes. I would merge it into core for now after testing, and make it being tried out by community (from main sync code perspective). When all fixes are there make more effort to place it in separate app - maybe also together with new chunking algorithm as they are similar (kind of).

2018-01-16 10:54 UTC, DeepDiver1975 commented
> maybe also together with new chunking algorithm as they are similar (kind of).

chunking is an integral part of owncloud - why separate it?

2018-01-16 10:56 UTC, DeepDiver1975 commented
> Hmm, ok. I had a look and moving it into separate app will be quite difficult, and we would need to make more changes

I dont see this being moved to an app - the code is tightly coupled to the dav code base.
This needs continuous testing and needs to be developed further together with the rest of the dav code.

2018-01-16 10:57 UTC, DeepDiver1975 commented
@ahmedammar please perform one final rebase and we merge your baby. Thanks a lot!

And sorry for the long waiting time ... we need to do better in keeping in touch with the community contributors!

2018-01-16 12:20 UTC, ahmedammar commented
Rebased, thanks guys!

2018-02-05 10:40 UTC, orzeech commented
Hi, I've been testing this code a bit. The server rarely, but has problems when synchronizing many big files that were modified at once. Sometimes it reports wrong block size (to the delta-sync enabled client) and makes synchronization impossible. I haven't had any problems with regular client. I will let you know if this happens with further testing.

2018-02-22 21:39 UTC, mrow4a commented on apps/dav/lib/HookManager.php
> +			'deleteZsyncMetadata');
wait wait.. ok this PR needs hard performance review...

2018-02-22 21:41 UTC, mrow4a commented on apps/dav/lib/Files/ZsyncPlugin.php
> +	function httpDelete(RequestInterface $request, ResponseInterface $response) {
I would love to see at some point some relations here.. without integrity contraints it can be a mess and corruption on corruption.

2018-02-22 22:03 UTC, mrow4a commented on apps/dav/lib/Upload/ChunkingPluginZsync.php
> +		if (strpos($node->getDavPermissions(), 'M') === false) {
@DeepDiver1975 does this prevents also files_primary?

2018-02-22 22:14 UTC, mrow4a commented
Apart from what @orzeech said, which if less usual case. For me this has to pass this test plan:

DSC - delta sync client
NC - normal client

1. Client with and without delta sync client support

DSC uploads new - > NC downloads -> NC uploads new
NC uploads new - > DSC downloads -> NC uploads new -> DSC downloads
NC uploads new - > DSC downloads -> NC uploads new -> DSC uploads new -> NC downloads
NC uploads new - > DSC downloads -> NC moves -> DSC uploads new -> NC downloads

2. DSCs

DSC1 uploads new -> DSC2 moves -> DSC1 downloads -> DSC1 uploads new

3. Pass some of smashbox

https://github.com/owncloud/smashbox/blob/master/lib/test_basicSync.py
https://github.com/owncloud/smashbox/blob/master/lib/test_nplusone.py 
Some more oriented on sharing cases

4. Performance review

I am bit worried on the amount of additional metadata (and data) operations it does. While for user it might not that much matter, it does for admins which pay for infrastructure.

2018-03-03 23:19 UTC, mrow4a commented
For the moment I have to give a red flag for this PR 👎 All the integration tests failed - for many reasons - please find my full delta sync report here https://cloud.owncloud.com/index.php/s/7ARBkhLl4mYunVg @DeepDiver1975 @ahmedammar @PVince81 @guruz @pmaier1 @ckamm

2018-03-03 23:39 UTC, ahmedammar commented
These errors show something not quite right with your setup: “unable to parse zsync file” ... Those should really never happen.

2018-03-03 23:43 UTC, mrow4a commented
Whatever is the setup, it should work.. windows, linux, mac. I should be able to build a client from given branches and run flawlessly.

2018-03-03 23:48 UTC, mrow4a commented
How will you explain, that master branch of client passes the 3 integrations tests, but delta-sync branch fails? I doubt it is my setup in that case

2018-03-03 23:54 UTC, ahmedammar commented
Would have been great if you ran these integration tests months ago when my pull request was made, no idea how stuff has diverged since ... 

All I’m saying is those errors at the validity of the zsync file itself is far from normal. Knowing your setup would help track down and actually fix the problem.

2018-03-03 23:59 UTC, mrow4a commented
What setup details do you have in mind? 
- macoc 10.13.3
- clean installation of https://github.com/ahmedammar/core
- clean build of https://github.com/owncloud/client/tree/delta-sync. Master on client comes from that branch without delta sync commits. 
- Projects/client/src/3rdparty/zsync, zsync git:(3271b60), Author: Ahmed Ammar<ahmed.a.ammar@gmail.com>Date:   Sat Nov 11 21:43:08 2017 +0200

2018-03-04 00:13 UTC, ahmedammar commented
That setup is similar to mine, did you run the unit tests? Where can I find the test script?

2018-03-04 00:14 UTC, mrow4a commented
seems @orzeech had exactly the same problem

2018-03-04 00:20 UTC, mrow4a commented
https://github.com/owncloud/smashbox/blob/master/lib/test_deltamove.py

Make sure that in etc/smashbox.conf you have similar configuration. Additionaly please mind that for master branch,``` oc_sync_cmd = '/Users/mrow4a/Projects/client-build-mac/bin/testpilotcloudcmd --trust --exclude /Users/mrow4a/Projects/client/sync-exclude.lst --deltasync'``` you cannot use flag --`deltasync` since it will fail. I recommend you to test first with master branch of the client. Use also `brew install python2` and ensure you can run `python2` and not `python`.

smashbox git:(delta_test) ✗ cat etc/smashbox.conf
```
oc_account_name = None
oc_account_password = 'test'
oc_account_reset_procedure = 'delete'
oc_account_runid_enabled = False
oc_admin_password = 'admin'
oc_admin_user = 'admin'
oc_check_diagnostic_log = False
oc_check_server_log = False
oc_group_name = None
oc_number_test_groups = 1
oc_number_test_users = 3
oc_root = ''
oc_server = 'localhost/delta'
oc_server_datadirectory = '/var/www/html/owncloud/data'
oc_server_folder = ''
oc_server_log_user = 'www-data'
oc_server_shell_cmd = ''
oc_server_tools_path = 'server-tools'
oc_ssl_enabled = False
oc_sync_cmd = '/Users/mrow4a/Projects/client-build-mac/bin/testpilotcloudcmd --trust --exclude /Users/mrow4a/Projects/client/sync-exclude.lst --deltasync'
oc_sync_repeat = 1
oc_webdav_endpoint = 'remote.php/webdav'
pycurl_verbose = None
rundir_reset_procedure = 'delete'
runid = None
scp_port = 22
smashdir = '/Users/mrow4a/Projects/smashdir'
web_user = 'www-data'
workdir_runid_enabled = False```

Lets move this conversation to the email for details - piotr@owncloud.com

I really like this delta sync work, and I would love to merge the server side of it. Your code quality is very good (for enterprise we would need to optimize it, but for community use it is fine). If we pass these 3 integration test_nplusone, test_deltamove and test_basicSync I happily merge this PR.

2018-03-04 00:27 UTC, mrow4a commented
@ahmedammar 

➜  client-build-mac make test 
Running tests...
Test project /Users/mrow4a/Projects/client-build-mac
      Start  1: OwncloudPropagatorTest
 1/23 Test  #1: OwncloudPropagatorTest ...........   Passed    0.40 sec
      Start  2: UpdaterTest
 2/23 Test  #2: UpdaterTest ......................   Passed    0.04 sec
      Start  3: NetrcParserTest
 3/23 Test  #3: NetrcParserTest ..................   Passed    0.05 sec
      Start  4: OwnSqlTest
 4/23 Test  #4: OwnSqlTest .......................   Passed    0.09 sec
      Start  5: SyncJournalDBTest
 5/23 Test  #5: SyncJournalDBTest ................   Passed    0.07 sec
      Start  6: SyncFileItemTest
 6/23 Test  #6: SyncFileItemTest .................   Passed    0.04 sec
      Start  7: ConcatUrlTest
 7/23 Test  #7: ConcatUrlTest ....................   Passed    0.07 sec
      Start  8: XmlParseTest
 8/23 Test  #8: XmlParseTest .....................   Passed    0.05 sec
      Start  9: ChecksumValidatorTest
 9/23 Test  #9: ChecksumValidatorTest ............   Passed    0.20 sec
      Start 10: ExcludedFilesTest
10/23 Test #10: ExcludedFilesTest ................   Passed    0.04 sec
      Start 11: FileSystemTest
11/23 Test #11: FileSystemTest ...................   Passed    0.04 sec
      Start 12: UtilityTest
12/23 Test #12: UtilityTest ......................   Passed    0.09 sec
      Start 13: SyncEngineTest
13/23 Test #13: SyncEngineTest ...................***Failed    3.83 sec
      Start 14: SyncMoveTest
14/23 Test #14: SyncMoveTest .....................   Passed    3.85 sec
      Start 15: SyncConflictTest
15/23 Test #15: SyncConflictTest .................   Passed    3.88 sec
      Start 16: SyncFileStatusTrackerTest
16/23 Test #16: SyncFileStatusTrackerTest ........***Failed    3.80 sec
      Start 17: ChunkingNgTest
17/23 Test #17: ChunkingNgTest ...................   Passed   56.24 sec
      Start 18: ZsyncTest
18/23 Test #18: ZsyncTest ........................   Passed    9.18 sec
      Start 19: UploadResetTest
19/23 Test #19: UploadResetTest ..................   Passed    3.80 sec
      Start 20: AllFilesDeletedTest
20/23 Test #20: AllFilesDeletedTest ..............   Passed    3.87 sec
      Start 21: FolderWatcherTest
21/23 Test #21: FolderWatcherTest ................   Passed    0.73 sec
      Start 22: FolderManTest
22/23 Test #22: FolderManTest ....................   Passed    0.58 sec
      Start 23: OAuthTest
23/23 Test #23: OAuthTest ........................   Passed    5.88 sec

91% tests passed, 2 tests failed out of 23

2018-03-04 07:33 UTC, ckamm commented
I cannot reproduce "unable to parse zsync file”. But I do see 400 replies to MOVE requests. On first look it seems like the MOVE is triggered too early. This was testing a 20 000 000 bytes file being increased in size by 1 000 000 bytes:

```
03-04 08:08:52:167 [ info sync.networkjob.zsync.put ]:	Done reading: "deltatest2.txt" 95.0% of target seeded.
03-04 08:08:52:167 [ debug sync.networkjob.zsync.put ]	[ OCC::PropagateUploadFileNG::slotZsyncSeedFinished ]:	Number of ranges: 1
03-04 08:08:52:167 [ debug sync.networkjob.zsync.put ]	[ OCC::PropagateUploadFileNG::slotZsyncSeedFinished ]:	Total bytes: 2048576

03-04 08:08:52:125 [ info sync.accessmanager ]: 6 "MKCOL" "http://localhost/remote.php/dav/uploads/admin/3495531370" has X-Request-ID "19ffe157-3619-4dc4-bd13-113670592261"
03-04 08:08:52:230 [ info sync.networkjob.mkcol ]:      MKCOL of QUrl("http://localhost/remote.php/dav/uploads/admin/3495531370") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
03-04 08:08:52:230 [ info sync.accessmanager ]: 3 "" "http://localhost/remote.php/dav/uploads/admin/3495531370/0000000019922944" has X-Request-ID "15099e25-6d4b-4351-b06e-d3ab881f73cb"
03-04 08:08:52:289 [ info sync.accessmanager ]: 3 "" "http://localhost/remote.php/dav/uploads/admin/3495531370/.zsync" has X-Request-ID "c52f11cd-365b-46c6-a3eb-50608ed53118"
03-04 08:08:52:338 [ info sync.networkjob.put ]:        PUT of "http://localhost/remote.php/dav/uploads/admin/3495531370/0000000019922944" FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) "" QVariant(int, 201) QVariant(QString, "Created")
03-04 08:08:52:338 [ info sync.propagator.upload ]:	Chunked upload of 1048576 bytes took 109 ms, desired is 60000 ms, expected good chunk size is 577197798 bytes and nudged next chunk size to  100000000 bytes
03-04 08:08:52:339 [ info sync.accessmanager ]: 3 "" "http://localhost/remote.php/dav/uploads/admin/3495531370/0000000020000000" has X-Request-ID "a6913337-7291-4f9d-b74f-1e0ccbc5f732"
03-04 08:08:52:391 [ info sync.networkjob.put ]:        PUT of "http://localhost/remote.php/dav/uploads/admin/3495531370/.zsync" FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) "" QVariant(int, 201) QVariant(QString, "Created")

Move starts before the second chunk PUT is done:
03-04 08:08:52:391 [ info sync.accessmanager ]: 6 "MOVE" "http://localhost/remote.php/dav/uploads/admin/3495531370/.file.zsync" has X-Request-ID "54201d6c-d7b3-4edc-9ceb-d6611c93a09a"
03-04 08:08:52:591 [ warning sync.networkjob ]: QNetworkReply::NetworkError(ProtocolInvalidOperationError) "Server replied \"400 Bad Request\" to \"MOVE http://localhost/remote.php/dav/uploads/admin/3495531370/.file.zsync\"" QVariant(int, 400)
03-04 08:08:52:591 [ info sync.networkjob.move ]:       MOVE of QUrl("http://localhost/remote.php/dav/uploads/admin/3495531370/.file.zsync") FINISHED WITH STATUS QNetworkReply::NetworkError(ProtocolInvalidOperationError) "Server replied \"400 Bad Request\" to \"MOVE http://localhost/remote.php/dav/uploads/admin/3495531370/.file.zsync\""
03-04 08:08:52:591 [ debug sync.propagator.upload ]	[ OCC::PropagateUploadFileCommon::commonErrorHandling ]:	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\BadRequest</s:exception>\n  <s:message>Chunks on server do not sum up to 2048925 but to 1048925</s:message>\n</d:error>\n"
03-04 08:08:52:592 [ info sync.networkjob.put ]:        PUT of "http://localhost/remote.php/dav/uploads/admin/3495531370/0000000020000000" FINISHED WITH STATUS QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid) QVariant(Invalid)
```

Also the chunk sizing is odd. From the logs it looks like this is what happens meaning that chunks overlap:
```
chunk 1: start 19922944, size 1048576, computed end: 20971520
chunk 2: start 20000000 unknown size/end
```
And the server seems to expect 2048925 bytes, so 1024*1024 + 1 000 000; but that plus 19922944 doesn't add up to the expected 21 000 000.

I can look at this more on Monday.

2018-03-04 10:06 UTC, mrow4a commented
This one looks interesting also `03-03 21:06:29:413 [ fatal default ]: ASSERT: "_jobs.isEmpty()" in file /Users/mrow4a/Projects/client/src/libsync/propagateuploadng.cpp, line 490` @ckamm

2018-03-06 11:58 UTC, ckamm commented
I expect to have the upload issues fixed with the owncloud/client#6382 PR - that would also cover the assert failure you mentioned.

2018-03-11 15:40 UTC, mrow4a commented
@DeepDiver1975 @PVince81 I did another round of tests - it passes test_deltamove.py in smashbox, and this is enough for me to confirm that delta works correctly and as expected.

Things still not working as of https://github.com/owncloud/client/pull/6382 : 

- conflicts
- performance/reliability for larger installations (needs a bit of work there)
- might not work in some environments, lets see community input

Please bring this baby in 👍

2018-03-12 11:34 UTC, DeepDiver1975 approved these changes

2018-03-12 11:35 UTC, merged

2019-03-20 11:02 UTC, guruz commented
This feature will be in the upcoming 2.6 alpha release.
Meanwhile you can try it inside the daily builds 2.6.x https://download.owncloud.com/desktop/daily/