Disable nginx buffering for file downloads
owncloud/core pull request #29400
Opened 2017-10-31 12:12 UTC by jvillafanez

## Description
nginx buffering seems to be causing memory problems while a big file download is happening (big file upload hasn't been checked). The memory usage of the nginx process (not the php-fpm) keeps growing which might crash the server at some point depending on the file size and the memory available in the server.

Note that this behaviour isn't present in apache or in nginx without buffering the response

## Related Issue
https://github.com/owncloud/core/issues/29328

## Motivation and Context
This solution should disable the nginx buffering only for file downloads. The rest of the operation should behave normally depending on the specific nginx configuration.
While modifying the nginx configuration should be possible, it might be complex to disable just the buffering for file downloads, so you might disable the it for the whole server or for a specific location context.

## How Has This Been Tested?
Tested manually with a 4.4GB file (check https://github.com/owncloud/core/issues/29328#issuecomment-340718926 for set up)

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@DeepDiver1975 @PVince81 To be decided if this will be the solution. Not happy to include server-specific code but it's probably the easiest solution.

2017-10-31 14:46 UTC, mmattel commented
@PVince81 @jvillafanez 
👍 
Approved, works, see https://github.com/owncloud/core/issues/29328#issuecomment-340784009
Please restart the check.
I propose backporting.
Thanks a lot !

2017-10-31 15:05 UTC, jvillafanez commented
Backport to stable10 in https://github.com/owncloud/core/pull/29403

2017-11-02 12:02 UTC, DeepDiver1975 requested changes
Squash please - otherwise 👍

2017-11-02 15:16 UTC, PVince81 approved these changes
:+1:

2017-11-02 15:17 UTC, merged