Migrating mysql php 7.0 job from jenkins to drone
owncloud/core pull request #29409
Opened 2017-11-02 08:46 UTC by SergioBertolinSG

2017-11-02 08:49 UTC, DeepDiver1975 requested changes

2017-11-02 08:49 UTC, DeepDiver1975 commented on .drone.yml
> +      DB_TYPE: mysql
which mysql version is used on drone? we have to be care full to choose an older version which does not automatically enable mb4

2017-11-02 09:03 UTC, SergioBertolinSG commented on .drone.yml
> +      DB_TYPE: mysql
5.7

2017-11-02 09:19 UTC, DeepDiver1975 commented on .drone.yml
> +      DB_TYPE: mysql
Jenkins is currently running 5.5 - 5.7 is the version to be used with mb4 ...
https://github.com/owncloud/core/blob/master/build/autotest.sh#L228

2017-11-02 09:20 UTC, DeepDiver1975 commented on .drone.yml
> +      DB_TYPE: mysql
Please also incorporate these settings in the server - this will give us faster execution times - https://github.com/owncloud/core/blob/master/tests/docker/mariadb/oc.cnf

but lets first see how long it takes without

2017-11-02 09:22 UTC, SergioBertolinSG commented on .drone.yml
> +      DB_TYPE: mysql
Ok, should I migrate the mb4 stage in this PR as well or in a different one?

2017-11-02 09:27 UTC, DeepDiver1975 commented on .drone.yml
> +      DB_TYPE: mysql
mb4 into a pr of its own please

2017-11-02 09:27 UTC, DeepDiver1975 commented on .drone.yml
> +      DB_TYPE: mysql
THX

2017-11-03 10:17 UTC, DeepDiver1975 approved these changes

2017-11-03 10:19 UTC, merged