[Central group table] Check for sub admin privileges rather then sub admin
owncloud/core pull request #29453
Opened 2017-11-05 18:34 UTC by mrow4a

As in the title

2017-11-05 18:41 UTC, mrow4a commented on lib/private/SubAdmin.php
>  	public function isSubAdmin(IUser $user) {
I bumped on this when changing the code. Having hidden knowledge of admin (which during setup is not subadmin physically - https://github.com/owncloud/core/blob/master/lib/private/Setup.php#L363) is subadmin is super confusing..

2017-11-05 18:43 UTC, mrow4a commented on lib/private/legacy/api.php
> -					$admin = OC_User::isAdminUser($user);
I also removed one fency query here.

2017-11-06 09:56 UTC, DeepDiver1975 requested changes

2017-11-06 09:56 UTC, DeepDiver1975 commented on lib/private/legacy/user.php
> +	public static function hasSubAdminPrivileges($uid) {
👎 this is a legacy class - never add new functionality into a legacy class

2017-11-06 09:58 UTC, mrow4a commented on lib/private/legacy/user.php
> +	public static function hasSubAdminPrivileges($uid) {
The other option is to just add admin user as subadmin of admin group

2017-11-06 10:51 UTC, mrow4a commented on tests/lib/SubAdminTest.php
> +		$this->assertEmpty($subAdmin->getSubAdminsGroups($this->users[0]));
The above problem will be addressed with https://github.com/owncloud/core/pull/29107 @DeepDiver1975

2017-11-06 10:53 UTC, mrow4a commented on tests/lib/SubAdminTest.php
> +		$this->assertEmpty($subAdmin->getSubAdminsGroups($this->users[0]));
This situation won't be possible with foreign keys

2017-11-07 14:03 UTC, PVince81 commented on settings/Application.php
> -		$container->registerService('IsSubAdmin', function(IContainer $c) {
you'll likely need to alias this in case apps are using this ?

2017-11-07 14:19 UTC, mrow4a commented on settings/Application.php
> -		$container->registerService('IsSubAdmin', function(IContainer $c) {
I will PR new version based on chat with you. I will remove these two services with FIXME

2017-11-07 18:18 UTC, mrow4a commented on settings/Application.php
> +				$c->query('GroupManager'),
@PVince81 I took this approach

2017-11-07 18:18 UTC, mrow4a commented on settings/Application.php
> -		/** FIXME: Remove once OC_User is non-static and mockable */
fixed FIXME @PVince81 @DeepDiver1975

2017-11-14 08:07 UTC, mrow4a commented
Any input here

2017-11-14 08:16 UTC, mrow4a commented on settings/Application.php
> -		/** FIXME: Remove once OC_User is non-static and mockable */
Is it proper way to fix it @PVince81 @DeepDiver1975  ?

2017-11-15 10:40 UTC, mrow4a commented on settings/Application.php
> -				$c->query('IsAdmin'),
Removed workaround from FIXME block @DeepDiver1975 @PVince81

2017-11-15 10:40 UTC, mrow4a commented on settings/Application.php
> -				$c->query('IsSubAdmin')
Removed workaround from FIXME block @DeepDiver1975 @PVince81

2017-11-15 10:40 UTC, mrow4a commented on settings/Application.php
> -				$c->query('IsAdmin'),
Removed workaround from FIXME block @DeepDiver1975 @PVince81

2017-11-24 07:43 UTC, DeepDiver1975 requested changes

2017-11-24 07:43 UTC, DeepDiver1975 commented on tests/Settings/Controller/UsersControllerTest.php
> +		$this->container['GroupManager']
move this to the setUp() method - seems to be identical for all tests

2017-11-24 07:43 UTC, DeepDiver1975 commented on lib/private/legacy/api.php
> +					if (OC_User::isAdminUser($user)) {
Can we implement this please without using OC_User

2017-11-24 07:45 UTC, DeepDiver1975 commented
And please fix code coverage - some code paths are not yet covered ....

2017-11-27 12:02 UTC, mrow4a commented on lib/private/legacy/api.php
> +					if (OC_User::isAdminUser($user)) {
Unfortunetely not, since this fancy thing has to check for incognito mode, and there is no other way to retrieve it

2017-11-27 12:27 UTC, mrow4a commented on tests/Settings/Controller/UsersControllerTest.php
> +		$this->container['GroupManager']
Unfortunetelly, in some test false is returned, look testDestroyNotAccessibleToSubAdmin

2017-11-28 12:44 UTC, mrow4a commented
As mentioned above, not much can be done with code coverage, as it is legacy code.

2017-11-28 12:46 UTC, mrow4a commented
@PVince81 are you aware of any app which can use `->isSubAdmin`, assuming the admin account is also subadmin, instead of checking for admin additionaly?

2017-11-28 15:09 UTC, PVince81 commented
grep in local workspace shows these:
```
apps3/side/customgroups/lib/Service/MembershipHelper.php|306| || $this->groupManager->getSubAdmin()->isSubAdmin($this->userSession->getUser())
apps3/side/customgroups/tests/unit/Service/MembershipHelperTest.php|413| ->method('isSubAdmin')
apps3/side/customgroups/build/customgroups/lib/Service/MembershipHelper.php|358| || $this->groupManager->getSubAdmin()->isSubAdmin($this->userSession->getUser())
apps3/side/impersonate/controller/settingscontroller.php|98| $this->subAdmin->isSubAdmin($this->userSession->getUser())]);
apps3/side/impersonate/controller/settingscontroller.php|163| if($this->subAdmin->isSubAdminofGroup($this->userSession->getUser(), $this->groupManager->get($group))) {
apps3/side/impersonate/tests/controller/settingscontrollertest.php|181| ->method('isSubAdminofGroup')
```

2017-11-28 15:14 UTC, mrow4a commented
Ok, will have a look.. I just hope they don't work on this assumption and check for admin additionally.

2017-11-30 08:57 UTC, DeepDiver1975 commented
- [ ] get coverage in shape - basically a unit test for this is missing https://codecov.io/gh/owncloud/core/pull/29453/src/lib/private/Group/Manager.php

2017-11-30 09:00 UTC, DeepDiver1975 approved these changes

2017-11-30 09:00 UTC, DeepDiver1975 commented
@PVince81 I'm okay with this - please approve as well - THX

2017-11-30 14:08 UTC, mrow4a commented
@PVince81 Confirmed, and programers of impersonate and custom groups were careful enough not to look into internal implementation, and follow the interface:

- [x] Impersonate - https://github.com/owncloud/impersonate/blob/master/controller/settingscontroller.php#L101-L103
- [x] Impersonate - https://github.com/owncloud/customgroups/blob/master/lib/Service/MembershipHelper.php#L303-L306

2017-11-30 15:19 UTC, PVince81 approved these changes
:+1:

2017-11-30 19:16 UTC, merged