Moved postgresql job from jenkins to drone
owncloud/core pull request #29456
Opened 2017-11-06 09:19 UTC by SergioBertolinSG

@DeepDiver1975 do we need also to test with the previous version of postgres? (9.6)

2017-11-06 09:32 UTC, SergioBertolinSG commented
Drone error

```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "oc_storages_numeric_id_...
```

Which is the expected from https://github.com/owncloud/core/issues/29342

2017-11-07 13:06 UTC, DeepDiver1975 requested changes

2017-11-07 13:06 UTC, DeepDiver1975 commented on .drone.yml
> +    image: postgres:10.0
Jenkins is testing against 9.4 - please use that version.
especially since we know that postgres 10 is having trouble

2017-11-08 08:24 UTC, SergioBertolinSG commented
@DeepDiver1975 ready to go?

2017-11-09 09:17 UTC, DeepDiver1975 approved these changes

2017-11-09 09:17 UTC, merged

2017-11-10 01:29 UTC, phil-davis commented
Backport stable10 #29517