add unit test for group commands
owncloud/core pull request #29513
Opened 2017-11-09 07:08 UTC by karakayasemi

## Motivation and Context

More code coverage
## How Has This Been Tested?

 SQLite and MySQL

## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2017-11-09 09:38 UTC, DeepDiver1975 requested changes
as discussed on irc yesterday - please use the command tester - https://github.com/owncloud/core/blob/master/tests/Core/Command/Apps/AppsDisableTest.php

Thanks a lot!

2017-11-09 09:38 UTC, DeepDiver1975 commented on tests/Core/Command/Group/AddMemberTest.php
> + * @copyright Copyright (c) 2017, ownCloud, Inc.
GmbH

2017-11-09 19:31 UTC, karakayasemi commented
@DeepDiver1975  Command tester is really good to use. I rewrote it all of them by using the command tester.

2017-11-10 07:16 UTC, DeepDiver1975 requested changes

2017-11-10 07:16 UTC, DeepDiver1975 commented on tests/Core/Command/Group/AddMemberTest.php
> +        \OC::$server->getUserManager()->createUser('user2', 'password');
You can use the User trait - https://github.com/owncloud/core/blob/master/apps/dav/tests/unit/Command/CleanupChunksTest.php#L40
This gives you some short cuts like https://github.com/owncloud/core/blob/9fd116cedf00cf4520c72dd696dc0e02b9501660/apps/dav/tests/unit/Command/CleanupChunksTest.php#L71-L72

2017-11-10 12:43 UTC, karakayasemi commented
Is there a problem in Jenkins? or something is wrong with PR

2017-11-10 13:04 UTC, DeepDiver1975 commented
Jenkins needs restart

2017-11-10 16:49 UTC, DeepDiver1975 commented
> Jenkins needs restart

job restarted

2017-11-10 16:50 UTC, DeepDiver1975 approved these changes

2017-11-10 18:14 UTC, DeepDiver1975 commented
Just rebased to make use of jobs running on drone

2017-11-10 20:09 UTC, merged

2017-11-10 20:10 UTC, DeepDiver1975 commented
@karakayasemi THX a lot! Can I ask you to backport this to stable10? THX

2017-11-11 12:06 UTC, DeepDiver1975 commented
backport open