[WIP] Migrating oracle unit tests job from jenkins to drone
owncloud/core pull request #29534
Opened 2017-11-10 14:31 UTC by SergioBertolinSG

Work in progress

Pending:
- [ ] Add oci Extension to PHP dockers.
- [ ] Remove the start/stop of oracle container in unit test execution.

2017-12-12 13:37 UTC, DeepDiver1975 commented
@ownclouders rebase

2017-12-12 13:45 UTC, DeepDiver1975 commented
@ownclouders rebase

2017-12-12 13:57 UTC, ownclouders commented
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

2017-12-12 13:57 UTC, ownclouders commented
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

2017-12-12 13:57 UTC, ownclouders commented
Automated rebase was successful!

2017-12-12 16:38 UTC, DeepDiver1975 requested changes

2017-12-12 16:38 UTC, DeepDiver1975 commented on tests/drone/test-phpunit.sh
> +      wait-for-it oracle:1521
this is also not enough - the port will be available pretty early - but during the init phase the database will throw an error back .... see build/autotest.sh here as well

2017-12-12 17:40 UTC, SergioBertolinSG commented on tests/drone/test-phpunit.sh
> +      wait-for-it oracle:1521
OK. I'm trying to use sqlplus but the loop doesn't end:

```bash
      DATABASEUSER=autotest
      DATABASENAME='XE'
      for i in {1..48}
          do
              if "${SQLPLUS}" "${DATABASEUSER}/owncloud@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=$DATABASEHOST)(Port=1521))(CONNECT_DATA=(SID=XE)))" < /dev/null | grep 'Connected to'; then
                  break;
              fi
              sleep 5
          done
```

is that line with the connection correct?

2017-12-12 17:56 UTC, SergioBertolinSG commented on tests/drone/test-phpunit.sh
> +      wait-for-it oracle:1521
Is that really needed? We don't have it in mysql and oracle tests here have passed just checking the port.

2017-12-14 07:47 UTC, DeepDiver1975 commented on tests/drone/test-phpunit.sh
> +      wait-for-it oracle:1521
mysql !== oracle

2017-12-14 07:50 UTC, DeepDiver1975 approved these changes

2017-12-14 07:50 UTC, merged

2018-01-08 15:33 UTC, PVince81 commented
backport to stable10?

2018-02-03 15:58 UTC, phil-davis commented
Backport stable10 #30066