Testing /remote.php/dav/meta/$fileId/v
owncloud/core pull request #29637
Opened 2017-11-20 19:12 UTC by DeepDiver1975

## Description
Follow up of https://github.com/owncloud/core/pull/29488
This PR will add more integration tests for the meta dav resource

## How Has This Been Tested?
using behat

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-11-21 08:19 UTC, SergioBertolinSG requested changes

2017-11-21 08:19 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
What is doing this step?

We have functions to get the id of a file, maybe adding this extension rdx/behat-variables can be avoided.

Here we use a variable to store file id:
https://github.com/owncloud/core/blob/master/tests/integration/features/webdav-related-new-endpoint.feature#L358

To get the file id we can use this function:
https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/WebDav.php#L1141

2017-11-21 08:19 UTC, SergioBertolinSG commented on tests/integration/features/bootstrap/WebDav.php
> +	 * @When user :user restores version nr :versionIndex of file :path
"nr" means number? then it should be "number", no need to put "nr".

2017-11-21 08:23 UTC, DeepDiver1975 commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
Ah - didn't know that .... but this is causing another request to the server. Good? bad? ...

2017-11-21 08:24 UTC, DeepDiver1975 commented on tests/integration/features/bootstrap/WebDav.php
> +	 * @When user :user restores version nr :versionIndex of file :path
Sounds reasonable - will adjust ... or maybe even code different

2017-11-21 09:54 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
I think it is better than adding another dependency.

2017-11-21 10:06 UTC, DeepDiver1975 commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
But I think this step is incomplete 'And user "user0" stores id of file "/textfile0.txt"'

How to save multiple file ids? How to check multiple fileids in follow up steps?

2017-11-21 10:07 UTC, DeepDiver1975 commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
Furthermore I explicitly need to reference the fileid in the url in a later step

```
  Scenario: User cannot access meta folder of a file which is owned by somebody else
    Given user "user1" exists
    And user "user0" uploads file with content "123" to "/davtest.txt"
    And we save it into "FILEID"
    And as an "user1"
    When sending "PROPFIND" with exact url to "/remote.php/dav/meta/<<FILEID>>"
    Then the HTTP status code should be "404"

2017-11-21 10:43 UTC, SergioBertolinSG commented on tests/integration/features/dav-versions.feature
> +    And we save it into "FILEID"
> How to save multiple file ids? How to check multiple fileids in follow up steps?

Currently only works with one.

About the following steps, you could add a new step like

When getting metadata of last file id stored

And keep the last part about the http status.

2017-11-21 10:50 UTC, DeepDiver1975 commented
> When getting metadata of last file id stored
> 
> And keep the last part about the http status.

but then I have to code a hell of new steps vs. re-using an existing step and get simple string interpolation.

I'm not convinced ...

2017-11-21 10:55 UTC, SergioBertolinSG commented
OK, add the dependency then, maybe we can use it in the future.

The problem could be if we upgrade behat version at some point and somehow this extension doesn't work with the newer version, making us fixing it upstream or having to remove it.

2017-11-21 11:29 UTC, SergioBertolinSG requested changes

2017-11-21 11:29 UTC, SergioBertolinSG commented on tests/integration/features/bootstrap/WebDav.php
> +	public function userRestoresVersionNrOfFile($user, $versionIndex, $path) {
The function name has the old name.

2017-11-21 11:32 UTC, DeepDiver1975 commented on tests/integration/features/bootstrap/WebDav.php
> +	public function userRestoresVersionNrOfFile($user, $versionIndex, $path) {
k - will adjust .... but it actually has no meaning - right?

2017-11-21 11:33 UTC, DeepDiver1975 commented on tests/integration/features/bootstrap/WebDav.php
> +	public function userRestoresVersionNrOfFile($user, $versionIndex, $path) {
I mean the function is detected by the regex in the phpdoc - unlike ruby/cucumber where the function name is used .... anyway

2017-11-21 11:37 UTC, SergioBertolinSG commented on tests/integration/features/bootstrap/WebDav.php
> +	public function userRestoresVersionNrOfFile($user, $versionIndex, $path) {
Yes, just a cosmetic change.

2017-11-21 13:08 UTC, DeepDiver1975 commented on tests/integration/features/bootstrap/WebDav.php
> +	public function userRestoresVersionNrOfFile($user, $versionIndex, $path) {
done

2017-11-21 13:10 UTC, SergioBertolinSG approved these changes

2017-11-22 07:38 UTC, merged

2018-02-08 02:55 UTC, phil-davis commented
@DeepDiver1975 @SergioBertolinSG should these tests be backported?

I noticed because I am looking at ``composer.json`` diffs between ``master`` and ``stable10``.

2018-02-08 10:26 UTC, DeepDiver1975 commented
> @DeepDiver1975 @SergioBertolinSG should these tests be backported?
> 
> I noticed because I am looking at composer.json diffs between master and stable10.

yes please

2018-02-08 10:29 UTC, phil-davis commented
Assigned myself so I find this again. I will backport after the latest composer PR in stable10 gets merged (no point backporting now when I know there will be more conflict to come)

2018-03-21 02:58 UTC, phil-davis commented
See discussion in #30429 - backport here is waiting on/dependent on if other related meta dav stuff is backported. Leaving backport label here for now, so it gets noticed every now and then.

2018-06-12 11:31 UTC, phil-davis commented
This code is all backported in #31050 which has been merged. Removing the backport-request label.