[WIP] Add new symfony dispatcher events
owncloud/core pull request #29651
Opened 2017-11-22 15:36 UTC by sharidas

Add new symfony dispatcher events

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Add new symfony dispatcher events

## Related Issue

https://github.com/owncloud/core/issues/29174

## Motivation and Context

Adding more symfony dispatcher events.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-11-23 13:58 UTC, PVince81 reviewed
See my comments above.

I wonder whether it's possible for event dispatcher to first ask whether there is any listener before retrieving potentially expensive operation.

2017-11-23 13:58 UTC, PVince81 commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
Did you check whether we could trigger the dispatcher directly inside of basicOperation ?
I'd like to avoid having an extra call to `getFileInfo` for the events because it will cause more DB calls even if no listener is created. Please check whether basicOperation already has the file info object available somewhere for reuse.

also we used to have pre and post hooks, would be good to also have those as dispatcher event. Goal is that at some time in the future these could replace the old hooks, so we need to be close to the original functionality.

2017-11-23 13:58 UTC, PVince81 commented on lib/private/Files/View.php
> +			$this->eventDispatcher->dispatch('\OC\Filesystem::delete_completed', $event);
is there a pre-delete event ?

maybe let's settle on names, howabout beforeDelete, afterDelete ? beforeCreate, afterCreate ?

@DeepDiver1975 thoughts ?

2017-11-23 13:58 UTC, PVince81 commented on lib/private/Files/View.php
> +			$event->setArgument('path', $path);
if we have file info we likely don't need the path as it's already contained inside the file info object

2017-11-23 13:58 UTC, PVince81 commented on lib/private/Files/View.php
> +				$this->logger->warning(__METHOD__ . " failed to retrieve file info for $path");
if we don't log the exception we'll never know what really happened there... we have `$this->logger->logException()`

2017-11-23 14:17 UTC, sharidas commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
Unfortunately I couldn't find call to `getFileInfo` at basicOperation or FileInfo object. This was bothering me too as each call becomes expensive, whether there are listeners or not :(

Sure I will add post and pre events.

2017-11-23 15:56 UTC, PVince81 commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
Hmmm that's sad then. As an alternative we could rather pass in the file id only and let the listener get the file info by themselves. The question is how to get it in an efficient manner.

The public API states that one should use `\OC::$server->getUserFolder()->getById($fileId)` but that's a rather expensive call. The other alternative would be to inject the `View` and the `$path` and let the subscriber resolve it. However the `View` is not supposed to be public API...

bringing in @jvillafanez for further ideas

2017-11-24 08:15 UTC, DeepDiver1975 requested changes

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +	private $eventDispatcher;
PHPDoc

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +	private $logger;
PHPDoc

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +			$this->eventDispatcher->dispatch('\OC\Filesystem::delete_completed', $event);
agreed - sounds great

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::read_completed', $event);
this is not read_completed but beforeRead

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
@PVince81 I'd expect here to have OCP namespace .....

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
but we might want to stick to the symfony event naming convention? see https://symfony.com/doc/current/components/event_dispatcher.html#naming-conventions

2017-11-24 08:15 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
should we fully kill the emitter concept as we are working on this as of now? All emitter interfaces never hit the public api - we can kill it right away @PVince81 thoughts

2017-11-24 08:39 UTC, sharidas commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::read_completed', $event);
I wanted to make the call after basicOperation. So after the call to basicOperation its read_completed. I will update the PR accordingly.

2017-11-24 08:49 UTC, PVince81 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
> All emitter interfaces never hit the public api

Really ? I remember that @patrickjahns's example app was using the emitter events from the public files Node API. I'm sure other apps do so to.

Once we have symfony events for everything, we can first deprecate all hooks and emitter events and give app devs time to migrate. Only then we can kill these completely.

2017-11-24 08:51 UTC, PVince81 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
ok, so change the format again ? we already settled on this OC namespace + event id for many other events.

Anyway, I'm ok switching convention now as I prefer to refer to documented stuff.

> I'd expect here to have OCP namespace

This would imply that there are also private symfony events. Not sure if we want private events any more ?

2017-11-24 08:55 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
emitters are private - we can kill them right away
hooks is a different story - yes

2017-11-24 08:59 UTC, PVince81 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
Ok, so emitters that are triggering events from a private object (`\OC` namespace) could be replaced with using symfony events. But this is out of scope for this PR.

The purpose of this PR is to add new events without causing any regressions.
Killing/replacing anything will require careful regression testing and potentially adding new tests where tests are missing.

2017-11-24 09:01 UTC, PVince81 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
Raised here https://github.com/owncloud/core/issues/29672

2017-11-24 09:23 UTC, sharidas commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
@DeepDiver1975 @PVince81  how about "ocp_iusermanager.beforeCreate" for https://github.com/owncloud/core/blob/master/lib/private/User/Manager.php#L323 ( as an example )?
Instead of using namespace with slashes "/" use "_" and all letters remain in small case as per document.

2017-11-24 09:40 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +					$event = new GenericEvent(null, ['user' => $this]);
from an implementation point of view - this can help to streamline the code base and avoid duplications:

```php
private emittingCall(\Closure $fn, $class, $eventName) {
    $this->eventDispatcher->dispatch("$class::before$eventName");
    $result = $fn();
    $this->eventDispatcher->dispatch("$class::after$eventName");
    return $result;
}

// within the implementation of e.g. create user

private function createUser() {
    return emittingCall( function() use($userManager) {
        return $userManager->createUser();
    }, '\OCP\IUserManager', 'create');
}

2017-11-24 10:21 UTC, karakayasemi commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
IMHO, we can add all the events name as a constant of the relevant class. For example in the \OCP\User class we can add
```php
const EventCreate = 'ocp_user.create';
const EventDelete = 'ocp_user.delete';
```
In this way we can access it via \OCP\User::EventCreate or directly event name string. It also makes easier to find the class events for developers.

2017-11-24 12:44 UTC, PVince81 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
"iusermanager" here doesn't make sense. Whoever is listening to the event shouldn't need to know where the event come from. The only thing a listener is interested in is the type of event and what it applies to.

So I think I prefer "user.beforeCreate" and "user.afterCreate". This makes it clear that it's about a user being created or deleted. What component of ownCloud does it (user manager or whatever) doesn't matter. And I don't like ocp when used this way.

2017-11-24 12:45 UTC, PVince81 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
Regarding the constants, I'm not even sure whether we should have the constants directly in the `\OCP\User` object. Should we have a more global location for all user and group management related event constants ? Depending on specific classes feels too close to the old emitter pattern.

2017-11-28 07:50 UTC, jvillafanez commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
What about using custom events instead of the default one? The custom event could have the `View` object inside (or any other needed dependency) and provide custom methods to access to the object depending on what we want to expose.
(Info in https://symfony.com/doc/current/components/event_dispatcher.html#creating-an-event-class)

2017-11-28 08:25 UTC, sharidas commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
@DeepDiver1975 @PVince81 So with the current state of the patch, if we add a custom event as per @jvillafanez , then we can send `View` object and `$path1` and/or `$path2`. And in the trait, for `before` and `after` events we can use the data from this custom event. And the subscriber of the event would resolve it.

2017-11-28 09:05 UTC, sharidas commented
@DeepDiver1975 @butonic Thoughts regarding  ( discussed the same with @PVince81 
 ) https://github.com/owncloud/core/issues/29174#issuecomment-347457541

2017-11-28 09:22 UTC, PVince81 commented on lib/private/Files/View.php
> +		$this->eventDispatcher->dispatch('\OC\Filesystem::create', $event);
`View` is considered private API. If we were to pass something it would need to be the current folder from  `getUserFolder()->get($path)` which is likely expensive to resolve. Note that said folder is from the `\OCP\Files\Node` interface which itself implements/embeds the `FileInfo`.

2017-12-11 14:18 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +			'before' => ['path' => $this->fileView->getAbsolutePath($this->path)],
store the result of getAbsolutePath into a variable instead of calling it twice ? not sure how expensive the actual call is

2017-12-11 14:19 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +				\OC::$server->getEventDispatcher()->dispatch('file.create.allowed', $event);
what does "allowed" mean here ?

didn't we agree on using something like "file.beforeCreate" and "file.afterCreate" ?

2017-12-11 14:20 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +			$event->setArgument('run', $run);
if $run is modified by the listener, you need to read out the modified value again from the event object

2017-12-11 14:20 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +			$event->setArgument('run', $run);
better add a test for this: if a dispatcher listener sets the run value to false, then the main method will also return false

2017-12-11 14:21 UTC, PVince81 commented on lib/private/Server.php
> +				\OC::$server->getEventDispatcher()->dispatch('\OC\User\Manager::createUser', $event);
let's use `user.beforeCreate` and `user.afterCreate` here

2017-12-11 14:21 UTC, PVince81 commented on lib/private/Server.php
> +					\OC::$server->getEventDispatcher()->dispatch('user.afterfeaturechange.data', $event);
I see you still have the ".data" mode here, I guess you didn't want to modify this until the file one got reviewed ?

2017-12-11 14:23 UTC, PVince81 reviewed
Some small changes needed for the file hooks especially the part about the `$run` logic.

Seems you haven't touched the user manager yet, please adjust afterwards to use the same patterns.

2017-12-11 14:40 UTC, DeepDiver1975 commented
has conflicts

2017-12-12 15:03 UTC, sharidas commented
> Seems you haven't touched the user manager yet, please adjust afterwards to use the same patterns.
Guess this change got missed for review: https://github.com/owncloud/core/pull/29651/files#diff-2ad387ea4134715ffda3bb0f12140f91R293

2017-12-14 09:16 UTC, PVince81 commented on apps/dav/tests/unit/Connector/Sabre/FileTest.php
> +			$this->assertInstanceOf(Exception::class, $e);
is there no specific exception for this ?

Also use `@expectedException` in the PHPDoc for PHPUnit to check for this exception.
The problem with this code is that if the exception is not thrown at all the test still passes, so would need an additional check, or have the assert outside... Best is to use `@expectedException` instead in this situation with the proper exception class name. There is also a tag for the exception message if that makes sense.

2017-12-14 09:17 UTC, PVince81 commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeCreate', $event);
here you also forgot to check the value of `$run`. Please recheck all occurrences for this logic.

2017-12-14 09:17 UTC, PVince81 commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeUpdate', $event);
re-read the last value of `$run` from the argument.

Now I find it strange that the value doesn't seem to be used below and is just passed again...

2017-12-14 09:19 UTC, PVince81 commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeUpdate', $event);
so I suggest to just re-read the value from the event argument to keep the old logic working as it was before...

2017-12-14 09:21 UTC, PVince81 commented on tests/lib/Events/EventEmitterTraitTest.php
> +			array_push($calledAfterEvent, $event);
why not just use `$calledAfterEvent[] = $event` to push to array ? changing the code style in the middle looks weird.

same comment applies to all other `array_push` locations

2017-12-14 09:21 UTC, PVince81 reviewed
Looks better, getting close. Please check my latest comments.

2017-12-14 10:08 UTC, sharidas commented on apps/dav/tests/unit/Connector/Sabre/FileTest.php
> +			$this->assertInstanceOf(Exception::class, $e);
Indeed it does have exception \Sabre\DAV\Exception. There was a failure observed when I tried with `@expectedException`. Yesterday I spent sometime with the same. The error of exception failure was observed only in Jenkins. Where as when I used `@expectedException` in local machine it never caused a problem. Yes I used `@expectExceptionMessage` for message in the same version of the PR which had `@expectedException`.

2017-12-15 15:31 UTC, sharidas commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeUpdate', $event);
I did verified with file operations like create, modify/update, delete, rename operations in web ui. At least in that context no damage happened. The problem might appear, when the event listener alters `$run` value. But as of now the alteration happens only in tests so, I guess we are safe for now. @PVince81 Let me know if this change looks ok. If you really feel that just re-read value is sufficient, then I can do that.

2017-12-15 15:41 UTC, PVince81 commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeUpdate', $event);
Please just re-read the value, for consistency with the other code.

2017-12-15 16:44 UTC, sharidas commented on lib/private/Files/View.php
> +				$this->eventDispatcher->dispatch('file.beforeUpdate', $event);
@PVince81 Ok, I have updated the PR, by just re-reading the value.

2017-12-15 16:46 UTC, PVince81 approved these changes
:+1:

2017-12-18 08:43 UTC, PVince81 commented
restarted drone build

2017-12-20 13:49 UTC, merged

2017-12-20 13:49 UTC, PVince81 commented
@sharidas please backport

2017-12-21 07:45 UTC, sharidas commented
Backport to stable10: https://github.com/owncloud/core/pull/29939