Adding files external tests for webdav to drone
owncloud/core pull request #29661
Opened 2017-11-23 11:59 UTC by SergioBertolinSG

2017-11-23 12:26 UTC, DeepDiver1975 commented
would be good to get coverage on files_external as well ...

2017-11-27 08:44 UTC, DeepDiver1975 requested changes
there is no coverage reported for external tests - see https://codecov.io/gh/owncloud/core/pull/29661/tree/apps

2017-11-27 08:44 UTC, DeepDiver1975 commented on .drone.yml
> +      TEST_SUITE: coverage
If tests are executed with coverage we don't need to execute the same tests without as well

2017-11-27 08:44 UTC, DeepDiver1975 commented on tests/drone/test-coverage.sh
> +  exec phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest-external.xml ${GROUP} --coverage-clover tests/autotest-external-clover-${DB_TYPE}.xml
I wonder if we shall merge the config ...... let me think about that

2017-11-27 12:57 UTC, SergioBertolinSG commented on .drone.yml
> +      TEST_SUITE: coverage
Removed.

2017-11-27 17:22 UTC, DeepDiver1975 requested changes

2017-12-06 11:56 UTC, DeepDiver1975 commented
@ownclouders rebase

2017-12-06 11:56 UTC, ownclouders commented
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

2017-12-06 11:56 UTC, ownclouders commented
Automated rebase failed! Please rebase your pull request manually via the command line.

Error:
```Command '['git', 'clone', '--depth', '1', 'rebase', '/tmp/tmp4rir7u12']' returned non-zero exit status 128.```

2017-12-13 13:45 UTC, DeepDiver1975 approved these changes

2017-12-13 13:45 UTC, merged

2017-12-13 13:45 UTC, DeepDiver1975 commented
THX @SergioBertolinSG - please backport - THX

2017-12-13 14:53 UTC, SergioBertolinSG commented
Backport stable10 https://github.com/owncloud/core/pull/29835