Exclude DAV CORS handling for non-browsers
owncloud/core pull request #29798
Opened 2017-12-08 18:03 UTC by PVince81

## Description
CORS only makes sense for browsers and davfs has trouble with the OPTIONS logic from CORS.

## Related Issue
Fixes https://github.com/owncloud/core/issues/29793

## Motivation and Context

## How Has This Been Tested?
- [x] TEST: Manual local test with davfs.
- [ ] TEST: rerun sample app tests

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-12-11 07:48 UTC, DeepDiver1975 requested changes

2017-12-11 07:48 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (strpos(strtolower($this->server->httpRequest->getHeader('user-agent')), 'mozilla/') === false) {
Matching on the user agent is not the right thing to do as far as I can tell after reading a bit into the specs
If I understand correctly we shall only apply CORS handling on the server if the 'Origin' header is sent with the request ...

see 
https://www.html5rocks.com/en/tutorials/cors/
https://spring.io/understanding/CORS
https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L68

2017-12-11 09:26 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (strpos(strtolower($this->server->httpRequest->getHeader('user-agent')), 'mozilla/') === false) {
That's even better, I'll adjust accordingly. Thanks for pointing out.

2017-12-11 12:19 UTC, PVince81 commented
I've adjusted and squashed to use the "Origin" header only for detection.

Tested and works fine with davfs mounting and also the example app from https://github.com/noveens/staticOwncloudWebapp

@DeepDiver1975

2017-12-11 12:39 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		// TODO: use $this->server->getAllowedMethods($request->getPath()) in the right location
https://github.com/owncloud/core/pull/29813

2017-12-13 11:57 UTC, PVince81 commented
- [ ] check if Origin is the same as current URL and skip CORS if that's the same

2017-12-13 14:01 UTC, PVince81 commented
I pushed something, unfinished... Need a utility function to properly compare domain + port with defaults (80, 443) in case they are specified still in case of quirky clients.

2017-12-15 10:18 UTC, PVince81 commented
Rebased, squashed.

I've added a `\OCP\Util::isSameDomain($url1, $url2)` function now in the first commit, with unit tests.
Then this method is used to check by CorsPlugin to detect cross-domain situations. If not cross-domain, it will skip CORS.

@DeepDiver1975 please re-review.

2017-12-15 10:20 UTC, PVince81 commented on lib/public/Util.php
> +	 * If this method returns true, a browser would consider both URLs to be
changing this to `false`

2017-12-15 12:19 UTC, DeepDiver1975 requested changes

2017-12-15 12:19 UTC, DeepDiver1975 commented on lib/public/Util.php
> +		\OC_App::loadApps(['theme']);
seems unrelated - rebase left over?

2017-12-15 12:24 UTC, PVince81 commented on lib/public/Util.php
> +		\OC_App::loadApps(['theme']);
indeed, no idea how this got here.

2017-12-15 12:26 UTC, DeepDiver1975 commented on lib/public/Util.php
> +		\OC_App::loadApps(['theme']);
no worries - stuff happens

2017-12-15 12:51 UTC, PVince81 commented
@DeepDiver1975 I've removed the bad line.

2017-12-18 08:47 UTC, DeepDiver1975 approved these changes

2017-12-18 08:48 UTC, merged

2017-12-18 08:58 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/29874