Added php 7.2 with sqlite to the matrix
owncloud/core pull request #29811
Opened 2017-12-11 11:28 UTC by SergioBertolinSG

2017-12-11 13:27 UTC, SergioBertolinSG commented
I think it is missing a fix for this commit :

 https://github.com/owncloud/core/pull/28575/commits/dc77daf44036464e728884ce3ef33994d471dc0c

2017-12-11 13:56 UTC, DeepDiver1975 commented
This needs to be adjusted as well - yes - @SergioBertolinSG can you take care please? THX

2017-12-11 14:38 UTC, DeepDiver1975 requested changes

2017-12-11 14:38 UTC, DeepDiver1975 commented on console.php
> -if (version_compare(PHP_VERSION, '7.2.0alpha1') !== -1) {
please keep this and adjust the version to 7.3

2017-12-11 14:38 UTC, DeepDiver1975 commented on console.php
> -if (version_compare(PHP_VERSION, '7.2.0alpha1') !== -1) {
see https://github.com/php/php-src/blob/16eb3873b0c85e1e71ecb89276cbdf03492ada78/NEWS#L3 
7.3.0alpha1 seems to be a good string to test against.

2017-12-11 14:52 UTC, SergioBertolinSG commented on console.php
> -if (version_compare(PHP_VERSION, '7.2.0alpha1') !== -1) {
Changed.

2017-12-11 19:06 UTC, DeepDiver1975 commented
last error to be addressed:

````

 There was 1 error:

1) Test\User\BasicAuthModuleTest::testAuth with data set "user2 is not known" (false, 'user2')
count(): Parameter must be an array or an object that implements Countable

/drone/src/lib/private/User/BasicAuthModule.php:55
/drone/src/tests/lib/User/BasicAuthModuleTest.php:76

2017-12-12 13:40 UTC, DeepDiver1975 commented
jenkins failure is related to 739351e

````
12:55:28 [Tue Dec 12 12:55:28 2017] PHP Stack trace:
12:55:28 [Tue Dec 12 12:55:28 2017] PHP   1. {main}() /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/index.php:0
12:55:28 [Tue Dec 12 12:55:28 2017] PHP   2. OC::handleRequest() /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/index.php:56
12:55:28 [Tue Dec 12 12:55:28 2017] PHP   3. OC\Route\Router->match() /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/base.php:931
12:55:28 [Tue Dec 12 12:55:28 2017] PHP   4. call_user_func:{/var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/private/Route/Router.php:342}() /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/private/Route/Router.php:342
12:55:28 [Tue Dec 12 12:55:28 2017] PHP   5. OC\Route\Route->OC\Route\{closure}() /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/private/Route/Router.php:342
12:55:28 [Tue Dec 12 12:55:28 2017] ::1:59860 [500]: /index.php/apps/files_trashbin/ajax/delete.php - require_once(): Failed opening required '..' (include_path='/var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/apps') in /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/private/Route/Route.php on line 155
12:55:28 [Tue Dec 12 12:55:28 2017] require_once(): Failed opening required '..' (include_path='/var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/apps') at /var/lib/jenkins/workspace/owncloud-core_core_PR-29811-RHFDMLDZR3TSA3EASJHEF2JWMTHMG3AZI3VFEETPJ3X4QEB4GTRQ@3/lib/private/Route/Route.php#155

2017-12-12 13:43 UTC, DeepDiver1975 commented
@SergioBertolinSG there is some error

![bildschirmfoto von 2017-12-12 14-42-36](https://user-images.githubusercontent.com/1005065/33887646-bd04583c-df4a-11e7-9cec-4abba2838ee6.png)

2017-12-12 14:08 UTC, DeepDiver1975 approved these changes

2017-12-13 11:44 UTC, DeepDiver1975 requested changes

2017-12-13 11:44 UTC, DeepDiver1975 commented on index.php
>  	echo 'You are currently running ' . PHP_VERSION . '.';
please be more careful when resolving conflicts - the recently introduced changes just got killed - see https://github.com/owncloud/core/blob/877715561fdac5dff46d98c26791c180eecf1a3c/index.php#L32-L41 @SergioBertolinSG

2017-12-13 11:44 UTC, DeepDiver1975 commented on index.php
>  	echo 'You are currently running ' . PHP_VERSION . '.';
same in console.php

2017-12-13 13:21 UTC, DeepDiver1975 commented
conflicting @SergioBertolinSG

2017-12-13 15:29 UTC, DeepDiver1975 commented
1149c05f2c5d2fe1c3781a5574bcc54d5ca53530 needs to be squashed into 8806702b3f0885f8d1075922178a1f8e6c83ff81 - this is where the trouble started @SergioBertolinSG

2017-12-14 08:30 UTC, DeepDiver1975 approved these changes

2017-12-14 08:30 UTC, merged