Removed double step for webdav files_external in drone
owncloud/core pull request #29838
Opened 2017-12-13 16:09 UTC by SergioBertolinSG

A double step was added in https://github.com/owncloud/core/pull/29661#event-1385643777

This PR objective is to fix it.

2017-12-14 10:16 UTC, SergioBertolinSG commented
The php-unit-tests step is not running.

2017-12-14 11:47 UTC, tboerger commented
As mentioned on chat, please keep the step and test suite naming and just merge the shell scripts and add the coverage enable/disable variables.

2017-12-14 12:28 UTC, SergioBertolinSG commented
If you see the .drone.yml you can realize that there are three sections which are very similar: phpunit, coverage and files_external. All can be combined into php-unit-tests.

2017-12-14 22:30 UTC, tboerger commented
Merging the test runs is totally fine, but just keep the naming.

2018-01-03 12:01 UTC, SergioBertolinSG commented
@tboerger ok now?

2018-01-03 13:34 UTC, tboerger approved these changes
Seems fine

2018-01-03 16:39 UTC, SergioBertolinSG commented
There is a problem in mariadb tests, there are running less tests than expected:

OK, but incomplete, skipped, or risky tests!
Tests: 4555, Assertions: 24815, Skipped: 103.

In a previous pull request they were:

OK, but incomplete, skipped, or risky tests!
Tests: 9532, Assertions: 35726, Skipped: 200.

2018-01-03 17:54 UTC, tboerger commented
Because you skip the db group, of course you will loose lots of test cases

2018-01-08 14:13 UTC, PVince81 commented
does this need a second review if anything was changed since approval ?

2018-01-09 09:28 UTC, tboerger commented on tests/drone/test-phpunit.sh
> +if [[ "${DB_TYPE}" == "none" || "${DB_TYPE}" == "sqlite" || "${ENABLE_COVERAGE}" == "true" ]]; then
Why do you disable the db group for coverage? Now we won't get the coverage report for the tests that require a database?

2018-01-09 09:38 UTC, DeepDiver1975 commented
as far as I can tell coverage for files external is missing.

2018-01-09 09:39 UTC, SergioBertolinSG commented on tests/drone/test-phpunit.sh
> +if [[ "${DB_TYPE}" == "none" || "${DB_TYPE}" == "sqlite" || "${ENABLE_COVERAGE}" == "true" ]]; then
It is the opposite isn't? without this change only 4555 tests run, with it 9532.

Otherwise the codecov will fail, covering less than before.

2018-01-09 09:43 UTC, DeepDiver1975 commented
> as far as I can tell coverage for files external is missing.
> Merge state

also missing on master @SergioBertolinSG can you have a look please? THX
Let me know if you need support

2018-01-09 09:44 UTC, SergioBertolinSG commented
> as far as I can tell coverage for files external is missing.

It is this one, isn't?

![screen shot 2018-01-09 at 10 42 04](https://user-images.githubusercontent.com/9048796/34714473-d989cb78-f529-11e7-8836-29cfede5a33a.png)

2018-01-09 09:47 UTC, DeepDiver1975 commented
> It is this one, isn't?

yes - but if you go into lib/Lib/Backend - I expect code coverage on OwnCloud.php - because this is the test which is executed .... there is something wrong

2018-01-09 09:52 UTC, DeepDiver1975 commented
looks like you missed the explicit call to test the specific backend - see https://github.com/owncloud/core/blob/c5407f3b9140eb4058798f3c21ff4a3ac6c148b0/build/autotest-external.sh#L202-L217

2018-01-09 14:23 UTC, DeepDiver1975 commented on tests/drone/test-phpunit.sh
> -        exec phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest-external.xml ${GROUP} --coverage-clover tests/autotest-external-clover-${DB_TYPE}.xml
leave this as well - this is the generic test execution.

I know this is confusing ....

2018-01-12 13:27 UTC, SergioBertolinSG commented
There is still a problem with external storage, it is not being detected as configured:

ownCloud backend not configured

2018-01-16 08:55 UTC, SergioBertolinSG commented
Last commit skips the particular run of WebdavTest.php. We found that OwncloudTest.php was not running correctly due to a config problem and WebdavTest.php was not running in Jenkins in first place. So we decided to skip this particular test for the moment and focus in moving everything left from Jenkins.

2018-01-16 11:49 UTC, DeepDiver1975 commented on tests/drone/test-phpunit.sh
> +        if [[ ${FILES_EXTERNAL_TYPE} !=  "Webdav" ]]; then
why?

2018-01-17 18:26 UTC, patrickjahns requested changes
@SergioBertolinSG 
please do not include any 3rdparty owncloud containers

2018-01-17 18:26 UTC, patrickjahns commented on .drone.yml
> +    image: morrisjobke/owncloud:latest
What is the reason of moving to a third party owncloud image?

2018-01-17 18:57 UTC, DeepDiver1975 commented on .drone.yml
> +    image: morrisjobke/owncloud:latest
morrisjobke/owncloud is used for years in jenkins. First tries with owncloud/server did show errors.
My request was to first move the jobs as is and enhance afterwards.

2018-01-17 23:00 UTC, patrickjahns commented on .drone.yml
> +    image: morrisjobke/owncloud:latest
> My request was to first move the jobs as is and enhance afterwards.    

Fair enough - i've put this as a task in the backlog 
To move forward with the drone migration lets get this PR wrapped up, and we can divide&conquer the remaining tasks 

> First tries with owncloud/server did show errors.  

Do we have links to the logs here? - would like to link these findings in the backlog for easy access 

I don't see the need for the owncloud server container actually - a minimal apache + mod_dav configuration should be sufficient for this scenario. It's faster and more lightweight.
OC -> OC webdav should be covered via federated sharing scenarios from the integration tests

2018-01-17 23:00 UTC, patrickjahns approved these changes

2018-01-18 08:30 UTC, DeepDiver1975 commented on .drone.yml
> +    image: morrisjobke/owncloud:latest
> I don't see the need for the owncloud server container actually - a minimal apache + mod_dav configuration should be sufficient for this scenario. It's faster and more lightweight.

this is a second test - see the start-webdav-apache.sh 

and yes - we shall test both - different implementation behave different

2018-01-18 08:30 UTC, DeepDiver1975 requested changes
- cleanup git history @SergioBertolinSG 
- have a look at codecov @DeepDiver1975

2018-01-18 09:31 UTC, DeepDiver1975 commented
- https://drone.owncloud.com/owncloud/core/2569/71 generates the coverage file tests/autotest-external-clover-sqlite-Webdav.xml
- this one is not uploaded - https://drone.owncloud.com/owncloud/core/2569/72

2018-01-18 10:04 UTC, DeepDiver1975 requested changes

2018-01-18 10:04 UTC, DeepDiver1975 commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
what about using wildcards? like tests/autotest-clover-*.xml and make sure all clover reports generate the report. Please read the docs of the plugin

2018-01-18 11:42 UTC, SergioBertolinSG commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
Not sure, the plugin is not using quotes:
https://github.com/robertstettner/drone-codecov/blob/master/entrypoint.sh#L22

and they look necessary:
https://github.com/codecov/codecov-bash/blob/master/codecov#L98-L99

2018-01-18 12:25 UTC, DeepDiver1975 commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
Please give it a try ...

2018-01-18 13:13 UTC, SergioBertolinSG commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
After commit b51415b :

2018/01/18 13:00:58 using coverage files: tests/autotest-clover-*.xml, tests/autotest-external-clover-*.xml
2018/01/18 13:00:58 no coverage files found

2018-01-19 13:48 UTC, tboerger commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
I have written the plugin and globbing works fine, it just needs to be documented properly

2018-01-19 14:22 UTC, SergioBertolinSG commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
it is not using robertstettner one?

2018-01-19 14:35 UTC, tboerger commented on .drone.yml
> +     - tests/autotest-external-clover-${DB_TYPE}-${FILES_EXTERNAL_TYPE}.xml
Nope, https://github.com/drone-plugins/drone-codecov

All plugins/* images MUST be built within this github org.

2018-01-19 16:35 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-01-19 16:35 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-01-19 16:35 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-01-20 23:11 UTC, patrickjahns commented on .drone.yml
> +      - ENABLE_COVERAGE=${ENABLE_COVERAGE}
Please add `FILES_EXTERNAL_TYPE=${FILES_EXTERNAL_TYPE}` to the environment here. Running `drone exec` locally would otherwise fail.

2018-01-21 21:16 UTC, patrickjahns commented
I used this PR as basis for #30207 and also noticed, that many of the vars in the script are not quoted. Run into quite some scenarios when debugging another failure, where the bash tests would also not evaluate correctly - please always quote relevant vars (background: http://mywiki.wooledge.org/Quotes )

2018-03-07 13:12 UTC, closed without merging