Fix public link share vulnerability
owncloud/core pull request #29865
Opened 2017-12-15 11:07 UTC by settermjd

## Description

The script that emails a user about a public link share contains an HTML injection vulnerability. This PR has been created to patch the issue.

## Related Issue

https://github.com/owncloud/security-tracker/issues/255

## Motivation and Context

It closes an HTML injection vulnerability.

## How Has This Been Tested?

There is a limited ability to suitably test `/ocs/ajax/share.php`. Given that, I created tests for the class that I developed, which filters out the HTML injection vulnerability.
Then, I manually tested the changes via the browser.

## Screenshots (if appropriate):

Relevant screenshots are contained in the related issue.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2017-12-15 12:46 UTC, tomneedham commented
We should validate the email addresses with https://github.com/owncloud/core/blob/master/lib/private/Mail/Mailer.php#L118

2017-12-15 14:16 UTC, settermjd commented
I deliberately avoided adding validation, as I'm not that familiar with the rest of the codebase, and felt that that may lead down a dark rabbit hole. However, I'm more than happy to add that in a separate PR.

2017-12-21 15:17 UTC, settermjd commented
I made minor amendments. Any input @tomneedham @PVince81 @DeepDiver1975 would be appreciated.

2017-12-22 14:08 UTC, PVince81 commented on composer.json
> +        "zendframework/zend-inputfilter": "^2.8",
@DeepDiver1975 are we ok to bring in these new libs ?

2017-12-22 14:41 UTC, PVince81 commented on lib/private/Share/Filters/MailNotificationFilter.php
> +class MailNotificationFilter {
PHPDoc, what is this class about ?

2018-01-05 11:55 UTC, settermjd commented on lib/private/Share/Filters/MailNotificationFilter.php
> +class MailNotificationFilter {
Will get that updated.

2018-01-05 12:07 UTC, settermjd commented
@PVince81, file and class dockblock comments added. Thanks for spotting that.

2018-01-08 10:40 UTC, DeepDiver1975 commented on composer.json
> +        "zendframework/zend-inputfilter": "^2.8",
license is  BSD-3-Clause - need to chat with @hodyroff about this

2018-01-08 10:48 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-01-08 10:48 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-01-08 10:49 UTC, ownclouders commented
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

error: Failed to merge in the changes.


```

2018-01-08 14:17 UTC, hodyroff commented on composer.json
> +        "zendframework/zend-inputfilter": "^2.8",
License is good, need to add to our list.

2018-01-08 14:24 UTC, PVince81 commented
@settermjd can you rebase ? Seems the bot is not able today 😄 (job security for professional rebasers FTW)

2018-01-08 14:25 UTC, DeepDiver1975 approved these changes

2018-01-09 15:33 UTC, settermjd commented
@PVince81 can do.

2018-01-09 15:47 UTC, settermjd commented
@PVince81, merged with master.

2018-01-09 16:14 UTC, DeepDiver1975 requested changes

2018-01-09 16:14 UTC, DeepDiver1975 commented on composer.lock
> +            "version": "4.1.4",
this should not have happened

2018-01-09 16:14 UTC, DeepDiver1975 commented on composer.lock
> +                "reference": "93474c65a2a7bf959200ab5f7a14cc450645c185"
same - please do not run composer update

2018-01-10 14:01 UTC, settermjd commented on composer.lock
> +                "reference": "93474c65a2a7bf959200ab5f7a14cc450645c185"
Fair call. Will change.

2018-01-10 14:25 UTC, settermjd commented
@DeepDiver1975; file revised.

2018-01-11 14:11 UTC, DeepDiver1975 approved these changes

2018-01-16 15:20 UTC, merged

2018-01-16 15:20 UTC, DeepDiver1975 commented
I assume we want to backport this ... @settermjd

2018-01-16 15:20 UTC, DeepDiver1975 commented
... will take care

2018-01-16 15:56 UTC, DeepDiver1975 commented
backport open