Adding new Symfony events
owncloud/core pull request #29885
Opened 2017-12-18 14:48 UTC by sharidas

Adding new Symfony events, to check, if creating
shares or downloading zips are blocked by any
apps or not.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Adding new Symfony events to check if any apps revoked the premission to download zip files or creating public links.

## Related Issue

https://github.com/owncloud/enterprise/issues/2329

## Motivation and Context

Adding new symfony events which can be used by the apps to see if creating public links for files/folders are allowed or not. And also see if downloading zip files are allowed or not.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-12-22 10:08 UTC, PVince81 requested changes
See comments above.

Note that for ZIP download I think there are at least 3 cases:

- URL with "files" with only one file => direct download
- URL with "files" and multiple files with full path => download all of them as ZIP
- URL with "dir" containing base dir and "files" containing a list of files inside that dir => prepend dir to all files and download as ZIP
- URL with "dir" without "files" => download said folder as ZIP

this is from memory, please check the code

2017-12-22 10:08 UTC, PVince81 commented on lib/private/legacy/files.php
> +			$event = new \Symfony\Component\EventDispatcher\GenericEvent(null, ['files' => $files]);
Please double check what happens if "$dir" is set with a single value and multiple "$files" are set. It is likely that we also need to pass `$dir`. The alternative is to have a loop that prepends the directory to all given `$files` entries.

2017-12-22 10:08 UTC, PVince81 commented on lib/private/legacy/files.php
> +				throw new Exception();
A generic exception without a message will confuse the user. Maybe throw ForbiddenException instead with a message "Access denied".

In general I'd rather expect event listeners to directly throw an exception from inside with a proper message, so the exception itself would already be forwarded by not catching it in the `dispatch()` call.

2017-12-22 10:08 UTC, PVince81 commented on apps/files_sharing/lib/API/Share20OCS.php
> +		$this->eventDispatcher->dispatch('file.beforecreateShare', $event);
And also catch exception here and transform it to an OCS Result with the exception message. I expect that listeners will throw exceptions in case of denied access.

2017-12-22 10:08 UTC, PVince81 commented on apps/files_sharing/lib/API/Share20OCS.php
> +			return new \OC\OCS\Result(null, 404, $this->l->t('No permission to create share'));
no permission is a 403 forbidden, not 404 not found

2017-12-22 12:30 UTC, sharidas commented on lib/private/legacy/files.php
> +			$event = new \Symfony\Component\EventDispatcher\GenericEvent(null, ['files' => $files]);
Here is the snapshot I took from IDE: 
![getmethod_singledir_multiplefiles](https://user-images.githubusercontent.com/3600427/34297966-3349a864-e741-11e7-8ec9-50896bb181cd.png)

Basically during testing I have used a directory and a file. Above is the screenshot of the `get` method with single dir `newfolder` and multiple files: `welcome.txt` and `rename_testfile.txt`. The newfolder and the files reside in the home folder of the user. The `$dir` is "/" in the above screenshot. I tried to create a folder inside `newfolder` and then created few files inside `newfolder`. In this case also `$dir` remains "/".

2017-12-22 13:18 UTC, sharidas commented
Made the following changes:
- injected the event dispatcher to the constructor.
- used camel case for event name
- Replaced generic exception with ForbiddedException
- Added `$dir` to the event array
- Added after event to make sure the creation of share is successful.
@PVince81 Hope the new change looks better.

2017-12-22 14:28 UTC, PVince81 requested changes
better, still some changes needed

2017-12-22 14:28 UTC, PVince81 commented on apps/files_sharing/lib/API/Share20OCS.php
> +		$event->setArgument('output', $output);
create a new event instance, don't  resend the same one

2017-12-22 14:28 UTC, PVince81 commented on apps/files_sharing/tests/ApiTest.php
> +			$event->setArgument('run', true);
is this really needed ? "run" is true by default

2017-12-22 14:28 UTC, PVince81 commented on lib/private/legacy/files.php
> +			if ($event->hasArgument('run') and ($event->getArgument('run') === false) and ($event->hasArgument('message'))) {
Make sure the "run" argument is created by you and set to "true" by default like you did for share creation.
Any reason you chose to not simply use the same pattern like for share creation ?

rename "message" to "errorMessage"

2017-12-22 14:40 UTC, sharidas commented on apps/files_sharing/tests/ApiTest.php
> +			$event->setArgument('run', true);
This was added because the tests were failing. It was using false value from Share20OCSTest.php. That's the reason I set `run` value to true here.

2017-12-22 14:53 UTC, sharidas commented
Updated the changes:
- made sure that run is set in the files.php
- Created new instance of event for after share event 
- The reason for making run to true is addressed at : https://github.com/owncloud/core/pull/29885#discussion_r158502885

2018-01-08 14:06 UTC, PVince81 commented on apps/files_sharing/tests/ApiTest.php
> +			$event->setArgument('run', true);
Strange. Do you mean one test is influencing another ? This shouldn't happen. We need to find a way to reset the event dispatcher in `tearDown` to avoid test side effects.

2018-01-08 14:08 UTC, PVince81 commented on lib/private/legacy/files.php
> +			if (($event->getArgument('run') === false) and ($event->hasArgument('errorMessage'))) {
this should be `||`, not `and`. If run is false and no error message was supplied, we should still stop running.

2018-01-08 14:08 UTC, PVince81 commented on lib/private/legacy/files.php
> +			$event = new \Symfony\Component\EventDispatcher\GenericEvent(null, ['result' => 'success']);
please also pass `dir` and `files` arguments here

2018-01-09 10:10 UTC, sharidas commented
@PVince81 Let me know if this change looks ok.

2018-01-09 11:48 UTC, sharidas commented
Created backport to stable10 PR: https://github.com/owncloud/core/pull/30067

2018-01-10 14:40 UTC, PVince81 approved these changes
:+1:

2018-01-10 16:05 UTC, merged