accountMapper either returns an object or throws an exception
owncloud/core pull request #30000
Opened 2017-12-31 19:57 UTC by butonic

the AccountManager getByUid cannot return null

thx @mrow4a for pointing this out

2018-01-01 20:19 UTC, mrow4a commented on lib/private/User/Manager.php
> +			$this->cachedUsers->set($uid, null);
Hmm, do we have some unit test checking if we don't make an unnecessarily call? Via e.g. checking number of calls for mocked object? It might prevent some silly errors later.

2018-01-01 20:30 UTC, butonic commented on lib/private/User/Manager.php
> +			$this->cachedUsers->set($uid, null);
nope ... AFAICT this line is untested. care to implement the test?

2018-01-01 20:32 UTC, mrow4a commented on lib/private/User/Manager.php
> +			$this->cachedUsers->set($uid, null);
I am anyways touching that fragment of code in my PR with unit tests, so I can include it there - in fact it is how I found it out ;d If we merge it quick I will cover it.

2018-01-08 07:25 UTC, DeepDiver1975 requested changes
fix tests please and make ci happy

2018-02-15 15:33 UTC, PVince81 commented
any update ?

2018-04-26 07:27 UTC, merged

2018-04-26 07:27 UTC, PVince81 commented
@butonic please backport

2018-05-16 04:12 UTC, phil-davis commented
Backport ``stable10`` #31445