Add group option to files:scan command
owncloud/core pull request #30020
Opened 2018-01-05 11:35 UTC by sharidas

Add --group option for files:scan command

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Adding --group option to the files:scan command.

## Related Issue

https://github.com/owncloud/core/issues/29569

## Motivation and Context

Adding --group option to files:scan command.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-01-10 14:33 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +						array_push($users[$group], $user->getUID());
this will likely not scale for groups with 1000+ members.

can you check whether the group manager has pagination or some method like `callOnAllGroups` that takes a callback ?

if not then let's keep this

2018-01-10 14:33 UTC, PVince81 commented
@mmattel can you review and test as you submitted the original ticket ?

2018-01-11 07:26 UTC, sharidas commented on apps/files/lib/Command/Scan.php
> +						array_push($users[$group], $user->getUID());
Unfortunately I didn't see pagination or method like `callOnAllGroups`. If I get any better idea I will update the PR.

2018-01-12 14:56 UTC, mmattel approved these changes
👍 

sudo -uwww-data ./occ files:scan -gtestgroup

Scanning group testgroup
Starting scan for user 1 out of 2 (bazbarfoo)
Starting scan for user 2 out of 2 (foobarbaz)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 3110    | 69416 | 00:08:36     |
+---------+-------+--------------+

Interrupting with ctrl-c also works.
I can not judge on groups with 1000+ members, but this is great!

2018-01-16 15:04 UTC, DeepDiver1975 commented
@dependabot rebase

2018-01-16 15:08 UTC, DeepDiver1975 requested changes

2018-01-16 15:08 UTC, DeepDiver1975 commented on apps/files/lib/Command/Scan.php
> +						array_push($users[$group], $user->getUID());
then let's add some pagination mechanism. I'd love to see the usage of a generator here.
Feels more logic when programming compared to a callOnX

2018-01-16 15:08 UTC, DeepDiver1975 commented on apps/files/lib/Command/Scan.php
> +					$output->writeln("\nScanning group $group");
I prefer output->writeln(); instead of adding \n - because to be precise you need to use PHP_EOL

2018-01-16 15:08 UTC, DeepDiver1975 commented on apps/files/tests/Command/ScanTest.php
> +		$this->command = new Scan($this->userManager, $this->groupManager, $this->lockingProvider, $this->mimeTypeLoader, $this->iconfig);
try to use the commandtester class - see other command tests like add user

2018-01-16 15:11 UTC, PVince81 commented on apps/files/tests/Command/ScanTest.php
> +		$this->command = new Scan($this->userManager, $this->groupManager, $this->lockingProvider, $this->mimeTypeLoader, $this->iconfig);
ah, so you too tried to add a test class for the scanner... see my failed attempt here: https://github.com/owncloud/core/pull/29635 (Oracle hates me)

2018-01-19 08:43 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +		yield $users;
only yield if not empty ? it probably doesn't hurt leaving it as is

2018-01-19 08:44 UTC, PVince81 commented on apps/files/tests/Command/ScanTest.php
> +			[['--groups' => 'group1'], 'Starting scan for user 1 out of 1 (user1)'],
please also add a test with two groups to make sure parsing the groups input works

2018-01-19 08:44 UTC, PVince81 reviewed
see comments

2018-01-22 14:24 UTC, PVince81 approved these changes
:+1: looks good, thanks!

2018-01-22 14:26 UTC, PVince81 commented
```
OK, but incomplete, skipped, or risky tests!
Tests: 9563, Assertions: 35812, Skipped: 202.
Segmentation fault
```

🙁 
Strangely I also got this in my own PR where I added other tests for the scanner with the command tester: https://github.com/owncloud/core/pull/29635

2018-01-22 14:30 UTC, PVince81 commented
it's PHP 7.2.1 with sqlite and 5.7.26.

Could be a PHP 7.2 bug ?

2018-01-22 14:33 UTC, PVince81 commented
I switched to PHP 7.1 in Drone on my branch of https://github.com/owncloud/core/pull/29635, let's see if that works...

2018-01-22 14:34 UTC, sharidas commented
Yah lets see. Thanks for the helping hand :)

2018-01-31 14:44 UTC, sharidas commented
@ownclouders rebase

2018-01-31 14:45 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-01-31 14:45 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-02-06 11:16 UTC, mmattel commented
@sharidas can you please add a documentation PR to reflect the changes and reference it ?
(https://github.com/owncloud/documentation/tree/master/admin_manual/configuration/server/occ_command.rst)

Any Progress on that, would really love to get this implemented?

2018-02-06 13:46 UTC, PVince81 commented
@mmattel we found a bug in phpunit with PHP 7.2 and memcache which breaks CI on this PR and another one and haven't decided on the solution. It seems that writing unit tests of the file scanner triggers this phpunit segfault bug.

@DeepDiver1975 @patrickjahns should we disable memcache when running phpunit ? As far as I remember there are only a small subset of tests that would cover memcache.

2018-02-06 15:43 UTC, patrickjahns commented
@PVince81 it is fine for me - though I'd like to know @DeepDiver1975 thought on this.

Remove the option from https://github.com/owncloud-ci/php/blob/7.2/Dockerfile and after a build we are ready to go

2018-02-08 15:52 UTC, PVince81 commented
@ownclouders rebase

2018-02-08 15:52 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-02-08 15:52 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-02-13 10:29 UTC, merged

2018-02-13 10:45 UTC, mmattel commented
Backporting?

2018-02-26 11:43 UTC, PVince81 commented
@sharidas can you backport this ?

it's also blocking the backport of https://github.com/owncloud/core/pull/29635

2018-02-26 11:52 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/30615