Stable10 drone adding oracle phpunit
owncloud/core pull request #30066
Opened 2018-01-09 11:47 UTC by SergioBertolinSG

Backport of https://github.com/owncloud/core/pull/29534

2018-01-09 16:21 UTC, DeepDiver1975 commented
@SergioBertolinSG we should finish the clean up of scripts before backporting

2018-01-09 16:39 UTC, SergioBertolinSG commented
This PR in master was previous to the clean up one. I think the right choice is to backport this one now and later backport the clean up one in the same order as they were/will be merged in master.

2018-01-10 11:33 UTC, DeepDiver1975 requested changes

2018-01-10 11:33 UTC, DeepDiver1975 commented on Jenkinsfile
> -    stage 'Files External: webdav'
no :-)

2018-02-26 09:57 UTC, PVince81 commented
what's missing ? failed rebase ?

2018-03-10 10:35 UTC, patrickjahns commented
closing in favor of #30728 - which contains oracle test runs

2018-03-10 10:35 UTC, closed without merging