Correct theme documentation in config.sample.php
owncloud/core pull request #30218
Opened 2018-01-22 08:44 UTC by settermjd

This is necessary, as https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html, is generated from this file. So if this file is wrong, so is the documentation. This also fixes
https://github.com/owncloud/documentation/issues/3728.

2018-01-22 09:24 UTC, phil-davis commented on config/config.sample.php
> + * Since version 10.0, however, themes are apps and are stored in one of app directories.
s/one of app directories/one of the app directories/

2018-01-22 20:13 UTC, DeepDiver1975 requested changes

2018-01-22 20:13 UTC, DeepDiver1975 commented on config/config.sample.php
> + * Since version 10.0, however, themes are apps and are stored in one of app directories.
I'd simply drop this example config value - all themes should be apps as of oc 10

2018-01-22 21:11 UTC, VicDeo commented on config/config.sample.php
> + * Since version 10.0, however, themes are apps and are stored in one of app directories.
But we still keep backward compatibility. 
Or not? :)

2018-01-22 21:17 UTC, DeepDiver1975 commented on config/config.sample.php
> + * Since version 10.0, however, themes are apps and are stored in one of app directories.
yes - but there is no need in advertising this ....

2018-01-23 14:17 UTC, settermjd commented on config/config.sample.php
> + * Since version 10.0, however, themes are apps and are stored in one of app directories.
So, it's ok to remove the `theme` configuration example from `config/config.sample.php`?

2018-01-23 15:07 UTC, settermjd commented
@DeepDiver1975, updated as per suggestion.

2018-01-24 15:33 UTC, DeepDiver1975 approved these changes

2018-01-25 12:59 UTC, settermjd commented
@DeepDiver1975, can you trigger the build again?

2018-01-31 08:13 UTC, settermjd commented
@DeepDiver1975?

2018-01-31 08:20 UTC, phil-davis commented
@ownclouders rebase

2018-01-31 08:21 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-01-31 08:22 UTC, phil-davis commented
@settermjd I made the bot do @DeepDiver1975 work. It triggers all CI again as a bonus, not just Jenkins.

2018-02-03 15:44 UTC, merged

2018-02-03 15:50 UTC, phil-davis commented
Backport stable10 #30350