return 403 and not 500 Error on ForbiddenException
owncloud/core pull request #30236
Opened 2018-01-23 11:00 UTC by individual-it

## Description
In case the access to a preview is forbidden (e.g by a firewall rule) return a 403 error and not a 500 error

## Related Issue
https://github.com/owncloud/firewall/issues/452

## Motivation and Context
better error reporting
tests expect correct error code

## How Has This Been Tested?
tried accessing blocked previews

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-01-23 14:56 UTC, PVince81 commented
please adjust unit test if possible to make codecov happy

2018-01-23 15:02 UTC, individual-it commented
There haven't been any to be adjusted, so here are some brand new ones. Lets see if now everybody is happy ;-)

2018-01-24 01:10 UTC, individual-it commented
@ownclouders rebase

2018-01-24 01:10 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-01-24 01:10 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-01-24 15:43 UTC, DeepDiver1975 requested changes

2018-01-24 15:43 UTC, DeepDiver1975 commented on apps/dav/tests/unit/Files/PreviewPluginTest.php
> +		$fileNode = $this->getMockBuilder('OCP\Files\IPreviewNode')
IPreviewNode::class please

2018-01-24 15:43 UTC, DeepDiver1975 commented on apps/dav/tests/unit/Files/PreviewPluginTest.php
> +		$this->logger = $this->getMockBuilder('OC\Log')->disableOriginalConstructor()->getMock();
```php
logger = $this->createMock(ILogger:class);

2018-01-24 15:54 UTC, individual-it commented
@DeepDiver1975 done requested changes, please re-review

2018-01-24 15:55 UTC, DeepDiver1975 commented on apps/dav/tests/unit/Files/PreviewPluginTest.php
> +		$node = $this->getMockBuilder('OCA\DAV\Files\IFileNode')
::class here as well - and createMock should do what is needed - no need to use getMockBuilder
please apply to all occurrances - THX

2018-01-24 16:05 UTC, individual-it commented on apps/dav/tests/unit/Files/PreviewPluginTest.php
> +		$node = $this->getMockBuilder('OCA\DAV\Files\IFileNode')
done

2018-01-30 15:40 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-01-30 15:40 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-01-30 17:58 UTC, DeepDiver1975 approved these changes

2018-01-30 17:58 UTC, merged

2018-01-30 17:58 UTC, DeepDiver1975 commented
@individual-it backport?

2018-01-31 03:39 UTC, individual-it commented
@DeepDiver1975 @phil-davis no backport needed/possible as that plug-in only exists in master, it was created by @DeepDiver1975 in #29319