Changepassword setting
owncloud/core pull request #30324
Opened 2018-01-31 11:27 UTC by sushilkshetri

new feature with its page object has been added

2018-01-31 11:48 UTC, individual-it requested changes
looks generally very good, just small change requests 👍

2018-01-31 11:48 UTC, individual-it commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> +		$this->find('xpath', $this->xpathOfChangePasswordButton)->click();
let's check if `find()` returns `null` as we do in other places before clicking
and we should be able to use `findById()` and not `find("xpath", ...)` to make it simpler

2018-01-31 12:49 UTC, phil-davis reviewed
Looks good. Just try the change suggested by Artur.

2018-01-31 12:49 UTC, phil-davis commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> +		$this->find('xpath', $this->xpathOfChangePasswordButton)->click();
Nice to see that a button has an id that can be used!

2018-02-01 11:01 UTC, sushilkshetri commented
@phil-davis , @individual-it  please review again I have added some more tests.

2018-02-02 03:14 UTC, individual-it requested changes

2018-02-02 03:14 UTC, individual-it commented on tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
> +		PHPUnit_Framework_Assert::assertEquals($wrongPasswordmessageText, $this->personalGeneralSettingsPage->getWrongPasswordMessageText($this->getSession()));
that line is far too long. Please make it shorter. Check also the coding standards https://doc.owncloud.org/server/10.0/developer_manual/general/codingguidelines.html

2018-02-02 03:14 UTC, individual-it commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> +			throw new ElementNotFoundException(__METHOD__ . " could not find element with id $this->changePasswordButtonID");
too long line

2018-02-02 03:14 UTC, individual-it commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> +			throw new ElementNotFoundException(__METHOD__ . " could not find element with id $this->passwordErrorMessageID");
too long line

2018-02-02 03:14 UTC, individual-it commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> +		$this->waitForAjaxCallsToStartAndFinish($session);
I don't think that waiting makes sense here. No Ajax request should be active here, you have already got all information and haven't done any action (like click).
but at the end of `public function changePassword($oldPassword, $newPassword) {` that might be very usefull

2018-02-02 03:14 UTC, individual-it commented on tests/ui/features/other/changePasswordFromSetting.feature
> +		Then a message should be displayed with the text "Wrong password"
I think we should have a more specific step here. Something like `a password error message should be displayed ...`

2018-02-02 10:51 UTC, phil-davis commented on tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
> +		$this->getSession());
Format - if you need to use extra lines, then the method/function name and ``(`` is on line1, then a line (or lines) for the parameters, then the closing ``)`` on its own line. Something like:
```
$this->personalGeneralSettingsPage->changePassword(
    $oldPassword, $newPassword, $this->getSession()
);
```

2018-02-02 10:52 UTC, phil-davis commented on tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
> +		$this->getSession());
Format here also

2018-02-02 10:54 UTC, phil-davis commented on tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
> +	public function aMessageShouldBeDisplayedWithTheText(
This function name might get duplicated by a general function checking for a message.
Maybe: ``aPasswordErrprMessageShouldBeDisplayedWithTheText``

2018-02-02 10:55 UTC, phil-davis commented on tests/ui/features/lib/PersonalGeneralSettingsPage.php
> -
While editing, try not to remove blank lines between functions

2018-02-02 11:02 UTC, phil-davis commented on tests/ui/features/other/changePasswordFromSetting.feature
> +	Scenario: Change password from setting
I am not sure what "from setting" means here. This ordinary scenario could just be called
```
Scenario: Change password
```

2018-02-02 11:02 UTC, phil-davis requested changes
I made a few comments about formatting and words.

2018-02-19 09:00 UTC, sushilkshetri commented
@phil-davis  @individual-it  please review again.

2018-02-19 09:25 UTC, phil-davis reviewed
Just 1 unused var that I can see.

2018-02-19 09:25 UTC, phil-davis commented on tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
> +		$username = $this->featureContext->getCurrentUser();
``$username`` is unused here - the line can be deleted

2018-02-19 10:00 UTC, sushilkshetri commented
@phil-davis  @individual-it  please review again.

2018-02-19 10:08 UTC, phil-davis approved these changes
LGTM

2018-02-20 05:14 UTC, individual-it commented
please rebase to make the CI run again

2018-02-20 05:26 UTC, individual-it commented
@ownclouders rebase

2018-02-20 05:26 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-02-20 05:27 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-02-20 05:49 UTC, individual-it commented
rebased by using the bot

2018-02-20 10:52 UTC, individual-it approved these changes

2018-02-20 10:53 UTC, merged

2018-02-20 10:56 UTC, individual-it commented
backport in #30545