Fix for when account not found during sync
owncloud/core pull request #30367
Opened 2018-02-05 12:38 UTC by tomneedham

Fixes https://jenkins.owncloud.org/job/upgrade-testing/CONFIG=8.2.11%3Bdaily-master-qa,DB=sqlite/285/console

2018-02-05 13:58 UTC, DeepDiver1975 requested changes

2018-02-05 13:58 UTC, DeepDiver1975 commented on lib/private/User/SyncService.php
> +					$a = $this->createNewAccount($backendClass, $uid);
since this was not detected by the regular CI process - I assume this is missing unit tests

2018-02-05 14:00 UTC, phil-davis commented on lib/private/User/SyncService.php
> +					$a = $this->createNewAccount($backendClass, $uid);
The regression looks like it happened here:
https://github.com/owncloud/core/pull/29669/files#diff-37958be4e01e8baeb127a59409e1a593L114

2018-02-06 06:53 UTC, tomneedham commented on lib/private/User/SyncService.php
> +					$a = $this->createNewAccount($backendClass, $uid);
Yep - looking at tests for this

2018-02-06 08:20 UTC, tomneedham commented
Added a test to run through the sync service at least once.

2018-02-07 05:35 UTC, individual-it commented
restarted drone, now passed

2018-02-07 07:47 UTC, merged