Update config.sample.php
owncloud/core pull request #30400
Opened 2018-02-07 13:58 UTC by cdamken

Removing the old apps store from config.sample.php

2018-02-07 14:20 UTC, DeepDiver1975 requested changes

2018-02-07 14:20 UTC, DeepDiver1975 commented on config/config.sample.php
> - 'apps_paths' =>
why this one? We better adjust the documentation and not name the app store - but the config option itself is still falid

2018-02-07 16:37 UTC, cdamken commented on config/config.sample.php
> - 'apps_paths' =>
ok, then we can just remove the other part

2018-02-08 13:35 UTC, DeepDiver1975 approved these changes

2018-02-08 13:35 UTC, merged