Email notifications app
owncloud/core pull request #30468
Opened 2018-02-13 08:01 UTC by jvillafanez

## Description
Send notifications via email to the user

## Related Issue
New feature

## Motivation and Context

## How Has This Been Tested?
Unittests plus manually tested the overall behaviour of the app

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@PVince81

2018-02-13 08:17 UTC, DeepDiver1975 requested changes

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/appinfo/info.xml
> +	<namespace>notifications_mail</namespace>
Please use a nice namespace

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/appinfo/info.xml
> +	<default_enable/>
really?

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/appinfo/info.xml
> +	<use-migrations>true</use-migrations>
not really

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Application.php
> +		$container->registerService(NotificationSender::class, function (IContainer $c) {
automated DI should work on all of these - please adopt

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +					'message' => $this->l10n->t('Invalid value')
be nice to users - tell them more what went wrong

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +					'message' => $this->l10n->t('Saved')
needed? this can be done pure on frontend

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +				'status' => 'success',
please use http status codes

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +			$this->config->setUserValue($this->userSession->getUser()->getUID(), 'notifications_mail', 'email_sending_option', $value);
handle getUser returning null - we had that these days

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +	 * @param string $value any of ["never", "action", "always"]
no admin annotation is missing

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/NotificationConsumer.php
> +	public function markProcessed(INotification $notification) {}
codes tyle

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/NotificationSender.php
> +		$serverUrlLink = "<a href=\"$serverUrl\">$serverUrl<a/>";
missing encoding?

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/NotificationSender.php
> +			case "never":
single quote

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Panels/Personal/EmailNotificationsPanel.php
> +				'visibleText' => 'Never send me any notification email',
no translation?

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Panels/Personal/EmailNotificationsPanel.php
> +		$emailSendingOption = $this->config->getUserValue($this->userSession->getUser()->getUID(), 'notifications_mail', 'email_sending_option', 'never');
getUser can return null

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Panels/Personal/EmailNotificationsPanel.php
> +		return 'additional';
we should find a proper section - like notifications or something @pmaier1

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/templates/panels/personal/emailnotifications.php
> +	<p><?php p($l->t('You can receive notifications generated by any app in your configured email address. Choose if you let ownCloud to send you such emails.')); ?></p>
missing white labeling

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/tests/unit/Controller/NotificationOptionsController.php
> +		$this->userSession = $this->getMockBuilder('\OCP\IUserSession')
IUSerSession::class - please apply to all in here - THX

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/tests/unit/Controller/NotificationOptionsController.php
> +	private $userSession;
missing phpdoc on all of them

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/tests/unit/bootstrap.php
> +if (!defined('PHPUNIT_RUN')) {
can be dropped

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/tests/unit/bootstrap.php
> +if(!class_exists('PHPUnit\Framework\TestCase')) {
can be dropped

2018-02-13 08:17 UTC, DeepDiver1975 commented on apps/notifications_mail/tests/unit/bootstrap.php
> +\OC_App::loadApp('dav');
dav - really?

2018-02-13 08:17 UTC, DeepDiver1975 commented on lib/public/Notification/Events/AbstractRegisterConsumerEvent.php
> +abstract class AbstractRegisterConsumerEvent extends Event {
why do we need abstract events here?

2018-02-13 08:17 UTC, DeepDiver1975 commented on lib/public/Notification/Exceptions/NotifierIdInUseException.php
> +class NotifierIdInUseException extends \Exception {
I really question if we need that many additional exception types

2018-02-13 08:17 UTC, DeepDiver1975 commented on tests/lib/Notification/ManagerTest.php
> +		$this->eventDispatcher = \OC::$server->getEventDispatcher();
please mock the event dispatcher

2018-02-13 08:17 UTC, DeepDiver1975 commented on tests/lib/Notification/ManagerTest.php
> +		$app = $this->getMockBuilder('OCP\Notification\IApp')
::class

2018-02-13 08:18 UTC, DeepDiver1975 commented
![bildschirmfoto von 2018-02-13 09-18-11](https://user-images.githubusercontent.com/1005065/36139696-dbea3444-109e-11e8-8af1-052df7006e3c.png)

2018-02-13 09:48 UTC, jvillafanez commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +					'message' => $this->l10n->t('Saved')
I'm trying to use the `OC.msg` component in the frontend to keep a similar style with the rest of the UI. In this case, the text to be displayed to the user will come from the `response.data.message` as it is, so we either provide the translation from the backend or we change the value on-the-fly in the frontend.
I think other apps choose the first options, so I just followed what those apps implemented.

2018-02-13 09:50 UTC, jvillafanez commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +				'status' => 'success',
The default http status is 200, which fits with a successful response as this one.

2018-02-13 10:08 UTC, jvillafanez commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +			$this->config->setUserValue($this->userSession->getUser()->getUID(), 'notifications_mail', 'email_sending_option', $value);
Fixed in the controller (changes pending to be pushed), but I'm not sure how to handle it from the panels... maybe using a different (error) template?

2018-02-13 10:09 UTC, DeepDiver1975 commented on apps/notifications_mail/lib/Controller/NotificationOptionsController.php
> +				'status' => 'success',
yes - but then there is no need to have this status element in here.
please just kill it. this fits into your comment of OC.msg above - just adopt this as well please. This is so wrong. we need to stop doing things wrong. THX

2018-02-13 10:19 UTC, jvillafanez commented on apps/notifications_mail/lib/NotificationSender.php
> +		$serverUrlLink = "<a href=\"$serverUrl\">$serverUrl<a/>";
Since it's a clickable link I don't think it's needed. I'll change the phpdoc to clarify

2018-02-13 10:29 UTC, jvillafanez commented on apps/notifications_mail/lib/Panels/Personal/EmailNotificationsPanel.php
> +				'visibleText' => 'Never send me any notification email',
the translation will be handled in the template

2018-02-13 13:41 UTC, jvillafanez commented on lib/public/Notification/Events/AbstractRegisterConsumerEvent.php
> +abstract class AbstractRegisterConsumerEvent extends Event {
I don't think there is an event interface that we can use, and we need to hide implementation details.
The notification manager provides a couple of new registration methods that are used in the event implementations that aren't part of the interface, and I don't think it's a good idea to expose those.

If we add public events, the calls that the event needs to do to perform the registration should be public, which implies the calls being part of the `IManager` interface. This implies that at least 2 different ways to register for the notifications would be available for the users from the notification manager.

2018-02-13 13:46 UTC, jvillafanez commented on lib/public/Notification/Exceptions/NotifierIdInUseException.php
> +class NotifierIdInUseException extends \Exception {
This is a situation that could happen and that the notification manager can't deal with it. I think it's fine since these exceptions are part of the notification component, so it should help to identify where the problem is easily and take apropiate action if needed.

2018-02-13 16:32 UTC, jvillafanez commented
I think the only thing pending is to decide in which section the panel should be placed. The rest of the comments are either addressed or commented.
https://github.com/owncloud/core/pull/30468/commits/10086292dd5b2589f687d0dab9fa85cc69b76a55 contains the changes for the app based on the code review since the previous commit changes the app name.

2018-02-14 10:01 UTC, jvillafanez commented
Drone errors seem unrelated.

2018-02-14 11:09 UTC, DeepDiver1975 commented
The app will go into it's own repo ....

2018-02-14 15:51 UTC, DeepDiver1975 requested changes
> The app will go into it's own repo ....

https://github.com/owncloud/notifications_mail

2018-02-14 16:08 UTC, closed without merging

2018-02-14 17:02 UTC, jvillafanez commented
This has been splitted:
* Required core changes: https://github.com/owncloud/core/pull/30489
* App: https://github.com/owncloud/notifications_mail/pull/1