Address a few code inspections
owncloud/core pull request #30471
Opened 2018-02-13 09:59 UTC by butonic

Only for php files in the root folder ... I initially also addressed `'Exception', superclass of exception class 'Error', has already been caught` but it turns out that seems to be a false positive in the PHPStorm Inspectien triggered by the Error Polyfill from Paragonie random_compat or Symphony. Double checked with

```php
try {
	throw new Error();
} catch (Exception $e) {
	echo 'caught Exception';
} catch (Error $e) {
	echo 'caught Error';
}
// gives 'caught Error'
```

Should we return 500 Status for the JSON responses in cron.php

2018-02-13 10:04 UTC, DeepDiver1975 commented on cron.php
> -			OC_JSON::error(['data' => ['message' => 'Background jobs disabled!']]);
I'd just leave it this way for the time being.

2018-02-13 10:24 UTC, butonic commented on cron.php
> -			OC_JSON::error(['data' => ['message' => 'Background jobs disabled!']]);
using the json response as recommended in the deprecation text for OC_JSON. No change in behavior. If we want to get rid of deprecated code we need to start somewhere.

2018-03-12 22:16 UTC, DeepDiver1975 commented on cron.php
> -			OC_JSON::error(['data' => ['message' => 'Background jobs disabled!']]);
Proper fix for this: split cron.php into two pieces:
1. occ command
2. pure http route for ajax and web cron

2018-03-12 22:19 UTC, DeepDiver1975 requested changes
the JSONResonse changes look strange ....

2018-04-24 14:47 UTC, PVince81 commented
conflicts.

if no agreement and p4-low I suggest closing

moving to "triage" meanwhile

2018-06-28 12:48 UTC, PVince81 commented on cron.php
> -			OC_JSON::error(['data' => ['message' => 'Background jobs disabled!']]);
=> https://github.com/owncloud/core/pull/31914

2018-08-01 06:50 UTC, DeepDiver1975 commented
conflicting heavily - please resubmit

2018-08-01 06:50 UTC, closed without merging