Use type juggling for comparison on size in chunking plugin
owncloud/core pull request #30504
Opened 2018-02-16 15:27 UTC by sharidas

Intially we tried to go ahead with int comparison.
But that didn't worked with 32 bit systems. Because of
explicit conversion of double to int. So in this patch
decided to move ahead with type juggling comparison
or loose comparison of size in chunking plugin

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Loose type comparison of size in chunk plugin helps when large files are uploaded.

## Related Issue

## Motivation and Context

Loose type comparison of size in chunk plugin helps when large files are uploaded.

## How Has This Been Tested?

- [x] Verified by uploading various large files 3 GB, 3.8 GB, 4 GB, 4.8 GB, 7.6 GB from web UI.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-02-16 15:54 UTC, DeepDiver1975 requested changes
please add test for the different data types as we did see while testing. THX

2018-02-19 06:57 UTC, sharidas commented on apps/dav/lib/Upload/ChunkingPlugin.php
> +		if ($expectedSize != $actualSize) {
loose comparison.

2018-02-19 06:58 UTC, sharidas commented on apps/dav/tests/unit/Upload/ChunkingPluginTest.php
> +			['12345678910', 12345678910.0123],
Just another comparison to check if it throws exception. If so its handled here https://github.com/owncloud/core/pull/30504/files#diff-228fe7c1be519f23fe9364825968a88cR209

2018-02-19 06:59 UTC, sharidas commented on apps/dav/tests/unit/Upload/ChunkingPluginTest.php
> +			['999999999999999.9999', 999999999999999.9999],
A large float for comparison.

2018-02-19 19:14 UTC, DeepDiver1975 approved these changes

2018-02-19 20:36 UTC, merged

2018-03-13 16:30 UTC, PVince81 commented
@sharidas please backport

2018-03-13 17:49 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/30772

2018-03-28 15:18 UTC, sharidas commented
This PR : https://github.com/owncloud/core/pull/30285 was my first reference for this task.