Fixing variable dependency
owncloud/core pull request #30508
Opened 2018-02-16 21:59 UTC by Julian1998

oc_current_user doesn't exist anymore and has to be replaced by OC.getCurrentUser() for supporting all necessary versions.

2018-02-17 07:58 UTC, DeepDiver1975 approved these changes

2018-02-19 07:52 UTC, DeepDiver1975 requested changes

2018-02-19 07:52 UTC, DeepDiver1975 commented on apps/files/js/files.js
> +			var currentUser = OC.getCurrentUser();
wait ..... getCurrentUser returns an array

![bildschirmfoto von 2018-02-19 08-51-39](https://user-images.githubusercontent.com/1005065/36367265-2ec37f06-1552-11e8-83d7-826fb4ec91e5.png)

2018-02-19 09:19 UTC, PVince81 commented
Nice catch! Please see the above.

2018-02-19 15:02 UTC, Julian1998 commented on apps/files/js/files.js
> +			var currentUser = OC.getCurrentUser();
Sure! I knew that - But calendar and co. need an object

2018-02-19 15:07 UTC, Julian1998 commented on apps/files/js/files.js
> +			var currentUser = OC.getCurrentUser();
Sure! I knew that - But calendar needs this object. oc_current_user and getCurrentUser() are equal!

2018-02-19 15:17 UTC, Julian1998 commented
Sorry...my fault - Fixed

2018-02-20 16:48 UTC, PVince81 commented
squashed and rebased

2018-02-21 09:29 UTC, merged