[WIP] Add user:modify command to core
owncloud/core pull request #30540
Opened 2018-02-20 08:31 UTC by sharidas

Add user:modify command to core.
This command will help user to set the
email and displayname using occ command.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Intention of adding this command is to provide admins the ability to set the email address and displayname for users using occ command.

## Related Issue

https://github.com/owncloud/core/issues/30529

## Motivation and Context

This change would help administrators to set the displayname and email address for users using occ command.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-02-20 08:34 UTC, sharidas commented on core/Command/User/Modify.php
> +			if ($user->canChangeDisplayName() === false) {
Argh doesn't make sense, as the administrator triggers the command.

2018-02-20 08:49 UTC, sharidas commented on core/Command/User/Modify.php
> +		if (($key === 'email') && ($value === null)) {
Lets say if user doesn't want to modify the settings `displayname` or `email` then lets display it and return. Same applies for https://github.com/owncloud/core/pull/30540/files#diff-bb62ccd405c6abbc168c61fb1ea08817R115. So basically --value=something means we are setting it.

2018-02-20 10:34 UTC, DeepDiver1975 requested changes

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +	private $userManager;
phpdoc missing

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +	public function __construct(IUserManager $userManager) {
phpdoc missing

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +				'Setting key to set, get or delete',
get? I'd not expect a get option in a modify command

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +			throw new \InvalidArgumentException("The key cannot be empty");
single quote

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +		if (($input->getArgument('key') === '') or ($input->getArgument('key') === null)) {
use || not or

2018-02-20 10:34 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +			throw new \InvalidArgumentException("Supported keys are " . implode(', ', $this->allowedKeys));
single quote

2018-02-20 10:34 UTC, DeepDiver1975 commented on tests/Core/Command/User/ModifyTest.php
> +		$mock = $this->getMockBuilder('OC\Core\Command\User\Modify')
Modify::class

2018-02-20 10:34 UTC, DeepDiver1975 commented on tests/Core/Command/User/ModifyTest.php
> +			[false, 'foo', '', "The user foo does not exist"],
single quote

2018-02-20 10:34 UTC, DeepDiver1975 commented on tests/Core/Command/User/ModifyTest.php
> +	 * @param $uidExist
missing types

2018-02-20 10:34 UTC, DeepDiver1975 commented on tests/Core/Command/User/ModifyTest.php
> +		/*return [
remove?

2018-02-20 10:34 UTC, DeepDiver1975 commented on tests/Core/Command/User/ModifyTest.php
> +	public function dataExecute() {
I usually start provider methods with provides ...

2018-02-20 12:49 UTC, sharidas commented on core/Command/User/Modify.php
> +			if ($this->mailer->validateMailAddress($value) === true) {
Additional check to verify invalid address provided.

2018-02-20 13:18 UTC, mmattel commented on core/Command/User/Modify.php
> +				'Setting key to set',
1. InputArgument::OPTIONAL --> InputArgument::REQUIRED (see line 87)
2. ``Setting key to set`` --> ``Key to be changed``

2018-02-20 13:20 UTC, mmattel commented on core/Command/User/Modify.php
> +				'The new value of the setting.'
``The new value of the setting`` --> `` The new value of the key``

2018-02-20 13:22 UTC, tomneedham commented on core/Command/User/Modify.php
> +				'Setting key to set',
Maybe we also give a list of valid values here?

2018-02-20 21:25 UTC, mmattel commented on core/Command/User/Modify.php
> +				InputArgument::OPTIONAL,
I need to ask again,
why do you have a argument optional when you then throw an excpetion if it is null or empty?
See the query in line 87

2018-02-21 06:44 UTC, mmattel commented
LGTM
Please add (and link) a documentation PR to describe the new command.

2018-02-23 13:25 UTC, DeepDiver1975 requested changes

2018-02-23 13:25 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +				$output->writeln('The email address of ' . $uid . ' updated to ' . $value);
```php
"The email address of $uid updated to $value"

2018-02-23 13:25 UTC, DeepDiver1975 commented on core/Command/User/Modify.php
> +	}
no return at the end?

2018-02-26 07:16 UTC, sharidas commented
Updated the PR with the changes requested.

2018-02-26 14:20 UTC, DeepDiver1975 requested changes
Running ./occ u:m admin displayname has no output - nobody knows whats going on.

And why is value an option?

2018-02-26 15:18 UTC, sharidas commented
> And why is value an option?

Modified value from option to argument and marked as required.

2018-02-28 14:07 UTC, PVince81 commented on core/Command/User/Modify.php
> +		if (($key === 'email') && ($value !== null)) {
is it possible to set the email and display name to empty string ?

2018-02-28 14:07 UTC, PVince81 commented on tests/Core/Command/User/ModifyTest.php
> +			['foo', 'email', 'foo@bar.com@foobar'], //Test for invalid email
please add tests for setting empty values

2018-02-28 14:39 UTC, mmattel commented on core/Command/User/Modify.php
> +		if (($key === 'email') && ($value !== null)) {
Imho there must be a username but there may be an eMail address, or can the username also be empty?

If the username can be empty, then we need to check that the eMail address is either already existent or populated by the key.

2018-02-28 15:05 UTC, sharidas commented on core/Command/User/Modify.php
> +				'Key to be changed. The valid keys are : displayname, email'
Addressed in this version of PR.

2018-02-28 15:05 UTC, sharidas commented on tests/Core/Command/User/ModifyTest.php
> +			['foo', 'email', 'foo@bar.com@foobar'], //Test for invalid email
Added tests for empty values. In fact added more cases for input uid/key/values.

2018-02-28 15:08 UTC, sharidas commented on core/Command/User/Modify.php
> +		if (($key === 'email') && ($value !== null)) {
IMHO lets make it simple, if the username is empty then lets not do anything ( of course display valid message ).

2018-02-28 15:10 UTC, sharidas commented on tests/Core/Command/User/ModifyTest.php
> +			[true, '', '', '', 'The user  does not exist'],
When the user is empty/null then just provide this message shown in the last argument.

2018-02-28 15:11 UTC, sharidas commented on tests/Core/Command/User/ModifyTest.php
> +			[true, 'foo', 'email', '', 'The value cannot be empty'],
When the value is empty or null deliver the message as shown in the last index of the array.

2018-02-28 15:12 UTC, sharidas commented on tests/Core/Command/User/ModifyTest.php
> +			[true, 'foo', null, '', 'The key cannot be empty'],
When key is empty or null case addressed here.

2018-02-28 16:44 UTC, PVince81 approved these changes
:+1: please backport

2018-02-28 17:11 UTC, mmattel commented
@sharidas pls add a documentation PR to add the changes to the occ command

2018-03-01 06:15 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/30652

2018-03-01 06:24 UTC, sharidas commented
Here is the documentation ticket : https://github.com/owncloud/documentation/issues/3853

2018-03-01 09:15 UTC, merged