[WIP] Remove user from the storage setting or storage when user is deleted
owncloud/core pull request #30712
Opened 2018-03-06 14:07 UTC by sharidas

Remove user from the storage if there are multiple
users associated with the storage during deletion
of the user. Else remove the storage when user is
deleted, since the storage is only associated with
the user being deleted.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Remove user from the external storage list when there are multiple users applicable users for the storage, during deletion of user. Else remove the storage as the user which is being deleted is the only storage associated with the user.

## Related Issue

https://github.com/owncloud/core/issues/30694

## Motivation and Context

This change would help to clean up the external storage when a user is being deleted.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-03-06 14:16 UTC, PVince81 commented on lib/private/User/User.php
> +		foreach (\OC::$server->getUserGlobalStoragesService()->getStorageForAllUsers() as $storageForAllUser) {
did you try with `getUserStoragesService()` instead ? this would be more direct and give you the whole list without the need to filter.
However one problem is that this service works with the user from the session, might need to refactor it in a way that allows creating/querying it for a given user.

2018-03-06 14:17 UTC, PVince81 commented on lib/private/User/User.php
> +					\OC::$server->getGlobalStoragesService()->removeStorage($id);
but actually you might be right, this removes storages created by an admin and applied only for a user, so maybe this approach is ok

2018-03-06 14:20 UTC, PVince81 commented
I wonder if this logic could be put in a method of one of the services. But it seems the services don't know from each other yet. Does deleting a storage not work from the "UserGlobalStoragesService" ?

2018-03-06 15:09 UTC, sharidas commented
> Does deleting a storage not work from the "UserGlobalStoragesService" ?

If we use "getUserGlobalStoragesService", then the problem happens when `./occ user:delete` is executed. The deletion of storage doesn't work and causes exception. The exception message is `UserGlobalStoragesService writing is disallowed`

2018-03-06 15:42 UTC, PVince81 commented
Yeah, `UserGlobalStoragesService` is designed for read-only use in the web UI and storage level, to find out all storages the current user has access to, whether configured globally or locally.

Another approach would be to simply have two calls: one for the local storages, maybe `UserStoragesService->deleteAll()` and another one `GlobalStoragesService->deleteAllForUser($userId)`.

It would also make it easier to write unit tests as you'd mostly write tests for these two methods.

2018-03-12 06:32 UTC, sharidas commented on lib/private/User/User.php
> +		\OC::$server->getGlobalStoragesService()->deleteAllForUser($this->getUID());
Doesn't local storage gets deleted here. I mean https://github.com/owncloud/core/pull/30712/files#diff-3030ca4989f892c50dea24eaa3f1ae38R236

2018-03-12 10:20 UTC, PVince81 commented on lib/private/User/User.php
> +		\OC::$server->getGlobalStoragesService()->deleteAllForUser($this->getUID());
yeah, the home storage gets deleted later as part of user deletion

however home storage is untouched by the any of the *storagesservice* which only operate on external storage currently

2018-06-11 17:41 UTC, mmattel commented
@sharidas any update on this ?

2018-06-12 08:43 UTC, PVince81 commented on tests/lib/Files/External/Service/GlobalStoragesServiceTest.php
> +				$this->assertTrue($this->service->deleteAllForUser($storageParams['applicableUsers'][0]));
please also verify that the "applicable" value was properly set after `deleteAllForUser` and possibly other values. Checking for the return value is not enough to ensure the function is doing its job

2018-06-19 09:51 UTC, sharidas commented on tests/lib/Files/External/Service/GlobalStoragesServiceTest.php
> +				$this->assertTrue($this->service->deleteAllForUser($storageParams['applicableUsers'][0]));
Done.

2018-06-19 15:17 UTC, PVince81 commented on lib/private/Files/External/Service/GlobalStoragesService.php
> +		$mounts = $this->getStorageForAllUsers();
here I'm wondering about scalability: if there are 10000 users and each have a mount, we're querying all possible mounts, even the personal mounts of irrelevant users

I wonder if we should split this in two parts:
1) get all personal mounts of said user, then remove said storages
and
2) get all system mounts (no personal mounts) and then filter applicable users as you did below

@butonic does that make sense or is the current solution sufficient for real-life scenarios ?

2018-06-19 15:19 UTC, PVince81 commented on tests/lib/Files/External/Service/GlobalStoragesServiceTest.php
> +					$storages = \count($this->service->getAllStorages());
you should also make sure that non-relevant storages were not deleted and are still present
for this, create a few unrelated storages and check for these

you could use the "store their id" technique after creation then requery them to see if they still exist and confirm that the correct ones are gone

2018-06-21 08:08 UTC, PVince81 commented on lib/private/Files/External/Service/GlobalStoragesService.php
> +		$mounts = $this->getStorageForAllUsers();
@sharidas let's go with the proposed approach to play it safe. Here I'm assuming that we already have the necessary API calls to retrieve this info.

2018-06-22 07:13 UTC, sharidas commented
Based on https://github.com/owncloud/core/pull/30712#discussion_r196468148 I made changes by adding an extra method at https://github.com/owncloud/core/pull/30712/files#diff-3a0ca1d458a0f44d92a863f6baf81d3dR145. I found that using this method we can get the personal mounts for a user. And the old method we have, that is, https://github.com/owncloud/core/pull/30712/files#diff-16d6579da5930e07b8c14d76623559e8R192 will try to grab the global mount points. I have tested the same with 2 users `admin` and `user1`. Where `admin` user has 2 external storages -  owncloud. And `user1` has - owncloud and SFTP. When `user1` is deleted, the `deleteAllMountsForUser()` would show 3 mounts -> owncloud, SFTP and '/user1'. And when `deleteAllForUser()` is called, 2 global storages are shown - SFTP and owncloud.
My query here would be does this approach look ok?

2018-06-25 07:55 UTC, PVince81 commented on lib/private/User/User.php
> +		\OC::$server->getUserStoragesService()->deleteAllMountsForUser($this);
`$this->getUID()` ?

2018-06-25 07:57 UTC, PVince81 commented on lib/public/Files/External/Service/IGlobalStoragesService.php
> +	 * @since 10.0.8
set to 10.0.10

2018-06-25 07:58 UTC, PVince81 commented on lib/private/User/User.php
> +		\OC::$server->getGlobalStoragesService()->deleteAllForUser($this->getUID());
be consistent: use either UID or user object

2018-06-25 12:45 UTC, sharidas commented on lib/private/User/User.php
> +		\OC::$server->getGlobalStoragesService()->deleteAllForUser($this->getUID());
Done. Prefer to use user object. Considering future usage.

2018-06-25 12:45 UTC, sharidas commented on lib/public/Files/External/Service/IGlobalStoragesService.php
> +	 * @since 10.0.8
Done

2018-06-25 12:50 UTC, sharidas commented
I have created a new file in this PR, https://github.com/owncloud/core/pull/30712/files#diff-31407757e5ad52b7e7c4a81530bb4113. The reason why I created a new file is while playing with storageId, I found that `GlobalStoragesServiceTest` extens `StoragesServiceTest` and that was causing issues while testing. So I thought its better to separate this test in a separate file.

2018-07-06 13:50 UTC, sharidas commented
@PVince81 review required.

2018-07-09 10:29 UTC, PVince81 requested changes
Looks good, there's only one additional adjustment needed to avoid performance issue by reading too many configs that aren't needed

2018-07-09 10:29 UTC, PVince81 commented on lib/private/Files/External/Service/GlobalStoragesService.php
> +		$mounts = $this->getStorageForAllUsers();
It seems this method returns not only admin mounts but also personal mounts as it uses `DBConfigService::getAllMounts()` instead of `getAdminMounts()`.

From reading the code further, it seems you'd need to call `getAllStorages()` or `getStorages()` which do call `DBConfigService::getAdminMounts()` through `StorageService::readConfig()`

2018-07-12 10:37 UTC, sharidas commented on lib/private/Files/External/Service/GlobalStoragesService.php
> +		$mounts = $this->getStorageForAllUsers();
Modified the PR, and updated the change to use `getStorages()` https://github.com/owncloud/core/pull/30712/files#diff-16d6579da5930e07b8c14d76623559e8R197

2018-07-16 12:11 UTC, PVince81 approved these changes

2018-07-16 12:11 UTC, merged

2018-07-16 12:11 UTC, PVince81 commented
@sharidas please backport

2018-08-28 15:58 UTC, phil-davis commented
@sharidas has this been backported?