[WIP] A new exception to suppress exception logs
owncloud/core pull request #30771
Opened 2018-03-13 15:56 UTC by sharidas

There are scenarios where an app would have
done the job and the logger would have logged.
But the main task would throw an exception.
Since its logged gracefully we need not throw
exception in the log. This change would help
for the same.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

There can be situations where we need not throw the exceptions to the logger. For example when an antivirus app had detected the file cannot be uploaded and logged gracefully, it would be nice to exclude the exception logged.

## Related Issue

https://github.com/owncloud/core/issues/30751

## Motivation and Context

There can be situations where we need not throw the exceptions to the logger. For example when an antivirus app had detected the file cannot be uploaded and logged gracefully, it would be nice to exclude the exception logged.

## How Has This Been Tested?

- [x] Uploaded the eicar test file and the exception is not logged.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-03-14 12:27 UTC, tomneedham commented on lib/public/Files/ExcludeForbiddenException.php
> + * Files/InvalidContentException class
?

2018-03-14 12:27 UTC, tomneedham commented on lib/public/Files/ExcludeForbiddenException.php
> + * @since 6.0.0
?

2018-03-22 19:44 UTC, VicDeo requested changes

2018-03-22 19:44 UTC, VicDeo commented on lib/public/Files/ExcludeForbiddenException.php
> + * @since 6.0.0
10.0.8 or 10.1.0 ? :unsure:

2018-03-22 19:44 UTC, VicDeo commented on lib/public/Files/ExcludeForbiddenException.php
> + * Files/InvalidContentException class
c&p ;)

2018-03-22 19:44 UTC, VicDeo commented on lib/public/Files/ExcludeForbiddenException.php
> +class ExcludeForbiddenException extends \Exception {}
What HTTP status will get a desktop client in this case, something like 50x? Imho this exception should extend `ForbiddenException`... and files_ antivirus should throw it with `$retry=true` https://github.com/owncloud/core/blob/master/lib/public/Files/ForbiddenException.php#L43

2018-03-22 19:44 UTC, VicDeo commented on apps/dav/lib/Connector/Sabre/File.php
> +			throw new UnsupportedMediaType($e->getMessage(), 0, $e);
it's not that critical to have exactly `UnsupportedMediaType` exception here. Actually I was choosing between **415 Unsupported Media Type** and **418 I'm a teapot**. And some people consider 415 status to be a bug, see https://github.com/owncloud/files_antivirus/issues/177 ;)

2018-03-26 13:58 UTC, VicDeo requested changes

2018-03-26 13:58 UTC, VicDeo commented on lib/public/Files/ExcludeForbiddenException.php
> + * Exception for invalid content
@sharidas Class description need to be updated too.   'ForbiddenException with suppressed logging' or so.

2018-03-26 14:17 UTC, sharidas commented on lib/public/Files/ExcludeForbiddenException.php
> + * Exception for invalid content
@VicDeo Done.

2018-03-27 16:55 UTC, VicDeo approved these changes

2018-03-27 16:57 UTC, VicDeo commented
Works as expected. There are no extra entries in log, Antivirus message is properly escalated to UI.

2018-03-27 17:02 UTC, VicDeo commented
@PVince81 please consider backport to stable10 or files_antivirus will need a separate branch to support  stable10

2018-03-28 08:41 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/Directory.php
> +				throw new ExcludeForbiddenException($ex->getMessage(), $ex->getRetry(), $ex);
this feels rather hacky. we can't create a subclass for every possible exception that we don't want to be logged.

or rename this exception with a name like "FileContentNotAllowedException" which is not semantically about "prevent logging" but about the actual error which is about disallowed file contents

2018-03-28 14:41 UTC, sharidas commented on apps/dav/lib/Connector/Sabre/Directory.php
> +				throw new ExcludeForbiddenException($ex->getMessage(), $ex->getRetry(), $ex);
Ok, renaming `ExcludeForbidenException` to `FileContentNotAllowedException`.
@VicDeo  I will update https://github.com/owncloud/files_antivirus/pull/219 accordingly.

2018-04-03 10:09 UTC, PVince81 commented on lib/public/Files/FileContentNotAllowedException.php
> + * @since 10.1.0
make that 10.0.8 if you think we can backport in time

2018-04-03 10:09 UTC, PVince81 approved these changes
:+1:

2018-04-03 11:02 UTC, sharidas commented
Updated the PR as requested.

2018-04-03 11:09 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/30991

2018-04-03 12:07 UTC, merged