Set empty authtoken names to 'none'
owncloud/core pull request #30815
Opened 2018-03-19 11:52 UTC by IljaN

## Description
Empty authtokens names were allowed in earlier versions, but are now disallowed. This results in a crash during login when empty authokens are encountered.

This migration sets all empty authtoken names to 'none'.

## Related Issue
#30792

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2018-03-19 12:06 UTC, IljaN commented
- [ ] Backport

2018-03-19 12:38 UTC, PVince81 commented on core/Migrations/Version20180319102121.php
> +		$q->automaticTablePrefix(true);
we never used this before I hope it doesn't break :see_no_evil:

2018-03-19 12:40 UTC, IljaN commented on core/Migrations/Version20180319102121.php
> +		$q->automaticTablePrefix(true);
Is there a better way to get the table prefix? I saw that migration kind "schema" injects prefix trough a param. But this is not the case here...

2018-03-19 12:43 UTC, IljaN commented on core/Migrations/Version20180319102121.php
> +		$q->automaticTablePrefix(true);
Or do you mean query builder?

2018-03-19 13:51 UTC, PVince81 commented on core/Migrations/Version20180319102121.php
> +		$q->automaticTablePrefix(true);
ah now I remember: you don't need to bother about table prefix. Just remove line 15 and that's it.

2018-03-21 07:48 UTC, DeepDiver1975 requested changes

2018-03-21 07:48 UTC, DeepDiver1975 commented on core/Migrations/Version20180319102121.php
> +			->where("name = ''")
use expression builder

2018-03-21 07:48 UTC, DeepDiver1975 commented on core/Migrations/Version20180319102121.php
> +			->orWhere('name IS NULL')
use expression builder

2018-03-23 08:33 UTC, IljaN commented
@DeepDiver1975 Plz merge :)

2018-03-23 16:33 UTC, PVince81 approved these changes
:+1:

2018-03-23 16:33 UTC, merged

2018-03-23 16:33 UTC, PVince81 commented
@IljaN please backport