Adding multiple role support in navigation
owncloud/core pull request #30870
Opened 2018-03-22 10:43 UTC by sharidas

The navigation manager should support multiple
roles. It was allowed to enter only one role
in the info.xml. With this change, the app
developer can provide multiple roles comma
separted for role.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

It would be nice to have multiple roles. One scenario that came to my attention was with users page. The users page should be accessible for both admin and group admin. Hence this PR helps for the same.

## Related Issue

## Motivation and Context

It would be nice to have multiple roles. One scenario that came to my attention was with users page. The users page should be accessible for both admin and group admin. Hence this PR helps for the same.

## How Has This Been Tested?

- [x] Verified that single roles and multiple roles with users page.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-03-23 16:48 UTC, PVince81 commented
Interesting. cc @pmaier1 


@sharidas what are roles ? is it an alias for groups ?

I don't remember seeing any concept of role in info.xml, would be great if you could clarify this. Maybe provide steps to demonstrate the behavior before and after your PR.

2018-03-26 06:09 UTC, sharidas commented
When I tried using user_management app, I was trying to test if everything works as before. And to my surprise it was broken when user logged in as group admin. By broken I mean, the users page wont get displayed or cannot be accessed from the UI for group admin. Had a look at market app's info.xml which showed me https://github.com/owncloud/market/blob/master/appinfo/info.xml#L28. After debugging a bit figured out we could have single value for the role in info.xml. Significance of role is : to whom should the UI of the app should be displayed. So if the role is `admin` only user logged in as admin could see the UI. If the role is `sub-admin` then sub-admin user could see it.

This also brings a question what if an app's UI should be visible or usable for both admin and sub-admin. Hence extended the info.xml to use `role="admin,sub-admin"` ( ref: https://github.com/owncloud/user_management/pull/10/files#diff-224bb875c5d3cfcd7621135069013242R15). The change in the core would help app developers to provide comma separated role ( instead of single role ). Hope this make sense?

2018-03-26 08:59 UTC, PVince81 commented
Do you mean there is a regression where a group admin cannot use the users page any more ? If yes, please bisect to find when the regression was introduced and make a p1 ticket as this is quite important and could be a release blocker.

2018-03-26 09:12 UTC, DeepDiver1975 commented
> If yes, please bisect to find when the regression was introduced and make a p1 ticket as this is quite important and could be a release blocker.

no release blocker - this is master only

the sub.admin role was introduced by myself while moving the user management app out side of the core repo

the sub-admin role was never part of stable10 -> no release blocker

2018-03-26 09:26 UTC, sharidas commented
> no release blocker - this is master only

Indeed this is not a release blocker as this issue should be there in master only.

2018-03-26 09:29 UTC, PVince81 commented
we still need a "regression" label and priority somewhere. would be good to have a ticket and clarify that it is master only

2018-03-29 12:37 UTC, DeepDiver1975 requested changes

2018-03-29 12:37 UTC, DeepDiver1975 commented on lib/private/NavigationManager.php
> +				$discontinue = false;
just continue in here

2018-03-29 12:37 UTC, DeepDiver1975 commented on lib/private/NavigationManager.php
> +			$role = explode(',', $role);
array elements need to be trimmed

2018-03-29 12:37 UTC, DeepDiver1975 commented on tests/lib/NavigationManagerTest.php
> +			]], ['navigation' => ['@attributes' => ['role' => 'admin,sub-admin'], 'route' => 'test.page.index']], false, true]
please add test for 'admin, sub-admin' and 'sub-admin' and 'admin'

2018-03-29 14:04 UTC, sharidas commented on lib/private/NavigationManager.php
> +				$shallContinue = true;
Code readability improved. ( no inverted logic ).

2018-03-29 14:04 UTC, sharidas commented on lib/private/NavigationManager.php
> +			$role = array_map('trim', $role);
Trim the elements of array.

2018-03-29 14:06 UTC, sharidas commented on tests/lib/NavigationManagerTest.php
> +			]], ['navigation' => ['@attributes' => ['role' => '   admin   '], 'route' => 'test.page.index']], true]
Added tests for "admin,sub-admin", "admin" and "sub-admin". Added tests for roles with spaces.

2018-04-12 09:30 UTC, DeepDiver1975 approved these changes

2018-04-12 09:30 UTC, merged