Run API acceptance tests on drone
owncloud/core pull request #30883
Opened 2018-03-23 11:59 UTC by phil-davis

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-03-23 12:59 UTC, SergioBertolinSG commented
When running locally I'm seeing a failure:

PHP_VERSION=7.1 DB_TYPE=mariadb USE_SERVER=true INSTALL_SERVER=true CHOWN_SERVER=true OWNCLOUD_LOG=true BEHAT_SUITE=apiWebdav TEST_SUITE=api drone exec --commit-branch master --build-event push

```
[fix-permissions:L1:2s] chown: changing ownership of '/drone/src/build/bin/bower': No such file or directory
[fix-permissions:L2:19s] chown: changing ownership of '/drone/src/core/vendor': No such file or directory
```

2018-03-23 13:14 UTC, SergioBertolinSG requested changes

2018-03-23 13:14 UTC, SergioBertolinSG commented on tests/acceptance/run.sh
> +    $OCC config:system:set trusted_domains 2 --value=federated
This part is already done here:
https://github.com/owncloud/core/blob/c036f91d180df960d4c28d6c889c5cd068e7c0ec/.drone.yml#L119-L120

2018-03-23 15:29 UTC, phil-davis commented on tests/acceptance/run.sh
> +    $OCC config:system:set trusted_domains 2 --value=federated
Thanks, I had taken that from the old "sample" code in the POC PR.

2018-03-23 16:11 UTC, patrickjahns requested changes

2018-03-23 16:11 UTC, patrickjahns commented on Jenkinsfile
> -	stage 'Acceptance Testing'
I'd like to keep the acceptance tests both running on jenkins and drone for 1-2 weeks until we have feedback

2018-03-23 16:14 UTC, patrickjahns commented
At some point it would be great to have only one entry script for running ui / api tests -> but we can tackles this with a different PR

2018-03-23 16:19 UTC, phil-davis commented on Jenkinsfile
> -	stage 'Acceptance Testing'
OK, I will remove that commit from here.

2018-03-26 04:57 UTC, phil-davis commented
@patrickjahns @SergioBertolinSG I reorganized the commits here so that the Jenkins job continues to run, with each suite running as an individual job (and of course in practice the jobs run serially on Jenkins - so there is no improvement to total elapsed time for Jenkins).

In making the separate suites, the various scenarios and setups get executed in a different order from previously if you try to run the whole API acceptance tests in a single run. That results in some errors getting reported for some tests.

PR #30902 will show what happens if we take the existing Jenkins system and simply split the API acceptance test suites. (I am guessing there will be test fails, that are existing "issues" in the test setup/teardown somewhere)

PR #30901 will show what happens if we add testing on drone, and also with the extra split of  API acceptance test suites. I expect there will be the same problems on Jenkins as in PR #30902

PR #30900 shows that just add the drone testing (the first commit in this PR #30883 ) works fine. As long as we keep the current API suite structure, we can put in the drone testing and still keep the Jenkins "single-pass" testing. It might be useful to merge just that commit in PR #30900 and then investigate what are the "latent" issues with reorganizing the API acceptance test suites.

2018-03-26 11:34 UTC, phil-davis commented
Please look at #30900 and approve if you agree. Then I can look deeper at what are the issues when reorganizing the ``apiMain`` suite into smaller pieces.

2018-03-26 16:10 UTC, phil-davis commented
I looked into the failing tests. PR #30927 has a better set of commits that fix the failing test issue, without messing with the job/s in Jenkinsfile. So that seems better, leaving Jenkinsfile completely untouched for this drone change. 

I will leave this PR open for now, until there is some positive feedback on the other PR.

2018-03-27 15:17 UTC, phil-davis commented
Superceded by #30927

2018-03-27 15:17 UTC, closed without merging