Silence retried to delete file messages
owncloud/core pull request #30974
Opened 2018-04-02 04:15 UTC by phil-davis

## Description
If the scenario step does not expect the file to be able to be deleted, then do not emit messages about "retried to delete". In this case we know that we are supposed to retry a bit, and then it is expected that we will give up and not be able to delete the file.

In this case, reduce the number of retries so we do not waste so much time rechecking that a delete really cannot be done.

## Related Issue
#30897 
This "cleanup" is to reduce "noise" in the test output, so that people do not mis-understand what is "normal" and what is a problem.

## Motivation and Context
When a test tries to delete a file, and expects that it should not be possible to delete the file, then actually the "Delete" action does not exist in the file actions menu. That is expected and what is being tested for. But while doing the checks, the code emits messages like:
```
INFORMATION: retried to delete file
Error while deleting file
```
These are disturbing to read in the test output, and can send you off looking for problems in the wrong place, when actually this is expected to happen for these test scenario steps.

When we are doing this kind of "negative" "cannot delete" test, we should not emit this noise.

## How Has This Been Tested?
Run a full set of webUI tests on Travis. Inspect the logs and see that these ``INFORMATION:`` messages no longer appear.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test refactoring

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-02 04:17 UTC, phil-davis commented
Backport ``stable10`` #30975

2018-04-03 03:59 UTC, individual-it requested changes

2018-04-03 03:59 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageBasic.php
> +	public function deleteFile($name, Session $session, $expectToDeleteFile = true, $maxRetries = STANDARDRETRYCOUNT) {
long line makes it harder to review in GitHub

2018-04-03 04:28 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageBasic.php
> +	public function deleteFile($name, Session $session, $expectToDeleteFile = true, $maxRetries = STANDARDRETRYCOUNT) {
reformat pushed

2018-04-03 05:02 UTC, individual-it approved these changes

2018-04-03 09:59 UTC, merged