[WIP] [stable10] Verify checksums command
owncloud/core pull request #31008
Opened 2018-04-04 15:59 UTC by IljaN

## Related Issue
#30951 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-04 16:00 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +				$pathWithoutUid = ltrim($path, "/{$user->getUID()}");
Improve this because path starting with username would also be trimmed

2018-04-04 16:00 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			->addOption('path', 'p', InputOption::VALUE_REQUIRED, "Specific path to check");
Implement this

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +				$pathWithoutUid = preg_replace( "/\\/{$user->getUID()}/", '', $path, 1);
I'm not sure if this will work properly... consider the following scenarios:
* user_ldap app with custom home folder (which doesn't match it's uid - check the home folder naming rule in the user_ldap configuration). This can have several problems:
    1. The preg_replace might not match anything -> you can have "abcd-1234-5678" as uid but a "user1home/thumbnails/43" path
    2. The preg_replace might match a different folder -> you can have "abcd-1234-5678" as uid but a "user1home/files/allimages/abcd-1234-5678/cities" path. While this scenario is quite unlikely to happen, the uid can also be a more common word such as "user1"
* External storages might work differently

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +		$userManager = \OC::$server->getUserManager();
This should be injected in the command

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +			$scanFunction($userManager->get($user));
I'd move the scanFunction definition to a private or public method in this class (I'm not sure if it's possible to use a private method as a callback).

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +		} else if ($user && !$userManager->userExists($user)) {
```
if ($user) {
  if ($userManager->userExists($user)) {
  } else {
  }
} else {
}
```
This feels better since the conditions are evaluated only once. In your case, if $user is empty you check for $user twice before deciding to scan all users. If the user doesn't exists, you check for 4 conditions: $user, $userManager->userExists, $user again and finally !$userManager->userExists

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +		$repairQuestion = new ConfirmationQuestion("Do you want to reset (repair) broken checksums (y/N)? ", false);
I'd rather try to fetch or create the objects we're going to use only if we're going to use them. I don't expect this to be heavy, but it should be easy to move these 2 lines inside the condition in order to create the objects and ask if it's truly needed.

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +	private static function repairChecksumsForFiles(array $files) {
why static?

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +	protected function reconnectToDatabase(OutputInterface $output) {
why protected? (I think I'll start asking this more frequently)

Good time to think about how we can do this reconnection properly? It's not the first place where I've seen this...

2018-04-06 08:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +	private static function calculateActualChecksums($path, IStorage $storage) {
why static?

2018-04-06 08:49 UTC, jvillafanez commented
If this has been tested, please specify what scenarios and setup have been tested.

2018-04-06 08:51 UTC, IljaN commented
@jvillafanez Thanks for your review,  after discussion with @DeepDiver1975  we will iterate over node api recursivly instead of using scanner

2018-04-06 08:52 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +	private static function calculateActualChecksums($path, IStorage $storage) {
I use static to mark private functions without side-effects

2018-04-06 08:53 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +	protected function reconnectToDatabase(OutputInterface $output) {
Copy paste error, protected not rquired here

2018-04-06 08:54 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			$rootFolder =  \OC::$server->getRootFolder();
:+1:

2018-04-06 08:54 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +				\OC::$server->getLogger()
:+1:

2018-04-06 08:54 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			->setDescription("Get all checksums in filecache and compares them by recalculating the checksum of the file.\n")
:+1:

2018-04-06 08:55 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +		$userManager = \OC::$server->getUserManager();
:+1:

2018-04-06 09:44 UTC, jvillafanez commented on apps/files/lib/Command/VerifyChecksums.php
> +	private static function calculateActualChecksums($path, IStorage $storage) {
hmmm, I guess from a technical perspective it's fine, but on the other hand, a private method can't be unittested (we can but it feels like hacking and also a bad practice). It's true that in this case we might not need to unittest these private methods... (we can consider this as an internal implementation, and the code is quite easy, so as long as the code is covered by some tests it shouldn't be important)

We can argue that we don't use "private static" often, so we can remove the static keyword to follow the same code style.

I don't have an opinion strong enough to go against in this case, so maybe @PVince81 for a second opinion?

2018-04-06 14:17 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +	private static function calculateActualChecksums($path, IStorage $storage) {
we have `invokePrivate` for testing private methods, let's use this if the alternative requires too much code gymnastics

2018-04-06 14:37 UTC, IljaN commented
Scanner removed, @jvillafanez tested with "old" objectstore

2018-04-06 14:43 UTC, IljaN commented
Note that path option currently does not work with objectstore: https://github.com/owncloud/objectstore/issues/90

2018-04-06 14:57 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +	private $nodesWithBrokenChecksums = [];
will this scale in case of 10k entries ? should the repair be done in a paginated manner ?

2018-04-06 14:58 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			'SHA1:%s MD5:%s ADLER32:%s',
did we have a function that specifies these exact three ? hard-coding here is a bit risky in case we ever decide to change the checksums we compute by default.

2018-04-06 14:58 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			if ($input->getOption('repair') || $questionHelper->ask($input, $output, $repairQuestion)) {
without repair option does it even make sense to cache the nodes in "nodesWithBrokenChecksums" or just output the list directly to the console ?

2018-04-06 14:59 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			$node = $this->rootFolder->get($input->getOption('path'));
how does this behave in case the path doesn't exist ?

2018-04-06 14:59 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			$output->writeln("<error>User $userName does not exist</error>");
double quotes around "$userName" for readability ?

2018-04-06 15:00 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +	private $nodesWithBrokenChecksums = [];
Probably not, but as far as I know broken checksums are a rare occurence, (10 Files in 5k files)

2018-04-06 15:01 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +				$this->walkNodes($node->getDirectoryListing(), $callBack);
can we avoid recursion in case of very deep paths ? (happened before)

maybe some iteration with `yield` ?

2018-04-06 15:01 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			$node = $this->rootFolder->get($input->getOption('path'));
Error is shown, we can catch it and output <error></error> to omit the stacktrace which occurs on console.

2018-04-06 15:05 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			if ($input->getOption('repair') || $questionHelper->ask($input, $output, $repairQuestion)) {
If repair option is not given there is a interactive prompt at the end which asks if you want to repair.

2018-04-06 15:11 UTC, PVince81 commented
- [ ] add unit tests, there are already existing examples of command tests

2018-04-06 15:11 UTC, PVince81 commented
you could use the approach from Command/ScanTest to generate some cache data, then have the test code scramble the hash value, then run the command

2018-04-06 15:11 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +			'SHA1:%s MD5:%s ADLER32:%s',
Unfortunately not could introduce a format constant inside ChecksumWrapper

2018-04-06 15:36 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +	private $nodesWithBrokenChecksums = [];
Paginated repair would be possible if we remove interactive prompt at the and, this would also solve https://github.com/owncloud/core/pull/31008#discussion_r179787185, I will go for it...

2018-04-06 15:36 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +	private $nodesWithBrokenChecksums = [];
We can repair during scan then and don`t need to collect broken files

2018-04-06 15:44 UTC, DeepDiver1975 requested changes
Tests Missing

2018-04-09 12:35 UTC, PVince81 approved these changes
Code looks good :+1: 

My comments are only little optional tweaks

2018-04-09 12:35 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			->addOption('repair', 'r', InputOption::VALUE_NONE, "Repair filecache-entry with missmatched checksums.")
s/missmatched/mismatched/

2018-04-09 12:35 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			// Files without calculated checksum can`t cause checksum errors
strange backtick, use `'` for "can't", not the backtick

2018-04-09 12:35 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +					$output->writeln("<info>Repairing!</info>");
repairing what ? (think of people grepping for this specific line who want to see what files are going to be repaired)

2018-04-09 12:35 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +		$cache->update(
I'm wondering now whether we should also trigger an etag update. If we do so, the desktop clients will redownload said files. It might not be necessary because clients that already have the file with the correct checksum can stay as is. Clients which had trouble downloading files due to mismatch checksum will anyway try again.

So no need to adjust etag.

2018-04-09 12:35 UTC, PVince81 commented on apps/files/tests/Command/VerifyChecksumsTest.php
> +			$this->assertThat(
we usually use `$this->assertSame($expectedChecksums(), $f->getChecksum())` for strict equality

2018-04-10 07:27 UTC, DeepDiver1975 requested changes

2018-04-10 07:27 UTC, DeepDiver1975 commented on apps/files/lib/Command/VerifyChecksums.php
> +				$this->walkNodes($node->getDirectoryListing(), $callBack);
valid point - as soon as we find a better solution transfer-ownership needs to be adapted (!) as well

2018-04-10 10:15 UTC, IljaN commented on apps/files/lib/Command/VerifyChecksums.php
> +				$this->walkNodes($node->getDirectoryListing(), $callBack);
@DeepDiver1975 If I understand yield correctly this change should be made inside getDirectoryListing because yield returns an iterator. This would be a bigger api change which needs good testing...

2018-04-10 10:51 UTC, DeepDiver1975 requested changes
Things seem to get mixed up in here .... please clarify - THX

2018-04-10 10:51 UTC, DeepDiver1975 commented on tests/lib/Files/ViewTest.php
> -	public function testFilePutContentsClearsChecksum() {
??? why is this test obsolete ??? 

Please add more explanation - THX

2018-04-10 10:51 UTC, DeepDiver1975 commented on lib/private/Files/Cache/Scanner.php
> +						// Only reset checksum on file change
Why is there a change to the scanner neccessary? This command no longer uses the scanner - right?

2018-04-10 10:59 UTC, PVince81 commented on tests/lib/Files/ViewTest.php
> -	public function testFilePutContentsClearsChecksum() {
This is kind of an obscure thing.

This logic was added as part of https://github.com/owncloud/core/commit/0dbcbc4cae2eb669fc73f60a761855a907469111 to fix `file_put_contents()` as used by the text editor. The reason is that said logic automatically calls `scanFile()` after updating the contents on-disk. This was related to the old checksum logic before we even had the checksum wrapper. Since we did not have a way to compute the checksum, we need to clear it.
Remembber, back in the days a checksum could only be stored when sent by the client, we did not compute on server.

As of today, the checksum wrapper is able to compute the checksum on the fly during the `file_put_contents()` operation so when it reaches the code from https://github.com/owncloud/core/pull/31008#discussion_r180376503 the checksum is already present in `$data`, so instead of clearing we use just that.

However, when dealing with external storages we still need to clear the checksum if mtime, size, etag has changed on the remote storage. (remote storage currently does not deliver a checksum)

Hope this clarifies.

2018-04-10 11:10 UTC, IljaN commented on lib/private/Files/Cache/Scanner.php
> +						// Only reset checksum on file change
@DeepDiver1975 Scanner is called when adding a file via NodeAPI

2018-04-10 12:25 UTC, PVince81 commented on lib/private/Files/Cache/Scanner.php
> +						// Only reset checksum on file change
see my explanations above

2018-04-11 09:10 UTC, butonic commented on lib/private/Files/ObjectStore/NoopScanner.php
>  		//we don't need the storage, so do nothing here
comment no longer true

2018-04-11 09:10 UTC, butonic commented on lib/private/Files/ObjectStore/NoopScanner.php
> +			$this->storage->getCache()->put(
put updates only when the data changes, which is good

2018-04-11 09:10 UTC, butonic commented on lib/private/Files/ObjectStore/NoopScanner.php
> +		$meta = $this->storage->getMetaData($path);
how expensive is this operation for objectstorages? another trip over the wire? do we get the checksum in the PUT response? can we cache that? or better yet, directly update the cache? then this commit would not be necessary

2018-04-11 09:15 UTC, DeepDiver1975 commented on lib/private/Files/ObjectStore/NoopScanner.php
> +		$meta = $this->storage->getMetaData($path);
the checksum is computed while writing - the getMetaData operation grabs the computed checksums from memory and stores them to the cache.

so no additional operation on the objectstore. no trip over the wire.

2018-04-11 10:09 UTC, mmattel commented
@settermjd FYI
@IljaN please create a doc issue inlcuding a link to this PR and if possible a PR desribing the change.

2018-04-11 10:38 UTC, DeepDiver1975 approved these changes

2018-04-11 12:52 UTC, merged