Check basic auth credentials periodically after a timeout instead of …
owncloud/core pull request #31051
Opened 2018-04-09 10:41 UTC by butonic

…every request to stop hammering ldap servers if client uses basic auth

2018-04-09 13:30 UTC, PVince81 commented
This seems somewhat redundant of `Session::checkTokenCredentials()` or maybe the latter only applied for tokens and not regular passwords ? Considering that this PR uses the exact same setting it seems the logic was copied to also apply to regular passwords.

Just wanted to make sure that this all fits together. @butonic @DeepDiver1975 can you clarify ?

2018-04-09 13:46 UTC, PVince81 commented on lib/private/User/BasicAuthModule.php
> +		$last_check_timeout = (int)$this->config->getAppValue('core', 'last_check_timeout', 5);
camel case for PHP variables, let's not go back to underscores...

2018-04-09 13:48 UTC, PVince81 commented
As I understand this only works for the combination of basic auth + session because it stores the state into the session.

So if some client is hammering the server with multiple requests and accepts cookies, it will only recheck the password periodically, not always. This also means that if a client is funny and sends a different password in the middle, it would go undetected. Not sure if that's a bad thing...

For pure basic auth (ex: cadaver) this likely will not help.

2018-04-09 15:08 UTC, tomneedham commented
> So if some client is hammering the server with multiple requests and accepts cookies, it will only recheck the password periodically, not always. This also means that if a client is funny and sends a different password in the middle, it would go undetected. Not sure if that's a bad thing...

Yes this means in between the timeout, we rely on the session for the auth.

2018-04-09 15:14 UTC, butonic commented
@PVince81 I only reused the config option name. yes it does what the token check does for basic auth. best we can do for new. proper fix is to not use a session for dav & ocs ... but that is a way bigger change.

2018-04-09 15:15 UTC, butonic commented
cadaver currently also hits ldap. no change there, yes

2018-04-09 15:18 UTC, PVince81 commented
Thanks, makes sense then. Would be good to get a review from @DeepDiver1975 or @tomneedham with who you discussed this in more detail

2018-04-10 08:26 UTC, DeepDiver1975 requested changes

2018-04-10 08:26 UTC, DeepDiver1975 commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
logging is done in deeper layers - no need here. let's remove this comment

2018-04-10 08:26 UTC, DeepDiver1975 commented on lib/private/User/BasicAuthModule.php
> +				$this->session->set('last_check_timeout', $now);
time should only be checked if checkPassword below is successful

2018-04-10 09:29 UTC, butonic commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
No. there is a difference between not being able to log in a user by username vs by email. the if statement below also needs debug log for cases when 0 ore more thin one user was found. 

If you are talking about https://github.com/owncloud/core/blob/7666497c0ada87c5df67a793e22152d478f2740a/lib/private/User/Manager.php#L253 that line uses warning ... which is bs because login via email is perfectly fine, in which case we currently ALWAYS log a warning ... which makes any admin crazy.

2018-04-10 09:33 UTC, butonic commented on lib/private/User/BasicAuthModule.php
> +		$last_check_timeout = (int)$this->config->getAppValue('core', 'last_check_timeout', 5);
I am reusing the option from the token check -> no camel case

2018-04-10 09:33 UTC, DeepDiver1975 commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
but this whole code block as of today is NOT used for login *yet* but only for verifying the auth headers. I fear we potentially pollute the log too much

2018-04-10 10:05 UTC, butonic commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
debug = I really need to know what is going on in order to debug a problem, eg why the hell is the user unable to login. we can discuss if this is debug or trace level debugging ... but the decisions are made here ... so we need the debug log here

2018-04-10 10:15 UTC, DeepDiver1975 commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
okay - debug log level is fine for me - just add it right away - THX

2018-04-10 10:31 UTC, butonic commented on lib/private/User/BasicAuthModule.php
> +			// TODO inject logger & debug log if no user was found.
There is no sich thing as too much logging. there is just not enough filtering. which brings back https://github.com/owncloud/core/pull/10405 ... we already added too much logic to log related stuff. different issue ...

2018-04-10 14:50 UTC, PVince81 commented
Ok tests pass now. Needs review approval and also some testing for the case this fixes.

Regression auth testing will be done in RC after merge.

cc @patrickjahns

2018-04-10 15:03 UTC, DeepDiver1975 approved these changes

2018-04-10 15:05 UTC, merged

2018-04-10 15:08 UTC, PVince81 commented
thanks, please backport

2018-04-10 15:15 UTC, DeepDiver1975 commented
> thanks, please backport

will do

2018-04-18 12:10 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/31076