[stable10] During chunking process the after file creation not triggered
owncloud/core pull request #31087
Opened 2018-04-11 13:24 UTC by sharidas

In the clients like android, where chunking happens for files
greater than 1MB. Under such conditions the after file creation
symfony event is not triggered. This change helps to fix the
issue.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When clients try to upload files and chunking is enabled. Then the after file creation symfony event is not triggered. This change addresses the issue.

## Related Issue

## Motivation and Context

When clients try to upload files and chunking is enabled. Then the after file creation symfony event is not triggered. This change addresses the issue.

## How Has This Been Tested?

- [x] Upload a file using android app.
- [x] The after event triggered is listened using a test app.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-04-11 13:25 UTC, sharidas commented
Original pr: https://github.com/owncloud/core/pull/31086

2018-04-11 13:47 UTC, SergioBertolinSG commented
https://github.com/owncloud/admin_audit/issues/66 is fixed with this patch.

@sharidas do you think this PR could affect other parts of the server? createFileChunked looks risky, what else should be tested before merging this?

2018-04-12 20:10 UTC, PVince81 requested changes
also need to verify that aftercreate is submitted not only of old chunking like done in this PR (remote.php/webdav) but also for new chunking (remote.php/dav/files/$user/)

2018-04-12 20:10 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +				$path = explode('/', $this->fileView->getAbsolutePath($this->path));
too hacky. doesn't `$targetPath` already contain the absolute path and file name of the final file after assembly ?

2018-04-12 20:10 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +					\OC::$server->getEventDispatcher()->dispatch('file.aftercreate', $afterEvent);
is `aftercreate` correct for all scenarios here ? do we have different events for "create a brand new file" and "overwrite an existing file" ?

2018-04-12 20:10 UTC, PVince81 commented
do we also have a matching "beforecreate" event for this scenario ?

2018-04-13 10:00 UTC, cdamken commented
@PVince81 RC2 ?
Otherwise please move to development milestone. Thanks

2018-04-13 14:04 UTC, PVince81 commented
added to my RC2 list...

2018-04-16 05:39 UTC, sharidas commented
After evaluating a bit further. I have made changes to this PR:
- [x] Create separate create and update events for `put()`
- [x] Create separate create and update for chunking method `createFileChunked()`.

The reason why create and update were required is, I observed that files can be updated and created using same calls. The unit tests were written for the same to make my observation firm.

2018-04-16 11:40 UTC, sharidas commented
Updating the tests by checking values too...

2018-04-16 12:51 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +					if (!$this->fileView->file_exists($targetPath)) {
the file always exists after upload, so this check cannot be accurate and will always say "file exists"

please cache the value at the top

2018-04-16 19:26 UTC, PVince81 approved these changes

2018-04-17 09:19 UTC, merged