During chunking process the after file creation not triggered
owncloud/core pull request #31086
Opened 2018-04-11 13:05 UTC by sharidas

In the clients like android, where chunking happens for files
greater than 1MB. Under such conditions the after file creation
symfony event is not triggered. This change helps to fix the
issue.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When clients try to upload files and chunking is enabled. Then the after file creation symfony event is not triggered. This change addresses the issue.

## Related Issue

## Motivation and Context

When clients try to upload files and chunking is enabled. Then the after file creation symfony event is not triggered. This change addresses the issue.

## How Has This Been Tested?

- [x] Upload a file using android app.
- [x] The after event triggered is listened using a test app.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-04-11 13:24 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31087

2018-04-17 09:59 UTC, PVince81 commented
please update to align the PR to its stable10 version

2018-04-18 14:42 UTC, PVince81 requested changes
needs to be updated with stable10 changes

2018-04-23 14:27 UTC, PVince81 approved these changes
:+1:

2018-04-23 14:28 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-23 14:28 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-24 14:13 UTC, PVince81 commented
@ownclouders rebase

2018-04-24 14:13 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-24 14:14 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-25 08:25 UTC, PVince81 commented
@sharidas please fix according to suggestions from PHP CS Fixer

2018-04-27 11:22 UTC, merged