Improving token_auth_enforced description text in config.sample.php
owncloud/core pull request #31101
Opened 2018-04-12 09:33 UTC by mmattel

## Description
Description improvement for the oAuth2 key ``token_auth_enforced``

## Related Issue

## Motivation and Context
Improving the description to make it more understandable what it is about

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

The documentation will be updated asap after merging.

2018-04-12 14:09 UTC, mmattel commented
Jenkins suicided ...

2018-04-13 08:06 UTC, mmattel commented on config/config.sample.php
> + * Enforces oAuth2 token only authentication for clients connecting to ownCloud.
I am happy to further imrove this config.sample.php text.
Please do any suggestion and I will incorporate it.

2018-04-16 08:38 UTC, mmattel commented
@ownclouders rebase

2018-04-16 08:38 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-16 08:38 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-16 09:56 UTC, mmattel commented
@ownclouders rebase

2018-04-16 09:56 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-16 09:57 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-16 10:16 UTC, mmattel commented
@ownclouders rebase

2018-04-16 10:16 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-16 10:16 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-16 11:28 UTC, SamuAlfageme requested changes
It actually does not require the OAuth2 app to be installed/enabled - this setting also works out for application password logins (also token-based auth.). 

More info on https://github.com/owncloud/core/issues/29300#issuecomment-337935504

2018-04-16 12:55 UTC, mmattel commented
@SamuAlfageme your statement is valid. 
I also see that the term "App Password" used in the personal settings page (just checked in my prod 10.0.7) has room for improvement to reflect what you say because we use token an password in the same context. 

I will remove the term OAuth2 from the first sentence and remove the whole last sentence as suggested.

Question: which role does OAuth2 play in this game?

2018-04-16 13:46 UTC, mmattel commented
@SamuAlfageme I adopted the text, pls check

2018-04-16 14:11 UTC, phil-davis commented
``oauth2`` is another token-based authentication method. So when ``token_auth_enforced`` is set to ``true`` then both "app/device password" and ``oauth2`` still work for authentication. "username-password" does not work (i.e. works only for the webUI login so you can get to the settings page to generate app passwords...)

2018-04-16 14:19 UTC, mmattel commented
@phil-davis anything to improve on the text or are you ok with?

2018-04-16 15:00 UTC, phil-davis commented
I am OK with it. I can't think how to mention ``oauth2`` without adding confusion.

2018-04-16 15:21 UTC, mmattel commented
I have added you as approver 😃 
In case, please also approve the backport

2018-04-16 15:26 UTC, phil-davis approved these changes

2018-04-17 08:10 UTC, SamuAlfageme commented
@mmattel @phil-davis 

> I can't think how to mention`oauth2` without adding confusion. 

... maybe consider to name _"the option to also use alternative authorization mechanisms like ownCloud's OAuth2 app"_ - also linking to https://marketplace.owncloud.com/apps/oauth2

2018-04-17 08:10 UTC, SamuAlfageme approved these changes

2018-04-17 08:13 UTC, merged