make attributes to list configurable, add verbose option
owncloud/core pull request #31115
Opened 2018-04-13 08:45 UTC by butonic

Makes `occ list:users` more useful, fully backwards compatible (if only using a single attribute the list will be in a single row for human readable output).

```
Usage:
  user:list [options] [--] [<search-pattern>]

Arguments:
  search-pattern                 Restrict the list to users whose user ID contains the optional search pattern.

Options:
      --output[=OUTPUT]          The output format to use (plain, json or json_pretty, default is plain). [default: "plain"]
  -a, --attributes[=ATTRIBUTES]  Attributes to include from uid, displayName, email, quota, enabled, lastLogin, home, backend, cloudId, searchTerms [default: ["displayName"]] (multiple values allowed)
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --no-warnings              Skip global warnings, show command output only
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  List users and their attributes.
```

eg
```console
% ./occ user:list           
  - 34C3F461-90FE-417C-ADC5-CE97FE5B8E72: Carol
  - 53CDB5AC-B02E-4A49-8FEF-001A13725777: David
  - 9F625F70-08DD-4838-AD52-7DE1F72DBE30: Bobbie
  - B5275C13-6466-43FD-A129-A12A6D3D9A0D: Alicia3
  - admin: admin
  - foo: foo
% ./occ user:list -a enabled 
  - 34C3F461-90FE-417C-ADC5-CE97FE5B8E72: true
  - 53CDB5AC-B02E-4A49-8FEF-001A13725777: true
  - 9F625F70-08DD-4838-AD52-7DE1F72DBE30: true
  - B5275C13-6466-43FD-A129-A12A6D3D9A0D: true
  - admin: true
  - foo: true
% ./occ user:list --output=json
{"34C3F461-90FE-417C-ADC5-CE97FE5B8E72":{"displayName":"Carol"},"53CDB5AC-B02E-4A49-8FEF-001A13725777":{"displayName":"David"},"9F625F70-08DD-4838-AD52-7DE1F72DBE30":{"displayName":"Bobbie"},"B5275C13-6466-43FD-A129-A12A6D3D9A0D":{"displayName":"Alicia3"},"admin":{"displayName":"admin"},"foo":{"displayName":"foo"}}
% ./occ user:list --output=json -a enabled
{"34C3F461-90FE-417C-ADC5-CE97FE5B8E72":{"enabled":true},"53CDB5AC-B02E-4A49-8FEF-001A13725777":{"enabled":true},"9F625F70-08DD-4838-AD52-7DE1F72DBE30":{"enabled":true},"B5275C13-6466-43FD-A129-A12A6D3D9A0D":{"enabled":true},"admin":{"enabled":true},"foo":{"enabled":true}}
% ./occ user:list -a email -a enabled
  - 34C3F461-90FE-417C-ADC5-CE97FE5B8E72:
    - email: carol@example.org
    - enabled: true
  - 53CDB5AC-B02E-4A49-8FEF-001A13725777:
    - email: dave@example.org
    - enabled: true
  - 9F625F70-08DD-4838-AD52-7DE1F72DBE30:
    - email: bobbie@example.org
    - enabled: true
  - B5275C13-6466-43FD-A129-A12A6D3D9A0D:
    - email: alicia3@example.org
    - enabled: true
  - admin:
    - email
    - enabled: true
  - foo:
    - email
    - enabled: true
% ./occ user:list -a email -a enabled --output=json
{"34C3F461-90FE-417C-ADC5-CE97FE5B8E72":{"email":"carol@example.org","enabled":true},"53CDB5AC-B02E-4A49-8FEF-001A13725777":{"email":"dave@example.org","enabled":true},"9F625F70-08DD-4838-AD52-7DE1F72DBE30":{"email":"bobbie@example.org","enabled":true},"B5275C13-6466-43FD-A129-A12A6D3D9A0D":{"email":"alicia3@example.org","enabled":true},"admin":{"email":null,"enabled":true},"foo":{"email":null,"enabled":true}}
% ./occ user:list -v --output=json_pretty B5275C13-6466-43FD-A129-A12A6D3D9A0D
{
    "B5275C13-6466-43FD-A129-A12A6D3D9A0D": {
        "uid": "B5275C13-6466-43FD-A129-A12A6D3D9A0D",
        "displayName": "Alicia3",
        "email": "alicia3@example.org",
        "quota": "default",
        "enabled": true,
        "lastLogin": 1523542266,
        "home": "\/var\/www\/html\/core\/data2\/alicia@example.org",
        "backend": "LDAP",
        "cloudId": "B5275C13-6466-43FD-A129-A12A6D3D9A0D@localhost",
        "searchTerms": [
            "zombie1000",
            "alicia3@example.org",
            "\u0013\\'"
        ]
    }
}
```

2018-04-13 09:29 UTC, mmattel commented
@butonic mind to add [stable10] in the PR text in front 😄

2018-04-13 09:32 UTC, mmattel commented
This needs in case of merging a documentation change.
To be added:
``  -a, --attributes[=ATTRIBUTES]  Attributes to include from uid, displayName, email, quota, enabled, lastLogin, home, backend, cloudId, searchTerms [default: ["displayName"]] (multiple values allowed)
``

@settermjd fjy

2018-04-13 10:28 UTC, felixboehm commented
code looks good

2018-04-13 10:43 UTC, phil-davis commented
Note when testing: see issue #31117 - the ``occ`` user and group list commands are currently making you put at least the (configurable, default 4) minimum number of characters in order to do a "filtered" listing of users (or groups). So you cannot (currently) add a user ``abc`` and
```
./occ user:list abc
```
You get no output.

So when testing using the search-pattern parameter, create long UIDs!

2018-04-13 10:54 UTC, phil-davis approved these changes
WFM

2018-04-13 10:55 UTC, phil-davis commented
Backport mean forward-port in this case.

2018-04-13 12:47 UTC, butonic commented
- [ ] fixme -a option without argument is possible - options are ALWAYS optional ...

2018-04-16 23:41 UTC, tomneedham commented
Looks good. Needs a command test to make codecov happy - even if just a sanity execution to check it doesn't explode.

2018-04-17 08:04 UTC, PVince81 commented
after talking with @pmaier1 let's defer this to 10.0.9 as there is no time left

2018-04-23 14:46 UTC, PVince81 commented
Fixes https://github.com/owncloud/core/issues/28056

2018-04-25 09:08 UTC, PVince81 commented
@ownclouders rebase

2018-04-25 09:08 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-25 09:08 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-25 10:48 UTC, butonic commented
adding test

2018-04-27 12:28 UTC, DeepDiver1975 requested changes

2018-04-27 12:28 UTC, DeepDiver1975 commented on core/Command/User/ListUsers.php
> +				InputOption::VALUE_IS_ARRAY|InputOption::VALUE_REQUIRED,
why required? default to userid and have the behavior as before

2018-04-27 12:37 UTC, jvillafanez commented on core/Command/User/ListUsers.php
> +					switch ($attribute) {
I'd prefer to figure out something to improve this. 90% of the function just to generate the output doesn't look good.

2018-04-27 12:46 UTC, butonic commented on core/Command/User/ListUsers.php
> +				InputOption::VALUE_IS_ARRAY|InputOption::VALUE_REQUIRED,
VALUE_REQUIRED just means that the option must have a value, not that the option itself is required. Options are always optional ...

2018-04-27 12:48 UTC, butonic commented on core/Command/User/ListUsers.php
> +				InputOption::VALUE_IS_ARRAY|InputOption::VALUE_REQUIRED,
A already fall back to the userid. In fact, I went the extra mile to make human readable output use a single line if only one attribute is requested to match the current output.

2018-04-27 12:57 UTC, butonic commented on core/Command/User/ListUsers.php
> +					switch ($attribute) {
The logic was added to match the current human readable output:
```
% ./occ user:list           
  - 34C3F461-90FE-417C-ADC5-CE97FE5B8E72: Carol
  - 53CDB5AC-B02E-4A49-8FEF-001A13725777: David
  - 9F625F70-08DD-4838-AD52-7DE1F72DBE30: Bobbie
  - B5275C13-6466-43FD-A129-A12A6D3D9A0D: Alicia3
```

without this the output always introduces a newline:
```
% ./occ user:list -a email -a enabled
  - 34C3F461-90FE-417C-ADC5-CE97FE5B8E72:
    - displayName: Carol
  - 53CDB5AC-B02E-4A49-8FEF-001A13725777:
    - displayName: David
  - 9F625F70-08DD-4838-AD52-7DE1F72DBE30:
    - displayName: Bobbie
  - B5275C13-6466-43FD-A129-A12A6D3D9A0D:
    - displayName: Alicia3
```
This would break any scrips out there that parse this list, which is tempting because it used to be all in one line.

If we fix this it needs to be done in `core/Command/Base::writeArrayInOutputFormat`, but in a different PR.

2018-04-27 13:27 UTC, DeepDiver1975 approved these changes

2018-04-27 13:37 UTC, jvillafanez commented on core/Command/User/ListUsers.php
> +					switch ($attribute) {
We should think about what commands needs human-readable output and / or scriptable output, and how we can be provide that.
I think we should focus on human-readable output by default. We can use json as scriptable output if needed for the moment, or add other formats, but human-readable output shouldn't be parsed.

I don't think the command should need to worry about the formatting of the output.

2018-04-27 15:03 UTC, butonic commented on core/Command/User/ListUsers.php
> +					switch ($attribute) {
I know that it shouldn't be parsed ... but making it two lines is a lot harder to parse for my eyes as well

2018-04-27 15:03 UTC, merged

2018-05-02 10:15 UTC, phil-davis commented
Forward port to master is PR #31298