Ability to log extra fields
owncloud/core pull request #31121
Opened 2018-04-13 13:27 UTC by PVince81

## Description
If a logger supports it like the default logger, additional fields can
now be added to the base JSON object.

Built to still support old loggers so this shouldn't break any API contracts.

## Related Issue
None

## Motivation and Context
Some log analyzers prefer to have the fields directly appearing in the base JSON object instead of serialized into strings.

## How Has This Been Tested?
Add `\OC::$server->getLogger()->error("Test extra fields", ['app' => 'test', 'extraFields' => ['hello' => 'field', 'another' => 'field']]);` to Sabre\Directory constructor and open the web UI.
Then check the logs:
```
{"reqId":"S9ulvAzpHQcTLEtVRMPf","level":3,"time":"2018-04-13T13:22:51+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"test","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Test extra fields","hello":"field","another":"field"}
```

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-13 14:32 UTC, PVince81 commented
Added https://github.com/owncloud/core/pull/31121/commits/95cd4e4e895dd9f5e9ed373ce109535d0e680a58 and updated OP with section 2

2018-04-13 14:37 UTC, butonic commented
- [ ] allow syslog logger to log these extra attributes? see https://github.com/owncloud/core/pull/31124

2018-04-13 15:01 UTC, PVince81 commented
> allow syslog logger to log these extra attributes

separately

2018-04-13 15:02 UTC, PVince81 commented
I force pushed matching unit tests in each of the former commits

2018-04-16 08:12 UTC, butonic commented
when forward porting, this will interfere with https://github.com/owncloud/core/pull/31072

backport https://github.com/owncloud/core/pull/31072 and rebase this PR on top of it?

2018-04-16 08:12 UTC, butonic requested changes
when forward porting, this will interfere with #31072

backport #31072 and rebase this PR on top of it?

2018-04-16 09:45 UTC, DeepDiver1975 approved these changes

2018-04-16 09:46 UTC, DeepDiver1975 commented
failing jenkins can be ignored -> merging

2018-04-16 09:46 UTC, merged

2018-04-16 10:03 UTC, DeepDiver1975 commented
> when forward porting, this will interfere with #31072
> 
> backport #31072 and rebase this PR on top of it?

this optimization is actually reverted now with this PR

2018-04-16 11:25 UTC, PVince81 commented
> this optimization is actually reverted now with this PR

To clarify: it is a requirement to be able to send the event with the log message even if the message will not be logged with the current log level. It is for external logging apps that might have their own levels.

If interpolation is a problem we could decide to remove it from the event and expect the hook listener to redo the interpolation if needed.

2018-05-15 12:59 UTC, mmattel commented
@PVince81 @DeepDiver1975 @settermjd 
are these new extra fields + events something that should be documented, eg in https://github.com/owncloud/documentation/blob/master/developer_manual/app/fundamentals/logging.rst or in any othe place?

2018-05-22 10:45 UTC, PVince81 commented
@mmattel good point. Raised here: https://github.com/owncloud/documentation/issues/4162