Master 7ff1236ec41bfd74ccd92762442072113e7b3f61
owncloud/core pull request #31135
Opened 2018-04-16 10:03 UTC by DeepDiver1975

*port of #31121

2018-04-16 11:41 UTC, butonic requested changes

2018-04-16 11:41 UTC, butonic commented on lib/private/Log.php
> +		$formattedMessage = $this->interpolate($message, $context);
interpolation should only happen after the event has been handled. The app might want to change the context before interpolating. move this inside the `if ($level >= $minLevel) {`

2018-04-16 12:17 UTC, DeepDiver1975 commented on lib/private/Log.php
> +		$formattedMessage = $this->interpolate($message, $context);
see my comment on the original PR of this event dispatching of log messages.
the performance optimization is obsolete because the formatted message is part of the event which is dispatched in any case.

2018-04-19 12:55 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-04-19 12:55 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-19 12:55 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-24 07:53 UTC, PVince81 commented
added commit from https://github.com/owncloud/core/pull/31247

2018-05-10 13:54 UTC, tomneedham commented
IMO remove optimisation - separate PR, target master then backport, like usual. Now we're messing with a forward port and it's going to end in tears.

2018-06-03 22:33 UTC, patrickjahns commented
@DeepDiver1975 @PVince81 - any update?

2018-06-11 09:15 UTC, PVince81 commented
blocks forward port of https://github.com/owncloud/core/pull/31623

2018-06-28 12:11 UTC, PVince81 commented on lib/private/Log.php
> +		$formattedMessage = $this->interpolate($message, $context);
We'd then need to expose the interpolation method to hook listeners.

I agree with @DeepDiver1975 and would like to move forward and merge this

2018-07-03 07:12 UTC, DeepDiver1975 commented on lib/private/Log.php
> +		$formattedMessage = $this->interpolate($message, $context);
redoing the interpolation on all listeners will duplicate the calls - not optimal either.

2018-07-03 07:12 UTC, DeepDiver1975 commented
merging this to move on

2018-07-03 07:12 UTC, merged