Improve text in settings/personal App Password
owncloud/core pull request #31159
Opened 2018-04-17 09:26 UTC by mmattel

## Description

The text ``App Password`` can be improved because it is used as token.
Passwords have a meaning for the user and token getting its ground too.

## Related Issue

https://github.com/owncloud/core/issues/31140 ([Feature Request] Better naming for "App-Password" in settings/personal)
https://github.com/owncloud/core/pull/31101 (Improving token_auth_enforced description text in config.sample.php)

## Motivation and Context

Improve readability and link the word password and token in this context

## How Has This Been Tested?

Text change only

## Screenshots (if appropriate):
**Before:**
![image](https://user-images.githubusercontent.com/3321281/38860974-bf0876d2-4231-11e8-8cc2-2a0a63fc1372.png)

**After:**
![image](https://user-images.githubusercontent.com/3321281/38860788-505840be-4231-11e8-9f1c-b5c84aaa84ba.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-17 09:55 UTC, phil-davis commented on settings/templates/panels/personal/tokens.php
> +		<button id="add-app-password" class="button"><?php p($l->t('Create new app passcode')); ?></button>
I guess this is consistent with the explanation text above that says ``An app password or token is a passcode``

```
passcode = [ 'password', 'token' ]
```
Will changing this word here confuse or enlighten people?
Actually I am not sure - opinions?

2018-04-17 16:17 UTC, mmattel commented on settings/templates/panels/personal/tokens.php
> +		<button id="add-app-password" class="button"><?php p($l->t('Create new app passcode')); ?></button>
![image](https://user-images.githubusercontent.com/3321281/38882808-7a9cdd5a-426b-11e8-809c-38536ef48b79.png)

2018-04-25 05:00 UTC, mmattel commented
Any more comments or a approvals ?

2018-04-26 07:26 UTC, PVince81 commented
I'd like to have a review from @pmaier1 as well

2018-05-16 16:37 UTC, pmaier1 requested changes
Good point in general, agreed. What do you think about adding a hint on what app passwords are actually good for? "Use these as a security measure to hide your actual password which you only use for the web interface login." or similar/better English ;)

2018-05-16 19:34 UTC, mmattel commented
@pmaier1 added your suggestion, please check

2018-05-17 01:10 UTC, phil-davis commented
@ownclouders rebase

2018-05-17 10:52 UTC, mmattel commented
@pmaier1 @phil-davis  can you take a look why the drone build fails. I do not see a relationship to this PR?

2018-05-17 12:04 UTC, phil-davis commented
@mmattel there is no ``apiProvisioning`` suite any more - -they are now called ``apiProvisioing-v1`` and ``apiProvisioning-v2``
You just need to rebase to current ``master`` - make sure to first get the current ``master`` locally (``git fetch origin`` ``git pull`` - that sort of stuff) and then rebase to it and force push.

2018-05-18 09:29 UTC, mmattel commented
@pmaier1 @phil-davis checks passed 😄

2018-05-18 09:40 UTC, phil-davis approved these changes
LGTM

2018-05-22 09:21 UTC, mmattel commented
@pmaier1 merge?

2018-05-22 11:00 UTC, pmaier1 approved these changes

2018-05-22 11:02 UTC, pmaier1 requested changes

2018-05-22 11:02 UTC, pmaier1 commented on settings/templates/panels/personal/tokens.php
> +		<button id="add-app-password" class="button"><?php p($l->t('Create new app passcode')); ?></button>
"passcode" is inconsistent with "password" in the headline. Why change?

2018-05-24 08:19 UTC, mmattel commented on settings/templates/panels/personal/tokens.php
> +		<button id="add-app-password" class="button"><?php p($l->t('Create new app passcode')); ?></button>
Historically the text contained the word password which is not correct in the context of oauth2.
The correct naming is token (or passcode). Sadly the documentation used password too. 
To bridge the old with the correct one, I used this way for a smooth transition.
App passwords or tokens are passcodes --> passcode is the common of them all...

2018-05-25 12:47 UTC, pmaier1 commented on settings/templates/panels/personal/tokens.php
> +		<button id="add-app-password" class="button"><?php p($l->t('Create new app passcode')); ?></button>
I'm sorry but this has nothing to do with OAuth2. It is a separate feature called "App passwords" that generates passwords/passcodes to be used in a single client to avoid using the user's regular login password. Anyway, I find it inconsistent but will approve.

2018-05-25 12:47 UTC, pmaier1 approved these changes

2018-05-27 18:48 UTC, merged

2018-06-08 14:02 UTC, phil-davis commented
Backport ``stable10`` #31539