Fix mail debug message recipient field
owncloud/core pull request #31227
Opened 2018-04-20 14:29 UTC by PVince81

## Description
For public link shares we use the BCC field now, so this one isn't logged properly.
This PR logs all the recipients as taken from To, CC and BCC now.
Also it uses `json_encode()` for a nicer formatting that looks less shitty than `Array( ... )`

## Related Issue
None

## Motivation and Context

## How Has This Been Tested?
Set "loglevel" to 0 and observe log.
Allow users to send share emails.
- [ ] TEST: public link email single recipient
- [ ] TEST: public link email multiple recipients
- [ ] TEST: internal share email single recipient
- [ ] TEST: internal share email group recipient

Before the fix: shitty empty `Array()` in log for public link email.
After the fix: both email types have a proper array with all recipients

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-20 23:18 UTC, DeepDiver1975 requested changes

2018-04-21 09:55 UTC, DeepDiver1975 commented
@ownclouders rebase

2018-04-21 09:55 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-21 09:55 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-23 10:31 UTC, PVince81 commented on lib/private/Mail/Mailer.php
> +		$logMessage = sprintf('Sent mail from "{from}" to "{recipients}" with subject "{subject}"');
argh, forgot to remove

2018-04-23 10:33 UTC, PVince81 commented
removed sprintf

2018-04-23 14:01 UTC, PVince81 commented
@ownclouders rebase

2018-04-23 14:02 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-04-23 14:02 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-23 16:28 UTC, phil-davis commented
All stable10 Jenkins are failing like this - I ran a test PR this morning #31240 to confirm.

2018-04-23 19:24 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-04-23 20:38 UTC, patrickjahns approved these changes
LGTM

2018-04-24 07:54 UTC, merged

2018-04-24 07:56 UTC, PVince81 commented
master: https://github.com/owncloud/core/pull/31254