[stable10] Add events for user preference changes
owncloud/core pull request #31266
Opened 2018-04-25 13:35 UTC by PVince81

## Description
Add events for user preference changes

## Related Issue
Fixes https://github.com/owncloud/core/issues/31264

## Motivation and Context

## How Has This Been Tested?
- [ ] add unit tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-27 07:27 UTC, PVince81 commented
@sharidas please take over and add tests

(and port to master after merge)

2018-04-27 11:55 UTC, PVince81 commented
unfortunately I didn't find how to trigger the "delete app" code path, it is possible that this can only be triggered by uninstalling an app through the app manager in the settings page

2018-04-27 12:44 UTC, PVince81 commented
Testing code looks fine. @sharidas please review my part and test, thanks

2018-04-27 12:44 UTC, sharidas commented
@PVince81 Yes I am trying to check the delete app part.

2018-04-27 13:29 UTC, sharidas commented
Modified the code in `disableapp.php`
```
//OC_App::disable($appId);
\OC::$server->getConfig()->deleteAppFromAllUsers($appId);
```
And clicked disable. Traced the code flow and found that before and after events are executed.

2018-04-27 13:50 UTC, sharidas commented
- `deleteUserValue()` call is verified using debugger. When user logs in the before and after events (`userpreferences.beforedeletevalue` and `userpreferences.afterdeletevalue`) are emitted from LoginController.
- `deleteAllUserValues()` remove the user. Verified that before and after events (`userpreferences.beforedeleteuser` and `userpreferences.afterdeleteuser`) are triggered.
- `setUserValue()` call is verified. The rain loop app when enabled and as admin user when tried to logout both `userpreferences.beforesetvalue` and `userpreferences.aftervalue` are emitted successfully.

2018-04-30 08:36 UTC, sharidas commented
Forward port to master branch: https://github.com/owncloud/core/pull/31307

2018-04-30 08:39 UTC, sharidas commented
Tried to improve code of `AllConfig.php` a little more ( which is not part of the PR ).

2018-05-04 09:04 UTC, jvillafanez commented
I'd rather avoid the use of traits and use DI instead. The problem I see is that you're forced now to use whatever object the trait uses in the tests, and you can't mock it. Basically, you aren't unittesting the class because you're using another object in the tests.

This problem is also affecting the tests: ideally the tests should just check that an event has been triggered using something like:
```
$dispatcherMock->expects($this->once())->method('dispatch')->with($this->equalTo('event.name'), $this->equalTo($eventMock));
```

There is the additional problem of code readability the `$this->emittingCall` call.
```
$dispatcher->dispatch('event1', $event);
/*
 * Do a lot of stuff
 */
$dispatcher->dispatch('event2', $event);
```
This seems quite easier to read and understand than using the `$this->emittingCall`

For the specific events, I don't know what do we want exactly. I see an usability problem which might be a bit difficult to solve. Right now, if I'm interested in a specific key to be deleted, I should listen to the `userpreferences.afterdeletevalue` event, but I won't get any event if any of the other delete method is used. Basically, you're forcing people to listen to all those events.

In addition, note that we have to keep consistency with the event names, specially if we don't use custom events (whose name could be easily be inside a class constant). I think all the event names are camel-case, so using other kind of names will be confusing.

2018-05-04 10:43 UTC, sharidas commented
@jvillafanez So from https://github.com/owncloud/core/pull/31266#issuecomment-386543876 I do understand that I would have to update the PR, using DI and try to remove traits. But I have a query regarding 

> Right now, if I'm interested in a specific key to be deleted, I should listen to the userpreferences.afterdeletevalue event, but I won't get any event if any of the other delete method is used

Even for each delete events we have different events emitted. I am not clear here.

2018-05-10 13:16 UTC, sharidas commented
I guess it would be better to document this scenario. I am having a very ugly solution of passing cache to the event argument, which can not be considered.

2018-05-17 14:16 UTC, PVince81 commented on lib/private/AllConfig.php
> +		$this->eventDispatcher->dispatch('userpreferences.afterdeletevalue',
why are you sending "afterdeletevalue" before actually deleting the value from the DB ?

2018-05-23 16:32 UTC, jvillafanez commented
Since we won't use custom events for now, at least we should keep the event names consistent. I think all the event names are camelcase, so we should stick with this convention.

2018-05-25 14:36 UTC, sharidas commented
@jvillafanez The only reason why camelcase wasn't used is because of https://symfony.com/doc/current/components/event_dispatcher.html#naming-conventions. If we still need camel case, then I can do it.

2018-05-28 06:05 UTC, sharidas commented on lib/private/AllConfig.php
> +		$this->eventDispatcher->dispatch('userpreferences.beforedeleteuser', new GenericEvent(null, $arguments));
Yes we have `user.afterdelete` here -> https://github.com/owncloud/core/blob/master/lib/private/Server.php#L341

2018-05-28 07:10 UTC, jvillafanez commented on lib/private/AllConfig.php
> +		$this->eventDispatcher->dispatch('userpreferences.beforedeleteuser', new GenericEvent(null, $arguments));
They are different events. This one is triggered when all the keys are deleted, not when the user is deleted. We might want to delete all the keys but not the user (it's a weird case, but it might happen).
The question is whether we want to trigger this one or not. I'd rather keep it for the sake of consistency.

2018-05-28 07:20 UTC, sharidas commented on lib/private/AllConfig.php
> +		$this->eventDispatcher->dispatch('userpreferences.beforedeleteuser', new GenericEvent(null, $arguments));
@jvillafanez Indeed I agree with you to have this one. My intention behind sharing the link was to point out: we have event for deleting the user. But we don't have the one for deleting keys of user.

2018-05-28 07:20 UTC, jvillafanez commented
> The only reason why camelcase wasn't used is because of https://symfony.com/doc/current/components/event_dispatcher.html#naming-conventions. If we still need camel case, then I can do it.

Then we have a problem. The event names aren't consistent with what we have in other parts of the code. I don't think we can change the rest of the code at this moment. Unless someone says otherwise, I'd prioritize consistency

2018-05-28 07:37 UTC, sharidas commented
> Unless someone says otherwise, I'd prioritize consistency

I have changed event names to camel case.

2018-05-29 10:26 UTC, PVince81 commented
@jvillafanez @sharidas just be consistent with whatever case we have used for all the other symfony events we already have. Here use the format we used for the appconfig ones for consistency at least across config related events.

2018-05-31 11:38 UTC, jvillafanez commented on lib/private/AllConfig.php
> +		if (null !== $preCondition) {
I'd rather switch the condition: `if ($precondition !== null)`

2018-05-31 11:38 UTC, jvillafanez commented on lib/private/AllConfig.php
> +	public function __construct(SystemConfig $systemConfig, EventDispatcher $eventDispatcher = null) {
I'm not sure about not requiring the eventDispatcher. Note that if the event dispatcher isn't injected, we won't send notifications (nobody will be listener to events dispatched by the one created inside this class). This can be confusingin the long run.
If there is a use case where we don't want to send these events, there might be better ways to do it.

2018-05-31 11:52 UTC, sharidas commented on lib/private/AllConfig.php
> +		if (null !== $preCondition) {
Updated, with `if ($precondition !== null)`

2018-05-31 11:54 UTC, sharidas commented on lib/private/AllConfig.php
> +	public function __construct(SystemConfig $systemConfig, EventDispatcher $eventDispatcher = null) {
@jvillafanez I have updated the constructor and hence made changes in places where the changes are required.

2018-05-31 11:57 UTC, phil-davis commented on lib/private/AllConfig.php
> +		if (null !== $preCondition) {
The anti-Yoda code style checks will not like anyway, when a forward-port to master is attempted.
Poor Yoda, loved his grammar is not.

2018-05-31 12:43 UTC, jvillafanez commented on lib/base.php
> +		$fakeRequest = new \OC\AppFramework\Http\Request($params, null, new \OC\AllConfig(new \OC\SystemConfig(self::$config), new \Symfony\Component\EventDispatcher\EventDispatcher()));
I'd include a comment here. The dispatcher we're injecting will act as a dummy (which I think it fine in this case). The comment should help to clarify that we don't expect events to be listened here, so it isn't a bug that modifications in the configuration made by the fake request (which in fact there isn't a reason to do so) won't throw events.
In addition, split the line because it's too long

2018-05-31 12:54 UTC, sharidas commented on lib/base.php
> +		$fakeRequest = new \OC\AppFramework\Http\Request($params, null, new \OC\AllConfig(new \OC\SystemConfig(self::$config), new \Symfony\Component\EventDispatcher\EventDispatcher()));
Done.

2018-06-01 09:22 UTC, butonic requested changes
`user` would indicate the user object, `userId` should be used. If you must I would accept `uid`.

2018-06-01 09:22 UTC, butonic commented on lib/private/AllConfig.php
> +			'user' => $userId, 'key' => $key, 'value' => $value,
`'userId' => $userId, 'key' => $key, 'value' => $value,` or
`'uid' => $userId, 'key' => $key, 'value' => $value,`

2018-06-01 09:48 UTC, sharidas commented on lib/private/AllConfig.php
> +			'user' => $userId, 'key' => $key, 'value' => $value,
Updated. Replaced `user` with `uid`.

2018-06-04 14:51 UTC, PVince81 commented
As I see the comments were adressed :+1:

2018-06-04 14:51 UTC, merged

2018-06-04 14:51 UTC, PVince81 commented
@sharidas please port to master

2018-06-04 17:14 UTC, sharidas commented
Master branch PR updated: https://github.com/owncloud/core/pull/31307