The Great Fix of object store acceptance tests ....
owncloud/core pull request #31285
Opened 2018-04-26 14:51 UTC by DeepDiver1975

## Description
This PR holds a great variety of fixes which are needed to pass our acceptance test suites.

## Related Issue
refs https://github.com/owncloud/files_primary_s3/pull/48

## Motivation and Context
Acceptance tests should run properly with objectstore as well

## How Has This Been Tested?
- manually
- ci on https://github.com/owncloud/files_primary_s3/pull/48

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-05-03 14:30 UTC, phil-davis commented on tests/acceptance/features/apiTrashbin/trashbin-new-endpoint.feature
> +    @skip-on-objectstore
And use one of the "standards" for naming:
API acceptance tests have made tag names like ``skip_on_objectstore``
webUI acceptance tests have made camelCase tag name like ``skipOnLDAP``
hmmm - it's a shame these diverging "standards" happen.

2018-05-03 14:32 UTC, DeepDiver1975 commented on tests/acceptance/features/apiTrashbin/trashbin-new-endpoint.feature
> +    @skip-on-objectstore
> indentation

github display issue from my pov - I have 4 spaces locally ....

2018-05-03 14:40 UTC, DeepDiver1975 commented on tests/acceptance/features/apiTrashbin/trashbin-new-endpoint.feature
> +    @skip-on-objectstore
underscores are so damn ugly ... I hate them in each and every owncloud app name .....

2018-05-03 15:28 UTC, patrickjahns commented on tests/acceptance/features/apiTrashbin/trashbin-new-endpoint.feature
> +    @skip-on-objectstore
> hmmm - it's a shame these diverging "standards" happen. 

we can refactor and unify it again - if we have a standard we can also document it and ask people to follow it. Worst case, have a gherkin "code-style" in place

2018-05-03 15:29 UTC, DeepDiver1975 commented on tests/acceptance/features/apiTrashbin/trashbin-new-endpoint.feature
> +    @skip-on-objectstore
adopted to existing standard with _

2018-05-04 11:08 UTC, butonic requested changes

2018-05-04 11:08 UTC, butonic commented on lib/private/Files/ObjectStore/NoopScanner.php
> +		if (isset($meta['checksum']) && !empty($meta['checksum'])) {
redundant, only  `!empty` is sufficient, see https://stackoverflow.com/a/4559976

2018-05-04 15:55 UTC, patrickjahns commented on lib/private/Files/ObjectStore/NoopScanner.php
> +		if (isset($meta['checksum']) && !empty($meta['checksum'])) {
Not exactly - different behaviors: https://www.virendrachandak.com/techtalk/php-isset-vs-empty-vs-is_null/

2018-05-14 09:55 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		if ($pathSections[0] !== 'files' && \in_array($storagePrefix, ['home', 'object'], true)) {
Why object?

2018-05-14 09:56 UTC, mrow4a commented on lib/private/User/User.php
> +		Storage::remove('object::user:' . $this->getUID());
so there are now two homes for user?

2018-05-14 09:57 UTC, mrow4a commented on lib/private/Files/Cache/Propagator.php
> +			$builder->execute();
:>

2018-05-14 10:03 UTC, mrow4a commented on apps/dav/lib/DAV/CopyPlugin.php
>  				$destinationNode->put($sourceNode->get());
`$destinationNode->put` itself is not setting locks ? Need to go deeper, it is a logic of put itself, isnt it?

2018-05-14 13:41 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +		if ($pathSections[0] !== 'files' && \in_array($storagePrefix, ['home', 'object'], true)) {
There are basically two different types of storage prefixes: 'home' for regular file system and 'object' for objectstore - the later part was missing in some places - fixed in this PR

2018-05-14 13:41 UTC, DeepDiver1975 commented on lib/private/User/User.php
> +		Storage::remove('object::user:' . $this->getUID());
see above

2018-05-14 13:42 UTC, DeepDiver1975 commented on lib/private/Files/Cache/Propagator.php
> +			$builder->execute();
:twisted_rightwards_arrows:

2018-05-14 13:44 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/CopyPlugin.php
>  				$destinationNode->put($sourceNode->get());
search for other places there put is used - the node is locked before

2018-05-14 13:51 UTC, mrow4a commented on lib/private/Share20/DefaultShareProvider.php
> +		if ($pathSections[0] !== 'files' && \in_array($storagePrefix, ['home', 'object'], true)) {
ok, makes sense!

2018-05-14 13:51 UTC, mrow4a commented on lib/private/User/User.php
> +		Storage::remove('object::user:' . $this->getUID());
can be something else then X=user in object::X:  ?

2018-05-17 09:28 UTC, butonic commented on lib/private/Files/ObjectStore/NoopScanner.php
> +		if (isset($meta['checksum']) && !empty($meta['checksum'])) {
`isset` checks if the variable, in this case the array key is set, and the value is **not** `null`.
`!empty` does the same thing: `empty` will check if the the array key is set, and the value **is** `null` (or `''`, `'0'`, `0`, `0.0`, `false` or `[]`). the result is negated. it literally checks what `isset` did again.

You could nitpick that `!empty` will return false for `'0'`, `0`, `0.0` ... which may or may not be valid checksums. But I think @DeepDiver1975 just added the empty check to handle `''` correctly. And checksums with `''`, `'0'`, `0`, `0.0`, `null`, `false` or `[]` dont make much sense.

Get rid of the `isset`. it is redundant.

2018-05-17 14:44 UTC, butonic approved these changes

2018-05-17 14:49 UTC, merged

2018-05-18 11:43 UTC, patrickjahns commented
Since this PR got merged, I am seeing frequent issues in the logfile 

```
{"reqId":"PvBstjnGLSwoDKQm9Ktg","level":3,"time":"2018-05-18T11:35:12+00:00","remoteAddr":"172.20.0.5","user":"user1","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/users\/user1","message":"fclose() expects parameter 1 to be resource, object given at \/var\/www\/owncloud\/lib\/private\/legacy\/util.php#437"}
```

2018-05-18 12:09 UTC, mrow4a commented
Can you track down in what case this copyr gets object instead of resource and how to reproduce it ?

2018-05-18 12:11 UTC, patrickjahns commented
first guess as it just accesses `/ocs/v1.php/cloud/users/user1` - this might be related to ocs api calls - will push some more objectstorage tests into apps and get steps to reproduce

2018-05-18 12:49 UTC, DeepDiver1975 commented
copyr is used to copy over the skeleton files on first login ...

2018-05-23 18:25 UTC, mrow4a commented
No idea, I have never been in that part of code - it is also legacy - I assumed it fixes some bug, but apparently it makes some tests fail, probably also because of how unit tests are mocking things.

2018-05-28 05:47 UTC, phil-davis commented
I fixed other things in the test scenario "Trashbin can be emptied" in master PR https://github.com/owncloud/core/pull/31523
When backporting to stable10, I discovered that I needed the commit:
"Handle CSRF token errors on ajax/delete.php request"
from here.
That was because I  fixed scenario "Trashbin can be emptied" so that it really worked, and had the possibility to fail.
So that commit "Handle CSRF token errors on ajax/delete.php request" has been backported to stable10 as part of https://github.com/owncloud/core/pull/31536

2018-05-28 05:48 UTC, phil-davis commented
@DeepDiver1975 what is happening about backporting this PR?
It would be nice to have at least other bits-and-pieces from here backported, if not the whole PR.

2018-06-12 11:22 UTC, phil-davis commented
@DeepDiver1975 what is the status of backporting this PR?

This is another one that seems to have a pile of commits gathering..

2018-06-12 11:39 UTC, phil-davis commented
I am looking through the listed of clossed PRs that still have backport-request label.
Thankfully most are easy, like this. The backport has been done and just the label needs to be removed.