Master symfony user preferences
owncloud/core pull request #31307
Opened 2018-04-30 06:40 UTC by sharidas

## Description

Add events for user preference changes

## Related Issue

Fixes https://github.com/owncloud/core/issues/31264

## Motivation and Context

## How Has This Been Tested?

- [x] add unit tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-04-30 08:36 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31266

2018-06-05 07:37 UTC, DeepDiver1975 requested changes

2018-06-05 07:37 UTC, DeepDiver1975 commented on lib/private/AllConfig.php
> +
one day we need to use query builder everywhere .....

2018-06-05 07:37 UTC, DeepDiver1975 commented on tests/lib/AllConfigTest.php
> +		$this->eventDispatcher = new  EventDispatcher();
I would have a used a mock here .... no need to run all the event dispatcher logic
and there is one space too much ;-)

2018-06-05 07:37 UTC, DeepDiver1975 commented on tests/lib/AllConfigTest.php
> +		$this->eventDispatcher->addListener('userpreferences.beforeSetValue',
This code should read much easier using a mock

```php
$this->eventDispatcher->expects($this->once())->method('dispatch')->with('userpreferences.beforeDeleteApp', new GenericEvent(null, [....]))

2018-06-05 08:54 UTC, PVince81 commented
@sharidas when backporting or forward porting please make sure it is clear. When reading this PR it looks like this is the original PR but it isn't. The original PR is the stable10 one and this one here is a forward port. And now you're getting review change requests for something that is just a port.

2018-06-05 09:04 UTC, PVince81 commented on tests/lib/AllConfigTest.php
> +		$this->eventDispatcher = new  EventDispatcher();
it's easier to use the real object instead of mocking all its methods (I tried to mock this one in another PR and gave up). To note is that we use a standalone dispatcher and not the real `\OC::$server->getEventDispatcher()` because that would register and trigger events for the whole system

2018-06-05 09:06 UTC, PVince81 commented
@DeepDiver1975 considering that this is a master port (wasn't clear from the first post), I'd rather keep the code as is. If you think this code must absolutely be changed then we shall do so in a separate PR that we will backport again to stable10.

2018-06-05 09:21 UTC, sharidas commented
Sorry for the confusion created. This PR is a forward port from https://github.com/owncloud/core/pull/31266 ( which is merged ).

2018-06-05 09:43 UTC, phil-davis commented
The challenge with forward-ports is that extra CI in ``master``` (like codecov) might point out some issue or deficiency that is already in the code merged to ```stable10``
In most cases, code should first be done in ``master``. If the code concept needs to also be demonstrated for ``stable10``  (e.g. related to behavior of old versions of dependencies or...) then it would be best to develop 2 PRs,, 1 for each branch, to see that it can work for both. Then at the end make a "proper" backport from ```master`` ...

2018-06-05 09:49 UTC, PVince81 commented
@phil-davis ok that makes sense. The original stable10 PR was created on said branch to save some time back then in case it was needed quickly. You pointed out good reasons to continue starting with master first.

2018-06-05 09:53 UTC, DeepDiver1975 commented
> @DeepDiver1975 considering that this is a master port (wasn't clear from the first post), I'd rather keep the code as is.

yes - agreed

>  If you think this code must absolutely be changed then we shall do so in a separate PR that we will backport again to stable10.

I'd really like this to be changed @sharidas please have a look if time permits and @PVince81 agrees as well

2018-06-05 09:54 UTC, DeepDiver1975 commented
> In most cases, code should first be done in master.

this is the prime rule for many years - whenever we broke this rule - code broke as well.

2018-06-05 09:57 UTC, merged

2018-06-05 09:57 UTC, PVince81 commented
@sharidas has the requested changes ready, please push to a separate master PR which we will backport after review. Thanks

2018-06-05 09:58 UTC, DeepDiver1975 commented on tests/lib/AllConfigTest.php
> +		$this->eventDispatcher = new  EventDispatcher();
only one method needs to me mocked and the assertion code is much less - see below