[WIP] split UID unto userId (user_id) and userName (lower_user_id)
owncloud/core pull request #31335
Opened 2018-05-02 15:01 UTC by butonic

## Description
This PR allows renaming usernames by
* treating the lower_user_id column as the user name 
* treading the user_id column as a generated user id
* existing code asking for the uid will get the user_id, making migration unneeded:
  * existing users will keep their user_id
  * new users will get a generated id, the username will be stored in the lower_user_id column

Requires https://github.com/owncloud/user_management/pull/27

# TODO
- [ ] rename lower_user_id column - deferred for now for easier testing
- [ ] Work on the tests

## Related Issue

- fixes https://github.com/owncloud/core/issues/6984
- allows us to subsequently do https://github.com/owncloud/core/issues/29503
- deprecates https://github.com/owncloud/core/pull/30617

## Motivation and Context

username != userid != display name

## How Has This Been Tested?

manual testing, waiting for ci

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-02 15:54 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Accidentally added to the commit
(easily done with ``git add -A``)

2018-05-02 17:15 UTC, DeepDiver1975 requested changes

2018-05-02 17:15 UTC, DeepDiver1975 commented on lib/public/IUserManager.php
> +	 * @deprecated use getByUserId or getByUserName to clarify code
This is rather radical. Im not Happy about this

2018-05-02 18:33 UTC, butonic commented on lib/public/IUserManager.php
> +	 * @deprecated use getByUserId or getByUserName to clarify code
the code using this method still works as expected, but I deprecated the method to make sure developers start switching to getByUserId or getByUserName (or getByEMail) to make the intention of the code always clear.

2018-05-06 16:46 UTC, mrow4a commented on lib/private/User/Database.php
> +		// username on next login?
What is the problem with `@` in username?

2018-05-06 16:48 UTC, mrow4a commented on lib/private/User/Database.php
> +		// TODO ... we could use the displayname column to store the login.
Ok, just to be clear, userName == displayName == login ?

2018-05-06 16:50 UTC, mrow4a commented on lib/private/User/Manager.php
> +	public function createUser($uid = null, $password, $userName = null) {
Ok, I have to admit, this is confusing. Why `$uid` can be null?

2018-05-06 16:51 UTC, mrow4a commented on lib/private/User/Manager.php
> +		return $this->emittingCall(function () use (&$uid, &$password, &$backend, &$userName) {
what about userName before backend?

2018-05-06 16:51 UTC, mrow4a commented on lib/private/User/Session.php
> +	public function login($loginName, $password) {
Ok, cool :>

2018-05-06 16:55 UTC, mrow4a commented on lib/public/IUserManager.php
> +	 * @deprecated use getByUserId or getByUserName to clarify code
Why couldn't `get` imply `getByUserId` ?

2018-05-06 16:55 UTC, mrow4a commented on lib/public/IUserManager.php
> +	public function createUser($uid = null, $password, $userName = null);
Why `uid` can be null? I think you mention you want it later to be account_id, am I correct?

2018-05-06 16:56 UTC, mrow4a commented on lib/public/IUserManager.php
> +	public function createUserFromBackend($uid, $password, $backend, $userName);
username before backend?

2018-05-06 16:57 UTC, mrow4a reviewed
There are many unclear parts to me, also having similar doubt as Thomas

2018-05-07 10:10 UTC, butonic commented on lib/public/IUserManager.php
> +	 * @deprecated use getByUserId or getByUserName to clarify code
It does. But it is used as `getByUserName`. So I need to check every occurence of the get call to double check if it the parameter that is used is really the userid or actually the username. Prominent examples? 
https://github.com/owncloud/core/blob/78eca952cdcae27e049d1a1f126eef164c0ec27d/lib/private/User/Session.php#L621-L626
https://github.com/owncloud/core/blob/78eca952cdcae27e049d1a1f126eef164c0ec27d/lib/private/User/Manager.php#L273-L282

get() still works. It internally uses getByUserID. But we should make as clear as we can how to use it. That means deprecating get() und using properly named functions. This is about readability. And there is nothing radical about it. Existing code will still work.

2018-05-07 10:14 UTC, butonic commented on lib/private/User/Database.php
> +		// username on next login?
so a user uses `foo@bar.com` to login. which user is it when there is a user with the username `foo@bar.com` and a user with the userid `evilmcknevil` who has the email `foo@bar.com`. Who do you then login? no one? the one where the password matches? users currently can just change their email. and it is not even unique. but we still allow login by email. so if I want to prevent you from logging in with your email I just set my email to yours. I hope you still know your username to log in with it. Oh wait ... you username IS your email ... too bad for you... this affects all existing guest users.

2018-05-07 10:17 UTC, butonic commented on lib/private/User/Database.php
> +		// TODO ... we could use the displayname column to store the login.
userName != displayName != login

checkPassword gets the login and password. but the database backend does not store the username. only the userid. I was thinking about misusing the displayname as username, but It makes more sense to actually lookup the userid with the login and then check the password for that uiserid.

2018-05-07 10:19 UTC, butonic commented on lib/private/User/Manager.php
> +	public function createUser($uid = null, $password, $userName = null) {
so that the current code to create users still works. The create User method is used in many places. This will make existing code, that does not know about the userid / username split, work correctly: If you do not pass a username, uid will be used as username and the userId will be generated.

2018-05-07 10:25 UTC, butonic commented on lib/public/IUserManager.php
> +	public function createUser($uid = null, $password, $userName = null);
legacy code will only call `createUser('foo','secret')` -> the new implementation will use 'foo' as userName and generate a userId
now code can call `createUser(null, 'secret', 'foo')` to achieve the same thing or call `createUser('c30cf2d0-51e0-11e8-b566-0800200c9a66','secret','foo')` if it wants to also set the uid, which makes sense for ldap, which provides a uuid attribute that is used to identify users when syncing them

2018-05-07 10:26 UTC, butonic commented on lib/public/IUserManager.php
> +	public function createUserFromBackend($uid, $password, $backend, $userName);
would change the api

2018-06-04 14:23 UTC, butonic commented on lib/public/IUser.php
> +	public function getUserId();
Well ok, this won't work, because adding methods to existing public interfaceslike this  will break code that implements these interfaces.

2018-06-04 14:45 UTC, butonic commented on lib/public/IUser.php
> +	public function getUserId();
@DeepDiver1975 I wish we would use abstract classes for the API classes that are intended to be used by apps, eg the `IUserManager` or `IUser`. Not being able to add methods is rather painful. We should add an `AbstractUser` and expose that in the AppFramework.

see https://theamiableapi.com/java-cl-section-2-1/#cl.item.2.1.8. I know that is java ... it still holds true for the app framework:
> Abstract classes can be used everywhere Java interfaces can with the limitation that a class can only extend a single (abstract) superclass while it can implement multiple interfaces. In most APIs Java’s lack of support for multiple class inheritance is not an issue because the interfaces are _**not intended to be implemented by clients**_. In these cases abstract classes are the better design choice.

2018-07-24 12:18 UTC, PVince81 commented
@butonic any plans to finish this ? if not, please put it in a form that someone can take over, expand the concept parts a bit

2018-07-31 10:37 UTC, butonic commented
@PVince81 I would like to make the differentiation between userid and username explicit, by deprecating get() which has no clear meaning. We can leave it in with the meaning of getUserId or gerUserName. Most existing codepaths expect uid. That is what this PR implements. The current problem is installation, which first creates an admin user and then executes the migrations. But this pr changes the checkpassword call and that causes havoc because it no longer works with the old tables... Will continue after vacations.

2019-02-18 09:23 UTC, butonic commented
We introduced a username into the public IUser interface with https://github.com/owncloud/core/pull/31951/files#diff-dc2e2ee403cebc838875eddf32a8a7beR56 The internal User class implements in using the preferences table. It is used to allow syncing the login (samaccountname) from ldap and use it to mound a wnd. This works but could be further developed to move the username into the account table. Actually the lower_user_id column should be renamed to username and any username from the preferences table should be copied to the column in the account table.

This PR now documents some of the challenges that are involved in doing that, because a naive approach will cause the installation to fail.

Anyway, since I assume user management will be handled differently with OCIS which is based on OpenID Connect, I will unassign myself and close this PR.

2019-02-18 09:23 UTC, closed without merging