Do not set the password again if it hasn't changed
owncloud/core pull request #31367
Opened 2018-05-07 08:41 UTC by jvillafanez

## Description
Do not set the password again in case the permissions has changed.

## Related Issue
Reported for 10.0.8 in https://central.owncloud.org/t/password-request-for-link-share/13342

## Motivation and Context

## How Has This Been Tested?
Manually tested for 10.0.8

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-07 09:57 UTC, jvillafanez commented
Backport in https://github.com/owncloud/core/pull/31370

2018-05-07 15:31 UTC, patrickjahns commented
@jvillafanez 
please provide a digest for the test information either in a github ticket or in the PR - when testing the changelog it is a mess if you have to read through a central post to determine if it works as desired

2018-05-07 15:31 UTC, patrickjahns requested changes
Missing test steps

2018-05-28 15:38 UTC, PVince81 commented
@ownclouders rebase

2018-05-28 15:38 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-05-28 15:38 UTC, PVince81 approved these changes
Code looks fine :+1:

2018-05-28 15:40 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-05-29 10:23 UTC, merged

2018-06-08 13:41 UTC, phil-davis commented
Backport happened - removing backport-request label