VerifyChecksum: Ignore files which are in filecache but not in the storage
owncloud/core pull request #31430
Opened 2018-05-14 12:29 UTC by IljaN

## Description
The verifier currently produces false-positives for files which are in filecache but not on the storage.

## Related Issue
https://github.com/owncloud/enterprise/issues/2518

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-14 12:37 UTC, patrickjahns commented
Shouldn't this require a normal `occ file:scan` then?

2018-05-18 13:44 UTC, PVince81 requested changes
one major issue with instance of check and a few minor ones

2018-05-18 13:44 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +			if ($storage instanceof ISharedStorage || $storage instanceof FailedStorage) {
`$storage->instanceOfStorage(ISharedStorage::class)` because of storage wrappers... please closely follow how the Util\Scanner does it

2018-05-18 13:44 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +				$output->writeln("Skipping $owner/$path => File is in file-cache but doesn`t exist on storage/disk", OutputInterface::VERBOSITY_VERBOSE);
use apostrophe and not backtick for "doesn't"

make sure to replace every other occurrence if any

an alternative is to use "does not"

2018-05-18 13:44 UTC, PVince81 commented on apps/files/lib/Command/VerifyChecksums.php
> +		$statResult = $node->stat();
I see we don't have a method `->exists()` on the node, ok.

Now I wonder what happens if the file happens to not be readable due to messed up permissions. Maybe also check `$node->isReadable()` ?

2018-05-23 14:50 UTC, PVince81 commented
@IljaN please adjust tests for code coverage. The new conditions aren't called by tests.

If needed you can check the unit tests for the Util/Scanner

2018-06-05 18:31 UTC, PVince81 commented
I've added tests for the test coverage.

Note that for the `stat()` call I had to add an `@` sign to prevent a PHP warning to be logged.

2018-06-07 15:14 UTC, PVince81 commented
make linter happy...

2018-06-08 07:46 UTC, PVince81 commented
oh noes... Oracle :cry: 

```
1) OCA\Files\Tests\Command\VerifyChecksumsTest::testSkipNoStoredChecksum
Failed asserting that 'This operation might take quite some time.
Checking 1-verifycheksums7uC2gMxQjBNp4/files/dir/nested/somefile.txt => SHA1:2ef7bde608ce5404e97d5f042f95f89f1c232871 MD5:ed076287532e86365e841e92bfc50d8c ADLER32:1c49043e
Checking 1-verifycheksums7uC2gMxQjBNp4/files/dir/nested/somefile2.txt => SHA1:77ba9cd915c8e359d9733edcfe9c61e5aca92afb MD5:e48e13207341b6bffb7fb1622282247b ADLER32:01fe00cf
Checking 1-verifycheksums7uC2gMxQjBNp4/files/dir/nested/subdir/hallo2.txt => SHA1:f8df862af4cbfed3e19b561186005d353261d2c3 MD5:1e2cb228ed73c2122f0f3a08c1976425 ADLER32:1c1004a4
Checking 1-verifycheksums7uC2gMxQjBNp4/files/otherdir/bar.txt => SHA1:749de5cc8ef9ff0fb0869179ea66555c2dff2fbf MD5:4c843bd5e890558b89583052fe61a44c ADLER32:03620142
Checking 1-verifycheksums7uC2gMxQjBNp4/files/rootfile.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
Checking 1-verifycheksums7uC2gMxQjBNp4/files/song.mp3 => SHA1:7bb865d84faf4da193fd2736ec7a3738bccff7d9 MD5:52a8552679a800dcaf01f2df4702089b ADLER32:576b0859
Checking 2-verifycheksums9FKdeKjGBV8x4/files/bling.tif => SHA1:308c265b9b9b0d9124cf090181f9157135dc0841 MD5:77f200afb4245c9d13d1c502a844730e ADLER32:1a9803fa
Checking 2-verifycheksums9FKdeKjGBV8x4/files/pong.tif => SHA1:7b52009b64fd0a2a49e6d8a939753077792b0554 MD5:c20ad4d76fe97759aa27a0c99bff6710 ADLER32:00960064
Checking 2-verifycheksums9FKdeKjGBV8x4/files/sdvsdvs/secrets/bar/baz/moo.txt => SHA1:f05ea879e5531704ed3f85fab6be849531fe60df MD5:384ecbcf3e7e60e4f7e83a6507221580 ADLER32:19a9044b
Checking 2-verifycheksums9FKdeKjGBV8x4/files/welcome.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
' contains "Skipping 1-verifycheksums7uC2gMxQjBNp4/files/dir/nested/somefile.txt".

/drone/src/apps/files/tests/Command/VerifyChecksumsTest.php:400
```

2018-06-08 08:10 UTC, PVince81 commented
it seems that when telling Oracle to clear the checksum by setting it to empty string it doesn't actually reset it... might need to set it to "null" instead.

I wonder if other code paths where we try to clear stuff fail with Oracle :see_no_evil:

2018-06-08 08:27 UTC, PVince81 commented
we need to fix the file cache, I'd rather to this separately first: https://github.com/owncloud/core/issues/31692

2018-07-05 10:35 UTC, IljaN commented
:crossed_fingers:

2018-07-16 07:01 UTC, PVince81 commented
now it's only codecov again. I can't open the report though...

2018-07-16 14:21 UTC, IljaN commented
:crossed_fingers: :crossed_fingers:

2018-07-23 14:58 UTC, PVince81 commented
```
1) OCA\Files\Tests\Command\VerifyChecksumsTest::testFileWithoutChecksumIsIgnored
Failed asserting that 'This operation might take quite some time.
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/dir/nested/somefile.txt => SHA1:2ef7bde608ce5404e97d5f042f95f89f1c232871 MD5:ed076287532e86365e841e92bfc50d8c ADLER32:1c49043e
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/dir/nested/somefile2.txt => SHA1:77ba9cd915c8e359d9733edcfe9c61e5aca92afb MD5:e48e13207341b6bffb7fb1622282247b ADLER32:01fe00cf
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/dir/nested/subdir/hallo2.txt => SHA1:f8df862af4cbfed3e19b561186005d353261d2c3 MD5:1e2cb228ed73c2122f0f3a08c1976425 ADLER32:1c1004a4
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/otherdir/bar.txt => SHA1:749de5cc8ef9ff0fb0869179ea66555c2dff2fbf MD5:4c843bd5e890558b89583052fe61a44c ADLER32:03620142
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/rootfile.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
Checking 1-verifycheksumsgEEvlSgfKbg6i/files/song.mp3 => SHA1:7bb865d84faf4da193fd2736ec7a3738bccff7d9 MD5:52a8552679a800dcaf01f2df4702089b ADLER32:576b0859
Checking 2-verifycheksumsiZetO2ZpuAwlA/files/bling.tif => SHA1:308c265b9b9b0d9124cf090181f9157135dc0841 MD5:77f200afb4245c9d13d1c502a844730e ADLER32:1a9803fa
Checking 2-verifycheksumsiZetO2ZpuAwlA/files/pong.tif => SHA1:7b52009b64fd0a2a49e6d8a939753077792b0554 MD5:c20ad4d76fe97759aa27a0c99bff6710 ADLER32:00960064
Checking 2-verifycheksumsiZetO2ZpuAwlA/files/sdvsdvs/secrets/bar/baz/moo.txt => SHA1:f05ea879e5531704ed3f85fab6be849531fe60df MD5:384ecbcf3e7e60e4f7e83a6507221580 ADLER32:19a9044b
Checking 2-verifycheksumsiZetO2ZpuAwlA/files/welcome.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
' contains "somefile.txt => No Checksum".

/drone/src/apps/files/tests/Command/VerifyChecksumsTest.php:316
```

not sure if this is up to date though

2018-08-03 15:26 UTC, PVince81 commented
@ownclouders rebase

2018-08-03 15:26 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-08-03 15:27 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-08-06 09:15 UTC, PVince81 commented
Oracle failure:
```
There was 1 failure:

1) OCA\Files\Tests\Command\VerifyChecksumsTest::testFileWithoutChecksumIsIgnored
Failed asserting that 'This operation might take quite some time.
Checking 1-verifycheksumsy8HROuV53cdZi/files/dir/nested/somefile.txt => SHA1:2ef7bde608ce5404e97d5f042f95f89f1c232871 MD5:ed076287532e86365e841e92bfc50d8c ADLER32:1c49043e
Checking 1-verifycheksumsy8HROuV53cdZi/files/dir/nested/somefile2.txt => SHA1:77ba9cd915c8e359d9733edcfe9c61e5aca92afb MD5:e48e13207341b6bffb7fb1622282247b ADLER32:01fe00cf
Checking 1-verifycheksumsy8HROuV53cdZi/files/dir/nested/subdir/hallo2.txt => SHA1:f8df862af4cbfed3e19b561186005d353261d2c3 MD5:1e2cb228ed73c2122f0f3a08c1976425 ADLER32:1c1004a4
Checking 1-verifycheksumsy8HROuV53cdZi/files/otherdir/bar.txt => SHA1:749de5cc8ef9ff0fb0869179ea66555c2dff2fbf MD5:4c843bd5e890558b89583052fe61a44c ADLER32:03620142
Checking 1-verifycheksumsy8HROuV53cdZi/files/rootfile.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
Checking 1-verifycheksumsy8HROuV53cdZi/files/song.mp3 => SHA1:7bb865d84faf4da193fd2736ec7a3738bccff7d9 MD5:52a8552679a800dcaf01f2df4702089b ADLER32:576b0859
Checking 2-verifycheksumskcqMUUbwMMHM3/files/bling.tif => SHA1:308c265b9b9b0d9124cf090181f9157135dc0841 MD5:77f200afb4245c9d13d1c502a844730e ADLER32:1a9803fa
Checking 2-verifycheksumskcqMUUbwMMHM3/files/pong.tif => SHA1:7b52009b64fd0a2a49e6d8a939753077792b0554 MD5:c20ad4d76fe97759aa27a0c99bff6710 ADLER32:00960064
Checking 2-verifycheksumskcqMUUbwMMHM3/files/sdvsdvs/secrets/bar/baz/moo.txt => SHA1:f05ea879e5531704ed3f85fab6be849531fe60df MD5:384ecbcf3e7e60e4f7e83a6507221580 ADLER32:19a9044b
Checking 2-verifycheksumskcqMUUbwMMHM3/files/welcome.doc => SHA1:d58f12c8b4ccdf68b6bd115ad8ce8af7d6f48c46 MD5:cbff38f3fa5224405e56bb3feae869d0 ADLER32:2bf605e7
' contains "somefile.txt => No Checksum".

/drone/src/apps/files/tests/Command/VerifyChecksumsTest.php:316
```

2018-08-15 11:38 UTC, IljaN commented
@ownclouders rebase

2018-08-15 11:38 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-08-15 11:40 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-08-15 14:58 UTC, IljaN commented
Looks like #32248 fixed this :tada:

2018-08-16 09:59 UTC, IljaN commented
Backport #32360

2018-08-16 10:50 UTC, DeepDiver1975 approved these changes

2018-08-16 10:51 UTC, merged

2018-08-28 15:48 UTC, phil-davis commented
Backport in #32360 has been merged.