Add symfony events for tag actions
owncloud/core pull request #31505
Opened 2018-05-23 06:59 UTC by sharidas

For the following actions on tag the symfony
events will be dispatched:
a) create
b) update
c) delete

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Create symfony events for create, update and delete actions on tag.

## Related Issue

## Motivation and Context

Create symfony events for create, update and delete actions on tag.

## How Has This Been Tested?

- [x] Using unit test

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-29 10:03 UTC, PVince81 requested changes
see comments

2018-05-29 10:03 UTC, PVince81 commented on apps/systemtags/lib/Activity/Listener.php
> +				['subject' => Extension::CREATE_TAG,
subject is redundant information: it is already possible to know the action from the event name

it would be good to use a similar pattern like the other events we already have

2018-05-29 10:03 UTC, PVince81 commented on apps/systemtags/lib/Activity/Listener.php
> +					'newTag' => $event->getTag()->getName(), 'previousTag' => $event->getTagBefore()->getName()]);
in the share event we had "name" and "oldName", why not use a similar pattern and call the arguments "tagName" and "oldTagName" ?

2018-05-29 10:04 UTC, PVince81 commented on apps/systemtags/lib/Activity/Listener.php
> +				['subject' => Extension::CREATE_TAG,
I understand that you wanted to be consistent with activity entries below. However I think it would be better to have all events consistent between each other instead

2018-05-31 10:09 UTC, sharidas commented on apps/systemtags/lib/Activity/Listener.php
> +					'newTag' => $event->getTag()->getName(), 'previousTag' => $event->getTagBefore()->getName()]);
Updated to `tagName` and `oldTagName` respectively.

2018-06-01 09:31 UTC, butonic requested changes

2018-06-01 09:31 UTC, butonic commented on apps/systemtags/lib/Activity/Listener.php
> +					'uid' => $actor,
In the beginning of this function remember the user object:
```php

 		$user = $this->session->getUser();
 		if ($user instanceof IUser) {
 			$actor = $actor->getUID();
 		} else {
 			$actor = '';
 		}
```

then you can add user object to the event:
```php
			$genericEvent = new GenericEvent(null,	[
				'action' => 'create',
				'user' => $user,
	 			'tagName' => $event->getTag()->getName()
			]);
```

objects are always more useful than mere ids

2018-06-01 09:39 UTC, sharidas commented on apps/systemtags/lib/Activity/Listener.php
> +					'uid' => $actor,
Done.

2018-06-04 07:45 UTC, butonic requested changes
This PR does not make sense. The `OCP\SystemTag\ManagerEvent`s are emitted by the `OC\SystemTag\SystemTagManager` and this class just consumes them to add an activity. re-emitting these events makes no sense. Or I don't get it. Please explain?

2018-06-04 07:45 UTC, butonic commented on apps/systemtags/tests/ListenerTest.php
> +		$this->assertEquals('foo', $calledCreateEvent[1]->getArgument('user')->getUID());
here you are testing if your mockup works. use `$this->assertSame($iUser, $calledCreateEvent[1]->getArgument('user'));`
1. you want to use assertSame to check the objects literally **are** the same.
2. getUID has only been implemented as a mock, no need to test the mock works as expected

2018-06-04 07:45 UTC, butonic commented on apps/systemtags/tests/ListenerTest.php
> +		$this->assertEquals('foo', $calledCreateEvent[1]->getArgument('user')->getUID());
here you are testing if your mockup works. use `$this->assertSame($iUser, $calledCreateEvent[1]->getArgument('user'));`
1. you want to use assertSame to check the objects literally **are** the same.
2. getUID has only been implemented as a mock, no need to test the mock works as expected

2018-06-04 07:45 UTC, butonic commented on apps/systemtags/tests/ListenerTest.php
> +		$this->assertEquals('foo', $calledCreateEvent[1]->getArgument('user')->getUID());
here you are testing if your mockup works. use `$this->assertSame($iUser, $calledCreateEvent[1]->getArgument('user'));`
1. you want to use assertSame to check the objects literally **are** the same.
2. getUID has only been implemented as a mock, no need to test the mock works as expected

2018-06-04 07:45 UTC, butonic commented on apps/systemtags/lib/Activity/Listener.php
> +					'tagName' => $event->getTag()->getName(), 'oldTagName' => $event->getTagBefore()->getName()]);
you should just pass the tag object ... wait ... why are we even implementing this?

2018-06-04 08:16 UTC, sharidas commented
Changes requested for this PR are done:
- [x] https://github.com/owncloud/core/pull/31505#discussion_r192647628
- [x] https://github.com/owncloud/core/pull/31505#discussion_r192647858
- [x] https://github.com/owncloud/core/pull/31505#discussion_r192647888
- [x] https://github.com/owncloud/core/pull/31505#discussion_r192650101 ( passed the tag object )

2018-06-04 11:08 UTC, sharidas commented
Closing this PR as we have references to the events dispatched in the `SystemTagManager.php`.
These are the events that already exist:
- [x] create - https://github.com/owncloud/core/blob/2038c0b0cf57f739c74162fec653162abaefc2f0/lib/private/SystemTag/SystemTagManager.php#L221
- [x] update - https://github.com/owncloud/core/blob/2038c0b0cf57f739c74162fec653162abaefc2f0/lib/private/SystemTag/SystemTagManager.php#L276
- [x] delete https://github.com/owncloud/core/blob/2038c0b0cf57f739c74162fec653162abaefc2f0/lib/private/SystemTag/SystemTagManager.php#L321

2018-06-04 11:08 UTC, closed without merging