Use the userid obtained from checkPassword after login is validated
owncloud/core pull request #31515
Opened 2018-05-24 05:17 UTC by sharidas

The user id sent to the after event should use the id obtained
from checkPassword method, which validates the login credentials
passed to loginWithPassword method. This change would help the
the subscriber of the after event to get the appropriate userid.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Use the uid returned from `checkPassword()` instead of the uid passed to `loginWithPassword()`. Updated the after event data accordingly to pick the uid.

## Related Issue

https://github.com/owncloud/core/issues/31509

## Motivation and Context

Use the uid returned from `checkPassword()` instead of the uid passed to `loginWithPassword()`. Updated the after event data accordingly to pick the uid.

## How Has This Been Tested?

- [x] With the unit test written for `loginWithPassword()`

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-24 07:17 UTC, butonic requested changes
thx for trying to fix this. uid vs login is not clear everywhere. see individual comments

2018-05-24 07:17 UTC, butonic commented on lib/private/User/Session.php
> +		return $this->emittingCall(function (&$afterArray) use (&$uid, &$password) {
try `return $this->emittingCall(function (&$afterArray) use ($uid, $password) {`

2018-05-24 07:17 UTC, butonic commented on lib/private/User/Session.php
> +					$afterArray['uid'] = $user->getUID();
why not pass in the user object? `$afterArray['user'] = $user;` the old hook does the same thing in https://github.com/owncloud/core/pull/31515/files#diff-9c47cee6ac987e5256aeee509f91ddb1R502

An object is much more useful than the uid as string

2018-05-24 07:17 UTC, butonic commented on tests/lib/User/SessionTest.php
> +		$this->assertArrayHasKey('uid', $calledBeforeEvent[1]);
in the before event this is not the uid, but the login (email or username). please rename the key to `login`. `uid` is just plain wrong. changeit in https://github.com/owncloud/core/pull/31515/files#diff-9c47cee6ac987e5256aeee509f91ddb1R517

2018-05-24 07:17 UTC, butonic commented on lib/private/User/Session.php
>  	private function loginWithPassword($uid, $password) {
so ... $uid here is actually the login (username or email). rename it to `$login` (also update the phpdoc)

2018-05-28 14:49 UTC, PVince81 commented
@sharidas comments adressed ? can you finish this ?

2018-05-28 14:55 UTC, PVince81 commented
@sharidas please also leave the old keys in there for compatibility in case apps use this already.
Mark as deprecated in the code for now and say so in the symfony events documentation (or have the doc only mention the new keys)

- [ ] update symfony doc ticket

2018-05-29 09:51 UTC, PVince81 commented
@butonic please recheck as you had concerns

2018-05-29 10:40 UTC, butonic requested changes

2018-05-29 10:40 UTC, butonic commented on lib/private/User/Session.php
> +					$afterArray['uid'] = $user;
`$afterArray['uid'] = $user->getUID();` uid is the string ...

2018-05-29 10:40 UTC, butonic commented on lib/private/User/Session.php
> +		}, ['before' => ['login' => $login, 'uid' => $login, 'password' => $password], 'after' => ['user' => $login, 'uid' => $login, 'password' => $password]], 'user', 'login');
Just to indicate what needs to go where:
```php
['before' => [
  'login' => $login,
  'uid' => $login, // actually I'd love to deprecate this ... before login we don't know the uid. just here for compatability
  '_uid' => 'deprecated: please use \'login\', the real uid is not yet known' // maybe we can expose the deprecation this way?
  'password' => $password
], 'after' => [
  'login' => $login,
  'uid' => $user->getUid(), // uid = the string
  'user' => $user, // user = the object
  'password' => $password
]]
```

@PVince81 @DeepDiver1975 how do we deprecate uid in the preLogin hook params? We could also use an object that implements `toString()` which logs a warning if someone accesses it?

2018-05-31 12:26 UTC, jvillafanez commented on lib/private/User/Session.php
> +		return $this->emittingCall(function (&$afterArray) use ($login, $password) {
Could we simplify this and make it more standard? This is really confusing as it is.
This should as be as simple as:
```
send before event
do your stuff
send after event
```
You can easily read the function from top to bottom, as well as include extra parameters to the "after event" if needed.

Right now what we have is a big callback function and some parameters that it isn't clear where they're going to go. You have to go to the bottom of the function to know what parameters are going to be sent, and then scroll up to read the real function.
In addition, the `&$afterArray` make things worse: using references inside callbacks is quite dangerous because normally you don't use them, and also the code above must be prepared for it. If 90% of the calls don't use references but a 10% do, the first thing you think is that there might be a bug. Note that just checking the changes I thought it was dead code; I had to check the code of the "emittingCall" function to understand.

My point is that the function is structured in a counter-intuitive way. To understand a function you should just read through it, but this isn't happening with the current code.

2018-05-31 12:46 UTC, sharidas commented on lib/private/User/Session.php
> +		return $this->emittingCall(function (&$afterArray) use ($login, $password) {
Updated as per request. Unfortunately haven't updated the event name to camel case. The reason being I suspect there are listeners to the event in other app, like admin_audit.

2018-05-31 13:52 UTC, butonic reviewed
I like the increase in readability, now add some newlines I I am happy

2018-05-31 13:52 UTC, butonic commented on lib/private/User/Session.php
> +		$user = $this->manager->checkPassword($login, $password);
add a newline before this line to separate event throwing code from the actual password check

2018-05-31 13:52 UTC, butonic commented on lib/private/User/Session.php
> +				$afterEvent = new GenericEvent(null, ['user' => $user, 'uid' => $user->getUID(), 'password' => $password]);
add a newline before this line

2018-05-31 13:52 UTC, butonic commented on lib/private/User/Session.php
> +				return true;
add a newline before this line

2018-05-31 13:58 UTC, sharidas commented on lib/private/User/Session.php
> +		$user = $this->manager->checkPassword($login, $password);
done

2018-05-31 13:58 UTC, sharidas commented on lib/private/User/Session.php
> +				$afterEvent = new GenericEvent(null, ['user' => $user, 'uid' => $user->getUID(), 'password' => $password]);
done

2018-05-31 13:58 UTC, sharidas commented on lib/private/User/Session.php
> +				return true;
done

2018-05-31 13:58 UTC, butonic approved these changes

2018-05-31 16:01 UTC, merged

2018-06-01 03:05 UTC, phil-davis commented
Backport ``stable10`` #31605