While decrypting userkey prepareEncryptionModules() must be called, keep fileid on decrypt
owncloud/core pull request #31510
Opened 2018-05-23 15:11 UTC by sharidas

Regression was caused because of omitting call to method
prepareEncryptionModules. This change will get the userkey encryption
work as before.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Call to `prepareEncryptionModules()` was omitted and the check for `userkeys` also got missing. This resulted in regression. And hence encryption with userkey was not decrypted properly. This change would help to fix the regression.

## Related Issue

## Motivation and Context

Call to `prepareEncryptionModules()` was omitted and the check for `userkeys` also got missing. This resulted in regression. And hence encryption with userkey was not decrypted properly. This change would help to fix the regression.

## How Has This Been Tested?

- [x] Enable userkey encryption
- [x] execute `./occ encryption:decrypt-all`
- [x] The files should be decrypted.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-23 15:13 UTC, patrickjahns commented
Is it possible to create Tests to catch these regressions?

2018-05-29 09:49 UTC, sharidas commented on lib/private/Encryption/DecryptAll.php
> +								foreach ([\OCP\Share::SHARE_TYPE_GROUP, \OCP\Share::SHARE_TYPE_USER, \OCP\Share::SHARE_TYPE_LINK, \OCP\Share::SHARE_TYPE_REMOTE] as $shareType) {
Note: This piece of code is inspired or copy/pasted from transfer-ownership command.

2018-05-29 09:57 UTC, PVince81 commented
What regression ? What breaks and what works now ?

2018-05-29 10:00 UTC, PVince81 requested changes
see comments

2018-05-29 10:00 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +				if (\OC::$server->getAppConfig()->getValue('encryption', 'userSpecificKey', '0') !== 0) {
`'0'` is always strictly different from `0`, please be careful with data types

2018-05-29 10:00 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +								foreach ([\OCP\Share::SHARE_TYPE_GROUP, \OCP\Share::SHARE_TYPE_USER, \OCP\Share::SHARE_TYPE_LINK, \OCP\Share::SHARE_TYPE_REMOTE] as $shareType) {
add as comment in PHP code then ?

2018-05-29 10:00 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +									while (true) {
use `do...while` instead ?

2018-05-29 10:00 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +												$this->shareManager->updateShare($share);
why does the decryption process need to update shares ?

We should skip received shares when decrypting. If the admin wants to decrypt the received share files, the admin must decrypt the share owner's home storage instead.

2018-05-29 10:06 UTC, sharidas commented
> What regression ? What breaks and what works now ?

Regression:
- With oC instance encrypted with user-keys, the decrypt-all command was not working as expected. After decrypt-all command is executed, the files remained encrypted.

What this PR addresses:
- This PR address 2 issues. One is the regression mentioned above. And other fix is the shares become visible after the decrypt-all command is run.

2018-05-29 11:52 UTC, sharidas commented
Issue of share lost issue present in versions:
- 9.1.8 -> https://github.com/owncloud/core/commit/7993a510f8ec28002c9fdab1a5783fc567c11d05
- 10.0.0 -> https://github.com/owncloud/core/commit/ce40499f02717afa0af25bf2f67629a3159a29d3
- 10.0.1 -> https://github.com/owncloud/core/commit/1c54fcd45dc4bc242eeb84b56a85da7a276d55a8
- 10.0.2 -> https://github.com/owncloud/core/commit/1b8359fca33d002f10e00b6225100071d486e4b6
- 10.0.3 -> https://github.com/owncloud/core/commit/5ae38448f1f98a5a9a1a629a5094a34bb64550e6

Didn't checked versions previous to 9.1.8 version of oC.

2018-05-29 12:45 UTC, sharidas commented
The root cause of the problem is lets say we have a single file `a.txt` in user `admin`. And when user executes decrypt-all, this is how the problem arises:
The problem -> https://github.com/owncloud/core/blob/master/lib/private/Encryption/DecryptAll.php#L252-L254
- copy('a.txt', 'a.txt.decrypted.1234')
- rename('a.txt.decrypted.1234', 'a.txt')
This causes old `a.txt` to be overwritten. But the fileid is changed. Now `a.txt` would have fileid of `a.txt.decrypted.1234`. And that results in loss of meta data.

So a quick ( it sounds horribly weird  :( ) solution that comes to my mind:
- copy(`a.txt`, `a.txt.decrypted.1234`)
- copy(`a.txt.decrypted.1234`, `a.txt`)
- unlink(`a.txt.decrypted.1234`)

2018-05-29 14:41 UTC, PVince81 commented
@sharidas how about appending ".part" to the decrypted file name ?

this would skip the file cache and then when you rename the part file to overwrite an existing file, it's supposed to keep file id
this is basically how uploads work: the data is stored to a part file and then the part file gets rename+overwrite the original file. the file cache entry stays unchanged apart from size, mtime, etag

2018-05-29 14:49 UTC, PVince81 commented on lib/private/Encryption/DecryptAll.php
> +												$this->shareManager->updateShare($share);
reason explained below: because of fileid change. we're researching an alternative solution

2018-05-29 15:35 UTC, PVince81 reviewed
Code looks good, as discussed!

Would be good to add a test that confirms that the file id hasn't changed after decryption, to enforce the fixed behavior.

2018-05-29 15:36 UTC, PVince81 commented
@sharidas please add your test steps you used to validate that the part file thing works, thanks!

- [ ] unit test to enforce file id
- [ ] list of manual test steps used to confirm that it works

2018-05-29 15:36 UTC, sharidas commented
I have updated the PR: https://github.com/owncloud/core/pull/31510 with the '.part' file extension solution.
Below are the tests I did:
- Created users `admin` and `user1`
- Login as `user1` and then logout.
- Login as `admin` and create files `groupshare.txt`, `localshare.txt`, `publiclink.txt`
- Create group `group1`
- Add `user1` to `group1`
- Share `groupshare.txt` to `group1`
- share `localshare.txt` to `user1`
- create public link for `publiclink.txt`
- Finally run the decrypt-all and verified the checks below:
- [x] Verified that `user1` has shares `groupshare.txt` and `localshare.txt`
- [x] Verified that `admin` has files shared -> `publiclink.txt`, `groupshare.txt` and `localshare.txt`

2018-05-30 07:03 UTC, sharidas commented
Updated the unit test and manual steps to confirm that it works.

2018-05-30 08:17 UTC, PVince81 approved these changes
Code looks good and validated by unit test, as discussed :+1:

2018-05-30 08:18 UTC, merged

2018-05-30 08:18 UTC, PVince81 commented
@sharidas please backport to stable10

2018-05-30 10:00 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31590