Add symfony event for public links shared by email
owncloud/core pull request #31537
Opened 2018-05-25 11:41 UTC by sharidas

Adding symfony event for public links shared by email.
When an email is triggered, the recipient, the cc or
bcc and the link data is shared using the event.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Add new symfony event, when a public link is shared by email. The details include:
a) recipient
b) link
d) cc or bcc

## Related Issue

## Motivation and Context

Add new symfony event, when a public link is shared by email. The details include:
a) recipient
b) link
d) cc or bcc

## How Has This Been Tested?

- [x] Tested if the event is called using debugger
- [x] With the unit test.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-29 09:56 UTC, PVince81 commented on lib/private/Share/MailNotifications.php
> +		$event = new GenericEvent(null, ['link' => $link, 'recipient' => $recipient, 'ccorbcc' => $options]);
did you test with multiple recipients ?

2018-05-30 12:49 UTC, PVince81 commented on lib/private/Share/MailNotifications.php
> +		$event = new GenericEvent(null, ['link' => $link, 'recipient' => $recipient, 'ccorbcc' => $options]);
are we getting a single event with multiple recipients or multiple events ?

in the former case the attribute should then be called `recipients`, plural

2018-05-30 15:01 UTC, sharidas commented on lib/private/Share/MailNotifications.php
> +		$event = new GenericEvent(null, ['link' => $link, 'recipient' => $recipient, 'ccorbcc' => $options]);
A single event with multiple recipients. The `recipient` here is the `to` in the mail. The manual test in the UI makes multiple bcc recipients. And that gets populated in `$options`

2018-05-30 20:50 UTC, PVince81 commented on lib/private/Share/MailNotifications.php
> +		$event = new GenericEvent(null, ['link' => $link, 'recipient' => $recipient, 'ccorbcc' => $options]);
Passing in the options array as is as a different attribute name is confusing. What happens if in the future we add more options that are unrelated to cc/bcc ?

I suggest we split semantically into three attributes: "to", "cc" and "bcc" so it's very clear to the event consumer that what is coming in are these fields.

2018-06-01 05:20 UTC, sharidas commented on lib/private/Share/MailNotifications.php
> +		$event = new GenericEvent(null, ['link' => $link, 'recipient' => $recipient, 'ccorbcc' => $options]);
Splitted the attributes to 'to', 'cc' and 'bcc'.

2018-06-01 09:13 UTC, butonic requested changes

2018-06-01 09:13 UTC, butonic commented on lib/private/Share/MailNotifications.php
> +		$ccRecipients = isset($options['cc']) === true ? $options['cc'] : '';
`$ccRecipients = isset($options['cc']) ? $options['cc'] : '';`
`$bccRecipients = isset($options['bcc']) ? $options['bcc'] : '';`

2018-06-01 09:13 UTC, butonic commented on tests/lib/Share/MailNotificationsTest.php
> + * @group DB
why does this test now need db access?

2018-06-01 13:20 UTC, sharidas commented on tests/lib/Share/MailNotificationsTest.php
> + * @group DB
I have updated the code and brought back `@group DB`. Basically trying to improve code coverage.

2018-06-04 14:26 UTC, PVince81 commented
ignoring untestable codecov stuff, merging

2018-06-04 14:27 UTC, merged

2018-06-04 14:27 UTC, PVince81 commented
@sharidas please backport

2018-06-04 14:49 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31632