Fixes #31568 - Validate maximum length of a username before creation
owncloud/core pull request #31569
Opened 2018-05-28 23:50 UTC by mdusher

When creating a user, there is no validation on the maximum length for a username. Creating a user with a username longer than 64 characters results in the username being truncated to 64 characters when inserted into the database.

This adds validation to make sure the username is less than 64 characters.

2018-05-29 04:08 UTC, phil-davis commented
Before:
```
./occ user:add a234567890b234567890c234567890d234567890e234567890f234567890g2345
Enter password: 
Confirm password: 

In AbstractMySQLDriver.php line 115:                                 
  An exception occurred while executing 'INSERT INTO `oc_users` ( `uid`, `password` ) VALUES( ?, ? )' with params ["a234567890b234567890c234567890d234567890e234567  
  890f234567890g2345", "1|$2y$10$ZkmBA5b3KShHT3xIki0sj.NYUJ9XSTSSWRmx0Cmvyx.Zn6GeM9cWi"]:                  
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uid' at row 1
In PDOStatement.php line 107:
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uid' at row 1
In PDOStatement.php line 105:                                                                                               
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uid' at row 1
```
After:
```
./occ user:add a234567890b234567890c234567890d234567890e234567890f234567890g23xz
Enter password: 
Confirm password: 

In Manager.php line 355:
                                                     
  The username can not be longer than 64 characters  

user:add [--password-from-env] [--display-name [DISPLAY-NAME]] [--email [EMAIL]] [-g|--group [GROUP]] [--] <uid>
```
good

2018-05-29 04:11 UTC, phil-davis commented
And the UI gives the message
```
Error creating user: The username can not be longer than 64 characters
```
instead of a long cryptic database message about error inserting...

2018-05-29 08:31 UTC, mmattel commented
It is not necessary to maintain translation files (eg en_GB.js/json) as they get populated and overwritten automatically. Any translation made is done via Transifex. If this PR gets merged, the correspondent text will be uploaded to Transifex automatically where you can translate into any available language. The results get backpopulated automatically too.

2018-05-30 00:55 UTC, mdusher commented
Ah cool, I wasn't sure whether that was necessary or not. Do you need me to revert them?

2018-05-30 06:03 UTC, mmattel commented
You can take them out, files will be overwritten by transifex anyway :smile:

2018-06-04 07:02 UTC, DeepDiver1975 requested changes
please remove the translation file changes and we are ready to go - THX

2018-06-05 01:42 UTC, mdusher commented
Changes have been reverted

2018-06-06 11:52 UTC, DeepDiver1975 approved these changes

2018-06-06 11:53 UTC, merged

2018-06-06 13:48 UTC, phil-davis commented
Backport ``stable10`` #31664