Proceed encrypt-all by enabling user-keys if no mode is selected by user
owncloud/core pull request #31597
Opened 2018-05-31 06:42 UTC by sharidas

Proceed encrypt-all by enabling user-keys, if user
had not selected any encryption mode before executing
the command.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

If user had not selected either user-keys or masterkey encryption modes, then proceed encrypt-all command by enabling user-keys.

## Related Issue

## Motivation and Context

If user had not selected either user-keys or masterkey encryption modes, then proceed encrypt-all command by enabling user-keys.

## How Has This Been Tested?

- [x] Create user `admin`
- [x] Enable encryption. Do not select any encryption mode ( this is done from command line )
- [x] Run encrypt-all command
- [x] Verify the db. The user should see 
```
sqlite> select * from oc_appconfig where appid="encryption" and configkey='userSpecificKey';
encryption|userSpecificKey|1
sqlite>
```

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-01 09:07 UTC, butonic requested changes
makes sense, but have a look at https://github.com/owncloud/core/pull/31598#pullrequestreview-125091801 ... add the same _make-user-individual-keys-explicit_ logic to the encryption login hook.

2018-06-01 10:31 UTC, sharidas commented
Created https://github.com/owncloud/encryption/pull/36, as per the request suggested in the encryption login hook.

2018-06-01 10:40 UTC, butonic approved these changes

2018-06-01 10:58 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31612

2018-06-01 10:59 UTC, merged

2018-06-08 13:32 UTC, phil-davis commented
Backport has happened.