[stable10] Accept user share stable10
owncloud/core pull request #31613
Opened 2018-06-01 11:19 UTC by jvillafanez

## Description
Backport of https://github.com/owncloud/core/pull/30106 to stable10

## Related Issue
https://github.com/owncloud/core/issues/19153

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@owncloud/qa please verify the .drone.yml configuration to recheck all the tests we want to run are there. There were some conflicts there so I've mostly copied whatever there is in the master branch.

2018-06-01 13:55 UTC, PVince81 commented
strange failure with swift and postgres run:
```
PHP Fatal error: Cannot use Test\TestCase as TestCase because the name is already in use in /drone/src/apps/files_sharing/tests/HooksTest.php on line 30
```

Not sure if related at all

2018-06-04 13:57 UTC, jvillafanez commented
I'm not sure if we should move the fix for the tests to master. The tests aren't complaining about it though.

2018-06-05 08:52 UTC, PVince81 commented
@patrickjahns please review the extra commit https://github.com/owncloud/core/pull/31613/commits/75f77a622469ed285e3195939b1e0dba01cc3d34.

2018-06-05 20:08 UTC, patrickjahns commented on .drone.yml
> +  setup-caldav-tests:
this is not related to this pr ?

2018-06-06 06:57 UTC, jvillafanez commented on .drone.yml
> +  setup-caldav-tests:
It seems so. It seems it was added with https://github.com/owncloud/core/pull/31613/commits/484f89c1912f66a43bdb0fbbea0af6482afd0e82 . All the changes were cherry-picked except the last one (to fix breaking things), so not sure why this was needed in the master PR.

Feel free to remove it.

2018-06-06 16:08 UTC, phil-davis commented
Rebased and added commit from #31661 to resolve ``run.sh`` conflict.

2018-06-07 07:18 UTC, PVince81 commented
It's green.

Any update on https://github.com/owncloud/core/pull/31613#discussion_r193309072 ? Is this acceptable ?

2018-06-07 08:34 UTC, patrickjahns commented on .drone.yml
> +  setup-caldav-tests:
please remove the step - it is unrelated to this PR

2018-06-07 08:38 UTC, patrickjahns requested changes
Please remove unnecessary .drone step

2018-06-07 08:38 UTC, phil-davis commented
I will have a look at the drone conflict... and rebase/push in the next few minutes.

2018-06-07 08:41 UTC, phil-davis commented
Conflict resolved.

2018-06-07 15:21 UTC, PVince81 commented
Green again, no more conflict. Merge ?

2018-06-08 00:17 UTC, phil-davis commented
Rebased and added the 4 commits from #31665

2018-06-08 07:17 UTC, phil-davis approved these changes
Looks OK now to me. I guess that @patrickjahns review has been addressed? Because I do not see a problem with ``.drone.yml``any more.

2018-06-08 07:56 UTC, patrickjahns approved these changes

2018-06-08 08:00 UTC, merged