Provide summarized acceptance test chunking upload steps
owncloud/core pull request #31620
Opened 2018-06-01 17:12 UTC by phil-davis

## Description
Make summarized steps for acceptance test chunking uploads that let you do the whole process by writing a single step.

## Related Issue
#31616 

## Motivation and Context
It is tedious to write all the individual chunking setup, upload and finalization acceptance test steps.
For most "happy" cases it is the same flow, so make summarized step definitions that can do old/new chunking with a single gherkin step.

## How Has This Been Tested?
Local test runs

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test enhancement

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-06-01 17:56 UTC, phil-davis commented
Backport ``stable10`` #31621

2018-06-01 18:18 UTC, patrickjahns commented
I gave this a thought today - it would probably also be great to have a chunking step that you could pass a file. The method would then split the file automatically and upload it as if it would have been via chunks? 

What do you think @IljaN @individual-it @phil-davis ?

2018-06-05 16:09 UTC, individual-it requested changes
Code looks good, I would prefer to have a bit more documentation

2018-06-05 16:09 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @param array $chunkDetails
Some documentation about what the array should contain would be helpful

2018-06-05 16:09 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @param TableNode $chunkDetails
Documentation about what the table should contain would be useful

2018-06-05 16:09 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @param TableNode $chunkDetails
More documentation details

2018-06-05 16:30 UTC, phil-davis commented
PHP doc added.

2018-06-05 19:55 UTC, individual-it approved these changes

2018-06-05 19:57 UTC, individual-it commented
Drone failed because of docker problems, restarted

2018-06-05 20:27 UTC, merged