Adding background:queue commands: status and delete
owncloud/core pull request #31630
Opened 2018-06-04 12:45 UTC by DeepDiver1975

## Description
Adding two new commands for listing background jobs and deleting individual jobs

## Related Issue
#31617 

## Motivation and Context
Adding a full feature set around occ and background jobs

## How Has This Been Tested?
- manual testing
- unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-04 13:20 UTC, tomneedham requested changes

2018-06-04 13:20 UTC, tomneedham commented on core/Command/Background/Queue/Delete.php
> +
missing copyright header

2018-06-04 13:20 UTC, tomneedham commented on core/Command/Background/Queue/Delete.php
> +			return;
return 1 for the error?

2018-06-04 13:20 UTC, tomneedham commented on core/Command/Background/Queue/Delete.php
> +		$output->writeln('Job has been deleted.');
return 0

2018-06-04 13:20 UTC, tomneedham commented on lib/public/BackgroundJob/IJobList.php
> +	 * @since 10.0.3
10.0.9?

2018-06-04 13:39 UTC, mmattel commented
For the sake of documentation :smile:

``background:queue:delete`` ``'id'``
``background:queue:status``  ``'Id', 'Job', 'Last run', 'Arguments'``

2018-06-04 13:54 UTC, mmattel commented
@DeepDiver1975 
in command delete, you have ``id``
in command status, you have ``Id``
could you haronize them eg to ``ID`` (or whatever but equal) ?

in command status, you have ``Arguments``, I guess this means ``Job Arguments`` or ?
if yes, what about renaming to make it clear which arguments are meant, else you could think of occ command arguments

@butonic you have in #31617 in code ``TimedJob.php`` line 59 ``id``. Please sync with @DeepDiver1975 and have everywhere the same

@DeepDiver1975 , same codline as above in ``TimedJob.php`` @butonic names a ``class`` here as additional text printed. Either this is missing in your PR in ``status`` or it maybe equal to your ``Arguments`` value. Can you pls sync and harmonize?

2018-06-04 13:57 UTC, tomneedham approved these changes

2018-06-04 14:45 UTC, mmattel commented
@DeepDiver1975 
Having a ``background:queue:delete`` command.
What happens if I delete all jobs or accidentially one job?
How can I come back to a working state?
What about a ``background:queue:reset`` command which resets all jobs to a state like the system got shipped?

2018-06-04 21:06 UTC, DeepDiver1975 commented
> in command delete, you have id
> in command status, you have Id

I see no inconsistency here - id in the argument follows the command argument naming convention and the Id in the status command is a human readable table column - all columns are upper case.



> in command status, you have Arguments, I guess this means Job Arguments or ?
> if yes, what about renaming to make it clear which arguments are meant, else you could think of occ command arguments

agreed



> @DeepDiver1975 , same codline as above in TimedJob.php @tomneedham names a class here as additional text printed. Either this is missing in your PR in status or it maybe equal to your Arguments value. Can you pls sync and harmonize?

job arguments hold the class name as well as required arguments for the execution of the job.
the timedjob is already an instanciated job of one specific type.

the information is identical but it's represenations is different - I see no way to harmonize this right away



> What happens if I delete all jobs or accidentially one job?
> How can I come back to a working state?

well - this is what backups are for ;-)
seriously: one better knows what he does when killing a job - we can think about a enqueue commend or something

reset is not the way to go because there are multiple sources how jobs are enqueued - we can only restore some of them. I dislike partial solutions

2018-06-05 08:11 UTC, mmattel commented
@DeepDiver1975 @tomneedham 
``delete``: ``->addArgument('id', InputArgument::REQUIRED, 'id of the job to be deleted');``
``status``: ``$t->setHeaders(['Id', 'Job', 'Last run', 'Job Arguments']);``
``Execute``:``->addArgument('jobId', InputArgument::REQUIRED)``

All three lines are printed and the user can see it.
The presentation to the user is different ``id`` vs ``Id`` vs ``jobId``.
Independent for what you decide, the look should be consistent else this is unprofessional.
Same version of how we write it should be taken in all PR´s.

> job arguments hold the class name as well as required arguments for the execution of the job

Could we agree to have the same naming in all PR´s for this too, like ``Job Arguments`` or what ever

> one better knows what he does when killing a job

I would not sign this... I do not know, but a possible solution could be to have a marker in the database for jobs defined by core and you can enable/disable them. All other jobs not beeing part of core do not get/have that marker.

> I dislike partial solutions

Agreed - therefore I take the effort to write my thoughts down 😄

2018-06-05 08:52 UTC, DeepDiver1975 commented
> Execute:->addArgument('jobId', InputArgument::REQUIRED)

I agree to use the same argument name here.

2018-06-05 09:34 UTC, tomneedham commented
Status and delete are useful commands, but only for debugging / analysis, not normal operation. This should be clear in any documentation. 

Likewise with my execute command, it is only really for use in exceptional scenarios where we need to forcefully trigger a job on demand for analysis. It should not be expected that these commands are used in normal operation.

2018-06-05 09:35 UTC, tomneedham commented
<img width="836" alt="screen shot 2018-06-05 at 10 34 43" src="https://user-images.githubusercontent.com/660805/40967858-148aecde-68ac-11e8-86cf-e8db3a94100e.png">

Need to update tests with expected table output

2018-06-05 09:57 UTC, DeepDiver1975 commented
> Need to update tests with expected table output

addressed

2018-06-05 11:15 UTC, mmattel commented
@DeepDiver1975 
being a pain, I know, but id -> ``jobId``
delete: Line 44, 57
status: Line 54

(all changes including the proposal below need table length adoption ...)

@tomneedham I do not know where the right place to note that is so I do here,
In your PR in Job.php in line 59 you define a log output having the name ``class`` and ``arguments``
@DeepDiver1975 in status beginning with line 54 you define the printable output

Looking at both PR´s I see that ``\get_class`` gets called but in job.php it is printed as ``class`` while in status it is printed as ``Job``.
I propose to have on **both** the term ``Job name`` and for ``arguments`` the term ``Job Arguments``

2018-06-11 19:46 UTC, merged

2018-06-11 19:46 UTC, DeepDiver1975 commented
we can harmonize print out later on ...

2018-06-11 19:47 UTC, DeepDiver1975 commented
@tomneedham feel free to adjust your PR - THX

2018-06-12 16:00 UTC, PVince81 commented
@DeepDiver1975 backport to stable10 ?

2018-06-13 06:56 UTC, DeepDiver1975 commented
we will backport once #31617 is merged and we backport this together as one

2019-03-18 05:26 UTC, phil-davis commented
Backport `stable10` is in PR #34783
Passes CI

2019-03-18 14:28 UTC, PVince81 commented
some objections to be clarified in https://github.com/owncloud/core/pull/31617 first

cc @tomneedham

2019-03-29 12:09 UTC, phil-davis commented
I added label only-in-master so I can find and recognise this PR easily.
If/when the backporting is merged:
- [ ] remove label only-in-master
- [ ] remove label backport-request

2019-04-03 04:51 UTC, phil-davis commented
> some objections to be clarified in #31617 first
> 
> cc @tomneedham

Ping @tomneedham or anyone for comment about backporting.