Allow admin to blacklist groups for the files_sharing app
owncloud/core pull request #31672
Opened 2018-06-07 08:23 UTC by jvillafanez

## Description
Allow admins to blacklist groups so user can't share with those groups. Blacklist will be done per backend + group displayname for now.

## Related Issue
https://github.com/owncloud/core/issues/31578

## Motivation and Context

## How Has This Been Tested?
Manually tested for now

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-07 20:14 UTC, PVince81 reviewed
See review comments.

I'm not convinced about the need to have a cache here.

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/js/settings.js
> +	$('#files_sharing .files_sharing_settings').change(function(){
so the generic functions didn't work ? might be possible to adjust the generic existing JS function for saving settings to include `textarea` additionally to `input`

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/API/Share20OCS.php
> +				return new \OC\OCS\Result(null, 403, $this->l->t('The group is blacklisted for sharing'));
not sure if this qualifies as information disclosure, maybe just return 404 "Please specify a valid group" as above

cc @settermjd

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/Controller/SettingsController.php
> +		'blacklisted_group_displaynames' => true,
looks like early optimization/refactoring before it is even needed, but ok

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/Panels/Admin/SettingsPanel.php
> +		$tmpl->assign('backendNames', $backendNames);
great that you put this in :+1:

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +class SharingBlacklist {
Add PHPDoc. Is this the actual black list array or just a utility class ? This is what a developer wonders about when seeing only the class name used in various places

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +	 * @param IGroup $group the group to check
missing `@return`

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		foreach ($blacklistedComponents as $blacklistedComponent) {
is this operation so expensive that we need a cache with all complexity that comes with it ?

in general I don't think we expect more than 10 or so blacklisted groups

2018-06-07 20:14 UTC, PVince81 commented on apps/files_sharing/templates/settings.php
> +		<textarea placeholder="OC\Group\Database::localGroups&#10OCA\User_LDAP\Group_Proxy::ldapGroup" class="files_sharing_settings" name="blacklisted_group_displaynames"><?php p($_['blacklistedDisplaynam
what's this weird `&#10` entity here ? likely a newline. I suggest to put this in a template variable instead and initialize it from the PHP template in which you can write it in a more readable format that includes `\n`

2018-06-08 07:54 UTC, jvillafanez commented on apps/files_sharing/js/settings.js
> +	$('#files_sharing .files_sharing_settings').change(function(){
I'm not aware of any generic function to save values in the appconfig table. I've just found the `OC.AppConfig.setValue` function to perform the operation (code already adjusted to use it, soon), but there isn't auto binding, so I'll need to bind the event manually.

2018-06-08 07:56 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/SettingsController.php
> +		'blacklisted_group_displaynames' => true,
I'll remove the class because get and set for the appconfig table will go through core (using OC.Appconfig in js). No need to handle this on our own.

2018-06-08 08:15 UTC, jvillafanez commented on apps/files_sharing/lib/SharingBlacklist.php
> +		foreach ($blacklistedComponents as $blacklistedComponent) {
For the sharees we'll need to check if each group is blacklisted. This leads potentially to a lot of calls to this function.
Since the blacklist will be stored as a large string, each call will need to fetch the string and process it in order to make the decission. This might be heavy we need to check a lot of groups.
In addition, I'd rather not rely on the appconfig to be cached to have a decent performance.

I also don't expect a lot of blacklisted groups, but we might need to include more options for the blacklist, such as blacklist by group id, and I'd prefer the check to be as fast as possible.

2018-06-08 08:34 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		foreach ($blacklistedComponents as $blacklistedComponent) {
Ok, fair enough. Make sure the unit tests also take the cache into account and prove that it properly invalidates, if applicable.

2018-06-08 13:27 UTC, jvillafanez commented
Code should be mostly ready, but there are tests missing for the SettingsPanel.php and SharingBlacklist.php and the `getBackends` method of the `IGroupManager`

2018-06-12 14:28 UTC, tomneedham commented on apps/files_sharing/lib/SharingBlacklist.php
> +		if (isset($this->blacklistCache['displaynames'][$groupBackend][$groupDisplayname])) {
I am still concerned we do the matching on the displaynames. Can't we store ID's but allow admins to specify displaynames?

2018-06-12 16:28 UTC, jvillafanez commented
Backport to stable10 in https://github.com/owncloud/core/pull/31740

2018-06-15 13:38 UTC, PVince81 requested changes
apart from the settings cache this looks good

2018-06-15 13:38 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
since we now removed the class names from the group ids, maybe we don't need the cache any more ?

based on @tomneedham's comment here https://github.com/owncloud/core/issues/31578#issuecomment-396246250 we can use the same approach as "exclude groups from sharing" which also doesn't expect a higher number of groups than the blacklist.

also now the logic for reading the settings has simplified itself since we don't store the prefix any more

@jvillafanez can you remove the cache and read directly from the setting ?

2018-06-18 06:54 UTC, jvillafanez commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
I think we'll still need this. The problem is with sharees: we'll fetch a list of groups and each group needs to be checked whether is blacklisted or not; without proper caching we'll need to fetch the list from the configuration and then parse the list for each group.
Even if we rely on the configuration being cached, we still need to parse the stored json several times.

2018-06-18 09:23 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
is there no way to change the caller code then to only fetch the blacklist array once ?

2018-06-18 11:01 UTC, jvillafanez commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
We might use a `filterBlacklistedGroups(array $groups)` function, but the calls would be a bit weird:
* The share API just needs to check one group, so you'll need to wrap it in an array, which feels bad.
* For the sharees, the intention would be to return the groups that aren't blacklisted. However, in case we need to do something with the blacklisted groups (maybe log them) things will get complicated both for the caller and the implementation. Note that, in any case, we'll need to traverse the sharees list twice.

I agree the code is a bit complex, but it should be fine if this complexity is isolated in this class. On the other hand, the usage is simple. Maybe we can document in the class what is the expected usage.

2018-06-18 11:47 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
I was more thinking that the caller code calls "give me all the blacklisted groups", store it in a local var and then use that when checking against each group. Unless the caller codes is spread across various classes, this could work.

2018-06-19 07:41 UTC, jvillafanez commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
You'll move the complexity to the callers. you still need to compare the target group with the blacklist. This comparison code will be spread into several classes, and the way you'll likely compare will use the `in_array` function instead of more efficients approaches (you don't want to add more complexity to the caller).

Current code has a faster performance an a cleaner interface at a cost of including a cache.

2018-06-19 08:30 UTC, PVince81 commented on apps/files_sharing/lib/SharingBlacklist.php
> +		$configuredBlacklist = $this->config->getAppValue('files_sharing', 'blacklisted_receiver_groups', '[]');
> Current code has a faster performance an a cleaner interface at a cost of including a cache.

Okay, let's leave it then

2018-06-19 08:33 UTC, PVince81 reviewed
Code looks good.

What happens if shares exist that were shared with a group that has now been blacklisted ? I assume these must still appear in the shares list and be unshareable by users. I don't think we need to add a mechanism to also exclude existing shares/mounts that point to blacklisted groups.

@tomneedham thoughts on the latter ?

2018-06-21 08:10 UTC, PVince81 commented
@jvillafanez let's move on with this. The additional concern, if addressed in any way, will not affect the code of this PR.

2018-06-21 08:11 UTC, PVince81 commented
I've added a comment here to address as part of the ticket/concept before we close it: https://github.com/owncloud/core/issues/31578#issuecomment-399014984

2018-06-21 08:11 UTC, PVince81 approved these changes

2018-06-21 08:11 UTC, merged

2018-06-21 08:11 UTC, PVince81 commented
@jvillafanez please adjust the backport PR and ping me there when done

2018-07-26 11:07 UTC, settermjd commented on apps/files_sharing/lib/API/Share20OCS.php
> +				return new \OC\OCS\Result(null, 403, $this->l->t('The group is blacklisted for sharing'));
Honestly? I'm don't believe that this is information disclosure. However, something more generic, yet still informative, such as "This group is not available for sharing, would work better.

2018-07-26 11:34 UTC, settermjd commented on apps/files_sharing/lib/Controller/ShareesController.php
>  			// FIXME: use a more efficient approach
I can't think of a more efficient approach off the top of my head. However, you could use an implementation of a [FilterIterator](https://secure.php.net/manual/en/class.filteriterator.php) to simplify the logic here, making it that much simpler to maintain over time.

2018-07-26 11:54 UTC, settermjd commented on apps/files_sharing/tests/SharingBlacklistTest.php
> +			[$groupMock1, '["one group", "Mygroup"]'],
Isn't this, effectively, the same as the line above?

2018-07-26 12:04 UTC, phil-davis commented on apps/files_sharing/tests/SharingBlacklistTest.php
> +			[$groupMock1, '["one group", "Mygroup"]'],
There were issues in various places with group names that contain a space - maybe that was a concern here?