Reload the filelist view when accepting or rejecting a share
owncloud/core pull request #31765
Opened 2018-06-13 16:29 UTC by jvillafanez

## Description
The "all files" list will be reloaded when a share notification is accepted, either local or remote.
The "shared with you" list will be reloaded when any action for a share notification (local or remote) is taken.

As remark, the "all files" list won't be reloaded if the share is rejected.

## Related Issue
https://github.com/owncloud/core/issues/31549

## Motivation and Context
User would need to manually reload the page to see the changes.

## How Has This Been Tested?
Manually tested

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

I haven't found a good way to trigger the reload of the "all files" list. Right now there is an explicit dependency between the files_sharing and files app (the `OCA.Files.App.fileList.reload()` call). For now this is the easiest way to fix the problem.

We might want to refine when we want to reload the "all files" view in order to reload only if the file would appear in the current folder.

2018-06-15 08:29 UTC, jvillafanez commented
Errors seem unrelated to the PR

2018-06-15 13:23 UTC, PVince81 requested changes
Great job!

Just a little adjustment for the JS test expectation rformat

2018-06-15 13:23 UTC, PVince81 commented on apps/files_sharing/tests/js/appSpec.js
> +			expect(1).toEqual(fileListInReloadStub.callCount);
we usually swap the values: expect contains the variable and toEqual the expected value
it's the opposite of PHPUnit

2018-06-25 08:41 UTC, PVince81 approved these changes
:+1: please backport

2018-06-25 08:41 UTC, merged