Skip filecache repair step for version greater than 10.0.4
owncloud/core pull request #31795
Opened 2018-06-15 08:19 UTC by sharidas

Skip the filecache repair step for version greater than 10.0.4

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

The file cache repair step can be omitted if the current oC version is 10.0.4 or greater than 10.0.4.

## Related Issue

https://github.com/owncloud/core/issues/31464

## Motivation and Context

The file cache repair step can be omitted if the current oC version is 10.0.4 or greater than 10.0.4.

## How Has This Been Tested?

Below are the steps done for verification:
```
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.3.tar.bz2; mv owncloud/* . 
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y
➜  owncloud4 rm -fr data config/config.php; ./occ  maintenance:install --admin-user "admin" --admin-pass "admin"
Cannot load Xdebug - it was already loaded
ownCloud is not installed - only a limited number of commands are available
creating sqlite db
ownCloud was successfully installed
➜  owncloud4 vim config/config.php 
➜  owncloud4 ./occ user:add user1
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user1" was created successfully
➜  owncloud4 cp -fa config/config.php /tmp/backup/10.0.3 ; cp -fa data /tmp/backup/10.0.3    
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.4.tar.bz2; mv owncloud/* .        
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y

➜  owncloud4 
➜  owncloud4 cp -fa /tmp/backup/10.0.3/config.php config/ ; cp -fa /tmp/backup/10.0.3/data . 
➜  owncloud4 ./occ maintenance:mode --on; sudo /etc/init.d/apache2 stop                      
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode enabled
Please also consider to stop the web server on all ownCloud instances
[ ok ] Stopping apache2 (via systemctl): apache2.service.
➜  owncloud4 

➜  owncloud4 ./occ upgrade                                                                   
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-15T07:15:11+00:00 Set log level to debug
2018-06-15T07:15:11+00:00 Turned on maintenance mode
2018-06-15T07:15:11+00:00 Repair step: Repair MySQL database engine
2018-06-15T07:15:11+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T07:15:11+00:00 Repair step: Repair MySQL collation
2018-06-15T07:15:11+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T07:15:11+00:00 Repair step: Repair SQLite autoincrement
2018-06-15T07:15:12+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-06-15T07:15:12+00:00 Repair info: lucene_status table does not exist -> nothing to do
2018-06-15T07:15:12+00:00 Repair step: Upgrade app code from the marketplace
2018-06-15T07:15:12+00:00 Repair info: Using market to update existing apps
2018-06-15T07:15:12+00:00 Repair info: Attempting to update the following existing compatible apps from market: 
2018-06-15T07:15:12+00:00 Repair info: Fetching app from market: activity
2018-06-15T07:15:16+00:00 Repair info: 
2018-06-15T07:15:16+00:00 Repair info: Fetching app from market: admin_audit
2018-06-15T07:15:19+00:00 Repair info: 
2018-06-15T07:15:19+00:00 Repair info: Fetching app from market: comments
2018-06-15T07:15:23+00:00 Repair info: App (comments) is not known at the marketplace.
2018-06-15T07:15:23+00:00 Repair info: Fetching app from market: configreport
2018-06-15T07:15:26+00:00 Repair info: App (configreport) is not known at the marketplace.
2018-06-15T07:15:26+00:00 Repair info: Fetching app from market: dav
2018-06-15T07:15:29+00:00 Repair info: App (dav) is not known at the marketplace.
2018-06-15T07:15:29+00:00 Repair info: Fetching app from market: diagnostics
2018-06-15T07:15:33+00:00 Repair info: 
2018-06-15T07:15:33+00:00 Repair info: Fetching app from market: enterprise_key
2018-06-15T07:15:40+00:00 Repair warning: Marketplace API key missing
2018-06-15T07:15:40+00:00 Updating database schema
2018-06-15T07:15:40+00:00 Updated database
2018-06-15T07:15:40+00:00 Updating <market> ...
2018-06-15T07:15:40+00:00 Updated <market> to 0.2.3
2018-06-15T07:15:40+00:00 Updating <dav> ...
2018-06-15T07:15:40+00:00 Updated <dav> to 0.3.2
2018-06-15T07:15:40+00:00 Updating <notifications> ...
2018-06-15T07:15:40+00:00 Updated <notifications> to 0.3.2
2018-06-15T07:15:40+00:00 Repair step: Repair mime types
2018-06-15T07:15:40+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
2018-06-15T07:15:40+00:00 Repair step: Generate ETags for file where no ETag is present.
2018-06-15T07:15:40+00:00 Repair info: ETags have been fixed for 0 files/folders.
2018-06-15T07:15:40+00:00 Repair step: Clean tags and favorites
2018-06-15T07:15:40+00:00 Repair info: 0 tags of deleted users have been removed.
2018-06-15T07:15:40+00:00 Repair info: 0 tags for delete files have been removed.
2018-06-15T07:15:40+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2018-06-15T07:15:40+00:00 Repair info: 0 tags with no entries have been removed.
2018-06-15T07:15:40+00:00 Repair step: Drop old database tables
2018-06-15T07:15:40+00:00 Drop old database tables
2018-06-15T07:15:40+00:00 
                                                    2018-06-15T07:15:40+00:00  Done
 28/28 [============================] 100%2018-06-15T07:15:40+00:00 
2018-06-15T07:15:40+00:00 Repair step: Drop old background jobs
2018-06-15T07:15:40+00:00 Repair step: Remove getetag entries in properties table
2018-06-15T07:15:40+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
2018-06-15T07:15:40+00:00 Repair step: Repair outdated OCS IDs
2018-06-15T07:15:40+00:00 Repair step: Repair invalid shares
2018-06-15T07:15:40+00:00 Repair step: Remove old share propagation app entries
2018-06-15T07:15:40+00:00 Repair step: Move user avatars outside the homes to the new location
2018-06-15T07:15:40+00:00 Repair step: Remove shares of a users root folder
2018-06-15T07:15:40+00:00 Repair step: Repair unmerged shares
2018-06-15T07:15:40+00:00 Starting code integrity check...
2018-06-15T07:16:19+00:00 Finished code integrity check
2018-06-15T07:16:19+00:00 Update successful
2018-06-15T07:16:19+00:00 Turned off maintenance mode
2018-06-15T07:16:19+00:00 Reset log level
➜  owncloud4

➜  owncloud4 cp -fa config/config.php /tmp/backup/10.0.4 ; cp -fa data /tmp/backup/10.0.4

➜  owncloud4 cp -fa /tmp/backup/10.0.4/config.php config/ ; cp -fa /tmp/backup/10.0.4/data .

➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.8.tar.bz2; mv owncloud/* .

➜  owncloud4 cp -f /tmp/RepairMismatchFileCachePath.php lib/private/Repair/RepairMismatchFileCachePath.php
➜  owncloud4 cp -f /tmp/Repair.php lib/private/Repair.php

➜  owncloud4 ./occ upgrade                                                                                
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-15T07:43:24+00:00 Set log level to debug
2018-06-15T07:43:24+00:00 Turned on maintenance mode
2018-06-15T07:43:24+00:00 Repair step: Repair MySQL database engine
2018-06-15T07:43:24+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T07:43:24+00:00 Repair step: Repair MySQL collation
2018-06-15T07:43:24+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T07:43:24+00:00 Repair step: Repair SQLite autoincrement
2018-06-15T07:43:24+00:00 Repair step: Repair orphaned reshare
2018-06-15T07:43:24+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-06-15T07: [...]

2018-06-15 11:56 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31803

2018-06-15 12:05 UTC, PVince81 requested changes
You touched code that affects "occ files:scan --repair" so please retest that. The code tells me that it doesn't work any more.

2018-06-15 12:05 UTC, PVince81 commented on lib/private/Repair.php
> +				\OC::$server->getLogger(), \OC::$server->getConfig()),
please be consistent with the above line formatting

2018-06-15 12:05 UTC, PVince81 commented on lib/private/Repair/RepairMismatchFileCachePath.php
> +								ILogger $logger, IConfig $config) {
same here, be consistent with formatting

2018-06-15 12:05 UTC, PVince81 commented on lib/private/Repair/RepairMismatchFileCachePath.php
> +		if (\version_compare($currentOCVersion, '10.0.4', '<')) {
this code confuses me, had to look up how other repair steps do it

it's not always the current OC version:
- during occ upgrade, it's the version from which we are upgrading from
- when run from occ files:scan, it's the currently installed version: this means the repair step will never run with that command ?

2018-06-15 13:43 UTC, sharidas commented
The reason for using `array_unshift` in the code is to preserve the order of the array.
Below are the output captured from the console which makes sure that this change works
- This particular repair step is called when version is less than 10.0.4. Any version greater than 10.0.4 during upgrade, the repair step is not called.
- This repair step is not blocked during file scan. The version restriction isn't applied to files scan.

Upgrade before 10.0.4  call filecache repair:
```
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.4.tar.bz2; mv owncloud/* .
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y
➜  owncloud4 cp -fa /tmp/backup/10.0.3/config.php config/ ; cp -fa /tmp/backup/10.0.3/data . 
➜  owncloud4 ./occ upgrade                                                                   
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-15T13:34:43+00:00 Set log level to debug
2018-06-15T13:34:43+00:00 Turned on maintenance mode
2018-06-15T13:34:43+00:00 Repair step: Repair MySQL database engine
2018-06-15T13:34:43+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T13:34:43+00:00 Repair step: Repair MySQL collation
2018-06-15T13:34:43+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T13:34:43+00:00 Repair step: Repair SQLite autoincrement
2018-06-15T13:34:44+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-06-15T13:34:44+00:00 Repair info: lucene_status table does not exist -> nothing to do
2018-06-15T13:34:44+00:00 Repair step: Upgrade app code from the marketplace
2018-06-15T13:34:44+00:00 Repair info: Using market to update existing apps
2018-06-15T13:34:44+00:00 Repair info: Attempting to update the following existing compatible apps from market: 
2018-06-15T13:34:44+00:00 Repair info: Fetching app from market: activity
2018-06-15T13:34:49+00:00 Repair info: 
2018-06-15T13:34:49+00:00 Repair info: Fetching app from market: admin_audit
2018-06-15T13:34:50+00:00 Repair info: 
2018-06-15T13:34:50+00:00 Repair info: Fetching app from market: comments
2018-06-15T13:34:51+00:00 Repair info: App (comments) is not known at the marketplace.
2018-06-15T13:34:51+00:00 Repair info: Fetching app from market: configreport
2018-06-15T13:34:53+00:00 Repair info: App (configreport) is not known at the marketplace.
2018-06-15T13:34:53+00:00 Repair info: Fetching app from market: dav
2018-06-15T13:34:55+00:00 Repair info: App (dav) is not known at the marketplace.
2018-06-15T13:34:55+00:00 Repair info: Fetching app from market: diagnostics
2018-06-15T13:34:56+00:00 Repair info: 
2018-06-15T13:34:56+00:00 Repair info: Fetching app from market: enterprise_key
2018-06-15T13:35:00+00:00 Repair warning: Marketplace API key missing
2018-06-15T13:35:00+00:00 Updating database schema
2018-06-15T13:35:00+00:00 Updated database
2018-06-15T13:35:00+00:00 Updating <market> ...
2018-06-15T13:35:00+00:00 Updated <market> to 0.2.3
2018-06-15T13:35:00+00:00 Updating <dav> ...
2018-06-15T13:35:00+00:00 Updated <dav> to 0.3.2
2018-06-15T13:35:01+00:00 Updating <notifications> ...
2018-06-15T13:35:01+00:00 Updated <notifications> to 0.3.2
2018-06-15T13:35:01+00:00 Repair step: Repair mime types
2018-06-15T13:35:01+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
2018-06-15T13:35:01+00:00 Repair step: Repair mime types
2018-06-15T13:35:01+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
2018-06-15T13:35:01+00:00 Repair step: Generate ETags for file where no ETag is present.
2018-06-15T13:35:01+00:00 Repair info: ETags have been fixed for 0 files/folders.
2018-06-15T13:35:01+00:00 Repair step: Clean tags and favorites
2018-06-15T13:35:01+00:00 Repair info: 0 tags of deleted users have been removed.
2018-06-15T13:35:01+00:00 Repair info: 0 tags for delete files have been removed.
2018-06-15T13:35:01+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2018-06-15T13:35:01+00:00 Repair info: 0 tags with no entries have been removed.
2018-06-15T13:35:01+00:00 Repair step: Drop old database tables
2018-06-15T13:35:01+00:00 Drop old database tables
2018-06-15T13:35:01+00:00 
                                                    2018-06-15T13:35:01+00:00  Done
 28/28 [============================] 100%2018-06-15T13:35:01+00:00 
2018-06-15T13:35:01+00:00 Repair step: Drop old background jobs
2018-06-15T13:35:01+00:00 Repair step: Remove getetag entries in properties table
2018-06-15T13:35:01+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
2018-06-15T13:35:01+00:00 Repair step: Repair outdated OCS IDs
2018-06-15T13:35:01+00:00 Repair step: Repair invalid shares
2018-06-15T13:35:01+00:00 Repair step: Remove old share propagation app entries
2018-06-15T13:35:01+00:00 Repair step: Move user avatars outside the homes to the new location
2018-06-15T13:35:01+00:00 Repair step: Remove shares of a users root folder
2018-06-15T13:35:01+00:00 Repair step: Repair unmerged shares
2018-06-15T13:35:01+00:00 Starting code integrity check...
2018-06-15T13:35:43+00:00 Finished code integrity check
2018-06-15T13:35:43+00:00 Update successful
2018-06-15T13:35:43+00:00 Turned off maintenance mode
2018-06-15T13:35:43+00:00 Reset log level
➜  owncloud4
```

Upgrade after 10.0.4 doesn't call the file cache repair step:

```
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.8.tar.bz2; mv owncloud/* .
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y
➜  owncloud4 cp -fa /tmp/backup/10.0.4/config.php config/ ; cp -fa /tmp/backup/10.0.4/data . 
➜  owncloud4 ./occ upgrade                                                                              
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-15T13:39:58+00:00 Set log level to debug
2018-06-15T13:39:58+00:00 Turned on maintenance mode
2018-06-15T13:39:58+00:00 Repair step: Repair MySQL database engine
2018-06-15T13:39:58+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T13:39:58+00:00 Repair step: Repair MySQL collation
2018-06-15T13:39:58+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-15T13:39:58+00:00 Repair step: Repair SQLite autoincrement
2018-06-15T13:39:58+00:00 Repair step: Repair orphaned reshare
2018-06-15T13:39:58+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-06-15T13:39:58+00:00 Repair info: lucene_status table does not exist -> nothing to do
2018-06-15T13:39:58+00:00 Repair step: Upgrade app code from the marketplace
2018-06-15T13:39:58+00:00 Repair info: Using market to update existing apps
2018-06-15T13:39:58+00:00 Repair info: Attempting to update the following missing apps from market: diagnostics
2018-06-15T13:39:58+00:00 Repair info: Fetching app from market: diagnostics
2018-06-15T13:40:05+00:00 Repair info: Attempting to update the following existing compatible apps from market: diagnostics
2018-06-15T13:40:05+00:00 Repair info: Fetching app from market: activity
2018-06-15T13:40:06+00:00 Repair info: 
2018-06-15T13:40:06+00:00 Repair info: Fetching app from market: admin_audit
2018-06-15T13:40:08+00:00 Repair info: 
2018-06-15T13:40:08+00:00 Repair info: Fetching app from market: comments
2018-06-15T13:40:09+00:00 Repair info: App (comments) is not known at the marketplace.
2018-06-15T13:40:09+00:00 Repair info: Fetching app from market: configreport
2018-06-15T13:40:11+00:00 Repair info: App (configreport) is not known at the marketplace.
2018-06-15T13:40:11+00:00 Repair info: Fetching app from market: dav
2018-06-15T13:40:16+00:00 Rep [...]

2018-06-15 14:14 UTC, sharidas commented
Updated the test.

2018-06-18 08:29 UTC, sharidas commented
- The reason for adding `tests/lib/RealRepairTest.php` is tests/lib/RepairStepTest.php because `RepairStepTest.php` fails by default. For example if we run:

```
➜  owncloud3 git:(master) ✗ make test-php TEST_DATABASE=sqlite TEST_PHP_SUITE=tests/lib/RepairStepTest.php                     
php build/composer.phar install --dev
Cannot load Xdebug - it was already loaded
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
PHPUNIT="/home/sujith/test/owncloud3/lib/composer/phpunit/phpunit/phpunit" build/autotest.sh sqlite tests/lib/RepairStepTest.php
Using PHP executable /usr/bin/php
Cannot load Xdebug - it was already loaded
Cannot load Xdebug - it was already loaded
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for sqlite testing on local storage ...
Installing ....
Cannot load Xdebug - it was already loaded
creating sqlite db
ownCloud was successfully installed
Testing with sqlite ...
Cannot load Xdebug - it was already loaded
/home/sujith/test/owncloud3/lib/composer/phpunit/phpunit/phpunit --configuration phpunit-autotest.xml --coverage-clover autotest-clover-sqlite.xml --coverage-html coverage-html-sqlite --log-junit autotest-results-sqlite.xml ../tests/lib/RepairStepTest.php 
Cannot load Xdebug - it was already loaded
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1 with Xdebug 2.6.0
Configuration: /home/sujith/test/owncloud3/tests/phpunit-autotest.xml

EEWE                                                                4 / 4 (100%)

Time: 5.93 seconds, Memory: 38.00MB

There were 3 errors:

1) Test\RepairTest::testRunRepairStep
Error: Class 'Test\TestRepairStep' not found

/home/sujith/test/owncloud3/tests/lib/RepairStepTest.php:61

2) Test\RepairTest::testRunRepairStepThatFail
Error: Class 'Test\TestRepairStep' not found

/home/sujith/test/owncloud3/tests/lib/RepairStepTest.php:74

3) Test\RepairTest::testRunRepairStepsContinueAfterWarning
Error: Class 'Test\TestRepairStep' not found

/home/sujith/test/owncloud3/tests/lib/RepairStepTest.php:116

--

There was 1 warning:

1) Test\RepairTest::testRunRepairStepsWithException
Cannot stub or mock class or interface "\Test\TestRepairStep" which does not exist

ERRORS!
Tests: 4, Assertions: 0, Errors: 3, Warnings: 1.

Generating code coverage report in Clover XML format ...^CMakefile:163: recipe for target 'test-php' failed
make: *** [test-php] Interrupt

➜  owncloud3 git:(master) ✗
```
That's the reason I quickly wrote `tests/lib/RealRepairTest.php`.

2018-06-18 09:34 UTC, PVince81 commented on lib/private/Repair.php
> +			\array_unshift($repairSteps, new RepairMismatchFileCachePath(
is there a way to keep the version check inside the repair class ?

you might need to refactor its `run()` method to be callable differently from the scanner to skip the version check

2018-06-18 09:36 UTC, PVince81 requested changes

2018-06-18 09:36 UTC, PVince81 commented on tests/lib/RealRepairTest.php
> +class GetRepairTest extends TestCase {
class name doesn't match file name

2018-06-18 09:36 UTC, PVince81 commented on tests/lib/RealRepairTest.php
> +class GetRepairTest extends TestCase {
I see that on master in the RepairStepTest class there are two classes. would be better to move these into two separate files, one for each class.

Then you could add this test in there. However the outcome of https://github.com/owncloud/core/pull/31795/files#r196017158 might obsolete this

2018-06-18 09:48 UTC, sharidas commented on lib/private/Repair.php
> +			\array_unshift($repairSteps, new RepairMismatchFileCachePath(
> is there a way to keep the version check inside the repair class ?

In `RepairMismatchFileCachePath()`, right?

2018-06-18 10:06 UTC, PVince81 commented on lib/private/Repair.php
> +			\array_unshift($repairSteps, new RepairMismatchFileCachePath(
wherever fits: requirement is that the repair code only runs once on upgrade, but can run any time when called from the `occ files:scan --repair` command

2018-06-18 12:31 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +		$this->config->setSystemValue('callFromScanCommand', true);
no... just make a new method in the repair step

2018-06-18 13:02 UTC, sharidas commented on apps/files/lib/Command/Scan.php
> +		$this->config->setSystemValue('callFromScanCommand', true);
Added a new method in the repair step. And removed the systemValue being written and updated logic.

2018-06-18 13:03 UTC, sharidas commented
With the latest change updated, below are the console log output:

upgrade from 10.0.3 to 10.0.4:
----------------------------------------
```
10.0.3 to 10.0.4
------------------
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.3.tar.bz2; mv owncloud/* .        
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? %                                                                                                            ➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.4.tar.bz2; mv owncloud/* .
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y
➜  owncloud4 cp -fa /tmp/backup/10.0.3/data .; cp -fa /tmp/backup/10.0.3/config.php config
➜  owncloud4 ./occ maintenance:singleuser --on                                            
Cannot load Xdebug - it was already loaded
This version of ownCloud is not compatible with PHP 7.2
You are currently running 7.2.6-1+ubuntu16.04.1+deb.sury.org+1.
➜  owncloud4 ./occ maintenance:singleuser --on
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Single user mode enabled
➜  owncloud4 ./occ upgrade                                                                
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-18T12:51:19+00:00 Set log level to debug
2018-06-18T12:51:19+00:00 Turned on maintenance mode
2018-06-18T12:51:19+00:00 Repair step: Repair MySQL database engine
2018-06-18T12:51:19+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-18T12:51:19+00:00 Repair step: Repair MySQL collation
2018-06-18T12:51:19+00:00 Repair info: Not a mysql database -> nothing to do
2018-06-18T12:51:19+00:00 Repair step: Repair SQLite autoincrement
2018-06-18T12:51:19+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-06-18T12:51:19+00:00 Repair info: lucene_status table does not exist -> nothing to do
2018-06-18T12:51:19+00:00 Repair step: Upgrade app code from the marketplace
2018-06-18T12:51:19+00:00 Repair info: Using market to update existing apps
2018-06-18T12:51:19+00:00 Repair info: Attempting to update the following existing compatible apps from market: 
2018-06-18T12:51:19+00:00 Repair info: Fetching app from market: activity
2018-06-18T12:51:27+00:00 Repair info: 
2018-06-18T12:51:27+00:00 Repair info: Fetching app from market: admin_audit
2018-06-18T12:51:28+00:00 Repair info: 
2018-06-18T12:51:28+00:00 Repair info: Fetching app from market: comments
2018-06-18T12:51:30+00:00 Repair info: App (comments) is not known at the marketplace.
2018-06-18T12:51:30+00:00 Repair info: Fetching app from market: configreport
2018-06-18T12:51:31+00:00 Repair info: App (configreport) is not known at the marketplace.
2018-06-18T12:51:31+00:00 Repair info: Fetching app from market: dav
2018-06-18T12:51:33+00:00 Repair info: App (dav) is not known at the marketplace.
2018-06-18T12:51:33+00:00 Repair info: Fetching app from market: diagnostics
2018-06-18T12:51:35+00:00 Repair info: 
2018-06-18T12:51:35+00:00 Repair info: Fetching app from market: enterprise_key
2018-06-18T12:51:39+00:00 Repair warning: Marketplace API key missing
2018-06-18T12:51:39+00:00 Updating database schema
2018-06-18T12:51:39+00:00 Updated database
2018-06-18T12:51:39+00:00 Updating <market> ...
2018-06-18T12:51:39+00:00 Updated <market> to 0.2.3
2018-06-18T12:51:39+00:00 Updating <dav> ...
2018-06-18T12:51:39+00:00 Updated <dav> to 0.3.2
2018-06-18T12:51:39+00:00 Updating <notifications> ...
2018-06-18T12:51:39+00:00 Updated <notifications> to 0.3.2
2018-06-18T12:51:39+00:00 Repair step: Repair mime types
2018-06-18T12:51:39+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
2018-06-18T12:51:39+00:00 Repair step: Generate ETags for file where no ETag is present.
2018-06-18T12:51:39+00:00 Repair info: ETags have been fixed for 0 files/folders.
2018-06-18T12:51:39+00:00 Repair step: Clean tags and favorites
2018-06-18T12:51:39+00:00 Repair info: 0 tags of deleted users have been removed.
2018-06-18T12:51:39+00:00 Repair info: 0 tags for delete files have been removed.
2018-06-18T12:51:39+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2018-06-18T12:51:39+00:00 Repair info: 0 tags with no entries have been removed.
2018-06-18T12:51:39+00:00 Repair step: Drop old database tables
2018-06-18T12:51:39+00:00 Drop old database tables
2018-06-18T12:51:39+00:00 
                                                    2018-06-18T12:51:39+00:00  Done
 28/28 [============================] 100%2018-06-18T12:51:39+00:00 
2018-06-18T12:51:39+00:00 Repair step: Drop old background jobs
2018-06-18T12:51:39+00:00 Repair step: Remove getetag entries in properties table
2018-06-18T12:51:39+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
2018-06-18T12:51:39+00:00 Repair step: Repair outdated OCS IDs
2018-06-18T12:51:39+00:00 Repair step: Repair invalid shares
2018-06-18T12:51:39+00:00 Repair step: Remove old share propagation app entries
2018-06-18T12:51:39+00:00 Repair step: Move user avatars outside the homes to the new location
2018-06-18T12:51:39+00:00 Repair step: Remove shares of a users root folder
2018-06-18T12:51:39+00:00 Repair step: Repair unmerged shares
2018-06-18T12:51:39+00:00 Starting code integrity check...
2018-06-18T12:52:17+00:00 Finished code integrity check
2018-06-18T12:52:17+00:00 Update successful
2018-06-18T12:52:17+00:00 Turned off maintenance mode
2018-06-18T12:52:17+00:00 Reset log level
➜  owncloud4 ./occ files:scan  --all --repair 
Cannot load Xdebug - it was already loaded
    0 [>---------------------------]

Scanning files for 2 users
Starting scan for user 1 out of 2 (admin)
Starting scan for user 2 out of 2 (user1)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 10      | 10    | 00:00:00     |
+---------+-------+--------------+
➜  owncloud4 ./occ files:scan  --all --repair
Cannot load Xdebug - it was already loaded
    0 [>---------------------------]

Scanning files for 2 users
Starting scan for user 1 out of 2 (admin)
Starting scan for user 2 out of 2 (user1)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 10      | 10    | 00:00:00     |
+---------+-------+--------------+
➜  owncloud4 ./occ files:scan  --all --repair
Cannot load Xdebug - it was already loaded
    0 [>---------------------------]

Scanning files for 2 users
Starting scan for user 1 out of 2 (admin)
Starting scan for user 2 out of 2 (user1)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 10      | 10    | 00:00:00     |
+---------+-------+--------------+
➜  owncloud4
```

Upgrade from 10.0.4 to 10.0.8
----------------------------------------
```
➜  owncloud4 rm -fr * ; tar jxf ~/Downloads/owncloud-enterprise-complete-10.0.8.tar.bz2; mv owncloud/* .
zsh: sure you want to delete all the files in /home/sujith/test/owncloud4 [yn]? y
➜  owncloud4 cp -fa /tmp/backup/10.0.4.2/data .; cp -fa /tmp/backup/10.0.4.2/config.php config 
➜  owncloud4 
➜  owncloud4 ./occ upgrade                                                                    
Cannot load Xdebug - it was already loaded
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-06-18T12:56:29+00:00 Set log level to debug
2018-06-18T12:56:29+00:00 Turned on maintenance mode
2018-06-18T12:56:29+00:00 Repair step: Repair MySQL database engine
2018-06-18T12:56:29+00:00 Repair info: Not a [...]

2018-06-18 13:08 UTC, PVince81 commented on apps/files/lib/Command/Scan.php
> +		$repairStep->canAlwaysRunRepair();
this is what I had in mind:

have two methods:
- $repairStep->doRepair() that does the repair without version check
- $repairStep->run() => this one does the version check then calls `$repairStep->doRepair()`

if you prefer keeping the flag, then call the method something like `setDisableVersionCheck` or something. A method is usually an action so it needs to have the matching verb

2018-06-18 13:14 UTC, sharidas commented on apps/files/lib/Command/Scan.php
> +		$repairStep->canAlwaysRunRepair();
Better to remove the flag...

2018-06-18 13:40 UTC, sharidas commented
https://github.com/owncloud/core/pull/31795#issuecomment-398046803 holds true for the change made.

2018-06-18 13:54 UTC, sharidas commented
Making modification, so that IConfig can be DI to the repair step.

2018-06-18 14:04 UTC, sharidas commented
- added version check's config to constructor. Looks much better now.

2018-06-19 08:37 UTC, PVince81 commented on lib/private/Repair/RepairMismatchFileCachePath.php
> +			$out->info($this->getName() . ' is not executed');
not needed, this will mislead many people reading the upgrade log

2018-06-19 08:38 UTC, PVince81 reviewed
Looks better, please remove the extra unneeded log entry and this is good to go. Thanks

2018-06-19 13:44 UTC, PVince81 approved these changes

2018-06-19 13:45 UTC, merged

2018-06-19 13:45 UTC, PVince81 commented
please backport

2018-06-19 15:48 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/31803