API-test-use-webdav-version-table
owncloud/core pull request #31799
Opened 2018-06-15 10:24 UTC by paurakhsharma

## Description
This PR adds `Scenario Outline` table for using `old DAV path` and `new DAV path` in a single scenario.

## How Has This Been Tested?
Locally

## Motivation
To make reading test scenarios more easier.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-15 10:57 UTC, paurakhsharma commented
Some problem with caldav-test. Can someone restart the drone?

2018-06-18 06:45 UTC, phil-davis requested changes
There are a few changes to make - see comments.
But I think this looks like a good thing to do. It removes all the copied scenarios, condensing them into scenario outlines.

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiMain/checksums.feature
>    @local_storage
Looks like this tag should also be deleted.

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiMain/favorites.feature
> -	Scenario: sharee file favorite state should not change the favorite state of sharer
This scenario is different/opposite to the one above. I think it needs to come back and have scenario outline applied.

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Examples:
indent

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Scenario Outline: Renaming a folder to a backslash encoded should return an error using new endpoint
delete "using new endpoint" from the scenario outline descriptions (from here down...)

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Scenario Outline: Downloading a file on the new endpoint should serve security headers
delete "on the new endpoint"

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
> -	Scenario: Setting custom DAV property using a new endpoint and reading it using an old endpoint
This scenario has gone nowhere. It is a mix of old and new. Maybe we should make a feature called ``webdav-related-old-vs-new.feature`` ?
There is a "requirement"  that when something is done using new DAV path, that the change is seen when using old DAV path and the opposite.
You could even write the scenario with an outline table like:
```
	Examples:
			| action_dav_version | other_dav_version |
			| old | new|
			| new | old |
```

2018-06-18 06:45 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
>  	Scenario: Setting custom DAV property using an old endpoint and reading it using a new endpoint
See comment above - this scenario can probably be made into a scenario outline...

2018-06-18 06:47 UTC, phil-davis commented
@paurakhsharma 
1) I rebased this to fix the caldav issue (there are now 4 caldav/carddav test jobs on drone and a folder got renamed). So you will need to delete your local branch and get it again from GitHub.
2) Please keep the first commit, and add a commit with the changes - that will be much easier to review.
3) When it is all good, it can be squashed.

2018-06-18 07:06 UTC, phil-davis commented
And codecov results did not come. Don't worry about that - might be luckier when you push another commit :)

2018-06-18 09:34 UTC, paurakhsharma commented on tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
>  	Scenario: Setting custom DAV property using an old endpoint and reading it using a new endpoint
I have moved scenario to webdav-related.feature

2018-06-18 09:34 UTC, paurakhsharma commented on tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
> -	Scenario: Setting custom DAV property using a new endpoint and reading it using an old endpoint
Thank you for this ides.
I have moved scenario to webdav-related.feature

2018-06-18 10:41 UTC, phil-davis commented on tests/acceptance/features/apiMain/checksums.feature
> -  @local_storage
This looks like it uses local_storage - so the tag should stay.

2018-06-18 10:41 UTC, phil-davis commented on tests/acceptance/features/apiMain/favorites.feature
> -	Scenario: sharee file favorite state should not change the favorite state of sharer
This still needs to come back.

2018-06-18 10:44 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Scenario: Doing a GET with a web login should work with CSRF token on the new backend
Does this really only work on the new backend?
Or can you put back the scenario outline, and just change the scenario description?

2018-06-18 10:44 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Scenario: Doing a PROPFIND with a web login should work with CSRF token on the new backend
Does this really only work on the new backend?
Or can you put back the scenario outline, and just change the scenario description?

2018-06-18 10:44 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related.feature
> +	Scenario Outline: Setting custom DAV property using one endpoint and reading it with other endpoint
good

2018-06-18 10:44 UTC, phil-davis commented on tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
> -	Scenario: Setting custom DAV property using a new endpoint and reading it using an old endpoint
good

2018-06-18 10:45 UTC, phil-davis reviewed
A couple more comments...

2018-06-20 07:30 UTC, phil-davis approved these changes

2018-06-20 07:33 UTC, phil-davis commented
@DeepDiver1975 or @PVince81 - lost the codecov battle here. This is Behat feature files only, so I have no idea what codecov is thinking.

Can you override and merge this please?

2018-06-20 08:43 UTC, merged

2018-06-20 10:13 UTC, paurakhsharma commented
Backport on #31842