Provide a pre-commit hooks which disallows commit if the code style f…
owncloud/core pull request #31837
Opened 2018-06-20 06:37 UTC by DeepDiver1975

…ails

## Description
Committing without having valid php code style in place is pointless.
This pre-commit hook runs make test-php-style and disallows to commit if the code style is wrong.

Please note that this does not automatically install the pre-commit hook. Each and every user has to locally install the hook script

```sh
cd .git/hooks
ln -s ../../build/git-hooks/pre-commit.sh pre-commit
```

## Screenshots (if appropriate):
![screenshot from 2018-06-20 08-35-45](https://user-images.githubusercontent.com/1005065/41641262-0b62a470-7465-11e8-9623-04def4c0687d.png)
![screenshot from 2018-06-20 08-36-06](https://user-images.githubusercontent.com/1005065/41641261-0b245e9a-7465-11e8-916d-6d3fdd034307.png)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-20 23:32 UTC, patrickjahns commented
Please use `.githooks` or `.hooks` in the root folder. Using `build` as a dump all folder is not suitable.

(needs cleaning up from my pov instead of having more permanent files added).

Please add this to the documentation - alternatively instead of committing this into the repository, add it to the developer documentation as best practice?

2018-06-21 06:30 UTC, DeepDiver1975 commented
> Please add this to the documentation - alternatively instead of committing this into the repository, add it to the developer documentation as best practice?

I think it is more convenient to have the hook script(s) in the git repo and the developer does a simple ln into .git/hooks

2018-06-21 07:55 UTC, PVince81 commented
how long does the script take ? last time I ran php-cs-fixer locally it seemed to take ages. not nice if this happens for every commit.

if the style checker can be scoped to the commit's changes then ok

2018-06-21 07:56 UTC, PVince81 requested changes
style check must only run on actually modified files

2018-06-21 09:28 UTC, phil-davis commented
note: php-cs-fixer keeps a cache of stuff it checked previously, so it is much faster after the first run (assuming you didn't change 1000 files in your branch)

2018-06-21 13:53 UTC, PVince81 commented
not sure if it's my env but currently when I run `make test-php-style` it shows a lot of Fs.
I'm trying to run it to the end again as the previous run had an "out of memory error" despite the allowed 1Gb.

2018-06-21 13:55 UTC, PVince81 commented
![image](https://user-images.githubusercontent.com/277525/41723477-7ac5235e-756b-11e8-9b84-41ce43985c16.png)

2018-06-21 14:52 UTC, phil-davis commented
@PVince81 I have a lot less lines of ``.........`` than you. Somehow in your environment it is checking more than just the core files. 

``.php_cs.dist`` should have code in it that builds and exclude list of all the folders in ``apps`` that are not bundled in the core repo.

2018-06-21 17:40 UTC, patrickjahns commented
> I think it is more convenient to have the hook script(s) in the git repo and the developer does a simple ln into .git/hooks

talking about convenience - introduce a make rule, that looks for scripts in .githooks and symlinks them into `.git/hooks` ;-)

I leave it up 2 you guys - but before merging - please add it to documentation

2018-06-25 07:12 UTC, DeepDiver1975 commented
script moved to .githooks

2018-06-25 15:37 UTC, patrickjahns commented
How about providing a simple makefile rule to include the githooks:
```
init:
  find .git/hooks -type l -exec rm {} \;
  find .githooks -type f -exec ln -sf ../../{} .git/hooks/ \;
```

Originally by https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/

2018-06-25 18:28 UTC, DeepDiver1975 commented
> How about providing a simple makefile rule to include the githooks:

nice - wanna commit to this PR right away?

2018-06-26 08:30 UTC, PVince81 commented
> .php_cs.dist should have code in it that builds an exclude list of all the folders in apps that are not bundled in the core repo.

I tired adding "apps2", "apps3" and "apps-external" to `php_cs.dist` but I still see a forest of `F`.

If you guys agree I can push this here.

2018-06-27 07:47 UTC, PVince81 commented
I'll use https://github.com/owncloud/core/issues/31863#issuecomment-400575991 to continue investigating why I get errors / out of memory despite exclusion of apps2/apps3

2018-07-24 16:03 UTC, PVince81 commented
my problems with the style checker have been solved already

carry on with the commit hook ?

2018-07-26 10:45 UTC, PVince81 commented on .githooks/pre-commit.sh
> +#  cd .git/hooks
extra space before cd

maybe prefix all commands with a "% " as it's universally understood as "run this command"

2018-08-06 09:25 UTC, DeepDiver1975 commented on .githooks/pre-commit.sh
> +#  cd .git/hooks
It is simply indented by one char - I don't care much how to doc this in here. I guess people will understand that cd and ln are commands to be used on the terminal

2018-08-08 14:58 UTC, PVince81 commented on .githooks/pre-commit.sh
> +#  cd .git/hooks
fine by me, merge ?

2018-10-17 08:52 UTC, closed without merging