Adjust IProvider2::isAvailable to match IProvider::isAvailable as wel…
owncloud/core pull request #31846
Opened 2018-06-20 14:25 UTC by DeepDiver1975

…l as IPreview::isAvailable

## Description
IPreview::isAvailable requires FileInfo as argument - IProvider2::isAvailable shall use the same otherwise we are breaking the API.

```
{"reqId":"2SbzswhSScFkJApSWk0H","level":3,"time":"2018-06-20T13:46:41+00:00","remoteAddr":"80.187.104.75","user":"admin","app":"index","method":"GET","url":"/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 1 passed to OC\\Preview\\TXT::isAvailable() must be an instance of OCP\\Files\\File, instance of OC\\Files\\FileInfo given, called in /var/www/owncloud/lib/private/PreviewManager.php on line 221\",\"Code\":0,\"Trace\":\"
#0 /var/www/owncloud/lib/private/PreviewManager.php(221): OC\\Preview\\TXT->isAvailable(Object(OC\\Files\\FileInfo))
#1 /var/www/owncloud/apps/activity/lib/Controller/OCSEndPoint.php(311): OC\\PreviewManager->isAvailable(Object(OC\\Files\\FileInfo))
#2 /var/www/owncloud/apps/activity/lib/Controller/OCSEndPoint.php(238): OCA\\Activity\\Controller\\OCSEndPoint->getPreview('admin', 39081, '/Hacker-Songs/N...')
#3 /var/www/owncloud/apps/activity/lib/Controller/OCSEndPoint.php(181): OCA\\Activity\\Controller\\OCSEndPoint->get(Array)
#4 /var/www/owncloud/apps/activity/lib/Controller/EndPoint.php(68): OCA\\Activity\\Controller\\OCSEndPoint->getFilter(Array)
#5 [internal function]: OCA\\Activity\\Controller\\EndPoint->getFilter('all')
#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#7 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Activity\\Controller\\EndPoint), 'getFilter')
#8 /var/www/owncloud/lib/private/AppFramework/App.php(103): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Activity\\Controller\\EndPoint), 'getFilter')
#9 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\\AppFramework\\App::main('EndPointControl...', 'getFilter', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)
#11 /var/www/owncloud/lib/private/Route/Router.php(342): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)
#12 /var/www/owncloud/lib/base.php(919): OC\\Route\\Router->match('/apps/activity/...')
#13 /var/www/owncloud/index.php(55): OC::handleRequest()
#14 {main}\",\"File\":\"/var/www/owncloud/lib/private/Preview/TXT.php\",\"Line\":97}"}
```

## Motivation and Context
Don't break our public api

## How Has This Been Tested?
- retest activity app - @michaelstingl has detailed steps

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-06-20 14:27 UTC, PVince81 commented on lib/private/Preview/Image.php
> +	public function isAvailable(FileInfo $file) {
remove the `File` import everywhere ?

2018-06-20 14:32 UTC, PVince81 requested changes
approach looks good, please adjust the imports

2018-06-20 20:10 UTC, michaelstingl commented
> @michaelstingl has detailed steps

Sorry, no detailed steps. Just broken on my private server. But I can test the PR as soon a patch for stable10 is available.

2018-06-21 08:01 UTC, PVince81 commented
@DeepDiver1975 probably also needs some test adjustments and use a FileInfo mock instead of File ?

2018-06-21 09:50 UTC, DeepDiver1975 commented
> @DeepDiver1975 probably also needs some test adjustments and use a FileInfo mock instead of File ?

adjusted

2018-06-21 10:07 UTC, PVince81 approved these changes
:+1:

2018-06-21 13:32 UTC, merged

2018-06-21 13:32 UTC, PVince81 commented
@DeepDiver1975 please backport

2018-06-26 17:15 UTC, michaelstingl commented
I can confirm, fixed with the `owncloud-10.0.9RC2.tar.bz2`

2018-08-28 15:31 UTC, phil-davis commented
Backport ``stable10`` #31862