[WIP] Cleanup the encryption keys after file deletion
owncloud/core pull request #31844
Opened 2018-06-20 12:20 UTC by sharidas

The encryption keys were not deleted even after
files were deleted from the file system. The
reason for this is because of the wrong path
shared. Instead of filename, the relative path
from the files should be shared.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

The encryption keys should be deleted or removed once the files are deleted from the trashbin.

## Related Issue

## Motivation and Context

The encryption keys should be deleted or removed once the files are deleted from the trashbin.

## How Has This Been Tested?

- Created a user admin and login as admin user
- Now create a file a.txt and try to update it so that versions are also created.
- Before deletion of a.txt this is how the console output of tree command would look like
```
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗ tree data -I "thumbnails"
data
├── admin
│   ├── cache
│   ├── files
│   │   ├── a.txt
│   │   ├── foo
│   │   │   └── f.txt
│   │   └── welcome.txt
│   ├── files_encryption
│   │   └── keys
│   │       └── files
│   │           ├── a.txt
│   │           │   └── OC_DEFAULT_MODULE
│   │           │       ├── fileKey
│   │           │       └── master_fea6d2f9.shareKey
│   │           ├── foo
│   │           │   └── f.txt
│   │           │       └── OC_DEFAULT_MODULE
│   │           │           ├── fileKey
│   │           │           └── master_fea6d2f9.shareKey
│   │           └── welcome.txt
│   │               └── OC_DEFAULT_MODULE
│   │                   ├── fileKey
│   │                   └── master_fea6d2f9.shareKey
│   ├── files_versions
│   │   ├── a.txt.v1529496454
│   │   ├── a.txt.v1529496457
│   │   ├── a.txt.v1529496458
│   │   └── foo
│   │       ├── f.txt.v1529496435
│   │       ├── f.txt.v1529496438
│   │       └── f.txt.v1529496439
│   └── files_zsync
├── avatars
│   ├── 21
│   │   └── 23
│   │       └── 2f297a57a5a743894a0e4a801fc3
│   └── 24
│       └── c9
│           └── e15e52afc47c225b757e7bee1f9d
├── files_encryption
│   └── OC_DEFAULT_MODULE
│       ├── master_fea6d2f9.privateKey
│       ├── master_fea6d2f9.publicKey
│       ├── pubShare_fea6d2f9.privateKey
│       └── pubShare_fea6d2f9.publicKey
├── index.html
├── owncloud.db
└── owncloud.log

26 directories, 22 files
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗
```
- Now delete a.txt so that file moves to trashbin and after this operation the tree command would show us:
```
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗ tree data -I "thumbnails"
data
├── admin
│   ├── cache
│   ├── files
│   │   ├── foo
│   │   │   └── f.txt
│   │   └── welcome.txt
│   ├── files_encryption
│   │   └── keys
│   │       ├── files
│   │       │   ├── foo
│   │       │   │   └── f.txt
│   │       │   │       └── OC_DEFAULT_MODULE
│   │       │   │           ├── fileKey
│   │       │   │           └── master_fea6d2f9.shareKey
│   │       │   └── welcome.txt
│   │       │       └── OC_DEFAULT_MODULE
│   │       │           ├── fileKey
│   │       │           └── master_fea6d2f9.shareKey
│   │       └── files_trashbin
│   │           └── files
│   │               └── a.txt.d1529496497
│   │                   └── OC_DEFAULT_MODULE
│   │                       ├── fileKey
│   │                       └── master_fea6d2f9.shareKey
│   ├── files_trashbin
│   │   ├── files
│   │   │   └── a.txt.d1529496497
│   │   ├── keys
│   │   └── versions
│   │       ├── a.txt.v1529496454.d1529496497
│   │       ├── a.txt.v1529496457.d1529496497
│   │       └── a.txt.v1529496458.d1529496497
│   ├── files_versions
│   │   └── foo
│   │       ├── f.txt.v1529496435
│   │       ├── f.txt.v1529496438
│   │       └── f.txt.v1529496439
│   └── files_zsync
├── avatars
│   ├── 21
│   │   └── 23
│   │       └── 2f297a57a5a743894a0e4a801fc3
│   └── 24
│       └── c9
│           └── e15e52afc47c225b757e7bee1f9d
├── files_encryption
│   └── OC_DEFAULT_MODULE
│       ├── master_fea6d2f9.privateKey
│       ├── master_fea6d2f9.publicKey
│       ├── pubShare_fea6d2f9.privateKey
│       └── pubShare_fea6d2f9.publicKey
├── index.html
├── owncloud.db
└── owncloud.log

32 directories, 22 files
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗
```
- Now delete the file a.txt from the trashbin. And after this operation the kesy should be deleted. Below is the output which justifies the same:
```
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗ tree data -I "thumbnails"
data
├── admin
│   ├── cache
│   ├── files
│   │   ├── foo
│   │   │   └── f.txt
│   │   └── welcome.txt
│   ├── files_encryption
│   │   └── keys
│   │       └── files
│   │           ├── foo
│   │           │   └── f.txt
│   │           │       └── OC_DEFAULT_MODULE
│   │           │           ├── fileKey
│   │           │           └── master_fea6d2f9.shareKey
│   │           └── welcome.txt
│   │               └── OC_DEFAULT_MODULE
│   │                   ├── fileKey
│   │                   └── master_fea6d2f9.shareKey
│   ├── files_trashbin
│   │   └── files
│   ├── files_versions
│   │   └── foo
│   │       ├── f.txt.v1529496435
│   │       ├── f.txt.v1529496438
│   │       └── f.txt.v1529496439
│   └── files_zsync
├── avatars
│   ├── 21
│   │   └── 23
│   │       └── 2f297a57a5a743894a0e4a801fc3
│   └── 24
│       └── c9
│           └── e15e52afc47c225b757e7bee1f9d
├── files_encryption
│   └── OC_DEFAULT_MODULE
│       ├── master_fea6d2f9.privateKey
│       ├── master_fea6d2f9.publicKey
│       ├── pubShare_fea6d2f9.privateKey
│       └── pubShare_fea6d2f9.publicKey
├── index.html
├── owncloud.db
└── owncloud.log

26 directories, 16 files
➜  owncloud3 git:(fix-encryptionkey-trashbin) ✗ 
```

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-20 13:59 UTC, tomneedham commented
Tests?

2018-06-20 14:00 UTC, sharidas commented
> Tests?

Yes working on the same

2018-06-20 14:44 UTC, pako81 commented
Tested on 10.0.9RC1. Works as expected.

2018-06-21 09:06 UTC, PVince81 requested changes
please add unit tests as discussed, mock the source storage

2018-06-28 09:49 UTC, PVince81 approved these changes

2018-06-28 09:50 UTC, merged

2018-06-28 09:50 UTC, PVince81 commented
@sharidas please backport