Search API based on webDAV report
owncloud/core pull request #31873
Opened 2018-06-22 12:41 UTC by jvillafanez

## Description
Add support to search files through webDAV

## Related Issue
https://github.com/owncloud/core/issues/25373

## Motivation and Context
Allow search file using the REPORT webDAV method. The request must be made to the base of the user's directory for files, usually "/remote.php/webdav/" or "/remote.php/dav/files/myuser/". Trying to search in inner directories will return an NotImplemented exception.

The minimum xml body request is:
```
<?xml version="1.0" encoding="utf-8" ?>
<oc:search-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns" >
        <oc:search>
                <oc:pattern>search-pattern</oc:pattern>
        </oc:search>
</oc:search-files>
```

The base xml body request must be:
```
<?xml version="1.0" encoding="utf-8" ?>
<oc:search-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns" >
        <a:prop>
                <oc:fileid/>
                <oc:permissions/>
                <a:getlastmodified/>
                <a:getetag/>
                <a:getcontenttype/>
                <oc:size/>
                <oc:owner-id/>
                <oc:owner-display-name/>
                <oc:size/>
        </a:prop>
        <oc:search>
                <oc:pattern>gif</oc:pattern>
                <oc:limit>5</oc:limit>
        </oc:search>
</oc:search-files>
```

The list of properties can be adjusted to get what you need as any PROPFIND request.
The base search limit is hardcoded to 30 results if no explicit limit is set in the request.

## How Has This Been Tested?
Manually tested

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-22 14:18 UTC, DeepDiver1975 requested changes
looks good over app - please add tests- THX

2018-06-22 14:18 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +		/**
indent

2018-06-22 14:18 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +	 * @param \OC\Search\Result\File[] $searchResults the results coming from the search service, within the files app
add use statement - 80 chars per line please

2018-06-25 12:43 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +		$searchResults = $this->searchService->searchPaged($searchInfo['pattern'], ['files'], 1, $limit);
is 1 page one ? strange that it doesn't start at zero...

2018-06-25 12:43 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +			return $filesUri . $searchResult->path;
sad that the search result doesn't contain node ids as it would spare us a step

but for the sake of "keep it simple" and not touching too many things, this is ok

2018-06-26 11:56 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +		$searchResults = $this->searchService->searchPaged($searchInfo['pattern'], ['files'], 1, $limit);
According to the phpdocs in the function, it starts at 1. The default value is also 1. 🤷‍♂️

2018-06-26 11:58 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +			return $filesUri . $searchResult->path;
I'd vote for a new API for searches. Something that needs to be planned in any case.

2018-06-27 08:00 UTC, jvillafanez commented on apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
> +		/**
Looks like this slipped by... I'll fix this during the squash

2018-06-27 10:44 UTC, jvillafanez commented
squashed (with minor fixes)

2018-06-28 09:06 UTC, PVince81 approved these changes
:+1:

2018-06-28 09:06 UTC, merged

2018-06-28 09:07 UTC, PVince81 commented
@jvillafanez please backport

2018-08-28 15:27 UTC, phil-davis commented
Backport PR #31946 has been merged.