Acceptance tests for issue 31870 share auto-accept for groups
owncloud/core pull request #31913
Opened 2018-06-26 10:42 UTC by phil-davis

## Description
1) ``sharingNotifications.feature:52`` - make a group share when auto-accept is on. Now turn off auto-accept. Make a new user in the group. All the users should get notifications, but they don't.

2) ``sharingNotifications.feature:80`` - make a group share when auto-accept is off. Make a new user in the group. Existing users get a notification - good. The new user should also get a notification, but does not - bad.

3) ``sharingNotifications.feature:108`` - make a group share when auto-accept is off. Turn on auto-accept. Make a new user in the group. The new user gets no notification - good. But the existing users still get notifications - bad.

4) ``sharingNotifications.feature:118`` - make a group share when auto-accept is on. Make a new user in the group. None of the users get notifications - good, the existing code happens to work for this sequence of actions.

## Related Issue
#31870 

## Motivation and Context
Share auto-accept for members of groups is inconsistent.
Make test scenarios that demonstrate the issue.

## How Has This Been Tested?
Run scenarios locally and confirm that they fail against current ``master``

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance tests

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed - except the ones that are supposed to fail ;)

2018-06-26 11:16 UTC, individual-it requested changes
one question, rest looks logical to me

2018-06-26 11:16 UTC, individual-it commented on tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
> +		Then user "user1" should have 1 notification
why should the old user have a notification? The old user already auto-accepted the share when it got shared

2018-06-26 11:57 UTC, phil-davis commented on tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
> +		Then user "user1" should have 1 notification
In this particular sequence, ``user1`` has not logged in (since the share was created). e.g. ``user1`` was on 1 month leave. She arrives back at work. During the time away, some folders were shared with her, some when auto-accept was on (like here) and some after auto-accept was switched off.

With the current code, she will get the "older" shares auto-accepted and will have notifications about the newer shares. So it might seem inconsistent.

But actually this scenario is not a big deal - someone can decide the requirement for what happens to the existing notifications (or not) of users when the auto-accept setting is toggled.

2018-06-26 12:07 UTC, phil-davis commented on tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
> +		Then user "user1" should have 1 notification
I just manually tested the reverse also, 

1) get ``userx`` in a state where they have a notification waiting to accept/decline a share.
2) enable auto-accept (system-wide setting)
3) login as ``userx``
4) ``userx`` still has the notification about the pending share
5) ``userx`` can accept/decline the share from the notification.

These seem harmless - existing users in groups do not get their notifications "synced-up" at the moment that the auto-accept setting is changed.

2018-06-26 12:16 UTC, phil-davis commented
The "trouble" in all this is because the notifications are "registered" to the relevant users at the time the share is created. So after that, whenever anything happens to the share or the group (or the auto-accept setting, if that is a requirement), then the pending notifications have to be adjusted to match:

1) share added - add notifications - works
2) share removed - remove notifications - works
3) user added to group - give them notifications for shares to that group - not implemented
4) user removed from group - take away notifications about shares to that group - not implemented
5) auto_accept switched on - remove all pending notifications about shares - not implemented
6) auto_accept switched off - add all pending notifications about shares - not implemented

2018-06-26 16:22 UTC, PVince81 commented
hmm, how come CI passes while the test was supposed to enforce the behavior from https://github.com/owncloud/core/issues/31870 ?

or should we first merge the tests that reflect the current behavior and adjust later when the fix comes ?

2018-06-26 16:45 UTC, phil-davis commented
The tests that fail are skipped. The dev who "fixes" the behavior some day, should remove the ``@skip`` lines.

2018-06-28 12:04 UTC, individual-it approved these changes

2018-06-28 12:06 UTC, individual-it commented
after merging this would be good to have an todo item in the issue to remind the dev. to remove the corresponding `@skip` lines

2018-06-28 12:16 UTC, phil-davis commented
I will leave this waiting for a few days. There is a lot of discussion in the issue. So the exact desired behavior needs to be finally decided.

2018-06-29 09:03 UTC, PVince81 commented
at this point it tends to "leave it by design", but we can check again later when @pmaier1 is back

2018-07-17 08:08 UTC, PVince81 commented
@phil-davis we've closed https://github.com/owncloud/core/issues/31870 as "won't fix", please adjust the PR accordingly, if needed.

2018-07-17 14:59 UTC, phil-davis commented
I wil look at the end of the week when I am back in the office.

2018-08-08 14:56 UTC, PVince81 commented
@phil-davis did you get a chance ?

2018-08-23 13:41 UTC, phil-davis commented
@individual-it please review again.
I have now documented the existing behavior in the scenarios. The rough summary is that existing notifications do not come or go as auto-accept is switched on or off, and that as users are added to a group, they do not get sent notifications about the group shares they just received.

2018-08-24 03:54 UTC, individual-it approved these changes

2018-08-24 04:02 UTC, phil-davis commented
Backport ``stable10`` #32432

2018-08-24 06:36 UTC, merged