Resubmit of "[stable10] generated resource routes should allow slashes""
owncloud/core pull request #31939
Opened 2018-06-28 11:51 UTC by PVince81

Resubmit of original PR that was merged by mistake.

Don't merge due to code freeze!

2018-07-18 06:58 UTC, DeepDiver1975 requested changes

2018-07-18 06:58 UTC, DeepDiver1975 commented on tests/lib/Route/RouterTest.php
> +	public function __construct($name = null, array $data = [], $dataName = '') {
Why in ctor? setup is to be used for initializations

2018-07-18 07:30 UTC, PVince81 commented on tests/lib/Route/RouterTest.php
> +	public function __construct($name = null, array $data = [], $dataName = '') {
arghh, no idea, it was like this in the original PR. I'll fix this on master first then

2018-07-25 19:31 UTC, PVince81 commented on tests/lib/Route/RouterTest.php
> +	public function __construct($name = null, array $data = [], $dataName = '') {
here we go for master https://github.com/owncloud/core/pull/32158

already cherry-picked here

2018-08-01 09:26 UTC, DeepDiver1975 approved these changes

2018-08-01 09:26 UTC, merged