[objectstorage] Cache stat while fetching objectstore object metadata
owncloud/core pull request #31958
Opened 2018-06-30 17:22 UTC by mrow4a

### Description

Due to the fact that objectstorage uses filecache as metadata, and not filesystem/objectstorage directly, the same logic for calling stat is inefficient - specificly for `getMetadata` call. 

### Related PRs

Due to the fact there is no decision on introducing "cache of filecache", this PR is just fixing the code logic. 

- Cache in filecache (https://github.com/owncloud/core/pull/28166)
- Cache of objectstore metadata (https://github.com/owncloud/core/pull/31486)

@PVince81 @DeepDiver1975 @butonic

2018-07-02 09:14 UTC, PVince81 commented
this is likely not enough, you also need logic to invalidate the entries whenever other file operations are called.

remember that many high level file operations might involve more than a single low level FS operation

here's an example stat cache that was added for external storage: https://github.com/owncloud/core/blob/v10.0.8/lib/private/Files/Storage/DAV.php#L78 and https://github.com/owncloud/core/blob/v10.0.8/lib/private/Files/Storage/CacheableFlysystem.php#L32

2018-07-02 17:07 UTC, mrow4a commented
@PVince81 the stat cache gets set and invalidated in the same function - getMetadata. There is no other place in code to set the cache - so cache will leave only for duration of that function

2018-07-02 20:37 UTC, PVince81 commented
so are we assuming that all file operations like $objectStore->unlink() and $objectStore->rename() will call `getMetadata()` again to invalidate and refresh the stat cache info ? it might be the case now but there is no guarantee it will be in the future

2018-07-03 19:57 UTC, mrow4a commented
@PVince81 so your suggestion is to have a look how stat cache is realized in other implementations?

2018-07-04 09:10 UTC, PVince81 commented
> so your suggestion is to have a look how stat cache is realized in other implementations?

that or think about stat cache invalidation for every file operation that go through the storage

2018-08-07 06:11 UTC, mrow4a commented
@butonic what do you think about approach suggested by @PVince81 ?

2018-08-12 14:13 UTC, mrow4a commented
@PVince81 @DeepDiver1975 @butonic @tomneedham all tests passing - I also updated the PR description with the context.

2018-08-20 12:52 UTC, mrow4a commented
@butonic this does not touch filecache at all. It is a layer below, storage stat cache - please look a description. CC @PVince81 @DeepDiver1975

2018-08-20 17:18 UTC, mrow4a commented
@butonic and to mention further, this PR is only to make objectstore work with similar performance as filesystem, no filecache "caching" is here in place, I just cache results of the filesystem calls wrapped by objectstorage

2018-08-21 06:59 UTC, mrow4a commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +				$this->objectStatCache->set($path, $stat);
@DeepDiver1975 @butonic note that I only cache stat calls for objects metadata, not a file-tree (filecache trees)

2018-08-21 08:02 UTC, PVince81 commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +	private function rmObjects($path) {
why has this method been moved down ? this makes it difficult to review as now we can't see whether you made change to it

if you want to reformat a file please do so in a separate commit

2018-08-21 08:03 UTC, PVince81 commented
I agree with @mrow4a that a stat cache on the storage class is useful to avoid repeated real-storage access as higher level OC code tends to repeat operations (like file_exists, etc). We already use this approach for other storages like DAV, Dropbox, etc.

2018-08-21 09:25 UTC, mrow4a commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +	private function rmObjects($path) {
You can also use diff -> split. But I can do it in separate commit, should I?

2018-08-21 09:31 UTC, mrow4a commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +				$this->objectStatCache->set($path, $stat);
additionally, file need to exists to be cached (I don't cache e.g. false)

2018-09-18 09:37 UTC, DeepDiver1975 requested changes
I'm fine in merging this to master and get an understanding how this works.

We shall rebase and rerun the tests ....

2018-10-10 18:13 UTC, mrow4a commented
@DeepDiver1975 @PVince81 any decision on this?

2018-10-26 10:21 UTC, butonic submitted a review, later dismissed
I like the conservative approach. It at least caches stuff for objectstorage.

2018-10-26 10:21 UTC, butonic commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +		$this->objectStatCache = new ArrayCache();
this will eat memory when doing a lot of file activities, eg in a background job. use `CappedMemoryCache`

2018-11-07 21:53 UTC, DeepDiver1975 approved these changes

2018-11-07 23:05 UTC, merged

2018-11-08 18:34 UTC, mrow4a commented
@DeepDiver1975 @butonic I will keep an eye on smashbox with objectostrage tests for this change.