Fix update to reset column on oracle
owncloud/core pull request #31989
Opened 2018-07-04 15:21 UTC by IljaN

## Description
FileCache columns were not reset on oracle when an empty value was passed instead of null.
Issue: #31692

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

Unit-tests 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-04 15:23 UTC, DeepDiver1975 requested changes

2018-07-04 15:23 UTC, DeepDiver1975 commented on lib/private/Files/Cache/Cache.php
> +		if ($this->connection->getDatabasePlatform()->getName() === 'oracle') {
usually we go for
```php
if ($this->connection->getDatabasePlatform() instanceof OraclePlatform) {

2018-07-04 15:29 UTC, IljaN commented on lib/private/Files/Cache/Cache.php
> +		if ($this->connection->getDatabasePlatform()->getName() === 'oracle') {
Will push changes after/if more change requests arrive to conserve ci-ressources.

2018-07-05 09:51 UTC, PVince81 approved these changes
:+1:

2018-07-05 09:55 UTC, DeepDiver1975 approved these changes

2018-07-05 10:03 UTC, merged

2018-07-05 10:21 UTC, IljaN commented
Backport here: https://github.com/owncloud/core/pull/31996