Always try avatar migration. Stored when done. Skip when done already
owncloud/core pull request #31994
Opened 2018-07-05 10:04 UTC by tomneedham

## Description
For some upgrades, this migration took too long and was not completed. I removed the version check so that it can be attempted again using `occ maintenance:repair` without downtime. It will store when it is complete, and 

## Related Issue

- Fixes <issue_link>

## Motivation and Context
Failed avatar migrations, and avatars were disabled. This allows another attempt at the migration, without downtime, even after upgrade to ownCloud 10.

## How Has This Been Tested?
 - Manually running the occ maintenance:repair command

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-05 10:05 UTC, tomneedham commented
Related: https://github.com/owncloud/core/issues/29868

2018-07-05 12:11 UTC, PVince81 requested changes
see comments

2018-07-05 12:11 UTC, PVince81 commented on lib/private/Repair.php
> +			new RepairMismatchFileCachePath(
starting with 10.0.10 we'l anyway only run this one once: https://github.com/owncloud/core/pull/31803

now wondering whether we should revert that in case someone wants to rerun the check ? or add the check as part of occ files:scan --repair-check ?

2018-07-05 12:11 UTC, PVince81 commented on lib/private/Repair/MoveAvatarOutsideHome.php
> +		// TODO when installed_at is finally stored, dont run if installed_at >= 10.0.0
the PR https://github.com/owncloud/core/pull/30140 was merged, please adjust.

is there no other approach like what versions we're upgrading from ? 9.2 is actually supposed to be 10.0

2018-07-05 12:11 UTC, PVince81 commented
please run `make test-php-style` locally

2018-07-12 10:30 UTC, tomneedham commented on lib/private/Repair.php
> +			new RepairMismatchFileCachePath(
I don't like the version checks because they stop you from using the code again without code hacks. I think this solution is better.

2018-07-12 10:33 UTC, tomneedham commented
> please run make test-php-style locally

Can I tell this to look only at core? Otherwise output is massive with it considering every app I have cloned locally - not really usable

2018-07-12 11:05 UTC, phil-davis commented
``test-php-style`` ignores any "bonus" apps in the ``apps``  folder.

2018-07-12 14:33 UTC, tomneedham commented
> test-php-style ignores any "bonus" apps in the apps folder.

Not custom app dirs it seems :/

2018-07-12 14:39 UTC, phil-davis commented
> Not custom app dirs it seems
@PVince81 had this problem, and I guess has added some ``excludes`` for his local repo - you might ask him what he did.

2018-07-12 14:46 UTC, tomneedham commented
Updated to not run if installed since owncloud 10 and updated code style.

2018-08-08 14:52 UTC, PVince81 commented
@tomneedham can you adjust the tests of the move avatar repair steps to match the new checks ?

2018-08-23 13:40 UTC, tomneedham commented
> @tomneedham can you adjust the tests of the move avatar repair steps to match the new checks ?

not sure I fully understand what you mean @PVince81 ?

2018-08-23 14:27 UTC, PVince81 commented
@tomneedham does MoveAvatarOutsideHomeTest contain any tests for the version checks ?

2019-02-08 16:50 UTC, PVince81 commented
@tomneedham instructions for take over ?

2019-02-21 16:57 UTC, tomneedham commented
Avatars were migrated from OC 9 -> 10. This is done with a repair step. This is quite expensive and some installations skipped it. 

This PR makes this step only run once - and stores when complete. This also allows us to reset that flag and try again should we need it.

2019-02-21 16:58 UTC, tomneedham commented
> @tomneedham does MoveAvatarOutsideHomeTest contain any tests for the version checks ?

It does - but it uses `first_installed_version` which was only added recently. So we still do a check to see if it has executed before, and store a flag on complete.

2019-02-21 16:59 UTC, closed without merging

2019-02-21 17:00 UTC, tomneedham commented
Closing this actually. I think we can come up with a better strategy to fix instances where we need to re-run the avatar migration.

2019-03-09 03:04 UTC, phil-davis commented
Removing backport label since this has been closed.