Improve logging text in config.sample.php
owncloud/core pull request #32035
Opened 2018-07-12 08:14 UTC by mmattel

## Description
Alternative approach for https://github.com/owncloud/core/pull/32030
Only merge this or the other one !

This PR just improves the text a bit and references for the details the logging section in the documentation - keeping config.sample.php small and clean.

The log rotate script will be added in the logging section at the documentation!

## Related Issue

- Fixes https://github.com/owncloud/documentation/issues/2998 
(Document best practice examples to rotate/compress oC logfiles)

## Motivation and Context
Improve log rotation capabilities, see referenced doc issue

## How Has This Been Tested?

No test necessary, doc text changes only.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/documentation/issues/2998

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

@voroyam @michaelstingl

2018-07-12 09:11 UTC, mmattel commented
Drone tells...
```
Error response from daemon: Get https://registry-1.docker.io/v2/selenium/standalone-chrome-debug/manifests/latest: 
dial tcp: lookup registry-1.docker.io on 172.16.102.1:53: no such host
```

2018-07-13 08:57 UTC, settermjd commented on config/config.sample.php
> + * These parameters configure the options for logging.
I'd suggest making it just a bit shorter and more direct with:

> These parameters configure the logging options.

2018-07-13 08:58 UTC, settermjd commented on config/config.sample.php
> + * For additional information or advanced configuration please see the logging
One minor, nitpicky, change:

> For additional information or advanced configuration, please see the logging section in the documentation.

2018-07-13 08:59 UTC, settermjd commented on config/config.sample.php
> + * A new logfile is created with a new name when the old logfile reaches your limit.
s/when the old logfile reaches your limit./when the old logfile reaches the defined limit./g

2018-07-13 09:00 UTC, settermjd commented on config/config.sample.php
> + * If enabled, only the active log file and one rotation file are present.
s/and one rotation file are present./and one rotated file are stored./g

2018-07-13 09:00 UTC, settermjd requested changes
On the whole, it looks good. Just a few minor changes.

2018-07-13 11:46 UTC, mmattel commented
Changes added, many thanks @settermjd

2018-07-13 13:42 UTC, settermjd approved these changes
Thanks!

2018-07-13 14:05 UTC, mmattel commented
I love drone...
```
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled 
while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

2018-07-13 14:09 UTC, phil-davis commented
I restarted the drone job for you. Fingers-crossed.

2018-07-13 14:11 UTC, phil-davis commented
Backport ``stable10`` #32049

2018-07-17 08:05 UTC, merged