Add methods to disable or enable sharing settings
owncloud/core pull request #32043
Opened 2018-07-13 10:13 UTC by paurakhsharma

## Description
This PR adds toggle functions to disabling/enabling sharing settings.

## Related Issue
#31983

## How Has This Been Tested?
Locally

## Types of changes
- [x] Tests

## Checklist:
- [x] Acceptance tests added

2018-07-13 17:22 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
> +		$this->getSession()->reload();
Why do we need the reloads everywhere?

2018-07-13 17:22 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
> -	 * @When the admin disables share via link using the webUI
You could use regular expression in the step to have the same line for enable/disable, then you could use the old steps and don't need to change existing scenarios

2018-07-13 17:22 UTC, individual-it commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +	public function toggleShareApi($requiredState) {
A lot of duplicated in the toggle functions, maybe we can combine them?

2018-07-16 09:56 UTC, individual-it requested changes

2018-07-16 09:56 UTC, individual-it commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		$checkCheckbox = $this->findById($checkboxId);
please check if `find*()` returns `null`

2018-07-16 09:56 UTC, individual-it commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +	 * @param string $action e.g "|enables|disables|"
not "e.g." only "enables" or "disables" can be used

2018-07-16 09:56 UTC, individual-it commented on tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
> +		Scenario: enable resharing
wrong indent

2018-07-16 10:10 UTC, paurakhsharma commented
@individual-it can you please review it again. Thank you :slightly_smiling_face:

2018-07-16 10:20 UTC, individual-it approved these changes

2018-07-16 10:21 UTC, individual-it commented
looks good lets see what :robot: says
please backport

2018-07-16 10:38 UTC, paurakhsharma commented
@PVince81 Some problem with codecov. Can you please merge this PR.

2018-07-16 10:44 UTC, merged

2018-07-16 10:44 UTC, PVince81 commented
please backport

2018-07-16 10:44 UTC, paurakhsharma commented
Ok, thank you

2018-07-16 10:45 UTC, paurakhsharma commented
Backport on #32054