Add ownCloud motto change password email
owncloud/core pull request #32081
Opened 2018-07-18 09:22 UTC by imujjwal96

## Description

- Added the motto as footer
- Added alternative Plain text page for notify email
- Update notify email with html template.

## Related Issue

- Fixes #32042 

## How Has This Been Tested?

- test environment: https://
ec2-35-154-227-4.ap-south-1.compute.amazonaws.com

## Screenshots (if appropriate):
<img width="752" alt="screen shot 2018-07-18 at 2 50 53 pm" src="https://user-images.githubusercontent.com/8245662/42872233-006fa7ca-8a9a-11e8-9aaf-910fcccacf09.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-26 12:19 UTC, VicDeo requested changes

2018-07-26 12:19 UTC, VicDeo commented on core/templates/lostpassword/notify.php
> +						echo $l->t('Password changed successfully');
p($l->t('Password changed successfully'));

2018-07-26 12:19 UTC, VicDeo commented on core/Controller/LostController.php
> +
two empty lines won't pass CI, please remove this one.

2018-07-26 12:19 UTC, VicDeo commented on core/templates/lostpassword/altnotify.php
> +echo $l->t('Password changed successfully');
p($l->t('Password changed successfully'));

2018-08-01 12:16 UTC, DeepDiver1975 commented
@imujjwal96 can I kindly ask you to adapt the unit tests? THX

```
1) Tests\Core\Controller\LostControllerTest::testSetPasswordSuccessful
Failed asserting that Array &0 (
    'status' => 'error'
    'msg' => 'Expectation failed for method name is equal to <string:setPlainBody> when invoked at sequence index 2
Parameter 0 for invocation OC\Mail\Message::setPlainBody('Password changed successfully...ud.org') does not match expected value.
Failed asserting that two strings are equal.'
) is identical to Array &0 (
    'status' => 'success'
).

/drone/src/tests/Core/Controller/LostControllerTest.php:536

2019-02-07 15:58 UTC, PVince81 commented
@imujjwal96 are you still interested in finishing this ? see comment above

2019-02-12 16:26 UTC, closed without merging