Cleanup federation phase 1
owncloud/core pull request #32086
Opened 2018-07-18 15:04 UTC by VicDeo

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-20 13:04 UTC, PVince81 commented on apps/federatedfilesharing/lib/FedShareManager.php
> +		$link = \OCP\Util::linkToAbsolute('files', 'index.php', $args);
note for later: we could use permalink here, see ViewController how to generate one

2018-07-20 13:10 UTC, PVince81 requested changes
Awesome!

Please adjust the exception catch block I pointed to

2018-07-20 13:10 UTC, PVince81 commented on apps/federatedfilesharing/lib/RequestHandler.php
> +		} catch (\Exception $e) {
better catch Share\Exceptions\ShareNotFound then and let the other through for proper error reporting ?

2018-07-20 13:10 UTC, PVince81 commented on apps/federatedfilesharing/lib/RequestHandler.php
> +		} catch (\Exception $e) {
same here

2018-07-20 13:10 UTC, PVince81 commented on apps/files_sharing/ajax/external.php
> +$federatedSharingApp = new \OCA\FederatedFileSharing\AppInfo\Application();
sad to see we still have ajax endpoints, oh well

2018-07-20 14:10 UTC, VicDeo commented
@PVince81 updated

2018-07-20 16:19 UTC, PVince81 approved these changes
:+1:

2018-07-20 16:20 UTC, PVince81 commented
As discussed, unit tests will be added in the next round

2018-07-20 16:20 UTC, merged

2018-07-20 16:20 UTC, PVince81 commented
no backport for now

2018-10-05 10:45 UTC, VicDeo commented
Stable10: https://github.com/owncloud/core/pull/33027