Fixes #32090 - browser extension urls in origin header do not trigger…
owncloud/core pull request #32120
Opened 2018-07-23 07:09 UTC by DeepDiver1975

… CORS verification

## Description
Browser extension send an Origin header with an url which has the schema moz-extension or chromw-extension. We shall no perform CORS verification on these requests since they come from non-websites.

## Related Issue
- Fixes #32090 

## How Has This Been Tested?
- not tested personally with an extension
- maybe @julianpoemp can help testing if extensions work now

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-23 08:08 UTC, julianpoemp commented
@DeepDiver1975 tested your new version again. Unfortunality it didn't work on my owncloud installation with Chrome (extensions Buttercup and Tusk). I replaced the old CorsPlugin.php with the new version.

My little change of your code before fixed even my issue with webdav on MacOS. With this fix the connection to webdav via Finder workes for me.

2018-07-23 08:34 UTC, julianpoemp commented
I found the problem:
The return of ``$request->getHeader('Origin');`` is ``"null"`` as string and not al ``null``. Checked it with an easy if condition.

2018-07-23 08:53 UTC, alfredbuehler commented
I was curious about the impact of that change on my ocpad. Surprisingly, the "<all_urls>" in the manifest.json is still required for oc10.

2018-07-23 10:11 UTC, DeepDiver1975 commented
> @DeepDiver1975 I found the problem:
> The return of $request->getHeader('Origin'); is "null" as string and not al null. That's why the condition if(empty($originHeader) does not trigger. Checked it with an easy if condition if($originHeader == "null")

but "null" is an invalid value - see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
this is clearly a but in the extensions from my point of view

2018-07-27 09:49 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (empty($originHeader)) {
empty is evil and also matches the string "0"

2018-07-27 09:49 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (empty($originHeader)) {
should we rather match the string "null" and not the object `null` here ?
as I understood this line was intended to catch the null case

2018-07-27 09:50 UTC, PVince81 commented
I'm fine catching null. Maybe add a PHPDoc comment to say this is sent by some clients that do not respect the spec.

2018-07-27 09:50 UTC, PVince81 requested changes
see comments

2018-07-27 12:44 UTC, DeepDiver1975 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (empty($originHeader)) {
agreed on the evil empty.

I'm undecided about the "null" comparison ....

2018-07-27 12:56 UTC, julianpoemp commented
if this is considered as evil, what Do you think about this?:
A new option in config.php, something  like "AllowNullOrigin", that is false by default. If set "null" and null as value for origin is allowed. In that way it's the admin's responsibility to allow it or not.

2018-07-27 13:07 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +		if (empty($originHeader)) {
there is more benefit in adding it as more clients will work correctly again

we could consider this "bug" a regression because before we had CORS the mentioned client likely already worked as we had no Origin check, which would increase severity

I suggest we move forward with the null and add a warning. If there are tickets in said client trackers, you could refer these here as well. If in the future this gets fixed there, we can remove the workaround again.

2018-07-27 13:11 UTC, DeepDiver1975 commented
@PVince81 addressed please have a look again
@julianpoemp I decided to accept 'null' for now - let's see ...

2018-07-30 07:50 UTC, DeepDiver1975 commented
@PVince81 addressed please have a look again
@julianpoemp I decided to accept 'null' for now - let's see ...

2018-07-30 07:57 UTC, PVince81 approved these changes
:+1:

2018-07-30 07:57 UTC, PVince81 commented
@julianpoemp mind testing this patch to confirm that the clients you use work now ?

2018-07-30 08:36 UTC, julianpoemp commented
it works very fine! I tested it with Firefox, Chrome, Opera and Buttercup Extension on MacOS and Windows 10.

@DeepDiver1975 , @PVince81 thank you!

2018-07-30 08:53 UTC, merged