Add hidden password field on share to fool the browser password-popup
owncloud/core pull request #32195
Opened 2018-07-30 16:38 UTC by felixheidecke

## Description
Added an extra hidden password field in the public share to fool the browsers password-save popup panel upon entering a password for the share.

Based on the ideas mentioned [here](https://gist.github.com/runspired/b9fdf1fa74fc9fb4554418dea35718fe)

## Related Issue

- Fixes https://github.com/owncloud/core/issues/28259

## How Has This Been Tested?

Visual test on Mac Chrome & Firefox and Win IE11

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-07-30 16:39 UTC, felixheidecke commented
This might need some testing on other machines and browsers.

2018-07-31 07:04 UTC, PVince81 commented on core/js/sharedialoglinkshareview.js
> +				'<input style="position:absolute;left:-100px;top:-100px;" type="password" name="fakepasswordrememberedworkaround">' +
can we define a global CSS class for "offscreen" elements ? I thought we already had one

2018-07-31 07:04 UTC, PVince81 commented
@felixheidecke mind also testing Safari ?

2018-07-31 07:27 UTC, felixheidecke commented on core/js/sharedialoglinkshareview.js
> +				'<input style="position:absolute;left:-100px;top:-100px;" type="password" name="fakepasswordrememberedworkaround">' +
I'll have a look, if I can't find any, I'll have one done.

2018-07-31 07:28 UTC, felixheidecke commented
> mind also testing Safari ?

Works as well, at least on my system ;-) Would be nice to have more people test it.

2018-08-02 08:24 UTC, felixheidecke commented
@haukman did you have time to check it out?

2018-08-02 13:05 UTC, haukman commented
When I try to apply the patch I get the following error:

```
root@61eb98ec7331: /var/www/owncloud/core/js # patch < /var/www/owncloud/patch  --dry-run
(Patch is indented 2 spaces.)
checking file sharedialoglinkshareview.js
patch: **** malformed patch at line 23:                                   '</div>' +
```
Not sure if the issue is on my side ;)

2018-08-08 08:24 UTC, PVince81 requested changes

2018-08-08 08:37 UTC, felixheidecke commented
@haukman … hmmm … "funny"

```
Applying: Add hidden password field on share to fool the browser password-popup
.git/rebase-apply/patch:14: trailing whitespace.
				'<input style="position:absolute;left:-100px;top:-100px;" type="password" name="fakepasswordrememberedworkaround">' +
error: patch failed: core/js/sharedialoglinkshareview.js:41
error: core/js/sharedialoglinkshareview.js: patch does not apply
Patch failed at 0001 Add hidden password field on share to fool the browser password-popup```

2018-08-08 08:52 UTC, felixheidecke commented
@PVince81 I added the class. However, this "fix" is very hacky and wobbly and may not work in upcoming browser releases.

2018-08-08 16:46 UTC, felixheidecke commented
@haukman have you found other means of testing this? Can't help you with the patch :-(

2018-08-09 11:03 UTC, patrickjahns commented
@ownclouders rebase

2018-08-09 11:03 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-08-09 11:05 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-08-10 12:53 UTC, haukman commented
@PVince81: Can you help with the patch?

2018-08-10 16:13 UTC, PVince81 commented
@felixheidecke please recreate a patch for @haukman based on stable10 or v10.0.9.
a patch of a PR to master likely doesn't apply cleanly on stable10 or v10.0.9

2018-08-13 12:36 UTC, felixheidecke commented
The patch is the same for stable10: [32195-stable10.txt](https://github.com/owncloud/core/files/2282939/32195-stable10.patch.txt)

2018-08-14 13:33 UTC, DeepDiver1975 commented
> The patch is the same for stable10: 32195-stable10.txt

@haukman can you test and verify this is fixed now? THX

2018-08-21 08:45 UTC, PVince81 commented
@felixheidecke please create a patch on top of v10.0.9 not stable10.

2018-08-28 09:51 UTC, haukman commented
same issue as before: 

```
root@ae1a8e355dc9: /var/www/owncloud # patch -p 1 <patch 
patching file core/js/sharedialoglinkshareview.js
patch: **** malformed patch at line 13:                                   '</div>' +
```
Did you test that patch? :P

2018-08-29 08:59 UTC, felixheidecke commented
@haukman have you simply tried `git apply 32195-v10.0.9.patch.txt` ??
I see no need for the -p flag here

2018-08-29 09:01 UTC, PVince81 commented
@felixheidecke he's using the tarball, please provide a patch and a command that works for the 10.0.9 tarball

2018-08-30 08:47 UTC, felixheidecke commented
Sorry @haukman the patch works fine on my system. I just patched my 10.0.9 tarball:

![bildschirmfoto von 2018-08-30 10-43-40](https://user-images.githubusercontent.com/12717530/44840691-e767ee80-ac41-11e8-975d-e304c9603cd1.png)

Are you using Windows or some sh*t?

2018-08-30 13:34 UTC, felixheidecke commented
What worked the last time doesn't work anymore :-(
There is another workaround that kinda goes like this':

`<input name="password" type="text" style="font-family:'dotsfont'>` 

Mean that the password field is reverted to a simple text input using a font-face that only displays dots. I don't know if this threatens security or not. If the font doesn't load, the password is displayed.

Here is the font in question: https://github.com/kylewelsby/dotsfont
Is this so important that we want to go this route?

2018-08-31 05:56 UTC, PVince81 commented
@settermjd any thoughts about this approach ?

This is likely not an issue because the password is being typed and any JS code can read it anyway, regardless of field type.

This also means that selecting the dots and copy-pasting will work as well.

@felixheidecke do all modern browsers support loading custom fonts now ? Has this approach been recommended anywhere ?

2018-08-31 05:57 UTC, PVince81 commented
does the font also work for Chinese 汉字 and Cyrillic for example ?

2018-09-03 11:33 UTC, felixheidecke commented
There might be another solution to the problem. We cloud forego the classic form submission so that the browser does not recognize the password saving process. I'll give it a go and come back with the results.

2018-10-24 10:20 UTC, felixheidecke commented
As I was looking into it, there is no classic `.submit()` anywhere and there is even no `<form>` wrapping around it. So the solution I suggested is not valid.

At this point I would just leave it alone and live with it. *…sigh*

2018-11-06 11:45 UTC, felixheidecke commented
@haukman any updates on how to proceed? I wouldn't want to sink any more time into this sinking ship :-P

2018-11-14 15:04 UTC, felixheidecke commented
After further research, I found no solution that works reliably across all browsers. I suggest keeping an eye on the matter and I will open a new PR / issue if browsers do change in that matter.

2018-11-14 15:06 UTC, closed without merging