Add support in the actions to mark if the clients should redirect
owncloud/core pull request #32212
Opened 2018-08-01 12:13 UTC by jvillafanez

## Description

## Related Issue

- Fixes (required for https://github.com/owncloud/notifications/issues/212)

## Motivation and Context
Adding this support is required to fix https://github.com/owncloud/notifications/issues/212

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-01 12:47 UTC, DeepDiver1975 requested changes

2018-08-01 12:47 UTC, DeepDiver1975 commented on lib/private/Notification/Action.php
> +		$this->redirect = false;
initialize the field itself - no need to set this in ctor.

2018-08-01 12:47 UTC, DeepDiver1975 commented on lib/public/Notification/IAction.php
> +	 * @since 10.0.10
@PVince81 10.0.10 - was that agreed on? Just asking ... this change has implications to core + 2 apps. 

Didn't we want 10.0.10 to be a bug fix release only? again - just asking. THX

2018-08-01 13:14 UTC, PVince81 commented on lib/public/Notification/IAction.php
> +	 * @since 10.0.10
this is currently just a POC, we still should agree on the approach proposed in https://github.com/owncloud/notifications/issues/212

I don't think there was a decision about 10.0.10 being bug fix release only. However from the list of open tasks it will likely be a "90% bugfixing" and "10% new stuff" release so far.

The above is mostly needed to resolve the redirect actions problem which is a tech debt introduced by the password policy, I hoped we could iron it out for 10.0.10 instead of letting it get forgotten.

2019-02-07 16:00 UTC, PVince81 commented
I'm closing this for now until there is interest in continuing https://github.com/owncloud/notifications/issues/212.
we can reopen and adjust once we have an agreement on the approach and also a commitment to make it happen with all clients.

2019-02-07 16:00 UTC, closed without merging