#32217 Change the file locking on large uploads
owncloud/core pull request #32226
Opened 2018-08-02 15:15 UTC by micbar

## Description
When uploading large files >10GB, the assembly process on the server runs very long (>5minutes). This causes a timeout on the client side (Version 2.4.2). The setup is a clustered web server behind a F5 load balancer.
New move Requests by the client, let the running assembly processes fail.

## Related Issue

- Fixes #32217 

## Motivation and Context
Created PR to test if we can make the file locking process more robust

## How Has This Been Tested?
- test environment: Local docker images with Desktop client 2.4.2
- test case 1: Upload 10GB file, while slowing down the assembly process (sleep()) to produce timout at the client side

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ x] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-03 12:11 UTC, DeepDiver1975 requested changes
Please fix unit tests - rest :+1:

2018-08-06 15:40 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->changeLock(ILockingProvider::LOCK_EXCLUSIVE);
please move this before `fopen` to avoid having two concurrent processes opening the file at the same time

2018-08-10 12:04 UTC, micbar commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->changeLock(ILockingProvider::LOCK_EXCLUSIVE);
are you sure? If i do this, tho whole operations fails.
Is it possible to lock a file before opening?

2018-08-10 16:04 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +				$this->changeLock(ILockingProvider::LOCK_EXCLUSIVE);
how exactly does it fail ? it shouldn't fail as the storage fopen shouldn't lock anything. Maybe there is something else that is suspicious there...

in general if we leave it like you did then a concurrent process would be able to lock the target file, but would fail after fopen and before starting stream copy. so the error handler would need to close the file again, which I think will happen anyway.

would still be good to investigate why moving the lock before makes the operation fail, in case there are some ghosts hidden somewhere...

2018-08-13 15:26 UTC, micbar commented
@DeepDiver1975 @PVince81 
I had to adjust the testing of the put method.

As seen in https://github.com/owncloud/core/blob/eda2a55adfdecbe6af0f9e8ad589f878b64c1912/apps/dav/lib/Connector/Sabre/LockPlugin.php#L64
the put() is executed with a shared lock.

Please review and ping back, i get the impression, that this is a very sensitive part :-)

2018-08-14 13:39 UTC, DeepDiver1975 approved these changes

2018-08-14 13:39 UTC, merged

2018-08-28 14:51 UTC, phil-davis commented
Backport ``stable10`` #32334

2018-09-10 14:49 UTC, PVince81 commented
@micbar do you remember where exactly you put the `sleep` statements ? this is for expanding the tests for manual QA to verify

2018-09-10 15:27 UTC, micbar commented on apps/dav/lib/Connector/Sabre/File.php
> +
I had a sleep() statement after setting the exclusive lock and before the final move operation.

2018-09-14 16:56 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +
@micbar which value did you use ? how high to set it to have the desktop client time out on its own ?

2018-09-14 17:04 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/File.php
> +
`sleep(300)' in both locations

2018-09-17 07:41 UTC, micbar commented on apps/dav/lib/Connector/Sabre/File.php
> +
The desktop client resends the MOVE request after 300sec.