Change e-mail validation regex to accept subdomains with hyphens.
owncloud/core pull request #32240
Opened 2018-08-06 08:10 UTC by micbar

## Description
The filter regex which helps to validate the entered e-mail addresses does not accept subdomains with hyphens.

### Steps to reproduce
1. Configure ownCloud to allow Users to send notification emails while sharing
2. Share something via public link
3. Send link as e-mail
4. Enter e-mail address

### Expected behaviour
E-Mail address is being added to the field

### Actual behaviour
Some E-Mail addresses with "-" charakter in the **second** subdomain get rejected / could not be added.

#### Examples - working
- firstname.lastname@td-l.xyz
- firstname.lastname@s-ub.tdl.xyz
- firstname.lastname@sub.tdl.xyz

#### Examples - not working
- firstname.lastname@sub.t-dl.xyz
- firstname.lastname@stud.uni-goettingen.de

## Related Issue

- Fixes owncloud/enterprise#2773

## Motivation and Context
This has been discovered by a customer whose domains all contain a second subdomain with a hyphen

## How Has This Been Tested?

- this has been tested manually and 
- and within a regex tester.

## Screenshots (if appropriate):
![screenshot_2018-08-06 dateien - owncloud](https://user-images.githubusercontent.com/4378513/43704690-c99d1cd4-9960-11e8-8b90-4496c3e57890.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-06 10:10 UTC, felixboehm commented
would this work?
firstname.lastname@sub.sub2.tdl.xyz

2018-08-06 10:31 UTC, micbar commented
@felixboehm 
i checked your mail address. It will pass the check.

If you accidently put two dots in the address, it will fail verification.
firstname.lastname@sub.sub2.tdl..xyz

2018-08-06 11:08 UTC, micbar commented
@PVince81 after conversation in the chat, we need your feedback on this.

2018-08-06 11:54 UTC, DeepDiver1975 commented
I'd be happy to see a unit test covering the various samples of email addresses passing the regex.

2018-08-06 14:22 UTC, DeepDiver1975 requested changes
squash commits please

2018-08-06 14:30 UTC, micbar commented
ok, i accidently committed the wrong file

2018-08-06 14:31 UTC, micbar commented
complete mess :-(

2018-08-06 14:41 UTC, micbar commented
sorry for the noise...

2018-08-08 14:11 UTC, PVince81 approved these changes
:+1:

2018-08-08 14:12 UTC, merged

2018-08-08 14:12 UTC, PVince81 commented
@micbar please backport to stable10

2018-08-09 08:17 UTC, phil-davis commented
Backport ``stable10`` #32281