Add method to clear notification when user is deletd
owncloud/core pull request #32260
Opened 2018-08-07 06:53 UTC by sharidas

Added a method to clear notification entry of user
when the user is deleted from oC.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

User entries from notification table should be deleted, once the user is deleted from oC.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

User entries from notification table should be deleted, once the user is deleted from oC.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Requires https://github.com/owncloud/notifications/pull/221

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-07 08:26 UTC, sharidas commented
Fixes -> https://github.com/owncloud/password_policy/issues/69

2018-08-07 09:59 UTC, PVince81 commented on lib/public/Notification/IApp.php
> +	 * @since 10.1.0
I think you can put 10.0.10 here

2018-08-07 09:59 UTC, PVince81 commented on lib/public/Notification/IApp.php
> +	 * @since 10.1.0
PHPDoc is incomplete

2018-08-07 09:59 UTC, PVince81 requested changes
see comment

2018-08-07 14:50 UTC, jvillafanez commented
What are the reasons to provide the solution here?

This implies that the core's notification manager knows that the notification is stored by the apps, which implies that is expected that the apps store notifications somewhere, which leads to store duplicate information (by different apps).

Core doesn't need to know whether the notifications are being stored. If the notifications app or any other provider stores notifications it's their own responsability to clean them.

I'd prefer to move the solution to the notification app: just listen the delete event there and remove the stored notifications. No need to change the core's interface.

2018-08-07 16:13 UTC, sharidas commented
@jvillafanez 
> I'd prefer to move the solution to the notification app: just listen the delete event there and remove the stored notifications. No need to change the core's interface.

In fact you are right, the core should not bother about the changes I made in this PR. The notification app should listen to the event and then do the action, i.e, to remove the entry of the user from the table.
Thanks for the suggestion.

2018-08-08 14:34 UTC, PVince81 commented
@sharidas please link to your new PR in the notifications app then close

2018-08-09 07:44 UTC, sharidas commented
The notification PR https://github.com/owncloud/notifications/pull/221 is sufficient to achieve the result. Hence closing this PR.

2018-08-09 07:44 UTC, closed without merging