Prevent passwords being set with empty strings
owncloud/core pull request #32261
Opened 2018-08-07 08:37 UTC by settermjd

## Description

Currently, if an attempt is made to set a password with an, effectively, empty string it will be accepted
without question. This PR seeks to prevent that from happening, by ensuring that passwords must be set to a meaningful/valid value.

## Related Issue

- Fixes https://github.com/owncloud/security-tracker/issues/282.

## Motivation and Context

It prevents a user's password from being set to an empty string. 

## How Has This Been Tested?

- Unit tests have been added to cover the changes. 

## Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Technical debt
- [X] Tests

## Checklist:

- [X] Code changes
- [X] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-07 09:16 UTC, phil-davis commented on lib/private/User/Database.php
> +		if (empty($password)) {
This will prevent someone setting their password to the string char "0".
I guess that is not such a bad restriction on valid password strings.

2018-08-07 09:57 UTC, settermjd commented on lib/private/User/Database.php
> +		if (empty($password)) {
True. But on reading after coming to understand the code better and reading through https://github.com/owncloud/security-tracker/issues/282 in light of that information, it appears to me that this PR isn't required, as the code works as expected.

2018-08-07 10:38 UTC, settermjd commented on lib/private/User/Database.php
> +		if (empty($password)) {
Turns out, this PR's still in the game after further discussion with @PVince81.

2018-08-07 11:36 UTC, PVince81 commented on lib/private/User/Database.php
> +		if (empty($password)) {
please avoid using `empty()` in any case due to its nasty implicit nature.
if you intend to check for "0" then add an explicit check for it

2018-08-08 07:34 UTC, settermjd commented on lib/private/User/Database.php
> +		if (empty($password)) {
Feedback addressed @PVince81.

2018-08-08 13:48 UTC, PVince81 commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
@DeepDiver1975 thoughts on this ? does PHP 7.2 bring something ?

2018-08-08 13:48 UTC, PVince81 commented on lib/private/User/Database.php
> +			throw new ArgumentNotSetException('Password cannot be empty');
we usually use `\InvalidArgumentException`

2018-08-08 13:51 UTC, PVince81 requested changes
sounds like a bit much adding all these new traits and classes just for this simple thing

2018-08-08 13:51 UTC, PVince81 commented on tests/lib/Traits/PasswordTrait.php
> +	public function providesEmptyPasswordData() {
feels like overkill to have a trait just for this

maybe we could move the test set to the `TestCase` base class and put common data providers there, but then it would be `providesEmptyValues()` and not specific to passwords

2018-08-21 09:35 UTC, settermjd commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
@DeepDiver1975?

2018-08-21 10:07 UTC, PVince81 commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
@settermjd can you remove this trait ? this feels a bit overengineered

2018-08-21 10:08 UTC, PVince81 commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
maybe put this as a local method on the class then. I'd rather move this forward to get it merge then spend a long time trying to decide where this method needs to go

2018-08-21 14:00 UTC, settermjd commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
I'm slightly reluctant as it'd have to be copied into both Database and User, as they don't share a common base class and the functionality's not logically specific to either. However, if that's the call, just say and I'll make it happen.

2018-08-22 15:21 UTC, PVince81 commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
should we then rather move it to \OCP\Util then ? then any app can use it.
a Trait feel a bit like overkill

2018-08-23 06:59 UTC, settermjd commented
@PVince81, is it ok to go now?

2018-08-27 12:06 UTC, PVince81 commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
@settermjd please move this to `\OCP\Util`

2018-08-31 06:11 UTC, PVince81 requested changes
please move the utility function to \OCP\Util

2018-09-04 11:38 UTC, settermjd commented on lib/private/Traits/EmptyStringTrait.php
> +trait EmptyStringTrait {
Odd, I thought I'd already done this.

2018-09-04 12:06 UTC, settermjd commented
@PVince81, the function's been moved. Thanks for the push.

2018-09-04 14:28 UTC, PVince81 commented
please fix the styles, see https://drone.owncloud.com/owncloud/core/10097/69 or run `make test-php-styles`

2018-09-04 19:30 UTC, PVince81 commented
@ownclouders rebase

2018-09-04 19:31 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-09-04 19:32 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-09-04 20:58 UTC, PVince81 commented
squashed. I hope this will also nudge Drone

2018-09-04 21:00 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/32581

hopeful that there were no more testing issues then...

2018-09-05 02:31 UTC, phil-davis commented
Some drone problem in the install-server step of all the sub-jobs. I restarted drone just now.

2018-09-05 07:06 UTC, PVince81 commented
@settermjd I already fixed those myself

2018-09-05 07:06 UTC, PVince81 commented
restarted the builds

2018-09-05 13:12 UTC, PVince81 commented
seems rebasing did not help:
```
federatedfilesharing enabled
+ php occ a:l
Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
+ php occ a:e testing
testing not found
```

maybe resend the PR separately ?

2018-09-05 13:28 UTC, settermjd commented
I don't understand what you're asking in https://github.com/owncloud/core/pull/32261#issuecomment-418725246.

2018-09-05 14:09 UTC, phil-davis commented
@settermjd I rebased it locally and force pushed here. CI is running again, let's see.

2018-09-05 14:36 UTC, phil-davis commented
CI passing :fireworks:

2018-09-05 15:40 UTC, merged