Password reset text formatted and token reset for users not logged in
owncloud/core pull request #32313
Opened 2018-08-13 11:41 UTC by sharidas

Password reset text is formatted accordingly for
users who had not logged in once. Also token reset
is required if the password is reset using password
reset link, when the token is expired.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Password reset template should have text accordingly for users who have not logged in once. The token should be reset, if user sets password for first time using password reset link, and the token is expired. 

## Related Issue

- Fixes <issue_link>

## Motivation and Context

Password reset template should have text accordingly for users who have not logged in once. The token should be reset, if user sets password for first time using password reset link, and the token is expired. 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Required https://github.com/owncloud/user_management/pull/48

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-13 12:18 UTC, jvillafanez commented on core/Controller/LostController.php
> +	private function checkPasswordResetToken(&$token, $userId) {
Unless there is a really good reason to modify the parameter here, better not change this. You shouldn't need to modify the token.

2018-08-13 12:18 UTC, jvillafanez commented on core/templates/lostpassword/resetpassword.php
> +			$link =  \explode('/', $_['link']);
Try to move this code out of the template. The template should just show values, not perform any operation.

2018-08-13 12:18 UTC, jvillafanez commented on core/templates/lostpassword/resetpassword.php
> +			$link =  \explode('/', $_['link']);
```
<?php if ($_['isnewUser']): ?>
<input type="submit" id="submit" value="<?php p($l->t('Please set your password')); ?>" />
<?php else: ?>
<input type="submit" id="submit" value="<?php p($l->t('Reset password')); ?>" />
<?php endif; ?>
```

2018-08-13 12:18 UTC, jvillafanez commented on core/Controller/LostController.php
> +				//This would help to reset the token as the user had not logged in once
I don't know what you're trying to do here. If the token has expired, why would you want to automatically generate a new token without admin permission? This seems that you have a valid permanent token as long as you don't login with that user....

2018-08-16 13:54 UTC, DeepDiver1975 requested changes

2018-08-16 13:54 UTC, DeepDiver1975 commented on core/Controller/LostController.php
> +	private function checkPasswordResetToken(&$token, $userId) {
I have to agree ... this feels wrong ...

2018-08-23 15:30 UTC, sharidas commented
Closing this PR as we have https://github.com/owncloud/user_management/pull/48.

2018-08-23 15:30 UTC, closed without merging