remove .gitignore file from api test skeleton folder
owncloud/core pull request #32323
Opened 2018-08-14 06:41 UTC by individual-it

## Description
replace the `.gitignore` file with an other file with the same size

## Related Issue
https://github.com/owncloud/encryption/pull/41#issuecomment-412764399

## Motivation and Context
The `.gitignore` file does not end up in the QA builds, but we still need a file in the folder, because it's impossible to commit an empty folder. Also we want the new file to be exactly the same size so that all quota tests pass.

## How Has This Been Tested?
ran some quota tests, now let :robot: do its job

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-14 07:07 UTC, phil-davis approved these changes

2018-08-14 07:13 UTC, DeepDiver1975 requested changes

2018-08-14 07:13 UTC, DeepDiver1975 commented on apps/testing/data/apiSkeleton/FOLDER/for-git-commit
> +this file is here because git does not allow to commit empty folders
usually .gitkeep is used

2018-08-14 07:52 UTC, individual-it commented on apps/testing/data/apiSkeleton/FOLDER/for-git-commit
> +this file is here because git does not allow to commit empty folders
@DeepDiver1975 will `.gitkeep` end up in the QA build? `.gitignore` does not

2018-08-14 07:54 UTC, DeepDiver1975 commented on apps/testing/data/apiSkeleton/FOLDER/for-git-commit
> +this file is here because git does not allow to commit empty folders
no idea to be honest

2018-08-14 08:17 UTC, phil-davis commented on apps/testing/data/apiSkeleton/FOLDER/for-git-commit
> +this file is here because git does not allow to commit empty folders
``Makefile`` at the top of ``core`` has:
```
	find $@ -name .gitkeep -delete
	find $@ -name .gitignore -delete
```
It looks like ``.gitkeep`` and ``.gitignore`` get the same treatment when builds are being made.

2018-08-14 08:19 UTC, individual-it commented on apps/testing/data/apiSkeleton/FOLDER/for-git-commit
> +this file is here because git does not allow to commit empty folders
will try to have an empty `.gitkeep` and fix the expected quotas

2018-08-14 10:04 UTC, individual-it commented
@DeepDiver1975 please review again

2018-08-14 10:28 UTC, phil-davis commented
Latest looks good to me.

2018-08-14 13:37 UTC, DeepDiver1975 approved these changes

2018-08-14 13:37 UTC, merged

2018-08-15 06:51 UTC, individual-it commented
backport in #32344