resetpassword command supports send password reset link and display link
owncloud/core pull request #32345
Opened 2018-08-15 15:07 UTC by sharidas

The resetpassword supports options to
1) display the password reset link in command line.
2) send email to reset the password for user and
   display the link in the command line.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

The resetpassword supports options to 
1) display the password reset link in command line.
2) send email to reset the password for user and display the link in the command line.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

The resetpassword supports options to 
1) display the password reset link in command line.
2) send email to reset the password for user and display the link in the command line.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-08-16 08:54 UTC, jvillafanez commented
Do we have an use case for both options? Having the "via-mail" option is hard to figure out why we need the "via-link" option.
I'd expect that if the target user doesn't have an email set, you show a warning message in the console (because you couldn't send the email) and show the link (which I'm not really sure if it's needed... how is the link expected to be sent if the admin doesn't know the user email?)

2018-08-16 09:07 UTC, jvillafanez commented
In addition, I don't have a clear view of the expected flow.
For example: the command to be focused on setting a new password. The password can be provided interactively or via environment variable. Once the password is correctly set, we send an email to the user to notify the password has been reset.

I don't think this is the flow we want, but the current code doesn't seem to have a clear idea such as the one above.

2018-08-22 08:53 UTC, PVince81 commented
@jvillafanez the option to output the link on the CLI is intended for docker setups where VMs are created automatically and a custom email is sent by VM scripts, including the link. For example "your server has been setup, click here to set your initial password: XYZ"

2018-08-22 08:55 UTC, PVince81 commented
As far as I understand this PR is only for generating a password reset token and sending the link by email and/or outputting on the CLI. It is not intended to actually set a password.

2018-08-27 11:47 UTC, sharidas commented
Review required @PVince81

2018-08-27 12:01 UTC, PVince81 commented on core/Command/User/ResetPassword.php
> +				'via-link',
"via link" means "something will be send through a link" and doesn't reflect what is happening here
maybe call it "output-link" or something similar

and rename "via-email" to "send-email"

2018-08-27 12:02 UTC, PVince81 commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
was this copy-pasted from another location ?

2018-08-27 12:02 UTC, PVince81 commented on core/Command/User/ResetPassword.php
> +		} elseif ($displayLink) {
emailing and displaying link aren't mutually exclusive. one could specify both

2018-08-27 12:02 UTC, PVince81 requested changes
see comments

2018-08-27 13:45 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
Yes, this was copy-pasted from LostController.

2018-08-27 13:55 UTC, PVince81 commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
can we make the code reusable ? not too happy to see that many lines copy-pasted...

2018-08-27 14:03 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +		} elseif ($displayLink) {
Updated the code, user can execute either email or displaying link or both.

2018-08-27 14:03 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +				'via-link',
Renamed to "send-email" and "output-link".

2018-08-28 08:25 UTC, PVince81 requested changes
a few more minor things, see comments

2018-08-28 10:55 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
Agreed. I have refactored the code, in which case at this point of time refactoring LostController, would be too much for this PR, I guess.

2018-08-28 10:56 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +		} elseif ($emailLink | $displayLink) {
Done

2018-08-28 10:56 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +					$output->writeln('<error>Can\'t send new user mail to ' . $user->getEMailAddress() . ': ' . $e->getMessage());
Added `</error>`.

2018-08-28 11:16 UTC, PVince81 commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
I don't see what has been refactored.

Is there a way then to pick smaller pieces ? I'm a bit worried that for example the token generation + token expiration code is duplicated. If one would decide to change the token format there is a risk of mismatch.

2018-08-28 15:04 UTC, sharidas commented on core/Command/User/ResetPassword.php
> +				$subject = $this->l10n->t('Your password is reset');
Updated the code by modifying LostController, to provide link which can be used by ResetPassword for both send-email and output-link options.

2018-08-28 15:07 UTC, PVince81 approved these changes
Looks better, thanks :+1:

2018-08-29 05:56 UTC, merged

2018-08-29 06:18 UTC, sharidas commented
Backport stable10 : https://github.com/owncloud/core/pull/32500