Use FileUtils instead of function in Scanner
owncloud/core pull request #32375
Opened 2018-08-19 10:44 UTC by mrow4a

As in the topic - addressing technical dept

2018-08-19 10:46 UTC, mrow4a commented on lib/public/Files/Cache/IScanner.php
>  	public static function isPartialFile($file);
I dont even think if anybody is using this interface.. why would it? It was circumvented anyways in View and used cache directly

2018-08-19 10:46 UTC, mrow4a commented on lib/public/Files/Cache/IScanner.php
>  	public static function isPartialFile($file);
Can we delete it?

2018-08-20 09:13 UTC, DeepDiver1975 requested changes

2018-08-20 09:13 UTC, DeepDiver1975 commented on lib/public/Files/Cache/IScanner.php
> +	 * @deprecated use FileUtils
FileUtils is OC namespace - it cannot be used to deprecate an OCP method.

keep it here

2018-08-20 09:13 UTC, DeepDiver1975 commented on tests/lib/Files/Utils/FileUtilsTest.php
> + * Copyright (c) 2012 Robin Appelman <icewind@owncloud.com>
wrong copytight - please adjust

2018-08-20 09:13 UTC, DeepDiver1975 commented on tests/lib/Files/Utils/FileUtilsTest.php
> +class FileUtilsSTest extends \Test\TestCase {
-S

2018-08-20 09:13 UTC, DeepDiver1975 commented on tests/lib/Files/Utils/FileUtilsTest.php
> +class FileUtilsSTest extends \Test\TestCase {
import TestCase

2018-08-20 15:08 UTC, DeepDiver1975 commented on lib/public/Files/Cache/IScanner.php
> +	 * @deprecated use FileUtils
you can deprecate it and we can remove the api call in some month/years

2018-08-21 07:40 UTC, mrow4a commented
@DeepDiver1975 all tests passing, review addressed

2018-08-23 12:39 UTC, DeepDiver1975 commented
conflicting ... please resolve

2018-09-18 10:18 UTC, mrow4a commented
@DeepDiver1975 rebased

2018-09-27 12:46 UTC, PVince81 commented on lib/private/Files/Utils/FileUtils.php
> +		if (\strpos($path, '.part/') !== false) {
in some cases you replaced this part was missing, I wonder if this will break some undiscovered cases with "part folders"

let's keep this PR master only just in case

2018-09-27 12:47 UTC, PVince81 approved these changes
:+1:

2018-09-27 12:47 UTC, merged

2019-03-29 06:00 UTC, phil-davis commented
Is https://github.com/owncloud/core/pull/32375#issuecomment-425077409 still correct?
A breaking change, or is backport possible?
@PVince81 @DeepDiver1975

2019-04-01 12:59 UTC, PVince81 commented
let's play it safe => no backport.