use official docker container for federaated servers
owncloud/core pull request #32413
Opened 2018-08-22 10:50 UTC by patrickjahns

## Description
Use official docker container in federated tests

## Related Issue

## Motivation and Context
Fix CI

## How Has This Been Tested?
🤖 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

2018-08-22 10:55 UTC, individual-it requested changes

2018-08-22 10:55 UTC, individual-it commented on .drone.yml
> +      - TEST_SERVER_FED_URL=http://federated"
that will make `run.sh` to try to set various settings on the fed. server, in test cases where it was not started it fails.
that was the reason to use `echo "export TEST_SERVER_FED_URL=http://federated" > /drone/saved-settings.sh`

2018-08-22 10:55 UTC, individual-it commented on .drone.yml
> +#  install-fed-server:
why not deleting those lines?

2018-08-22 15:43 UTC, patrickjahns commented on .drone.yml
> +#  install-fed-server:
Was quickly prototyping - will be deleted when review-ready

2018-08-22 15:45 UTC, patrickjahns commented
Issue I am facing now is, that the testing repository would either needed to be moved in a subdirectory to pull the latest changes - or we misuse a github release tag ( 'latest' ) - and re-release the app always on that tag

2018-08-28 10:27 UTC, patrickjahns commented
@ownclouders rebase

2018-08-28 10:27 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-08-28 10:28 UTC, ownclouders commented
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

error: Failed to merge in the changes.


```

2018-08-30 12:09 UTC, patrickjahns commented
Parts of this PR are superseded by #32505 - but once the Guzzle part is finished, we can move with docker containers as federated servers

2018-08-31 09:10 UTC, patrickjahns commented
Rebased to fetch latest changes from core/master - afaik we do not require the guzzle part with ssl certificate anylonger

2019-02-08 15:20 UTC, PVince81 commented
@phil-davis please evaluate if we should continue this and reschedule

2019-02-14 11:24 UTC, patrickjahns commented
Went over the current ideas and have the following remarks:
- DIND is not necessary to start the owncloud container when we don't need to add/edit/mount files directly in the container

```
federated:
    image: owncloud/server:latest
    pull: true
    detach: true
    environment:
      - OWNCLOUD_APPS_INSTALL=https://github.com/owncloud/testing/releases/download/latest/testing.tar.gz
      - OWNCLOUD_APPS_ENABLE=testing
    when:
      matrix:
        TEST_FEDERATION: true
```

Now here is the caveat - what type of onwcloud remote instance do we want to test with federation?  Following topics need some more thought:
- should the federated server have redis ( file locking ) or not?
- should we have more than one database system on the federated system ? 


Regarding the issue with ssl:
When you continue to use dind - you could mount a custom apache config and also ssl certificates inside the docker containers and start it with ssl

2019-02-14 11:31 UTC, individual-it commented
blocked by https://github.com/owncloud/core/issues/34483

2019-02-15 08:59 UTC, individual-it commented
seems pretty complicated to me, closing this in favour of the discussion here https://github.com/owncloud/core/issues/34500
We can reopen this PR or reuse the code if needed

2019-02-15 08:59 UTC, closed without merging