UI test for public share with password
owncloud/core pull request #32726
Opened 2018-09-17 10:56 UTC by paurakhsharma

## Description
UI test for public share with password

## How Has This Been Tested?
Locally

## Types of changes
- [x] Tests

## Checklist:
- [x] Acceptance tests added

2018-09-17 11:06 UTC, phil-davis reviewed
see minor comments

2018-09-17 11:06 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$waringMessage = $this->publicLinkFilesPage->getWarningMessage();
s/waringMessage/warningMessage

2018-09-17 11:06 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then the public should not get access to public share file
Then the public should not get access to the publicly shared file

2018-09-17 12:06 UTC, individual-it requested changes

2018-09-17 12:06 UTC, individual-it commented on tests/acceptance/features/lib/PublicLinkFilesPage.php
> +		$passwordInputField = $this->findById($this->passwordFieldId);
please check here if the return of `findById()` is `null`

2018-09-17 12:06 UTC, individual-it commented on tests/acceptance/features/lib/PublicLinkFilesPage.php
> +	public function waitForAjaxCallsToStartAndFinish(
why to reimplement this function?

2018-09-18 04:00 UTC, paurakhsharma commented on tests/acceptance/features/lib/PublicLinkFilesPage.php
> +		$passwordInputField = $this->findById($this->passwordFieldId);
yes, I should do that.

2018-09-18 04:04 UTC, paurakhsharma commented on tests/acceptance/features/lib/PublicLinkFilesPage.php
> +	public function waitForAjaxCallsToStartAndFinish(
My bad, I should access it through `featureContext`.

2018-09-18 05:46 UTC, individual-it approved these changes

2018-09-18 05:50 UTC, phil-davis approved these changes

2018-09-18 05:53 UTC, paurakhsharma commented
Backport on #32741

2018-09-18 08:48 UTC, merged