Test for creating tags for files
owncloud/core pull request #32884
Opened 2018-09-27 06:31 UTC by skshetry

## Description

Backport for #32883

2018-09-27 11:41 UTC, phil-davis commented on tests/acceptance/features/webUITags/createTags.feature
> +    And the user has logged in with username "user1" and password "qwerty" using the webUI
I expect that this login will fail.
The password neeeds to be ``%regular%``

2018-09-27 14:35 UTC, phil-davis requested changes
See comments in master PR. It needs ``.drone.yml`` entries.

2018-09-29 01:31 UTC, phil-davis approved these changes

2018-09-29 01:32 UTC, phil-davis commented
@skshetry there was no drone result reported. Anyway, because of the code style check rules added to core yesterday, it will be good for you to to rebase and run CI again.

2018-09-29 01:45 UTC, phil-davis commented
@ownclouders rebase

2018-09-29 01:45 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-09-29 01:46 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-10-01 04:38 UTC, phil-davis approved these changes

2018-10-02 05:02 UTC, phil-davis commented
@ownclouders rebase

2018-10-02 05:02 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-10-02 05:03 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-10-02 06:50 UTC, phil-davis commented
@skshetry one of the tags tests failed???

2018-10-02 09:48 UTC, phil-davis commented
@ownclouders rebase

2018-10-02 09:48 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-10-02 09:50 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-10-02 10:40 UTC, merged