Test for creating tags for files
owncloud/core pull request #32883
Opened 2018-09-27 05:57 UTC by skshetry

## Description

## Related Issue

- Related to #32843 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-09-27 06:13 UTC, phil-davis reviewed
It should work. Just put the spaces around the ``=``

2018-09-27 06:13 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		$tabName=null, $fileName, $folderName
we usually put spaces like:
```
$tabName = null
```
also it is not really useful to have an optional parameter in the middle of the list.

Let's see what happens when the full test suite runs, maybe Behat knows how to call this method in the different ways.

2018-09-27 06:27 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		$tabName=null, $fileName, $folderName
@phil-davis I fixed that. Please review again

2018-09-27 06:31 UTC, skshetry commented
Backport for `stable10` on #32884

2018-09-27 08:42 UTC, phil-davis reviewed
We need to use the password substitutions nowadays, so that different passwords can be automatically passed in if needed.

2018-09-27 08:42 UTC, phil-davis commented on tests/acceptance/features/webUITags/createTags.feature
> +      | user1    | qwerty   | User One    | u1@oc.com.np |
Use the regular user password by putting:
```
%regular%
```
in the password column, and in the step 2 lines below.

2018-09-27 11:33 UTC, phil-davis approved these changes

2018-09-27 11:41 UTC, phil-davis commented on tests/acceptance/features/webUITags/createTags.feature
> +    And the user has logged in with username "user1" and password "qwerty" using the webUI
I expect that this login will fail.
The password neeeds to be ``%regular%``

2018-09-27 14:33 UTC, phil-davis requested changes
This needs matrix entries added in ``.drone.yml``
Currently drone is not actually running the tests in the new suite. That is why the test run is passing.

Also, please rebase to current master. master was updated to have extra PHP code style checks, so we want to be sure that those pass.

2018-09-28 04:09 UTC, skshetry commented
@phil-davis  I fixed that password and added config in `drone.yml`. I ran the new acceptance-test-style too

2018-09-28 04:13 UTC, phil-davis approved these changes

2018-09-29 01:53 UTC, phil-davis commented
@ownclouders rebase

2018-09-29 01:53 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-09-29 01:56 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-09-29 02:48 UTC, skshetry commented
I should also to wait for the dropdown to appear. Locally, it is very fast and doesn't need to wait. But, it seems that it's slower on the ci.

2018-09-29 03:12 UTC, phil-davis commented
OK, I will not merge this today. We can look again on Monday.

2018-10-01 04:17 UTC, skshetry commented
@phil-davis now it will wait for the dropdown and should pass.

2018-10-01 04:37 UTC, phil-davis approved these changes

2018-10-01 05:45 UTC, phil-davis commented
@skshetry one of the new tags scenarios failed:
https://drone.owncloud.com/owncloud/core/10990/515

But in stable10 it passed.

???

2018-10-01 05:53 UTC, skshetry commented
@phil-davis I have rebased with master. Maybe it's not this, but I don't know. I am out of options. Let's see if it passes.

2018-10-01 08:02 UTC, phil-davis commented on tests/acceptance/features/webUITags/createTags.feature
> +      | username | password  | displayname | email        |
@skshetry Please adjust this table and rebase. The way users are created changed at the weekend.

2018-10-01 08:29 UTC, skshetry commented on tests/acceptance/features/webUITags/createTags.feature
> +      | username | password  | displayname | email        |
Fixed.

2018-10-01 08:42 UTC, phil-davis approved these changes

2018-10-02 05:01 UTC, merged