Test tags suggestions
owncloud/core pull request #33008
Opened 2018-10-04 05:33 UTC by skshetry

## Description

This adds a test for suggestions in the tags dropdown.

## Related Issue

- Related to #32843 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-10-04 06:11 UTC, phil-davis requested changes
See comments.

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +			PHPUnit_Framework_Assert::assertTrue(true);
Do we really need this line?

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		throw new \Exception("Tag $tagName is on the dropdown.");
s/is on the dropdown/is on the dropdown list but should not be/

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/webUITags/tagsSuggestion.feature
> +Feature: Suggestion of the tags
Suggestions for matching tag names

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/webUITags/tagsSuggestion.feature
> +  I want to get suggestions for adding tags from already exisiting tags
I want to get suggestions for adding tag names from already existing tag names

Note: make sure to fix typo "exisiting"

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/webUITags/tagsSuggestion.feature
> +    But the tag "gham" should not be listed in the dropdown list on the webUI
Also check:
```
And the tag "notspam" should not be listed in the dropdown list on the webUI
```

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/webUITags/tagsSuggestion.feature
> +    And the tag "Violates T&C" should not be listed in the dropdown list on the webUI
Also make a ``not user-assignable``  tag that has the letters ``sp`` in it, and test that it is not listed.

2018-10-04 06:11 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +	 * @Then all the tags starting with :value in their name should be listed in the dropdown list on the webUI
The code here actually does:
```
Then only tags starting with :value in their name should be listed in the dropdown list on the webUI
```
maybe that is OK, so you could change the Gherkin step text.

Otherwise, you need to loop through the array of all created tags and check that each one starting with :value is in the list.

2018-10-04 08:57 UTC, skshetry commented
@phil-davis please review again. I fixed the issues you raised and also made some changes in `Tags.php`.

2018-10-04 09:04 UTC, phil-davis approved these changes

2018-10-05 05:37 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Tags.php
> +		}
Looks good.

2018-10-05 05:39 UTC, phil-davis approved these changes

2018-10-05 06:15 UTC, merged