Center the logo and login fields
owncloud/core pull request #33375
Opened 2018-11-01 01:00 UTC by ChrisEdS

## Description
Force constant vertical height for login box over all devices

## Motivation and Context
I incorporate this function into almost every theme I create. The logo and credential fields are centered on each device. That's why I thought it would be great to integrate this improvement into our Core Theme.

## How Has This Been Tested?
Tested on Chrome and Firefox browser with different resolutions
## Screenshots (if appropriate):

Before:
<img width="1478" alt="screenshot 2018-11-01 at 01 35 48" src="https://user-images.githubusercontent.com/33026403/47826648-56181400-dd79-11e8-88a6-88e666f92f36.png">

After (1440x900px):
<img width="799" alt="screenshot 2018-11-01 at 01 50 32" src="https://user-images.githubusercontent.com/33026403/47826659-629c6c80-dd79-11e8-9220-d1e848a955ff.png">

After (568x320px iPhone 5/5s/SE):
<img width="579" alt="screenshot 2018-11-01 at 01 50 48" src="https://user-images.githubusercontent.com/33026403/47826701-99728280-dd79-11e8-8da4-350ebd5780d9.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-12 08:37 UTC, DeepDiver1975 requested changes
Looks :hankey: on desktop:
- too much space on top
- 2 pixel border on the right

![screenshot from 2018-11-12 09-36-55](https://user-images.githubusercontent.com/1005065/48335596-848dcd00-e65e-11e8-9852-7d3d87e4f074.png)

2018-11-12 10:44 UTC, ChrisEdS commented
Fixed scrollbar and the space to the bottom
___
![screenshot 2018-11-12 at 11 43 08](https://user-images.githubusercontent.com/33026403/48342536-35509800-e670-11e8-904e-999715fb132e.png)

2019-01-07 23:15 UTC, DeepDiver1975 commented
nice

![screenshot from 2019-01-08 00-15-01](https://user-images.githubusercontent.com/1005065/50798961-7e247600-12da-11e9-8fe2-61d0bfaf50b9.png)

2019-01-07 23:16 UTC, DeepDiver1975 approved these changes

2019-01-08 09:05 UTC, merged