Add reset email tests for cli resetUserPassword test
owncloud/core pull request #33385
Opened 2018-11-01 07:55 UTC by paurakhsharma

## Description
Add tests to check if reset email is send to user when administrator invokes `--send-email` via occ command. And also check it a 
Related issue: #32564

## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-01 08:21 UTC, individual-it requested changes

2018-11-01 09:42 UTC, phil-davis approved these changes

2018-11-01 09:42 UTC, phil-davis commented on tests/acceptance/features/cliProvisioning/resetUserPassword.feature
> +    When the administrator invokes password reset for user "brand-new-user" using the occ command
What happens if ``brand-new-user`` does not have an email address set?
We should also test that - hopefully the ``occ`` command gives an error status and error message.

2018-11-01 09:50 UTC, paurakhsharma commented on tests/acceptance/features/cliProvisioning/resetUserPassword.feature
> +    When the administrator invokes password reset for user "brand-new-user" using the occ command
It gives the nice error message saying `Email address is not set for the user`

2018-11-01 09:52 UTC, individual-it submitted a review, later dismissed

2018-11-01 09:52 UTC, individual-it commented on tests/acceptance/features/bootstrap/CommandLine.php
> +		if (!$password) {
this can give you ugly autocasting e.g. `0` `false` ""

2018-11-01 09:56 UTC, phil-davis commented on tests/acceptance/features/cliProvisioning/resetUserPassword.feature
> +    When the administrator invokes password reset for user "brand-new-user" using the occ command
We should have a test scenario for that. It can be in another PR, if you like.

2018-11-01 14:46 UTC, merged

2018-11-02 06:00 UTC, phil-davis commented
Backport ``stable10`` #33391