[WIP] Fix the group selector drop down
owncloud/core pull request #33442
Opened 2018-11-06 14:58 UTC by sharidas

This change gets the group selector drop
down

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Fix the group selector in the core.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/31739

## Motivation and Context

Fix the group selector in the core.

## How Has This Been Tested?

- Login as admin and create users `group1`, `group2`
- Tick the exclude shares check box mentioned in the issue
- Admin user can see `admin`, `group1` and `group2` listed.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-06 15:06 UTC, sharidas commented
Current state of the PR:
- [x] Added `MetaData.php` from `user_management` to core
- [x] Created a new controller for the group selector request.
- [ ] Update the unit tests

2018-11-06 15:34 UTC, DeepDiver1975 requested changes

2018-11-06 15:34 UTC, DeepDiver1975 commented on settings/Controller/GroupsSelectController.php
> +	public function index($pattern = '', $filterGroups = false, $sortGroups = MetaData::SORT_USERCOUNT) {
you need all parameters here?

2018-11-06 15:34 UTC, DeepDiver1975 commented on lib/private/MetaData.php
> +class MetaData {
As explained I don't want to see this class in code

2018-11-07 09:15 UTC, sharidas commented
Current state of the PR:
- Added separate controller for group selector
- This PR has no dependency with user_management. Meaning, user_management remains untouched.
- Added unit test for the change made.

2018-11-12 08:30 UTC, DeepDiver1975 requested changes

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +						'message' => 'No groups available'
this message is wrong

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +	 * @return array|\OCP\IGroup[]
why array? IGroup[] is sufficient

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +class GroupsController extends Controller {
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +	private $groupManager;
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +	public function __construct(string $appName,
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +	 * @NoAdminRequired
Usually we add a no csrf annotation to GET requests ... please have a second look and see if needed ...

2018-11-12 08:30 UTC, DeepDiver1975 commented on settings/Controller/GroupsController.php
> +				$adminGroup['name'] = $group->getGID();
there is a getDisplayName afaik - please adapt

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +class GroupsControllerTest extends TestCase {
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +	private $appName;
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +	private $request;
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +	private $groupManager;
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +	private $userSession;
PHPDoc

2018-11-12 08:30 UTC, DeepDiver1975 commented on tests/Settings/Controller/GroupsControllerTest.php
> +	private $groupsController;
PHPDoc

2018-11-13 11:13 UTC, sharidas commented
@DeepDiver1975 kindly review my change. The updated PR includes:
- [x] Updated the message when the user is null
- [x] Added missing PHP Doc ( for both controller and the test )
- [x] Updated the get request with `NoCSRFRequired` annotation. Grepped through the source code, and figured out that the GET requests are using the same. Hence adapting it.
- [x] Updated the code to use `getDisplayName` for the group name ( earlier getGID was used ).
- [x] Updated the code to return `IGroup[]` ( earlier it was array|IGroup[] )

2018-11-14 16:08 UTC, PVince81 commented
@sharidas mind adding a summary at the top to explain why this PR fixes the issue ?

I see a lot of controller stuff being shuffled around but it's not clear why this helps fixing the issue.

2018-11-14 16:46 UTC, sharidas commented
@PVince81 
> @sharidas mind adding a summary at the top to explain why this PR fixes the issue ?
> 
> I see a lot of controller stuff being shuffled around but it's not clear why this helps fixing the issue.

I have updated the `Description` and `Motivation and Context` section of the PR. A breif summary has been added to know why this change is added.

2018-11-15 10:04 UTC, PVince81 commented
@sharidas is this a brand new controller written from scratch or does it reuse some of the code that was moved to the user_management app ?

2018-11-15 14:16 UTC, sharidas commented
> @sharidas is this a brand new controller written from scratch or does it reuse some of the code that was moved to the user_management app ?

@PVince81 Yes this is a new controller. It is inspired or lets say influenced from user_management's https://github.com/owncloud/user_management/blob/master/lib/Controller/GroupsController.php. Here is the comment, which helped to create this PR https://github.com/owncloud/user_management/pull/96#issuecomment-436304331. Also I have tried to avoid code duplication while writing this controller. Hope this address your query.

2018-11-15 14:38 UTC, PVince81 reviewed
See comment.
Looks ok otherwise.

2018-11-15 14:38 UTC, PVince81 commented on settings/Controller/GroupsController.php
> +				$adminGroup['userCount'] = 1;
I think there can be more than one user in the admin group

2018-11-16 13:34 UTC, sharidas commented
Current state of the PR

- [x] Replaced admin users count from `1` to `$group->count('')`. This was from the request https://github.com/owncloud/core/pull/33442#discussion_r233865426. I have verified with the latest change, the code does grab all the users from admin or non admin groups.

Hence kindly request for review @PVince81

2018-11-16 15:29 UTC, sharidas commented
- [x] Updated the test with more than one user in a group.
  - [x] Though there is a test which I updated in this version, I have tried to add another test. In the new test I have not used mocks. It directly alters the db.

@PVince81 I have updated the new version with the unit tests updated. I missed updating the test, in my previous version :(

2018-11-22 15:45 UTC, PVince81 commented
@sharidas can you click "resolve conversation" on the review items that you solved ?

2018-11-23 06:16 UTC, sharidas commented
> @sharidas can you click "resolve conversation" on the review items that you solved ?

I have clicked "resolve conversation" on the review items, that were solved with respect to the current state of the PR.

2018-11-23 08:06 UTC, DeepDiver1975 approved these changes

2018-11-23 08:06 UTC, merged

2019-03-29 11:53 UTC, phil-davis commented
Note: This PR would need to be backported to `stable10` if we some-day release the `user_management` app as a separate app, along with a core 10.* release.