[WIP] Add background job to clean up orphaned properties
owncloud/core pull request #33464
Opened 2018-11-09 11:34 UTC by sharidas

Add a background job to clean up orphaned properties
in the table.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Clean up orphan properties in the table.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/33413

## Motivation and Context

Clean up orphan properties.

## How Has This Been Tested?

- [ ] Steps need to be provided

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-09 11:53 UTC, sharidas commented
The essence of this PR,
- It tries to iterate through the properties table and fetches the fileid
- It checks if this fileid is there in the filecache table.
- If fileid is found in filecache, it wont delete the property from the table, else the property is deleted.
Let me know if this change looks ok. @PVince81

2018-11-09 15:24 UTC, PVince81 requested changes

2018-11-10 17:05 UTC, micbar commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +		$qb->select('fileid')
Would be interesting for Files Lifcycle too. Fo the moment, we have a SQL Query like this 
https://github.com/owncloud/files_lifecycle/blob/master/lib/ArchiveQuery.php#L44

I have a WIP query for the query builder, which doesn't work.
https://gist.github.com/micbar/95e7a7edd9eda5c391b300da9b96a0f2

It gives me a SQL syntax error. I suspect, that the escaping of the property names is the problem here https://gist.github.com/micbar/95e7a7edd9eda5c391b300da9b96a0f2#file-archivequery-php-L18

2018-11-19 13:58 UTC, sharidas commented
Current state of the PR:
- [x] Updated the query to use a left join. The query will provide the fileid's to be deleted from the oc_properties table. And then delete it.

Kindly review this PR.

2018-11-22 10:41 UTC, PVince81 reviewed
Looks better.
A little perf improvement would be nice, see comment.

2018-11-22 10:41 UTC, PVince81 commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +			$this->deleteOrphan($row['fileid']);
deleting one by one could be slow. might be better to batch them in chunks and have the deletion query use `where fileid in (...)`

2018-11-22 10:41 UTC, PVince81 commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +			$this->deleteOrphan($row['fileid']);
did you try `delete from oc_properties p where p.fileid not in (select fileid from oc_filecache f)` ?
as far as I remember this probably doesn't work on all databases so your current approach is closer to the better compromise

2018-11-23 08:53 UTC, sharidas commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +			$this->deleteOrphan($row['fileid']);
> did you try `delete from oc_properties p where p.fileid not in (select fileid from oc_filecache f)` ?
> as far as I remember this probably doesn't work on all databases so your current approach is closer to the better compromise

No I have not done this way.

2018-11-23 09:00 UTC, sharidas commented
Current state of the PR:
- [ ] delete operation is not done one by one. Its done as per the suggestion `where fileid in (...)`. I also preferred to delete in a batch of 200 fileids.
- [ ] Updated the tests for large deletion ( 300 entries deleted from 310 entries ).

2018-11-23 10:03 UTC, sharidas commented
Oops postgresql failed. 
- [ ] Verify the change works with postgresql.

2018-11-23 13:32 UTC, sharidas commented
@PVince81 another round of review is required. 

- I have updated the unit test for the postgresql failure.
- Also points mentioned at https://github.com/owncloud/core/pull/33464#issuecomment-441184672 remains valid for the review.

2018-11-23 14:28 UTC, PVince81 reviewed
See comment. The chunking solution should also cover the detection query.

2018-11-26 07:06 UTC, sharidas commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +			$this->logger->info("Deleting property for fileids: " . \implode(',', $strFileIds), ['app' => 'dav']);
Updated the code to use `debug` and the changeset now shows the total number of entries deleted.

> do we use `info` in other background jobs ? as far as I remember we only summarize by saying how many entries we processed, not more

Nope. I thought since its an information to the admin, hence added info. Looked into some of the background jobs they do have debug. And they just summarize saying how many entries were deleted.

2018-11-26 07:08 UTC, sharidas commented
The current state of the PR:

- [x] Updated the change set to use `debug`, instead of `info` to log. Also the log will have only the total number of deleted entries.
- [x] Updated the select query to provide 200 entries each time. And these entries will be passed on to the delete query, until nothing is left.

2018-11-26 07:09 UTC, sharidas commented on apps/dav/lib/BackgroundJob/CleanProperties.php
> +			$fileIds[] = (int) $row['fileid'];
I have updated the query in the latest version of the PR.

2018-11-28 09:44 UTC, PVince81 approved these changes
:+1:

2018-11-28 09:45 UTC, merged

2018-11-28 09:45 UTC, PVince81 commented
@sharidas please backport

2018-11-28 10:53 UTC, sharidas commented
Backport to stable10 https://github.com/owncloud/core/pull/33677