Update to PHPUnit 6
owncloud/core pull request #33474
Opened 2018-11-11 22:12 UTC by carusogabriel

## Description

As we minimum require PHP 7.1, we can require this PHPUnit version. The PHPUnit 7 version requires more work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2018-11-12 07:34 UTC, DeepDiver1975 requested changes
This will break all apps ...

- Apps use core's phpunit to run their tests
- Apps are usually written to work on ooc10+
- This requires php5.6

As long as oc10 is maintained we cannot merged this

But: feel free to migrate the code to work with phpunit 6 - older phpunit versions have a compatibility layer in place. THX

2018-11-12 10:23 UTC, carusogabriel commented
@DeepDiver1975 Gotcha. Following @phil-davis's suggestion as well, I've update this patch.

2018-11-12 10:26 UTC, DeepDiver1975 requested changes
AFAIK there are cs-fixer rules for PHPUnit as well ... please have a look ... THX

2018-11-12 10:35 UTC, phil-davis commented on apps/files/tests/Controller/ViewControllerTest.php
> +			$this->expectException('OCP\Files\NotFoundException');
@carusogabriel "I will later create"  or "I would hate to create" or?
The auto-spell-checker in my brain is confused :)

2018-11-12 10:38 UTC, carusogabriel commented on apps/files/tests/Controller/ViewControllerTest.php
> +			$this->expectException('OCP\Files\NotFoundException');
@phil-davis Sorry, misspelling :man_facepalming:, edited

2018-11-12 10:50 UTC, phil-davis reviewed
Some files do not yet have the ``use`` statement added.

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/CapabilitiesContext.php
> +			PHPUnit\Framework\Assert::assertEquals(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/CommandLine.php
> +		PHPUnit\Framework\Assert::assertGreaterThanOrEqual(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Comments.php
> +				PHPUnit\Framework\Assert::assertTrue(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/EmailContext.php
> +		PHPUnit\Framework\Assert::assertContains(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Logging.php
> +				PHPUnit\Framework\Assert::assertArrayHasKey(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/SearchContext.php
> +		PHPUnit\Framework\Assert::assertNotFalse(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/ShareesContext.php
> +		PHPUnit\Framework\Assert::assertEquals($sharees, $respondedArray);
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIAdminGeneralSettingsContext.php
> +		PHPUnit\Framework\Assert::assertEquals(\trim($expectedVersion), $actualVersion);
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUILoginContext.php
> +		PHPUnit\Framework\Assert::assertEquals(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUINotificationsContext.php
> +		PHPUnit\Framework\Assert::assertEquals(
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +		PHPUnit\Framework\Assert::assertTrue($this->personalGeneralSettingsPage->isVersionDisplayed());
no ``use`` added for this file?

2018-11-12 10:50 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalSecuritySettingsContext.php
> +		PHPUnit\Framework\Assert::assertNotEmpty($appTr);
no ``use`` added for this file?

2018-12-23 15:35 UTC, carusogabriel commented
Closing as I'm gonna work on updating the version of PHPUnit instead

2018-12-23 15:35 UTC, closed without merging