Adding more federation acceptance tests
owncloud/core pull request #33506
Opened 2018-11-13 17:23 UTC by VicDeo

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-12-04 11:37 UTC, VicDeo commented
Only CI gods know what is happening here...

```
> make test-acceptance-webui BEHAT_FEATURE=tests/acceptance/features/webUISharingExternal/federationSharing.feature:187
php build/composer.phar install --dev
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating optimized autoload files
Composer cleaner: Removed 17 files or directories.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
./tests/acceptance/run.sh --remote --type webUI
Script path: /home/deo/public_html/autotest/tests/acceptance
Not using php inbuilt server for running scenario ...
Updating .htaccess for proper rewrites
"maxDuration":"3600"
{"extensions" : {"Behat\\MinkExtension" : {"browser_name": "chrome", "base_url" : "http://172.17.0.1/~deo/autotest", "selenium2":{"capabilities": {"marionette":null, "browser": "chrome", "name": "ownCloud non-CI", "extra_capabilities": {"maxDuration":"3600"}}, "wd_host":"http://localhost:4445/wd/hub"}}, "SensioLabs\\Behat\\PageObjectExtension" : {}}}
Running webUISharingExternal tests tagged ~@skipWhenTestingRemoteSystems&&~@skipOnOcV11&&~@skipOnOcV11.0&&~@skipOnOcV11.0.0&&@webUI&&~@skip on browser 'chrome' 
@webUI @insulated @disablePreviews @TestAlsoOnExternalUserBackend
Feature: Federation Sharing - sharing with users on other cloud storages
  As a user
  I want to share files with any users on other cloud storages
  So that other users have access to these files

  Background:                                                 # /home/deo/public_html/autotest/tests/acceptance/features/webUISharingExternal/federationSharing.feature:7                                                                                                     
    Given using server "REMOTE"                               # FeatureContext::usingServer()
    And user "user1" has been created with default attributes # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And using server "LOCAL"                                  # FeatureContext::usingServer()
    And user "user1" has been created with default attributes # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "user1" has logged in using the webUI            # WebUILoginContext::theUserLogsInUsingTheWebUI()

  Scenario: test sharing folder to a remote server and resharing it back to the local                                   # /home/deo/public_html/autotest/tests/acceptance/features/webUISharingExternal/federationSharing.feature:187
    Given using server "LOCAL"                                                                                          # FeatureContext::usingServer()
    And these users have been created:                                                                                  # FeatureContext::theseUsersHaveBeenCreated()
      | username |
      | user2    |
    When the user shares folder "simple-folder" with remote user "user1@%remote_server_without_scheme%" using the webUI # WebUISharingContext::theUserSharesFileFolderWithUserUsingTheWebUI()
    And using server "REMOTE"                                                                                           # FeatureContext::usingServer()
    And user "user1" re-logs in to "%remote_server%" using the webUI                                                    # WebUILoginContext::theUserRelogsInToUsingTheWebUI()
    And the user accepts the offered remote shares using the webUI                                                      # WebUISharingContext::theUserAcceptsTheOfferedRemoteShares()
    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"         # FederationContext::userFromServerHasSharedWithUserFromServer()
    And using server "LOCAL"                                                                                            # FeatureContext::usingServer()
    And user "user2" re-logs in to "%local_server%" using the webUI                                                     # WebUILoginContext::theUserRelogsInToUsingTheWebUI()
INFORMATION: timed out waiting for outstanding ajax calls
    And the user accepts the offered remote shares using the webUI                                                      # WebUISharingContext::theUserAcceptsTheOfferedRemoteShares()
      │ INFORMATION: timed out waiting for outstanding ajax calls
    Then as "user2" folder "/simple-folder (2)" should exist                                                            # FeatureContext::asFileOrFolderShouldExist()
    And as "user2" file "/simple-folder (2)/lorem.txt" should exist                                                     # FeatureContext::asFileOrFolderShouldExist()
SCENARIO RESULT: (pass)

1 scenario (1 passed)
17 steps (17 passed)
1m42.68s (25.87Mb)
runsh: Exit code of main run: 0
```

```
> make test-acceptance-webui BEHAT_FEATURE=tests/acceptance/features/webUISharingExternal/federationSharing.feature:203
php build/composer.phar install --dev
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating optimized autoload files
Composer cleaner: Removed 17 files or directories.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
./tests/acceptance/run.sh --remote --type webUI
Script path: /home/deo/public_html/autotest/tests/acceptance
Not using php inbuilt server for running scenario ...
Updating .htaccess for proper rewrites
"maxDuration":"3600"
{"extensions" : {"Behat\\MinkExtension" : {"browser_name": "chrome", "base_url" : "http://172.17.0.1/~deo/autotest", "selenium2":{"capabilities": {"marionette":null, "browser": "chrome", "name": "ownCloud non-CI", "extra_capabilities": {"maxDuration":"3600"}}, "wd_host":"http://localhost:4445/wd/hub"}}, "SensioLabs\\Behat\\PageObjectExtension" : {}}}
Running webUISharingExternal tests tagged ~@skipWhenTestingRemoteSystems&&~@skipOnOcV11&&~@skipOnOcV11.0&&~@skipOnOcV11.0.0&&@webUI&&~@skip on browser 'chrome' 
@webUI @insulated @disablePreviews @TestAlsoOnExternalUserBackend
Feature: Federation Sharing - sharing with users on other cloud storages
  As a user
  I want to share files with any users on other cloud storages
  So that other users have access to these files

  Background:                                                 # /home/deo/public_html/autotest/tests/acceptance/features/webUISharingExternal/federationSharing.feature:7                                                                                                     
    Given using server "REMOTE"                               # FeatureContext::usingServer()
    And user "user1" has been created with default attributes # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And using server "LOCAL"                                  # FeatureContext::usingServer()
    And user "user1" has been created with default attributes # FeatureContext::userHas [...]

2018-12-21 12:57 UTC, VicDeo commented
To reproduce  failure:
setup ownCloud to strip index.php from the URLs:
- add  'htaccess.RewriteBase'` into the config.php
- run `occ maintenance:update:htaccess`

2019-01-15 08:15 UTC, individual-it requested changes
looks good, just minor change requests

I wrote some general explanations about how we usually write the tests

Also, if you don't care particularly to test the UI but the sharing in general, its might be better to write pure API tests, they are much faster

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
you should be able to go without this statement
its not needed for the `using the webUI` steps, because you specify the server the user logs in to
and its also not needed for the step `    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"` because you specify the remote/local servers directly there

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
not needed, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
not needed, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
not needed, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
that is a given step, but here used as a when step
better to use here
```suggestion
    And user "user1" from server "REMOTE" shares "/simple-folder (2)" with user "user2" from server "LOCAL using the sharing API"
```
`@Given` steps are for setup only, so we don't care how the action is done (API, UI, occ,...)
with `@When` steps we want to test the acting they perform, so we want to mention how they do the action (API, UI, occ,...)
Also `@Given` steps should test if they succeed, because the set-up should always succeed
`@When` steps do not check the outcome them-self but leave the work for the following `@Then` step. A `@When` step might fail and its OK, maybe a sharing should **not** work

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
use When step, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
not needed, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
not needed, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
use When step, see comment above

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And the user opens folder "simple-folder (2)" using the webUI
```suggestion
    When the user opens folder "simple-folder (2)" using the webUI
```

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And it should not be possible to delete file "lorem.txt" using the webUI
```suggestion
    Then it should not be possible to delete file "lorem.txt" using the webUI
```

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And the user opens folder "simple-folder (2)" using the webUI
```suggestion
    When the user opens folder "simple-folder (2)" using the webUI
```

2019-01-15 08:15 UTC, individual-it commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And it should not be possible to delete file "lorem.txt" using the webUI
```suggestion
    Then it should not be possible to delete file "lorem.txt" using the webUI
```

2019-01-15 12:46 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
removed

2019-01-15 12:47 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
removed

2019-01-15 12:47 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
removed

2019-01-15 12:47 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
removed

2019-01-15 12:47 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "REMOTE"
removed

2019-01-15 12:47 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And using server "LOCAL"
removed

2019-01-15 12:52 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
thanks for the explanation. updated.

2019-01-15 12:52 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
updated

2019-01-15 12:53 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And user "user1" from server "REMOTE" has shared "/simple-folder (2)" with user "user2" from server "LOCAL"
updated

2019-01-15 15:30 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And the user opens folder "simple-folder (2)" using the webUI
changed

2019-01-15 15:30 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And it should not be possible to delete file "lorem.txt" using the webUI
changed

2019-01-15 15:30 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And the user opens folder "simple-folder (2)" using the webUI
changed

2019-01-15 15:30 UTC, VicDeo commented on tests/acceptance/features/webUISharingExternal/federationSharing.feature
> +    And it should not be possible to delete file "lorem.txt" using the webUI
changed

2019-01-16 05:00 UTC, individual-it approved these changes

2019-01-16 05:31 UTC, phil-davis approved these changes
Looks good.
There are lots of other combinations that could also be tested some day, but this is a good start.

2019-01-17 15:38 UTC, merged

2019-01-17 15:43 UTC, VicDeo commented
Stable10: https://github.com/owncloud/core/pull/34172