Add more api tests for webdav search api
owncloud/core pull request #33512
Opened 2018-11-14 06:53 UTC by paurakhsharma

## Description
Add more tests for WebDAV search API.

Related issue: #32602
## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-14 08:48 UTC, individual-it requested changes
search also for UTF characters in search string

2018-11-14 08:48 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/search.feature
> +        And user "user0" has uploaded file with content "does-not-matter" to "/just-a-folder/lolol.txt"
indent

2018-11-14 08:48 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @Then /^the (?:propfind|search) result of "([^"]*)" should (not|)\s?contain these entries:$/
make it more universal, so old steps don't break
```suggestion
	 * @Then /^the (?:propfind|search) result of "([^"]*)" should (not|)\s?contain these (?:files|entries):$/
```

2018-11-14 08:48 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @Then the propfind/search result of :user should contain :numFiles entries
make more universal

2018-11-14 08:48 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/search.feature
> +      | /फनी näme/upload.txt          |
this are 4 entries
maye add also a "should not contain" section

2018-11-16 04:50 UTC, individual-it approved these changes

2018-11-16 05:02 UTC, merged

2018-11-16 05:06 UTC, paurakhsharma commented
Backport on: #33547