cli Test trashbin
owncloud/core pull request #33534
Opened 2018-11-15 10:14 UTC by paurakhsharma

## Description
Add cli tests for trashbin
Related issue: #33051

## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-15 10:24 UTC, individual-it requested changes

2018-11-15 10:32 UTC, paurakhsharma commented
@individual-it, I have addressed all the comments. Please review

2018-11-15 10:46 UTC, paurakhsharma commented
@phil-davis, As you can see in the test when we run occ command `trashbin:cleanup` all users trashbin are cleaned. Isn't this risky? because the administrator can type this by accident. There should be some verification or `--all` should be added. What do you think? Or do we think administrator are not supposed to make mistakes?

2018-11-16 03:17 UTC, individual-it approved these changes

2018-11-16 03:59 UTC, phil-davis requested changes

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +	 * @When the administrator empties the trasbin of user :user using the occ command
s/trasbin/trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +	public function theAdministratorEmptiesTheTrasbinOfUserUsingTheOccCommand($user) {
s/trasbin/trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +	 * @When the administrator empties the trasbin of all users using the occ command
s/trasbin/trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +	public function theAdministratorEmptiesTheTrasbinOfAllUsersUsingTheOccCommand() {
s/trasbin/trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +		$this->theAdministratorEmptiesTheTrasbinOfUserUsingTheOccCommand('');
s/trasbin/trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/cliTrashbin/trashbin.feature
> +  Scenario: delete files and folder of a user from a trashbin
s/a trashbin/the trashbin

2018-11-16 03:59 UTC, phil-davis commented on tests/acceptance/features/cliTrashbin/trashbin.feature
> +  Scenario: delete files and folder of all user from a trashbin
s/a trashbin/the trashbin

2018-11-16 05:58 UTC, phil-davis approved these changes

2018-11-16 05:59 UTC, merged

2018-11-16 06:05 UTC, paurakhsharma commented
Backport on: #33548