Rename user creation given step to be default
owncloud/core pull request #33551
Opened 2018-11-16 08:24 UTC by skshetry

## Description

## Related Issue
- Fixes #33396 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-16 08:37 UTC, phil-davis commented on tests/acceptance/features/apiCapabilities/capabilities.feature
> +    And group "grp1"has been created with default attributes
@skshetry a lot of lines have a space missing between ``group "grp1"`` and ``has been created``
;)

2018-11-16 08:38 UTC, phil-davis commented on tests/acceptance/features/apiComments/comments.feature
> +    And user "user0"has been created with default attributes
Same space missing problem with this user step

2018-11-16 08:40 UTC, skshetry commented on tests/acceptance/features/apiComments/comments.feature
> +    And user "user0"has been created with default attributes
umm, it's problem with replacing the text. just pushed to see failures in drone. :)

2018-11-16 09:37 UTC, phil-davis commented on lib/private/Files/Stream/Checksum.php
> +	 * Make checksums available for part files and the original file for which part file has been created with default attributes
random editor replace

2018-11-16 16:52 UTC, skshetry commented
@ownclouders rebase

2018-11-16 16:52 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-11-16 16:55 UTC, ownclouders commented
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

error: Failed to merge in the changes.


```

2018-11-20 10:31 UTC, individual-it requested changes

2018-11-20 10:31 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			if ($displayName === null and $setDefault == true) {
use `&&` here like in other places

2018-11-20 10:31 UTC, individual-it commented on tests/acceptance/features/cliProvisioning/resetUserPassword.feature
> +    Given these users have been created with default attributes:
this will setup an email address

2018-11-20 10:40 UTC, individual-it submitted a review, later dismissed
LGTM, hoping CI passes

2018-11-20 10:59 UTC, phil-davis commented on tests/acceptance/features/apiSharees/sharees.feature
>      And user "Another" has been added to group "ShareeGroup2"
I have a feeling this will be case-sensitive?
The user is in ``another``
We will see if CI passes.

2018-11-20 11:04 UTC, phil-davis submitted a review, later dismissed

2018-11-20 11:11 UTC, skshetry commented
Backport for `stable10` in #33591

2018-11-20 11:19 UTC, skshetry commented
@phil-davis @individual-it I have missed few files. I have added a few. But, the github cannot show the diffs of just that. [Here's the diff of what's changed](https://github.com/owncloud/core/pull/33591/commits/59ec3c6100e16216884533759ec7fda0aaa52ff4). Though, it's on `stable10`.

2018-11-21 08:49 UTC, skshetry commented
@phil-davis @individual-it you might need to re-review this again as i have made few changes.

2018-11-21 14:20 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/getUser.feature
> +    Given these users have been created with default attributes:
Note for future readers of this PR: "with default attributes" means that attributes that do not appear in the table are supplied with default value. For example, in this case, ``brand-new-user`` will get some default password and get an email address "generated" for them by the underlying test code. The display name will be set as specified in the table. This is "a good thing".

2018-11-21 14:23 UTC, phil-davis approved these changes

2018-11-21 14:23 UTC, merged