Add test for deleting versions does not shows in webUI
owncloud/core pull request #33585
Opened 2018-11-20 08:22 UTC by dpakach

## Description

Add webUI acceptance tests for checking if no versions are shown in the webUI after clearing all versions

## Related Issue

- Fixes  #33382

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-20 08:35 UTC, individual-it requested changes
please also add tests to check if the clean-up of a single user works

2018-11-20 08:35 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +		);
check at least the result of the command

2018-11-20 10:50 UTC, skshetry approved these changes

2018-11-20 11:20 UTC, individual-it approved these changes

2018-11-21 09:02 UTC, individual-it commented
CI failed because of connection issue with github
![image](https://user-images.githubusercontent.com/2425577/48830304-60d43080-ed9c-11e8-9ae3-cf7c597c9e0a.png)

2018-11-21 09:07 UTC, merged