Touch last login time when using auth modules
owncloud/core pull request #33593
Opened 2018-11-20 11:54 UTC by tomneedham

## Description
Auth modules do not update the lastLoginTime in oc_accounts. 

## Related Issue
-

## Motivation and Context
Last Login is used to detect 'seen' users, without this some users can never get a last_login time and will not be included in other processes. 

## How Has This Been Tested?
Tried with oAuth since this uses an auth module, however the time was not updated, past the initial connection - but I expected it to be. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-11-20 12:27 UTC, butonic approved these changes

2018-11-20 12:33 UTC, butonic requested changes
maybe it makes more sense to move this to `Session::loginUser()` because that method actually logs in the user and fires events?

2018-11-21 10:24 UTC, butonic approved these changes

2018-11-21 12:09 UTC, tomneedham commented
No changes to coverage - no idea what codedov is saying

2018-12-04 10:51 UTC, PVince81 commented
@ownclouders rebase

2018-12-04 10:51 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-12-04 10:53 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-12-04 10:54 UTC, PVince81 commented
I'll massage Drone when needed. @tomneedham please backport

2018-12-04 12:02 UTC, merged

2018-12-04 12:03 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/33752