deleting a file when 2 files exist with different case
owncloud/core pull request #33597
Opened 2018-11-20 15:50 UTC by davitol

## Related Issue
https://github.com/owncloud/core/issues/32357 part

## Motivation and Context
Spread Tests

## How Has This Been Tested?
Local test runs

2018-11-21 09:45 UTC, individual-it requested changes

2018-11-21 09:45 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +    When user "user0" uploads file with content "uploaded content" to "/textfile1.txt" using the WebDAV API
I suggest to use Given here
Given user "user0" has uploaded ....
as this is a setup step for the tests

2018-11-21 09:45 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +    When user "user0" deletes file "/textfile0.txt" using the WebDAV API
do you meant to delete `textfile1.txt`? as we want to test the different cases

2018-11-21 09:45 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +    And as "user0" file "/textfile0.txt" should not exist
see comment above

2018-11-22 10:47 UTC, individual-it submitted a review, later dismissed

2018-11-22 10:47 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +    And as "user0" file "/textfile1.txt" should not exist
where does the delete happen?

2018-11-22 10:47 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +    And as "user0" file "/textfile1.txt" should not exist
I'm actually worried about the fact that CI passes

2018-11-22 13:46 UTC, phil-davis requested changes
This scenario fails for me locally. I don't know how it passed CI on drone - maybe related to the recent drone problems???

I suggest that each file should have different content. Then delete one of the files. Check that the deleted file does not exist, check that the remaining file has the expected content. That will confirm that both the correct file name and the correct file content were deleted.

2018-11-22 14:20 UTC, phil-davis approved these changes

2018-11-22 14:47 UTC, merged

2018-11-22 14:49 UTC, phil-davis commented
@davitol when making the backport, please make sure that you have pulled the very latest ``stable10`` of core, and branch from that. Maybe the problems we have been having are related to PRs branched from old master or stable10 - I don't know.

2018-11-23 09:20 UTC, davitol commented
Backport in : https://github.com/owncloud/core/pull/33633