Refactor sends HTTP method to use specific methods
owncloud/core pull request #33676
Opened 2018-11-28 06:39 UTC by paurakhsharma

## Description
Refactor behat setps like `user sends HTTP method 'PUT' to endpoint '/cloud/xyz'` to more specific methods, hiding endpoints from behat steps definitions.

Related issue: #33364
## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-28 07:35 UTC, phil-davis commented
Now the commit message says: ``[tx-robot] updated from transifex``
Some problem when doing a rebase?
Next time you need to change something, fix the commit message also.

2018-11-28 08:04 UTC, phil-davis reviewed
Stuff I found so far to the end of apiProvisioning-v1 suite.

2018-11-28 08:04 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
> +    When the administrator removes user "brand-new-user" from subadmin of group "new-group" using the provisioning API
How to write this?
Maybe
```
When the administrator removes user "brand-new-user" from being a subadmin of group "new-group" using the provisioning API
```

2018-11-28 08:04 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
> +    When the user "newuser" removes user "subamin" from subadmin of group "new-group" using the provisioning API
s/subamin/subadmin/

2018-11-28 08:27 UTC, individual-it requested changes

2018-11-28 08:36 UTC, phil-davis reviewed
review comments for apiProvisioning-v2 suite

2018-11-28 08:36 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v2/addGroup.feature
> +    When user "user0" tries to send a group creation request for group "new-group" using the provisioning API
user "brand-new-user"

2018-11-28 08:36 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v2/addToGroup.feature
> +    When user "subadmin" tries to add himself to group "new-group" using the provisioning API
tries to add user "brand-new-user"

2018-11-28 08:36 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v2/addToGroup.feature
> +    When user "other-subadmin" tries to add himself to group "new-group" using the provisioning API
tries to add user "brand-new-user"

2018-11-28 08:36 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v2/removeSubAdmin.feature
> +    When the user "newuser" removes user "subamin" from subadmin of group "new-group" using the provisioning API
s/subamin/subadmin

2018-11-28 08:37 UTC, paurakhsharma commented on tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
> +    When the administrator removes user "brand-new-user" from subadmin of group "new-group" using the provisioning API
Yes, this one reads better.

2018-11-28 08:39 UTC, paurakhsharma commented on tests/acceptance/features/apiProvisioning-v1/addGroup.feature
> +    When user "user0" tries to send a group creation request for group "new-group" using the provisioning API
It's a mistake.

2018-11-28 08:46 UTC, phil-davis reviewed
Few more items

2018-11-28 08:46 UTC, phil-davis commented on tests/acceptance/features/apiShareManagement/deleteShare.feature
> +    When user "user0" shares folder "shared" with user "user1" using the sharing API
IMO this step can be deleted

2018-11-28 08:46 UTC, phil-davis commented on tests/acceptance/features/apiShareOperations/accessToShare.feature
> +    When user "user1" gets all shares to him from file "textfile1 (2).txt" using the provisioning API
Maybe:
```
When user "user1" gets all the shares shared with him as path/file...
```

2018-11-28 08:46 UTC, phil-davis commented on tests/acceptance/features/apiShareOperations/gettingShares.feature
> +    When user "user0" gets all shares from him using the sharing API
```
When user "user0" gets all shares shared by him using the sharing API
```

2018-11-28 08:46 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @When user :user sends a user deletion request for user :anotheruser using the provisioning API
Yes, you are right. I might have written it because there was when ...... sends user creation request.

2018-11-28 08:49 UTC, paurakhsharma commented on tests/acceptance/features/apiShareManagement/deleteShare.feature
> +    When user "user0" shares folder "shared" with user "user1" using the sharing API
Yes, it should be deleted. Thank for catching that.

2018-11-28 08:52 UTC, paurakhsharma commented on tests/acceptance/features/apiShareOperations/accessToShare.feature
> +    When user "user1" gets all shares to him from file "textfile1 (2).txt" using the provisioning API
`When user "user1" gets all the shares shared with him as file "xyz.txt"` 
or 
`When user "user1" gets all the shares shared with him from file file "xyz.txt"`

2018-11-28 10:35 UTC, phil-davis reviewed
2 more things

2018-11-28 10:35 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/deleteGroup.feature
> +    When user "subadmin" tries to delete a group "new-group" using the provisioning API
this will also need to say ``tries to delete group``
I expect the current step text is going to fail

2018-11-28 10:35 UTC, phil-davis commented on tests/acceptance/features/apiShareManagement/deleteShare.feature
> +    When user "user0" shares folder "shared" with user "user1" with permissions 1 using the sharing API
There are now 2 ``When`` steps

2018-11-28 10:36 UTC, phil-davis commented on tests/acceptance/features/apiShareOperations/accessToShare.feature
> +    When user "user1" gets all shares to him from file "textfile1 (2).txt" using the provisioning API
The challenge here is that the original file is called ``textfile1.txt`` but when ``user1`` sees it, it is called ``textfile1 (2).txt``

Maybe:
```
When user "user1" gets all the shares shared with him that are received as file/folder "textfile1 (2).txt"
```

If that fits with the way the API works - I guess the receiver of the share queries based on the name that they see the shared file/folder.

2018-11-28 10:38 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/deleteGroup.feature
> +    When user "subadmin" tries to delete a group "new-group" using the provisioning API
Oh - this test was snake-oil - the step has ``user "subamin"``` (typo) previously. Good that is fixed!

2018-11-28 10:39 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v2/removeSubAdmin.feature
> +    When user "newuser" removes user "subamin" from being a subadmin of group "new-group" using the provisioning API
Another ``subamin``` here

2018-11-29 04:12 UTC, phil-davis reviewed
I have reviewed it all now! There are just a few comments to be resolved, and get CI to pass.

2018-11-29 04:12 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +	 * @When the administrator all shares shared by him using the sharing API
```
When the administrator gets all shares...
```

``gets`` is missing

2018-11-29 04:12 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @When user :user tires to remove user :anotheruser from group :group using the provisioning API
s/tires/tries

2018-11-29 05:16 UTC, phil-davis requested changes

2018-11-29 05:16 UTC, phil-davis commented on package-lock.json
> +{
what happened? this is a bonus file

2018-11-29 06:38 UTC, phil-davis approved these changes
Should be good now, if CI passes.

2018-11-29 07:10 UTC, individual-it requested changes

2018-11-29 07:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +		. "/ocs/v{$this->ocsApiVersion}.php/apps/files_sharing/api/v{$this->sharingApiVersion}/shares?path=$path&subfiles=true";
make the line shorter

2018-11-29 07:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +		. "/ocs/v{$this->ocsApiVersion}.php/apps/files_sharing/api/v{$this->sharingApiVersion}/shares?reshares=true&path=$path";
make the line shorter

2018-11-29 07:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +		. "/ocs/v{$this->ocsApiVersion}.php/apps/files_sharing/api/v{$this->sharingApiVersion}/shares?path=$path";
make the line shorter

2018-11-29 09:10 UTC, individual-it requested changes

2018-11-29 09:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		PHPUnit_Framework_Assert::assertTrue(($this->response->getStatusCode() === 200 || 400));
no need to check the outcome in a `@When` step
and I think you can delete `@When user :user tries to make user :anotheruser a subadmin of group :group using the provisioning API` step

2018-11-29 09:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param string $observer
please explain in a comment what that means

2018-11-29 09:30 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param string $observer
Or maybe just call it ``$user``

2018-11-29 09:31 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		PHPUnit_Framework_Assert::assertTrue(($this->response->getStatusCode() === 200 || 400));
did you have a reason for putting this status check in here?

2018-11-29 11:02 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param string $observer
Great, I will go with @phil-davis 's suggestion.

2018-11-30 09:17 UTC, individual-it approved these changes

2018-11-30 09:33 UTC, paurakhsharma commented
@DeepDiver1975 Some issue with codecov. Can you please merge this. Thanks

2018-11-30 11:04 UTC, phil-davis commented
@paurakhsharma please backport. You will need to think about step text in extra scenarios in ``stable10`` that might need to be adjusted (e.g. user management). But maybe none of those are effected by this.

2018-11-30 15:58 UTC, merged

2018-12-03 06:17 UTC, paurakhsharma commented
Backport on: #33721