Add tests for local mount for specific user
owncloud/core pull request #33702
Opened 2018-11-30 09:02 UTC by paurakhsharma

## Description
This PR adds test for creating a local mount for a specific user.

Related issue: #33679

## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-30 09:12 UTC, individual-it requested changes

2018-11-30 09:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/BasicStructure.php
> +	 * @return null
```suggestion
	 * @return void
```

2018-11-30 09:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/BasicStructure.php
> +		\array_push($this->storageIds, $storageId);
user `$this->addStorageIds()`

2018-11-30 09:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +		$tempLoc = $this->featureContext->temporaryStorageSubfolderName();
maybe place that in a separate function and call it from `setupLocalStorageBefore()`

2018-11-30 09:58 UTC, paurakhsharma commented
@individual-it I have made the required changes. Please review it again.

2018-11-30 10:00 UTC, individual-it approved these changes

2018-11-30 10:01 UTC, individual-it requested changes
return comment wrong for `createLocalStoragaeMount()`

2018-11-30 10:28 UTC, individual-it approved these changes

2018-11-30 10:30 UTC, skshetry requested changes

2018-11-30 10:30 UTC, skshetry commented on tests/TestHelpers/SetupHelper.php
> +	public static function createLocalStoragaeMount($mount) {
```suggestion
	public static function createLocalStorageMount($mount) {
```

2018-11-30 11:30 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +	 * @When the administrator sets user :user as the applicable for last local storage mount using the occ command
This sentence does not read very well, but that is because ``files_external:applicable`` command is a strange name.
So I do not have a good sugggestion for what to do!

2018-12-03 08:04 UTC, skshetry approved these changes

2018-12-03 09:20 UTC, phil-davis approved these changes

2018-12-03 09:20 UTC, phil-davis commented
@paurakhsharma backport can be made

2018-12-03 09:31 UTC, paurakhsharma commented
Backport on: #33723

2018-12-03 12:07 UTC, phil-davis commented
Rebased to make drone happen

2018-12-03 12:54 UTC, merged