[stable10] [test] Change username for CleanPropertiesTest
owncloud/core pull request #33718
Opened 2018-12-01 14:33 UTC by phil-davis

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-12-01 15:11 UTC, patrickjahns commented
We only have a `setup` https://github.com/owncloud/core/blob/d4d770e7c57d681138913e9c3ad62adf37fca0b9/apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php#L45-L52 - bot not a `teardown`.

Which porbably causes the issue we see down the line.
This makes me wonder, how many other unit tests don't properly cleanup after themselves

2018-12-01 15:12 UTC, patrickjahns requested changes
Please provide a proper cleanup instead of the work around

2018-12-01 15:16 UTC, phil-davis commented
My IDE finds ``tests/lib/Traits/UserTrait.php`` that has ``tearDownUserTrait()`` - but I guess that is not called automagically.

``CleanPropertiesTest`` has multiple tests that make use of ``user1`` so somehow those are all running one after the other. But later on the encryption test fails.

Yes, this is a workaround. But CI is failing in ``stable10`` and needs to be fixed.

2018-12-01 15:32 UTC, phil-davis commented
I removed the review label and review requests. I agree it will be better to revert the offending PR and then apply a "proper" fix.

2018-12-03 06:59 UTC, phil-davis commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
It would be good that tests cleanup afterward, deleting users, groups etc that they created for the test.

2018-12-03 07:45 UTC, sharidas commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
In this context, https://github.com/owncloud/core/blob/master/tests/lib/Traits/UserTrait.php#L59 does cleanup the users created for the test.

2018-12-03 08:06 UTC, phil-davis commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
It is supposed to. I guess that method actually runs?
There is a problem somewhere!?

2018-12-03 10:16 UTC, PVince81 commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
there are other older tests that don't use `$this->createUser()` like that encryption one likely, so those tests wouldn't benefit from proper cleanup

2018-12-03 10:20 UTC, phil-davis commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
OK, I don't understand. If this new test that has ``createUser()`` does a proper ``deleteUser()`` cleanup on its way out, then the existence of ``userXYZ`` will be undetectable to any later code (test or otherwise)

2018-12-03 10:22 UTC, PVince81 commented on apps/dav/tests/unit/BackgroundJob/CleanPropertiesTest.php
> +		$this->createUser('userCleanPropertiesTest');
unless "later dirty code" actually runs earlier ?

2018-12-04 03:47 UTC, phil-davis commented
Closing, a workaround was implemented in a different PR.

2018-12-04 03:47 UTC, closed without merging