Unittest WebDavHelper
owncloud/core pull request #33724
Opened 2018-12-03 09:58 UTC by skshetry

## Description

This adds a test for `WebDavHelper`, though we cannot check that directly. so, we check for the `lastRequest` made.

## Related Issue

- Part of #32527

## Motivation and Context

## How Has This Been Tested?

- Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-12-03 10:02 UTC, skshetry commented
The diff for changes from #33704 is here: [e7107fe..7d62aad](https://github.com/owncloud/core/compare/e7107fe..7d62aad)

2018-12-04 03:50 UTC, individual-it requested changes

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		$this->assertEquals(['http://own.cloud/core%3Fq="my files"%23L133'], $lastRequest->getHeaders()["Destination"]);
please make that line shorter

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			'http://own.cloud///core',
why extra multiple `/` here?

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		// $davPath = WebDavHelper::getDavPath(null, 2, 'files');
please delete this lines that do not run

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		$davPath = WebDavHelper::getDavPath('user1', 2, 'files');
this and the test above is the same

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			['http://own.cloud/login?redirect=//two.cloud//files', 'http://own.cloud/login?redirect=/two.cloud/files']
make the line shorter

2018-12-04 03:50 UTC, individual-it commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			['http://own.cloud/login?redirect=//two.cloud//files', 'http://own.cloud/login?redirect=/two.cloud/files/']
shorter line pleae

2018-12-05 05:09 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			'http://own.cloud///core',
fixed.

2018-12-05 05:09 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		// $davPath = WebDavHelper::getDavPath(null, 2, 'files');
deleted. please review

2018-12-05 05:09 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		$davPath = WebDavHelper::getDavPath('user1', 2, 'files');
Making sure that the defaults is set to `files`

2018-12-05 05:10 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			['http://own.cloud/login?redirect=//two.cloud//files', 'http://own.cloud/login?redirect=/two.cloud/files']
done

2018-12-05 05:10 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +			['http://own.cloud/login?redirect=//two.cloud//files', 'http://own.cloud/login?redirect=/two.cloud/files/']
done

2018-12-05 05:10 UTC, skshetry commented
@individual-it please review again

2018-12-05 05:10 UTC, skshetry commented on tests/TestHelpers/Unit/WebDavHelperTest.php
> +		$this->assertEquals(['http://own.cloud/core%3Fq="my files"%23L133'], $lastRequest->getHeaders()["Destination"]);
done

2018-12-05 05:17 UTC, phil-davis reviewed
Needs various PHPdoc fixing

2018-12-05 05:17 UTC, phil-davis commented on tests/TestHelpers/HttpRequestHelper.php
> +		$client =  null
Needs PHPdoc of new parameter

2018-12-05 05:17 UTC, phil-davis commented on tests/TestHelpers/DeleteHelper.php
> +		$client = null
Needs PHPdoc of new parameter

2018-12-05 05:17 UTC, phil-davis commented on tests/TestHelpers/Unit/DeleteHelperTest.php
> +	public function setUp() {
Add PHPdoc for each method. (I expect that the code style checker will complain)
It should be easy - mostly no parameters and returns nothing

2018-12-05 05:17 UTC, phil-davis commented on tests/TestHelpers/WebDavHelper.php
> +		$client = null
PHPdoc needed for new parameter

2018-12-12 07:39 UTC, phil-davis commented
@skshetry needs rebase and resolve conflict

2018-12-12 08:37 UTC, skshetry commented
@phil-davis @individual-it I have made fixes on docs and code style. Please review again.

2018-12-12 08:41 UTC, phil-davis submitted a review, later dismissed
Seems OK.
@individual-it you had comments previously. Please check through them and approve if all is good.

2018-12-12 09:59 UTC, phil-davis approved these changes
Looks OK. We will see what CI says

2018-12-13 10:02 UTC, individual-it approved these changes

2018-12-13 10:02 UTC, merged

2018-12-13 10:08 UTC, skshetry commented
Backport for `stable10` in #33876