Test files:scan for specific users (negative validation)
owncloud/core pull request #33747
Opened 2018-12-04 10:06 UTC by skshetry

## Description

This adds a test for occ command `files:scan` for specific user.

## Related Issue

- Part of #33741

## Motivation and Context

## How Has This Been Tested?

- Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-12-04 10:06 UTC, skshetry commented
Negative validation for groups blocked by #33738

2018-12-04 10:36 UTC, skshetry commented on tests/acceptance/features/bootstrap/BasicStructure.php
> +			['file' => LOCAL_STORAGE_DIR_ON_REMOTE_SERVER . "/$path"],
Currently, this function is unknown that there can be multiple local storages. At present, we only delete from the `local_storage`. Will change in upcoming PR.

2018-12-04 10:43 UTC, individual-it requested changes

2018-12-04 10:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/BasicStructure.php
> +	public function theAdministratorCreatesFileWithContentInLocalStorageUsingTheTestingApi($path, $content, $mountPoint) {
please make the line shorter

2018-12-04 10:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/BasicStructure.php
> +			['file' => TEMPORARY_STORAGE_DIR_ON_REMOTE_SERVER . "/$mountPoint/$path", 'content' => $content],
make line shorter

2018-12-04 10:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +	public function theAdministratorHasSetTheExternalStorageToBeNever() {
I don't think we need that function at all, just use `theAdministratorHasSetTheExtStorageWithMountPoint()` and adjust the steps in feature files

2018-12-05 03:50 UTC, phil-davis commented on tests/acceptance/features/cliMain/files.feature
> +    And user "user0" has created a folder "/local_storage/folder1"
``created a folder`` diffs will need to be changed back to ``created folder``

2018-12-05 06:25 UTC, individual-it approved these changes

2018-12-05 06:26 UTC, merged

2018-12-05 06:47 UTC, skshetry commented
Backport for stable10 on #33768