[stable10] Test files:scan for specific users (negative validation)
owncloud/core pull request #33768
Opened 2018-12-05 06:46 UTC by skshetry

Backport for #33747

2018-12-05 06:59 UTC, phil-davis approved these changes

2018-12-06 06:12 UTC, phil-davis commented on tests/TestHelpers/UploadHelper.php
> +			$result = WebDavHelper::makeDavRequest Total 5 min Monthly Balance -22 h 26 min
@paurakhsharma something went wrong here

2018-12-06 06:12 UTC, phil-davis requested changes
Rebase has accidental code changes

2018-12-06 06:16 UTC, paurakhsharma commented on tests/TestHelpers/UploadHelper.php
> +			$result = WebDavHelper::makeDavRequest Total 5 min Monthly Balance -22 h 26 min
@skshetry Pasted his tmetric stats here 😄

2018-12-07 05:10 UTC, skshetry commented
@ownclouders rebase

2018-12-07 05:10 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-12-07 05:11 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-12-07 05:22 UTC, phil-davis approved these changes
Looks good now

2018-12-07 07:45 UTC, merged