webUI tests for admin external storage page
owncloud/core pull request #33839
Opened 2018-12-10 08:52 UTC by paurakhsharma

## Description
This PR webUI tests for files_external.

Related issue: https://github.com/owncloud/enterprise/issues/2417

## How Has This Been Tested?
🤖

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-12-10 09:03 UTC, skshetry requested changes

2018-12-10 09:03 UTC, skshetry commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +		$this->waitUntillSuccessOrFailureSymbol();
```suggestion
		$this->waitUntilSuccessOrFailureSymbol();
```

2018-12-10 09:03 UTC, skshetry commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	public function waitUntillSuccessOrFailureSymbol(
```suggestion
	public function waitUntilSuccessOrFailureSymbol(
```

2018-12-10 09:08 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
> +	 * WebUIAdminStorageSettingsContext constructor.
That's a great suggestion but that's the way docstring is written in all webUI contexts.

2018-12-10 09:10 UTC, paurakhsharma commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +		$this->waitUntillSuccessOrFailureSymbol();
Oh, there are no two l's in untill 😄

2018-12-10 09:16 UTC, phil-davis reviewed
Looks like "a good thing". I only found typos.

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
> +	public function theAdministratorAddsUserAsTheApplicableUserForTheLastLocalStorageMountUsingTheUsingTheWebui($action, $userOrGroup, $user) {
put parameters on a new line

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	protected $filesExternalForumXpath = "//form[@id='files_external']";
Forum or Form?

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	protected $applibableUserXpath = "//tr[@id='addMountPoint']/preceding-sibling::tr[1]//li[@class='select2-search-choice'][%s]//span";
s/applibableUser/applicableUser/

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	protected $applibableUserDeleteXpath = "//tr[@id='addMountPoint']/preceding-sibling::tr[1]//li[@class='select2-search-choice'][%s]//a";
s/applibableUser/applicableUser/

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +		$this->waitUntillSuccessOrFailureSymbol();
s/Untill/Until

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +				$applibableUserDelete = $this->find(
s/applibable/applicable

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	 * Wait untill sucess or failure symbol to appear
s/untill sucess/until success 

Wait until success or failure symbol appears

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	public function waitUntillSuccessOrFailureSymbol(
s/Untill/Until

2018-12-10 09:16 UTC, phil-davis commented on tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
> +  Scenario: administrator assigns a applicable user to a local storage mount
s/a applicable user/an applicable user

2018-12-10 09:46 UTC, phil-davis commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	 * Wait until sucess or failure symbol to appear
s/sucess/success

2018-12-11 09:02 UTC, paurakhsharma commented
@phil-davis @skshetry Please review it again, thanks.

2018-12-11 09:06 UTC, skshetry commented on tests/acceptance/features/lib/AdminStorageSettingsPage.php
> +	public function waitUntilSuccessOrFailureSymbol(
```suggestion
	public function waitUntilSuccessOrFailureSymbolAppears(
```

2018-12-11 09:07 UTC, skshetry requested changes
LGTM except a issue. See above comment.

2018-12-11 09:20 UTC, phil-davis approved these changes
Looks good now. Saugat just has 1 suggestion of a method name.

2018-12-11 10:10 UTC, skshetry approved these changes

2018-12-11 10:11 UTC, merged

2018-12-11 10:14 UTC, paurakhsharma commented
Backport on: #33855