Add webUI acceptance tests for checking set and delete profile pic (a…
owncloud/core pull request #33877
Opened 2018-12-13 10:12 UTC by dpakach

…vatar)

## Description

Add webui test for checking profile picture
1. Set profile picture and check if it shows
2. Delete existing profile picture 

## Related Issue

- Related to #32850

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2018-12-13 11:03 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +		if ($should) {
This should be straightforward to check. 
```suggestion
		if ($should !== 'not') {
```

2018-12-13 11:07 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +		$should = $shouldOrNot !== "not";
```suggestion
```

2018-12-13 11:09 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +		$should = $shouldOrNot !== "not";
Sorry, see above comment.

2018-12-13 11:16 UTC, skshetry requested changes

2018-12-13 11:16 UTC, skshetry commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +	public function setProfilePic($fileName, Session $session) {
```suggestion
	public function setProfilePicture($fileName, Session $session) {
```

2018-12-13 11:16 UTC, skshetry commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +	public function isProfilePicPreviewDisplayed() {
```suggestion
	public function isProfilePicturePreviewDisplayed() {
```

2018-12-13 11:16 UTC, skshetry commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +	public function deleteProfilePic(Session $session) {
```suggestion
	public function deleteProfilePicture(Session $session) {
```

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +		$this->waitTillElementIsNotNull($this->setProfilePicFromFilesBtnXpath);
Should this line be before the ``find()`` ?

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +		$this->waitTillElementIsNotNull($this->setProfilePicFileListXpath . \sprintf($this->fileListElementMatchXpath, $fileName));
This line is long. Split it.

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @When the user sets profile picture to :filename from the uploaded files using the webUI
This step selects the profile picture from the user's cloud storage files - skeleton files or files they have uploaded or synced. In the test steps, we do not see any files being uploaded, but we see this step that mentions "from the uploaded files", which was a bit confusing for me.

Maybe say:
```
When the user sets the profile picture to :filename from their cloud files using the webUI
```
or?

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @Given the user has set profile picture to :filename from the uploaded files
And change the words of this step to something like above:
```
Given the user has set the profile picture to :filename from their cloud files
```

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @Then /^the preview of profile picture should (not|)\s?be shown in the webUI$/
s/the preview of profile picture/the preview of the profile picture

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @When the user deletes existing profile picture
```
When the user deletes the existing profile picture
```

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @Given the user has deleted existing profile picture if any
```
Given the user has deleted any existing profile picture
```
reads easier IMO

2018-12-13 13:47 UTC, phil-davis commented on tests/acceptance/features/webUIPersonalSettings/personalGeneralSettings.feature
> +  Scenario: User sets profile picture from uploaded file
User sets profile picture from cloud file
?

2018-12-14 04:47 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @When the user sets profile picture to :filename from the uploaded files using the webUI
ok That sounds preety good to me too

2018-12-14 05:14 UTC, individual-it requested changes

2018-12-14 05:14 UTC, individual-it commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +		$file = $fileList->find('xpath', \sprintf($this->fileListElementMatchXpath, $fileName));
please check also with `OwncloudPage::assertElementNotNull()`

2018-12-14 05:14 UTC, individual-it commented on tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
> +			__METHOD__ . "Profile Picture delete Button not found"
space after `"`

2018-12-14 08:03 UTC, skshetry approved these changes

2018-12-14 10:43 UTC, individual-it approved these changes

2018-12-14 10:44 UTC, merged

2018-12-14 10:48 UTC, dpakach commented
Stable10 backport on #33892