[WIP] View-only dav plugin using extra share permissions manager.
owncloud/core pull request #33994
Opened 2018-12-31 16:30 UTC by mrow4a

- [x] Implement extra share permissions manager from Approach 3 here - https://github.com/owncloud/core/issues/33458
- [x] Implement view-only plugin using extra share permissions manager to restrict view-only permission for read-only files.
- [ ] Use additional table instead of extended table, clean the code.

@PVince81 @DeepDiver1975 @pmaier1

2019-01-07 09:57 UTC, mrow4a commented
In PR for view-only plugin & extra share permission, I initially took an approach (https://github.com/owncloud/core/issues/33458) of extending `oc_share` table with new string column (json) `extra_share_permissions`. However, I think of going with the approach of external tables. These are pros&cons:

Extended `oc_share` table:
- currently adds new function `setExtraPermissions/getExtraPermissions` only to Share20\Share class - https://github.com/owncloud/core/pull/33994/files#diff-a19a495d2d4616d9b451f849126013a4. IShare is not touched as it would require all apps to adjust.
- easy to implement, no additional queries needed (single query retrieves the information). Expensive as each share need to reserve string space in DB
- requires to add additional API functions to IShare?, or keep with appraoch of `if instanceof Share20\Share` https://github.com/owncloud/core/pull/33994/files#diff-faddd9984dfaf09a2b85d8dc4867207aR887

New `extra_share_permissions` table:
- ExtraShareManager used to retrieve extra share permissions for shares
-`IShare` or `Share/IManager` not extended, new classes used (`Share/ExtraPermissions/IManager`)
- new table, reserves space in DB only for shares which have extra share permissions (by full-share-id/share-id).
- might need some additional queries to DB to retrieve extra share permissions. 

@DeepDiver1975 @PVince81 do you have any input?

2019-01-07 21:41 UTC, DeepDiver1975 requested changes

2019-01-07 21:41 UTC, DeepDiver1975 commented on core/Migrations/Version20181220085457.php
> +		// FIXME: Should Type::TEXT or Type::JSON be used?
give it a try with the JSON type as discussed and let's see ...

2019-01-07 21:41 UTC, DeepDiver1975 commented on lib/private/Share20/DefaultShareProvider.php
> +		$qb->setValue('extra_permissions', $qb->createNamedParameter($shareExtraPermissions->serialize()));
the table defines a default value - no need to set anything here from my pov ....

2019-01-07 21:41 UTC, DeepDiver1975 commented on lib/private/Share20/ExtraPermissions/Permissions.php
> +class Permissions implements IPermissions {
I don't see the need of this class. Just use an array with the app as key and the permission as value

2019-01-07 21:41 UTC, DeepDiver1975 commented on lib/private/Share20/ExtraPermissions/Permission.php
> +	private $app;
why app again? app is the key in the permissions array ....

2019-02-11 07:41 UTC, DeepDiver1975 requested changes
Looks good - this can be merged after comments have been addressed

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> + * @copyright Copyright (c) 2018, ownCloud GmbH
2019

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +	public function __construct() {
remove if not needed

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +		} catch (NotFound $e) {
log them all

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +				throw new Forbidden('File is in secure-view mode and cannot be directly downloaded.');
translation necessary? @PVince81 do we translate exception messages in dav plugins at all?

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +		$this->request = $this->getMockBuilder('Sabre\HTTP\RequestInterface')->getMock();
use ::class

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +		$this->request = $this->getMockBuilder('Sabre\HTTP\RequestInterface')->getMock();
use createMock

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +		$this->tree->method('getNodeForPath')->willReturn('this is not Dav File');
getNodeForPath will not return this string - right?

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +		$davNode->method('getNode')->willReturn('this is not File or Folder');
get node is returning a node instance - not a string

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +	public function nodeReturns() {
name proposal: providesDataForCanGet

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +	public function testCanGet($node, $canDownloadPerm, $isUpdatable, $expected) {
expected argument is usually always the first

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +		if ($extraPermissions !== null) {
looks like code duplication from below - line 1201++

2019-02-11 07:41 UTC, DeepDiver1975 commented on apps/files_sharing/tests/ApiTest.php
>  		$params = [];
easier to read
```php
$params = [
  'permissions' => '1',
  'extraPermissions' => [
    'app' => 'app1'
    ....
]
]

2019-02-11 07:41 UTC, DeepDiver1975 commented on core/Migrations/Version20181220085457.php
> +namespace OC\Migrations;
file header is missing

2019-02-11 07:41 UTC, DeepDiver1975 commented on core/js/shareitemmodel.js
> +				throw "Unknown Share";
will the user see this? translate then

2019-02-11 07:41 UTC, DeepDiver1975 commented on lib/private/Share20/ExtraPermissions.php
> +	public function __construct() {
remove - not needed

2019-02-11 07:41 UTC, DeepDiver1975 commented on lib/public/Share/IShare.php
> +	public function setExtraPermissions($permissions);
add type to argument please

2019-02-11 07:41 UTC, DeepDiver1975 commented on lib/public/Share/IShare.php
> +	public function getExtraPermissions();
add return type please

2019-02-11 18:05 UTC, mrow4a commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +				throw new Forbidden('File is in secure-view mode and cannot be directly downloaded.');
Not, there are no - also Dav Browser Error plugin is broken and displays legacy page, see - 
https://github.com/owncloud/core/pull/33992

2019-03-09 15:02 UTC, mrow4a commented on core/js/shareitemmodel.js
> +				throw "Unknown Share";
It is everywhere in the code like that, would require refactor to change it. Anyways it is rather a signal of the bug rather than expected exception

2019-03-11 07:44 UTC, DeepDiver1975 requested changes

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +	/** @var \Sabre\DAV\Server $server */
ilogger

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/files/download.php
> +	\header("HTTP/1.0 500 Forbidden");
500? forbiddeb?

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/files_sharing/lib/ViewOnly.php
> +					$canDownload = false;
maybe return right away?

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/files_sharing/lib/ViewOnly.php
> +		$files = Filesystem::getDirectoryContent($dir);
hard to mock - use non-static

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/files_sharing/tests/FileListenersTest.php
> +		$this->eventDispatcher = \OC::$server->getEventDispatcher();
mock this please

2019-03-11 07:44 UTC, DeepDiver1975 commented on apps/files_sharing/tests/FileListenersTest.php
> +			\OC::$server->getRootFolder(),
mock

2019-03-11 19:04 UTC, mrow4a commented on apps/files_sharing/tests/FileListenersTest.php
> +		$this->eventDispatcher = \OC::$server->getEventDispatcher();
@DeepDiver1975 this was the problem I tried to solve for a long time working on unit tests for this feature. It is non trivial to test that Hook class which uses that ViewOnly class (which uses Filesystem directly).

2019-03-11 19:05 UTC, mrow4a commented on apps/files_sharing/tests/FileListenersTest.php
> +			\OC::$server->getRootFolder(),
I had to use real classes not to make other unit tests fail (it uses global event dispatcher, and thus the registered listeners are active across many tests.. thus real classes need to be used not mocks)

2019-03-11 19:05 UTC, mrow4a commented on apps/files_sharing/lib/ViewOnly.php
> +		$files = Filesystem::getDirectoryContent($dir);
@DeepDiver1975 what non-static equivalent function do you suggest?

2019-03-11 19:08 UTC, mrow4a commented on apps/files_sharing/tests/FileListenersTest.php
> +		$this->eventDispatcher = \OC::$server->getEventDispatcher();
I can probably test ViewOnly separatelly and with Hooks class I just tests that these functions are being called - maybe this could simplify it.

2019-03-11 19:16 UTC, DeepDiver1975 commented on apps/files_sharing/tests/FileListenersTest.php
> +			\OC::$server->getRootFolder(),
it should be possible to mock dispatcher as well as all other instances you are passing into the hooks class ... as long as no static file system methods are used (this should be avoided in any case)

2019-03-22 11:25 UTC, jvillafanez commented on lib/private/Share20/DefaultShareProvider.php
> +		if ($data !== null) {
being a private function and stating that the "$data" parameter is a string (in the phpdoc), this check doesn't seem needed. I'd move the responsability to the caller.

2019-03-22 11:25 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +		foreach ($perms->getScopes() as $scope) {
I've seen this piece of code in several places... maybe it should be part of the `IAttributes`. A `toArray()` might be interesting. Note that the definition should be flexible

2019-03-22 11:32 UTC, DeepDiver1975 commented on apps/files_sharing/lib/AppInfo/Application.php
> +				$uid
Absolutly - furthermore it is a hard requirement in any case because of the initialization process and when the current user is know ...

2019-03-22 13:54 UTC, mrow4a commented on lib/private/Share20/Manager.php
> +		foreach ($perms->getScopes() as $scope) {
@jvillafancez not sure what is the intention here

2019-03-22 13:56 UTC, mrow4a commented on apps/files_sharing/lib/ViewOnly.php
> +				continue;
It has unit tests, and is 100% covered for each of the cases

2019-03-22 13:56 UTC, mrow4a commented on apps/files_sharing/lib/ViewOnly.php
> +				continue;
Check HooksTest

2019-03-22 13:58 UTC, mrow4a commented on lib/private/Share20/Manager.php
> +		foreach ($perms->getScopes() as $scope) {
you want IAttributes to have function toArray which returns map with attributes?

2019-03-22 14:27 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +		foreach ($perms->getScopes() as $scope) {
I think the intention here is to create a json based on the contents of the attribute object. While returning a json might be too much, just returning a known array structure that can be easily feed into a json can be enough. This piece of code can be moved into the IAttribute, which additionally will prevent code duplication.
You'll still need to do the loops, but we move the responsability to create a known array structure to the IAttribute class.

2019-03-22 14:29 UTC, jvillafanez commented on apps/files_sharing/tests/HooksTest.php
> +		$return[] = [ '/bar.txt', $senderUserFolder, true ];
if possible, better use "result" as variable name to prevent any confusion

2019-03-27 02:03 UTC, mrow4a commented on apps/files_sharing/lib/AppInfo/Application.php
> +				$uid
makes sense, adjusted

2019-03-27 02:03 UTC, mrow4a commented on apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
> +			$ret = $this->plugin->checkViewOnly($this->request);
I now assert for exception

2019-03-27 20:41 UTC, mrow4a commented
@jvillafanez @DeepDiver1975 adjusted to reviews

2019-04-01 13:56 UTC, PVince81 commented on apps/files_sharing/lib/Hooks.php
> +					$viewOnlyHandler = new ViewOnly(
weird that "ViewOnly" is not imported anywhere ?!

2019-04-01 14:04 UTC, PVince81 commented on apps/files_sharing/lib/Hooks.php
> +					$viewOnlyHandler = new ViewOnly(
never mind, same namespace

2019-04-01 14:23 UTC, PVince81 requested changes
some minor changes like bad condition, typo

one nice to have: ability to switch a checkbox to set a permission to "false" instead of "true"

2019-04-01 14:23 UTC, PVince81 commented on apps/files_sharing/lib/Hooks.php
> +				if ($uid = $this->getCurrentUserUid()) {
bad practice, please use strict comparison.

in PHP `if  "0"` returns false, so user ids like "0" would fail this test...

2019-04-01 14:23 UTC, PVince81 commented on core/Migrations/Version20181220085457.php
> +					Type::JSON,
do we have integration tests covering this ? I hope this works for all our supported DBs

2019-04-01 14:23 UTC, PVince81 commented on core/js/sharedialogshareelistview.js
> +					enabled: checked
use the "value" attribute to make it reversible ? we can then set "value='false'" to have the checkbox negate a permission when ticked

this would open the door for more understandable checkbox labels like "restricted mode" or something instead of "can view"

2019-04-01 14:23 UTC, PVince81 commented on core/js/shareitemmodel.js
> +					filteredAttributes.push({
adding generic attributes on the server side was ok for storage purposes, but treating them in a generic way on the client just for 2 new attributes instead of hard-coding feels a bit over-engineered.

also this will cost way more time to add unit tests to make sure your generic logic works correctly while with a few hard-coded states for 2 attributes would produce smaller tests

let's leave this as is for now...

2019-04-01 14:23 UTC, PVince81 commented on core/js/shareitemmodel.js
> +			var currentAttributes = JSON.parse(share.attributes);
hmm, I'd have expected these to be pre-parsed when returned in the JSON response

anyway, let's leave this

2019-04-01 14:23 UTC, PVince81 commented on lib/private/Share20/Manager.php
> +			'attributes' => $share->getattributes(),
capital A

2019-04-01 14:23 UTC, PVince81 commented on lib/public/Share/IAttributes.php
> +interface IAttributes {
IShareAttributes would have been better... we started a bad trend by having interface names relying on their namespaces... general confusion then when importing multiple of them with `use`

2019-04-01 14:25 UTC, PVince81 commented
also:

- [ ] missing JS tests especially for the complex frontend attribute logic

2019-04-01 14:34 UTC, PVince81 commented
- [ ] raise docs ticket and provide documentation for registering custom share attributes and their details

2019-04-01 14:36 UTC, PVince81 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +use OCA\Files_Sharing\SharedStorage;
this will fail to import if the "files_sharing" app is disabled. better use the string instead for instance check like we do in other places.

2019-04-01 14:36 UTC, PVince81 commented on apps/dav/lib/DAV/ViewOnlyPlugin.php
> +			if (!$storage->instanceOfStorage(SharedStorage::class)) {
use string here because class might not be loaded when "files_sharing" is disabled

2019-04-01 14:42 UTC, PVince81 commented on core/js/sharedialogshareelistview.js
> +					enabled: checked
or add an attribute "reverse" in the share attribute spec

2019-04-01 14:44 UTC, PVince81 commented on core/js/sharedialogshareelistview.js
> +			'<input id="can-{{name}}-{{cid}}-{{shareWith}}" type="checkbox" name="{{name}}" class="attributes checkbox" {{#if enabled}}checked="checked"{{/if}} data-scope="{{scope}}" data-enabled="{{enabled}}
"enabled" is semantically the same as "checked".

in frontend terms we usually use "enabled" and "disabled" to gray out a component to make it read-only for example.

so when reading this code I was confused that "enabled" actually meant "checked"

2019-04-01 14:47 UTC, PVince81 commented
what happens if two apps register the same attribute in the frontend ?

2019-04-01 14:51 UTC, PVince81 commented
fixed minor points, rebased and adjusted for php unit 6

2019-04-01 14:53 UTC, PVince81 commented on core/js/shareitemmodel.js
> +	 * @property {OC.Share.Types.ShareAttribute[]} incompatibleAttributes
please add the actual doc text, what are these attributes about ?

2019-04-02 09:08 UTC, DeepDiver1975 commented on core/Migrations/Version20181220085457.php
> +					Type::JSON,
unit tests are covering this - at least as we initially discussed using this data type

2019-04-02 10:01 UTC, DeepDiver1975 requested changes
will submit fixes for the comments asap

2019-04-02 13:10 UTC, PVince81 commented
I've squashed everything into two distinct commits:
1) first commit adds support for extra share permissions
2) second commit uses said support for the view-only "download" permission

2019-04-02 13:10 UTC, PVince81 commented
I'm a bit concerned that the JSON field might not work in all databases with upsert from this upcoming PR https://github.com/owncloud/core/pull/34769.

we will see after merging and rebasing the other one...

2019-04-02 13:18 UTC, PVince81 approved these changes

2019-04-02 13:43 UTC, merged

2019-04-02 13:47 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/34951

2019-04-02 14:52 UTC, PVince81 commented
seems no issues with upsert and JSON: https://github.com/owncloud/core/pull/34952

2019-04-09 14:09 UTC, DeepDiver1975 commented
THX @LinneyS - mind opening a pull request? We can much easier discuss this then. THX a lot!

2019-04-09 19:41 UTC, mrow4a commented
@LinneyS what is such permission about? We need to be sure that it follows the logic for "permissions in owncloud". That means, that checked permission box adds some higher level of permission, and unchecked lowers the permission level.

2019-04-10 10:38 UTC, LinneyS commented on core/js/shareitemmodel.js
> +	 * @property {OC.Share.Types.ShareAttribute[]} incompatibleAttributes
How and where is the `description` property used?

2019-05-28 11:22 UTC, phil-davis commented
`backport-request`  label removed. The backport was done already, see https://github.com/owncloud/core/pull/33994#issuecomment-479003389