Improve Files UX error handling
owncloud/core pull request #33992
Opened 2018-12-31 09:58 UTC by mrow4a

This fixes a bug in which when e.g. Forbidden is thrown for file when "Download" is clicked, the loading wheel is still spinning

This
<img width="1153" alt="faileddownload" src="https://user-images.githubusercontent.com/13368647/50557995-8f71ef00-0cea-11e9-8222-733dca8a88d6.png">

Now will be 
<img width="982" alt="handledfaileddownload" src="https://user-images.githubusercontent.com/13368647/50558005-97ca2a00-0cea-11e9-9404-775eecac6f19.png">

2018-12-31 13:02 UTC, mrow4a commented
I also noticed that BrowserErrorPagePlugin works incorrectly (https://github.com/owncloud/core/blob/master/apps/dav/lib/Files/BrowserErrorPagePlugin.php#L98), showing such ugly page as it cannot load scripts

<img width="912" alt="screenshot at dec 31 14-00-46" src="https://user-images.githubusercontent.com/13368647/50560803-a45b7c00-0d04-11e9-9067-783f740a53f6.png">

2019-01-07 15:54 UTC, PVince81 commented on apps/files/js/files.js
> +								'You cannot download this file!'),
what's the usual cause ? file was deleted from disk but still in file cache ?

depending on this we could tweak the message

2019-01-07 16:21 UTC, mrow4a commented on apps/files/js/files.js
> +								'You cannot download this file!'),
@PVince81 E.g. that user tries to download it using some URI/button, but one of the apps prevents it. It should show nice message instead of ugly page

2019-01-07 16:21 UTC, mrow4a commented on apps/files/js/files.js
> +								'You cannot download this file!'),
But I am still not sure how to solve https://github.com/owncloud/core/pull/33992#issuecomment-450643425

2019-01-11 09:22 UTC, PVince81 commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +			$this->setSecretCookie('ocDownloadFailed', $token);
I wonder if we could reuse the other cookie but add a special value ?

2019-01-11 09:23 UTC, PVince81 requested changes
also please fix the JS tests

2019-01-11 13:48 UTC, mrow4a commented
@PVince81 do you know what might be wrong with these "ugly pages" and `Refused to load X.js because it appears` ?

2019-01-30 21:46 UTC, mrow4a commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
> +		$this->server->on('exception', [$this, 'handleDownloadFailure']);
To simulate exception, one can just add in FilesPlugin 
```
...
		$this->server->on('method:GET', [$this, 'throwEx'], 90);
...

	public function throwEx() {
		throw new Forbidden("cannot download");
	}
	
```

2019-02-19 17:45 UTC, mrow4a commented
This can be closed in favour of not showing download button in UX when special dav flag is enabled. Reopen if this wont be easily possible.

2019-03-15 11:04 UTC, PVince81 commented
I'll first reopen to investigate

2019-03-15 11:05 UTC, PVince81 commented
hiding the button is a good idea but won't cover the case where the permissions changed while the web UI is already rendered. we need both:

- [ ] fix forbidden page
- [ ] hide button when permission not set

where can we read the permission from ? @mrow4a

2019-03-15 13:26 UTC, mrow4a commented
@PVince81 I already included this in https://github.com/owncloud/core/pull/33994/commits/ddfe043f49cd8ec5bacbe329cc3e2f7f770986b5

2019-03-18 16:45 UTC, PVince81 commented
Steps to reproduce without the richdocuments app on master:

1. Enable firewall app
1. Upload a file "test.txt"
1. Apply a new system tag "forbidden"
1. Create a firewall rule to block based on this tag
1. Try downloading the file

Expected: proper error handling.
Actual: forbidden page.

As the firewall is a rather common app, I wonder when this problem started happening.

2019-03-18 16:46 UTC, PVince81 commented
we might be missing CSP rules to properly display the "Forbidden" page:
![image](https://user-images.githubusercontent.com/277525/54547294-b82e8a00-49a5-11e9-9e16-0727a535a273.png)

2019-03-18 16:56 UTC, PVince81 commented
also happens on OC 10.0.5... hmmm....

2019-03-18 17:11 UTC, PVince81 commented
ok, seems the BrowserErrorPagePlugin is missing CSP rules, but is also not properly forwarding the exception message...

2019-03-18 17:22 UTC, PVince81 commented
PR to fix the error page specifically: https://github.com/owncloud/core/pull/34798

2019-03-19 15:05 UTC, PVince81 commented
@m

2019-03-19 18:32 UTC, mrow4a commented
@PVince81 this PR is needed to fix spinning wheel problem, even including #34798 when error page appears, and you "go back to previous page", javascript is broken with exception.

Firewall app is also affected.

2019-03-19 18:35 UTC, mrow4a commented
@PVince81 @IljaN just tested and it work, can you review and merge?

2019-03-21 20:14 UTC, mrow4a commented
@PVince81 you want to take this over? This is just an improvement to the UX

2019-03-25 09:27 UTC, PVince81 approved these changes
:+1:

2019-03-25 09:27 UTC, merged

2019-03-25 09:29 UTC, PVince81 commented
stable10: https://github.com/owncloud/core/pull/34886