Fix persistent lock timeout behavior
owncloud/core pull request #34100
Opened 2019-01-09 13:32 UTC by PVince81

## Description
Set timeout from header when specified.
Timeout value returned in lock discovery must be the remaining time.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/33846

## Motivation and Context
Timeout has bugs

## How Has This Been Tested?
Manual tests

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-09 13:35 UTC, PVince81 commented
- [ ] inclarity about infinity timeout

@DeepDiver1975 please clarify: currently the code always uses "1800" seconds if no timeout is given.

I've fixed it to properly read the timeout header which can be any integer or "Infinite".

It seems the decision was to ignore "Infinite" (-1) and go with 1800 ?
The current logic + SQL cannot deal with infinite timeout. RFC says the server has the last say.
It even seems that a request can contain multiple timeout values, in case one is not accepted... Seems Sabre ignores the second value so no fallback possible.

- [ ] LOCK response always contains the value from the "Timeout" header, even if we overrode it. Need to adjust "lockInfo" in case of override / non-accepted value

2019-01-15 13:29 UTC, DeepDiver1975 requested changes

2019-01-15 13:51 UTC, PVince81 commented on apps/dav/lib/Files/FileLocksBackend.php
> +			$lockInfo->timeout = $lock->getTimeout() - (\OC::$server->getTimeFactory()->getTime() - $lock->getCreatedAt());
injection is usually ugly with Sabre plugins.

will try it in the next iteration

2019-01-17 09:30 UTC, PVince81 commented
as discussed:

- change LockManager to return the ILock instance, then get its timeout value in FileLockBackend to be set to lockInfo
- proposal: have a max value of 1 day. if given timeout value is higher or infinte, set it back to 1 day

2019-01-17 14:36 UTC, PVince81 commented
- added timefactory
- added default and max timeout of 1 day
- adjusted phpdocs
- now using ILock as return value for lockNodePersistent() to be able to read the updated timeout value

@DeepDiver1975 there is some little trouble now: since we return ILock after creation, the object itself doesn't have all attributes populated: the user and the abs dav path are not populated after insert. So the object you get is not 100% the same as the one you get with getLocks.

An alterative proposal would be to have lockNodePersistent return an updated lockInfo object instead...

2019-01-17 14:37 UTC, PVince81 commented on lib/private/Lock/Persistent/LockManager.php
> +				return $lock;
I hope this is ok: there can be only one lock with a given token, so no need to continue searching the list, we can return directly. Please confirm @DeepDiver1975

2019-01-17 14:38 UTC, PVince81 commented
@DeepDiver1975 please review again, made changes as discussed.

See additional comment on the diff + the comment above about incomplete lock object

2019-01-21 08:59 UTC, DeepDiver1975 approved these changes

2019-01-21 08:59 UTC, DeepDiver1975 commented on lib/private/Lock/Persistent/LockManager.php
> +				return $lock;
:+1:

2019-01-21 15:21 UTC, PVince81 commented
rebased, and had to fix a failing test due to clash with the other locking PR from https://github.com/owncloud/core/pull/34171

2019-01-21 19:52 UTC, PVince81 commented
web ui acceptance tests ran too long... I'll take the risk and merge this

2019-01-21 19:52 UTC, merged

2019-01-24 13:07 UTC, phil-davis commented
Backport ``stable10`` #34208