WebDav Client missing proxy credentials
owncloud/core pull request #34101
Opened 2019-01-09 14:12 UTC by micbar

## Description
Adds the proxy user and passwords to the Curl Options.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/3078

## Motivation and Context
Federation behind a Proxy is not possible without this patch.

## How Has This Been Tested?
- will be tested manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-09 15:15 UTC, PVince81 commented on lib/private/Http/Client/WebDavClientService.php
> +			$proxyUri .= $proxyUserPwd . '@';
wondering if it works if the password contains a "@" :-D

2019-01-09 15:18 UTC, PVince81 commented on tests/lib/Http/Client/WebDavClientServiceTest.php
> +					['proxyuserpwd', null, 'user:password']
also need a test case where proxuyuserpwd is not set ?

2019-01-09 15:18 UTC, PVince81 reviewed
thanks for the PR, as discussed

some minor comments

2019-01-09 16:11 UTC, micbar commented on tests/lib/Http/Client/WebDavClientServiceTest.php
> +					['proxyuserpwd', null, 'user:password']
Ok, that would be advisable.

2019-01-09 16:40 UTC, micbar commented on lib/private/Http/Client/WebDavClientService.php
> +			$proxyUri .= $proxyUserPwd . '@';
Little research tells me, that we should encode special characters. We are not doing it in the GuzzleHttp Client either. Maybe we should leave it this way and document, that we need an encoded string in config.php
`foo:B@r` should look like `foo:B%40r`

2019-01-09 16:43 UTC, micbar commented on tests/lib/Http/Client/WebDavClientServiceTest.php
> +					['proxyuserpwd', null, 'user:password']
Done.

2019-01-09 17:06 UTC, micbar commented
Added an additional test.
I think we should document the need to encode special chars in the username:password string.

@PVince81

2019-01-10 16:05 UTC, mmattel commented on lib/private/Http/Client/WebDavClientService.php
> +			$proxyUri .= $proxyUserPwd . '@';
In case, please drop a note if there is a doc change necessary and what.

2019-01-14 08:56 UTC, PVince81 commented
@micbar would it take more time to document it or to implement it correctly right away ?

2019-01-14 09:12 UTC, micbar commented
@PVince81 regarding the implementation  I would prefer documenting the need for escaping.

regarding the code, I have not been able to test it yet. Adjusted the labels.
maybe @patrickjahns has an idea how to get a test setup with two federated servers with FQDN an SSL Cert which can only resolve the other domain via a password protected proxy server?

2019-01-14 09:58 UTC, PVince81 commented
@micbar ok, please document by editing config.sample.php

2019-01-15 17:10 UTC, mmattel commented
@micbar pls add me or @settermjd  to the config.sample.php PR (and backport) when improving the description because we have to do some backend task to transfer the content to docs when it gets merged - thanks.

2019-01-15 19:17 UTC, patrickjahns commented
> maybe @patrickjahns has an idea how to get a test setup with two federated servers with FQDN and SSL Cert which can only resolve the other domain via a password protected proxy server?

Could you clarify what you mean by resolving the domain? Resolving ( dns ) is independent of proxy servers. Http connections should pass through a proxy.

For manually testing, you might just use mitmproxy in regular mode https://docs.mitmproxy.org/stable/concepts-modes/#regular-proxy 

Steps:
- setup remote ownCloud "somewhere" ( example:  use local loopback device with 10.254.254.254 + docker container on port 8080. Add "federated.cloud" to /etc/hosts with 10.254.254.254  )
- setup the ownCloud with this patch locally 
- start mitmproxy
- configure local owncloud to use mitmproxy
validate that all requests that arrive at federated.cloud:8080 passed through mitmproxy

2019-01-18 20:31 UTC, micbar commented
@cdamken @PVince81 
We need someone to take over. I am not available for the next 4 weeks due to a full-time project.

I am not sure with the current approach. Maybe something else is missing.

We got the stack trace above, when entering `user:pass@proxy.domain` as the `proxy` value in config.php. This sends the same values to the CURL Request as with this PR and separate values.

2019-02-27 10:31 UTC, PVince81 commented
as discussed internally, @micbar will take over again and finish this.

2019-04-08 15:13 UTC, micbar commented
@PVince81 
I invested some time again.
I think that the code of the PR works correctly, because it sets the proxy values correctly.

I could not overcome the last part of reading from a federated file.
I get the following error from the proxy:
Exeption:
```
Array
(
    [version] => 1.1
    [status] => 400
    [reason] => Bad Request
    [headers] => Array
        (
            [Server] => Array
                (
                    [0] => mitmproxy 4.0.4
                )

            [Connection] => Array
                (
                    [0] => close
                )

            [Content-Length] => Array
                (
                    [0] => 305
                )

            [Content-Type] => Array
                (
                    [0] => text/html
                )

        )

    [effective_url] => http://cloud.fed:10000/public.php/webdav/
    [body] => Resource id #106
)
```

Stack:
```
RequestFsm.php:131, GuzzleHttp\RequestFsm->GuzzleHttp\{closure}()
FulfilledPromise.php:25, React\Promise\FulfilledPromise->then()
CompletedFutureValue.php:55, GuzzleHttp\Ring\Future\CompletedFutureArray->then()
FutureResponse.php:43, GuzzleHttp\Message\FutureResponse::proxy()
RequestFsm.php:134, GuzzleHttp\RequestFsm->__invoke()
Client.php:165, GuzzleHttp\Client->send()
Client.php:125, GuzzleHttp\Client->get()
Client.php:136, OC\Http\Client\Client->get()
DAV.php:344, OCA\Files_Sharing\External\Storage->fopen()
Wrapper.php:295, OC\Files\Storage\Wrapper\Availability->fopen()
Availability.php:318, OC\Files\Storage\Wrapper\Availability->fopen()
Checksum.php:59, OC\Files\Storage\Wrapper\Checksum->fopen()
Wrapper.php:295, OCA\Files_Trashbin\Storage->fopen()
StorageWrapper.php:263, OCA\Workflow\Engine\Wrapper\StorageWrapper->fopen()
View.php:1184, OC\Files\View->basicOperation()
View.php:1029, OC\Files\View->fopen()
File.php:394, OCA\DAV\Connector\Sabre\File->get()
CorePlugin.php:90, Sabre\DAV\CorePlugin->httpGet()
WildcardEmitterTrait.php:96, OCA\DAV\Connector\Sabre\Server->emit()
Server.php:464, OCA\DAV\Connector\Sabre\Server->invokeMethod()
Server.php:241, OCA\DAV\Connector\Sabre\Server->start()
Server.php:309, OCA\DAV\Connector\Sabre\Server->exec()
Server.php:299, OCA\DAV\Server->exec()
remote.php:31, require_once()
remote.php:175, {main}()
```

2019-04-08 15:48 UTC, micbar commented
@PVince81 
Any Ideas? IMO the remaining issue is not an authentication issue, it has something to do with the kind of the DAV Get request for opening the file.

2019-04-23 16:11 UTC, micbar commented
@PVince81 As discussed, this can be merged. It fixes the proxy issue.

The remaining issue is the WebDAV GET Request to the external storage when opening the federated share file. The url format seems to be rejected by the proxy server (400 - bad request). It expects an absolute Url but gets a relative one

2019-04-25 07:20 UTC, mmattel commented
> Maybe we should leave it this way and document, that we need an encoded string in config.php
foo:B@r should look like foo:B%40r

There is no answer to my question raised (see above) if that should be documented in https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html#the-optional-authentication-for-the-proxy-to-use-to-connect-to-the-internet
Currently there is no mentioning...

Pls advice

2019-04-25 07:43 UTC, micbar commented
@mmattel It should be mentioned.

2019-04-25 08:36 UTC, mmattel commented
@micbar what is the procedure for an admin to create an encoded proxy password. pls keep in mind that an andmin is not a programmer...

2019-04-25 10:11 UTC, PVince81 commented
@micbar this is why I'd prefer we fix it right away ^

2019-04-25 10:14 UTC, micbar commented
> @micbar this is why I'd prefer we fix it right away ^

Sorry, i lost the track what should be fixed... :-)

2019-04-25 10:23 UTC, PVince81 commented
here we go:

- [ ] escape the proxy settings in code instead of documenting, ref https://github.com/owncloud/core/pull/34101#issuecomment-453939075

2019-04-25 10:25 UTC, micbar commented
> here we go:
> 
>     * [ ]  escape the proxy settings in code instead of documenting, ref [#34101 (comment)](https://github.com/owncloud/core/pull/34101#issuecomment-453939075)

Cool, thx

2019-05-06 13:26 UTC, patrickjahns commented
Late to the party - but a serious question I have asked myself:
- do we really need to have a second parameter and add complex logic to escaping things in code?

If `proxyuserpwd` is never used - we can just use the normal `proxy` parameter and define the full url in there. ( As this is anyway how it is internally done).

Example:
```
   'proxy' => 'https://username:password@proxy.tld:9999' 
```

Or with special characters:
```
   'proxy' => 'https://username:p%40assword@proxy.tld:9999' 
```

This is a common way of defining proxyurls - so we can adhere to it and have less code and less confusion? ( also not needing a bug fix but rather a documentation change)

2019-05-06 13:47 UTC, mmattel commented
@patrickjahns as far my understanding goes, more or less independent of which key used, the question is how to get the escaped passwd for an admin who is not a programmer... pls correct if my pov is wrong.

2019-05-06 13:55 UTC, micbar commented
@mmattel We cannot do that.

Imagine `'proxyuserpwd' => 'user:n@me:password'`

We would need to use a regex to extract the two values before we could encode them without the delimiter. This could fail hard, if the admin enters something, we could not anticipate.

2019-05-06 13:56 UTC, micbar commented
I made an addition to the config.sample.php

2019-05-06 13:57 UTC, micbar commented on config/config.sample.php
> + * Example: "usern@me" needs to be encoded as "usern%40ame"
We could just copy that to the docs.

2019-05-06 14:03 UTC, micbar commented
Thanks to @patrickjahns we found the config value used in other code paths. So we can not deprecate the setting and need to continue with this PR as suggested and extend the docs here.

```./core/lib/private/Http/Client/Client.php:		$proxyUserPwd = $this->config->getSystemValue('proxyuserpwd', null);
./core/lib/private/SystemConfig.php:		'proxyuserpwd' => true,
```

2019-05-06 14:07 UTC, patrickjahns commented
@mmattel 
> admin who is not a programmer... pls correct if my pov is wrong.

I honestly expect that a ownCloud administrator knows what url_encdode / url_decode is - if he does not know this - I expect this person to be capable to use a common search engine with the description to find a resolution for how to url_encode/decode. In the worst case scenario, the documentation could include a short snippet how to url encode/decode the password. 

Having a proxy to reach the internet is not a common scenario on average hosting providers - you usually find this scenario in corporate networks as they want to scan incoming/outgoing traffic. I believe an administrator in an enterprise is able to find a person that can tell them about url encode/decode

2019-05-15 21:27 UTC, micbar commented
@patrickjahns @PVince81 
Current WIP seems to work. I also tested an urlencoded username.

## What I did
- Check if we do a get() on a stream resource
- Modify the stream context to use only `tcp://proxyhost`
- Move the Authorization in the Stream Context to the Header `Proxy-Authorization: Basic $auth` and `base64_encode(urldecode($auth))`

IMO the other get() requests without stream context can use `user:pw@proxyhost`

2019-05-16 07:38 UTC, patrickjahns commented on lib/private/Http/Client/Client.php
> +		if ($options['stream']) {
Should this only be set if proxy is `$this->config->getSystemValue('proxy', null) !== null` ? 
Or is it fine to set proxy to `tcp://null` and the underlying code works as expected?

2019-05-16 08:08 UTC, micbar commented on lib/private/Http/Client/Client.php
> +		if ($options['stream']) {
good point. Let us add it to the if clause

2019-05-16 13:54 UTC, micbar commented on config/config.sample.php
> + * Example: "usern@me" needs to be encoded as "usern%40ame"
@mmattel @settermjd

2019-05-17 12:26 UTC, micbar commented
@cdamken 
Could we schedule a manual testing with @pako81 or @voroyam ?
I think this pr could have quite an impact on External WebDaV Storage.

2019-05-17 13:34 UTC, patrickjahns commented on lib/private/Files/Storage/DAV.php
> +												'request_fulluri' => true
does it make sense to always use this, or only in a proxy scenario?

2019-05-17 13:36 UTC, micbar commented on lib/private/Files/Storage/DAV.php
> +												'request_fulluri' => true
That is a good question my dear :-)

2019-05-17 13:37 UTC, micbar commented on lib/private/Files/Storage/DAV.php
> +												'request_fulluri' => true
What could go wrong? Why use relative paths to a webDav Resource anyway?

2019-05-17 13:38 UTC, patrickjahns commented on lib/private/Http/Client/Client.php
> +			if ($proxyHost !== null) {
should we match the `empty()` call from the check below.
I guess it's a matter of preference - do we allow the user to do something like this in config.php
```
'proxy' => '',
```

2019-05-17 13:39 UTC, patrickjahns commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
please remove this change

2019-05-17 13:40 UTC, micbar commented on .htaccess
> +ErrorDocument 404 /core/templates/404.php
oh, it slipped in accidentally.

2019-05-17 13:41 UTC, micbar commented on lib/private/Http/Client/Client.php
> +			if ($proxyHost !== null) {
👍

2019-05-17 13:43 UTC, patrickjahns commented
@micbar 
Currently you only put this change to `get` to fix a specific scenario

What about moving that change into `setDefaultOptions()` - other request might also fail if the response is streamed

2019-05-17 13:45 UTC, micbar commented
> @micbar
> Currently you only put this change to `get` to fix a specific scenario
> 
> What about moving that change into `setDefaultOptions()` - other request might also fail if the response is streamed

I had this in mind too. I was looking around for another use of fopen() in the DAV External Storage implementation. Found none.

2019-05-17 13:46 UTC, patrickjahns commented
If we widen the spectrum to include all options, I wonder if we can easily setup acceptance scenarios with having a proxy inbetween. 
It should be possible to have a mitmproxy in a container. And then we run the acceptance scenarios for a federation/webdav etc with the proxy in-between.

Just not sure about the effort - might need to talk to @owncloud/qa

2019-05-17 13:50 UTC, patrickjahns commented
> I had this in mind too. I was looking around for another use of fopen() in the DAV External Storage implementation. Found none.

Need to double check - but this is not only DAV related - that's ownClouds default http client. So any request using the client would run into the issue

2019-05-20 07:02 UTC, individual-it commented
@patrickjahns created a new issue for that https://github.com/owncloud/core/issues/35263

2019-05-22 09:58 UTC, micbar commented
@individual-it @DeepDiver1975 
I tested it with a proxy and proxy auth
1) Establish fed share in both ways
2) Access the fed share
3) Connect an external Storage WebDAV
The external storage WebDAV refuses to create files or folders, but lists and reads files, except pdf

2019-06-19 12:58 UTC, skshetry commented
#35325 runs with this patch on passthrough proxy. Tests currently pass. I also ran through proxy without this patch on #35322, which fails. So, this demonstrates that the patch solves the issue. 

cc @micbar

2019-07-01 10:16 UTC, micbar commented
@DeepDiver1975 Could you review? I am not able to fully qualify the impact on external storages. See my comment about WebDAV External Storage.

2019-07-15 17:46 UTC, VicDeo requested changes

2019-07-15 17:46 UTC, VicDeo commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyHost)) {
` $proxyHost === null` ?

2019-07-15 17:46 UTC, VicDeo commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyUserPwd)) {
the same as above

2019-07-15 18:00 UTC, micbar commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyHost)) {
What if somebody enters `'proxy'=> ''` ?

2019-07-15 18:01 UTC, micbar commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyUserPwd)) {
same as above...

2019-07-15 18:03 UTC, VicDeo commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyHost)) {
and what if somebody enters `'proxyUserPwd' => '0'`? :)

2019-07-15 18:41 UTC, micbar commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyHost)) {
ok. :-)

2019-07-15 18:47 UTC, micbar commented on lib/private/Http/Client/Client.php
> +			if (!empty($proxyUserPwd)) {
ok

2019-07-16 12:45 UTC, VicDeo approved these changes
Good to go

2019-07-16 12:46 UTC, merged

2019-07-16 13:06 UTC, VicDeo commented
@micbar  backport?

2019-07-18 03:39 UTC, phil-davis commented
Backport `stable10` #35868