add before-after share link auth events
owncloud/core pull request #34158
Opened 2019-01-16 11:22 UTC by karakayasemi

## Description
Adds before and after events for public share link auths.

## Related Issue
The first step for:
#33542, https://github.com/owncloud/brute_force_protection/issues/57

## Motivation and Context
To be able to detect and interrupt public link share auth attempts.

## How Has This Been Tested?
Unit test and manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

I am not sure about the location of the events. As far as I see, adding events in `linkShareAuth` function is enough. But, if you see any missing place, please let me know. 

When this pr merged, I will update here: https://github.com/owncloud/docs/issues/311#issuecomment-419377043

2019-01-20 02:19 UTC, phil-davis commented
Unrelated drone CI fail. I restarted drone, and raised issue #34186 to look into why this is happening too often.

2019-01-20 12:47 UTC, karakayasemi commented
@phil-davis it failed again. I tried to restart the build one more time with drone.io's API, but I could not. Have you any suggestion to make CI green.

2019-01-20 14:09 UTC, phil-davis commented
@ownclouders rebase

2019-01-20 14:09 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-01-20 14:10 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-01-20 14:13 UTC, phil-davis commented
I restart the drone build and it failed again. But I made a fresh PR #34187 (not this code) just to check the drone CI - that passed first time.

Either this code really does make some difference to the test, or something goes wrong because the failing scenarios were only recently merged to master and this PR is a few days old. I tried a rebase, maybe that will help??? But I see that you force-pushed only 1 day ago.

2019-01-20 14:19 UTC, karakayasemi commented
I forced pushed to re-trigger ci with only changing commit message. I hope rebase will work.

2019-02-04 13:40 UTC, sharidas requested changes
Kindly have a look at my comment.

2019-02-04 13:40 UTC, sharidas commented on apps/files_sharing/tests/Controllers/ShareControllerTest.php
> +		$this->eventDispatcher->addListener(
Is there a way to mock `eventDispatcher->dispatch()` and check the args called, this might reduce the code added here. to verify if the before or after is called or not. 
@karakayasemi can you please have a look.
On a side note, I do agree there are places where I have written similar test code. May be one day we have to update them too ( if possible )

2019-02-06 16:02 UTC, karakayasemi commented
The event dispatcher injected to ShareController class as a non-mock object in here:
https://github.com/owncloud/core/blob/4fe6d6f7760414989ad70aa2cea2b14d7de70d57/apps/files_sharing/tests/Controllers/ShareControllerTest.php#L87

I can inject a mock EventDispatcher object and update my tests, but there are other events which are not related to this PR in this class. I should refactor their tests also. 

@sharidas both of the cases fine for me. What do you think?

2019-02-06 16:09 UTC, sharidas commented
> @sharidas both of the cases fine for me. What do you think?

Humm there are more calls to `addListener()` . Well just leave it then. At least we can make sure for the new test files we can mock the EventDispatcherInterface and use it in our tests.

2019-02-06 16:09 UTC, sharidas approved these changes
Looks fine to me :+1:

2019-02-07 08:16 UTC, merged

2019-02-07 08:17 UTC, PVince81 commented
@karakayasemi please backport to stable10

2019-03-09 06:49 UTC, phil-davis commented
Backport `stable10` #34399