add public link remove accpetance test
owncloud/core pull request #34215
Opened 2019-01-22 10:43 UTC by iamsauravsharma

## Description
this PR adds webUI test for removing public link of shared file

## How Has This Been Tested?

locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [X] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [X] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-22 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=34215) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=34215) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=34215) it.</sub>

2019-01-22 14:20 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			$ocDialog = \end($ocDialogs);
These two lines could just be outside conditional check.

2019-01-22 14:22 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	public function removePublicLink(Session $session, $cancel = null) {
Why not have two separate interface for cancelling/confirming? Or, even multiple steps (not `feature steps`)?

2019-01-22 14:24 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +		$publicLinkRemoveBtn->click();
Doesn't need `wait` in here? Is it handled by `ocDialog` or is not needed for this?

2019-01-23 01:48 UTC, skshetry commented
@phil-davis Random test failure?
```
    Then as user "user1" folder "/merge-test-outside-groups-renamebeforesecondshare-renamed" should contain a property "oc:permissions" with value "SRDNVCK"                # WebDavPropertiesContext::asUserFolderShouldContainAPropertyWithValue()
      Cannot find property "oc:permissions"
      Failed asserting that false is true.
```

@dpakach Two test failed on step:
```
    And the user sets the sharing permissions of "user2@%local_server%/ (federated)" for "simple-folder (2)" using the webUI to   # WebUISharingContext::theUserSetsTheSharingPermissionsOfForOnTheWebUI()
      | edit | no |
      SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException: Page\FilesPageElement\SharingDialog::setSharingPermissions xpath .//*[@id='shareWithList']//*[@class='has-tooltip username' and .='user2@https://server/ (federated)']/.. could not find share permissions field for user user2@https://server/ (federated) in /drone/src/tests/acceptance/features/lib/OwncloudPage.php:821
```

2019-01-23 01:49 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-01-23 01:49 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-01-23 01:50 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-01-23 01:50 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-01-23 02:11 UTC, phil-davis commented
@skshetry that new test scenario is failing a bit - I saw 2 of them yesterday.

2019-01-23 05:39 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	public function removePublicLink(Session $session, $cancel = null) {
Should not the default be `false`? 
```suggestion
	public function removePublicLink(Session $session, $cancel = false) {
```

2019-01-23 05:56 UTC, skshetry commented on tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
> +    When the user cancel the remove operation of file "lorem.txt" using webUI
```suggestion
    When the user cancels the remove operation of file "lorem.txt" using webUI
```

2019-01-23 06:10 UTC, dpakach requested changes

2019-01-23 06:10 UTC, dpakach commented on tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
> +    And the content of the file shared by the last public link should be the same as "lorem.txt"
```suggestion
    Then the content of the file shared by the last public link should be the same as "lorem.txt"
```

2019-01-23 08:18 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
> +    When the user cancels the remove operation of file "lorem.txt" using webUI
```suggestion
    When the user tries to remove the public link of file "lorem.txt" but later cancels the remove dialog using webUI
```

2019-01-23 08:22 UTC, paurakhsharma commented
DRY your code, copy repeating steps from `removePublicLink` and `cancelRemovePublicLinkOperation` and make a new function which you call from these functions.

2019-01-23 10:34 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	private function clickRemoveBtn(Session $session) {
I'd love if this name was declarative instead of being imperative. That said, I don't have any suggestion (naming things are hard). But, if you have any good name, it'd be better to rename this.

2019-01-24 09:28 UTC, dpakach submitted a review, later dismissed

2019-01-24 09:55 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	private function clickRemoveBtn(Session $session) {
I think in this case its ok, its only an internal function

2019-01-24 09:57 UTC, individual-it approved these changes

2019-01-24 09:58 UTC, merged

2019-01-24 10:42 UTC, iamsauravsharma commented
Backport on:  #34247