Web UI test for multiple public link creation and removal of certain
owncloud/core pull request #34246
Opened 2019-01-24 10:16 UTC by bishalrijal

creates multiple public link and remove certain public link acceptance test

Co-authored-by: Saurav Sharma <appdroiddeveloper@gmail.com>

## How Has This Been Tested?
locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [X] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [X] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-24 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=34246) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=34246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=34246) it.</sub>

2019-01-24 10:32 UTC, phil-davis commented
@bishalrijal please click the buttons to sign the CLA

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then the public link with name :entryName should not be in public links list
s/should not be in public links list/should not be in the public links list

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			"could not find public link remove button"
s/button/buttons/

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +		$publicLinkRemoveBtn = $publicLinkRemoveBtns[$number - 1];
The next line overwrites this variable???

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	public function checkIfNameIsInList(Session $session, $entryName) {
I was confused when reading this method. It throws an exception if the name is in the list.
Maybe rename the method to ``checkThatNameIsNotInPublicLinkList``

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			throw new \Exception("Count is not equal to expected value");
The message could be more informative, so when it fails we do not have to guess which way the count was wrong.
e.g.
```
$publicLinkTitlesCount = \count($publicLinkTitles);
if ($publicLinkTitlesCount != $count) {
    throw new \Exception("Found $publicLinkTitlesCount public link entries but expected $count");
}
```

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	public function checkCount(Session $session, $count) {
make the method name more informative, e.g. ``checkPublicLinkCount``

2019-01-24 11:37 UTC, phil-davis commented on tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
> +  Scenario: user create a multiple public link of a file and delete the first link
user creates multiple public links of a file and deletes the first link

2019-01-24 11:53 UTC, phil-davis commented
See https://drone.owncloud.com/owncloud/core/14559/74 for code style fail.
Do:
```
make test-php-style
```
locally and get it passing.

2019-01-25 08:34 UTC, individual-it requested changes
small comments
please add more tests deleting second and third link and check if correct one is deleted

2019-01-25 08:34 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function theUserRemovesTheFirstPublicLinkOfFileUsingTheWebui($number, $entryName) {
first?

2019-01-25 08:34 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +		$this->assertElementNotNull(
no need for `assertElementNotNull` because `findAll` never returns `null`

2019-01-25 08:34 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +		$this->assertElementNotNull(
see comment above

2019-01-25 08:55 UTC, individual-it approved these changes
please squash and then we can merge
also please backport

2019-01-25 13:55 UTC, individual-it commented
@ownclouders rebase

2019-01-25 13:55 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-01-25 13:56 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-01-25 15:09 UTC, merged