Fix the share permissions evaluation
owncloud/core pull request #34250
Opened 2019-01-24 14:24 UTC by sharidas

When user tries to access "Shared with you"
to know the list of files/folders shared with
the user, the share tab for the files or folder
are having an issue. When the group(s) to which
the user belong is excluded from sharing, the
share options appear in the tab. This change
tries to fix the issue.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Enable guest user,  block the guest group ( `guest_app`) by selecting the check box `Exclude groups from sharing` and add the guest group name. Now login as guest user and navigate to the `Shared with you` and then select the share tab. The share tab should not be visible `Sharing not allowed` message should be seen. This is seen when user navigates from `All files` and then selects the file/folder sharing section. Where as guest user is able to share the file or folder even though the guest group is blocked. This issue tries to address the resharing not working as expected. 

As per the investigation the `permission` which is set to `31` for the file/folder in this scenario. And hence in the parse method in shareitemmode.js, the permissions is not evaluated properly. Which was resulting in permissions set to `31`, and hence the guest user was able to reshare the file/folder. In this PR, the server does check if the current user falls under the group which is blocked or not. If so the assign permissions read only mode.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

This PR tries to check if the user falls under the group which is blocked to reshare. If the user falls under the blocked user, then permissions are set to read only mode.

## How Has This Been Tested?

- As admin user enable the guest user.
- As admin user navigate to admin->Settings->Sharing and check `Exclude groups from sharing`. Add the guest group ( select it from the drop down )
- Now login as guest user.
- Navigate to `All files` and select the file/folder. The share tab should be invisible
- Navigate to `Shared with you` and select the file/folder. The share tab should be invisible.
- Create a user as admin
- As admin share a file/folder to the new user.
- Login as new user.
- The share tab should be visible in `All files` and `Shared with you`.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-25 10:21 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> -    And user "user1" should not be able to share file "testimage (2).jpg" with user "User Three" using the sharing API
This line could be put back in at the end of the scenario.
It checks that, regardless of what happens in the webUI, "user1" really cannot go "underneath" and use the sharing API to share the file.

2019-01-25 10:21 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
>      And the share-with field should not be visible in the details panel
The double-check about not being able to share has been missed from this scenario. You could add it in this PR:
```
And user "user1" should not be able to share file "testimage.jpg" with user "User Three" using the sharing API
```
(see my other comment below - it is nice to check some API also when checking something that should be blocked, because it is easy for the webUI to seem to block something, but there is a way to "hack" it behind the webUI)

2019-01-25 12:06 UTC, sharidas commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
>      And the share-with field should not be visible in the details panel
I have updated the PR by adding :
```
And user "user1" should not be able to share file "testimage.jpg" with user "User Three" using the sharing API
```
@phil-davis  let me know if this ok.

2019-01-25 12:34 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
>      And the share-with field should not be visible in the details panel
That line can be added to this scenario, (as well as the one below)

2019-01-25 12:35 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And user "user1" should not be able to share file "testimage.jpg" with user "User Three" using the sharing API
s/testimage.jpg/testimage (2).jpg/
The received shared file in this scenario gets the name ``testimage (2).jpg``

2019-01-25 12:36 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> -    And user "user1" should not be able to share file "testimage (2).jpg" with user "User Three" using the sharing API
Line has been added. I made a new comment on the added line.

2019-01-25 13:50 UTC, sharidas commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And user "user1" should not be able to share file "testimage.jpg" with user "User Three" using the sharing API
@phil-davis  I have updated with `testimage (2).jpg`.

2019-01-25 14:30 UTC, phil-davis reviewed
Acceptance test looks good.
@PVince81 for actual code review

2019-02-01 06:24 UTC, PVince81 requested changes

2019-02-12 12:42 UTC, sharidas commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +							$share->setPermissions(\OCP\Constants::PERMISSION_READ);
Aah it took a while to get the pitch, what is the "share" bit. I have updated the PR with the change set. Took a few references how the it is calculated to 15. I after this change, i was able to create another folder inside the guest folder.

2019-02-12 12:45 UTC, sharidas commented
@PVince81 I have updated the PR. Let me know if this is the pointer shared by you in the comment.

2019-02-12 13:28 UTC, PVince81 approved these changes
Thanks for the nice explanation in the OP.
Understood and change makes sense :+1:

2019-02-13 07:50 UTC, sharidas commented
Backport to stable10 https://github.com/owncloud/core/pull/34473

2019-02-14 06:19 UTC, sharidas commented
@PVince81 I am merging this PR, because the backport of this PR is merged.

2019-02-14 06:19 UTC, merged