Share file with other user and delete shared with users
owncloud/core pull request #34317
Opened 2019-01-30 08:22 UTC by bishalrijal

## Description
Test for deleting shared with user using webUI 

## How Has This Been Tested?
locally 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [X] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [X] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-01-30 08:39 UTC, dpakach requested changes

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    When the user delete share with user "User Two"
Delete share for which file? It is not clear. 
I think it should be 
`
    When the user delete share with user "User Two" for the current file
`

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    When the user delete share with user "User Two"
Same goes for the next step

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	 * check if user with the given username is present
```suggestion
	 * check if user with the given username is present in the shared with list
```

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +		$this->waitForAjaxCallsToStartAndFinish($session);
Is this required here?

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +				$userOrGroup->find('xpath', "//a[contains(@class,'unshare')]")->click();
Do not use xpath here. make a variable.

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$this->sharingDialog = $this->filesPage->openSharingDialog("lorem.txt", $this->getSession());
Why does it use explicit file name (i.e. "lorem.txt")?
Can we not do for other files?

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		if ($this->sharingDialog->isUserPresentInShareWithList($this->getSession(), $username)) {
Use assertion here from PHPUnitFramework

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$this->sharedWithOthersPage->isEmpty();
There might be still other files in the `SharedWithOthersPage`

2019-01-30 08:39 UTC, dpakach commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +				$userOrGroup->find('xpath', "//a[contains(@class,'unshare')]")->click();
Also make sure to wait for any ajax calls

2019-01-30 08:42 UTC, dpakach submitted a review, later dismissed

2019-01-30 08:42 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	private $userAndGroupsTab;
I dont think this variable is used anywhere.

2019-01-30 08:42 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And the file "lorem.txt" should not be in share with other list
```suggestion
    And the file "lorem.txt" should not be in shared with other list
```

2019-01-30 08:45 UTC, dpakach commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +	 * get the list of shared with list
```suggestion
	 * get the list of shared with users
```

2019-01-31 09:41 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And file "lorem.txt" should not be listed in shared-with-others page on the webUI
Maybe you can also add `And as "user2" file "lorem (2).txt" should not exist`

2019-02-01 10:06 UTC, individual-it commented
@ownclouders rebase

2019-02-01 10:06 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-02-01 10:08 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-02-01 10:11 UTC, skshetry reviewed
Looks good to me. I'll add phil-davis and individual-it to the reviewers list.

@paurakhsharma please review again
@dpakach please review and discard your earlier request for changes.

2019-02-01 10:25 UTC, individual-it approved these changes

2019-02-01 11:03 UTC, individual-it commented
not part of the sprint, as its a project for trainees

2019-02-01 11:19 UTC, merged