allow user to configure automatically accept incoming shares
owncloud/core pull request #34593
Opened 2019-02-22 13:22 UTC by karakayasemi

## Description
Let the users decide whether they want to manually accept shares or not. FR, part of the product roadmap. 

## Related Issue
>
- Fixes `files_sharing` part of https://github.com/owncloud/enterprise/issues/3128 . There will be another PR for `federatedfilesharing`

## Motivation and Context
some users will not want that shares are accepted automatically.

## How Has This Been Tested?
Unit tests are added. Manually tested.
- When global `auto_accept_share` enabled, go Sharing Personal Panel and disable `auto accept share`, the next share should be on the pending status.
- When global `auto_accept_share` enabled, go Sharing Personal Panel and enable`auto accept share`, the next share should be accepted automatically.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-02-25 12:40 UTC, jvillafanez commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/personalsettings/setautoaccept',
I'm pretty sure this won't be the last sharing thing we'll want the user to choose, and I'm also pretty sure that most of the future configuration options for the user will end up in the same place.
Try something more generic that can be reused in the future.

2019-02-25 12:40 UTC, jvillafanez commented on apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
> +			$this->config->getUserValue(
Better move this at the beginning of the function. The `assign` function feels quite bloated because you usually write it like `$tmpl->assign('myvar', $myvar)`

2019-02-25 12:42 UTC, PVince81 requested changes
looks fine, see comments for some small additions

2019-02-25 12:42 UTC, PVince81 commented on apps/files_sharing/js/settings-personal.js
> +			OC.generateUrl('apps/files_sharing//personalsettings/setautoaccept'), {state: value}
double slash ?

2019-02-25 12:42 UTC, PVince81 commented on apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
> +	 * @since 10.0
`@since` not needed as this is no public API, same below

2019-02-25 12:42 UTC, PVince81 commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		$this->config->setUserValue(
please validate the state and don't accept arbitrary values.

a unit test should confirm that validation works

2019-02-25 19:23 UTC, karakayasemi commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/personalsettings/setautoaccept',
@jvillafanez Are you suggesting to change the path as something like `setconfig` and use this endpoint for all the future configuration options? In this way, every input change leads to set all configuration options. I thought the future options can implement their own endpoint under `/personalsettings/`  URL path.

2019-02-25 19:25 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		$this->config->setUserValue(
done

2019-02-25 19:27 UTC, karakayasemi commented on apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
> +			$this->config->getUserValue(
done

2019-02-26 15:28 UTC, jvillafanez commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/personalsettings/setautoaccept',
> Are you suggesting to change the path as something like `setconfig` and use this endpoint for all the future configuration options

That's the idea. 90% of the options will follow the same code path, which means that each time we need to add a new option we don't need to test everything (there shouldn't be code changes there, and it should also be tested already), and the code changes required to add a new option are minimal.
As long as the input and output of the endpoint are clear, I don't see many problems: you know what you can expect. For special cases, we'll need to add additional code anyway, so for me, it's a matter of how many special cases do we expect to handle.

2019-02-26 20:07 UTC, karakayasemi commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/personalsettings/setautoaccept',
@jvillafanez I added allowed user config keys constant array in settings to validate coming params and converted `setUserConfig` method to a more generic one. Please review, one more time. Thanks.

2019-02-27 10:15 UTC, jvillafanez commented on apps/files_sharing/js/settings-personal.js
> +		var post = $('#files_sharing_settings').find('input:checkbox').map(function() {
Include a comment here to explain what you want to do. It's a bit difficult to follow.

2019-02-27 10:15 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		return new DataResponse(
We should adjust this reponse. The problem I see is that I can send several key-value pairs but only a couple of them will be saved. The response seems to tell that all the key-value pairs were saved correctly.

I think we can send a 4xx response if all the keys were rejected, and a 2xx response if any of them was saved, but in this case we can send the key-value pairs that were rejected and saved as part of the body, so the client can check if there was any key that wasn't saved

2019-02-27 10:15 UTC, jvillafanez commented on apps/files_sharing/js/settings-personal.js
> +	userConfig.find('input[type=checkbox]').change(saveSettings);
Note that the handler will be attached to all the checkboxs in the section. This means that when you change a checkbox you'll be sending the information of all the checkboxes found.
I'd just send only the information of the changed checkbox. I don't think we want a button to save all the settings.

2019-02-27 10:15 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		return new DataResponse(
If the function will save only one setting at a time, return the proper error response if it couldn't be saved.

2019-02-27 18:31 UTC, karakayasemi commented on apps/files_sharing/js/settings-personal.js
> +	userConfig.find('input[type=checkbox]').change(saveSettings);
now it only sends changed checkbox value.

2019-02-27 18:33 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		return new DataResponse(
Now it will only take a config key-value pair and if cant set the value, it will return a response with Http::STATUS_BAD_REQUEST.

2019-02-27 18:34 UTC, karakayasemi commented on apps/files_sharing/js/settings-personal.js
> +	userConfig.find('input[type=checkbox]').change(saveSettings);
It will listen to all the checkbox changes but only send related checkbox change.

2019-02-27 18:35 UTC, karakayasemi commented on apps/files_sharing/js/settings-personal.js
> +		var post = $('#files_sharing_settings').find('input:checkbox').map(function() {
removed.

2019-02-27 18:38 UTC, karakayasemi commented
@jvillafanez I believe this time the code is sufficient for all the discussed requirements. Please, review one more time. Thanks.

2019-02-28 08:19 UTC, jvillafanez commented
It would be better if the calls are something like `/personalsettings/setuserconfig?mykey=myvalue&myotherkey=myothervalue` (don't mind the "GET-like" request).

In the controller you should be able to do something like (make sure the request is accesible):
```
$requestParams = $this->request->getParams();
foreach ($requesParams as $key => $value) {
  if (isKeyValid($key)) {
    save($key, $value);
  }
}
```
The client can send the data like (double-check the syntax), classic key-value pairs:
```
var item = $(this);
$.post(url, {
  item.attr('name'): item.is(":checked") ? "yes" : "no"
});
```

From a client perspective, I think this makes more sense.

Note that, although the server can accept several key-value pairs at the same time, the client will only send them one by one (at least for now). This is fine.

2019-02-28 08:32 UTC, karakayasemi commented
Sorry, but I don't quite understand the benefit of using "GET" instead of "POST". I can already use `$request->getParams()` with the "POST" request. But, there are unrelated entries in params like `_route`. To get rid of this and to make sure there was only a config parameter, I preferred to write in this way.

2019-02-28 09:06 UTC, jvillafanez commented
> Sorry, but I don't quite understand the benefit of using "GET" instead of "POST"

Forget this and keep using POST. It was just an example.

> there are unrelated entries in params like `_route`

You're still validating that the keys we want to set are known, so we can just include a comment to be warned about additional keys not fully related to the request. You can also skip all the keys starting with underscore.

> to make sure there was only a config parameter, I preferred to write in this way.

As far as I know, this is self-imposed. I don't mind as long as it makes sense, although I prefer a flexible server and let the client do what it wants
The problem I see is that the requests don't look "natural". If you want to save a key-value pair, you normally want to send something like "key=value", or something along those lines ({key: value} for json, etc).

2019-02-28 11:19 UTC, karakayasemi commented
@jvillafanez Now, the controller is accepting both single and multiple inputs and responding with accepted-rejected keys in the body. If it can not set at least one key, it is returning `HTTP::Status_Bad_Request`.  I need your review one more time. Thanks.

2019-02-28 13:22 UTC, jvillafanez reviewed
last touches and we're good to go

2019-02-28 13:22 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +				\array_push($acceptedKeys, $key);
`$acceptedKeys[] = $key` should perform faster, unless you push several items, which isn't the case.

2019-02-28 13:22 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +			if ($this->validateKey($key) && ($value === 'yes' || $value === 'no')) {
I don't see much value in the `validateKey` function. If it won't have more checks, it's better to use just the wrapped function (the `inArray`). Or is there any plan to improve / increase the validation there?

2019-02-28 13:22 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +	 * @param array $config
Adjust docs

2019-02-28 13:22 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +				return (\substr($key, 0, 1) !== '_');
`strpos($key, '_') === 0` should perform faster according to https://stackoverflow.com/a/1962244 (we could use `$key[0] === '_'` but we need another check to verify the string isn't empty, so it might not be faster)

2019-02-28 13:51 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +	 * @param array $config
adjusted

2019-02-28 13:53 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +			if ($this->validateKey($key) && ($value === 'yes' || $value === 'no')) {
I changed the function to validate key-value pair. IMHO, it is improving readability and we can add specific controls to this function when validating future key-values.

2019-02-28 13:54 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +				return (\substr($key, 0, 1) !== '_');
I don't think that's right for our case. 
- `strpos` should iterate over all string to determine a non-existing character's position. Its worst-case time-complexity should be the length of string O(N). 
-  substr complexity should be the length of substring O(k), which is 1 for our case O(1).  I think substr should work faster here. 
Anyway, IMHO time performance is not a big deal for our function. Nothing changes in readability, I left it the same way.

2019-02-28 14:16 UTC, jvillafanez approved these changes

2019-02-28 14:27 UTC, PVince81 commented on apps/files_sharing/lib/Controller/PersonalSettingsController.php
> +		'auto_accept_share'
a bit over-engineering for just a single key...

2019-02-28 14:29 UTC, PVince81 approved these changes
:+1: I'll accept this for now so we don't invest any more time

2019-02-28 14:29 UTC, merged

2019-02-28 14:29 UTC, PVince81 commented
@karakayasemi please backport

2019-03-09 07:00 UTC, phil-davis commented
Backport `stable10` #34647