Provide common make files
owncloud/core pull request #34660
Opened 2019-03-04 03:18 UTC by phil-davis

## Description
Provide various `*.mk` files in core that can be included by app `Makefile` so that chunks of `make` code do not have to be repeated in every app.

## Related Issue
https://github.com/owncloud/QA/issues/604

## Motivation and Context

## How Has This Been Tested?
Local runs of JS unit, PHP unit and acceptance tests from various app repos.
PoC drone CI runs from activity, password_policy and... apps.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-03-04 05:56 UTC, phil-davis commented on build/rules/dist.mk
> +	doc_files=README.md CHANGELOG.md
Should `CONTRIBUTING.md` be in this `doc_files` list. Most app repos have one, and it is easy enough to add one. For private repos it can say something different, because the private repo won't be publicly visible to contribute to :)

2019-03-04 06:41 UTC, phil-davis commented
Questions:

- [ ] what to put in the default `doc_files` list?
- [ ] what to put in the default `src_files` list?
- [ ] what to do about `app:check-code` ? put it in a common `test-app-check-code.mk` in core? or just leave that block in the `Makefile` of apps that happen to have it? or remove it everywhere? or?

2019-03-05 09:34 UTC, individual-it commented on build/rules/dist.mk
> +	doc_files=README.md CHANGELOG.md
I would vote to add `CONTRIBUTING.md` and `LICENSE`

2019-03-05 09:39 UTC, PVince81 commented on build/rules/clean.mk
> +clean-deps: ## Clean all dependencies
I think the clean rules need to be part of each module

the dist rules module has clean-dist, the npm deps has clean-npm-deps, etc

you can use a generic variable to which every module can add their clean rules to the main "clean" target.
see https://github.com/owncloud/customgroups/blob/master/Makefile#L25 and https://github.com/owncloud/customgroups/blob/master/rules/deps.mk#L16

2019-03-05 09:39 UTC, individual-it commented
don't think we need `test-all.mk`

2019-03-05 09:42 UTC, PVince81 commented
there is one drawback with this: app builds will now depend on the core git checkout that was used.

which means that if we fix makefile rules in core we might need to do another release of apps.

we'll need to settle on a single OC version when buildling apps then, we could say it always needs to be from the git checkout of the latest stable release.

note that we had an internal POC from @patrickjahns where we build apps using a docker based on the OC-10.0.10 release. this approach would not work any more because the release tarball does not contain the makefile rules.

might need a different approach then, like putting the makefile rules in a common repo like the coding standards one ?

2019-03-05 09:45 UTC, PVince81 commented on build/rules/vendor-bin.mk
> +clean_deps_rules+=clean-vendor clean-vendor-bin
ah, you aready have this

2019-03-05 09:56 UTC, PVince81 commented
ideas for later: a rules file with checkers.

as this will be used by apps, we can check that many things are already properly in place in the dist tarball, like info.xml, changelog.md exists, etc

2019-03-05 11:16 UTC, phil-davis commented on build/rules/dist.mk
> +	doc_files=CHANGELOG.md CONTRIBUTING.md LICENSE README.md
Some app repos have `LICENSE.md` others have just `LICENSE`

Do we set a standard? Or do I write some more fancy code that sucks in whichever file exists?

2019-03-05 12:52 UTC, phil-davis commented on build/rules/dist.mk
> +	doc_files=README.md CHANGELOG.md
Now it adds `CONTRIBUTING.md` `LICENSE` and/or `LICENSE.md` only if they exist.
That makes it flexible and we do not have to force a decision here to always require these in every repo.

2019-03-05 12:54 UTC, phil-davis commented on build/rules/dist.mk
> +	doc_files=CHANGELOG.md CONTRIBUTING.md LICENSE README.md
I made it flexible so it adds whichever file exists.

2019-03-05 13:00 UTC, phil-davis commented
> which means that if we fix makefile rules in core we might need to do another release of apps.

> we'll need to settle on a single OC version when buildling apps then, we could say it always needs to be from the git checkout of the latest stable release.

If the problem caused an app tarball to be released with missing/wrong stuff, then fir sure the app has to be released again. But that is already the case if there is a problem in the local `Makefile`

The default "recommended" action when making an app release tarball would be to have the end of the current core release branch checked out, e.g. core `stable10`. That way you get the included `*.mk` as they were at the last core release, plus any recent fixes that will end up in the next release tag. But also in most cases core `master` will have exactly the same `*.mk` as core `stable10` so it will not make a real difference.

2019-03-05 13:12 UTC, phil-davis commented
@PVince81 IMO this now matches the "standard" `Makefile` code in the apps, and has flexibility to deal with finding various files. It can reduce the `Makefile` code duplication across the apps. 

If we find we need more flexibility, then it is easy to add `ifdef` etc conditional statements so that it continues to work for apps that use it, but can also handle some more unusual thing we find in "an app I haven't thought of yet".

Or if the app really is "weird", then it does not have to include all the `*.mk` files, and can continue to "do its thing its own way" until we really sort it out. I don't believe there are any apps like that.

If we some day want to migrate to putting this in a separate repo, or use some completely different build tool, then that will be possible and should be easier because we have this common set of knowledge about what build and test services are commonly used by apps.

Please review again.

2019-03-05 14:42 UTC, PVince81 commented
> If we some day want to migrate to putting this in a separate repo, or use some completely different build tool, then that will be possible and should be easier because we have this common set of knowledge about what build and test services are commonly used by apps.

Would be better to decide this right away. We're going to need to touch every app already for this change to make sense. If later on we introduce a common location, we'd need to touch all apps yet again.

2019-03-05 15:10 UTC, phil-davis commented
OK, so how do we decide?

2019-03-05 15:14 UTC, patrickjahns commented
Please do not make apps depend on core makefiles. 

If we are looking for a central part for makefiles, please put them in a dedicated repository to have clear separation of concerns. 
Core repository should be about ownCloud core and not about a build/makefile infrastructure for apps

2019-03-11 15:18 UTC, phil-davis commented
I removed the "To review" label. 
This PR is now a "demonstration" of the makefile targets that could be put somewhere common, and a way that those could be split into logical parts in `*.mk` files.
We need to research a good solution for where and how to store and retrieve this common build infrastructure - issue https://github.com/owncloud/QA/issues/604
And then perhaps be able to efficiently copy-paste some structure and code from here into the selected separate repo/tool/whatever.

2019-03-11 15:51 UTC, PVince81 requested changes
:-1: for now (to prevent accidental merge)

2019-07-20 03:01 UTC, phil-davis commented
Closing see comment https://github.com/owncloud/richdocuments/pull/253#issuecomment-513429624
There will be a different approach "some day"

2019-07-20 03:01 UTC, closed without merging