[stable10] User IUserSession in Share20OcsController ctor
owncloud/core pull request #34696
Opened 2019-03-06 09:38 UTC by phil-davis

Backport #34622

2019-03-07 12:53 UTC, DeepDiver1975 requested changes
ocsPUTAuth.feature seems to be missing - https://github.com/owncloud/core/pull/34622/files#diff-960259729d5ea049d7dccedc7accf2e9R14

2019-03-07 13:00 UTC, DeepDiver1975 commented
maybe we should backport https://github.com/owncloud/core/pull/33180 as well?

@pvince81

2019-03-07 13:01 UTC, phil-davis commented
> ocsPUTAuth.feature seems to be missing - https://github.com/owncloud/core/pull/34622/files#diff-960259729d5ea049d7dccedc7accf2e9R14

In `stable10` the test scenarios were already there and correct. When I back-ported there were no changes to make.
https://github.com/owncloud/core/blob/stable10/tests/acceptance/features/apiAuth/ocsPUTAuth.feature

2019-03-07 13:03 UTC, DeepDiver1975 commented
> maybe we should backport #33180 as well?

or remove these changes to https://github.com/owncloud/core/pull/34696/commits/aa9f637240da59d2db2c1c3174584139005f40af#diff-910e48efa188d7af32364e0de3db5a2b - they are not necessary because the IUser in ctor issue only allies to controllers ....

2019-03-07 13:03 UTC, phil-davis commented
The backport was not easy. So I have probably made some errors, or stuff needs to be implemented differently in `stable10`. I am waiting for drone to be functional again, and restart CI for this to see what it reports.

Or @DeepDiver1975 do you want to start from the beginning and do the cherry-pick backport yourself. Then you will see the conflicts and maybe resolve them much more easily than me.

2019-03-18 08:13 UTC, DeepDiver1975 commented
let's see how far we get: https://github.com/owncloud/core/pull/34786

2019-03-18 10:15 UTC, phil-davis commented
Closing in favor of PR #34786 - it sorts this out and passes CI

2019-03-18 10:15 UTC, closed without merging