Don't show reset link on missed LDAP login
owncloud/core pull request #34854
Opened 2019-03-20 13:32 UTC by micbar

## Description
Do not create a reset link for failed LDAP Logins

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/3220

## Motivation and Context
Some Instances have DB Users and LDAP Users in parallel. They want a working reset link for DB Users and don't show a reset link for LDAP users because they cannot be changed in OC. The current behaviour is misleading and could be considered as a bug

## How Has This Been Tested?
Manualle

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-03-27 11:56 UTC, jvillafanez commented
Check if setting the "canResetPassword" as false by default in https://github.com/owncloud/core/pull/34854/files#diff-5ab999f57c47dddcd9de7539846aeee3L139 works.

2019-04-08 08:16 UTC, micbar commented
@PVince81 
Could you provide feedback on this approach?
I could finish this too before code freeze

2019-04-08 08:27 UTC, PVince81 requested changes
:-1: no, this would also match partial user names. needs a different approach

2019-04-08 08:37 UTC, micbar commented
@PVince81 ok

We would need an mechanism to find users by
- Displayname
- UserID
- E-Mail
- all allowed LDAP Attributes from the Login Filter eg. CN, samaccountname, Distinguished name and so on

2019-04-08 08:38 UTC, PVince81 commented
@micbar the part I don't understand is that the PR title says it's removing something, the reset link, but the code seems to want to match more, which doesn't seem to fit with "removing".

as far as I understand, the match by email was there mostly for the local user backend, so we could also add a backend class name check maybe

2019-04-08 08:40 UTC, PVince81 commented
in general we advise people with LDAP setups to disable password reset by link completely by setting this value to "disabled": https://github.com/owncloud/core/blob/stable10/config/config.sample.php#L277

if that's not acceptable, this means that the use case in question is a setup with LDAP users mixed with local ones, maybe guests ?

2019-04-08 09:26 UTC, micbar commented
> @micbar the part I don't understand is that the PR title says it's removing something, the reset link, but the code seems to want to match more, which doesn't seem to fit with "removing".

@PVince81 The reset link does not show up, when the user backend returns false on the canChangePassword() method. If the correct UserBackend does not get determined, it will create the link anyway. This is a bug IMO

2019-04-08 09:27 UTC, micbar commented
> if that's not acceptable, this means that the use case in question is a setup with LDAP users mixed with local ones, maybe guests ?

The have a mixed seutp and want to keep the reset link for the DB users.

2019-04-08 10:23 UTC, PVince81 commented
wouldn't that be a security issue ?
this would let an attacker know what users exist in the system by finding the ones where the reset link isn't there.
in general I thought we'd let the user request a link anyway but in some cases we just don't send it out.

and maybe there for LDAP users, if they do click the link, the page should tell them that they need to contact admin for changing password or something. I wonder if that wouldn't be the better flow

2019-07-05 09:46 UTC, micbar commented
Originating Issue was closed.

2019-07-05 09:46 UTC, closed without merging