allow users to opt-out autocomplete in share dialog
owncloud/core pull request #34862
Opened 2019-03-21 15:01 UTC by karakayasemi

## Description
allow users to opt-out autocomplete in sharing dialog

- Also, I make easy to add a new config option to personal sharing panel.
## Related Issue
https://github.com/owncloud/enterprise/issues/3142

## Motivation and Context
some users do not want to be found via autocomplete

## How Has This Been Tested?
Manually tested by  applying the following steps:
- Create a user `test`
- Login with `admin`
- Enable `Allow username autocompletion in share dialog` checkbox within the sharing admin panel 
- Login with `test`
- Disable `Allow finding you via autocomplete in share dialog` from personal sharing panel with `test` user
- As an admin, search `tes` keyword in share dialog, `test` should not be listed
- Enable `Allow finding you via autocomplete in share dialog` from personal sharing panel with `test` user
- As an admin, search `tes` keyword in share dialog, `test` should be listed

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- x ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-03-29 10:54 UTC, karakayasemi commented
@jvillafanez you already reviewed similar things in auto-accept and I believe, you are familiar with code base of this PR. Your review in here can help me. Thanks.

2019-03-29 14:15 UTC, jvillafanez commented on apps/files_sharing/templates/settings-personal.php
> -			<input type="checkbox" name="auto_accept_share" id="userAutoAcceptShareInput" class="checkbox" value="1" checked="checked" />
double-check that these ids aren't being used by any code in js. Changing the id might break things.

2019-03-29 14:15 UTC, jvillafanez commented on apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
> +				$userEnabled = $this->config->getUserValue(
Could you check if writting the function in one line looks good? It seems there is quite a bunch of logic when it isn't true. Same for the `getAppValue` above.
No need to change anything if the line gets too long.

2019-03-29 14:15 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/ShareesController.php
> +				) === 'yes';
If this will only be used here, better move the `=== 'yes'` into the "if" for better readability:
```
if ($userAutoCompleteEnabled === 'true') {.....}
```

2019-03-29 14:18 UTC, jvillafanez commented
I haven't checked the logic in depth, nor tested it. The code looks fine, just minor touches.

2019-03-29 14:27 UTC, karakayasemi commented on apps/files_sharing/templates/settings-personal.php
> -			<input type="checkbox" name="auto_accept_share" id="userAutoAcceptShareInput" class="checkbox" value="1" checked="checked" />
Recently, I added these lines of code. It is also well covered with webUI acceptance tests. I adjusted acceptance tests for this change. Looks like everything is fine.

2019-03-29 14:34 UTC, karakayasemi commented on apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
> +				$userEnabled = $this->config->getUserValue(
Maximum line length is 80 characters in our code style guideline. If I write it in one-line, it takes 140 characters. IMHO, this way is more appropriate.

2019-03-29 14:40 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/ShareesController.php
> +				) === 'yes';
I made the suggested change.

2019-03-29 15:31 UTC, karakayasemi commented
@ownclouders rebase

2019-03-29 15:31 UTC, ownclouders commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2019-03-29 15:33 UTC, ownclouders commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2019-04-01 08:40 UTC, PVince81 commented on apps/files_sharing/templates/settings-personal.php
> +			<input type="checkbox" name="<?php echo $key?>" id="<?php echo $key . '_input'?>" class="checkbox" value="1" checked="checked" />
we have `p()` functions instead of `echo`, see other examples in templates

2019-04-01 08:42 UTC, PVince81 requested changes
@karakayasemi please use `p()` for proper sanitization

2019-04-01 12:27 UTC, karakayasemi commented on apps/files_sharing/templates/settings-personal.php
> +			<input type="checkbox" name="<?php echo $key?>" id="<?php echo $key . '_input'?>" class="checkbox" value="1" checked="checked" />
all `echo`'s changed with `p()`

2019-04-01 12:37 UTC, PVince81 approved these changes
:+1:

2019-04-01 13:13 UTC, merged