Add a command to check federated share updates
owncloud/core pull request #34903
Opened 2019-03-26 16:50 UTC by VicDeo

## Description
Allow manually check federated share updates

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?
testing in progress

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Document
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-03-26 16:58 UTC, VicDeo commented
@PVince81 Won't you mind a quick preliminary review?

2019-03-26 17:30 UTC, mmattel commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +			->setDescription('Sync external shares');
`Sync external shares` --> `Sync federated shares`
Else it confuses a bit because external is also a eg SMB share.

2019-03-26 17:32 UTC, mmattel commented
This is documenation relevant because it is a new command !
Please edit the PR and add a doc issue for it.

2019-03-27 13:27 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +			->setDescription('Sync external shares');
thanks, changed.

2019-03-28 09:07 UTC, PVince81 requested changes
See comments

2019-03-28 09:07 UTC, PVince81 commented on apps/federatedfilesharing/appinfo/info.xml
> +        <command>OCA\FederatedFileSharing\Command\SyncIncomingShares</command>
it's not really syncing but just updating the etag that will result in a later sync

2019-03-28 09:07 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +			->setDescription('Manual synchronisation of incoming federated shares');
same as above. don't use the term "sync" as it sounds like we're synchronizing files

2019-03-28 09:07 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +				$storage = $mount->getStorage();
would it make sense to filter by federated share mounts/storage instances ? as far as I understand this would refresh/rescan also other external storages

2019-03-28 09:07 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +		return $qb->execute();
would this cursor lock the table for any further concurrent updates ?

@tomneedham @butonic

2019-03-28 11:34 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +				$storage = $mount->getStorage();
`getExternalMountProvider` returns `\OCA\Files_Sharing\External\MountProvider` and `\OCA\Files_Sharing\External\MountProvider::getMountsForUser` creates Mounts using `'\OCA\Files_Sharing\External\Storage'` storage class. 'External' in this context means 'Federated'. https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/External/Storage.php#L86
Moving the storage, provider, etc into the federation app is listed in this task https://github.com/owncloud/core/issues/22209
as **Migrate apps/files_sharing/lib/external to the federated file sharing app**

2019-03-28 11:41 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +		return $qb->execute();
this is just an ordinary `SELECT DISTINCT` query, so I don't think so

2019-03-28 11:55 UTC, VicDeo commented on apps/federatedfilesharing/appinfo/info.xml
> +        <command>OCA\FederatedFileSharing\Command\SyncIncomingShares</command>
changed to `PollIncomingShares`

2019-03-28 11:56 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/SyncIncomingShares.php
> +			->setDescription('Manual synchronisation of incoming federated shares');
changed into `incoming-shares:poll` and **Poll incoming federated shares manually to detect updates**

2019-03-28 13:36 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +	protected function getCursor() {
Move this to the `FederatedShareProvider`? It should be fine to inject the provider directly in order to use a public method that isn't in the interface.

2019-03-28 13:36 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					// it can be locked, let's skip it then
I'd rather know about these error somehow. Maybe document that these errors can be thrown here and handle them in the `execute` method. It might be overkill, but you can do in the `execute` method
```
try {
  $this->refreshStorageRoot($storage)
} catch (\Exception $e) {
  $output->writeln($e->getMessage());
}
```
This way, if something goes wrong, at least the admin can know what happened.
You can also catch the specific exceptions you want to catch and provide a more detailed error message.

Note that, in any case, the process still tries to update all the shares, and the admin can know what mount point or path hasn't been updated and also the reason.

2019-03-28 13:36 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		return \OC\Files\Filesystem::getLoader();
this might be able to be injected. In the application.php you can create this command with this particular loader. A bit ugly, but it should allow mocking it.

2019-03-28 13:36 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
Any alternative? Worst case, we can move this also to the application.php file in order to inject the class.

2019-03-28 13:41 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
I don't see any. 
When I try to inject `\OCA\Files_Sharing\External\MountProvider` directly the command explodes

2019-03-28 13:45 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					// it can be locked, let's skip it then
it will be used for a cronjob mainly. But ok.

2019-03-28 13:55 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
In the application.php class you should be able to do something like:
```
                $container->registerService(
			PollIncomingShares::class,
			function ($c) use ($server) {
                                $sharingApp = new OCA\Files_Sharing\AppInfo\Application()
				return new PollIncomingShares(
					$server->getDBConnection(),
					$server->getUserManager(),
					$sharingApp->getContainer()->query('ExternalMountProvider'),
				);
			}
		);
```
That might work, although it's ugly. Note that if the sharing app is disabled it will explode, so we should mitigate this scenario somehow.

I'm not sure if core provides a way to get the application container of another app...

2019-03-28 13:59 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
how about putting that command directly in this app then ?

2019-03-28 13:59 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
ah, it's already there but the mount provider is in files_sharing... hmm... and putting the command in files_sharing is also ugly

2019-03-28 15:12 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					// it can be locked, let's skip it then
done

2019-03-28 15:12 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		return \OC\Files\Filesystem::getLoader();
moved to Appinfo

2019-03-28 15:12 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$app = new Application();
moved to Appinfo

2019-03-28 17:11 UTC, tomneedham commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					$output->writeln($e->getMessage());
Problem here, is exceptions never get logged and since this command is designed probably to run in cron, will go unnoticed. Would suggest to log as well.

2019-03-29 10:08 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					$output->writeln($e->getMessage());
@tomneedham at least some of them are logged by the dav app:
```
deo@reborn:~/public_html/oc-master> rm data/owncloud.log
deo@reborn:~/public_html/oc-master> php occ incoming-shares:poll
Sabre\HTTP\ClientHttpException: Unauthorized
deo@reborn:~/public_html/oc-master> cat data/owncloud.log          
{"reqId":"0jcYYTjvA7asrGLBtk0R","level":3,"time":"2019-03-29T10:07:45+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"#0 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(232): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(259): Sabre\\\\DAV\\\\Client->propFind('http:\\\/\\\/localhos...', Array)\\n#2 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(579): OC\\\\Files\\\\Storage\\\\DAV->propfind('')\\n#3 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(175): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#4 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Common->filemtime('')\\n#5 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(252): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#6 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->filemtime('')\\n#7 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#8 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/apps\\\/federatedfilesharing\\\/lib\\\/Command\\\/PollIncomingShares.php(110): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#9 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/apps\\\/federatedfilesharing\\\/lib\\\/Command\\\/PollIncomingShares.php(92): OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares->refreshStorageRoot(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#10 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(960): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(255): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(148): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Console\\\/Application.php(164): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/console.php(106): OC\\\\Console\\\\Application->run()\\n#16 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/occ(11): require_once('\\\/home\\\/deo\\\/publi...')\\n#17 {main}\",\"File\":\"\\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":155}"}
{"reqId":"0jcYYTjvA7asrGLBtk0R","level":3,"time":"2019-03-29T10:07:45+00:00","remoteAddr":"","user":"--","app":"files_external","method":"--","url":"--","message":"Unauthorized"}
{"reqId":"0jcYYTjvA7asrGLBtk0R","level":3,"time":"2019-03-29T10:07:45+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageInvalidException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Unauthorized\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(830): OC\\\\Files\\\\Storage\\\\DAV->throwByStatusCode(401, Object(Sabre\\\\HTTP\\\\ClientHttpException), '')\\n#1 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(275): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientHttpException), '')\\n#2 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(579): OC\\\\Files\\\\Storage\\\\DAV->propfind('')\\n#3 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(175): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#4 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Common->filemtime('')\\n#5 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(252): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#6 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->filemtime('')\\n#7 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(232): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#8 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/apps\\\/federatedfilesharing\\\/lib\\\/Command\\\/PollIncomingShares.php(110): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filemtime('')\\n#9 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/apps\\\/federatedfilesharing\\\/lib\\\/Command\\\/PollIncomingShares.php(92): OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares->refreshStorageRoot(Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#10 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(960): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(255): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\FederatedFileSharing\\\\Command\\\\PollIncomingShares), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/home\\\/deo\\\/public_html\\\/oc-master\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(148): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Out [...]

2019-03-29 10:16 UTC, jvillafanez commented
We have to check what happens if the sharing app is disabled. We might need to workaround something.

2019-03-29 11:24 UTC, VicDeo commented
@jvillafanez good point. Added:
```
deo@reborn:~/public_html/oc-master> php occ a:d files_sharing
files_sharing disabled
deo@reborn:~/public_html/oc-master> php occ incoming-shares:poll
Polling is not possible when files_sharing app is disabled. Please enable it with 'occ app:enable files_sharing'
```

2019-03-29 11:51 UTC, VicDeo commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +	protected function getCursor() {
My taste tells me that it should stay here. 
Could be moved to the provider but it needs to be renamed into `getUniqueRecipients` and return them as an array of uids (and this array may be huuuge)

2019-03-29 13:39 UTC, jvillafanez commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +	protected function getCursor() {
If you don't want to leak DB stuff, you may return a generator instead of an array. As long as it's clear that the function returns a generator of uids I think it's fine.

2019-03-29 13:43 UTC, jvillafanez commented
Do we want to go a bit further and check if the sharing app is present, not just disabled? or do we assume that the sharing app will always be present?
We might need to include a comment somewhere so we make clear what happen with the mount provider if the sharing app is disabled / removed.

2019-03-29 13:48 UTC, VicDeo commented
@jvillafanez I can't go further too much as there are estimates.
It seems to me that if sharing app is disabled/missing/stolen/shipped_to_Mars then federated sharing is also pointless

2019-03-29 13:50 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +					$output->writeln($e->getMessage());
it's likely logged on a higher level already ?

2019-03-29 13:51 UTC, PVince81 commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +	protected function getCursor() {
I think the current code is good enough

2019-03-29 13:51 UTC, PVince81 approved these changes

2019-03-29 13:52 UTC, PVince81 commented
codecov fail likely due to Application.php, skipping

2019-03-29 13:52 UTC, merged

2019-03-29 13:52 UTC, PVince81 commented
@VicDeo please backport

2019-03-29 14:13 UTC, VicDeo commented
stable10: https://github.com/owncloud/core/pull/34933