[stable10] This commit adds the required server-side support for delta-sync.
owncloud/core pull request #35011
Opened 2019-04-12 13:21 UTC by PVince81

Backport of https://github.com/owncloud/core/pull/29404 to stable10.

Should we add a config switch to disable the feature ?

2019-04-13 08:13 UTC, mrow4a commented on apps/dav/lib/Files/ZsyncPlugin.php
> +		$this->view->mkdir('files_zsync');
@PVince81 @DeepDiver1975 we have to find another way. This is invasive operation, and should be lazy.

2019-04-13 08:16 UTC, mrow4a requested changes
Lets fix that mkdir issue. Lets maybe disable it by default, (informing this is experimental feature?)

2019-04-15 09:43 UTC, guruz commented
It's already behind a [x] switch in the client, so I'd say you can keep it ON in the server since clients control if they want to use it?

2019-04-15 09:44 UTC, guruz commented on apps/dav/lib/Files/ZsyncPlugin.php
> +		$this->view->mkdir('files_zsync');
Note that this is a backport, not the original PR.

2019-04-15 13:19 UTC, mrow4a commented
@guruz this is exactly the problem... This `mkdir` is execute even you don't use delta sync

2019-06-05 09:10 UTC, guruz commented
Just curious about this one :-)
As 2.6.0 will ship with delta sync

2019-07-30 06:47 UTC, closed without merging