Filter unavailable users on polling
owncloud/core pull request #35010
Opened 2019-04-12 12:30 UTC by VicDeo

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-04-18 07:31 UTC, PVince81 requested changes

2019-04-18 07:31 UTC, PVince81 commented on apps/files_sharing/lib/External/Manager.php
> +	public function setUid($uid) {
was very confused when seeing this, then noticing that it would just update the already injected `$uid`

can you adjust the PHPDocs to clarify what this is.
is this the currently logged in user ? or do we have one external manager instance per user ?

ideal would be to use IUserSession instead. if you think it's too risky to change, add some "FIXME" to hint at this

2019-04-18 12:10 UTC, VicDeo commented on apps/files_sharing/lib/External/Manager.php
> +	public function setUid($uid) {
@PVince81 we polling in CLI and there is not user in session.
While removing the share manager tries to to strip `/uid/files` and fails to do it correctly. See 
https://user-images.githubusercontent.com/991300/56204970-3dfb2f00-6051-11e9-8c7d-737ee65f588c.png

2019-04-18 12:19 UTC, VicDeo commented on apps/files_sharing/lib/External/Manager.php
> +	public function setUid($uid) {
@PVince81 Added PHPDoc and fixme

2019-04-22 16:14 UTC, PVince81 approved these changes
:+1:

2019-04-22 16:14 UTC, merged

2019-04-22 16:14 UTC, PVince81 commented
@VicDeo please backport to release-10.2.0 branch

2019-04-22 17:41 UTC, VicDeo commented
release-10.2.0: https://github.com/owncloud/core/pull/35073

2019-05-28 11:40 UTC, phil-davis commented
This was backported into `release-10.2.0`  which was then merged into `stable10` - so it is part of `stable10` release series.