restore system config after running acceptance test
owncloud/core pull request #35119
Opened 2019-04-29 09:38 UTC by HariBhandari07

## Description

Restore system config after running acceptance test scenarios
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-04-29 10:47 UTC, skshetry reviewed
LGTM :slightly_smiling_face:

2019-04-29 10:50 UTC, individual-it requested changes

2019-04-29 10:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/AppConfiguration.php
> +					SetupHelper::runOcc(
try to run that for any case, `type=json` should work for any type.
currently you have e.g. not covered `boolean`

2019-04-30 03:44 UTC, skshetry commented
@ownclouders rebase

2019-05-02 03:28 UTC, individual-it approved these changes

2019-05-02 05:50 UTC, merged

2019-05-02 11:19 UTC, HariBhandari07 commented
Backport on #35141