shareAutocompletion feature updated for the user to be not listed in …
owncloud/core pull request #35133
Opened 2019-05-02 05:19 UTC by HariBhandari07

…autocomplete list in webUI

## Description

shareAutocompletion feature updated for the user to be not listed in autocomplete list in webUI
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-02 08:28 UTC, individual-it requested changes

2019-05-02 08:28 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +  Scenario: autocompletion of already existing user
more explanation please

2019-05-02 08:28 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +  Scenario: autocompletion of already existing user
need more explanation, what is the difference to the last scenario

2019-05-02 09:06 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then the user :username should not be listed in the autocomplete list on the webUI
We don't usually use `the user` when user name is given.
```suggestion
	 * @Then user :username should not be listed in the autocomplete list on the webUI
```

2019-05-02 09:06 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function theUserShouldNotBeListedInTheAutocompleteListOnTheWebui($username) {
```suggestion
	public function userShouldNotBeListedInTheAutocompleteListOnTheWebui($username) {
```

2019-05-02 09:07 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 *
no line between return and throw.

2019-05-02 09:10 UTC, paurakhsharma reviewed
Looks good.
Some small changes needed.

2019-05-02 09:13 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			throw new Exception("$username should not be present in the autocomplete items list");
Error message should tell what the current state is, not what needs to be. 
Below is just a basic suggestion, needs to be improved.
```suggestion
			throw new Exception("$username was found in the autocomplete items list, but was not expected.");
```

2019-05-02 12:22 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then the user :username should not be listed in the autocomplete list on the webUI
https://doc.owncloud.com/server/developer_manual/core/acceptance-tests.html#referring-to-named-entities
and the doc on that page has the "standards" that we try to use for consistency.

2019-05-03 07:01 UTC, HariBhandari07 commented
@skshetry @paurakhsharma @phil-davis can you please provide review?

2019-05-03 07:03 UTC, paurakhsharma reviewed
Looks good to me. @skshetry @dpakach Please have a look.

2019-05-03 07:51 UTC, dpakach reviewed
LGTM :+1:

2019-05-03 08:15 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			throw new Exception("$username found in autocomplete list but not expected");
```suggestion
			throw new Exception("$username was found in the autocomplete items list, but was not expected.");
```

2019-05-03 11:25 UTC, individual-it requested changes

2019-05-03 11:25 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +  Scenario: autocompletion of a pattern where the name of existing users contain the pattern somewhere in the last
s/somewhere in the last/at the end

2019-05-06 04:35 UTC, HariBhandari07 commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			throw new Exception("$username found in autocomplete list but not expected");
I think the error message is ok.

2019-05-06 04:59 UTC, individual-it approved these changes

2019-05-06 06:02 UTC, merged

2019-05-06 06:19 UTC, HariBhandari07 commented
backport on #35152