Add new exceptions for objectstore
owncloud/core pull request #35144
Opened 2019-05-03 14:13 UTC by sharidas

Add new exceptions for objectstore.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Introducing new exception(s) to objectstorage. The idea of having new exception is because the interface `IObjectStore` relies on exception.
So we have an exception heirarchy as shown below:
![ObjectStoreWriteException](https://user-images.githubusercontent.com/3600427/57142583-826d2580-6dda-11e9-8af3-60fea1ef242a.png)

The idea is any operation specific exceptions ( like `readObject`, `writeObject` and `deleteObject` ) will use exceptions like `ObjectStoreWriteException` ( for `writeObject` ) extends `ObjectStoreOperationException`. The `ObjectStoreOperationException` extends `ObjectStoreException`.

This PR focuses only on the 3 exceptions shared above. So in future lets say we need to add exception for `readObject` then we could create new exception like `ObjectStoreWriteException` which would inherit from `ObjectStoreOperationException` and so on.
But lets say if we need to have an exception for connection, then we also have an option to create, say `ObjectStoreConnectionException` which can be inherited from `ObjectStoreException`

## Related Issue

- Fixes <issue_link>

## Motivation and Context

Introduces new exception for objectstorage.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-06 13:05 UTC, jvillafanez commented
The `getStatusCode()` should be in the `ObjectStoreOperationException`. I expect the read and delete operation to have also a status code we can check. The `ObjectStoreWriteException` (and others) will set the status code using the parent constructor, and they'll use the inherited method (no need to redefine it)

Another question: do we need to distinguish between the exception code and the status code? Is there any potential problem if we set the exception code as the status code? Just trying to simplify the number of things we need to get to throw the exception.

2019-05-06 13:22 UTC, jvillafanez commented on lib/public/Files/ObjectStore/ObjectStoreWriteException.php
> +		$message = $message . " The status code from object storage is $statusCode.";
I don't think we need to rewrite the message here. There is no expectation of subclassing this particular exception, so whatever throws this exception should write the appropiate message by itself.
If you still want to show the status code automatically in the message, You can try to use `$message = "($statusCode) $message";` (just prepending the status code to the message), which is more compact and it doesn't feel so invasive.

2019-05-07 06:32 UTC, sharidas commented
##### Regarding readObject statusCode

`statusCode` for read is not available. The only exception it would throw is from `init()` call in the `readObject()` ( in files_primary_s3 ). The reason is that it expects return from fopen. Hence even if it fails all we would get a `false`.

##### Regarding deleteObject statusCode

The return from `$this->connection->deleteObject()` does have a result with `@metadata`. Here is the list from `@metadata`:
```
'statusCode' => 204,
  'effectiveUri' => 'http://localhost:8000/owncloud/urn%3Aoid%3A35',
  'headers' => 
  array (
    'x-amz-delete-marker' => 'true',
    'x-amz-version-id' => '3938343432373839363432303134393939393939524730303120203231',
    'server' => 'S3 Server',
    'x-amz-id-2' => '38e32c73ae43b4071577',
    'x-amz-request-id' => '38e32c73ae43b4071577',
    'date' => 'Tue, 07 May 2019 06:25:58 GMT',
    'connection' => 'close',
  ),
  'transferStats' => 
  array (
    'http' => 
    array (
      0 => 
      array (
      ),
    ),
  ),
)
```

2019-05-27 06:52 UTC, jvillafanez commented
There are tests failing.

2019-05-27 08:08 UTC, phil-davis commented
Unit test fail https://drone.owncloud.com/owncloud/core/17672/127 is due to the current issue #35330 - there is a unit test that is uccrently always failing in master

2019-05-28 09:50 UTC, jvillafanez approved these changes

2019-05-30 09:29 UTC, DeepDiver1975 requested changes

2019-05-30 09:29 UTC, DeepDiver1975 commented on lib/public/Files/ObjectStore/ObjectStoreWriteException.php
> +	 * @since 10.2.0
10.2 is Out. This will Go Info 10.3

2019-05-30 10:25 UTC, sharidas commented on lib/public/Files/ObjectStore/ObjectStoreWriteException.php
> +	 * @since 10.2.0
Updated all new files created in this PR with `10.3.0`

2019-05-30 13:27 UTC, sharidas commented
@DeepDiver1975 I have updated the PR as requested. Kindly review the change set.

2019-05-31 08:19 UTC, DeepDiver1975 approved these changes

2019-05-31 08:20 UTC, merged

2019-05-31 08:31 UTC, sharidas commented
Backport PR to stable10 : https://github.com/owncloud/core/pull/35389