feature test for share autocomplete list in webUI
owncloud/core pull request #35153
Opened 2019-05-06 07:35 UTC by HariBhandari07

## Description

Test for autocompletion feature in share dialog using webUI.
Also includes test for #34942 and #34779
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-06 07:46 UTC, dpakach commented on tests/acceptance/features/lib/PersonalSharingSettingsPage.php
> +	protected $allowFindingYouViaAutocompleteCheckboxXpathCheckboxId
```suggestion
	protected $allowFindingYouViaAutocompleteCheckboxId
```

2019-05-06 07:51 UTC, HariBhandari07 commented on tests/acceptance/features/lib/PersonalSharingSettingsPage.php
> +	protected $allowFindingYouViaAutocompleteCheckboxXpathCheckboxId
I followed the legacy coding style: _
	protected $autoAcceptLocalSharesCheckboxXpath
	
	protected $autoAcceptLocalSharesCheckboxXpathCheckboxId
		
	protected $autoAcceptFederatedSharesCheckboxXpath
		
	protected $autoAcceptFederatedSharesCheckboxXpathCheckboxId

2019-05-06 07:52 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
>  	}
```suggestion
	}
	
```

2019-05-08 09:11 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
```suggestion
    When the user re-logs in as "user1" using the webUI
```

We can use both logout and login step using one step.

2019-05-08 09:12 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
Same here

2019-05-08 09:17 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
```suggestion
   When the user re-logs in as "user1" using the webUI
```

2019-05-08 09:18 UTC, HariBhandari07 commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
Paurakh, here "regularuser" logs out and "user1" logs in, so logging out and logging in single step is not possible.

2019-05-08 09:19 UTC, HariBhandari07 commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
same as above

2019-05-08 10:50 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
> +    And user "user1" has logged in using the webUI
This step implementation doesn't take into account which user is currently logged in,
so this should be possible

2019-05-10 04:12 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
> +	public function allowFindingYouViaAutocompleteCheckboxShouldNotBeDisplayedOnThePersonalSharingSettingsPage() {
Function name is way too long (must be auto-generated). You can truncate function name however you like. We try to cap line length to 79 chars (but is not a hard limit).

2019-05-10 04:23 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
> +	 * @When /^the user (disables|enables) allow finding you via autocomplete in share dialog$/
We try to order these kinds of step definitions based on behat keywords. So, `Given` steps are grouped at the top, then `When` steps and `Then` steps.

So, it'd be good to place this in the group of `When` step definitions.

2019-05-10 04:37 UTC, HariBhandari07 commented on tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
> +	public function allowFindingYouViaAutocompleteCheckboxShouldNotBeDisplayedOnThePersonalSharingSettingsPage() {
yup, it's long and was autogenerated but check out other functions name(for example in line 89, 100)

2019-05-13 04:42 UTC, skshetry reviewed
LGTM

2019-05-13 04:42 UTC, paurakhsharma submitted a review, later dismissed
Looks good to me :+1:

2019-05-14 03:44 UTC, individual-it requested changes
add tests 
- to check if user has disallowed autocompleting but sharer types full username
- to check if typing full display name when autocompletion is disabled (admin and user)

2019-05-14 03:44 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		if (!\in_array($username, $names)) {
use assert here

2019-05-14 03:44 UTC, individual-it commented on tests/acceptance/features/lib/PersonalSharingSettingsPage.php
> +		$localAutoAcceptCheckbox = $this->find('xpath', $this->allowFindingYouViaAutocompleteCheckboxXpath);
make line shorter

2019-05-14 05:02 UTC, HariBhandari07 commented
backport on #35217

2019-05-14 05:04 UTC, individual-it approved these changes

2019-05-14 08:29 UTC, individual-it commented
@ownclouders rebase

2019-05-14 09:34 UTC, merged