Add acceptance test for checking changing sharing permissions
owncloud/core pull request #35166
Opened 2019-05-07 06:33 UTC by dpakach

## Description

Add acceptance test for checking changing sharing permissions from 
1. read-write to upload-write-without-modify
2. upload-write-without-modify to read-write

## Related Issue

- Test for issue #35155

## Motivation and Context

## How Has This Been Tested?

:robot: 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-08 03:38 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +			$retries = $expect ? 1 : null;
Is this used anywhere?

2019-05-08 03:47 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +	public function itShouldNotBePossibleToDeleteFileFolderUsingTheWebUI($shouldOrNot, $name) {
Can you split this function? It was too difficult for me to think about this.

2019-05-13 03:52 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		$possible = $shouldOrNot !== "not";
🤦🏼

2019-05-15 07:35 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageBasic.php
> +		} else {
`else` not required here

2019-05-15 07:36 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/FileActionsMenu.php
> +		} else {
`else` is not essential

2019-05-16 09:14 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: Permissions work correctly on public link share with upload-write-without-modify
The scenario needs to have when step.

2019-05-16 09:14 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: Permissions work correctly on public link share with read-write
The scenario needs to have when step

2019-05-17 06:39 UTC, individual-it requested changes
looks generally good to me, just a small request

work for additional PRs:
- test with single files
- test through API

2019-05-17 06:39 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: User tries to upload existing file in public link share with permissions upload-write-without-modify
`upload-write-without-modify` ? copy-paste problem?

2019-05-17 07:18 UTC, sharidas approved these changes
LGTM :+1:

2019-05-17 10:40 UTC, individual-it approved these changes

2019-05-17 10:42 UTC, merged

2019-05-20 09:59 UTC, dpakach commented
Backport on #35267