feature test for public link share expiration date deletion
owncloud/core pull request #35175
Opened 2019-05-08 07:49 UTC by HariBhandari07

## Description

Includes two tests for deletion of expiration date when the expiration date is not enforced and enforced.
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-08 08:24 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then the user should see an error message on the edit public link popup saying :message
```suggestion
	 * @Then the user should see an error message on the public link popup saying :message
```

2019-05-08 08:25 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function theUserShouldSeeAnErrorMessageOnTheEditPublicLinkPopupSaying($message) {
```suggestion
	public function theUserShouldSeeAnErrorMessageOnThePublicLinkPopupSaying($message) {
```

2019-05-08 08:46 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: user deletes the expiration date of already existing public link using webUI when expiration date is enforced
```suggestion
  Scenario: user tries to delete the expiration date of already existing public link using webUI when expiration date is enforced
```

We usually use `tries to` when writing a scenario where the action is not supposed to be completed.

2019-05-08 08:47 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +    Given parameter "shareapi_enforce_expire_date" of app "core" has been set to "yes"
```suggestion
    And parameter "shareapi_enforce_expire_date" of app "core" has been set to "yes"
```

2019-05-08 08:48 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +      | expireDate |  |
```suggestion
      | expireDate |
```
Extra pipe

2019-05-08 08:49 UTC, paurakhsharma reviewed
Some small suggestions

2019-05-08 08:59 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +use PHPUnit\Framework\Assert;
Is this used anywhere?

2019-05-10 04:46 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
> +		return $this->editPublicLinkPopupPageObject;
I don't have any good suggestions here. I don't like returning the `PageObject` here, but, `editLink` assumed before that no error would occur (obvious as it has no `try`/`catch` even though other sub-functions throw lots of error). So, seems there's no way.

2019-05-10 04:52 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$errormessage = $this->publicSharingPopup->getErrorMessage();
Instead of saving to `publicSharingPopup` above, would this work? This way, we will always have fresh `publicSharingPopup` (I could be wrong here).
```suggestion
		$publicSharingPopup = $this->publicShareTab->updateSharingPopup();
		$errormessage = $publicSharingPopup->getErrorMessage();
```

P.S. Currently, `updateSharingPopup` doesnot return anything.

2019-05-10 04:53 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
> +		$errorMessage = $this->popupElement->find("xpath", $this->expirationDateRequiredErrorMessageXpath)->getText();
You should get the element and then, check if element is there. `getText` will return text or fail here.
```suggestion 
		$errorMessageElement = $this->popupElement->find("xpath", $this->expirationDateRequiredErrorMessageXpath);
```
Then, extract message using:
```suggestion
		$errorMessage = $errorMessageElement->getText();
```

2019-05-10 04:58 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$errormessage = $this->publicSharingPopup->getErrorMessage();
As per the discussion with @paurakhsharma, the both suggestions don't make much difference.

2019-05-10 08:39 UTC, HariBhandari07 commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
> +		return $this->editPublicLinkPopupPageObject;
some suggestion please

2019-05-10 09:02 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
> +		$errorMessage = $errorMessageElement->getText();
This check should be after the assert.

2019-05-13 06:23 UTC, skshetry reviewed
:+1:

2019-05-13 06:24 UTC, paurakhsharma reviewed
Looks good to me :+1:

2019-05-14 03:55 UTC, individual-it requested changes

2019-05-14 03:55 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$this->publicSharingPopup = $this->publicShareTab->editLink($session, $linkName, null, null, null, $date);
shorter line please

2019-05-14 03:55 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
> +		$errorMessage = $errorMessageElement->getText();
save one line ;-)
```suggestion
		return $errorMessageElement->getText();
```

2019-05-14 03:55 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +      | expireDate |   5 days    |
don't we need `+ 5 days` here, like in the test above?

2019-05-14 03:55 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +    Then the user should see an error message on the public link popup saying "Expiration date is required"
can we also check the result by API? e.g.
```
    Then the fields of the last response should include
      | expireDate |  +5 days |
```

2019-05-15 10:20 UTC, individual-it requested changes
just small things

2019-05-15 10:20 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +				if ($value != null) {
```suggestion
				if ($value !== null) {
```

2019-05-15 10:20 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
> +		$errorMessageElement = $this->popupElement->find("xpath", $this->expirationDateRequiredErrorMessageXpath);
please make the line shorter / break it

2019-05-15 10:41 UTC, HariBhandari07 commented on tests/acceptance/features/bootstrap/Sharing.php
> +				if ($value != null) {
since we are changing the expiration to " " which is empty string(not null)  it's better to use  (!empty($value))

2019-05-15 11:32 UTC, individual-it requested changes

2019-05-15 11:32 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +					PHPUnit\Framework\Assert::assertFalse(
this logic does not look correct to me. We expect the field to be in the response and be empty, so `isFieldInResponse()` should return `true`

2019-05-21 03:52 UTC, individual-it commented
@HariBhandari07 please fix the conflicts and ping me again for review

2019-05-23 08:24 UTC, paurakhsharma reviewed
Looks good :+1:

2019-05-24 09:44 UTC, individual-it approved these changes

2019-05-24 09:45 UTC, merged

2019-05-24 09:45 UTC, individual-it commented
@HariBhandari07 please backport to stable10

2019-05-30 06:40 UTC, HariBhandari07 commented
Backport on #35369