Add webUI tests for share mail notification
owncloud/core pull request #35215
Opened 2019-05-14 04:10 UTC by paurakhsharma

## Description
Add webUi acceptance test for mail notification on internal share.

## Related Issue
#35195

## Motivation and Context

## How Has This Been Tested?
🤖

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-05-14 08:29 UTC, skshetry reviewed
:+1: 

EDIT: Just a suggestion. Everything looks good to me.

2019-05-14 08:30 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			$errorMessage = $e->getMessage();
Would be better to have the following exception inside catch

2019-05-14 08:30 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		PHPUnit\Framework\Assert::assertContains(
Just throwing exception should work here, if above suggestion is accepted.

2019-05-14 08:37 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			$errorMessage = $e->getMessage();
If we move this inside catch block the code will still pass even if it was able to click the "notify by email" button which is not expected in this case.

2019-05-14 08:40 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		PHPUnit\Framework\Assert::assertContains(
If we move this inside catch block and add new throw Exception here. It would work but it would be unnecessary in my opinion.

2019-05-14 09:10 UTC, individual-it requested changes
what if a user was added to the group after the notification was send?
what if one user in the group has an email address send and an other not?

2019-05-15 07:34 UTC, individual-it requested changes

2019-05-15 07:34 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    Then the email address "user1@example.org" should not have received an email
why `user1@example.org` not receive the email? what about `user0`?
Can the sharer resend the notification to the newly added users?

2019-05-15 07:40 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    Then the email address "user1@example.org" should not have received an email
> why `user1@example.org` not receive the email? what about `user0`?

It's a mistake. That should be `user1@example.org`

> Can the sharer resend the notification to the newly added users?

No, the sharer can not resend the notification after a new user is added to the group.

2019-05-15 10:08 UTC, individual-it approved these changes

2019-05-15 10:08 UTC, merged

2019-05-15 10:54 UTC, paurakhsharma commented
Backport on: #35235

2019-05-16 06:04 UTC, paurakhsharma commented
release-10.2.0: #35240