user creation with username containing capital letters
owncloud/core pull request #35253
Opened 2019-05-17 07:12 UTC by HariBhandari07

## Description

Letter case in username should not matter in user creation.
For eg;
when a user creates user (eg "TestUser") with username containing capital letter, user with username containing all lower case ("testuser") is created i.e. letters case( upper or lower) doesn't matter in user creation
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-17 10:45 UTC, individual-it requested changes
please add the same tests to v2 API

2019-05-17 10:45 UTC, individual-it commented on tests/acceptance/features/apiProvisioning-v1/addUser.feature
> +    And user "brand-new-user" should exist
please test also that `"BRAND-NEW-USER"` does not exist

2019-05-18 01:44 UTC, phil-davis commented on tests/acceptance/features/apiProvisioning-v1/addUser.feature
> +    And the API should not return any data
Could also check here that nothing strange happened - that the original user is still there...
```
And user "brand-new-user" should exist
And user "BRAND-NEW-USER" should not exist
```

2019-05-20 07:12 UTC, skshetry reviewed
:+1:

2019-05-21 03:45 UTC, individual-it commented
@ownclouders rebase

2019-05-21 03:47 UTC, individual-it commented on tests/acceptance/features/apiProvisioning-v1/addUser.feature
> +    And the API should not return any data
it will exist, because the API does not care about how you send the username

2019-05-21 03:48 UTC, individual-it approved these changes
please squash before merging

2019-05-21 03:57 UTC, HariBhandari07 commented
Backport on #35276

2019-05-22 09:58 UTC, merged