Add cli tests for background queue status and delete
owncloud/core pull request #35254
Opened 2019-05-17 07:12 UTC by paurakhsharma

## Description
Add cli acceptance tests for `background:queue:status` and `background:queue: delete`

Had to create a new background job `OC\Command\CommandJob` by
deleting a file so that the `background:queue:delete` can delete this newly created
background job maintaining the test isolation.

## Related Issue
#35229

## Motivation and Context

## How Has This Been Tested?
🤖

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-05-17 08:11 UTC, dpakach commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +      | table_column                                       |
I think renaming this `jobs` or `background jobs` would make it more readable.

2019-05-17 08:12 UTC, paurakhsharma commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +      | table_column                                       |
I wrote it `table_column` so that it can be used for other values too. But maybe this title can
be changed to something more general?

2019-05-17 08:15 UTC, dpakach commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator deletes last background job "OC\Command\CommandJob" using the occ command
Do we have to use "last" when we give the job name itself? or are there multiple jobs with same name?

2019-05-17 08:18 UTC, paurakhsharma commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator deletes last background job "OC\Command\CommandJob" using the occ command
There can be more than one job with the same job class.

2019-05-17 08:19 UTC, paurakhsharma commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator deletes last background job "OC\Command\CommandJob" using the occ command
But, we want to delete only the latest. Which is possibly the one we created.

2019-05-17 08:36 UTC, skshetry commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator gets all the jobs in the background queue using the occ command
```suggestion
    When the administrator lists all the jobs in the background queue using the occ command
```

2019-05-17 08:48 UTC, skshetry reviewed
:+1:

2019-05-17 08:58 UTC, paurakhsharma commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator gets all the jobs in the background queue using the occ command
I am not sure what to use. I have seen many places where `gets` is used. But
``lists` also makes sense.

2019-05-17 08:58 UTC, paurakhsharma commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator gets all the jobs in the background queue using the occ command
@phil-davis What do you think?

2019-05-17 09:09 UTC, individual-it requested changes
how do we make sure the job is back for the next test after deleting it?

2019-05-17 09:09 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +		if ($jobId === $match) {
can use assert directly

2019-05-17 09:14 UTC, paurakhsharma commented
> how do we make sure the job is back for the next test after deleting it?

The job is created every time the scenario runs. 
The job `OC\Command\CommandJob` is when a user deletes their file.

2019-05-17 09:16 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +		if ($jobId === $match) {
Yeah, I will make a change.

2019-05-17 09:39 UTC, individual-it approved these changes

2019-05-17 10:25 UTC, paurakhsharma commented
@PVince81 @patrickjahns Can you please merge this. Codecov is crossing it's limits 😄

2019-05-17 10:59 UTC, phil-davis commented on tests/acceptance/features/cliBackground/backgroundQueue.feature
> +    When the administrator gets all the jobs in the background queue using the occ command
Yes, `lists` is a bit nicer in this context. But if we already have `gets` in various places for `occ` commands that output a multi-item list (e.g. listing users, groups...) then it is OK here also.

In a separate PR somebody could refactor `gets` to `lists` "some day"

2019-05-20 01:31 UTC, individual-it commented
@ownclouders rebase

2019-05-20 06:34 UTC, skshetry submitted a review, later dismissed
This PR needs to be rebased, and the function `theCommandOutputTableShouldContainTheFollowingText` should be removed from here, as it is already in the #35257.

Dismiss this review when it's done (verify by looking at the diff, no `theCommandOutputTableShouldContainTheFollowingText` should be there).

2019-05-21 03:49 UTC, individual-it commented
restarted drone build

2019-05-21 05:10 UTC, merged

2019-05-21 08:01 UTC, individual-it commented
fixes  #35229