Add cli tests for config file values
owncloud/core pull request #35269
Opened 2019-05-20 10:25 UTC by paurakhsharma

## Description
Add cli tests for checking `config.php` default values.

## Related Issue
#31347

## Motivation and Context

## How Has This Been Tested?
🤖

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-05-20 10:49 UTC, dpakach commented on tests/acceptance/features/bootstrap/OccContext.php
> +			$this->featureContext->getStdOutOfOccCommand(), true
use `$featureContext->getSystemConfig();` method here. That may be a bit easy.

2019-05-20 10:54 UTC, dpakach commented on tests/acceptance/features/bootstrap/OccContext.php
> +		if ($system_config[$key] === $value) {
Use `PHPUnit\Framework\Assert::assertEqual` instead of `if ()  + PHPUnit\Framework\Assert::fail `

2019-05-20 11:07 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +			$this->featureContext->getStdOutOfOccCommand(), true
Actually, I am getting the output of the previous command. So, changing the behat step title 
should be a good idea.

2019-05-21 09:06 UTC, skshetry commented on tests/acceptance/features/bootstrap/OccContext.php
> +		$config_list = \json_decode(
:camel:
```suggestion
		$configList = \json_decode(
```

2019-05-21 09:06 UTC, skshetry commented on tests/acceptance/features/bootstrap/OccContext.php
> +		$system_config = $config_list['system'];
:camel: ?
```suggestion
		$system_config = $config_list['system'];
```

2019-05-21 10:02 UTC, skshetry commented on tests/acceptance/features/bootstrap/OccContext.php
> +		foreach ($configArray as $innerConfigArray) {
Guiding comments please .....

http://antirez.com/news/124

2019-05-21 10:48 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +		foreach ($configArray as $innerConfigArray) {
@skshetry Please have a look at the comments.

2019-05-21 11:26 UTC, skshetry reviewed
:+1:

2019-05-22 06:10 UTC, individual-it requested changes

2019-05-22 06:10 UTC, individual-it commented on tests/acceptance/features/cliMain/configKey.feature
> +      | key      | value  |
lets have a type column here, then we can compare the types correctly

2019-05-22 07:17 UTC, individual-it requested changes

2019-05-22 07:17 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +			$value = $value === 'true' ? true : false;
```suggestion
			$value = (bool)$value ;
```

2019-05-22 07:17 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +				if ($innerConfigArray[$value['key']] === $value['value']) {
we could delete from the table the found keys and then the ones that are not found will be left over, so the error can show which one were not found

2019-05-22 08:09 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +			$value = $value === 'true' ? true : false;
`(bool)` typecasting casts `"false"` to `true`

2019-05-22 08:11 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +				if ($innerConfigArray[$value['key']] === $value['value']) {
Yeah, that seems to be the better way.

2019-05-23 06:50 UTC, individual-it requested changes

2019-05-23 06:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccContext.php
> +			$matchAttribute = \preg_match(
you can use `PHPUnit\Framework\Assert::matchesRegularExpression()`

2019-05-23 08:30 UTC, individual-it requested changes

2019-05-23 08:30 UTC, individual-it commented on tests/acceptance/features/cliMain/configKey.feature
> +  Scenario: log time zone should be listed in the config file
copy paste error

2019-05-23 11:02 UTC, individual-it approved these changes

2019-05-23 11:04 UTC, individual-it commented
@paurakhsharma please backport and mark in #35207

2019-05-23 11:24 UTC, merged

2019-05-24 05:49 UTC, paurakhsharma commented
Backport on: #35320