Acceptance test for giving controlled  access to users to change thei…
owncloud/core pull request #35270
Opened 2019-05-20 11:27 UTC by bhawanaprasain

## Description
Administrator can give controlled access to users in settings page to change their full name

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-05-21 09:00 UTC, individual-it approved these changes

2019-05-21 09:01 UTC, individual-it commented
@bhawanaprasain please make a backport to stable10 branch

2019-05-21 10:57 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +			echo "next one\n";
Is this debug code? 
Or it is intended?

2019-05-21 10:58 UTC, paurakhsharma reviewed
@bhawanaprasain  I have some comments. Please check them.

2019-05-21 11:36 UTC, individual-it requested changes
@paurakhsharma good catch

2019-05-21 11:38 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @throws Exception
`PHPUnit\Framework\Assert::fail` throws the exception

2019-05-21 15:28 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
> +	 * @throws Exception
Oh, I see, this method throws an exception because we are only catching 
`Behat\Mink\Exception\ElementNotFoundException`

2019-05-22 11:29 UTC, individual-it approved these changes

2019-05-22 11:29 UTC, merged

2019-05-22 11:30 UTC, individual-it commented
@bhawanaprasain please backport to stable10 branch

2019-05-24 10:42 UTC, phil-davis commented
Backport `stable10` #35287