api test for sharing with user by entering username in capital letters
owncloud/core pull request #35309
Opened 2019-05-23 06:09 UTC by HariBhandari07

## Description

includes api test for creating new shares using sharing api by entering username in capital letters
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-23 06:17 UTC, individual-it requested changes
please check also if the user did receive the file
there are steps line `... should see following elements`

2019-05-23 06:17 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +  Scenario: share with user by entering username in capital letters
```suggestion
  Scenario: share with user when username contains capital letters
```

2019-05-23 08:17 UTC, paurakhsharma reviewed
Tests look good to me :+1:

2019-05-23 08:50 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | ocuser0  |
```suggestion
      | user0  |
```

2019-05-23 08:50 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | ocuser1  |
```suggestion
      | user1  |
```

2019-05-23 08:50 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | uid_owner   | ocuser0      |
```suggestion
      | uid_owner   | user0      |
```

2019-05-23 08:50 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | share_with  | ocuser1      |
```suggestion
      | share_with  | user1      |
```

2019-05-23 08:51 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | ocuser1  |
```suggestion
      | user1  |
```

2019-05-23 08:51 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +    When user "ocuser0" shares file "/welcome.txt" with user "OCUSER1" using the sharing API
```suggestion
    When user "user0" shares file "/welcome.txt" with user "USER1" using the sharing API
```

2019-05-23 08:51 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | share_with  | ocuser1      |
```suggestion
      | share_with  | user1      |
```

2019-05-23 08:51 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +    And user "ocuser1" should see the following elements
```suggestion
    And user "user1" should see the following elements
```

2019-05-24 09:47 UTC, individual-it requested changes

2019-05-24 09:47 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | uid_owner   |   user0      |
please fix formating

2019-05-24 09:47 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +      | uid_owner   |   user0      |
same for other places

2019-05-24 09:47 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +    When user "user0" shares file "/welcome.txt" with user "USER1" using the sharing API
it would be more interesting to share with that group
```suggestion
    And user "USER1" has been added to group "grp1"
    When user "user0" shares file "/welcome.txt" with group "grp1" using the sharing API
```

2019-05-27 03:44 UTC, individual-it approved these changes

2019-05-27 05:00 UTC, phil-davis commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +    And user "USER1" has been added to group "grp1"
This scenario is really testing that users can be added to groups using not-case-sensitive user names.
Maybe we should also add a specific scenario for adding and removing users to/from groups

2019-05-28 04:04 UTC, phil-davis commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +    And user "USER1" has been added to group "grp1"
I made PR #35342 to cover various scenarios of mixed-case user and group names for managing users, groups and group membership.

2019-05-28 04:05 UTC, phil-davis commented
@HariBhandari07 is there an issue to go with this PR?
If not, I can create one, because I need one for other mixed-case user and group name tests.

2019-05-29 08:56 UTC, merged

2019-05-29 09:09 UTC, HariBhandari07 commented
backport on #35357