Get enabled and disabled apps from same request in acceptance tests
owncloud/core pull request #35353
Opened 2019-05-29 05:48 UTC by dpakach

## Description

In acceptance test use same http request to get enabled and disabled apps.

## Related Issue

- Related https://github.com/owncloud/QA/issues/621

## Motivation and Context

Because of lots of tests the CI has become very slow and takes a lot of time to finish especially in apps like encryption where all core tests are executed multiple times. This improves the code by a little bit so that it can be improved.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-29 06:03 UTC, phil-davis approved these changes

2019-05-29 06:13 UTC, paurakhsharma reviewed
Looks good to me :+1:

2019-05-29 07:28 UTC, individual-it requested changes
:+1: maybe just place that all into a new function

2019-05-29 07:28 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$apps = \json_decode($this->getStdOutOfOccCommand());
```suggestion
		$apps = \json_decode($this->getStdOutOfOccCommand(), true);
```
to get an array

2019-05-29 09:36 UTC, phil-davis approved these changes

2019-05-30 05:06 UTC, individual-it approved these changes

2019-05-30 05:06 UTC, merged

2019-05-30 06:48 UTC, dpakach commented
Backport on #35372