sharing with user with uppercase username
owncloud/core pull request #35388
Opened 2019-05-31 08:25 UTC by HariBhandari07

## Description

acceptance test for sharing file with user with username containing uppercase letters
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-05-31 09:23 UTC, dpakach reviewed
LGTM :+1:

2019-05-31 09:28 UTC, skshetry reviewed
:+1:

2019-05-31 09:30 UTC, phil-davis commented
This provides a test scenario for issue #35382

2019-05-31 09:30 UTC, phil-davis approved these changes

2019-05-31 09:58 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given these users have been created:
```suggestion
    And these users have been created without skeleton files:
      | username  |
      | SomeUser |
```

Please rebase and user this step instead.

2019-05-31 09:59 UTC, phil-davis commented
It got drone CI "cannot reach github.com" errors.
I restarted drone just now.

2019-05-31 10:00 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given these users have been created:
@paurakhsharma why change `Given`  to `And` ?

2019-05-31 10:14 UTC, phil-davis requested changes
When it works properly, we expect to see `lorem (2).txt` because the user already has `lorem.txt` from their skeleton.

I ran this scenario in `release-10.2.0` branch and the problem is not in that branch, so the regression has happened in some PR since `10.2.0`  was released.

2019-05-31 10:14 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then file "lorem.txt" should not be listed on the webUI
```suggestion
    Then file "lorem (2).txt" should not be listed on the webUI
```

2019-05-31 10:14 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +#    Then file "lorem.txt" should be listed on the webUI
```suggestion
#    Then file "lorem (2).txt" should be listed on the webUI
```

2019-05-31 10:47 UTC, paurakhsharma commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given these users have been created:
Oh my fault, that should be given

2019-05-31 11:04 UTC, paurakhsharma reviewed
Looks good to me :+1:

2019-06-03 07:08 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then file "lorem.txt" should not be listed on the webUI
@HariBhandari07 IMO when this works we expect to see `lorem (2).txt` on the webUI.
So we want to check `lorem (2).txt`

2019-06-03 07:15 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then file "lorem.txt" should not be listed on the webUI
`SomeUser` has been created without a skeleton folder

2019-06-03 07:16 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then file "lorem.txt" should not be listed on the webUI
OK, now I understand

2019-06-03 07:16 UTC, phil-davis approved these changes

2019-06-03 07:17 UTC, merged

2019-06-03 07:17 UTC, phil-davis commented
@HariBhandari07 please backport to `stable10`

2019-06-03 08:52 UTC, HariBhandari07 commented
Backport on #35409