Test for speeding up CI
owncloud/core pull request #35395
Opened 2019-05-31 11:17 UTC by bhawanaprasain

## Description
These tests speedup CI .

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-05-31 11:19 UTC, bhawanaprasain commented
@dpakach @paurakhsharma @skshetry please review on my PR.

2019-06-03 09:07 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When :user0 requests endpoint with :method using basic token auth then status codes should be as listed
```suggestion
	 * @When :user requests endpoint with :method using basic token auth then status codes should be as listed
```

2019-06-03 09:07 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When user0 requests these endpoints with :method using new browser session then status code be as listed
```suggestion
	 * @When user requests these endpoints with :method using new browser session then status code be as listed
```

2019-06-03 09:07 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When :user0 requests endpoint with :method using basic token auth then status codes should be as listed
```suggestion
	 * @When :user requests endpoint with :method using basic token auth then status codes should be as listed
```

2019-06-03 09:07 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +		$this-> adminRequestsEndpointsWithPassword($method, null, $table);
```suggestion
		$this->adminRequestsEndpointsWithPassword($method, null, $table);
```

2019-06-03 09:07 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +			$this->ocsContext->theOCSStatusCodeShouldBe(
This bit of code is used multiple times. It may be a good idea to put it in different function and  call that.

2019-06-03 09:14 UTC, dpakach commented on tests/acceptance/features/bootstrap/Auth.php
> +			$this->ocsContext->theOCSStatusCodeShouldBe(
A same function to check ocs and http code.

2019-06-04 10:34 UTC, bhawanaprasain commented
@dpakach @paurakhsharma @skshetry please review again.

2019-06-05 05:31 UTC, individual-it requested changes

2019-06-05 05:31 UTC, individual-it commented on tests/acceptance/features/bootstrap/Auth.php
> +	public function userRequestsEndpointsWithWrongPassword($user, $method, $password, TableNode $table) {
why "wrong" password? could we not send a correct password into that function

2019-06-05 05:31 UTC, individual-it commented on tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
> +      When user requests these endpoints with "GET" using new browser session then status code be as listed
better to specify the user-name  here

2019-06-05 05:31 UTC, individual-it commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @param string $user0
choose a better name for the variable

2019-06-05 06:41 UTC, phil-davis reviewed
Try to make the text of each step have consistent words.

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When user :user requests with :method using these endpoints with password :password then the status codes should be as listed
```suggestion
	 * @When user :user requests these endpoints with :method using password :password then the status codes should be as listed
```

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When admin requests these endpoint with :method then the status codes should be as listed
```suggestion
	 * @When the administrator requests these endpoints with :method then the status codes should be as listed
```

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When admin requests these endpoints with :method using password :password then the status codes should be as listed
```suggestion
	 * @When the administrator requests these endpoints with :method using password :password then the status codes should be as listed
```

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When :user requests endpoint with :method using basic token auth then status codes should be as listed
```suggestion
	 * @When user :user requests these endpoints with :method using basic token auth then the status codes should be as listed
```

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When user0 requests these endpoints with :method using new browser session then status code be as listed
```suggestion
	 * @When the user requests these endpoints with :method using a new browser session then the status codes should be as listed
```

2019-06-05 06:41 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When the user requests these endpoints with :method using the generated app password then status code should be as listed
```suggestion
	 * @When the user requests these endpoints with :method using the generated app password then the status codes should be as listed
```

2019-06-06 08:07 UTC, phil-davis reviewed
2 comments remaining now.

2019-06-06 08:07 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Auth.php
> +	 * @When the user :user requests these endpoints with :method using basic token auth then the status codes should be as listed
```suggestion
	 * @When user :user requests these endpoints with :method using basic token auth then the status codes should be as listed
```

2019-06-06 08:09 UTC, phil-davis commented
@bhawanaprasain because of core CI  trouble overnight, you will need to rebase to latest master as well as fixing up the review comments.

2019-06-10 03:55 UTC, individual-it approved these changes

2019-06-10 03:55 UTC, merged

2019-06-10 03:55 UTC, individual-it commented
@bhawanaprasain please backport to stable10

2019-06-12 06:52 UTC, phil-davis commented
Backport `stable10` #35472