Test for speeding up CI
owncloud/core pull request #35434
Opened 2019-06-05 08:21 UTC by bhawanaprasain

## Description
These tests help to speedup CI by sending requests in loops rather than in scenario outline.

## Motivation and Context

Sending HTTP requests to endpoints  using scenario outline takes considerable time .If we send these requests in loops time required to get status code minimizes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

2019-06-05 08:52 UTC, bhawanaprasain commented
@individual-it @phil-davis please review on my PR.

2019-06-06 06:21 UTC, individual-it commented
need to be on top of #35395
and should use as much as possible the steps created there

2019-06-12 08:23 UTC, phil-davis commented
@bhawanaprasain this will be good to have. `apiAuthOCS` suite is one of the slowest, so it will be good to speed it up.
Please rebase and resolve conflicts.

2019-06-12 10:35 UTC, individual-it requested changes

2019-06-12 10:35 UTC, individual-it commented on tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
> +      | 1               | /apps/files_sharing/api/v1/remote_shares/pending/123 | 997      | 401       | group1 |
use the full path of the ocs endpoint here, then you can also reuse the steps you have done in the other PR

2019-06-14 10:59 UTC, bhawanaprasain commented
@paurakhsharma @dpakach @skshetry please review on my PR.

2019-06-14 11:17 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OCSContext.php
> +	 * @param string $verb false, $body
This must be a copy-paste error, right?

2019-06-14 11:18 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OCSContext.php
> +	 * @When administrator sends request these endpoints with :method with body using password :password then the status codes should be as listed
```suggestion
	 * @When administrator requests these endpoints with :method with body using password :password then the status codes should be as listed
```

2019-06-14 11:21 UTC, paurakhsharma reviewed
Some minor comments, please have a look

2019-06-18 04:45 UTC, individual-it approved these changes

2019-06-18 04:45 UTC, merged

2019-06-21 00:51 UTC, phil-davis commented
Backport `stable10` #35586