api test for federation sharing when the receiver has matching file/folder
owncloud/core pull request #35453
Opened 2019-06-07 04:40 UTC by HariBhandari07

## Description

Includes api test for federation sharing when the receiver has matching file/folder 
## Related Issue

https://github.com/owncloud/core/issues/35414

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-07 05:53 UTC, individual-it requested changes

2019-06-07 05:53 UTC, individual-it commented on tests/acceptance/features/apiFederation/federated.feature
> +  Scenario Outline: share of a folder to thfe remote user who already has the same name folder
s/thfe/a

2019-06-07 05:53 UTC, individual-it commented on tests/acceptance/features/apiFederation/federated.feature
> +    And the HTTP status code should be "200"
check also the existence of the file for the receiver

2019-06-10 09:06 UTC, individual-it approved these changes

2019-06-10 09:33 UTC, HariBhandari07 commented
Backport on #35462

2019-06-11 04:51 UTC, merged