rename folder without skeleton
owncloud/core pull request #35477
Opened 2019-06-11 08:17 UTC by HariBhandari07

## Description

Do not use skeleton files for ```webUIRenameFolders``` to speed up CI
## Related Issue

- Fixes <issue_link>
Part of https://github.com/owncloud/QA/issues/622
## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-11 08:36 UTC, individual-it requested changes

2019-06-11 08:36 UTC, individual-it commented on tests/acceptance/features/webUIRenameFolders/renameFolders.feature
> -    And user "user1" has logged in using the webUI
Why deleting the login and browse step from the background?

2019-06-12 04:49 UTC, dpakach commented on tests/acceptance/features/webUIRenameFolders/renameFolders.feature
> -    And user "user1" has logged in using the webUI
If we log in at beginning then we would have to reload the page after creating the files if we want to interact with those files through the webUI. IMO that just makes the tests a bit slower.

2019-06-12 04:50 UTC, dpakach reviewed
LGTM :+1:

2019-06-12 05:58 UTC, phil-davis approved these changes

2019-06-12 06:25 UTC, individual-it approved these changes

2019-06-12 07:09 UTC, merged

2019-06-12 07:17 UTC, HariBhandari07 commented
Backport on #35496