file operations in webui without skeleton
owncloud/core pull request #35499
Opened 2019-06-12 08:54 UTC by HariBhandari07

## Description

Do not use skeleton files for ```webUIFiles``` to speed up C
## Related Issue

- Fixes <issue_link>

## Motivation and Context

Part of https://github.com/owncloud/QA/issues/622
## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-12 09:52 UTC, phil-davis commented
@HariBhandari07 when a PR is being reviewed, set the "3 - To Review" label.
When the review is done and approved, then we set "4 - To Release"
Then when we see green CI and "4 - To release" anyone can press merge.

2019-06-12 10:26 UTC, phil-davis reviewed
For the various search scenarios IMO it will be good to have some more file(s) so that we know that the search is being selective.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
> +    And user "user1" has uploaded file with content "some content" to "<folder>/<file>"
This test was supposed to make sure that browsing directly will select the correct file when there are multiple files in the root folder and somewhere in a sub-folder.
So create all 6 files in the `Background` section. (All scenarios want these files)
(also I notice that the `Then` steps do not verify that the sharing details panel is for the correct expected file - but that is an existing problem)

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user1" has uploaded file with content "some content" to "/randomfile.txt"
This scenario used to have lots of files. We want to make sure that the search by tag does only return the file with the tag.
Upload another file, so that there will at least be 2 files for the search to choose from.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user1" has uploaded file with content "some content" to "/a-folder/randomfile.txt"
upload some other file(s) so we will know that the search is selecting just the tagged file(s)

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user0" has uploaded file with content "does-not-matter" to "randomfile.txt"
Upload some other file to `user1` so that `user1` has more files than just the received share.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user2" has uploaded file with content "does-not-matter" to "randomfile.txt"
Upload some other file to `user1` so that `user1` will have an extra file(s) to search.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user0" has created folder "a-folder"
Create some other folder(s) for `user1` so they have folders to search.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    Given user "user1" has uploaded file with content "does-not-matter" to "randomfile.txt"
upload another file for `user1` so they have more to search.

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user1" has created folder "strängé नेपाली folder"
create some other file/folder so there is more to search for

2019-06-12 10:26 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "user1" has created folder "/strängé नेपाली folder"
create some other file/folder so there is more to search for

2019-06-12 10:56 UTC, individual-it requested changes

2019-06-12 10:56 UTC, individual-it commented on tests/acceptance/features/webUIFiles/scrollMenuIntoView.feature
> +    Given user "user1" has been created with default attributes and without skeleton files
this needs to have the skeleton folder, otherwise the test does not make sense
this test check if clicking on the action menue does scroll the screen so that the complete action menu is visible
without skeleton folder we will have to create more folders in `When the user creates so many files/folders that they do not fit in one browser page`

2019-06-12 10:56 UTC, individual-it commented on tests/acceptance/features/webUIFiles/search.feature
> +    Given user "user1" has been created with default attributes and without skeleton files
the search does benefit from the skeleton folder to try different searches, so maybe do not change it

2019-06-12 14:15 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
> +
bonus lines can be deleted

2019-06-12 14:15 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
> +      | zzzz-must-be-last-file-in-folder.txt | simple-folder | last file                   |
and while you are here, put back the end-of-line

2019-06-13 07:58 UTC, individual-it approved these changes

2019-06-13 07:59 UTC, individual-it commented
please squash before merging

2019-06-13 09:02 UTC, HariBhandari07 commented
Backport on #35499

2019-06-13 12:06 UTC, phil-davis commented
The backport passed and has been merged, but no codecov came here.
Restarting drone to see if we can get codecov to come.

2019-06-13 23:39 UTC, phil-davis commented
@HariBhandari07 please rebase and force push. Maybe we will get lucky and receive codecov status.
(the backport already passed and is merged)

2019-06-13 23:50 UTC, skshetry commented on tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
> +    Given user "user1" has been created with default attributes and without skeleton files
Dai, what difference did this make on your local computer? I presume it's slower than copying skeleton files.

2019-06-14 05:42 UTC, merged