Enhance re share tests
owncloud/core pull request #35521
Opened 2019-06-13 13:40 UTC by phil-davis

## Description

## Related Issue
https://github.com/owncloud/enterprise/issues/3364

## Motivation and Context

## How Has This Been Tested?
Local acceptance test runs

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-14 12:07 UTC, individual-it requested changes
some minor requests

2019-06-14 12:07 UTC, individual-it commented on tests/acceptance/features/apiShareManagement/reShare.feature
> +    #And publicly uploading a file should work
is there an issue with that scenario or why that commented line?

2019-06-14 12:07 UTC, individual-it commented on tests/acceptance/features/apiShareManagement/reShare.feature
> +    #And publicly uploading a file should work
why this two lines? there is no public link

2019-06-14 13:02 UTC, phil-davis commented on tests/acceptance/features/apiShareManagement/reShare.feature
> +    #And user "user1" has created folder "/qqq"
My mistake - I had been debugging my scenario at one point.

2019-06-14 13:04 UTC, phil-davis commented on tests/acceptance/features/apiShareManagement/reShare.feature
> +    #And publicly uploading a file should work
mistake

2019-06-14 13:05 UTC, phil-davis commented on tests/acceptance/features/apiShareManagement/reShare.feature
> +    #And publicly uploading a file should work
copy-paste of mistake - I need to review my own code first :(

2019-06-14 13:07 UTC, phil-davis commented
@individual-it random commented-out lines have been removed.
Ready for review again.

2019-06-14 16:17 UTC, individual-it commented
CI failure unrelated, restarting

2019-06-14 16:17 UTC, individual-it approved these changes

2019-06-15 01:11 UTC, phil-davis commented
Backport `stable10` #35547

2019-06-15 02:59 UTC, merged