set default expiration date if expiration date is enforced and it is new share
owncloud/core pull request #35564
Opened 2019-06-17 18:41 UTC by karakayasemi

## Description
Automatic expiration date setting behavior changed with #34971. It caused regression on client sides. This PR fixes this regression by keeping #34971's functionality. 

If max expiration date is enforced set default expiration date for new share. @ckamm please check the behavior is same as expected or not. 

@micbar @pmaier1  we should consider this PR for v10.2.1.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/35550

## Motivation and Context
Automatic expiration date setting behavior changed with #34971. It caused regression on client sides. This PR fixes this regression by keeping #34971's functionality. 

## How Has This Been Tested?.
To test issue #35550 
- Activate, "Set expiration date" and enforce max expiration date.
- Try to create new public link from a desktop client
- It should create link and fill expiration date with default.

To test issue #34960
- Activate, "Set expiration date" but not enforce.
- Click share a file via public link and remove default expiration date from its input field. The share should be created without an expiration date.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-17 19:18 UTC, micbar commented
@karakayasemi Great!
Please force push, random CI failure

2019-06-18 06:52 UTC, jvillafanez commented
It feels better if this is added in the `createShare` method unless this is also somehow applied when a user updates the share.

2019-06-18 07:03 UTC, karakayasemi commented
> 
> 
> It feels better if this is added in the `createShare` method unless this is also somehow applied when a user updates the share.

Both `createShare` and `updateShare` method are using `validateExpirationDate` method. 
If expirationDate null, for a new share `validateExpirationDate` method sets default date with this PR (expected behavior for clients), but for an update case, it throws `InvalidArgumentException`.

2019-06-18 07:41 UTC, ckamm commented
@karakayasemi Excellent, I'll test it now.

2019-06-18 07:57 UTC, ckamm commented
Tests:
1) Default + enforced expiration date
- Web: Expiration date is pre-filled. Removing it leads to error. (good)
- Desktop 2.6: Expiration date is pre-filled. Removing is impossible. (good)
- Desktop 2.5: Creating share works, has expiration date. Removing is impossible. (good)

2) Default, but not enforced expiration date
- Web: Expiration date is pre-filled. Removing it before creation leads to share **with** expiration. (bug)
- Desktop 2.6: Expiration date is **not** pre-filled (client side bug). Removing it before creation leads to share **with** expiration. (bug)
- Desktop 2.5: Creating share works, has expiration date. Can be removed. (good)

What's the API for "create share without expiration" vs "create share with default expiration"?

2019-06-18 07:57 UTC, ckamm requested changes
Test issues, see comment

2019-06-18 08:29 UTC, karakayasemi commented
@ckamm thanks for detailed explanation. I moved the code-block which set expiration date inside `if($this->shareApiLinkDefaultExpireDateEnforced())` condition.  
I tested scenarios with webUI and client 2.5.4, everything seems okay this time. Please you also test one more time. Thanks.

> What's the API for "create share without expiration" vs "create share with default expiration"?

They both uses same OCS API and following same code flow, no difference between them.

2019-06-18 08:30 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +			try {
It might be better if this check is moved to a private function `isNewShare` or similar.

2019-06-18 08:57 UTC, karakayasemi commented on lib/private/Share20/Manager.php
> +			try {
@jvillafanez moved to a new function. Thanks.

2019-06-18 09:02 UTC, jvillafanez commented
code looks fine, so if it behaves fine I think it's good to merge

2019-06-18 09:17 UTC, patrickjahns commented
> I'm pretty sure one can only get everything right by keeping the old "null means default" behavior intact and making the new "request share without expiration" have different API.

Thanks for highlighting this - was this change introduced in 10.2.0 or before?

2019-06-18 12:19 UTC, ckamm approved these changes

2019-06-18 16:00 UTC, patrickjahns approved these changes

2019-06-19 08:20 UTC, merged

2019-06-19 08:58 UTC, phil-davis commented
Backports
`stable10` #35592 
`release-10.2.1` #35593