Empty code blocks removed. normalizePath Used.
owncloud/core pull request #35577
Opened 2019-06-18 10:23 UTC by ozata

## Description

I have deleted remove empty code blocks and if there is if {} else{} situation with empty if block, I negated the if condition by putting " ! " and put the code in the else inside of the empty if, I have used Filesystem::normalizePath() instead of cleanPath() and deleted the cleanPath() method.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32692

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-20 10:03 UTC, ozata commented
Test is still pending.

2019-06-20 10:39 UTC, phil-davis commented
Something bad happened in CI. It has bad days!
https://drone.owncloud.com/owncloud/core/18509
I suggest that you rebase and force push - that will trigger CI again.

2019-06-20 12:02 UTC, ozata commented
I rebased and force pushed, hope CI will pass this time. Thank you.

2019-06-20 13:21 UTC, ozata commented
CI Successfully passed, thanks for the suggestion, waiting for codecov, excited.

2019-06-20 14:16 UTC, phil-davis commented
codecov has been a PITA recently and often the result does not come.
Once one of the devs reviews, then someone will "happily" override and merge this sort of thing, where it is obvious that there is no code coverage issue.

2019-06-20 19:11 UTC, ozata commented
Thanks for quick answers and clean explanations.

2019-06-21 07:41 UTC, jvillafanez requested changes

2019-06-21 07:41 UTC, jvillafanez commented on lib/private/App/CodeChecker/NodeVisitor.php
> -					 * TODO: find a way to detect something like this:
Please, find a way to keep these comments in order not to forget there are still things to do around.

2019-06-21 07:41 UTC, jvillafanez commented on lib/private/Files/Storage/Common.php
> -	public function cleanPath($path) {
We can't delete this method. This is also used by the DAV storage, and there might be other storages using it.
Feel free to mark it as deprecated pointing to a better alternative, but as said, we can't delete this.

2019-06-21 07:43 UTC, jvillafanez commented on lib/private/Files/Storage/Common.php
> -	public function cleanPath($path) {
Alternatively, you can change the implementation of this method to use the `Filesystem::normalizePath` instead.

2019-06-21 10:18 UTC, ozata commented on lib/private/App/CodeChecker/NodeVisitor.php
> -					 * TODO: find a way to detect something like this:
So should I undelete this if or just leave the comments?

2019-06-21 10:19 UTC, ozata commented on lib/private/Files/Storage/Common.php
> -	public function cleanPath($path) {
Okay, I deleted this because it was instructed, I'll undelete it.

2019-06-21 10:29 UTC, jvillafanez commented on lib/private/App/CodeChecker/NodeVisitor.php
> -					 * TODO: find a way to detect something like this:
Removing dead code is fine, but the comments are there to indicate there are things to do. I haven't checked all the comments, so I'm not sure if leaving the comments will be enough. I'd recommend to leave them an read the code again. If you can clearly understand what is left to do, then we're fine with that comment. This is mainly to ensure the comment can be understood after a while, otherwise we should include some additional information in the comment.

2019-06-21 20:10 UTC, ozata commented on lib/private/App/CodeChecker/NodeVisitor.php
> -					 * TODO: find a way to detect something like this:
I understand now, thanks for the thorough review, I am on it

2019-07-11 16:36 UTC, ozata commented
I am on it.

2019-07-12 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=35577) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=35577) before we can accept your contribution.<br/>**15** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: DeepDiver1975<br/>:white_check_mark: ozata<br/>:white_check_mark: phil-davis<br/>:white_check_mark: VicDeo<br/>:white_check_mark: HariBhandari07<br/>:white_check_mark: skshetry<br/>:white_check_mark: dpakach<br/>:white_check_mark: karakayasemi<br/>:white_check_mark: jvillafanez<br/>:white_check_mark: sharidas<br/>:white_check_mark: dependabot-preview[bot]<br/>:white_check_mark: bhawanaprasain<br/>:white_check_mark: paurakhsharma<br/>:white_check_mark: individual-it<br/>:white_check_mark: ho4ho<br/>:x: dependabot[bot]<br/>:x: ownclouders<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=35577) it.</sub>

2019-07-30 07:27 UTC, DeepDiver1975 commented
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

2019-07-30 07:27 UTC, closed without merging