Add cli tests for app upgrade of major and minor release
owncloud/core pull request #35580
Opened 2019-06-18 11:33 UTC by paurakhsharma

## Description
Test `major` and `minor` app release upgrade. 

This tests can only be run in a local test system because when there needs to be a minor or major
upgrade of the app `./occ upgrade` needs to be executed which in turn disables `testing app`
and switches to `maintenance` mode and hence remote test calls cannot be executed.

## Related Issue
https://github.com/owncloud/QA/issues/613

## Motivation and Context
- Make CI faster in scenarios where there is no need for user files.

## How Has This Been Tested?
🤖

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-06-18 11:34 UTC, paurakhsharma commented
Some problem in `drone.yml` will fix it tomorrow.

2019-06-18 12:02 UTC, phil-davis commented on .drone.yml
> +      - PHP_VERSION: 7.1
It probably does not like the extra indent here

2019-06-18 14:49 UTC, paurakhsharma commented on .drone.yml
> +      - PHP_VERSION: 7.1
Yeah, this might be the cause. Thank you :)

2019-06-18 14:55 UTC, paurakhsharma commented
I am not sure about using `local-test-acceptance-cli` method. Please let me know your thought.

2019-06-18 15:05 UTC, phil-davis commented on .drone.yml
> +      - make local-test-acceptance-cli
```suggestion
      - make test-acceptance-local-cli
```
All the acceptance test make targets should start with `test-acceptance` so that they are consistent and you can auto-complete nicely when typing.

IMO `local-cli` is an OK name. Others might have other ideas?

2019-06-18 15:18 UTC, skshetry commented on tests/acceptance/features/bootstrap/OccContext.php
> +		\system("sudo -u www-data ./occ upgrade", $status);
Use of `sudo` is bad, but don't know any alternatives. But, we previously used to call local occ command. How did we do it previously, @phil-davis ?

2019-06-18 15:21 UTC, skshetry commented on .drone.yml
> +      - make local-test-acceptance-cli
I'd opt for using `TESTING_EXTERNAL` env variable instead of creating targets from makefile, and set that env variable and use tag (eg: `@local-cli`) and skip-tag (`skipWhenTestingExternal` or something similar).

2019-06-18 15:27 UTC, skshetry commented on tests/acceptance/features/bootstrap/OccContext.php
> +		\system("sudo -u www-data ./occ upgrade", $status);
This is how we used to do that: https://github.com/owncloud/core/blob/dac4bf080022d009254ec31a3c6fc8930ab1a0f2/tests/acceptance/features/bootstrap/CommandLine.php#L41-L72

2019-06-19 05:32 UTC, paurakhsharma commented on .drone.yml
> +      - make local-test-acceptance-cli
> I'd opt for using TESTING_EXTERNAL env variable instead of creating targets from makefile

For that we have to remove `--remote` flag from test start script in our `Makefile`.

And I think think that is a good way to do this.
What do you think @phil-davis?

2019-06-19 05:33 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/OccContext.php
> +		\system("sudo -u www-data ./occ upgrade", $status);
Yes we want both `php-dev` server users and `apache` users to be able to use this.

2019-06-21 06:55 UTC, paurakhsharma commented
weird that only two scenarios are passing in drone. Locally all scenarios are passing. 
Looks like last 2 scenarios are failing because there is some problem running `occ` command
in the `AfterScenario` of the second scenario.

2019-06-28 03:06 UTC, individual-it requested changes
looks generally good, I believe we could do it even simpler

2019-06-28 03:06 UTC, individual-it commented on .drone.yml
> +      - TESTING_REMOTE_SYSTEM=${TESTING_REMOTE_SYSTEM:=true}
I don't think we should need that,  `run-sh` still can do all its actions as on a remote system, should not matter because at that time the testing app is active and functional

2019-07-01 05:48 UTC, paurakhsharma commented on .drone.yml
> +      - TESTING_REMOTE_SYSTEM=${TESTING_REMOTE_SYSTEM:=true}
Yes, that's right I had added this for the previous solution. 
This is not required now.

2019-07-01 05:53 UTC, paurakhsharma commented
@skshetry @phil-davis  please review again.

2019-07-01 06:11 UTC, phil-davis approved these changes
Looks good now.
Should we also have tests that put the app in combinations of `apps` and `apps-external` ?
(those could come in a next PR)

2019-07-01 06:35 UTC, individual-it approved these changes

2019-07-01 09:22 UTC, paurakhsharma commented
no code cov 😢 @DeepDiver1975 please merge this.

2019-07-01 10:13 UTC, phil-davis commented
No CLA either ???

2019-07-02 03:40 UTC, phil-davis commented
I rebased. Now the CLA has passed - must have been some GitHub problem the other day.
Let's see if we get drone and codecov results.

2019-07-02 05:30 UTC, merged

2019-07-02 05:34 UTC, paurakhsharma commented
Backport on: #35729