Test regression with public link not created when default expiration date set and enforced
owncloud/core pull request #35594
Opened 2019-06-19 09:42 UTC by skshetry

## Description

This adds a regression test that public link was not getting created when default expiration date was set and enforced.

## Related Issue

- Fixes #35550 

## Motivation and Context

## How Has This Been Tested?

- locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-19 09:43 UTC, skshetry commented
I am currently testing this without the fix in #35564. I'll just remove comments when the tests fail.

2019-06-19 11:33 UTC, micbar commented
@skshetry Fix got merged

2019-06-20 07:26 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +  @issue-35550
```suggestion
  @issue-35550 @public_link_share-feature-required
```

2019-06-20 09:05 UTC, skshetry commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$this->setLastShareData($this->getResponseXml());
I don't know how previous tests were passing without this.

2019-06-20 09:06 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		$this->publicSharingPopup = $this->publicShareTab->updateSharingPopup($this->getSession());
There's no way to get the popup. It's not the best way, but I went with the easiest way.

2019-06-20 11:09 UTC, karakayasemi approved these changes

2019-06-21 07:04 UTC, paurakhsharma commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When /^user "([^"]*)" gets the info of the last public link using the sharing API$/
I think this should go inside `Sharing.php`

2019-06-21 07:05 UTC, paurakhsharma reviewed
Just a small comment, other looks good for me.

2019-06-21 08:37 UTC, HariBhandari07 commented
looks good

2019-06-21 11:02 UTC, individual-it requested changes

2019-06-21 11:02 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When /^user "([^"]*)" gets the info of the last public link using the sharing API$/
why not using `userGetsInfoOfLastShareUsingTheSharingApi()`?

2019-06-21 11:07 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When /^user "([^"]*)" gets the info of the last public link using the sharing API$/
I feel this is *good-enough*, because if I put this in `Sharing.php`:
1. The similar step will exist.
2. Other developers might use this step even though, they should be using other step (due to suggestion from autocompletion).
3. Might need to use xpath on most element (due to responseXml differences).
4. This is only needed for `webUI` stuffs. Keeping on `webUI` prevents step2 from happening and provide isolation.

2019-06-21 11:10 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When /^user "([^"]*)" gets the info of the last public link using the sharing API$/
Creating public links does not set `lastShareData` which `userGetsInfoOfLastShareUsingTheSharingApi` uses. So, I have to manually set.

2019-06-21 11:43 UTC, individual-it requested changes
also fix https://github.com/owncloud/core/commit/aded6395c9f687042ffef1d3d362e98350e6e8d6#diff-7a6686160e3f99113ae6c2c807e63a58R801

I think that is what you are stumbling about.
in `isFieldInResponse` we mostly use data from the last response `$this->getResponseXml()` but for the expiration date we get the data when the share was created `$this->getServerLastShareTime()` this is not correct if the share was created but an other response like
`And the user gets the info of the last share using the sharing API` was done afterwards

2019-06-21 11:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When /^user "([^"]*)" gets the info of the last public link using the sharing API$/
OK, you don't have the id of the share here, get it and then use `userGetsInfoOfLastShareUsingTheSharingApi`

2019-06-25 07:00 UTC, individual-it requested changes

2019-07-01 06:22 UTC, individual-it approved these changes

2019-07-01 06:34 UTC, phil-davis approved these changes

2019-07-01 06:36 UTC, phil-davis commented
@skshetry please make the `stable10` backport.
Then I will look at what acceptance test changes are pending `release-10.2.1` backport and make a PR for those. That will run all these scenarios against `release-10.2.1`

2019-07-01 06:54 UTC, skshetry commented
Backport for `stable10`: #35703

2019-07-01 07:19 UTC, merged