Return false if the rename fails except for connect exceptions
owncloud/core pull request #35598
Opened 2019-06-19 10:06 UTC by jvillafanez

## Description
A failure during the rename operation due to insufficient permissions was causing the storage to be unavailable. In this case, the operation should return false instead of throwing a StorageNotAvailableException

## Related Issue
https://github.com/owncloud/phoenix/issues/1326

## Motivation and Context
It should fail normally instead of blocking the storage

## How Has This Been Tested?
This has been checked with the "old" UI, not with phoenix, although it's expected a similar behaviour.

1. Ensure the file can be edited by the user, but the parent folder is only readable
2. Try to rename a file.

**Note**: it seems the UI behaves badly under these circumstances. There is an error shown, but the "renamed" file disappears. The storage is available, and you can go outside and then inside the folder to make the file reappear again. The "move" http request ends up with a 404 error code.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-19 10:20 UTC, DeepDiver1975 requested changes

2019-06-19 10:20 UTC, DeepDiver1975 commented on apps/files_external/lib/Lib/Storage/SMB.php
> -				$ex = new StorageNotAvailableException($e->getMessage(), $e->getCode(), $e);
This code logic is there in other operations as well. Please double check those locations as well. THX

2019-06-19 12:13 UTC, mmattel commented
@jvillafanez question:
would your change also work in following situation:
client: macos, sync client installed
backend mount to sync to: smb
create a file on macos containing an invalid character for smb like mypicture_2019:06:19.png
when syncing, it tells that storage is not available instead rejecting the sync

2019-06-19 14:16 UTC, jvillafanez commented
It's very likely. In any case, the error isn't caused by the storage not being available but due to invalid chars in the file name.
I'm not fully sure how the client will behave because the changes are currently limited to the storage connector and there are several layers on top of it. This is still under investigation.

2019-06-19 16:11 UTC, jvillafanez commented
Rename UI problem should be fixed with https://github.com/owncloud/core/pull/35598/commits/1799af879aa8eda8c26da3921814eeff0fb52ba9 (checked in the "old" UI, not in phoenix). Throwing a Forbidden exception might not be nice, but I haven't seen a better alternative.

I've also notice that we've been writing information in the cache even though the operation failed. Maybe that has been the cause of ghost entries. They should be fixed with https://github.com/owncloud/core/pull/35598/commits/57807013f30047009a964fef1decc66aeab485cb (pending to be verified, but changes make sense to me)

2019-06-19 16:38 UTC, mmattel commented
> Throwing a Forbidden exception might not be nice, but I haven't seen a better alternative.

Maybe http 422 (Unprocessable Entity) ?
(The response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.)

2019-06-19 16:48 UTC, jvillafanez commented
I think we should throw any of the exceptions in https://github.com/sabre-io/dav/tree/master/lib/DAV/Exception which should be the ones that are expected to be handled by the sabre library (which will be the one handling the request anyway). It's unlikely that any other exception outside of that list will be properly handled.
I'm not familiar with the code around dav, so maybe I'm wrong. In any case I'd wait until @DeepDiver1975 confirms

2019-06-19 17:51 UTC, mmattel commented
FYI, I tried to test on my local Ubuntu 18.04 dev machine with a client installed how your PR works with the client. To the shame of oC, the Ubuntu client is either far out of date (2.4.x and unusable due to bugs) or not manually installable due to broken dependencies. I reported a client issue in central... :face_palm:

2019-06-26 08:40 UTC, jvillafanez commented
I don't think I can improve coverage here. Most of the changes related to the storage can't be unittested, and testing the changes in the view, if possible, is too complex.

2019-06-27 08:52 UTC, DeepDiver1975 approved these changes

2019-06-27 08:54 UTC, DeepDiver1975 commented
> Maybe http 422 (Unprocessable Entity) ?

no - see https://tools.ietf.org/html/rfc4918#section-11.2

422 has a clear definition which does not match to this case.

403 looks reasonable and is consistent with the way we use this exception in other places

2019-06-27 08:54 UTC, merged

2019-06-27 09:11 UTC, jvillafanez commented
Backport in https://github.com/owncloud/core/pull/35683

2019-09-09 05:06 UTC, HariBhandari07 commented
@jvillafanez I are doing the manual testing of this pr. How can I achieve step 1 ```Ensure the file can be edited by the user, but the parent folder is only readable``` of ```How has this been tested?``` . 

When a parent folder is shared with read-only permission the receiver cannot edit the child files.