Improve isFieldInResponse to handle more combinations
owncloud/core pull request #35618
Opened 2019-06-21 07:59 UTC by phil-davis

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-21 08:22 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +	public function isFieldInResponse($field, $contentExpected, $expectSuccess = true, $data = null) {
Note: nothing currently calls this passing `$data` parameter. So we can push it out to parameter 4 without breaking anything.

2019-06-21 08:42 UTC, individual-it requested changes

2019-06-21 08:42 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +				if ($contentExpected == "ANY_VALUE") {
```suggestion
				if ($contentExpected === "ANY_VALUE") {
```

2019-06-21 09:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +				if ($contentExpected == "ANY_VALUE") {
@individual-it I did another refactoring, also putting in plenty of `===`
Please review the whole thing again.

2019-06-21 09:42 UTC, skshetry commented on tests/acceptance/features/bootstrap/Sharing.php
> +	public function isFieldInResponse($field, $contentExpected, $expectSuccess = true, $data = null) {
That's really not the `$expectSuccess`, but provides debug information. And, as it's purpose is to provide debug info, it would be good to push it to the edge, I think.

2019-06-21 09:52 UTC, individual-it approved these changes

2019-06-21 10:22 UTC, skshetry commented on tests/acceptance/features/bootstrap/Sharing.php
> +		if (($contentExpected === "ANY_VALUE")
It was quite difficult to understand previously. Next thing to do would be to not pass `$contentExpected` as string (except, for if we are checking for value). We could encapsulate these on something like `Token` class as static variables.

2019-06-21 10:24 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +		if (($contentExpected === "ANY_VALUE")
or using our `%something%` inline substitutions

2019-06-21 13:31 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +		if (($contentExpected === "ANY_VALUE")
Yes, someday this will need the next refactoring.
e.g. if/when somebody writes a test with usernames `A_TOKEN` and `A_NUMBER` and they want to test that `share_with` field has the actual value `A_NUMBER` :)

2019-06-21 13:35 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +	public function isFieldInResponse($field, $contentExpected, $expectSuccess = true, $data = null) {
It does actually tell the function if the caller is expecting a `true` or `false` return.
If the caller is expecting `true` but the function is about to return `false` then emit some debug info to give clues about why the expected content was not found.
If the caller is expecting `false` but the function is about to return `true` then emit some debug info to give clues about what (unexpected) content was found.

2019-06-21 13:37 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$contentExpected = (string) $contentExpected;
We let the caller pass "mixed" in `$contentExpected` (just because they can anyway).
The responses really only have string values (even if they happen to look like numbers...). So we cast to string here, then can do `===` comparisons in comfort.

2019-06-21 14:58 UTC, merged

2019-06-24 07:56 UTC, phil-davis commented
Backport `stable10` #35622