if user has enough permission, allow to increase permission
owncloud/core pull request #35614
Opened 2019-06-20 15:56 UTC by karakayasemi

## Description
After https://github.com/owncloud/core/pull/35447 merged, it has become that only node owners can increase permissions on a share. It has lead to this regression: https://github.com/owncloud/core/issues/35528

This PR checks Session User's permission on share node. If user has enough permission, it let session user to increase permission of the share.

## Related Issue
- Fixes #35528 

## Motivation and Context
Solving bug.

## How Has This Been Tested?
Followed the scenario described in the issue. Also, we have acceptance tests that are covering bug scenario.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-06-20 16:23 UTC, sharidas approved these changes
LGTM :+1:

2019-06-20 19:00 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			if ($nodeOwner !== $userObj->getUID() && ($allowedPermissions < $permissions)) {
Our permissions have no hierarchy in their values.
Sharing(16) > Write(8) -> does this imply that if a user has share permissions he has automatically write permissions?

2019-06-20 19:01 UTC, DeepDiver1975 requested changes
Please have a look at my comment above - I'm not happy ....

2019-06-20 21:35 UTC, patrickjahns commented
@karakayasemi 
please add unit tests to cover your change and outline intended behavior

2019-06-21 06:00 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			if ($nodeOwner !== $userObj->getUID() && ($allowedPermissions < $permissions)) {
@DeepDiver1975 Thank you for pointing out this. Now, bit-wise operations used in comparison.

2019-06-21 07:55 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +	 * @param int $permissions
This might need extra information. I don't understand where these permissions come from, nor what these permissions are used for.
As far as I know, you're allowed to increase the permissions only if you're the owner, so you have enough information from the user session and the share.

2019-06-21 08:48 UTC, DeepDiver1975 requested changes

2019-06-21 08:48 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			if ($nodeOwner !== $userObj->getUID() && ($permissions & ~$allowedPermissions)) {
Just to be sure - this is identical to https://github.com/owncloud/core/pull/35600/files#diff-faddd9984dfaf09a2b85d8dc4867207aR831

Who ever introduced bitfuxxing to owncloud:  :gun:

2019-06-21 10:42 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			if ($nodeOwner !== $userObj->getUID() && ($permissions & ~$allowedPermissions)) {
yes. Better include at least a comment around so we know what this code is trying to do. It would be better to have function to handle these operations, but it's out of scope.

2019-06-21 11:22 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			if ($nodeOwner !== $userObj->getUID() && ($permissions & ~$allowedPermissions)) {
I moved this logic to `hasEnoughPermissions` method and I singularized this check handling by using this method at least this class wide.

2019-06-21 11:30 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +	 * @param int $permissions
I changed variable name as `newPermissions`.

> As far as I know, you're allowed to increase the permissions only if you're the owner, so you have enough information from the user session and the share.

To fix regression, I have add additional condition to this method and update its phpdoc. Now, if the share node is mounted to Session User's home folder and Session User has enough permission to increase permission, The user can increase permission even he is not owner of the node.

2019-06-21 13:43 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +	private function hasEnoughPermissions($allowedPermissions, $newPermissions) {
`strictSubsetOf` might be a better name. `hasEnoughPermission` might sound like if $allowedPermissions is "read" and $newPermissions is "read+write" it should return true because "read+write" has enough permissions if "read" is allowed

2019-06-21 13:48 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +	private function hasEnoughPermissions($allowedPermissions, $newPermissions) {
changed as `strictSubsetOf`

2019-06-21 13:52 UTC, DeepDiver1975 approved these changes

2019-06-21 13:52 UTC, DeepDiver1975 commented on apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
> +			[\bindec('11111'), \bindec('0111'), true],
:+1:

2019-06-21 13:57 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +	 * @param int $permissions
The problem I have is that I read "*If the user is not the owner of the share*" and I think "*if the method is called "canIncreasePermission" this is fine*" but then I read "*has not enough permission on Node,*" and I don't know what to think. How we can know if the user has or not enough permissions?
There is also a parameter with newPermissions which, just reading the documentation, I don't understand what is used for. Are those the permissions we're expecting to be set later?

My main point here is that, if I already have problems to understand these changes (just a part of it, not all), I'm pretty sure next year I'll have no idea what this code do, and this will be something risky to touch because it isn't clear what the code should be doing (not what the code really does).

Don't be afraid of writing an explanation in the code as long as it helps to understand what the code is doing.

2019-06-24 09:27 UTC, micbar commented
@karakayasemi new tests merged into release branch. Could you rebase?

2019-06-24 09:33 UTC, phil-davis commented
Note: acceptance tests in `master` `stable10` and `release-10.2.1` are all the same. So for getting the first version of this PR reviewed, `master` base should be fine.
Then we also make the backport PRs to `stable10` and `release-10.2.1` and confirm CI is good there also.

2019-06-24 09:35 UTC, micbar commented
@phil-davis @karakayasemi Sorry for my misleading comment.
Anyway, I would give CI a last chance to finish correctly.

2019-06-24 09:36 UTC, patrickjahns commented
@ownclouders rebase

2019-06-24 09:40 UTC, IljaN approved these changes

2019-06-24 10:27 UTC, phil-davis approved these changes

2019-06-24 15:55 UTC, karakayasemi commented
Codecov came for backport PRs. I deleted old codecov report comments. I will try my chance with this way, started a new build.

2019-06-24 20:05 UTC, merged

2019-06-25 04:28 UTC, phil-davis commented
Backports
`stable10` #35634 
`release-10.2.1` #35633