Use Throwable as type hint in the exception callback
owncloud/core pull request #35713
Opened 2019-07-01 12:30 UTC by DeepDiver1975

## Description
Not only exceptions can be thrown at runtime but also Errors. The common interface is \Throwable

## Motivation and Context
Handle Errors properly as well

## How Has This Been Tested?
- add a wrong type declaration in the code which is executed on the webdav endpoint
- see the error page properly popping up

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-01 17:38 UTC, patrickjahns approved these changes
LGTM

2019-07-01 17:38 UTC, patrickjahns commented on apps/dav/lib/Connector/Sabre/FilesPlugin.php
>  	 * @param \Exception $ex
adjust docs

2019-07-01 17:39 UTC, patrickjahns requested changes

2019-07-01 17:39 UTC, patrickjahns commented on apps/dav/lib/Files/BrowserErrorPagePlugin.php
>  	 * @param \Exception $ex
please adjust docs

2019-07-01 17:39 UTC, patrickjahns commented on apps/dav/lib/Files/BrowserErrorPagePlugin.php
>  	 * @param \Exception $ex
please adjust docs

2019-07-02 06:58 UTC, DeepDiver1975 commented
@patrickjahns addressed - THX

2019-07-02 15:58 UTC, patrickjahns approved these changes
LGTM 👍

2019-07-03 06:33 UTC, merged

2019-07-03 06:35 UTC, DeepDiver1975 commented
backport https://github.com/owncloud/core/pull/35748