Add webui test for setting share permissions
owncloud/core pull request #35737
Opened 2019-07-02 09:49 UTC by dpakach

## Description

Add webUI acceptance tests for setting share permissions.

## Related Issue

- Fixes #35732

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-02 09:54 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +					throw new \Exception('not clicked');
```suggestion
					throw new \Exception('The checkbox could not be clicked.');
```

2019-07-03 08:04 UTC, individual-it requested changes
let's not use the skeleton folder here, you only need one folder with one file here

Please note: actually two tests are covered in every scenario:
1. does setting the permissions work correctly
2. does, not having particulat permissions change the UI on the receiver side

theoretically we should do two different tests for that, but this way, we save a lot of CI time

2019-07-03 14:22 UTC, individual-it approved these changes

2019-07-04 05:03 UTC, phil-davis approved these changes

2019-07-04 05:03 UTC, merged

2019-07-04 08:43 UTC, dpakach commented
Backport on #35762