Trigger dav events for the public.php/webdav endpoint
owncloud/core pull request #35759
Opened 2019-07-03 17:02 UTC by jvillafanez

## Description
Trigger events in order to know when the public.php/webdav endpoint is being accessed. The main goal for this is to know when a download through this public endpoint happens.
Note that these events aren't being listened by anyone for now.

## Related Issue
Foundation to solve https://github.com/owncloud/admin_audit/issues/162

## Motivation and Context
This will allow us to know when a file is being downloaded through the public.php/webdav endpoint, or when a file is being uploaded through the same endpoint (assuming enough permissions to do so)

## How Has This Been Tested?
Manual modifications in the code to ensure the events are being triggered

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-10 08:31 UTC, sharidas requested changes
Kindly add php docs for the functions. Other wise it looks ok.

2019-07-10 08:31 UTC, sharidas commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function initialize(Server $server) {
Would be nice to have phpdoc describing about the function

2019-07-10 08:31 UTC, sharidas commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function beforeMethod(RequestInterface $request, ResponseInterface $response) {
Same here

2019-07-10 08:31 UTC, sharidas commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function afterMethod(RequestInterface $request, ResponseInterface $response) {
Same here.

2019-07-10 10:21 UTC, jvillafanez commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function initialize(Server $server) {
done

2019-07-10 10:22 UTC, jvillafanez commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function beforeMethod(RequestInterface $request, ResponseInterface $response) {
done

2019-07-10 10:22 UTC, jvillafanez commented on apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
> +	public function afterMethod(RequestInterface $request, ResponseInterface $response) {
done

2019-07-10 11:05 UTC, sharidas approved these changes
LGTM :+1:

2019-07-11 08:36 UTC, sharidas commented
- Added token to the event.

2019-07-15 06:26 UTC, DeepDiver1975 approved these changes

2019-07-15 06:26 UTC, merged

2019-07-15 07:01 UTC, sharidas commented
Backport PR: https://github.com/owncloud/core/pull/35820