acceptance test for checking shares pointing to deleted groups are not retrieved
owncloud/core pull request #35792
Opened 2019-07-10 04:15 UTC by HariBhandari07

…t retrieved

## Description

Includes api and webui tests to verifiy shares that point to deleted groups are not retrieved.
## Related Issue

- Fixes <issue_link>
https://github.com/owncloud/QA/issues/357
## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-10 04:26 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +     And parameter "shareapi_only_share_with_membership_groups" of app "core" has been set to "yes"
Is this step required here?

2019-07-10 04:26 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +     Then as "user2" file "/textfile0 (2).txt" should not exist
```suggestion
     And as "user2" file "/textfile0 (2).txt" should not exist
```

2019-07-10 04:26 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    Then file "lorem.txt" should be marked as shared with "grp1" by "User One" on the webUI
I dont think this step is required here.

2019-07-10 04:26 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    Then the user "grp1" should not be in share with user list
```suggestion
    And the user "grp1" should not be in share with user list
```

2019-07-10 06:16 UTC, dpakach commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    And the user re-logs in as "user1" using the webUI
```suggestion
    When the user re-logs in as "user1" using the webUI
```

2019-07-10 06:16 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +     And group "grp1" has been deleted
This is a given step, I think a When step should be used here.

2019-07-10 06:34 UTC, skshetry commented on tests/acceptance/features/apiShareManagementBasic/createShare.feature
> +       | user2    |
Share using `user0` to the group and check for both users.

2019-07-10 06:36 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			if ($userOrGroup->find('xpath', $this->userOrGroupNameSpanXpath)->getHtml() === $username) {
Please check if the element is null or not.

2019-07-10 06:36 UTC, skshetry commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			if ($group->find('xpath', $this->userOrGroupNameSpanXpath)->getHtml() === $groupName . " (group)") {
same here

2019-07-15 06:27 UTC, paurakhsharma commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			if ($user->find('xpath', $this->userOrGroupNameSpanXpath)->getText() === $username) {
```suggestion
			if ($expectedUsername->getText() === $username) {
```

2019-07-15 06:29 UTC, paurakhsharma commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
>  		}
please return false here.

2019-07-15 06:31 UTC, paurakhsharma reviewed
Just some minor comments, please have a look.

2019-07-15 06:51 UTC, individual-it requested changes
to fix https://github.com/owncloud/QA/issues/357
we need more checks. We need to check not only if the share is visible at the receivers end but also what the underlying share informations are.
you can do that by sending `GET` to ocs api sharing endpoint `/apps/files_sharing/api/v1/shares`
see https://github.com/owncloud/core/blob/e17ced4cb34bf1cff90a454b677ffdd441d4b59a/tests/acceptance/features/apiShareManagementBasic/createShare.feature#L542

2019-07-15 06:51 UTC, individual-it commented on tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
> +			if ($actualUsername->getText() === $username) {
why changing from `getHtml`? If its needed please confirm it has no side effects and works corrects

2019-07-16 06:28 UTC, individual-it approved these changes

2019-07-17 04:39 UTC, HariBhandari07 commented
backport on https://github.com/owncloud/core/pull/35852

2019-07-17 12:40 UTC, phil-davis commented
restarted drone - master CI should be OK now.

2019-07-17 14:50 UTC, merged