Add acceptance test steps related to trusted server
owncloud/core pull request #35814
Opened 2019-07-12 04:41 UTC by dpakach

## Description

Add Test steps for handling trusted servers.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

API for handling trusted servers was added to the testing app in https://github.com/owncloud/testing/pull/101 along with its test steps. Since there is no other way to add/remote trusted servers other than API these steps are good to have in core.

## How Has This Been Tested?

:robot: 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-12 04:50 UTC, individual-it requested changes
a couple of small comments
where are the tests themself? different PR?

2019-07-12 04:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/AppConfiguration.php
> +			throw new \Exception("The request failed with status $status");
maybe say what request failed

2019-07-12 04:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/AppConfiguration.php
> +				\PHPUnit\Framework\Assert::fail("Given url $url is a trusted server");
```suggestion
				\PHPUnit\Framework\Assert::fail("Given url $url is a trusted server, but should not be.");
```

2019-07-12 04:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/AppConfiguration.php
> +	public function restoreTrustedServers() {
we will have to run that on both remote an local server

2019-07-12 10:46 UTC, dpakach commented
> a couple of small comments
> where are the tests themself? different PR?

The tests will be added in different PR. Tests using these steps are in testing app and are passing locally.

2019-07-12 10:56 UTC, individual-it approved these changes

2019-07-12 12:23 UTC, phil-davis commented
CI failed https://drone.owncloud.com/owncloud/core/19395/618
```
  Scenario: Delete a user, and specify the user name in different case         # /drone/src/tests/acceptance/features/cliProvisioning/deleteUser.feature:16
    Given these users have been created with skeleton files:                   # FeatureContext::theseUsersHaveBeenCreated()
      | username       |
      | brand-new-user |
    When the administrator deletes user "Brand-New-User" using the occ command # OccUsersGroupsContext::theAdministratorDeletesUserUsingTheOccCommand()
    Then the OCS status code should be "100"                                   # OCSContext::theOCSStatusCodeShouldBe()
      OCS status code is not the expected value
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'100'
      +'200'
    And the HTTP status code should be "200"                                   # FeatureContext::theHTTPStatusCodeShouldBe()
    And user "brand-new-user" should not exist                                 # FeatureContext::userShouldNotExist()
```
How did the code in this PR effect that?

Restarting drone CI...

2019-07-12 12:28 UTC, phil-davis approved these changes

2019-07-15 08:36 UTC, merged

2019-07-15 08:41 UTC, dpakach commented
Backport on #35823