Add webui Acceptance test for trusted server in admin settings
owncloud/core pull request #35826
Opened 2019-07-15 15:35 UTC by dpakach

## Description

Add webUI Acceptance test for trusted server in admin settings.

## Related Issue

- Related issue https://github.com/owncloud/QA/issues/22

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-16 07:54 UTC, haribhandari07 reviewed
Looks good

2019-07-16 08:07 UTC, phil-davis commented on tests/acceptance/features/webUISharingExternal/adminSharingSettings.feature
> +  As a administrator
```suggestion
  As an administrator
```

2019-07-16 08:07 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
> +	 * @Then a error message for trusted server should contain :text
Maybe:
```suggestion
	 * @Then a trusted server error message should be displayed on the webUI with the text :text
```

which is similar to `WebUIPersonalGeneralSettingsContext` 
```
Then a password error message should be displayed on the webUI with the text :wrongPasswordMessageText
```

2019-07-16 10:04 UTC, individual-it requested changes
:+1: just more checks if `find` returns `null`

2019-07-16 10:04 UTC, individual-it commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		$btn = $this->find("xpath", $this->addTrustedServerBtnXpath);
need to have checks is find returns `null`
otherwise we will have ugly error messages

2019-07-16 10:51 UTC, individual-it approved these changes

2019-07-16 11:01 UTC, skshetry submitted a review, later dismissed

2019-07-16 11:01 UTC, skshetry commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		return $this;
Why does this return the whole page object? Used anywhere?

2019-07-16 11:05 UTC, dpakach commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		return $this;
Not used currently but I dont think it is a good practice and also doesn't breaks anything.

2019-07-16 11:06 UTC, dpakach commented
Backport on #35842

2019-07-16 11:11 UTC, individual-it commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		return $this;
methods should return pageObjects https://github.com/SeleniumHQ/selenium/wiki/PageObjects

2019-07-16 11:21 UTC, skshetry commented on tests/acceptance/features/lib/AdminSharingSettingsPage.php
> +		return $this;
```
Because we're encouraging the developer of a test to try and think about the services that they're interacting with rather than the implementation, PageObjects should seldom expose the underlying WebDriver instance. To facilitate this, methods on the PageObject should return other PageObjects. This means that we can effectively model the user's journey through our application.
```

We don't chain the methods in our test code. We just use it to interact. Unless we do that, I think, we should stick to the usual standards (if there is) to return void.

2019-07-16 15:54 UTC, phil-davis commented
weird Javascript drone job issue. I restarted the build.

2019-07-17 12:38 UTC, phil-davis commented
Restarted drone - master CI should be fixed now.

2019-07-17 13:59 UTC, merged