acceptance tests for checking the content of public link share
owncloud/core pull request #35926
Opened 2019-07-25 10:57 UTC by HariBhandari07

## Description

Includes webui and api test to check the content of public link share folder
## Related Issue

Fix: https://github.com/owncloud/core/issues/35847

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-07-25 11:12 UTC, individual-it requested changes

2019-07-25 11:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	 * @When the public downloads file :fileName from inside the last public shared folder using the WebDav API
not needed, same step exists already see https://github.com/owncloud/core/pull/35926/files#diff-5f186b9c00c7128af4d5c3c92e08aad1L110

2019-07-25 11:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +	 * @Then the public downloads file :fileName using the webUI
1. we should mention that its from inside a shared folder, otherwise the step looks very similar to `When the public downloads the last created file/folder using the webUI`
2. is that a When or a Then step?
3. would that step work also for other downloads, e.g. in the "normal" file-list? If yes we do not need to mention "the public"

2019-07-25 11:12 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +    And the public downloads file "lorem.txt" using the webUI
When?

2019-07-26 08:14 UTC, individual-it requested changes

2019-07-26 08:14 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
>      Then the downloaded content should be "original content"
add `And all the three links to download the public share should be same`

2019-07-26 08:14 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			throw new Exception("Download link urls are not same");
use an assert, no need to have the complete trace here

2019-07-26 08:15 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then all the three links to download the public share should be same
```suggestion
	 * @Then all the links to download the public share should be the same
```

2019-07-26 08:19 UTC, HariBhandari07 commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
>      Then the downloaded content should be "original content"
We can't use this step here because lorem.txt is listed on the webUI and there's only one download button (top right corner)

2019-07-26 08:44 UTC, phil-davis approved these changes

2019-07-26 09:01 UTC, individual-it approved these changes

2019-07-26 09:28 UTC, HariBhandari07 commented
Backport on https://github.com/owncloud/core/pull/35930

2019-07-26 11:06 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function thePublicDownloadsAllTheSharedDataUsingTheWebui() {
@HariBhandari07 calls to this method need to be renamed

2019-07-26 13:24 UTC, merged