improve description of 'skeletondirectory' key in config.php
owncloud/core pull request #35969
Opened 2019-08-01 14:36 UTC by pako81

## Description
improve wording in the description of 'skeletondirectory' key in config.php

## Motivation and Context
Make the description clearer

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ x] Tests only (no source changes)

2019-08-01 14:41 UTC, voroyam approved these changes

2019-08-01 15:26 UTC, phil-davis approved these changes

2019-08-01 16:45 UTC, micbar approved these changes

2019-08-01 16:47 UTC, micbar requested changes
rebase

2019-08-01 21:12 UTC, voroyam commented
> @pako81 please rebase locally and force-push.
> You need to get the new language translations from master to make CI green.

And there is the extra work I was talking about, @pako81 :)

2019-08-02 07:59 UTC, mmattel commented on config/config.sample.php
> + * The value of this key must not be empty.
Leave empty
Must not be empty

Confusing

2019-08-02 12:10 UTC, voroyam commented on config/config.sample.php
> + * The value of this key must not be empty.
**Directory** empty
**key** not empty 

For me, if the words are in different sentences, it is not confusing because of the dot in between them.

The idea here was to make clear that **empty** is referring to the directory, not the key value. To prevent customers generating errors by putting this in their config.php:

`'skeletondirectory' => '',`

If you have a better suggestion, feel free to add your suggestion :)

2019-08-02 12:44 UTC, pako81 commented on config/config.sample.php
> + * The value of this key must not be empty.
edited description

2019-08-02 21:05 UTC, mmattel commented
Proposal: If the key is set, you must define a valid path. For an empty path, remove the key, else an error is logged.

2020-04-14 11:23 UTC, phil-davis commented
I rebased and resolved conflicts with other edits.
The proposal originally had this text:
```
/**
 * The directory where the skeleton files are located. These files will be
 * copied to the data directory of new users. Leave this directory empty if you do not want to copy any skeleton files.
 * A valid path must be given for this key otherwise errors will be generated in owncloud.log when left empty.
 */
'skeletondirectory' => '/path/to/owncloud/core/skeleton',
```

Now it has:
```
/**
 * Define the directory where the skeleton files are located
 * These files will be copied to the data directory of new users.
 * Leave this directory empty if you do not want to copy any skeleton files.
 * A valid path must be given for this key otherwise errors will be generated in owncloud.log.
 */
'skeletondirectory' => '/path/to/owncloud/core/skeleton',
```

This can be reviewed again.

2020-04-14 14:14 UTC, mmattel approved these changes

2020-04-14 14:32 UTC, phil-davis commented
Assigned myself so that I notice it.

2020-05-12 03:30 UTC, phil-davis commented
@micbar I rebased just now to make sure the diffs here are "correct".
You have a "red" review here. Please review again.

2020-05-12 07:42 UTC, micbar approved these changes

2020-05-12 07:47 UTC, merged