Document phoenix.baseUrl in config.sample.php
owncloud/core pull request #36007
Opened 2019-08-09 10:02 UTC by DeepDiver1975

## Description
The new config parameter phoenix.baseUrl is now documented in config.sample.php

## Related Issue
- refs #35932 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-08-12 14:08 UTC, mmattel commented on config/config.sample.php
> + * url. Phoenix will handle these links accordingly.
But only if the Phoenix App is loaded and enabled...
(Additional, add a comma for better readability: `is set public` --> `is set, public`)
Maybe to tell why this is necessary ? A brief reason would help.

2019-08-12 16:32 UTC, DeepDiver1975 commented on config/config.sample.php
> + * url. Phoenix will handle these links accordingly.
> But only if the Phoenix App is loaded and enabled...

Phoenix can operate independent from owncloud - there is no need in having it installed as an app

2019-08-12 17:29 UTC, mmattel commented on config/config.sample.php
> + * url. Phoenix will handle these links accordingly.
confusing, as there is an app on the marketplace...

2019-08-13 09:46 UTC, DeepDiver1975 commented on config/config.sample.php
> + * url. Phoenix will handle these links accordingly.
To be precise: 
- phoenix can be installed as an owncloud app
- phoenix can be installed on any web space (basically when installed as an app nothing else then serving the web assets is done by owncloud/apache)

2019-08-14 11:01 UTC, settermjd commented on config/config.sample.php
> + * As an example, in case 'phoenix.baseUrl' is set to 'http://phoenix,example.com,
The URL needs a trailing single quote.

2019-08-14 11:02 UTC, settermjd requested changes
Other than the missing, trailing, single quote, it looks good to me.

2019-08-16 10:04 UTC, merged