reverse proxy
owncloud/core pull request #36012
Opened 2019-08-12 09:05 UTC by HariBhandari07

## Description

wip reverse proxy
## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-08-16 04:41 UTC, phil-davis commented on .drone.jsonnet
> +  pipeline.behat(
This is taking about 90 minutes. Split it into 3 parts like for the webUI smoke tests

2019-08-16 08:36 UTC, individual-it requested changes
please try to have the names of the proxy-suites in drone.yml be named something with "proxy"

2019-08-19 03:27 UTC, individual-it commented
tests failed because of some drone issue

2019-08-19 03:30 UTC, individual-it approved these changes

2019-08-19 09:13 UTC, merged