[POC] roles api
owncloud/core pull request #36024
Opened 2019-08-13 13:20 UTC by DeepDiver1975

## Description

The roles api allows clients to ask the server for supported roles.
Currently only roles for public links are implemented.
Apps can listen to the event dispatcher and add their own roles.

The current concept does not reflect any capability for apps to change roles (core or from other apps)

## Related Issue
- refs https://github.com/owncloud/enterprise/issues/3473

## How Has This Been Tested?
- :man_shrugging:

## Screenshots (if appropriate):
```sh
curl http://deepdiver:8080/ocs/v1.php/cloud/roles?format=json  -u admin -H 'Accept-Language: de-DE' | json_pp 
Enter host password for user 'admin':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1301  100  1301    0     0   1848      0 --:--:-- --:--:-- --:--:--  1845
{
   "ocs" : {
      "data" : [
         {
            "id" : "core.viewer",
            "context" : {
               "publicLinks" : {
                  "order" : 10,
                  "permissions" : {
                     "ownCloud" : {
                        "read" : true
                     }
                  },
                  "displayDescription" : "Empfänger können Inhalte sehen und herunterladen.",
                  "resourceTypes" : [
                     "*"
                  ]
               }
            },
            "displayName" : "Herunterladen / Ansehen"
         },
         {
            "displayName" : "Herunterladen / Ansehen / Bearbeiten",
            "context" : {
               "publicLinks" : {
                  "displayDescription" : "Empfänger können Inhalte sehen, herunterladen und bearbeiten.",
                  "resourceTypes" : [
                     "httpd/unix-directory"
                  ],
                  "order" : 20,
                  "permissions" : {
                     "ownCloud" : {
                        "update" : true,
                        "delete" : true,
                        "read" : true,
                        "create" : true
                     }
                  }
               }
            },
            "id" : "core.editor"
         },
         {
            "context" : {
               "publicLinks" : {
                  "order" : 30,
                  "permissions" : {
                     "ownCloud" : {
                        "read" : true,
                        "create" : true
                     }
                  },
                  "displayDescription" : "Empfänger können Inhalte sehen, herunterladen und hochladen.",
                  "resourceTypes" : [
                     "httpd/unix-directory"
                  ]
               }
            },
            "id" : "core.contributor",
            "displayName" : "Herunterladen / Ansehen / Hochladen"
         },
         {
            "displayName" : "Nur Hochladen (File Drop)",
            "context" : {
               "publicLinks" : {
                  "order" : 40,
                  "permissions" : {
                     "ownCloud" : {
                        "create" : true
                     }
                  },
                  "displayDescription" : "Von mehreren Empfängern Dateien empfangen, ohne den Inhalt des Ordners preiszugeben.",
                  "resourceTypes" : [
                     "httpd/unix-directory"
                  ]
               }
            },
            "id" : "core.uploader"
         }
      ],
      "meta" : {
         "status" : "ok",
         "message" : "OK",
         "statuscode" : 100,
         "totalitems" : "",
         "itemsperpage" : ""
      }
   }
}

```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

2019-08-19 13:16 UTC, michaelstingl commented
@felix-schwarz @hosy @TheOneRing Could you have a look?

2019-08-20 06:54 UTC, felix-schwarz commented
The JSON and `Accept-Language`-support checks all the boxes from https://github.com/owncloud/enterprise/issues/2742 that are needed by the iOS client. Looks good to me. 👍

2019-08-20 12:29 UTC, PVince81 requested changes
See minor comments.

I'm missing unit tests for RolesController, at least to check that a few of the roles are returned (does not need to be 100% match).
Also need to test that the AddRoleEvent contents will actually appear in the roles API result.

2019-08-20 12:29 UTC, PVince81 commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +		$ext = isset($pathinfo['extension']) ? '.'.$pathinfo['extension'] : '';
seems the automatic formatter did not decide to add spaces between the "." for concatenation (wenn schon denn schon!)

same for some other reformatting below

2019-08-20 12:29 UTC, PVince81 commented on core/Controller/RolesController.php
> +				'displayName' => $this->l10n->t('Upload only') . ' (File Drop)',
I'd think the "File Drop" should be part of the translation text. I assume this is the pattern we already had and you copied it here.

2019-08-20 21:19 UTC, DeepDiver1975 commented on core/Controller/RolesController.php
> +				'displayName' => $this->l10n->t('Upload only') . ' (File Drop)',
Yes - this was plain copied over from the link dialog.
AFAIK (File Drop) was not translated on purpose because it is a feature/product name and any translation will be :hankey:

2019-08-22 07:38 UTC, PVince81 approved these changes
Looks good to me :+1:

2019-08-22 07:38 UTC, merged

2019-08-26 07:20 UTC, phil-davis commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +				if ($value) {
Changing `$value` to `true` here makes richdocuments tests pass.
See core issue #36090

2019-08-27 11:01 UTC, phil-davis commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +				if ($value) {
This was fixed by PR #36086

2019-10-01 10:49 UTC, settermjd commented
@DeepDiver1975, do you have a code example of how apps can listen to the event dispatcher and add their own roles?

2019-10-01 11:03 UTC, DeepDiver1975 commented
> @DeepDiver1975, do you have a code example of how apps can listen to the event dispatcher and add their own roles?

No app is currently using this - I suggest to leave this undocumented for the time being.
We will extend this - and then really need this - as soon as we are implementing the roles api for collaboration.

I'll let you know as soon as we are at this point. THX

2019-10-01 11:28 UTC, settermjd commented
Thanks for the clarification.