Check status on given steps in Comments and WebDav acceptance test code
owncloud/core pull request #36032
Opened 2019-08-14 11:18 UTC by phil-davis

## Description

## Motivation and Context

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-08-14 12:52 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> -    And user "some-user" has created folder "/simple-folder"
`simple-folder` already exists from the skeleton. This is an unneeded step, and the step gets some `4xx` HTTP status also.

2019-08-14 12:54 UTC, phil-davis commented on tests/acceptance/features/apiMain/quota.feature
> -    And the quota of user "user0" has been set to "10 MB"
The main refactoring in `quota.feature` is to move the setting of limited quota to after any extra files/folders have been uploaded, shared etc. That ensures that the `Given` steps that are setting up the file system of the user do not accidentally fail because the user has limited quota.

2019-08-14 12:56 UTC, phil-davis commented on tests/acceptance/features/apiMain/quota.feature
> +    And the content of file "/testquota.txt" for user "user0" should be "test"
The overwriting attempts happen over-and-over to the same file `testquota.txt`
They should all fail (`507` checked above). And so actually the content of `testquota.txt` should be unchanged.

2019-08-14 12:56 UTC, phil-davis commented on tests/acceptance/features/apiMain/quota.feature
> +    And the content of file "/testquota/testquota.txt" for user "user0" should be "test"
see comment https://github.com/owncloud/core/pull/36032/files#r313858377

2019-08-14 12:56 UTC, phil-davis commented on tests/acceptance/features/apiMain/quota.feature
> +    And the content of file "/testquota.txt" for user "user0" should be "test"
see comment https://github.com/owncloud/core/pull/36032/files#r313858377

2019-08-15 04:41 UTC, individual-it requested changes

2019-08-15 04:41 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> -    And user "some-user" has created folder "/simple-folder"
better to create the user without skeleton

2019-08-15 05:12 UTC, phil-davis commented
@individual-it fixed the scenario - please review again.

2019-08-15 07:00 UTC, individual-it approved these changes

2019-08-15 07:00 UTC, merged