add ocs api for public link share email notification
owncloud/core pull request #36063
Opened 2019-08-19 13:41 UTC by karakayasemi

## Description
This PR adds an OCS API for public link e-mail notifications. old ajax endpoints removed and oc10 adjusted to use the new API.

I aimed to keep the same functionality as oc10. In addition, the current code is simplified by removing redundant post parameters:
- The old endpoint is taking many pieces of information related to the share of link as POST parameter like expiration date, filename, itemType, etc. It is also trying to validate them on the backend. However, we can already extract these parameters by reaching related share object on the backend. So, I considered them redundant and, removed.
- I could not find any usage of `cc` and `bcc` fields in the codebase. So, I removed these options regards to YAGNI principle.
- When `toSelf` parameter is posted, the backend side is only adding user's e-mail to the recipient list. I moved this logic to the client-side and removed `toSelf` from POST parameters.

## Usage
* **URL**
/ocs/v1.php/apps/files_sharing/api/v1/notification/notifypubliclinkwithemail

* **Method:**
  `POST`
  
*  **POST Params**
   **Required:**
   `recipients=[string]`
   `link=[string]`
   `personalNote=[string]`
```
* **Success Response:**
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":[]}}
 
* **Fail Response:**
{"ocs":{"meta":{"status":"error","statuscode":400,"message":"Couldn't send mail to following recipient(s): test@email.com","totalitems":"","itemsperpage":""},"data":[]}}
```
## Related Issue
- Part of #35983

## Motivation and Context
In Phoenix, shared links shall be sent via email. We need an API for that.

## How Has This Been Tested?
- Unit tests are added.
- Manually by sending public link e-mails from the web interface.
- Manually with API call.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-08-19 13:56 UTC, DeepDiver1975 requested changes

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/api/v1/notification/notifypubliclinkwithemail',
maybe kebab style looks better? notify-public-link-by-email
Or pascal notifyPublicLinkByEmail

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +/**
please move to the beginning of the file

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$mailNotification = new MailNotifications(
maybe simplify this be injecting class MailNotifications?

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $recipients
string[] ??

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $link
~This way this API could be used for sending any data to anybody. We might want to change the api to reference a share id and also check if the current use is allowed to access the share.~

2019-08-19 13:56 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $recipients
also add type hint array for this argument

2019-08-19 14:51 UTC, DeepDiver1975 commented
- [ ] The email subject did change. Before this change: 'Admin shared foo.txt with you' After the change: 'Admin shares public link with you' - link name va file name
- [ ] ^ same with the email body
- [ ] unrelated to this change but found while testing: the subject is html escaped - which is bad
![Screenshot from 2019-08-19 16-50-31](https://user-images.githubusercontent.com/1005065/63275290-919cb400-c2a1-11e9-8232-c6bddcc18de1.png)

2019-08-19 15:06 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$mailNotification = new MailNotifications(
If we refactor this class, it will be unit testable. Since Internal email notification part of the code is also using this class. I can move internal email notification to the new controller after refactoring.

2019-08-19 15:14 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $recipients
its type is string. if it has multiple emails, they are separated with a comma. `MailNotifications` class is accepting input in this way. If you prefer in array type, I can refactor it also.

2019-08-20 06:10 UTC, DeepDiver1975 commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $recipients
Please at least add a comment then - THX a lot

2019-08-20 06:11 UTC, DeepDiver1975 commented
- [ ] acceptance tests need to be adjusted I guess - see https://drone.owncloud.com/owncloud/core/20273/76/14

2019-08-20 18:09 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +/**
resolved

2019-08-20 18:11 UTC, karakayasemi commented on apps/files_sharing/appinfo/routes.php
> +			'url' => '/api/v1/notification/notifypubliclinkwithemail',
now it is kebab style.

2019-08-20 18:14 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +	 * @param string $recipients
After refactoring, now it takes `string[]`. Doc updated.

2019-08-20 18:26 UTC, karakayasemi commented
@DeepDiver1975 Reason behind the e-mail subject and, body change is related to my mistake. I mistakenly used `$share->getName()` as file name. Now, I corrected it. Html escape issue is also related to this mistake. Since it's no longer needed, I've reverted your last commit changes.

Acceptance test fail is also related to this mistake. I hope this time, it will pass. Please, review the PR one more time. Thanks.

2019-08-20 18:30 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$mailNotification = new MailNotifications(
`MailNotifications` class is now injectable. Internal sharing email notification mechanism also moved to the new controller. PR description updated to according to this.

2019-08-20 20:30 UTC, DeepDiver1975 commented
> Html escape issue is also related to this mistake. Since it's no longer needed, I've reverted your last commit changes.

If the file name holds e.g. äöü - the subject is not escaped? This issue also existed before this PR - please double check. THX

2019-08-23 11:58 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$node = $nodes[0] ?? null;
`$node = $nodes[0]` ? I don't think we need more than that...
In addition, what happens with the rest of the nodes? Consider to add a comment explainig.

2019-08-23 14:08 UTC, karakayasemi commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$node = $nodes[0] ?? null;
@jvillafanez in the beginning, this pr aimed only to add ocs api for public link email notification. However, I had to refactor `MailNotifications` class to make it injectable and testable. 
The only other consumer of this class was this method.  Since `Share20OcsController` already pretty big, that's why I did not want to inject new dependency to it. To keep the change minimum, I just moved this method from `Share20OcsController` to the new Notification Controller and, adapted the code to use injected `MailNotifications` class. So, I did not interest with the logic behind this method. I guess this node will be used for checking both sender and recipient have this node  :confused:.

2019-08-26 07:04 UTC, jvillafanez commented on apps/files_sharing/lib/Controller/NotificationController.php
> +		$node = $nodes[0] ?? null;
we'll have to check it at some point. It's ok for now.

2019-08-26 07:05 UTC, jvillafanez approved these changes

2019-08-26 13:14 UTC, merged

2019-10-04 12:46 UTC, settermjd commented
@karakayasemi, I've not been able to use the API successfully, as yet. The only response I get is the following:

```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Public link mail notification is not allowed</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

That said, the following two configuration options are in effect:

```php
'shareapi_allow_public_notification' => 'yes',
'dav.enable.tech_preview' => true,
```

Any suggestions?

2019-10-04 13:01 UTC, karakayasemi commented
![image](https://user-images.githubusercontent.com/14157973/66209444-0431e980-e6c0-11e9-90a3-89e8fd4f0875.png)

Please enable the option that I highlighted in the image from admin sharing settings.

2019-10-04 13:03 UTC, settermjd commented
Thanks for the clarification. I had thought that setting the config value would be sufficient.

2019-10-04 13:14 UTC, settermjd commented
It seems I don't have the same version as you do. 

![Screenshot_2019-10-04 Settings - ownCloud](https://user-images.githubusercontent.com/196801/66210239-9f739080-e6b9-11e9-82d7-190097203e1a.png)

2019-10-04 13:15 UTC, settermjd commented
I'm running 10.3.0 alpha2 (cloned from master).

2019-10-04 13:18 UTC, karakayasemi commented
There is another option appearing after allowing users to share via link.