shareowner can edit re-share permissions without any restriction
owncloud/core pull request #36193
Opened 2019-09-12 17:57 UTC by karakayasemi

This is the first PR of related issue. The other PRs do not feel right to me and I returned back to this one. Sorry for all the confusion.

I just made the UserSession nullable in the Manager constructor and adjusted tests. @PVince81 like you said in here https://github.com/owncloud/core/pull/36166#discussion_r323642423, whenever the session user is null, mentioned `if` condition will be disabled in this pr.

## Description
Shareowner should have full permission on re-shares. For detecting re-share, this PR compares the session user UID with the shareowner UID as described in this comment: https://github.com/owncloud/core/issues/36107#issuecomment-525170914. 

## Related Issue
- Fixes #36107 

## Motivation and Context
Fighting with bugs.

## How Has This Been Tested?
Manually with steps in #36107, acceptance tests added and unit tests adjusted.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-09-13 07:22 UTC, jvillafanez commented
Code looks good if this is the final approach we want to take.

2019-09-13 07:33 UTC, karakayasemi commented
No interface change, no confusing part in the code, I guess this is the best one. I would like to continue with this one.

2019-09-13 08:31 UTC, micbar requested changes

2019-09-13 08:31 UTC, micbar commented on lib/private/Server.php
>  			);
Let us inject the user object.

2019-09-13 08:47 UTC, karakayasemi commented
@micbar `User` object injected instead of `UserSession`, let's see what CI will say.

2019-09-13 08:59 UTC, jvillafanez commented
I think there have been cases where the user isn't set yet inside the session during the dependency wiring. In addition, user in the session might change, which will likely cause bugs.

2019-09-13 09:02 UTC, micbar commented
> I think there have been cases where the user isn't set yet inside the session during the dependency wiring. In addition, user in the session might change, which will likely cause bugs.

So injecting the session would be better?

2019-09-13 09:03 UTC, karakayasemi commented
Hmm, @jvillafanez is pointing out a right point. @micbar let's use `UserSession` if you agree.

2019-09-13 09:05 UTC, micbar commented
Vincent and me wanted to have it more clear in the code why we have a session in ShareManager.

We don't need the session, we need the acting user.
The main underlying flaw her IMO is that the ShareManager Class has no visible context. Is it meant to be used as an admin / user / cli ?

2019-09-13 09:05 UTC, micbar commented
But I see your point @jvillafanez

2019-09-13 09:16 UTC, jvillafanez commented
I think we're back to square 1.
The reason we discarded this solution was because of problems in the CLI, because we don't really have a user session there. In practice, we'll have to login and logout with the users while doing things in the CLI. This is why we moved to extending the interface with the "acting user".

2019-09-13 10:21 UTC, karakayasemi commented
Actually, the current behavior of `ShareManager` is logically correct. It does not allow reshares permission higher than the original share permission. But, we want to give privilege to share-owner in this specific case. To implement the desired behavior, we need to compromise from somewhere.

One of the options is changing the interface in a minor release. IMHO, in another interface implementation, our desired behavior can be unwanted. So, I would not identify this `$actinguser` parameter as common in interface wide. So, this option does not feel right to me.

On the injected `IUserSession` option, we will be able to reach our specific desire with being faithful to our interface contract. Share-owner will be able to edit own reshares with his permissions. 
lf `IUserSession` or `User` is null, it indicates CLI or Admin usage and in this situation, `ShareManager` will work with share-owner permissions. In my POV, injecting `UserSession` seems the best option.

2019-09-13 11:47 UTC, karakayasemi commented on lib/private/Share20/Manager.php
> +		$this->userSession = $userSession;
Injecting user seems not possible like explained in this comment: https://github.com/owncloud/core/pull/36193#issuecomment-531159332

2019-09-13 11:47 UTC, karakayasemi commented on lib/private/Server.php
>  			);
Injecting user seems not possible like explained in this comment: #36193 (comment)

2019-09-13 11:47 UTC, karakayasemi commented on lib/private/Share20/Manager.php
> +			$share->getShareOwner() !== $this->userSession->getUser()->getUID()) {
Injecting user seems not possible like explained in this comment: #36193 (comment)

2019-09-13 13:14 UTC, PVince81 approved these changes
:+1: fine by me with the IUserSession approach

2019-09-13 13:15 UTC, micbar approved these changes

2019-09-13 13:25 UTC, jvillafanez approved these changes
Code looks good

2019-09-13 13:27 UTC, merged

2019-09-13 13:28 UTC, micbar commented
@davitol Please test again during RC1 and test `occ transfer-ownership` with a lot of shares and reshares.

2019-10-04 11:39 UTC, HanaGemela commented
Works as expected on the desktop sync client 2.5.4 and 2.6.0 RC1, macOS 10.14.5 and server 10.3.0RC1