only collect shares inside the given path in transfer-ownership command
owncloud/core pull request #36222
Opened 2019-09-26 17:02 UTC by karakayasemi

## Description
`files:transfer-ownership` command is not respecting to the given path when collecting shares for transfer. With this PR it will only collect shares inside the given path. 

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/3520

## Motivation and Context
Even `path` argument given, `files:transfer-ownership` command is trying to transfer all shares of `sourceUser`. This situation causes random errors like mentioned issue.  `files:transfer-ownership` command should only transfer the shares inside of the given folder. 

## How Has This Been Tested?
✋ Manually with following steps:  
- Create at least two user (`user1`, `user2`)
- `user1` creates a folder and fills it with random files.
- `user1` creates a file outside of the created folder and shares this file with `user2`.
- Transfer the created folder with this command;
`./occ files:transfer-ownership --path="folder-path"  user1 user2`

### Expected behavior
- The folder should be transferred without any error messages.

### Current behavior
- There are some errors in console output like `Share with id x points at deleted file, skipping`, because the command is trying to transfer all the shares.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2019-09-27 10:04 UTC, micbar commented
@karakayasemi could you increase coverage?

2019-09-27 10:24 UTC, phil-davis commented on apps/files/lib/Command/TransferOwnership.php
> +						return \strpos($share->getNode()->getPath(), $this->inputPath) === 1;
Without testing myself, I have a suspicion that if:
- the user has 2 folders `sub` and `subfolder`
- both folders contain shares
- someone tries to transfer for `sub`

This will also match `subfolder`, so shares from both will get transferred.

2019-09-27 10:31 UTC, phil-davis commented
> @karakayasemi could you increase coverage?

There is also `tests/acceptance/features/cliMain/transfer-ownership.feature` - hopefully it should be easy to make or adjust acceptance test scenarios to cover this.

2019-09-27 10:35 UTC, micbar commented on apps/files/lib/Command/TransferOwnership.php
> +						return \strpos($share->getNode()->getPath(), $this->inputPath) === 1;
@karakayasemi please investigate.

2019-09-27 10:41 UTC, karakayasemi commented on apps/files/lib/Command/TransferOwnership.php
> +						return \strpos($share->getNode()->getPath(), $this->inputPath) === 1;
@phil-davis Most probably, you are right about your suspicions. I will investigate and fix it. Thank you!

2019-09-27 10:46 UTC, karakayasemi commented
> 
> 
> @karakayasemi could you increase coverage?

The command has not any unit test class. But, I can add tests by using Symfony's `CommandTester` class.

2019-09-27 10:48 UTC, phil-davis commented on apps/files/lib/Command/TransferOwnership.php
> +						return \strpos($share->getNode()->getPath(), $this->inputPath) === 1;
We had to do similar `strpos` path-parsing logic recently in https://github.com/owncloud/core/pull/36170/files - it might give some clues, or you can think of a cleaner way.

2019-09-27 11:30 UTC, micbar commented
> > @karakayasemi could you increase coverage?
> 
> The command has not any unit test class. But, I can add tests by using Symfony's `CommandTester` class.

Yes, there are good examples in other apps.

2019-10-04 08:09 UTC, micbar requested changes
Can you add a unit test where you transfer a subfolder and have another folder with shares which should not be transferred?
Like: testTransferSpecificFolderSkipOthers()

2019-10-04 08:17 UTC, micbar commented
@karakayasemi Could you rebase?
After rebase you will get the new changelog generator templates.
You have the honour to place one of the the first changelog files into [changelog](https://github.com/owncloud/core/changelog/). Just create a folder `unreleased` there if it does not exist and put a file there with your PR as a filename.
Write the changelog into that file according to https://github.com/owncloud/core/blob/master/changelog/TEMPLATE

2019-10-10 09:56 UTC, micbar approved these changes

2019-10-10 09:56 UTC, merged