Add dir/path sharing info
owncloud/core pull request #36254
Opened 2019-10-08 12:16 UTC by felixheidecke

## Description

Adding `getDirShareInfo()` and `getPathShareInfo()` allows getting info about sharetypes in a folder or the whole path down to root.

## Related Issue

https://github.com/owncloud/enterprise/issues/3453 (Discussion)
https://github.com/owncloud/enterprise/issues/3556 (Vis. Concept)

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](../changelog/README.md)

2019-10-08 12:38 UTC, PVince81 reviewed
Looks fine so far, except for the missing docs.

Now to see how this will be used

2019-10-08 12:38 UTC, PVince81 commented on apps/files/js/filelist.js
> +		getDirShareInfo: function(dir) {
missing JS Doc, what does this function do and return ?

2019-10-08 12:38 UTC, PVince81 commented on apps/files/js/filelist.js
> +		getPathShareInfo: function(path) {
JSDoc missing

2019-10-08 12:38 UTC, PVince81 commented on apps/files/js/filelist.js
> +			var parts      = (path === '/') ? ['/'] : path.split('/')
what if path is an empty string ? it happens sometimes...

2019-10-23 12:44 UTC, PVince81 requested changes
See comments.

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> +	position: absolute;
indent

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> +    background-image: url(../img/shareinfo.svg);
any chance to use an existing image / icon class ? else themes will need to override this one additionally

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> +	transform: translateY(5px);
why not use margin instead of transform ?

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> +	content: '"';
adding content with CSS feels hacky, unless there is no better way

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> + * Directory sharing indocator
s/indocator/indicator/

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> + * #927800 - Text dark dirty yellow
assuming these are colors we already used elsewhere ?
also need to remember theming

2019-10-23 12:44 UTC, PVince81 commented on apps/files/css/files.css
> +	float: right;
indent...

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +				$textbox   = $('<span>', { class : "text", text : t('core', 'shared') })
missing `var` for these variables. jslint should have complained ?

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +					$el.fadeOut('fast')
this seems to contract "fadeIn" below.

is the initial state visible or hidden ?
if visible, you can only fade out, not fade in
if hidden, you can only fade in, not fade out

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +			this._setShareTree().then(function() {
let's call those `_updateShareXXX()` because "set" feels like a regular setter which is usually not asynchronous

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +						$.get( OC.linkToOCS('apps/files_sharing/api/v1', 2) + 'shares?' + OC.buildQueryString({format: 'json', path: (dir.path + '/' + dir.name)}), function(e) {
so this is for getting shares for children and not parents ? please add comments for both calls just to clarify which shares (incoming/outgoing/...) we are fetching to avoid confusion

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +			$('#fileList tr td.filename .thumbnail:not(.sharetree-item)').addClass('sharetree-item')
use `this.$el` or similar, please avoid using global access.

also consider that such global access will not work for the "shared with you" and other file lists.
did you test this PR with those ? we should not fetch share info there

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +				if (!$('#app-sidebar').hasClass('disappear')) {
I suggest to extend core/js/apps.js to add a method to check visibility

2019-10-23 12:44 UTC, PVince81 commented on apps/files/js/filelist.js
> +				client.getFileInfo(dir, options).done(function(s, dir) {
when navigating from the top to bottom, are you reloading all shares for all the path sections ?

for example if I'm in "/first" we have already loaded all share information for "/first"
then I navigate into "/first/second": when loading the list we should then only load the share information for "second" as we already have the one for "/first", we can cache it.

2019-10-25 11:10 UTC, felixheidecke commented on apps/files/js/filelist.js
> +				client.getFileInfo(dir, options).done(function(s, dir) {
I was about to lay out the problem(s) I had with none existing folder IDs yet it just came into my mind that I use each path `/first`  ... `/first/second` as the keys.

I'll get to it right away 😸

2019-10-25 11:39 UTC, felixheidecke commented on apps/files/js/filelist.js
> +				client.getFileInfo(dir, options).done(function(s, dir) {
@PVince81 https://github.com/owncloud/core/pull/36254/commits/18ef04c780a4f28cddb6ec7fb4666c80b85f640e#diff-dafefd9519924bec4efa9f5af4af8e68R1789

2019-10-28 15:42 UTC, felixheidecke commented
@PVince81 there is no need to merge it yet, but if the code is fine, we can supply a patch to the customer.

2019-10-28 15:44 UTC, felixheidecke commented on apps/files/js/filelist.js
> +					$el.fadeOut('fast')
this (and the above) will be addressed, if the code comes back.

2019-10-29 08:17 UTC, PVince81 commented on apps/files/css/files.css
> + sharing indicator on the top right is still pending
the code is kept anyway in git history ?

2019-10-29 08:17 UTC, PVince81 commented on apps/files/js/filelist.js
> +		---------------------------------------------------
git history

2019-10-29 08:19 UTC, PVince81 commented on apps/files/js/filelist.js
> +			this.$el.find('#fileList tr td.filename .thumbnail:not(.sharetree-item)').addClass('sharetree-item')
don't match by id, use this.$fileList then, it should already contain the "fileList" element

2019-10-29 08:23 UTC, PVince81 commented on apps/files/js/filelist.js
> +			this.$el.find('#fileList tr td.filename .thumbnail:not(.sharetree-item)').addClass('sharetree-item')
by the way, this won't be enough: what happens if you scroll down and the icon is supposed to be on the second page of results ? please have a test with 100+ items

if it doesn't work you'll likely need to tap into the "fileActionsReady" event which is fired after new elements are appended, and then add the icon in question. see https://github.com/owncloud/core/blob/master/apps/files_sharing/js/share.js#L128

2019-10-29 08:24 UTC, PVince81 commented on apps/files/js/filelist.js
> +							else if (share.share_type === 3) {
`OC.Share.SHARE_TYPE_LINK`. same for the user group share

2019-10-29 08:25 UTC, PVince81 reviewed
Looks fine so far except for the concern about scrolling to the next page where items are rendered dynamically. Once this is solved this could be tested as patch.

Also, before we merge this we must add JS unit tests.

2019-10-30 15:18 UTC, felixheidecke commented
I think we are good for delivering the patch to test. If all is fine, I can get to adding unit tests.

2019-10-31 08:24 UTC, PVince81 commented on apps/files/js/filelist.js
> +					var path = dir.path + glue + dir.name
please note that there are utility functions for joining paths: `OC.joinPaths` that handle slashes

2019-10-31 08:28 UTC, PVince81 reviewed
Apart from the cache purge logic the code looks fine now.

2019-11-12 20:21 UTC, felixheidecke commented
@PVince81 I couldn't keep myself from writing a little event system called OCE, because it made a couple of things much easier, especially catching the initial render of the linklist as you will see.

https://github.com/owncloud/core/pull/36254/files#diff-ffd2df04c44ef2411d4fab6e43174ed2

If we could set an env variable from DEV to PROD and vice versa, we could keep the logging here.

@pmaier1 User/Group and link shares are now separated.

2019-11-13 08:11 UTC, PVince81 commented on core/js/events.js
> +var OCE = {
I disagree with adding yet another event system.

We already have jquery, you can use this on the body element if you need global events. There are places where we already do this, for example in FileActions.

Or if you need something cleaner but local to classes, you can extend the class with Backbone's event system.

2019-11-13 08:16 UTC, PVince81 commented on apps/files/js/filelist.js
> +						self.changeDirectory(currentDir, true);
no risk of infinite loop here ?

2019-11-13 08:16 UTC, PVince81 commented on apps/files/js/filelist.js
> +					if (key > dir) {
seems this is still unsolved ?

2019-11-13 08:16 UTC, PVince81 commented on apps/files/js/filelist.js
> +			OCE.on('linkShareViewRendered', setShareTreeLinkView = function() {
I dislike that these events are global. They should be local to the sharing sidebar panel and the FileList instance has access to the sidebar.

Normally the FileList doesn't know anything about sharing and this "knowledge" is injected by the share.js plugins by extension. Please check whether you can extend this function from inside the share.js plugin instead, the plugin already knows about the sidebar panel so the sidebar panel can trigger events on itself. (it already triggers other events (backbone style) like "sharesUpdated" or something, so use the same approach)

2019-11-13 12:16 UTC, felixheidecke commented on core/js/events.js
> +var OCE = {
😢

2019-11-13 12:24 UTC, felixheidecke commented on apps/files/js/filelist.js
> +						self.changeDirectory(currentDir, true);
The only thing I did was wrapping it in a Promise so I could act after the reload was done.
This seems to have worked for the last 5 years ;-)

2019-11-19 15:12 UTC, micbar commented
@felixheidecke Can you adress the input from @PVince81 ?
And I would be glad about some JS unit tests

2019-11-20 14:31 UTC, felixheidecke commented
@micbar @PVince81 just added the changes as discussed. If the current implementation behaves as desired, I'll add tests.

2019-11-25 12:30 UTC, felixheidecke commented
I added three tests for sharing, yet I can't figure out why this one here calles the fakeServer twice 🤔 

```
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.PublicApp tests File list Uses public webdav endpoint FAILED
        Expected 2 to equal 1.
        apps/files_sharing/tests/js/publicAppSpec.js:97:46
```

2019-11-28 09:13 UTC, phil-davis commented
Added QA-team and acceptance test labels.
@skshetry please delegate someone to make some UI acceptance tests for this.
Needs to just check that the share-indicator icon does (or not) appear when viewing a file, folder, sub-folder, file in folder that is shared.

2019-11-28 09:16 UTC, phil-davis requested changes
Needs some acceptance tests.
I am adding this "request changes" review so that the PR his held until the acceptance tests are done.
QA-team will push a commit with the acceptance tests

2019-11-28 09:26 UTC, skshetry commented
Assigning @kiranparajuli589, for writing the test.

2019-12-06 13:14 UTC, phil-davis commented
See #36534 for a rebased/squashed version of this.

2019-12-08 08:42 UTC, individual-it commented
closing in favour of #36534

2019-12-08 08:42 UTC, closed without merging