Updated config sample files
owncloud/core pull request #36325
Opened 2019-10-23 15:43 UTC by mmattel

## Description
This PR updates the config sample files to fix formatting issues when running the config-to-docs process. With this fix, headlines, line breakes in headlines ect are corrected. In addidtion, based on the fix, a harmonized look and feel is now on all headlines.

## Related Issue
None

## Motivation and Context
Improving docs layout.

## How Has This Been Tested?
Running the config-to-docs process and the antora build afterwards successfully.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

A doc PR with a new update of the config files will be released asap.

2019-10-24 13:49 UTC, settermjd commented on config/config.sample.php
> + * Define the maximum y width for previews.
"y width" isn't necessarily intuitive, at least to me.

2019-10-24 13:53 UTC, settermjd commented on config/config.sample.php
> + * Define MySql 3/4 byte character handling.
A little nitpicky, but _MySql_ should be spelt as _MySQL_.

2019-10-24 14:01 UTC, settermjd commented on config/config.sample.php
> + * Enable or disbale debug logging for SMB access.
"disbale" is misspelled. It should be "disable"

2019-10-24 14:03 UTC, settermjd requested changes
On the whole, it looks fine to me. Just a few small changes required.

2019-10-24 15:34 UTC, mmattel commented
Changes incorporated as requested

2019-10-24 18:39 UTC, mmattel commented
Failing on sqlite tests ...???

2019-10-25 03:02 UTC, phil-davis commented
> Failing on sqlite tests ...??? (@phil-davis can you help)

Needs to pull latest master, rebase to that and force push. CI was broken the last 2 days due to owncloudci/php docker image updates.

2019-10-25 03:27 UTC, phil-davis reviewed
I am not sure whether to write "Define xyz" or "Defines xyz", "Enable or disable xyz" or "Enables or disables xyz". But we should be consistent.

Someone else can decide which form of words to use! Then this can be made consistent throughout the document.

2019-10-25 03:27 UTC, phil-davis commented on config/config.apps.sample.php
> + * Possible values: `ldapIgnoreNamingRules` 'doSet' or `false`.
`doset` has ordinary single quotes, `false` has  back-ticks. Is it supposed to be that way?

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * This unique identifyer is created automatically by the installer.
```suggestion
 * This unique identifier is created automatically by the installer.
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Hardening an ownCloud instance by hiding the version information in `status.php`.
```suggestion
 * This hardens an ownCloud instance by hiding the version information in `status.php`.
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * such as files, documents or calendar ect. You can use a comma-separated list of app names,
```suggestion
 * such as files, documents or calendar etc. You can use a comma-separated list of app names,
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * The Help menue can be found in top right of the ownCloud Web interface.
```suggestion
 * The Help menu can be found in top right of the ownCloud Web interface.
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Enables or disable  avatars or user profile photos
```suggestion
 * Enables or disables avatars or user profile photos
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define the default language of your ownCloud instance
```suggestion
 * Defines the default language of your ownCloud instance
```

What convention are we using throughout this document?
e.g. up to here the first line has said `Defines something` `Indicates something`  rather than `Define something` `Indicate something`

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define the default app to open on user login
```suggestion
 * Defines the default app to open on user login
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Allow or disallow users to change their display names
```suggestion
 * Allows or disallows users to change their display names
```

What do we want to do about boolean options - `Allow or disallow` or `Allows or disallows`

@settermjd what is the "best" to do, then we be consistent?

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define the lifetime of the remember login cookie
```suggestion
 * Defines the lifetime of the remember login cookie
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define the lifetime of a session after inactivity
```suggestion
 * Defines the lifetime of a session after inactivity
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define additional login buttons on the logon screen
```suggestion
 * Defines additional login buttons on the logon screen
```

do we be consistent?

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define the directory where the skeleton files are located
```suggestion
 * Defines the directory where the skeleton files are located
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define excluded files from integrity checking
```suggestion
 * Define files that are excluded from integrity checking
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define excluded apps or themes from integrity checking
```suggestion
 * Define apps or themes that are excluded from integrity checking
```

2019-10-25 03:27 UTC, phil-davis commented on config/config.sample.php
> + * Define memory caching backend for file locking
```suggestion
 * Define the  memory caching backend for file locking
```

2019-10-25 15:12 UTC, mmattel commented
@phil-davis @settermjd many thanks for your suggestions, all incorporated and rebased

2019-10-26 17:29 UTC, mmattel commented
> Needs to pull latest master, rebase to that and force push. CI was broken the last 2 days due to owncloudci/php docker image updates.

@phil-davis I did that. Yesterday and today. Always the same. CI fails and fails ...

2019-10-29 08:33 UTC, phil-davis commented
packagist had problems over the weekend. Nobody in the world was getting reliable fetch of PHP dependencies. Basically CI had a bad week last week, and then this packagist problem over the weekend. I restarted the drone build.

2019-10-29 17:43 UTC, mmattel commented
@settermjd @phil-davis It´s green :smile: could you approve and merge ?

2019-11-04 09:15 UTC, mmattel commented
May I ping ...

2019-11-04 10:51 UTC, phil-davis reviewed
Looking good...

2019-11-04 10:51 UTC, phil-davis commented on config/config.sample.php
> + * Enables or disables  avatars or user profile photos
```suggestion
 * Enables or disables avatars or user profile photos
```

2019-11-04 10:51 UTC, phil-davis commented on config/config.sample.php
> + * Disable or disable the web based updater
```suggestion
 * Disable the web based updater
```

2019-11-04 10:51 UTC, phil-davis commented on config/config.sample.php
> + * Disable or disable the web based updater
A line could be added like:
```
The web based updater is enabled by default.
```

2019-11-04 10:51 UTC, phil-davis commented on config/config.sample.php
> + * Enable or disbale tech previews
```suggestion
 * Enable or disable tech previews
```

2019-11-04 15:22 UTC, mmattel commented
@phil-davis thanks for your comments, rebased, all incorporated

2019-11-05 21:10 UTC, mmattel commented
@settermjd @phil-davis could you review pls, many thanks.

2019-11-06 04:04 UTC, phil-davis approved these changes
Looks good.
@settermjd please also review.

2019-11-11 10:29 UTC, settermjd commented on config/config.apps.sample.php
> + * Define the group name for users allowed to use collabora.
As "collabora" represents a proper noun, it should be written Collabora.

2019-11-11 10:30 UTC, settermjd commented on config/config.sample.php
> +  * The salt used to hash all passwords and is auto-generated by the ownCloud installer.
"The salt used to hash all passwords and" in this sentence seems redundant, because of the preceding sentence.

2019-11-11 10:34 UTC, settermjd commented on config/config.sample.php
> + * Define phoenix base URL
I'd write this as either "Define Phoenix's base URL" or "Define the Phoenix base URL".

2019-11-11 10:36 UTC, mmattel commented on config/config.sample.php
> +  * The salt used to hash all passwords and is auto-generated by the ownCloud installer.
True, but proposing to keep it.
The first line is shown in docs as headline as part of the TOC.
Else, open for a suggestion

2019-11-11 10:36 UTC, settermjd commented on config/config.sample.php
> + * Allows ownCloud to verify a working .well-known URL redirects.
It seems like this sentence should end with "redirect".

2019-11-11 10:37 UTC, settermjd commented on config/config.sample.php
> + * Define logging if cron ran successfully
cron should be written as Cron.

2019-11-11 10:38 UTC, settermjd commented on config/config.sample.php
> + * Define the log rotations size
This isn't quite correct. I suggest "Define the maximum log rotation file size".

2019-11-11 10:39 UTC, settermjd commented on config/config.sample.php
> + * Enable or disable single user mode
Is "single user" hyphenated?

2019-11-11 10:40 UTC, settermjd commented on config/config.sample.php
> + * Define redis connection details
As redis is a proper noun, it should be spelled as: Redis.

2019-11-11 10:42 UTC, settermjd commented on config/config.sample.php
> + * Set this ownCloud instance into debugging mode
I'd use "Place" instead of "Set".

2019-11-11 10:43 UTC, settermjd requested changes
For the most part it looks perfectly fine. Just a few, admittedly nit-picky, changes requested.

2019-11-11 10:50 UTC, settermjd commented on config/config.sample.php
> +  * The salt used to hash all passwords and is auto-generated by the ownCloud installer.
Fair enough

2019-11-11 14:41 UTC, mmattel commented
@settermjd updated and pushed according your suggestions

2019-11-11 18:28 UTC, settermjd approved these changes

2019-11-11 18:28 UTC, settermjd commented
@mmattel, it all looks good to me. @phil-davis, would you mind merging it?

2019-11-11 23:53 UTC, merged