[For 10.4] User group share expiration
owncloud/core pull request #36324
Opened 2019-10-23 14:55 UTC by felixheidecke

## Description

Excerpt from the feature file:

* As a user I want to set an expiration date for collaborators in order to stay in control of access permissions by giving time-based access instead of granting access forever or until I manually remove the collaborator.
* As a user I want to automatically limit my responsibility for a guest account. Guests are bound to being a collaborator. If they are not a collaborator of any resource, they can't log in anymore.
* As an admin I want to set a default expiration date without enforcement to give a recommendation to users and help them maintain control over their resources. Still, I don't want to force or annoy users as some may have reasons to collaborate on resources for a longer or unrestricted amount of time, e.g., in projects.
* As an admin I have to follow corporate policies which dictate that data exchange between employees or also with externals may only take place for a certain maximum amount of time to prevent data leaks by human mistake or negligence.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/2001

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots:
![Anmerkung 2019-11-11 133034](https://user-images.githubusercontent.com/12717530/68587484-82d03280-0487-11ea-8749-1aad9b8f85c1.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-10-24 08:26 UTC, PVince81 reviewed
Had a quick look and it looks fine so far. Might need a deeper review to check corner cases etc.

The part I didn't is where does the expiration field gets added to the UI ?

2019-10-24 08:26 UTC, PVince81 commented on lib/public/Share/IShareProvider.php
> +	const CAPABILITY_STORE_EXPIRATION = 'share expiration';
use camel case maybe as this is not a text to display ?

2019-10-24 08:26 UTC, PVince81 commented on settings/js/admin.js
> +		if (isNaN(value) || (parseInt(value) <= 0) || parseInt(value).toString() !== value) {
always use `parseInt(value, 10)` to avoid octal parsing in case there is a leading zero, see https://stackoverflow.com/questions/850341/how-do-i-work-around-javascripts-parseint-octal-behavior

2019-10-28 15:45 UTC, felixheidecke commented
> The part I didn't is where does the expiration field gets added to the UI ?

I opened @jvillafanez branch so we can keep this PR open for conversation. UI Code is in development.

2019-10-28 17:29 UTC, felixheidecke commented
@jvillafanez 

- [x] "Set default expiration date for user shares" doesn't set a date
- [ ] "Enforce as maximum expiration date"

**Doesn't set the date** 👎 

- [x] "Set default expiration date for user shares" doesn't set a date
- [x] "Enforce as maximum expiration date"

**Set's the date** 👍

2019-10-29 08:10 UTC, jvillafanez commented
> :heavy_check_mark: "Set default expiration date for user shares"
> :x: "Enforce as maximum expiration date"

It should match the behaviour of link expiration in previous ownCloud versions. I think that the default expiration date is just a hint for the frontend, but it won't be set unless explicitly requested by sending that date in the "create" request.
In the case the expiration is enforced, we set the default as maximum because we don't want to set it as "undefined" / "null", which is what happen if the expiration isn't enforced.

That should explain the behaviour. I agree this is kind of weird, but as said it's the same behaviour the link expiration had before, so I think it's better to keep the same behaviour for now.

2019-11-06 12:19 UTC, felixheidecke commented
@jvillafanez in order to update/set the expiration date, the API needs to accept `expiration` as a parameter.

Currently, I get "Wrong or no update parameter given" if I'm trying to PUT `expiration: 2019-11-14T00:00:00+01:00` --> `/ocs/v2.php/apps/files_sharing/api/v1/shares/123?format=json`

2019-11-06 16:38 UTC, PVince81 commented
as discussed, need to fix parameter presence validation in "updateShare" to properly check for "expireDate" additionally to "permissions"

2019-11-07 12:41 UTC, jvillafanez commented
> Currently, I get "Wrong or no update parameter given" if I'm trying to PUT expiration: 2019-11-14T00:00:00+01:00 --> /ocs/v2.php/apps/files_sharing/api/v1/shares/123?format=json

@felixheidecke  did you check with `2019-11-13 00:00:00`? You probably just need the date because you can fill the "00:00:00" easily before sending the info.
It should be compatible with whatever is being used for the link shares.

2019-11-07 13:14 UTC, jvillafanez commented
```
curl -X POST -u admin:Password --data 'shareType=0&shareWith=user1&permissions=19&path=/pic3.jpg&expireDate=2019-11-15 10:00:00' 'http://10.0.2.27:6080/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json'
```
that works, although the time part is ignored. `expireDate=2019-11-15` is enough

2019-11-07 13:45 UTC, jvillafanez commented
> as discussed, need to fix parameter presence validation in "updateShare" to properly check for "expireDate" additionally to "permissions"

I fail to see where the problem is. Backend changes are mostly moving things around, so the same validation we had for links is being applied to both users and groups. Any use case?

2019-11-08 09:53 UTC, felixheidecke commented
I found a little problem with the defaultExpireationDate approach: @PVince81 @jvillafanez 

With links, we have two different states. We are either the add-modal with new links, or the edit-modal with existing links.

**While adding a link**, the default expiration date is displayed in the form where the user would be able to remove it if it's not wanted.

**While editing a link** the expiration date field is empty, as the value is null.

**With user/group shares**, there is only edit. So there is no place to display the recommended default expiration date.

I currently have no solution for this :-/

2019-11-08 10:43 UTC, PVince81 commented
@felixheidecke unrelated note: I had this branch checked out and noticed that we are not using the same date picker element. Did you intend to switch to the same picker element later on ? (I did not see a TODO checkbox for it, that's why I'm asking)

2019-11-08 10:45 UTC, jvillafanez commented
Removing some checks around https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L755 and https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L844 should do the trick I think

2019-11-11 09:05 UTC, felixheidecke commented
> @PVince81  Did you intend to switch to the same picker element later on?

In my current (unpushed) code, I do use the OC default datepicker. It'll be there soon ;-)

2019-11-11 10:07 UTC, felixheidecke commented
@jvillafanez works great, thanks 👍 

I talked with @pmaier1 and we do have a solution for this problem right here --> https://github.com/owncloud/core/pull/36324#issuecomment-551485101

We need to change the behavior for the user/group `defaultExpirationDate` a bit.
As we do not have a confirmation dialog für user/group shares, we do net to set the `expirationDate` in advance. The user then has the remove the unwanted expiration date instead of setting it.

thus solving the problem :-D

@jvillafanez can you do that little change? Just ping me if you have any questions.

2019-11-11 11:27 UTC, jvillafanez commented
> We need to change the behavior for the user/group defaultExpirationDate a bit.
As we do not have a confirmation dialog für user/group shares, we need to set the expirationDate in advance. The user then has the option to remove the unwanted expiration date instead of setting it.

There are some capabilities in place for that, although I think they aren't put in the config model. I'm not sure why there are capabilities copied into the config model, so I didn't touch that part.
(https://github.com/owncloud/core/pull/36324/files#diff-ce11fa52acdfc132e8854ee17e90c873R114-R126)

2019-11-26 11:43 UTC, PVince81 commented on apps/files_sharing/css/sharetabview.css
> +	background-image: url('../../../core/img/actions/close.svg');
don't we have already a reusable CSS class for this icon ?

2019-11-26 11:43 UTC, PVince81 commented on core/js/tests/specs/sharedialogviewSpec.js
> +					share_type: OC.Share.SHARE_TYPE_USER,
add a test for the group enforced ?

also, does it make sense to also test the other possible flags ?

2019-11-26 11:43 UTC, PVince81 commented on lib/public/Share/IShareProvider.php
> +	const CAPABILITY_STORE_EXPIRATION = 'share expiration';
ping

2019-11-26 11:43 UTC, PVince81 commented on settings/js/admin.js
> +		if (isNaN(value) || (parseInt(value) <= 0) || parseInt(value).toString() !== value) {
ping

2019-11-26 16:27 UTC, felixheidecke commented on core/js/tests/specs/sharedialogviewSpec.js
> +					share_type: OC.Share.SHARE_TYPE_USER,
Group enforced happens on the server side only.

I added some tests for USER and GROUPS in here: https://github.com/owncloud/core/pull/36324/files?file-filters%5B%5D=.js#diff-eb4e94032220ff30f56e13ac40197070R1144

2019-11-26 19:58 UTC, felixheidecke commented
@jvillafanez there are some PHP unit test failing :-|
Unfortunately I can't solve these.

2019-11-27 11:40 UTC, felixheidecke commented on apps/files_sharing/css/sharetabview.css
> +	background-image: url('../../../core/img/actions/close.svg');
I didn't find any. Yet, we could use this class in other occurences ... don't you think? I could make it a more general class.

2019-11-27 11:55 UTC, felixheidecke commented
@PVince81 @jvillafanez I did the requested changes as well as gave some feedback to some points.
The php related CI errors need to be adressed.

2019-11-27 13:25 UTC, PVince81 approved these changes
:+1: fine by me if the tests pass now

2019-11-27 13:30 UTC, jvillafanez commented
I think we should retest everything. I've done some changes in the code for the tests, so maybe I've reverted some behaviour. Mainly for https://github.com/owncloud/core/pull/36324/commits/b2e40c76a4ee376a27e3d15daeb090eb2ad60d98#diff-faddd9984dfaf09a2b85d8dc4867207aR754

2019-11-28 09:02 UTC, skshetry requested changes
This is missing tests. Assigning myself for it.

2019-12-04 15:01 UTC, phil-davis commented on core/js/sharedialogshareelistview.js
> +			if (this.configModel.isDefaultExpireDateUserEnforced())
Do group shares also come through here? Does there need to be more logic for the "group" case also?

2019-12-05 09:30 UTC, skshetry commented on core/js/shareconfigmodel.js
> +		isDefaultExpireDateUserEnforced: function() {
yes, the expiration field does not appear for group share, if user share expiration is disabled. cc @phil-davis @felixheidecke

2019-12-05 09:37 UTC, phil-davis commented on core/js/shareconfigmodel.js
> +		isDefaultExpireDateUserEnforced: function() {
@micbar this is the problem mentioned in standup.
IMO, since this is "only" JS, it is probably just in the UI (the UI does not correctly understand that the group expire date should be available to enter). I suspect that API requests will work OK.

2019-12-06 04:15 UTC, phil-davis commented
To all: this PR has 17 commits and is quite out-of-date from master. There are multiple people working on acceptance tests and there will be bugs to fix also. But rebasing and squashing this will cause risk from people maybe re-pushing and old local branch that they have...

PR #36531 has the 17 commits from here rebased and squashed on top of master - that branch is called `feature/user_group_share_expiration`

When doing fixes or test code, please first checkout `feature/user_group_share_expiration` then checkout a new branch from there and make the changes in that new branch. Then we can carefully cherry-pick good new things into `feature/user_group_share_expiration` as they are ready.

2019-12-06 15:07 UTC, micbar commented
@felixheidecke Please investigate.

2019-12-06 17:03 UTC, felixheidecke commented
Fixed via https://github.com/owncloud/core/pull/36535

2019-12-08 05:17 UTC, individual-it commented
closing as its superseded by #36531

2019-12-08 05:17 UTC, closed without merging