New changelog item
owncloud/core pull request #36342
Opened 2019-10-28 07:55 UTC by jvillafanez

## Description
New changelog item

## Related Issue
Linking to https://github.com/owncloud/core/pull/36242

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-10-28 07:59 UTC, micbar requested changes
Please correct the time.

2019-10-28 07:59 UTC, micbar commented on changelog/unreleased/36242
> +This can happen in a DFSr folder, where such folder is visible even though the user doesn't have permissions to read the folder.
The long description needs to be in past tense.

2019-10-28 08:06 UTC, micbar approved these changes
👍

2019-10-28 17:39 UTC, mmattel commented on changelog/unreleased/36242
> +This happened in a DFSr folder, where such folder was visible even though the user didn't have permissions to read the folder.
For better understanding, proposal: `DFSr` --> `DFS Replication (DFSr)`

2019-10-29 08:14 UTC, phil-davis approved these changes

2019-10-29 15:23 UTC, merged