Add new regex config parameter version to blacklisted files and excluded directories
owncloud/core pull request #36360
Opened 2019-11-02 10:57 UTC by mmattel

This PR is based on the work of @tdaget at PR https://github.com/owncloud/core/pull/36331
The referenced PR will be closed because of rebasing issues and CI will never get green there.

## Description
This PR enhances the existing config parameters `blacklisted_files` and `excluded_directories` by a new regex parameter version `blacklisted_files_regex` and `excluded_directories_regex`. 

## Related Issue

- No issue related

## Motivation and Context

Sometimes it is necessary to exclude/blacklist files or directories to be written/renamed/scanned on a more complex parameter than a static version as we have right now. This PR allows eg. to prevent uploading Microsoft Outlook .pst files or creating / renaming / scanning directories based on a pattern. The existing process is not touched but extended only.

## How Has This Been Tested?

Running local

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: Not necessary as doc is part of config.sample.php 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-02 22:34 UTC, tdaget requested changes
An error is located in each preg_match call, regex must be surrounded by `\`. Plus, as regex match is case insensitive an `i` must be added to the end of the string.

In lib/private/Files/Filesystem.php:
It might be: `\preg_match('/'.$item.'/i', $path_part)`

2019-11-02 22:41 UTC, tdaget requested changes
You add a comment for regex variables :
 * INFO: Compare pairs are converted to lowercase by default.

I'm ok for regular variables, for regex the comment might be adapted as things are not simple as a lowercase string.

Maybe :
 * INFO: regex matching is forced case insensitive.

2019-11-02 23:08 UTC, mmattel commented
@tdaget thanks for the comments, both fixed

2019-11-03 17:23 UTC, mmattel commented
@phil-davis can you do me a favour and take a look why CI fails.
I have rebased on latest master (on and on...) and it never gets green.

2019-11-04 00:41 UTC, phil-davis commented
The unit tests fail:
```
There were 3 failures:

1) Test\Files\FilesystemTest::testIsFileBlacklistedRegex with data set #6 ('/etc/dummy/machin.chose', array('.*\.pst$', '.*dummy.*', '^sample.*'), false)
Failed asserting that true matches expected false.

/drone/src/tests/lib/Files/FilesystemTest.php:299

2) Test\Files\FilesystemTest::testIsExcludedRegex with data set #8 ('/foo/_Thomas/Files', array('.*backup.*', 'Thomas.*'), false)
Failed asserting that true matches expected false.

/drone/src/tests/lib/Files/FilesystemTest.php:347

3) Test\Files\FilesystemTest::testIsExcludedRegex with data set #10 ('/foo/_ThomasFoo/Files', array('.*backup.*', 'Thomas.*'), false)
Failed asserting that true matches expected false.

/drone/src/tests/lib/Files/FilesystemTest.php:347
```

2019-11-07 13:41 UTC, mmattel commented
Tests fixed (locally tested), rebased and pushed, CI is green :smile:
@phil-davis can you do a review pls

2019-11-07 13:57 UTC, phil-davis reviewed
Just nits about spelling etc.
Somebody in product management needs to decide if this feature should be added.

2019-11-07 13:57 UTC, phil-davis commented on config/config.sample.php
> + * WARNING: COMPLEX REGEX MAY SIGNIFICANT IMPACT YOUR SCANNING PERFORMANCE.
```suggestion
 * WARNING: COMPLEX REGEX MAY SIGNIFICANTLY IMPACT YOUR SCANNING PERFORMANCE.
```

2019-11-07 13:57 UTC, phil-davis commented on config/config.sample.php
> + * WARNING: COMPLEX REGEX MAY SIGNIFICANT IMPACT YOUR SCANNING PERFORMANCE
```suggestion
 * WARNING: COMPLEX REGEX MAY SIGNIFICANTLY IMPACT YOUR SCANNING PERFORMANCE
```

2019-11-07 13:57 UTC, phil-davis commented on config/config.sample.php
> +	'thomas.*',		// exclude folders with name beginning by 'thomas'
```suggestion
	'thomas.*',		// exclude folders with name beginning with 'thomas'
```

2019-11-07 13:57 UTC, phil-davis commented on config/config.sample.php
> +	'^sample.*',	// disallow file with name beginning by 'sample'
```suggestion
	'^sample.*',	// disallow file with name beginning with 'sample'
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +	 * Regex validy check.
```suggestion
	 * Regex validity check.
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +	private static function regexValidyCheck($regexToBeChecked, $callerMessage='') {
```suggestion
	private static function regexValidityCheck($regexToBeChecked, $callerMessage='') {
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +	 * @param string $callerMessage Message from the calling function to identify where a possible error it is coming from
```suggestion
	 * @param string $callerMessage Message from the calling function to identify where a possible error is coming from
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +			@\preg_match($newItem, null);                         // regex validy check
```suggestion
			@\preg_match($newItem, null);                         // regex validity check
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +			if (self::regexValidyCheck($item, $callerMessage)) {  // check if regex error occur
```suggestion
			if (self::regexValidyCheck($item, $callerMessage)) {  // check if regex error occurred
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +						&& self::regexValidyCheck($item,
```suggestion
						&& self::regexValidityCheck($item,
```

2019-11-07 13:57 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +								'Checked string: '.$path_part)) { // check if regex error occur
```suggestion
								'Checked string: '.$path_part)) { // check if regex error occurred
```

2019-11-07 20:19 UTC, mmattel commented
@micbar @pmaier1 adding you according the suggestion of @phil-davis 
This PR is a great and useful feature, adding good functionality, not breaking an exiting config.
Your review / approval is welcomed.

2019-11-12 11:20 UTC, mmattel commented
@phil-davis CI did not started at all after pushing a rebase this morning? Can you help?

2019-11-12 11:40 UTC, phil-davis commented
> @phil-davis CI did not started at all after pushing a rebase this morning? Can you help?

drone has a huge backlog today. It seems to have missed some triggers from PRs. Rebase again.

2019-11-12 18:44 UTC, mmattel commented
@micbar mind reviewing, CI is green

2019-11-15 09:49 UTC, mmattel commented
squashed and rebased

2019-11-15 10:53 UTC, micbar commented on changelog/unreleased/36325
> +
The title is limited to 80 chars.

2019-11-19 11:10 UTC, mmattel commented
Ping?

2019-12-02 05:45 UTC, phil-davis commented
@micbar IMO this code is OK and the feature works. The next question is will it be accepted into core?

If so, then we can schedule adding a few acceptance test scenarios...

2019-12-19 09:06 UTC, mmattel commented
@micbar ping?

2019-12-19 09:27 UTC, tdaget commented
+1 ...

2019-12-19 11:09 UTC, pmaier1 commented
> @micbar @pmaier1 adding you according the suggestion of @phil-davis
This PR is a great and useful feature, adding good functionality, not breaking an exiting config.
Your review / approval is welcomed.

Great work! Thanks for the contribution. We'd accept it and take it over to the product. Still, we would highly appreciate if you could complete the checklist in the PR template and add the relevant acceptance tests. I think @phil-davis and @micbar can support you with this.

Does this work for you?

2019-12-19 11:15 UTC, phil-davis commented
This is an enhancement, so would need to go in a minor release (according to semver "rules)
So that means either add tests ASAP and get it merged for 10.4, or it will end up waiting "however long" until we do a 10.5 
@micbar comment?

2019-12-19 11:20 UTC, micbar commented
@phil-davis 10.4 is out of scope here. We need to have qa on this first.

@mmattel We have a good general explanation of acceptance tests in our DEV docs.
https://doc.owncloud.com/server/developer_manual/testing/acceptance-tests.html

We can use your contribution. We need to handle it like many other open source projects.
We can decide to merge it but we cannot maintain in on ourselves. So we need your commitment in maintaining this and help testing it.

@phil-davis can assist.

2019-12-19 16:41 UTC, mmattel commented
@micbar @pmaier1 as you know me, I stand for the code I am contributing - since day 1 of my participation. The code always works as expected and wanted and if there is any upcoming issue, I commit maintaining it (btw, this was never necessary in all the years :smile:)

@phil-davis I would appreciate your assistance for the tests

2019-12-19 16:57 UTC, phil-davis commented
@mmattel I am offline all tomorrow, so I can look at the weekend or Monday.
Without having looked closely, there should be acceptance tests for the existing blacklist options and hopefully it is "just" a matter of copy-paste and edit some new scenarios that test the new options using interesting regex.

2019-12-20 17:42 UTC, cdamken commented
Is this already tested with sync-clients?

2019-12-20 19:21 UTC, mmattel commented
@cdamken this is a (regex) extension of the existing blacklist/excluded functionality which is present since ages

2019-12-23 08:28 UTC, phil-davis commented
I rebased and added a commit with various code-review adjustments.
Now I will add some acceptance tests.

2019-12-23 15:45 UTC, phil-davis commented on config/config.sample.php
> +'excluded_directories' => [
```suggestion
'excluded_directories_regex' => [
```

2019-12-27 09:59 UTC, micbar commented
@phil-davis Wow! Impressive amount of Tests!

2019-12-27 10:08 UTC, phil-davis commented
I cherry-picked from https://github.com/owncloud/core/pull/36643 where I added some upload tests for the existing options, so it looks more than it is.

I still need to add tests for webDAV move/delete/copy etc. I have those already in core master now for the existing features, so in theory I just copy-paste the scnearios and adjust them to have some example regex. Hope to do that in the next hours...

2019-12-27 17:44 UTC, phil-davis commented
@micbar I have completed acceptance tests for this. The new regex features work.

Somebody could give a technical review of the source code changes.

@individual-it can do a review of the acceptance tests.

If this is approved, then we could also cherry-pick this back into release-10.4 branch so it can get released.

In making tests for the existing blacklist and excluded directories features, I discovered https://github.com/owncloud/core/issues/36645 - in "old" "v1" chunking uploads the blocked uploads return a 507 (rather than 403). The uploads are blocked - so that existing issue is not so important. Similar behaviour happens in the new regex features.

2019-12-30 10:39 UTC, individual-it reviewed
tests look good
we could move them all over to a separate feature file though

2019-12-30 12:52 UTC, phil-davis commented
I created issue #36654 for the reorganisation of feature files, because that impacts more than just the scenarios in this PR

2020-01-02 09:57 UTC, phil-davis commented
Rebased and resolved conflict

2020-01-02 10:02 UTC, phil-davis approved these changes

2020-01-03 10:14 UTC, merged

2020-01-03 10:40 UTC, karakayasemi commented on lib/private/Files/Filesystem.php
> +				foreach ($path as $path_part) {
please use camel case for variable names.

2020-01-03 10:40 UTC, karakayasemi commented on lib/private/Files/Filesystem.php
> +			$exclude_folders = $ed;
please use camel case for variable names.

2020-01-03 10:40 UTC, karakayasemi commented on lib/private/Files/Filesystem.php
> +		$blacklist_files = \array_unique($blacklist_files);
To prevent code duplication, we can move these assignments to a private function. But, I am not sure is it worth. It is up to writer.

2020-01-03 10:40 UTC, karakayasemi commented on lib/private/Files/Filesystem.php
> +		// force that the last element (possibly the filename) is an array
This line is confusing, the last element of `$path_parts` is string, not an array. As far as understand, what is meant here, the last element of `$path_parts` should be holded on an array to easy comparison or I am misunderstanding.

2020-01-03 10:40 UTC, karakayasemi commented on config/config.sample.php
> +'excluded_directories_regex' => [
Should not this only apply to directories? As far as I see, we are also applying it to files.

2020-01-03 11:01 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +	* @param array $ed is only used in conjunction with unit tests as we handover here the blacklisted / excluded
I will call it `$excluded`
Note: it was already called `$ed` before this PR

2020-01-03 11:01 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +			$exclude_folders = $ed;
PR incoming to fix the var naming.

2020-01-03 11:17 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +		// force that the last element (possibly the filename) is an array
I have rewritten the comment a bit. PR incoming.

2020-01-03 11:24 UTC, phil-davis commented on lib/private/Files/Filesystem.php
> +		if (isset($exclude_folders)) {
Hmmm - I am not even sure why this test is here - there is already code above that always sets `$exclude_folders` - so the code inside this `if` will always be run.
I will remove the unneeded if in all 4 places.

2020-01-03 12:14 UTC, mmattel commented on lib/private/Files/Filesystem.php
> +	* @param array $ed is only used in conjunction with unit tests as we handover here the blacklisted / excluded
It was named `$ed` because of the currently not available constructor in tests and not to get confused by all the other `$excluded` variables below. Maybe better to give it a more meaningful name like `$excludedTest` ... ?

2020-01-03 12:15 UTC, phil-davis commented
See #36694 and #36695 for the changes to address the review comments