[WIP]
owncloud/core pull request #36384
Opened 2019-11-06 13:40 UTC by VicDeo

## NOT ready for review - i'm just checking how many existing tests will fail

## Description
Allow sharing with guest users when `Restrict users to only share with users in their groups` option is enabled

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/3578

## Motivation and Context
To be filled by O.E.M.

## How Has This Been Tested?
To be filled by O.E.M.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-07 10:28 UTC, jvillafanez commented
We might need to consider to create a `UserTypeDetection` class or similar at least to move this code to a place. It isn't the first place we try to detect if a user is a guest, and it won't be the last.

2019-11-07 16:20 UTC, micbar commented
looks promising.

2019-11-08 07:30 UTC, karakayasemi commented on lib/private/Share20/Manager.php
> +				return;
Returning from here misses the rest of the userCreateChecks like already shared path check. I guess, we can change the upper if condition to something like the below condition instead of returning: 
`if ($this->shareWithGroupMembersOnly() && !$userTypeHelper->isGuestUser($sharedWith->getUID()))`

2019-11-08 07:32 UTC, karakayasemi reviewed
I am not familiar with the Guest app concept, so I am not sure of the concept. In terms of code, rest of the things are good.

2019-11-08 07:46 UTC, karakayasemi commented on lib/private/Share20/Manager.php
> +			if (empty($groups) && !$userTypeHelper->isGuestUser($sharedWith->getUID())) {
I know, it is not a big deal about performance, but if the user is a guest, no need to make any calculation about group intersection. Because of that, moving this check to one upper level is better in terms of performance.

2019-11-08 07:46 UTC, karakayasemi requested changes
I know, it is not a big deal about performance, but if the user is a guest, no need to make any calculation about group intersection. Because of that, moving this check to one upper level is better in terms of performance.

2019-11-08 08:15 UTC, micbar approved these changes

2019-11-08 08:19 UTC, karakayasemi approved these changes

2019-11-08 08:25 UTC, jvillafanez commented on lib/private/Helper/UserTypeHelper.php
> +	public function __construct(IAppManager $appManager = null, IConfig $config = null) {
include a comment explaining why the appManager and config can be null.

2019-11-08 08:25 UTC, jvillafanez commented on lib/private/Helper/UserTypeHelper.php
> +		if ($guestsAppEnabled) {
should the method return true for the guest user even if the app is disabled? I find it weird that a user is reported as guest, but then, after disabling the app, the user isn't a guest any longer.

2019-11-08 08:25 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +		$userTypeHelper = new UserTypeHelper();
this should be injected

2019-11-08 10:01 UTC, merged