[API] user-sync OCS API
owncloud/core pull request #36428
Opened 2019-11-13 19:16 UTC by micbar

## Description
External user provisioning system need an http api to trigger user-sync for a specific user.

### Authorization
The http API can only be executed by a user with admin priviledges. Suggestion is to create a technical user who is in the admin group

### Route
```sh
 curl -X POST http://localhost:8080/ocs/v2.php/cloud/user-sync/admin -v -u admin

```

### Response
- 200 - if sync was executed
- 404 - given userId is unknown
- 409 - mutliple users have been found for the given user id - not unique user criteria

## Related Issue
- refs https://github.com/owncloud/enterprise/issues/3521

## How Has This Been Tested?
- user curl command as above with an admin user

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-13 19:18 UTC, micbar commented
@phil-davis Now you can add the acceptance tests to this branch.

This is a breaking change for the next minor version.
We will do the full QA here before merging.

2019-11-14 06:40 UTC, dpakach commented
@micbar @DeepDiver1975 , I have added acceptance tests for checking the cases when there are not any external user backends. Some status codes seem out of place. Please have a look

2019-12-02 06:04 UTC, phil-davis commented
> @micbar @DeepDiver1975 , I have added acceptance tests for checking the cases when there are not any external user backends. Some status codes seem out of place. Please have a look

@micbar @DeepDiver1975 please have a look at the added acceptance test scenarios and see if any of the failure codes need to be adjusted/made more consistent.

2019-12-02 06:06 UTC, phil-davis commented
@dpakach I don't think we ever sorted out how to add a "happy path" acceptance test for this in the `user_ldap` tests. Can link post here about how far you got (or link to a comment somewhere)?

We really need to have a "happy path" test passing somewhere.

2019-12-02 06:41 UTC, dpakach commented
> @dpakach I don't think we ever sorted out how to add a "happy path" acceptance test for this in the `user_ldap` tests. Can link post here about how far you got (or link to a comment somewhere)?
> 
> We really need to have a "happy path" test passing somewhere.

@phil-davis I tried doing that but could not make work. Either there is some problem in my configuration or some bug. I had created the issue https://github.com/owncloud/core/issues/36312. 
I think those tests should be added in user_ldap.

2019-12-02 08:27 UTC, DeepDiver1975 commented
> @micbar @DeepDiver1975 please have a look at the added acceptance test scenarios and see if any of the failure codes need to be adjusted/made more consistent.

I'm not that deep into the acceptance tests these days - I see you as the lead dev on these topic @phil-davis .

Regarding the tests not working properly I cannot add more then I did on https://github.com/owncloud/core/issues/36312
We have this API live in production for weeks now and it works - with an ldap backend.

2019-12-02 08:40 UTC, phil-davis commented
> Regarding the tests not working properly I cannot add more then I did
NP - I will look with @dpakach and our guys

2019-12-03 05:03 UTC, phil-davis commented on tests/acceptance/features/apiMain/userSync.feature
> +      | 2               | 500             | 500              |
`500` is not a nice status code. Should be `401` "unauthorized" or `403` "forbidden"?

2019-12-04 11:43 UTC, phil-davis commented on tests/acceptance/features/apiMain/userSync.feature
> +    | 2               | 200             |
@micbar @DeepDiver1975 ping - should this be adjusted?

2019-12-04 11:43 UTC, phil-davis commented on tests/acceptance/features/apiMain/userSync.feature
> +      | 2               | 500             | 500              |
@micbar @DeepDiver1975 ping - should this be adjusted?

2019-12-04 13:06 UTC, DeepDiver1975 submitted a review, later dismissed

2019-12-04 13:06 UTC, DeepDiver1975 commented on tests/acceptance/features/apiMain/userSync.feature
> +      | 2               | 500             | 500              |
500 is not an acceptable status code - I suspect there is an exception raised in this case which fully is thrown back to the client. Please have a look and adjust - THX

2019-12-04 13:06 UTC, DeepDiver1975 commented on tests/acceptance/features/apiMain/userSync.feature
> +    | 2               | 200             |
Technically speaking a sync is also possible on a local user - if reasonable is a different story ;-)

From my pov this is okay to keep it as is. THX

2019-12-05 11:27 UTC, phil-davis commented on tests/acceptance/features/apiMain/userSync.feature
> +      | 2               | 500             | 500              |
@DeepDiver1975 (cc: @micbar ) who is supposed to be doing "Please have a look and adjust"?
Is there a dev allocated somehow? Or is it me?

2019-12-05 13:10 UTC, DeepDiver1975 commented
Feel free to fix right away, Phil

2019-12-05 14:25 UTC, phil-davis commented
Note: I rebased just now so that we have this on top of the latest master.

2019-12-06 06:35 UTC, phil-davis commented
> Feel free to fix right away, Phil

@micbar I have lots to do, and I do not see easily how to fix/catch this `500` status code.

`NotAdminException` is thrown - I guess in `SecurityMiddleware.php` and that should be caught somewhere and turned into a nicer HTTP status like 403.

Strangely, I do not see other examples of places where it is currently being caught.

Some developer will know what to do in 5 minutes (maybe)?

2019-12-06 12:06 UTC, micbar commented
Thanks @sharidas . Let us see what CI says.

2019-12-06 12:07 UTC, micbar commented
@phil-davis @skshetry The response Code is not 403 Forbidden.

2019-12-06 12:21 UTC, phil-davis commented
> @phil-davis @skshetry The response Code is now 403 Forbidden.

I suspect that this will be a more general fix that might catch other places where we test sending an API request to an admin-only endpoint, but with only authentication of an ordinary user. Probably the status codes will now be better. There might be some test expectations to adjust (improve) when we see the CI result.

2019-12-17 04:15 UTC, phil-davis commented
I rebased just now to make sure this is up-to-date and passing.

2019-12-19 12:57 UTC, phil-davis reviewed
Tests are OK here, as far as they go.
We will need to work out a way to do a manual test of this with LDAP set-up, because I never managed to get the user_ldap CI setup to successfully do a user sync through this API.
Someone else needs to approve the actual code.

2019-12-19 13:08 UTC, VicDeo requested changes
Looks good, just some minor changes

2019-12-19 13:08 UTC, VicDeo commented on core/Controller/UserSyncController.php
> +				return new Result([], 409, "Multiple users returned from backend($backEndName) for: $userId. Cancelling sync.");
`\OC\AppFramework\Http::STATUS_CONFLICT` ?

2019-12-19 13:08 UTC, VicDeo commented on core/Controller/UserSyncController.php
> +		return new Result([], 404, "User is not known in any user backend: $userId");
`\OC\AppFramework\Http::STATUS_NOT_FOUND` ?

2019-12-19 13:08 UTC, VicDeo commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +			} elseif ($exception instanceof  NotAdminException) {
two spaces in `instanceof  NotAdminException`

2019-12-19 13:25 UTC, micbar commented on core/Controller/UserSyncController.php
> +		foreach ($this->userManager->getBackends() as $backEnd) {
@VicDeo Variable Name?

2019-12-19 13:29 UTC, phil-davis commented on core/Controller/UserSyncController.php
> +		foreach ($this->userManager->getBackends() as $backEnd) {
I guess he means the variable can be called `$backend`

2019-12-19 13:31 UTC, jvillafanez commented on core/Controller/UserSyncController.php
> +			$users = $backEnd->getUsers($userId, 2);
If I remember correctly, we had already problems if there are users with the similar name. What if we have "Scott", "Scotty", "Scott_A"... and we want to sync "Scott"? Even if we have only one "Scott" in the system, I think the method will return an error.

2019-12-19 13:31 UTC, jvillafanez commented on core/Controller/UserSyncController.php
> +			if (\count($users) === 1) {
we can save the count in a variable to avoid counting the same data twice.

2019-12-19 13:31 UTC, jvillafanez commented on core/Controller/UserSyncController.php
> +				$this->syncService->run($backEnd, new ArrayIterator([$users[0]]));
I'm not sure if we should consider external timeouts (if syncing one LDAP user for example), or apache timeouts (for the worst possible case sync scenario). Probably not needed for now because I guess the worst normal case would be around 5-10 secs per user and we only sync one.

2019-12-19 13:31 UTC, jvillafanez commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +				return $controller->buildResponse(new Result(null, $exception->getCode(), $exception->getMessage()));
The exception doesn't explicitly says that the error code should be an HTTP code, and it doesn't guarantee it. We should at least include a comment saying that we expect an HTTP code as the error code of the exception.

2019-12-19 22:14 UTC, micbar commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +			} elseif ($exception instanceof  NotAdminException) {
elseif not necessary IMO, another if could be clearer.

2019-12-19 22:19 UTC, micbar commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +				return $controller->buildResponse(new Result(null, $exception->getCode(), $exception->getMessage()));
The docblock of the parent method mentions that the return value is a http Response object. Isn't that sufficient?

2019-12-19 22:28 UTC, micbar commented on lib/private/User/SyncService.php
> +			if ($callback) {
done

2019-12-19 22:29 UTC, micbar commented on core/Controller/UserSyncController.php
> +		return new Result([], 404, "User is not known in any user backend: $userId");
done

2019-12-19 22:29 UTC, micbar commented on core/Controller/UserSyncController.php
> +				return new Result([], 409, "Multiple users returned from backend($backEndName) for: $userId. Cancelling sync.");
done

2019-12-19 22:29 UTC, micbar commented on core/Controller/UserSyncController.php
> +			if (\count($users) === 1) {
done

2019-12-19 22:30 UTC, micbar commented on core/Controller/UserSyncController.php
> +				$this->syncService->run($backEnd, new ArrayIterator([$users[0]]));
thanks for pointing out. As @DeepDiver1975 was mentioning, this code is running on a production system since months without issues.

2019-12-19 22:32 UTC, micbar commented on core/Controller/UserSyncController.php
> +			$users = $backEnd->getUsers($userId, 2);
You mean it will throw an exception? Or return an empty value?

2019-12-20 11:52 UTC, VicDeo commented on lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
> +				return $controller->buildResponse(new Result(null, $exception->getCode(), $exception->getMessage()));
`NotAdminException` has a code `Http::STATUS_FORBIDDEN` so it looks ok from my side...
https://github.com/owncloud/core/blob/master/lib/private/AppFramework/Middleware/Security/Exceptions/NotAdminException.php#L37

2019-12-20 11:54 UTC, VicDeo approved these changes

2019-12-20 11:57 UTC, merged

2020-05-26 08:31 UTC, phil-davis commented
Note: acceptance test added in https://github.com/owncloud/user_ldap/pull/562