New option in files_external:list --mount-options
owncloud/core pull request #36420
Opened 2019-11-12 21:43 UTC by mmattel

## Description

Adding a new option for the `files_external:list` command `--mount-options`.
Using `--mount-options` shows all mount options independent the fact if they are default or not.
I came across when working on #36397 where I wanted to see if an option is set or not.

```
./occ files_external:list  --output=json_pretty
[
    {
        "mount_id": 2,
        "mount_point": "\/ttt",
        "storage": "SMB \/ CIFS",
        "authentication_type": "Username and password",
        "configuration": "host: \"filer\", share: \"swwindows\", root: \"\", domain: \"mydomain\", user: \"martin\", password: \"***\"",
        "options": "",
        "applicable_users": "All",
        "applicable_groups": ""
    }
]
```
```
./occ files_external:list  --mount-options --output=json_pretty
[
    {
        "mount_id": 2,
        "mount_point": "\/ttt",
        "storage": "SMB \/ CIFS",
        "authentication_type": "Username and password",
        "configuration": "host: \"filer\", share: \"swwindows\", root: \"\", domain: \"mydomain\", user: \"martin\", password: \"***\"",
        "options": "encrypt: true, previews: true, filesystem_check_changes: 1, enable_sharing: false, encoding_compatibility: false",
        "applicable_users": "All",
        "applicable_groups": ""
    }
]
```
**NOTE:** during testing, I found a bug in the  `json`/ `json_pretty` output when using option `--all` causing a php error. This is now fixed.

## Related Issue

## Motivation and Context

Helps identifying which options are present and in which state independent if they are set to default or not.

## How Has This Been Tested?

Running local

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: will be made on merge 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-13 06:27 UTC, mmattel commented
CI is :nauseated_face:

2019-11-13 14:35 UTC, tboerger commented on changelog/unreleased/36420-1
> +Bug: Fix a php error of occ command files_external:list --output=json respectively --output=json_pretty
Fixes should not be put together with a new feature.

2019-11-13 14:38 UTC, mmattel commented on changelog/unreleased/36420-1
> +Bug: Fix a php error of occ command files_external:list --output=json respectively --output=json_pretty
You are right. It was not intended to find this issue, but is was a very easy win I took with only a minimum of changes.

2019-11-15 10:31 UTC, micbar requested changes

2019-11-15 10:31 UTC, micbar commented on changelog/unreleased/36420
> +Enhancement: Adding a new option in occ command files_external:list --mount-options
@mmattel The title should not exceed 80 chars

2019-11-15 10:31 UTC, micbar commented on changelog/unreleased/36420-1
> +Bug: Fix a php error of occ command files_external:list --output=json respectively --output=json_pretty
Same as above

2019-11-15 10:31 UTC, micbar commented on apps/files_external/lib/Command/ListCommand.php
> +				'Show all mount options even they are set to default'
missing "if"

2019-11-19 11:09 UTC, mmattel commented
Ping ?

2019-11-19 11:19 UTC, micbar approved these changes

2019-11-19 13:50 UTC, merged