Request->getHeader('Authentication') returns ''
owncloud/core pull request #36465
Opened 2019-11-22 16:17 UTC by butonic

causes ugly to debug bugs

2019-11-22 16:30 UTC, DeepDiver1975 requested changes
Code style 🤷

2019-11-22 16:35 UTC, tomneedham commented on apps/dav/lib/Connector/Sabre/Auth.php
> +				($this->userSession->isLoggedIn() && $this->session->get(self::DAV_AUTHENTICATED) === $this->userSession->getUser()->getUID() && ($request->getHeader('Authorization') === null || $request->getHea
Missing a closing `)` :)

2019-11-24 19:36 UTC, micbar commented
@butonic Can you push again? I need to release 10.3.2 on monday.

2019-11-25 08:55 UTC, DeepDiver1975 approved these changes

2019-11-25 12:17 UTC, merged