[WIP] Objectstore transfer2
owncloud/core pull request #36464
Opened 2019-11-22 13:29 UTC by jvillafanez

## Description
Superseeds https://github.com/owncloud/core/pull/36326 , which was having problems and was reverted (in https://github.com/owncloud/core/pull/36460)

## Related Issue
https://github.com/owncloud/enterprise/issues/3520

## Motivation and Context
Fix the original issue as well as additional problems found (which caused the revert)

## How Has This Been Tested?
`occ files:transfer-ownership` still works with shares without problems.
In addition, checked the following scenario which was failing with the previous PR:
1. Create 2 users and make sure both users use different S3 buckets (in a multibucket setup)
2. user1 creates a folder "foo1" and shares it with user2
3. user1 uploads a file in his root folder
4. user1 moves the uploaded file into the shared folder ("file1.txt" -> "foo1/file1.txt")
5. Check that the file is moved without a problem and that user 2 can access to the shared file.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-22 14:47 UTC, phil-davis commented
To test against this with `files_primary_s3` we will also need to revert the `markTestSkippedIfMultiBucketObjectStorage()` changes, so that the test actually runs in object storage.

2019-11-24 19:37 UTC, micbar commented
> To test against this with `files_primary_s3` we will also need to revert the `markTestSkippedIfMultiBucketObjectStorage()` changes, so that the test actually runs in object storage.
> 
> Update: drone CI was green here, so I pushed `Revert "Skip testTransferAllFiles when on ObjectStoreStorage"` so I can try from `files_primary_s3`

Ok, sounds like progress.

2019-11-25 08:00 UTC, phil-davis commented
https://github.com/owncloud/files_primary_s3/pull/271#issuecomment-558036641
All 9899 core unit tests are passing - great start!

2019-11-26 04:07 UTC, phil-davis commented
@jvillafanez I rebased this just now so that it has all the things that happened in core master related to getting `files_primary_s3` CI green.

Now I will run this from `files_primary_s3` and see the result.

2019-11-28 13:37 UTC, jvillafanez commented
Moving to review because the tests pass and there is no additional development planned (unless bugs happen)

2019-11-28 14:04 UTC, micbar requested changes
needs changelog item

2019-11-28 15:10 UTC, micbar approved these changes

2019-11-28 18:37 UTC, karakayasemi approved these changes
The code looks good. I just added some small suggestions that caught my attention while reading.

2019-11-28 18:37 UTC, karakayasemi commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +			if (!isset($this->movingBetweenBuckets[$this->getBucket()]['paths'][$path])) {
we can also move `$mimeType` and `$stat` assignment to the inside of this condition.

2019-11-29 08:24 UTC, jvillafanez commented on lib/private/Files/ObjectStore/ObjectStoreStorage.php
> +				unset($this->movingBetweenBuckets[$this->getBucket()]);
The above method is for the source storage. We still need to clear the current storage.
Note that we need to prevent cache changes in both the source and target storages.

2019-12-02 06:18 UTC, phil-davis commented
@micbar IMO this should be OK for 10.4 - if so, please add it to the 10.4 project.
Then we can rebase it (to be sure!) and I will run the `files_primary_s3` CI against it again to check that all is well.

2019-12-05 11:23 UTC, phil-davis commented
I rebased and squashed the commits just now. Let's see what CI says here in core, and in https://github.com/owncloud/files_primary_s3/pull/271 (which I just pushed again to run this core code with files_primary_s3)

2019-12-05 14:30 UTC, phil-davis approved these changes

2019-12-05 14:31 UTC, phil-davis commented
CI passed in https://github.com/owncloud/files_primary_s3/pull/271 so this is good from a QA PoV.
@micbar feel free to override the codecov result and merge if it is OK with you.

2019-12-05 14:39 UTC, merged