user is only allowed to see their own home trashbin
owncloud/core pull request #36488
Opened 2019-11-28 12:01 UTC by karakayasemi

## Description
User is only allowed to see their own home trashbin.

## Related Issue
- Fixes #36378

## Motivation and Context
Trashbin API had allowed users to see the trashbin content of other users. This bug has been resolved.

## How Has This Been Tested?
Followed #36378's reproduce steps. Also, acceptance tests already cover this issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-11-28 12:16 UTC, karakayasemi commented on apps/dav/lib/TrashBin/RootCollection.php
> +			return new SimpleCollection($name);
Acceptance tests were expecting 401, as HTTP status code. I could throw a `NotAuthenticated` exception for this purpose. However, throwing an exception is violating the contract of the parent class abstract method. Because of that, I preferred to return `SimpleCollection` and adjust acceptance tests to expect 404 as the HTTP status code.

2019-11-30 02:19 UTC, phil-davis reviewed
Looks good from QA acceptance test point of view

2019-11-30 02:19 UTC, phil-davis commented on changelog/unreleased/36488
> +Bugfix: Fix Trash-bin api to no allow users to see trash-bin content of other users
```suggestion
Bugfix: Fix Trash-bin api to not allow users to see trash-bin content of other users
```

2019-12-02 06:21 UTC, phil-davis commented
@micbar this needs a developer technical review of the code, then IMO it can be merged for 10.4 release.

2019-12-02 10:28 UTC, DeepDiver1975 requested changes

2019-12-02 10:28 UTC, DeepDiver1975 commented on apps/dav/lib/TrashBin/RootCollection.php
> +		$sessionUser = \OC::$server->getUserSession()->getUser();
inject user session here - better unit testing capabilities then at the end

2019-12-02 10:28 UTC, DeepDiver1975 commented on apps/dav/lib/TrashBin/RootCollection.php
> +			throw new NotAuthenticated();
shall we log something here?

2019-12-02 10:28 UTC, DeepDiver1975 commented on apps/dav/tests/unit/TrashBin/RootCollectionTest.php
> +		\OC::$server->getUserSession()->setUser($user);
user session should be mocked

2019-12-02 10:28 UTC, DeepDiver1975 commented on changelog/unreleased/36488
> +Trash-bin API had allowed users to see the trash-bin content of other users. This bug has been resolved.
since this is a bug fix I assume that 'This bug has been resolved' - not needed sentence from my pov

2019-12-03 05:24 UTC, karakayasemi commented on apps/dav/lib/TrashBin/RootCollection.php
> +		$sessionUser = \OC::$server->getUserSession()->getUser();
UserSession injected to class.

2019-12-03 05:26 UTC, karakayasemi commented on changelog/unreleased/36488
> +Trash-bin API had allowed users to see the trash-bin content of other users. This bug has been resolved.
'This bug has been resolved' sentence removed.

2019-12-03 05:36 UTC, karakayasemi commented on apps/dav/lib/TrashBin/RootCollection.php
> +			throw new NotAuthenticated();
I looked at similar classes, generally, we do not log anything in RootCollections, I could not find specific things to log. If you have any suggestions, I can add it.

2019-12-05 11:04 UTC, phil-davis commented
@DeepDiver1975 or somebody - review again, and we can merge?

2019-12-06 07:47 UTC, DeepDiver1975 approved these changes

2019-12-06 07:47 UTC, merged