Use ICacheIterator to retrieve ICacheEntry child entries
owncloud/core pull request #36496
Opened 2019-11-29 17:28 UTC by mrow4a

**Results for const memory iteration:**
childrenIterator 23068672 B
childrenIterator  for 1000 entries before after 23068672 B

**Result for putting all entries in memory:**
getFolderContents before 23068672 B
getFolderContents  for 1000 entries before after 25165824 B

2019-12-02 07:18 UTC, DeepDiver1975 requested changes
No generator? Am i looking at the wrong PR?

2019-12-02 07:18 UTC, DeepDiver1975 commented on lib/private/Files/Cache/CacheChildrenIterator.php
> +		$this->mimetypeLoader = \OC::$server->getMimeTypeLoader();
Inject please

2019-12-02 08:33 UTC, mrow4a commented
> No generator? Am i looking at the wrong PR?

@DeepDiver1975 @jvillafanez there are few reasons why not to use generator after my investigation:
- if you run query with `LIMIT ~ OFFSET 0`, if you use generator to do `fetch()`, first call will return to the driver WHOLE result anyways - https://www.php.net/manual/en/pdostatement.fetch.php (cursor orientation and scrollable cursor behaviour). To prevent allocating whole RESULT space in memory, we would need to use Scrolling Cursor enabled, which is not available e.g. for MySQL as this cursor type would allow scroll also backwards. You will also need to be able to manipulate PDO configuration, which is not possible in current implementation of `Database Connection` class.
- because of no Scrolling Cursor, the only way to achieve constant memory is by fetching data in batches of const memory using `LIMIT 512 OFFSET 0 where fileid > [last-seen-fileid]`. This is why I decided on implementing `\Iterator` interface, which in the background fetches data in batches  when triggered on certain Iterator calls to `iterator->next()`.  
- `\Iterator` forces developer to implement properly interfaces responsible for iterating over single record of the data (batching in memory), while generator you will need to do hacks to retrieve queries after 512 records.
- `\Iterator` class in php is inheriting `\Traversable`, can be iterated with foreach, like a normal array (cannot however be used with index access, count and other ArrayAccess interfaces as this is exactly what we want to prevent).

2019-12-02 08:43 UTC, DeepDiver1975 commented
I see - thanks for clarification! 

I'd still suggest to add all this to a new method and not change the current impl of Cache::getFolderContentsById - just as a risk prevention action.

2019-12-22 18:49 UTC, mrow4a commented
Closing, would require too high refactor, and only few places could benefit

2019-12-22 18:49 UTC, closed without merging