Add validation for sender email address
owncloud/core pull request #36505
Opened 2019-12-02 12:58 UTC by pako81

## Description

This PR adds validation for the sender e-mail address when using the e-mail notification mechanism for public links as well as internal shares.

## Motivation and Context

Given the following scenarios:

Scenario 1:

- User1 shares a folder with User2
- User1 does not have an e-mail address (`NULL` set in oc_accounts table)
- User2 have a valid e-mail address
- User1 clicks on the `notify by email` button: an error appears and the user cannot be notified

Scenario 2:

User1 (who does not have an email address) creates a brand new file or folder, creates a public link out of it and clicks on the `Send link via email` button in order to notify an external user. Also, in this case, the same error as above is returned.

## How Has This Been Tested?

Manually by testing the two scenarios above and make sure no error is returned and e-mail is correctly delivered. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised 
- [ ] Changelog item

2019-12-02 13:03 UTC, pako81 commented
@owncloud/qa would be good to have this covered by tests.

2019-12-02 14:57 UTC, phil-davis commented
code style is failing, looks like indent issues - see https://drone.owncloud.com/owncloud/core/21653/2/6
do:
```
make test-php-style-fix
```

2019-12-02 14:58 UTC, phil-davis commented
@micbar if you think this can get into 10.4 then please add to the 10.4.0 project and we can add some acceptance tests this week.

2019-12-02 15:00 UTC, micbar commented
@phil-davis Done.

2019-12-02 15:03 UTC, phil-davis commented
@HariBhandari07 please assign someone to write some relevant acceptance test scenarios

2019-12-03 10:19 UTC, micbar commented
@pako81 Can you add a changelog file
https://github.com/owncloud/core/blob/master/changelog/TEMPLATE
https://github.com/owncloud/core/blob/master/changelog/README.md

2019-12-03 17:30 UTC, karakayasemi commented on lib/private/Share/MailNotifications.php
> +			if (empty($replyTo)) {
I thought we can write a method to avoid code duplication similar to `getFrom` method of the same class. Something like;
````
/**
 * @param string $senderMailAdress
 * @return string
 */
protected function getReplyTo($senderMailAdress) {
	if(empty($senderMailAdress)) {
		return Util::getDefaultEmailAddress('sharing-noreply');
	}
	return $senderMailAdress;
}
````

2019-12-03 20:32 UTC, pako81 commented on lib/private/Share/MailNotifications.php
> +			if (empty($replyTo)) {
Thanks for the suggestion! It looks indeed cleaner this way, I have implemented the changes.

2019-12-04 02:33 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/21690/3/7
```
------ ----------------------------------------- 
  Line   lib/private/Share/MailNotifications.php  
 ------ ----------------------------------------- 
  186    Undefined variable: $senderMailAdress    
  267    Undefined variable: $senderMailAdress    
 ------ ----------------------------------------- 

 [ERROR] Found 2 errors                                                         
```

2019-12-04 02:34 UTC, phil-davis commented
@HariBhandari07 please be careful adding a commit with tests. This branch is still being force-pushed so it will be easy for your commit/code to get lost. Maybe work in a branch on top of this.

2019-12-04 09:50 UTC, phil-davis commented
@pako81 the acceptance tests added by @HariBhandari07 have disappeared with your force push.
We need to first pull whatever is on GitHub, then make changes and push.

@HariBhandari07 please find your local commit with the tests and add it again to this PR.

2019-12-05 08:48 UTC, karakayasemi approved these changes
Code looks good.

2019-12-05 08:52 UTC, phil-davis approved these changes

2019-12-05 08:54 UTC, phil-davis requested changes
I will squash the commits.

2019-12-05 09:00 UTC, phil-davis approved these changes

2019-12-05 11:02 UTC, merged

2019-12-05 11:04 UTC, pako81 commented
thanks @phil-davis @micbar @karakayasemi  @HariBhandari07 !