Make settings page work in Phoenix
owncloud/core pull request #36506
Opened 2019-12-02 16:56 UTC by PVince81

## Description
Adjust CSP rules to allow iframing.
Receive "phoenix=true" URL parameter to signal that we're coming from
Phoenix.
Remove page header when in Phoenix mode.
Use different URLs for navigation sections.

## Related Issue
For https://github.com/owncloud/phoenix/issues/2598

## Motivation and Context
Make settings page accessible without leaving Phoenix frontend

## How Has This Been Tested?
Manual test, try switching sections, etc

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-12-02 17:04 UTC, PVince81 commented
The links in the navigation have been modified in this PR to point back to Phoenix, if the phoenix param was passed.

I was thinking that maybe we rather need a Router decorator that rewrites OC URLs to Phoenix, this way we're able to better catch those routes. Route rewriting will also need to work on the JS side...

2019-12-02 17:19 UTC, PVince81 commented
- [ ] find a way to redirect to Phoenix when opening settings page URL directly ? (like from the desktop client)

2019-12-02 18:47 UTC, DeepDiver1975 requested changes
To be honest i dislike the approach to circumvent csp by supplying a request Parameter.
It actually breaks the idea of csp.
With this we allow any Client to bypass iframing....

2019-12-03 08:33 UTC, PVince81 commented
> To be honest i dislike the approach to circumvent csp by supplying a request Parameter.
> It actually breaks the idea of csp.
> With this we allow any Client to bypass iframing....

I considered that approach and decided against it already.
The CSP rule condition is only based on whether Phoenix exists in the config.php, so we can use that URL and add it to the CSP whitelist

2019-12-10 08:55 UTC, PVince81 commented
Abandoned, see https://github.com/owncloud/phoenix/issues/2598#issuecomment-563932184

2019-12-10 08:55 UTC, closed without merging