Folder open issue
owncloud/core pull request #36521
Opened 2019-12-04 10:06 UTC by kiranparajuli589

## Description
Added acceptance test to assert presence of share indicator for shared/received shares on different pages on the webUI

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then following resources should not have share indicators on the webUI
```suggestion
    Then the following resources should not have share indicators on the webUI
```
Adjust the step definition

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then following resources should have share indicators on the webUI
```suggestion
    Then the following resources should have share indicators on the webUI
```

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: user receives a share from another user and view that received share in files page and shared-wih-you page when auto-accept-share is enabled
```suggestion
  Scenario: user receives a share from another user and views that received share in files page and shared-wih-you page when auto-accept-share is enabled
```

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And the user has shared folder "simple-folder" with user "User Two" using the webUI
Use API "given" steps to make the share, then you do not have to login and re-login

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: shares a sub folder and view the received share form files page and shared-with-you page
```suggestion
  Scenario: share a sub folder and view the received share from files page and shared-with-you page
```

2019-12-04 10:31 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: shares a sub folder and view the shared resource form files page and shared-with-others page
```suggestion
  Scenario: share a sub folder and view the shared resource from files page and shared-with-others page
```

2019-12-04 10:40 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then following resources should not have share indicators on the webUI
:rocket:

2019-12-04 10:43 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Then following resources should have share indicators on the webUI
:rocket:

2019-12-04 10:44 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: user receives a share from another user and view that received share in files page and shared-wih-you page when auto-accept-share is enabled
:rocket:

2019-12-04 10:52 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And the user has shared folder "simple-folder" with user "User Two" using the webUI
:rocket:

2019-12-04 10:53 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: shares a sub folder and view the received share form files page and shared-with-you page
:rocket:

2019-12-04 10:54 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And the user has shared folder "simple-folder" with user "User Two" using the webUI
I've a question...
If I use API "given" steps to create shares, then the "when" part in the scenario would be only `to open` those shared resources. Is that OK?

2019-12-06 04:45 UTC, individual-it requested changes

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		Assert::assertEquals(true, $isMarked, "Expected: " . $fileOrFolder . " to be marked as shared but found: " . \strval($isMarked));
to long line

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		Assert::assertEquals(false, $isMarked, "Expected: " . $fileOrFolder . " not to be marked as shared but found: " . \strval($isMarked));
to long line

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function folderShouldNotHaveShareIndicatorOnTheWebUI($fileOrFolder, $filename) {
```suggestion
	public function ressourceShouldNotHaveShareIndicatorOnTheWebUI($fileOrFolder, $filename) {
```

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @param TableNode $resourceTable table headings: must be: |name|
that is not true, header is not needed

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/lib/FilesPage.php
> +	public function isShareIndicatorPresent($fileName) {
move the searching of the indicator to fileRow page object
to find that specific file row use `$this->findFileRowByName()`

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +<<<<<<< HEAD
??????

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> -    Then file "lorem.txt" with path "" should be listed in the shared with others page on the webUI
don't change this existing test if its still valid

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/lib/SharedByLinkPage.php
> +	public function findFileRowByNameAndPath($name, $path, Session $session) {
I don't think we should need this function

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given the setting "Automatically accept new incoming local user shares" in the section "Sharing" has been enabled
I think this is default, so should not need it

2019-12-06 04:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    and shared-by-link page
why is that in a new line?

2019-12-06 10:44 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/SharedByLinkPage.php
> +	public function findFileRowByNameAndPath($name, $path, Session $session) {
I've reverted everything mess i'd made as this PR is not really concerned about this!
But we've to look into it some other time!

2019-12-06 10:45 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> -    Then file "lorem.txt" with path "" should be listed in the shared with others page on the webUI
I've reverted everything back to as it was!
:rocket:

2019-12-06 10:51 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		Assert::assertEquals(true, $isMarked, "Expected: " . $fileOrFolder . " to be marked as shared but found: " . \strval($isMarked));
condensed!
:rocket:

2019-12-06 10:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function folderShouldNotHaveShareIndicatorOnTheWebUI($fileOrFolder, $filename) {
done
:rocket:

2019-12-06 10:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		Assert::assertEquals(false, $isMarked, "Expected: " . $fileOrFolder . " not to be marked as shared but found: " . \strval($isMarked));
shortened!
:rocket:

2019-12-06 10:53 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @param TableNode $resourceTable table headings: must be: |name|
yup!
:rocket:

2019-12-08 11:42 UTC, individual-it commented
closing in favour of  #36534

2019-12-08 11:42 UTC, closed without merging