Add sample OIDC configuration to the sample app config file
owncloud/core pull request #36526
Opened 2019-12-05 11:46 UTC by settermjd

## Description

Add sample OIDC (OpenID Connect) configuration to the sample app config file

## Related Issue

- Relates to https://github.com/owncloud/docs/issues/2100

## Motivation and Context

## How Has This Been Tested?

- 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)
- [X] Documentation

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-12-05 12:02 UTC, DeepDiver1975 requested changes

2019-12-05 12:02 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> +    'provider-url' => '',
following are missing (they are optional aka come with reasonable defaults) - never the less
```
'autoRedirectOnLoginPage' => false,
  'mode' => 'userid',
      'search-attribute' => 'sub',
      'use-token-introspection-endpoint' => true
```

- autoRedirectOnLoginPage (default is false) - if true the login page will automatically be redirected to the idp (just like the button is pressed)
- use-token-introspection-endpoint (default is false) - there are tokens which are not JWT and information like the expiry cannot be read from the token it self. In these cases the IdP needs to be called on the token introspection endpoint to get this information
- mode (default is 'email' - alternative value: 'userid') - this is the attribute in the owncloud accounts table to search for users
- search-attribute (default: 'email') - this is the claim from the OpenID user info which shall be used for searching in the accounts table

2019-12-05 12:09 UTC, settermjd commented on config/config.apps.sample.php
> +    'provider-url' => '',
Thank you for the further information.

2019-12-05 13:22 UTC, settermjd commented on config/config.apps.sample.php
> +    'provider-url' => '',
The four parameters have been added to the documentation.

2019-12-09 05:32 UTC, phil-davis reviewed
Language looks OK. I am not qualified to know if the detailed content is correct/complete.

2019-12-09 15:11 UTC, mmattel commented
@DeepDiver1975 :wave: mind to re-review so we could merge ?
Because of other changes in config.sample.php, a config-to docs run needs to be done and I want to do it in one shot...

2019-12-11 08:34 UTC, DeepDiver1975 requested changes

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * Configure OIDC OpenID Configuration
duplication OIDC is OpenID Connect - and it is "OpenID Connect" not OpenID - this is something totally different

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * OIDC Configuration
following https://en.wikipedia.org/wiki/OpenID_Connect

We might want to write "OpenID Connect(OIDC)"

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * taken from the OpenID Provider's setup. The `loginButtonName` variable can
OpenID Connect

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * OpenID Provider does NOT support service discovery.
add Connect

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * If true, the login page will automatically be redirected to the IdP, as when
IdP -> OpenID Connect Provider - for the sake for clarity

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * This is the claim from the OpenID user information which shall be used for
add Connect

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * There are tokens which are not JWT and information like the expiry cannot be
JWT -> JSON WebToken(JWT)

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * read from the token itself. In these cases, the IdP needs to call on the
IdP -> OpenID Connect Provider

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> +    // Only required if the OpenID Provider does not support service discovery
add Connect

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * This is the claim from the OpenID user information which shall be used for
ref for claims - https://openid.net/specs/openid-connect-core-1_0.html#Claims

2019-12-11 08:34 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> + * There are tokens which are not JWT and information like the expiry cannot be
ref token introspection -> https://tools.ietf.org/html/rfc7662

2019-12-12 10:19 UTC, phil-davis commented
@settermjd I don't see where changes have been pushed yet

2019-12-12 10:40 UTC, DeepDiver1975 requested changes
please respect given comments - THX

2020-01-18 13:23 UTC, mmattel commented
@settermjd 
Because these config values belong to a particular app which are not part of core or part of apps bundled with core in the tar file, you need to write which app is needed for these config values.
```
/**
 * OIDC Configuration  (Which App??)
 */
```
Please see the examples in the file. If there is no app needed, you have to move this to the standard config.sample file into the correct section.

2020-01-22 09:01 UTC, mmattel commented
@settermjd ping, any update?

2020-01-27 10:53 UTC, DeepDiver1975 submitted a review, later dismissed
Looks good now - THX

- [ ] squash
- [ ] make drone happy (code style is wrong)

2020-01-27 11:43 UTC, mmattel commented on config/config.apps.sample.php
> +    'mode' => 'userid',
@deepdiver are there other modes than `userid` ? or is this a single fixed value.
In case of other possible values, which are they and when to chose?

2020-01-27 11:44 UTC, mmattel commented on config/config.apps.sample.php
> +    'search-attribute' => 'sub',
@deepdiver are there other modes than sub? or is this a single fixed value.
In case of other possible values, which are they and when to chose?

2020-01-27 11:45 UTC, mmattel commented on config/config.apps.sample.php
> +    'use-token-introspection-endpoint' => true,
@DeepDiver1975 what happens if false?
In case of other possible values, which are they and when to chose?

2020-01-27 11:47 UTC, mmattel commented on config/config.apps.sample.php
> +        'authorization_endpoint' => '...',
@DeepDiver1975 why do we write `'...'` where above we only have  `''` does not look consitent

2020-01-27 11:50 UTC, DeepDiver1975 commented on config/config.apps.sample.php
> +        'authorization_endpoint' => '...',
ask @settermjd not me ...

2020-01-27 11:56 UTC, mmattel commented on config/config.apps.sample.php
> +        'authorization_endpoint' => '...',
ah, ok. so no prerequisite.

@settermjd do you have a reason for?
I think using dots are not that good

2020-01-27 14:42 UTC, settermjd commented
> Looks good now - THX
> 
>     * [ ]  squash
> 
>     * [ ]  make drone happy (code style is wrong)

shall do.

2020-01-27 14:47 UTC, settermjd commented on config/config.apps.sample.php
> +        'authorization_endpoint' => '...',
It might have been a carry-over from the notes that I was given to use. I'll edit the reference shortly.

2020-01-27 15:28 UTC, settermjd commented on config/config.apps.sample.php
> +        'authorization_endpoint' => '...',
Done.

2020-01-27 16:10 UTC, micbar commented
@settermjd please use the shorthand array format `[]` instead of `array()`

2020-01-31 08:47 UTC, phil-davis commented
@settermjd ping
This likely only needs you to make minor fixes and squash.

2020-02-04 09:37 UTC, phil-davis approved these changes

2020-02-04 10:03 UTC, mmattel approved these changes

2020-02-04 10:40 UTC, merged