Test: User group share expiration
owncloud/core pull request #36525
Opened 2019-12-05 06:43 UTC by skshetry

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-12-06 16:18 UTC, individual-it commented
taking over this PR for now

2019-12-06 16:27 UTC, skshetry commented on tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature
> -      | shareWith   | grp1              |
@individual-it, these were accidentally removed.

2019-12-06 16:30 UTC, skshetry reviewed
@individual-it, there's a few changes that needs to be done (see below).  I haven't added tests for folder (was thinking of doing using `Scenario Outline:`.

2019-12-06 16:30 UTC, skshetry commented on tests/acceptance/features/bootstrap/Sharing.php
> +			],
This is duplicated because I rebased on top of another commit that does this already. If you look at the end, it is already there.

2019-12-06 16:30 UTC, skshetry commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then /^the user changes expiration date for share of (user|group) "([^"]*)" to "([^"]*)" in the share dialog$/
s/Then/When

2019-12-08 04:24 UTC, individual-it requested changes

2019-12-08 04:24 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +			],
done in 30acf9d91a

2019-12-08 04:25 UTC, individual-it commented on tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature
> -    And user "user0" has created a share with settings
done in ae415c506fde4a9376e40d720346e25adb8f00bf

2019-12-08 04:26 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +  Scenario: expiration date is disabled for sharing with users and groups, user shares file with another user
done in ae415c506fde4a9376e40d720346e25adb8f00bf

2019-12-08 04:26 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +    And the administrator adds system config key "user.search_min_length" with value "2" using the occ command
fixed in ae415c506fde4a9376e40d720346e25adb8f00bf

2019-12-08 04:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +	 * @Then /^the response when user "([^"]*)" gets the info of their last share should include$/
done in ae415c506fde4a9376e40d720346e25adb8f00bf

2019-12-08 04:28 UTC, individual-it commented on tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature
> -      | shareWith   | grp1              |
fixed in ae415c506fde4a9376e40d720346e25adb8f00bf

2019-12-08 04:35 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then /^the user changes expiration date for share of (user|group) "([^"]*)" to "([^"]*)" in the share dialog$/
done in 6500bf8f82

2019-12-08 05:30 UTC, individual-it commented
superseded by #36541

2019-12-08 05:30 UTC, closed without merging