[For 10.4] Add share indicator in webUI
owncloud/core pull request #36534
Opened 2019-12-06 13:13 UTC by phil-davis

## Description
This is a rebased and squashed version of #36254 (which has many commits)

Filelist shows share indicators on files and folders, that reside inside a shared folder / shared folders.
The sidebar share-tab reveals a detailed view of the share-tree including share-recipients and the respective folders the life in.

![2019-11-12-21-23-13](https://user-images.githubusercontent.com/12717530/68707852-d54a4580-0592-11ea-9585-819370243361.gif)

## Related Issue

https://github.com/owncloud/enterprise/issues/3453 (Discussion)
https://github.com/owncloud/enterprise/issues/3556 (Vis. Concept)

## How Has This Been Tested?

Manual testing in
- Google Chome
- Mozilla Firefox
- MSIE 11

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](../changelog/README.md)

2019-12-06 13:15 UTC, phil-davis commented
ToDo: I need to review the tests in the 2nd commit.

2019-12-08 09:40 UTC, individual-it requested changes

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/lib/FilesPage.php
> +		$resourceMarkedSharedXpath = \sprintf($this->resourceSharedIndicatorXpath, $fileName);
use `findFileRowByName`

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/lib/SharedByLinkPage.php
> +	public function findFileRowByNameAndPath($name, $path, Session $session) {
unneeded

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    When the user shares folder "simple-folder" with user "User One" using the webUI
sharing should be done by API

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: Create share with internal users and view those shared resources in files page and shared-with-others page
views don't make a difference, because we have to go into a folder

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: user creates a public link for a folder and views the shared folder from files page, shared-with-others page
public link has to be put in other feature file

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given the setting "Automatically accept new incoming local user shares" in the section "Sharing" has been enabled
that is default

2019-12-08 09:40 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: Create share for a folder within a group and view the shared folder in files page and shared-with-others page
group shares are is separate feature file

2019-12-08 11:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> -			case "shared with others page":
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	public function folderShouldHaveShareIndicatorOnTheWebUI($fileOrFolder, $filename) {
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:43 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Then /^(file|folder) "([^"]*)" should have share indicator on the webUI$/
deleted the complete function in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:44 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +		Assert::assertEquals(true, $isMarked, "Expected: " . $fileOrFolder . " to be marked as shared but found: " . \strval($isMarked));
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:44 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @param TableNode $resourceTable table headings: must be: |name|
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:44 UTC, individual-it commented on tests/acceptance/features/lib/FilesPage.php
> +		$resourceMarkedSharedXpath = \sprintf($this->resourceSharedIndicatorXpath, $fileName);
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:44 UTC, individual-it commented on tests/acceptance/features/lib/SharedByLinkPage.php
> +	public function findFileRowByNameAndPath($name, $path, Session $session) {
deleted in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    When the user shares folder "simple-folder" with user "User One" using the webUI
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    Given the setting "Automatically accept new incoming local user shares" in the section "Sharing" has been enabled
no need to test in other views in the first place, deleted in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:45 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: Create share for a folder within a group and view the shared folder in files page and shared-with-others page
fixed in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:46 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +  Scenario: Create share with internal users and view those shared resources in files page and shared-with-others page
deleted unneeded tests in 448552d664b5db9ac8837b67495c2f5be13bd0ec

2019-12-08 11:48 UTC, individual-it commented
ToDo left for tests:
- [ ] test if uploading file in a shared folder shows the indicator immediately
- [ ] test if creating a folder in a shared folder shows the indicator immediately
- [ ] test with public links
- [ ] test with federation shares

2019-12-08 12:17 UTC, individual-it commented
- [ ]  details view does not indicate if the share receiver is a group or user as usual in the sharing dialogues
![image](https://user-images.githubusercontent.com/2425577/70389242-d715f600-19e4-11ea-8648-ce112ff3b2d4.png)

2019-12-08 13:00 UTC, individual-it commented
- [ ]  reshares are not shown in the details for the original sharer like in the share list
![image](https://user-images.githubusercontent.com/2425577/70389675-b2bd1800-19ea-11ea-8bca-1741b931a952.png)
vs
![image](https://user-images.githubusercontent.com/2425577/70389679-c0729d80-19ea-11ea-9dd8-950e1fc77fa1.png)

both screenshots are of the original sharer, but uu1 has reshared the folder to uu2

2019-12-09 08:02 UTC, phil-davis reviewed
leftovers from conflicts must be cleaned up

2019-12-09 08:02 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +<<<<<<< HEAD
leftover from conflict

2019-12-09 08:02 UTC, phil-davis commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +<<<<<<< HEAD
leftover from conflict

2019-12-09 08:05 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +<<<<<<< HEAD
:rocket:

2019-12-09 08:05 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
> +<<<<<<< HEAD
fixed!
:rocket:

2019-12-09 11:46 UTC, felixheidecke commented
@individual-it I addressed the two issues above in this PR:
https://github.com/owncloud/core/pull/36549

2019-12-10 06:13 UTC, jasson99 commented
[](file:///home/jasminebaral/Pictures/Screenshot%20from%202019-12-10%2011-55-06.png)

2019-12-10 06:19 UTC, jasson99 commented
Public links created without name through webUI or using  sharing API are listed without any name on the webUI as shown below.


![Screenshot from 2019-12-10 11-55-06](https://user-images.githubusercontent.com/40829116/70500818-89180400-1b44-11ea-81f1-9d1fcc5fa2df.png)

2019-12-10 09:50 UTC, felixheidecke commented
@jasson99 @individual-it I addressed the issue with the missing name for public links here:
https://github.com/owncloud/core/pull/36559

2019-12-11 00:11 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=36534) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=36534) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: felixheidecke<br/>:white_check_mark: kiranparajuli589<br/>:white_check_mark: individual-it<br/>:x: jasson99<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=36534) it.</sub>

2019-12-11 00:13 UTC, individual-it submitted a review, later dismissed

2019-12-11 00:13 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: sharing details of items inside a shared folder
Need to be skipped on 10.3

2019-12-11 03:39 UTC, individual-it commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: sharing details of items inside a shared folder
done in https://github.com/owncloud/core/pull/36534/commits/7bc6d3515fc5dc8e6f2dd2aa0e690781f8a48177

2019-12-11 03:45 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +  Scenario: sharing details of items inside a shared folder
this is fixed in ##36559

2019-12-11 09:28 UTC, individual-it commented
@micbar @felixheidecke @phil-davis I think acceptance-test wise we are ready here, taking off the QA-team label. Please review if the tests are what you would expect from the feature

2019-12-11 10:12 UTC, phil-davis commented
See PR #36572 - I have squashed and rebased this long list of commits. That PR has the same code on top of current master. Please do final reviews there.
(A simple squash-rebase here gave me various conflicts during the rebase process and I wanted to make sure to not lose anything that is already on this branch)

I will close here after CI finishes.

2019-12-11 10:52 UTC, closed without merging