Update Encryption.php to fix issue #34599 "encrypted remote storage"
owncloud/core pull request #36546
Opened 2019-12-09 09:53 UTC by phil-davis

This is an updated rebase of PR #36179 

I will use this to help me run the core acceptance tests from the encryption app

2019-12-10 04:19 UTC, phil-davis commented
Various things related to notifications are failing when encryption is on (user and/or master key)

https://drone.owncloud.com/owncloud/encryption/1026/114/16 - user key webUISharingNotifications
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/notificationLink.feature:16
    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature:21
    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature:18
    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature:28
    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature:36
    /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature:47

6 scenarios (6 failed)
67 steps (49 passed, 6 failed, 12 skipped)
```
and the same for master-key at https://drone.owncloud.com/owncloud/encryption/1026/89/16

https://drone.owncloud.com/owncloud/encryption/1026/61/14 - user key apiSharingNotifications
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature:23
    /var/www/owncloud/testrunner/tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature:35
    /var/www/owncloud/testrunner/tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature:69
    /var/www/owncloud/testrunner/tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature:94
    /var/www/owncloud/testrunner/tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature:133

9 scenarios (4 passed, 5 failed)
122 steps (105 passed, 5 failed, 12 skipped)
```

and the same at https://drone.owncloud.com/owncloud/encryption/1026/36/14 - master key apiSharingNotifications

2020-01-10 04:38 UTC, phil-davis commented
Rebased just now. After some changes to CI in encryption today, I will run encryption CI again against this...

2020-01-22 08:43 UTC, mmattel commented
Hi @phil-davis do you have an update on this?

2020-01-24 06:04 UTC, phil-davis commented
Rebased again just now.
And will run tests with encryption...

2020-01-24 08:37 UTC, mmattel commented
Seems that CI is failing with errors creating some images 😢

2020-01-24 09:04 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/22911/22/7
It's just stupid CI - lately the Oracle docker image has often "hung" when being fetched from docker. install-core waits up to 10 minutes for Oracle to become available and then gives up.
I don't really care about the core pipelines that failed!

2020-01-30 04:05 UTC, phil-davis commented
I found the issue with CI - https://github.com/owncloud/encryption/pull/166#issuecomment-578053262 - and actually all the tests pass fine.

2020-01-30 04:23 UTC, phil-davis commented
@micbar I added a changelog.

From a QA point-of-view this does not break anything.

Please get an appropriate person to do a final code review. then IMO this could be merged.

2020-01-30 08:12 UTC, micbar approved these changes

2020-01-30 08:13 UTC, micbar requested changes
Changelog title exceeds 80 chars.
Otherwise 👍

2020-01-30 08:25 UTC, phil-davis commented
> Changelog title exceeds 80 chars.

fixed

(I thought that the 80 char limit would be for the text after the `Bugfix:` keyword - but it is the length of the whole line)

2020-01-30 10:59 UTC, phil-davis commented
@micbar CI has passed - ready for review again.

2020-01-31 08:50 UTC, micbar approved these changes

2020-01-31 08:51 UTC, merged