integrate download in sharing tests
owncloud/core pull request #36583
Opened 2019-12-12 11:00 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2019-12-13 07:55 UTC, dpakach reviewed
LGTM :+1:

2019-12-13 10:09 UTC, individual-it commented
there should be now some scenarios that are obsolete and can be deleted, where are those?

2019-12-13 11:15 UTC, HariBhandari07 commented
@individual-it I have removed the obsolete sharing tests. There are many tests but with permissions attached, so I didn't remove them.

2019-12-13 11:46 UTC, individual-it requested changes

2019-12-13 11:46 UTC, individual-it commented on tests/acceptance/features/apiShareOperations/downloadFromShare.feature
> -  Scenario: Download a file that is in a folder contained in a folder that has been shared with public with default permissions
cannot see that test being added somewhere else

2019-12-13 11:46 UTC, individual-it commented on tests/acceptance/features/apiShareOperations/downloadFromShare.feature
> -  Scenario: Download a file that is in a folder contained in a folder that has been shared with public with Read only permission
cannot see this test being added somewhere

2019-12-17 08:25 UTC, individual-it approved these changes

2019-12-17 08:26 UTC, merged