Reduce memory footprint of trash expiry jobs
owncloud/core pull request #36602
Opened 2019-12-17 22:24 UTC by mrow4a

Related issue: https://github.com/owncloud/enterprise/issues/2899

Main problem: PHP PDO driver leaks memory - https://www.dragonbe.com/2015/07/speeding-up-database-calls-with-pdo-and.html . We cannot have (and it is not good idea either in all cases) scrollable cursor, and thus whole resultset is returned to memory. when calling execute.

- [x] do not fetch trashbin locations for background jobs (as it is not used)
- [x] split trashbin manager (online queries mostly) and trash expiry manager (background jobs only) to optimize for each case
- [x] do not keep memory for results of functions that potentially can return large results sets and keep them for duration of function, causing memory to grow further
- [ ] add unit tests
- [ ] as memory grows with number of users due to PDO memory leak (PDO keeps in memory cached result as it might be needed), do not allow cron to process all the users at once

@DeepDiver1975 @jvillafanez @PVince81

2019-12-18 00:39 UTC, mrow4a commented
@jvillafanez @DeepDiver1975 @pako81 will 500 users per session be good? The same we have for FileScan - https://github.com/owncloud/core/blob/master/apps/files/lib/BackgroundJob/ScanFiles.php#L98

2019-12-19 05:40 UTC, DeepDiver1975 requested changes

2019-12-19 05:40 UTC, DeepDiver1975 commented on tests/lib/User/AccountMapperTest.php
> +		// don use offset and limit
Do or don't?

2019-12-22 18:46 UTC, mrow4a commented on tests/lib/User/AccountMapperTest.php
> +		// don use offset and limit
Done

2019-12-30 13:55 UTC, mrow4a commented
@DeepDiver1975 @jvillafanez MR is ready.

2020-01-15 13:37 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +				unset($remainingUserTrashbinContent[$key]);
Confirm this works as expected. Modifying the list you're looping causes problems in most of the languages.
I think it's works because you're looping over a copy of the array, not over the array itself, so modifying the array won't affect the loop.

2020-01-15 13:37 UTC, jvillafanez commented on apps/files_trashbin/lib/Trashbin.php
>  	protected static function getQuota() {
I don't think this method is useful. Either move the code to where it's being used or clarify in the phpdocs that the method will always return a new `Quota` instance.

2020-01-21 10:08 UTC, micbar requested changes
Please add changelog item

2020-01-24 14:50 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +	public function callForUsers($callback, $search, $onlySeen, $limit = null, $offset = null) {
@jvillafanez AccountMapper is internal to code, also this method. It has no public interface (it actually has no interface implementation). But I will do that just to be sure.

2020-01-24 15:05 UTC, mrow4a commented on apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php
> +			$this->config->setAppValue('files_trashbin', 'cronjob_trash_expiry_offset', $offset);
I do not think it is a good idea. In that class we already use offset and limit, also FileScan uses similar mechanism - https://github.com/owncloud/core/blob/master/apps/files/lib/BackgroundJob/ScanFiles.php#L98. I would not over-engineer it here if this is not needed.

2020-01-24 16:18 UTC, mrow4a commented on lib/private/User/AccountMapper.php
>  		while ($row = $stmt->fetch()) {
I think it is a good idea to refactor some parts of the code and clean them. However I can barely think of the place in the code that we do that try/finally clause

2020-01-24 16:23 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +			$qb->orderBy('user_id'); // needed for predictable limit & offset
I think it is better to order by user_id, at least in the scope of this PR. Please have a look in another places in the class, and there we order by user_id (for some reason it was done, and I would not change it before some consultation). For the second comment, I commented in https://github.com/owncloud/core/pull/36602#discussion_r370680380.

2020-01-24 16:34 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
>  	protected static function getQuota() {
It is being used just a function above https://github.com/owncloud/core/blob/v10.3.2/apps/files_trashbin/lib/Trashbin.php#L778. Lets keep it in the class that it is used at.

2020-01-24 17:08 UTC, mrow4a commented on lib/private/User/AccountMapper.php
>  		while ($row = $stmt->fetch()) {
@jvillafanez I will skip this if you dont mind and not change the existing code that is not related to this PR. I noticed that we actually nowhere use the `try/finally` clause with cursors, and I would avoid introducing it without proper discussion with others.

2020-01-24 17:15 UTC, mrow4a commented on apps/files_trashbin/lib/Command/Expire.php
> +		return new TrashExpiryManager(
we cannot inject it (I tried). It is ICommand, that requires its class arguments to be serializable (actual arguments from command)

2020-01-24 17:21 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +	public function callForUsers($callback, $search, $onlySeen, $limit = null, $offset = null) {
Done

2020-01-24 17:21 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +	public function expiryByRetentionEnabled() {
Done

2020-01-24 17:21 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +					'Remove "' . $trashbinEntry->getName() . '" from "' . $uid . '" trashbin because it exceeds max retention obligation term.',
Done

2020-01-24 17:22 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +		$availableSpace = $this->quota->calculateFreeSpace($trashBinSize, $uid);
I added a comment in the function description. The comment also is available below this function call.

2020-01-24 17:24 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +				unset($remainingUserTrashbinContent[$key]);
I refactored it so it is more clear that this is a associative array (unset just removed the index key from array, that still later can be iterated with foreach)

before: `[ 0 => a, 1=>b, 2=>c]`
after: `[ 0 => a, 2=>c]`

2020-01-26 14:31 UTC, mrow4a commented
@jvillafanez @micbar while reviewing, please note that also refactor of trashbin manager was motivated to be able to test it with unit tests properly and cover whole code there.

2020-01-27 08:46 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +		$availableSpace = $this->quota->calculateFreeSpace($trashBinSize, $uid);
>  Retention expiry will be applied first, and if quota not reached (available space would be still negative for the user),

"quota is not reached" can be easily interpreted as " you're below the quota and you have to fill it up". It sounds better to say "if you're still over the quota" to clarify we still need to delete items.

2020-01-27 08:46 UTC, jvillafanez commented on apps/files_trashbin/lib/Trashbin.php
>  	protected static function getQuota() {
the function is being used, but what's the point of a function that just creates a new object? Instead of doing `self::getQuota()` you can do `new Quota(.....)`.
Right now, I don't see any benefit: the function is only used in one place (it isn't being reused) and you can't mock it in the unittests. Note that this might be confusing in the long run because 95% of the "get" function will return always the same instance, they won't create a new instance each time they're called.

2020-01-27 08:46 UTC, jvillafanez commented on lib/private/User/AccountMapper.php
> +			$qb->orderBy('user_id'); // needed for predictable limit & offset
as long as the sorting column is indexed, I don't think it's relevant if you sort by id or user_id. My point is that the "offset" clause is bad and we should get rid of it (https://www.eversql.com/faster-pagination-in-mysql-why-order-by-with-limit-and-offset-is-slow/)

Taking into account that this is a new function, it could be a good starting point. Maybe the change is bigger than I think, so if you think the change is too big for the PR, we can go with the current code for now.

2020-01-27 19:42 UTC, mrow4a commented on lib/private/User/AccountMapper.php
> +			$qb->orderBy('user_id'); // needed for predictable limit & offset
@jvillafanez I am not sure if this is a good idea in this case to expose rowid/accountids for limit, as we use IUserManager->callForUsers public interface - limit and offset are already used in this class in 3 other functions. If this was some internal implementation to page data I would be more then opting for this solution.

I know it is super tempting in this case, but it might happen that other use-cases would be interested in non-arbitrary pages (e.g. you have UI with 100 users per page, and 1000 pages, and I want to calculate something for a page no. 4, how do you do that with the offset being some magic number?).

2020-01-27 19:55 UTC, mrow4a commented on apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php
> +			$this->config->setAppValue('files_trashbin', 'cronjob_trash_expiry_offset', $offset);
This was refactor to always remember last scanned user. If users are added, no expiration would be needed to be done. If user is removed, there wont be anything to expire probably.

2020-01-27 19:56 UTC, mrow4a commented on apps/files_trashbin/lib/Command/Expire.php
> +		return new TrashExpiryManager(
yes, it is too big (this PR is already quite big)

2020-01-27 19:56 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +					'Remove "' . $trashbinEntry->getName() . '" from "' . $uid . '" trashbin because it exceeds max retention obligation term.',
Refactored in a class

2020-01-27 19:56 UTC, mrow4a commented on apps/files_trashbin/lib/TrashExpiryManager.php
> +		$availableSpace = $this->quota->calculateFreeSpace($trashBinSize, $uid);
Done

2020-01-27 19:56 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
>  	protected static function getQuota() {
Done

2020-01-28 08:59 UTC, jvillafanez approved these changes
Just a little detail, but I can live with it.

2020-01-28 08:59 UTC, jvillafanez commented on apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php
> +	protected function tearDownFS() {
this isn't really needed. Just move the `\OC_Util::tearDownFS()` call inside the `run` method

2020-01-28 08:59 UTC, jvillafanez commented on lib/private/User/AccountMapper.php
> +			$qb->orderBy('user_id'); // needed for predictable limit & offset
I'm willing to discuss this offline. Anyway, we can keep the limit + offset approach in this case.

2020-01-28 09:04 UTC, jvillafanez commented on apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php
> +			$this->config->setAppValue('files_trashbin', 'cronjob_trash_expiry_offset', $offset + $usersScanned);
Just saying, you can sell this better as a transactional mechanism to deal with a memory crash.

2020-01-28 09:31 UTC, DeepDiver1975 approved these changes

2020-01-28 09:47 UTC, micbar approved these changes

2020-01-28 09:48 UTC, merged