Allow "+" character in usernames
owncloud/core pull request #36613
Opened 2019-12-18 21:23 UTC by pako81

## Description

Allow `+` character when creating users

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/3712

## Motivation and Context

This PR allows the `+` character in the username when creating new users. This is also required when sharing with guest users having i.e. the following format `name+2@test.com`.

## How Has This Been Tested?

Manually by creating new users having the `+` sign in their usernames over the Users management page as well by using the `user:add` occ command.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised 
- [ ] Changelog item

2019-12-19 04:20 UTC, phil-davis commented on lib/private/User/Manager.php
> +			if (\preg_match('/[^a-zA-Z0-9 \+_\.@\-\']/', $uid)) {
Note: the escaping of `\+` here is not strictly required (just like the escaping of `\.` is actually not strictly required) but it does not hurt. In other contexts in a regex the plus sign does need to be escaped, so escaping it here just helps people not to have to think about that.

2019-12-19 04:22 UTC, phil-davis commented
@pako81 I adjusted acceptance tests to include some cases with a user with `+` in the username. And also added a changelog entry.

IMO  this works. @micbar this could be merged for 10.4 - is that OK?

2019-12-19 09:37 UTC, pako81 commented
thanks a lot @phil-davis :)

2019-12-19 10:18 UTC, pako81 commented
@phil-davis I was now thinking about the user provisioning APIs. In there, the `+` sign is still not correctly escaped and rather replaced with a space character.

2019-12-19 12:03 UTC, phil-davis commented
@pako81 I added provisioning API tests. They are passing locally for me and I expect that they will pass in drone CI. 
Probably the tests are providing the `+` in the URL as ASCII 43, `%2B` (I think that is true, without actually digging deep into the test code)
And that is how any client using the Provisioning API would need to specify a username containing a `+` - and the backend code will receive the `%2B` turned back into a `+` and it "just works"

2019-12-19 13:20 UTC, pako81 commented
@phil-davis correct, I was testing the wrong way. The following seems to work correctly.

`curl -X POST http://admin:password@example.com/ocs/v1.php/cloud/users -d userid="name%2B1@test.com" -d password="test"`

2019-12-19 16:03 UTC, phil-davis commented
There have been other major features merged just now. So I rebased this PR to make sure that the CI is all green on top of those changes now in master.

2019-12-19 16:06 UTC, phil-davis commented
@micbar @HanaGemela I have added acceptance test coverage and it passes (adding users with `+` in ther username via the webUI, cli and provisioning API and doing stuff with them...) So this looks like it works fine.

I some developer can review the code and approve, and you think this is a change/enhancement that we should have, then feel free to merge it for 10.4

2019-12-20 07:55 UTC, sharidas reviewed
LGTM :+1:

2019-12-20 07:57 UTC, karakayasemi requested changes
Everything seems good. As a last, this should be adjusted also.
https://github.com/owncloud/core/blob/98922f11f87cb4818212d530a59c51d57fb4f124/core/Command/User/Add.php#L67

2019-12-20 08:08 UTC, pako81 commented
thanks @karakayasemi :) missed that

2019-12-20 09:46 UTC, karakayasemi approved these changes

2019-12-20 09:48 UTC, merged