Add function to create ldap user without escaping
owncloud/core pull request #36750
Opened 2020-01-13 10:00 UTC by kiranparajuli589

## Description
Previously, user creation were skipped and pre-created users were used when running ldap tests.
Function to create user in ldap server are added.

## How Has This Been Tested?
- CI
- manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-01-13 10:18 UTC, phil-davis reviewed
Just a quick first review of noticeable stuff

2020-01-13 10:18 UTC, phil-davis commented on composer.json
> +        "zendframework/zend-ldap": "^2.10"
can this go in `require-dev` section?
It should only be needed by tests.

2020-01-13 10:18 UTC, phil-davis commented on tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
> +
bonus line

2020-01-13 10:18 UTC, phil-davis commented on composer.json
> +        "zendframework/zend-ldap": "^2.10"
It is also added to `vendor-bin/behat/composer.json`
Maybe it can be removed from here completely?

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given these users have been created using LDAP server:
Can we not just check `TEST_EXTERNAL_USER_BACKENDS` env variable and create user on ldap server rather than  having a separate step for it.

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 * @var Ldap
```suggestion
	 * @var string
```

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param $setDefaultAttributes
Its better to use parameter type as well here. eg.
```suggestion
	 * @param boolean $setDefaultAttributes
```

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$this->deleteUserAndGroups();
No need to create an extra function. I guess that is not used anywhere other than here.

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$initialize = $doNotInitialize === "";
Would be easy if `$doNotInitialize` was just a boolean value. or even better use `$initialize`

2020-01-13 10:48 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				return;
The function returns here so it would not create all the users, Will return just after creating one user.

2020-01-14 03:51 UTC, kiranparajuli589 commented on composer.json
> +        "zendframework/zend-ldap": "^2.10"
done! :+1:

2020-01-14 03:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 * @var Ldap
done!

2020-01-14 04:00 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given these users have been created using LDAP server:
This is just created for fun...will be deleted later!

2020-01-14 04:06 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
> +
removed :hocho:

2020-01-14 04:06 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				return;
done!

2020-01-14 04:06 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$this->deleteUserAndGroups();
done!

2020-01-14 04:06 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param $setDefaultAttributes
done!

2020-01-14 04:13 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$initialize = $doNotInitialize === "";
done!

2020-01-15 08:45 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		return $this->featureContext->removeSchemeFromUrl($this->ldapHost);
```suggestion
		return $this->removeSchemeFromUrl($this->ldapHost);
```

2020-01-15 10:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			foreach ($this->toDeleteDNs as $dn) {
`toDeleteDNs` is never written to (yet?)
Maybe this code is not needed, and the `toDeleteDNs` var can be deleted.

2020-01-15 10:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$this->countUsersCreated += 1;
This could be done inside `createALdapUser` ?
Otherwise anything that calls `createALdapUser` has to remember to also increment the count.

2020-01-15 10:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$response = SetupHelper::runOcc(
Do we need to do this?
`createTheGroup` already has some logic to throw an exception if something obvious went wrong with group creation.

2020-01-15 10:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +					$this->createALdapGroup($group);
Do we need to do a sync of LDAP groups to make the new group be seen in owncloud?

2020-01-15 10:23 UTC, phil-davis commented
@kiranparajuli589 when you are ready, we should be able to make a PR in user_ldap that has the needed changes in user_ldap (e.g. taking out the code from `UserLdapGeneralContext` that has been moved to here in core, and adjusting to call the methods in core...)

The user_ldap PR can get the core test code from this core branch, instead of core master.

Then we will know for sure that everything works/passes.

2020-01-16 04:05 UTC, kiranparajuli589 commented on composer.lock
> +        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
done!

2020-01-16 04:27 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +					$this->createALdapGroup($group);
yes, `sync` is needed.
sync step is inside `createALdapGroup()` function

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/config/ldap_config.php
> +$port = 389;
what will we use this code for?

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +		$this->featureContext->runOcc(
why do we need this change?

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			} elseif (!$setDefaultAttributes) {
This is the opposite of `} elseif ($setDefaultAttributes) {` above, so if we get to here, this will always be true and the next `else` is never going to be executed.

Maybe this `elseif` is not needed (or can be the else?)

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * ldap-user are re-synced after creating a new user
```suggestion
	 * ldap users are re-synced after creating a new user
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * creates user in ldap server
```suggestion
	 * creates a user in the ldap server
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * created user is added to `createdUsersList`
```suggestion
	 * the created user is added to `createdUsersList`
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function createALdapUser($setting) {
```suggestion
	public function createLdapUser($setting) {
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function createALdapGroup($group) {
```suggestion
	public function createLdapGroup($group) {
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getUsersOfALdapGroup($group) {
```suggestion
	public function getUsersOfLdapGroup($group) {
```
for these methods that are not also gherkin steps, we do not need to bother put "a", "an", "the" in the method name.
That saves having t think if it should be `ALdapGroup` or `AnLdapGroup`

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		if (\getenv("TEST_EXTERNAL_USER_BACKENDS") === "true") {
should we call `getLdapTestStatus` here?

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				"User " . $username . " is not created using Ldap and do not exists as Ldap User"
```suggestion
				"User " . $username . " was not created using Ldap and does not exist as an Ldap User"
```

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$occResponse = SetupHelper::runOcc(
why do we need to do this 2nd check using the `occ` command?
If the API endpoint returns 4xx then the group does not exist???

2020-01-20 04:23 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		if (\getenv("TEST_EXTERNAL_USER_BACKENDS") === "true") {
can we call `getLdapTestStatus` here?

2020-01-20 06:15 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +		$this->featureContext->runOcc(
`occContext->invokingTheCommand()` when passing args as occ command only, the command donot run as an administrator!

The above step is implemented for admin user so admin configs are passed iniside occ function..

2020-01-20 06:34 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +		$this->featureContext->runOcc(
`occContext->invokingTheCommand()` when passing args as occ command only, the command donot run as an administrator!

The above step is implemented for admin user so admin configs are passed iniside occ function..

2020-01-20 06:34 UTC, kiranparajuli589 commented on tests/acceptance/config/ldap_config.php
> +$port = 389;
its not necessary here!
removed!

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			} elseif (!$setDefaultAttributes) {
This is edited because display name can't be left empty for ldap users!
I've adjusted the condition as
`if ($this->getLdapTestStatus && !setDefaultAttributes) {`

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * ldap-user are re-synced after creating a new user
done!

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * creates user in ldap server
done!

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * created user is added to `createdUsersList`
done!

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function createALdapUser($setting) {
done!

2020-01-20 06:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function createALdapGroup($group) {
done!

2020-01-20 06:39 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getUsersOfALdapGroup($group) {
done!

2020-01-20 06:39 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		if (\getenv("TEST_EXTERNAL_USER_BACKENDS") === "true") {
yes!
done..

2020-01-20 06:39 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				"User " . $username . " is not created using Ldap and do not exists as Ldap User"
done!

2020-01-20 06:42 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$occResponse = SetupHelper::runOcc(
Some group-names created during test consists slashes("/") due to which API endpoint returns 4xx although the group is created successfully or a group is an existing group!
But occ command seems to be fine whatever the group-name is!

2020-01-20 07:42 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$occResponse = SetupHelper::runOcc(
OK, yes, that is a problem/feature of the current provisioning API. I guess we work around like this for now.

2020-01-20 07:45 UTC, phil-davis commented
@kiranparajuli589 now you have fun to rebase and "resolve" the conflicts!
It should be just:
- delete `BasicStructure`
- make the changes from `BasicStructure` in `FeatureContext`

2020-01-20 08:42 UTC, individual-it requested changes

2020-01-20 08:42 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +			$this->featureContext->getOcPath()
these are all unused

2020-01-20 08:42 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +		$this->featureContext->runOcc(
occ commands don't have a username its always the "administrator"

2020-01-20 08:50 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +			$this->featureContext->getOcPath()
then why do we check for baseUrl or admin username/password inside runOcc function?

2020-01-20 09:11 UTC, individual-it commented on tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
> +			$this->featureContext->getOcPath()
we need the admin username, password and the URL to send the command to the testing app

2020-01-21 03:24 UTC, phil-davis commented
Make sure to rebase to latest master first and resolved the conflicts in `FeatureContext`
And https://drone.owncloud.com/owncloud/core/22767/41/13 is failing some `addGroup` scenarios.

2020-01-21 05:17 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
>      # After fixing issue-31015, change the following step to "should exist"
What is happening? The test is now passing.
I guess that the group creation request does succeed, it is just that the query for the group was giving an error.
So for this scenario we can delete the comment lines. 
But we should add a scenario that gets group information of a group containing a `/` in the name, that can record the current "wrong" behaviour.

2020-01-21 05:17 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
>      # After fixing issue-31015, change the following step to "should exist"
similar here - the comments are now out-of-date

2020-01-21 05:19 UTC, phil-davis commented
CI is still failing https://drone.owncloud.com/owncloud/core/22790/41/13

2020-01-21 05:58 UTC, kiranparajuli589 commented on tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
>      # After fixing issue-31015, change the following step to "should exist"
group-names with slashes inside still cannot be deleted using afterscenario cleanups, so the issue is not fixed completely!

2020-01-21 10:02 UTC, individual-it requested changes

2020-01-21 14:14 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->removeUserFromLdapGroup($user, $group);
💫

2020-01-21 14:17 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
>  		$this->userRemovesUserFromGroupUsingTheProvisioningApi(
removeUserFromLdapGroup

2020-01-22 03:19 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$occResponse = SetupHelper::runOcc(
Ok..sure!!

2020-01-22 03:20 UTC, kiranparajuli589 commented on tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
> -    And the administrator deletes group "grp1" using the provisioning API
To go green! :smile:

2020-01-22 03:20 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$body["displayName"] = $row["username"];
done!

2020-01-22 03:20 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			} elseif ($this->getLdapTestStatus() === true && !$setDefaultAttributes) {
done!

2020-01-22 03:20 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function setAttributesForUser($setDefaultAttributes, $table) {
done

2020-01-22 04:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function deleteLdapUserAndGroups() {
done!

2020-01-22 04:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function resetOldConfig() {
done!

2020-01-22 04:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @param array $bodies
done!

2020-01-22 04:58 UTC, kiranparajuli589 commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
when we create a group named `Case-Sensitive-Group` in Ldap and sync with OC then the group name gets changed to `case-sensitive-group`...

2020-01-22 04:59 UTC, kiranparajuli589 commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
because group-names with only integers are not synced properly..
we can create group named `123` in Ldap but after sync we do not get it as OC group

2020-01-22 05:00 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->editLdapUserDisplayName(
done!

2020-01-22 05:00 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->createTheGroup($row["groupname"]);
since it's a given step, i've added an assertion here checking the group exists after they are created...

2020-01-22 05:01 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @When /^the administrator deletes group "([^"]*)"$/
done!

2020-01-22 05:01 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->removeUserFromLdapGroup($user, $group);
done!

2020-01-22 05:03 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$this->userShouldExist($user);
ok sure..

2020-01-22 09:31 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->createTheGroup($row["groupname"]);
done!

2020-01-23 06:27 UTC, individual-it requested changes

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $userAttribute) {
```suggestion
		foreach ($usersAttributes as $userAttributes) {
```

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $user) {
```suggestion
		foreach ($usersAttributes as $userAttributes) {
```

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $expectedUser) {
only do this check in the Given step

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function changeTheDisplayNameOfUserUsingTheProvisioningApi(
seems to be unused

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function adminHasChangedTheDisplayNameOfUser(
as this is an given step, we want to have a check at the end, that it worked. You can use the provisioning API for that

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> -			$this->createTheGroup($row['groupname']);
extra noise

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$this->usersHaveBeenCreated(
catch LdapExeption like with creating groups

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$this->addUserToLdapGroup(
catch LdapExeption like with creating groups

2020-01-23 06:27 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given user :user has been removed from group :group
as this in a Given step, add a check if the user is successfully removed from group

2020-01-23 08:10 UTC, individual-it submitted a review, later dismissed

2020-01-23 08:10 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getLdapTestStatus() {
```suggestion
	public function isTestingWithLdap() {
```

2020-01-23 09:11 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getLdapTestStatus() {
done!

2020-01-23 09:11 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given user :user has been removed from group :group
done!

2020-01-23 09:12 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$this->addUserToLdapGroup(
done!

2020-01-23 09:15 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				$this->usersHaveBeenCreated(
done!

2020-01-23 09:15 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> -			$this->createTheGroup($row['groupname']);
removed!

2020-01-23 09:16 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function adminHasChangedTheDisplayNameOfUser(
done!

2020-01-23 09:16 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $expectedUser) {
done!

2020-01-23 09:20 UTC, kiranparajuli589 commented on tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
> +  @smokeTest @skipOnLdap
done!

2020-01-23 09:20 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function changeTheDisplayNameOfUserUsingTheProvisioningApi(
removed!

2020-01-23 09:22 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $user) {
done!

2020-01-23 09:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		foreach ($usersAttributes as $userAttribute) {
done!

2020-01-23 09:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		return $this->oldConfig;
done!

2020-01-23 09:26 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	}
actually i'm working on a PR of user_ldap test where we remove all previous ldap_configs....that PR is created on top of this one, so when we are going to access ldap anywhere beside featureContext or Provisioning, we cannot user `$this->ldap`, so I think I'm gonna leave this one although its unused.
**other unused functions are removed!**

2020-01-23 10:37 UTC, kiranparajuli589 commented on tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
> +  @smokeTest @skipOnLdap
@issue-ldap-500

2020-01-23 10:39 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * This will be faster in comparision to waiting for each request to complete before sending another request.
```suggestion
	 * This will be faster in comparison to waiting for each request to complete before sending another request.
```
only if we need to make other changes

2020-01-23 10:39 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
>  			return;
This return means that `userShouldNotBelongToGroup` will not be run at line 2780

2020-01-23 10:39 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
>  		}
maybe put `} else {` here and remove the `return` above it?

2020-01-23 10:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * This will be faster in comparision to waiting for each request to complete before sending another request.
done!

2020-01-23 10:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
>  		}
ok sure.. :100:

2020-01-24 03:23 UTC, phil-davis commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
should this have an issue tag?

2020-01-24 03:23 UTC, phil-davis commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
should this have an issue tag?

2020-01-24 04:57 UTC, kiranparajuli589 commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
yeah,,,actually i've tried both manually and through our test locally, LDAP user with full integer name can be added into any LDAP group using LDAP server but when we sync them with OC, we donot get those users as members of group assigned before!

2020-01-24 04:58 UTC, kiranparajuli589 commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
yes, it should! :smile:

2020-01-24 06:25 UTC, phil-davis approved these changes

2020-01-24 06:25 UTC, merged

2020-01-24 06:27 UTC, phil-davis commented
@kiranparajuli589 this is now merged to master :1st_place_medal: 
Please run your user_ldap PR again against the latest master (IMO CI will immediately start using the new test code from master).
That will get user_ldap CI great.

2020-01-24 06:29 UTC, kiranparajuli589 commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
@phil-davis should I open an issue about this thing!!

2020-01-24 06:39 UTC, phil-davis commented on tests/acceptance/features/cliProvisioning/getGroup.feature
> +  @skipOnLDAP
yes