Change the wording in the additional tab to not confuse users
owncloud/core pull request #36775
Opened 2020-01-16 23:24 UTC by ChrisEdS

## Description
This PR changes two strings that caused confusion in the additional tab.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/2500

## Motivation and Context
Confusion should be avoided.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-01-17 04:13 UTC, phil-davis reviewed
~and needs a changelog~
has been done

2020-01-17 04:13 UTC, phil-davis commented on settings/templates/settingsPage.php
> +			<h2><?php p($l->t('Currently no settings available in this category')); ?></h2>
```suggestion
			<h2><?php p($l->t('Currently no settings are available in this category')); ?></h2>
```

2020-01-17 04:16 UTC, phil-davis commented
I added 1 word and added a changelog.
Tested manually - the text looks fine to me on the webUI.
@pmaier1 please review

2020-01-17 07:57 UTC, pmaier1 approved these changes
Text is fine. Thanks for taking care everybody :ok_hand:

2020-01-17 08:05 UTC, micbar requested changes
Needs to be decided when to merge.

Currently it would go into 10.4 but we didn't update the translations.

2020-01-24 12:10 UTC, phil-davis commented
Note: PR #36776 changed the word "Error" to "Other" on that page. So that "fixed" it for 10.4.

I rebased this just now.

After 10.4 is released, someone can decide if they would like to have the words in this PR, and merge it.

2020-01-24 12:28 UTC, micbar commented
@phil-davis thanks. I think everybody agreed on the solution.

2020-02-13 14:40 UTC, mmattel commented
Ping ?

2020-02-13 16:11 UTC, phil-davis commented
This is waiting until after 10.4.0 is released. 10.4.0 changed the word "Error" to "Other", which at least gets rid of the misleading word "Error".

If we had realised how long it would be until we got 10.4.0 released, then we could have merged this and the new translations would have had plenty of time to be done. Anyway, too late for that now.

2020-02-28 11:25 UTC, phil-davis commented
I rebased this and adjusted the words of the changelog entry.
With 10.4.0 release "real soon now", we could consider merging this next week for 10.4.1

2020-04-14 11:14 UTC, phil-davis commented
This missed out on 10.4.1
If we want it, then we could merge it this week (e.g. straight after 10.4.1 branch gets merged back...). And that will then give time to do translations before the next release.

2020-05-29 11:15 UTC, phil-davis commented
Nobody merged this.
@micbar if we merge this now, will necessary translations have time to happen and get back from Transifex to core master before an official 10.5.0 branch is created?

2020-05-29 11:19 UTC, micbar approved these changes

2020-05-29 11:19 UTC, merged