[Tests only] Add acceptance test to export created mounts using occ command
owncloud/core pull request #36794
Opened 2020-01-21 10:46 UTC by jasson99

## Description
 Add acceptance test to export created mounts using occ command

## Related Issue

- Related #36704 

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-01-22 05:05 UTC, dpakach commented on tests/acceptance/features/bootstrap/OccContext.php
> +					$isStorageEntryListed = true;
Just break the loop after this, no point in keep going.

2020-01-22 05:05 UTC, dpakach commented on tests/acceptance/features/bootstrap/OccContext.php
> +				throw new Exception("Expected local storages not found");
```suggestion
				throw new Exception("Expected local storage: $expectedStorageEntry not found in the command output");
```

2020-01-22 05:05 UTC, dpakach commented on tests/acceptance/features/bootstrap/OccContext.php
> +	 * @When the administrator exports the mounts using the occ command
```suggestion
	 * @When the administrator exports the local storage mounts using the occ command
```

2020-01-22 06:26 UTC, jasson99 commented on tests/acceptance/features/bootstrap/OccContext.php
> +					$isStorageEntryListed = true;
fixed

2020-01-22 06:26 UTC, jasson99 commented on tests/acceptance/features/bootstrap/OccContext.php
> +				throw new Exception("Expected local storages not found");
fixed

2020-01-22 06:26 UTC, jasson99 commented on tests/acceptance/features/bootstrap/OccContext.php
> +	 * @When the administrator exports the mounts using the occ command
fixed

2020-01-23 10:01 UTC, phil-davis commented
Needs #36781 to be merged first, then rebase this

2020-01-23 11:51 UTC, phil-davis requested changes

2020-01-23 11:51 UTC, phil-davis commented on tests/acceptance/features/bootstrap/OccContext.php
> +
This is duplicated - delete it

2020-01-24 03:27 UTC, jasson99 commented on tests/acceptance/features/bootstrap/OccContext.php
> +
fixed

2020-01-24 05:57 UTC, phil-davis approved these changes

2020-01-24 05:57 UTC, merged