Initial draft for license management
owncloud/core pull request #36814
Opened 2020-01-23 12:34 UTC by jvillafanez

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-01-27 10:00 UTC, DeepDiver1975 requested changes

2020-01-27 10:00 UTC, DeepDiver1975 commented on lib/private/License/LicenseManager.php
> +				$this->config->setAppValue('core', "trials_{$appid}", $this->timeFactory->getTime());
try using setAppValue('trials', $appid, $time)

This way you can get all trials using the config->getAppKeys

2020-01-27 10:43 UTC, jvillafanez commented on lib/private/License/LicenseFetcher.php
> +class LicenseFetcher {
While I agree this seems too much for what is currently implemented, we'd need to take into account what are the plans we have for this feature.

Unless we won't ever implement additional things over this feature (as sketched in the PHP comment) I'd prefer to keep this class, otherwise I'm pretty sure the `LicenseManager` will end up bloated with more things because we won't have time to do things properly.

With what is currently under implementation, the main benefit is that we can inject this for unittests. In addition, small things usually implies easier tests.

2020-01-27 10:50 UTC, DeepDiver1975 commented on lib/private/License/LicenseFetcher.php
> +class LicenseFetcher {
I'd split up classes later as needed - but I keep this up to you. Go ahead

2020-01-27 10:59 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +			$callerFile = \debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 1)[0]['file'];
I haven't found better alternatives to ensure the trial only starts if it's called from the app. I'd rather not rely on the "programmer's well behaviour".

If we use something like `startTrialPeriod($app)` we can't guarantee that the function will be called only by the target app: either core or any rogue app could start a trial over "myApp"

So far, the function is intended to be called only once per app, so as long as it doesn't crash it should be fine I guess. It might need some additional stress test to ensure it doesn't break, but hopefully, memory-wise it should be fine because we're ignoring the arguments (which is what it usually break the function) and we only get the first element

2020-01-27 11:04 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +				$this->config->setAppValue('core', "trials_{$appid}", $this->timeFactory->getTime());
I'll use "core-trials" then. It's even less likely there will be a collision with a valid app name.

2020-01-27 13:43 UTC, DeepDiver1975 commented on lib/private/License/LicenseManager.php
> +			$callerFile = \debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 1)[0]['file'];
Well - who is the app developer of apps which can start a trial: it is us at ownCloud GmbH

There is not much damage caused I guess.

2020-02-14 14:05 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +			$apps = [];
This "includeExtras" needs to be moved to a private method.

2020-02-14 14:20 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +			$callerFile = \debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 1)[0]['file'];
Taking into account there will be only one "global" grace period, I think we can remove this. If an app wrongly checks the license of a different app, it shouldn't be a big deal

2020-02-18 16:19 UTC, pmaier1 commented
## Suggestion for wording

**Upgrade to ownCloud Enterprise**

You have enabled one or more ownCloud Enterprise apps but your installation does not have a valid license yet.
A grace period of 24 hours has started to allow you to get going right away. Once the grace period ends, all Enterprise apps will become disabled unless you supply a valid license key.

To try ownCloud Enterprise, just [start a 30-day trial on the ownCloud Marketplace](link) and enter the provided license key below.

2020-02-19 08:14 UTC, jvillafanez commented
![Screenshot from 2020-02-19 09-08-17](https://user-images.githubusercontent.com/1477829/74814505-b2e56800-52f7-11ea-9c12-7c34de447338.png)

@pmaier1 I guess we want to include a link in "start a 30-day trial on the ownCloud Marketplace" but it isn't available yet? If so, I think we should block this until we have the link

2020-02-20 12:29 UTC, pmaier1 commented
> @pmaier1 I guess we want to include a link in "start a 30-day trial on the ownCloud Marketplace" but it isn't available yet? If so, I think we should block this until we have the link

Exactly. We'll need to wait for the Marketplace rework to include the URL of the landing page there.

2020-02-21 13:03 UTC, micbar commented on lib/private/License/LicenseManager.php
> +				return false;
Can we log this event?

2020-02-21 13:03 UTC, micbar commented on lib/private/License/LicenseManager.php
> +				$this->config->setAppValue('core-license-complains', $appid, $licenseKey);
logging?

2020-02-21 13:27 UTC, micbar commented
Tested the PR, looks good to me. IMO we need some logging. See my comments.

Next question: How would the market app play together with this change.

2020-02-21 14:33 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +				return false;
I guess the warning message in the log is enough. No need to distinguish different license states.

2020-02-21 14:41 UTC, jvillafanez commented on lib/private/License/LicenseManager.php
> +				$this->config->setAppValue('core-license-complains', $appid, $licenseKey);
Using a debug log because the "complain" will be set on every request, so the log will spam too much otherwise.
We could use a "get + set" approach to prevent the spam, although not sure how efficient it will be because the cause will be executed on every request (during the grace period). It might be fine if we rely on the caching mechanism of the `config`.

2020-02-21 14:41 UTC, jvillafanez commented
Logs added.

2020-04-20 08:47 UTC, micbar commented
@pmaier1 We now need the link to the landing page.

2020-04-20 08:53 UTC, micbar commented
@jvillafanez Could you check that we also support keys in the `oc_appconfig` Table

2020-04-20 08:59 UTC, micbar commented
@enbrnz @xoxys Can you give us an opinion about changing the `config.php` from OC side after deployment?

Or is that not the case here, because you would not do a evaluation deployment with ansible?
If you do a demo deployment, you would anyway provide a demo key? Correct?

2020-04-20 10:59 UTC, enbrnz commented
> Or is that not the case here, because you would not do a evaluation deployment with ansible?
> If you do a demo deployment, you would anyway provide a demo key? Correct?

Yes, I don't think we have to worry about this in regards to ansible. When you do a deployment, people have most likely already decided whether they need CE or EE. And even if it would set a license key in the `config.php` and remove it again later, I don't think it would be a problem for ansible-deployments.

2020-04-20 11:26 UTC, xoxys commented
> don't think it would be a problem for ansible-deployments.
Shouldn't be a problem. Ansible (and I guess also docker) are using a custom-config.php

2020-04-20 11:34 UTC, jvillafanez commented
> @jvillafanez Could you check that we also support keys in the oc_appconfig Table

Fixed with the latest commit. If the config.php is marked as read-only, the license will be stored in the DB. In addition, the DB will also be checked if the license isn't found in the config.php file (license in the config.php takes precedence)

2020-05-11 08:17 UTC, micbar commented
@jvillafanez Does the PR have feature parity enterprise key app for the key expiration?

Please check again the messages and the UI notifications.

2020-05-11 08:17 UTC, micbar commented
Url for landing page should be generic.

2020-05-12 07:59 UTC, jvillafanez commented
Feature parity missing pieces:
* [ ] yellow notifications about current license (invalid, about to expire etc)
* [ ] license status in the settings page

2020-05-15 10:52 UTC, jvillafanez commented
Some clarifications regarding feature-parity with the enterprise_key app:
* Messages shown in the settings panel and in the yellow notification will be the same. As such, some messages have been slightly changed to make it clear it comes from the license part of core, specially with the yellow notification.
* There is no distinction regarding the behaviour between a normal and demo key, although the expected messages might be different.
* Yellow notification message will appear in all the pages if the license is invalid, expired or about to expire.
  * An "about to expire" license is a valid license which will expire in 60 days or less (currently hardcoded)
* Demo licenses are expected to have a 30-days valid period. This means that they'll be in a constant "about to expire" state and the yellow notification will always appear.
* Yellow notification will only be shown to admins.

2020-05-18 09:08 UTC, phil-davis commented
Changelog still needs to be added.

2020-05-18 09:37 UTC, DeepDiver1975 commented on core/js/license-state-notification.js
> +			OC.Notification.showHtml(data.translated_message.join('<br/>'), {type: 'error'});
what about escaping? more a general thought ...

2020-05-18 09:37 UTC, DeepDiver1975 commented on lib/public/License/ILicenseManager.php
> +	public function getLicenseStateFor(string $appid);
we should define php return types where ever possible

2020-05-18 09:48 UTC, jvillafanez commented on core/js/license-state-notification.js
> +			OC.Notification.showHtml(data.translated_message.join('<br/>'), {type: 'error'});
Some of the translated messages contain a mailto link which would break if we escape the message. Since the mailto link also has a prefilled subject (which might be used for sales), I'm not sure how important is to keep the same message as before or if we can change / adjust it

2020-05-18 10:09 UTC, jvillafanez commented
todo things:
* [ ] demo license message in the login page
* [ ] revert back text for the demo messages
* [ ] recheck return types

I'll add the changelog item after having everything in place, as the last step.

2020-05-18 11:57 UTC, micbar commented
@jvillafanez Question:

Does the change affect the behavior of the status.php page?

2020-05-18 13:01 UTC, jvillafanez commented
> Does the change affect the behavior of the status.php page?

Fixed with the latest changes

I've only found the "enterprise_key" string there and in the "new" `licenseFetcher` (to keep compatibility if the license is present in the DB)

2020-05-18 19:04 UTC, micbar commented
@jvillafanez This pr might need a rebase to fix the unit tests.

2020-05-19 07:42 UTC, jvillafanez commented
https://github.com/owncloud/core/pull/36814/commits/3b02e9d07e2f948d7159a103e434a7a346dabb2b#diff-ec8c121d705ff47eacbfdd23f36a9f6cR476

The "community vs enterprise" edition string might need some additional hardening... I've followed the previous code, but now I think if the license is invalid or expired, we should change the edition string to community

2020-05-19 07:53 UTC, micbar commented
> The "community vs enterprise" edition string might need some additional hardening... I've followed the previous code, but now I think if the license is invalid or expired, we should change the edition string to community

It might help to understand, that we have 2 different use cases:
- 1) Expired demo key
- 2) Expired Production key

We always had the understanding that on a production system we do not "disable" any features. That includes the status.php IMO

For a demo key, this would be a desired feature.

@pmaier1 Please confirm

2020-05-19 09:58 UTC, jvillafanez commented
If I didn't miss anything, the following table shows the current state with all the cases. It might need some changes.
:red_circle: => message shouldn't appear
:green_circle: => message should appear

|                                                | login message  | grace popup    | notification   | settings warning | status.php |
|------------------------------------------------|:--------------:|:--------------:|:--------------:|------------------|------------|
| grace active + license missing                 | :red_circle:   | :green_circle: | :red_circle:   | normal           | community  |
| grace active + license invalid                 | :green_circle: | :green_circle: | :green_circle: | warning          | enterprise |
| grace active + license valid (demo)            | :green_circle: | :red_circle:   | :green_circle: | normal           | enterprise |
| grace active + license valid (prod)            | :red_circle:   | :red_circle:   | :red_circle:   | normal           | enterprise |
| grace active + license almost expired (demo)   | :green_circle: | :red_circle:   | :green_circle: | normal           | enterprise |
| grace active + license almost expired (prod)   | :red_circle:   | :red_circle:   | :green_circle: | normal           | enterprise |
| grace active + license expired (demo)          | :green_circle: | :green_circle: | :green_circle: | warning          | enterprise |
| grace active + license expired (prod)          | :green_circle: | :green_circle: | :green_circle: | warning          | enterprise |
|                                                |                |                |                |                  |            |
| grace inactive + license missing               | :red_circle:   | :red_circle:   | :red_circle:   | normal           | community  |
| grace inactive + license invalid               | :green_circle: | :red_circle:   | :green_circle: | warning          | enterprise |
| grace inactive + license valid (demo)          | :green_circle: | :red_circle:   | :green_circle: | normal           | enterprise |
| grace inactive + license valid (prod)          | :red_circle:   | :red_circle:   | :red_circle:   | normal           | enterprise |
| grace inactive + license almost expired (demo) | :green_circle: | :red_circle:   | :green_circle: | normal           | enterprise |
| grace inactive + license almost expired (prod) | :red_circle:   | :red_circle:   | :green_circle: | normal           | enterprise |
| grace inactive + license expired (demo)        | :green_circle: | :red_circle:   | :green_circle: | warning          | enterprise |
| grace inactive + license expired (prod)        | :green_circle: | :red_circle:   | :green_circle: | warning          | enterprise |

2020-05-19 13:49 UTC, micbar commented
@jvillafanez Would it be possible to have a call-to-action button "Get your demo key". for the link to the landing page?

2020-05-19 14:38 UTC, jvillafanez commented
> @jvillafanez Would it be possible to have a call-to-action button "Get your demo key". for the link to the landing page?

The link is already clickable. The only problem is that with the default style the link could be unnoticed.

2020-05-19 15:34 UTC, micbar commented
@jvillafanez The link is clickable yes.

PM requested that we use a button in a new line.

2020-05-19 18:07 UTC, micbar commented
![Screenshot_2020-05-19 Files - ownCloud](https://user-images.githubusercontent.com/4378513/82362202-48ce8300-9a0c-11ea-84b5-515a7437bc30.png)

@hodyroff @pmaier1 

OK.

LGTM 👍

2020-05-19 18:09 UTC, micbar approved these changes

2020-05-20 07:08 UTC, DeepDiver1975 approved these changes

2020-05-20 09:49 UTC, jvillafanez commented
This is ready to merge

2020-05-20 12:04 UTC, jvillafanez commented
hopefully last touches:
* [ ] open " get a demo key" link in a new tab +  change target link to "owncloud.com/try-enterprise"

2020-05-20 12:12 UTC, phil-davis commented
@jvillafanez if you rebase and force-push then you should get codecov results/status back. That problem has been fixxed today in latest master.

2020-05-20 13:04 UTC, jvillafanez commented
> 2. Config (can come later, but nice to have if small thing)
> if there is no config, use default url: https://owncloud.com/try-enterprise/
> if there is a configured url, use that.

I'll open a new ticket for that in order to merge this PR today.

2020-05-22 06:43 UTC, merged