[Tests-Only] Web UI accept pending federated
owncloud/core pull request #37146
Opened 2020-03-20 10:41 UTC by Talank

## Description
- Test for accepting federated share from remote to local user.
- Test to ensure that when a local user makes federated share with remote then, the file is listed in `shared with other` page

## Related Issue
- Fixes https://github.com/owncloud/core/issues/37140

## How Has This Been Tested?
locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-03-20 11:03 UTC, mmattel commented
Please run `make test-php-style-fix` to fix code style issues amd make CI happy

2020-03-21 11:11 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When the user closes federation share dialog
```suggestion
	 * @When the user closes the federation sharing dialog
```

2020-03-21 11:11 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @When the user accepts the pending remote shares using the webUI
```suggestion
	 * @When the user accepts the pending remote share using the webUI
```
IMO the page object code will only accept 1 pending share (even if there are multiple waiting to be accepted). So we should write the singular in the step text, otherwise it will mislead people in the future who use this step.

2020-03-23 06:11 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/SharedWithYouPage.php
> +
php doc missing

2020-03-23 06:15 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/SharedWithYouPage.php
> +
And, to avoid _php-style_ failure in **drone** run `make test-php-style` to check lint errors and `make test-php-style-fix` to fix, or you can fix manually

2020-03-25 03:27 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	}
Do we really need this step. I think federation share dialog and normal sharing dialog are same so same method can work for both.

2020-03-25 04:01 UTC, Talank commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	}
I didn't find any other step for closing this kind of dialog. Actually this dialog is like the login error dialog. Most of previously defined steps focuses on the dialog that appears like a windows alert. May be we need to generalize that kind of steps(for closing any dialog box) in some other PR!

2020-03-25 04:25 UTC, kiranparajuli589 commented
LGTM :+1:

2020-03-25 05:31 UTC, individual-it requested changes
please squash commits, then we can merge this

2020-03-25 09:05 UTC, individual-it approved these changes

2020-03-25 09:06 UTC, merged