Gdrive lib update
owncloud/core pull request #37265
Opened 2020-04-15 16:56 UTC by jvillafanez

## Description
* Update google library to version 2.4.1
* There are some update of the library code for icewind's 3.1.2 (code in the repo seems older than the last composer update. Maybe the code wasn't updated. No real update in the composer's dependency)
* In addition, google's new version uses guzzle, so try to enforce guzzle version to 5.3.1 (matching core's version). Using guzzle 6 might reduce the amount of dependencies brought by google, but could be problematic for core.

First commit is the library update, both google and icewind.
The second commit contains the actual changes to adapt to the API changes.
The third commit is just readability improvements.

Note that change detection has been changed because the API no longer provides a id per change, so using the google's change API was a problem. It probably isn't suited for the use case implemented in the code.

## Related Issue
https://github.com/owncloud/core/issues/36509#issuecomment-597061791

## Motivation and Context
Update google's library version to be compatible with latest php 7.4 deprecations.

## How Has This Been Tested?
Tested manually basic file operations through ownCloud.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### Requires testing for gdrive and SMB connectors due to library updates

2020-04-17 09:20 UTC, jvillafanez commented
:exclamation: Please double-check "[gdrive_lib_update bcbe4f753b] Fix google docs downloads" is there :exclamation:

2020-04-17 10:56 UTC, jvillafanez commented
There is a known issue when a file is re-uploaded (just upload the same file twice or more): the file is duplicated in the gdrive with the same name, which will be problematic (we don't handle multiple files with the same name)

It seems the problem is with the ownCloud's .part file. Disabling the .part files in gdrive in https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/File.php#L637 would solve the problem because the file will be uploaded directly to the previous file, overwriting it.
We need to decide how to proceed with this issue. Adding the gdrive storage there is the simplest solution, but a bad approach.

2020-04-17 11:14 UTC, mmattel commented
I am adding @micbar so he knows about this PR and may add his thoughts

2020-04-17 19:08 UTC, micbar commented
@jvillafanez what is the question?

2020-04-20 06:49 UTC, jvillafanez commented
The question is if we want to spend time refactoring https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/File.php#L637 in order to provide a good solution, or if we include directly the storage name there to prevent using .part files in google drive.

2020-04-27 10:05 UTC, cdamken commented
IMHO .part files should be always in the temp folder and then upload to the external storage once is finished (and even checked by the antivirus if enabled)

2020-04-27 12:37 UTC, jvillafanez commented
Decided to add the google storage to the core's ".part file exclusion list" for now in order to progress with the PR.
Opened https://github.com/owncloud/core/issues/37313 to discuss a possible refactor.

2020-04-27 15:21 UTC, ho4ho commented
.part file related by #37062, #25826 ?

2020-05-05 08:52 UTC, phil-davis commented
This is also related to https://github.com/owncloud/core/issues/36509#issuecomment-623394556 for PHP 7.4 support.

2020-05-05 08:56 UTC, phil-davis commented
I added this to the 10.5.0 project. It needs review and moving forward.

2020-05-08 09:08 UTC, phil-davis commented
I rebased to get this up-to-date with other stuff that has happened in core master in the last week.

@jvillafanez @micbar what happens next?

This needs to move forward - it is becming a blocker if we need it for 10.5.0

2020-05-08 10:39 UTC, jvillafanez commented
Code-wise this is ready. It still need review.
Ignoring the first commit which contains both library update, the rest of the commits should be easy to understand.

2020-05-08 11:01 UTC, micbar commented
@jvillafanez I requested a review. Hope that helps ;-)

2020-05-08 12:29 UTC, VicDeo requested changes

2020-05-08 12:29 UTC, VicDeo commented on apps/files_external/lib/Lib/Storage/Google.php
> +		static $fileFields = null;  // keep static variable to avoid recreating the string
IMO static is kinda functional thing. class constant suits better here

2020-05-08 12:29 UTC, VicDeo commented on apps/files_external/lib/Lib/Storage/Google.php
> +		static $folderFields = null;  // keep static variable to avoid recreating the string
the same as above. could be a class property.

2020-05-10 11:20 UTC, karakayasemi reviewed
Reviewing deeply is not easy. The changeset looks okay, basic file operations and authorization are working.

2020-05-10 11:20 UTC, karakayasemi commented on apps/files_external/lib/Lib/Storage/Google.php
>  		} else {
If upper `if statement` ends with a `return` like here, no need to open an `else` block. I am aware of cyclomatic complexity is so high in the `Google.php` class wide, but, optionally we may reduce this complexity at least the places that we touch in this pr. It increases readability by reducing number of multiple nested conditonal blocks.

2020-05-11 07:05 UTC, jvillafanez commented on apps/files_external/lib/Lib/Storage/Google.php
> +		static $fileFields = null;  // keep static variable to avoid recreating the string
I'm not sure what it the best option. The problem with the class constant is that is easy that the field list becomes unreadable if a string is used. If we use an array, we'll have to build the string every time.
Another alternative could be to use a class attribute, but for me it would be polluting the class with information that isn't part of the class. In addition, the attribute could be changed in any part of the class.

I think this is a way the keep balance between readability and performance. The string is built only once when needed, and using an array makes it easier to read. In addition, all this complexity is isolated inside the method, without polluting the class.

2020-05-11 07:44 UTC, VicDeo requested changes

2020-05-11 07:44 UTC, VicDeo commented on apps/dav/lib/Connector/Sabre/Node.php
> +			return null;
this invalidates the current PHPDoc for `getSize`

2020-05-11 09:00 UTC, VicDeo approved these changes

2020-05-11 09:23 UTC, karakayasemi approved these changes

2020-05-11 10:30 UTC, phil-davis commented
`codecov/project` fails because of the change in size of all the "crud" here.... - I will override that.

2020-05-11 10:31 UTC, merged