[Tests-Only]  Added default capabilities scenario for a normal user
owncloud/core pull request #37354
Opened 2020-05-06 11:06 UTC by kiranparajuli589

## Description
Since admin user cannot get capabilities detail from ocis-reva server but normal user can, test scenario is added for a normal user to check default capabilities set.

## Related Issue
- https://github.com/owncloud/ocis-reva/issues/149

## Motivation and Context

## How Has This Been Tested?

- :robot:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-05-06 11:11 UTC, kiranparajuli589 commented
different behaviour of `ocis-reva` and `core` servers for capabilities response is described in issue https://github.com/owncloud/ocis-reva/issues/175

2020-05-06 11:49 UTC, individual-it commented
Please make a separate test for OCIS and one for oC10, so that both path in the respected environment

2020-05-07 03:13 UTC, individual-it requested changes

2020-05-07 03:13 UTC, individual-it commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +      | core          | status@@@versionstring                    | 10.5.0alpha1      |
for owncloud we should be able to get these values dynamically

2020-05-07 03:13 UTC, individual-it commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +  @skipOnOcis @issue-ocis-reva-176
```suggestion
  @skipOnOcis @issue-ocis-reva-175 @issue-ocis-reva-176
```

2020-05-07 03:13 UTC, individual-it commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +  @skipOnOcV10 @issue-ocis-reva-176
```suggestion
  @skipOnOcV10 @issue-ocis-reva-175 @issue-ocis-reva-176
```

2020-05-07 03:14 UTC, individual-it commented
please also make a PR to ocis-reva and ocis repo that uses this branch as test-runner to make sure the tests pass there

2020-05-07 08:10 UTC, kiranparajuli589 commented
https://github.com/owncloud/ocis/pull/255 - run tests on ocis

2020-05-07 08:11 UTC, kiranparajuli589 commented
https://github.com/owncloud/ocis-reva/pull/178 - run tests on ocis-reva repo

2020-05-07 08:12 UTC, kiranparajuli589 commented
@individual-it changes has been made, please review again!

2020-05-07 10:57 UTC, individual-it approved these changes

2020-05-07 13:26 UTC, merged