Add fed shares scanner batched cronjob
owncloud/core pull request #37391
Opened 2020-05-14 21:43 UTC by mrow4a

<img width="442" alt="image" src="https://user-images.githubusercontent.com/13368647/81988935-9332b700-963c-11ea-8ce4-4c934a8921f1.png">

2020-05-15 09:21 UTC, mmattel commented
Pls run: `make test-php-style-fix` to fix coding style error(s)

2020-05-15 13:38 UTC, VicDeo commented on apps/files_sharing/lib/External/ScanExternalSharesJob.php
> +	protected function fixDIForJobs() {
As far as I know this is no longer needed DI for jobs was fixed in core

2020-05-17 10:35 UTC, mrow4a commented on apps/files_sharing/lib/External/ScanExternalSharesJob.php
> +	protected function fixDIForJobs() {
apparently not
```
➜  octest git:(feature/fed-shares-cronjob) ✗ ./occ background:queue:execute --force --accept-warning 12
PHP ArgumentCountError:  Too few arguments to function OCA\Files_Sharing\External\ScanExternalSharesJob::__construct(), 0 passed in /Users/mrow4a/Projects/www/octest/lib/private/BackgroundJob/JobList.php on line 258 and exactly 5 expected in /Users/mrow4a/Projects/www/octest/apps/files_sharing/lib/External/ScanExternalSharesJob.php on line 55
PHP Stack trace:
PHP   1. {main}() /Users/mrow4a/Projects/www/octest/occ:0
```

2020-05-17 10:53 UTC, mrow4a commented on apps/files_sharing/lib/External/ScanExternalSharesJob.php
> +	protected function fixDIForJobs() {
this is what I see in the logs
```
\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCP\\\\IUserManager! Class can not be instantiated
```

2020-05-17 11:36 UTC, phil-davis commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$output->writeln("WARNING: incoming-shares:poll has been depreciated and replaced by periodic external shares cronjob. Please check Federated Cloud Sharing settings and documentation.");
```suggestion
		$output->writeln("WARNING: incoming-shares:poll has been deprecated and replaced by periodic external shares cronjob. Please check Federated Cloud Sharing settings and documentation.");
```

2020-05-17 13:25 UTC, mrow4a commented on apps/federatedfilesharing/lib/Command/PollIncomingShares.php
> +		$output->writeln("WARNING: incoming-shares:poll has been depreciated and replaced by periodic external shares cronjob. Please check Federated Cloud Sharing settings and documentation.");
done

2020-05-17 13:31 UTC, mrow4a commented
@micbar do you want to fit this in 10.5?

2020-05-18 09:57 UTC, VicDeo requested changes

2020-05-18 11:50 UTC, mrow4a commented on apps/files_sharing/appinfo/Migrations/Version20200504211654.php
> + * Auto-generated migration step: Please modify to your needs!
ahh good catch

2020-05-18 11:51 UTC, mrow4a commented on apps/federatedfilesharing/tests/Panels/AdminPanelTest.php
> +		$this->shareProvider->expects($this->once())->method('isOutgoingServer2serverShareEnabled')->willReturn(false);
good catch, forgot to put proper function

2020-05-19 10:46 UTC, VicDeo approved these changes

2020-05-19 11:55 UTC, merged

2020-06-06 11:53 UTC, mrow4a commented
@pmaier1 👍 
### Migrations when upgrading from 10.4 + potential impact on upgrade duration (small/mid/high)

MID - we are adding a new column to mid-sized table, but we do not update/alter the values

### Replaces former background job? If yes, is it still available or not?

It replaces former `occ command` that was scheduled by admins via crontab. It will be still avaiable (depreciated), but is discouraged. If admin enables checkbox in admin settings, he SHOULD remove depreciated job from crontab

### Is the checkbox in admin settings the same as `occ` command ?

Yes, this is the same config.

### Does it need to be added to crontab?

No. This is owncloud cronjob that does not require setting crontab entry, as soon as admin enables checkbox, cronjob will go in effect in intervals of 10min.

### Docs?

Seems some work already started (https://github.com/owncloud/docs/issues/2648), but generally:

1. Fed share scan cronjob is disabled by default, to enable use occ or checkbox:

```
occ config:app:set files_sharing cronjob_scan_external_enabled --value yes
 ```

![](https://user-images.githubusercontent.com/13368647/81988935-9332b700-963c-11ea-8ce4-4c934a8921f1.png)
 
2. To customize minimum amount of hours when last login of user happened so scan is triggered (ensures only active users get fed shares synced) - 24h
```
occ config:app:set files_sharing cronjob_scan_external_min_login --value <integer-seconds>
```
 
3. To customize minimum amount of hours when last scanned so next scan is triggered (avoid frequent scan when active collaboration) - 3h
```
occ config:app:set files_sharing cronjob_scan_external_min_scan --value <integer-seconds>
```
 
4. To customize maximum amount of fed share checks per 10 minutes - unlimited
```
currently not limited, amounts to numbers of fed shares in the system
```
 
5. To customize maximum amount of fed share scans per 10 minutes (scan performed only if fed share files got updated) - 100
```
occ config:app:set files_sharing cronjob_scan_external_batch --value <integer-number>
```

2020-06-08 16:15 UTC, pmaier1 commented
Thanks @mrow4a. 
- Regarding the list (1-5): Is the last value in the line (e.g., 24h) the default value?
- Regarding 3.: Does this mean that a fed share that was scanned within the last e.g., 3h will not be scanned again until the configured period has passed?
- Regarding 4./5.: What's the difference between fed share **check** and fed share **scan**. Check only discovers changes and scan actually updates the contents?

2020-06-09 18:23 UTC, mrow4a commented
@pmaier1 

> * Regarding the list (1-5): Is the last value in the line (e.g., 24h) the default value?

Yes, this is default value currently configured 

> * Regarding 3.: Does this mean that a fed share that was scanned within the last e.g., 3h will not be scanned again until the configured period has passed?

yes, fed share can be scanned only once per 3h (by default).

> * Regarding 4./5.: What's the difference between fed share **check** and fed share **scan**? Check only discovers changes and scan actually updates the meta data? If yes, this is also an improvement compared to the previous command as that one only did the discovery, right?

**check** -> operation of checking if fed share should be scanned
**scan** -> only fed shares for which user logged-in in last 24h and last scan of that share happened at least 3h ago are scanned (scan is operation of checking storage root for change, and if changed syncing filecache of remote with local). Currently, we scan only in batches of 100 fed shares per 10 minutes, remembering the offset at which it finished last `app.files_sharing.cronjob_scan_external_offset`