[Tests-Only] update reva api tests
owncloud/core pull request #37396
Opened 2020-05-15 12:54 UTC by C0rby

I fixed some issues, unskipped the corresponding tests.
The pr with the fixes:
https://github.com/cs3org/reva/pull/748

Partially fixed
owncloud/ocis-reva#20

Fixed:
owncloud/ocis-reva#26
owncloud/ocis-reva#43
owncloud/ocis-reva#44
owncloud/ocis-reva#94

2020-05-18 03:01 UTC, individual-it requested changes
just a small comment, rest looks good, but please make a PR to ocis and ocis-reva  where this branch is used to run the tests (you just need to change this line in the drone file https://github.com/owncloud/ocis-reva/blob/master/.drone.star#L104 )

2020-05-20 09:46 UTC, PVince81 commented
there's a conflict

also, should we convert this to a draft PR since the fix itself is not merged, so not ready for review yet?

2020-05-20 09:49 UTC, C0rby commented
Yes, I think a draft pr would make sense since we don't know when the reva changes will be merged.
There isn't a way to turn this pr to a draft directly, is it?

2020-05-20 10:05 UTC, PVince81 commented
it's a bit hard to find :-D
<img width="193" alt="image" src="https://user-images.githubusercontent.com/277525/82433717-24b58500-9a92-11ea-9324-d3b6ea6cc05c.png">

2020-05-25 08:31 UTC, C0rby commented on tests/acceptance/features/apiVersions/fileVersions.feature
> -  @smokeTest @issue-ocis-reva-94
Why should we leave the issue tag?

2020-05-25 08:40 UTC, individual-it approved these changes

2020-05-25 08:41 UTC, C0rby commented
@PVince81, I can't merge because codecov/patch is stuck...

2020-05-25 08:41 UTC, C0rby commented
Ah nevermind

2020-05-25 08:41 UTC, merged

2020-05-25 08:41 UTC, individual-it commented
@C0rby I've faked that codecov CI ;-)