[Tests-Only] Run file move tests on OCIS
owncloud/core pull request #37414
Opened 2020-05-19 04:10 UTC by HariBhandari07

## Description

This PR adds basic file/folder move scenarios to run on OCIS
## Related Issue

- https://github.com/owncloud/ocis-reva/issues/14

## Motivation and Context

## How Has This Been Tested?

- CI
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-05-19 11:08 UTC, individual-it requested changes
please also make PRs to ocis and ocis-reva repo to make sure the tests pass there and link those PRs to here

2020-05-19 11:08 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
>    Scenario: disabled async operations leads to original behavior
I think we should skip this kind of tests because there is no administrator that can disable the async operation. I'm surprised that the step does not fail

2020-05-19 11:08 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
> +  @skipOnFirewall @skipOnOcis
lets keep this one skipped, we are not able to slow down the HTTP-Request on ocis

2020-05-19 11:08 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
>    Scenario: Moving a file to a folder with no permissions
I'm surprised that this works. AFAIK there is no async functionality yet in ocis

2020-05-19 11:08 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFolder.feature
> +  @skipOnOcis
please tag the scenarios with the corresponding issues and create scenarios that are showing the current behaviour is OCIS and are skipped on oc10

2020-05-19 11:11 UTC, HariBhandari07 commented
> please also make PRs to ocis and ocis-reva repo to make sure the tests pass there and link those PRs to here

@individual-it Here's the ocis-reva PR https://github.com/owncloud/ocis-reva/pull/210

2020-05-20 07:51 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
> +    When the administrator updates system config key "blacklisted_files" with value '["blacklisted-file.txt",".htaccess"]' and type "json" using the occ command
in OCIS the administrator cannot set this kind of system configs see https://github.com/owncloud/ocis-reva/issues/54 & https://github.com/owncloud/ocis-reva/issues/65 
So this kind of test is snake-oil anyway, no need to add it

2020-05-20 11:18 UTC, individual-it requested changes

2020-05-20 11:18 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFolder.feature
> +  @issue-ocis-reva-211 @skipOnOcV10
please put this test below the corresponding oc10 test and tag both tests with the issue

same for the other tests

2020-05-20 12:33 UTC, jasson99 reviewed
LGTM

2020-05-21 11:12 UTC, individual-it approved these changes

2020-05-21 13:25 UTC, merged