[Tests-only] Adjust public link tests
owncloud/core pull request #37552
Opened 2020-06-18 09:15 UTC by PVince81

Enabled some tests and tagged others that are not working yet.

For https://github.com/owncloud/ocis-reva/issues/49.

2020-06-18 14:36 UTC, PVince81 commented
Squashed and pushed. Added some more tickets and excluded tests.

Still, I managed to enable a bunch of tests for public link upload, download, creation, etc. Updating and deleting is not implemented yet.

2020-06-24 15:36 UTC, PVince81 commented
While splitting the "old public webdav" and "new public webdav" I came accross a test tagged with `@issue-36055`.
That test had the test steps commented out for the "new public webdav".

It turns out that this bit still doesn't work. I've now marked it as `@skipOnOcV10` and reopened the ticket, see  https://github.com/owncloud/core/issues/36055#issuecomment-648895940

@individual-it FYI

2020-06-24 15:40 UTC, PVince81 commented
I ran the unskipped tests marked with issue 49 against the matching Reva PR that solves those: https://github.com/cs3org/reva/pull/877
```
TEST_SERVER_URL=http://localhost:9140 \
TEST_EXTERNAL_USER_BACKENDS=true \
TEST_OCIS=true \
OCIS_REVA_DATA_ROOT=/var/tmp/reva/ \
SKELETON_DIR=$HOME/work/workspace/owncloud/apps-external/testing/data/apiSkeleton \
BEHAT_FILTER_TAGS='~@skipOnOcV10&&~@skipOnLDAP&&@TestAlsoOnExternalUserBackend&&~@local_storage&&@issue-ocis-reva-49&&~@skipOnOcis'
```

and they all pass:
```
21 scenarios (21 passed)
145 steps (145 passed)
```

please note that some are still skipped due to other issues, see OP for a listing of related issues to address separately.

2020-06-24 15:40 UTC, PVince81 commented
we might want to wait for the Reva PRs to be merged and updated in ocis-reva just to be on the safe side

2020-06-25 06:53 UTC, individual-it requested changes

2020-06-25 06:53 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +    When the public downloads the last public shared file with range "bytes=0-9" using the old public WebDAV API
```suggestion
    When the public downloads the last public shared file with range "bytes=0-9" using the new public WebDAV API
```

2020-06-25 06:53 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
>      And the public upload to the last publicly shared file using the old public WebDAV API should fail with HTTP status code "403"
```suggestion
    And the public upload to the last publicly shared file using the new public WebDAV API should fail with HTTP status code "403"
```

2020-06-25 06:53 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +    Then the downloaded content should be "Random dat"
remove this line, that check is done above and fail here because there is no download before this step

2020-06-25 10:00 UTC, PVince81 commented
@individual-it thanks for spotting. I already rechecked those bits over and over again for discrepancies but still managed to miss it. I've fixed that location and squashed.

2020-06-26 09:51 UTC, individual-it approved these changes

2020-06-26 09:59 UTC, PVince81 commented
API tests passed in https://cloud.drone.io/owncloud/ocis-reva/521, merging

2020-06-26 09:59 UTC, merged