[Tests-Only] API test for upload file with Mtime
owncloud/core pull request #37553
Opened 2020-06-18 10:42 UTC by Talank

## Description
API test for upload a file with Mtime header.

## Related Issue
https://github.com/owncloud/ocis-reva/issues/273

## How Has This Been Tested?
- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-06-18 11:04 UTC, individual-it requested changes

2020-06-18 11:04 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * 						Human readable format is taken as input and then converted into milliseconds
wrong indent

2020-06-18 11:04 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +      | new         |
more tests:
- upload into a folder
- move file after upload should not change mtime

2020-06-18 11:06 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  Scenario Outline: upload file with mtime
you will have to skip the tests on OCIS for now, as the functionality is in a PR only

2020-06-18 11:35 UTC, PVince81 commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  Scenario Outline: upload file with mtime
it's been merged and will come with the next ocis-reva update https://github.com/owncloud/ocis-reva/pull/279

2020-06-18 11:36 UTC, PVince81 commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  Scenario Outline: upload file with mtime
let's skip it still, tag it with https://github.com/owncloud/ocis-reva/issues/174

2020-06-19 07:51 UTC, individual-it approved these changes

2020-06-19 08:03 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  @skipOnOcis
```suggestion
  @skipOnOcis owncloud/ocis-reva#174
```

2020-06-19 08:03 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  @skipOnOcis
issue tag
```suggestion
  @skipOnOcis owncloud/ocis-reva#174
```

2020-06-19 08:03 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  @skipOnOcis
same here

2020-06-22 02:58 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +  @skipOnOcis
The format it @issue-ocis-reva-174

2020-06-22 04:03 UTC, merged