[Tests-Only] Make various file operations test pass on EOS
owncloud/core pull request #37577
Opened 2020-06-23 10:36 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-06-23 12:13 UTC, phil-davis commented
@HariBhandari07 apologies! PR #37578 split some acceptance test suites.

Now there is `apiWebdavProperties1` and `apiWebdavProperties2` acceptance test suites. So you will need to find the feature files there and edit them.

2020-06-24 03:06 UTC, individual-it requested changes

2020-06-24 03:06 UTC, individual-it commented on tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
> +  @skipOnOcV10 @issue-ocis-reva-214 @skipOnOcis-EOS-Storage
```suggestion
  @skipOnOcV10 @issue-ocis-reva-214 @issue-ocis-reva-265 @skipOnOcis-EOS-Storage
```

2020-06-24 05:33 UTC, individual-it approved these changes

2020-06-24 05:33 UTC, merged