[Tests-Only] Added API test for public link Mtime
owncloud/core pull request #37589
Opened 2020-06-24 10:18 UTC by Talank

## Description
API Acceptance test for public link mtime is added 

## Related Issue
Fixes https://github.com/owncloud/ocis-reva/issues/296

## How Has This Been Tested?
- Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-06-24 10:21 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 *
add PHP doc for function variable

2020-06-24 11:16 UTC, individual-it requested changes
please add tests:
 - check the mtime if the share is a share of a folder and not a file
 - upload as public with a historic mtime (share is a file or folder, different permissions (e.g. upload only, upload and read) - check that the mtime is reported correctly through the webdav interface of the user
 - upload as public overwriting an existing file and setting the mtime

2020-06-24 11:16 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +  @skipOnOcis
```suggestion
  @skipOnOcis @issue-ocis-reva-49
```

2020-06-24 11:16 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +      | permissions | read        |
I don't think we are interested in those lines, all that is tested in other tests, lets focus on the mtime here

2020-06-29 11:39 UTC, PVince81 commented
fix was added in https://github.com/owncloud/phoenix/pull/3686#pullrequestreview-439036189

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	 * @When the mtime of the last shared public link for file :fileName using the WebDAV API should not be :mtime
```suggestion
	 * @Then the mtime of file :fileName in the last shared public link using the WebDAV API should not be :mtime
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	public function publicGetsTheMtimeOfTheLastSharedPublicLinkUsingTheWebdavApi(
```suggestion
	public function theMtimeOfFileInTheLastSharedPublicLinkUsingTheWebdavApiShouldBe(
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	public function publicDoNotGetsTheMtimeOfTheLastSharedPublicLinkUsingTheWebdavApi(
```suggestion
	public function theMtimeOfFileInTheLastSharedPublicLinkUsingTheWebdavApiShouldNotBe(
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	 * @When the public uploads a file :fileName to last shared folder with mtime :mtime using the :davVersion public WebDAV API
```suggestion
	 * @When the public uploads file :fileName to the last shared folder with mtime :mtime using the :davVersion public WebDAV API
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +	 * @When the mtime of the last shared public link for file :fileName using the WebDAV API should be :mtime
```suggestion
	 * @Then the mtime of file :fileName in the last shared public link using the WebDAV API should be :mtime
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +  Scenario: overwriting a file changes its mtime
```suggestion
  Scenario: overwriting a file changes its mtime (old public webDAV API)
```

2020-06-29 11:57 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +  Scenario: overwriting a file changes its mtime
```suggestion
  Scenario: overwriting a file changes its mtime (new public webDAV API)
```

2020-06-30 03:05 UTC, individual-it commented
code-style problem 
![image](https://user-images.githubusercontent.com/2425577/86078825-af849900-baae-11ea-99a8-cd82aacf9a5b.png)

always good to run  `make test-php-style` before committing, e.g. in pre-commit hook

2020-06-30 04:46 UTC, individual-it requested changes
don't implement tests using the old public link webdav API, nobody cares about it and it will never be implemented in OCIS

2020-06-30 04:48 UTC, individual-it requested changes

2020-06-30 04:48 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +  Scenario: Get the mtime of a file inside a folder shared by public link using old dav version
old or new? the test says "new"

2020-06-30 05:16 UTC, kiranparajuli589 reviewed
lgtm :+1:

2020-07-01 03:13 UTC, individual-it requested changes

2020-07-01 03:13 UTC, individual-it commented on tests/acceptance/features/bootstrap/PublicWebDavContext.php
> +				(new TestHelpers\WebDavHelper)->getMtimeOfFileinPublicLinkShare($baseUrl, $fileName, $token)
why do we need that construct?
shouldn't `\TestHelpers\WebDavHelper::getMtimeOfFileinPublicLinkShare($baseUrl, $fileName, $token)` work? The functions in the TestHelpers should all be static

2020-07-01 03:17 UTC, individual-it requested changes
please try the tests also on ocis/ocis-reva repository.
If they work its great, if not we need to open issues, skip the existing tests and make tests that show the issues in ocis

2020-07-01 03:17 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +	public function getMtimeOfFileinPublicLinkShare(
make the function static like all others

2020-07-01 03:17 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
> +    And the mtime of file "file.txt" in the last shared public link using the WebDAV API should not be "Thu, 08 Aug 2019 04:18:13 GMT"
check the mtime also through the "normal" webDAV api

2020-07-02 03:40 UTC, individual-it approved these changes

2020-07-02 03:49 UTC, merged