[Tests-Only] Added API test scenario for overwriting a file with Mtime
owncloud/core pull request #37607
Opened 2020-06-29 11:15 UTC by Talank

## Description
API test scenario for a file with the new Mtime is added. Follow up of https://github.com/owncloud/core/pull/37553
 
## Related Issue
Part of https://github.com/owncloud/ocis-reva/issues/273

## How Has This Been Tested?
- Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-06-29 11:35 UTC, individual-it requested changes

2020-06-29 11:35 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    When user "Alice" uploads file with content "uploaded content for file name ending with a dot" to "file.txt" using the WebDAV API
make it a given step, this is not what we are testing in this test

2020-06-29 11:35 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    And user "Alice" uploads file to "file.txt" with mtime "Thu, 08 Aug 2019 04:18:13 GMT" using the WebDAV API
I think that step should also say the content that is uploaded, so that we can check that the correct content is uploaded.

2020-06-29 11:35 UTC, individual-it commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    And as "Alice" the mtime of the file "file.txt" should be "Thu, 08 Aug 2019 04:18:13 GMT"
I think in that case it would be good also to check the content

2020-06-30 11:16 UTC, swoichha commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    Then as "Alice" the mtime of the file "file.txt" should be "Thu, 08 Aug 2019 04:18:13 GMT"
```suggestion
    Then as "Alice" file "file.txt" should exist
    And as "Alice" the mtime of the file "file.txt" should be "Thu, 08 Aug 2019 04:18:13 GMT"
```

2020-07-01 03:06 UTC, individual-it approved these changes
looks good, please try to run this test in ocis & ocis-reva repo also, if it works you can remove the skip tag

2020-07-02 07:26 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (\TestHelpers\OcisHelper::isTestingOnOcis()) {
what is that for?

2020-07-02 08:02 UTC, Talank commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (\TestHelpers\OcisHelper::isTestingOnOcis()) {
because in ocis, mtime format that we got from PROPFIND is  `Thu, 08 Aug 2019 04:18:13 +0000` which was expected to be `Thu, 08 Aug 2019 04:18:13 GMT`. The mtime we get from PROPFIND is correct only the format for representing time zone is different in ocis.

2020-07-02 11:04 UTC, swoichha reviewed
LGTM :+1:

2020-07-02 11:13 UTC, individual-it approved these changes
looks good
Please squash commits before merging & rerun ocis PRs with most recent code

2020-07-03 11:05 UTC, dpakach approved these changes
lgtm :+1:

2020-07-03 11:06 UTC, dpakach commented
@Talank  please squash your changes and maybe this time codecov will also pass

2020-07-03 11:36 UTC, jasson99 reviewed
LGTM

2020-07-06 03:05 UTC, phil-davis reviewed
@Talank please rebase to latest core master and squash. (We don't want 7 commits to master)
Code looks good.

2020-07-06 03:26 UTC, swoichha approved these changes
LGTM

2020-07-06 05:19 UTC, Talank commented
Blocked by https://github.com/owncloud/core/pull/37646

2020-07-06 09:35 UTC, phil-davis commented
@Talank PR #37646 has been merged. Please rebase.

2020-07-06 10:32 UTC, phil-davis approved these changes

2020-07-06 12:11 UTC, merged