[Tests-Only] Api test for copying file within a public link folder
owncloud/core pull request #37627
Opened 2020-07-02 09:11 UTC by swoichha

## Description
API test scenario for copying a file within within a public link folder

## Related Issue
https://github.com/owncloud/ocis-reva/issues/310

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-07-02 11:19 UTC, jasson99 commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    When user "Alice" copies file "/testFolder" to "/testFolder-copy" using the new public WebDAV API
```suggestion
    When user "Alice" copies folder "/testFolder" to "/testFolder-copy" using the new public WebDAV API
```

2020-07-02 11:19 UTC, jasson99 commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" file "/PARENT/testFolder" should exist
```suggestion
    And as "Alice" folder "/PARENT/testFolder" should exist
```

2020-07-02 11:19 UTC, jasson99 commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" file "/PARENT/testFolder-copy" should exist
```suggestion
    And as "Alice" folder "/PARENT/testFolder-copy" should exist
```

2020-07-03 08:16 UTC, individual-it requested changes
more tests should be added to cover copy operations that should not work, but that can be in a new PR

2020-07-03 08:16 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" file "/PARENT/copy1.txt" should exist
please also check the content of the copy and the original file, just to make sure the data hasn't been corrupted

2020-07-03 08:16 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And user "Alice" has created folder "/PARENT/testFolder"
place some file in the folder, so the copy operation is more than just creating a folder

2020-07-03 08:16 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +@api @files_sharing-app-required @public_link_share-feature-required @skipOnOcis @issue-ocis-reva-310
I believe that should work on OCIS now, so no need to skip it on ocis

2020-07-03 10:52 UTC, individual-it approved these changes
please squash before merging!

2020-07-03 11:35 UTC, jasson99 reviewed
LGTM

2020-07-03 12:02 UTC, merged