[Tests-Only] Api test for copying file within a public link folder
owncloud/core pull request #37660
Opened 2020-07-07 08:35 UTC by swoichha

## Description
API test scenario for copying a file within within a public link folder

## Related Issue
- owncloud/ocis-reva#310
- Fixes https://github.com/owncloud/ocis-reva/issues/338

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-07-07 10:12 UTC, individual-it requested changes
more ideas what to test:
- copy a file to a name of an existing folder
- copy a file where the source name has some difficult characters
- copy a file where the destination name has some difficult characters
- copy a file where the destination folder name has some difficult characters

example for difficult characters: https://github.com/owncloud/core/blob/bcc6b5b422754e4474b901ff93047bccdde9adb9/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature#L26

- copy a folder to a destination with a name of an existing file
- copy a file/folder to itself
- copy a file/folder to an empty name

2020-07-08 06:17 UTC, jasson99 commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And user "Alice" has uploaded file with content "some data" to "/PARENT/copy1.txt"
IMO the content should be different.

2020-07-08 06:17 UTC, jasson99 commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    When user "Alice" copies folder "/testFolder" to "/copy1.txt" using the new public WebDAV API
is it copied to a same folder name as already existing one?

2020-07-08 10:15 UTC, swoichha commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    When user "Alice" copies folder "/testFolder" to "/copy1.txt" using the new public WebDAV API
Yes, it copies `testfile.txt` inside of folder `testFolder` to already existing file `copy1.txt`. File `copy1.txt` is overridden and it is now a folder with `testfile.txt` inside of it.

2020-07-08 11:20 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" folder "/PARENT/copy1.txt" should exist
wow that overwrites the folder and makes it a file?

2020-07-08 11:22 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" folder "/PARENT/new-folder" should exist
looks like that became a file now

2020-07-08 11:22 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +      | C++ file.cpp          |
add a filename containing a comma, we had recently issue with that

2020-07-08 11:23 UTC, individual-it requested changes
added some comments, need to clarify if the overwrite is correct

2020-07-08 11:48 UTC, phil-davis reviewed
We should also have ordinary COPY test scenarios that copy a file over a folder, and a folder over a file for an ordinary user's files/folders and files/folders in a received share. But that can be in a separate PR.

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +  Scenario: Copy file within a public link folder to same file name as already exiting one
```suggestion
  Scenario: Copy file within a public link folder to same file name as already existing one
```

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +  Scenario: Copy folder within a public link folder to same folder name as already exiting one
```suggestion
  Scenario: Copy folder within a public link folder to the same name as an already existing file
```

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +  Scenario: Copy file within a public link folder to a file with name same as of existing folder
```suggestion
  Scenario: Copy file within a public link folder to a file with name same as an existing folder
```

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +      | destination-file-name |
```suggestion
      | file-name |
```
It is hard to say if this is source or destination file name - in the `Given` it is the destination to create, in the `When` it is  the source to copy from.

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +  Scenario Outline: Copy file within a public link folder to a folder with special characters
```suggestion
  Scenario Outline: Copy file within a public link folder into a folder with special characters
```

2020-07-08 11:48 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +      | destination-file-name |
```suggestion
      | destination-folder-name |
```

2020-07-08 11:58 UTC, phil-davis commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +    And as "Alice" folder "/PARENT/copy1.txt" should exist
I raised issue #37669 to add test scenarios like this for "normal" user files, and files in user/group received shares

2020-07-13 13:26 UTC, individual-it requested changes

2020-07-13 13:26 UTC, individual-it commented on config/identifier-registration.yaml
> +---
file not needed

2020-07-13 13:26 UTC, individual-it commented on ldap.crt
> +-----BEGIN CERTIFICATE-----
file not needed

2020-07-13 13:26 UTC, individual-it commented on ldap.key
> +-----BEGIN RSA PRIVATE KEY-----
file not needed

2020-07-13 13:26 UTC, individual-it commented on server.crt
> +-----BEGIN CERTIFICATE-----
file not needed

2020-07-13 13:26 UTC, individual-it commented on server.key
> +-----BEGIN RSA PRIVATE KEY-----
file not needed

2020-07-14 11:07 UTC, individual-it requested changes
just a small comment and please squash the commits, rest looks good to me

2020-07-14 11:07 UTC, individual-it commented on tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
> +#    And the content of file "/PARENT/new-folder/testfile1.txt" for user "Alice" should be "some data 1"
please remove

2020-07-15 03:18 UTC, individual-it approved these changes

2020-07-15 03:19 UTC, merged