Fix for centering the credential fields on IE11
owncloud/core pull request #37692
Opened 2020-07-14 18:58 UTC by ChrisEdS

## Description
In IE11 the input fields for user and password were not centered.

## Related Issue

https://github.com/owncloud/core/issues/37690

## Motivation and Context
Even users of old browsers should experience centered input fields. 
However, this does not change the fact that IE11 should no longer be used, dear folks.

## How Has This Been Tested?

- Manually tested in IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-07-15 07:05 UTC, mmattel commented
@ChrisEdS pls change the type in changelog from `Fix` --> `Bugfix` else you will not get a happy CI :smile:

...
file changelog/unreleased/37692: entry type "Fix" is invalid, valid types: map[Bugfix:2 Change:3 Enhancement:4 Security:1]
...

2020-07-15 07:13 UTC, micbar requested changes
Please change the target branch to `release-10.5.0`

2020-07-15 07:24 UTC, phil-davis commented
I made PR #37693 to `release-10.5.0` branch. That was easy, and does not get tangled up trying to switch branches here.

2020-07-15 09:27 UTC, micbar approved these changes

2020-07-15 09:27 UTC, micbar commented
ok, so we merge both

2020-07-15 10:21 UTC, phil-davis commented
We can merge just #37693 - and it will get merged-back into master when the release is finished.
@micbar you choose, but we need #37693 approved.

2020-07-29 11:13 UTC, phil-davis commented
Note: #37693 is merged in `release-10.5.0`. So this change will end up getting merged-back from `release-10.5.0` into `master` in due course.
Leaving this PR open for now, but probably we can close it.

2020-07-29 14:26 UTC, micbar approved these changes

2020-09-04 05:10 UTC, phil-davis commented
This code is in `master` now, after 10.5.0 was merged back in #37764

2020-09-04 05:10 UTC, closed without merging