[10.5.0] Ignore enterprise_key app when checking for apps to default_enable
owncloud/core pull request #37711
Opened 2020-07-20 16:19 UTC by phil-davis

## Description
If someone upgrades to 10.5.0 and then, after putting the 10.5.0 code in place, they copy back their non-core apps from the previous installation, and that includes an recent but old version of the `enterprise_key` app, then the `enterprise_key` app will not have any core `max_version` set, and it will have `default_enable` in its `info.xml`. So the `enterprise_key` app will get auto-enabled.

That is unfortunate in 10.5.0!

This PR teaches the server code about the special-case of the `enterprise_key` app.

1) it will now be ignored when calculating the "shipped apps" (which include apps that have `default_enable`)
2) the `occ app:enable` command will also refuse to enable it (e.g. if someone puts an old version in their `apps` dir and then manually tries to `occ app:enable enterprise_key`)

## How Has This Been Tested?
```
$ php occ a:e enterprise_key

In app.php line 390:
                                                                                 
  App enterprise_key can't be enabled. It is not used from core 10.5.0 onwards.  
                                                                                 

app:enable [-g|--groups GROUPS] [--] <app-id>
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-07-20 16:26 UTC, phil-davis commented
These seem to be the 2 places to protect against accidentally enabling `enterprise_key` in core from 10.5.0 onward. It should stop the `enterprise_key` app from getting accidentally enabled.

Any better ideas are welcome. core needs to have special knowledge about this "old" app to avoid it. So I'm not sure how to make the "nicer"/"more generic"

2020-07-21 03:36 UTC, phil-davis commented
What is the chance for unit tests in this code?
Somebody give me clues please.

2020-07-23 10:53 UTC, jnweiger requested changes
We have an alternative solution to mitigate the situation addressed here.
https://github.com/owncloud/enterprise_key/pull/132
@phil-davis please review there and check, if that completeley this PR in part, or fully.

2020-07-23 11:41 UTC, phil-davis commented
@jnweiger the "empty" enterprise_key app will be fine, as long as the site actually has that new version of enterprise_key app. If it is distributed in the "app bundle" with 10.5.0 tarballs, then admins will get it.

But what happens if an admin installs some old version of the enterprise_key app like 0.2.0 which does not have max_version 10.4 and enables it, and ignores that it not the latest? Do we want the server to protect against installation of old versions of apps that should be "gone"?

2020-07-23 11:46 UTC, jnweiger commented
Valid point. So the dummy app does not really replace this. It amends it nicely.
I propose to build RC6 including this and the dummy app.

2020-07-23 11:50 UTC, jnweiger approved these changes
Thanks for the clarifications. Approved!

2020-07-23 11:52 UTC, merged

2020-07-23 11:53 UTC, phil-davis commented
Merged. IMO RC6 can be built when you have the "dummy" enterprise_key app ready.