[Tests-Only]Modify functions to check the presence of files and folders
owncloud/core pull request #37721
Opened 2020-07-22 10:17 UTC by jasson99

## Description
This PR modifies the function used to assert the presence or absence of files/folders such that it strictly checks for the files and folders as provided in the step.

## Motivation and Context
We had functions to assert that a file/folder exists or doesnot exist. The tests passed for the presence or absence of a file with the same name when the step actually wanted to assert that for a folder, and vice versa. However, sometimes strict assertions are needed.

## How Has This Been Tested?
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-07-22 10:33 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebDav.php
> +			return;
I don't think you need to check all this if the file/folder is not expected to exist.

2020-07-22 10:33 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebDav.php
> +			Assert::isEmpty(count($isCollection), 0, "Unexpectedly, `$path` is not a file");
```suggestion
			Assert::assertEquals(count($isCollection), 0, "Unexpectedly, `$path` is not a file");
```

2020-07-22 10:36 UTC, phil-davis commented
@jasson99 needs code style fixed so we can see the actual test run:
https://drone.owncloud.com/owncloud/core/26047/2/6

2020-07-22 11:03 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +			Assert::isEmpty(count($isCollection), 0, "Unexpectedly, `$path` is not a file");
fixed

2020-07-22 11:04 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +			return;
but it should pass when we are checking for the absence of a folder but a file with the same name is found

2020-07-22 11:29 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +			return;
These lines could be removed. The function will exit anyway right after here.

2020-07-22 11:29 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
This line can go inside `if ($this->isEtagValid()) {}`
And then there will be less chance that it will fail completely somehow.

2020-07-22 11:29 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +			}
```suggestion
			$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
			if (\count($isCollection) === 0) {
				$actualResourceType = "file";
			} else {
				$actualResourceType = "folder";
			}
			Assert::assertFail(
				"$entry '$path' should not exist. But it does exist and is a $actualResourceType";
			);
```

whenever we get inside `isEtagValid()` then we have to fail. Because if the Etag is valid then the file or folder exists.

Code something like this might work to report what type of resource was expected to not exist, and what type of resource did actually exist.

2020-07-22 11:33 UTC, individual-it requested changes

2020-07-22 11:33 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
should be moved into the `if ($this->isEtagValid()) {` block as its only needed in that case

2020-07-22 11:33 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
can be moved after the assert in the next line

2020-07-23 05:41 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +			return;
fixed

2020-07-23 05:41 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
fixed

2020-07-23 05:41 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +			}
fixed

2020-07-23 05:41 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
fixed

2020-07-23 05:42 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$isCollection = $this->getResponseXmlObject()->xpath("//d:prop/d:resourcetype/d:collection");
fixed

2020-07-23 05:42 UTC, jasson99 commented on tests/acceptance/features/bootstrap/TransferOwnershipContext.php
> +	 * @return void
fixed

2020-07-23 06:05 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +		} else {
```suggestion
		} elseif ($entry === "file") {
```

We should only make this assert when the step specifically said `file "abc" should exist'

If the feature file has a step `entry "abc" should exist` then we only care that the entry exists. It can be a file or a folder.

2020-07-23 07:17 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/26053/55/13
```
  Scenario: Download a file that exists in filecache but not storage fails with 404          # /drone/src/tests/acceptance/features/apiMain/external-storage.feature:49
    Given user "Alice" has been created with default attributes and skeleton files           # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "Alice" has created folder "/local_storage/foo3"                                # FeatureContext::userHasCreatedFolder()
    And user "Alice" has moved file "/textfile0.txt" to "/local_storage/foo3/textfile0.txt"  # FeatureContext::userHasMovedFile()
    And file "foo3/textfile0.txt" has been deleted from local storage on the server          # FeatureContext::fileHasBeenDeletedInLocalStorage()
    When user "Alice" downloads file "local_storage/foo3/textfile0.txt" using the WebDAV API # FeatureContext::userDownloadsFileUsingTheAPI()
    Then the HTTP status code should be "404"                                                # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as "Alice" file "local_storage/foo3/textfile0.txt" should not exist                  # FeatureContext::asFileOrFolderShouldNotExist()
      file 'local_storage/foo3/textfile0.txt' should not exist. But it does exist and is a file
```

The new code for `And as "Alice" file "local_storage/foo3/textfile0.txt" should not exist` is probably finding the file in the file cache.

That last step could be changed to "should exist"

An raise an issue to discuss what should happen. Because I think that  when a client attempts a download of a file, the file is not found, and the client gets a 404, then the server should remove knowledge about the file from the file cache.

At the moment it seems to leave the file entry in the file cache, and someone has to do a scan of the storage to clear the file cache entry.

2020-07-23 07:22 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/26053/63/13
```
  Scenario Outline: user tries to share a folder with another user when the sharing api has been disabled  # /drone/src/tests/acceptance/features/apiShareManagement/disableSharing.feature:25
    Given using OCS API version "<ocs_api_version>"                                                        # FeatureContext::usingOcsApiVersion()
    When parameter "shareapi_enabled" of app "core" has been set to "no"                                   # AppConfigurationContext::serverParameterHasBeenSetTo()
    Then user "Alice" should not be able to share folder "/FOLDER" with user "Brian" using the sharing API # FeatureContext::userTriesToShareFileUsingTheSharingApi()
    And the OCS status code should be "404"                                                                # OCSContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "<http_status_code>"                                                # FeatureContext::thenTheHTTPStatusCodeShouldBe()

    Examples:
      | ocs_api_version | http_status_code |
      | 1               | 200              |
        Unexpectedly, `/FOLDER` is not a file
        Failed asserting that 0 matches expected 1.
      | 2               | 404              |
        Unexpectedly, `/FOLDER` is not a file
        Failed asserting that 0 matches expected 1.
```

I guess that `Then user "Alice" should not be able to share folder "/FOLDER" with user "Brian" using the sharing API` is first checking that the folder exists. Probably the code will need to pass "folder" through to the "should exist" code.

There are other scenarios that  fail in a similar way. Please check the CI results.

This change is "a good thing" - it is finding places where file/folder might be mixed up in test scenarios.

2020-07-23 07:58 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		} else {
fixed

2020-07-23 10:13 UTC, individual-it commented on tests/acceptance/features/apiMain/external-storage.feature
> +    And as "Alice" file "local_storage/foo3/textfile0.txt" should exist
why should that file now exist?

2020-07-23 10:14 UTC, individual-it submitted a review, later dismissed
please make sure these changes also work correctly in ocis, ocis-reva and cs3org/reva

2020-07-23 10:41 UTC, phil-davis commented on tests/acceptance/features/apiMain/external-storage.feature
> +    And as "Alice" file "local_storage/foo3/textfile0.txt" should exist
The code for "should not exist" has changed the way that it detects if the file "exists".

Previously it did a `GET` of the file, which was effectively the same as `When user "Alice" downloads file...` - because the file actual does not exist in the underlying local storage file system, the `GET` returns a 404.

But now, "should not exist" uses a similar request to "should exist" and is just getting the Etag etc properties of the file. That is found in the file cache (database) and gets returned. For that "properties-only" request the server does not need to read the actual file content on disk. So the server never notices that the file content is gone. So the file "does exist".

Actually IMO this makes the test "better" (more readable), after reading the description:
`Scenario: Download a file that exists in filecache but not storage fails with 404`

The file "exists" as far as the ownCloud database is concerned, but cannot be downloaded.

The behavior on OCIS will need to be sorted out, because OCIS is probably better - there will not be the distinction between "the database file cache" and "the real filesystem". So this might become an example of bad behavior in oC10 and correct behavior in OCIS

2020-07-24 08:09 UTC, phil-davis commented on tests/TestHelpers/WebDavHelper.php
> +	 * @return SimpleXMLElement|ResponseInterface
This `listFolder` is called by WebDav.php `listFolder` and TrashbinContext.php `listTrashbinFolder`
And those are called by various things. But they seem to be all "positive" checks on a resource that should exist. So maybe they will be OK?

2020-07-24 08:09 UTC, phil-davis commented on tests/TestHelpers/WebDavHelper.php
>  		$responseXmlObject = HttpRequestHelper::getResponseXml($response);
Maybe we should only directly return the response if `isTestingOnOcis` and HttpRequestHelper::getResponseXml fails?

`HttpRequestHelper::getResponseXml()` throws an exception, so we could catch that and if `OcisHelper::isTestingOnOcis()` then `return $response` and otherwise re-throw the exception.

That will allow us to process the `$responseXmlObject` in cases where OCIS does return it.

2020-07-24 08:09 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (OcisHelper::isTestingOnOcis()) {
We could check here if `$this->responseXmlObject` is a `ResponseInterface` 

If we are testing on OCIS but do get a proper XML object back, then it will be good to run the "normal"  code in the `else` block.

2020-07-24 08:12 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (OcisHelper::isTestingOnOcis()) {
But listFolder function returns response only when testingOnOcis.

2020-07-24 08:17 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (OcisHelper::isTestingOnOcis()) {
You can modify `listFolder` so that it always tries to get the XML. But if that throws an exception, then check if testing on OCIS, and only then return the whole response.

That way we minimize the change in behavior of the code. If an OCIS call does return some valid XML in the response then we will check it in the same way as we do on oC10. As these sort of issues are fixed on OCIS, the test code will automatically check the XML of OCIS  responses.

2020-07-24 08:38 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (OcisHelper::isTestingOnOcis()) {
fixed

2020-07-24 08:38 UTC, jasson99 commented on tests/TestHelpers/WebDavHelper.php
>  		$responseXmlObject = HttpRequestHelper::getResponseXml($response);
fixed

2020-07-24 08:40 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (\gettype($this->responseXmlObject === "ResponseInterface")) {
```suggestion
		if (\gettype($this->responseXmlObject) === "ResponseInterface") {
```
IMO the brackets need fixing

2020-07-24 09:08 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		if (\gettype($this->responseXmlObject === "ResponseInterface")) {
fixed

2020-07-24 09:14 UTC, phil-davis reviewed
Looking good so far - let's see what CI says in each repo.

2020-07-27 06:07 UTC, phil-davis commented
I requested review from myself again so that I see this in my list. @jasson99 please ping when you have got this passing in ocis-reva (or when you get really stuck!)

2020-07-28 08:04 UTC, phil-davis approved these changes

2020-07-28 08:04 UTC, merged