[nomerge] dedicated reva test suite changes
owncloud/core pull request #37798
Opened 2020-08-10 12:58 UTC by butonic

Currently, reva implements the ocs api, but we are moving it to ocis-ocs.

Some of the changes make endpoints return different statuscodes. To unblock other PRs in reva we will use this branch until the testuite there has moved to cs3 grpc api based testing.

Affected PRs:
- https://github.com/cs3org/reva/pull/1064

2020-08-10 13:17 UTC, butonic commented
pinging @individual-it and @phil-davis to double check the approach makes sense to them as well.

2020-08-10 14:35 UTC, individual-it commented
:+1: LGTM. we even could merge this here as the tests in other repos are bound to a commitid

2020-08-10 15:37 UTC, phil-davis commented
Something is stuck in codecov ??? It says it is "in progress" but no result.

2020-08-10 15:39 UTC, phil-davis approved these changes

2020-08-10 15:44 UTC, phil-davis commented
As @individual-it says, we can merge this. And actually PR https://github.com/cs3org/reva/pull/1036 is waiting for merge and that gives local control of the core API test scenarios ffor `cs3org/reva`

The same has already been done in `owncloud/ocis-reva`.

The same is waiting in https://github.com/owncloud/ocis/pull/427 because we did not want to cause confusion with the current efforts to get `owncloud/ocis` updated. (But maybe it will make life easier in `owncloud/ocis` by merging that?)

2020-08-11 11:20 UTC, individual-it requested changes
as discussed today lets not merge this but apply the system of https://github.com/owncloud/ocis/pull/427 
also waiting for https://github.com/owncloud/ocis/pull/439

2020-12-12 08:47 UTC, phil-davis commented
codecov suddenly posted a report!!!???

@butonic is this PR still relevant to anything?

2021-06-25 06:17 UTC, butonic commented
I guess this is outdated

2021-06-25 06:17 UTC, closed without merging