redesign ugly, yellow notification center
owncloud/core pull request #37875
Opened 2020-09-02 13:38 UTC by hurradieweltgehtunter

2020-09-02 19:41 UTC, mmattel commented
Without having tested it, this must work very well with https://github.com/owncloud/direct_menu 😃

2020-09-03 03:02 UTC, phil-davis commented
CI fails - see #37877 - need to look at how a user can clear the notification so that they can see file(s) behind it.

2020-09-03 07:40 UTC, hurradieweltgehtunter commented
> CI fails - see #37877 - need to look at how a user can clear the notification so that they can see file(s) behind it.

Uh that's unfortunate. I didn't touch the JS logic, I just did css changes. Some notifications do not have a close button in general (only type: error).
IMHO the notifications do not block the access of files since the user can just scroll down. 

There could be a solution: Change all notifications to `type:error` so the closing icon appears.
See comment https://github.com/owncloud/core/issues/37877#issuecomment-686314819

2020-09-03 10:04 UTC, hurradieweltgehtunter commented
I think these are two different topics. My changes only affect the appearance. Clearing notifications is changing the behaviour -> JS work
Question is, if the notifications on the bottom are really that bad for the user (= failing test) or if the test needs to be adjusted.
IMO the new look does does not overlay the whole file (max-width: 60%) so it's still clickable. For non-clearable notifications it is quite important to resolve the hint. Thus, permanently showing it is ok.
Clearable notifications are not blocking anything too.

Todo: Check all notifications if they should be clearable or not and change them accordingly -> different scope to this PR
What do you think?

2020-09-03 10:59 UTC, phil-davis commented
Yes, the problem with the tests is not strictly a blocker for this PR. A real user can scroll the files list so that the file they want to see is visible above the notification, and then open the sharing panel or whatever they want to do.

The selenium test driver "automagically" scrolls the file list so that the required file  is in the "displayed" part of the file list. e.g. it scrolls down so that `lorem.txt` is "on  the screen" - but only just on the bottom of the "screen". It ends up where the notification overlays the bottom part of the file list.

We can either:
1) sort out the tests so they don't rely on files that are a long way down the list (or some other test workaround) or;
2) make this notice dismissable, and adjust the test so that after checking that the notice is there, it clicks the "close-dismiss" button to get rid of the notification.

Actually (2) will provide better UI anyway (give the user a way to acknowledge and dismiss the notification), and the test scenario will also flow smoothly in a similar way to a typical user.

2020-09-07 08:26 UTC, hurradieweltgehtunter commented
Agreed. But then we need to change the notifications' JS logic. Either
- Change the defaults notification behaviour to have all types of notifications include the close button
or
- Change all notifications in OC to `type: error`

So far I didn't find the declaration of the notification function. Need to inspect which one is more suitable ( I think the cirst one)

2020-09-10 13:02 UTC, hurradieweltgehtunter commented
Latest change switched notifications to show close button as default setting. 
Added option `hideCloseButton` to hide it explicitly (useful for some notifications).

Questions is: Were the notifications until now intented to be not closeable?

2020-09-10 19:08 UTC, hurradieweltgehtunter commented
Made some important notifiactions not dismissible (Integrity Check, Trial License). 
Somehow the JS Tests fail even more. Someone should check this out, I'm not aware how therse tests work and can be fixed.

2020-09-11 02:41 UTC, phil-davis commented
Needs a rebase because https://drone.owncloud.com/owncloud/core/26733/64/13 
```
[Behat\Testwork\Suite\Exception\SuiteNotFoundException]                            
  `apiShareManagementBasic` suite is not found or has not been properly registered.
```
The API test suite name changed yesterday. This branch needs and up-to-date "view" of the changed `.drone.star`

2020-09-11 06:58 UTC, phil-davis commented
I pushed webUI acceptance test code to dismiss the notification in the locking tests before going on to check items on the files page. I will let CI run then we can rebase...

2020-09-11 07:50 UTC, phil-davis commented
> Made some important notifiactions not dismissible (Integrity Check, Trial License).
> Somehow the JS Tests fail even more. Someone should check this out, I'm not aware how therse tests work and can be fixed.

I adjusted a JS test expectation so that it knows to expect the close button to exist.

2020-09-11 07:52 UTC, phil-davis commented
Rebased. CI should all pass now.

@micbar ready for technical review and review of the new UI from a user perspective. Please allocate the appropriate people.

If all is approved, then commits could be squashed... before merge.

2020-09-14 14:33 UTC, DeepDiver1975 requested changes
And some sqashing of commits would be good habit from my pov .....

2020-09-14 14:33 UTC, DeepDiver1975 commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
negative logic is beyond best practice

Please use 'showCloseButton' instead of 'hideCloseButton'

2020-09-14 15:24 UTC, phil-davis commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
```suggestion
	 * @param {string} [options.type] notification type
	 * @param {string} [options.hideCloseButton] hide close button
```
Bracket-pairing needs fixing.
(and also comment above by @DeepDiver1975

2020-09-15 08:47 UTC, hurradieweltgehtunter commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
But it is the desired behaviour. Close button is always visible until this option is set to true.
Using `showCloseButton` would mean to change every single implementation of `showNotification`

2020-09-15 08:51 UTC, micbar commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
Use positive default?

2020-09-15 09:35 UTC, DeepDiver1975 commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
I'm not asking to change the behavior but to change the program and api logic to make it more intuitive.

Having showCloseButton with default true is the same as hideCloseButton with default false and vise-versa.

2020-09-15 14:07 UTC, hurradieweltgehtunter commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
Yeah wasn't thinking right. Switched to positive logic.

2020-09-15 14:16 UTC, hurradieweltgehtunter commented on core/js/js.js
> +	 * @param {string] [options.hideCloseButton] hide close button
done

2020-09-15 14:16 UTC, hurradieweltgehtunter commented
Squashed commits

2020-09-15 14:25 UTC, phil-davis commented on core/js/js.js
> +		if (options.showCloseButton !== true) {
```suggestion
		if (options.showCloseButton === true) {
```
Or do I not understand?

2020-09-15 14:25 UTC, phil-davis commented on core/js/js.js
> +	 * @param {string} [options.hideCloseButton] hide close button
This looks out-of-date.

2020-09-16 08:41 UTC, hurradieweltgehtunter commented on core/js/js.js
> +		if (options.showCloseButton !== true) {
you are right. done

2020-09-16 08:41 UTC, hurradieweltgehtunter commented on core/js/js.js
> +	 * @param {string} [options.hideCloseButton] hide close button
done

2020-09-17 05:54 UTC, phil-davis commented on core/js/js.js
> +			showCloseButton: false,
I was fixing the JS tests, and switched  this from default true to default false. That preserves whatever was the previous behavior of existing notifications.

But maybe we do want to give notifications a close button by default???

2020-09-17 05:55 UTC, phil-davis commented on core/js/js.js
> +		if ((options.showCloseButton === true) || (options.type === 'error')) {
And I put back the `(options.type === 'error')` so that whatever notifications are currently type "error" will continue to show a close button.

2020-09-17 05:57 UTC, phil-davis commented on core/js/license-state-notification.js
> +			OC.Notification.showHtml(data.translated_message.join('<br/>'), {showCloseButton: false});
This is a behavior change. Prior to this, the license notification would have had a close button, now it will not have a close button. Is that change intended?

2020-09-17 06:00 UTC, phil-davis commented
I rebased and fixed the JS tests. While doing that, I made `showCloseButton` default to `false` to preserve the existing behavior more closely. See my comments above.

Or should we make `showCloseButton` be true by default, and make sure to find all the notifications that should not have a close button, and make them explicitly set `showCloseButton` to false?

2020-09-17 08:08 UTC, hurradieweltgehtunter commented on core/js/license-state-notification.js
> +			OC.Notification.showHtml(data.translated_message.join('<br/>'), {showCloseButton: false});
License notifications and CSFR check notifications should not be closeable, yes

2020-09-17 08:09 UTC, hurradieweltgehtunter commented
`showCloseButton = true` should be the default

2020-09-17 09:33 UTC, phil-davis commented
I will change the default back to `showCloseButton = true` and adjust tests...

2020-09-17 10:45 UTC, phil-davis commented
Done - `showCloseButton = true` is the default. Hopefully CI passes!

I assigned myself so that I easily notice this PR. If the net code diff is OK now, I can squash the commits and merge.

@DeepDiver1975 @micbar please review again.

2020-09-17 10:52 UTC, DeepDiver1975 approved these changes

2020-09-17 11:00 UTC, phil-davis approved these changes
squashed - this should be OK to merge when CI passes

2020-09-17 15:56 UTC, merged

2020-09-18 11:43 UTC, hurradieweltgehtunter commented
🍾  thank you for your help!

2020-09-18 12:13 UTC, mmattel commented
@hurradieweltgehtunter 
can you please file a docs issue and link it.
this merged pr is docs relevant 😃

2020-09-18 13:50 UTC, phil-davis commented
docs PR https://github.com/owncloud/docs/issues/2793