[Tests-Only] Fix timing problem in testScanShareInvalidLastScan
owncloud/core pull request #37888
Opened 2020-09-06 16:34 UTC by phil-davis

## Description

## How Has This Been Tested?
Local unit test runs

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-09-06 16:43 UTC, phil-davis commented on apps/files_sharing/tests/External/ScanExternalSharesJobTest.php
> +		$lastScanThreshold = '2';
Without this change, adding `\sleep(1)` here makes the test fail.
An unlucky tick of the system clock between setting `'lastscan' => \time(),` at line 274, and getting into the the code of `shouldScan` causes the test to fail.

2020-09-07 16:12 UTC, mrow4a requested changes

2020-09-07 16:12 UTC, mrow4a commented on apps/files_sharing/tests/External/ScanExternalSharesJobTest.php
> +		$lastScanThreshold = '2';
perfectly fine, most important is that it is larger :) could be even larger, as `\time()+2` could still see issue.

Plus would be good to add -> `add 10 seconds to time() in order to force shouldScan return false`

2020-09-09 04:43 UTC, phil-davis commented on apps/files_sharing/tests/External/ScanExternalSharesJobTest.php
> +		$lastScanThreshold = '2';
Or I could make a more realistic "ordinary" case - set `$lastScanThreshold = '20'`  and `'lastscan' => \time() - 10,`

A share that has been scanned 10 seconds ago, and the last scan threshold is 20 seconds, should not be chosen for scanning.

The existing test here was checking exactly the edge case of the last scan time being just 1 second different from the threshold. But actually for this feature we don't care about that sort of edge case. e.g. if the threshold is set to 900 seconds (15 minutes) then if a share was last scanned 899, 900, or 901 seconds ago we really do not care if the one at exactly 900 seconds is chosen for scanning or not. The requirement does not need to specify and test that.

2020-09-10 11:29 UTC, phil-davis commented on apps/files_sharing/tests/External/ScanExternalSharesJobTest.php
> +		$lastScanThreshold = '2';
I did what I wrote above ^

2020-09-10 12:07 UTC, mrow4a commented
@phil-davis shalll we do the same with login ?

2020-09-10 12:14 UTC, phil-davis commented
> @phil-davis shall we do the same with login ?

`testScanShareInvalidLastLogin` does not have the same timing issue. It sets the user to have last logged in 2 seconds ago, then sets the last login threshold to 1 second, then calls `shouldScan`. If there is 1 or more seconds delay before `shouldScan` runs then it makes no difference to the test result. The user will look like they last logged in 3, 4, 5... seconds ago, the threshold is 1 second, so they will not be considered a "recent" user.

Do you think I should adjust those numbers anyway to be more "realistic"?

2020-09-15 09:16 UTC, phil-davis commented
@mrow4a or anyone, please review

2020-09-15 10:08 UTC, mrow4a approved these changes

2020-09-15 10:28 UTC, merged