Add new defaults for the icon and label of the phoenix menu item
owncloud/core pull request #37923
Opened 2020-09-21 12:55 UTC by kulmann

## Description
When phoenix is configured (phoenix.baseUrl in config.php), the app switcher has a menu item for Phoenix. This now has a new and configurable default icon and default label, as discussed and decided by the design initiative last week.

Open question: Is it relevant to have translations for the menu item label?

## Related Issue
- Fixes https://github.com/owncloud/product/issues/227

## Motivation and Context
Make it easier for users to spot the switch to the new design.

## How Has This Been Tested?
✋ 

## Screenshots (if appropriate):
<img width="1427" alt="Screenshot 2020-09-21 at 14 29 11" src="https://user-images.githubusercontent.com/3532843/93768826-437f8000-fc1a-11ea-8208-84305445e040.png">
<img width="1427" alt="Screenshot 2020-09-21 at 14 29 24" src="https://user-images.githubusercontent.com/3532843/93768835-47130700-fc1a-11ea-89e3-1b4966dc1c2b.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-09-21 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=37923) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=37923) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=37923) it.</sub>

2020-09-21 13:06 UTC, pmaier1 commented
Nice work, thanks!

> Open question: Is it relevant to have translations for the menu item label?

Yes, please!

2020-09-21 13:55 UTC, DeepDiver1975 requested changes

2020-09-21 13:55 UTC, DeepDiver1975 commented on lib/private/NavigationManager.php
> +				'name' => $l->t($label),
no need to translate this - there is no string that can be extracted and translate by anybody.
If you want 'New Design' to be translated - call $l->t() in line 197

2020-09-21 14:02 UTC, kulmann commented on lib/private/NavigationManager.php
> +				'name' => $l->t($label),
Fixed, thank you!

2020-09-21 14:23 UTC, micbar approved these changes

2020-09-22 04:51 UTC, kulmann commented
@micbar codecov results are missing...

2020-09-22 04:54 UTC, phil-davis commented
codecov results are almost always missing in core. I had a support ticket about that - https://codecov.freshdesk.com/support/tickets/3634 - but no joy yet. Some days the results get posted back to GitHub, some days not.

2020-09-22 04:57 UTC, kulmann commented
Ah, ok. Thanks for explaining @phil-davis :-)

2020-09-22 07:56 UTC, merged