[Tests-Only] Refactor apiShareCreateSpecial1 to use Shares folder
owncloud/core pull request #37938
Opened 2020-09-23 10:50 UTC by HariBhandari07

## Description

This PR makes `apiShareCreateSpecial1` test scenarios to be valid in both oC10 and OCIS. OCIS always puts received shares into a folder called Shares for the share receiver. On OCIS, auto-accept shares is always disabled.

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/518
## Motivation and Context

## How Has This Been Tested?

- CI

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-09-25 07:21 UTC, phil-davis requested changes

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               | 200             | 200              |
The `/Shares/Shares/FOLDER` value is issue #37883 
Tag this scenario `notToImplementOnOCIS` and `issue-37883`
Make another similar scenario with the correct expected value `/Shares/FOLDER` and tag it `skipOnOcV10`
That will make sure that we only try to implement code for "good" scenarios in OCIS.

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               | 200             | 200              |
The `/Shares/Shares/FOLDER` value is issue #37883 
Tag this scenario `notToImplementOnOCIS` and `issue-37883`
Make another similar scenario with the correct expected value `/Shares/FOLDER` and tag it `skipOnOcV10`
That will make sure that we only try to implement code for "good" scenarios in OCIS.

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               | 200             | 200              |
Another one that demonstrates issue #37883

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               | 200             | 200              |
Another one that demonstrates issue #37883

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               |
Another one that demonstrates issue #37883

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               |
Another one that demonstrates issue #37883

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               |
Another one that demonstrates issue #37883

2020-09-25 07:21 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +      | 2               |
Another one that demonstrates issue #37883

2020-09-25 07:22 UTC, phil-davis commented
I also raised issue #37944 - it applies to a lot of these "sharing to share_folder" scenarios in multiple PRs. So we can sort that out next week.

2020-09-28 03:25 UTC, dpakach requested changes, later dismissed
Some scenarios have 
`Then the status code should be <code>` step which checks the status of accepting the share not creating the share. Please fix those to check the status of Sharing step.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +    And the HTTP status code should be "<http_status_code>"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +    And the HTTP status code should be "<http_status_code>"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +    And the HTTP status code should be "<http_status_code>"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareExpirationDate.feature
> +    And the HTTP status code should be "<http_status_code>"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareReceivedInMultipleWays.feature
> +    And the HTTP status code should be "200"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 03:25 UTC, dpakach commented on tests/acceptance/features/apiShareCreateSpecialShares1/createShareReceivedInMultipleWays.feature
> +    And the HTTP status code should be "200"
This step is supposed to check the status code of sharing step but here it checks the status of accepting the share.

2020-09-28 05:26 UTC, phil-davis approved these changes

2020-09-28 06:44 UTC, merged