check public link already authenticated before checking password of link
owncloud/core pull request #38016
Opened 2020-10-17 13:13 UTC by karakayasemi

## Description
ShareManager was checking password of already authenticated public links.
This situation has been led to wrong "share.failedpasswordcheck" events emitting in already authenticated links and led to the related issue on brute force protection app. This problem has been resolved by first checking link already authenticated.

@micbar I would like to add this PR to 10.6 if it is possible.

## Related Issue
- Fixes https://github.com/owncloud/brute_force_protection/issues/138

## How Has This Been Tested?
- https://github.com/owncloud/brute_force_protection/issues/138 is resolved after the fix.

## Screenshots (if appropriate):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-10-17 15:51 UTC, phil-davis commented
I restarted drone - in the previous run there were lots of pipelines that had 10-minute timeouts waiting for stuff.

2020-10-19 07:19 UTC, mrow4a requested changes
Before this PR we always checked for password first (even if public_link_authenticated is set). Do you think this can have some security implications? Could you comment on this in the code?

2020-10-19 07:20 UTC, jvillafanez approved these changes

2020-10-19 07:36 UTC, jvillafanez commented
It might be a better idea to let the `shareManager->checkPassword()` function handle the "public_link_authenticated" session variable.
Basically, you don't do anything with the "public_link_authenticated" variable outside the function, but call always to the `checkPassword` function. It will be the `checkPassword` function the one that checks (and sets) the session variable. It could also provide a better control of when the "share.failedpasswordcheck" event is triggered.

2020-10-19 08:39 UTC, phil-davis commented
I restarted ddrone CI  - there were some silly startup fails of PHP unit test pipelines.

2020-10-19 08:43 UTC, micbar commented
@karakayasemi Can we merge this soon to get into 10.6?

2020-10-19 08:51 UTC, phil-davis commented
@micbar - @mrow4a gave a "change requested" review comment. That needs to be cleared (assuming the comment has been addressed...)

2020-10-19 09:09 UTC, karakayasemi commented
> Before this PR we always checked for password first (even if public_link_authenticated is set), or was that just a bug? . Do you think this can have some security implications? Could you comment on this in the code (if relevant)?

@mrow4a if `checkPassword` fails, the code looks `public_link_authenticated` anyway. So, in my opinion there is no risk in terms of security.

> It might be a better idea to let the shareManager->checkPassword() function handle the "public_link_authenticated" session variable.

@jvillafanez I thought same first but there are other usages of `checkPassword` method, since it will change the inside logic of `checkPassword`. So, I did not want to touch `checkPassword` method to keep the change minimal.

> @karakayasemi Can we merge this soon to get into 10.6?

@micbar IMHO, PR is ready to merge after CI problems resolved. There were some unrelated CI fails, I hope this time we will see green CI.

2020-10-19 09:17 UTC, phil-davis commented
fsweb.test.owncloud.com seems to be down (or not working nicely). All core CI pipelines that test against it are failing, in all PRs currently running.

2020-10-19 17:19 UTC, mrow4a approved these changes
@karakayasemi @jvillafanez I did some research, and indeed this change is bugfix. Also, the public link code is spaghetti a little that begs for refactoring https://github.com/owncloud/core/blob/v10.5.0/apps/files_sharing/lib/Controllers/ShareController.php . Also used in public apps https://github.com/owncloud/richdocuments/blob/740bd280caf35c7e8b6e8e96f05320acd9e689b1/lib/Storage.php#L136-L141 . Considering how it is currently implemented, legit solution.

2020-10-20 02:26 UTC, phil-davis commented
Rebased to get fresh CI.

2020-10-20 03:33 UTC, merged