Add the getSharesByPath share method to the interface
owncloud/core pull request #38054
Opened 2020-10-29 13:49 UTC by jvillafanez

This method was being used in the files_sharing app even though it was
an implementation detail. The IShareProvider interface requires that
method to be implemented in the providers already, and the current share
manager already has the method implemented. This means that this will
just expose that method through the interface
In addition, the pagination wasn't being used and it wasn't implemented
in the share providers, so it has been removed

## Description
Make the `getSharesByPath` method available through the interface

## Related Issue
No opened issue.
`getSharesByPath` is used in the files_sharing app, as shown in this PR, and will be used in https://github.com/owncloud/windows_network_drive/pull/310

## Motivation and Context
Using methods not exposed by the interface while using the interface (and not the actual implementation) is a bad practice.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-10-30 19:43 UTC, karakayasemi approved these changes

2020-10-30 19:50 UTC, karakayasemi requested changes
The change make sense to me. I double checked usage of deleted parameters. Just needs changelog entry before merge.

2020-11-03 08:22 UTC, phil-davis commented
@jvillafanez needs a rebase due to a composer major version 2.0 change that happened in CI yesterday.

2020-11-03 10:26 UTC, karakayasemi approved these changes

2020-11-03 10:27 UTC, merged