Coerce occ config:app:set boolish value to 0 or 1 due the string 'fal…
owncloud/core pull request #38099
Opened 2020-11-10 14:50 UTC by HieronymusPerro

…se' will be evaluated to true

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-11-10 14:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38099) before we can accept your contribution.<br/><hr/>**jan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38099) it.</sub>

2020-11-13 13:48 UTC, DeepDiver1975 requested changes
unit test? THX

2020-11-17 13:03 UTC, HieronymusPerro commented
> unit test? THX

Added a acceptance test instead

2020-11-25 12:59 UTC, jvillafanez commented
I don't think this is a good idea.

There are a couple of things to take into account:
* The DB will store any value as string because that's how the DB column is defined.
* The user will always input a string

I guess the main problem here is the lack of information. This cli command is part of core and it very agnostic about how the value will be used.
The key point is that it depends on the app how that value will be interpreted, and as such, it should be documented by the app using the value.

For example, an app could store "useFeature" with "true" or "false", so the app can tell you to use `occ config:app:set app useFeature --value true`. Now, the app could have something like:
```
$useFeature = getFromDB('useFeature');
if ($useFeature === 'true') {
.....
}
```
so yeah, the app is explicitly checking for the "true" string because it knows that the function will return a string, and it expect it to be "true" the same it could expect it to be "theAppMustUseThis" string.
The app could also use the `filter_var` function for a more flexible validation so "1" or "on" could also be accepted as valid, but again, it depends on the app.

My main point is that the interpretation of the value depend on each specific app using the value, and core shouldn't interfere.

Note that this is different than the case with `occ config:system:set` where it will be translated to actual php code, which requires explicit typing.

2020-11-25 13:05 UTC, jvillafanez commented
I agree that having "true" / "false" stored and used as strings is confusing and should be avoided, but it's probably a better idea to promote the usage of "yes" / "no" instead and check the value with `filter_var`.

2020-11-26 08:48 UTC, HieronymusPerro commented
I mostly agree @micbar must decide

2020-12-12 10:15 UTC, mmattel commented
@JanAckermann any news on that?

2020-12-12 10:50 UTC, JanAckermann commented
Not yet @mmattel, I need to speak about this with @micbar 

More thoughts on this are welcome as well

2020-12-12 11:24 UTC, karakayasemi commented on changelog/unreleased/37697
> +Enhancement: Fix expiring a wrong share entry problem
This looks like a copy-paste mistake.

2021-09-16 13:11 UTC, JanAckermann commented
@JammingBen time to say good bye to our real first PR :cry:

2021-09-16 13:11 UTC, closed without merging