adapted solution for 5xx error on i10n vsprintf
owncloud/core pull request #38103
Opened 2020-11-11 13:49 UTC by HieronymusPerro

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-11-11 13:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38103) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38103) before we can accept your contribution.<br/><hr/>**jan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38103) it.</sub>

2020-11-13 09:14 UTC, DeepDiver1975 requested changes
Please add a unit test for this. THX

2020-11-13 13:56 UTC, phil-davis commented on changelog/unreleased/38103
> +form Transifex. This is critical as every user is able to contribute to
```suggestion
from Transifex. This is critical as every user is able to contribute to
```

2020-11-13 14:34 UTC, DeepDiver1975 requested changes

2020-11-13 14:34 UTC, DeepDiver1975 commented on tests/lib/L10N/L10nTest.php
> +		$this->assertEquals('malformed', $lString->__toString());
self:: please  
assertEquals is static

2020-11-13 15:16 UTC, DeepDiver1975 requested changes

2020-11-13 15:16 UTC, DeepDiver1975 commented on .htaccess
> +ErrorDocument 403 /core/templates/403.php
:see_no_evil:

2020-11-13 15:16 UTC, DeepDiver1975 commented on Makefile
> +TEST_PHP_SUITE=tests/Core/Command/Config/App/SetConfigTest.php
:see_no_evil:

2020-11-16 09:18 UTC, DeepDiver1975 commented
squash commits into one and we are ready to go @HieronymusPerro - THX

2020-11-16 10:35 UTC, HieronymusPerro commented
Done, THX for reviewing!

2020-11-16 10:47 UTC, DeepDiver1975 approved these changes

2020-11-17 10:22 UTC, merged