CORS add url only allow http or https protocol
owncloud/core pull request #38101
Opened 2020-11-11 09:35 UTC by HieronymusPerro

## Description
In Settings->Security you can add CORS urls.
Due not checking the protocol it is easy for the user to make mistakes without knowing the reason.
From now, we validate CORS url protocol is http or https based and also trim white spaces. 

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37644

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-11-11 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38101) before we can accept your contribution.<br/><hr/>**jan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38101) it.</sub>

2020-11-16 15:26 UTC, DeepDiver1975 requested changes, later dismissed

2020-11-16 15:26 UTC, DeepDiver1975 commented on settings/Controller/CorsController.php
> +		$encoded_path = \array_map('urlencode', \explode('/', $path));
Why all this encode-fu?

```
$schem = parse_url($url, PHP_URL_SCHEME)
return $scheme === 'http || $scheme === 'https;

2020-11-16 15:26 UTC, DeepDiver1975 commented on settings/js/panels/cors.js
> +            { domain : $('#domain').val().trim()},
should be done server side .... generally speaking ....

2020-11-17 10:42 UTC, phil-davis commented on changelog/unreleased/37664
> +Adding a white-listed domain allowed strange protocols like kkk://google.de, restricted to http/https
```suggestion
Adding a white-listed domain allowed strange protocols like zzz://google.de, restricted to http/https
```

"kkk" is an unfortunate acronym in conjunction with "white"-list. Maybe don't issue a changelog with those 2 things on the same line.

2020-11-18 15:58 UTC, phil-davis reviewed
Looks OK to me. But @DeepDiver1975 please review again.

2020-11-23 08:43 UTC, mmattel commented
@DeepDiver1975 I know that you are very busy, but could you add a statement if you agree to the PR? If ok, we could proceed :smile: Many thanks

2020-11-23 11:45 UTC, jvillafanez commented on settings/Controller/CorsController.php
> +		if ($this->isValidUrl($domain) && $this->isValidProtocol($domain)) {
You can move the check for the protocol inside the `isValidUrl` method, and include a comment here about what we expect. For me, a domain doesn't include the protocol, but it's seems required here.

In addition, note that we might need to parse the whole url. It seems you can add something like `https://example.com:7777/oc/test?myping=abcd#info`, which could be validated as true, but I don't think is a valid CORS value

2020-11-23 12:15 UTC, HieronymusPerro commented on settings/Controller/CorsController.php
> +		if ($this->isValidUrl($domain) && $this->isValidProtocol($domain)) {
Why this should not be a valid CORS value https://example.com:7777/oc/test?myping=abcd#info 
If you look to the RFC port is an important part of CORS and paths and queries should be ignored.

2020-11-23 12:26 UTC, HieronymusPerro commented on settings/Controller/CorsController.php
> +		if ($this->isValidUrl($domain) && $this->isValidProtocol($domain)) {
But yeah I will have a look at this very soon!

2020-11-23 13:12 UTC, HieronymusPerro commented
According to @jvillafanez this has now updated in favor of:
- Only allow http / https protocol
- Don't allow url paths like http://example.com/hello world
- Don't allow url querys like http://example.com?test=true

2020-11-23 14:54 UTC, jvillafanez commented on settings/Controller/CorsController.php
> +		if (\parse_url($url, PHP_URL_SCHEME) !== 'http' && \parse_url($url, PHP_URL_SCHEME) !== 'https') {
not sure how the function is implemented, but I'm confident that calling the `parse_url` function once in order to parse the whole string is more efficient than calling it several times.

In addition, the `filter_var` might be obsolete if we rely on the `parse_url` because it should return false if it can't parse the url.

2020-11-23 15:06 UTC, HieronymusPerro commented on settings/Controller/CorsController.php
> +		if (\parse_url($url, PHP_URL_SCHEME) !== 'http' && \parse_url($url, PHP_URL_SCHEME) !== 'https') {
>In addition, the filter_var might be obsolete if we rely on the parse_url
that's not true.

parse_url(1);

returns the following

array(1) {
  ["path"]=>
  string(1) "1"
}

2020-11-23 15:38 UTC, HieronymusPerro commented on settings/Controller/CorsController.php
> +		if (\parse_url($url, PHP_URL_SCHEME) !== 'http' && \parse_url($url, PHP_URL_SCHEME) !== 'https') {
@jvillafanez 
Please review again. I don't like this approach that much, even if it is more efficient, it lacks of readability.

2020-11-24 08:21 UTC, jvillafanez commented on settings/Controller/CorsController.php
> +		if (\parse_url($url, PHP_URL_SCHEME) !== 'http' && \parse_url($url, PHP_URL_SCHEME) !== 'https') {
what about using type hinting in the function definition to ensure the url is a string? is it good enough to remove the filter_var check?

for the other checks, you could try:
```
// parsed url mustn't contain the following pieces
$mustBeMissing = ['user', 'pass', 'path', 'query', 'fragment'];
foreach ($mustBeMissing as $piece) {
  if (isset($parsedUrl[$piece])) {
    return false;
  }
}
```
you'd still need to check the scheme, but the current code is fine

2020-11-24 09:43 UTC, jvillafanez approved these changes
Just a couple of minor details. Note that you still need to adjust the code style according to drone.
I'm approving since these are minor optional changes (other than the drone's ones) which won't affect the functionality.

2020-11-24 09:43 UTC, jvillafanez commented on settings/Controller/CorsController.php
> +		$notAllowedUrlComponents = ['user', 'pass', 'path', 'query', 'fragment'];
I'd prefer to move this close to where it's going to be used. It's up to you if you want to make this change or not.

2020-11-24 09:43 UTC, jvillafanez commented on settings/Controller/CorsController.php
> +			return  false;
double space between "return" and "false"

2020-11-24 10:35 UTC, mmattel commented
@HieronymusPerro 
> ...this has now updated in favor of:
> - Only allow http / https protocol
> - Don't allow url paths like http://example.com/hello_world
> - Don't allow url querys like http://example.com?test=true

Please file a doc issue, because this needs a doc change in: https://github.com/owncloud/docs/blob/master/modules/user_manual/pages/personal_settings/security.adoc

2020-11-24 16:21 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/27686/2/7
code style failed.

2020-11-25 09:25 UTC, merged

2020-11-25 10:20 UTC, mmattel commented
@HieronymusPerro ping regarding https://github.com/owncloud/core/pull/38101#issuecomment-732810945 as this PR is now merged, thanks.

2020-11-25 10:27 UTC, HieronymusPerro commented
> @HieronymusPerro ping regarding [#38101 (comment)](https://github.com/owncloud/core/pull/38101#issuecomment-732810945) as this PR is now merged, thanks.

Can you explain exactly what action is required from my side or link an explanation?
Thx

2020-11-25 10:44 UTC, mmattel commented
This is easy :smile:
open an issue in docs and describe that there is a change necessary for the CORS documentation (user manual) and add the link to the cors doc I provided above so it can be easier identified where to write. Add a reference to this core PR so we see in docs where it belongs to and here that an issue has been created. When the docs PR has been merged, the issue will be closed and we can see from all sides nothing is open. Please also add in the issue that this will be part of the 10.6 release.

2020-11-25 10:51 UTC, HieronymusPerro commented
Thank you, done =)
> Please also add in the issue that this will be part of the 10.6 release.
Can you explain where? There is no milestone/project or label for 10.6

2020-11-25 10:51 UTC, HieronymusPerro commented
> This is easy 
> open an issue in docs and describe that there is a change necessary for the CORS documentation (user manual) and add the link to the cors doc I provided above so it can be easier identified where to write. Add a reference to this core PR so we see in docs where it belongs to and here that an issue has been created. When the docs PR has been merged, the issue will be closed and we can see from all sides nothing is open. Please also add in the issue that this will be part of the 10.6 release.

Thank you, done =)
> Please also add in the issue that this will be part of the 10.6 release.

Can you explain where? There is no milestone/project or label for 10.6