enable group tests on ocis
owncloud/core pull request #38110
Opened 2020-11-13 06:31 UTC by dpakach

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-11-13 13:52 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
> +    Then the groups returned by the API should be
This will have the problem that the test scenario in core will need to be adjusted when the "default" groups in OCIS  are changed. But we can think about that in a later PR - maybe this scenario could be moved into the local OCIS API tests, rather than being in core.

2020-11-13 13:52 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
> +#  Scenario: admin gets all the groups, including groups with mixed case
Did you want this commented-out scenario to be left here?

2020-11-13 13:52 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @notToImplementOnOCIS @skipOnOcV10
why does this have both tags `@notToImplementOnOCIS @skipOnOcV10` ?
It won't run anywhere.

2020-11-13 13:52 UTC, phil-davis commented on tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
> +  @notToImplementOnOCIS @skipOnOcV10
This does not run anywhere? Why is it tagged like this?

2020-11-13 13:52 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$this->deleteTheGroupUsingTheProvisioningApi($group);
why is it good to do `deleteTheGroupUsingTheProvisioningApi` again here?

2020-11-18 06:04 UTC, individual-it requested changes

2020-11-18 06:04 UTC, individual-it commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @smokeTest @notToImplementOnOCIS
why will that not be implemented in ocis?

2020-11-18 06:04 UTC, individual-it commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @notToImplementOnOCIS
why shouldn't that function be implemented in ocis?

2020-11-18 06:04 UTC, individual-it commented on tests/acceptance/features/apiProvisioningGroups-v2/getGroup.feature
> +    Given these users have been created with default attributes and skeleton files:
do we need the skeleton files in these tests? could get changed for the whole file (an other PR)

2020-11-18 06:47 UTC, dpakach commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @smokeTest @notToImplementOnOCIS
This test is added in the scenario added at the end of this file.

2020-11-18 06:48 UTC, dpakach commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @notToImplementOnOCIS
scenario for ocis added at the end of this file

2020-11-18 06:49 UTC, dpakach commented on tests/acceptance/features/apiProvisioningGroups-v2/getGroup.feature
> +    Given these users have been created with default attributes and skeleton files:
Yes, we definitely can. (on other PR)

2020-11-18 09:14 UTC, individual-it commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
> +  @notToImplementOnOCIS
ok, I understand. OCIS always returns `users` as group, even if the user hasn't been added to any group

2020-11-18 09:14 UTC, individual-it approved these changes

2020-11-18 09:21 UTC, phil-davis approved these changes

2020-11-18 10:01 UTC, merged