[tests-only] tests for TUS upload to share
owncloud/core pull request #38150
Opened 2020-11-27 11:24 UTC by swoichha

## Description
test for TUS uploads to a received share folder

## Related Issue
- part of owncloud/product#153

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-11-27 12:03 UTC, individual-it requested changes
some general comments that apply to all scenarios

2020-11-27 12:03 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +    Then the HTTP status code should be "200"
I don't think this checks the response of the upload, the tus library does not return the response code

2020-11-27 12:03 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +    And as "Alice" file "/FOLDER/textfile.txt" should exist
maybe the next line will be enough, I actually don't know why we keep on checking the existence of the item when we also check the content. To make sure PROPFIND also works correctly? @phil-davis ?

2020-11-27 12:03 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +    And the content of file "/FOLDER/textfile.txt" for user "Alice" should be "uploaded content"
maybe check the content or file existence as Brian

2020-11-27 12:03 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +  Scenario Outline: Uploading file in a group to received read/write share folder
```suggestion
  Scenario Outline: Uploading a file into a group share as share receiver
```

2020-11-30 04:20 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +    And the content of file "/FOLDER/textfile.txt" for user "Alice" should be "uploaded content"
The content is checked for Alice because the file was uploaded by Brian so we want to make sure that the newly uploaded file also exist for user Alice.

2020-11-30 05:20 UTC, individual-it approved these changes
please bump the commit id of core in ocis & cs3org/reva

2020-11-30 08:23 UTC, merged