[tests-only] added tus tests for creation with upload
owncloud/core pull request #38194
Opened 2020-12-04 11:48 UTC by swoichha

## Description
test for TUS to upload a file using creation with upload

## Related Issue

- Fixes <issue_link>

## Motivation and Context
- part of owncloud/product#153

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-12-16 02:51 UTC, individual-it requested changes

2020-12-16 02:51 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
> +      | Location      | /http[s]?:\/\/.*:\d+\/data\/.*/ |
I think it also should give us `Upload-Offset` header, lets check that too

2020-12-17 10:50 UTC, individual-it requested changes

2020-12-17 10:50 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
> +      | Upload-Offset | /\d+/                           |
you can actually check for the exact offset it should give, it should be 16 if I'm not wrong

2020-12-17 10:50 UTC, individual-it commented on tests/acceptance/features/bootstrap/TUSContext.php
> +		$client->setMetadata($uploadMetadata);
let's dry this with `userUploadsUsingTusAFileTo()`

2020-12-17 10:50 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
> +    When user "Alice" uploads file "textFile.txt" with content "12345" and "-1" bytes using the TUS protocol on the WebDAV API
1. need a better way to distinguish between this step and ` @When user :user uploads file :source to :destination using the TUS protocol on the WebDAV API`
2. `-1` is not very much "natural language"

maybe we can change the step to something like:
`When user "Alice" creates file "textFile.txt" and uploads content "12345" in the same request using the TUS protocol on the WebDAV API` and assume its always meant to be the complete file and if we want to upload only chunks we mention `chunks` in a different step
or
we change the wording of ` @When user :user uploads file :source to :destination using the TUS protocol on the WebDAV API`
or
???

2020-12-18 07:37 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
> +      | Upload-Offset | /\d+/                           |
Since this step uses regex expression to check the header's value I think it would be better this way.

2020-12-18 08:28 UTC, individual-it requested changes

2020-12-18 08:28 UTC, individual-it commented on tests/acceptance/features/bootstrap/TUSContext.php
> +		if ($bytes != null) {
```suggestion
		if ($bytes !== null) {
```

2020-12-18 08:28 UTC, individual-it commented on tests/acceptance/features/bootstrap/TUSContext.php
> +		array $creationWithUploadHeader = []
not needed as you directly overwrite those variables

2020-12-18 08:32 UTC, individual-it requested changes

2020-12-18 08:32 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
> +    Then the HTTP status code should be "200"
that When step does not report back any HTTP status

2020-12-18 09:19 UTC, individual-it approved these changes

2020-12-21 05:33 UTC, merged