[Tests-Only]TUS upload to non existing folder
owncloud/core pull request #38193
Opened 2020-12-04 10:16 UTC by jasson99

## Description
Tests for TUS upload to a non existing folder

## Related Issue
- Part of https://github.com/owncloud/product/issues/153

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-12-04 13:13 UTC, phil-davis commented
Needs coding standard fixed so that the rest of CI will run https://drone.owncloud.com/owncloud/core/27843/2/7

2020-12-07 03:04 UTC, individual-it requested changes

2020-12-07 03:04 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
> +  @skipOnOcV10.3 @skipOnOcV10.4 @skipOnOcV10.5
no need to add this line, the skip tag on top of the file will do

2020-12-07 03:04 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
> +  So that I can store and share files between multiple client systems
please adjust for uploads to not existing folders

2020-12-07 03:04 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
> +    When user "Alice" uploads file with content "uploaded content" to "/Shares/FOLDER/textfile.txt" using the TUS protocol on the WebDAV API
this is a good special case, please try also uploads to not-existing folders outside of `/Shares` 
and to not-existing folders within correctly received shares

2020-12-08 04:08 UTC, individual-it approved these changes

2020-12-08 04:29 UTC, phil-davis commented
@jasson99 code-style failed CI

2020-12-14 10:39 UTC, individual-it approved these changes

2020-12-15 08:23 UTC, phil-davis approved these changes

2020-12-15 08:24 UTC, merged