[Tests-Only] added api test for share shared to deleted user
owncloud/core pull request #38205
Opened 2020-12-11 10:26 UTC by SwikritiT

Co-authored-by: Saw-jan <saw.jan.grg3e@gmail.com>

## Description
Added api test for share shared to deleted user

## Related Issue
- https://github.com/owncloud/ocis/issues/903

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2020-12-11 10:43 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +      Then user "Brian" should not exist
This check is not really necessary

2020-12-11 10:43 UTC, dpakach commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +      When the administrator deletes user "Brian" using the provisioning API
Put this on given, as this is the precondition for this scenario

2020-12-11 10:44 UTC, jasson99 requested changes

2020-12-11 10:44 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +      And user "Alice" shares file "textfile0.txt" with user "Brian" using the sharing API
is this a when step or a given step?

2020-12-11 10:47 UTC, individual-it requested changes

2020-12-11 10:47 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +  Scenario: shares shared to deleted user should not be shown
```suggestion
  Scenario: shares to a deleted user should not be listed as shares for the sharer
```

2020-12-15 08:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38205) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38205) it.</sub>

2020-12-15 10:42 UTC, jasson99 requested changes

2020-12-15 10:42 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    When user "Alice" gets all the shares shared with him that are received as file "textfile0.txt" using the provisioning API
shared with him?? is "textfile0.txt" is not shared with alice in the scenario? Alice has shared the file with Brian. After brian is deleted, i think you need to check if the shares shared by alice with user brian are listed.  Alice never received the share in this scenario.

2020-12-15 10:45 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    When user "Alice" gets all the shares shared with him that are received as file "textfile0.txt" using the provisioning API
You can check if Brian is included in the response without deleting the user Brian in this case and see if it passes

2020-12-15 12:05 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given /^the administrator has deleted user "([^"]*)" using the provisioning API$/
Inside the given step it is better to check if the user is actually deleted or not, otherwise if the `when` step fails, the error might be out of scope. (debugging will be easier).

2020-12-16 06:22 UTC, saw-jan requested changes

2020-12-16 06:22 UTC, saw-jan commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    When user "Alice" sends HTTP method "GET" to OCS API endpoint "/apps/files_sharing/api/v1/shares"
wouldn't it be better to to get the share info of only the shared file in this scenario. 
As `/apps/files_sharing/api/v1/shares` endpoint gets shared info of all the shared files, better to use `apps/files_sharing/api/v1/shares?path=textfile0.txt`

And also `/apps/files_sharing/api/v1/shares` doesn't illustrate the actual scenario in the WebUI, it should be `apps/files_sharing/api/v1/shares?path=textfile0.txt&reshares=true`

Or this step can be utilized:
`user "Alice" gets all the shares with reshares from the file "textfile0.txt" using the sharing API`

2020-12-16 07:18 UTC, saw-jan commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    When user "Alice" sends HTTP method "GET" to OCS API endpoint "/apps/files_sharing/api/v1/shares"
`apps/files_sharing/api/v1/shares?path=textfile0.txt` this should be enough

2020-12-16 09:24 UTC, individual-it requested changes

2020-12-16 09:24 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    When user "Alice" sends HTTP method "GET" to OCS API endpoint "/apps/files_sharing/api/v1/shares"
I think `reshare=true` is optional  also we can be very broad and  just try
```
When user "Alice" sends HTTP method "GET" to OCS API endpoint "/apps/files_sharing/api/v1/shares"
Then the last response should be empty

2020-12-16 09:24 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    And user "Brian" should not exist
no need to check here, but create a new function as suggested by @kiranparajuli589 for the given step and add a check there

2020-12-17 07:00 UTC, phil-davis commented
@SwikritiT https://drone.owncloud.com/owncloud/core/28005/2/7
`make test-php-style` is failing

2020-12-17 09:48 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
> +    And user "Carol" should be included in the response
You can also use `But` instead of `And` for one of these steps. I think that makes it more clear. for example:
```suggestion
    And user "Carol" should be included in the response
    But user "Brian" should not be included in the response
```
We can also discuss about it.

2020-12-22 06:24 UTC, phil-davis commented
There were some silly yarn-install errors in drone. I restarted CI.

2020-12-22 09:29 UTC, individual-it approved these changes

2020-12-22 09:33 UTC, jasson99 approved these changes

2020-12-22 09:36 UTC, merged