User should be able to see their own subadmin groups
owncloud/core pull request #38281
Opened 2021-01-11 00:53 UTC by rpocklin

## Description
See related issue below.

## Related Issue
- Fixes https://github.com/owncloud/owncloud-sdk/issues/658

## Motivation and Context
When logging in, we want to check what groups a user is a subadmin of, so we know what UI to present them with if they can manage specific groups.

## How Has This Been Tested?
Works as expected, normal users can call the owncloud-sdk without an error response (even if they have are not a subadmin of the group).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-01-11 03:29 UTC, phil-davis commented
CI is failing https://drone.owncloud.com/owncloud/core/28176 because this PR is branched from an old version of master that has out-of-date drone CI settings.

@rpocklin please pull a current master and rebase to that.

While doing that, you can add a link to this PR into the changelog file.

2021-01-11 04:37 UTC, rpocklin commented
> CI is failing https://drone.owncloud.com/owncloud/core/28176 because this PR is branched from an old version of master that has out-of-date drone CI settings.
> 
> @rpocklin please pull a current master and rebase to that.
> 
> While doing that, you can add a link to this PR into the changelog file.

Thanks for the feedback, done and done :)

2021-01-11 06:29 UTC, mmattel commented
@micbar @phil-davis no reviewer was added before. Pls feel free to add one 😃

Related to https://github.com/owncloud/core/pull/38280

2021-01-11 08:08 UTC, phil-davis commented
drone CI got a silly error: https://drone.owncloud.com/owncloud/core/28180/156/12
```
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT 52.217.17.156:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

I have restarted CI. I expect that it will pass.

2021-01-11 08:57 UTC, mmattel commented
https://drone.owncloud.com/owncloud/core/28182 --> ERR_TUNNEL_CONNECTION_FAILED

2021-01-11 09:37 UTC, phil-davis commented
> https://drone.owncloud.com/owncloud/core/28182 --> ERR_TUNNEL_CONNECTION_FAILED

It looks green to me. Maybe the drone server had a "hiccup" rendering the results for a second.

2021-01-12 01:03 UTC, rpocklin commented
After further testing I have updated this PR to be more complete, so that it correctly handles admin, subadmin and non-admin users calling this API in the correct manner (for themselves, or for others).  I have tested manually but would recommend it have unit or acceptance tests also but I am unable to do this currently due to lack of experience in PHP and time constraints.

2021-01-12 03:01 UTC, phil-davis reviewed
There are code-style things to fix https://drone.owncloud.com/owncloud/core/28185/2/7
It would be good to sort those out, then the rest of CI will run and we will see how the various existing API acceptance tests go.

2021-01-12 05:18 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/28187/2/7 code style is still failing. It needs to get past that so the real tests will run.

2021-01-12 08:41 UTC, mmattel commented
@rpocklin to fix the code styling tests, run `./make test-php-style-fix` from the root of the repo

2021-01-12 23:09 UTC, rpocklin commented
Thanks for the instructions guys, will fix this soon.

2021-01-13 02:27 UTC, phil-davis commented
Some different status codes get returned in unit tests: https://drone.owncloud.com/owncloud/core/28208/9/8
```
There were 4 failures:

1) OCA\Provisioning_API\Tests\UsersTest::testAddToGroupSuccessfulAsSubadmin
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OC\OCS\Result Object (
     'data' => Array ()
     'message' => null
-    'statusCode' => 104
+    'statusCode' => 100
     'items' => null
     'perPage' => null
     'headers' => Array ()
 )

/drone/src/apps/provisioning_api/tests/UsersTest.php:1949

2) OCA\Provisioning_API\Tests\UsersTest::testGetUserSubAdminGroupsNotExistingTargetUser
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OC\OCS\Result Object (
     'data' => Array ()
-    'message' => 'User does not exist'
-    'statusCode' => 101
+    'message' => null
+    'statusCode' => 997
     'items' => null
     'perPage' => null
     'headers' => Array ()
 )

/drone/src/apps/provisioning_api/tests/UsersTest.php:2517

3) OCA\Provisioning_API\Tests\UsersTest::testGetUserSubAdminGroupsWithGroups
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OC\OCS\Result Object (
     'data' => Array (
-        0 => 'TargetGroup'
     )
     'message' => null
-    'statusCode' => 100
+    'statusCode' => 997
     'items' => null
     'perPage' => null
     'headers' => Array ()
 )

/drone/src/apps/provisioning_api/tests/UsersTest.php:2545

4) OCA\Provisioning_API\Tests\UsersTest::testGetUserSubAdminGroupsWithoutGroups
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OC\OCS\Result Object (
     'data' => Array ()
-    'message' => 'Unknown error occurred'
-    'statusCode' => 102
+    'message' => null
+    'statusCode' => 997
     'items' => null
     'perPage' => null
     'headers' => Array ()
 )

/drone/src/apps/provisioning_api/tests/UsersTest.php:2568
```

That needs to be sorted out. It looks to me like more `997` is happening now than should be. I am expecting that only a few test cases will need to change, and those changes should be that a subadmin can "see" their group better than before.

2021-01-13 02:39 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/28208/59/13 API acceptance test fails:
```
  Scenario: a subadmin cannot add users to groups the subadmin is responsible for                                 # /drone/src/tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature:133
    Given these users have been created with default attributes and skeleton files:                               # FeatureContext::theseUsersHaveBeenCreated()
      | username       |
      | brand-new-user |
      | subadmin       |
    And group "brand-new-group" has been created                                                                  # FeatureContext::groupHasBeenCreated()
    And user "subadmin" has been made a subadmin of group "brand-new-group"                                       # FeatureContext::userHasBeenMadeSubadminOfGroup()
    When user "subadmin" tries to add user "brand-new-user" to group "brand-new-group" using the provisioning API # FeatureContext::userTriesToAddUserToGroupUsingTheProvisioningApi()
    Then the OCS status code should be "104"                                                                      # OCSContext::theOCSStatusCodeShouldBe()
      OCS status code is not the expected value 104 got 100
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'104'
      +'100'
    And the HTTP status code should be "200"                                                                      # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And user "brand-new-user" should not belong to group "brand-new-group"                                        # FeatureContext::userShouldNotBelongToGroup()
```

The sub-admin can now add a member to the group. That ability was removed in PR #31337 back in 2018, because it allows a sub-admin to add any user to "their" group and then change the user's password (thus being able to access the user's data) or delete the user (the sub-admin could delete every other user on the system, leaving just 1 real admin and themselves!)
Also see my comment https://github.com/owncloud/core/issues/38279#issuecomment-757685626

This PR currently does more than its current title: "User should be able to see their own subadmin groups"

IMO we should just fix the "see their own subadmin groups" thing, get that done, and we can have a separate discussion about changing what a sub-admin can and cannot do.

2021-01-15 06:01 UTC, rpocklin commented
> https://drone.owncloud.com/owncloud/core/28208/59/13 API acceptance test fails:
> 
> ```
>   Scenario: a subadmin cannot add users to groups the subadmin is responsible for                                 # /drone/src/tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature:133
>     Given these users have been created with default attributes and skeleton files:                               # FeatureContext::theseUsersHaveBeenCreated()
>       | username       |
>       | brand-new-user |
>       | subadmin       |
>     And group "brand-new-group" has been created                                                                  # FeatureContext::groupHasBeenCreated()
>     And user "subadmin" has been made a subadmin of group "brand-new-group"                                       # FeatureContext::userHasBeenMadeSubadminOfGroup()
>     When user "subadmin" tries to add user "brand-new-user" to group "brand-new-group" using the provisioning API # FeatureContext::userTriesToAddUserToGroupUsingTheProvisioningApi()
>     Then the OCS status code should be "104"                                                                      # OCSContext::theOCSStatusCodeShouldBe()
>       OCS status code is not the expected value 104 got 100
>       Failed asserting that two strings are equal.
>       --- Expected
>       +++ Actual
>       @@ @@
>       -'104'
>       +'100'
>     And the HTTP status code should be "200"                                                                      # FeatureContext::thenTheHTTPStatusCodeShouldBe()
>     And user "brand-new-user" should not belong to group "brand-new-group"                                        # FeatureContext::userShouldNotBelongToGroup()
> ```
> 
> The sub-admin can now add a member to the group. That ability was removed in PR #31337 back in 2018, because it allows a sub-admin to add any user to "their" group and then change the user's password (thus being able to access the user's data) or delete the user (the sub-admin could delete every other user on the system, leaving just 1 real admin and themselves!)
> Also see my comment [#38279 (comment)](https://github.com/owncloud/core/issues/38279#issuecomment-757685626)
> 
> This PR currently does more than its current title: "User should be able to see their own subadmin groups"
> 
> IMO we should just fix the "see their own subadmin groups" thing, get that done, and we can have a separate discussion about changing what a sub-admin can and cannot do.

Apologies, the change in `addToGroup` was inadvertently added from another current PR I am working on, I will remove it so we can focus on `getUserSubAdminGroups` as that is the intent.

2021-02-15 05:36 UTC, rpocklin commented
@phil-davis I am attempting to investigate the failures (which are less now) but phpunit tests keep freezing at 48% on my Ubuntu, are you able to offer suggestions?  I am not familiar with PHP or their toolkits, and i'm using mariadb locally.

```robertp@APL-RP-LT1:~/p/core$ make test-php-unit --debug
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'test-php-unit' does not exist.
Must remake target 'test-php-unit'.
PHPUNIT="/home/robertp/p/core/lib/composer/phpunit/phpunit/phpunit" build/autotest.sh mysql
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for mysql testing on local storage ...
Updated 0 paths from the index
Installing ....
ownCloud was successfully installed
Testing with mysql ...
/home/robertp/p/core/lib/composer/phpunit/phpunit/phpunit --configuration phpunit-autotest.xml --coverage-clover autotest-clover-mysql.xml --coverage-html coverage-html-mysql --log-junit autotest-results-mysql.xml
PHPUnit 8.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: /home/robertp/p/core/tests/phpunit-autotest.xml
Error:         No code coverage driver is available

...........................................................    59 / 10415 (  0%)
..........................S................................   118 / 10415 (  1%)
...........................................................   177 / 10415 (  1%)
...........................................................   236 / 10415 (  2%)
...........................................................   295 / 10415 (  2%)
...........................................................   354 / 10415 (  3%)
...........................................................   413 / 10415 (  3%)
...........................................................   472 / 10415 (  4%)
...........................................................   531 / 10415 (  5%)
...........................................................   590 / 10415 (  5%)
...........................................................   649 / 10415 (  6%)
...........................................................   708 / 10415 (  6%)
...........................................................   767 / 10415 (  7%)
...........................................................   826 / 10415 (  7%)
...........................................................   885 / 10415 (  8%)
...........................................................   944 / 10415 (  9%)
...........................................................  1003 / 10415 (  9%)
...........................................................  1062 / 10415 ( 10%)
...........................................................  1121 / 10415 ( 10%)
...........................................................  1180 / 10415 ( 11%)
...........................................................  1239 / 10415 ( 11%)
...........................................SS..............  1298 / 10415 ( 12%)
...........................................................  1357 / 10415 ( 13%)
...........................................................  1416 / 10415 ( 13%)
...........................................................  1475 / 10415 ( 14%)
...........................................................  1534 / 10415 ( 14%)
...........................................................  1593 / 10415 ( 15%)
...........................................................  1652 / 10415 ( 15%)
...........................................................  1711 / 10415 ( 16%)
...........................................................  1770 / 10415 ( 16%)
...........................................................  1829 / 10415 ( 17%)
...........................................................  1888 / 10415 ( 18%)
...........................................................  1947 / 10415 ( 18%)
...........................................................  2006 / 10415 ( 19%)
...........................................................  2065 / 10415 ( 19%)
...........................................................  2124 / 10415 ( 20%)
...........................................................  2183 / 10415 ( 20%)
...........................................................  2242 / 10415 ( 21%)
...........................................................  2301 / 10415 ( 22%)
...........................................................  2360 / 10415 ( 22%)
...........................................................  2419 / 10415 ( 23%)
...........................................................  2478 / 10415 ( 23%)
...........................................................  2537 / 10415 ( 24%)
...........................................................  2596 / 10415 ( 24%)
...........................................................  2655 / 10415 ( 25%)
...........................................................  2714 / 10415 ( 26%)
...........................................................  2773 / 10415 ( 26%)
...........................................................  2832 / 10415 ( 27%)
...........................................................  2891 / 10415 ( 27%)
...........................................................  2950 / 10415 ( 28%)
..............................................S............  3009 / 10415 ( 28%)
...........................................................  3068 / 10415 ( 29%)
...........................................................  3127 / 10415 ( 30%)
..................S........................................  3186 / 10415 ( 30%)
...................................................S.......  3245 / 10415 ( 31%)
...........................................................  3304 / 10415 ( 31%)
..................................S........................  3363 / 10415 ( 32%)
...........................................................  3422 / 10415 ( 32%)
................S..........................................  3481 / 10415 ( 33%)
..............................................S............  3540 / 10415 ( 33%)
...........................................................  3599 / 10415 ( 34%)
...........................................................  3658 / 10415 ( 35%)
...........................................................  3717 / 10415 ( 35%)
...........................................................  3776 / 10415 ( 36%)
...........................................................  3835 / 10415 ( 36%)
...........................................................  3894 / 10415 ( 37%)
...........................................................  3953 / 10415 ( 37%)
...........................................................  4012 / 10415 ( 38%)
...........................................................  4071 / 10415 ( 39%)
...........................................................  4130 / 10415 ( 39%)
...........................................................  4189 / 10415 ( 40%)
...........................................................  4248 / 10415 ( 40%)
.....................................................FF....  4307 / 10415 ( 41%)
...........................................................  4366 / 10415 ( 41%)
...........................................................  4425 / 10415 ( 42%)
...........................................................  4484 / 10415 ( 43%)
...........................................................  4543 / 10415 ( 43%)
...........................................................  4602 / 10415 ( 44%)
...........................................................  4661 / 10415 ( 44%)
................................... [...]

2021-02-15 05:52 UTC, phil-davis commented
I know that some of the unit tests somehow use a lot of memory. You can run just the test(s) that you know are a probledm, get those passing, and let CI run the full suite. Something like:
```
make test-php-unit NOCOVERAGE=true TEST_PHP_SUITE=apps/provisioning_api/tests/UsersTest.php
```

2021-02-17 10:37 UTC, rpocklin commented
> I know that some of the unit tests somehow use a lot of memory. You can run just the test(s) that you know are a probledm, get those passing, and let CI run the full suite. Something like:
> 
> ```
> make test-php-unit NOCOVERAGE=true TEST_PHP_SUITE=apps/provisioning_api/tests/UsersTest.php
> ```

Thanks that helped me move forward cheers.

2021-02-23 06:13 UTC, rpocklin commented
I keep getting the following error running the **test-acceptance-api** tests locally, any ideas?

```
Nothing to install or update
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
61 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
./tests/acceptance/run.sh --type api
Script path: /home/robertp/p/core/tests/acceptance
Using php inbuilt server for running scenario ...
8080
6151
8180
6152
[Tue Feb 23 17:12:15 2021] PHP 7.4.3 Development Server (http://localhost:8180) started
[Tue Feb 23 17:12:15 2021] PHP 7.4.3 Development Server (http://localhost:8080) started
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38312 Accepted
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38312 [302]: POST /ocs/v2.php/apps/testing/api/v1/occ
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38312 Closing
-:2: parser error : Start tag expected, '<' not found

^
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38314 Accepted
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38314 [302]: POST /ocs/v2.php/apps/testing/api/v1/occ
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38314 Closing
-:2: parser error : Start tag expected, '<' not found

^
Could not set mail_domain on http://localhost:8080/ocs/v2.php/apps/testing/api/v1/occ. Result:
''
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38316 Accepted
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38316 [302]: POST /ocs/v2.php/apps/testing/api/v1/occ
[Tue Feb 23 17:12:20 2021] 127.0.0.1:38316 Closing
-:2: parser error : Start tag expected, '<' not found

^
runsh: Exit code of main run:
make: *** [Makefile:207: test-acceptance-api] Error 1```

2021-02-25 05:12 UTC, phil-davis commented
You need to have a local ownCloud install that will already work properly on localhost:8080 (for example)
I find it easiest to already have my system-under-test running before starting the tests. Then I can login to it manually on the web UI and know that it is working. 

Sometimes I get this problem because I have enable and app and it wants `php occ upgrade` to be done.

To run the tests, I then do:
```
export TEST_SERVER_URL=http://localhost:8080
```

And then run a particular test(s):
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiCapabilities/capabilities.feature
```

If `TEST_SERVER_URL` then the test runner script does not start up its own PHP dev server.

2021-02-26 04:46 UTC, rpocklin commented
Thanks @phil-davis I believe it all passes now =)  Ssomeone added in the acceptance tests relating to this *@issue-owncloud-sdk-658* for me, which was helpful and thoughtful.

2021-02-26 05:07 UTC, phil-davis commented
The code looked like it will now allow an ordinary user who is not a subadmin of any groups to query about what groups they are sub-admin of, so I added an acceptance test scenario for that. They get "success" OCS and HTTP status with an empty list - which seems correct.

2021-02-26 05:08 UTC, phil-davis approved these changes
LGTM - also needs review from a developer.

2021-02-26 08:07 UTC, VicDeo approved these changes

2021-02-26 08:14 UTC, JanAckermann commented on apps/provisioning_api/lib/Users.php
> +		if ($targetUser === null) {
Needs to investigated, I am Not quite sure, but isn't it against our security policy, to Show If a User exists, to a

2021-02-26 08:53 UTC, VicDeo commented on apps/provisioning_api/lib/Users.php
> +		if ($targetUser === null) {
This requires a logged in user... I think  it's better to use a share dialog if you need some usernames

2021-02-26 08:53 UTC, phil-davis commented on apps/provisioning_api/lib/Users.php
> +		if ($targetUser === null) {
@JanAckermann "to a..." what?

2021-02-26 10:20 UTC, JanAckermann approved these changes

2021-02-26 10:24 UTC, JanAckermann requested changes

2021-02-26 10:24 UTC, JanAckermann commented on apps/provisioning_api/lib/Users.php
>  			return new Result(null, 101, 'User does not exist');
```suggestion
			return new Result(null, API::RESPOND_NOT_FOUND, 'The requested user could not be found');
```

For consistency purposes

2021-02-28 22:29 UTC, rpocklin commented
> The code looked like it will now allow an ordinary user who is not a subadmin of any groups to query about what groups they are sub-admin of, so I added an acceptance test scenario for that. They get "success" OCS and HTTP status with an empty list - which seems correct.

Yep that's right, thanks for adding that.

2021-02-28 23:01 UTC, phil-davis commented
@JanAckermann IMO this is ready. Please review again.

2021-03-01 00:58 UTC, JanAckermann commented
Unit Tests are failing

2021-03-02 02:41 UTC, rpocklin commented
Updated the tests, everything passes now.  Incorporating the change @JanAckermann suggested meant I needed to update the `tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature` file to change the OCS and HTTP response code from `400` to `404.

2021-03-02 07:04 UTC, JanAckermann approved these changes

2021-03-02 11:23 UTC, phil-davis approved these changes

2021-03-02 11:30 UTC, merged