Fix subadmin group validation for addToGroup function
owncloud/core pull request #38280
Opened 2021-01-10 22:51 UTC by rpocklin

## Description
This change aligns the provisioning API (and by extension, the **owncloud-sdk**) to allow subadministrators of groups (not just admins) to add users to groups they are a subadministrator of.  This is already permitted via the OC10 UI (which uses the PHP API directly).  The method `removeFromGroup` in this same file already had this check, but it seems the `addToGroup` method was changed and became inconsistent.  This PR makes it consistent across all 3 approaches.

I have re-opened the issue again here:
- Fixes https://github.com/owncloud/core/issues/38279

## Motivation and Context
As detailed above.

## How Has This Been Tested?
Locally it has been tested and works as expected.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-01-10 22:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38280) it.</sub>

2021-01-11 04:38 UTC, rpocklin commented
Rebased to current master.

2021-01-11 06:25 UTC, mmattel commented
@micbar @phil-davis no reviewer was added before. Pls feel free to add one 😃

2021-01-11 08:15 UTC, mrow4a requested changes

2021-01-11 08:15 UTC, mrow4a commented on apps/provisioning_api/lib/Users.php
> -		if (!$this->groupManager->isAdmin($user->getUID())) {
I think isAdmin is still needed, but put it below canUserManageGroup please.

2021-01-11 21:50 UTC, rpocklin commented on apps/provisioning_api/lib/Users.php
> -		if (!$this->groupManager->isAdmin($user->getUID())) {
@mrow4a I think that check is encapsulated inside the `canUserManageGroup` method: https://github.com/owncloud/core/blob/089357601f8634710324e84eeea0e1a750682c68/apps/provisioning_api/lib/Users.php#L453-L464

2021-01-16 09:46 UTC, mrow4a requested changes
currently does not satisfy requirements from security standpoint -> https://github.com/owncloud/core/issues/38279#issuecomment-760714329

2021-04-07 01:31 UTC, rpocklin commented
Closing in favour of toggleGroups approach, see https://github.com/owncloud/core/issues/38279 - will raise an alternate PR for this approach in the future.

2021-04-07 01:31 UTC, closed without merging