[Tests-Only] Add test to check response of webdav url with invalid fi…
owncloud/core pull request #38318
Opened 2021-01-20 07:36 UTC by HariBhandari07

…leId

## Description

This PR adds a test to check the response when webdav URLs are requested with an invalid file id.
## Related Issue

- https://github.com/owncloud/ocis/issues/771

## Motivation and Context

## How Has This Been Tested?

- CI
- Manual

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-01-20 10:43 UTC, individual-it commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +     | SmFua2FyaVRlY2hIYXJpQXNoaXNoRGlwYWtBcnR1cj1QaGlsS2lyYW5UYWxhbmtKYXNtaW5lU3dvaWNoaGE=                |
would be nice to have an other column that shows to what value the base64 decodes to
```
     | file-id                                                                                             | decoded-value | comment |
     | MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OGNjZDI3NTEtOTBhNC00MGYyLWI5ZjMtNjFlZGY4NDQyMWY0 | 1284d238-aa92-42ce-bdc4-0b00000091578ccd2751-90a4-40f2-b9f3-61edf84421f4 | no = sign

2021-01-20 10:47 UTC, individual-it requested changes

2021-01-20 10:47 UTC, individual-it commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +     | MTI4NGQyMzgtYWEMi00MmNlLWJkxzQtMGIwMDAwMsA5MTU2OjhjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA== |
this does not look like that does decode to something useful at all, I good tests

2021-01-21 08:26 UTC, individual-it approved these changes

2021-01-21 10:51 UTC, dpakach approved these changes

2021-01-21 13:46 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/28314/62/13 has hung for 8 hours in drone CI. I will cancel and restart it.

2021-01-22 04:37 UTC, merged