Fixed regex pattern used in download content matching
owncloud/core pull request #38320
Opened 2021-01-20 14:59 UTC by Talank

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-01-21 06:32 UTC, phil-davis commented
See my comment https://github.com/owncloud/core/issues/38300#issuecomment-764394701

IMO it will be easier and clearer code if we remove the 3 lines of special `preg_replace` stuff from `downloadedContentShouldBe` and make a separate step that does a not-exact "special" match of the content. Maybe the "special" code is only needed for the new step "the downloaded content for multipart byterange should be" `theDownloadedContentForMultipartByterangeShouldBe` and so the special `preg_replace` code can be put in there.

2021-01-22 08:04 UTC, saw-jan commented
@Talank also if it is to remove extra space before and after the text content,  `trim()` will do the job well.

2021-01-25 10:46 UTC, Talank commented
> @Talank also if it is to remove extra space before and after the text content, `trim()` will do the job well.

it's more about preserving the spaces between words, The trimming is done perfectly by the special `preg_replace` stuff

2021-01-25 14:27 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +			$actualContent = (string) $this->response->setBody();
```suggestion
			$actualContent = (string) $this->response->getBody();
```

This "looks wrong"

2021-01-25 14:27 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +				"The downloaded content was expected to be '$content', but actually is '$actualContent'. HTTP status was $actualStatus"
```suggestion
				"The downloaded content was expected to be '$content', but actually is '$actualContent'. HTTP status was $actualStatusCode"
```

2021-01-25 14:27 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDav.php
> +			$this->downloadedContentShouldBe($content);
Why do we call this? I thought that the content was already compared in the `Assert::assertEquals` call above.

2021-01-26 07:30 UTC, phil-davis approved these changes, later dismissed

2021-01-26 07:36 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/28384/57/13
Some scenarios are failing, for example:
```
  Scenario: getting shares shared by disabled user                                                         # /drone/src/tests/acceptance/features/apiProvisioning-v1/disableUser.feature:179
    Given the administrator has set the default folder for received shares to "Shares"                     # OccContext::theAdministratorHasSetTheDefaultFolderForReceivedSharesTo()
    And auto-accept shares has been disabled                                                               # FeatureContext::autoAcceptSharesHasBeenDisabled()
    And user "Alice" has been created with default attributes and skeleton files                           # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "Brian" has been created with default attributes and without skeleton files                   # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has shared file "/textfile0.txt" with user "Brian"                                    # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "Brian" has accepted share "/textfile0.txt" offered by user "Alice"                           # FeatureContext::userHasReactedToShareOfferedBy()
    When the administrator disables user "Alice" using the provisioning API                                # FeatureContext::adminDisablesUserUsingTheProvisioningApi()
    Then as "Brian" file "/Shares/textfile0.txt" should exist                                              # FeatureContext::asFileOrFolderShouldExist()
    And the content of file "/Shares/textfile0.txt" for user "Brian" should be "ownCloud test text file 0" # FeatureContext::contentOfFileForUserShouldBe()
      The downloaded content was expected to be 'ownCloud test text file 0', but actually is 'ownCloud test text file 0
      '. HTTP status was 200
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'ownCloud test text file 0'
      +'ownCloud test text file 0\n
      +'
```

There is a step `contentOfFileForUserShouldBePlusEndOfLine` that should work for those scenarios - `textfile0.txt` has an end-of-line character.

Also the similar fails in https://drone.owncloud.com/owncloud/core/28384/58/13

2021-01-26 07:38 UTC, Talank commented
@phil-davis I think the idea of completely removing the `preg_replace()` from `downloadedContentShouldBe` is not that accurate. I will add a `preg_replace()` to filter the `\n`

2021-01-26 08:15 UTC, phil-davis requested changes
We have a step already to specifically check for the end-of-line character. We want the tests to check the exact file content (we do not want the test to still pass if the downloaded content has an extra `\n` or is missing the `n`.

We can just use the step.

2021-01-26 11:12 UTC, phil-davis approved these changes

2021-01-26 11:54 UTC, merged