[Tests-Only] api and webUI tests for moving file
owncloud/core pull request #38352
Opened 2021-01-27 08:18 UTC by swoichha

## Description
This PR adds api and webUI tests for moving file within a received shared folder to new destination.

## Related Issue
- https://github.com/owncloud/ocis/issues/873

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-01-27 11:46 UTC, jasson99 requested changes, later dismissed

2021-01-27 11:46 UTC, jasson99 commented on tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
> +    And the user accepts share "simple-empty-folder" offered by user "Alice" using the webUI
```suggestion
    And the user has accepted share "simple-empty-folder" offered by user "Alice" using the webUI
```

2021-01-27 11:46 UTC, jasson99 commented on tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
> +    And user "Brian" moves folder "/Shares/FOLDER/fileToShare2.txt" to "/simple-folder" using the WebDAV API
```suggestion
    And the user moves file "/Shares/FOLDER/fileToShare2.txt" to "/simple-folder" using the WebDAV API
```

2021-01-27 11:46 UTC, jasson99 commented on tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
> +    But as "Alice" file "/simple-empty-folder/fileToShare2.txt" should not exist
```suggestion
    And as "Alice" file "/simple-empty-folder/fileToShare2.txt" should not exist
```

2021-01-28 10:48 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    When user "Brian" moves file "/Shares/folderToShare/fileToShare2.txt" to "/FOLDER/fileToShare2.txt" using the WebDAV API
```suggestion
    And user "Brian" moves file "/Shares/folderToShare/fileToShare2.txt" to "/FOLDER/fileToShare2.txt" using the WebDAV API
```

2021-01-28 10:48 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    But as "Alice" file "/folderToShare/fileToShare2.txt" should not exist
```suggestion
    And as "Alice" file "/folderToShare/fileToShare2.txt" should not exist
```

2021-01-28 10:56 UTC, Talank commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    But as "Alice" file "/folderToShare/fileToShare2.txt" should not exist
I think `But` also makes good sense :thinking:

2021-01-28 11:09 UTC, Talank reviewed
LGTM

2021-01-28 12:19 UTC, phil-davis approved these changes

2021-01-28 12:19 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +	 * @Given /^the user has (declined|accepted) share "([^"]*)" offered by user "([^"]*)" using the webUI$/
This is not actually needed in the new scenario added by this PR. But is does not hurt to have this form of the step.
(Although we might never use it)

2021-01-28 12:20 UTC, merged