[tests-only] Expand API test coverage for hidden file
owncloud/core pull request #38361
Opened 2021-01-29 07:15 UTC by saw-jan

## Description
API test coverage for `hidden` files
- move to/from
- rename to/from
- upload
- download
- delete
- restore from trashbin

## Related Issue
- closes https://github.com/owncloud/core/issues/36362

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-01 05:03 UTC, dpakach commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +      | new         | /FOLDER/.hidden_file   | .hidden_file          | I am a hidden file |
no need to have content in the example table if it's gonna be the same

2021-02-01 05:04 UTC, jasson99 requested changes, later dismissed

2021-02-01 05:04 UTC, jasson99 commented on tests/acceptance/features/apiTrashbin/trashbinRestore.feature
> +    But as "Alice" the file with original path "<path>" should exist in the trashbin
These are the then steps for some test scenarios already performed. we don't need them here. the only thing we care about in this scenario should be that the hidden file can be restored.

2021-02-01 05:04 UTC, jasson99 commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +  Scenario Outline: download a file
```suggestion
  Scenario Outline: download a hidden file
```

2021-02-01 05:36 UTC, saw-jan commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    Then the content of file "<path>" for user "Alice" should be "uploaded content"
And the content of file "<path>" for user "Alice" should be "uploaded content"

2021-02-01 05:41 UTC, saw-jan commented on tests/acceptance/features/apiTrashbin/trashbinRestore.feature
> +    Then the content of file "<path>" for user "Alice" should be "to delete"
```suggestion
    And the content of file "<path>" for user "Alice" should be "to delete"
```

2021-02-01 05:42 UTC, saw-jan commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    Then the content of file "<path>" for user "Alice" should be "uploaded content"
```suggestion
    And the content of file "<path>" for user "Alice" should be "uploaded content"
```

2021-02-01 06:14 UTC, jasson99 reviewed
LGTM

2021-02-02 03:21 UTC, dpakach reviewed
Tests are good, I think https://github.com/owncloud/core/pull/38366#pullrequestreview-580953203 can be applied here too

2021-02-03 03:23 UTC, dpakach commented on tests/acceptance/features/apiTrashbin/trashbinRestore.feature
> +    Then the HTTP status code should be "201"
This only checks the status code of the last request, I think you will need to use somethihing like 
https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/OCSContext.php#L504

to check the statuscodes for every request

2021-02-03 04:47 UTC, saw-jan commented on tests/acceptance/features/bootstrap/TrashbinContext.php
> +	}
use `$this->featureContext->verifyTableNodeColumns()` instead

2021-02-03 04:47 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebDav.php
> +	}
use `$this->verifyTableNodeColumns()` instead

2021-02-03 05:18 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebDav.php
> +	}
use $this->verifyTableNodeColumns() instead

2021-02-03 06:05 UTC, saw-jan commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    And the content of the following files for user "Alice" should be "hidden file"
```suggestion
    Then the content of the following files for user "Alice" should be "hidden file"
```

2021-02-03 11:37 UTC, dpakach commented on tests/acceptance/features/apiTrashbin/trashbinRestore.feature
> +    Then the HTTP status code should be "201"
I think we have a different step we can use here, this  one just check the status code of last request
use
```
    Then the HTTP status code of responses on all endpoints should be "401"

2021-02-04 11:24 UTC, swoichha reviewed
LGTM

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +      | /FOLDER/.hidden_file102 | .hidden_file102         |
check status codes here

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +      | hidden_file101.txt | .hidden_file102    |
check status codes here

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +      | /FOLDER/.hidden_file |
check status codes here

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +    When user "Alice" downloads file ".hidden_file" using the WebDAV API
status code check

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
> +    Then as "Alice" the following files should exist
check status codes here

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebDav.php
> +			$this->userMovesFileUsingTheAPI($user, $file['from'], $type, $file['to']);
```
			$this->featureContext->pushToLastHttpStatusCodesArray(
				$this->featureContext->getResponse()->getStatusCode()
			);
```

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebDav.php
> +			$this->uploadFileWithContent($user, $content, $destination["path"]);
```
			$this->featureContext->pushToLastHttpStatusCodesArray(
				$this->featureContext->getResponse()->getStatusCode()
			);
```

2021-02-05 03:12 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebDav.php
> +			$this->userDeletesFile($user, $file["path"]);
```
			$this->featureContext->pushToLastHttpStatusCodesArray(
				$this->featureContext->getResponse()->getStatusCode()
			);

2021-02-08 03:10 UTC, dpakach reviewed
LGTM :+1:

2021-02-08 04:10 UTC, individual-it approved these changes

2021-02-08 04:10 UTC, merged