[Tests-Only] polyfill samesite cookie attribute
owncloud/core pull request #38400
Opened 2021-02-14 18:51 UTC by fschade

## Description
some browsers do not support samesite cookie attribute, this pr introduces a cookie helper to polyfill those requirements. The samesite attribute is needed to define where the cookie can be used. This is a major requirement when using openid connect where the idp is deployed to a different domain or similar scenarios. 

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/4191

## Motivation and Context
- https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/
- https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
- https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/
- https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Set-Cookie/SameSite

## How Has This Been Tested?
- local installation 
- openidconnect on azure ad 

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- 
## Checklist:

- [ ] test with all supported browsers
- [ ] test with supported idps
- [ ] test with supported platforms
- [ ] changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-14 18:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38400) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38400) it.</sub>

2021-02-14 21:40 UTC, phil-davis reviewed
Minor comments only. And there are some code-style fails https://drone.owncloud.com/owncloud/core/28612/2/7

2021-02-14 21:40 UTC, phil-davis commented on lib/private/Http/CookieHelper.php
> + * It supports POLYFILL_DETECT mode which tries to detect if the samesite attribute ist supported.
```suggestion
 * It supports POLYFILL_DETECT mode which tries to detect if the samesite attribute is supported.
```

2021-02-14 21:40 UTC, phil-davis commented on lib/private/Http/CookieHelper.php
> +	// if polyfill is set to true it returns the cookie legacy name
```suggestion
	// return the cookie legacy name
```

I don't see an "if" statement in this function.

2021-02-15 10:55 UTC, fschade commented
> Minor comments only. And there are some code-style fails https://drone.owncloud.com/owncloud/core/28612/2/7

thanks phil, done

2021-02-19 13:55 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> + * @copyright Copyright (c) 2018, ownCloud GmbH
2021

2021-02-20 00:27 UTC, phil-davis commented
Lots of people have been requested for review, so I removed "WIP" from the title.

2021-02-23 02:56 UTC, phil-davis reviewed
Needs changelog?

2021-02-23 15:58 UTC, IljaN approved these changes

2021-02-24 09:31 UTC, micbar requested changes
CookieHelper needs full unit test coverage

2021-02-24 10:31 UTC, DeepDiver1975 requested changes

2021-02-24 10:31 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +	public static function setCookie(string $name, string $value = '', array $options = [], string $polyfill = self::POLYFILL_FALLBACK): void {
no static functions - you cannot unit test this that way

2021-02-24 10:31 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +			\trigger_error(
no trigger error - throw exceptions

2021-02-24 10:31 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +		\header(\implode('; ', $header), false);
you cannot unit test the header call

2021-02-24 10:31 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +			$user_agent = $_SERVER['HTTP_USER_AGENT'];
user request instance

2021-02-24 10:31 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +	public static function canSameSite($user_agent = ''): bool {
string declaration missing

2021-02-25 16:05 UTC, micbar commented on lib/private/Http/CookieHelper.php
> +		\header(\implode('; ', $header), false);
move into wrapper method

2021-02-26 11:06 UTC, IljaN commented on lib/private/Http/CookieHelper.php
> +			$user_agent = $_SERVER['HTTP_USER_AGENT'];
Request instance via \OC::$server->getRequest is not initialized at this point. Also not in the calling code. Any ideas?

2021-02-26 11:07 UTC, micbar commented on lib/private/Http/CookieHelper.php
> +			$user_agent = $_SERVER['HTTP_USER_AGENT'];
good catch.

2021-02-26 11:18 UTC, DeepDiver1975 commented on lib/private/Http/CookieHelper.php
> +			$user_agent = $_SERVER['HTTP_USER_AGENT'];
classic cyclic dependency ....

get rid of it by removing the default value from user_agent.

caller has to properly fill this parameter

this way you get a testable CookieHelper - caller afaik is anyhow not unit tested ....

2021-03-02 12:00 UTC, IljaN commented
Superseded by https://github.com/owncloud/core/pull/38457

2021-03-02 12:00 UTC, closed without merging