- Moving de duplication names to View instead of SharedMount
owncloud/core pull request #38427
Opened 2021-02-18 21:55 UTC by wnabrud

- Removing file scans for deduplication

## Description
I am moving the detection of file duplication to the View from the SharedMount.  With this we remove file scans and do it with the files from database.

This is really a concept that work in my local, and would like someone to comment on in.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/38063

## Motivation and Context

Resolve the performance hit with installations that use sharing in Distributed filesystems

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...
I can not make the test to run in my local. I am still working on it.

## Screenshots (if appropriate):

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-18 21:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38427) before we can accept your contribution.<br/><hr/>**wnabruds** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38427) it.</sub>

2021-02-20 00:21 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/28768/5/7
`phan` reports: "lib/private/Files/View.php:1565 PhanUndeclaredMethod Call to undeclared method \OC\Files\Mount\MountPoint::deDuplicate"

Please run `make test-php-phan` to see the report, and adjust whatever is needed.

Also please sort out the commit author(s) and CLA signing. GitHub thinks there is an author `wnabruds` but this PR is from `wnabrud` so there is some confusion around your GitHub name.

2021-02-22 17:27 UTC, mrow4a requested changes
This PR does not "just" move deduplication logic outside, but constructs mountpoint with possibly wrong mountpoint path. There are more points in the code that are just "shortcuts".

Might need another approach to fix https://github.com/owncloud/core/issues/38063

2021-02-22 17:27 UTC, mrow4a commented on lib/private/Files/View.php
>  			$mounts = Filesystem::getMountManager()->findIn($path);
This function returns https://github.com/owncloud/core/blob/master/lib/public/Files/Mount/IMountPoint.php

2021-02-22 17:27 UTC, mrow4a commented on lib/private/Files/View.php
> +							return $mount->getShare()->getTarget();
https://github.com/owncloud/core/blob/master/lib/public/Files/Mount/IMountPoint.php does not publish `getShare()`

2021-02-22 17:27 UTC, mrow4a commented on apps/files_sharing/lib/SharedMount.php
>  		parent::__construct($storage, $absMountPoint, $arguments, $loader);
now absMountPoint will not have unique target. I am not sure if this will work. God knows what other logic relies on this __construct having verified mount point, would probably require archeology in the code

2021-02-22 19:55 UTC, mrow4a commented
other fix got found -> https://github.com/owncloud/core/issues/38063

2021-02-22 19:55 UTC, closed without merging

2021-02-27 21:42 UTC, wnabrud commented on apps/files_sharing/lib/SharedMount.php
>  		parent::__construct($storage, $absMountPoint, $arguments, $loader);
Thanks for taking the time to review. I agree with you that trying to fix this will cause a snowball effect, but what the code is doing currently is also scaring, has big performance hit, and is getting call everywhere. 
Will go back to the bug list and try to help with something else.