[Tests-Only] Adds API tests for counting number of etag elements in response of a versioned file
owncloud/core pull request #38439
Opened 2021-02-23 10:49 UTC by SwikritiT

## Description
Adds API tests for counting number of etag elements  in response of a versioned file

## Related Issue

- Demonstrates  https://github.com/owncloud/ocis/issues/1234

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-24 07:06 UTC, Talank commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +    And the number of etag element in the response should be "2"
Also, check the number of `d:getlastmodified` tags as you have specified in the scenario title.

2021-02-24 07:27 UTC, SwikritiT commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +    And the number of versions should be "2"
@Talank  this checks  the version by counting the last modified so I thought that wouldn't be necessary. Maybe I should rephrase the scenario title.

2021-02-24 07:36 UTC, SwikritiT commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +    And the number of versions should be "2"
@Talank this checks the version by counting `d:getlastmodified` so I thought that wouldn't be necessary. Maybe I should rephrase the scenario title.

2021-02-24 07:57 UTC, Talank commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +    And the number of versions should be "2"
That works, I suppose.

2021-02-24 08:03 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @Then the number of etag element in the response should be :arg1
```suggestion
	 * @Then the number of etag element in the response should be :number
```
If you wish you can change it to something meaningful like this
else LGTM :+1:

2021-02-24 10:40 UTC, Talank reviewed
LGTM

2021-02-24 10:46 UTC, individual-it requested changes

2021-02-24 10:46 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +	 * @Then the number of etag element in the response should be :number
```suggestion
	 * @Then the number of etag elements in the response should be :number
```

2021-02-24 10:46 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebDav.php
> +			"Expected number of etag element was '$number', but got '$actualNumber'"
```suggestion
			"Expected number of etag elements was '$number', but got '$actualNumber'"
```

2021-02-25 07:49 UTC, individual-it approved these changes

2021-02-26 10:58 UTC, merged