[Tests-Only] Refactor api scenario outline examples
owncloud/core pull request #38433
Opened 2021-02-22 08:00 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-23 07:27 UTC, Talank commented on tests/acceptance/features/apiProvisioning-v1/addUser.feature
> +    Then the following users should exist
```suggestion
    And the following users should exist
```

2021-02-23 10:20 UTC, saw-jan commented
LGTM

2021-02-23 10:22 UTC, saw-jan reviewed
LGTM

2021-02-23 10:38 UTC, kiranparajuli589 commented
lgtm :+1:

2021-02-23 11:21 UTC, Talank reviewed
LGTM

2021-02-24 06:36 UTC, individual-it requested changes

2021-02-24 06:36 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		$this->verifyTableNodeColumns($table, ['groupname'], ["comment"]);
lets do the inverted commas the same:
```suggestion
		$this->verifyTableNodeColumns($table, ['groupname'], ['comment']);
```

2021-02-24 06:36 UTC, individual-it commented on tests/acceptance/features/apiProvisioning-v1/addUser.feature
> +  Scenario: admin creates a user with username that contains capital letters
that is not quite the same test anymore
in the original test we create the user with a specific lower/upper case combination and expect it being available in any other lower/upper case combination. e.g. creating user `Brand-New-User` but the user `BRAND-NEW-USER` should exist.
In the changed version of the test it creates all types of users and check if they all exist.
So I think we should not refactor this test

2021-02-24 06:36 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	public function pushToLastStatusCodesArray() {
```suggestion
	public function pushToLastStatusCodesArrays() {
```

2021-02-24 06:36 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	public function pushToLastStatusCodesArray() {
please write also some comments about what the function does

2021-02-24 08:10 UTC, individual-it approved these changes

2021-02-24 10:20 UTC, merged