Added test for request to edit non-existing user by authorized admin
owncloud/core pull request #38441
Opened 2021-02-24 10:28 UTC by Talank

## Description
Request to edit non-existing user by authorized (admin) user sends HTTP status code 401 (unauthorized)

## Related Issue
- Demonstrates https://github.com/owncloud/core/issues/38423

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-24 11:31 UTC, kiranparajuli589 reviewed
Lgtm ✌️

2021-02-24 11:43 UTC, dpakach commented on tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
> +    Scenario: Request to edit non-existing user by authorized admin gets unauthorized in http response
In case of bug demonstration tests we put them in seperate files and skip them. Please Fix this.

2021-02-24 11:44 UTC, dpakach commented on tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
> +    Scenario: Request to edit non-existing user by authorized admin gets unauthorized in http response
For eg https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiAuthWebDav/webdavMultiShashOC10Issue34365.feature

And no need to put issue tag

2021-02-26 11:28 UTC, dpakach reviewed
LGTM :+1:

2021-03-01 06:36 UTC, individual-it requested changes

2021-03-01 06:36 UTC, individual-it commented on tests/acceptance/features/apiAuthOcs/ocsPUTAuthOc10Issue38423.feature
> +
Please add a comment to delete this file when the bug is fixed an use the one from `ocsPUTAut.feature`

2021-03-01 07:17 UTC, individual-it approved these changes

2021-03-02 16:47 UTC, merged