Set user share type to guest if apply
owncloud/core pull request #38440
Opened 2021-02-24 10:24 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-24 16:58 UTC, mrow4a reviewed
can api return „userType” instead? is this possible? this would make it more generic

2021-02-24 17:03 UTC, JanAckermann commented
> can api return „userType” instead? is this possible? this would make it more generic

Of course, we can do this, are there more types than 'user' and 'guest'?

2021-02-24 17:07 UTC, mrow4a commented
> > can api return „userType” instead? is this possible? this would make it more generic
> 
> Of course, we can do this, are there more types than 'user' and 'guest'?

needs to be investigated, best if returns some ID / CONST defined in core.

2021-02-25 13:06 UTC, JanAckermann commented
@mrow4a ok updated in that favor, might have quick look? if you give me green light, I will update the tests

2021-02-25 13:12 UTC, mrow4a requested changes
generally makes sense, one small detail to be fixed

2021-02-25 13:12 UTC, mrow4a commented on lib/public/User.php
> +class User extends \OC\User\Constants{
public/User using private/User ? Constanst should be public, and not private implementation

2021-02-25 13:14 UTC, JanAckermann commented on lib/public/User.php
> +class User extends \OC\User\Constants{
I took the share implementation as boilerplate

2021-02-25 15:28 UTC, JanAckermann commented
@mrow4a Tests passed, approve?

2021-02-25 17:28 UTC, mrow4a approved these changes

2021-02-25 18:05 UTC, merged