[Tests-Only] Refactor api scenario outline examples (part2)
owncloud/core pull request #38444
Opened 2021-02-25 02:58 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-02-26 07:47 UTC, Talank commented on tests/acceptance/features/apiProvisioningGroups-v1/deleteGroupOc10Issue31015.feature
> +    When the administrator sends a group creation request for the following group using the provisioning API
Shouldn't this be in the `Given` step? :thinking:

2021-03-01 03:25 UTC, dpakach commented on tests/acceptance/features/bootstrap/Provisioning.php
> +		pushToLastStatusCodesArrays();
```suggestion
		$this->pushToLastStatusCodesArrays();
```

2021-03-02 06:23 UTC, kiranparajuli589 requested changes, later dismissed

2021-03-02 06:23 UTC, kiranparajuli589 commented on tests/acceptance/features/apiProvisioning-v2/addUser.feature
> +=======
incomplete rebase??

2021-03-02 06:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Then the the following user should belong to the following group
```suggestion
	 * @Then the following users should belong to the following groups
```

2021-03-02 06:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Then the the following user should not belong to the following group
```suggestion
	 * @Then the following users should not belong to the following groups
```

2021-03-02 06:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given the following user have been added to the following group
```suggestion
	 * @Given the following users have been added to the following groups
```

2021-03-02 06:23 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @When the administrator removes the following user from the following group using the provisioning API
```suggestion
	 * @When the administrator removes the following users from the following groups using the provisioning API
```

2021-03-03 03:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Then the the following users should belong to the following groups
```suggestion
	 * @Then the following users should belong to the following groups
```

2021-03-03 03:54 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Then the the following users should not belong to the following groups
```suggestion
	 * @Then the following users should not belong to the following groups
```

2021-03-04 11:10 UTC, swoichha reviewed
lgtm

2021-03-09 06:52 UTC, individual-it requested changes

2021-03-09 06:52 UTC, individual-it commented on tests/acceptance/features/apiProvisioning-v2/addUser.feature
>      Examples:
no table for the Examples?
I think we can delete the complete Scenario Outline, it will not run anymore

2021-03-09 06:52 UTC, individual-it commented on tests/acceptance/features/apiProvisioningGroups-v1/addGroupOc10Issue31015.feature
> +    #And group "<group_id>" should exist
left over comment or should we add anything to that step?

2021-03-09 10:54 UTC, kiranparajuli589 reviewed
lgtm :+1:

2021-03-09 11:01 UTC, Talank reviewed
LGTM :+1:

2021-03-10 03:29 UTC, individual-it approved these changes

2021-03-10 03:30 UTC, individual-it commented
Please bump the core commit id in ocis and cs3org/reva repos

2021-03-10 03:56 UTC, merged