[tests-only] TUS tests for checksum
owncloud/core pull request #38466
Opened 2021-03-04 07:59 UTC by swoichha

## Description
This PR adds test for TUS checksum.

## Related Issue
- https://github.com/owncloud/ocis/issues/1599

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-04 08:37 UTC, Talank reviewed
LGTM

2021-03-04 10:52 UTC, individual-it requested changes

2021-03-04 10:52 UTC, individual-it commented on tests/acceptance/features/bootstrap/TUSContext.php
> +	 * @Given user :user has uploaded file with checksum :checksum to the last created TUS Location with offset :offset and content :content using the TUS protocol on the WebDAV API
The Given step seems not to be used, if you want to have a given step, please split it off and add at least simple checks to see if it succeeded

2021-03-04 10:56 UTC, swoichha commented on tests/acceptance/features/bootstrap/TUSContext.php
> +	 * @Given user :user has uploaded file with checksum :checksum to the last created TUS Location with offset :offset and content :content using the TUS protocol on the WebDAV API
It has been used here https://github.com/owncloud/core/pull/38466/files#diff-26b35f83f03795db544087e974a4b86d10d40038b2f5183c82df603984f08301R40

2021-03-04 12:24 UTC, individual-it requested changes

2021-03-04 12:24 UTC, individual-it commented on tests/acceptance/features/bootstrap/TUSContext.php
> +		$this->sendsAChunkToTUSLocationWithOffsetAndData($user, $offset, $content, $checksum);
need a check here if the step actually succeeded

2021-03-05 04:23 UTC, dpakach reviewed
LGTM :+1:

2021-03-05 07:15 UTC, individual-it approved these changes

2021-03-05 07:46 UTC, merged