chore: add logging to signed url verifier
owncloud/core pull request #38465
Opened 2021-03-04 07:48 UTC by DeepDiver1975

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-04 07:53 UTC, DeepDiver1975 commented
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would create a [changelog](https://github.com/owncloud/core/blob/master/changelog/README.md) item based on your changes.

not needed

2021-04-21 13:12 UTC, IljaN approved these changes

2021-04-21 13:24 UTC, micbar commented
> > Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would create a [changelog](https://github.com/owncloud/core/blob/master/changelog/README.md) item based on your changes.
> 
> not needed

Why?

2021-04-21 15:09 UTC, DeepDiver1975 commented
> Why?

this started off as a pure debugging pr and by that time there was no need .... not there is for sure .... needs to be added ....

2021-05-10 11:36 UTC, AlexAndBear requested changes
Add changelog item

2021-05-12 15:42 UTC, DeepDiver1975 commented
@JanAckermann chanelog added - thx for the reminder

2021-05-12 15:44 UTC, JanAckermann approved these changes
Nice :+1:

2021-05-12 16:45 UTC, merged