[Tests-Only] Refactor scenarios with large skeleton files
owncloud/core pull request #38468
Opened 2021-03-05 08:33 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-17 06:49 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
> +    Given these users have been created with default attributes and without skeleton files:
this step initializes the user...does this affect the scenario?? :thinking:

2021-03-17 06:49 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
> +    And user "Brian" has been created with default attributes and large skeleton files
imo brian can also be created without skeleton. just two resources to prepare

2021-03-17 06:49 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
> +    And user "<username>" has been created with default attributes and large skeleton files
IMO can be created without skeleton files. there are only just two resources to prepare.

2021-03-17 06:49 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingInternalUsers1/miscShareWithUsers.feature
> +    And user "Brian" has been created with default attributes and large skeleton files
can be used without skeleton

2021-03-18 11:41 UTC, Talank commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "Carol" has been created with default attributes and without skeleton files
you can use the step `these users have been created with default attributes and without skeleton files:` as both are created with the same config.

2021-03-18 11:41 UTC, Talank commented on tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
> +    And user "Brian" has been created with default attributes and without skeleton files
same here. use `these users have been created with default attributes and without skeleton files:`

2021-03-18 12:13 UTC, jasson99 commented on tests/acceptance/features/webUIFiles/fileDetails.feature
> +    Given these users have been created with default attributes and without skeleton files:
```suggestion
    Given user "Alice" has been created with default attributes and without skeleton files
```

2021-03-18 12:13 UTC, jasson99 commented on tests/acceptance/features/webUIWebdavLocks/unlock.feature
> +    Given these users have been created without skeleton files:
```suggestion
    Given user "receiver1" has been created without skeleton files
```

2021-03-23 03:20 UTC, dpakach reviewed
lgtm :+1:

2021-03-23 11:11 UTC, kiranparajuli589 reviewed
lgtm :+1:

2021-03-24 05:01 UTC, individual-it requested changes

2021-03-24 05:01 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given /^these users have been created without skeleton files ?(and not initialized|):$/
this should not make any big difference
not initialising a user was just an old trick to save time, the skeleton is only copied on initialisation. If we don't use the skeleton in the first place, not initialising only saves one network request

2021-03-24 05:08 UTC, HariBhandari07 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	 * @Given /^these users have been created without skeleton files ?(and not initialized|):$/
In settingsMenu tests like for eg; https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUISettingsMenu/settingsMenu.feature#L29

we have scenarios where user's last login is checked. If a user is not initialized, `last login` is `never` while for initialized users `last login` is `seconds ago`. So, this can be used for those tests.

2021-03-24 07:59 UTC, jasson99 reviewed
Apart from existing comments, LGTM

2021-03-25 06:04 UTC, individual-it approved these changes

2021-03-25 06:21 UTC, merged