[tests-only] Tus tests for uploading to shared files with checksums
owncloud/core pull request #38484
Opened 2021-03-09 11:26 UTC by swoichha

## Description
This PR adds tests for:
- Issue  https://github.com/owncloud/ocis/issues/1747
- Uploading to shared files

## Related Issue
- https://github.com/owncloud/ocis/issues/1754

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-09 11:32 UTC, Talank reviewed
LGTM

2021-03-09 11:32 UTC, Talank commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +      | Upload-Metadata | filename L1NoYXJlcy9GT0xERVIvdGV4dGZpbGUudHh0 |
it is hard to understand the encrypted name and would have been better if there is a comment somewhere that says what is the actual name of this file.
But, that's just a suggestion. Everything looks good to me anyway. :+1:

2021-03-10 05:57 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +      | Upload-Metadata | filename L1NoYXJlcy9GT0xERVIvdGV4dGZpbGUudHh0 |
The encrypted file name can be seen here https://github.com/owncloud/core/pull/38484/files#diff-0613ee3f838a6348f280cfa6593798e61953aea15b0fb94b85d92335095700d9R91. 

So far for all the tests we haven't mentioned the encrypted file name(which is sent as metadata to created the file) in any comments so I don't if we should or shouldn't do it. @individual-it what do you think about this idea of mentioning encrypted filename in a comment?

2021-03-10 06:17 UTC, individual-it commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +      | Upload-Metadata | filename L1NoYXJlcy9GT0xERVIvdGV4dGZpbGUudHh0 |
I think it would be good to mention. maybe let's have an other PR doing that for all places

2021-03-10 06:22 UTC, individual-it requested changes
please also add tests where
- [x] the sharer upload a file in a shared folder and the receiver checks the checksum with propfind and in the header
- [ ] upload with other checksum types
- [ ] upload with chucks to a share (from both sides)
- [ ] upload wrong checkssums (from both sides)

if you like some or all of those things could go in a separate PR

2021-03-10 08:41 UTC, dpakach reviewed
apart from everything mentioned already looks good

2021-03-10 08:46 UTC, swoichha commented
> please also add tests where
> 
> * [x]  the sharer upload a file in a shared folder and the receiver checks the checksum with propfind and in the header
> * [x]  upload with other checksum types
> * [x]  upload with chucks to a share (from both sides)
> * [x]  upload wrong checkssums (from both sides)
> 
> if you like some or all of those things could go in a separate PR

@individual-it I have added all these tests and removed changes done in tests for `OPTIONS` request, I will add them back later on new PR as this PR claims to be about shares.

2021-03-10 09:04 UTC, Talank commented on tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
> +    And user "Alice" uploads file with checksum "SHA1 8cb2237d0679ca88db6464eac60da96345513954" to the last created TUS Location with offset "0" and content "uploaded content" using the TUS protocol
```suggestion
    When user "Alice" uploads file with checksum "SHA1 8cb2237d0679ca88db6464eac60da96345513954" to the last created TUS Location with offset "0" and content "uploaded content" using the TUS protocol on the WebDAV API
```
I think this is supposed to be a `When` step

2021-03-10 09:25 UTC, Talank reviewed
LGTM :+1:

2021-03-10 10:23 UTC, individual-it approved these changes

2021-03-11 05:18 UTC, merged