[Tests-Only] Add acceptance tests for resharing deleted file
owncloud/core pull request #38490
Opened 2021-03-11 04:14 UTC by dpakach

## Description

Add acceptance tests for resharing a deleted file.

## Related Issue

- Tests for issue https://github.com/owncloud/ocis/issues/1787

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-11 04:26 UTC, Talank requested changes

2021-03-11 04:26 UTC, Talank commented on tests/acceptance/features/apiShareReshareToRoot1/reShare.feature
> +      | 2               | 200             | 200              |
since the HTTP status code is 200 in both examples, you do not need to keep it in the example table.

2021-03-11 05:41 UTC, Talank approved these changes

2021-03-11 11:10 UTC, individual-it approved these changes
is the bug described in https://github.com/owncloud/ocis/issues/1787 also reproducible with files? 
@kulmann mentioning sharing of folders.
maybe we could add also a test with sharing a folder

2021-03-12 08:20 UTC, individual-it approved these changes

2021-03-15 05:16 UTC, merged