[Tests-Only]Add tests to create tags with names in lower and upper case and assert they are displayed differently
owncloud/core pull request #38503
Opened 2021-03-12 08:21 UTC by jasson99

## Description
This PR adds test scenarios to create tags with names in lowercase and in uppercase and asserts that these created tags are displayed accordingly. 

## Related Issue
- Fixes https://github.com/owncloud/core/issues/38499
- Can be merged after rebasing with https://github.com/owncloud/core/pull/38498

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-12 10:20 UTC, individual-it requested changes

2021-03-12 10:20 UTC, individual-it commented on tests/acceptance/features/webUITags/createTags.feature
> +    Then file "/randomfile.txt" should have the following tags for user "Alice"
additionally a check of the tags on the UI would be useful
in #38498 only the display of capital/lower case of the tag was fixed by adjusting CSS
and I'm even not sure if selenium would pick up that change anyway

These tests pass currently even without the fix in #38498

2021-03-12 10:25 UTC, jasson99 commented on tests/acceptance/features/webUITags/createTags.feature
> +    Then file "/randomfile.txt" should have the following tags for user "Alice"
yes, you are right. I am doing that right now.

2021-03-15 11:29 UTC, jasson99 commented on tests/acceptance/features/webUITags/createTags.feature
> +    Then file "/randomfile.txt" should have the following tags for user "Alice"
fixed

2021-03-15 11:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +		$results = $this->filesPage->getDetailsDialog()->getTagsListItems();
you can also, verify the table column names

2021-03-15 11:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +		$displayedTags = [];
verify the table col to have `name` column

2021-03-15 11:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +			\array_push($displayedTags, $tag);
can you assert here so that next for loop needn't to be initiated?? :thinking:

2021-03-15 11:41 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +				"Tagname $tagName was not displayed in the Tag list"
```suggestion
				"Tag name $tagName was not displayed in the tag list"
```

2021-03-16 05:49 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +				"Tagname $tagName was not displayed in the Tag list"
fixed

2021-03-16 05:50 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +		$results = $this->filesPage->getDetailsDialog()->getTagsListItems();
fixed

2021-03-16 05:50 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUITagsContext.php
> +		$displayedTags = [];
fixed

2021-03-16 06:01 UTC, kiranparajuli589 commented
lgtm :+1:

2021-03-16 06:04 UTC, individual-it approved these changes

2021-03-16 07:34 UTC, kiranparajuli589 approved these changes

2021-03-16 09:10 UTC, merged