[tests-only] Adds api tests for overwiting file with checksums
owncloud/core pull request #38504
Opened 2021-03-12 08:31 UTC by SwikritiT

## Description
This PR adds tests for:

* Upload a file with checksum and overwrite the file with new data and checksum(correct / invalid)
*  Upload a file with checksum and overwrite the file with new data and invalid checksum(correct / invalid)

## Related Issue

- https://github.com/owncloud/ocis/issues/1789

## Motivation and Context

## How Has This Been Tested?

- :robot: 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-15 04:38 UTC, swoichha requested changes

2021-03-15 04:38 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
> +  Scenario Outline: Overwriting as existing file with new data and checksum should return the checksum of new data in the propfind
```suggestion
  Scenario Outline: Overwriting an existing file with new data and checksum should return the checksum of new data in the propfind
```

2021-03-15 04:38 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
> +      | Upload-Metadata | filename dGV4dEZpbGUudHh0 |
Please add a comment for encoded filename like in https://github.com/owncloud/core/blob/bdb0dd654ff0b3c1e9fc6e678eb5052dff2c1465/tests/acceptance/features/apiWebdavUploadTUS/checksums.feature#L11

2021-03-15 04:38 UTC, swoichha commented on tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
> +    And as "Alice" file "textFile.txt" should not exist
Here the file `textFile.txt` for user `Alice` should exist with original content `12345`

2021-03-15 07:28 UTC, dpakach approved these changes
LGTM :+1:

2021-03-15 11:13 UTC, individual-it approved these changes
:+1: 
please make sure the core commit id gets updated in ocis and cs3org/reva repo

2021-03-16 05:19 UTC, swoichha approved these changes

2021-03-16 06:30 UTC, merged