used skeleton files more wisely on capabilites and comments part of a…
owncloud/core pull request #38516
Opened 2021-03-15 12:19 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiComments
  - apiCapabilities

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-15 16:16 UTC, Talank commented on tests/acceptance/features/apiComments/deleteComments.feature
> +    And user "Brian" should have the following comments on folder "/FOLDER"
This step sounds like a `Then` step. Maybe, you should consider rewording this as well :thinking: 
Other than this, everything LGTM :+1:

2021-03-16 08:37 UTC, individual-it requested changes

2021-03-16 08:37 UTC, individual-it commented on tests/acceptance/features/apiComments/comments.feature
> -    Given user "Alice" has uploaded file "filesForUpload/textfile.txt" to "/myFileToComment.txt"
what about leaving this step and for that don't use any skeleton in the Background?

2021-03-16 08:37 UTC, individual-it commented on tests/acceptance/features/apiComments/deleteComments.feature
> -    Given user "Alice" has uploaded file "filesForUpload/textfile.txt" to "/myFileToComment.txt"
same comment as for comments.feature

2021-03-17 07:38 UTC, kiranparajuli589 commented on tests/acceptance/features/apiComments/deleteComments.feature
> +    And user "Brian" should have the following comments on folder "/FOLDER"
yeah..we do not need to use then verification for given steps.
removed this! TY :clinking_glasses:

2021-03-17 07:45 UTC, kiranparajuli589 commented
@individual-it @Talank addressed your comments. please review again!

2021-03-17 08:23 UTC, individual-it requested changes
I don't understand why you do extra work and changing names of files/folders that work fine

2021-03-17 08:23 UTC, individual-it commented on tests/acceptance/features/apiComments/deleteComments.feature
> +    And user "Alice" has commented with content "<comment>" on file "/textfile0.txt"
why do we need to change those names? `myFileToComment` sounds like a good name

2021-03-17 11:38 UTC, Talank reviewed
LGTM

2021-03-17 11:41 UTC, Talank commented on tests/acceptance/features/apiComments/deleteComments.feature
> +    And user "Alice" has commented with content "<comment>" on file "/textfile0.txt"
the changes made the filename more simple but less descriptive

2021-03-18 03:27 UTC, individual-it approved these changes
still one place where you change the folder name for no reason and you also add `/` in some file actions :thinking: 
That just adds extra noise in the PR, but because the overall result seems to be OK I will approve it.

Please make sure the commit ids are bumped in ocis and cs3org/reva repos

2021-03-18 11:27 UTC, Talank commented on tests/acceptance/features/apiComments/comments.feature
> +    And user "Alice" has commented with content "My first comment" on file "/myFileToComment.txt"
Why? 🤔 Is it really necessary to add `/`?

2021-03-19 11:09 UTC, kiranparajuli589 commented on tests/acceptance/features/apiComments/comments.feature
> +    And user "Alice" has commented with content "My first comment" on file "/myFileToComment.txt"
just be uniform in this feature file with the placement of `/`

2021-03-22 07:09 UTC, merged