[Tests-Only] used small skeleton directory more wisely on API share create special features
owncloud/core pull request #38517
Opened 2021-03-15 12:51 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiShareCreateSpecialToRoot1
  - apiShareCreateSpecialToRoot2
  - apiShareCreateSpecialToShares1
  - apiShareCreateSpecialToShares2

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-17 11:26 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" has shared file "welcome.txt" with group "grp1"
do we want to share `welcome.txt` :thinking:

2021-03-18 10:49 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" has shared file "welcome.txt" with group "grp1"
no, we don't.
fixed this!

2021-03-18 12:27 UTC, dpakach reviewed
lgtm :+1:

2021-03-19 11:22 UTC, individual-it requested changes

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareWhenExcludedFromSharing.feature
> +    And user "Brian" has uploaded file "filesForUpload/textfile.txt" to "/textfile0.txt"
I would leave the filename `fileToShare.txt` I think its actually more descriptive and would lead to a smaller diff

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareWhenExcludedFromSharing.feature
> +    And user "Alice" has been added to group "grp1"
why changing that around?

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareWhenExcludedFromSharing.feature
> +    And user "Brian" has created folder "FOLDER"
no need to change the username or the folder name

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareGroupAndUserWithSameName.feature
> +    And user "Alice" has uploaded file with content "foo" to "/textfile0.txt"
using `randomfile.txt` would lead to a much smaller diff

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithInvalidPermissions.feature
> +    And user "Alice" has created folder "<item>"
its always `PARENT`, so having it hard-coded here would make the test more readable

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithInvalidPermissions.feature
> +      | path        | <item>        |
its always `PARENT`, so having it hard-coded here would make the test more readable

2021-03-19 11:22 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupCaseSensitive.feature
> +    When user "Alice" shares file "textfile2.txt" with group "<group_id2>" using the sharing API
good catch :+1:

2021-03-25 05:15 UTC, jasson99 commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWhenShareWithOnlyMembershipGroups.feature
>      And group "grp0" has been created
Cannot these be added to the background?

2021-03-25 10:22 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWhenShareWithOnlyMembershipGroups.feature
>      And group "grp0" has been created
yes, it could be..other steps were also suitable in the background.
fixed this...!!

2021-03-25 11:58 UTC, individual-it requested changes

2021-03-25 11:58 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareWhenExcludedFromSharing.feature
> +    And user "Brian" has uploaded file "filesForUpload/textfile.txt" to "/textfile0.txt"
you need a `fileToShare.txt`

2021-03-26 06:36 UTC, jasson99 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
> +    And user "Brian" has been created with default attributes and without skeleton files
Looks like this too can be added to the background

2021-03-26 06:36 UTC, jasson99 commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWhenShareWithOnlyMembershipGroups.feature
>      And group "grp0" has been created
is it fixed?

2021-03-30 07:34 UTC, individual-it requested changes

2021-03-30 07:34 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>        | /PARENT/                  |
Brian does not create this folder, not uploads `parent.txt` so the tests fail. would be good to make Brian to create those files, to make sure the share is received in `Shares`

2021-03-30 07:37 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWhenShareWithOnlyMembershipGroups.feature
>      And group "grp0" has been created
yes it is!

2021-03-30 09:14 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>        | /PARENT/                  |
in this scenario...received shares that exist inside `Shares` folder are asserted properly. `FOLDER` is never used for any shares. So I've removed that from the list of elements to be seen by the receiver (receiver specific like /PARENT or /FOLDER). we've other tests to verify that IMO.

2021-03-30 09:21 UTC, individual-it approved these changes

2021-03-30 09:23 UTC, merged