[Tests-Only] used skeleton files more wisely on favorites and main part of API tests
owncloud/core pull request #38515
Opened 2021-03-15 11:17 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiFavorites
  - apiMain

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-15 11:30 UTC, Talank reviewed
LGTM

2021-03-17 08:25 UTC, individual-it requested changes

2021-03-17 08:25 UTC, individual-it commented on tests/acceptance/features/apiFavorites/favorites.feature
> +    And user "Alice" has been created with default attributes and small skeleton files
this used to be the way we want it:
we want to name the files/folders that we use more explicitly, so that a reader of the feature file would be able to understand what happens without having to know about the skeleton files.
We want only to use the skeleton files where we need a lot of them

2021-03-18 11:44 UTC, individual-it requested changes
please check that all tests that are testing "overwriting" have a file in place to overwrite

2021-03-18 11:44 UTC, individual-it commented on tests/acceptance/features/apiMain/checksums.feature
>    Scenario Outline: Uploading a file with invalid SHA1 checksum overwriting an existing file
this test is about overwriting an existing file, as you don't use the skeleton files anymore, what is good, we need to upload a file first

2021-03-19 04:58 UTC, kiranparajuli589 commented on tests/acceptance/features/apiMain/checksums.feature
>    Scenario Outline: Uploading a file with invalid SHA1 checksum overwriting an existing file
fixed

2021-03-19 05:02 UTC, individual-it approved these changes

2021-03-19 08:14 UTC, individual-it approved these changes
please make sure core id commits are bumped and merged before you leave for the weekend, otherwise leave this for monday

2021-03-23 03:26 UTC, dpakach reviewed
lgtm :+1:

2021-03-23 03:33 UTC, merged