Used skeleton folders more wisely in API provisioning tests
owncloud/core pull request #38513
Opened 2021-03-15 09:37 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on apiProvisioning* tests

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-15 11:25 UTC, Talank requested changes

2021-03-15 11:25 UTC, Talank commented on tests/acceptance/features/apiProvisioning-v1/editUser.feature
> +#    Given using OCS API version "1"
Why commenting it? And why not deleting instead of commenting? :thinking:

2021-03-15 11:28 UTC, kiranparajuli589 commented on tests/acceptance/features/apiProvisioning-v1/editUser.feature
> +#    Given using OCS API version "1"
just for a test purpose! i've reverted it.

2021-03-18 11:34 UTC, Talank reviewed
LGTM

2021-03-18 11:35 UTC, Talank approved these changes

2021-03-23 03:22 UTC, dpakach reviewed
Lgtm :+1:

2021-03-24 09:14 UTC, individual-it approved these changes

2021-03-25 05:06 UTC, jasson99 reviewed
And also resolve the conflicts

2021-03-25 05:06 UTC, jasson99 commented on tests/acceptance/features/apiProvisioning-v1/enableUser.feature
> +    Given these users have been created with default attributes and without skeleton files:
```suggestion
    Given user "Alice" been created with default attributes and without skeleton files:
```

2021-03-25 05:06 UTC, jasson99 commented on tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
> +    Given these users have been created with default attributes and without skeleton files:
```suggestion
    Given user "another-admin" has been created with default attributes and without skeleton files:
```

2021-03-25 05:06 UTC, jasson99 commented on tests/acceptance/features/apiProvisioning-v2/enableUser.feature
> +    Given these users have been created with default attributes and without skeleton files:
```suggestion
    Given user "Alice" has been created with default attributes and without skeleton files:
```

2021-03-25 05:06 UTC, jasson99 commented on tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
>        | Alice    |
```suggestion
    Given user "Alice" has been created with default attributes and without skeleton files:
```

2021-03-25 05:06 UTC, jasson99 commented on tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
>        | Alice    |
```suggestion
    Given user "Alice" has been created with default attributes and without skeleton files:
```

2021-03-25 14:23 UTC, merged