used skeleton files more wisely on api share operations to features
owncloud/core pull request #38533
Opened 2021-03-17 07:17 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiShareOperationsToRoot
  - apiShareOperationsToShares

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-17 08:20 UTC, individual-it requested changes
we need to do the opposite: wherever we have used `welcome.txt` we need to get rid of it

2021-03-17 08:20 UTC, individual-it commented on tests/acceptance/features/apiShareOperationsToRoot/accessToShare.feature
> +    And user "Alice" has shared file "welcome.txt" with user "Brian"
don't rely on having a `welcome.txt` that will not be the case for ocis or other special implementations like BayernBox

2021-03-17 11:06 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToRoot/changingFilesShare.feature
> +    And user "Alice" has moved file "/welcome.txt" to "/shared/sub/shared_file.txt"
welcome.txt is being used in several places.

2021-03-18 10:20 UTC, kiranparajuli589 commented
@individual-it @Talank addressed your comments. please review again.

2021-03-18 11:30 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToRoot/accessToShare.feature
> +    And user "Alice" has shared file "welcome.txt" with group "grp1"
Use `textfile0.txt` instead of `welcome.txt`

2021-03-18 11:49 UTC, individual-it requested changes
`welcome.txt` is still used
please double check if any of the tests in those files are expecting a file to exist to test "overwriting"

2021-03-19 03:12 UTC, individual-it approved these changes

2021-03-19 04:44 UTC, merged