fix downloadURL of public links
owncloud/core pull request #38532
Opened 2021-03-16 15:44 UTC by C0rby

## Description
Make the downloadURL always relative to the owncloud base path.

## Related Issue

- https://github.com/owncloud/web/pull/4689#pullrequestreview-613291079

## Motivation and Context

If ownCloud is setup in a subdirectory like `https://example.com/owncloud/` then we don't wan't to include the subdirectory in the relative downloadURL.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-16 15:46 UTC, kulmann approved these changes
👍

2021-03-16 16:01 UTC, micbar approved these changes

2021-03-17 13:42 UTC, jnweiger commented
@C0rby when and how can the double prefix occur? I don't understand the context of https://github.com/owncloud/web/pull/4689#pullrequestreview-613291079

2021-03-17 13:48 UTC, jnweiger commented on apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
> +					$path = '/remote.php/dav/' . $server->getRequestUri();
This results in a partial URL starting with a /.
So it is not relative, but rooted. 
I'd normally object that, as it looks like it should break, when installing owncloud in a subdirectory.

But as you introduce that exactly to fix something with subdirectories, I assume you know what you are doing.

2021-03-17 13:50 UTC, kulmann commented on apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
> +					$path = '/remote.php/dav/' . $server->getRequestUri();
Good spot. In fact the leading slash gets removed again in ownCloud Web. So it'd be fine to have a relative URL here.

2021-03-17 13:57 UTC, jnweiger requested changes
I lack enough insights to review the fix itself.
It affects the behavior of the propFind() method. Not sure how widely used that method is. 

Please provide a clear example how to make a PROPFIND call that would benefit from that.
Is this a problem with new code, or is the same problem also present in released versions?

2021-03-17 15:21 UTC, C0rby commented on apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
> +					$path = '/remote.php/dav/' . $server->getRequestUri();
> This results in a partial URL starting with a /.
So it is not relative, but rooted.

Yes, you're right.

> I'd normally object that, as it looks like it should break, when installing owncloud in a subdirectory.

It's the client responsibility to prepend the base path to this. Including the subdirectory if owncloud was intalled in one.
But as you commented here: https://github.com/owncloud/web/pull/4689#issuecomment-801107583
> Why do we go for flexibility? I'd argue that a full URL is more robust, as no errors can be made during URL-assembly.

I was thinking that maybe in a loadbalanced setup having the full URL could break things. After thinking about it again I don't think so anymore.
The instances would have to configure the `overwrite.cli.url` anyways right? So I could just use that as the base url and it should point to the load balancer/public address.

2021-03-17 15:25 UTC, C0rby commented
> I lack enough insights to review the fix itself.
> It affects the behavior of the propFind() method. Not sure how widely used that method is.
> 
> Please provide a clear example how to make a PROPFIND call that would benefit from that.
> Is this a problem with new code, or is the same problem also present in released versions?

It's not a problem in released versions. This PR fixes a problem which was introduced with a new feature for 10.7 #38376 

To test this you can send this PROPFIND request:
```
curl -s -u public:<share_password>  -k -X PROPFIND -d '<?xml version="1.0"?>
  <d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
    <d:prop>
      <oc:permissions />
      <oc:favorite />
      <oc:fileid />
      <oc:owner-id />
      <oc:owner-display-name />
      <oc:share-types />
      <oc:privatelink />
      <d:getcontentlength />
      <oc:size />
      <d:getlastmodified />
      <d:getetag />
      <d:resourcetype />
      <oc:downloadURL />
    </d:prop>
  </d:propfind>' https://localhost:9200/remote.php/dav/public-files/rUenhLAqWpfHPXJ | xmllint --format -
  ```
  
  You have to do propfind requests for public shares with and without passwords.

2021-03-17 15:41 UTC, C0rby commented on apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
> +					$path = '/remote.php/dav/' . $server->getRequestUri();
> Also note that legacy "/remote.php/webdav/" endpoint is still supported I think. It doesn't seem a good idea to mix both endpoints. I don't know if some webdav clients could throw errors if you change the endpoint; at least I would be suspicious

I see your point but will a generic webdav client even use this owncloud proprietary attribute?
Or am I wrong and this isn't a proprietary attribute?

Anyways this feature is especially implemented to solve a problem of webclients or more specifically of ownCloud web.
Our other clients don't even need this.

2021-03-17 23:55 UTC, jnweiger commented
Tested the patch in https://188.34.186.241/owncloud
Looks good. Thanks for the details!

2021-03-17 23:56 UTC, jnweiger approved these changes
Tested the patch in https://188.34.186.241/owncloud
Looks good. Thanks!

2021-03-18 09:26 UTC, C0rby commented
@micbar @jnweiger, regarding putting the full URL into `downloadURL`. Can I assume that the config option `overwrite.cli.url` will always be set? If not I'd leave it at the rooted url.

Or is there any other reliable way to get the owncloud base path like `https://owncloud.example.com/` or `https://example.com/owncloud/`.

2021-03-18 10:04 UTC, C0rby commented
I found a way. And now the downloadURL is a full URL not a rooted/relative URL. So the handling for the frontend should be easier now. :)

2021-03-18 14:14 UTC, merged