[Tests-Only] used small skeletons more wisely on share management test features
owncloud/core pull request #38534
Opened 2021-03-17 07:34 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiShareOperationsToRoot
  - apiShareOperationsToShares

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-24 02:40 UTC, dpakach reviewed
lgtm :+1:

2021-03-24 12:59 UTC, Talank commented on tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
> +    And user "Alice" has shared file "welcome.txt" with user "Brian"
I think we want to avoid the use of `welcome.txt` file 🤔

2021-03-25 05:20 UTC, jasson99 commented on tests/acceptance/features/apiWebdavLocksUnlock/unlockOnDelete.feature
> +    Given user "Alice" has locked file "locked/textfile0.txt" setting the following properties
```suggestion
    And user "Alice" has locked file "locked/textfile0.txt" setting the following properties
```

2021-03-25 05:20 UTC, jasson99 commented on tests/acceptance/features/apiWebdavLocksUnlock/unlockOnDelete.feature
> +    Given user "Alice" has locked file "alsonotlocked/PARENT" setting the following properties
```suggestion
    And user "Alice" has locked folder "locked/PARENT" setting the following properties
      | lockscope | <lock-scope> |
    And user "Alice" has locked folder "notlocked/PARENT" setting the following properties
      | lockscope | <lock-scope> |
    And user "Alice" has locked file "alsonotlocked/PARENT" setting the following properties
```

2021-03-26 09:06 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
> +    And user "Alice" has shared file "welcome.txt" with user "Brian"
true
fixed✅

2021-03-30 04:23 UTC, jasson99 reviewed
LGTM

2021-03-31 11:18 UTC, individual-it commented on tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
> +    And user "Brian" has moved file "/fileToShare.txt" to "/FOLDER/fileToShare.txt"
why not uploading directly to the correct place? this tests seems not to be about moving

2021-03-31 11:32 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
> +    And user "Brian" has moved file "/fileToShare.txt" to "/FOLDER/fileToShare.txt"
i've adjusted the scenario, please have a look again

2021-04-01 03:09 UTC, individual-it reviewed
apiShareManagementToShares/acceptShares.feature:392 fails because Brian hasn't uploaded textfile0.txt

2021-04-01 05:01 UTC, individual-it requested changes

2021-04-01 05:01 UTC, individual-it commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    Given user "Alice" has shared file "welcome.txt" with user "Brian"
don't rely on `welcome.txt`

2021-04-01 05:01 UTC, individual-it commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    And user "Alice" has shared file "welcome.txt" with group "grp1"
don't rely on `welcome.txt`

2021-04-01 05:01 UTC, individual-it commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    And user "Alice" has shared file "welcome.txt" with group "grp1" with permissions "read,update,share"
don't rely on `welcome.txt`

2021-04-01 05:01 UTC, individual-it commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +    And user "Alice" has shared file "welcome.txt" with group "grp1" with permissions "share,read"
don't rely on `welcome.txt`

2021-04-01 08:43 UTC, kiranparajuli589 commented
@artur changes have been made. please review again.

2021-04-01 09:14 UTC, individual-it commented
tests still failing :-(

2021-04-01 09:39 UTC, kiranparajuli589 commented
> tests still failing :-(

phpstan failed 🤕 
restarted

2021-04-01 09:47 UTC, individual-it approved these changes

2021-04-06 04:05 UTC, merged