[tests-only] prepare required resources rather than using skeleton directories in API WebDav move, operations and preview features
owncloud/core pull request #38569
Opened 2021-03-23 04:38 UTC by kiranparajuli589

## Description
With this PR:
- skeleton file/folders are used more wisely on the following features suite
  - apiWebdavMove1
  - apiWebdavMove2
  - apiWebdavOperations
  - apiWebdavPreviews

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-03-24 02:41 UTC, dpakach reviewed
lgtm :+1:

2021-03-24 09:18 UTC, individual-it requested changes

2021-03-24 09:18 UTC, individual-it commented on tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
> +
extra line

2021-03-24 09:18 UTC, individual-it commented on tests/acceptance/features/apiWebdavOperations/search.feature
> -      | /FOLDER                  |
lets create `FOLDER` also, that is a good test when searching for `ol`

2021-03-25 05:26 UTC, jasson99 reviewed
LGTM

2021-03-26 08:51 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavOperations/search.feature
> -      | /FOLDER                  |
okay!

2021-03-26 08:55 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
> +
removed!

2021-03-26 09:34 UTC, individual-it approved these changes

2021-03-29 10:27 UTC, merged