Translation in the activity stream for shares which expired automatically
owncloud/core pull request #38631
Opened 2021-04-09 09:30 UTC by JammingBen

## Description
Add a proper translation in the activity stream for shares which expired automatically. Previous to this, the expiry was authored by a user, which is technically not true.

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/4455

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/50302941/114160225-fd280f00-9926-11eb-9e87-e0a27b312d19.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-04-09 11:09 UTC, JanAckermann approved these changes

2021-04-09 12:22 UTC, jvillafanez commented
I'm not sure if this is right. Technically, the agent is like a virtual user that performs the action on behalf of another user.

Having a "share_expire_author" doesn't fit here. What if there are more actions triggered during the share expiration? They could have the "share_expire_author" for a delete file action, which seems weird. Also note that whoever is listening for the delete file event won't likely take into account a "share_expire_author" agent, or won't receive any special treatment.

I'd prefer to reuse the "automation_author" in this case and try to figure out if the share has expired in a different way. A "cli_author" seems to generic for this case, but we could use a different author.
The question is who performs the share expiration **and any other related action** that could happen during that time.

2021-04-09 12:28 UTC, jvillafanez commented on apps/files_sharing/lib/ExpireSharesJob.php
> +		\OCP\Activity\IManager $activityManager
I'm not sure if there is any advantage in using this instead of `use OCP\Activity\IManager as ActivityManager` along with the rest of the "use" statements. I'd prefer the later since all the "use" statements are close to each other.

2021-04-09 12:28 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +			\OCP\Activity\IManager $activityManager,
same here

2021-04-09 13:30 UTC, JammingBen commented
@jvillafanez 

> I'd prefer to reuse the "automation_author" in this case and try to figure out if the share has expired in a different way.

What do you think of expanding the event parameters here by `shareExpired`: https://github.com/owncloud/core/blob/4d11dd4524ca25cf7f92a5002fb9be758248238f/lib/private/Share20/Manager.php#L1098. This way we could use this information in the activity app and add it as param. The author could be `automation_author` then.

2021-04-09 13:38 UTC, jvillafanez commented
That's fine

2021-04-12 09:15 UTC, JanAckermann requested changes

2021-04-12 09:15 UTC, JanAckermann commented on apps/files_sharing/lib/ExpireSharesJob.php
> +		$this->setInterval(5);
WHOOOOPS

2021-04-12 09:16 UTC, JammingBen commented on apps/files_sharing/lib/ExpireSharesJob.php
> +		$this->setInterval(5);
Dammit!

2021-04-12 09:18 UTC, JanAckermann requested changes

2021-04-12 09:18 UTC, JanAckermann commented on changelog/unreleased/38631
> +Add a proper translation in the activity stream for shares which expired automatically.
```suggestion
Add a proper message in the activity stream for shares which expired automatically.
```

2021-04-12 09:18 UTC, JanAckermann commented on lib/private/Share20/Manager.php
> +	private static function shareHasExpired($share) {
Why this needs to be a static ?

2021-04-12 09:22 UTC, JammingBen commented on lib/private/Share20/Manager.php
> +	private static function shareHasExpired($share) {
Because we need to call it in `static function formatUnshareHookParams()`. So either make that one non-static, or make `shareHasExpired()` static. I went for the latter because it has no connection to the class instance however.

2021-04-12 09:41 UTC, JammingBen commented
@jvillafanez I implemented it the way you suggested. Some changes are required in the activity app for this, see https://github.com/owncloud/activity/pull/944. We basically now use the automation author and the `shareExpired` param to indicate if a share expired.

2021-04-12 09:44 UTC, JanAckermann approved these changes

2021-04-12 11:53 UTC, jvillafanez approved these changes

2021-04-12 13:02 UTC, merged