[tests-only] created resources rather than using skeleton dirs with users in webUI suites
owncloud/core pull request #38635
Opened 2021-04-13 03:27 UTC by kiranparajuli589

… suites

## Description
created resources rather than using skeleton dirs with users in webUI suites

## Related Issue

- Part of https://github.com/owncloud/QA/issues/658

## Motivation and Context

## How Has This Been Tested?

- 🤖 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-04-13 04:26 UTC, saw-jan commented on tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
> +
extra line?

2021-04-13 04:29 UTC, saw-jan commented on tests/acceptance/features/webUIFavorites/favoritesFile.feature
> +    And user "Alice" has created folder "strängé नेपाली folder"
you can make use of this step
```
Given user "Alice" has created the following folders
      | path         |
```

2021-04-13 07:21 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFavorites/favoritesFile.feature
> +    And user "Alice" has created folder "strängé नेपाली folder"
nice.... I've used that! have a look again!

2021-04-13 07:31 UTC, Talank reviewed
LGTM

2021-04-13 08:24 UTC, saw-jan commented on tests/acceptance/features/webUIFavorites/favoritesFile.feature
> +      | strängé नेपाली folder             |
minor indentation to fix

2021-04-13 08:24 UTC, saw-jan commented on tests/acceptance/features/webUIFiles/search.feature
> +      | strängé नेपाली folder |
minor indentation to fix

2021-04-13 08:24 UTC, saw-jan commented on tests/acceptance/features/webUIFiles/search.feature
> +      | strängé नेपाली folder |
minor indentation to fix

2021-04-13 08:24 UTC, saw-jan commented on tests/acceptance/features/webUIFiles/search.feature
> +      | strängé नेपाली folder |
minor indentation to fix

2021-04-13 09:38 UTC, swoichha commented on tests/acceptance/features/webUIFavorites/favoritesFile.feature
> +      | simple-folder/simple-empty-folder |
Indentation

2021-04-13 09:48 UTC, swoichha requested changes

2021-04-13 09:48 UTC, swoichha commented on tests/acceptance/features/webUIFiles/search.feature
> +      | strängé नेपाली folder |  |
```suggestion
      | strängé नेपाली folder    | 
```

2021-04-13 09:48 UTC, swoichha commented on tests/acceptance/features/webUIFiles/search.feature
> +      | strängé नेपाली folder |  |
```suggestion
      | strängé नेपाली folder    | 
```

2021-04-13 09:48 UTC, swoichha commented on tests/acceptance/features/webUIFiles/search.feature
>      And the user reloads the current page of the webUI
```suggestion
    When the user reloads the current page of the webUI
```

2021-04-13 09:59 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFiles/search.feature
>      And the user reloads the current page of the webUI
its converted to given step. the scenario does not need sharing as a when step

2021-04-13 10:42 UTC, saw-jan commented on tests/acceptance/features/webUIFiles/search.feature
>      And the user reloads the current page of the webUI
she means this step `And the user reloads the current page of the webUI`

2021-04-13 10:58 UTC, swoichha commented on tests/acceptance/features/webUIFiles/search.feature
>      And the user reloads the current page of the webUI
Yes, @saw-jan is right. IMO the `And the user reloads the current page of the webUI` is the `When` step.

2021-04-15 04:19 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFiles/search.feature
>      And the user reloads the current page of the webUI
thank you for pointing. but it can go as a given step too..
fixed!

2021-04-15 04:26 UTC, saw-jan reviewed
LGTM :+1:

2021-04-15 04:44 UTC, individual-it requested changes

2021-04-15 04:44 UTC, individual-it commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "Alice" has uploaded file "filesForUpload/zzzz-must-be-last-file-in-folder.txt" to "strängé नेपाली folder/zzzz-must-be-last-file-in-folder.txt"
please create also a `lorem.txt` file to make sure the search algorithm works correctly. We check that lorem.txt is not viewed in the results, but if we don't have that file in the first place this test becomes irrelevant.
Please also double check other tests for the same issue

2021-04-15 05:56 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFiles/search.feature
> +    And user "Alice" has uploaded file "filesForUpload/zzzz-must-be-last-file-in-folder.txt" to "strängé नेपाली folder/zzzz-must-be-last-file-in-folder.txt"
fixed!

2021-04-15 06:10 UTC, individual-it commented on tests/acceptance/features/webUIFiles/search.feature
> +    Then file "strängéनेपालीloremfile.txt" should be listed on the webUI
why this change?

2021-04-15 06:25 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFiles/search.feature
> +    Then file "strängéनेपालीloremfile.txt" should be listed on the webUI
I was also confused by this. If I run the test with a large skeleton, the then step succeeds, but if I created the files, its failing
@individual-it do you see something missing here??

2021-04-15 06:55 UTC, swoichha approved these changes
LGTM

2021-04-15 07:11 UTC, kiranparajuli589 commented on tests/acceptance/features/webUIFiles/search.feature
> +    Then file "strängéनेपालीloremfile.txt" should be listed on the webUI
I've created an issue for this https://github.com/owncloud/core/issues/38641
Actually this test scenario should have reload after the files upload...so I've fixed the scenario. The scenario above `Search for a newly uploaded file` this demonstrates the bug issued.

2021-04-15 07:33 UTC, individual-it approved these changes

2021-04-15 10:44 UTC, merged