Trashbin skip list regex
owncloud/core pull request #38704
Opened 2021-05-06 12:57 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-05-06 13:36 UTC, JanAckermann commented
@jvillafanez even if this is files_trashbin I would love to save the settings in the config.php because it's hard to set arrays via occ config:app:set agree?

2021-05-11 07:25 UTC, jvillafanez commented
Just a couple of things so far:
* I'd move the checks to its own class. This way it's easier to add unit tests for this and it also keeps the code isolated.
* I'd try to avoid using regular expressions unless needed.
  * So far, the examples provided in the config.php are for extensions and files inside folders (basically, paths ending or starting with some chars). This can be done faster without regular expressions.
  * Regular expressions are error-prone. My concern here is that the admin could enter a "wrong" regular expression, such as `.*.png` which could affect to files the admin doesn't want to, such as `a_file.apng`. This simply cannot be detected.
  * Case insensitiveness seems a bad idea if it wasn't asked for explicitly. The config.php file doesn't say anything about this.
* Taking into account that we don't expect too many skips, we probably should include some logs at info level (warning might be too much) for tracing purposes.

2021-05-11 16:07 UTC, jvillafanez commented
I still think it's better to move the checks to a dedicated class. We'll need to add unit tests, and it should be easy to add them in a dedicated class. It should also be easier to include an initialization phase to clean the config input and make the actual action easier to read.
In addition, it might be better to split into multiple smaller functions in order to give meaningful names to the functions to make the code easier to follow.

Also note that there could be filenames with "*" in the path (I don't think we're doing anything special), so there could be a "*abc" folder in the root.

2021-05-12 06:53 UTC, jvillafanez commented
Note that we should include an option to skip the trashbin by filesize, which will probably be the main use case for this feature. Taking this into account, maybe having "trashbin.skip.extensions", "trashbin.skip.directories" and "trashbin.skip.sizes" as config options might be a better choice

2021-05-12 08:29 UTC, JanAckermann commented
@jvillafanez without the cool new wildcard logic ?

2021-05-12 08:52 UTC, jvillafanez commented
I think so. The code seems complex at first sight, probably because the PHP string functions aren't easy to handle, and it also has some edge cases we need to take care. I don't mind having the wildcard logic if it easy to follow though.
My concern is that a 3rd person might take 1-2 days trying to put a fix there successfully because every time he touches something he breaks another thing. If you're confident your code is fool-proof, go ahead.

2021-05-12 09:32 UTC, JanAckermann commented
@jvillafanez can you have a second look, this is not quite final, tests need to be added.

2021-05-12 09:36 UTC, phil-davis commented on .htaccess
> +ErrorDocument 404 //core/templates/404.php
This is an accident - need to remove

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +class SkipTrashbinManager {
I don't think "manager" is the right term here. Sounds like it should have CRUD operations somehow, which isn't the case. Maybe "TrahbinSkipper" or "TrashbinSkipChecker" is more meaningful as classname

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +	public function shouldSkipPath(string $path, string $mountPoint): bool {
It seems it should be asking for the full path. I don't think we need to split mount point + path.
Also "path" is quite generic: full path including uid, such as "/user1/files/folder/to/file.txt"? or FS path such as "/folder/to/file.txt"?  with or without leading "/"? You can describe the expectations in the PHPDoc so it's easier to know how we can use the function properly.

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +		$skipByDirectoriesConfigList = $this->config->getSystemValue('trashbin_skip_by_directories', []);
Should we use "trashbin.skip.directories" for the config key? Although there is no special meaning, the namespacing gives the similar properties a sense of togetherness.

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +				$this->logger->info("Path $path record exists in config value trashbin_skip_by_directories and will be deleted immediately");
Should we include in the log the rule that made the skip happen? It might give interesting information.

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +		$skipByDirectoriesListIncludesExtension = \in_array(\pathinfo($path, PATHINFO_EXTENSION), $skipByDirectoriesExtensionsConfigList);
I prefer to use strict checking in the `in_array` function (adding `true` as 3rd param).

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +		$skipByDirectoriesExtensionsConfigList = $this->config->getSystemValue('trashbin_skip_by_size', false);
`skipByDirectoriesExtensionsConfigList` is a wrong variable name to be used here.

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +		if ($filesize > $configComputerFilesize) {
I guess we don't want to consider skipping files with less than a specific size. It might have some usage if we consider files less than 100 bytes as useless or dummies which don't need to go to the trashbin. It's a weird use case, so I'm not going to push in this direction, but you can check with PM if there is any interest.

Anyway, I think this check should be `>=`. An exact filesize match shouldn't go to the trashbin I think.

2021-05-12 11:35 UTC, jvillafanez commented on apps/files_trashbin/lib/Storage.php
> +				$container->query('OCA\Files_Trashbin\SkipTrashbinManager')
`SkipTrashbinManager::class` is usually preferred

2021-05-12 11:35 UTC, jvillafanez commented on config/config.sample.php
> +'trashbin_skip_by_size' => "1GB",
It might be useful to know what units are available, and the specific format, if any.
Is it "1 GB" (with the space) allowed? What about "01GB"?

2021-05-12 11:49 UTC, jvillafanez commented
For the config.sample file, I prefer to use the default values if any. If it isn't possible (the defaults in this case will likely be empty lists, which doesn't add any value), some sane defaults is a better choice, so it's easy to copy and paste them. You might also want to clarify whether there is a default value in use or not (mainly to clarify that 1GB files will still reach the trashbin by default, for example). You can add additional examples in the comments to clarify things.
In this regard, you could include:
* for the extensions, the .exe files or .mkv might be more common choices.
* for the directories, I think our use case is the .snapshot folder. It's something we might need, so better to have it around
* for the filesize, 1GB seems reasonable. Depending on the usage, you might want to increase it to 5GB or 10GB

2021-05-12 12:43 UTC, JammingBen commented on apps/files_trashbin/lib/SkipTrashbinManager.php
> +		$skipByDirectoriesConfigList = $this->config->getSystemValue('trashbin_skip_by_directories', []);
Some trashbin-config-settings already exist, they all start with `trashbin_`. So I'd go with the same naming convention here to keep things consistent.

I removed the `_by_` though as it was kind of misleading.

2021-05-12 13:23 UTC, JammingBen commented
@jvillafanez I updated the PR with some general improvements and your suggestions. Also added tests for the new class. I'm not a 100% sure about the ´config.sample´ yet. At least it should now be more clear how to use these config params.

Thanks for your help here btw 👍

2021-05-12 14:33 UTC, jvillafanez commented on apps/files_trashbin/lib/Storage.php
> +			$app = new App('files_trashbin');
I'm very wary about creating a new app on our own. The app could register itself in some place and could cause problems with duplicated calls among other things.
For this case, I think it's better to create a new instance of the `TrashbinSkipChecker` directly. The dependencies can be picked up from the `\OC::$server` instance (it's already there for the userManager anyway)

You might also want to include a note in the `TrashbinSkipChecker` to warn that there are instances created without DI (in case that we add a new dependency and the code here doesn't yell)

2021-05-12 14:33 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$filesize = Filesystem::getView()->filesize($path);
Taking into account that the trashbin storage already uses a `View`, the `shouldSkipPath` could need the view as parameter. Something like `shouldSkipPath($view, $relativatePath)`. This has some advantages:
* No dependency with the `Filesystem`. Using a mock view in the tests is easier and reduce coupling.
* You don't need to ask whether the path is a folder or not. The view can take care of that. Method invocation is easier
* It's more natural to think that the relativePath required is based on the view

2021-05-12 14:40 UTC, jvillafanez commented
Warning messages seem harsh. I understand that we might want that message for the "skip directories" configuration as a deterrent, but the ones for the extension and file size... I expect the skip by file size to be widely used.

2021-05-14 14:26 UTC, JanAckermann commented
TBD: 
- [ ] Inform @mmattel to run config-to-docs-command for 10.8

2021-05-14 14:39 UTC, mmattel commented
@JanAckermann @jvillafanez 
Could you pls make in config.php each first line a brief description line as you can see in the other examples above or below.
The first line of a new config parameter is always taken as line for the table of contents. The lines below can be anything you like. See also the doc on the web how it renders.
I would like to avoid post merge corrections if possible 😃

2021-05-15 06:51 UTC, mmattel commented on config/config.sample.php
> + * Define a list of folders that will skip the trashbin and therefore be deleted immediately
```suggestion
  * Define trashbin skip folder list
  * Define a list of folders that will skip the trashbin and therefore be deleted immediately
```

2021-05-15 06:55 UTC, mmattel commented on config/config.sample.php
> + * Define a list of file extensions to determine files that will skip the trashbin and therefore be deleted immediately
```suggestion
  * Define trashbin file skip list
  * Define a list of file extensions to determine files that will skip the trashbin and therefore be deleted immediately
```

2021-05-15 06:57 UTC, mmattel commented on config/config.sample.php
> + * Define a threshold for files to skip the trashbin and delete immediately
```suggestion
  * Define trashbin threshold size
  * Define a threshold for files to skip the trashbin and delete immediately
```

2021-05-15 07:11 UTC, mmattel commented on config/config.sample.php
> +  * Define a list of folders that will skip the trashbin and therefore be deleted immediately
```suggestion
 * Define trashbin folder skip list
 * Define a list of folders that will skip the trashbin and therefore be deleted immediately
```

2021-05-15 07:12 UTC, mmattel commented on config/config.sample.php
> +  * Define a list of file extensions to determine files that will skip the trashbin and therefore be deleted immediately
```suggestion
 * Define trashbin file extension skip list
 * Define a list of file extensions to determine files that will skip the trashbin and therefore be deleted immediately
```

2021-05-15 07:12 UTC, mmattel commented on config/config.sample.php
> +  * Define a threshold for files to skip the trashbin and delete immediately
```suggestion
 * Define trashbin threshold size
 * Define a threshold for files to skip the trashbin and delete immediately
```

2021-05-15 07:14 UTC, mmattel commented
@JanAckermann sorry, my fault, there was a leading blank too much on each changed line, one is correct, two not. Fixed

2021-05-15 07:27 UTC, mmattel approved these changes
OK from config.php POV
Code not reviewed

2021-05-15 09:53 UTC, mmattel commented
@phil-davis info: drone is inaccessible which results in an unsuccessful check

2021-05-15 10:54 UTC, JanAckermann commented
@mmattel Thank you, not yet ready some minor code improvements needs to be done

2021-05-15 10:57 UTC, JanAckermann commented
@jvillafanez do you mean the warning messages in the config sample ?
```
 * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
 ```

Mabye @mmattel can suggest what we should shout here, because data loss could be possible...

2021-05-15 11:28 UTC, JanAckermann commented
@jvillafanez changed in favour of your suggestions

2021-05-15 12:07 UTC, JanAckermann commented
- [ ] Improve config sample @mmattel

2021-05-15 16:04 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
```suggestion
 * Define a list of folders that will skip the trashbin and therefore be deleted immediately.
 * Folder names are valid for all mount points, take care selecting the name.
 * Defined folder names can be in any location of the path and skip this folder from the trashbin.
 * All content of defined folders and their subfolders are affected.
 * Consider not using reserved folder names when using a storage system that provides snapshots.
 * It is not necessary to set a trailing slash, the folder name is enough.
 *
```

2021-05-15 16:09 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
```suggestion
 * Define trashbin directory skip list
 * Define a list of directories that will skip the trashbin and therefore be deleted immediately.
 * Directory names are valid for all mount points, take care selecting the name.
 * Defined directory names can be in any location of the path and skip this directory from the trashbin.
 * All content of defined directories and their subdirectories s are affected.
 * Consider not using reserved directory names when using a storage system that provides snapshots.
 * It is not necessary to set a trailing slash, the directory name is enough.
 *
```

2021-05-15 16:11 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
```suggestion
 * Define trashbin file extension skip list
 * Define a list of file extensions to determine files that will skip the trashbin and therefore be deleted immediately
 * Extension names are valid for all mount points, take care when selecting the names.
 * Values must not have a leading ".", otherwise corresponding files wont be detected.
 *
```

2021-05-15 16:16 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
```suggestion
 * Define trashbin threshold size
 * Define a threshold for files to skip the trashbin and delete immediately
 * Once the size of a resource is greater than or equal the given value, the trashbin will be skipped.
 * File sizes are valid for all mount points, take care when defining the threshold.
 *
 * All positive numbers and zero is allowed. Append one of the following options directly and without space:
 * B, K, KB, MB, M, GB, G, TB, T, PB, P
 *
```
> and zero is allowed

means, you can not have a zero length file = no file at all (but directories only) ... hmmm ... does this make sense?

2021-05-17 06:56 UTC, jvillafanez requested changes
the .htaccess file shouldn't be modified.

2021-05-17 06:56 UTC, jvillafanez commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
I don't think the changes in this file are needed.

2021-05-17 06:56 UTC, jvillafanez commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
@JanAckermann could you double-check with ".tar.gz" or ".tar.bz2" files? I'm not sure how it will be handled. I guess the expectation is to use those extensions, so if it isn't possible we should document it.

2021-05-17 07:25 UTC, mmattel commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$skipFile = \in_array(\pathinfo($relativePath, PATHINFO_EXTENSION), $fileExtensionsToSkip, true);
Referring to comments from @jvillafanez 
https://github.com/owncloud/core/pull/38704#discussion_r633266666
https://github.com/owncloud/core/pull/38704#discussion_r633266666

This will definitely not catch `.tar.gz`
Also noted in https://www.php.net/manual/en/function.pathinfo.php

You need to extract the `basename` from `$relativePath` and use `strstr — Find the first occurrence of a string` on the basename to catch extensions starting with a dot at the first occurrence in the basename. Then you catch `.mkv` and `.tar.gz`

I would NOT propose to exclude an extension like `.tar.gz` but adopting the code to make it work.

2021-05-17 07:53 UTC, JanAckermann commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$skipFile = \in_array(\pathinfo($relativePath, PATHINFO_EXTENSION), $fileExtensionsToSkip, true);
@mmattel @jvillafanez I am not quite sure if we can really catch this, dot separation in file names are not always extensions.
If we follow the mentioned example, a file named '2021.07.01.jpg' would give us the file extension: 07.01.jpg.

This would mean, that our config wouldn't have any effect here

```'trashbin_skip_extensions' => [
	'jpg'
]```

2021-05-17 08:06 UTC, JanAckermann commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
> Defined directory names can be in any location of the path and will be skipped from the trashbin.
This is not quite true, we do an exact match here inside the files path

2021-05-17 09:04 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$skipFile = \in_array(\pathinfo($relativePath, PATHINFO_EXTENSION), $fileExtensionsToSkip, true);
What about something like "endsWith", with a leading "."?
By putting "jpg" we'd match files which end with ".jpg", and by putting "tar.bz2" we'd match files ending with ".tar.bz2". We could also match something like ".01.jpg" or ".myfile.gz", which we could consider as extensions although they aren't. It should be acceptable.
We'd need to take care about ".jpg" file (exact match), but it should be easy.

2021-05-17 09:12 UTC, mmattel commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$skipFile = \in_array(\pathinfo($relativePath, PATHINFO_EXTENSION), $fileExtensionsToSkip, true);
You are right,
`2021.07.01.tar.gz.` --> `07.01.tar.gz.`
But this would be eliminated when using:
`str_ends_with ( string $haystack , string $needle )`
or?

2021-05-17 09:23 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
I fixed the suggestion and changed the text accordingly

2021-05-17 09:36 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +		$skipFile = \in_array(\pathinfo($relativePath, PATHINFO_EXTENSION), $fileExtensionsToSkip, true);
For our case, it would be removed, yes. However, anyone could create an app which uses "07.01.tar.gz" as extension. Anyway, the setting will be set by the admin, and he won't set that kind of extension.
Although not technically correct, if it helps to simplify the code, I think the solution is good enough.

2021-05-17 09:50 UTC, jvillafanez commented on config/config.sample.php
> + * All positive numbers and zero is allowed. Append one of the following options directly and without space:
Did you check with negative values?
I think the code still works and it will cause the trashbin to skip all the files. We probably should clarify what happens because the admin could think that a negative value will disable the feature, which means that all files should go to the trashbin and won't be removed directly.
As long as it's documented, I'm ok with removing the files directly (no code changes)

2021-05-17 09:56 UTC, jvillafanez commented on apps/files_trashbin/tests/TrashbinSkipCheckerTest.php
> +		Filesystem::mkdir($folder);
Better use a mock view not to rely on static calls.

2021-05-17 09:57 UTC, JanAckermann commented on config/config.sample.php
> + * All positive numbers and zero is allowed. Append one of the following options directly and without space:
To be honest, I would love to have a validator here, what do you think?

2021-05-17 09:58 UTC, jvillafanez commented
I think those will be the last changes for me.

2021-05-17 10:05 UTC, JanAckermann commented on apps/files_trashbin/tests/TrashbinSkipCheckerTest.php
> +		Filesystem::mkdir($folder);
> Also check other calls to the Filesystem class in the tests.
Which ones?

2021-05-17 10:41 UTC, jvillafanez commented on config/config.sample.php
> + * All positive numbers and zero is allowed. Append one of the following options directly and without space:
Up to you.

2021-05-17 10:43 UTC, jvillafanez commented on apps/files_trashbin/tests/TrashbinSkipCheckerTest.php
> +		$view->file_put_contents($folder . '/somefile.pdf', 'file1');
neither the `mkdir` nor the `file_put_contents` methods should be needed now.

2021-05-17 10:44 UTC, JanAckermann commented on apps/files_trashbin/tests/TrashbinSkipCheckerTest.php
> +		$view->file_put_contents($folder . '/somefile.pdf', 'file1');
what do we use instead?

2021-05-17 10:47 UTC, JanAckermann commented on config/config.sample.php
> + * All positive numbers and zero is allowed. Append one of the following options directly and without space:
@jvillafanez would love to comeup with symfony/validator here (and for the future)... Any objections ?

2021-05-17 10:58 UTC, jvillafanez commented on apps/files_trashbin/tests/TrashbinSkipCheckerTest.php
> +		$view->file_put_contents($folder . '/somefile.pdf', 'file1');
the method to be tested will use the mock view, so just configure the mock as you need. In fact, those methods shouldn't be doing anything.

2021-05-17 11:02 UTC, jvillafanez commented on config/config.sample.php
> + * All positive numbers and zero is allowed. Append one of the following options directly and without space:
It seems too complex... you're already using the `computerFileSize` method, so it should be returning a negative value if the size is negative. You can just check for that.

2021-05-17 11:06 UTC, mmattel commented on config/config.sample.php
> +any subdirectores. Take care when selecting the names.
```suggestion
 * Extension names are valid for all mount points, take care when selecting the names.
```

2021-05-17 11:09 UTC, mmattel commented on config/config.sample.php
> +any subdirectores. Take care when selecting the names.
```suggestion
```

2021-05-17 11:20 UTC, mmattel commented on config/config.sample.php
> + * WARNING: THIS SETTING IS SYSTEM WIDE AND COULD CAUSE DATA LOSS. USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
```suggestion
 * Define trashbin directory skip list
 * Define a list of directories that will skip the trashbin and therefore be deleted immediately.
 * Only defined directories and only in the root of a mount will skip for the trashbin. 
 * The setting expects folder names with or without trailing slash.
 * All the content inside such directories will also skip the trashbin.
 *
```

2021-05-17 11:32 UTC, mmattel commented
For some strange reasons, already committed text suggestions for config.php got corrupted.
For one smaller corruption, I changed the bad line and committed it directly.
The other reconstructed suggestion is multi line and I would like to get another eye on @JanAckermann

2021-05-17 14:24 UTC, mmattel commented
@jvillafanez 
> the .htaccess file shouldn't be modified.

This has been fixed by @JanAckermann, no changes in the file.
Pls re-review/approve.

2021-05-18 06:41 UTC, mmattel approved these changes
OK from the config.php POV
Code not tested

2021-05-18 06:52 UTC, jvillafanez approved these changes
Tiny detail, maybe for the next time.

2021-05-18 06:52 UTC, jvillafanez commented on apps/files_trashbin/lib/TrashbinSkipChecker.php
> +			return  false;
Double space

2021-05-18 08:21 UTC, merged