improve-public-share-interface
owncloud/core pull request #38712
Opened 2021-05-07 10:33 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-05-08 11:42 UTC, JanAckermann commented
TODO:
* Create Docs issue if needed
* Remove old code
* Fix remote without http/https

2021-05-09 16:35 UTC, JanAckermann commented
@JammingBen pre-review is welcome :rabbit:

2021-05-10 07:22 UTC, JammingBen commented on apps/files_sharing/js/public.js
> +			if(!loading){
It should be `if(loading) {}` here, shouldn't it?

2021-05-10 07:23 UTC, JanAckermann commented on apps/files_sharing/js/public.js
> +			if(!loading){
no, why?

2021-05-10 07:37 UTC, JammingBen commented on apps/files_sharing/js/public.js
> +			if(!loading){
Because the next line indicates loading: `that.$saveToOcButton.html(t('files_sharing', 'Loading...') + '<img id="save-to-oc-button-loading" src="'+ OC.imagePath('core', 'loading-small.gif') + '">');`. So I expect `loading` to be true. Maybe I'm just confused about the variable naming 😄  It's meant to be something like `isLoaded` then?

2021-05-10 07:54 UTC, JanAckermann commented on apps/files_sharing/js/public.js
> +			if(!loading){
if it is not loading we add a loading indicator, I don't get it :D

2021-05-11 07:41 UTC, JanAckermann commented
@phil-davis Patrick told me that, you are a quite good text reviewer, can you look at the texts for the oc.dialogs.drop maybe :) ?

2021-05-19 09:07 UTC, VicDeo requested changes
Cool improvement but it need to respect the setups where OC is located in the subfolder of the server webroot:
1. Install OC into `localhost/owncloud`
2. Create a public folder share
3. Open it as a guest user
4. Click 'Add to localhost'

### Expected
login screen

### Actual 
404
 as it requests 
http://localhost/index.php/apps/files#  instead of
http://localhost/owncloud/index.php/apps/files#

2021-05-19 09:51 UTC, JanAckermann commented
@VicDeo good catch, thx!

2021-05-19 11:03 UTC, VicDeo commented on .htaccess
> +ErrorDocument 403 //core/templates/403.php
@JanAckermann accidental commit?

2021-05-19 12:07 UTC, JanAckermann commented on .htaccess
> +ErrorDocument 403 //core/templates/403.php
Yep :/

2021-05-19 13:58 UTC, VicDeo approved these changes

2021-05-19 13:59 UTC, merged