Add user profile picture boolean to capabilities
owncloud/core pull request #38722
Opened 2021-05-10 11:24 UTC by pascalwengerter

## Description
Adds another boolean to the capabilities

## Related Issue
- Fixes #38708

## Motivation and Context
Needed for the new web frontend to know whether to fetch&render avatar profile pictures

Please review with care, I'm not a PHP dev!

2021-05-10 11:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38722) it.</sub>

2021-05-10 12:29 UTC, phil-davis commented
We usually add new capabilites to https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiCapabilities/capabilities.feature test scenarios, similar to the way it is done at line 107.

Do you want me to add?

2021-05-10 14:23 UTC, pascalwengerter commented
:x

> We usually add new capabilites to https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiCapabilities/capabilities.feature test scenarios, similar to the way it is done at line 107.
> 
> Do you want me to add?

Great idea @phil-davis , please go ahead and do so (this will also restart the pipeline which should actually pass, timed out on the last run)

2021-05-11 10:33 UTC, pascalwengerter commented on tests/acceptance/features/apiCapabilities/capabilities.feature
> +      | files_sharing | user@@@profile_picture | 1     |
Yeah, we initially checked in the oCIS capabilities and `core` didn't feel right since it was very basic and generic settings, while there's already `user` in the `files_sharing` capabilities (and profile pictures are mostly used in the file context, plus capabilities are available through the web runtime anyways). I'd merge this now as respective changes in reva/oCIS have been merged already...

2021-05-11 10:50 UTC, JammingBen requested changes
LGTM code-wise 👍  Just the PR-link in the changelog

2021-05-11 10:50 UTC, JammingBen commented on changelog/unreleased/38721
> +https://github.com/owncloud/core/pull/38721
```suggestion
https://github.com/owncloud/core/pull/38722
```

2021-05-11 11:25 UTC, phil-davis commented on changelog/unreleased/38721
> +https://github.com/owncloud/core/pull/38721
I updated the PR link, name of the file and text.

2021-05-11 11:37 UTC, JammingBen approved these changes

2021-05-11 11:44 UTC, phil-davis approved these changes

2021-05-11 12:40 UTC, merged