[Tests-Only] tests modified according to ocis responses
owncloud/core pull request #38744
Opened 2021-05-18 15:50 UTC by kiranparajuli589

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-05-21 07:14 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavPreviews/previews.feature
> +  Scenario Outline: download different sizes of previews of file on ocis
https://github.com/owncloud/ocis/issues/188#issuecomment-816570583
> In `oCIS`,  we currently take the larger of the two dimensions and recalculate the smaller dimension to match the original aspect ratio.

2021-05-25 05:27 UTC, Talank reviewed
Looks good.

2021-05-25 07:45 UTC, dpakach reviewed
looks good. If you add new tests at the bottom of the file, you wont have to change as many lines in the expected failures file.

2021-05-25 09:50 UTC, individual-it requested changes
please use general `skipOnOcis` tag for tests that should not run on ocis, no need to mention every storage separately
And tests that are specific for ocis, should be placed in the ocis repo

2021-05-25 12:49 UTC, kiranparajuli589 commented
Specific `ocis` related tests moved using https://github.com/owncloud/ocis/pull/2075/files

2021-05-26 02:51 UTC, individual-it requested changes

2021-05-26 02:51 UTC, individual-it commented on tests/acceptance/features/apiWebdavPreviews/previews.feature
> +  @issue-2069 @skipOnOcis
```suggestion
  @issue-ocis-2069 @skipOnOcis
```

2021-05-26 04:53 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavPreviews/previews.feature
> +  @issue-2069 @skipOnOcis
fixed

2021-05-26 07:46 UTC, individual-it approved these changes

2021-05-26 09:38 UTC, merged