[Tests-Only] add api tests for accessing shares by id
owncloud/core pull request #38757
Opened 2021-05-20 08:00 UTC by dpakach

## Description

Add API tests for accessing shares by using share id, accepting and declining them.

## Related Issue

- Related https://github.com/owncloud/ocis/issues/2059
## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-05-20 11:12 UTC, Talank reviewed
Fix consecutive givens and whens

2021-05-20 11:12 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    Given using OCS API version "<ocs_api_version>"
2 consecutive givens
```suggestion
    And using OCS API version "<ocs_api_version>"
```

2021-05-20 11:12 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    Given using OCS API version "<ocs_api_version>"
2 consecutive givens

```suggestion
    And using OCS API version "<ocs_api_version>"
```

2021-05-20 11:12 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    When user "Brian" accepts share with ID "%last_share_id%" using the sharing API
2 consecutive when
```suggestion
    And user "Brian" accepts share with ID "%last_share_id%" using the sharing API
```

2021-05-20 11:12 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToRoot/shareAccessByID.feature
> +    When user "Brian" declines share with ID "%last_share_id%" using the sharing API
2 consecutive when
```suggestion
    And user "Brian" declines share with ID "%last_share_id%" using the sharing API
```

2021-05-20 11:12 UTC, Talank commented on tests/acceptance/features/apiShareOperationsToRoot/shareAccessByID.feature
> +    When user "Brian" accepts share with ID "%last_share_id%" using the sharing API
```suggestion
    And user "Brian" accepts share with ID "%last_share_id%" using the sharing API
```

2021-05-20 11:50 UTC, jasson99 commented on tests/acceptance/features/apiShareOperationsToRoot/shareAccessByID.feature
> +    Given using OCS API version "<ocs_api_version>"
```suggestion
    And using OCS API version "<ocs_api_version>"
```

2021-05-20 11:50 UTC, jasson99 commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    And user "Brian" has accepted share "/textfile0.txt" offered by user "Alice"
If this is a when step, make it something like
```suggestion
    And user "Brian" accepts share "/textfile0.txt" offered by user "Alice"
```

2021-05-20 11:50 UTC, jasson99 commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    And user "Alice" gets share with id "<share_id>" using the sharing API
```suggestion
    When user "Alice" gets share with id "<share_id>" using the sharing API
```

2021-05-20 11:50 UTC, jasson99 commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    And user "Brian" has accepted share "/textfile0.txt" offered by user "Alice"
Or these can be given step

2021-05-20 11:54 UTC, saw-jan commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    And user "Brian" has accepted share "/textfile0.txt" offered by user "Alice"
```suggestion
    And user "Brian" accepts share "/textfile0.txt" offered by user "Alice" using the sharing API
```
We also have this step which grammarly fits here

2021-05-20 11:54 UTC, saw-jan reviewed
We also have this step which grammarly fits here

2021-05-21 10:37 UTC, saw-jan reviewed
LGTM

2021-05-21 10:41 UTC, Talank reviewed
LGTM

2021-05-21 11:28 UTC, jasson99 reviewed
LGTM. I think we have been leaving 2 lines between each scenario. Implementing the same style would make our work more uniform, I think.

2021-05-24 03:21 UTC, individual-it requested changes

2021-05-24 03:21 UTC, individual-it commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +      | 2               | $#@r3      | 404             |
please add `0` and a complete empty id
same in other examples

2021-05-24 03:21 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +			return null;
I think I would prefer to throw an error here, because otherwise we would not notice if no id was found

2021-05-26 05:45 UTC, dpakach commented on tests/acceptance/features/bootstrap/Sharing.php
> +			return null;
I don't think we can do that because this function is currently used by `substituteInlineCodes`, which checks if a function returns the value or null and returns the original if null is returned.
Furthermore, the function signature states that it returns `string|null` so the consumers should check themself if the returned value is null and handle the error accordingly.

2021-05-26 07:09 UTC, individual-it approved these changes

2021-05-26 08:00 UTC, merged

2021-05-27 03:16 UTC, phil-davis commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +    And user "Alice" gets share with id "<share_id>" using the sharing API
See #38781

2021-05-27 03:16 UTC, phil-davis commented on tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
> +      | 2               | $#@r3      | 404             |
See #38781