Add action to resend the invitation email for a user
owncloud/core pull request #38774
Opened 2021-05-25 10:19 UTC by JammingBen

## Description
This only goes for users which have not been logged in yet.

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/4577#event-4791370289

## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/50302941/119481754-5c18da80-bd53-11eb-9d48-9cb00e503705.png)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-05-25 10:33 UTC, JanAckermann commented
@phil-davis @JammingBen acceptance tests needed ?

2021-05-25 12:45 UTC, phil-davis commented
> @phil-davis @JammingBen acceptance tests needed ?

We have existing test scenarios like: https://github.com/owncloud/enterprise/issues/4454
```
  Scenario Outline: user sets his own password after being created with an Email address only
    When the administrator creates a user with the name "<username>" and the email "guiusr1@owncloud" without a password using the webUI
    And the administrator logs out of the webUI
    And the user follows the password set link received by "guiusr1@owncloud" using the webUI
    And the user sets the password to "%regular%" and confirms with the same password using the webUI
    Then the user should be redirected to the login page
    And the email address "guiusr1@owncloud" should have received an email with the body containing
      """
      Password changed successfully
      """
    When the user logs in with username "<username>" and password "%regular%" using the webUI
    Then the user should be redirected to a webUI page with the title "Files - %productname%"
    Examples:
      | username | comment               |
      | guiusr1  | simple user-name      |
      | a@-+_.'b | complicated user-name |
```

We could add a scenario where the user "forgets" and the email needs to be sent again.

It will need some additions to the page object for the users page, so that the test can find where to click to re-send the email. Who should do that? (I can get someone to look at it tomorrow, if you like)

2021-05-25 12:53 UTC, JammingBen commented
> It will need some additions to the page object for the users page, so that the test can find where to click to re-send the email. Who should do that? (I can get someone to look at it tomorrow, if you like)

We take care 👍

2021-05-25 12:59 UTC, ChrisEdS commented
Will this action only be showed when the user was invited via email initially?

2021-05-25 13:33 UTC, JanAckermann commented
> Will this action only be showed when the user was invited via email initially?
Nope

2021-05-25 13:50 UTC, JanAckermann commented on tests/acceptance/features/webUIAddUsers/addUsers.feature
> +  @smokeTest @skipOnLDAP @skipOnOcV10.3
@phil-davis should we change the @skipOnOCV part?

2021-05-25 13:56 UTC, phil-davis commented on tests/acceptance/features/webUIAddUsers/addUsers.feature
> +  @smokeTest @skipOnLDAP @skipOnOcV10.3
```suggestion
  @smokeTest @skipOnLDAP @skipOnOcV10.6 @skipOnOcV10.7
```

Yes. This test will only pass on 10.8 (current master). So skip on recent releases that we care to test against (some oC10 apps test against latest and one earlier release)

2021-05-25 13:56 UTC, phil-davis commented on tests/acceptance/features/webUIAddUsers/addUsers.feature
> +    And the user follows the password set link received by "guiusr1@owncloud" using the webUI
There should now be 2 emails waiting. Probably this scenario is going to pass even if the "resend click" does not work.
Maybe we can add a step that specifically follows the second link:
```suggestion
    And the user follows the second password set link received by "guiusr1@owncloud" using the webUI
```
The code for that step can specifically check that there are 2 emails, and then use the 2nd email.

2021-05-25 15:08 UTC, JanAckermann commented
@phil-davis now we also cover, that the first link have an expired/invalid token. Thanks for the hint!

2021-05-25 15:42 UTC, phil-davis approved these changes
LGTM

2021-05-26 06:56 UTC, jvillafanez commented
Maybe a designer should check the icon. It isn't crystal clear to me that you'll send an email. The color is also different from the trashbin icon.

2021-05-26 06:56 UTC, jvillafanez approved these changes
Code looks good

2021-05-26 06:59 UTC, JanAckermann commented
@jvillafanez  there is a gray icon available, will have a look. In general NC has the same Icon, I am OK with it.

2021-05-26 07:34 UTC, JanAckermann requested changes
- [ ] Add title attribute for tooltip
- [x] Make icon look similar to delete

2021-05-26 07:39 UTC, AlexAndBear approved these changes

2021-05-26 09:29 UTC, mmattel commented
Maybe stupid but why not in addition a occ command set where you can trigger to resend an invite to either a named or all never logged in like:
```
occ resend-invite:list
occ resend-invite:send --all
occ resend-invite:send <name>
```

2021-05-26 10:01 UTC, JammingBen commented
> Maybe stupid but why not in addition a occ command set where you can trigger to resend an invite to either a named or all never logged in like:

I personally find it more intuitive via WebUI. The admin creates users via UI, therefore it makes sense to place this action there, too. These commands could be a nice addition though.

2021-05-26 10:31 UTC, JanAckermann commented
@mmattel can you point out a real-world use-case for the command?

2021-05-26 11:17 UTC, phil-davis commented
Note: IMO `occ user:add` does not currently have the ability to specify just the email address, and have an invitation email sent to the new user. It seems to always want a password. So maybe there are no admins currently using the command line to create users in this way.

2021-05-26 12:29 UTC, merged