[Tests-Only]earlyFail
owncloud/core pull request #38789
Opened 2021-05-28 08:36 UTC by jasson99

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-06-02 06:49 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 07:10 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 07:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38789) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jasson99<br/>:x: xoxys<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38789) it.</sub>

2021-06-02 08:01 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-6-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 08:02 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-8-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 08:02 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-7-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 08:02 UTC, xoxys commented
<details><summary>:boom: Acceptance tests <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 08:03 UTC, xoxys commented
@jasson99 please stop pushing to this pr

2021-06-02 13:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-02 13:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiProvisioningGroups-v1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiSharingNotificationsToRoot-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIUpload-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIProxySmoke-3-2-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFfSmoke-3-2-firefox-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-6-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiProxySmoke-8-4-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-04 08:54 UTC, dpakach requested changes, later dismissed

2021-06-04 08:54 UTC, dpakach commented on .drone.star
> +        }]
this is not necessary
```suggestion
    else:
        return []
```

2021-06-04 08:54 UTC, dpakach commented on .drone.star
> +        }]
```suggestion
        return []
```

2021-06-04 08:54 UTC, dpakach commented on .drone.star
> +        }]
```suggestion
        return []
```

2021-06-04 08:59 UTC, jasson99 commented on .drone.star
> +        }]
fixed

2021-06-04 08:59 UTC, jasson99 commented on .drone.star
> +        }]
fixed

2021-06-04 08:59 UTC, jasson99 commented on .drone.star
> +        }]
fixed

2021-06-08 11:01 UTC, dpakach reviewed
looks good 👍🏼 
It would be better if phpunit failure would also trigger early fail, but maybe we can do that in other PR

2021-06-08 11:14 UTC, phil-davis approved these changes
LGTM - let's merge this. Then we can do the next parts.

2021-06-08 11:15 UTC, merged

2021-06-08 11:19 UTC, phil-davis commented
@jasson99 I commented in the issue: https://github.com/owncloud/QA/issues/672#issuecomment-856676732

We also want to disable `earlyFail` if the PR title contains `full-ci`. So that is the next thing to do here.