Report 23:59 in share expiration
owncloud/core pull request #38813
Opened 2021-06-07 14:32 UTC by phil-davis

## Description

## Related Issue
- Fixes <issue_link>

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-06-07 16:04 UTC, phil-davis commented
@micbar what is the requirement for external behavior for reporting the expiration date-time of a share?

2021-06-08 07:40 UTC, phil-davis commented
@TheOneRing one of the questions is: do the clients care if the expiration of a share has a date and then time of `23:59:00` rather than `00:00:00`?

And the other question could be: What benefit might there be to the expiration in a share response having time `23:59:00`?

2021-06-08 09:00 UTC, phil-davis commented
Yes, IMO all the current clients only set/display share expiration down to the day. They have no display of the expiration time within a day. So, if a PR like this goes ahead, we just need to double-check in QA that each client (desktop, iOS, Android) copes OK  with the expiration time set to `23:59:00` (i.e. no observable difference to now). The traditional webUI is fine - CI passes here.

2021-06-08 09:21 UTC, micbar commented
I did another deep thinking here.

IMO it is totally fine if the api doesn't report the time, only the day.

But in the best practise for API stability, changing this is not possible without a new API version.

It is bad, that `<expiration>2021-06-22 00:00:00</expiration>` implicitly means `<expiration>2021-06-23 00:00:00</expiration>`

If we are strict here, we should not change it regardless of the fact that it is just wrong.

2021-06-08 09:23 UTC, micbar commented
@michaelstingl @dragotin @butonic This is so "broken"

The bad thing about this is, we need to keep the APIs for oCIS "bug" compatible.

2021-06-08 16:57 UTC, phil-davis commented
> IMO it is totally fine if the api doesn't report the time, only the day.

PR #38817 demonstrates not reporting the time at all. Nothing breaks in the webUI, API tests pass with the expected difference. It would be easy enough to check that the other clients behave OK when the time is left out. So that is a possible thing to do.

And it is possible to just do nothing :)

2021-06-09 15:53 UTC, michaelstingl commented
> It would be easy enough to check that the other clients behave OK when the time is left out.

@jesmrec @gabi18 can we validate this in the next desktop and mobile releases?

2021-06-10 07:56 UTC, JanAckermann approved these changes

2021-06-10 07:56 UTC, JanAckermann commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
Maybe we call it time instead of timeOffset ?

2021-06-10 07:58 UTC, JanAckermann commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
and maybe we should make use of 23:59:59 which represents EOD a bit more

2021-06-10 08:05 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
Agree. 23:59:59 is as close as we can go to end-of-day.
First, someone needs to decide if we do this at all, or we remove the time completely - demonstrated in #38817

2021-06-10 08:08 UTC, JanAckermann commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
Ok, I'll move it to needs info then, so it will get recognized again ;)

2021-06-14 07:45 UTC, micbar approved these changes

2021-06-14 07:45 UTC, JanAckermann requested changes

2021-06-14 07:45 UTC, JanAckermann commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +			$result['expiration'] = $expiration->format('Y-m-d 23:59:00');
```suggestion
			$result['expiration'] = $expiration->format('Y-m-d 23:59:59');
```

2021-06-14 07:45 UTC, JanAckermann commented on apps/files_sharing/tests/ApiTest.php
> +		$this->assertEquals($date->format('Y-m-d') . ' 23:59:00', $data['expiration']);
```suggestion
		$this->assertEquals($date->format('Y-m-d') . ' 23:59:59', $data['expiration']);
```

2021-06-14 07:45 UTC, JanAckermann commented on apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
> +			'expiration' => '2000-01-02 23:59:00',
```suggestion
			'expiration' => '2000-01-02 23:59:59',
```

2021-06-14 07:45 UTC, JanAckermann commented on apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
> +				'expiration' => '2001-01-02 23:59:00',
```suggestion
				'expiration' => '2001-01-02 23:59:59',
```

2021-06-14 07:45 UTC, JanAckermann commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
```suggestion
				$timeOffset = "23:59:59";
```

2021-06-14 07:53 UTC, JanAckermann commented
Changelog needs to be provided, as it says in the todos :)

2021-06-14 07:54 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +				$timeOffset = "23:59:00";
expiration time is now reported as 23:59:59

2021-06-14 07:55 UTC, phil-davis commented on tests/acceptance/features/bootstrap/Sharing.php
> +				// responses indicate this by including a time of 23:59:00
```suggestion
				// responses indicate this by including a time of 23:59:59
```

2021-06-14 08:05 UTC, JanAckermann approved these changes
LGTM, changelog missing, then :rocket:

2021-06-14 09:10 UTC, merged

2021-06-14 09:13 UTC, phil-davis commented
Documentation updated in PR https://github.com/owncloud/docs/pull/3681