Improve login screen
owncloud/core pull request #38821
Opened 2021-06-09 02:56 UTC by phil-davis

## Description

## Related Issue
- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-06-10 07:44 UTC, JanAckermann requested changes

2021-06-10 07:44 UTC, JanAckermann commented on core/js/js.js
> +		color: $('p.info').css('color')
Should we make use of the var color, here ? otherwise it wont get used

2021-06-10 07:45 UTC, JanAckermann commented
![image](https://user-images.githubusercontent.com/26169327/121485549-91b6f800-c9d0-11eb-8914-a274919697e7.png)

Setup looks quite broken

2021-06-10 08:08 UTC, phil-davis commented
This is the same code as already approved in PR #38506 

@hurradieweltgehtunter can you look at the review comments please? Or whoever is managing these code changes.

2021-06-11 08:04 UTC, JanAckermann commented
Fixed setup:

![image](https://user-images.githubusercontent.com/26169327/121652931-76192380-ca9c-11eb-91a7-7b88fa1c409b.png)

2021-06-11 08:07 UTC, JanAckermann commented
Datadir is too wide :-1:

2021-06-11 09:50 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavMove1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiTags-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareCreateSpecialToRoot2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareReshareToShares1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavMove2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareOperationsToRoot-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiAuth-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareCreateSpecialToShares1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiShareReshareToRoot1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavLocks2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-11 09:57 UTC, JanAckermann commented
What the hack is going on ?

2021-06-11 11:02 UTC, JanAckermann commented
Don't merge yet, wip

2021-06-11 13:17 UTC, mmattel commented
Just a reminder, docs relevant, pls file a docs issue when close to merge.
@EParzefall fyi

2021-06-14 10:21 UTC, hurradieweltgehtunter approved these changes

2021-06-14 10:27 UTC, JanAckermann commented
Let me rebase, are we ready then?

2021-06-14 10:30 UTC, JanAckermann commented
![image](https://user-images.githubusercontent.com/26169327/121878625-3c4e5400-cd0c-11eb-9ef1-0e8227582c82.png)

Maybe some margin between the Setup database label and buttons?

2021-06-14 10:58 UTC, JammingBen commented
LGTM code-wise. I really like the new look 👍 

One small addition to @JanAckermann 's [last comment](https://github.com/owncloud/core/pull/38821#issuecomment-860578678): The db-buttons seem to be a little bit "off" horizontally compared to the input fields.

2021-06-14 11:12 UTC, hurradieweltgehtunter commented
Fixed the margin, cursor and horinzontal alignment issues

2021-06-14 11:23 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-06-14 11:39 UTC, JanAckermann approved these changes

2021-06-14 11:42 UTC, phil-davis commented on core/js/setup.js
> +	// }
Do we want to leave this commented-out code here?

2021-06-14 11:47 UTC, hurradieweltgehtunter commented on core/js/setup.js
> +	// }
No, I removed that in one of the last commits. Why is this back again

2021-06-14 12:19 UTC, phil-davis commented
@hurradieweltgehtunter is this done now? 
If so, then "somebody" (tm) should squash the commits. (I can do that when we are confident that the code is finished)

2021-06-14 12:39 UTC, hurradieweltgehtunter approved these changes

2021-06-14 12:40 UTC, hurradieweltgehtunter commented
Looks good so far and rady to merge IMO

2021-06-14 14:25 UTC, merged

2021-06-15 05:51 UTC, mmattel commented
It is really hard for the docs team to track changes where we please to file a docs issue when a PR gets close to merge (https://github.com/owncloud/core/pull/38821#issuecomment-859575260) - you would support a lot filing an issue on your own so that changes made finding its way into the documentation. Do not think that others will do it for you - just do it yourself, it is not a big effort but really helps 😢

2021-06-15 09:34 UTC, hurradieweltgehtunter commented
@mmattel sorry if this lead to frustration. I have the update of the docs in my mind but wanted to wait until PR got merged to get the final design. I'm on it rn

2021-06-15 09:37 UTC, phil-davis commented
Note: https://github.com/owncloud/password_policy/issues/338

password_policy CI started failing last night. I suspect that it is related to changes here, including changes that happen when resetting a password. I first need to see if it is just test code (either in password_policy or core) that needs adjusting, or if there is any real functional regression.

2021-06-15 10:42 UTC, hurradieweltgehtunter commented
@phil-davis I might have the solution. just pushing a new PR