TransferFiles To Custom Directory
owncloud/core pull request #38866
Opened 2021-06-18 15:42 UTC by T0mWz

## Description
When you migrate a user via files:transfer-ownership, all files will end up in a subfolder , for example ; `transferred from old-username on 2020618`.
Would be nice if the destination path becomes configurable, so that a transfer can end up elsewhere. For example in a subfolder with custom name or directly in the root when you move to a new account.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/38865

## How Has This Been Tested?

- test environment: Acceptance environment
- test case 1: without arguments
- test case 2: with empty argument
- test case 3: with an argument 

## Screenshots (if appropriate):
```
root@vm-web-acc-01:/var/www/owncloud # sudo -u apache /usr/bin/php72 /var/www/owncloud/occ files:transfer-ownership --destination-path='' old-user new-user
Analysing files of wezep001@surf.nl ...
   13 [============================]
Collecting all share information for files and folder of old-user ...
    0 [>---------------------------]
Transferring files to new-user/files/ ...
Restoring shares ...
    0 [>---------------------------]

```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-06-18 17:41 UTC, phil-davis commented
Note: this can be tested by adding scenarios to https://github.com/owncloud/core/blob/master/tests/acceptance/features/cliMain/transfer-ownership.feature
which will require adapting test code in https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/TransferOwnershipContext.php etc.

2021-06-20 13:43 UTC, mmattel commented on apps/files/lib/Command/TransferOwnership.php
> +				'selectively provide the path where the data will be transferred to. For example --destination-path="folder_name"'
```suggestion
				'Selectively provide the path where the data will be transferred to. For example --destination-path="folder_name"'
```

2021-06-20 13:45 UTC, mmattel commented on apps/files/lib/Command/TransferOwnership.php
> +			\OC::$server->getLogger()->debug('When destinationPath not defined we will use the default');
```suggestion
			\OC::$server->getLogger()->debug('The destinationPath is not defined, using the default one');
```
based on the query, it should result in a statement not a question.

2021-06-20 13:49 UTC, mmattel commented
Docs relevant, pls file a issue in docs when close to merge.
@EParzefall fyi

Regarding the definable path, pls write which restrictions or prerequisite(s) apply (eg, anywhere in the filesystem, access rights ect)

2021-06-21 07:11 UTC, jvillafanez commented on apps/files/lib/Command/TransferOwnership.php
> +			\OC::$server->getLogger()->debug('When destinationPath not defined we will use the default');
I don't think we need this log. Same with the log below.

2021-06-21 07:11 UTC, jvillafanez commented on apps/files/lib/Command/TransferOwnership.php
> +			$this->destinationPath = \ltrim($this->destinationPath, '/');
`trim($this->destinationPath, '/')` seems safer.

We can also reorder this a bit:
```
$this->destinationPath = "transferred from $this->sourceUser on $date";
$destinationPathOpt = $input->getOption('destination-path');
if ($destinationPathOpt !== null) {
  $this->destinationPath = \trim($destinationPathOpt, '/');
}
```

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingIntGroup1-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavOperations-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavMove2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavProperties2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiSharingNotificationsToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingAutocomp2-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:56 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>cliBackground-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingAcceptSh-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiFederationToShares2-git-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavPreviews-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavLocks2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>cliMain-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUICreateDelete-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiFederationToRoot1-latest-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavLocks3-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>apiWebdavProperties1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

2021-07-11 18:57 UTC, mmattel commented
I have rebased and squashed the commits. Rebasing was necessary due to: https://github.com/owncloud/core/pull/38973

2021-07-11 18:59 UTC, mmattel approved these changes
LGTM from a text pov 👍

2021-07-11 19:01 UTC, mmattel commented
To have a proper documentation preparation, pls tell the restrictions and axamples of the paths used.

2021-07-11 19:07 UTC, mmattel commented
Please create a **changelog** before merging !

2021-07-11 21:34 UTC, JanAckermann requested changes

2021-07-11 21:34 UTC, JanAckermann commented on apps/files/lib/Command/TransferOwnership.php
> -		// use a date format compatible across client OS
Maybe we can make the destinationPath optional, so we can keep the old behaviour with less required ?

2022-02-10 19:00 UTC, mrow4a requested changes
needs rebase , generally might evolve to quite complicated change but probably doable

2022-07-13 08:12 UTC, mmattel commented
@T0mWz do you have any update on this?

2024-11-19 07:56 UTC, closed without merging

2024-11-19 07:56 UTC, DeepDiver1975 commented
cleaning up - I think this is no longer of anybody's interest