Fix acceptance tests
owncloud/core pull request #38889
Opened 2021-06-24 11:24 UTC by JanAckermann

## Description

## Related Issue

- Fixes https://github.com/owncloud/activity/issues/975

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-06-24 11:28 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Accidental commit of .htaccess

2021-06-24 11:28 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiCapabilities-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/55/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/62/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/126/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIMoveFilesFolder-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/136/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/92/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt2-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/162/1

2021-06-24 11:29 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-6-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30797/175/1

2021-06-24 11:30 UTC, JanAckermann commented
@phil-davis we added a new subjectparam that's why we ran in the == 2 check was not fulfilled and the wrong text was rendered

2021-06-24 11:31 UTC, phil-davis approved these changes
LGTM

2021-06-24 11:33 UTC, JammingBen requested changes
We should do the same in `translateShort()`: https://github.com/owncloud/core/blob/cc899608ee0c4c21da8d44f7a19d84db15eb8c33/apps/files_sharing/lib/Activity.php#L312

2021-06-24 11:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiMain-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30800/58/1

2021-06-24 11:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30800/88/1

2021-06-24 11:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30800/109/1

2021-06-24 11:41 UTC, phil-davis approved these changes

2021-06-24 11:41 UTC, JammingBen approved these changes

2021-06-24 12:54 UTC, merged

2021-06-25 04:13 UTC, phil-davis commented
Activity CI passed last night :rocket: