[test-only] Adds test for sharing resource with sharee that has an existing resource with diff. case name
owncloud/core pull request #38950
Opened 2021-07-07 07:28 UTC by sakshamgurung

## Description

- Adds API test for for sharing resource with sharee that has an existing resource with different case sensitive name
## Related Issue

- API test for [32357](https://github.com/owncloud/core/issues/32357)

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-07-08 05:35 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31012/125/1

2021-07-08 05:35 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31012/126/1

2021-07-08 06:25 UTC, jasson99 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +    Given using OCS API version "1"
In my opinion, This step can go into background.

2021-07-08 06:32 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31013/125/1

2021-07-08 06:32 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31013/126/1

2021-07-08 06:32 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31013/127/1

2021-07-08 06:36 UTC, sakshamgurung commented
Why CI/CD is failing?

2021-07-08 07:01 UTC, kiranparajuli589 commented
some suites failed in `install-core` steps https://drone.owncloud.com/owncloud/core/31013/125/1
this can happen sometimes due to network failures.
please restart the CI.

2021-07-08 07:40 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt1-git-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31014/159/1

2021-07-08 10:31 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +  Scenario Outline:  sharing folder with user sharee that has an existing file with different case name
```suggestion
  Scenario Outline: sharing folder with user sharee that has an existing file with different case name
```

2021-07-08 10:48 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +      | /# %text file?=ed.txt | /# %TEXT FILE?=ed.txt |
Maybe we do not need so many examples for simple share tests. It will take more time to run in drone.

2021-07-08 10:50 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +  Scenario Outline: sharing folder with user sharee that has an existing file with different case name
Please use a different scenario title. This title is already used in this file at line 28

2021-07-08 10:57 UTC, swoichha requested changes

2021-07-08 10:57 UTC, swoichha commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +
```suggestion


```
Please add extra line before each scenario, as it is our common convention to add 2 lines gap between scenarios. We do this because in future if we need to add or remove any `tags` it won't change the line number.

2021-07-09 03:26 UTC, SwikritiT reviewed
LGTM

2021-07-09 10:37 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +      | file-1                | file-2                |
```suggestion
      | filename              | uppercased-filename                |
```

2021-07-09 10:37 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +      | folder-path-1 | folder-path-2 |
```suggestion
      | cased-folder-path | folder-path |
```
do not use numbers in the table heading rather try to describe the column. please review other table headings too

2021-07-09 10:40 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
> +  Scenario Outline: sharing files with different case name with user sharee
```suggestion
  Scenario Outline: sharing files with different case names with an internal user
```

2021-07-09 10:40 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
> +  Scenario Outline: sharing files with different case name with group sharee
```suggestion
  Scenario Outline: sharing files with different case names with group members
```

2021-07-09 11:25 UTC, saw-jan commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$user2,
```suggestion
		$sharer,
		$sharee,
```
having descriptive variable name is recommended

2021-07-09 11:39 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31061/114/1

2021-07-13 04:55 UTC, swoichha approved these changes
looks good :+1:

2021-07-13 07:36 UTC, phil-davis approved these changes

2021-07-13 07:36 UTC, merged

2021-07-14 10:16 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +@api @files_sharing-app-required @notToImplementOnOCIS
why is this feature `notToImplementOnOCIS` ? I didn't notice that when I reviewed it yesterday.