Fix errors reported by phpstan 0.12.92
owncloud/core pull request #38972
Opened 2021-07-11 12:07 UTC by phil-davis

## Description

## Related Issue
- Fixes #38971 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-07-11 14:16 UTC, phil-davis commented on apps/dav/lib/Connector/Sabre/AppEnabledPlugin.php
> +	 * @return void
This does not return anything, and the callers do not expect anything to be returned. IMO the PHPdoc was not correct.

2021-07-11 14:18 UTC, phil-davis commented on apps/dav/lib/Connector/Sabre/CorsPlugin.php
> +	 * @return false|void
If this follows the "doing nothing" path, then it "returns" `void`.
I just added that to the PHPdoc. 
But maybe it should always return `false`? Or?

2021-07-11 14:20 UTC, phil-davis commented on apps/files_sharing/lib/Controller/ShareesController.php
> +	 * @return void
This method is called `getRemote` - it "gets" the information into `$this->result`. It does not actually return anything, so I adjusted the PHP doc.

2021-07-11 14:21 UTC, phil-davis commented on apps/files_sharing/lib/SharedMount.php
> -	 * @return bool
This method does not return anything, and the callers do not expect anything to be returned. I deleted the PHP doc.

2021-07-11 14:22 UTC, phil-davis commented on apps/files_sharing/lib/SharedStorage.php
> +		return parent::unlockNodePersistent($this->getSourcePath($internalPath), $lockInfo);
Similar to `lockNodePersistent`, `unlockNodePersistent` is supposed to return the result.
I wonder if this will help any callers, or?

2021-07-11 14:24 UTC, phil-davis commented on core/Command/Encryption/ChangeKeyStorageRoot.php
> +		return 1;
This will make the command exit with error status if something goes wrong.
It might help any script that runs this command and wants to know if it succeeded or failed.

2021-07-11 14:24 UTC, phil-davis commented on core/Command/Encryption/SetDefaultModule.php
> +			return 1;
This will now exit with error status if the module does not exist.

2021-07-11 14:26 UTC, phil-davis commented on core/Command/Maintenance/DataFingerprint.php
> +		return 1;
This will now exit with an error status if the data fingerprint is not updated.

2021-07-11 14:45 UTC, phil-davis commented on core/Migrations/Version20180302155233.php
> +		// The meeded update has been done above, so return an empty array.
```suggestion
		// The needed update has been done above, so return an empty array.
```

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Encryption/Keys/Storage.php
> +		return false;
This will return false if encryption is not enabled - it used to "return" void. `false` should be better.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Files/Storage/DAV.php
> +		return false;
If we get here, then the `mode` did not match any of the switch cases. We did not `fopen()` anything, so we better return false.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Files/Storage/Wrapper/Wrapper.php
> +			return $storage->unlockNodePersistent($internalPath, $lockInfo);
This has a boolean result, so return it.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Files/Storage/Wrapper/Wrapper.php
> +		return false;
Somehow this was not `IPersistentLockingStorage` and so we did nothing.
I chose to return `false`.
Or should it return `true`?

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Repair/RepairMismatchFileCachePath.php
> -	 * @return bool true for success
The method does not return anything, and callers are not expecting it to return anything. I removed the PHP doc.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Settings/SettingsManager.php
> +		return [];
If some othe `$typ` is passed, then I guess we should return an empty array.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Settings/SettingsManager.php
> +				return false;
The caller needs to be able to more clearly know that there is no "proper" panel, so I returned false here.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Settings/SettingsManager.php
> +				if ($panel !== false) {
And now we can avoid trying to do these lines of code if `$panel` has nothing.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Setup/MySQL.php
> -	 * @return array
This does not return anything, and callers to not expect a return value, so I deleted the PHP doc.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/Theme/Theme.php
> -	 * @return string
This is a setter method. No return value.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/URLGenerator.php
> -				&& $imagePath = $this->getImagePathOrFallback($this->theme->getBaseDirectory() . '/' . $themeDirectory . $file)
Unused var.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/URLGenerator.php
> -			if ($imagePath = $this->getImagePathOrFallback($this->environmentHelper->getServerRoot() . $file)) {
Unused var.

2021-07-11 14:45 UTC, phil-davis commented on lib/private/URLGenerator.php
> +		return '';
If we get here, then "something is wrong/not found".
I return the empty string (rather than letting it "return void")

2021-07-11 14:45 UTC, phil-davis commented on lib/private/URLGenerator.php
> +		return false;
Callers of this method test its value in a "boolean" way. If we don't find the file, then it seems good to return `false`

2021-07-11 14:45 UTC, phil-davis commented on lib/private/User/RemoteUser.php
> +		return '';
This method is supposed to return a string.
What to return in this case?
Empty string seems better than "void".

2021-07-11 14:45 UTC, phil-davis commented on lib/public/Search/PagedProvider.php
> +		return $this->searchPaged($query, 1, self::SIZE_ALL);
The PHPdoc says that this should return an array of results.
This looks easy to fix - but it worries me why this "missing return" has not been causing problems.

2021-07-11 14:45 UTC, phil-davis commented on tests/Core/Command/Encryption/DecryptAllTest.php
> +		$this->assertEquals(0, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
The command `execute()` method is supposed to return `0` for success, and now it does.

2021-07-11 14:45 UTC, phil-davis commented on tests/Core/Command/User/ResetPasswordTest.php
> +		$this->assertEquals(0, $this->invokePrivate($this->resetPassword, 'execute', [$input, $output]));
The command `execute()` method is supposed to return `0` for success, and now it does.

2021-07-11 14:45 UTC, phil-davis commented on vendor-bin/phpstan/composer.json
> +        "phpstan/phpstan": "^0.12.92"
`0.12.92` implements the improved checks that find this stufff. So make sure it is the minimum version of `phpstan` that we use.

2021-07-11 15:14 UTC, micbar requested changes
let us merge after the release

2021-07-11 15:58 UTC, phil-davis commented
> let us merge after the release

I will make PRs to pin `phpstan` to the previous patch version. That will get CI  green in both `master` and `release-10.8.0`

2021-07-21 16:20 UTC, phil-davis commented
`release-10.8.0` has been merged back. I have rebased this PR. It is ready for review.

2021-07-22 07:06 UTC, micbar approved these changes

2021-07-22 07:18 UTC, JammingBen reviewed
Found some more inconsistencies with return values in Commands, see my annotations. IMO this is a good PR to tackle those as well.

2021-07-22 07:18 UTC, JammingBen commented on apps/files_external/lib/Command/Applicable.php
> +		return 0;
This method also returns `404` in some cases, which is not consistent with the Symfony docs.

Not sure if we should make it part of this PR, but I think `return 1` is more fitting. However, we would need to check if the returned `404` is used somewhere. Usually these `execute()` methods don't get called from the outside, except in the tests. Could be possible that the tests do some assertions with `404`.

2021-07-22 07:18 UTC, JammingBen commented on apps/files_external/lib/Command/Config.php
> +		return 0;
More `404` returns, see above.

2021-07-22 07:18 UTC, JammingBen commented on apps/files_external/lib/Command/Delete.php
> +		return 0;
More `404` returns, see above.

2021-07-22 07:18 UTC, JammingBen commented on apps/files_external/lib/Command/Verify.php
> +		return 0;
More `404` returns, see above.

2021-07-22 07:18 UTC, JammingBen commented on apps/files_sharing/lib/Controller/ShareesController.php
> +	 * @return void
Confusing name for this method, I expect `get...()` to actually return something, not set something 😄 
Just on a side note, I know it's been there for ages probably.

2021-07-22 07:18 UTC, JammingBen commented on core/Command/Config/Import.php
> +		return 0;
There is an empty `return` above in line 68 -> `return 1;`.

2021-07-22 07:18 UTC, JammingBen commented on core/Command/Encryption/DecryptAll.php
> +		return 0;
Empty return above in line 150 -> `return 0;`. And a `return null` in line 140, unsure about this one 🤷  Probably `return 2` as the command is invalid?

2021-07-22 07:18 UTC, JammingBen commented on core/Command/Group/ListGroups.php
>  			return $group->getGID();
Once again unsure about the return here, might be used in the tests though.

2021-07-22 07:18 UTC, JammingBen commented on core/Command/L10n/CreateJs.php
> +		return 0;
Empty return above in line 57 -> `return 1;`

2021-07-22 07:18 UTC, JammingBen commented on core/Command/TwoFactorAuth/Disable.php
> +		return 0;
Empty return above in line 58 -> `return 1`;

2021-07-22 07:18 UTC, JammingBen commented on core/Command/TwoFactorAuth/Enable.php
> +		return 0;
Empty return above in line 58 -> `return 1;`

2021-07-22 07:18 UTC, JammingBen commented on core/Command/User/Disable.php
> +		return 0;
Empty return above in line 57 -> `return 1;`

2021-07-22 07:18 UTC, JammingBen commented on core/Command/User/Enable.php
> +		return 0;
Empty return above in line 57 -> `return 1;`

2021-07-22 07:18 UTC, JammingBen commented on core/Command/User/LastSeen.php
> +		return 0;
Empty return above in line 60 -> `return 1;`

2021-07-23 05:39 UTC, phil-davis commented on apps/files_external/lib/Command/Applicable.php
> +		return 0;
Make a script containing:
```
exit 404
```

Execute the script and see the exit status:
```
./script.sh
echo $?
148
```

404-256=148. These kind of script/command exit codes are limited to 0 to 255. So 404 actually provides exit code 148 back to the thing that executed the command.

I  will change it to 1,

2021-07-23 05:43 UTC, phil-davis commented on apps/files_sharing/lib/Controller/ShareesController.php
> +	 * @return void
It does "get" the data, and remembers it internally in the class. But yes, the function name is not the best. IMO we don't touch that now.

2021-07-23 05:49 UTC, phil-davis commented on core/Command/Group/ListGroups.php
>  			return $group->getGID();
That is inside the function of \array_map - it is not a return out of `execute()`

I added:
```
use OCP\IGroup;
```
because the IDE didn't understand what sort of object `$group` is.

2021-07-23 05:55 UTC, phil-davis commented
Review comments addressed and rebased. IMO this is ready to merge when CI passes.

2021-07-23 07:01 UTC, JammingBen commented
The assertion in https://github.com/owncloud/core/blob/eebd754771a99bc44820eb67a6d57cea238e6b86/tests/Core/Command/Encryption/DecryptAllTest.php#L258 seems to be wrong now. Other than that, LGTM!

2021-07-23 08:08 UTC, phil-davis commented
I need to sort the unit test cases out...

2021-07-23 08:54 UTC, JammingBen commented on tests/Core/Command/Encryption/DecryptAllTest.php
> +		$this->assertEquals(2, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
`2` is just returned for the last argument of the data provider. So you'll need something like:

```
if (($confirmVal !== 'yes') && ($confirmVal !== 'no')) {
	$expected = 2;
} else {
	$expected = 0;
}

$this->assertEquals($expected, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
```

2021-07-23 11:04 UTC, phil-davis commented on tests/Core/Command/Encryption/DecryptAllTest.php
> +		$this->assertEquals(2, $this->invokePrivate($instance, 'execute', [$this->consoleInput, $this->consoleOutput]));
I have put the expected exit code in the data provider:
```
	public function providesConfirmVal() {
		return [
			['yes', 0],
			['no', 0],
			['foo', 2]
		];
	}
```

2021-07-23 12:10 UTC, JammingBen approved these changes
🚀

2021-07-23 13:14 UTC, merged