Feature/oc sessionPassphrase expire enhancement
owncloud/core pull request #38992
Opened 2021-07-14 06:27 UTC by jestovar1980

## Description

## Related Issue

- Fixes https://github.com/owncloud/core/issues/38991

## Motivation and Context
As User, I want my session to expire after a period of time defined in the configuration variable session_lifetime

The expected behavior is setting session_lifetime in config.php will make oc_sessionPassphrase cookie to expire in that period of time invalidating my session and forcing a log out. Otherwise, if session_lifetime is not defined, oc_sessionPassphrase will assume its original value of 0.

## How Has This Been Tested?

- test environment:
- define session_lifetime in config.php and login to OC10, oc_sessionPassphrase will show expiration time defined by session_lifetime
- remove session_lifetime from config.php,  oc_sessionPassphrase will show expiration time `Session`

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-07-14 06:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=38992) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=38992) before we can accept your contribution.<br/><hr/>**Jesus Tovar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=38992) it.</sub>

2021-07-19 08:47 UTC, jvillafanez commented
I think this is already handled by the server. Sessions should expire according to that config option in the server (if the session is idle)

2021-07-19 09:01 UTC, jvillafanez requested changes
Handling for PHP 7.3 and lower needs to be the same.

2021-07-19 09:01 UTC, jvillafanez commented on lib/private/Session/CryptoWrapper.php
> +					$sessionLifetime = ($cfgSessionLifetime > 0 ? time() + $cfgSessionLifetime : 0);
```
$sessionLifetime = $config->getSystemValue('session_lifetime', 0);
if ($sessionLifetime > 0) {
  $sessionLifetime += $this->timeFactory->getTime();  // add current timestamp to expire after the lifetime period
} else {
  $sessionLifetime = 0;
}
```
It seems easier to follow. Taking into account that it can't be unit tested, the `$this->timeFactory->getTime()` (which you should inject) can be substituted by a direct `time()`. Anyway, up to you.

2021-07-20 06:49 UTC, jestovar1980 commented
> I think this is already handled by the server. Sessions should expire according to that config option in the server (if the session is idle)

Hi, many thanks for the comments and review, I have added some changes following your review above.  

 As part of the observations in my test environment, when I set session_keepalive=false and session_lifetime > 0,  Session expires as per  base.php:

![image](https://user-images.githubusercontent.com/63689259/126274042-437d35d5-59af-4d7e-8ff5-925264916ccf.png)

however,  if the `notifications app` is enabled, the LAST_ACTIVITY attribute gets refreshed in every poll for notification (every 30 seconds) and session remains alive while I keep the browser open. 

I added some extra debug logs in my dev environment to capture these events:

```
{"reqId":"7d6ef2bb0f684f95675de9562b9fb855","level":2,"time":"2021-07-15T04:49:39+00:00",
"remoteAddr":"abcd","user":"myuser@test","app":"no app in context",
"method":"GET","url":"\/oc\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json",
"message":"Session base.php Record Last_Activity"}```

With this PR, I am looking for having a well defined expiration time for the os_SessionPassphrase cookie which forces the session to end upon expiration. 

Looking forward your feedback on this. 

Best regards.

2021-07-20 07:03 UTC, jvillafanez commented on lib/private/Server.php
> +				$timeFactory
Change it to `$c->getTimeFactory()`. There is already an instance available, so no need to create a new one.

2021-07-20 07:03 UTC, jvillafanez commented on lib/private/Session/CryptoWrapper.php
> +					$sessionLifetime = $config->getSystemValue('session_lifetime', 0);
This can be moved out of the "if" because the code is the same.

2021-07-20 12:30 UTC, jvillafanez commented
Code style is complaining.
```
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) lib/private/Session/CryptoWrapper.php (class_definition, braces)
      ---------- begin diff ----------
--- /drone/src/lib/private/Session/CryptoWrapper.php
+++ /drone/src/lib/private/Session/CryptoWrapper.php
@@ -96,9 +96,9 @@
 
 				$sessionLifetime = $config->getSystemValue('session_lifetime', 0);
 				if ($sessionLifetime > 0) {
-				  $sessionLifetime += $this->timeFactory->getTime();
+					$sessionLifetime += $this->timeFactory->getTime();
 				} else {
-				  $sessionLifetime = 0;
+					$sessionLifetime = 0;
 				}
 
 				if (\version_compare(PHP_VERSION, '7.3.0') === -1) {

      ----------- end diff -----------
```
Remember to use tabs instead of spaces.

2021-07-21 08:09 UTC, jvillafanez approved these changes

2021-07-21 08:14 UTC, jvillafanez commented
@jestovar1980 you need to sign the cla, otherwise we can't merge your PR.

2021-07-21 08:18 UTC, phil-davis commented
The CLA assistant is complaining:
"Robert Pocklington seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account."

@rpocklin did you make the last commit from some other device that did not have your correct GitHub account and email address?

2021-07-21 08:18 UTC, phil-davis commented
There is no changelog. I guess that this should have a changelog?

2021-07-21 08:53 UTC, jvillafanez commented
For the changelog item, you can check any of the recent PRs  in https://github.com/owncloud/core/pulls?q=is%3Apr+is%3Aclosed+enhancement to give you an idea. Just follow the same format.

2021-07-28 14:58 UTC, JammingBen approved these changes
LGTM 🚀 
Merge?

2021-07-28 17:00 UTC, jvillafanez commented
> Merge?

No problem on my side.

2021-07-29 04:21 UTC, merged