[Tests-Only] Test case for groupadmin being able to see email and password in users page
owncloud/core pull request #38997
Opened 2021-07-14 10:51 UTC by sakshamgurung

## Description

- Adds UI test for groupadmin being able to see email and password filed at the same time in users page

## Related Issue

- Test for https://github.com/owncloud/core/issues/34652

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-07-14 10:53 UTC, sakshamgurung commented on tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
> +
Sorry not intended to push this

2021-07-14 10:57 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFfSmoke-3-1-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/165/1

2021-07-14 10:57 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFfSmoke-3-2-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/166/1

2021-07-14 10:57 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt2-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/163/1

2021-07-14 10:57 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt1-10.6.0-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/161/1

2021-07-14 10:58 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/172/1

2021-07-14 10:58 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-3-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31186/170/1

2021-07-14 11:10 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31188/142/1

2021-07-14 11:25 UTC, SwikritiT commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And user "Alice" logs in using the webUI
```suggestion
    And the administrator has logged out of the webUI
    And user "Alice" has logged in using the webUI
```

2021-07-14 11:43 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31192/142/1

2021-07-19 07:04 UTC, Talank commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +	}
I think these 2 functions has a lot in common. So, instead of rewriting the logic, you might want to reuse the logic.

2021-07-19 07:04 UTC, Talank commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +	}
same here

2021-07-19 07:10 UTC, sakshamgurung commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +	}
I know, but I failed to write regex for "be" and "not be". How to do that?

2021-07-20 09:32 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31392/142/1

2021-07-20 11:16 UTC, saw-jan commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And user "Alice" has logged in using the webUI
I think this would do the same
```suggestion
    And the user has re-logged in as "Alice" using the webUI
```

2021-07-21 04:00 UTC, sakshamgurung commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And user "Alice" has logged in using the webUI
I am getting ElementNotFoundException error from that

2021-07-21 04:16 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31411/142/1

2021-07-21 07:48 UTC, sakshamgurung commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And user "Alice" has logged in using the webUI
I am getting ElementNotFoundException error from that

2021-07-22 03:50 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +	public function theGroupadminShouldBeAbleToSeePasswordFieldOfNewUser($shouldOrNot) {
```suggestion
	public function groupAdminShouldOrShouldNotSeePasswordFieldOfNewUser($shouldOrNot) {
```

2021-07-22 04:27 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31450/142/1

2021-07-22 05:49 UTC, jasson99 requested changes, later dismissed
The tests are failing.
![Screenshot from 2021-07-22 11-32-50](https://user-images.githubusercontent.com/40829116/126594950-45e3b24b-e8a0-40b0-a796-9f4c5df03b80.png)

2021-07-22 06:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISettingsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31453/142/1

2021-07-27 10:38 UTC, swoichha commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And the administrator enables the setting "Set password for new users" in the User Management page using the webUI
Why disabling the settings for `Set password for new users"` and enabling again in next step?

2021-07-29 06:00 UTC, sakshamgurung commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And the administrator enables the setting "Set password for new users" in the User Management page using the webUI
Because password field is not visible initially but when we disable and enable it, it will appear again. But after reloading the page same thing happens.

2021-07-29 06:10 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UsersPage.php
> +		return true;
```suggestion
		return $newPasswordField->isVisible()
```
isVisible() returns boolean anyway..

2021-07-29 06:10 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And the administrator enables the setting "Set password for new users" in the User Management page using the webUI
according to your scenario title, IMO this should be in the setup part (given) rather than a when step.
Please try enabling the setting before the user logs into the browser.

2021-07-30 03:55 UTC, sakshamgurung commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And the administrator enables the setting "Set password for new users" in the User Management page using the webUI
@kiranparajuli589 In my local system I can see both password and email field for new user while running test with remmina.
But, it is failing in drone with following error (can not see password field):
![Screenshot from 2021-07-30 09-33-43](https://user-images.githubusercontent.com/41365307/127597695-4a15f0e0-1b3d-4495-8c52-cd33d336582f.png)

2021-07-30 07:00 UTC, SwikritiT commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    And the administrator enables the setting "Set password for new users" in the User Management page using the webUI
Maybe try this step in given 
`Given the administrator has disabled the setting "Set password for new users" in the User Management page`
And enable it in when step and then check if the password field is visible.

2021-07-30 10:27 UTC, kiranparajuli589 reviewed
https://drone.owncloud.com/owncloud/core/31676/3/7

failed on php style

please run `make test-php-style-fix`

2021-07-30 10:57 UTC, kiranparajuli589 commented
failing at the same thing again:
![Screenshot from 2021-07-30 16-41-55](https://user-images.githubusercontent.com/39373750/127643395-f56c7037-8d47-4bb8-b298-6cee5f6eebf7.png)

2021-07-30 10:58 UTC, kiranparajuli589 requested changes, later dismissed

2021-07-30 10:58 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
>  	 * @param string $action
```suggestion
	 
	 * @param string $action
```

2021-07-30 10:59 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
>  	 * @param string $action
php-style needs an extra line in between step defn and params section

2021-08-03 10:46 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
> +    Then the subadmin should be able to see email field of new user
```suggestion
    Then the subadmin should be able to see email field in new user form on the webUI
```
For then steps its better to add `on the webui`  for visual assertions

Also, what do you mean by email field of new user?? Imo will be more clear to say email field in new user creating form.

2021-08-04 03:55 UTC, kiranparajuli589 reviewed
lgtm 👍🏼

2021-08-04 04:26 UTC, Talank reviewed
lgtm

2021-08-04 04:30 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +		$visible = $this->usersPage->isPasswordFieldOfNewUserVisible();
I think $visible is a bit misleading.

```suggestion
		$isVisible = $this->usersPage->isPasswordFieldOfNewUserVisible();
```

2021-08-04 04:30 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +			$visible,
```suggestion
			$isVisible,
```

2021-08-04 04:30 UTC, jasson99 commented on tests/acceptance/features/bootstrap/WebUIUsersContext.php
> +			. $expectedMsg . " in the User Management page, but is not."
When the expected is "not visible", and the test fails, the message would be something like: 
`The password field of new user was expected to be invisible in the User Management page, but is not.`
I would prefer to make it clearer.

2021-08-04 11:05 UTC, SwikritiT reviewed
LGTM

2021-08-04 11:51 UTC, swoichha reviewed
LGTM :+1:

2021-08-05 08:28 UTC, jasson99 reviewed
LGTM

2021-08-09 06:12 UTC, phil-davis approved these changes

2021-08-09 06:12 UTC, merged