owncloud.org -> owncloud.com
owncloud/core pull request #39014
Opened 2021-07-16 08:26 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-07-16 08:33 UTC, phil-davis commented on tests/lib/Mail/MailerTest.php
> +			['lukas@owncloud.com@owncloud.com', false]
```suggestion
			['lukas@domain.com@owncloud.com', false]
```
This one might look odd to future readers? They might wonder if this is testing a special case of repeating the same domain twicce?

2021-07-16 08:38 UTC, JanAckermann commented on tests/lib/Mail/MailerTest.php
> +			['lukas@owncloud.com@owncloud.com', false]
:heart:

2021-07-16 08:41 UTC, JanAckermann commented
Do wee need a changelog here ?

2021-07-16 08:52 UTC, phil-davis commented on README.md
> +* :clipboard: [Forum](https://central.owncloud.com)
https://central.owncloud.com says "the site can't be reached."

This still seems to be only on https://central.owncloud.org

2021-07-16 08:52 UTC, phil-davis commented on README.md
> +* :envelope: [Mailing list](https://mailman.owncloud.com/mailman/listinfo)
https://mailman.owncloud.com/mailman/listinfo can't be reached.
And neither can https://mailman.owncloud.org/mailman/listinfo

If this is still "a thing" then where can it be reached?

2021-07-16 08:52 UTC, phil-davis commented on apps/comments/lib/Dav/EntityCollection.php
> +	public const PROPERTY_NAME_READ_MARKER  = '{http://owncloud.com/ns}readMarker';
Does this get stored anywhere?
(I am not familiar with how all this relates to stored comments - if this has ended up anywhere in the database of comments, then there might be a migration... needed)

2021-07-16 08:53 UTC, phil-davis commented on README.md
> +* :clipboard: [Forum](https://central.owncloud.com)
Looks like it is fixed already.

2021-07-16 08:53 UTC, phil-davis commented on README.md
> +* :envelope: [Mailing list](https://mailman.owncloud.com/mailman/listinfo)
Looks like it is fixed already.

2021-07-16 08:55 UTC, phil-davis commented
> Do wee need a changelog here ?

IMO no changelog needed. This only adjusts tests, README links and that internal `PROPERTY_NAME_READ_MARKER` string.

2021-07-16 08:59 UTC, JanAckermann commented on apps/comments/lib/Dav/EntityCollection.php
> +	public const PROPERTY_NAME_READ_MARKER  = '{http://owncloud.com/ns}readMarker';
I try to figure out, what this const, does but at least I can confirm not stored in db

2021-07-16 09:06 UTC, JanAckermann commented on apps/comments/lib/Dav/EntityCollection.php
> +	public const PROPERTY_NAME_READ_MARKER  = '{http://owncloud.com/ns}readMarker';
@DeepDiver1975 do you know if this value is safe to replace ?

2021-07-16 09:12 UTC, xoxys commented on Makefile
> +#      - https://doc.owncloud.com/server/latest/developer_manual/core/unit-testing.html#running-unit-tests-for-the-owncloud-core-project
https://doc.owncloud.com/server/latest/developer_manual/testing/unit-testing.html#running-unit-tests-for-owncloud-core

2021-07-16 09:12 UTC, xoxys commented on Makefile
> +#      - https://doc.owncloud.com/server/latest/developer_manual/general/devenv.html#check-out-the-code
Anchor `#running-unit-tests-for-the-owncloud-core-project` does not exist

2021-07-16 09:12 UTC, xoxys commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +			'changeLogUrl' => 'https://owncloud.com/changelog/#latest8.1',
Broken if that matters

2021-07-16 09:12 UTC, xoxys commented on tests/lib/AppFramework/Http/EmptyContentSecurityPolicyTest.php
> +		$expectedPolicy = "default-src 'none';manifest-src 'self';style-src www.owncloud.com www.owncloud.com";
Does not make sense here, be careful with csp stuff, even if that is just a test. Should be `www.owncloud.com www.owncloud.org`

2021-07-16 09:12 UTC, xoxys commented on tests/lib/AppFramework/Http/EmptyContentSecurityPolicyTest.php
> +		$expectedPolicy = "default-src 'none';manifest-src 'self';img-src www.owncloud.com www.owncloud.com";
Same here and in the whole file. Don't know if that will break tests.

2021-07-16 09:12 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-3-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31283/170/1

2021-07-16 09:25 UTC, DeepDiver1975 requested changes

2021-07-16 09:25 UTC, DeepDiver1975 commented on apps/comments/lib/Dav/EntityCollection.php
> +	public const PROPERTY_NAME_READ_MARKER  = '{http://owncloud.com/ns}readMarker';
NO - Don't change them!

2021-07-16 09:34 UTC, JanAckermann commented
@DeepDiver1975 agreed this is some kind webdav server related, correct ? Won't change but would love to hear what this is exactly about, do we run an internal webdav server with this domain?

**Even if we would change it in core and get it running - this would break all other apps**

2021-07-16 09:34 UTC, DeepDiver1975 commented
> @DeepDiver1975 agreed this is some kind webdav server related, correct ? Won't change but would love to hear what this is exactly about, do we run an internal webdav server with this domain?

Please read about xml namespaces - google helps ;-)

2021-07-16 09:46 UTC, JanAckermann commented
@DeepDiver1975 done, why is changing the namespace not an option?

2021-07-16 09:48 UTC, DeepDiver1975 requested changes
What's the intention of killing all .org references?

2021-07-16 09:48 UTC, DeepDiver1975 commented on apps/updatenotification/tests/Controller/AdminControllerTest.php
> +			'changeLogUrl' => 'https://owncloud.com/changelog/#latest8.1',
it doesn't

2021-07-16 09:48 UTC, DeepDiver1975 commented on tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php
> +		$expectedPolicy = "default-src 'none';manifest-src 'self';script-src 'self' www.owncloud.com www.owncloud.com 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'sel
now the same domain is there two times. it has to be two different otherwise this test is loosing parts of the purpose.

just leave that as is - thx

2021-07-16 09:49 UTC, DeepDiver1975 commented
> @DeepDiver1975 done, why is changing the namespace not an option?

the xml namespace is part of the api contract. all clients in the world which are talking to owncloud are referencing properties with this namespace.
it would be a major bc!

2021-07-16 09:54 UTC, mmattel commented
> the xml namespace is part of the api contract. all clients in the world which are talking to owncloud are referencing properties with this namespace.

This is definitely something to be added to the developer docs...

2021-07-16 10:04 UTC, DeepDiver1975 commented
> This is definitely something to be added to the developer docs...

Not really - this is basic knowledge in the area of WebDAV and XML.
What comes next: php coding tutorial in our docs?

People need to understand how different technologies work - the internet is full of information - no need to create even more.

2021-07-16 10:20 UTC, DeepDiver1975 submitted a review, later dismissed

2021-07-16 10:20 UTC, DeepDiver1975 commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
please revert - thx

2021-07-16 10:27 UTC, JanAckermann commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
This is a draft - there will be a lot of BS until i convert it

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavUpload1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/103/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavEtagPropagation2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/92/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiAuthOcs-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/53/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocksUnlock-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/96/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/56/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/84/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavMove1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/97/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiCapabilities-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/55/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/107/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/62/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiAuth-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/52/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/95/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/66/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/108/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/79/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/83/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/73/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/109/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/88/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/60/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/93/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/94/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/69/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavEtagPropagation1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/91/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/85/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSharees-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/67/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiTrashbinRestore-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/89/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/68/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSharePublicLink1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/76/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiTranslation-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/87/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/71/1

2021-07-16 14:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31309/112/1

2021-07-16 14:55 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIRenameFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31313/139/1

2021-07-16 23:28 UTC, JanAckermann commented
Searched with regex pattern: (owncloud\.org\/*)(?!ns)\w+

nothing more left but translations and changelogs, converting to ready to review

2021-07-17 09:51 UTC, mmattel commented
I have rebased the PR because of #39018 (Update config.sample.php (url-typo))

2021-07-17 10:02 UTC, mmattel commented
This PR is important as it helps eliminating SEO issues. It is one of the puzzle pieces we need to fix to complete the job. In case of a merge, it would be great that goes into 10.8.0 by forward porting to `release-10.8.0` - @phil-davis your opinion on this would be great.

2021-07-17 10:03 UTC, mmattel approved these changes
LGTM 👍

2021-07-17 11:53 UTC, phil-davis reviewed
LGTM - the `org` to `com` changes are OK.

I made one comment about some code that builds a link to the server changelog. IMO that was already broken anyway, so it could be fixed in a separate PR, or fixed here???

2021-07-17 11:53 UTC, phil-davis commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$changeLogUrl = 'https://owncloud.com/changelog/#latest' . \implode('.', $versionParts);
I don't see how the `#latest` followed by some `versionParts` (something like `10.8` ?) actually links to the changelog for the new version.

The URL to the server changelog is: https://owncloud.com/changelog/server

And on that page are sections like: https://owncloud.com/changelog/server/#10.7.0

So I don't see how this is going to work.

2021-07-17 11:56 UTC, phil-davis commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$changeLogUrl = 'https://owncloud.com/changelog/#latest' . \implode('.', $versionParts);
@janalexa when/where does the `changeLogUrl` get displayed?
Fix it?

2021-07-17 11:57 UTC, janalexa commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$changeLogUrl = 'https://owncloud.com/changelog/#latest' . \implode('.', $versionParts);
@phil-davis I already recognized it, but I can't find the relevant part in the UI, do you have a hint? 
(Fixing here)

2021-07-17 12:26 UTC, janalexa commented on apps/updatenotification/lib/Controller/AdminController.php
> +				$changeLogUrl = 'https://owncloud.com/changelog/#latest' . \implode('.', $versionParts);
Will be shown if a new update is available

2021-07-17 12:52 UTC, mmattel commented
@janalexa the changelog link with 'latest' was correct. latest is resolved on the webserver and points to the latest available release. this is used a lot. when 10.8 is out, this resolves correctly. pls revert.

2021-07-17 12:55 UTC, janalexa commented
@mmattel This is not quite correct!
It would resolve to 
https://owncloud.org/changelog/#latest10.8
this link does not exist 

I will change it to https://owncloud.com/server/changelog/#latest10.8

2021-07-17 13:03 UTC, phil-davis commented
> I will change it to https://owncloud.com/changelog/server/#latest10.8

But, for example, https://owncloud.com/changelog/server/#latest10.7 does not work.

https://owncloud.com/changelog/server/#10.7.0 works.

Something changed in the recent past. It needs all 3 parts of the version, and no "latest".

2021-07-17 13:04 UTC, mmattel commented
You are right, I am in sorry. It is about the owncloud.com page and not docs...
Just taken a look, maybe the version independent page where you can click on the corresponding version you are looking for is better.  

https://owncloud.com/changelog/server/

2021-07-17 13:06 UTC, janalexa commented
I am on a train ^^ 
So the resolve latest on the webserver doesn't work, right? Is this broken on the webserver (resolver) and @xoxys has to look after it, or do we go with https://owncloud.com/changelog/server/#10.7.0  ?

2021-07-17 13:12 UTC, phil-davis commented
> I am on a train ^^
> So the resolve latest on the webserver doesn't work, right? Is this broken on the webserver (resolver) and @xoxys has to look after it, or should we go with https://owncloud.com/changelog/server/#10.7.0 ?

It's not about the "base" URL. It is just about the https://en.wikipedia.org/wiki/URI_fragment that is a reference/id withing the page. That seems to be generated by the recent changelog generating tools. It seems good to me to provide the URI fragment that takes the user directly to the most relevant part of the changelog.

2021-07-17 13:15 UTC, janalexa commented
Misunderstanding here - I know its not about the base url moreover about the anchor, and the anchor doesn't work -> 
question: is this an issue or intended ?

2021-07-17 13:20 UTC, phil-davis commented
> Misunderstanding here - I know its not about the base uri, moreover about the #latest anchor, and the anchor doesn't work ->
> question: is this an issue or intended ?

I doubt that a URI fragment like `#latest10.6` ever worked. It should have been either `#latest` or `#10.6`. The existing code that appends `latest` + `10.6` was always wrong.

And the code knows the version at that point, so it may as well go to the full version `#10.6.0` `#10.7.0` etc. And so there is no need to ever generate `#latest` here.

Maybe the changelog web page generator should generate a `latest` - that might be a good idea. But we don't need to use it here, so for this discussion, it doesn't matter if it exists, or not, or will exist.

2021-07-17 13:24 UTC, janalexa commented
I assume (how it should work) the latest refers to the minor version so if we had a 10.8.0 and 18.0.1 and 10.8.1 and 10.8.2 #latest10.8 would use the link to 10.8.2 changelog.

This would also make sense since updating to the highest minor version is very appropriate

2021-07-17 13:31 UTC, phil-davis commented
> This would also make sense since updating to the latest minor version is very appropriate

Maybe you are right, and it worked like this in the past.

So we need someone like @micbar (who is "defining the requirements" of the changelog generation) to decide if the existing changelog generation of the changelog web page should be adjusted to have some other system of ids that can be referenced by URI fragments - e.g. like the URI fragments that the code currently generates.

2021-07-17 13:40 UTC, xoxys commented
If you need something on owncloud.com ask the marketing team. Not managed by us.

2021-07-17 13:41 UTC, janalexa commented
@phil-davis :+1: anyways I will now remove the latest part to have a working state

2021-07-17 13:44 UTC, janalexa commented on tests/lib/HTTPHelperTest.php
>  		];
Some orgs are still here, what should we do about it -> refer to .ONLINE?

2021-07-17 13:54 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31328/130/1

2021-07-17 14:25 UTC, mmattel commented on tests/lib/HTTPHelperTest.php
>  		];
As far I see, it is just a matter of upper/lowercase in the test.
Proposing to change .ORG to .COM

2021-07-17 14:50 UTC, phil-davis commented on tests/lib/HTTPHelperTest.php
>  		];
I agree - getting rid of `.org` (even in tests) is an "easy win" for the future. It means that "random" people will not ask in future "why is `owncloud.org` still mentioned here.

2021-07-18 06:17 UTC, mmattel commented
Looks good, merge and forwardport to release-10-8.0 ?

2021-07-18 08:50 UTC, phil-davis approved these changes
LGTM - the URI fragment for the changelog now points into the correct place in the current format of the online changelog. If someone wnats to change the format of the online changelog then that is a separate issue and PR/

2021-07-18 08:50 UTC, merged

2021-07-18 17:57 UTC, micbar commented
No please, no backporting to release branch. The train is leaving the station already.