Use md5 hash for chunk name
owncloud/core pull request #39088
Opened 2021-08-02 12:00 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-08-02 12:56 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31719/173/1

2021-08-02 14:04 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Accidental commit

2021-08-02 14:46 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiMain-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31723/59/1

2021-08-02 15:21 UTC, phil-davis commented
In master I can do an "old" chunked upload of:
`नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-012345678.txt`

But an "old" chunked upload of:
`नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-0123456789.txt`
fails.

So that is an example of the current point of failure.

Then I switch to this branch, and the longer file name still fails. I see a message like:
`fopen(/home/phil/git/owncloud/core/data/Alice/cache/नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-नेपालि-file-नाम-0123456789.txt-chunking-1298-0.haWImtSPYnIig60i.part): failed to open stream: File name too long at /home/phil/git/owncloud/core/lib/private/Files/Storage/Local.php#298`

That looks strange - all the UTF filename is there, plus there is `.haWImtSPYnIig60i` before `.part`

I was expecting that the full file path might be something like:
`fopen(/home/phil/git/owncloud/core/data/Alice/cache/haWImtSPYnIig60i.txt-chunking-1298-0.part)`

And also, now that I see that the full path includes the real path to the user "home" and the username, that if there is a reasonably short maximum path length on the OS+filesystem in use, then, for example, a long username cannot store a super-long filename.

2021-08-03 07:28 UTC, JammingBen commented
We're still missing some parts of the implementation. That's probably why the hashing does not work as expected yet.

> And also, now that I see that the full path includes the real path to the user "home" and the username, that if there is a reasonably short maximum path length on the OS+filesystem in use, then, for example, a long username cannot store a super-long filename.

The filename-length-check should be done based on the filename only, so the username does not affect the result. At least that's what we observed - do you have other information?

Additionally, there is the config setting `part_file_in_storage`. When set to `false`, the chunked parts wont be saved in the user directory.

2021-08-03 07:34 UTC, phil-davis commented
> The filename-length-check should be done based on the filename only, so the username does not affect the result. At least that's what we observed - do you have other information?

AFAIK the maximum path length in most Unix file-systems is "long". Much longer than the filename maximum. So ignore my comments about path length - people will only come across that if they have made really long and/or many levels of directories.

2021-08-03 07:37 UTC, JanAckermann commented
@phil-davis on your system webDav chunking is enabled, in our system not :)
Any idea how you enabled that?

2021-08-03 07:51 UTC, phil-davis commented
> @phil-davis on your system webDav chunking is enabled, in our system not :)
> Any idea how you enabled that?

I am running API acceptance tests locally, not using any client. The tests just "hit" the chunking endpoints, they don't check any capabilities or other evidence about "chunking enabled". Actually, I don't see how chunking can be purposely disabled.

2021-08-03 09:13 UTC, JanAckermann commented
@phil-davis the example with the `-chunking-` part in filename seems to be legacy code (old chunking mechanism) and is not used by WebUI or modern desktop clients, I think we should not touch it.

2021-08-03 09:55 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliLocalStorage-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31736/121/1

2021-08-03 10:16 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt2-10.7.0-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31740/165/1

2021-08-03 10:16 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31740/127/1

2021-08-03 10:19 UTC, phil-davis commented
There were some pipelines that failed in the "setup"  steps. I restarted CI.

2021-08-03 10:24 UTC, IljaN commented
Code looks good :+1: 

We should ask some people from the client-teams to take a look because there could be some assumptions made (accidentally) about the chunk naming in client-code. @michaelstingl

2021-08-03 10:35 UTC, michaelstingl commented
> We should ask some people from the client-teams to take a look because there could be some assumptions made (accidentally) about the chunk naming in client-code. @michaelstingl

did you compare `mitmproxy` flows from desktop client with this PR?

2021-08-03 11:11 UTC, IljaN commented
The http flows should be unchanged except for the hashed values. I guess trying chunked upload with the latest clients should do the trick.

2021-08-03 11:34 UTC, JanAckermann commented
@IljaN agreed, http request should not change here, tested successfully with desktop client for linux (2.5.1)

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/71/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/85/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/86/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/114/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliLocalStorage-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/121/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/64/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/60/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavPreviews-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/101/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-10.7.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/113/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavUpload2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/105/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/111/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/80/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSharingNotificationsToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/106/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/94/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavEtagPropagation1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/92/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliMain-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/122/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiTranslation-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/88/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/127/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocksUnlock-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/97/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/84/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/115/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-10.7.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/119/1

2021-08-03 11:36 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31747/91/1

2021-08-04 10:28 UTC, IljaN approved these changes

2021-08-05 08:50 UTC, jvillafanez commented
Some questions:
* What happens if the code changes during an upload? The use case could be:
  1. Start uploading a big file. Upload 5 out of 20 chunks.
  2. The server upgrades to 10.9 (or when this patch is applied)
  3. Keep uploading the next chunks.

  As long as the server doesn't explode, I think it's fine. If the server has to signal someone to the client to restart the upload, that's ok. I expect the server to recover automatically at some point.
* Should we move the code to a function somewhere? It should be easier to adjust the code in the future if we need. We might want not to hash the name so it's easier to identify what file had problems if the chunks are kept for too long, or we could use a different algorithm.

Code changes looks good, assuming we aren't missing anything.

2021-08-05 09:05 UTC, mrow4a requested changes
make it configurable by flag, otherwise we explode on upgrade in minor version.

2021-08-05 09:24 UTC, jvillafanez commented
@mrow4a could you elaborate a bit more?

For the use case described in https://github.com/owncloud/core/pull/39088#issuecomment-893283657 , I expect the server throw an error due to missing chunks (the first ones might not be found due to the code change), or maybe waiting until a timeout. In any case, I expect the client to retry the upload and the chunks should be eventually removed (I think we have a cron job for cleaning the chunks)
Note that, anyway, the use case is unlikely to happen because the admins usually announce a downtime for the upgrade so the users aren't expecting to be uploading files just before the upgrade.
If we use a flag, we're more likely to bump into this scenario because a downtime isn't expected to happen just to change the value.

2021-08-05 09:29 UTC, mrow4a commented
@jvillafanez it is just risk management. We would change an algorithm for chunking. I would make it optional and applicable only to these oc instances that have problems with too long filenames (which are mostly the ones with non-latin characters). When going to OC11 we could make it default mechanism.

2021-08-05 10:03 UTC, jvillafanez commented
As far as I know, we're only changing the name of the part file, anything else remains the same. I don't think we're storing permanently the name anywhere, the name is transient data I think.
Taking this into account, unless I'm missing something, the only potential problem is the one explained above, which should fix itself after a while. It seems a low risk.

The problem I see with the option is that I don't really see any reason to keep the current behaviour. The alternatives we have are: keep the current behaviour (which is problematic) or use md5 in the filename. We're already discarding the current behaviour, so the only option left is to use md5. Unless we include some other useful option, using a flag to select from only one valid option doesn't seem good.

2021-08-05 10:09 UTC, phil-davis commented
This is an internal implementation "detail" changing. AFAICT the external API remains the same. (the existing test scenarios all work unchanged) So the only issue is the "migration" of uploads that are in progress at the time of the server upgrade. (as discussed above)

In-progress uploads will fail when they get to the point when they try to assemble all the chunks. So the client will get an error and restart the upload. IMO that is acceptable.

Any "orphaned" chunks get cleaned up by `occ dav:cleanup-chunks`

2021-08-05 10:10 UTC, JammingBen commented
> What happens if the code changes during an upload? 

When updating OC, we advice our users to enable the maintenance mode. I don't see a scenario where the server crashes due to the change, but I'll try and see what happens.

> Should we move the code to a function somewhere? It should be easier to adjust the code in the future if we need. We might want not to hash the name so it's easier to identify what file had problems if the chunks are kept for too long, or we could use a different algorithm.

Good idea. Just create a private method in `apps/dav/lib/Connector/Sabre/File.php`? Or do you think about a more "generic" place such as a helper?

> As far as I know, we're only changing the name of the part file, anything else remains the same. I don't think we're storing permanently the name anywhere, the name is transient data I think.

Exactly. Therefore I don't see a good reason to make this configurable via flag.

2021-08-05 10:55 UTC, mrow4a approved these changes
assuming risks are accepted and all integration tests passing

2021-08-05 11:01 UTC, jvillafanez commented
> Good idea. Just create a private method in apps/dav/lib/Connector/Sabre/File.php? Or do you think about a more "generic" place such as a helper?

It needs to be used in the "Files/Stream/Checksum.php", so it should be somewhere in core. A helper might make sense; we could include a generic way to check for part files there too (maybe not in this PR, but at some point)

2021-08-05 13:44 UTC, JammingBen commented
@jvillafanez Please check again. I added the method in `Filesystem`, as it currently holds plenty helper methods. Any objections?

2021-08-05 13:56 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31767/131/1

2021-08-06 06:54 UTC, jvillafanez commented
No objections from my side.
Just include some additional information in the PHPDoc, I think it's important to mention that it's expected to be used with the file chunking to prevent file names over the limit (in case we want to adjust the implementation in the future), and some examples for the expected output (to show if there will be a leading slash or not, what part of the file name will be hashed).
We should also include some unit tests.

2021-08-06 08:15 UTC, merged