Update appinfo cache only if the app version is newer
owncloud/core pull request #39108
Opened 2021-08-12 08:14 UTC by jvillafanez

## Description
Cache app info for the appid only if the version is newer.

## Related Issue
https://github.com/owncloud/core/issues/38549

## Motivation and Context
If there are multiple versions of the same app in different locations, we're expected to use the one with the latest version.
Note that the problem happens having a local cache active.

## How Has This Been Tested?
1. Having at least 2 different app locations, install the same app (not the latest version) in all of them
2. In the config.php file, set the first app location as writable
3. Update the app via `occ market:upgrade <app>`

There is no problem with the upgrade. The installed version in the DB is the latest one (downloaded from the market). Reloading the page doesn't trigger the "update needed" page.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-08-13 12:36 UTC, jvillafanez commented
There are no clear steps to reproduce the original problem, so it's difficult to foresee if this PR will fix the issue.
The provided steps in this PR are convoluted and unlikely to happen for common users. This means that it might not fix the problem affecting those users.
This PR fixes the issue caused by following the provided steps, so it's still worthy to merge.

2021-08-25 13:01 UTC, JammingBen requested changes, later dismissed
Plus changelog, then LGTM. Hopefully it fixes the issue. But it's a good thing either way.

2021-09-06 08:52 UTC, VicDeo approved these changes
Ready to go

2021-09-06 08:53 UTC, merged

2021-12-01 23:54 UTC, jnweiger commented
cannot reproduce the issue now, but the changes look indeed very promising. Thanks for the hard digging!