Include a flag to mark if the loginName2userName has been processed
owncloud/core pull request #39105
Opened 2021-08-11 09:24 UTC by jvillafanez

## Description
Add a flag when asking for the username to indicate that someone has already processed the request and there is no need for others to check further.

## Related Issue

- Fixes <issue_link>

## Motivation and Context
When the user_ldap app is enabled, logging in with the admin user triggered an LDAP request. This shouldn't happen when the admin's account is empty and there is no relation with any ldap user.
If the LDAP server is busy, it will slow down the login process even for non-ldap users.

## How Has This Been Tested?
Having the user_ldap app enabled (and patched), log in with the admin user. With both patches, there is no bind request send to the LDAP server when logged in with the admin user.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-08-13 12:30 UTC, jvillafanez commented
This is pending to confirm that it fixes the original issue. Code should be ready to review, and only the changelog is missing.

2021-09-07 09:38 UTC, JanAckermann requested changes
I don't like how the value is passed by reference through multiple files, maybe we should use a class to handle this?

2021-09-07 09:56 UTC, jvillafanez commented
I don't think we have a better choice. The result comes from an event, so we shouldn't change the approach. We have multiple listeners and all of them have to respond, so that flag will indicate that we have a valid result and the next listeners shouldn't need to process anything.

A better approach would be to use an interface with a registration process so core could have a better control on who and how the calls are done. The problem is that this is a breaking change which will need changes in all the related apps.

Note that the goal of the fix is that if someone has already returned a valid value for the event, the rest of the listeners shouldn't need to bother to process the event because we already have a result. Without changing the approach of using an event (which, as said, is questionable), using a flag in the event is the easiest solution.

2021-09-07 10:35 UTC, JanAckermann approved these changes
Understood, maybe you could add some comments, that those vars are called by reference, so we make no bugs will be implemented later...

2021-09-12 21:56 UTC, JanAckermann commented
Restarted CI

2021-09-13 11:05 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32303/124/1

2021-09-13 11:12 UTC, phil-davis commented
Note: Issue #39213 PR #39219 will skip it. That will be merged when CI finishes. After that you can rebase, and that annoying fail will be gone.

2021-09-16 13:02 UTC, JammingBen approved these changes

2021-09-16 13:02 UTC, merged

2021-12-01 17:23 UTC, jnweiger commented
Confirmed fixed in 10.9.0 beta1

When user admin types his correct password, no ldap requests are done. 
When user admin mistypes his password, ldap is still queried. That is as expected.

2021-12-02 09:08 UTC, jvillafanez commented
Weird... https://github.com/owncloud/user_ldap/pull/675 should be needed and it hasn't been merged yet... :thinking: 
I'd expect no changes comparing the behaviour with previous versions.