[Tests-Only]Adjust tests according to the expected behavior in OCIS
owncloud/core pull request #39111
Opened 2021-08-13 11:27 UTC by jasson99

## Description
# This PR is not complete yet

## Related Issue
- https://github.com/owncloud/ocis/issues/2141

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-08-17 11:26 UTC, saw-jan commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  @issue-ocis-2141@notToImplementOnOCIS
```suggestion
  @issue-ocis-2141 @notToImplementOnOCIS
```

2021-08-17 11:26 UTC, SwikritiT commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  Scenario: receiver tries to rename a received file share with share, read permissions inside the Shares folder in group sharing)
```suggestion
  Scenario: receiver renames a received file share with share, read permissions inside the Shares folder in group sharing)
```
I think this should be renames, as the file is being renamed for reciever

2021-08-17 11:27 UTC, saw-jan commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  @issue-ocis-2141@notToImplementOnOCIS
```suggestion
  @issue-ocis-2141 @notToImplementOnOCIS
```

2021-08-17 11:27 UTC, SwikritiT commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  Scenario: receiver tries to rename a received folder share with share, read permissions inside the Shares folder in group sharing
Same as above

2021-08-18 03:55 UTC, Talank commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  @issue-ocis-1289 @skipOnOCV10
```suggestion
  @issue-ocis-1289 @skipOnOcV10
```
I think we write `skipOnOcV10` and not `skipOnOCV10`, following the convention.

2021-08-18 03:55 UTC, Talank commented on tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
> +  @skipOnOC10
```suggestion
  @skipOnOcV10
```

2021-08-18 04:04 UTC, phil-davis commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  @issue-ocis-1289 @skipOnOCV10
Yes, you have to use the exact tag `skipOnOcV10` or it will not get matched.

2021-08-18 10:16 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  @issue-ocis-2141@notToImplementOnOCIS
fixed

2021-08-18 10:16 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  Scenario: receiver tries to rename a received file share with share, read permissions inside the Shares folder in group sharing)
fixed

2021-08-18 10:16 UTC, jasson99 commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  @issue-ocis-1289 @skipOnOCV10
fixed

2021-08-18 10:16 UTC, jasson99 commented on tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
> +  @skipOnOC10
fixed

2021-08-18 10:19 UTC, jasson99 commented on tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
> +  Scenario: receiver tries to rename a received folder share with share, read permissions inside the Shares folder in group sharing
fixed

2021-08-18 13:06 UTC, Talank reviewed
LGTM

2021-08-19 04:05 UTC, individual-it requested changes

2021-08-19 04:05 UTC, individual-it commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  @issue-ocis-1289 @skipOnOcV10
why do we skip this on oc10?

2021-08-19 04:05 UTC, individual-it commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +    And user "Brian" has created folder "/FOLDER"
that folder is never used for anything in the test

2021-08-19 04:05 UTC, individual-it commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  Scenario Outline: keep group permissions in sync
I don't understand what we are trying to test here, could you please explain

2021-08-19 04:05 UTC, individual-it commented on tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
> +  @files_sharing-app-required @issue-ocis-reva-34
do we really want to do that? That will mess up more lines in the expected to fail file

2021-08-19 05:52 UTC, jasson99 commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  @issue-ocis-1289 @skipOnOcV10
I have removed the skipOnOc tag now. I had skipped it thinking the scenarios were almost same, but there is no harm in running in oc10 as the test passes there.

2021-08-19 05:53 UTC, jasson99 commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +    And user "Brian" has created folder "/FOLDER"
yes, it was a mistake. I have fixed it now.

2021-08-19 05:57 UTC, jasson99 commented on tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
> +  Scenario Outline: keep group permissions in sync
the above scenario actually tests that when a share which is moved to another folder by the receiver, and then when the sharer updates the share permission, the share permission is updated as expected. But since moving the share outside a shares folder, or even creating a new folder inside shares folder is not going to be implemented in ocis, I recreated a similar scenario where the share is just renamed instead of trying to move to some other folder.

2021-08-19 05:58 UTC, jasson99 commented on tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
> +  @files_sharing-app-required @issue-ocis-reva-34
yes, the changes has been made in expected failures, so while I am in this file, I wanted to make it uniform

2021-08-19 06:56 UTC, individual-it approved these changes

2021-08-19 07:33 UTC, phil-davis approved these changes

2021-08-19 07:33 UTC, merged