Feature/version metadata
owncloud/core pull request #39126
Opened 2021-08-20 09:02 UTC by pushnov-i

The file version author is now being saved in an appropriate timestamp-prefixed JSON file and displayed in the version list on PROPFIND request. Rename, copy and deletion are take into account.

2021-08-20 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=39126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=39126) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mrow4a<br/>:x: pushnov-i<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=39126) it.</sub>

2021-08-20 09:40 UTC, IljaN commented
- You can fix codestyle by running: ```make test-php-style-fix```
- You can run stan and phan (static-analyzers) via: ``` make test-php-phpstan``` and ``` make test-php-phan ```

2021-08-20 10:03 UTC, JammingBen reviewed
Added some comments 👍 

Some indentations seem to be off, `make test-php-style-fix` should fix this.

2021-08-20 10:35 UTC, pushnov-i commented on apps/dav/lib/Meta/MetaFile.php
> +	public function getUsername() {
done https://github.com/owncloud/core/pull/39126/commits/94729f8101878b2cdd9d470d75575541cb75b932

2021-08-20 10:35 UTC, pushnov-i commented on apps/files_trashbin/lib/Trashbin.php
> +					self::copy_recursive($owner . '/files_versions/' . $ownerPath . '.json', $owner . '/files_trashbin/versions/' . \basename($ownerPath) . 'json' . '.d' . $timestamp, $rootView);
good catch, fixed

2021-08-20 10:35 UTC, pushnov-i commented on apps/files_trashbin/lib/Trashbin.php
> +					self::move($rootView, $owner . '/files_versions/' . $ownerPath . 'json', $user . '/files_trashbin/versions/' . $filename . 'json' . '.d' . $timestamp);
fixed

2021-08-20 10:35 UTC, pushnov-i commented on apps/files_versions/lib/Storage.php
> +
fixed

2021-08-20 10:38 UTC, pushnov-i commented on apps/dav/lib/Meta/MetaFile.php
> +	public function getUsername() {
thanks, fixed that

> * You can fix codestyle by running: `make test-php-style-fix`
> * You can run stan and phan (static-analyzers) via: ` make test-php-phpstan` and `make test-php-phan`

code style is fixed by test-php-style-fix

2021-08-20 11:24 UTC, prsnbrg commented on apps/files_trashbin/lib/Trashbin.php
> +					self::move($rootView, $owner . '/files_versions/' . $ownerPath . 'json', $user . '/files_trashbin/versions/' . $filename . 'json' . '.d' . $timestamp);
I think, there is still a missing dot bevore `json`.

2021-08-20 13:32 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31929/162/1

2021-08-20 16:28 UTC, pushnov-i commented on apps/files_trashbin/lib/Trashbin.php
> +					self::move($rootView, $owner . '/files_versions/' . $ownerPath . 'json', $user . '/files_trashbin/versions/' . $filename . 'json' . '.d' . $timestamp);
fixed

2021-08-21 07:50 UTC, JammingBen commented
I'm not sure if we should add `getUsername()` to the overall file interface. This method is (only?) needed in the `MetaFileVersionNode` class. Look for example how this it done for `getContentDispositionFileName()` [1].

You could implement a dedicated interface for the `getUsername()` method, similar to `IProvidesAdditionalHeaders`. This has then to be implemented by your `MetaFileVersionNode` class [2]. Your `getUsername()` method in `MetaFile` would look something like:

```
public function getUsername() {
	if ($this->file instanceof \OCP\Files\IVersionAuthor) {
		return $this->file->getUsername();
	}
	return '';
}
```

[1] https://github.com/owncloud/core/blob/feature/version-metadata/apps/dav/lib/Meta/MetaFile.php#L116
[2] https://github.com/owncloud/core/blob/feature/version-metadata/lib/private/Files/Meta/MetaFileVersionNode.php#L42

About the failing JS test: As the UI now shows the author in the versions tab, you have to adjust the expected result in the tests: https://github.com/owncloud/core/blob/feature/version-metadata/apps/files_versions/tests/js/versionstabviewSpec.js#L71

On a side note: I tried it on my local instance, but I only see a `{` where the author should be:

![image](https://user-images.githubusercontent.com/50302941/130313970-5f80f34c-a51b-4e83-8ef5-e145dbe49db8.png)

Feel free to ask if you need any help with that 🙂

2021-08-21 08:57 UTC, mrow4a commented
@hodyroff @pushnov-i what about making it optional in admin settings ? Just not to release new feature and reduce blast radius in case of bugs? It touches core functionality of sync/share. 

I am bit worried what happens when one of that version “copy” commands fails in the middle. How consistent is the state? 

What about expiring old versions ? Is this also handled (if relevant)? 

What about acceptance tests here? 

Unit tests covering major classes ?

2021-08-21 10:54 UTC, Xxxxx1111 approved these changes

2021-08-23 13:47 UTC, phil-davis commented on lib/public/Files/IProvidesVersionAuthor.php
> +	 * @since 10.0.9
```suggestion
	 * @since 10.9.0
```

2021-08-23 13:47 UTC, phil-davis commented on lib/public/Files/IProvidesVersionAuthor.php
> + * @since 10.0.9
```suggestion
 * @since 10.9.0
```

2021-08-23 14:46 UTC, pushnov-i commented
@phil-davis thank you, corrected the changes in the version for the interface.
@JammingBen I implemented everything via interface and adjusted the tests, the unit tests and js tests pass now new quick action feature prevent the drone from getting a successful build

@mrow4a not sure if this is related to the expiration, only `retainVersions` and `getVersion` methods from storage are affected, tests have been adjusted. regarding the optional feature, how it should appear on the frontend?

2021-08-23 15:13 UTC, IljaN commented
There are 6 version-related unit-tests failing https://drone.owncloud.com/owncloud/core/31947/12/9 
Click "Show all Lines" and scroll down to line 249. You can ignore the skipped tests.

2021-08-23 17:58 UTC, pushnov-i commented
@IljaN thank you, I fixed one bug and adjusted the unit tests. it seems all is good now

2021-08-24 08:40 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
Could you check additionally for an explicit expected result value in the second element of $result here? Only if you don't need to jump trough too much hoops.

2021-08-24 08:40 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
Could you check additionally for an explicit expected result value in the second element of $result here? Only if you don't need to jump trough too much hoops.

2021-08-24 08:40 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
Also in all following assertions.

2021-08-24 08:49 UTC, IljaN commented on apps/dav/lib/Meta/MetaPlugin.php
> +				return $node->getUsername() ?? "Not available";
Will "Not available" be visible in the WebUI? If yes this string should be translated. You might need to inject https://github.com/owncloud/core/blob/3bff5c2aca12499972f285e0cf2ea467a473c6b5/lib/public/IL10N.php#L44 in to your component alternatively if this is an issue you can globally get the service from the registry like so ```		\OC::$server->getL10N('core')->t('Not Available');```

2021-08-24 08:51 UTC, IljaN commented
@pushnov-i Looks good now, good work! :man_dancing:  Just a few small nitpicks left.

2021-08-24 09:20 UTC, pushnov-i commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
@IljaN I did a check yesterday with xdebug and just checked once again now - for this specific case the trashbin dir contains two files first one is the file version with the timestamp and the second is the JSON file with metadata:

<img width="1030" alt="Снимок экрана 2021-08-24 в 12 13 46" src="https://user-images.githubusercontent.com/17140470/130590568-e72237a8-b3b7-43c2-9104-c782a37635ca.png">

2021-08-24 09:25 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
So if the second file was introduced trough your change we should maybe explicitly check for it.

2021-08-24 09:25 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
So if the second file was introduced trough your change we should maybe explicitly check for it.

2021-08-24 09:25 UTC, pushnov-i commented on apps/dav/lib/Meta/MetaPlugin.php
> +				return $node->getUsername() ?? "Not available";
@IljaN, you are right, and this placeholder is redundant since if no metadata is available, the empty string will be shown instead of the author's username. I will take translation wrapper into account though

2021-08-24 09:27 UTC, IljaN commented on apps/dav/lib/Meta/MetaPlugin.php
> +				return $node->getUsername() ?? "Not available";
:+1:

2021-08-24 09:40 UTC, pushnov-i commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
Do you imply a completely separate test for the trash bin, or just an additional test if the second file is a JSON, has a valid name, and contains metadata within `testDeleteVersionsOfFolder`?

2021-08-24 09:53 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
>  just an additional test if the second file is a JSON, has a valid name, and contains metadata within testDeleteVersionsOfFolder?

This ^

2021-08-24 09:56 UTC, IljaN commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(2, $results);
But the more the better ;)

2021-08-24 11:34 UTC, mrow4a commented
@pushnov-i is there a unit/integration test covering backwards compatibility? How code/ui is behaving if there is no metadata-file ?

2021-08-24 11:37 UTC, IljaN commented
> @mrow4a  wrote:
> Tested with encryption?

This is also a point we should take in to account as the feature will be used first in an ownCloud instnace with encryption.

2021-08-24 12:04 UTC, phil-davis commented
@pushnov-i the CLA assistant still says that you have not "signed" the CLA. Please press the button to do that.

2021-08-24 12:07 UTC, IljaN commented
@mrow4a I just checked with @phil-davis. If we merge this all acceptance-tests will be run with encryption (master-key and user-key) as nightly-job. Results will be posted by drone in #builds in chat.

2021-08-24 12:16 UTC, phil-davis commented on apps/files_trashbin/tests/StorageTest.php
> +		// file should not be in the  trashbin
random space

2021-08-24 12:30 UTC, phil-davis commented
I don't see any changelog. Did I miss it?

2021-08-24 13:58 UTC, pushnov-i commented on apps/files_trashbin/tests/StorageTest.php
> +		// file should not be in the  trashbin
fixed

2021-08-24 14:04 UTC, pushnov-i commented
@phil-davis added changelog, fixed space.
@IljaN I did not check the encryption since this requires installing an additional plugin, but if only the content of the files will be encrypted, this feature should not affect the workflow as long as the structure of the files within storage won't be changed. I did not manage to add additional tests yet... @mrow4a, if a JSON file is missing, no author will be shown on the UI side. On the code's side, within the storage, you can see that there are conditional checks everywhere, so if the JSON file is present, it will be considered, otherwise ignored.

2021-08-24 14:38 UTC, phil-davis commented
@pushnov-i please click the link to sign the CLA at https://github.com/owncloud/core/pull/39126#issuecomment-902547524

Does it not work for you? Or?

2021-08-24 15:02 UTC, pushnov-i commented
> @pushnov-i please click the link to sign the CLA at [#39126 (comment)](https://github.com/owncloud/core/pull/39126#issuecomment-902547524)
> 
> Does it not work for you? Or?

@phil-davis CLA requires me to change the author of one merge commit since it does not recognize it in github, working on it

2021-08-24 15:54 UTC, pushnov-i commented
> @pushnov-i please click the link to sign the CLA at [#39126 (comment)](https://github.com/owncloud/core/pull/39126#issuecomment-902547524)
> 
> Does it not work for you? Or?

done

2021-08-24 18:08 UTC, DeepDiver1975 requested changes
I am missing explicit uni tests (later acceptance tests as well) where the user information is stored and retrieved. THX

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +	public function getUsername() {
getUserName() if one asks me ....

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +	public function getUsername() {
instead of phpdoc we could use real php return values ...

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +		if ($this->file instanceof \OCP\Files\IProvidesVersionAuthor) {
import IProvidesVersionAuthor

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaPlugin.php
> +	public const VERSION_EDITED_BY_PROPERTYNAME = '{http://owncloud.org/ns}metaversioneditedby';
meta-version-edited-by

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/files_trashbin/lib/Trashbin.php
> +					$metaVersionFile = $owner . '/files_versions' . $v['path'] . '.v' . $v['version'] . '.json';
I always find string interpolation more readable ....

2021-08-24 18:08 UTC, DeepDiver1975 commented on apps/files_versions/js/versioncollection.js
> +		PROPERTY_VERSION_EDITED_BY:	'{' + OC.Files.Client.NS_OWNCLOUD + '}metaversioneditedby',
meta-version-edited-by

2021-08-24 18:08 UTC, DeepDiver1975 commented on lib/private/Share/Constants.php
> +	public const CREATED_BY_USER_METADATA = "{http://owncloud.org/ns}createdbyuser";
created-by-user

2021-08-24 18:08 UTC, DeepDiver1975 commented on lib/public/Files/IProvidesVersionAuthor.php
> + * @copyright Copyright (c) 2017, ownCloud GmbH
2021 - please check all other file headers - THX

2021-08-25 06:43 UTC, mrow4a commented
same as @DeepDiver1975 hard to judge if this works without manual testdrive if there are no functional unit/acceptance tests. 

e.g. what is displayed in versions tab when it has only 1 version (new file). What about shares and reshares?

2021-08-25 07:22 UTC, mrow4a commented on apps/files_versions/lib/Storage.php
> +				if ($user !== null) {
@pushnov-i regarding making this feature configurable, this is good example how it could be done if you decide on doing so -> https://github.com/owncloud/core/pull/39130

2021-08-25 07:22 UTC, mrow4a commented on apps/files_versions/lib/Storage.php
> +				if ($user !== null) {
to disable this feature, looking at existing code logic, it is enough just not to write the metadata.

2021-08-25 07:24 UTC, mrow4a commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +   **/
typo

2021-08-25 10:54 UTC, phil-davis commented
I have tried this out manually:
- have some versions existing before checking out this branch
- view an existing file with versions, the list in the UI does not e. the usernames
- make some edits by different users - the new versions do display the usernames
- create a new file and edit it - all the versions have usernames

I didn't look closely at the usernames. So I need to check again a scenario like:
- Alice creates file.txt
- Brian edits file.txt
- Carol edits file.txt

There should be 2 old versions. The oldest version was created by Alice. The next version was created by Brian. Carol is the user who created the current file. I just have a suspicion that the code may not have a way to know that - the oldest version is created when Brian does his edit, the code would have to know somewhere that Alice is the original creator...

Also need to check what happens when one of the usernames in the version history no longer exists. Hopefully the code displays the usernames from the JSON file without anything bad happening.

What do we want to do about display names? If username `alice` has set their display name to "Alice Hansen" then do we show the display name?

2021-09-01 11:24 UTC, pmaier1 commented
> display full name instead of a username

Please do it like it's done in the sharing dialog (e.g., autocomplete or share recipient list). There is an option to add the user id or the email address to the display name. This should be respected.

2021-09-01 11:25 UTC, pmaier1 commented
Please let me know when this is ready for a demo. I'll invite then.

2021-09-13 10:13 UTC, mmattel commented
Docs relevant because of a change in `config/config.sample.php`
Please file a docs issue
@EParzefall

2021-09-13 10:51 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32300/124/1

2021-09-13 10:57 UTC, phil-davis commented
Note: we are having trouble with an intermittent webUI test. Issue #39213 

PR #39219 will kip it. That will be merged when CI finishes. After you can rebase, and that annoying fail will be gone.

2021-09-30 02:21 UTC, phil-davis commented
https://github.com/owncloud/core/tree/feature/version-metadata
"This branch is 49 commits ahead, 97 commits behind master."

There has been a lot happening in core master recently. This branch is running quite "old" CI now. It would be good to rebase some time. (And to squash/cleanup the 49 commits)

2021-10-19 07:08 UTC, DeepDiver1975 requested changes

2021-10-19 10:37 UTC, IljaN commented
Checked this branch out for testing, Do I need to enable something?
![noversion](https://user-images.githubusercontent.com/246983/137893404-c9c33893-f1f3-4787-a36f-59150fd2c5c8.png)

2021-10-19 13:42 UTC, JammingBen commented
> Yes, it's false by default as it takes extra space for each file version and should be disabled by default as team has mentioned before

Okay 👍  In this case I would rename the config to something like `file_storage.save_version_author` to make it more clear. Versions in general are always saved.

On a side note: I noticed that some recent changed were overwritten during the merge process, e.g. in `config.sample.php`. Let's not forget to check that before merging eventually!

2021-10-20 14:10 UTC, pushnov-i commented
> > Yes, it's false by default as it takes extra space for each file version and should be disabled by default as team has mentioned before
> 
> Okay 👍 In this case I would rename the config to something like `file_storage.save_version_author` to make it more clear. Versions in general are always saved.
> 
> On a side note: I noticed that some recent changed were overwritten during the merge process, e.g. in `config.sample.php`. Let's not forget to check that before merging eventually!

done

2021-10-29 22:43 UTC, pushnov-i commented
> We did a short review:
> 
> 1.) The json files in the storage should store the uid and use that to lookup the display name. With the current implementation if the display name is changed afterwards the list becomes inconsistent.
> 
> In the screenshot bellow the display name of user1 was changed to "Hans Müller" ![versions_list](https://user-images.githubusercontent.com/246983/138873768-c3013f85-856f-493e-a5a0-4f67e6f0a275.png)
> 
> 2.) If you hover over the display name in the versions list the uid should be displayed in the tooltip in case there are two persons with the same display-name.
> 
> 3.) The expire versions job should also clean the corresponding json files:
> 
> https://github.com/owncloud/core/blob/ad8eb74bd6322019cce933b3f7a99857c7f06f22/apps/files_versions/lib/BackgroundJob/ExpireVersions.php#L32
> 
> We discovered this because the job ran during our review 🍀
> 
> 4.) @JammingBen mentioned that we should check if the rebase was done correctly. From what I see everything should be fine though.
> 
> 5.) We had an issue where we saw the current version also being in the list, but could not reproduce it reliably. Maybe related to 3.
> 
> /cc @pmaier1

Fixed UID save, display name, tooltip, tested expired version deletion, and rebased the branch on master. Regarding 5) as far as I understand the initial version of the file should be saved as an initial version as well? If so, everything seems to be working as expected.

2021-10-30 04:26 UTC, phil-davis commented
code style checks fail: https://drone.owncloud.com/owncloud/core/33484/3/6
Please fix those, and then the rest of CI will run and we can see what tests pass.

2021-10-30 11:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33487/85/1

2021-10-30 14:45 UTC, phil-davis commented on tests/acceptance/features/apiVersions/fileVersions.feature
> +      When user "Alice" gets the number of versions of file "/test/textfile0.txt" with edited by prop
```suggestion
      When user "Alice" gets the number of versions of file "/test/textfile0.txt"
```

There is no step definition that has "with edited by prop" in the text. Is that an accident?
https://drone.owncloud.com/owncloud/core/33487/85/13
```
--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @When user :arg1 gets the number of versions of file :arg2 with edited by prop
     */
    public function userGetsTheNumberOfVersionsOfFileWithEditedByProp($arg1, $arg2)
    {
        throw new PendingException();
    }
```

2021-10-31 15:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33499/85/1

2021-10-31 22:02 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33500/85/1

2021-11-01 09:49 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33512/85/1

2021-11-04 11:17 UTC, IljaN commented
Rebased with master

2021-11-04 11:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33570/85/1

2021-11-04 15:17 UTC, IljaN commented
![image](https://user-images.githubusercontent.com/246983/140346170-18eed368-d9fa-4877-8737-63ba0f55b22c.png)

2021-11-04 16:30 UTC, pushnov-i commented
> Debugging: ![image](https://user-images.githubusercontent.com/246983/140346170-18eed368-d9fa-4877-8737-63ba0f55b22c.png)

yes, WIP

2021-11-05 16:59 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33579/85/1

2021-11-08 09:05 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Accidentally committed.

2021-11-08 09:16 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33603/85/1

2021-11-08 13:50 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33617/85/1

2021-11-10 17:56 UTC, IljaN commented
Squashed history a bit

2021-11-10 19:07 UTC, IljaN commented
All tests should pass now

2021-11-11 09:48 UTC, IljaN commented
https://github.com/owncloud/core/pull/39126/commits/ff13cf3235042bd86fb8fe2a0fa414c1924d203a was done because I am not sure how to mock the config here: https://github.com/owncloud/core/pull/39126/files#diff-15bc6a3d0922d2990f622f71c6f18a14ee37052dcf2ca8e65ed03cb128c01920R208

Maybe relegate this to acceptance tests?

2021-11-11 10:00 UTC, JammingBen commented
> was done because I am not sure how to mock the config here:

> [ff13cf3](https://github.com/owncloud/core/commit/ff13cf3235042bd86fb8fe2a0fa414c1924d203a) was done because I am not sure how to mock the config here: https://github.com/owncloud/core/pull/39126/files#diff-15bc6a3d0922d2990f622f71c6f18a14ee37052dcf2ca8e65ed03cb128c01920R208

You could either inject the config to the class (don't know if that's easily possible here) and mock it, or you have to set the config value during your tests (and reset if afterwards). The latter would kinda "break" the scheme of a unit test IMO, but I believe it is done like that quite often.

2021-11-11 10:10 UTC, IljaN commented
@JammingBen This is already done here: https://github.com/owncloud/core/blob/34ca8fc9adfa4a3a7be49efa0fbbf19641192f8d/apps/files_versions/tests/VersioningTest.php#L150

But not sure how to do this with the static storage class. In all other classes it is non-static and the overriding works. But not in this case.

2021-11-11 10:28 UTC, JammingBen reviewed
Cool! 🚀  Some minor annotations.

2021-11-11 10:28 UTC, JammingBen commented on apps/files_versions/lib/Hooks.php
> +		}
This seems outdated? I can't find the `post_write_hook` method in this class 🤔

2021-11-11 10:28 UTC, JammingBen commented on apps/files_versions/js/versioncollection.js
> +    PROPERTY_VERSION_EDITED_BY_NAME:	'{' + OC.Files.Client.NS_OWNCLOUD + '}meta-version-edited-by-name',
Some indentations are a bit off in the js-files, like here for example

2021-11-11 10:28 UTC, JammingBen commented on apps/files_versions/lib/Storage.php
> +						$metaDataKey =  \sizeof($versions) == 1 ? Constants::CREATED_BY_USER_METADATA : MetaPlugin::VERSION_EDITED_BY_PROPERTYNAME;
```suggestion
						$metaDataKey =  \sizeof($versions) === 1 ? Constants::CREATED_BY_USER_METADATA : MetaPlugin::VERSION_EDITED_BY_PROPERTYNAME;
```

2021-11-11 10:28 UTC, JammingBen commented on apps/files_versions/lib/Storage.php
> +			$users_view->unlink($fileToRestore . '.json');
Do we need to check here if the file exists or if `file_storage.save_version_author` is enabled?

2021-11-11 10:31 UTC, IljaN commented on apps/files_versions/lib/Hooks.php
> +		}
:+1:

2021-11-11 10:41 UTC, JammingBen commented
> @JammingBen This is already done here:
> 
> https://github.com/owncloud/core/blob/34ca8fc9adfa4a3a7be49efa0fbbf19641192f8d/apps/files_versions/tests/VersioningTest.php#L150
> 
> But not sure how to do this with the static storage class. In all other classes it is non-static and the overriding works. But not in this case.

Okay but then `enabledMetadataFeature()` has to be called I think. Like done in `testRestoreSameStorage()`:

```
if ($metaDataEnabled) {
	$this->enabledMetadataFeature();
}
```

Or maybe I'm just not seeing it. Is it working for `testRestoreSameStorage()`?

2021-11-11 11:44 UTC, IljaN commented
Does not work, even if enableMetadataFeature is called:
```
There were 2 failures:

1) OCA\Files_Versions\Tests\VersioningTest::testRestoreSameStorage with data set "metaEnabled" (true)
A version metadata-file must be created for the file before restoration
Failed asserting that false is true.

/home/ilja/code/core/apps/files_versions/tests/VersioningTest.php:1054
/home/ilja/code/core/apps/files_versions/tests/VersioningTest.php:912

2) OCA\Files_Versions\Tests\VersioningTest::testRestoreCrossStorage with data set "metaEnabled" (true)
A version metadata-file must be created for the file before restoration
Failed asserting that false is true.

/home/ilja/code/core/apps/files_versions/tests/VersioningTest.php:1054
/home/ilja/code/core/apps/files_versions/tests/VersioningTest.php:926
```

Also tried adding: 

```
if ($metaDataEnabled) {
			\OC::$server->getConfig()->setSystemValue('file_storage.save_version_author', true);
}
```
before https://github.com/owncloud/core/blob/34ca8fc9adfa4a3a7be49efa0fbbf19641192f8d/apps/files_versions/tests/VersioningTest.php#L1000

2021-11-12 12:20 UTC, IljaN commented
Any hints on how to enable the feature correctly in testing? I am out of ideas, but without unit-tests we can't merge.

2021-11-12 12:29 UTC, JammingBen commented
Ohhh wait! https://github.com/owncloud/core/blob/feature/version-metadata/apps/files_versions/lib/Storage.php#L354 -> `setSystemValue`?? Shouldn't it be `getSystemValue`? That's why it's never evaluating to `true`.

2021-11-12 14:14 UTC, IljaN commented
This didn't help, the issue was the same, the bug with set was introduced in a later refactoring

2021-11-12 15:01 UTC, IljaN commented
@JammingBen Thanks for the hint. If CI-Passes now I would squash and then push again.

2021-11-16 08:50 UTC, DeepDiver1975 requested changes

2021-11-16 08:50 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
I did not yet have a deeper look .... but shouldn't this be inverted?
The version author is the one who edited the file last - if there is none -> use the creator.

Is it possible that neither of them is set?

2021-11-16 08:50 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +	public function getVersionAuthor() {
adding return type?

2021-11-16 08:50 UTC, DeepDiver1975 commented on apps/files_versions/js/versionstabview.js
> +        editedByName: version.has('editedByName')
indent

2021-11-16 08:50 UTC, DeepDiver1975 commented on apps/files_versions/lib/Storage.php
> -		 * @var \OC\Files\Storage\Storage $storage
why was that removed?

2021-11-16 08:50 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +	private $editedBy = "";
these two props are not really needed.

2021-11-16 08:50 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +	public function getEditedBy() {
php return type

2021-11-16 08:50 UTC, DeepDiver1975 commented on lib/public/Files/IProvidesVersionAuthor.php
> +	public function getEditedBy();
php return type

2021-11-16 08:50 UTC, DeepDiver1975 commented on lib/public/Files/IProvidesVersionAuthor.php
> +	 * Returns the file author's username
desc of both methods should reflect the different usage.

2021-11-16 09:08 UTC, IljaN commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +	private $editedBy = "";
They are used by the getters, which are needed to satisfy the interface

2021-11-16 09:32 UTC, DeepDiver1975 commented on lib/private/Files/Meta/MetaFileVersionNode.php
> +	private $editedBy = "";
sure - but all the logic can be implemented purly in the getters. No need to use props and the related logic in the ctor.

2021-11-16 10:56 UTC, IljaN commented
@DeepDiver1975 All changes commited, checking https://github.com/owncloud/core/pull/39126/files#r750037657 separately.

2021-11-16 12:18 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
If I understood the logic correctly either of the two is set - strange behavior for my understanding.

If there is always only one available - just implement one method.
No reason to overcomplicate things.

2021-11-16 17:14 UTC, IljaN commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
Thinking about your first comment, there might be extreme-edge-case (metadata files got lost due to error) I think in this case non of the both are set.
----

- We have a metadata-file collection for each file (one metdata-file corresponding to each version file)
- Chronologically the first metadata-file (first version) contains the "created-by" field while all subsequent metadata files contain the "edited-by" field.

2021-11-16 17:52 UTC, DeepDiver1975 requested changes, later dismissed

2021-11-16 17:52 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
Looking deeper in the code:
- there is always either getCreatedBy or getEditedBy filled
- on dav api level - there is only one property
-> use only one property in the  file node api level as well

2021-11-16 18:03 UTC, IljaN commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
But semantically created_by != edited_by not sure if we should use one property for both

2021-11-17 09:55 UTC, IljaN commented on apps/dav/lib/Meta/MetaFile.php
> +			return $this->file->getCreatedBy() ?: $this->file->getEditedBy();
Hmhh I think you are right, the initial idea was to have the initial version to have the "created-by" key, but in reviews we decided against it since it is inconsistent with the "normal" version implementation where the very first version of a file does not get a version created. So in this case we can remove the created-by key alltogether? 

Also this is currently wrong as the second edit to a file creates a first version which has the "created-by" key in the metadata.

2021-11-17 10:01 UTC, phil-davis commented
Note: This branch is 4 commits ahead, 71 commits behind master. 
https://github.com/owncloud/core/tree/feature/version-metadata

When doing the next changes/refactoring/... I suggest rebase to get the very latest CI result.

2021-11-17 11:07 UTC, phil-davis commented
- user uu1 creates folder "nf"
- user "uu1" shares folder "nf" with user "uu2"
- user uu1 creates file "atf.txt" in folder "nf"
- no versions are listed for "atf.txt" - correct
- user uu2 edits file "atf.txt" in folder "nf"
- user uu2 show the version history
- one version is shown - correct
- the version "owner" is displayed as "uu2" - not correct, that was the original file, which was created by uu1

![version-user-is-off-by-one](https://user-images.githubusercontent.com/1535615/142188628-f5aaed81-b2c2-42ee-8a41-a6b4666984bb.png)

That could be confusing for users who want choose a version to restore based on "who edited it"

2021-11-17 11:08 UTC, phil-davis commented
Here is an example with a file shared to a group of 4 users uu1 uu2 uu3 uu4. The version history shows uu2 uu3 uu4, but actually the current file is by uu4 and the 3 older versions are by uu1 uu2 uu3
![edits-by-group-members](https://user-images.githubusercontent.com/1535615/142189577-a23f7d08-1865-47da-9bcc-90d357ef24a1.png)

2021-11-17 12:39 UTC, pmaier1 commented
> The requirements need to be defined.

The requirement is to see the user who **created** a version (or: the user who uploaded/saved this state of a file) as part of the version metadata. Basically this enhancement shall allow to answer the questions "Check the last version that Peter created" or "Let's roll back to the state before Peter started working on it". 

Here's the original input https://github.com/owncloud/enterprise/issues/4518.

2021-11-17 16:07 UTC, IljaN commented
This requirement was removed in a subsequent call => Creator can be checked via activity app. Will clarify with @pmaier1 now. 

If we need to show the creator than this would mean that we will need to show the very first version of a file in the versions view which we don't do yet.

2021-11-17 16:16 UTC, phil-davis commented
We don't have to show the "creator" of the "current version" of a file (the "version" that is not shown in the version history, because it is not yet history!) But technically, IMO, we will have to remember it somewhere so that it is available if and when that data becomes an "old version".

At the moment, if 
1) Alice creates a file
2) Brian edits it
3) Carol edits it

At step (2) it is Brian who is authenticated. I don't think "the system" has any way to reliably know that the original file was created by Alice.

At step (3) it is Carol who is authenticated. I don't think "the system" has any way to reliably know that the file before the edit was uploaded by Brian.

2021-11-17 16:26 UTC, IljaN commented
Maybe we can create a specially-named metadata-file which is not returned by the webdav-api but is replaced as soon as a new version is available.

2021-11-17 17:28 UTC, IljaN commented
> Maybe we can create a specially-named metadata-file which is not returned by the webdav-api but is internally replaced as soon as a new version is available.

@pmaier1 Will implement something like this

2021-11-18 04:48 UTC, phil-davis commented
I raised an issue to make some acceptance tests for this. We can do that in parallel in a branch on top of this.

Note my comment https://github.com/owncloud/core/issues/39504#issuecomment-972533285

Currently for this feature there is no way for end-users to find out who is the author of the data in the current file. If I was user "Alice" looking at a file, and seeing the author of each old version in the version history, an thinking about restoring some version, then probably I am doing it because the current data in the file is "wrong/corrupt" in some way. So I will immediately want to know "who is the author of the current data in the file?"

As Alice I can already find out other meta-data about the current file - modified date, tags, comments. Should users be able to find out the "latest author"?

2021-11-18 08:49 UTC, IljaN commented
As of now we don't write versions for empty files (filesize=0): So we also shouldn't write metadata for emtpy files. (?)

2021-11-18 09:33 UTC, phil-davis commented
> Possible edge-case: As of now we don't write versions for empty files (filesize=0): So we also shouldn't write metadata for emtpy files. (?)

And a combination edge-case. If we add some way for users to find out the "author" of the current file, then if there is version history of non-empty versions of the file, and "someone" has uploaded an empty file as the current file, then I think that user Alice will want to know who uploaded the "nothing" to the file.

2021-11-18 10:57 UTC, AlexAndBear approved these changes
Approving for now - Still in Beta Phase - Will be ready before RC

2021-11-18 10:59 UTC, merged

2021-11-22 13:02 UTC, IljaN commented
Continued here: https://github.com/owncloud/core/pull/39516

2021-12-08 02:51 UTC, jnweiger commented
## tested in 10.9.0 beta1

* works fine with and without encryption.
* delete restore should be improved -> 39571

2021-12-08 02:57 UTC, phil-davis commented
Note: I am quite sure that the version authors are off-by-one in 10.9.0 beta1. That is being fixed in #39516