[tests-only] Adds uitests for downloading resources
owncloud/core pull request #39220
Opened 2021-09-13 10:46 UTC by SwikritiT

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-09-13 10:58 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32302/46/1

2021-09-13 11:10 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32305/46/1

2021-09-14 09:30 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32335/31/1

2021-09-14 10:24 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32338/31/1

2021-09-14 11:11 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32349/31/1

2021-09-14 11:21 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32351/31/1

2021-09-15 05:45 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32362/31/1

2021-09-15 05:51 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32363/31/1

2021-09-15 08:20 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		//get the name of recently downloaded folder from downloads list in chrome, google download has shadow-root dom
for consistent look
```suggestion
		// get the name of recently downloaded folder from downloads list in chrome, google download has shadow-root dom
```

2021-09-15 08:20 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		//removes the number and bracket so that only simple-folder.zip remains
for consistent look
```suggestion
		// removes the number and bracket so that only simple-folder.zip remains
```

2021-09-15 08:30 UTC, Talank commented on tests/acceptance/features/webUIFiles/download.feature
> +    Given user "Alice" has been created with default attributes and without skeleton files
I think we can put the step to create "Alice" in background.

2021-09-15 09:21 UTC, Talank reviewed
LGTM

2021-09-15 11:50 UTC, kiranparajuli589 reviewed
lgtm 👍🏼

2021-09-16 03:40 UTC, dpakach requested changes

2021-09-16 03:40 UTC, dpakach commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		$session->visit("chrome://downloads/");
I believe this will only work with chrome browser, so you should remember to skip the tests that use this in other browsers such as firefox.

2021-09-16 03:56 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		$session->visit("chrome://downloads/");
Done

2021-09-16 09:03 UTC, saw-jan reviewed
LGTM

2021-09-17 08:27 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/download.feature
> +@webUI @insulated @disablePreviews @javascript @skipOnFIREFOX @skipOnINTERNETEXPLORER @skipOnMICROSOFTEDGE
Good - the code for checking the name of the download is specific to Chrome.

2021-09-17 08:27 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIFilesContext.php
> +		sleep(5);
This is unfortunate. But we are only executing this code in a couple of scenarios. So this sleep will >99% make sure that the download has actually happened and so it will be listed on the downloads page.

2021-09-17 08:27 UTC, phil-davis commented on tests/acceptance/features/webUIFiles/download.feature
> +  Scenario: download all files and folder
why does this say "download all files and folder" but it selects "simple-folder" twice (maybe that will unselect it?) and does not select "textfile0.txt"

2021-09-17 08:33 UTC, SwikritiT commented on tests/acceptance/features/webUIFiles/download.feature
> +  Scenario: download all files and folder
That must be because I copy-pasted that line and forgot to edit it. I've fixed it in latest commit.

2021-09-17 08:34 UTC, phil-davis approved these changes

2021-09-17 08:46 UTC, dpakach approved these changes

2021-09-17 09:21 UTC, merged