MariaDb changes for MariaDb 10.6
owncloud/core pull request #39286
Opened 2021-09-25 05:15 UTC by phil-davis

## Description
These are the code changes cherry-picked from PR #39282 

They are code changes that make CI pass against MariaDb 10.6

This PR will confirm if these code changes are OK for the oldest supported MaraDb version 10.2.

## Related Issue
- part of #39283 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-09-27 12:58 UTC, phil-davis commented
@IljaN these are the changes that you made to get CI passing with MariaDb 10.6. The CI passes here with MariaDb 10.2, so the changes are backward-compatible on a newly-installed system.

1) can you please write a changelog for this?

For everyone:
2) what should we do about checking upgrades of existing oC10 systems that use MariaDb 10.2/3/4/5 ?
3) what else can we think of that might be a problem?

2021-09-27 13:18 UTC, JanAckermann commented
Did we already tried to connect from a former compressed database with the new connection params?

2021-09-27 13:19 UTC, JanAckermann commented
Do we know how long it might take to migrate for a user with a big database ?

2021-10-04 10:38 UTC, IljaN commented on lib/private/Repair/Collation.php
> +				$query = $this->connection->prepare('ALTER TABLE `' . $table .'`;');
Not sure if this is the right thing to do as this is in a repair command. So we might need to adjust the command so that it works with both

2021-10-04 10:45 UTC, IljaN commented
> Do we know how long it might take to migrate for a user with a big database ?
I couldn't find any info on this. So I guess we need to test. If it's only a metadata DDL change for MariaDB then it might not take long (depends). By the looks of it (just guessing) MariaDB used to store Columns (and indices?) in a compressed form and deprecated this now. Two scenarios I can think of:

- We only change the DDL and Maria is smart enough to convert it's internal structure on the fly / on use
- Database needs to be taken offline and converted/migrated where all data on disk is rewritten

2021-10-04 20:31 UTC, mrow4a commented on lib/private/Repair/Collation.php
> +				$query = $this->connection->prepare('ALTER TABLE `' . $table .'`;');
I think it is ok to remove it here, but we just need to make sure it is required for ALTER statement below

2021-10-04 20:33 UTC, mrow4a commented
In this PR migration step for ALTERING ROW_FORMAT for tables is missing.

2021-10-04 21:31 UTC, IljaN commented
Is this is something which should be done during a normal ownCloud (minor) upgrade or does it need planing by the admin?  There is also the option to set the row type globally so we might be able to remove it from table definitions?

https://github.com/nextcloud/server/issues/25436#issuecomment-873545194

2021-10-05 07:43 UTC, mrow4a commented
@IljaN ok, maybe we then provide Repair command only for these that fail to upgrade ? For all new instances we just do not use ROW_FORMAT ? Plus we make sure when MariaDB upgrade is attempted we throw proper error with what to do?

2021-10-05 08:48 UTC, JanAckermann commented
@IljaN @mrow4a I would rather love to have a migration command (if the migrate process is quite short), 
ROW_FORMAT DYNAMIC also has the advantage of a faster database.

From a user perspective, figuring out the problem, reading the docs, run the repair command is pretty laborious,
what do you think?

2021-10-05 10:00 UTC, phil-davis commented on core/Migrations/Version20211005081736.php
> + * Auto-generated migration step: Please modify to your needs!
Comment needs updating

2021-10-05 10:00 UTC, phil-davis commented on core/Migrations/Version20211005081736.php
> +		if($platformName !== 'mysql'){
```suggestion
		if ($platformName !== 'mysql'){
```

2021-10-05 10:00 UTC, phil-davis commented on core/Migrations/Version20211005081736.php
> +		// Only execute this migration on mysql platform
```suggestion
		// Only execute this migration on mysql platform (MySQL and MariaDb)
```

Maybe note here that this will apply to both MySQLcand MariaDb implementations of the "mysql" platform.

2021-10-05 10:00 UTC, phil-davis commented on core/Migrations/Version20181220085457.php
> -
Do we need to touch this file? Will that cause any problem or side-effect?

2021-10-05 10:00 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Accidental commit

2021-10-05 10:04 UTC, jvillafanez commented
I'd vote for removing the row format from our code. From my point of view, we shouldn't need to care about it. We could suggest to use a specific format because of performance reasons, but I don't think we should enforce it. The problem we have now is that we enforce to use a specific format that is now deprecated.

Ideally, that should be fixed by a DBA, completely isolated from ownCloud: switch off ownCloud, convert the DB (on your own, with whatever tools the DB provides), switch on ownCloud.

2021-10-05 10:12 UTC, JanAckermann commented
> I'd vote for removing the row format from our code


I agree, I will check if we can set the row_format=DEFAULT in the migration which is DYNAMIC in MariaDB

2021-10-05 10:28 UTC, JanAckermann requested changes

2021-10-05 10:28 UTC, JanAckermann commented on lib/private/DB/ConnectionFactory.php
> +				'row_format' => 'dynamic',
As @jvillafanez commented, we should remove this part here

2021-10-05 10:32 UTC, phil-davis commented
We could bump the oC10 version from `10.8.1 prealpha` to `10.9.0 prealpha` in this PR. That should trigger the migration to auto-run when any developer/QA person updates. That will allow someone to test by installing MariaDb 10.5 with oC 10.8.0 checked out, then checkout this branch (or head of master when this is merged) and `php occ:upgrade` and it should "just work".

2021-10-05 10:37 UTC, JanAckermann commented
@phil-davis good idea, still wondering if we should migrate or repair (which should be triggered), my favor is migrate

2021-10-05 10:42 UTC, phil-davis commented
> @phil-davis good idea, still wondering if we should migrate or repair (which should be triggered), my favor is migrate

I am happy whichever is decided - auto-migrate, or something for an admin to do explicitly.

2021-10-05 11:29 UTC, jvillafanez commented
I'm not sure ownCloud 10.x can work normally without having that row format in the DB, at least until the next core upgrade.

Assuming OC 10.x can work without problems (at least until the next core upgrade), I'd remove the migration.

If the admin keeps using mariaDB 10.5, the only changes we have is that we no longer require the compressed row format, so the repair step won't do anything.

If the admin wants to use mariaDB 10.6, he can change the row format at any time; there is no need to wait for the upgrade (assuming OC doesn't give any problem). The only thing he needs to be careful about is to update to 10.9 for the next upgrade. The upgrade itself on our side won't do anything special.
The only problematic scenario is that the admin, having mariaDB 10.6, updates to OC 10.8 or earlier. In that case, I expect the migration to take some time because I expect ownCloud to change the DB row format back to compressed (due to the repair steps). Anyway, I don't think we can do anything about this other than document that mariaDB 10.6 is "officially supported" from 10.9 onward.

For an update from mariaDB 10.5 + OC 10.8 to mariaDB 10.6 + OC 10.9, I think the best path is:
1. Change row format in mariaDB 10.5
2. Update mariaDB to 10.6
3. Update OC to 10.9
ownCloud should be able to run after each step without problem. In theory, you should be able to stay for a while in step 1, and the same for step 2.

2021-10-05 11:38 UTC, JanAckermann commented
> If the admin keeps using mariaDB 10.5, the only changes we have is that we no longer require the compressed row format, so the repair step won't do anything.

This is not quite correct, I will give the admin the possibility to change MariaDB to 10.6 easily.
**Why do we want to enforce our users to search for a problem, which we then need to explain and document, so the user needs to run several queries?**
We can solve all this overhead for us and the admin, by a simple migration

2021-10-05 11:55 UTC, phil-davis commented
If we have a migration, then it is currently going to run on every installation where `$platformName == 'mysql'`

I guess that will be every installation that uses "real" MySQL and that uses any supported MariaDb 10.2, 10.3 10.4 or 10.5.

Do installations with "real" MySQL need to do this change at all?
(Is a similar deprecation coming for MySQL?)

2021-10-05 12:00 UTC, IljaN commented
> Do installations with "real" MySQL need to do this change at all?
(Is a similar deprecation coming for MySQL?)

MySQL is not affected.

2021-10-05 12:01 UTC, JanAckermann commented
@phil-davis according to @jvillafanez  and also this comment https://github.com/nextcloud/server/issues/25436#issuecomment-932979889
I agree that row_format should be set by the DBA if needed and not by ownCloud, so I like to 
pull right away

2021-10-05 12:22 UTC, jvillafanez commented
> Why do we want to enforce our users to search for a problem, which we then need to explain and document, so the user needs to run several queries and commands?

* In theory, any ownCloud 10.x version is compatible with mariaDB 10.6 ("compatible" doesn't mean "officially supported"). The problem happens during the upgrade, when ownCloud enforces the compressed row format.
* Admins can update the DB separately from ownCloud. They don't need to wait until ownCloud 10.9 is released. It's probably safer to update one component at a time and check that everything keeps working afterwards.
* I expect the row format conversion to take a lot of time depending on the amount of data in the DB. If we use a migration, all that time will be consumed during the ownCloud upgrade. This is something to avoid if possible, and I think this time is possible.

The problem I have with the migration is that we have to accurately detect which mariaDB (**and not mysql**) version we're using, and I don't think we have such information. If the detection is wrong we end up converting the row format and wasting a lot of time when it isn't needed.

In general, I think that updating the DB separately is safer. The DB update also implies the row format conversion.
If the DB is already updated an ready to be used, ownCloud doesn't need to bother, it just needs not to enforce anything. This is why I don't think we need a migration in this case.

2021-10-05 14:23 UTC, JanAckermann commented
Discussed with @pmaier1 :
* remove migration
* introduce db:convert-row-format (without param, will set it to default)
* Official support for MariaDB 10.6 only >= ownCloud 10.9
* Good documentation Martin Mattel I will keep you updated

@jvillafanez We should not recommend switching to MariaDB 10.6 if the ownCloud instance is below 10.9 because the DBA would need to tackle every table which might be brought in after an app installation

2021-10-05 15:41 UTC, jvillafanez commented
So I guess the plan is:
1. Update to OC 10.9
2. Run `occ db:convert-row-format`
3. Update mariaDB to 10.6

On the one hand, I'm not happy having to deal with the conversion ourselves. On the other hand, the upgrade path seems reasonable, and probably safer from an admin point of view (less things he should worry about).

Note that the command MUST show progress somehow (a "converting row format for table whatever" message might be enough), and the command must also check if the row format is already the right one (either it was converted beforehand, or the command has been run multiple time).

> @jvillafanez We should not recommend switching to MariaDB 10.6 if the ownCloud instance is below 10.9 because the DBA would need to tackle every table which might be brought in after an app installation

I'm not sure because, as far as I know, apps usually don't fiddle with the DB, only just to create the tables they need. New tables should have been created with the default row format, I think.
Anyway, we should always recommend to go for official support, and official support for mariaDB 10.6 is with ownCloud 10.9

2021-10-05 16:08 UTC, JanAckermann commented
> New tables should have been created with the default row format, I think.
I suspect, that the connectionParams already eenforce the Compressed format, but we should check that.


>And the command must also check if the row format is already the right one

In the migration we already check if there are tables with row_format compressed, I think we can still rely on it, in this special case

2021-10-06 03:45 UTC, phil-davis commented
@JanAckermann this PR branch is quite a way behind master now. When you need to do more changes, or feel like squashing, you can rebase and force-push.

2021-10-06 04:20 UTC, JanAckermann commented
@phil-davis Thx, done

2021-10-06 04:47 UTC, JanAckermann commented
@jvillafanez 

> I'm not sure because, as far as I know, apps usually don't fiddle with the DB, only just to create the tables they need. New tables should have been created with the default row format, I think.
Anyway, we should always recommend to go for official support, and official support for mariaDB 10.6 is with ownCloud 10.9

I have double-checked that:
* Install ownCloud instance (master)
* Converting all table row_formats to default -> results in *dynamic*
* Activate files_spaces -> those tables are *compressed*

This is the issuer:
https://github.com/owncloud/core/blob/11c85238feabba1a7147bd7c0517e129b49edd57/lib/private/DB/ConnectionFactory.php#L221

![image](https://user-images.githubusercontent.com/26169327/136142111-eef4158a-68c2-4d36-8b19-48b15e35c73f.png)

2021-10-06 08:08 UTC, JanAckermann approved these changes

2021-10-06 08:16 UTC, JammingBen approved these changes

2021-10-06 08:26 UTC, phil-davis commented on core/Command/Db/ConvertRowFormat.php
> +		// Update row_format to DYNAMIC
```suggestion
		// Update row_format to DEFAULT
```

2021-10-06 08:40 UTC, phil-davis commented on core/Command/Db/ConvertRowFormat.php
> +		// Update row_format to DYNAMIC
I will commit this little comment fix and then squash...

2021-10-06 09:56 UTC, JanAckermann commented on core/Command/Db/ConvertRowFormat.php
> +	private $allowedFormats = ['default'];
No, this has been decided by @pmaier1, not for now

2021-10-06 09:57 UTC, JanAckermann commented on core/Command/Db/ConvertRowFormat.php
> +				'Desired row format',
See comment above

2021-10-06 09:57 UTC, jvillafanez commented
It seems to be a mismatch between the code and the expectations. The code seems to convert the table row format to the default one, however, the command's help suggests that it's possible to convert to other row formats, but this isn't the case.

2021-10-06 10:02 UTC, JanAckermann commented on core/Command/Db/ConvertRowFormat.php
> +			$alterTableQuery = $this->connection->prepare('ALTER TABLE `' . $tableName . '` ROW_FORMAT=DEFAULT;');
>ROW_FORMAT=DEFAULT
this should be the input

2021-10-06 10:02 UTC, phil-davis commented on core/Command/Db/ConvertRowFormat.php
> +				'Desired row format',
Do we even want to have this argument?
At the moment, we only want the admin to be able to set the table-row-format to default, so we can have no argument - the command can "just do it".

2021-10-06 10:11 UTC, jvillafanez commented on core/Command/Db/ConvertRowFormat.php
> +				'Desired row format',
I agree with @phil-davis . This will leave a bad impression with the current code. The admin can check what options MariaDB provides and check them one by one just to see no option is allowed.

I'm ok with having plans for the future, but in this case it seems better to have just a "TODO" comment to include an option to choose the row format; just a comment without any code.

2021-10-06 14:36 UTC, phil-davis reviewed
LGTM - I am the PR "owner" so I can't approve.

2021-10-06 14:52 UTC, jvillafanez approved these changes

2021-10-06 14:53 UTC, merged