Don't show mail in lock owner data if mail adress is empty string
owncloud/core pull request #39292
Opened 2021-09-27 08:45 UTC by JanAckermann

## Description

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37878

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2021-09-27 08:51 UTC, JanAckermann commented
On the other hand we can just remove the extra () field as @DeepDiver1975 suggested in the recent issue

2021-09-27 08:53 UTC, phil-davis commented on lib/private/Lock/Persistent/LockManager.php
> +				if (!empty($user->getEMailAddress())) {
I don't like these. In this case the email address should never be the string "0" or "0.0" so I guess there is no real email address that will evaluate to `empty()` `true`.

2021-09-27 09:00 UTC, JanAckermann commented on lib/private/Lock/Persistent/LockManager.php
> +				if (!empty($user->getEMailAddress())) {
Well @DeepDiver1975 recommended getting rid of the extra data, as this data won't be updated if the user changes the email. I am also not quite sure who is able to see the email and it might not be GDPR compliant.

2021-09-27 09:03 UTC, JanAckermann commented on lib/private/Lock/Persistent/LockManager.php
> +				if (!empty($user->getEMailAddress())) {
> so I guess there is no real email address that will evaluate to empty() true
Empty string evaluates to true, so I don't understand the objection

>In this case the email address should never be the string "0" or "0.0" 
And that is correct, isn't it?

2021-09-27 09:10 UTC, phil-davis commented on lib/private/Lock/Persistent/LockManager.php
> +				if (!empty($user->getEMailAddress())) {
In this case `empty()` works, because the value being compared can never be `0`, `0.0`, "0" or "0.0"!

2021-09-27 09:11 UTC, JanAckermann commented on lib/private/Lock/Persistent/LockManager.php
> +				if (!empty($user->getEMailAddress())) {
updated the condition

2021-09-27 09:30 UTC, JammingBen approved these changes

2021-09-27 09:32 UTC, phil-davis approved these changes
works.

Note: to get this problem in the first place, an email address has to have been set for/by a new user. Then the user deleted the email address (sets it to the empty string, effectively). If a user never ever had an email address then this problem did not happen - the user's email address was effectively `null`.

2021-09-27 09:43 UTC, DeepDiver1975 requested changes
Test coverage?

2021-09-28 06:38 UTC, DeepDiver1975 approved these changes

2021-09-28 06:40 UTC, merged