[Tests-Only][CI] added step to wait for selenium for acceptance test suites
owncloud/core pull request #39323
Opened 2021-10-05 09:48 UTC by kiranparajuli589

## Description
Added step to wait for selenium for acceptance test suites

## Related Issue
- Fixes https://github.com/owncloud/QA/issues/691

## How Has This Been Tested?
- 🤖 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

2021-10-05 10:20 UTC, phil-davis commented on .drone.star
> +            "wait-for-it -t 10000 selenium:4444",
```suggestion
            "wait-for-it -t 600 selenium:4444",
```
Other uses of this have 600 - IMO the unit of measure is seconds.

2021-10-05 10:26 UTC, phil-davis approved these changes

2021-10-05 10:39 UTC, phil-davis requested changes

2021-10-05 10:39 UTC, phil-davis commented on .drone.star
> +                                                waitForBrowserService(phpVersion) +
This needs to be in the steps, just below `waitForServer` (line 1673), so that it will make the sequence of steps wait for selenium before running the acceptance tests.
Otherwise it is running as a service, and does not make anyhting else wait.

2021-10-05 10:44 UTC, kiranparajuli589 commented on .drone.star
> +                                                waitForBrowserService(phpVersion) +
fixed

2021-10-05 10:57 UTC, phil-davis approved these changes

2021-10-05 10:58 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32875/79/1

2021-10-05 10:59 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32875/66/1

2021-10-05 11:00 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/32875/79/12

For api and cli tests we don't want to wait for selenium - there is no selenium.

2021-10-06 06:08 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/32890/124/14
```
7.4: Pulling from owncloudci/php
Digest: sha256:de5675563473127820613d188919d2eec03617c02957f966f70391c777823e5f
Status: Image is up to date for owncloudci/php:7.4
+ wait-for-it -t 600 selenium:4444
services are ready!
```

Looks good.

2021-10-06 06:08 UTC, phil-davis approved these changes

2021-10-06 07:23 UTC, merged