Remove BOM from text preview content
owncloud/core pull request #39644
Opened 2022-01-05 13:10 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-01-07 13:49 UTC, DeepDiver1975 requested changes
in addition to the comment: adding a test would be great ;-) THX

2022-01-07 13:49 UTC, DeepDiver1975 commented on lib/private/Preview/TXT.php
> +		$content = \str_replace("\xEF\xBB\xBF", '', $content);
BOM is only relevant in the beginning of the file - so no need to do a replace over the full content.

replacing only the first few bytes is enough

2022-01-07 13:49 UTC, DeepDiver1975 commented on lib/private/Preview/TXT.php
> +		$content = \str_replace("\xEF\xBB\xBF", '', $content);
https://gist.github.com/chrisguitarguy/6096271

2022-01-10 08:28 UTC, JanAckermann commented on lib/private/Preview/TXT.php
> +		$content = \str_replace("\xEF\xBB\xBF", '', $content);
@DeepDiver1975 
I agree in a perfect world you should have only one BOM in a file, but it might be possible that a user created a combined file using the unix cat command and have accidentally two or more BOMs in a file.

Should we ignore those user errors?

2022-01-10 11:25 UTC, jnweiger commented on lib/private/Preview/TXT.php
> +		$content = \str_replace("\xEF\xBB\xBF", '', $content);
The BOM is only a BOM when at the beginning of a file. But U+FEFF may legally appear anywhere inside a text file. And it is still valid text. Unicode.org says "For historical reasons, the character U+FEFF used for the byte order mark is named `zero width no-break space`" -- and requests proper handling (as a zero-width-nbsp, when found elsewhere) for backwards compatibility.

So that is not a user error :see_no_evil: -- that is part of the unicode horrors.

2022-01-10 12:44 UTC, jvillafanez commented
There are a couple of issues here:
* The text analyzer detects the BOM as an arabic character (last range in https://github.com/owncloud/core/blob/0b3cbdd5b6675a27d35cd181665e92ac72142ef1/lib/private/Utf8Analyzer.php#L95 seems to be wrong, I need to recheck)
* Since there is one arabic character, the text is considered arabic, not latin. The problem seems to be in https://github.com/owncloud/core/blob/0b3cbdd5b6675a27d35cd181665e92ac72142ef1/lib/private/Preview/TXT.php#L137-L144 , where latin is only used if there isn't any other match. Basically, although the text contains X latin chars, the text is considered as arabic due to the wrongly detected BOM.

I think these are the 2 issues we should fix instead of removing the BOM.

2022-01-10 13:06 UTC, jvillafanez commented
Alternative fix in https://github.com/owncloud/core/pull/39669

2022-01-14 14:07 UTC, closed without merging