[tests-only][full-ci]Add spaces tests on `apiAuthWebDav` suites
owncloud/core pull request #39718
Opened 2022-01-25 09:05 UTC by amrita-shrestha

## Description
use spaces DAV path in `apiAuthWebDav` suite

## Related Issue

- fixes https://github.com/owncloud/ocis/issues/3029

## How Has This Been Tested?

- Locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-01-25 11:01 UTC, kiranparajuli589 requested changes, later dismissed
spaces DAV path does not contain `remote.php`. please change the URLs for every use case.

2022-01-25 11:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
> +      | /remote.php/dav/spaces/%spaceid%/PARENT/parent.txt |
```suggestion
      | /dav/spaces/%spaceid%/textfile0.txt     |
      | /dav/spaces/%spaceid%/PARENT            |
      | /dav/spaces/%spaceid%/PARENT/parent.txt |
```

2022-01-25 11:19 UTC, kiranparajuli589 reviewed
looks good :+1:

2022-01-25 11:21 UTC, amrita-shrestha commented on tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
> +      | /remote.php/dav/spaces/%spaceid%/PARENT/parent.txt |
`remote.php` is optional for all WebDAV variants (new, old, spaces) . In this tests scenario, the new and old variant is using `remote.php`. Just to make its structure similar I added remote.php in spaces tests too.

2022-01-25 11:25 UTC, phil-davis commented
@kiranparajuli589 please give a "full green" review, or dismiss your previous red review.

2022-01-25 11:28 UTC, kiranparajuli589 approved these changes

2022-01-26 05:26 UTC, phil-davis approved these changes

2022-01-26 05:26 UTC, merged