[tests-only] added spaces examples for TUS related upload features
owncloud/core pull request #39723
Opened 2022-01-27 12:04 UTC by kiranparajuli589

## Description
- use spaces dav variant for TUS related upload features

## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/3028

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-01-31 05:13 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
> +    @personalSpace
```suggestion

    @personalSpace
```

2022-01-31 06:35 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
> +    @personalSpace
fixed

2022-01-31 11:37 UTC, individual-it requested changes
I'm missing the `@skipOnOc10` tags. Do we still need them?

2022-01-31 11:37 UTC, individual-it commented on tests/acceptance/features/bootstrap/ChecksumContext.php
> +		Assert::assertIsArray($parsed0Value, __METHOD__ . " parsed XML parsed0Value is not an array");
IMO those error messages will not help when seeing them in a test-run output.
```suggestion
		Assert::assertIsArray($parsed0Value, __METHOD__ . " could not find checksum in parsed XML expecting `$parsed[0]['value']` to be an array but received '" . $parsed0Value . "'");
```

similar in the following code

2022-01-31 11:37 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +		Assert::assertIsArray(
do we need this assertion if we also have `Assert::assertArrayHasKey(`?

2022-01-31 11:37 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +			__METHOD__ . " XML part does not have key 0"
please be more descriptive in the error message

2022-01-31 12:12 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +		Assert::assertIsArray(
sometimes, input for `Assert::assertArrayHasKey()` is not an array, so it throws strange errors.

2022-01-31 12:14 UTC, kiranparajuli589 commented
> I'm missing the `@skipOnOc10` tags. Do we still need them?

all of the features in `apiWebdavUploadTUS` suites already have `@skipOnOcV10` tag at top

2022-01-31 12:32 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +			__METHOD__ . " XML part does not have key 0"
fixed

2022-01-31 12:32 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/ChecksumContext.php
> +		Assert::assertIsArray($parsed0Value, __METHOD__ . " parsed XML parsed0Value is not an array");
fixed

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/54/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiMain-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/53/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFavorites-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/52/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/77/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/75/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavUpload1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/98/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-10.8.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/104/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/63/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareOperationsToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/70/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavMove2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/93/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/79/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/106/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/102/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/105/1

2022-01-31 12:33 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiFederationToRoot2-10.8.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34463/107/1

2022-01-31 12:33 UTC, individual-it requested changes

2022-01-31 12:33 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +			__METHOD__ . " XML part does not have key 0. Expected a value at index 0 of 'xmlPart' but, found: " . $xmlpart[0]
```suggestion
			__METHOD__ . " XML part does not have key 0. Expected a value at index 0 of 'xmlPart' but, found: " . $xmlpart
```
the key does not exist if that assertion fires

2022-01-31 12:59 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34464/172/1

2022-01-31 13:44 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34466/172/1

2022-02-01 03:18 UTC, individual-it approved these changes

2022-02-01 03:44 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSharePublicLink1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34476/71/1

2022-02-01 04:02 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +			__METHOD__ . " last modified expression is not found in the XML. Expected 'xmlPart' to be an array but, found: " . $xmlpart
Tests fail now with `Notice: Array to string conversion in /drone/src/tests/TestHelpers/WebDavHelper.php line 707`
for e.g test tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature:9
see https://drone.owncloud.com/owncloud/core/34476/71/13

2022-02-01 06:06 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliBackground-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34478/114/1

2022-02-01 07:28 UTC, phil-davis approved these changes
LGTM. There have been other PRs merged to master this morning, so you might like to rebase this and let CI run, just to be sure that everything is OK. Then merge.

2022-02-01 08:29 UTC, phil-davis commented
@kiranparajuli589 you can mark "Ready for Review" and merge when you are ready. Then make the next oCIS commit id bump.

2022-02-01 09:21 UTC, phil-davis commented
"This branch is 1 commit ahead of master. " - looks good.

2022-02-01 09:55 UTC, kiranparajuli589 commented
test PR passed https://drone.owncloud.com/owncloud/ocis/9059

2022-02-01 09:55 UTC, merged