[test-only] Added spaces examples for suite apiWebdavOperations
owncloud/core pull request #39729
Opened 2022-01-28 11:20 UTC by SagarGi

## Description
 Added Spaces Example for suite apiWebdavOperations 

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/3049

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-01-28 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=39729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=39729) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=39729) it.</sub>

2022-01-28 11:42 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIUpload-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34452/151/1

2022-01-31 04:38 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavOperations-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34456/94/1

2022-01-31 08:21 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature
> +    Examples:
```suggestion
 @skipOnOcV10 @personalSpace
    Examples:
```

2022-01-31 08:25 UTC, saw-jan commented on tests/TestHelpers/WebDavHelper.php
> +
we may not need this change or do we?

2022-01-31 08:26 UTC, amrita-shrestha commented on tests/TestHelpers/WebDavHelper.php
> +
unnecessary line added

2022-01-31 08:26 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +
```suggestion


```

2022-01-31 08:26 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +
```suggestion


```

2022-01-31 08:26 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +
```suggestion


```

2022-01-31 09:24 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFile.feature
> +
```suggestion


```

2022-01-31 09:24 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
> +#      | dav_version | folder_name |
uncomment examples
```suggestion
     | dav_version | folder_name |
```

2022-01-31 09:24 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +			WebDavHelper::getDavPath($user, $this->getDavPathVersion(), "files", $spaceId);
Why this changes is done? Can $path for dav version old and new be set correct by this?

2022-01-31 09:30 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
> +
```suggestion
    Examples:
      | dav_version | folder_name |
      | old         | /fo.        |
      | old         | /fo.1       |
      | old         | /fo...1..   |
      | old         | /...        |
      | old         | /..fo       |
      | old         | /fo.xyz     |
      | old         | /fo.exe     |
      | new         | /fo.        |
      | new         | /fo.1       |
      | new         | /fo...1..   |
      | new         | /...        |
      | new         | /..fo       |
      | new         | /fo.xyz     |
      | new         | /fo.exe     |

```

2022-01-31 09:30 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
>  		$spaceId = null;
Please delete this line also

2022-02-03 05:22 UTC, kiranparajuli589 commented
sorry the [ci build](https://drone.owncloud.com/owncloud/core/34498) failed at `install-core` in several suites, build restarted

2022-02-03 08:57 UTC, kiranparajuli589 requested changes, later dismissed

2022-02-03 08:57 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +		} finally {
use `catch`

2022-02-03 08:57 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
> -      | old         | /fo.exe     |
good catch! :fishing_pole_and_fish: :+1:

2022-02-03 08:57 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +
remove this last line

2022-02-03 08:57 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavOperations/listFiles.feature
> +      | simple-folder/simple-empty-folder/                        |
:tophat:

2022-02-03 08:57 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
> +      | old         |
revert this please

2022-02-03 11:40 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +			WebDavHelper::getDavPath($user, $this->getDavPathVersion(), "files", $spaceId);
I think this changes affect 
apiFavorites/favorites.feature:117
apiFavorites/favorites.feature:143
apiFavorites/favorites.feature:268

2022-02-03 14:35 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebDav.php
> +			WebDavHelper::getDavPath($user, $this->getDavPathVersion(), "files", $spaceId);
ok i will check it.

2022-02-04 08:00 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-02-04 09:56 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +			WebDavHelper::getDavPath($user, $this->getDavPathVersion(), "files", $spaceId);
i had created issue for that bug https://github.com/owncloud/ocis/issues/3111

2022-02-07 05:58 UTC, phil-davis commented
Issue #39549 `webUIUpload/upload.feature:131` failed. Unrelated to this PR. I restarted CI.

2022-02-07 06:07 UTC, phil-davis approved these changes

2022-02-07 06:16 UTC, phil-davis commented
@SagarGi I just merged PR #39745 that @amrita-shrestha made last week. It had similar changes to `tests/acceptance/features/bootstrap/WebDav.php` `getFullDavFilesPath` but not quite the same.

Please rebase this PR and sort out if there are any more changes needed to `getFullDavFilesPath`, or if her changes are OK.

2022-02-07 09:16 UTC, phil-davis approved these changes

2022-02-07 09:20 UTC, merged