Add wnd.listen.reconnectAfterTime config sample
owncloud/core pull request #39732
Opened 2022-01-30 12:07 UTC by mmattel

## Description
Adding a config.apps.sample for wnd.
Necessary to do a `config-to-docs` run.

**DO NOT MERGE** before the referenced PR gets merged.

## Related Issue
- References: https://github.com/owncloud/windows_network_drive/pull/391 (Add config option to set the connection timeout)

## Motivation and Context
A config key has been added in WND

## How Has This Been Tested?
Not necessary

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: comes asap
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

@pmaier1 FYI

2022-01-30 12:10 UTC, mmattel commented
No changelog necessary, config sample only

2022-01-30 14:46 UTC, phil-davis approved these changes

2022-01-30 14:48 UTC, phil-davis commented
@mmattel I converted to draft so that it soes not accidentally get merged. you can easily click the "Ready to Review" button and merge when the time is right.

2022-01-31 10:22 UTC, IljaN requested changes
@pmaier1 Asked for a high-level description. Will provide shortly.

2022-01-31 11:16 UTC, IljaN commented
Add this sentence when merged:
https://github.com/owncloud/windows_network_drive/pull/392/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R135-R136

2022-01-31 13:43 UTC, IljaN approved these changes

2022-01-31 14:54 UTC, phil-davis approved these changes

2022-02-01 13:49 UTC, merged