[tests-only][full-ci]Add spaces tests for apiWebdavMove2 suite
owncloud/core pull request #39774
Opened 2022-02-09 06:36 UTC by amrita-shrestha

## Description
adds spaces DAV path on `apiWebdavMove2 ` suite

## Related Issue

- fixes https://github.com/owncloud/ocis/issues/3107

## How Has This Been Tested?

- Locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require an increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-02-09 08:13 UTC, kiranparajuli589 approved these changes

2022-02-09 08:13 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +			$davPathVersionToUse
can we directly use the `$this->getDavPathVersion()` function here?
it should also give a new DAV path as default.

2022-02-09 08:15 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +			$davPathVersionToUse
can we use the `$this->getDavPathVersion()` fn directly here?

2022-02-09 08:16 UTC, kiranparajuli589 commented
approved accidentally...sorry for the inconvenience!

2022-02-09 12:50 UTC, amrita-shrestha commented on tests/TestHelpers/WebDavHelper.php
> +			$davPathVersionToUse
$this->getDAVPathVersion() is in bootstrap folder .Upto now we didn't call bootstrap fuction from helper folder.But their is a way in php to do so.

2022-02-09 14:43 UTC, kiranparajuli589 requested changes, later dismissed

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> -  @files_sharing-app-required
hmm... :fishing_pole_and_fish:  folder test was in files feature :+1:

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> -      | #oc ab?cd=ef# |
this is also fine I think. if more example needed to be added for files, then another column can be easily added

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +
\n

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +
\n

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +
\n

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
> +
\n

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +    And parameter "shareapi_auto_accept_share" of app "core" has been set to "yes"
this step is not necessary for ocis tests.

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +      | dav_version | mover | dst-folder        |
```suggestion
      | dav_version | mover | destination-folder        |
```

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +      | dav_version | mover | dst-folder        |
`dst` :face_with_spiral_eyes:

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +      | dav_version | mover | src-folder        |
```suggestion
      | dav_version | mover | source-folder        |
```

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +      | dav_version | mover | src-folder        |
use the same separators, `-` or `_`
also, look for other occurrences in the file

2022-02-09 14:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +    And user "Brian" stores id of file "/Shares/folderA/ONE"
`ONE` is a folder.

2022-02-10 09:53 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
> +      | dav_version | mover | src-folder        |
done

2022-02-10 09:55 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +
done

2022-02-10 12:30 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
> +
done

2022-02-10 12:30 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavMove2/moveFile.feature
> +
done

2022-02-11 04:09 UTC, kiranparajuli589 reviewed
please also mention the reasons behind adding a new feature file `moveShareOnOcis.feature`
rest lgtm :+1:

2022-02-11 09:46 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-02-11 10:06 UTC, phil-davis approved these changes

2022-02-11 10:06 UTC, merged