[tests-only][full-ci]added then steps for apiMain suite
owncloud/core pull request #39828
Opened 2022-02-24 10:31 UTC by sushmita56

## Description
This PR adds ``` Then ``` steps to existing API test scenarios to better check the results of ``` When ``` steps.

### Suite Covered
- ``` apiMain ```

## Related Issues
- Part of https://github.com/owncloud/core/issues/39512

## How Has This Been Tested?
- Locally
- CI

## Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-02-25 04:11 UTC, phil-davis approved these changes

2022-02-25 04:19 UTC, phil-davis commented
@sushmita56 are you finished? Is this ready?

2022-02-28 03:53 UTC, sushmita56 commented
Yes, it is.

2022-02-28 04:03 UTC, kiranparajuli589 requested changes

2022-02-28 04:03 UTC, kiranparajuli589 commented on tests/acceptance/features/apiMain/checksums-TestOc10Issue38835.feature
>      And user "Brian" uploads file with checksum "SHA1:ce5582148c6f0c1282335b87df5ed4be4b781399" and content "Some Text" to "/Shares/myChecksumFile.txt" using the WebDAV API
IMO, these 3 when steps are likely to be given steps

2022-02-28 08:45 UTC, phil-davis approved these changes

2022-02-28 10:13 UTC, kiranparajuli589 approved these changes

2022-02-28 10:13 UTC, merged