added then steps for apiShareCreateSpecialToRoot1 suite
owncloud/core pull request #39861
Opened 2022-03-10 08:07 UTC by sushmita56

## Description
This PR adds ``` Then ``` steps to existing API test scenarios to better check the results of ``` When ``` steps.

### Suite Covered
- ```apiShareCreateSpecialToRoot1```

## Related Issues
- Part of https://github.com/owncloud/core/issues/39512

## How Has This Been Tested?
- Locally
- CI

## Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-03-10 08:46 UTC, kiranparajuli589 submitted a review, later dismissed

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      Then the fields of the last response to user "Alice" sharing with user "Brian" should include
```suggestion
    And the fields of the last response to user "Alice" sharing with user "Brian" should include
```

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      Then the fields of the last response to user "Alice" should include
```suggestion
    And the fields of the last response to user "Alice" should include
```

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      Then the fields of the last response to user "Alice" should include
```suggestion
    And the fields of the last response to user "Alice" should include
```

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    # And the OCS status code should be "404"
can be removed or?

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareUniqueReceivedNames.feature
>      Then user "Carol" should see the following elements
```suggestion
    And user "Carol" should see the following elements
```

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/AppConfigurationContext.php
> +	}
please also add a check here to ensure the modification has actually been made

2022-03-10 08:46 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Sharing.php
> +	}
here too, a check to ensure the action (share is actually created or not) is `must` for `Given` steps.

2022-03-10 19:18 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And user "Alice" has created a share using the sharing API with settings
```suggestion
    And user "Alice" has created a share with settings
```

2022-03-10 19:18 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And user "Alice" has created a share using the sharing API with settings
```suggestion
    And user "Alice" has created a share with settings
```

2022-03-10 19:19 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And user "Alice" has created a share using the sharing API with settings
```suggestion
    And user "Alice" has created a share with settings
```

2022-03-10 19:19 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And user "Alice" has created a share using the sharing API with settings
```suggestion
    And user "Alice" has created a share with settings
```

2022-03-10 19:21 UTC, grgprarup commented on tests/acceptance/features/bootstrap/Sharing.php
> +	}
`Step` for this is already implemented below this line

2022-03-10 19:22 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And the administrator has set parameter "shareapi_default_expire_date_user_share" of app "core" to "no"
```suggestion
    And parameter "shareapi_default_expire_date_user_share" of app "core" has been set to "no"
```

2022-03-10 19:23 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And the administrator has set parameter "shareapi_default_expire_date_user_share" of app "core" to "no"
```suggestion
        And parameter "shareapi_default_expire_date_user_share" of app "core" has been set to "no"
```

2022-03-10 19:25 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And the administrator sets parameter "shareapi_default_expire_date_group_share" of app "core" to "no"
```suggestion
     And parameter "shareapi_default_expire_date_user_share" of app "core" has been set to "no"
```

2022-03-10 19:25 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And the administrator has set parameter "shareapi_default_expire_date_group_share" of app "core" to "no"
```suggestion
    And parameter "shareapi_default_expire_date_user_share" of app "core" has been set to "no"
```

2022-03-10 19:30 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    Then the OCS status code of responses on all endpoints should be "<http_status_code>"
```suggestion
    Then the OCS status code of responses on all endpoints should be "<ocs_status_code>"
```

2022-03-10 19:30 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +      | ocs_api_version | http_status_code |
```suggestion
      | ocs_api_version | ocs_status_code |
```

2022-03-10 19:31 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    Then the OCS status code of responses on all endpoints should be "<http_status_code>"
```suggestion
    Then the OCS status code of responses on all endpoints should be "<ocs_status_code>"
```

2022-03-10 19:31 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +      | ocs_api_version | http_status_code |
```suggestion
      | ocs_api_version | ocs_status_code |
```

2022-03-10 19:39 UTC, grgprarup commented on tests/acceptance/features/bootstrap/AppConfigurationContext.php
> +	}
This `Step` is already implemented.

2022-03-11 05:25 UTC, grgprarup reviewed
Changes to be made

2022-03-11 11:07 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
```suggestion
    And parameter "shareapi_expire_after_n_days_user_share" of app "core" has been set to "40"
    When user "Alice" gets the info of the last share using the sharing API
```

2022-03-11 11:13 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
```suggestion
    And parameter "shareapi_expire_after_n_days_user_share" of app "core" has been set to "15"
    When user "Alice" gets the info of the last share using the sharing API
```

2022-03-11 11:14 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
```suggestion
    And parameter "shareapi_expire_after_n_days_group_share" of app "core" has been set to "40"
    When user "Alice" gets the info of the last share using the sharing API
```

2022-03-11 11:18 UTC, grgprarup commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
```suggestion
    And user "Alice" has shared file "textfile0.txt" with group "grp1" with permissions "read,share"
    And parameter "shareapi_expire_after_n_days_group_share" of app "core" has been set to "15"
    When user "Alice" gets the info of the last share using the sharing API
```

2022-03-14 07:41 UTC, kiranparajuli589 commented
@sushmita56 @grgprarup these discussed tests mostly involves
- admin set some config (definitely given step)
- user creates a share (definitely given step)
- admins change some config (i think this should be when, as this step is actually changing some state, which we want to react after)
- user queries for the last share (this is just a helper to get data from the server for our then assertion, so if this can be handled from then step then it would be great.)
- share details assertions (definitely then step)

any comments, thoughts? cc @phil-davis

2022-03-15 05:59 UTC, phil-davis commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And the fields of the last response to user "Alice" sharing with user "Brian" should include
```suggestion
    When the administrator sets parameter "shareapi_default_expire_date_user_share" of app "core" to "no"
    Then the info about the last share by user "Alice" sharing with user "Brian" should include
```

The step `Then the info about the last share by user "Alice" sharing with user "Brian" should include` could be a new `Then` step that does:
- sharing API request to get the info
- checks that the HTTP and OCS statuses are reasonable
- checks the items in the table

The new step could just call the 4 methods that are the existing 4 steps that it "summarizes".

What do we think? Do something like this pattern for the other scenarios?

2022-03-15 06:00 UTC, phil-davis commented
> any comments, thoughts?

I made a suggestion in comment https://github.com/owncloud/core/pull/39861/files#r826605713

2022-03-15 07:37 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
> +    And the fields of the last response to user "Alice" sharing with user "Brian" should include
seems reasonable :+1:

2022-03-21 10:42 UTC, phil-davis commented
@saw-jan and @sushmita56 there are some comments above. The code can be adjusted as per the comments, then we can discuss and review again. (Or make more comments to discuss...) But priority is not high.

2022-03-24 06:59 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
```suggestion
```
I think you don't need this step.

2022-03-24 06:59 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" gets the info of the last share using the sharing API
You might not need the step `And user "Alice" gets the info of the last share using the sharing API` here either
```suggestion
```

2022-03-24 06:59 UTC, Talank commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" gets the info of the last share using the sharing API
same here

2022-03-24 07:33 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    And the OCS status code should be "100"
can be checked from then step.

2022-03-24 07:33 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    Then the HTTP status code should be "403"
then step assertion can be added after status code. and also same applies in case with brian.

2022-03-24 07:33 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>      @skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0 @issue-2440
Here as well !!

2022-03-24 07:33 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>      @skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0 @issue-2440
same here.

2022-03-24 10:00 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>      @skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0 @issue-2440
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    Then the HTTP status code should be "403"
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    And the OCS status code should be "100"
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" gets the info of the last share using the sharing API
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Alice" gets the info of the last share using the sharing API
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:01 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
>      And user "Alice" gets the info of the last share using the sharing API
not related to this suite. I've removed all changes from this feature.

2022-03-24 10:39 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
> +      | ocs_status_code | <<ocs_status_code> |
```suggestion
      | ocs_status_code | <<ocs_status_code>>|
```

2022-03-24 10:40 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$this->theHTTPStatusCodeShouldBeSuccess();
```suggestion
		$this->theHTTPStatusCodeShouldBe('200');
```

2022-03-24 10:47 UTC, SagarGi commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    And user "Alice" accepts share "<path>" offered by user "Carol" using the sharing API
@kiranparajuli589  can we check response for all these requests if possible?

2022-03-24 10:56 UTC, amrita-shrestha commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
>      And user "Brian" has uploaded file with content "First data" to "/randomfile.txt"
I think we should clear HTTP status code array in this given step

2022-03-24 10:56 UTC, amrita-shrestha commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
> +      | ocs_status_code | <<ocs_status_code>> |
we can put ocs status code inside function rather than passing from step

2022-03-24 10:56 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/Sharing.php
> +	/**
i think we can just add  @Then /^user "([^"]*)" should be able to accept pending share "([^"]*)" offered by user "([^"]*)"$/
in existing @Given /^user "([^"]*)" has accepted the (?:first|next|) pending share "([^"]*)" offered by user "([^"]*)"$/ step

2022-03-24 11:14 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
> +      | ocs_status_code | <<ocs_status_code> |
not included in this PR now.

2022-03-25 14:57 UTC, amrita-shrestha commented on tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
> +    And the HTTP status code should be "200"
```suggestion
    Then the OCS status code of responses on all endpoints should be "100"
    And the HTTP status code of responses on all endpoints should be "200"
```

2022-03-28 05:20 UTC, amrita-shrestha reviewed
lgtm

2022-03-28 06:47 UTC, SagarGi reviewed
lgtm as well

2022-03-28 08:04 UTC, individual-it requested changes

2022-03-28 08:04 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
>      And as "Alice" file "/Shares/child1/child2/rename.txt" should exist
But `rename2.txt` should not exist

2022-03-28 08:04 UTC, individual-it commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$this->userHasAcceptedThePendingShareOfferedBy($user, $share, $offeredBy);
how do we check that this was successful?

2022-03-28 09:38 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Sharing.php
> +		$this->userHasAcceptedThePendingShareOfferedBy($user, $share, $offeredBy);
HTTP and OCS status codes are checked underneath.

2022-03-28 10:47 UTC, individual-it requested changes
a lot of failures now :-(

2022-04-04 06:23 UTC, individual-it requested changes

2022-04-04 06:23 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    When user "Brian" creates folder "/Shares/child1/fo1" using the WebDAV API
what about using `Then user "Brian" should be able to create folder "/Shares/child1/fo1"` in those cases, then we would avoid Then->when->Then chains

2022-04-04 08:15 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    When user "Brian" creates folder "/Shares/child1/fo1" using the WebDAV API
fixed

2022-04-04 11:05 UTC, individual-it requested changes
I've pointed out some more cases where we should be keeping on using the original steps.
Why changing an existing nice Then step and splitting it into 3 When-Then-And steps

Same applies to a lot of other places in this PR

2022-04-04 11:05 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    Then the HTTP status code should be "403"
` should not be able to create folder`

2022-04-04 11:05 UTC, individual-it commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> +    Then the HTTP status code should be "201"
`should be able to rename file`

2022-04-04 12:52 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> -    And user "Brian" should be able to delete file "Shares/parent/child/lorem.txt"
as brian folder `Shares/parent` does not exist, so delete action is impossible to perform for files within that.

2022-04-04 13:14 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Sharing.php
> +	/**
fixed

2022-04-04 13:22 UTC, kiranparajuli589 commented on tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
> -    And user "Brian" should be able to delete file "Shares/parent/child/lorem.txt"
For user brian, `Shares/parent` should not exist, then how can he delete the file inside `Shares/parent`?

2022-04-06 06:12 UTC, kiranparajuli589 commented
@individual-it can you please have a look at this again.

2022-04-06 07:15 UTC, individual-it approved these changes

2022-04-06 07:15 UTC, individual-it commented
@kiranparajuli589 LGTM, please squash the commits

2022-04-06 07:41 UTC, merged