replace userid with username in login form
owncloud/core pull request #39870
Opened 2022-03-11 07:44 UTC by butonic

While digging into https://github.com/owncloud/oauth2/issues/326 @kulmann @TheOneRing and I pondered possible solutions to the original problem described in https://github.com/owncloud/oauth2/pull/286

AFAIU the problem is that users may see the LDAP UUID of a user in the login form, which is very confusing. The solution in https://github.com/owncloud/oauth2/pull/286 replaced the user *id* that clients picked up with the user *name*, but that parameter was originally only [intended to be used for mounting windows network drives](https://github.com/owncloud/core/pull/32587).

We tried various combinations of filling the `user` parameter un redirect and logout URLs produced by the oauth2 app and even found a bug where a redirect URL is not urlencoded. That will be followed up as a separate issue.

With this PR a `user` parameter will be replaced with the user name when a user with the given user id is found.

For users without a username this has no sideeffect, as the username falls back to the user id.

2022-03-11 07:52 UTC, DeepDiver1975 requested changes, later dismissed

2022-03-11 07:52 UTC, DeepDiver1975 commented on core/Controller/LoginController.php
> +				$parameters['loginName'] = $u->getUserName();
check if getUserName() returns null or false ..... possible in the code paths as far as my analysis goes ....

2022-03-11 11:20 UTC, butonic commented
maybe we should introduce a login_hint parameter?

2022-06-17 13:53 UTC, mmattel commented
@butonic we need a changelog, then we also see if ci loves you more than before 😄

2022-06-20 15:23 UTC, mmattel commented
@phil-davis mind to help?
I have rebased the PR because CI killed itself post the former push of @butonic. Some but not all phpunit tests complain about: `...was not expected to be called more than once.`

2022-06-20 15:57 UTC, phil-davis commented
> Some but not all phpunit tests complain about

Fixed - the new code can end up calling userManager "get" twice in some cases.

2022-06-21 09:18 UTC, mmattel commented
@DeepDiver1975 mind to have a look on it? The change you requested has been implemented and CI is green now

2022-06-30 17:27 UTC, mmattel commented
@DeepDiver1975 sorry for pinging again, but could be a quick win as all is green.

2022-07-07 10:08 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
This is definitely an accident and should be removed!

2022-07-07 10:10 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
I will fix it...

2022-07-07 10:16 UTC, phil-davis commented on .htaccess
> +#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
Fixed

2022-07-07 10:17 UTC, phil-davis commented
@jvillafanez I fixed my mistake, and rebased. CI is running. Please review and take over any needed code changes.

2022-07-07 10:18 UTC, jvillafanez approved these changes

2022-07-07 11:06 UTC, merged

2022-09-09 10:20 UTC, jnweiger commented
Confirmed fixed in oc 10.11.0-rc.1 using user_ldap 0.16.0 and oauth2-0.5.3

No uuid identifier seen anywhere! Thanks!