Improve FileDrop view
owncloud/core pull request #39900
Opened 2022-03-18 14:15 UTC by ChrisEdS

## Description
Small changes in design and in keeping the FileDrop view for Public Links.

- The font is bigger and thicker
- Separator lines were inserted
- The text in the "Dropbox" is wrapped properly, line-height was removed

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39899

## Motivation and Context
You should see immediately that something has changed in the UI after the first file is completely uploaded so that you are not tempted to upload files twice.

## How Has This Been Tested?

- Manually tested in Chrome and Firefox
- ...

## Screenshots:
Before:

<img width="600" alt="Screenshot 2022-03-18 at 13 41 54" src="https://user-images.githubusercontent.com/33026403/159018836-3d611f12-1073-4d39-ad66-8b3dcab63205.png">

After:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/33026403/159018873-1498094a-2bb2-4cce-9371-26567a3c73e2.png">

On small resolution:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/33026403/159018927-55b36ce4-2c87-4069-a9d5-ac8c69807252.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-03-18 15:06 UTC, JanAckermann requested changes

2022-03-18 15:06 UTC, JanAckermann commented on apps/files_sharing/js/PublicUploadView.js
> +		'        <hr>' +
Can you check, if there will be `<li>` items rendered inside the `<ul>`? otherwise, you'd need to change that in the js code.

You might also think about giving the `<ul>` a border top and bottom instead of having an `<hr>`

2022-03-18 15:07 UTC, ChrisEdS commented on apps/files_sharing/js/PublicUploadView.js
> +		'        <hr>' +
Yeah, great idea. I will try that approach.

2022-03-18 15:40 UTC, JanAckermann approved these changes

2022-03-18 15:40 UTC, JanAckermann commented on apps/files_sharing/js/PublicUploadView.js
> -
Is this change necessary? Other than that: LGTM

2022-03-18 15:44 UTC, ChrisEdS commented on apps/files_sharing/js/PublicUploadView.js
> -
Nope. My Atom does weird things. Let me fix that.

2022-03-21 03:50 UTC, phil-davis approved these changes
works for me

2022-03-21 03:50 UTC, merged

2022-03-21 07:57 UTC, tbsbdr commented
uha, nice :-)
if you ask for further improvement, you could also add:
- communicate the uploaded files more as a succes, eg. by adding checkmarks to them ✅
- within the drop-zone, add a very short headline above the instructional line, eg. "**Upload**"

<img width="972" alt="image" src="https://user-images.githubusercontent.com/26610733/159222251-185ff705-79b1-4c99-9427-7e3e7889916b.png">