[tests-only][full-ci]Improve then steps usages inside acceptance tests suite apiTrashbin
owncloud/core pull request #39925
Opened 2022-03-25 10:55 UTC by SagarGi

## Description
This PR adds `Then` steps to existing API test scenarios to better check the results of `When` steps.

**Suites covered:**
- `apiTrashbin`

## Related Issue

- Part of https://github.com/owncloud/core/issues/39512

## How Has This Been Tested?

- Locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-03-28 06:32 UTC, kiranparajuli589 commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      And as "Alice" file "<filename2>" should exist in the trashbin
these are `then` steps and are not necessary for the scenario.
can you please remove it?

2022-03-28 06:32 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->verifyTableNodeColumns($table, ["path","content"]);
```suggestion
		$this->verifyTableNodeColumns($table, ["path", "content"]);
```

2022-03-28 06:32 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		return $fileIds;
where are you returning these `fileIds`?

2022-03-28 07:40 UTC, amrita-shrestha commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      And as "Alice" the file with original path "<filename2>" should not exist in the trashbin
```suggestion
And as "Alice" the files with following original paths should not exist in the trashbin
```

2022-03-28 07:40 UTC, amrita-shrestha commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      And as "Alice" the file with original path "/PARENT/CHILD/child.txt" should not exist in the trashbin
```suggestion
And as "Alice" the files with following original paths should not exist in the trashbin
```

2022-03-28 07:40 UTC, amrita-shrestha commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      And as "Alice" the file with original path "/PARENT/child.txt" should exist in the trashbin
```suggestion
But as "Alice" the files with following original paths should exist in the trashbin
```

2022-03-28 07:51 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
I think  emptyLastHTTPStatusCodesArray() should be in **Given** step rather **When** when step because we use **When** step with other **When** step and it will eventually delete before **When** step HTTP status in array

2022-03-28 07:51 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
I think  emptyLastHTTPStatusCodesArray() should be in **Given** step rather **When** when step because we use **When** step with other **When** step and it will eventually delete before **When** step HTTP status in array

2022-03-28 10:11 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
we don't push HTTP status array in this function so we don't need to empty it

2022-03-28 10:11 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
i think we don't need this emptyLastHTTPStatusCodesArray() func here because pushHTTPStatusCode() in not used here

2022-03-28 10:11 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
we don't need this $this->emptyLastHTTPStatusCodesArray();

2022-03-28 10:35 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->emptyLastHTTPStatusCodesArray();
@amrita-shrestha its the given step that empty's the `https status code` before when step starts. you mentioned to keep it in then step rather than when step. Though it does not  push https status code but its safe to keep because some time there might be other then step `pushng https status code`.

2022-03-28 10:46 UTC, kiranparajuli589 reviewed
other than the existing comments, lgtm :+1:

2022-03-29 03:38 UTC, amrita-shrestha reviewed
lgtm

2022-03-29 07:30 UTC, individual-it requested changes
just a small issue

2022-03-29 07:30 UTC, individual-it commented on tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
>      Then as "Alice" file "sample,1.txt" should exist in the trashbin
```suggestion
    Then the HTTP status code should be "204"
    And as "Alice" file "sample,1.txt" should exist in the trashbin
```

2022-04-05 09:58 UTC, grgprarup commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      Then as "Alice" the file with original path "<filename1>" should not exist in the trashbin
```suggestion
    And as "Alice" the file with original path "<filename1>" should not exist in the trashbin
```

2022-04-05 09:59 UTC, grgprarup commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
>      Then as "Alice" the file with original path "/PARENT/textfile0.txt" should not exist in the trashbin
```suggestion
    And as "Alice" the file with original path "/PARENT/textfile0.txt" should not exist in the trashbin
```

2022-04-05 11:33 UTC, SwikritiT commented on tests/acceptance/features/apiTrashbin/trashbinSkip.feature
> +      | PARENT/lorem.dat |
As discussed maybe use the steps rather that data table here

2022-04-05 11:34 UTC, SwikritiT commented on tests/acceptance/features/apiTrashbin/trashbinSkip.feature
> +      | PARENT/sample.dat |
As discussed maybe use the steps rather that data table here

2022-04-06 06:11 UTC, kiranparajuli589 commented
@individual-it can you please have a look at this again

2022-04-06 07:17 UTC, individual-it approved these changes

2022-04-06 07:17 UTC, individual-it commented on tests/acceptance/features/apiTrashbin/trashbinDelete.feature
> +    Given using <dav-path> DAV path
good catch!

2022-04-06 07:18 UTC, individual-it commented
@SagarGi please squash both commits before merging

2022-04-06 07:43 UTC, merged

2022-04-06 07:43 UTC, kiranparajuli589 commented
> @SagarGi please squash both commits before merging

squashed and merged.