[tests-only] run ci with graph api enabled for users/group provisioning
owncloud/core pull request #39927
Opened 2022-03-28 07:59 UTC by kiranparajuli589

2022-03-31 12:55 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiAuthOcs-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35146/48
<!-- id: pr-39927 -->

2022-04-11 15:15 UTC, micbar commented
https://github.com/owncloud/ocis/pull/3507 was merged. should be unblocked now.

2022-04-12 08:28 UTC, saw-jan commented on tests/acceptance/features/bootstrap/bootstrap.php
> +);
Maybe only load classes from ocis if `PATH_TO_OCIS` is provided?

2022-04-12 08:29 UTC, saw-jan commented on tests/acceptance/features/bootstrap/bootstrap.php
> +}
This doesn't seem right. WIll I have ocis on that path?

2022-04-12 08:34 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/bootstrap.php
> +);
done!

2022-04-12 09:01 UTC, saw-jan commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			$groups = $this->graphContext->adminHasRetrievedGroupListUsingTheGraphApi();
just to make consistent
```suggestion
		$useGraph = OcisHelper::isTestingWithGraphApi();
		if ($useGraph) {
			$groups = $this->graphContext->adminHasRetrievedGroupListUsingTheGraphApi();
```

2022-04-12 09:04 UTC, saw-jan commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			// TODO: user do not belong in group
what to do here later?

2022-04-12 09:51 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +			// TODO: user do not belong in group
todo is already done here :)

2022-04-12 11:25 UTC, kiranparajuli589 commented
tests that crashes ocis server because of https://github.com/owncloud/ocis/issues/3483 are skipped in this PR.

2022-04-13 05:56 UTC, individual-it requested changes
big accomplishment!
Just minor comments

2022-04-13 05:56 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getAttributeOfCreatedUser(string $user, string $attribute) {
unused function?

2022-04-13 05:56 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getAttributeOfCreatedGroup(string $group, string $attribute) {
name should indicate that this is for the graph api, or maybe move to GraphHelper

2022-04-13 05:56 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				}
could be moved to GraphHelper

2022-04-13 05:56 UTC, individual-it commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				// https://github.com/owncloud/ocis/issues/3516
if this is a bug, why not just let it explode with ServerException?

2022-04-13 06:58 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getAttributeOfCreatedUser(string $user, string $attribute) {
For now, it is used by `GraphContext` to get the id of the created users.

2022-04-13 07:00 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +	public function getAttributeOfCreatedGroup(string $group, string $attribute) {
this can be used with any API system. If we move it to graphHelper, then `createdGroups` list should be provided as parameter, which will be more complicated imo.

2022-04-13 07:06 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				}
fixed

2022-04-13 07:06 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/Provisioning.php
> +				// https://github.com/owncloud/ocis/issues/3516
fixed

2022-04-13 07:24 UTC, individual-it approved these changes

2022-04-13 07:55 UTC, ScharfViktor approved these changes
cool work))

2022-04-13 08:50 UTC, merged

2022-04-13 08:52 UTC, kiranparajuli589 commented
the commit id will be bumped in https://github.com/owncloud/ocis/pull/3404