[tests-only] decode href value before assertions
owncloud/core pull request #39947
Opened 2022-04-04 11:41 UTC by kiranparajuli589

## Description
- decode href value before making assertions
- do not assert href using regex pattern

## Related Issue

- https://github.com/cs3org/reva/pull/2658

## Motivation and Context
https://github.com/cs3org/reva/pull/2658#issuecomment-1087259710

## How Has This Been Tested?

- :robot: 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-04-04 12:40 UTC, C0rby approved these changes
Looks good to me! :+1:

2022-04-05 04:15 UTC, kiranparajuli589 commented
still need to make changes for spaces webdav.

2022-04-05 04:21 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
> +			// for files decoded value will be like: "/owncloud/core/remote.php/ebdav/strängé folder/file.txt"
```suggestion
			// for files decoded value will be like: "/owncloud/core/remote.php/webdav/strängé folder/file.txt"
```

2022-04-05 04:24 UTC, individual-it requested changes
does not work for spaces, see 
https://github.com/cs3org/reva/pull/2658#issuecomment-1088250121

(just to make sure this is not accidentally merged)

2022-04-05 05:51 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
> +			// for files decoded value will be like: "/owncloud/core/remote.php/ebdav/strängé folder/file.txt"
fixed

2022-04-05 09:28 UTC, individual-it approved these changes

2022-04-05 09:28 UTC, individual-it commented on tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
> +    @skipOnOcV10.3 @skipOnOcV10.4.0 @issue-ocis-reva-217
why this change?

2022-04-05 09:29 UTC, merged