[tests-only][full-ci] Improve Then step in apiWebdavEtagPropagation1 suite
owncloud/core pull request #39944
Opened 2022-04-04 04:10 UTC by amrita-shrestha

## Description
This PR adds `Then` steps to existing API test scenarios to better check the results of the `When` steps.

**Suites covered:**
- `apiWebdavEtagPropagation1`

## Related Issue

- Part of https://github.com/owncloud/core/issues/39512

## How Has This Been Tested?

- Locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-04-04 06:07 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-04-04 06:31 UTC, grgprarup reviewed
LGTM :+1:

2022-04-04 10:58 UTC, individual-it requested changes

2022-04-04 10:58 UTC, individual-it commented on tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
> +    And as "Alice" file "/upload/sub/file.txt" should not exist
I don't think these changes are needed.
Here were are testing that the etags are changed, the fact that the code is correct after deleting and the file/folder is gone should be tested in other tests.

Same applies to most of the other tests below

2022-04-05 11:41 UTC, SwikritiT reviewed
LGTM

2022-04-06 07:19 UTC, individual-it approved these changes

2022-04-06 07:20 UTC, merged