Limit the width of the form on login page
owncloud/core pull request #39962
Opened 2022-04-07 12:42 UTC by ChrisEdS

## Description
The login form breaks if error messages and info messages are longer.

## Related Issue

- Fixes [<issue_link>](https://github.com/owncloud/core/issues/39961)

## How Has This Been Tested?

- Manually tested

## Screenshots:
Before:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/33026403/162200576-75d28df6-6a73-489e-a89a-499230dc95c2.png">

After:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/33026403/162200661-29d3aef8-e379-48e7-9990-e18658a48a86.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-04-07 12:44 UTC, JanAckermann requested changes
Please add a changelog item

2022-04-07 12:49 UTC, JanAckermann approved these changes

2022-04-07 15:01 UTC, phil-davis approved these changes

2022-04-07 15:02 UTC, merged

2022-05-13 08:24 UTC, jnweiger commented
Confirmed fixed in 10.10.0 RC2