Do not invalidate app tokens in case LDAP connection is temporary una…
owncloud/core pull request #40152
Opened 2022-06-20 09:03 UTC by pako81

…vailable

## Description

App tokens are getting deleted in case LDAP connection is temporary not available.

## Related Issue

- https://github.com/owncloud/enterprise/issues/5221

## Motivation and Context

Whenever connection to the LDAP server becomes unavailable app tokens are getting deleted after some minutes causing disconnection of connected clients.

## How Has This Been Tested?

1. Create an app token over /settings/personal?sectionid=security and use it to connect a desktop client
2. Deliberately cutting connection to the LDAP server;
--> without this fix: app token is getting deleted after some minutes causing disconnection of the desktop client
--> with this fix: app token is still valid till connection is back.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised

2022-06-20 17:30 UTC, ho4ho requested changes

2022-06-20 17:30 UTC, ho4ho commented on CHANGELOG.md
> +* Bugfix - Do not invalidate app tokens in case LDAP connection is temporary unavailable: [#40152](https://github.com/owncloud/core/pull/40152)
Thinking should done be differently:

https://github.com/owncloud/core/tree/master/changelog#create-changelog-items

2022-06-21 02:55 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/36099/10/7
```
There was 1 error:

1) Test\User\SessionTest::testValidateSessionDisabledUser
Error: Call to a member function getBackendClassName() on null

/drone/src/lib/private/User/Session.php:858
/drone/src/lib/private/User/Session.php:938
/drone/src/lib/private/User/Session.php:266
/drone/src/tests/lib/User/SessionTest.php:1058
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

--

There was 1 failure:

1) Test\User\SessionTest::testGetUser
Expectation failed for method name is "get" when invoked zero or more times
Parameter 0 for invocation OC\User\Manager::get(null, false) does not match expected value.
Failed asserting that null matches expected 'user123'.

/drone/src/lib/private/User/Session.php:857
/drone/src/lib/private/User/Session.php:938
/drone/src/lib/private/User/Session.php:266
/drone/src/tests/lib/User/SessionTest.php:149
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97
```
PHP unit tests need to be sorted out. Acceptance tests are passing, so there is no obvious end-user regression.

2022-06-22 16:39 UTC, IljaN approved these changes

2022-06-22 17:59 UTC, merged