Refactor expected failure closed issue
owncloud/core pull request #40392
Opened 2022-09-29 10:08 UTC by amrita-shrestha

## Description

This PR refactor scenario in closed issue to work 

## Related Issue

- [ ] https://github.com/owncloud/ocis/issues/4684
- [ ] https://github.com/owncloud/ocis/issues/4685
- [ ] https://github.com/owncloud/ocis/issues/4686
- [ ] https://github.com/owncloud/ocis/issues/4687

## Motivation and Context

## How Has This Been Tested?

- locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-09-29 10:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiWebdavOperations/listFiles.feature
> -
As before discussion 
>  > Is there any way to access public link resources by public users using the spaces WebDAV API?

> They can only be accessed via the WebDAV endpoint with the link token.

Visit this link for detail info : https://github.com/owncloud/ocis/issues/3085#issuecomment-1183442020

2022-09-30 04:10 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			throw new Exception('Target File' . $targetFile . ' could not be found');
```suggestion
			throw new Exception('Target File ' . $targetFile . ' could not be found');
```
Meybe we need a space here too?

2022-09-30 04:10 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 *
Don't we already have a similar step?

2022-09-30 04:11 UTC, SwikritiT commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
Why remove this step?

2022-09-30 07:07 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
In CI, we store ocis binary in the cache. This file checks the content of the robot.txt file in the ` services/web/assets/robot.txt` path which is not cached currently. So this step fails.

2022-09-30 07:07 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 *
No we don't have similar step

2022-09-30 08:20 UTC, saw-jan commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
@SagarGi might have some idea. I remember him working with tests related to robots.txt

2022-09-30 08:26 UTC, SagarGi commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
@SwikritiT the robot.txt file is generated when ocis is build. Thats why the tests fail as @amrita-shrestha said CI only store ocis binary in the cache where that file is not presented.
If this is not possible in CI for ocis, we can skip only on ocis because this feature runs in core. Please uncomment and skip the scenario on ocis.

2022-09-30 08:39 UTC, SwikritiT commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
we can add a separate scenario for OCIS with this step and skip it on oc10 and the current scenario can run in oc10 but skipped on OCIS

2022-09-30 08:40 UTC, SagarGi commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
@amrita-shrestha  NOTE: If we donot run this on ocis then we have to clean up related test code for ocis.

2022-09-30 08:40 UTC, SagarGi commented on tests/acceptance/features/apiMain/main.feature
> +      """
why is this added here?

2022-09-30 08:40 UTC, SagarGi commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
The main motive of this step is to check the content from API request with content of locally available `robot.txt`

2022-09-30 08:40 UTC, SagarGi commented on tests/acceptance/features/apiMain/main.feature
> +    And the content of the requested file in the response should be
We have to check the content of the file with API to the file available locally. Thats why we have specified path where that file is located.

2022-09-30 08:44 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 *
Does this step also work for this? Please check
https://github.com/owncloud/core/blob/c9f455278f3e6128f17724dede0c47d717851073/tests/acceptance/features/bootstrap/WebDav.php#L1153-L1161

2022-10-10 07:13 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> -    And the content in the response should match with the content of file "robots.txt" in the server root
@SagarGi @SwikritiT @saw-jan as discussed with Artur we are not going to skip the test in ocis.All the refactoring has been done after a discussion with Artur

2022-10-10 07:17 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +    And the content of the requested file in the response should be
Up to my knowledge and discussion with Artur. The motive of this scenario is to check whether we can get the content of the robot.txt with the help of API call. Locally build robots.txt file is only used to match the API response.

2022-10-10 07:19 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +      """
> @amrita-shrestha NOTE: If we donot run this on ocis then we have to clean up related test code for ocis.
 
@SagarGi as discussed with Artur we are not going to skip the test in ocis.All the refactoring has been done after a discussion with Artur

2022-10-10 07:20 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +      """
> why is this added here? 

@SagarGi please elaborate on your question.

2022-10-10 08:22 UTC, amrita-shrestha commented
@individual-it  could we add two different tests scenario for ocis and oc10 like @SwikritiT  suggested 
> we can add a separate scenario for OCIS with this step and skip it on oc10 and the current scenario can run in oc10 but skipped on OCIS

2022-10-10 12:11 UTC, saw-jan commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 *
@amrita-shrestha This can be utilized, I guess

2022-10-10 12:14 UTC, saw-jan commented on tests/acceptance/features/apiMain/main.feature
> +    And the content of the requested file in the response should be
I also believe that the main motive is just to check the accessibility of `robots.txt`.
I think it's fine if that works both for oC10 and oCIS.

2022-10-12 04:03 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 *
@saw-jan and @SwikritiT this step could not be utilized because the response is in the form of multiline. But i found next step 
```   
 Then if the HTTP status code was "200" then the downloaded content for multipart byterange should be:
      """
      User-agent: *
      Disallow: /
      """
```

2022-10-12 04:59 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/FeatureContext.php
> -
Removed because this step has been removed from feature file

2022-10-12 05:55 UTC, kiranparajuli589 commented on tests/acceptance/features/apiMain/main.feature
> +    Then if the HTTP status code was "200" then the downloaded content for multipart byterange should be:
what if the status code is not 200? will the test fail here?

2022-10-12 05:55 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +						return $multistatusResult;
nice catch, i was also running into trouble because of this :fishing_pole_and_fish:

2022-10-12 06:40 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +    Then if the HTTP status code was "200" then the downloaded content for multipart byterange should be:
nice catch bro. This step was not structured to throw error if HTTP status code was not as expected

2022-10-12 07:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->theHTTPStatusCodeShouldBe($statusCode);
I don't think this status code check should go inside this function. Only content check should go in this. What do you think?

2022-10-12 07:52 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->downloadedContentShouldBe($content);
why is this status code check fn also checking the content? this is confusing. maybe fix this while you're at it.

2022-10-12 08:07 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->theHTTPStatusCodeShouldBe($statusCode);
It depends upon what our principle is. In the coding sense and reuse sense it doesn't affect much. I don't think checking both in one step affects much. Can you elaborate on the reason behind not checking the HTTP status code with download content

2022-10-12 10:11 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +		$this->theHTTPStatusCodeShouldBe($statusCode);
just because of the function name ;)

2022-10-12 10:41 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +    And if the HTTP status code was "200" then the downloaded content for multipart byterange should be:
This step is designed in such a way as to use with `Then the HTTP status code should be "200"` step,
It doesn't throw an error when the HTTP status code mismatches. So we have to use it with  `Then the HTTP status code should be "200"` step

2022-10-13 03:46 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebDav.php
> +						$spaceId = (WebDavHelper::$SPACE_ID_FROM_OCIS) ?: WebDavHelper::getPersonalSpaceIdForUser(
Why removing here?
This ternary operator has no value to return when the condition is true (will return `1` by default).
Don't we want to return `space_id_from_ocis` if the condition is true?
```suggestion
						$spaceId = (WebDavHelper::$SPACE_ID_FROM_OCIS) ? WebDavHelper::$SPACE_ID_FROM_OCIS  : WebDavHelper::getPersonalSpaceIdForUser(
```

2022-10-13 03:51 UTC, saw-jan commented on tests/acceptance/features/apiMain/main.feature
> +      """
There is one fitting step exactly for this. May be you can use like this:
```suggestion
    And the downloaded content should be "User-agent: *\nDisallow: /"
```
Or, if that doesn't work then may be create a step which can take doc-string
```feature
And the downloaded content should be:
"""
User-agent: *
Disallow: /
"""
```

2022-10-13 04:11 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +      """
why create many steps for the same thing?  There are many steps in the core which was created in past but not in use now. I don't think creating many step for thing add any values just our file size increases.
This step is working fine 
`    And if the HTTP status code was "200" then the downloaded content for multipart byterange should be:`

We can't use this step `And the downloaded content should be "User-agent: *\nDisallow: /"`
Because our response comes in a multiline format.

2022-10-13 06:13 UTC, saw-jan commented on tests/acceptance/features/apiMain/main.feature
> +      """
I am guessing that if `\n` interprets while assertion then that would have worked.

2022-10-13 06:20 UTC, saw-jan commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +    And the following headers should match these regular expressions
What if the status code be `200`? Will `And the following headers should match these regular expressions` pass?

2022-10-13 06:21 UTC, saw-jan commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +    And the downloaded content for multipart byterange should be:
What if the status code is `200`? Will it pass?

2022-10-13 06:26 UTC, saw-jan commented on tests/acceptance/features/apiWebdavOperations/downloadFile.feature
> +    But the downloaded content should be "Welcome this is just an example file for developers."
Surely, the steps `if the HTTP status code was "<status-code>" then the downloaded content should be` has importance.
So, I don't think we can remove them. See how different status code means different contents

```suggestion
    But if the HTTP status code was "200" then the downloaded content should be "Welcome this is just an example file for developers."
```

2022-10-13 06:32 UTC, kiranparajuli589 reviewed
rest lgtm :+1:

2022-10-13 06:32 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebDav.php
> +			"The downloaded content was expected to be '$content', but actually is '$actualContent'. HTTP status was $actualStatusCode"
```suggestion
			"The downloaded content was expected to be:\n$content, but actually is:\n$actualContent\nHTTP status was $actualStatusCode"
```
for pystrings, inline messages may look unusual. newlines separations can be useful.

2022-10-13 06:57 UTC, kiranparajuli589 reviewed
Download API may end with 200(Complete) or 206(Partial). for these two cases, the downloaded content is different. the scenarios tries to cope with both cases,
- if status code is 206, the content check step for status 200 is skipped and vice versa
- content check step requires the status because it differs with the HTTP status received in the download request.

Please refactor you code accordingly. The step words a is bit confusing (at least for me). Adding some comments may help others coming here.

2022-10-13 06:59 UTC, kiranparajuli589 commented on tests/acceptance/features/apiMain/main.feature
> +      """
For long content assertions, this steps would not be so much readable. Adding a step with PyString support is good maybe.

2022-10-13 07:00 UTC, kiranparajuli589 commented on tests/acceptance/features/apiMain/main.feature
> +    Then if the HTTP status code was "200" then the downloaded content for multipart byterange should be:
here, do you need that status code check `206` or `200`?

2022-10-17 03:37 UTC, SwikritiT requested changes

2022-10-17 03:37 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/WebDav.php
> -						$spaceId = (WebDavHelper::$SPACE_ID_FROM_OCIS) ? WebDavHelper::$SPACE_ID_FROM_OCIS : WebDavHelper::getPersonalSpaceIdForUser(
If `$SPACE_ID_FROM_OCIS` is set then we use space id from ocis which can be the space id of shares jail or project spaces, if the variable is not set then only we use the `personal` space id. please revert the changes.

2022-10-18 03:58 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebDav.php
> -						$spaceId = (WebDavHelper::$SPACE_ID_FROM_OCIS) ? WebDavHelper::$SPACE_ID_FROM_OCIS : WebDavHelper::getPersonalSpaceIdForUser(
My ide settings change this automatically and I missed it while checking before the update. I was busy with other PR and tasks so I didn't have time to look over this PR. sawjan bro also comment on the same so I already noticed this.

2022-10-18 04:30 UTC, amrita-shrestha commented on tests/acceptance/features/apiMain/main.feature
> +    And the content in the response should match with the content:
as @kiranparajuli589 commented
> For long content assertions, this steps would not be so much readable. Adding a step with PyString support is good maybe.

2022-10-18 05:48 UTC, saw-jan commented on tests/acceptance/features/apiMain/main.feature
> +    And the content in the response should match with the content:
looks much readable
```suggestion
    And the content in the response should match the following content:
```

2022-10-18 08:37 UTC, saw-jan commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +
Move this to `WebDav.php` and it can be used as below.
```suggestion
	/**
	 * @Then the content in the response should match the following content:
	 *
	 * @param PyStringNode $content
	 *
	 * @return void
	 */
	public function theContentInTheResponseShouldMatchTheFollowingContent(PyStringNode $content): void {
		$this->checkDownloadedContentMatches($content->getRaw())
	}

```

2022-10-18 09:33 UTC, saw-jan reviewed
LGTM

2022-10-18 09:50 UTC, grgprarup reviewed
LGTM :+1:

2022-10-18 10:44 UTC, individual-it approved these changes

2022-10-18 10:45 UTC, SwikritiT approved these changes

2022-10-18 10:45 UTC, merged