Inbucket test branch
owncloud/core pull request #40442
Opened 2022-10-20 11:19 UTC by SagarGi

### Description

Testing `Inbucket` mail service as an alternative to `mailhog`

2022-11-02 06:06 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUILogin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37166/125
<!-- id: pr-40442 -->

2022-11-03 05:46 UTC, kiranparajuli589 commented on tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
> +      | email | foo@bar.co, goo@barr.co |
why changing this?

2022-11-03 05:46 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	public static function getSenderOfEmail(
i am a bit confused at this fn. if you have to get the sender for an email, here inputs are receiver email addr....so just grab mails for that specific email and then filter the required sender out of them.

2022-11-03 05:46 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * @param string $mailbox
could you add more desc. for mailbox param

2022-11-03 06:14 UTC, SagarGi commented on tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
> +      | email | foo@bar.co, goo@barr.co |
for inbucket `foo` will be same mailbox(single email basically) and scenarios says it different email address. so i changed it.

2022-11-03 08:23 UTC, SagarGi commented on tests/acceptance/features/bootstrap/EmailContext.php
> -		$this->clearMailHogMessages();
mailboxes are push to an array so clearing it in `beforescenario` would not be possible since it is always empty, because we require mailbox to delete inbucket messages (emails).

2022-11-03 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/EmailContext.php
> -		$this->clearMailHogMessages();
what if test breaks at the middle of the run? If there is no effect, cleanup wouldn't be necessary.

2022-11-03 08:45 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	public static function getMailboxeInformation(string $mailBox, ?string $xRequestId = null) {
```suggestion
	public static function getMailboxInformation(string $mailBox, ?string $xRequestId = null) {
```

2022-11-03 08:45 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * return general response information with mailBox (for foo@example.com, mailBox = foo)
```suggestion
	 * returns general information about the provided mailBox
	 * a mailbox is created automatically in InBucket for every unique email sender|receiver.
	 * for ex: mailbox for foo@example.com is created as 'foo'
```

2022-11-03 09:32 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +		if ($emailHost === false) {
I think env vars will be treated as string
```suggestion
		$emailHost = \getenv('EMAIL_HOST');
		if (($emailHost === '' || $emailHost === 'false') {
```

2022-11-03 09:34 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +		if ($localEmailHost === false) {
env vars will be treated as string
```suggestion
		$localEmailHost = \getenv('LOCAL_EMAIL_HOST');
		if ($emailHost === '' || $localEmailHost === 'false') {
```

2022-11-03 09:35 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +			$emailPort = "9000";
env vars will be treated as string
```suggestion
		$emailPort = \getenv('EMAIL_PORT');
		if ($emailPort === '' || $emailPort === 'false') {
			$emailPort = "9000";
```

2022-11-03 09:44 UTC, saw-jan commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		}
does this look cleaner?
```suggestion
		$mailBox =  explode("@", $emailAddress)[0];
		if (!\in_array($mailBox, $this->emailRecipients)) {
			$this->emailRecipients[] = $mailBox;
		}
```

2022-11-03 11:17 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * Returns the body of the last email according to email number (1 = latest received)
```suggestion
	 * Returns the body of the last received email for the provided receiver according to the provided email number
	 * For email number, 1 means the latest one
```

2022-11-04 04:06 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		}
yes thanks for reporting !! :+1:

2022-11-04 04:28 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/EmailContext.php
> -		$this->clearMailHogMessages();
https://github.com/inbucket/inbucket/discussions/300#discussioncomment-4049255

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * This functions splits email address as mailbox
```suggestion
	 * This function splits email address as mailbox
```

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * Returns the body of the last received email for the provided receiver according to the provided email number
```suggestion
	 * Returns the body of the last received email for the provided receiver according to the provided email address and the serial number
```

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +			if(sizeof($mailboxResponse) > 0) {
check also the serial number does not exceeds the count of the mailbox..

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +	 * @param int|null $emailNumber which number of multiple emails to read (first email is 1)
seems a bit confusing...

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/TestHelpers/InbucketHelper.php
> +			if(sizeof($mailBoxResponse) > 0) {
check also if the serial no. does not execeed the actual mailbox items count.

2022-11-04 04:41 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/AdminGeneralSettingsPage.php
>  use TestHelpers\EmailHelper;
```suggestion
```

2022-11-04 04:49 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +		if ($emailHost === false) {
func `getenv` return boolean(`false`) if the env is not set

2022-11-04 04:50 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +		if ($localEmailHost === false) {
func `getenv` return boolean(`false`) if the env is not set

2022-11-04 04:50 UTC, saw-jan commented on tests/TestHelpers/EmailHelper.php
> +			$emailPort = "9000";
func `getenv` return boolean(`false`) if the env is not set

2022-11-04 05:45 UTC, SagarGi commented on tests/acceptance/features/bootstrap/EmailContext.php
> -		$this->clearMailHogMessages();
A little research can be for this. May be it can be done in separate PR @kiranparajuli589 ?

2022-11-04 06:07 UTC, saw-jan commented on tests/TestHelpers/InbucketHelper.php
> +		return $splitEmailAddressAsMailBox[0];
less code
```suggestion
		return explode("@", $emailAddress)[0];
```

2022-11-04 06:10 UTC, saw-jan commented on tests/TestHelpers/InbucketHelper.php
> +	) {
```suggestion
	public static function getBodyOfLastEmail(
		string $emailAddress,
		string $xRequestId,
		?int $emailNumber = 1,
		?int $waitTimeSec = EMAIL_WAIT_TIMEOUT_SEC
	): string {
```

2022-11-04 06:11 UTC, saw-jan commented on tests/TestHelpers/InbucketHelper.php
> +		$currentTime = \time();
as per the function description.
or will it be other than string?
```suggestion
	 * @return string
	 * @throws GuzzleException
	 * @throws Exception
	 */
	public static function getEmailAddressOfSender(
		string $emailAddress,
		string $xRequestId,
		?int $emailNumber = 1,
		?int $waitTimeSec = EMAIL_WAIT_TIMEOUT_SEC
	): string {
		$currentTime = \time();
```

2022-11-04 06:13 UTC, SagarGi commented on tests/TestHelpers/InbucketHelper.php
> +		$currentTime = \time();
yes it will be a string.

2022-11-04 06:14 UTC, saw-jan commented on tests/acceptance/features/lib/AdminGeneralSettingsPage.php
> +					$row['value'] = InbucketHelper::getEmailHost();
keep it that way
```suggestion
					$row['value'] = EmailHelper::getEmailHost();
```

2022-11-04 06:14 UTC, saw-jan commented on tests/acceptance/features/lib/AdminGeneralSettingsPage.php
> +use TestHelpers\InbucketHelper;
```suggestion
use TestHelpers\EmailHelper;
```

2022-11-04 09:54 UTC, saw-jan reviewed
Looks Good :+1: :heart:

2022-11-04 11:45 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-11-04 11:45 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/EmailContext.php
> -		$this->clearMailHogMessages();
nice. :+1: separate PR would be good.

2022-11-07 03:55 UTC, individual-it requested changes
well done! :rocket: 
I just have small questions are recommendations

2022-11-07 03:55 UTC, individual-it commented on tests/TestHelpers/InbucketHelper.php
> +					\quoted_printable_decode($response->body->text . "\n" . $response->body->html)
do we need both bodies the text and html? I believe in mailhog we only got the text body and that was sufficient for the tests, But if we need both types, maybe the function can return an array so that the caller function can decide itself what body to use.

2022-11-07 03:55 UTC, individual-it commented on tests/TestHelpers/InbucketHelper.php
> +	public static function getContentOfAnEmailById(string $mailBox, string $mailboxId, ?string $xRequestId = null) {
```suggestion
	public static function getBodyOfAnEmailById(string $mailBox, string $mailboxId, ?string $xRequestId = null) {
```
just making the naming a bit more consistent because you have called the other function `getBodyOfLastEmail`

2022-11-07 03:55 UTC, individual-it commented on tests/TestHelpers/InbucketHelper.php
> +class InbucketHelper extends EmailHelper {
why not to dump it all into the EmailHelper itself?

2022-11-07 03:55 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUIGeneralContext.php
> +	 * @param ?int $emailNumber
does the new parameter do the same thing?

2022-11-07 03:55 UTC, individual-it commented on tests/acceptance/features/bootstrap/WebUISharingContext.php
> +			$this->featureContext->getStepLineRef(),
why this small change?

2022-11-07 04:20 UTC, SagarGi commented on tests/TestHelpers/InbucketHelper.php
> +					\quoted_printable_decode($response->body->text . "\n" . $response->body->html)
Some tests has assertion that requires html too. Regarding `mailhog` the body response contains both text body and html together.

2022-11-07 04:27 UTC, SagarGi commented on tests/TestHelpers/InbucketHelper.php
> +class InbucketHelper extends EmailHelper {
Thought if we switch to any other email service in future we can only this file and no need to to be more specific for the function in `EmailHelper`.

2022-11-07 04:27 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGeneralContext.php
> +	 * @param ?int $emailNumber
yes may be i missed description. doing it right away.

2022-11-07 04:27 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGeneralContext.php
> +	 * @param ?int $emailNumber
yes may be i missed the description. doing it right away.

2022-11-07 04:28 UTC, SagarGi commented on tests/TestHelpers/InbucketHelper.php
> +class InbucketHelper extends EmailHelper {
Thought if we switch to any other mail service near future. Only mail service helper function will be changed and no need to be more specific to the function in `EmailHelper`.

2022-11-07 05:22 UTC, individual-it commented on tests/TestHelpers/InbucketHelper.php
> +class InbucketHelper extends EmailHelper {
YAGNI https://en.wikipedia.org/wiki/You_aren't_gonna_need_it
If we ever need it, we can to it then

2022-11-10 04:53 UTC, individual-it approved these changes

2022-11-10 11:26 UTC, phil-davis approved these changes
Note: there are oc10 app acceptance test feature files that have the `@mailhog` tag, so those will need to be adjusted tomorrow. And maybe some of those tests will fail - let's see, it depends if any of the app test code is trying to call things in `EmailHelper` etc. that have changed.

2022-11-10 11:27 UTC, merged