add shib auth support for redirect url
owncloud/core pull request #40470
Opened 2022-11-02 08:09 UTC by mrow4a

## Description
Without this change, server-side Apache Auth (e.g. Shibboleth) resulted in redirect to default owncloud page, instead of last visited page. We now correctly handle redirect_url. 

In fact, we should have done page similar to https://github.com/owncloud/oauth2/blob/master/templates/authorize.php where user needs to click "Authorize" to be redirected to final page, but lets keep this direct redirect for backwards compatibility. 

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/5450
- Related https://github.com/owncloud/core/pull/40161

## How Has This Been Tested?
- manually in internal oc2.lab test instance

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] Base code changes
- [x] Make sure to handle corner cases in login
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-11-02 08:23 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37175/43
<!-- id: pr-40470 -->

2022-11-02 08:23 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUILogin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37175/125
<!-- id: pr-40470 -->

2022-11-02 08:23 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>cliTrashbin-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37175/110
<!-- id: pr-40470 -->

2022-11-02 08:23 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37175/142
<!-- id: pr-40470 -->

2022-11-02 12:04 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37185/53
<!-- id: pr-40470 -->

2022-11-02 12:04 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37185/55
<!-- id: pr-40470 -->

2022-11-02 12:04 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37185/51
<!-- id: pr-40470 -->

2022-11-02 12:04 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37185/52
<!-- id: pr-40470 -->

2022-11-28 08:35 UTC, DeepDiver1975 requested changes

2022-11-28 09:39 UTC, mrow4a commented on core/templates/apacheauthredirect.php
> +	<?php p($l->t('The application was authorized successfully. You should now get redirected to the requested page, otherwise you can close this window.'));?>
@DeepDiver1975 done

2022-12-12 07:49 UTC, DeepDiver1975 approved these changes

2022-12-12 07:49 UTC, merged