fix: Better output in case dataDirectory is invalid
owncloud/core pull request #40482
Opened 2022-11-09 09:29 UTC by d7oc

## Description
If the dataDirectory is not correct there is currently only the message `Your Data directory  is invalid` without specifying which directory is currently set. This small PR aims to add more output in this case.

## Motivation and Context
It solved the missing output in case something is wrong with the data directory.

## How Has This Been Tested?
- Local test

## Screenshots (if appropriate):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-11-09 10:11 UTC, jvillafanez commented
Could this be considered a security risk since we're leaking internal information?. Assuming the directory is invalid, anyone (maybe only registered users) could know where the data directory for ownCloud is located.

2022-11-09 10:19 UTC, DeepDiver1975 commented
> Could this be considered a security risk since we're leaking internal information?. Assuming the directory is invalid, anyone (maybe only registered users) could know where the data directory for ownCloud is located.

Absolutly - this error is exposed via the browser and we shall never ever expose internal paths.

2022-11-09 10:20 UTC, DeepDiver1975 requested changes
writing to log as an alternative is a no-go as we cannot write to data dir.
error_log() might be an alternative - error will go into the webserver error log then

2022-11-09 10:34 UTC, d7oc commented
Will `error_log()` also be visible when executing `occ`? I mainly need it in case that `occ` is executed, wasn't even aware that this shows up in the browser as well.

2022-11-09 10:39 UTC, DeepDiver1975 commented
> Will `error_log()` also be visible when executing `occ`?

no

2022-11-09 10:42 UTC, DeepDiver1975 commented
> I mainly need it in case that `occ` is executed, wasn't even aware that this shows up in the browser as well.

you can add a condition and use your error message if executed via occ

```php
if (\OC::$CLI) {
 # TODO: detailed message
}

2022-11-09 10:43 UTC, DeepDiver1975 commented
Or is this when executing ```occ check``` ?

2022-11-09 10:45 UTC, d7oc commented
No it happened directly when calling `occ`.

2022-11-09 14:20 UTC, d7oc commented
Updated the commit by force push to the branch. The output now looks like the following for my specific case:

```
root@owncloud-675d799b87-8mb4v:/var/www/owncloud# occ
Value of Data directory was: ""
Your Data directory must be an absolute path
Check the value of "datadirectory" in your configuration

Your Data directory is invalid
Please check that the data directory contains a file ".ocdata" in its root.

Cannot create "data" directory
This can usually be fixed by <a href="https://doc.owncloud.com/server/10.11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the root directory</a>.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/owncloud/lib/private/Console/Application.php:139
Stack trace:
#0 /var/www/owncloud/console.php(115): OC\Console\Application->loadCommands()
#1 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#2 {main}root@owncloud-675d799b87-8mb4v:/var/www/owncloud#
```

2022-11-09 14:25 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiWebdavLocks-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37238/78
<!-- id: pr-40482 -->

2022-11-09 15:44 UTC, DeepDiver1975 requested changes

2022-11-09 16:19 UTC, d7oc commented on lib/private/legacy/util.php
> +			print "Value of Data directory was: \"" . $dataDirectory . "\"\n";
Changed to the latter suggestion.

2023-02-01 04:59 UTC, phil-davis commented
https://github.com/owncloud/core/pull/40482#issuecomment-1308844730
https://drone.owncloud.com/owncloud/core/37803/38/14
```
Running apiCapabilities tests tagged ~@skipWhenTestingRemoteSystems&&~@skipOnOcVValue of Data directory was: /drone/src/data 10&&~@skipOnOcVValue of Data directory was: /drone/src/data 10.12&&~@skipOnOcVValue of Data directory was: /drone/src/data 10.12.0&&~@local_storage&&~@files_external-app-required&&@api&&~@skip 
```

For some reason there is output "Value of Data directory was: /drone/src/data" mixed in with the output about test tags.
"Something" is happening with `occ` commands at some point in the system setup that is emitting these messages. That needs investigation, because we should not be triggering the new message, but we are somehow.

I restarted CI to confirm the problem.

2023-02-01 05:36 UTC, phil-davis commented
The problem is;
```
$ php occ config:system:get version
Value of Data directory was: '/home/phil/git/owncloud/core/data'
10.12.0.1
```

That command is giving "bonus" new output.

2023-02-01 05:43 UTC, phil-davis commented
I adjusted the code so that the Data directory message is only emitted if it has a problem.

2023-02-01 13:21 UTC, jvillafanez commented
I'd vote for writing the message in the log instead of printing it. Printing messages should be the responsibility of a class as close to the user as possible (one of the `Command` for example).

> The problem is;
>> $ php occ config:system:get version
>> Value of Data directory was: '/home/phil/git/owncloud/core/data'
>> 10.12.0.1
>
> That command is giving "bonus" new output.

That's the side effect of printing anywhere. Not only it shows irrelevant information to the command, but also it could break 3rd party things (I could use that command to get the version and send an email about the update).

If logging isn't possible, I don't know if it's possible to send a 3rd key in the errors. I mean, I assume the "hint" is text that will be displayed in the web, and maybe "error" is a generic error text, so we could add a "cli" key for the error that should be displayed in the command line.

2023-08-10 08:02 UTC, phil-davis commented
@pako81 should anyone look at this for 10.13?
I see that @jvillafanez commented back in Feb 2023. But who would make decision, and who codes it?

2023-08-10 10:10 UTC, pako81 commented
We can try to get this into 10.13. No high priority but still nice to have. @d7oc would you be able to implement the requested change (logging it instead of printing it) ?

2023-08-10 12:50 UTC, d7oc commented
If `\OCP\Util::writeLog` can be used for that similar to https://github.com/owncloud/core/blob/8e3d09343984cf45aff772a0902e9fdfbc33cba5/lib/private/legacy/util.php#L398 I could adjust the PR.

2024-08-13 07:57 UTC, phil-davis commented
Is this still "a thing" to complete?
(it is on my GitHub "to review" list)

2024-08-13 08:11 UTC, jvillafanez commented
I'd say it need changes according to https://github.com/owncloud/core/pull/40482#issuecomment-1412050852 . Need someone to hit it with a stick.

2024-08-13 08:35 UTC, d7oc commented
There will be no progress from my side on this. So either there is somebody which will jump in here and drive it forward or we can close it.

2024-08-13 09:01 UTC, phil-davis commented
Rebased. I will have a look at what needs to be adjusted.

2024-09-05 09:34 UTC, DeepDiver1975 commented
> we can close it.

voting for this ...

2024-09-05 09:45 UTC, phil-davis commented
> voting for this

me too, it is a lot of messing around to get the output to happen in the "right" place in the calling stack and I don't think that it adds enough value.

2024-09-05 09:45 UTC, closed without merging