Encryption copy keys first3
owncloud/core pull request #40483
Opened 2022-11-09 12:34 UTC by jvillafanez

## Description
Follow up on https://github.com/owncloud/core/pull/40433 to solve https://github.com/owncloud/enterprise/issues/5344

The PR will copy the encryption keys instead of renaming them, so in case of error we can revert the action and we keep the encryption keys in the right location so the target file can be decrypted.

It seems the old PR was causing problems due to the failures caused by empty directories, which don't have encryption keys associated. The copyKeys method was reporting a failure because the expected directory with the keys doesn't exist. This has been adjusted: both copyKeys and renameKeys methods will return true if the directory doesn't exists.

## Related Issue
https://github.com/owncloud/enterprise/issues/5344

## Motivation and Context
Tests from other apps were failing due to the changes made in the old PR (which was reverted). This PR should cover the old failing scenarios.

## How Has This Been Tested?
Checked some of the previously failing scenarios.
1. With encryption active (after re-login to create the keys), create an empty directory
2. Delete the directory

With the old PR, a log about the encryption keys not being copied was showing. There was a forbidden exception happening. This is not happening with this PR.

1. With encryption active, create a directory and upload a file there
2. Run `occ encryption:recreate-master-key` command
3. From the desktop client, logout, login and upload a file

With the old PR, there were errors happening and uploading wasn't possible. This is also fixed with this PR.

1. With encryption active, create a directory
2. Share the directory with user2
3. With user2, upload a file and create a directory inside the shared directory.
4. With user2, delete the file and the folder

There were errors happening in the acceptance tests (these steps are based on the failing test). It works fine with the PR.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-11-14 10:29 UTC, jvillafanez commented
@phil-davis any chance to test this PR with all the apps in order to prevent having to revert it if something goes wrong?

2022-11-15 17:25 UTC, MeCorey requested changes

2022-11-15 17:25 UTC, MeCorey commented on lib/private/Files/Storage/Wrapper/Encryption.php
> -					$this->unencryptedSize[$target] = $this->unencryptedSize[$source];
- [ ]

2022-12-02 09:04 UTC, jvillafanez commented
ping

2022-12-14 15:22 UTC, IljaN reviewed
No need to check for exceptions as the files are always in a readable/acessible state between both operations. LGTM :+1: 

Restarting CI to check why it fails.

2022-12-14 15:37 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUILogin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37415/125
<!-- id: pr-40483 -->

2022-12-14 17:04 UTC, IljaN commented
CI seems to non-deterministically fail on different steps on each re-start :thinking:

2022-12-20 20:57 UTC, pako81 commented
The only test failing is related to `fsweb.test.owncloud.com` which is a known issue with this host, so it can be ignored.

2022-12-21 11:57 UTC, IljaN approved these changes

2022-12-21 11:58 UTC, merged