Remove empty directories from the files_versions
owncloud/core pull request #40499
Opened 2022-11-16 14:52 UTC by jvillafanez

## Description
Empty directories were left inside the files_versions directory. For large installations this is a waste of space because there could be a lot of empty directories that aren't useful in any way.

## Related Issue
https://github.com/owncloud/enterprise/issues/5471

## Motivation and Context

## How Has This Been Tested?
Mostly tested by deleting files from the web UI
1. Create "/f1/f2/f3" folder and upload a file with some versions
2. Check that the there are versions in `<userdir>/files_versions/f1/f2/f3/`
3. Remove the uploaded file

There should be only the `<userdir>/files_versions` folder without any directory in it. This is because the "f1/f2/f3" folders were empty.

Additional checks done:
* With multiple files, removing only one will keep the folder in the files_versions because there are more versions inside
* Removing the directory containing the files (removing "/f1/f2/f3" folder so "/f1/f2" is empty). Only `<userdir>/files_versions` exists because the rest of the folders were empty.
* Moving the files / directory around. As long as the source parent folder doesn't have versions, the folders will also be removed.
* `occ versions:cleanup` and `occ versions:expire` works with the same conditions.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

Note:
Existing empty version folder won't be removed unless a version ends up inside any of them. In this case, there won't be any difference and the folder will be removed once the last version is removed from the folder.

2022-12-06 11:07 UTC, pako81 commented
Should we move this forward?

2022-12-07 08:08 UTC, jvillafanez commented
As far as I know, this just needs review and merge. The failing test is due to the missing windows server.

2023-01-05 10:22 UTC, DeepDiver1975 requested changes
Any chance to add some tests to ensure that:
- empty folders are deleted
- non-empty folders are not deleted

THX

2023-01-05 12:37 UTC, phil-davis commented
> Any chance to add some tests

Not sure if you mean unit tests or acceptance tests. The behavior to test is in the back-end implementation, so not directly visible to any API call. But we do have the testing app, and that has https://github.com/owncloud/testing/blob/master/lib/ServerFiles.php which allows access to "see" what files and directories exist in the back-end data storage.

So, I can add some acceptance tests that check the back-end storage behavior of files_versions.

2023-01-05 12:51 UTC, mrow4a commented
> > Any chance to add some tests
> 
> Not sure if you mean unit tests or acceptance tests. The behavior to test is in the back-end implementation, so not directly visible to any API call. But we do have the testing app, and that has https://github.com/owncloud/testing/blob/master/lib/ServerFiles.php which allows access to "see" what files and directories exist in the back-end data storage.
> 
> So, I can add some acceptance tests that check the back-end storage behavior of files_versions.

I think what is meant here are unit tests in https://github.com/owncloud/core/blob/master/apps/files_versions/tests/VersioningTest.php

2023-01-05 13:01 UTC, DeepDiver1975 commented
Unit tests it would be

2023-01-18 08:52 UTC, DeepDiver1975 commented
let's first merge https://github.com/owncloud/core/pull/40531 to limit the rebase effort. THX

2023-01-27 14:48 UTC, IljaN approved these changes

2023-02-13 08:39 UTC, phil-davis commented
LGTM. @DeepDiver1975 please review again.

2023-02-13 15:19 UTC, DeepDiver1975 approved these changes

2023-02-13 15:19 UTC, DeepDiver1975 commented on apps/files_trashbin/tests/StorageTest.php
> +		$this->assertCount(0, $results);
old topic - `self::assertCount()` but this is all over our code base ....

2023-02-13 15:19 UTC, merged