[tests-only][full-ci]Refactor `MCKOL` request to non-existence user and to another users endpoint
owncloud/core pull request #40495
Opened 2022-11-15 07:01 UTC by SagarGi

## Description
- This PR adjust the response status code when a user make a `MCKOL` request to `non-existence-user` and other user's endpoint.
- Adds the bug demonstration test for the `MCKOL` request for `oc10`

## Related Issue

- https://github.com/owncloud/core/issues/40485

## Motivation and Context

## How Has This Been Tested?

- Locally
- CI

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2022-11-15 08:32 UTC, kiranparajuli589 commented on tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
> +    Then the HTTP status code of responses on all endpoints should be "409"
```suggestion
    When user "Brian" requests these endpoints with "MKCOL" including body "" about user "Alice"
      | endpoint                                        |
      | /remote.php/dav/files/%username%/textfile0.txt  |
      | /remote.php/dav/files/%username%/PARENT         |
      | /remote.php/dav/files/%username%/does-not-exist |
      | /remote.php/dav/files/%username%/PARENT/parent.txt |
    Then the HTTP status code of responses on all endpoints should be "403,403,403,409" respectively
```
can we merge these two when steps like this?

2022-11-15 09:03 UTC, SwikritiT commented on tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
>        | /remote.php/dav/files/%username%/does-not-exist |
```suggestion
    When user "Brian" requests these endpoints with "MKCOL" including body "" about user "Alice"
      | endpoint                                        |
      | /remote.php/dav/files/%username%/textfile0.txt  |
      | /remote.php/dav/files/%username%/PARENT         |
      | /remote.php/dav/files/%username%/does-not-exist |
      | /remote.php/dav/files/%username%/PARENT/parent.txt |
```

2022-11-15 09:03 UTC, SwikritiT commented on tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
> +    Then the HTTP status code of responses on all endpoints should be "404"
And then these steps can be removed? Same for scenario below

2022-11-16 07:50 UTC, amrita-shrestha requested changes

2022-11-16 07:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
> +    Then the HTTP status code of responses on each endpoint should be "403, 403, 403, 409" respectively
@SagarGi  Is there any scenario covering tests scenario for the non-existent user?

2022-11-16 07:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
> +@api @skipOnOcis
please add issue tag https://github.com/owncloud/core/issues/40485

2022-11-16 07:50 UTC, amrita-shrestha commented on tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
> +  @skipOnOcV10 @issue-ocis-reva-9 @issue-ocis-reva-197
add https://github.com/owncloud/ocis/issues/5049 issue tag

2022-11-16 07:55 UTC, amrita-shrestha commented
@SagarGi ocis issue https://github.com/owncloud/ocis/issues/5049 .

2022-11-16 10:29 UTC, SagarGi commented on tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
> +    Then the HTTP status code of responses on each endpoint should be "403, 403, 403, 409" respectively
i will check for non-existing user if not i will add one. Thanks for reporting !!

2022-11-18 11:11 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-8-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37307/174
<!-- id: pr-40495 -->

2022-11-18 11:11 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37307/175
<!-- id: pr-40495 -->

2022-11-18 11:11 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-7-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37307/173
<!-- id: pr-40495 -->

2022-11-21 04:09 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			return '1486d238-aa92-42ce-bdc4-0b0000009157$131daf35-c113-4aca-85a4-383ed5f4432';
this is a sample space-id for `non-existent-user`. In doubt what to give space_id for such user.

2022-11-21 08:32 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			return '1486d238-aa92-42ce-bdc4-0b0000009157$131daf35-c113-4aca-85a4-383ed5f4432';
for the non-existent user...a fake space ID is managed already. see https://github.com/owncloud/core/pull/40430

2022-11-21 11:28 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			return '1486d238-aa92-42ce-bdc4-0b0000009157$131daf35-c113-4aca-85a4-383ed5f4432';
@kiranparajuli589 thanks

2022-11-22 05:36 UTC, kiranparajuli589 commented on tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
> +      | /remote.php/dav/files/%non-existent-user%/textfile0.txt     |
```suggestion
      | /remote.php/dav/files/non-existent-user/textfile0.txt     |
```
why do we need to replace it. anyway the input will be the non-existent as we have not created it.

2022-11-22 05:36 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		}
this will not be necessary @SagarGi, if the below getter fn. fails (which is most likely for a non-exitent user) the `makeDavRequest` func. will catch the exception and feeds in the fake space ID. for the request to be made.

2022-11-23 03:16 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		}
Sure didnt know about it. i will refactor it. Thanks for reporting.

2022-11-23 06:34 UTC, kiranparajuli589 reviewed
lgtm :+1 few improvements:

2022-11-23 06:34 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +	 * This method first check if a user exist to return a his/her space_id
```suggestion
	 * First checks if a user exist to return its space ID
```

2022-11-23 06:34 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +	 * In case of non-existent user it returns a valid fake space_id
```suggestion
	 * In case of any exception, it returns a fake space ID
```

2022-11-23 06:34 UTC, kiranparajuli589 commented on tests/TestHelpers/WebDavHelper.php
> +	public static function checkAndGetUserPersonalSpaceId(string $baseUrl, string $user, string $password, string $xRequestId):string {
```suggestion
	public static function checkAndGetPersonalSpaceIdForUser(string $baseUrl, string $user, string $password, string $xRequestId):string {
```

2022-11-24 03:51 UTC, saw-jan reviewed
LGTM

2022-11-28 03:49 UTC, SwikritiT commented
All the tests are passing the failure is in `phpunit tests against sqilte windows`.

@phil-davis @individual-it can anyone of you take a look and maybe merge this PR if it's possible?

2022-11-28 04:09 UTC, individual-it requested changes

2022-11-28 04:09 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
>  		throw new Exception(__METHOD__ . " Personal space not found for user " . $user);
make the code here throw a special Exception, e.g. create a an exception called `SpaceNotFoundException`

2022-11-28 04:09 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +		} catch (Exception $e) {
catch here only the specific exception that is thrown in `getPersonalSpaceIdForUser` if space is not found. There might be other exceptions that we don't want to catch

2022-11-28 04:09 UTC, individual-it commented on tests/TestHelpers/WebDavHelper.php
> +	public static function checkAndGetPersonalSpaceIdForUser(string $baseUrl, string $user, string $password, string $xRequestId):string {
```suggestion
	public static function getPersonalSpaceIdForUserOrFakeIfNotFound(string $baseUrl, string $user, string $password, string $xRequestId):string {
```

2022-11-29 04:27 UTC, individual-it approved these changes

2022-11-29 10:26 UTC, amrita-shrestha approved these changes

2022-11-30 03:36 UTC, phil-davis approved these changes

2022-11-30 03:38 UTC, merged