Show Legal statement by personal settings
owncloud/core pull request #40511
Opened 2022-11-23 09:59 UTC by T0mWz

## Description
When your own legal statements are published, handy to show them at your personal settings page.

## How Has This Been Tested?
 - Applied within own environment

## Screenshots (if appropriate):
![Screenshot 2022-11-23 at 10 51 48](https://user-images.githubusercontent.com/2477797/203518286-212fccf3-3be5-478d-9acf-2e884a64e541.png)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

## ToDo:
 - Translation option added

2022-11-23 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=40511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=40511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=40511) it.</sub>

2023-01-30 15:09 UTC, mmattel commented
@T0mWz you need to sign the CLA to proceed, see the link above, it is just a click...

2023-01-30 15:11 UTC, T0mWz commented
ow, I already did that. But do it directly again @mmattel !

2023-01-30 15:18 UTC, mmattel commented
> I already did that

hmmm, I just clicked on recheck but it is still the same...?
Can you pls redo signing the online CLA?

2023-01-31 08:10 UTC, phil-davis commented
I rebased and force-pushed. Up-to-date CI is running.

The commit is by https://github.com/tomwezepoel @tomwezepoel and not by @T0mWz 

So "signing the CLA needs to be done by @tomwezepoel 

Tom - I suppose that both accounts are you, the same person? What happened?

2023-01-31 08:38 UTC, T0mWz commented
> I rebased and force-pushed. Up-to-date CI is running.
> 
> The commit is by https://github.com/tomwezepoel @tomwezepoel and not by @T0mWz
> 
> So "signing the CLA needs to be done by @tomwezepoel
> 
> Tom - I suppose that both accounts are you, the same person? What happened?

Ahja, shared personality. Haha!

2023-01-31 12:58 UTC, mmattel commented
A changelog entry is needed.

2023-02-02 07:58 UTC, mmattel commented
@phil-davis @DeepDiver1975 approve?

2023-02-02 10:59 UTC, DeepDiver1975 requested changes

2023-02-02 10:59 UTC, DeepDiver1975 commented on settings/templates/panels/personal/profile.php
> +                <label for="legal_privacy_policy"><?php p($l->t('Our Privacy Policy conditions:')); ?></label> <a href="<?php p($_['legal_privacy_policy']) ?>"><?php p($_['legal_privacy_policy']) ?><
I prefer to open the urls in a new tab - please add `target="_blank" rel="noopener noreferrer"`

2023-02-02 15:01 UTC, T0mWz commented on settings/templates/panels/personal/profile.php
> +                <label for="legal_privacy_policy"><?php p($l->t('Our Privacy Policy conditions:')); ?></label> <a href="<?php p($_['legal_privacy_policy']) ?>"><?php p($_['legal_privacy_policy']) ?><
@DeepDiver1975  For both, privacy and imprint ?

2023-02-02 15:03 UTC, DeepDiver1975 commented on settings/templates/panels/personal/profile.php
> +                <label for="legal_privacy_policy"><?php p($l->t('Our Privacy Policy conditions:')); ?></label> <a href="<?php p($_['legal_privacy_policy']) ?>"><?php p($_['legal_privacy_policy']) ?><
Yes please - THX a lot!

2023-02-02 16:23 UTC, mmattel commented
@T0mWz you need to run a php style fix. To do so, run 'make help' in the repo root and near the bottom of the output you will see the command example, then repush.

2023-02-03 01:56 UTC, phil-davis commented
> A changelog entry is needed.

done

2023-02-03 01:56 UTC, phil-davis commented
> @T0mWz you need to run a php style fix. To do so, run 'make help' in the repo root and near the bottom of the output you will see the command example, then repush.

done

2023-02-03 01:58 UTC, phil-davis commented
Note: this makes use of the existing core settings legal.privacy_policy_url and legal.imprint_url that have existed for some time - e.g. see old PR https://github.com/owncloud/theme-enterprise/pull/25 and #31699

2023-02-03 02:34 UTC, phil-davis approved these changes

2023-02-03 04:12 UTC, phil-davis commented
@DeepDiver1975 or @jvillafanez please also review. IMO this is ready to merge.

2023-02-06 14:44 UTC, DeepDiver1975 approved these changes

2023-02-06 14:44 UTC, merged