WIP: Implement persistent major version workflow (v2)
owncloud/core pull request #40531
Opened 2022-12-11 21:38 UTC by mrow4a

## Description

TODO

## Related Issue
- Replaces https://github.com/owncloud/core/pull/40319
- Implements https://github.com/owncloud/enterprise/issues/5286

## How Has This Been Tested?
- manually in the developer instance
- unit/acceptance tests

TODO

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] Base code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

## Example

TODO

2022-12-11 22:12 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUITags-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37402/143
<!-- id: pr-40531 -->

2023-01-03 13:07 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiMain-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37511/41
<!-- id: pr-40531 -->

2023-01-03 13:07 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37511/37
<!-- id: pr-40531 -->

2023-01-05 01:43 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/37534/9/7
```
There were 2 failures:

1) OCA\Files_Versions\Tests\VersioningTest::testExpire with data set "metaEnabled" (true)
Failed asserting that 3 matches expected 4.

/drone/src/apps/files_versions/tests/VersioningTest.php:354
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

2) OCA\Files_Versions\Tests\VersioningTest::testIsPublishedVersion with data set "metaEnabled" (true)
Failed asserting that false is true.

/drone/src/apps/files_versions/tests/VersioningTest.php:409
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97
```

2023-01-05 01:44 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/37534/143/18
```
runsh: Total unexpected failed scenarios throughout the test run:
webUITags/editTags.feature:15
webUITags/editTags.feature:28
```

```
    And the user edits the tag with name "random" and sets its name to "random-big" using the webUI # WebUITagsContext::theUserEditsTheTagWithNameAndSetsItsNameToUsingTheWebui()
      Page\FilesPageElement\DetailsDialog::renameTagxpath: //input[@id='view12-rename-input'] could not find tag edit input (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException)
```

2023-01-05 01:47 UTC, phil-davis commented
By default, CI gets killed as soon as one pipeline fails.
I suggest that you add `[full-ci]` to the PR title. Then all pipelines will run to completion and you can see all the things that are failing.

2023-01-05 20:36 UTC, mrow4a commented
@phil-davis would you mind having a look into https://drone.owncloud.com/owncloud/core/37551/142/17 ? I quite cannot scratch my head what is the problem, my change has nothing to do with Tags Tab, it touches only Versions Tab. Also backend logic nowhere touches tags logic. Would be quite grateful 🙏🏻

2023-01-08 11:00 UTC, mrow4a commented
@phil-davis started adjusting other acceptance tests due to the fact that PROPFIND now also returns current version and noncurrent version, plus restore logic changed. 

And... found out that in one case there is a bug in my implementation (`enable file versioning and check the history of changes from multiple users after renaming file by sharer`) ... without these tests would never have thought of that corner case, good job!

2023-01-09 09:22 UTC, mrow4a commented on tests/acceptance/features/webUIFiles/versions.feature
>      When the user restores the file to last version using the webUI
@phil-davis this case works perfectly when manually navigating, but somehow the restore here is wrongly catched as part of the test. I get error. Would appreciate any help here

```
    When the user restores the file to last version using the webUI                                         # WebUIFilesContext::theUserRestoresTheFileToLastVersionUsingTheWebui()
      element click intercepted: Element <a href="#" class="revertVersion" title="Restore">...</a> is not clickable at point (1016, 344). Other element would receive the click: <img src="/core/img/actions/checkmark.svg">
        (Session info: chrome=74.0.3729.169)
        (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 5.4.0-135-generic x86_64) (WebDriver\Exception\ElementClickIntercepted)
```

2023-01-09 09:23 UTC, mrow4a commented on tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
> -	private $tagEditInputXpath = "//input[@id='view12-rename-input']";
@phil-davis this was the problem with acceptance test for tags. I think this view13 should not be hardcoded. Lets not change this as part of this PR, should be separate I think

2023-01-09 09:24 UTC, mrow4a commented
@DeepDiver1975 @phil-davis ready for review, adjusted all tests (except one that has test code issue)

2023-01-09 09:48 UTC, DeepDiver1975 commented on lib/public/Files/Storage/IVersionedStorage.php
> +	public function getCurrentVersion($internalPath);
not perfect method naming.

`getCurrentVersion` implies that the current version is returned.

What about merging this into `getVersion` where `$versionId` is null?

2023-01-13 11:06 UTC, mrow4a commented on lib/public/Files/Storage/IVersionedStorage.php
> +	public function getCurrentVersion($internalPath);
@DeepDiver1975 ye ok... what maybe can be done, with getVersions() - which is used in public interface in DAV and FS, I could add optional argument `includeCurrent/includeRoot/..?` , which will make it also backwards compatible.. thoughts?

2023-01-13 11:30 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaPlugin.php
>  	public const VERSION_EDITED_BY_PROPERTYNAME_NAME = '{http://owncloud.org/ns}meta-version-edited-by-name';
should be named `VERSION_EDITED_BY_NAME_PROPERTYNAME_NAME`

2023-01-13 11:31 UTC, DeepDiver1975 commented on apps/dav/lib/Meta/MetaPlugin.php
> +				$manager = \OC::$server->getUserManager(); // FIXME: not so good
this indeed sucks - some eager loading would be great - but out of scope

2023-01-13 11:43 UTC, DeepDiver1975 requested changes

2023-01-13 11:43 UTC, DeepDiver1975 commented on apps/files_trashbin/lib/Trashbin.php
> -					if ($metaEnabled) {
why was that removed?

2023-01-13 11:43 UTC, DeepDiver1975 commented on apps/files_versions/lib/AppInfo/Application.php
> +		$container->registerService('VersionController', function ($c) {
should not be necessary - container should resolve the class by itself

2023-01-13 11:43 UTC, DeepDiver1975 commented on apps/files_versions/lib/Controller/VersionController.php
> +	public function __construct($appName, IRequest $request) {
not needed -> remove ctor

2023-01-13 11:43 UTC, DeepDiver1975 commented on apps/files_versions/lib/Controller/VersionController.php
> +			return new JSONResponse([], Http::STATUS_INTERNAL_SERVER_ERROR);
log the exception

2023-01-15 15:01 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
> -					if ($metaEnabled) {
the restore/retain from trashbin was wrong here (it was missing `.current.json` file in some scenarious). I fixed this one and also remove need for this operation, by implementing this handling properly in `apps/files_versions/lib/Storage.php`

2023-01-15 15:03 UTC, mrow4a commented on apps/files_versions/lib/AppInfo/Application.php
> +		$container->registerService('VersionController', function ($c) {
done

2023-01-15 15:03 UTC, mrow4a commented on apps/files_versions/lib/Controller/VersionController.php
> +	public function __construct($appName, IRequest $request) {
good catch

2023-01-15 15:07 UTC, mrow4a commented on tests/acceptance/features/webUIFiles/versions.feature
>      When the user restores the file to last version using the webUI
@phil-davis would be grateful if you could have a look on how to fix this.

2023-01-15 15:14 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
> -					if ($metaEnabled) {
in fact, the block below probably could also have been hidden behind the storage, but did not want to refactor too much and did not find time to investigate how to do it properly.

2023-01-19 07:40 UTC, mmattel commented
`occ config:system:set file_storage.save_version_metadata --value true --type boolean`

Needs documentation in our admin docs, pls file an issue in the docs-ocis repo

2023-01-19 07:44 UTC, mrow4a commented
> `occ config:system:set file_storage.save_version_metadata --value true --type boolean`
> 
> Needs documentation in our admin docs, pls file an issue in the docs-ocis repo

It is not docs-ocis repo. In PR description I already pointed which doc needs update (chexkbox)

2023-01-19 07:48 UTC, mmattel commented
> It is not docs-ocis repo

this was just a moring-typo, already corrected 😄

2023-01-19 10:30 UTC, DeepDiver1975 requested changes
- needs rebase again :see_no_evil: 
- what about s3 implementation of this?

2023-01-19 10:30 UTC, DeepDiver1975 commented on apps/files_versions/lib/AppInfo/Application.php
> +use OCA\Files_Versions\Controller\VersionController;
not needed

2023-01-20 09:44 UTC, DeepDiver1975 commented
rebasing ....

2023-01-20 09:51 UTC, DeepDiver1975 commented
@JammingBen looks like we had the same intention at the same time :see_no_evil:

2023-01-20 09:51 UTC, DeepDiver1975 commented
> * what about s3 implementation of this?

answered by looking into the tests - this is all not implemented on s3

2023-01-20 09:57 UTC, DeepDiver1975 commented
@mmattel for docu: this feature (tagging major versions) is not implemented on s3.
this pr also changes the implementation of verisons ordering - this is anyhow only non-s3 relevant

2023-01-24 08:53 UTC, mrow4a commented on tests/acceptance/features/webUIFiles/versions.feature
> +  Scenario: sharer can see the versions' respective author after version restore
@phil-davis so I wrote new scenario here, to prove scenario works, and that somehow in test **sharee can see the versions' respective author after version restore** the step `And the user restores the file to last version using the webUI Then the authors of the current and noncurrent versions of file "randomfile.txt" should be:` is buggy somehow

2023-01-24 08:54 UTC, mrow4a commented
@phil-davis I am also a bit fighting some other tests, as they hit race-conditions. The versions are based on mtime, which is in seconds. You could easily write a test that could have 2 different results based on timing (this is my current assumption)

2023-01-24 10:45 UTC, mrow4a commented on tests/acceptance/features/bootstrap/FilesVersionsContext.php
> +		\usleep(VERSION_MTIME_WAIT_TIMEOUT_MICROSEC); // make sure new version gets generated
@phil-davis ok I think I solved it with above

2023-01-24 11:41 UTC, mrow4a commented on tests/acceptance/features/webUIFiles/versions.feature
> +  Scenario: sharer can see the versions' respective author after version restore
@phil-davis ok... now this one fails, and other not.. it is like tossing a coin..

2023-01-30 09:39 UTC, pako81 commented
@mrow4a we still have a failing test here https://drone.owncloud.com/owncloud/core/37761/124/17. Mind to take care, thx.

2023-01-30 11:21 UTC, mrow4a commented
> @mrow4a we still have a failing test here https://drone.owncloud.com/owncloud/core/37761/124/17. Mind to take care, thx.

@pako81 I need assistance from @phil-davis or @individual-it here, do not know how to continue there as it seems problem with a test itself and not a code.

2023-02-02 11:59 UTC, phil-davis commented
Now I can reproduce it - if I make the browser width less, then the "tick" icon that should be displayed for the current version, actually overlays the next version.
![Screenshot from 2023-02-02 17-44-03](https://user-images.githubusercontent.com/1535615/216318837-03d087d2-3d92-41b8-aa08-39bc09928b23.png)

2023-02-02 12:12 UTC, phil-davis commented
And it only seems to happen while the time of the current version says "a few seconds ago - current"

If I wait a while, and it says "a minute ago - current" then it works OK. The test is shorter.

2023-02-02 13:00 UTC, mrow4a commented
@phil-davis cannot the selenium resolution be adjusted somehow?

2023-02-02 13:09 UTC, phil-davis commented
> @phil-davis cannot the selenium resolution be adjusted somehow?

I can manually reproduce the problem easily. So adjusting the screen size in the test will just hide the problem.

Can something be done in the UI code to make the "tick" stay against the correct "current" version?

2023-02-03 13:52 UTC, mrow4a commented
> Can something be done in the UI code to make the "tick" stay against the correct "current" version?

@phil-davis ok I will check, but if you use oc10.11 you might notice the problem was there actually already. But instead the restore buttons overlapped. Currentl OC10 design with frontend is not really resolution friendly.. I think we should define resolution where OC10 works 100% stable. Other resolutions can have a lot of functionalities malfunctioning .. check yourself :>

2023-02-03 14:09 UTC, mrow4a commented
@phil-davis ok.. I think I know where the problem is. It was not there before. It is because of the new "status" bar. I am weak in frontend, but will try to figure this out as probably would be hard to get capacity for this from someone fluent in it..

2023-02-03 19:20 UTC, mrow4a commented
@phil-davis I fixed the overlapping checkboxes. But something is still off there. Any clue what is going on now?

2023-02-06 11:59 UTC, jvillafanez commented
```
  Scenario: sharee can see the versions' respective author after version restore                            # /drone/src/tests/acceptance/features/webUIFiles/versions.feature:131
    Given the administrator has enabled the file version storage feature                                    # FeatureContext::theAdministratorHasEnabledTheFileVersionStorage()
    And user "Brian" has been created with default attributes and without skeleton files                    # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Carol" has been created with default attributes and without skeleton files                    # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has uploaded file with content "some content" to "/randomfile.txt"                     # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has shared file "randomfile.txt" with user "Brian"                                     # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "Alice" has shared file "randomfile.txt" with user "Carol"                                     # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "Brian" has uploaded file with content "Brian lorem content" to "/randomfile.txt"              # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "Alice lorem content" to "/randomfile.txt"              # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Carol" has uploaded file with content "Carol lorem content" to "/randomfile.txt"              # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Carol" has logged in using the webUI                                                          # WebUILoginContext::theUserHasLoggedInUsingTheWebUI()
    And the user has browsed to the files page                                                              # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    When the user browses directly to display the "versions" details of file "randomfile.txt" in folder "/" # WebUIFilesContext::theUserBrowsesDirectlyToDetailsTabOfFileInFolder()
    Then the authors of the current and noncurrent versions of file "randomfile.txt" should be:             # WebUIFilesContext::theAuthorsOfCurrentAndNoncurrentVersionsOfFileShouldBe()
      | index | author |
      | 1     | Carol  |
      | 2     | Alice  |
      | 3     | Brian  |
      | 4     | Alice  |
INFORMATION: timed out waiting for ajax calls to start
    When the user restores the file to last version using the webUI                                         # WebUIFilesContext::theUserRestoresTheFileToLastVersionUsingTheWebui()
      │ INFORMATION: timed out waiting for ajax calls to start
    Then the authors of the current and noncurrent versions of file "randomfile.txt" should be:             # WebUIFilesContext::theAuthorsOfCurrentAndNoncurrentVersionsOfFileShouldBe()
      | index | author |
      | 1     | Carol  |
      | 2     | Carol  |
      | 3     | Alice  |
      | 4     | Brian  |
      | 5     | Alice  |
      WebUIFilesContext::theAuthorsOfCurrentAndNoncurrentVersionsOfFileShouldBe Expected author 'Carol King' at index '2' but got 'Alice Hansen'
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'Carol King'
      +'Alice Hansen'
```
It seems a wrong expectation in the test. I've done the steps manually, and there is no restore action for the "current" (latest) version of the document. This means that it's impossible to restore Carol's version since it's the latest one, so a sequence of Carol - Carol - Alice - Brian - Alice can't happen.
It can also explain the timeout waiting in the test, because the test can't find the restore button.

Restoring the 2nd, 3rd, or 4th version (anything except the current version) also has a different behavior. As Carol, restoring Brian's version leads to a sequence Carol 0.5 - Alice 0.3 - Brian 0.2 - Alice 0.1 . I don't know if it's intended or it's a bug (I probably expect Carol 0.5 - Carol 0.4 - Alice 0.3 - Brian 0.2  Alice 0.1, and even Brian 0.5 instead of Carol 0.5)

2023-02-06 12:42 UTC, mrow4a commented
@jvillafanez it is incorrect, I modified the `tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php` to take second entry as "last version", which is not a current one.

2023-02-06 13:02 UTC, jvillafanez commented
> as per expectation -> it is also incorrect, now restore is creating new version with the author being the one restoring. behaviour changed, as described in the changelog and description

This seems to be the problem. After restoring, the expected 0.4 version disappears. I only see versions 0.5 (current), 0.3, 0.2 and 0.1, with Carol, Alice, Brian and Alice as their respective authors.

2023-02-06 13:15 UTC, jvillafanez commented on apps/files_trashbin/lib/Trashbin.php
> +					}
@mrow4a could you check this? It seems wrong.

If `$owner` is different than `$user`, we copy the metadata. But then, if we aren't forcing a copy, we rename the metadata. This seems to match what I'm seeing and it could be the cause of the test failure.

2023-02-06 13:41 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
> +					}
@jvillafanez this is a trashbin function. Should not be related to trashbin. The acceptance tests that fails is working in the UI when testing manual.

2023-02-06 13:42 UTC, mrow4a commented on apps/files_trashbin/lib/Trashbin.php
> +					}
also please note, that logic that I implemented is the same as was in the past. This code is not addition, it is replace+add

2023-02-06 13:48 UTC, mrow4a commented
> This seems to be the problem. After restoring, the expected 0.4 version disappears. I only see versions 0.5 (current), 0.3, 0.2 and 0.1, with Carol, Alice, Brian and Alice as their respective authors.

hmmm.... ok need to check this.. because maybe some retention policy triggered that is related to the fact that versions got created in close "mtime" to each other 🤔

2023-02-06 14:50 UTC, jvillafanez commented
I didn't change any setting other than the one to enable this feature. This means, no retention policy configured (other than the default one) and the quota for the users are unlimited. Moreover, there should be enough free space in the disk.
With these conditions, I don't think the retention policy should trigger and remove versions.

2023-02-06 15:22 UTC, mrow4a commented
@jvillafanez this is not true, read the doc again. The default retention is AUTO. This means after you reach 5 version retention is triggered for max versions per timeframe

2023-02-06 15:24 UTC, mrow4a commented
> The versions are adjusted along this pattern every time a new version is created and the background job was executed.

https://doc.owncloud.com/server/next/admin_manual/configuration/files/file_versioning.html#default-versions-delete-patterns

@jvillafanez

2023-02-07 09:48 UTC, jvillafanez commented
Assuming the retention policy triggers after restoring the file and it will never remove that file, we could try to disable the retention policy in the tests. I mean, if a previous version is removed from the list, that would still be ok.
The only reason to disable the retention is policy is to have a more predictable behavior.

I haven't checked, but I assume we have a test to ensure that persistent versions aren't removed by the retention policy. That would be the related use case we need to ensure.

2023-02-07 10:13 UTC, jvillafanez commented
I think I manually followed the test steps described in https://github.com/owncloud/core/pull/40531#issuecomment-1418967273 . The "When the user restores the file to last version using the webUI" was the confusing one, I think I restored Brian's version in that step.

2023-02-07 10:23 UTC, mrow4a commented
> I think I manually followed the test steps described in [#40531 (comment)](https://github.com/owncloud/core/pull/40531#issuecomment-1418967273) . The "When the user restores the file to last version using the webUI" was the confusing one, I think I restored Brian's version in that step.

you sure you refreshed browser caches so new javascript kicks in?

2023-02-07 10:58 UTC, jvillafanez commented
Yes, still happens with the latest code of this branch. Note that I'm doing the steps manually in the web UI. I'm not running the tests.

2023-02-07 11:27 UTC, phil-davis commented
![Screenshot from 2023-02-07 17-07-13](https://user-images.githubusercontent.com/1535615/217232052-caf0aa36-624c-436e-a553-294b4fda19ea.png)

I run the test scenario locally, putting a 30-second sleep in before DetailsDialog `restoreCurrentFileToLastVersion` so that the test "hangs" 30 seconds before it tries to find the top (latest) version revert button. That lets me look and take a screen shot.

The "tick" image that should be next to the current version, is actually over the top of the revert button of the latest version. The test code (and a real user) cannot effectively click the revert button.

2023-02-07 11:37 UTC, phil-davis commented
![Screenshot from 2023-02-07 17-17-54](https://user-images.githubusercontent.com/1535615/217234213-5eaa4fe2-51f2-4256-9207-f33657ca6e97.png)

If I change versionstabview.js line 350 to
```
				currentVersionLabel: t('files_versions', 'c')
```
(use just the shorter string "c" rather than the full word "current")
then the "tick" is rendered in its proper place, and the test passes.

We really just need to do whatever to stop the "tick" from being rendered in the wrong place.

2023-02-07 11:59 UTC, mrow4a commented
@phil-davis what is the resolution in acceptance test?

2023-02-07 12:48 UTC, phil-davis commented
> @phil-davis what is the resolution in acceptance test?

Looking in the chrome console while the test is sleeping, it tells me about 1050*978 pixels for the browser tab.

I see where `tests/acceptance/run.sh` can try to set `screenResolution` - but I think that was for choosing an actual OS screen size back in the days when we ran UI tests with SauceLabs. I tried changing those numbers, and it does not look like it has any effect.

2023-02-07 13:06 UTC, phil-davis commented
```
MOBILE_RESOLUTION='1200x800' make test-acceptance-webui BEHAT_FEATURE=tests/acceptance/features/webUIFiles/versions.feature:131
```

I found where we made the option to specify the browser window size. There is code in WebUIGeneralContext.php `setUpScenario()` which checks for a definition of `MOBILE_RESOLUTION` and sets the browser size to that. Normally we use it for running some test scenarios on a smaller size.

If I set the size like in the example command above, then the test passes. If it is set to a small width, then the test fails.

We could make a test step that resizes the browser window to a larger size, and use that in this scenario for now. (And make a separate issue to investigate and fix the problem that happens when the browser width is less)

2023-02-07 15:05 UTC, jvillafanez commented
This patch might work.
```
diff --git a/apps/files_versions/css/versions.css b/apps/files_versions/css/versions.css
index 2fe7954e67..570bedbee4 100644
--- a/apps/files_versions/css/versions.css
+++ b/apps/files_versions/css/versions.css
@@ -9,6 +9,12 @@
        float: left;
        border-bottom: 1px solid rgba(100,100,100,.1);
 }
+
+.versionsTabView li > div {
+       display: flex;
+       height: 100%;
+}
+
 .versionsTabView li:last-child {
        border-bottom: none;
 }
@@ -33,14 +39,13 @@
 }
 
 .versionsTabView .preview-container {
-       display: inline-block;
+       display: flex;
+       flex-direction: column;
        vertical-align: top;
        text-align: center;
-}
-
-.versionsTabView .preview-container {
        padding: 5px;
 }
+
 .versionsTabView img {
        cursor: pointer;
        padding-right: 4px;
@@ -56,10 +61,19 @@
 }
 
 .versionsTabView .version-container {
-       display: inline-block;
+       display: inline-flex;
+       flex-direction: column;
+       flex: auto;
+       overflow: auto;
        margin-top: 5px;
 }
 
+.versionsTabView .version-container .version-headline {
+       overflow: hidden;
+       text-overflow: ellipsis;
+       white-space: nowrap;
+}
+
 .versionsTabView .versiondate {
        min-width: 100px;
        vertical-align: super;
@@ -84,18 +98,17 @@
 }
 
 .versionsTabView .action-container {
-       display: inline;
+       display: flex;
+       flex: 0 0 auto;
 }
 
 .versionsTabView .revertVersion {
        cursor: pointer;
-       float: right;
        margin-right: -10px;
 }
 
 .versionsTabView .publishVersion {
        cursor: pointer;
-       float: right;
        margin-right: -10px;
 }
 .versionsTabView .current-version .version-headline {
```
At least, the button isn't hidden in small screens, so it should be clickable in the tests. Looks good to me.
Someone with more CSS expertise could double-check in case there is something wrong with it.

2023-02-07 19:19 UTC, mrow4a commented
@DeepDiver1975 @jvillafanez @phil-davis finally CI is green.

I decided not to change the existing logic with CSS to avoid risk related to regressions. Instead, I only show the new current/persistent label if screensize is >1200px in width. Commit is https://github.com/owncloud/core/pull/40531/commits/5cc9921b1682055bd20030af11dfdd23a1e38b96 , and FIXME tag added. Long term, it would be good to fix it for smaller screens too, and thus also to allow acceptance tests on these labels. But in this PR it will be too big/risky.

2023-02-08 09:35 UTC, jvillafanez commented on apps/files_versions/lib/MetaStorage.php
> +		// create new currentMetaFile and remove restoreMetaFile
I don't see we're removing the restoreMetaFile :)
We might need to add in the PHPDoc that the restored metadata isn't removed in order to clarify the behavior

2023-02-08 09:35 UTC, jvillafanez commented on apps/files_versions/lib/MetaStorage.php
> +		if (!$oldVersionTag) {
`$oldVersionTag === ''` seems more natural

2023-02-08 09:35 UTC, jvillafanez commented on apps/files_versions/lib/Storage.php
> +			}
The code might need to be moved.
If you have files with metadata and any of the parent folders are moved or copied, the metadata of the files inside that folder need to be moved.

2023-02-08 09:35 UTC, jvillafanez commented on lib/private/Files/Meta/MetaVersionCollection.php
> +		$storage = $this->node->getStorage();
we should be accessing the `$this->versionInfo` cache first.
```
if ($this->versionInfo) {
  return $this->versionInfo['edited_by'] ?? '';
}

$storage = $this->node->getStorage();
........
```

2023-02-08 09:42 UTC, jvillafanez commented
Taking into account that the user can't remove versions, I think we should have some condition to remove published versions. We might also need to check the performance of the expiration if there are quite a bunch of published versions.

We could remove published versions if there are only published versions, and starting from the oldest one. It seems in line with the current retention policy.

2023-02-08 09:52 UTC, mrow4a commented
@jvillafanez I will try to address the inputs, but some of them would need to discard. 

This change is large, and to avoid regressions I would prefer not to refactor too much or change existing logic. This code is many years old.

2023-02-08 10:46 UTC, jvillafanez commented
Yes, I'm ok with that. We'll have to be aware of possible issues, and be clear about what is left to do.

2023-02-10 10:40 UTC, mrow4a commented on apps/files_versions/js/versionstabview.js
> +					self._toggleLoading(false);
In fact I copied it from `versionModel.revert({` which is "related" button, just different function. I do not dare to change this as it is not documented why needed

2023-02-10 11:32 UTC, jvillafanez commented on apps/files_versions/js/versionstabview.js
> +					self._toggleLoading(false);
ok, then maybe write a TODO / FIXME to investigate later.

2023-02-10 12:09 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +		$newVersionEditedBy = \OC_User::getUser();
even if it is, the editor will be false here, and not displayed.

2023-02-10 12:10 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +			@\copy($currentMetaFile, $targetMetaFile);
I think this is something for follow up work. It would make sense to change it literally everywhere in this class

2023-02-10 12:11 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +		$newVersionEditedBy = \OC_User::getUser();
same as before answered

2023-02-10 12:26 UTC, mrow4a commented on apps/files_versions/js/versionstabview.js
> +			var isMajorVersion = version.has('versionTag') && version.get('versionTag').indexOf('.0', version.get('versionTag').length - '.0'.length) !== -1;
should be in the documentation and extended. ref https://doc.owncloud.com/server/next/admin_manual/configuration/files/file_versioning.html#conscious-persistent-major-versions

2023-02-10 12:55 UTC, mrow4a commented on apps/files_versions/js/versionstabview.js
> +					self._toggleLoading(false);
Ye I mean.. this code I guess is just to endure loading is disabled. Just in case some logic interferes. I would keep it just as safety (legacy) net

2023-02-10 12:56 UTC, mrow4a commented on config/config.sample.php
> +'file_storage.save_version_metadata' => false,
done

2023-02-10 13:07 UTC, mrow4a commented on apps/files_versions/js/versionstabview.js
> +					// reset and re-fetch the updated collection
commented

2023-02-10 13:07 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +	public function getVersion(FileInfo $versionFile) : array {
done

2023-02-10 13:07 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +		// preserve original restoration tag if set
removed

2023-02-10 13:07 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +		if (!$oldVersionTag) {
done

2023-02-10 13:07 UTC, mrow4a commented on apps/files_versions/lib/MetaStorage.php
> +		// create new currentMetaFile and remove restoreMetaFile
done

2023-02-10 13:08 UTC, mrow4a commented on apps/files_versions/lib/Storage.php
> +			}
commented in the code

2023-02-10 13:14 UTC, jvillafanez commented on apps/files_versions/js/versionstabview.js
> +			var isMajorVersion = version.has('versionTag') && version.get('versionTag').indexOf('.0', version.get('versionTag').length - '.0'.length) !== -1;
I'm not sure if that we'll be enough. I mean, we might let the user to set the versioning himself in the future, and we might assume that versions such as "1.0.1" will work. It won't be just allowing the user to set the versioning, but there is more code to be done.
I'm not saying that we have to code something for it right now, but I'd like to have something so we are reminded about this if we ever need to implement that use case. A well placed comment in the code is enough for me.

2023-02-10 13:22 UTC, jvillafanez commented on apps/files_versions/lib/MetaStorage.php
> +			@\copy($currentMetaFile, $targetMetaFile);
I'd remove the "@" for now so it's the same for all the methods. For the actual error handling, I think it's ok for a follow up (we'd need a ticket :) )

2023-02-10 14:19 UTC, jvillafanez approved these changes
Might need a squash, but code looks ok.

2023-02-10 14:39 UTC, mmattel commented
@mrow4a pls add the change that you proposed in docs in config_sample_php_parameters here in core. I will then do a `config-to-docs` run post merging this PR which transports the changes to docs properly.

2023-02-10 14:59 UTC, DeepDiver1975 approved these changes

2023-02-10 15:16 UTC, merged

2023-03-13 13:21 UTC, jnweiger commented
Confirmed fixed in 10.12.0-rc.3
- Persistent versions are retained with auto, other versions disapear as per policy.
- Persistent versions older than 2 days are retained with 'auto, 2', when `occ versions:expire` is run. 
- Persistent versions are deleted by 'occ versions:cleanup' - which is expected and documented behaviour.
- Works fine also with encryption.