Accept OCM to groups
owncloud/core pull request #40589
Opened 2023-01-20 12:00 UTC by michielbdejong

## Description

These are the hooks we need in the core repo to allow the [FederatedGroups app](https://github.com/SURFnet/rd-sram-integration/tree/main/federatedgroups) to deal with outgoing and incoming OCM shares to group.

## Related Issue

- Fixes #40530

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2023-01-20 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=40589) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=40589) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: michielbdejong<br/>:x: michiel-testing<br/>:x: navid-dada<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=40589) it.</sub>

2023-02-14 10:00 UTC, DeepDiver1975 requested changes

2023-02-14 14:55 UTC, michielbdejong commented on apps/files_sharing/js/external.js
> +										url: OC.generateUrl('/apps/files_sharing/api/externalShares/'+share.id+"?share_type="+shareType),
No, we will be storing OCM-to-group shares in a different database table than OCM-to-user shares, because @jvillafanez wanted to keep the impact on the existing database table minimal.

So now, on servers where OCM-to-group is enabled, you need to include the OCM share type to get a unique share id.

2023-02-14 15:05 UTC, DeepDiver1975 commented on apps/files_sharing/js/external.js
> +										url: OC.generateUrl('/apps/files_sharing/api/externalShares/'+share.id+"?share_type="+shareType),
:see_no_evil:

2023-03-03 13:35 UTC, michielbdejong commented on apps/federatedfilesharing/lib/Controller/OcmController.php
> +			$controller = \OCA\FederatedGroups\Application::getOcmController($this->request);
And then if the event is picked up the default code is not ran? What if the event is picked up twice?

2023-03-03 13:35 UTC, michielbdejong commented on apps/federatedfilesharing/lib/Controller/OcmController.php
> +			$controller = \OCA\FederatedGroups\Application::getOcmController($this->request);
Noted! We'll change it.

2023-03-03 13:37 UTC, michielbdejong commented on apps/federatedfilesharing/lib/Controller/OcmController.php
> +			$controller = \OCA\FederatedGroups\Application::getOcmController($this->request);
Btw, the reference to "the other PR" is [this discussion](https://github.com/owncloud/core/pull/40577#discussion_r1085438465)

2023-03-03 14:17 UTC, michielbdejong commented on apps/federatedfilesharing/lib/Controller/OcmController.php
> +			$controller = \OCA\FederatedGroups\Application::getOcmController($this->request);
I guess it could work with something like the PHP equivalent of the [stopImmediatePropagation pattern](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) which I know from the browser world, but it still feels like using a config variable that is the name of a class, like in https://github.com/owncloud/core/blob/838d8819411aee8d661e2b29514efca6d101eefc/apps/files_sharing/lib/Controller/ShareesController.php#L385-L389 is a better approach here.

2023-04-13 04:26 UTC, phil-davis commented
@michielbdejong https://drone.owncloud.com/owncloud/core/38230/3/7
It still fails code-style checks. If you fix those very minor things then we will get to see the results of unit tests and acceptance tests.

https://drone.owncloud.com/owncloud/core/38230/6/8
You might also need to add some "ignores" to `phpstan.neon` for the `Access to an undefined property` messages.

2023-04-13 07:39 UTC, michielbdejong commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +		} elseif ($shareType === Share::SHARE_TYPE_REMOTE || $shareType === Share::SHARE_TYPE_REMOTE_GROUP) {
@navid-dada can you check if this one is needed? It looks like maybe this is code that deals with OCS and not OCM

2023-04-13 07:42 UTC, michielbdejong commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +		} elseif ($shareType === Share::SHARE_TYPE_REMOTE || $shareType === Share::SHARE_TYPE_REMOTE_GROUP) {
Let's try without this change and we can add it back if we do find we need it.

2023-04-13 09:05 UTC, phil-davis commented on apps/federatedfilesharing/lib/Controller/OcmController.php
> +		  	return $controller->processNotification(
This line has tab, tab, space, space, tab - the 2 spaces are what is causing code-style to complain.

2023-04-14 12:11 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38252/68
<!-- id: pr-40589 -->

2023-04-17 11:22 UTC, jvillafanez commented
Just saying that the commits should be squashed when the PR is ready to merge.

2023-04-18 12:40 UTC, michielbdejong commented on apps/files_sharing/lib/Controller/Share20OcsController.php
> +		} elseif ($shareType === Share::SHARE_TYPE_REMOTE || $shareType === Share::SHARE_TYPE_REMOTE_GROUP) {
As discusses with @navid-dada, yes it's needed.

2023-04-19 10:26 UTC, michielbdejong commented
Hm, build was killed, I'm not sure why.

2023-04-19 11:46 UTC, jvillafanez commented
There are some tests failing in https://drone.owncloud.com/owncloud/core/38306/148/18

```
{"reqId":"hKNpkBk8bIqVRcbEE0R2","level":4,"time":"2023-04-19T09:20:55+00:00","remoteAddr":"192.168.28.5","user":"Alice","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Alice\/","message":"Exception: No share provider for share type 7: {\"Exception\":\"OC\\\\Share20\\\\Exception\\\\ProviderException\",\"Message\":\"No share provider for share type 7\",\"Code\":0,\"Trace\":\"#0 \\\/drone\\\/src\\\/lib\\\/private\\\/Share20\\\/Manager.php(160): OC\\\\Share20\\\\ProviderFactory->getProviderForType()\\n#1 \\\/drone\\\/src\\\/lib\\\/private\\\/Share20\\\/Manager.php(1272): OC\\\\Share20\\\\Manager->shareTypeToProviderMap()\\n#2 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(146): OC\\\\Share20\\\\Manager->getAllSharesBy()\\n#3 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(197): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->getSharesForNodeIds()\\n#4 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties()\\n#5 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1052): Sabre\\\\DAV\\\\Server->emit()\\n#6 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(984): Sabre\\\\DAV\\\\Server->getPropertiesByNode()\\n#7 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1662): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath()\\n#8 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1642): Sabre\\\\DAV\\\\Server->writeMultiStatus()\\n#9 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(83): Sabre\\\\DAV\\\\Server->Sabre\\\\DAV\\\\{closure}(*** sensitive parameters replaced ***)\\n#10 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n#11 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#12 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n#13 \\\/drone\\\/src\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#14 \\\/drone\\\/src\\\/remote.php(165): require_once('\\\/drone\\\/src\\\/apps...')\\n#15 {main}\",\"File\":\"\\\/drone\\\/src\\\/lib\\\/private\\\/Share20\\\/ProviderFactory.php\",\"Line\":138}"}
{"reqId":"hKNpkBk8bIqVRcbEE0R2","level":3,"time":"2023-04-19T09:20:55+00:00","remoteAddr":"192.168.28.5","user":"Alice","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Alice\/","message":"Cannot modify header information - headers already sent by (output started at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Message.php:117) at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Sapi.php#66"}
{"reqId":"hKNpkBk8bIqVRcbEE0R2","level":3,"time":"2023-04-19T09:20:55+00:00","remoteAddr":"192.168.28.5","user":"Alice","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Alice\/","message":"Cannot modify header information - headers already sent by (output started at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Message.php:117) at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Sapi.php#70"}
{"reqId":"hKNpkBk8bIqVRcbEE0R2","level":3,"time":"2023-04-19T09:20:55+00:00","remoteAddr":"192.168.28.5","user":"Alice","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Alice\/","message":"Cannot modify header information - headers already sent by (output started at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Message.php:117) at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Sapi.php#70"}
{"reqId":"hKNpkBk8bIqVRcbEE0R2","level":3,"time":"2023-04-19T09:20:55+00:00","remoteAddr":"192.168.28.5","user":"Alice","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Alice\/","message":"Cannot modify header information - headers already sent by (output started at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Message.php:117) at \/drone\/src\/lib\/composer\/sabre\/http\/lib\/Sapi.php#70"}
```

2023-04-21 07:08 UTC, navid-shokri commented
@phil-davis 
I fixed all the tests locally but Pipelines are failing. we cannot find the root cause of this. is it an infrastructure failure or are there some errors on our side? would you be able to review the process and let us know if there are any points to regard?

2023-04-21 08:03 UTC, phil-davis commented
@navid-shokri I have taken a copy of this code, rebased and made PR #40749 and put `full-ci` in the title.

I will have a look at what is failing and see if I can fix it...

2023-04-21 15:20 UTC, phil-davis commented
@navid-shokri @michielbdejong I have got the PHP unit tests and the acceptance tests passing.
See the extra commits in PR #40749 - cherry-pick those, or copy the code, whatever.

The JavaScript tests are also failing. You should have a look at that. I haven't looked at what JS you have touched.
https://drone.owncloud.com/owncloud/core/38320/8/4

2023-06-30 11:50 UTC, michielbdejong commented
@phil-davis all checks have passed! :)

2023-07-03 08:50 UTC, phil-davis commented
I made a separate PR with this code rebased to current master. That demonstrates that the CI passes right today.

@DeepDiver1975 @jvillafanez please review. I  can't really review this effectively because I am not familiar enough with exactly what core "hook points" are needed.

2023-07-03 11:10 UTC, jvillafanez reviewed
In general, for the js code all the sentences should end with `;` for consistency

2023-07-03 11:10 UTC, jvillafanez commented on apps/files_sharing/lib/Controllers/ExternalSharesController.php
> +		if ($share_type === "group" && $this->groupExternalManager !== null) {
You've already have a `getManagerForShareType` method.

2023-07-03 11:10 UTC, jvillafanez commented on apps/files_sharing/lib/Controllers/ExternalSharesController.php
> +		if ($share_type === "group" && $this->groupExternalManager !== null) {
It seems better to compare the share type against a constant.

2023-07-03 11:10 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +		if ($share === null) {
What about moving this block inside the `catch (ShareNotFound $ex)`?

2023-07-03 11:10 UTC, jvillafanez commented on lib/private/Share20/Manager.php
> +			} catch (ProviderException $ex) {
This requires either a comment or a log.

2023-07-03 11:14 UTC, jvillafanez commented
Not sure who can test this, but we need to ensure there are no problems with this new code with and without the app.

2023-07-03 11:27 UTC, phil-davis commented
"without the app" should be OK - the full CI test suite passes, including various federated API acceptance tests etc. So there is not any regression found when running a system without the app and without `sharing.ocmController` set.

If someone sets `sharing.ocmController` but does not install the/an app that has code that provides things like a `createShare` method, then there will be trouble. But I suppose this is a "plugin" that would only be "supported" for installations that are managing this stuff.

2023-07-14 06:56 UTC, soltanireza65 commented on apps/files_sharing/js/app.js
> +				...(!!shareType && { shareType }),
this is an es6+ syntax
the requests body needs to be in a stringified js object
what this line is trying to do is :
check if `shareType` exists make an object as : 
```json
{"shareType" : shareType} 
```
and pass it to JSON.stringify and then pass the stringified object as a body
so if shareType does not exist body would be an empty object

2023-07-14 07:10 UTC, soltanireza65 commented on apps/files_sharing/js/app.js
> +				...(!!shareType && { shareType }),
it's the same as:
```javascript
JSON.stringify((Boolean(shareType) ? { shareType: shareType } : {}))
```

2023-07-14 11:18 UTC, jvillafanez commented on apps/files_sharing/js/app.js
> +			data: JSON.stringify((Boolean(shareType) ? { shareType: shareType } : {})),
Isn't it better `(shareType === undefined ? ......)`?
I'd expect the shareType to be an integer (1,2,3....) or a string (user, group, remote...), so converting them to a boolean seems weird, specially when it isn't the main case. If the only additional case we need to handle is the "undefined", then checking for `shareType === undefined` makes it clearer.
If there are additional cases that I'm not aware of, we might need a code comment so we know what can be set in the shareType parameter.

2023-07-14 12:27 UTC, soltanireza65 commented on apps/files_sharing/js/app.js
> +			data: JSON.stringify((Boolean(shareType) ? { shareType: shareType } : {})),
if the shareType happens to be an empty string (for whatever reason) it will not result in undefined, so the condition may not work as expected
so the base case is to cast conditions to bool unless we are 100% sure

2023-07-14 13:15 UTC, jvillafanez commented on apps/files_sharing/js/app.js
> +			data: JSON.stringify((Boolean(shareType) ? { shareType: shareType } : {})),
I'm not fully convinced...

If we consider the empty string as invalid in order to not send it to the server, we should also include strings such as "aaa" or "bbb" which don't make sense for a share type.
It seems something that should be handled in the server, so if the client sends an empty share type (or any other invalid type), the server can reject the request (or assume a default share type, whatever is more convenient).

I think the best compromise is to include a code comment explaining the expectations, so we know that we don't want to send an empty string as shareType.

2023-07-15 12:18 UTC, phil-davis commented
https://drone.owncloud.com/owncloud/core/38743/5/1 cancel-previous-builds is no longer part of drone CI, due to changes to drone secrets in the last week or two.

Please rebase this PR to latest master, then the CI should work again.

2023-07-16 08:41 UTC, phil-davis commented
Now there are 220 commits in this PR - what happened???

2023-07-17 07:10 UTC, T0mWz commented
When appling this patch, I got;
```
Exception: No share provider for share type 7
```

Maybe good to verify behavior without Sciencemesh app, or it should be default shipped.

2023-07-17 07:55 UTC, phil-davis commented
> Now there are 220 commits in this PR - what happened???

I cherry-picked what I think are the real commits for this PR and created PR #40877 - that should be easier to review, rather than whatever happened here to have 221 commits listed.

2023-07-17 10:24 UTC, jvillafanez commented
Left a comment in https://github.com/owncloud/core/pull/40877/files#r1265137966 , but for the rest the other PR looks good.

> When appling this patch, I got;
Exception: No share provider for share type 7
Maybe good to verify behavior without Sciencemesh app, or it should be default shipped.

Maybe a problem in https://github.com/owncloud/core/pull/40877/files#diff-6c825986578290fe355bffe05c5232629a36e554d48f5d889bb2c1ec73645265R1542
I think we'll have to check what providers are available before trying to get an optional one.

> Now there are 220 commits in this PR - what happened???

We need to decide how to move forward. Options are:
* They fix the branch on their side
* They open a new PR with the relevant changes. Basically https://github.com/owncloud/core/pull/40877 but on their side so they can keep applying the changes needed.
* We take over the PR from https://github.com/owncloud/core/pull/40877 . This doesn't seem a good solution because I don't think we can test the whole solution, just that it doesn't break if the app isn't installed.

2023-08-10 07:59 UTC, phil-davis commented
@michielbdejong @shokri-navid 
was this done in #40886 ?

Can we close this PR?

2023-08-10 08:10 UTC, jvillafanez commented
I think this is the old PR that got broken and was superseded by the one that was already merged, but we can wait for confirmation.

2023-08-23 14:09 UTC, michielbdejong commented
Superseded by #40886

2023-08-23 14:09 UTC, closed without merging