tweak rewrite conditions in htaccess
owncloud/core pull request #40584
Opened 2023-01-17 13:52 UTC by C0rby

This change hardens the rewrite rules to match the exact paths we want and not any subpaths e.g. `/somefolder/status.php`. 

Thanks to Terry Franklin, Matt Harris, Hayden Barker and Colin Smith (aka yoloClin) from Radiant Security (https://radiant.security) for reporting this.

2023-01-17 13:57 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37669/45
<!-- id: pr-40584 -->

2023-01-17 14:56 UTC, xoxys approved these changes

2023-01-17 15:09 UTC, C0rby commented
@IljaN, could you maybe tell me why the test is failing?
I'm not sure if this is because of my change.

2023-01-17 16:39 UTC, DeepDiver1975 commented
https://github.com/owncloud/core/blob/32b69847223ef45f4cc4516e99864d407e63f0e5/tests/acceptance/run.sh#L764

2023-01-17 16:41 UTC, DeepDiver1975 requested changes, later dismissed

2023-01-17 16:41 UTC, DeepDiver1975 commented on lib/private/Setup.php
> +			$content .= "\n  RewriteCond %{REQUEST_FILENAME} !^/core/img/favicon.ico$";
`$` has to be escaped

2023-01-18 08:34 UTC, C0rby commented on lib/private/Setup.php
> +			$content .= "\n  RewriteCond %{REQUEST_FILENAME} !^/core/img/favicon.ico$";
I'm not so sure about that. This line already has a `$` which is not escaped and that was working before.
https://github.com/owncloud/core/blob/24fd78db1debb4b0f1523aefc94f9bb4f3b19e74/lib/private/Setup.php#L500

2023-01-18 09:13 UTC, DeepDiver1975 commented on lib/private/Setup.php
> +			$content .= "\n  RewriteCond %{REQUEST_FILENAME} !^/core/img/favicon.ico$";
true .... 

well run the occ command yourself and debug it :see_no_evil:

2023-01-19 21:08 UTC, ho4ho commented on lib/private/Setup.php
> +			$content .= "\n  RewriteCond %{REQUEST_FILENAME} !^/status.php$";
```suggestion
			$content .= "\n  RewriteCond %{REQUEST_FILENAME} !^/status\\.php$";
```

Also needing escaping to not machting by `status-php`?

2023-01-25 04:42 UTC, mdusher commented
It may be worth looking at swapping `%{REQUEST_FILENAME}` out for `%{REQUEST_URI}` as according to the mod_rewrite documentation (https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) there is some cases where `%{REQUEST_FILENAME}` can resolve to the full local path of the script/file (eg. /var/www/owncloud/status.php instead `/status.php`) which would break those `RewriteCond` rules.

2023-01-31 17:01 UTC, C0rby commented
> It may be worth looking at swapping `%{REQUEST_FILENAME}` out for `%{REQUEST_URI}` as according to the mod_rewrite documentation (https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) there is some cases where `%{REQUEST_FILENAME}` can resolve to the full local path of the script/file (eg. /var/www/owncloud/status.php instead `/status.php`) which would break those `RewriteCond` rules.

That is actually why the CI failed.... Thanks for the hint. :+1:

2023-02-01 04:50 UTC, phil-davis commented
@C0rby is a changelog needed for this?

2023-02-01 14:01 UTC, C0rby commented
> @C0rby is a changelog needed for this?

I added one. :+1:

2023-02-01 20:05 UTC, IljaN approved these changes

2023-02-01 23:11 UTC, merged

2023-03-15 22:27 UTC, ho4ho commented
Looked like issues cause by this by users have now this by upgradation by ownCloud 10.12.0 :-/

> Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.

https://central.owncloud.org/t/owncloud-stoped-working-after-update/41513

2023-03-15 22:29 UTC, ho4ho commented
Problem could be cause by new adding `^` not match by e.g. `/owncloud/remote.php` if use sub-dir install?

2023-03-16 08:13 UTC, C0rby commented
> Problem could be cause by new adding `^` not match by e.g. `/owncloud/remote.php` if use sub-dir install?

I did test sub-dir installations and that worked at that time but maybe I've missed something.

2023-03-25 09:10 UTC, ho4ho commented
Workaround document by https://github.com/owncloud/docs/pull/4823