Adjust stream chunk size to load big exif metadata
owncloud/core pull request #40600
Opened 2023-01-24 10:47 UTC by jvillafanez

## Description
There were problems loading the exif metadata of some images if the metadata was too large. This was causing problems loading the images because the right orientation was in the metadata that wasn't loaded.

## Related Issue
https://github.com/owncloud/enterprise/issues/5500

## Motivation and Context
Users expect the image to be loaded with the right orientation, like most of the apps.

## How Has This Been Tested?
Just upload the image below:
![portrait](https://user-images.githubusercontent.com/1477829/214271825-1c96afd7-0798-4500-8ab7-a6f04f42755a.jpg)

Tested with and without encryption. I'm not aware of any additional stream wrapper that could affect the behavior (quota isn't applied to read streams)

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

Supersedes https://github.com/owncloud/core/pull/40586

2023-01-25 03:51 UTC, phil-davis reviewed
changelog needed

2023-01-25 03:51 UTC, phil-davis commented on lib/private/legacy/image.php
> +	 * the "exif_red_data" native method to read a whole chunk of metadata
```suggestion
	 * the "exif_read_data" native method to read a whole chunk of metadata
```

2023-01-25 08:10 UTC, phil-davis reviewed
Looks reasonable to me. Needs a dev to review.

2023-01-26 11:41 UTC, DeepDiver1975 requested changes
My usual question: unit test? :see_no_evil:

2023-01-26 11:41 UTC, DeepDiver1975 commented on lib/private/legacy/image.php
> +			\stream_set_chunk_size($stream, 64 * 1024);
error handling?

2023-01-26 11:43 UTC, DeepDiver1975 commented on lib/private/legacy/image.php
> +			\stream_set_chunk_size($stream, 64 * 1024);
ok - not really - it only fails if the chunk size is negative or bigger then php max int ....https://www.php.net/manual/en/function.stream-set-chunk-size.php

2023-01-26 12:36 UTC, jvillafanez commented
I don't think unit tests are possible in the strict sense. We need a custom stream wrapper to trigger the behavior, so we either create a custom wrapper just for the tests or use ownCloud's node or view object to get the stream.

Even if we include integration tests as unit tests, it will take some time (estimate ~2 days) and it's unlikely to cover all the cases (need to find TIFF images that trigger this behavior).

2023-01-26 12:49 UTC, mrow4a commented
> I don't think unit tests are possible in the strict sense. We need a custom stream wrapper to trigger the behavior, so we either create a custom wrapper just for the tests or use ownCloud's node or view object to get the stream.
> 
> Even if we include integration tests as unit tests, it will take some time (estimate ~2 days) and it's unlikely to cover all the cases (need to find TIFF images that trigger this behavior).

I think it would be good to cover it with some integration test. Same story as with https://github.com/owncloud/files_classifier/tree/master/tests/acceptance/data and https://github.com/owncloud/files_classifier/blob/master/tests/unit/DocumentPropertiesTest.php#L37-L67

2023-01-30 09:35 UTC, pako81 commented
@jvillafanez @mrow4a do we want to have tests for this one?

2023-01-30 10:06 UTC, jvillafanez commented
If it's required, I'd vote for open a tech debt ticket to include the tests because it will take time. Note that, as said, we'd need to create a custom wrapper to trigger the behavior.

2023-02-02 11:28 UTC, jvillafanez commented
I've added a test that should cover the main use case, but there are things still not covered:
* TIFF images aren't loaded with the gd extension. This means that the code will be left untested for .tiff files. Currently, the exif data is loaded only if the image is loaded, so we'd need to change the code to load the exif data regardless of the images, but the data is pointless if we can't load the image.
* We're using the `close` stream wrapper because it seems the easiest one we can reuse. However, this will trigger a warning due to the missing `getSource` method. This is still ok for the tests because there isn't any additional custom wrapper in the stream whose chunk size needs to be adjusted. It shouldn't cause problems.

2023-02-06 08:52 UTC, jvillafanez commented
@DeepDiver1975 is this good enough?

2023-02-08 09:39 UTC, DeepDiver1975 requested changes

2023-02-08 09:39 UTC, DeepDiver1975 commented on tests/lib/ImageTest.php
> +		$this->assertSame(6, $img->getOrientation());  // orientation = right, top
all assert functions of phpunit are static if I am not totally miss taken ....

Should be self::assertSame ...

2023-02-08 09:49 UTC, phil-davis commented on tests/lib/ImageTest.php
> +		$this->assertSame(6, $img->getOrientation());  // orientation = right, top
`$this->assertSomething()` is done throughout the existing code.
But yes, the asserts are like:
```
    public static function assertSame($expected, $actual, string $message = ''): void
```

I wonder why we have done `$this->` rather than `self::` for all these years?

2023-02-08 09:54 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37892/52
<!-- id: pr-40600 -->

2023-02-08 09:54 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37892/44
<!-- id: pr-40600 -->

2023-02-08 10:08 UTC, phil-davis commented
I restarted CI - some pipelines failed when initially fetching docker images.

2023-02-08 10:09 UTC, DeepDiver1975 commented on tests/lib/ImageTest.php
> +		$this->assertSame(6, $img->getOrientation());  // orientation = right, top
Maybe because earlier versions of phpunit have been using `this->` ... no idea ..

I tend to fix such things when touching any code base ..... my idea is even throwing this as warnings into my face :shrug:

2023-02-08 11:26 UTC, DeepDiver1975 approved these changes

2023-02-08 11:26 UTC, merged