Fix two-factor enable over API
owncloud/core pull request #40617
Opened 2023-02-03 11:48 UTC by pako81

## Description

Fix reactivation of two-factor auth when using provisioning API.

## Motivation and Context
Using the provisioning API for reenabling two-factor auth for an user is currently broken.

1. Running:

```
curl -X PUT http://admin:admin@example.com/ocs/v1.php/cloud/users/user1 -d key="two_factor_auth_enabled" -d value="false"
```

correctly disable two-factor auth for that user. The configkey `two_factor_auth_disabled` is correctly set to the configvalue `1` in `oc_preferences` and user can normally login with username/password.

2. However, running:

 ```
curl -X PUT http://admin:admin@example.com/ocs/v1.php/cloud/users/user1 -d key="two_factor_auth_enabled" -d value="true"
```

does not correctly reenable two-factor auth for the user. The configkey `two_factor_auth_disabled` is not removed from the `oc_preferences` table and two-factor is still not enforced.

## How Has This Been Tested?
Manually:

By following the steps above.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised
- [ ] Changelog item

2023-02-08 09:32 UTC, DeepDiver1975 requested changes
change log is missing - will add it

2023-02-08 09:34 UTC, DeepDiver1975 approved these changes

2023-02-08 10:04 UTC, phil-davis approved these changes

2023-02-08 10:15 UTC, merged

2023-03-02 23:45 UTC, jnweiger commented
Confirmed fixed in 10.12.0-rc.2
`-d key="two_factor_auth_enabled" -d value="true"` works correctly, however
`-d key="two_factor_auth_enabled" -d value="yes"` or
`-d key="two_factor_auth_enabled" -d value="1"` dont. the 'two_factor_auth_disabled' configkey' remains at 1.

2023-03-03 09:27 UTC, pako81 commented
AFAICT `two_factor_auth_enabled` is currently the only boolean value when editing the user https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/Users.php#L295-L339. Do we want to also cover the case `yes/no` and `1/0` ?

2023-03-03 09:31 UTC, DeepDiver1975 commented
Boolean values are true and false.
No need to support anything else