[full-ci][tests-only][donot-merge]Try json drilling with library
owncloud/core pull request #40619
Opened 2023-02-06 03:59 UTC by SagarGi

### Description
This PR is the json drill down of the response data using `helmich/phpunit-json-assert` library which is alternative process of this PR https://github.com/owncloud/core/pull/40562

### Related Issue:
https://github.com/owncloud/core/issues/39796

2023-02-06 09:13 UTC, SagarGi commented
***Notes:***
- The only thing i doubt about using this library is if the json check or drilling is to long then the response to match value is also too  long that might decrease the readability of the feature file which is actually is the key point to a feature file.

But also has many benefits over this PR https://github.com/owncloud/core/pull/40562.

2023-02-07 05:59 UTC, individual-it requested changes

2023-02-07 05:59 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		$arrayResponse = json_decode($jsonResponse);
that does not feel right to have the XML response checked with JSON.
I would suggest to check the JSON responses with this system. e.g. the capabilities can be retrieved as JSON by adding `?format=json` to the URL

2023-02-07 05:59 UTC, individual-it commented on tests/acceptance/features/apiCapabilities/jsonDrillExample.feature
> +    And the data of the response should match
```suggestion
    And the JSON data of the response should match
```

2023-02-08 10:08 UTC, SagarGi commented
Some findings to be able to implement the above comment https://github.com/owncloud/core/pull/40619#discussion_r1098208051 .

1. Using `?format=json` at each endpoint of an API, we might need to refactor test suites according to it like i have done in this PR.
2. Also some API responses does not always doesn't give `json` so we will have to adjust the test both in `xml` and `json` as per requirements.  

need some suggestion towards it @individual-it @phil-davis

2023-02-09 11:25 UTC, ScharfViktor commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +    And the JSON data of the response should match
My question (maybe stupid):
Can I compare not all fields? Or `the JSON data of the response` be identical to the response?

2023-02-09 11:26 UTC, ScharfViktor commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +#      | files         | privateLinksDetailsParam                  | 1                 |
you left that for comparison, right?

2023-02-13 03:27 UTC, SagarGi commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +#      | files         | privateLinksDetailsParam                  | 1                 |
yes !!

2023-02-13 03:29 UTC, SagarGi commented on tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
> +    And the JSON data of the response should match
yes we can send the expected JSON according to our requirement. It is not mandatory we check all the json response.

2023-02-13 07:01 UTC, phil-davis commented
For test scenarios where we check all (or almost all) items in the JSON response, using `assertJsonDocumentMatchesSchema` seems OK to me. The schema that goes in the test scenario is a bit of a long thing. But these tests are technical tests of the content of API responses anyway. The scenarios in the feature files only need to be readable by reasonably-technical people anyway, not "mere mortal" users.

But we also have various tests that individually check that the system-under-test can change something, and the change is seen in the API response. This sort of thing:
```
  Scenario: lock file action can be enabled
    Given parameter "enable_lock_file_action" of app "files" has been set to "yes"
    When the administrator retrieves the capabilities using the capabilities API
    Then the OCS status code should be "100"
    And the HTTP status code should be "200"
    And the capabilities should contain
      | capability | path_to_element                 | value |
      | files      | file_locking_support            | 1     |
      | files      | file_locking_enable_file_action | 1     |
```
For these type of scenarios, we only care that the particular items in the response exist and have the expected values.
We could use `assertJsonValueMatches` for that, looping through each item in "the capabilities should contain".
And the table used for the step could have the items in JSON-path format
```
    And the capabilities should contain
      | JSONpath                                            | value |
      | $.files.file_locking_support                  | 1     |
      | $.files.file_locking_enable_file_action | 1     |
```

2023-02-13 07:14 UTC, phil-davis commented
Actually, we can probably keep the scenarios in close to their current format, and just replace `capability` and `path_to_element` columns with `JSONpath`. And write the JSON path of each element.

And the underlying code can just check each JSON path using `assertJsonValueMatches`

And adjust the words and underlying code for steps like:
```
Then the capabilities setting of "files_sharing" path "group_sharing" should be "1"
```
to something like:
```
Then the capabilities setting "$.files_sharing.group_sharing" should be "1"
```
That would be just an alternative step format for:
```
Then the capabilities should contain
  | JSONpath | value |
  | $.files_sharing.group_sharing | 1 |
```

I am not sure if we actually really need or want this alternative step. It might be easiest to just refactor those so that they are all using `Then the capabilities should contain`

2023-02-13 08:19 UTC, individual-it commented
Anyway we don't have to write down every detail of the structure into the schema, only what we care about. 
```
{
"name": "Phil",
"surname": "Davis"
}
```
would be matched by the schema:
```
{
   "type": "object",
   "required": [ "name"],
   "properties": [
        "name": [ "type": "string", "enum": ["Phil"] ]
    ]
}
```

2023-02-13 08:43 UTC, phil-davis commented
> Anyway we don't have to write down every detail of the structure into the schema, only what we care about

If that is true, then great. How fussy is `assertJsonDocumentMatchesSchema` ?

If the JSON has all the things mentioned in the expected schema, plus more, does `assertJsonDocumentMatchesSchema` still pass?

2023-02-13 10:31 UTC, phil-davis commented
OK - then `assertJsonDocumentMatchesSchema` can do enough flexible stuff for us to just use that.

2023-02-13 11:14 UTC, SagarGi commented
> OK - then `assertJsonDocumentMatchesSchema` can do enough flexible stuff for us to just use that.

@phil-davis @individual-it If so then i will be make some refactor and make this as a sample PR for suite `apiCapabilities` we can check other suites where such drilling is done and adjust accordingly.

2023-02-16 05:25 UTC, individual-it reviewed
LGTM. @ScharfViktor  @phil-davis what do you think? Should we merge this and refactor other tests also?
Or rather just use that for new tests?

2023-02-16 07:22 UTC, ScharfViktor commented
> LGTM. @ScharfViktor @phil-davis what do you think? Should we merge this and refactor other tests also? Or rather just use that for new tests?

Are we introducing new tests into the core?
For ocis, I would use this approach for contract tests, get rid of "@@@" and use in new tests

2023-02-16 08:13 UTC, individual-it commented
No, we are not adding any tests to core (except if there are new features).
I meant to say: merge this here, bring the same change to ocis, and use it in ocis for new tests

2023-02-16 08:20 UTC, ScharfViktor commented
> No, we are not adding any tests to core (except if there are new features). I meant to say: merge this here, bring the same change to ocis, and use it in ocis for new tests

I totally agree.

2023-02-17 07:57 UTC, phil-davis approved these changes
LGTM
I think that the commits should be squashed, it will be a bit confusing in future if we have such a long list of commits merged in master, if someone is trying to work out what happened.

And then we can:
- do similar in ocis
look at the other uses of `@@@` in the acceptance tests and design a way to refactor those away

2023-02-17 07:58 UTC, phil-davis commented
@individual-it please review again. I think that we can squash and then merge this.

2023-02-17 08:15 UTC, individual-it approved these changes

2023-02-17 08:15 UTC, merged