Add rewrite base to generated .htaccess rules
owncloud/core pull request #40697
Opened 2023-03-24 08:34 UTC by IljaN

## Description
If htaccess.RewriteBase is set we need to prepend it in the generated rules.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/40696
- Related https://github.com/owncloud/core/pull/40584

## Motivation and Context
The [hardened .htaccess fix](https://github.com/owncloud/core/pull/40584) caused a regression for installations which have owncloud in a subfolder.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2023-03-24 08:38 UTC, IljaN commented on lib/private/Setup.php
>  			$content .= "\n  RewriteBase " . $rewriteBase;
Hmhh this would probably dont put a "/" here

2023-03-24 08:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38112/60
<!-- id: pr-40697 -->

2023-03-24 08:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38112/54
<!-- id: pr-40697 -->

2023-03-24 08:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38112/51
<!-- id: pr-40697 -->

2023-03-24 09:25 UTC, jnweiger requested changes
A literal unescaped $rewriteBase can destroy the regexp. 
We need to apply proper regexp escaping, this is a security relevant.

2023-03-24 09:47 UTC, IljaN commented
We could do this in a addtional PR by sanitizing $rewriteBase with [preg_quote](https://www.php.net/manual/en/function.preg-quote.php). But IMO offtopic for this PR. A path shouldn't contain any Regex characters and is coming from the trusted config anyways, no?

2023-03-24 09:48 UTC, IljaN commented
Fail: https://drone.owncloud.com/owncloud/core/38114/172/15

2023-03-24 10:22 UTC, jnweiger commented
> We could do this in a addtional PR by sanitizing $rewriteBase with [preg_quote](https://www.php.net/manual/en/function.preg-quote.php). But IMO offtopic for this PR. A path shouldn't contain any Regex characters and is coming from the trusted config anyways, no?

No, I don't think so. This path is perfectly legal, imho.
occ config:system:set htaccess.RewriteBase --value '/funny$nameing-scheme-*-but+we+like+it'


Pfft. On another thought, we don't quote strings in .htaccess, that means it breaks apart, when RewriteBase contains whitespace...

2023-03-24 10:30 UTC, jnweiger commented on lib/private/Setup.php
> +			$rewriteBase_re = \preg_quote($rewriteBase_re);
```suggestion
			$rewriteBase_re = \preg_quote($rewriteBase);
```

2023-03-24 10:51 UTC, IljaN commented on lib/private/Setup.php
> +			$rewriteBase_re = \preg_quote($rewriteBase_re);
Okay definetly makes sense for "-" characters. Thx

2023-03-25 09:07 UTC, ho4ho commented
Fix #40686 also

2023-03-25 13:22 UTC, jnweiger approved these changes

2023-03-25 14:13 UTC, ho4ho commented on lib/private/Setup.php
> +			$content .= "\n  RewriteCond %{REQUEST_URI} !^$rewriteBaseRe/\\.well-known/(acme-challenge|pki-validation)/.*";
```suggestion
			$content .= "\n  RewriteCond %{REQUEST_URI} !^/\\.well-known/(acme-challenge|pki-validation)/.*";
```

Thinking always needing at root and not by subfolder.

2023-03-27 21:35 UTC, jnweiger approved these changes

2023-03-28 13:32 UTC, merged