Added "Continue" link to error page (#40909)
owncloud/core pull request #40910
Opened 2023-08-07 13:09 UTC by mijarena

## Description

## Related Issue

- #40909

## Motivation and Context
User can quickly return to the starting page when encountering an error.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):
![image](https://github.com/owncloud/core/assets/85600105/02eb58ce-91b9-421b-961b-16dcec7e029d)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2023-08-07 13:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/core?pullRequest=40910) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/core?pullRequest=40910) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/core?pullRequest=40910) it.</sub>

2023-08-07 13:32 UTC, jnweiger requested changes
href="/" is not always correct.

There are two config variables that need to be taken into account:
```
/**
 * Define the Web base URL
 * This key is necessary for the navigation item to the new ownCloud Web UI and for redirecting
 * public and private links.
 */
'web.baseUrl' => '',
/**
 * Define clean URLs without `/index.php`
 * This parameter will be written as `RewriteBase` on update and installation of
 * ownCloud to your `.htaccess` file. While this value is often simply the URL
 * path of the ownCloud installation it cannot be set automatically properly in
 * every scenario and needs thus some manual configuration.
 *
 * In a standard Apache setup this usually equals the folder that ownCloud is
 * accessible at. So if ownCloud is accessible via `https://mycloud.org/owncloud`
 * the correct value would most likely be `/owncloud`. If ownCloud is running
 * under `https://mycloud.org/` then it would be `/`.
 *
 * Note that the above rule is not valid in every case, as there are some rare setup
 * cases where this may not apply. However, to avoid any update problems this
 * configuration value is explicitly opt-in.
 *
 * After setting this value run `{occ-command-example-prefix} maintenance:update:htaccess`. Now, when the
 * following conditions are met ownCloud URLs won't contain `index.php`:
 *
 * - `mod_rewrite` is installed
 * - `mod_env` is installed
 */
'htaccess.RewriteBase' => '/',
```

2023-08-11 12:31 UTC, mijarena commented
Fixed on 403 page, too

2023-08-11 14:02 UTC, jnweiger approved these changes
Work in all my test cases.
* admin permission, wrong file id
* index.php less and other
* / and subfolder install.

2023-08-11 14:41 UTC, IljaN commented
- Should we make the "Continue" prettier. Maybe under the message box? But fine for me.
- CI is failing https://drone.owncloud.com/owncloud/core/38908/3/7
- Please add a changelog entry https://github.com/owncloud/core/pull/40910#issuecomment-1667830427
- Added additional reviewers since we worked on the code together ;)

2023-08-11 14:45 UTC, IljaN requested changes
- Should we make the "Continue" prettier. Maybe under the message box? But fine for me.
- CI is failing https://drone.owncloud.com/owncloud/core/38908/3/7
- Please add a changelog entry https://github.com/owncloud/core/pull/40910#issuecomment-1667830427
- Added additional reviewers since we worked on the code together ;)

2023-08-13 19:33 UTC, mijarena commented
I made this to be working correctly So it could be an accepted feature for the next release. I planed to polish code, style and translation next during beta.

2023-08-14 09:03 UTC, jvillafanez reviewed
Not sure if it's easy to add some basic unit tests.

2023-08-14 09:03 UTC, jvillafanez commented on apps/files/lib/Controller/ViewController.php
> +					"base_url" => \OC::$server->getURLGenerator()->getAbsoluteURL("/"),
Is it possible to inject the `URLGenerator`?

2024-11-19 07:49 UTC, DeepDiver1975 commented
cleaning up - I think this is no longer of anybody's interest

2024-11-19 07:49 UTC, closed without merging