Fix issue with LDAP groups in the applicable field
owncloud/core pull request #41063
Opened 2023-10-25 11:52 UTC by jvillafanez

## Description
The "applicable" field in the external storage configuration wasn't working for LDAP groups. This issue happens on new installations where the configured LDAP attribute for the groupname is the "objectguid" or "entryuid".
Old installations should have the "cn" attribute configured instead, which should match the configured displayname for the group, so the issue shouldn't happen

## Related Issue
https://github.com/owncloud/core/issues/41062

## Motivation and Context
The "applicable" field should work properly regardless of the LDAP configuration. In particular, the default configuration should work.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2023-10-30 04:46 UTC, phil-davis reviewed
Just a few comments on the changelog

2023-10-30 04:46 UTC, phil-davis commented on changelog/unreleased/41063
> +to be accessed by those group.
```suggestion
Now, users belonging to LDAP groups can access external storages configured
to be accessed by those groups.
```

2023-10-30 04:46 UTC, phil-davis commented on changelog/unreleased/41063
> +that group weren't be able to access to the external storage even though they
```suggestion
that group weren't able to access the external storage even though they
```

2023-11-08 09:08 UTC, DeepDiver1975 requested changes
Just some remarks on type declarations

2023-11-08 09:08 UTC, DeepDiver1975 commented on apps/files_external/lib/Controller/ApplicableController.php
> +	private $groupManager;
add type declaration?

2023-11-08 09:08 UTC, DeepDiver1975 commented on apps/files_external/lib/Controller/ApplicableController.php
> +	public function patternSearch($pattern = '', $limit = null, $offset = null) {
add return type

2023-11-08 09:08 UTC, DeepDiver1975 commented on apps/files_external/lib/Controller/ApplicableController.php
> +	public function patternSearch($pattern = '', $limit = null, $offset = null) {
will type declarations work on controller methods?

2023-11-08 09:08 UTC, DeepDiver1975 commented on apps/files_external/lib/Controller/ApplicableController.php
> +	public function userDisplayNames($users) {
return type

2023-11-08 11:47 UTC, DeepDiver1975 requested changes

2023-11-08 11:47 UTC, DeepDiver1975 commented on apps/files_external/lib/Controller/ApplicableController.php
> +	 * @return JSONResponse
`@return` is no longer needed as soon as proper return declarations are used - same for argument type declarations (when used)

2023-11-08 11:47 UTC, DeepDiver1975 commented on apps/files_external/tests/Controller/ApplicableControllerTest.php
> +	private function createMockUser($uid, $displayname) {
return declarations everywhere please :grin: 
as well as function argument types

2023-11-14 14:10 UTC, DeepDiver1975 approved these changes

2023-11-14 14:10 UTC, merged