Display security advisory for latest CVEs
owncloud/core pull request #41137
Opened 2023-12-08 13:53 UTC by IljaN

## Description
Display security-advisory instructions if license is available in Web-UI and after an
successful upgrade.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):
![Screenshot from 2023-12-08 14-51-10](https://github.com/owncloud/core/assets/246983/61d310bc-75e4-4bc1-a73c-a6d0f7541e8e)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

2023-12-11 09:56 UTC, jnweiger requested changes
This process appears to be broken.
The warning appears with the next core release, that is fine.
After admin ran the ioc-scanner, and confirmed that the system is uncompromised,
the warning should no longer appear.

We probably need something in the ioc-scanner so that we know when it was last run.
Alerts like this one should only appear, when really needed. E.g. when the scanner was not run for some time.

Also I'd like to question the style of this alert. I suggest, the updater should instead show friendly reminder like e.g.: "Please remember to run our ioc-scanner regularly, now is a good opportunity. More details <here>."

2023-12-11 15:37 UTC, jnweiger submitted a review, later dismissed
CI build is failing in php-style step:
```
....................                                          2399 / 2399 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error
   1) core/templates/update.admin.php (braces, method_argument_space)
      ---------- begin diff ----------
--- /drone/src/core/templates/update.admin.php
+++ /drone/src/core/templates/update.admin.php
@@ -1,7 +1,7 @@
 
 <?php $license = \OC::$server->query(\OC\License\LicenseFetcher::class)->getOwncloudLicense();
 if ($license !== null) {
-?>
+	?>
 <div class="update">
 <?php include('ioc.warning.php'); ?>
 </div>
      ----------- end diff -----------

Found 1 of 2399 files that can be fixed in 58.306 seconds, 50.000 MB memory used
Detected deprecations in use:
- Rule "braces" is deprecated. Use "single_space_around_construct", "control_structure_braces", "control_structure_continuation_position", "declare_parentheses", "no_multiple_statements_per_line", "curly_braces_position", "statement_indentation" and "no_extra_blank_lines" instead.
make: *** [Makefile:222: test-php-style] Error 8
```

2023-12-12 13:27 UTC, phil-davis commented
Works for me on my local dev setup with license key. The link takes me to the ioc-scanner script and PDF with instructions. It runs and produces "good" results (I have core master 10.13.4-prealpha).

When I go back to Settings-Admin-General on the webUI, it still shows me all the same "Critical Alert" in red stuff. Would there be some benefit for that screen to know when the scanner was last run, and display that date? Or even display the results summary as well?

2023-12-12 13:36 UTC, phil-davis approved these changes
Text looks OK.
Following the links from the webUI Settings-Admin-General section works.
Script works as per the PDF instructions for my local case.

2023-12-12 13:43 UTC, DeepDiver1975 commented
> Would there be some benefit for that screen to know when the scanner was last run, and display that date? Or even display the results summary as well?

There is no automated mechanism planned for this - especially because the tool needs to be executed on all servers. We have no understanding when this will be.
A specific config parameter can be added a scanned system to suppress the alert ......

2023-12-12 14:08 UTC, jvillafanez commented on core/Command/Upgrade.php
> +			}
Using the `ILicenseManager` seems better. It can also be injected.
```
if ($licenseManager->getLicenseStateFor('core') !== ILicenseManager::LICENSE_STATE_VALID) {
....
}
```
not sure if we want to check for additional states though.

2023-12-12 14:23 UTC, jvillafanez commented
> A specific config parameter can be added a scanned system to suppress the alert ......

I'd vote for this, even if it's just an acknowledgement. Something like "I've already applied the patch" and / or "I've read the message" might be good enough.
As long as it's clear that suppressing the message won't perform any validation, it's up to the admin to decide what to do with the message even if he hasn't done anything yet.

2023-12-12 14:44 UTC, DeepDiver1975 commented on core/Command/Upgrade.php
> +			}
We explicitly don't care about the license state. License set -> highly probably a customer -> alert them

2023-12-12 14:45 UTC, DeepDiver1975 commented
> I'd vote for this, even if it's just an acknowledgement. Something like "I've already applied the patch" and / or "I've read the message" might be good enough.
> As long as it's clear that suppressing the message won't perform any validation, it's up to the admin to decide what to do with the message even if he hasn't done anything yet.

https://github.com/owncloud/core/pull/41137/files#diff-94ffa1b0139a420b5ab07b770b526cfd9d2ba152610350bdfcba5d33971bbbe6R13-R14

2023-12-13 07:33 UTC, jnweiger reviewed
We have a config.php variable that suppresses the messages.
We don't have anything automated that sets this variable after the ioc-scanner was run.
Thus I'd suggest to add a button "I have done this" in the admin view.

2023-12-13 07:53 UTC, phil-davis commented
> Thus I'd suggest to add a button "I have done this" in the admin view.

And for more feature bloat, maybe the config variable should be automatically reset on/after an upgrade. And maybe it should reset after some time period (maybe every 3 months the alert would "reappear"?) And maybe we don't want/need to design in all this sort of stuff.

More importantly, when there is a new/changed ios-scanner script available (that checks for more things, new things), how is that communicated? I suppose that the read-only public link will always have the last ioc-scanner. But how will an admin know that they should download a newer version and run it?

2023-12-13 07:57 UTC, DeepDiver1975 commented
We want no easy way to click this away.
It must be hard. Best case they reach out to support and support tells them what to do AFTER we analysed the reports 

For the time being this will stay this way for 10.13.4. any change will come with future releases.

Time is key here..... THX

2023-12-13 08:41 UTC, pako81 commented
We need to document the new config.php option `indicators-of-compromise-scanner.confirmation` and we would also need changelog for this for the Release Notes.

2023-12-13 08:57 UTC, mmattel commented
> We need to document the new config.php option `indicators-of-compromise-scanner.confirmation`:

I guess that this is true/false. Defaults to false. With true making the message go away.

We should add this config.php change to this PR!

2023-12-13 09:12 UTC, phil-davis commented
> I guess that this is true/false. Defaults to false. With true making the message go away.

According to the code:
```
$ioc_exec_confirmation = \OC::$server->getConfig()->getSystemValue('indicators-of-compromise-scanner.confirmation', false);
if ($license !== null && $ioc_exec_confirmation !== 'EXECUTED_ON_ALL_NODES') {
```

To suppress the message, the config item has to be set to exactly the literal string "EXECUTED_ON_ALL_NODES".
Any other value (`false`, `true`, some other string, some number...) will not suppress it.

2023-12-13 10:49 UTC, DeepDiver1975 approved these changes

2023-12-13 11:00 UTC, merged